### PR TITLE
LPS-142109 Use - instead of _ in the language labels

### PR DESCRIPTION
**Pull request by victorg1991**
In the UI we show the language code with a `-` instead of a `_`. (e. g. en-US instead of en_US) This PR fixes that behaviour in the input localized

How to try this:

- go to web content
- create a new structure
- open the language selector

Before the PR
The label of the language is displayed with a `_`
Screenshot 2021-11-15 at 10 24 26

After the PR
The label of the language is displayed with a `-`
Screenshot 2021-11-15 at 10 24 03

### CODE REVIEW

**Comment by kresimir-coko** [comment]
This seems simple and straightforward enough 👍 

I remember seeing a discussion on the topic of consistency between `_` and `-` a week or two ago, is this PR a response to that, or the cause for the discussion?

One thing I'm wondering is if this should be a global change or not, in other words, should the change be directly on the language-keys files, so that we don't have to manipulate the string itself?

**Comment by victorg1991** [comment]
> I remember seeing a discussion on the topic of consistency between _ and - a week or two ago, is this PR a response to that, or the cause for the discussion?

I don't recall any discussion, do you know where it was? (slack, pr?) I just check the bugs board :p 

> One thing I'm wondering is if this should be a global change or not, in other words, should the change be directly on the language-keys files, so that we don't have to manipulate the string itself?

I'm afraid for these cases we are not even using language keys :(

**Comment by kresimir-coko** [comment]
> I don't recall any discussion, do you know where it was? (slack, pr?) I just check the bugs board :p

I can't find it, must have been a few unrelated things that my brain combined into something I thought to be related.

🤷 Looks good!

**Review by kresimir-coko — APPROVED** [review]

**Comment by carloslancha** [comment]
We have the same transformation in `updateTrigger` method so, even if would make sense to receive this language name in a different param that the id... doesn't worth the time for now IMHO. So let's live to see another day. Forwarding!

**Comment by carloslancha** [comment]
ci:forward

**Pull request closed without merging**
