### PR TITLE
LPS-168272 HR_334 SR doesn't read the checkbox with an accessible label

### PR DESCRIPTION
**Pull request by veroglez**
Just a few suggested changes here https://github.com/brianchandotcom/liferay-portal/pull/130594
- Make the language key (clear-selection-currently-x-of-x-x-selected) a sentence.
- Replace the output of the taglib `itemsType` by `localizedItemsType`

cc @carloslancha @marcoscv-work

### CODE REVIEW

**Comment by carloslancha** [comment]
I don't understand why do wee need `localizedItemsType`. And makes no sense to me to have that as an API name for the management toolbar js component. We have a similar pattern in other Tags like `title` in `AlertTag`. I mean, from the API POV there's no need to specify that the itemsType is localized, it's just a string, the name of the itemsType.

Could we check with Brian why do we need this? Thx and sorry for the delay!

**Comment by veroglez** [comment]
Hi @carloslancha! Brian has already [requested this change in this comment](https://github.com/brianchandotcom/liferay-portal/pull/130594#issuecomment-1438766276). What do you think if we pass this pull request and then we think about changing this name if it doesn't convince us? It's a Bank of America issue and we're trying to fix it as soon as possible 😅 .

**Comment by carloslancha** [comment]
I honestly don't like to add API we're not sure about, and being realistic based on the experience we won't fix it later.

I won't care that much if we were talking about internal variables but this is a public API of such and important js component like MT.

I'd like to understand the rationale if we go with this change (I don't get the comment about input/output) 🙏

**Comment by carloslancha** [comment]
ci:forward

**Comment by dsanz** [comment]
ci:forward

**Comment by carloslancha** [comment]
hey @veroglez it looks like semver is failing, feel free to forward it after updating the pr with the fix. Thx!!

**Comment by veroglez** [comment]
ci:forward

**Pull request closed without merging**
