### PR TITLE
LPS-169099 Replace drpodown link triggers with buttons

### PR DESCRIPTION
**Pull request by carloslancha**
- LPS-169099 Add support in Dropdown Provider for button triggers and warn about using non button triggers
- LPS-169099 Update dropdown trigger links to buttons and add aria-haspopup

### CODE REVIEW

**Review by bryceosterhaus — APPROVED** [review]
Looks good! 

Only question I have is in regards to the keyDown event. By changing these from ENTER and SPACE, do those no longer work?

**Comment by carloslancha** [comment]
@bryceosterhaus it works natively, no need to add custom handlers for it :)

**Comment by carloslancha** [comment]
ci:forward

**Comment by carloslancha** [comment]
ci:test:relevant

**Comment by carloslancha** [comment]
@manoelcyreno could you please take a look to see if failing tests are related? Thx!!

**Comment by mateusralv** [comment]
I'm taking a look 🕵🏽

**Comment by dsanz** [comment]
ci:test:relevant

**Comment by carloslancha** [comment]
@mateusralv we're waiting to fix following tests, right? Thx!

Test cases related:
Masterclass#AddMasterclassSite
MBPage#CanViewPagersForCategoriesAndThreads
WikiAdmin#CanComparePageVersions

**Comment by mateusralv** [comment]
Hi @carloslancha This fix should solve the failures, I will run the relevant again to confirm.

**Comment by mateusralv** [comment]
ci:test:relevant

**Comment by mateusralv** [comment]
Hi @carloslancha The failures are not related! 

[Testray comparison](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1678389119584&testrayRunIdA=2225028894&testrayRunIdB=2226424871)

**Comment by bryceosterhaus** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/131486

**Pull request closed without merging**
