### PR TITLE
[TS] LPS-127273

### PR DESCRIPTION
**Pull request by dacousalr**
Hi team,

This PR tries to solve LPS-127273 by adding a flag to enable or disable the inner focus management of Treeview component which interferes when selecting a new node after the component has lost its focus or it has been deactivated.

More details can be found in PTR-2425.

Please, let me know if further clarifications are needed. 

Thanks in advance

\cc @noornajj @victorg1991

### CODE REVIEW

**Comment by dacousalr** [comment]
ci:test:sf

**Comment by dacousalr** [comment]
ci:test:relevant

**Comment by markocikos** [comment]
@dacousalr I believe https://github.com/liferay-frontend/liferay-portal/pull/1063 will fix this issue.

**Comment by dacousalr** [comment]
Thanks @markocikos

I also believe so.

**Pull request closed without merging**
