### PR TITLE
LPS-158634 - Update alloy-ui to 3.1.0-deprecated.98

### PR DESCRIPTION
**Pull request by georgel-pop-lr**
Fixes: https://github.com/liferay/liferay-frontend-projects/pull/975

### CODE REVIEW

**Comment by georgel-pop-lr** [comment]
ci:test:relevant

**Comment by susanchen3** [comment]
Taking a look! :detective:

**Comment by susanchen3** [comment]
Reviewed, test failures unrelated :heavy_check_mark: Looks good to manually forward from QA perspective 

[**Comparison run:** ](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=2&testrayRunIdB=1912333033&testrayRunIdA=1912382185&statusB=3)
- Mainly Forms `Failed prior to running test`: ran some locally and they pass

**Comment by georgel-pop-lr** [comment]
Manually forwarded https://github.com/brianchandotcom/liferay-portal/pull/120686

**Pull request closed without merging**
