### PR TITLE
LPS-149497 Expose ERC in Comments and create endpoints by ERC in Comments of Documents

### PR DESCRIPTION
**Pull request by ccorreagg**
Related ticket: [LPS-149497](https://issues.liferay.com/browse/LPS-149497)

This PR contains the code for the Headless Delivery API to:

- Expose the external reference code in Comments
- Create new endpoints to delete, get and upsert Comments by external reference code (associated to Documents, accesing by external reference code)

**NOTE:** The creation of the endpoints of Comments associated to another Comment, BlogPosting or StructuredContent will be included in a future PR.

---

The external reference code field has been exposed by modifying the rest-openapi.yaml file:

```
Comment:
    description:
        Represents a comment. See [Comment](https://www.schema.org/Comment) for more details.
    properties:
        [...]
        externalReferenceCode:
            # @review
            description:
                The comment's external reference code.
            type: string
        [...]
```
Also the new endpoints:

```
"/sites/{siteId}/documents/by-external-reference-code/{documentExternalReferenceCode}/comments/by-external-reference-code/{externalReferenceCode}":
    delete:
        [...]
    get:
        [...]
    put:
        [...]
```

The ERC field may be tested by invoking, for example, the /headless-delivery/v1.0/sites/{siteId}/structured-contents endpoint; see the following example, given a documentId 43003:

```
curl \
	-H "accept: application/json" \
	-H "Content-Type: application/json" \
	-X 'POST' "http://localhost:8080/o/headless-delivery/v1.0/documents/43003/comments" \
	-u "test@liferay.com:test" \
	-d '{
               "text": "my comment 1",
               "externalReferenceCode": "ERC1235"
             }
            '
```
getting the following response:

```
{
  "creator": {
    "additionalName": "",
    "contentType": "UserAccount",
    "familyName": "Test",
    "givenName": "Test",
    "id": 20127,
    "name": "Test Test"
  },
  "dateCreated": "2022-04-06T09:16:01Z",
  "dateModified": "2022-04-06T09:16:01Z",
  "externalReferenceCode": "ERC1235",
  "id": 43026,
  "numberOfComments": 0,
  "parentCommentId": 43014,
  "text": "<p>my comment 1</p>"
}

```
It could be test the new get endpoint with the following command:

```
curl \
	-H "accept: application/json" \
        -X 'GET' 'http://localhost:8080/o/headless-delivery/v1.0/sites/20123/documents/by-external-reference-code/43003/comments/by-external-reference-code/ERC1235' \
	-u "test@liferay.com:test"
```

### CODE REVIEW

**Review by javierdearcos — APPROVED** [review]
Good job! 🎉 

Many things to be aware of and change in this PR and you make it great.

Next time maybe it is interesting to send several PRs with the things in the backend and the things in the API to avoid big PRs

**Comment by javierdearcos** [comment]
This test seem related:
[com.liferay.message.boards.comment.internal.MBCommentManagerImplTest.testAddCommentWithUserNameAndSubject](https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0/404254//testReport/com.liferay.message.boards.comment.internal/MBCommentManagerImplTest/testAddCommentWithUserNameAndSubject)

and I don't know about the SQL constraint violation but I would take a look in case it is the new externalReferenceCode field.

I'm not forwarding the PR so you can consider review this things before trying the CI again

**Comment by ccorreagg** [comment]
> This test seem related: [com.liferay.message.boards.comment.internal.MBCommentManagerImplTest.testAddCommentWithUserNameAndSubject](https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0/404254//testReport/com.liferay.message.boards.comment.internal/MBCommentManagerImplTest/testAddCommentWithUserNameAndSubject)
> 
> and I don't know about the SQL constraint violation but I would take a look in case it is the new externalReferenceCode field.
> 
> I'm not forwarding the PR so you can consider review this things before trying the CI again

I have resolved the first one and reviewing the second one, it is weird as I have not included any new field in the database in this PR

**Comment by ccorreagg** [comment]
The service and the API will be splitted in two PRs

**Pull request closed without merging**
