### PR TITLE
LPS-139343 Use Service instead of LocalService from the Portal Instance APIs

### PR DESCRIPTION
**Pull request by javierdearcos**
Replace the use of LocalService to Service to check permissions from the Portal Instance APIs. Just resending from here after rebase

Original PR from @SamZiemer at https://github.com/liferay-headless/liferay-portal/pull/712:

https://issues.liferay.com/browse/LPS-139343

This pull changes PortalInstanceResourceImpl to no longer use CompanyLocalService and instead use CompanyService for permission checking.

### CODE REVIEW

**Comment by javierdearcos** [comment]
ci:forward

**Comment by javierdearcos** [comment]
ci:test:relevant

**Comment by SamZiemer** [comment]
Hi @javierdearcos These test failures do not look related to these changes, do you Agree? If so, @Kyle-miho would you say this can be manually forwarded?

**Comment by javierdearcos** [comment]
Yes, @SamZiemer. 

Definitely the test failures are not related. 

I preferred to pass through the CI but if you have el OK to forward it manually, great

**Comment by javierdearcos** [comment]
Sent directly here: https://github.com/brianchandotcom/liferay-portal/pull/111198

**Pull request closed without merging**
