### PR TITLE
LPS-164616 | Add Autom. test FDSCustomView#CanBeSaved

### PR DESCRIPTION
**Pull request by mateusralv**
Manually forwarding 😃 

Orginal PR: https://github.com/mateusralv/liferay-portal/pull/14

---

**Test Plan**
Given Custom view enabled for a dataset display instance
When Make some changes to dataset display
And When Save As the custom view
Then A new custom view is created and selected as current view

JIRA Ticket:
https://issues.liferay.com/browse/LPS-164616

### CODE REVIEW

**Comment by mateusralv** [comment]
ci:test:sf

**Comment by eltonccdantas** [comment]
ci:test:sf

**Comment by john-co** [comment]
```
     [java] java.lang.Exception: Found formatting issues:
     [java] At least one commit message is missing a reference to a required JIRA project: BLADE, CLDSVCS, COMMERCE, FACES, IDE, LCD, LHC, LOOP, LPS, LRAC, LRCI, LRDOCS, LRIS, LRQA, OAUTH2, POSHI, RELEASE, SYNC, TR. Please verify that the JIRA project keys are specifiedin ci.properties in the liferay-portal repository
```

You'll want to update one of your commits to start with LPS-***

**Comment by mateusralv** [comment]
ci:test:sf

**Comment by mateusralv** [comment]
ci:forward

**Pull request closed without merging**
