### PR TITLE
LPS-132553, LPS-132551 | Refactor Theme and UIInfrastructureUsecase tests

### PR DESCRIPTION
**Pull request by zhangyan0701**
**Description**
Use JSON for basic setup steps in Theme and UIInfrastructureUsecase tests.

**Jira Ticket**
https://issues.liferay.com/browse/LPS-132553
https://issues.liferay.com/browse/LPS-132551

### CODE REVIEW

**Review by john-co — APPROVED** [review]
Looks good! I just modified a couple test case names toward sacred model. Please update PR title and comment to follow FI team PR guidelines, then go ahead and forward.

**Comment by john-co** [comment]
ci:test:frontend:nocompile

**Comment by zhangyan0701** [comment]
ci:test:frontend

**Comment by zhangyan0701** [comment]
ci:test:frontend

**Comment by zhangyan0701** [comment]
ci:forward

**Comment by john-co** [comment]
ci:test:sf

**Comment by john-co** [comment]
ci:forward

**Comment by zhangyan0701** [comment]
@john-co 

Thanks for fixing the SF failure!

**Comment by john-co** [comment]
> Thanks for fixing the SF failure!

No prob! :smile:  it was actually my commits that introduced the SF... :shushing_face:

**Pull request closed without merging**
