### PR TITLE
LPS-126057 Remove default sticker icon value from VerticalCardTag and set showSticker to false as default

### PR DESCRIPTION
**Pull request by carloslancha**
https://issues.liferay.com/browse/LPS-126057

- Removes the default sticker icon value from `VerticalCardTag` and adds it to `FileCardTag` instead.
- Set `isStickerShown` default value to `null` (in `VerticalCard` interface) and to `false` in `VerticalCardTag`.
- Set `isStickerShown` as true in case `stickerImageSrc` or `stickerIcon` are not `null`.

Before
image

After
image

Testing plan

Use case with no sticker:
- Go to Stylebooks
- Create a new one
- Change the view type to card view
- No sticker should appear since no `isStickerShown` is implemented in the model nor `stickerIcon` or `stickerImageSrc` are set.

Use case with sticker
- Go to Content & Data / Web Content
- Create a new Basic Web Content
- Change the view type to card view
- A sticker should appear since `stickerIcon` and `stickerImageSrc` are implemented in the model.

### CODE REVIEW

**Comment by jbalsas** [comment]
Doing `git grep isStickerShown` I get these relevant hits outside of `frontend-taglib-clay`.

```bash
modules/apps/depot/depot-web/src/main/java/com/liferay/depot/web/internal/servlet/taglib/clay/DepotEntryVerticalCard.java:      public Boolean isStickerShown() {
modules/apps/layout/layout-admin-web/src/main/java/com/liferay/layout/admin/web/internal/servlet/taglib/clay/DefaultStylebookLayoutVerticalCard.java:   public Boolean isStickerShown() {
modules/apps/layout/layout-admin-web/src/main/java/com/liferay/layout/admin/web/internal/servlet/taglib/clay/SelectStylebookLayoutVerticalCard.java:    public Boolean isStickerShown() {
```

Should we remove them and also verify they don't regress to showing stickers? They shouldn't need that override anymore.

**Comment by carloslancha** [comment]
> Should we remove them and also verify they don't regress to showing stickers? They shouldn't need that override anymore.

gotcha!

**Comment by jbalsas** [comment]
Also, not sure if we wanted to also change `ImageCard` or not. I guess probably not, but just double-checking!

**Comment by markocikos** [comment]
> Also, not sure if we wanted to also change `ImageCard` or not. I guess probably not, but just double-checking!

I understood that we wanted to change only `VerticalCard`, leave defaults on for `ImageCard` and `FileCard`.

**Comment by carloslancha** [comment]
> Also, not sure if we wanted to also change ImageCard or not. I guess probably not, but just double-checking!

`ImageCardTag` has already defined its defaults, I just moved the defaults from `VerticalCardTag` to `FileCardTag`. Is that what you mean?

**Comment by jbalsas** [comment]
> ImageCardTag has already defined its defaults, I just moved the defaults from VerticalCardTag to FileCardTag. Is that what you mean?

Yup, just making sure! 👍

**Comment by carloslancha** [comment]
ci:stop

**Comment by carloslancha** [comment]
ci:test:sf

**Comment by carloslancha** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
ci:forward

**Pull request closed without merging**
