### PR TITLE
LPS-194387 LPS-200809 Migrate FDS Show View Options Select to Clay Picker

### PR DESCRIPTION
**Pull request by thektan**
**Story:** https://liferay.atlassian.net/browse/LPS-194387
**Subtask:** https://liferay.atlassian.net/browse/LPS-200809

## Details

This migrates the use of `ClayDropDown` to `Picker` for the "Show View Options" button.

<p>Screenshot 2023-11-08 at 12 02 33 PM</p>

**Things to note:**
- To pass the active view's symbol to the custom trigger `ActiveViewSelectorTrigger`, I added a custom prop to `Picker` named `symbol`.
- `ActiveViewSelector` was always trying to persist the value and throwing an error with an invalid URL, so I added an extra check for to skip it if `appURL` wasn't defined.

## Demo

I didn't find any FDS with multiple view options being currently used in Portal so below is an example of adding a list view in the Data Set Manager. (Code I added for this demo: https://github.com/thektan/liferay-portal/commit/f3b55b37919ed9f9a465fcc0e83466de617406ba)

### Before

https://github.com/liferay-frontend/liferay-portal/assets/4496722/d5c0e857-74e8-4542-a078-251dbf216444

### After

The tooltip always appears after selecting an option, which feels a bit annoying to me, but I'm not sure if anything can be done since the focus goes back to the trigger.

https://github.com/liferay-frontend/liferay-portal/assets/4496722/a982249b-1f09-401e-a0e1-bfbf5fd2df00

### CODE REVIEW

**Comment by thektan** [comment]
ci:test:sf

**Review by markocikos — APPROVED** [review]
@thektan LGTM! :sparkles: 

The tooltip behavior, if it's a bug, it's a bug in the Clay component. There is a similarly glitchy bahavior in Web Content and Documents and Media. We can deal with it in a separate task, if we even wish to do so.

**Comment by JerryAdrianoo** [comment]
Hey @thektan testfix aren't needed to these changes, since we don't have tests with this new button or something like this.
These failures are not related to your changes!
[Comparison](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1699651918748&testrayRunIdA=2455807858&testrayRunIdB=2455346522)

**Comment by thektan** [comment]
@JerryAdrianoo I believe [LocalFile.FrontendDataSetFilters#WillRenderAsInitialState](https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/262044//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_FrontendDataSetFilters_WillRenderAsInitialState_) seems to be related since this changes the markup of the view button.

**Comment by JerryAdrianoo** [comment]
No worries @thektan, I tested locally, and this test is working fine. So if in the future needs some change, I can do it 😄

**Comment by thektan** [comment]
ci:forward:force

**Comment by thektan** [comment]
ci:forward:force

**Pull request closed without merging**
