### PR TITLE
LPS-122765 Fix semantic versioning issue with frontend token definition api

### PR DESCRIPTION
**Pull request by john-co**
This updates the package info to the recommended version to fix failing semantic versioning test described in https://issues.liferay.com/browse/LPS-122765

### CODE REVIEW

**Comment by john-co** [comment]
ci:test:sf

**Comment by john-co** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
Hey @john-co, I'm not sure this makes sense... @izaera changed this recently https://github.com/liferay/liferay-portal/commit/27c80f18e6ff58f2d7d50a82238aadef43998128#diff-20a00663edca54e96364a5e6407aee9228677ebb12f983f36b746e5a66087753 because there were changes in the package...

@izaera, can you figure out what happened here?

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
Okay, I see now that this is setting to `1.0.0` and in https://github.com/liferay-frontend/liferay-portal/pull/458 we'll need `1.1.0`,  so maybe we can just get that done there.

**Comment by jbalsas** [comment]
Asked @victorg1991 to do it in https://github.com/liferay-frontend/liferay-portal/pull/458. Closing here so we don't have conflicting PRs in flight.

**Pull request closed without merging**
