### PR TITLE
LPS-119068 [Page Audit] Create empty Page Audit sidebar view

### PR DESCRIPTION
**Pull request by dgarciasarai**
**Description**

Show empty/default Page Audit view in the sidebar when the user is not connected yet with PageSpeed functionality.

**How to test it**

- Add config file in `~/bundles/osgi/configs` to display the Page Audit icon in the Control Menu (you can find it in the ticket: https://issues.liferay.com/browse/LPS-119068)
- Create a Page
- Open the Page Audit sidebar panel

Screenshot 2021-03-15 at 11 04 46

**Within this pull request**

- Inject react data to frontend via React props
- Create the empty view
- Frontend unit tests

**Commits**

- LPS-119068 Inject data to frontend 10b18c24
- LPS-119068 Create react app and empty page audit view cd376f6
- LPS-119068 BuildLang b4c1f87
- LPS-119068 Add frontend tests 9d0ce24

**Screenshots**

Screenshot 2021-03-15 at 11 03 23 Screenshot 2021-03-15 at 10 58 15

### CODE REVIEW

**Comment by wincent** [comment]
Needs a rebase due to merge conflicts, which will make it easier to review as a bonus.

I took a quick look at the commits that you authored, and everything looks fine, except for this bit:

```jsx
return (
	<>
		<BasicInformation
			canonicalURLs={canonicalURLs}
			defaultLanguageId={defaultLanguageId}
		/>

		{validConnection ? (
			<></>
		) : (
			<EmptyLayoutReports
				assetsPath={assetsPath}
				showButton={showButton}
			/>
		)}
	</>
);
```

I don't think I'd ever render an empty React fragment (`<></>`); the only reason to use one ever is to group other elements together. Just [render `false`, `undefined` or `null` instead](https://reactjs.org/docs/jsx-in-depth.html#booleans-null-and-undefined-are-ignored):

```jsx
return (
	<>
		<BasicInformation
			canonicalURLs={canonicalURLs}
			defaultLanguageId={defaultLanguageId}
		/>

		{validConnection || (
			<EmptyLayoutReports
				assetsPath={assetsPath}
				showButton={showButton}
			/>
		)}
	</>
);
```

**Comment by dgarciasarai** [comment]
Hey @wincent, I rebased the pull request with master (normal, not Brian's, now it's all synced), solve the conflict and apply your feedback in https://github.com/liferay-frontend/liferay-portal/pull/903/commits/ebc8f4b5dead42d0ea4199f71251b1b607bac784 (`validConnection` || `()`). Let me know if you see something else. If not, forward it directly :) Thanks!

**Comment by dgarciasarai** [comment]
ci:test:sf

**Comment by dgarciasarai** [comment]
ci:test:relevant

**Comment by wincent** [comment]
> Let me know if you see something else.

see-nothing

**Comment by dgarciasarai** [comment]
Let's wait until the CI is green to forward it. Thanks @wincent!

**Comment by dgarciasarai** [comment]
ci:forward

**Pull request closed without merging**
