### PR TITLE
[LPS-160598] Add delete comment after delete answer 

### PR DESCRIPTION
**Pull request by thienquach87**
Dear Team,
Forwarded from [liferay-ts-reviewer#91](https://github.com/liferay-ts-reviewer/liferay-portal/pull/91)
This is the PR for fixing this ticket: https://issues.liferay.com/browse/LPS-160598. The original [PR](https://github.com/thienquach87/liferay-portal/pull/11) was passed my review.
The fix is based on the logic applied in 7.3.x.  This logic is still applied for now (https://github.com/liferay/liferay-portal-ee/blob/7.3.x/modules/apps/questions/questions-web/src/main/resources/META-INF/resources/js/components/Answer.es.js#L50-L64). 

cc: @sontruongces, @holatuwol

Regards,
Thien

### CODE REVIEW

**Comment by thienquach87** [comment]
@sontruongces could you help to check format source?

**Comment by sontruongces** [comment]
> @sontruongces could you help to check the format source?

@thienquach87 I updated the code with the format source. Thanks!

**Comment by thienquach87** [comment]
ci:test:sf

**Comment by thienquach87** [comment]
ci:test:relevant

**Comment by thienquach87** [comment]
ci:test:sf

**Comment by thienquach87** [comment]
> > @sontruongces could you help to check the format source?
> 
> @thienquach87 I updated the code with the format source. Thanks!

thank @sontruongces 
It looks good now

**Comment by bryceosterhaus** [comment]
ci:forward

**Pull request closed without merging**
