### PR TITLE
LPD-8425 - Remove unused @Reference variables

### PR DESCRIPTION
**Pull request by bryceosterhaus**

### CODE REVIEW

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Review by markocikos — APPROVED** [review]
@bryceosterhaus LGTM! :sparkles:

**Comment by bryceosterhaus** [comment]
ci:report:2543802763

**Comment by bryceosterhaus** [comment]
ci:forward:force

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
ci:stop

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
ci:report:2545354924

**Comment by bryceosterhaus** [comment]
ci:forward:force

**Comment by bryceosterhaus** [comment]
ci:forward:force

**Pull request closed without merging**
