### PR TITLE
LPS-187283 Avoid creating Filters in DataSet with invalid Date Range

### PR DESCRIPTION
**Pull request by antonio-ortega**
Hey,

First commit is enough to fix the case specified in the reproduction steps in [LPS-187283](https://issues.liferay.com/browse/LPS-187283)

I introduced second commit because when validating date range we are not considering the case when the user doesn't modify one or both input dates which is causing wrong validation. For example, if you just modify "From" input to set something in the future, it would return it's a valid date range when it is not.

### CODE REVIEW

**Comment by antonio-ortega** [comment]
ci:test:sf

**Comment by deborasoliveira** [comment]
I'll take a look at the relevant result.

**Comment by deborasoliveira** [comment]
The failures are unrelated to this PR.
[Comparison run](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=2&testrayRunIdB=2349417252&testrayRunIdA=2349259427&statusB=3)

**Review by bryceosterhaus — APPROVED** [review]
LGTM!

**Comment by antonio-ortega** [comment]
ci:forward:force

**Comment by markocikos** [comment]
ci:forward

**Comment by antonio-ortega** [comment]
ci:forward:force

**Pull request closed without merging**
