### PR TITLE
LPS-164321

### PR DESCRIPTION
**Pull request by holatuwol**
Sending based on the conversation in this slack thread:
https://liferay.slack.com/archives/CNBG06JS3/p1699435276057189

There was a typo where it was `aria-orentation` instead of `aria-orientation`.

## Steps to reproduce

1. Navigate to Control Panel > Password Policies
2. Edit the default password policy
3. Run a check for the incorrect attribute in the Developer Tools console:
```
document.querySelectorAll('.panel-group[aria-orentation]')
```
4. Run a check for the correct attribute in the Developer Tools console:
```
document.querySelectorAll('.panel-group[aria-orientation]')
```

### CODE REVIEW

**Comment by holatuwol** [comment]
ci:test:bundle

**Review by markocikos — APPROVED** [review]
@holatuwol LGTM! :sparkles:

**Comment by markocikos** [comment]
@holatuwol If you're ok with the changes in PR, feel free to `ci : forward` it. In FI we changed workflow a bit, reviewers don't typically forward.

**Comment by holatuwol** [comment]
Thanks, we'll go ahead and proceed on the other pull request!

**Pull request closed without merging**
