### PR TITLE
LPD-27195 - Fix filepaths for SF and also check tsc in playwright for SF

### PR DESCRIPTION
**Pull request by bryceosterhaus**

### CODE REVIEW

**Comment by bryceosterhaus** [comment]
ci:test:sf

**Comment by bryceosterhaus** [comment]
ci:test:sf

**Comment by bryceosterhaus** [comment]
ci:stop

**Comment by bryceosterhaus** [comment]
ci:test:sf

**Comment by bryceosterhaus** [comment]
ci:test:sf

**Comment by bryceosterhaus** [comment]
ci:test:sf

**Comment by bryceosterhaus** [comment]
ci:test:sf

**Comment by bryceosterhaus** [comment]
ci:forward:force

**Comment by izaera** [comment]
Forcing again as per https://github.com/liferay-frontend/liferay-portal/pull/4308#issuecomment-2221500966

**Comment by izaera** [comment]
ci:forward:force

**Pull request closed without merging**
