### PR TITLE
[TS] LPS-128028 Preventing curParam from being removed in the URL, so it can ensure independent pagination between Search Container 

### PR DESCRIPTION
**Pull request by orsolyaDekany**
Hello,

This PR is a continuation of PR: https://github.com/liferay-frontend/liferay-portal/pull/812

<hr>

Search containers do not ensure independent pagination currently, however different curParam variables are included in the search containers liferay-ui:search-container taglib for example here .

Root cause analysis: curParam, that ensures independent pagination, is not included in the iteratorURL when multiple search container pagination is being used on a site. Therefore, the cur value will be reset and set to the default value.
The curParam is set to null here that prevents the parameter being included in the URL.

Fix: curParam will be included in the URL by removing the code from search_paginator.

Please see more information on PTR: https://issues.liferay.com/browse/PTR-2221

LPS: https://issues.liferay.com/browse/LPS-128028

Cc. @antonio-ortega

### CODE REVIEW

**Comment by wincent** [comment]
Added @antonio-ortega and @jbalsas as reviewers because they seem to have a good understanding based on the discussion in [the previous version of the PR](https://github.com/liferay-frontend/liferay-portal/pull/812).

**Comment by orsolyaDekany** [comment]
ci:test

**Comment by antonio-ortega** [comment]
Looks good to me. Let's wait for the result of the full test suite since that brought to light Asset Publisher's error last time, and if everything is ok we can move it forward.

**Comment by jbalsas** [comment]
> Looks good to me. Let's wait for the result of the full test suite since that brought to light Asset Publisher's error last time, and if everything is ok we can move it forward.

To be honest, it's still hard for me to wrap my head around this particular fix... but if CI is green, I'd say we proceed with this.

@orsolyaDekany, second commit reads as "Partial Backport..." but is it? Looks more like a Frontport coming from a `7.0.x` specific fix. Not that it makes a lot of a difference, but it's weird to see a partial backport commit making it into `master`. @antonio-ortega, not sure this has ever happened before :D

**Comment by orsolyaDekany** [comment]
Hi @jbalsas , I think its my first PR to master and it looks really weird indeed..  Now I don't want to touch the commit - until you say so - just to be sure not breaking the ci test.

**Comment by jbalsas** [comment]
Hey @john-co, @calvinctvo, could you please review the test results here and make sure no failures are related to pagination issues like the ones we detected in https://github.com/liferay-frontend/liferay-portal/pull/812?

Thanks!

**Comment by john-co** [comment]
Just started reviewing :)

**Comment by john-co** [comment]
Reviewed. Test failures are unrelated. :heavy_check_mark: 

- archived-module-smoke-jdk8/0 test is failing from known issue: https://issues.liferay.com/browse/COMMERCE-5730
- other lpkg and modules integration look unrelated.

[Testray Comparison](
https://testray.liferay.com/home/-/testray/runs/compare?formDate=1614295705917&testrayRunIdA=1489033115&testrayRunIdB=1489136645) shows no other unique failures

**Comment by jbalsas** [comment]
Hey @orsolyaDekany, based on @john-co's assessment I think this is good to go. I'm still worried about possible regressions but we will need to forward this and see...

Could you please just amend the title on that last commit? I'd suggest you simply drop the "Partial Backport part" and explain what it does. Then, in the extra lines of the commit mention that this comes from a different LPS and a fix as you did so we can go and track it down.

Please, let me know when it's done so we can directly forward this, no need for additional testing.

**Comment by orsolyaDekany** [comment]
Hi @jbalsas , modifying the commit message is done.

**Comment by jbalsas** [comment]
Forwarded manually to Brian at https://github.com/brianchandotcom/liferay-portal/pull/99283

Thanks!

**Pull request closed without merging**
