### PR TITLE
LPS-136018 Upgrade liferay-ui:input-search markup

### PR DESCRIPTION
**Pull request by edalgrin**
This PR fixes the `<liferay-frontend:management-bar>` style and upgrades the `<liferay-ui:input-search>` markup to the Clay one.

---

**How to test the changes:**

- Open the appllications-menu
- Click on the Control Panel tab
- Click on Account Group under USERS category

### CODE REVIEW

**Comment by edalgrin** [comment]
I couldn't find out why the filter dropdown "All" isn't working but I think we can work on that with a different LPS

**Review by pat270 — CHANGES_REQUESTED** [review]
Are we planning to update these to use the new management bar (V3)? How "correct" should it be? If we are doing a quick visual fix until we can convert, I think this is good with me. For the dropdown not working, we need to change `[data-toggle="dropdown"]` to `[data-toggle="liferay-dropdown"]`. It should be a quick change, should bundle it with this pr.

Edit: I forgot to mention, do we care about people upgrading from an older version that might have used our v1 management bar? Should it work for someone upgrading?

**Comment by edalgrin** [comment]
My portal is giving me some issue, I couldn't test the change, can anyone?
image

**Comment by pat270** [comment]
ci:test:sf

**Comment by pat270** [comment]
ci:test:relevant

**Comment by pat270** [comment]
Going to forward since it deals with the issue.

**Comment by pat270** [comment]
ci:forward

**Pull request closed without merging**
