### PR TITLE
[TS] LPS-143560 Change the expiration session message to the actual behavior

### PR DESCRIPTION
**Pull request by orsolyaDekany**
Hi @liferay-frontend ,

LPS: https://issues.liferay.com/browse/LPS-143560
Previous PR: https://github.com/liferay-echo/liferay-portal/pull/6637
The reason I did not simply changed the value on Crowdin, because the whole meaning of the sentence is changed in this case (not a character or wrong translation only) and I suppose it would be nice to be reviewed first. Let me know if I am wrong.

Currently, the expiration alert message says: "Due to inactivity, your session has expired. **Please save any data you may have entered before refreshing the page.**"

The problem with this message is that when you try to save the data in the expired session, it actually does not allow to save the data, but instantly redirecting to the homepage and there is no chance for saving. "**You will be redirected to the home page where you can sign in again.**" would be a more meaningful message that matches with the actual behavior.

Could you review it?
Thank you.

### CODE REVIEW

**Comment by orsolyaDekany** [comment]
ci:test:sf

**Comment by orsolyaDekany** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
Hey @orsolyaDekany I believe that the message intention is to let the user that know they should "try" to save the content before refreshing or doing anything else. Without session you cannot save anything to the server, so saving in this case doesn't mean in the server, but rather in the user computer, like copying and pasting or something else. 

I think in this case we should warn the user one way or another that the unsaved data will be lost, so removing that part I think it may not be the best choice IMO. Maybe clarifying that the data should be saved locally? Let's see what @dsanz and @georgel-pop-lr think about it :)

**Comment by georgel-pop-lr** [comment]
> Hey @orsolyaDekany I believe that the message intention is to let the user that know they should "try" to save the content before refreshing or doing anything else. Without session you cannot save anything to the server, so saving in this case doesn't mean in the server, but rather in the user computer, like copying and pasting or something else.
> 
> I think in this case we should warn the user one way or another that the unsaved data will be lost, so removing that part I think it may not be the best choice IMO. Maybe clarifying that the data should be saved locally? Let's see what @dsanz and @georgel-pop-lr think about it :)

Makes sense what Victor is saying, maybe we should provide a more meaningful message, that once redirected anything unsaved will be lost, so please make sure to save or export your work locally ... 

Not sure if it makes sense to you @orsolyaDekany?

Regards.

**Comment by orsolyaDekany** [comment]
Hi @victorg1991 @georgel-pop-lr ,
I completely agree with you, makes sense.
Hope that its not too long and more meaningful. "Due to inactivity, your session has expired. **Before you continue, locally save any data you may have entered. You will be redirected from the page and need to login again.**"
What do you think?
Thanks!

**Comment by georgel-pop-lr** [comment]
> Hi @victorg1991 @georgel-pop-lr , I completely agree with you, makes sense. Hope that its not too long and more meaningful. "Due to inactivity, your session has expired. **Before you continue, locally save any data you may have entered. You will be redirected from the page and need to login again.**" What do you think? Thanks!

I'm not an English expert, but maybe even better:
"You will be redirected to the login page. Before you continue, if you wish, please save locally any data you entered, or it will be lost."

**Comment by orsolyaDekany** [comment]
ci:test:sf

**Comment by orsolyaDekany** [comment]
ci:test:relevant

**Comment by orsolyaDekany** [comment]
Sounds good to me! I pushed the branch with the changes @georgel-pop-lr @victorg1991 .
Thanks.

**Comment by victorg1991** [comment]
@orsolyaDekany, Thinking about this again and I have the feeling that the message is still a bit misleading, we are saying "you will be redirected to the login page" but this won't happen automatically, right? 🤔  And also it is also a very long message. What about something like "Due to inactivity, your session has expired. Please save **locally** any data you may have entered before refreshing the page."

**Comment by orsolyaDekany** [comment]
@victorg1991, If it is too long, we can leave the "redirecting" part out, but I think the "before continue" part should go first, because the user reads that first and warns you about being careful and not doing anything until..
How about: "Due to inactivity, your session has expired. Before you continue, please make sure your entered data is saved locally." 
What do you think?

**Comment by georgel-pop-lr** [comment]
> @victorg1991, If it is too long, we can leave the "redirecting" part out, but I think the "before continue" part should go first, because the user reads that first and warns you about being careful and not doing anything until.. How about: "Due to inactivity, your session has expired. **Before you continue, please make sure your entered data is saved locally.**" What do you think?

Okay, from my side! @victorg1991  you could merge.

**Comment by victorg1991** [comment]
hey @orsolyaDekany let's go with your last suggestion :) "Due to inactivity, your session has expired. Before you continue, please make sure your entered data is saved locally."

**Comment by orsolyaDekany** [comment]
I pushed the branch with the changes @victorg1991. Thanks!

**Comment by victorg1991** [comment]
Let's go with it then 😇

**Comment by victorg1991** [comment]
Thanks!!

**Comment by victorg1991** [comment]
ci:forward

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:test:relevant 🦄

**Comment by victorg1991** [comment]
ci:forward

**Pull request closed without merging**
