### PR TITLE
LPS-198883 React custom-element rendering twice with SPA enabled

### PR DESCRIPTION
**Pull request by izaera**

### CODE REVIEW

**Comment by izaera** [comment]
ci:test:relevant

**Comment by izaera** [comment]
ci:forward

**Comment by izaera** [comment]
ci:test:relevant

**Comment by izaera** [comment]
ci:forward

**Review by bryceosterhaus — APPROVED** [review]
LGTM!

**Comment by izaera** [comment]
ci:test:relevant

**Comment by deborasoliveira** [comment]
The failures are unrelated to the PR according to the comparison. 😃 

[Comparison run](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=2&testrayRunIdB=2447033815&testrayRunIdA=2446948333&statusB=3)

**Comment by izaera** [comment]
ci:forward:force

**Pull request closed without merging**
