### PR TITLE
LPS-142325 | A11yTool - Verifies violations can be detected after adding a fragment with a violation to a blank page.

### PR DESCRIPTION
**Pull request by susanchen3**
**Background**
Create automated tests for the A11y tool

**Test Plan**
- Navigate to a blank page 
- Verify there are no violations on page
- Add a fragment with a violation
- Assert the violation is highlighted and appears on the side panel

**JIRA Ticket:**
https://issues.liferay.com/browse/LPS-142325

### CODE REVIEW

**Comment by susanchen3** [comment]
ci:test:frontend:nocompile

**Comment by susanchen3** [comment]
ci:test:frontend:nocompile

**Comment by zhangyan0701** [comment]
Just started reviewing

**Comment by zhangyan0701** [comment]
Looks good to me!

**Review by zhangyan0701 — APPROVED** [review]

**Comment by zhangyan0701** [comment]
ci:forward

**Pull request closed without merging**
