### PR TITLE
LPS-110423 Updates alloyeditor to 2.11.11

### PR DESCRIPTION
**Pull request by diegonvs**
From: https://github.com/liferay/alloy-editor/commit/70b9faf5dfa8d2cc153ab362aa6f27e27a5ca6f1

LPS-110423

### CODE REVIEW

**Comment by diegonvs** [comment]
ci:test:sf

**Comment by diegonvs** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
Same as with the CKEditor update... seems trivial enough... let's see if we make it in (testing on the side)

**Comment by jbalsas** [comment]
ci:forward

**Comment by jbalsas** [comment]
I've closed it since I was experiencing some weird behaviours both in Blogs and Journal with AlloyEditor... will check better tomorrow.

**Pull request closed without merging**
