### PR TITLE
LPS-147836 Assert tooltip message is displayed when hovered over an action button in responsive mode

### PR DESCRIPTION
**Pull request by susanchen3**
**Background**
Create automated tests for Management Toolbar.

**Test Plan**
Given a user of the portal on responsive mode
When the user opens any section with the management toolbar
And hovers an action button
Then a tooltip message will be displayed

**JIRA Ticket:**
https://issues.liferay.com/browse/LPS-147836

### CODE REVIEW

**Comment by susanchen3** [comment]
ci:test:frontend:nocompile

**Comment by john-co** [comment]
ci:test:frontend:nocompile

**Comment by susanchen3** [comment]
ci:test:frontend:nocompile

**Comment by Esther-OC** [comment]
Looks good to me!

Maybe for a future refactor...
Will it be possible to hover any action button, not only "Download" as in this case?  I mean, for future maintenance, if the buttons change ("download" button disappears or change by "save" for instance), to get the test still working.
But for now I think it's ok and the other option can be overcomplicating the test (which can easily be fixed if needed).   I'm just thinking out loud.

**Comment by susanchen3** [comment]
hmmm... I think it might be possible to hover over any action button, but then I'm not sure how I would get it to assert the tooltip message if it hovers a random action button. :thinking: I think it's fine to use the 'Download' button because this testcase is using the Clay Sample Portlet :)

**Comment by susanchen3** [comment]
ci:forward

**Pull request closed without merging**
