### PR TITLE
LPS-157811 Standardize tooltip delays in FDS

### PR DESCRIPTION
**Pull request by markocikos**
### References

- [LPS-157811 Standardize tooltip delays in FDS](https://issues.liferay.com/browse/LPS-157811)

### What is the goal of this PR?

The goal was suppose to be to remove tooltip `delay` overrides, setting the delay to default 600ms. But, out of three usages in FDS:
- Two are in unused data renderers, `CommentRenderer` and `TooltipSummaryRenderer`. We are just removing those renderers, along with the test use in commerce `dev` environment.
- `TooltipTextRenderer` is also likely not used, but this one is hard to know for sure. This renderer is not set directly, but is a [conditional branch of the default renderer](https://github.com/liferay/liferay-portal/blob/master/modules/apps/frontend-data-set/frontend-data-set-web/src/main/resources/META-INF/resources/data_renderers/DefaultRenderer.js#L49-L51). This makes it hard to find usages, if they exist. To be on the safe side, we are just removing the delay.

### What does it look like?

There are likely no changes in UI. If `TooltipTextRenderer` is used somewhere, tooltip on it will be delayed by 600ms.

### CODE REVIEW

**Review by diegonvs — APPROVED** [review]

**Comment by diegonvs** [comment]
It's weird to see [some arbitraries values](https://cs.github.com/liferay/liferay-portal?q=delay%3D%20language%3AJavaScript) for tooltip delays around DXP but I remember you're already talking about it with Draco :)

**Comment by markocikos** [comment]
ci:forward

**Comment by diegonvs** [comment]
ci:reevaluate:1307401_3769

**Comment by markocikos** [comment]
ci:forward

**Comment by markocikos** [comment]
Error looks the same, but it's not repeating. The last one is something related to client extentions:
```
LIFERAY_ERROR: Unknown column 'clientexte0_.ctCollectionId' in 'field list'
```

**Comment by diegonvs** [comment]
ci:test:relevant

**Pull request closed without merging**
