### PR TITLE
LPS-186758 Reintroduce Migrate frontend-taglib-chart to ESM after rollback in LPS-186698 (PART 2)

### PR DESCRIPTION
**Pull request by izaera**
This is the second part of the whole feature. It does the real migration or recharts from AMD to ESM.

This PR adds nothing to DXP so there's no need for QA. We only need that it doesn't break anything.

Part 1 is here -> https://github.com/liferay-frontend/liferay-portal/pull/3421

### CODE REVIEW

**Review by bryceosterhaus — APPROVED** [review]
LGTM!

Can't wait for the day when we can remove frontend-taglib-soy

**Comment by izaera** [comment]
ci:test:sf

**Comment by izaera** [comment]
ci:test:relevant

**Comment by deborasoliveira** [comment]
I'm taking a look at the relevant results.

**Comment by mateusralv** [comment]
Hi @izaera The failures are not related, I will not forward it because it has conflict problems.

[Testray Comparison](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1687864868837&testrayRunIdA=2358261256&testrayRunIdB=2358309231)

**Comment by izaera** [comment]
Fixed rebase conflicts

**Comment by izaera** [comment]
ci:forward

**Comment by izaera** [comment]
ci:forward:force

**Comment by izaera** [comment]
ci:forward:force

**Pull request closed without merging**
