### PR TITLE
LPS-169327 Add "view" action to read-only client extensions deployed from OSGi

### PR DESCRIPTION
**Pull request by izaera**
Resend of https://github.com/brianchandotcom/liferay-portal/pull/127045 as per https://github.com/brianchandotcom/liferay-portal/pull/127045#issuecomment-1332477309 and https://github.com/brianchandotcom/liferay-portal/pull/127045#issuecomment-1332484729

### CODE REVIEW

**Comment by izaera** [comment]
ci:forward

**Comment by izaera** [comment]
Very strange: the compilation of JSPs fails locally too, but the files failing are phantom (some don't exist any more, others have been modified) :shrug:

**Comment by izaera** [comment]
ci:forward

**Comment by izaera** [comment]
The first failing test (LocalFile.RemoteApps#CustomElementCanConfigurePortletName) is working for me locally and I don't think the others are related either so I'm going to ask for a QA review

**Comment by mateusralv** [comment]
I'm taking a look 🕵🏽

**Comment by mateusralv** [comment]
ci:test:frontend-remote-apps:nocompile

**Comment by mateusralv** [comment]
Hi @izaera, ci:test:frontend-remote-apps:nocompile because, the test .RemoteApps#CustomElementCanConfigurePortletName works when I reproduce manually, but when I run Poshi the widget does not add the page, I want to see the results of the other tests, sorry for delay.

**Comment by mateusralv** [comment]
Hi @izaera the unique failures are due flakiness, the tests that failed here https://github.com/liferay-frontend/liferay-portal/pull/2889#issuecomment-1335042534 passed here https://github.com/liferay-frontend/liferay-portal/pull/2889#issuecomment-1335309892. So, seems safe to forward. 

[comparison run ](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1669981396111&testrayRunIdA=2090162416&testrayRunIdB=2095369711)

**Comment by izaera** [comment]
Sent manually as https://github.com/brianchandotcom/liferay-portal/pull/127228

**Pull request closed without merging**
