### PR TITLE
LPS-130894 Add endpoints to delete, get and upsert documents by externalReferenceCode

### PR DESCRIPTION
**Pull request by javierdearcos**
I've removed the Transactional annotation because I added it by mistake in an older commit and I realized this annotation is always added at the interface level and not at the class implementation level.

### CODE REVIEW

**Comment by javierdearcos** [comment]
cc @nhpatt

**Comment by nhpatt** [comment]
Why sending in another PR?

**Comment by javierdearcos** [comment]
It was to remove all the noise of previous errors, but it is true that we lose context. I won't do it again except it is really needed if the PR seems stuck

**Comment by javierdearcos** [comment]
ci:forward

**Pull request closed without merging**
