### PR TITLE
LPS-117287 Multiple clicks on links mess up SPA navigation

### PR DESCRIPTION
**Pull request by markocikos**
This is a bugfix, see description and discussion in https://issues.liferay.com/browse/LPS-117287. This ticket exposes several unrelated bugs, one of which we previously fixed in https://github.com/liferay-frontend/liferay-portal/pull/171.

To reproduce, double(+)click on an edit link in journal. I added few console logs for gifs, as it is not clear when I click.

Before:
before

After:
after

Notes:
- This issue is not only in Journal, it is all over the place. It is most noticeable when opening pages with editors, such as journal or blogs, but weird things can happen on any page. For example, management toolbar may render below page content. I was not brave enough to make the change on all links on the portal, or on all `<aui:a>` links. What would be the ideal scope for this kind of change?
- Alternative to prevention is to handle the breakage on opening. I tried this, or example detecting if the editor already exist before creating it and destroying it, but nothing worked on a satisfactory level.

### CODE REVIEW

**Comment by brunobasto** [comment]
hey @markocikos is that only a problem for Journal or could this be happening with other links too? I remember that Senna is supposed to gracefully deal with multiple clicks and cancel the pending navigation and start a new one. If that's affecting other places we might need to fix that in Senna itself.

**Comment by markocikos** [comment]
@brunobasto It is happening with many other links. Senna sound like the right place for the change, I'll give it a shot. Is this the correct [repo](https://github.com/liferay/senna.js) to look in? I never worked on it, so I might need some pointers with integration, PRs, publishing etc.

**Comment by wincent** [comment]
> Is [this](https://github.com/liferay/senna.js) the correct repo to look in?

That's the one.

**Comment by georgel-pop-lr** [comment]
> One thought before diving too heavily into Senna... (and perhaps a silly question) can we repro this behavior with SPA turned off?

I heavily looked into this, and I was unable to reproduce it with senna off, for the moment this is the workaround we offer to our clients who had this issues and all confirm this issues stopped once SPA was disabled.

**Comment by markocikos** [comment]
@brunobasto @wincent Well, I force-pushed **a** solution. My confidence is very low that it's the best one :smile: 

Looking at Senna, I found that, indeed, there is a [mechanism](https://github.com/liferay/senna.js/blob/master/src/app/App.js#L710-L718) that prevents multiple clicks breakage, with pending navigation check. It is a part of `app.navigate`. The problem becomes, why isn't this triggered correctly in portal?

This solution is a bit nuclear, we are forcing `navigate` on every link. Let me paste it full here:
```js
delegate(document, 'click', 'a', (event) => {
	const url = event.delegateTarget.href;

	if (app.canNavigate(url)) {
		app.navigate(url);
	}
});
```

This fixes the double-click bug portal-wide, but is also quite likely to break something. I'll run tests, am curious to see.

I would expect that enforcement like this exists somewhere, or we have some alternative mechanism that achieves auto-navigation. I couldn't find it, but intend to dig more. If you know it, please point me to it.

**Comment by markocikos** [comment]
ci:test:relevant

**Comment by brunobasto** [comment]
> @brunobasto @wincent Well, I force-pushed **a** solution. My confidence is very low that it's the best one 😄
> 
> Looking at Senna, I found that, indeed, there is a [mechanism](https://github.com/liferay/senna.js/blob/master/src/app/App.js#L710-L718) that prevents multiple clicks breakage, with pending navigation check. It is a part of `app.navigate`. The problem becomes, why isn't this triggered correctly in portal?
> 
> This solution is a bit nuclear, we are forcing `navigate` on every link. Let me paste it full here:
> 
> ```js
> delegate(document, 'click', 'a', (event) => {
> 	const url = event.delegateTarget.href;
> 
> 	if (app.canNavigate(url)) {
> 		app.navigate(url);
> 	}
> });
> ```
> 
> This fixes the double-click bug portal-wide, but is also quite likely to break something. I'll run tests, am curious to see.
> 
> I would expect that enforcement like this exists somewhere, or we have some alternative mechanism that achieves auto-navigation. I couldn't find it, but intend to dig more. If you know it, please point me to it.

Hey Marco, I think this can introduce some regressions. Senna has its way of not targeting certain links (or even form submissions) when they have a data attribute `data-senna-off`. With this solution, it seems we are going to bypass that mechanism and that will likely introduce regressions.

I think we might need to dig a little deeper on this one. Looking at git history for both `senna` and `frontend-js-web` it seems they haven't had significant changes in a long time. I wonder if this broke recently or if it's just this bug is been there silent for a long time..

**Comment by brunobasto** [comment]
This might have something to do with it: https://github.com/liferay/senna.js/blob/master/src/app/App.js#L434

Maybe @diegonvs can share some insight (if he remembers this). The issue that introduced this cancellation policy was https://github.com/liferay/senna.js/issues/262

**Comment by wincent** [comment]
> if he remembers this

Screenshot 2020-08-12 -192927-jch3MMp6@2x

i-remember-that

I have trouble remembering what I did yesterday... 👴

**Comment by brunobasto** [comment]
> > if he remembers this
> 
> Screenshot 2020-08-12 -192927-jch3MMp6@2x
> 
> i-remember-that
> 
> I have trouble remembering what I did yesterday... 👴

tenor-95542175

**Comment by diegonvs** [comment]
I don't remember easily which things were needed to change for having the pendingNavigations things working 😭  .

> The problem becomes, why isn't this triggered correctly in portal?

It needs to be investigated deeply ;/

**Comment by diegonvs** [comment]
Watching `Liferay.SPA.app.isNavigationPending` on the console I notice the error:

```
VM4459 ckeditor.js:350 Uncaught TypeError: Cannot read property 'unselectable' of null
    at f (VM3121 ckeditor.js:350)
    at c.<anonymous> (VM3121 ckeditor.js:346)
    at c.d (VM3121 ckeditor.js:10)
    at c.<anonymous> (VM3121 ckeditor.js:12)
    at c.CKEDITOR.editor.CKEDITOR.editor.fire (VM3121 ckeditor.js:13)
    at c.fireOnce (VM3121 ckeditor.js:12)
    at c.CKEDITOR.editor.CKEDITOR.editor.fireOnce (VM3121 ckeditor.js:13)
    at Object.<anonymous> (VM3121 ckeditor.js:273)
    at e (VM3121 ckeditor.js:253)
    at Object.load (VM3121 ckeditor.js:253)
```

is being thrown before the `isNavigationPending` flag is settled to false.

**Comment by markocikos** [comment]
Followup in https://github.com/liferay/senna.js/pull/337

**Pull request closed without merging**
