### PR TITLE
LPD-32142 - Set NODE_ENV in CI to production

### PR DESCRIPTION
**Pull request by bryceosterhaus**

### CODE REVIEW

**Comment by bryceosterhaus** [comment]
cI:test:relevant

**Comment by pyoo47** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
ci:report:43799988

**Comment by bryceosterhaus** [comment]
ci:test:sf

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
sent here https://github.com/liferay-frontend/liferay-portal/pull/4346

**Comment by bryceosterhaus** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/152688

**Pull request closed without merging**
