### PR TITLE
LPS-169672 Provide users with clear information to register iFrame client extensions 

### PR DESCRIPTION
**Pull request by dsanz**
I'm sending this as a rebased version of https://github.com/liferay-frontend/liferay-portal/pull/2894 which we forwarded to https://github.com/brianchandotcom/liferay-portal/pull/127864.

I'd like to hear about CI results because I had to merge some conflicts in the test cases (cc @mateusralv)

Other than that, I just changed some language keys.

### CODE REVIEW

**Comment by dsanz** [comment]
ci:test:relevant

**Comment by dsanz** [comment]
ci:test:stop

**Comment by dsanz** [comment]
ci:stop

**Comment by dsanz** [comment]
ci:test:frontend-remote-apps

**Comment by dsanz** [comment]
ci:test:sf

**Comment by mateusralv** [comment]
Hi @dsanz The results came out late for me and tomorrow I take a look at the results...

**Comment by mateusralv** [comment]
I'm taking a look 🕵🏽

**Comment by mateusralv** [comment]
ci:test:relevant

**Comment by mateusralv** [comment]
I ran the relevant again because I believe that this last round did not work, return + 2000 single failures ([testray comparison)](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1674077972693&testrayRunIdA=2164281093&testrayRunIdB=2164242655)

**Comment by dsanz** [comment]
ci:reevaluate:1317401_6733

**Comment by dsanz** [comment]
@mateusralv I'm not sure, but the failure numbers look the same after a couple of retries. Looks a lot of failing tests for a pull that changes a small portion of the UI. Is there anything we can do about this?

Thank you

**Comment by dsanz** [comment]
ci:test:relevant

**Comment by dsanz** [comment]
Ass agreed with @john-co and @mateusralv I'm closing this one in favor of https://github.com/liferay-frontend/liferay-portal/pull/2993 where I skipped the test commits. We'll continue there.

**Pull request closed without merging**
