### PR TITLE
LPD-15327 Tooltip / title no longer needed in "New" button

### PR DESCRIPTION
**Pull request by markocikos**
### References

- [LPD-15327 Tooltip / title no longer needed in "New" button](https://issues.liferay.com/browse/LPD-15327)
- This is a followup on https://github.com/liferay-frontend/liferay-portal/pull/4006

### What is the goal of this PR?

Compared to the previous solution:
- We are keeping the old trick to manage viewport width versions, using `d-md-block d-none` CSS classes. With this, we are consistent with SSR.
- We are not adding the `label` prop, to retain flexibility in usages. This was a reasonable change, but it caused a lot of regression. To make it work, we would need a more wide-spread migration, which is out of the scope of this task, and IMO probably not worth doing overall.
- We are still keeping the `forwardRef`, as we want to have consistent solution for button in dropdown and standalone button.
- We are reducing the scope of changes just to the creation button, with API toggle that has unchanged default for other usages. We can tweak default or remove API later on, if we get the same product requirements for other usages.

### CODE REVIEW

**Review by juanjofgliferay — APPROVED** [review]
Nice & simple  LGTM :rocket:

**Comment by markocikos** [comment]
ci:forward

**Comment by markocikos** [comment]
ci:forward

**Comment by markocikos** [comment]
ci:report:2549613543

**Comment by markocikos** [comment]
no unique failures, based on https://github.com/liferay-frontend/liferay-portal/pull/4065#issuecomment-1997122854

**Comment by markocikos** [comment]
ci:forward:force

**Pull request closed without merging**
