### PR TITLE
LPS-120737 Adds headless endpoints to Remote Apps Admin portlet - Work In Progress

### PR DESCRIPTION
**Pull request by brunobasto**
This is a draft adding headless endpoints to remote apps. Currently I've only implemented the listing of Remote Apps. I got it half working at some point and noticed there were no actions listed on the table (Edit, Delete). In order to get actions working I decided to follow what Commerce does and took as an example, but found a couple of roadblocks:

The headless java API has utility methods for serializing actions ([see this](https://github.com/liferay/liferay-portal/blob/master/modules/apps/commerce/headless/headless-commerce/headless-commerce-admin-catalog-impl/src/main/java/com/liferay/headless/commerce/admin/catalog/internal/resource/v1_0/ProductResourceImpl.java#L304)) , but some of its signatures depend on either a `groupId` or a `ModelResourcePermission`. Right now our Remote Apps are not scoped by `groupId` ad when trying to use with `ModelResourcePermission` I started getting `404` errors. I assume that's because we haven't implemented any kind of permission registering/checking yet so an exception is thrown somewhere. So I'm stuck at it right now.

As far as I know there are two ways of adding actions to a Data Set that uses the headless APIs:
1. Implement directly in the headless API - which is what I'm trying to do here.
2. Pass `clayDataSetActionDropdownItems` to the TagLib

Tomorrow I will try approach 2.

Another small detail is that on our DataSet we have the search keywords parameter fixed as `search` and from my experience  with portal we prefer using `keywords`. I temporarily [added both](https://github.com/liferay-frontend/liferay-portal/commit/28adbb9003af435a10fa2314eee523f5e733c11b#diff-cc003425be35e5622367c92c8887052bR194) just to make it work. We should probably make it configurable or follow convention and name it keywords (the latter will probably require a good renaming all over commerce.)

### CODE REVIEW

**Comment by wincent** [comment]
@jbalsas: Are we going to pass this one on to somebody else?

Seeing as Bruno is...

so-far-away

**Comment by jbalsas** [comment]
This will be like our memorial, so we can forever remember and cherish @brunobasto 

bye

**Comment by jbalsas** [comment]
In all seriousness... it should be okay to park this here for a little while until the waters clear out. We'll rekindle the flame in a few weeks ;)

**Comment by jbalsas** [comment]
Draft PRs starting to pile up... and you know what they say about broken windows, so I'm going to close this. It's still parked but closed :)

**Comment by brunobasto** [comment]
tenor-105950625

**Pull request closed without merging**
