### PR TITLE
LPS-168138 Adding role button

### PR DESCRIPTION
**Pull request by marcoscv-work**
**Alternative**: https://github.com/liferay-frontend/liferay-portal/pull/3022

---

Add role button to identifies the element as a button to assistive technology such as screen readers.

---

**How to test it**:
- Go to a screen with management-toolbar, example: Users and Organizations > Users
- Activate your screen reader
- Tabbing until you get to the Ascending/descending icon:
- You will see the link is read like a button and it preserves its functionality
image

### CODE REVIEW

**Comment by mateusralv** [comment]
I'm on it!

**Comment by mateusralv** [comment]
Most of the ci:test:relevant tests weren’t tested, so I ran relevant again.

**Comment by mateusralv** [comment]
ci:test:relevant

**Comment by dsanz** [comment]
closing in favor of https://github.com/liferay-frontend/liferay-portal/pull/3022

**Pull request closed without merging**
