### PR TITLE
LPS-182074 Automations for Cell Renderer on Client Extensions

### PR DESCRIPTION
**Pull request by JerryAdrianoo**
**Description:**
Add automations for the render a cell.

**JIRA Ticket:**
https://issues.liferay.com/browse/LPS-182074

### CODE REVIEW

**Comment by JerryAdrianoo** [comment]
ci:test:client-extension

**Comment by deborasoliveira** [comment]
ci:test:frontend-client-extensions

**Comment by JerryAdrianoo** [comment]
cc:@CarlosBrichete

**Comment by JerryAdrianoo** [comment]
ci:test:frontend-client-extensions

**Review by CarlosBrichete — APPROVED** [review]

**Comment by CarlosBrichete** [comment]
LGTM :) Feel free to forward it

**Comment by JerryAdrianoo** [comment]
ci:forward

**Pull request closed without merging**
