### PR TITLE
LPS-189969 LPS-191857 Test fix + Sort data set views by modified date

### PR DESCRIPTION
**Pull request by mateusralv**
**Description:**
Test fix for Sorts the Data Set Views page by modified date

### CODE REVIEW

**Comment by mateusralv** [comment]
ci:test:sf

**Comment by mateusralv** [comment]
ci:test:frontend-data-set

**Comment by thektan** [comment]
This PR can be closed, forwarded to BChan from this PR instead https://github.com/liferay-frontend/liferay-portal/pull/3556

**Comment by thektan** [comment]
ci:close

**Pull request closed without merging**
