### PR TITLE
LPS-174052 Test fix for ClientExtension#CustomElementCanBeDeleted

### PR DESCRIPTION
**Pull request by mateusralv**
### Description: 

- Test fix for ClientExtension#CustomElementCanBeDeleted
- Test fix for clay alert tests 

### JIRA Ticket:

- https://issues.liferay.com/browse/LPS-174220
- https://issues.liferay.com/browse/LPS-174052

### CODE REVIEW

**Comment by mateusralv** [comment]
ci:test:sf

**Comment by mateusralv** [comment]
ci:test:frontend-clay

**Comment by mateusralv** [comment]
ci:test:frontend-client-extensions

**Review by john-co — APPROVED** [review]
Looks good to me! :sunglasses:

**Comment by john-co** [comment]
ci:forward

**Pull request closed without merging**
