### PR TITLE
LPS-203725 Removes LPS-144527 Feature Flags

### PR DESCRIPTION
**Pull request by ealonso**
Motivation
----
Removes feature flags link of Epic [link](https://liferay.atlassian.net/browse/LPS-144527)

### CODE REVIEW

**Comment by ealonso** [comment]
cc: @dsanz

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:sf

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:sf

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by markocikos** [comment]
image    :heart_eyes:

**Review by markocikos — APPROVED** [review]

**Comment by ealonso** [comment]
@markocikos I talked with the Echo QA Team to fix poshi failures, Do we have some guys in Frontend that can help with it? since I think it is going to be a lot of changes.

**Comment by Tim-Cao** [comment]
Hi @ealonso, there is a regression on View Usages of display page template, The fitler button and order button are missing.
image

**Comment by Tim-Cao** [comment]
Running tests on https://github.com/liferay-frontend/liferay-portal/pull/3898

**Comment by Tim-Cao** [comment]
Also, Reports Admin missing filter button and order button cc @ealonso
image

**Comment by Tim-Cao** [comment]
Hi @ealonso, the new button becomes to plus icon on assign Form modal when window size becomes smaller.
image
Would you mind double check?
Form

**Comment by ealonso** [comment]
see: https://github.com/liferay-frontend/liferay-portal/pull/3898

**Pull request closed without merging**
