### PR TITLE
LPS-161245 Creates a new property called `resizeDir` for liferay-editor:editor tag

### PR DESCRIPTION
**Pull request by diegonvs**
# What it does

Given a call for liferay-editor:editor tag, it will enable users to:

```jsp
<liferay-editor:editor
    contents="<%= content %>"
    name="contentEditor"
    resizeDir="both"
/>
```

So, they can set which direction should we resize("vertical", "both", "horizontal")

# More than one possibility [1]

While implementing this, I noticed we could do the same job by adding:

```java
jsonObject
    .put("resize_dir", "both")
```

inside a Java class with the pattern of *EditorConfigContributor.

I decided to create this property/attribute on tag definition to bring one more way to extend this configuration. Like `resizable.`

# How to test

1. Deploy my code
2. Go to [this liferay-editor call](https://cs.github.com/liferay/liferay-portal/blob/29c7086d2a830e711dfa551844b2a77a62369d93/modules/apps/knowledge-base/knowledge-base-web/src/main/resources/META-INF/resources/admin/common/edit_kb_article.jsp#L176)
3. Add a new property called `resizeDir` and provide a value for it, different than "vertical"(default) and deploy the module
4. Go to Content and Data -> Knowledge Base -> Plus Button and create a new Article
5. Try to resize the editor

# Considerations

The default value is "vertical," as https://ckeditor.com/docs/ckeditor4/latest/features/resize.html#limiting-the-resizing-directions explains.

The original property name is `resize_dir` from CKEditor since we don't use snake case for things like properties, I converted it to camel case. 

You might see some limitations like there is a minimum value for the width/height and there is a doc about it here: https://ckeditor.com/docs/ckeditor4/latest/features/resize.html#limiting-the-width-and-height-for-ckeditor-4-resizing

I can't see anywhere on DXP where someone is setting this, but probably it can be overridable using [1]

/cc @pablo-agulla

### CODE REVIEW

**Comment by diegonvs** [comment]
ci:test:relevant

**Comment by diegonvs** [comment]
ci:test:relevant

**Comment by diegonvs** [comment]
`semvar` 😅 . HEAD commit should be renamed. Force-pushing new commit message

**Comment by diegonvs** [comment]
ci:test:sf

**Comment by diegonvs** [comment]
ci:test:relevant

**Comment by diegonvs** [comment]
ci:test:relevant

**Review by markocikos — APPROVED** [review]
@diegonvs  LGTM!

I initially was a bit off-put by `Dir`, as my first association is directory. So I was thinking.. what on earth is 'resize directory'? :thinking:   But I see base ckeditor uses the same config setting, so I guess it makes sense :man_shrugging: We may want to rename this into `resizeDirection`, but either one is ok by me.

You do need to update semver before we can forward this. Just run `gradle baseline` in `frontend-editor-taglib` dir. (see, dir :smile: )

**Comment by diegonvs** [comment]
> You do need to update semver before we can forward this. Just run gradle baseline in frontend-editor-taglib dir. (see, dir smile )

OHhhhhh, thanks!! <3 I missed you

**Comment by diegonvs** [comment]
ci:forward

**Comment by diegonvs** [comment]
ci:forward

**Pull request closed without merging**
