### PR TITLE
LPD-22017 - Use a link to navigate to Visualization Modes tab

### PR DESCRIPTION
**Pull request by juanjofgliferay**
## Story / Task
[LPD-21232](https://liferay.atlassian.net/browse/LPD-21232) / [LPD-22017](https://liferay.atlassian.net/browse/LPD-22017)

## Goal
We are replacing the dropdown as a way to navigate to the Visualization Modes tab when there are no Visualization Modes configured and using a link.

## UI
[Screencast from 2024-04-02 16-36-30.webm](https://github.com/liferay-frontend/liferay-portal/assets/132653342/baab55e5-c927-4caf-a677-428aef813d98)

## Updated Test Cases doc
https://docs.google.com/spreadsheets/d/1GdTSw3KrMDtjEfpkDrih8JcWOTn22ZuIL8s8WPBDAyM/edit?pli=1#gid=0&range=13:13

### CODE REVIEW

**Comment by juanjofgliferay** [comment]
ci:test:playwright

**Comment by juanjofgliferay** [comment]
No playwright failures are related with this PR :tada:

**Comment by herrardo** [comment]
LGTM!

**Comment by dsanz** [comment]
This LGTM ;)

**Review by dsanz — APPROVED** [review]

**Comment by juanjofgliferay** [comment]
ci:forward

**Comment by juanjofgliferay** [comment]
ci:forward:force

**Pull request closed without merging**
