### PR TITLE
LPS-114069 Replace layout classes with new clay components in headless-discovery-web

### PR DESCRIPTION
**Pull request by eduardoallegrini**
This is a simple code replacement of the old layout classes with the new clay layout components

We had some problems testing the original bundle but I've decided to remove the module that was causing problems and work on it separately

https://github.com/eduardoallegrini/liferay-portal/pull/92

### CODE REVIEW

**Comment by eduardoallegrini** [comment]
ci:test:sf

**Comment by eduardoallegrini** [comment]
ci:test:relevant

**Comment by wincent** [comment]
```
     [exec] @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
     [exec] @    WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!     @
     [exec] @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
```

Looks like something that CI infra may be able to sort out — this is the second pull I've seen this on today, so I mentioned it [in the `#ci` channel on Slack](https://liferay.slack.com/archives/C19PWQ74J/p1592483846053800).

**Comment by wincent** [comment]
```
     [exec] Execution failed for task ':apps:app-builder:app-builder-web:packageRunTest'.
```

Pulled this down and it looks like test is timing out. At least, as I write this, it hasn't finished or printed anything in over a minute. I interrupted that run, and it hangs on `master` too. In any case, I am not sure why this change would have repercussions in `app-builder-web`, so I think it's unrelated.

@john-co: does that sound about right to you?

**Comment by wincent** [comment]
Also [asked in `#d-quality-assurance` on Slack](https://liferay.slack.com/archives/CL84ZPHAT/p1592484341450100) about that one.

**Comment by wincent** [comment]
Timeout thing was a red herring. This one is a bad snapshot too:

```
     [exec] FAIL test/js/pages/table-view/EditTableView.es.js (24.093s)
     [exec]   ??? Console
     [exec] 
     [exec]     console.error ../../../node_modules/react-dom/cjs/react-dom.development.js:530
     [exec]       Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?
     [exec]       
     [exec]       Check the render method of `_default`.
     [exec]           in ClayContentRow (created by _default)
     [exec]           in _default (created by FieldTypeWrapper)
     [exec]           in FieldTypeWrapper (created by _default)
     [exec]           in _default (created by FieldsTabContent)
     [exec]           in FieldsTabContent (created by SidebarTabs)
     [exec]           in div (created by SidebarTabContent)
     [exec]           in div (created by SidebarTabContent)
     [exec]           in SidebarTabContent (created by SidebarTabs)
     [exec]           in SidebarTabs (created by _default)
     [exec]           in div (created by SidebarBody)
     [exec]           in SidebarBody (created by _default)
     [exec]           in div (created by ForwardRef)
     [exec]           in div (created by ForwardRef)
     [exec]           in ForwardRef (created by _default)
     [exec]           in div (created by _default)
     [exec]           in _default
     [exec]           in Unknown (created by Wrapper)
     [exec]           in Wrapper
     [exec]           in div
     [exec]           in Unknown (created by Context.Consumer)
     [exec]           in withRouter() (created by _default)
     [exec]           in Unknown (created by Context.Consumer)
     [exec]           in withRouter() (created by _default)
     [exec]           in _default
     [exec]           in Unknown
     [exec]           in Router (created by HashRouter)
     [exec]           in HashRouter (created by _default)
     [exec]           in AppContextProvider (created by _default)
     [exec]           in _default
     [exec] 
     [exec]   ??? EditTableView ??? renders
     [exec] 
     [exec]     expect(received).toMatchSnapshot()
     [exec] 
     [exec]     Snapshot name: `EditTableView renders 1`
     [exec] 
     [exec]     - Snapshot  - 7
     [exec]     + Received  + 6
     [exec] 
     [exec]     @@ -93,11 +93,11 @@
     [exec]                 <div
     [exec]                   class="sidebar-header"
     [exec]                 >
     [exec]                   <form>
     [exec]                     <div
     [exec]     -                 class="autofit-row sidebar-section"
     [exec]     +                 class="sidebar-section autofit-row"
     [exec]                     >
     [exec]                       <div
     [exec]                         class="autofit-col autofit-col-expand"
     [exec]                       >
     [exec]                         <div
     [exec]     @@ -158,11 +158,11 @@
     [exec]                 >
     [exec]                   <nav
     [exec]                     class="component-tbar tbar"
     [exec]                   >
     [exec]                     <div
     [exec]     -                 class="container-fluid"
     [exec]     +                 class="container-fluid container-fluid-max-xl"
     [exec]                     >
     [exec]                       <ul
     [exec]                         class="nav nav-underline"
     [exec]                         role="tablist"
     [exec]                       >
     [exec]     @@ -197,16 +197,15 @@
     [exec]                     <div
     [exec]                       class="active fade mt-3 show tab-pane"
     [exec]                       role="tabpanel"
     [exec]                     >
     [exec]                       <div
     [exec]     -                   class="autofit-row autofit-row-center field-type"
     [exec]     +                   class="field-type autofit-row autofit-row-center"
     [exec]                         data-field-type-name="Text"
     [exec]     -                   draggable="true"
     [exec]                       >
     [exec]                         <div
     [exec]     -                     class="autofit-col pl-2 pr-2"
     [exec]     +                     class="pl-2 pr-2 autofit-col"
     [exec]                         >
     [exec]                           <svg
     [exec]                             class="lexicon-icon lexicon-icon-drag"
     [exec]                             role="presentation"
     [exec]                           >
     [exec]     @@ -214,11 +213,11 @@
     [exec]                               xlink:href="#drag"
     [exec]                             />
     [exec]                           </svg>
     [exec]                         </div>
     [exec]                         <div
     [exec]     -                     class="autofit-col pr-2"
     [exec]     +                     class="pr-2 autofit-col"
     [exec]                         >
     [exec]                           <span
     [exec]                             class="sticker data-layout-builder-field-sticker sticker-rounded sticker-light sticker-md"
     [exec]                           >
     [exec]                             <span
     [exec]     @@ -234,11 +233,11 @@
     [exec]                               </svg>
     [exec]                             </span>
     [exec]                           </span>
     [exec]                         </div>
     [exec]                         <div
     [exec]     -                     class="autofit-col autofit-col-expand pr-2"
     [exec]     +                     class="pr-2 autofit-col autofit-col-expand"
     [exec]                         >
     [exec]                           <h4
     [exec]                             class="list-group-title text-truncate"
     [exec]                           >
     [exec]                             <span>
     [exec] 
     [exec]       221 | 		});
     [exec]       222 | 
     [exec]     > 223 | 		expect(asFragment()).toMatchSnapshot();
     [exec]           | 		                     ^
     [exec]       224 | 	});
     [exec]       225 | 
     [exec]       226 | 	it('renders with two fields in the sidebar and saves successfully', async () => {
     [exec] 
     [exec]       at Object.toMatchSnapshot (test/js/pages/table-view/EditTableView.es.js:223:24)
     [exec] 
     [exec]  ??? 1 snapshot failed.
```

**Comment by wincent** [comment]
So @eduardoallegrini, apart from the order of the class names changing (that is easily fixed with `yarn test -u`), the snapshot mismatches because we are dropping the `draggable="true"`, which is what I pointed out [here](https://github.com/eduardoallegrini/liferay-portal/pull/92#issuecomment-645415370).

The suspicious changes are in `FieldType.es.js`: it used to be a `div` and is now `ClayLayout.ContentRow`. Something about that change is preventing react-dnd from working properly. It may be that `ContentRow` doesn't have a necessary `forwardRef` on it yet (I believe — speaking from vague recollection only — that @bryceosterhaus added that over in Clay, but I don't think it's made it over to liferay-portal yet).

**Comment by john-co** [comment]
hi @wincent, yes looks like a bad snapshot as you found. :smiley:

The github preview message on js-unit test batch unfortunately doesn't provide the useful error message. I tried to correct this in the past but it brought up a more concerning issue where js-unit tests that failed by improper variable definitions were marked as passing. https://issues.liferay.com/browse/LRQA-55216

There's still an open ticket to try to have both: https://issues.liferay.com/browse/LRCI-952

**Comment by jbalsas** [comment]
@wincent, I think the fix should be coming in from https://github.com/liferay-frontend/liferay-portal/pull/36

**Comment by jbalsas** [comment]
Put on Hold until we merge https://github.com/liferay-frontend/liferay-portal/pull/38

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by john-co** [comment]
It looks like the last `ci:test:relevant` run didn't include the changes from #38 yet b/c it didn't yet sync to upstream. Upstream should be updated now but we're seeing merge conflicts and there's still the js-unit snapshot test failing.

**Comment by jbalsas** [comment]
Hey @eduardoallegrini, could you take care of rebasing and updating the branch, please? Try also running the `app-builder-web` tests locally to see if they pass.

Thanks!

**Comment by eduardoallegrini** [comment]
> Hey @eduardoallegrini, could you take care of rebasing and updating the branch, please? Try also running the `app-builder-web` tests locally to see if they pass.
> 
> Thanks!

I'm on it!

**Comment by eduardoallegrini** [comment]
Just started reviewing :)

**Comment by eduardoallegrini** [comment]
https://github.com/liferay-frontend/liferay-portal/pull/45

**Comment by jbalsas** [comment]
@eduardoallegrini, thanks for moving this forward!

Just in case, you know you can simply push-force a branch after a rebase so we can keep it all in the same PR?

See [10. For traceability, prefer updating existing pulls rather than creating new ones](https://github.com/liferay/liferay-frontend-guidelines/blob/master/dxp/code_review.md) in our [Code Review Guidelines](https://github.com/liferay/liferay-frontend-guidelines/blob/master/dxp/code_review.md)

> **For traceability, prefer updating existing pulls rather than creating new ones**. GitHub's UI isn't great for following conversation threads in long-lived pulls, but keeping the conversation in one place does make it less likely that important information will be overlooked. Adding additional commits to an existing pull is a good way to show incremental change in response to a review. Force pushing makes it harder to see what changed, but may be necessary if you must rebase. Likewise, you may squash commits if necessary to avoid confusing history and intermediate broken states from entering the upstream repo. Finally, if the conversation gets too messy, you can declare bankruptcy and create a new PR (always remember to link back to the prior one so that the history can be traced), or split conversation off into an issue (we have issues enabled on the repo for exactly this purpose).

**Comment by eduardoallegrini** [comment]
Yes I know sorry! I didn't have the local branch anymore and pulling from my repo started to give me weird conflicts, so I prefered to get it from this PR (I'll keep it in mind for future tasks)

**Comment by jbalsas** [comment]
Sounds good, no big deal, just making sure the guidelines are known so we can slowly adjust.

The other PR got closed, though, so waiting for a new one ;)

**Comment by wincent** [comment]
> I didn't have the local branch anymore

Pro-Tip™: Even if you delete the local branch, you almost certainly still have it (see `git reflog`; it will show you all the commits you've had checked out recently — you can go back to the `HEAD` of your deleted branch with `git checkout $SHA` once you know the SHA — and if it's too hard to see/find the SHA in the reflog, it will be visible on GitHub too).

**Pull request closed without merging**
