### PR TITLE
LPS-123906 Update clay dependencies

### PR DESCRIPTION
**Pull request by carloslancha**
Original pr: https://github.com/liferay-frontend/liferay-portal/pull/543

Updating @clayui/sticker, @clayui/list and @clayui/card dependencies

Resending because rebase conflicts

### CODE REVIEW

**Comment by carloslancha** [comment]
ci:forward

**Comment by carloslancha** [comment]
ci:forward

**Comment by carloslancha** [comment]
ci:forward

**Comment by pyoo47** [comment]
ci:forward

**Pull request closed without merging**
