### PR TITLE
LPS-119207 Allow "Browse Server" for links and images in CKEditor

### PR DESCRIPTION
**Pull request by matuzalemsteles**
This PR enables the `Browse Server` button in different CKEditor dialogs so things like Document Library Assets or Liferay Pages can be selected and linked when editing content.

**The PR:**
- Updates to a new `ClayModal` version that includes support for `zIndex`
- Adds a `zIndex` param to our existing `openModal` and `openSelectionModal` APIs
- Loads the `filebrowser` plugin by default making sure that dialogs stack on top of each other.

**The Result:**
links

### CODE REVIEW

**Comment by jbalsas** [comment]
Thanks @matuzalemsteles! I'll take this and push a commit soon!

**Comment by jbalsas** [comment]
Worked wonderfully @matuzalemsteles, @kresimir-coko!!

**Comment by jbalsas** [comment]
ci:test:sf

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
@carloslancha, your modals are also beautiful!!

just-sayin

**Comment by matuzalemsteles** [comment]
Failing CI tests look the same as other PRs, I think it's safe to send this manually. They are the same one that failed in #295.

**Comment by jbalsas** [comment]
ci:test:sf

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
Hey @john-co, @zhangyan0701, @PablitoBonito, `zhangyan0701` LocalFile.PagesAdmin#ViewCollectionItemViaPageFinderAndPageAdmin looks like maybe test fix remnant from our modals update.

I'll push this manually but take a look when you have the chance, please.

**Comment by jbalsas** [comment]
Manually forwarded to https://github.com/brianchandotcom/liferay-portal/pull/93202

**Comment by john-co** [comment]
Reviewed. Test failure looks unrelated. :heavy_check_mark: 

@liulukiwi looks like the SelectFrame.selectFrameNoLoading(locator1 = "IFrame#MODAL_BODY"); could be stabilized with SelectFrame(locator1 = "IFrame#MODAL_BODY");. There may be other areas in the test that could benefit from this as well.

**Comment by john-co** [comment]
created https://issues.liferay.com/browse/LRQA-61348 to follow up.

**Pull request closed without merging**
