### PR TITLE
LPS-118539 The table borders are missing in wiki

### PR DESCRIPTION
**Pull request by boton**
The table borders don't show when the user is editing a wiki entry.

**Before**

image

**After**
image

### CODE REVIEW

**Comment by wincent** [comment]
ci:test:sf

**Comment by wincent** [comment]
ci:test:relevant

**Comment by wincent** [comment]
cc @carloslancha @julien — can you please take a look at this one?

**Comment by julien** [comment]
@wincent sure

**Comment by carloslancha** [comment]
LGTM. I'd just want to emphasize that this will affect to all Creole CKEditor instances, just for you to take it into account ;)

**Comment by julien** [comment]
@boton so the change looks good to me, but as we saw on slack, the first time I click on the "table" button this error happens

image

Even though after that, it actually works ...

**Comment by jbalsas** [comment]
ci:forward

**Pull request closed without merging**
