### PR TITLE
LPS-138205 Honor requested locale for dataset JAXRS requests

### PR DESCRIPTION
**Pull request by izaera**

### CODE REVIEW

**Review by nhpatt — APPROVED** [review]
LGTM. I've added a technical task https://issues.liferay.com/browse/LPS-139949 to move these providers to another place in the future.

**Comment by izaera** [comment]
ci:forward

**Comment by izaera** [comment]
I've tried to reproduce the failing test manually and it doesn't fail.

**Comment by izaera** [comment]
ci:test:relevant

**Comment by izaera** [comment]
ci:reevaluate:1327401_532

**Comment by john-co** [comment]
Reviewed. Test failures are unrelated. :heavy_check_mark: 
- CommerceSmoke#PublishSimpleProduct is a known issue failing in upstream. Ok to manually forward

**Comment by john-co** [comment]
pushed to https://github.com/brianchandotcom/liferay-portal/pull/107909

**Pull request closed without merging**
