### PR TITLE
LPS-147887 Delete Clay Data Set tags and API

### PR DESCRIPTION
**Pull request by markocikos**
### References

- [LPS-147887 Delete Clay Data Set tags and API objects](https://issues.liferay.com/browse/LPS-147887)
- [LPS-143847 Migrate Frontend Data Set and apply to the current usages](https://issues.liferay.com/browse/LPS-143847)
- [Strategy to rebuild Data Set Display as a DXP app](https://liferay.atlassian.net/wiki/spaces/ENGFRONTENDINFRA/pages/1912931035/LPS-140691+-+Create+a+strategy+to+rebuild+Data+Set+Display+as+a+DXP+app)

### What is the goal of this PR?

This is the last PR in migration of Clay Dataset Display to Frontend Data Set. There are no usages of Clay Dataset Display in DXP. This was a component that was internal, never promoted or publicly documented, and very buggy for a long time. This is why we are deleting the tag, instead of deprecating it, and not adding it to the list of breaking changes.

There is probably no need for peer review on this PR. The only thing that could go wrong is some missing cleanup, semver update or similar. CI should catch any such error. Feel free to forward if CI is green.

### What does it look like?

No changes in UI.

### CODE REVIEW

**Comment by diegonvs** [comment]
Hey @markocikos, shouldn't we document this change on https://github.com/liferay/liferay-portal/blob/master/readme/BREAKING_CHANGES.markdown? It's not clear to me how we will manage this file as we move towards to Saas but 🤷🏼  /cc @dsanz

**Comment by markocikos** [comment]
Force-pushed. Fixed minor semver conflicts, and added an entry to `BREAKING_CHANGES.markdown`.

**Comment by markocikos** [comment]
ci:test:relevant

**Comment by markocikos** [comment]
No repeating failures in https://github.com/liferay-frontend/liferay-portal/pull/2480#issuecomment-1176331426 and https://github.com/liferay-frontend/liferay-portal/pull/2480#issuecomment-1175022899. It's likely that all failures are unrelated.

**Comment by diegonvs** [comment]
ci:forward

**Comment by markocikos** [comment]
Force-pushed to fix semver conflicts.

**Comment by diegonvs** [comment]
Weird, 

> Target exception: java.lang.NullPointerException

Is this from the server or from your PR?

**Comment by diegonvs** [comment]
ci:test:relevant

**Comment by markocikos** [comment]
> Is this from the server or from your PR?

Is is weird how the error is repeating, seemingly only on this PR. I took a closer look at the [server logs](https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/76123/console), and it seems unrelated. It looks like some garbage collector errors:
```
[beanshell] 1.131: [GC (Allocation Failure) [PSYoungGen: 261120K->0K(261632K)] 261120K->19160K(1048064K), 0.0107332 secs] [Times: user=0.07 sys=0.01, real=0.02 secs] 
[beanshell] 2.751: [GC (Allocation Failure) [PSYoungGen: 261120K->0K(261632K)] 280280K->45325K(1048064K), 0.0090434 secs] [Times: user=0.07 sys=0.01, real=0.02 secs] 
```

It is possible that I need to clean up reference to deleted tags or objects somewhere. :thinking: 

I'll try forwarding one more time, see if the error repeats.

**Comment by markocikos** [comment]
ci:test:relevant

**Comment by markocikos** [comment]
The same CI error: https://github.com/liferay-frontend/liferay-portal/pull/2471#issuecomment-1178987312

**Comment by markocikos** [comment]
ci:forward

**Comment by diegonvs** [comment]
ci:forward

**Comment by markocikos** [comment]
ci:forward

**Comment by markocikos** [comment]
ci:forward

**Comment by diegonvs** [comment]
ci:stop

**Comment by diegonvs** [comment]
ci:forward

**Comment by markocikos** [comment]
ci:forward

**Comment by markocikos** [comment]
Only one fake failure. So close... :disappointed:

**Comment by markocikos** [comment]
@Esther-OC Please take a look if this is safe to manually forward :pray:

**Comment by Esther-OC** [comment]
Hi @markocikos!
Sorry for the delay checking this.

It seems that the failure can be related to your PR because, when checking history, it only fails in this one.  Can be that when deleting something regarding the Clay tags it has affected the element?  Because the failure is this one:

` java.lang.Exception: Element is not present at "//button[contains(@class, 'dropdown-toggle') and contains(@class, 'btn-unstyled') and contains(@class, 'btn-monospaced') and contains(@class, 'component-action')]"`

[Test in Testray ](https://testray.liferay.com/home/-/testray/case_results/1911386841)

**Comment by markocikos** [comment]
@Esther-OC I checked the test failing in the last try, `ContentDashboard#FilterBlogByCategory`:
- The component used in that feature is not FDS, it's management toolbar + search container.
- The error does not appear in https://github.com/liferay-frontend/liferay-portal/pull/2480#issuecomment-1187137378
- If the feature failed because of dependency missing after PR, it would have failed a lot sooner, the component  would not even render
- I tried this case live on clean branch `ant all`, found no error. I did assume a few test steps, when category is selected. I didn't find the equivalent step, that `SelectFrame` looks suspicious to me. Anyways, after selection in UI, the element is there:

screenshot

I'd guess that this test does not correctly reproduce step of selecting a category. But, that's completely unrelated to this PR.

**Comment by susanchen3** [comment]
ci:test:sf

**Comment by susanchen3** [comment]
I think it is safe to manually forward :heavy_check_mark: based on 
- the [analysis](https://github.com/liferay-frontend/liferay-portal/pull/2480#issuecomment-1190316698) you provided 
- `ContentDashboard#FilterBlogByCategory` was able to pass locally for me
- a similar test ([LocalFile.ContentDashboard#FilterByCategory](https://testray.liferay.com/home/-/testray/case_results/1911386578)) passes on the same run 


Although there seems to be an SF issue that should be resolved first.. :)

**Comment by markocikos** [comment]
Force-pushed, adding a completely unrelated source format on `commerce-shipment-web`.

I'll try forwarding one last time, will manually forward if it fails.

**Comment by markocikos** [comment]
ci:test:sf

**Comment by markocikos** [comment]
ci:forward

**Comment by Esther-OC** [comment]
image

**Comment by markocikos** [comment]
Manual forward: https://github.com/brianchandotcom/liferay-portal/pull/120694

**Pull request closed without merging**
