### PR TITLE
LPS-178775 | Automation FrontendDataSetViews#ErrorAppearsWhenProviderBlank

### PR DESCRIPTION
**Pull request by abhnerramos**
**Description**
Confirm the error message that appears when the user tries to create a data set view without the filled name.

**Steps**
- Given access Datasets admin page
- When The user goes to add Datasets // clicking on the New dataset plus button
- And filling the field name with "Test Dataset"
- And clicking on the Save button
- Then Confirm that "This field is required" alert messages are present in the provider field

**JIRA Ticket**
https://issues.liferay.com/browse/LPS-178775

### CODE REVIEW

**Comment by abhnerramos** [comment]
ci:test:frontend

**Comment by abhnerramos** [comment]
@mateusralv could you take a look, please?

**Comment by mateusralv** [comment]
ci:help

**Review by mateusralv — APPROVED** [review]
Good Job! 🎉 the test are passing on CI

**Comment by mateusralv** [comment]
ci:forward

**Comment by abhnerramos** [comment]
ci:test:sf

**Comment by abhnerramos** [comment]
ci:test:sf

**Comment by abhnerramos** [comment]
ci:test:frontend

**Comment by eltonccdantas** [comment]
ci:forward

**Pull request closed without merging**
