### PR TITLE
LRQA-58284 | Consolidate multiple paths names that use the same locator

### PR DESCRIPTION
**Pull request by abhnerramos**
**Description**
Consolidate multiple paths names that use the same locator.

**JIRA Ticket**
https://issues.liferay.com/browse/LRQA-58284

### CODE REVIEW

**Comment by abhnerramos** [comment]
ci:test:stable

**Comment by abhnerramos** [comment]
ci:test:frontend

**Comment by abhnerramos** [comment]
ci:test:sf

**Comment by abhnerramos** [comment]
ci:test:sf

**Comment by abhnerramos** [comment]
ci:test:stable

**Comment by abhnerramos** [comment]
ci:test:frontend

**Comment by abhnerramos** [comment]
ci:test:relevant

**Comment by abhnerramos** [comment]
ci:test:sf

**Comment by abhnerramos** [comment]
ci:test:stable

**Comment by abhnerramos** [comment]
hey @CarlosBrichete, LGTM! Failures don't seem to be related, could you take a look please?

**Review by CarlosBrichete — APPROVED** [review]

**Comment by abhnerramos** [comment]
ci:forward

**Pull request closed without merging**
