### PR TITLE
LPS-144455 Decrease ExceptionMapper priority so other more specific m…

### PR DESCRIPTION
**Pull request by victorg1991**
…appers are called before

For a given Exception, when there is more than one ExceptionMapper, the priority is compared. For reference:
* https://github.com/apache/cxf/blob/master/rt/frontend/jaxrs/src/main/java/org/apache/cxf/jaxrs/provider/ServerProviderFactory.java#L192
* https://github.com/apache/cxf/blob/master/rt/frontend/jaxrs/src/main/java/org/apache/cxf/jaxrs/provider/ServerProviderFactory.java#L638

Currently none of ours ExceptionMapper have a priority assigned, that means that the value given is `Priorities.User` which is 5000. 

This pr set a lower priority for the default ExceptionMapper to allow other more specific Mapper handle their corresponding exception first ([lower priorities values means higher priority  ¯\_(ツ)_/¯](https://docs.oracle.com/javaee/7/api/javax/ws/rs/Priorities.html) ). 10 value is arbitrary, 1 would suffice, but having more we can have other priorities available in the future in case we need it

### CODE REVIEW

**Comment by javierdearcos** [comment]
Reviewing 👀

**Comment by javierdearcos** [comment]
Hi @victorg1991 ,

Thank you for working on this!

I was reviewing this in detail because I was not sure about the problem and solution... I think with the current solution we are putting the APIs general exception mapper in front of every portal request, not only the ones that are related to the APIs, and I think this is not desirable.

The problem comes from the AccessControlledContainerRequestResponseFilterExceptionMapper class that is handling the SecurityException exception and inside the logic is throwing the same exception, which causes this exception not to be caught by the ExceptionMapper chain. This ExceptionMapper is the one responsible to return the Forbidden response that we thought was the correct response, so I believe that this is the correct Exception Mapper but it is not working as expected.

I think this issue should be reviewed by the Security team that will have deeper knowledge about these issues. I will ask them through slack to check what they think about this.

Thank you for all the work

**Comment by javierdearcos** [comment]
Asked here: https://liferay.slack.com/archives/C0A1Z5FJL/p1641995821037100

**Comment by victorg1991** [comment]
Hey @javierdearcos I ended up spliting the class and creating a new exceptionmapper, now this works fine :)  Since this changes security modules I think we should redirect this pr to them. What do you think about the fix?

**Comment by javierdearcos** [comment]
Sent by Victor to the AppSec team to review the PR here: https://github.com/liferay-appsec/liferay-portal/pull/546

Thanks for all the work and help @victorg1991 ! 🤗

**Pull request closed without merging**
