### PR TITLE
LPS-171607 Create a sample for FDS custom data renderer from an external component

### PR DESCRIPTION
**Pull request by markocikos**
### References

- [LPS-171607 Create a sample for FDS data renderer loaded from an external component](https://issues.liferay.com/browse/LPS-171607)
- Related Slack discussion: https://liferay.slack.com/archives/CNBG06JS3/p1671208032869539

### What is the goal of this PR?

We are adding a sample for the use of `setContentRendererModuleURL`. To correctly set module name, we are using NPM Resolver. This is in contrast of the [only usage of API in DXP](https://github.com/liferay/liferay-portal/blob/master/modules/apps/commerce/commerce-product-content-web/src/main/java/com/liferay/commerce/product/content/web/internal/frontend/data/set/view/table/ReplacementCPInstanceTableFDSView.java#L52), where we use legacy NPM bridging.

Note that two conditions need to be met for wiring:
1. Module name needs to match target module `name` defined in [package.json](https://github.com/liferay/liferay-portal/blob/master/modules/apps/frontend-data-set/frontend-data-set-sample-web/package.json#L5).
2. Path needs to be the correct path to the component file: `/js/GreenCheckDataRenderer`

### What does it look like?

See small check next to `Green`:

screen

### Steps to reproduce

1. Deploy `frontend-data-set-sample-web`.
3. Place `Frontend Data Set Sample` widget on any page.

### CODE REVIEW

**Comment by marcelabc** [comment]
Just started reviewing :)

**Comment by markocikos** [comment]
ci:test:relevant

**Comment by dsanz** [comment]
LGTM ;)

**Comment by markocikos** [comment]
ci:forward

**Pull request closed without merging**
