### PR TITLE
LPS-117468 Uses moono-lisa skin

### PR DESCRIPTION
**Pull request by jbalsas**
By default, `liferay-ckeditor` now uses the `moono-lexicon` skin that better matches DXP's look and feel. That skin, however, is not meant to be used with `AlloyEditor` and introduces some conflicting styling.

This PR changes the skin used inside PageEditor AlloyEditor instances back to `moono-lisa`.

To test:
- Launch a clean installation of DXP
- Click the **pencil** icon to edit the home page (with the Hello World widget in it)
- Double click on the "Hello World" text to activate AlloyEditor
- Verify that the editor does not have a background

Screen Shot 2020-07-28 at 09 26 12

@p2kmgcl, can you verify this addresses your issue?

PS: This is a followup of https://github.com/liferay-frontend/liferay-portal/pull/157

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:test:sf

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by carloslancha** [comment]
Would it be an option to set the skin in `alloyeditor.jsp` (instead in the ConfigContributor) if no value is passed? In this way we would be creating the default right before calling the editor and there won't be needed to add it on every Contributor.

**Comment by jbalsas** [comment]
Hey @markocikos, @carloslancha, thanks for the feedback!

> Would it be an option to set the skin in alloyeditor.jsp (instead in the ConfigContributor) if no value is passed? In this way we would be creating the default right before calling the editor and there won't be needed to add it on every Contributor.

It wouldn't, since `PageEditor` renders `AlloyEditor` directly without the JSP tag, so it'll never go through `alloyeditor.jsp`. In this case, configuration is the common place for all editors, not the JSP.

> The change is a good workaround for now, it fixes the issue, but we should consider restricting our allowed configuration inheritance. Devs should start with an alloyeditor and modify it, instead of starting from zero and modify it to something close enough to alloyeditor to use its resources and skin.

Yeah, this makes total sense... as I said [here](https://github.com/liferay-frontend/liferay-portal/pull/157#issuecomment-663600189), I don't think it actually makes sense to be able to use any skin whatsoever with AlloyEditor, but wanted to get this fixed for GA5.

I'll move the configuration to the `BaseAlloyEditorConfigContributor`, though. That makes total sense! 👍

**Comment by jbalsas** [comment]
> I'll move the configuration to the BaseAlloyEditorConfigContributor, though. That makes total sense! 👍

Ok, scratch that 😂 

Not every `ConfigContributor` targeting `AlloyEditor` actually extends `BaseAlloyEditorConfigContributor`, which is where @julien already set the `skin` value. We cannot set it in `BaseEditorConfigContributor` directly because it then will affect **all** editors including those where we want `moono-lexicon`.

So, I'd say this is the way to go:
- Get this workaround merged
- Set `skin` to to `moono-lisa` in AlloyEditor and cut a release from there (no rush)
- Remove the workaround (no rush)

Please, @markocikos, @carloslancha, do you mind double-checking on this and let me know what you think? 

Forward if satisfied with my empty explanations :)

**Comment by markocikos** [comment]
Yeah, I agree we should merge this. :heavy_check_mark: 

What I suggest as a no-rush task is to change:
```
public class FragmentEntryLinkEditorConfigContributor
	extends BaseEditorConfigContributor {
```
to 
```
public class FragmentEntryLinkEditorConfigContributor
	extends BaseAlloyEditorConfigContributor {
```
... and to modify the configuration to override `alloyeditor`, instead of duplicating much of configuration, including the skin added in this PR. This is almost certain to break things, and would require some dependencies juggling, as base alloy class in not in portal kernel like base editor class.

**Comment by carloslancha** [comment]
> It wouldn't, since PageEditor renders AlloyEditor directly without the JSP tag, so it'll never go through alloyeditor.jsp. In this case, configuration is the common place for all editors, not the JSP.

True, didn't think in that.

> Set skin to to moono-lisa in AlloyEditor and cut a release from there (no rush)

We're setting `mono-lexicon` as the skin for CKEditor in `liferay-ckeditor`  so makes total sense to do the same but with `mono-lisa` in AlloyEditor.

**Comment by carloslancha** [comment]
ci:test:relevant

**Comment by carloslancha** [comment]
ci:forward

**Pull request closed without merging**
