### PR TITLE
LPS-159840, LPS-159841 | Add test WalkthroughSiteLevelConfiguration#JSONCanBeUpdated and WalkthroughSiteLevelConfiguration#CanBeDisabled

### PR DESCRIPTION
**Pull request by bronsonsoda**
**Background**
- JSON walkthrough is can be updated
- User is able to disable walkthrough and it doesn't show

**Test Plan**
_JSONCanBeUpdated_
Given walkthrough enabled site-level
When step 1 title is modified
Then step 1 title is updated

_CanBeDisabled_
Given walkthrough enabled site-level
When walkthrough is disabled
Then hotspot element is not present on site

https://issues.liferay.com/browse/LPS-159840
https://issues.liferay.com/browse/LPS-159841

### CODE REVIEW

**Comment by bronsonsoda** [comment]
ci:test:frontend:nocompile

**Comment by bronsonsoda** [comment]
ci:test:frontend:nocompile

**Comment by john-co** [comment]
cc/ @bronsonsoda, please see changes. Also, I updated a couple commit messages to use LPS-159840 instead of LPS-159839.

**Comment by john-co** [comment]
ci:forward

**Comment by john-co** [comment]
ci:stop

**Comment by john-co** [comment]
ci:forward

**Comment by john-co** [comment]
ci:forward

**Pull request closed without merging**
