### PR TITLE
LPD-34321 Correct filter source generation

### PR DESCRIPTION
**Pull request by herrardo**
The version is being duplicated due to a source url modification by an incorrect replacing.

https://liferay.atlassian.net/browse/LPD-34321

### CODE REVIEW

**Review by markocikos — APPROVED** [review]
@herrardo LGTM! :sparkles: 

@dsanz Can we hire this guy? :eyes:

**Comment by herrardo** [comment]
ci:test:sf

**Comment by dsanz** [comment]
ci:test:sf

**Comment by dsanz** [comment]
ci:forward

**Pull request closed without merging**
