### PR TITLE
[TS] LPS-121302

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-121302

Sending from https://github.com/wincent/liferay-portal/pull/367

CC @wincent

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by wincent** [comment]
This fix looks reasonable to me, but I want to page in our Resident Accessibility Expert™, @marcoscv-work.

**Comment by pat270** [comment]
From the LPS:

> If a grouping container that can be expanded or collapsed is not owned by the element that has the aria-expanded attribute, the author SHOULD identify the controlling relationship by **referencing the container from the element that has aria-expanded with the aria-controls property**.

It looks like the button (`.navbar-toggler`) is referencing the container (`.navbar-collapse`) via `aria-controls="navigationCollapse"`. The problem is the `aria-expanded="false"` on `.navbar-collapse`? @marcoscv-work can confirm.

**Comment by marcoscv-work** [comment]
Yeah, I think `aria-expanded` should be in the trigger, that looks like is the previous button. The state `true\false` must change and I'm not sure of that because that `.ftl` is a very custom markup.

Tomorrow afternoon I could take a deeper look

**Comment by ChrisKian** [comment]
Hi @marcoscv-work, have you been able to look into this issue further?  Thanks for your time!

**Comment by ChrisKian** [comment]
Hi @marcoscv-work, do you have any updates regarding this issue?  Is there anything I can provide on my end?  Thanks

**Comment by marcoscv-work** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcoscv-work** [comment]
Sorry for the delay @ChrisKian 

I think making the collapsable container a button is not the solution, it could get the focus and it wouldn't make much semantic sense.

The error is basically telling there is an aria property is not correct for the container, `aria-expand` so we can remove it and fix it.

**Comment by marcoscv-work** [comment]
resend here:
https://github.com/liferay-frontend/liferay-portal/pull/418

**Pull request closed without merging**
