### PR TITLE
LPS-130905 The add and remove row button doesn't work [Bug regression]

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
Reverted original issue LPS-130738 (FP1) because this regression is FP4 and likely a release blocker. 

 **Step to reproduce:**

1. Navigate to Categories admin
2. Add a vocabulary
3. Add a category
4. Click the ellipsis button of category entry > Edit > Properties tab
5. Click the plus icon button

**Before the fix:**
Nothing happens. Additionally, the following error is shown in Browser Console.
```Uncaught TypeError: cannot read property 'cleanNode' of null```

**After the fix:**
There should be a second property shown.

Screenshot 2021-04-21 at 12 57 27

### CODE REVIEW

**Comment by wincent** [comment]
cc @orsolyaDekany @antonio-ortega

We figure a revert is the right thing here because regression is currently pegged at FP4 (may be a release blocker) and original issue it was trying to fix was FP1.

@ambrinchaudhary: I'd say if we have any problems with CI we could just do a manual forward of this (and perhaps even if not).

**Review by wincent — APPROVED** [review]

**Comment by ambrinchaudhary** [comment]
> @ambrinchaudhary: I'd say if we have any problems with CI we could just do a manual forward of this (and perhaps even if not).

I will give a chance to CI ;-). If it fails or takes too much time I'll forward manually as suggested.

**Comment by ambrinchaudhary** [comment]
ci:forward

**Comment by ambrinchaudhary** [comment]
CI errors unrelated. Manually forwarded to Brian inhttps://github.com/brianchandotcom/liferay-portal/pull/100974

**Comment by wincent** [comment]
> Manually forwarded to Brian

i-support-you

**Pull request closed without merging**
