### PR TITLE
[7.4-Only] - LPS-125350 - Remove compat dropdowns

### PR DESCRIPTION
**Pull request by marcoscv-work**
This PR removes the compatibility layer for old dropdowns.

image

I've changed some markup in a navigation widget ftl:

image

---

To test this PR:

- Add subpages for `Home` page
- Refresh and take a look at de menu dropdown

### CODE REVIEW

**Comment by marcoscv-work** [comment]
ci:test:sf

**Comment by marcoscv-work** [comment]
v

**Comment by marcoscv-work** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
Screen Shot 2020-12-29 at 17 34 23

v

**Comment by marcoscv-work** [comment]
ci:test:sf

**Comment by marcoscv-work** [comment]
ci:test:relevant

**Comment by edalgrin** [comment]
Just started reviewing :)

**Review by edalgrin — APPROVED** [review]
I did a general check up in the Portal to spot critical errors, but I didn't find any, so I guess we can forward this and pay attention to bug reports.

**Comment by marcoscv-work** [comment]
ci:forward

**Comment by marcoscv-work** [comment]
Brian wants me to rebase:
https://github.com/brianchandotcom/liferay-portal/pull/97338

**Comment by marcoscv-work** [comment]
Resend here:
https://github.com/brianchandotcom/liferay-portal/pull/97357

**Comment by marcoscv-work** [comment]
Other PRs with other possible solutions to have in count in case of issues showed up:

- https://github.com/liferay-frontend/liferay-portal/pull/669
- https://github.com/liferay-frontend/liferay-portal/pull/670

**Pull request closed without merging**
