### PR TITLE
LPS-129061 Discuss how to solve the issue of empty permission list in site and asset library endpoints

### PR DESCRIPTION
**Pull request by javierdearcos**
This PR is to discuss the approach, if needed, to solve the issue with empty permissions in site and asset library endpoints.

**Problem**
By default, the sites and asset libraries have no entry in the ResourcePermission table to know the permissions they have, that is the one the service query to check permissions. So theoretically the current result with an empty list of permissions is correct, but it does not reflect the real permissions of the user. 

**Propose Solution**
The proposed solution is to create a fallback to the permissions of the type of resource (e.g. com.liferay.journal) in the company when the resource permissions do not exist. I guess that this is what the portal is doing, but we need to verify it to not show an incorrect list of permissions. 

The problem with this approach is there are some cases where it is difficult to differentiate whether the entry does not exist because it was never created, or if the entry does not exist because is true that the user has no permissions. A way I found to differentiate is to check if there is any resource permission with the primaryKey equals to the resourceID (siteId or assetLibraryId). That is the case when a role is given to check its permissions. I don't like it but it is the only way I can think right now.

**Pending**
Depending on what we decide we should modify the tests to be consistent with the behavior and let us check all is working as expected

Let's discuss other approaches, possible solutions, and problems with this code

### CODE REVIEW

**Comment by nhpatt** [comment]
What the portal is doing is this:

```
int count = ResourcePermissionLocalServiceUtil.getResourcePermissionsCount(themeDisplay.getCompanyId(), getSelResource(), ResourceConstants.SCOPE_INDIVIDUAL, getResourcePrimKey());

if (count == 0) {
	boolean portletActions = Validator.isNull(getModelResource());

	ResourceLocalServiceUtil.addResources(themeDisplay.getCompanyId(), getGroupId(), 0, getSelResource(), getResourcePrimKey(), portletActions, true, true);
}
```

And this is the long standing debate of if the APIs should simulate an action on a page or not. This works even deleting the permissions for a user, so I would go this route.

**Review by nhpatt — COMMENTED** [review]
^

**Comment by javierdearcos** [comment]
Thank you very much! I'll change the approach then to the one you suggest. 

Close the PR for the moment as this one was for discussing the topic and I will create a new one with the solution

**Comment by nhpatt** [comment]
There is an open ticket to analyze first: https://issues.liferay.com/browse/LPS-132038.

That could change the solution, we have to know why it's broken first.

**Comment by javierdearcos** [comment]
Ok, I'll start analyzing this bug first.

Thank you for bringing it up

**Pull request closed without merging**
