### PR TITLE
LPD-26175 - React 18 test

### PR DESCRIPTION
**Pull request by bryceosterhaus**

### CODE REVIEW

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
ci:test:sf

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
ci:report:34457017

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
ci:report:36200356

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
ci:report:39144786

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
ci:report:40355189

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
ci:report:65367950

**Comment by bryceosterhaus** [comment]
ci:report:65367950

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
Locally the failing unit tests are

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
ci:test:relevant:norebase

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:test:page-management-playwright

**Comment by bryceosterhaus** [comment]
ci:report:68837535

**Comment by victorg1991** [comment]
ci:test:page-management-playwright

**Comment by victorg1991** [comment]
ci:test:page-management-playwright:norebase

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
ci:stop

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
ci:report:74629313

**Comment by bryceosterhaus** [comment]
ci:report:74629313

**Comment by bryceosterhaus** [comment]
ci:report:77873192

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
ci:report:80947617

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
ci:hello:wakeup:youthere?

**Comment by bryceosterhaus** [comment]
ci:report:80947617

**Comment by bryceosterhaus** [comment]
ci:stop

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
ci:report:82688323

**Comment by bryceosterhaus** [comment]
ci:report:82688323

**Comment by bryceosterhaus** [comment]
ci:help

**Comment by bryceosterhaus** [comment]
ci:report:82688323

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
ci:report:3835230

**Comment by bryceosterhaus** [comment]
ci:report:5527322

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
ci:stop

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
ci:report:7986347

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
ci:report:14434152

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
ci:stop

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
ci:report:19840510

**Comment by bryceosterhaus** [comment]
ci:report:19840510

**Comment by bryceosterhaus** [comment]
closing in favor of https://github.com/liferay-frontend/liferay-portal/pull/4441

**Pull request closed without merging**
