### PR TITLE
LPS-196982 Use of library with known vulnerability: Webpack 5.70.0 (modules)

### PR DESCRIPTION
**Pull request by chestofwonders**
Issue: https://liferay.atlassian.net/browse/LPS-196982

The goal is to remove the dependency on Webpack 5.70.0 which has known vulnerabilities.

However, as modules uses @liferay/npm-scripts to build, Webpack is no longer needed, so this PR gets completely rid of it.

### CODE REVIEW

**Comment by izaera** [comment]
I'm not sure about this PR...

First of all, there are more projects depending on webpack:
image

Additionally, I think that dependency was introduced to override what `npm-scripts` declares. Although I admit we could remove it as suggested and maintain it in `npm-scripts` alone, which is where it should probably be done.

But if this is fixing a security issue I think the only options are:

1. Upgrade webpack version
2. Tell the customer this library is being used for development purposes only, not on production, like we have said before. That limits the possibility of security issues since it is a development tool, not something that runs in the final product.

If we don't do one of those two, the `webpack` dependency will still appear in all reports since `npm-scripts` is pulling it, for example.

**Review by izaera — CHANGES_REQUESTED** [review]
I'm not sure about this PR...

First of all, there are more projects depending on webpack:
image

Additionally, I think that dependency was introduced to override what `npm-scripts` declares. Although I admit we could remove it as suggested and maintain it in `npm-scripts` alone, which is where it should probably be done.

But if this is fixing a security issue I think the only options are:

1. Upgrade webpack version
2. Tell the customer this library is being used for development purposes only, not on production, like we have said before. That limits the possibility of security issues since it is a development tool, not something that runs in the final product.

If we don't do one of those two, the `webpack` dependency will still appear in all reports since `npm-scripts` is pulling it, for example.

**Comment by chestofwonders** [comment]
Thank you for the analysis @izaera! So, for what we would even want to override `npm-scripts` webpack? does it make sense?

You mention development purposes, does it mean that the portal is using (in some cases at least) webpack outside `npm-scripts` for development and `npm-scripts` for production?

**Comment by izaera** [comment]
> for what we would even want to override npm-scripts webpack? does it make sense?

Not sure, TBH... Maybe @bryceosterhaus can provide more insights... If not, we may try to remove it, I guess...

>You mention development purposes, does it mean that the portal is using (in some cases at least) webpack outside npm-scripts for development and npm-scripts for production?

No, I meant that `webpack` is exclusively used a development tool by us (Liferay) internally, not as something that customers will be using because they use DXP.

So unless `webpack` has a security issue that causes it to generate vulnerable code, it's impossible that a customer is affected by the devtools we use in our workflows. It would be only us who may be vulnerable.

**Comment by izaera** [comment]
Yeah, that would be an option too. But if you want to do that this PR doesn't fix it, most probably because as I said there re more dependencies with webpack in other places.

OK, I remember now. I've run `yarn why` in `liferay-portal/modules` and this is what I got:

image

That means that we are overriding to avoid having more than one webpack in the project even if subprojects want to use a different version.

So what you need to do is to change the version number of `webpack` in the `resolutions` section of `package.json`, instead of removing it.

**Comment by bryceosterhaus** [comment]
> So what you need to do is to change the version number of webpack in the resolutions section of package.json, instead of removing it.

yep this sounds accurate to me. I think we typically use resolutions as a way to unify our dependencies in DXP rather than having a bunch of different versions.

**Comment by chestofwonders** [comment]
Thanks for the comments @izaera @bryceosterhaus , I finally upgraded webpack in resolutions to 5.89.0 (current latest)

**Review by izaera — APPROVED** [review]

**Comment by chestofwonders** [comment]
ci:forward

**Comment by chestofwonders** [comment]
ci:test:sf

**Comment by JerryAdrianoo** [comment]
ci:test:stable

**Comment by JerryAdrianoo** [comment]
@chestofwonders if the stable is ok, you can forward it :)

**Comment by chestofwonders** [comment]
ci:forward

**Comment by chestofwonders** [comment]
ci:forward:force

**Pull request closed without merging**
