### PR TITLE
LPS-149452 Update liferay-ckeditor to 4.18.0-liferay.1

### PR DESCRIPTION
**Pull request by diegonvs**
**Full Changelog**: https://github.com/liferay/liferay-ckeditor/releases/tag/v4.18.0-liferay.1

This version bump was necessary to upgrade ckeditor base version on liferay-ckeditor

### CODE REVIEW

**Comment by diegonvs** [comment]
ci:test:sf

**Comment by diegonvs** [comment]
ci:test:relevant

**Comment by diegonvs** [comment]
ci:stop

**Comment by diegonvs** [comment]
ci:stop

**Comment by diegonvs** [comment]
ci:test:sf

**Comment by diegonvs** [comment]
ci:test:relevant

**Comment by diegonvs** [comment]
misericordia

**Comment by diegonvs** [comment]
ci:test:relevant

**Review by markocikos — COMMENTED** [review]
@diegonvs The CI failure could be related, it is on the changed `Click` function. Are we using `clickWaitForInlineCKEditorNoMouseOver` somewhere?

Other than that, LGTM!

**Comment by diegonvs** [comment]
> Are we using clickWaitForInlineCKEditorNoMouseOver somewhere?

Nope, See: https://liferay.slack.com/archives/C3JBR21HA/p1647980803604459?thread_ts=1645728546.036479&cid=C3JBR21HA

**Comment by john-co** [comment]
Looks very similar to https://github.com/liferay-frontend/liferay-portal/pull/1901#issuecomment-1040938821. If that's not the case please let me know if need help to investigate further.

**Comment by john-co** [comment]
ci:test:relevant

**Comment by john-co** [comment]
ci:test:acceptance-functional

**Comment by john-co** [comment]
cc/ @zhangyan0701 @Hijky could one of you follow up on the acceptance-functional analysis when it's ready?

**Comment by zhangyan0701** [comment]
The failures in acceptance-functional are unrelated.

**Comment by john-co** [comment]
ci:forward

**Pull request closed without merging**
