### PR TITLE
[TECHNICAL SUPPORT] LPS-127302 Site scope setting of Asset Publisher portlet does not work properly using Safari with disabled SPA

### PR DESCRIPTION
**Pull request by NemethNorbert**
Hey,
[LPS-127302](https://issues.liferay.com/browse/LPS-127302)

I ended up with the suggested solution from [PTR-2269](https://issues.liferay.com/browse/PTR-2269?focusedCommentId=2381434&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-2381434)

please review it,

Thanks

### CODE REVIEW

**Comment by NemethNorbert** [comment]
ci:test:sf

**Comment by NemethNorbert** [comment]
ci:test:relevant

**Comment by wincent** [comment]
Some good context in those links so just surfacing it here:

-   Original attempt: https://github.com/liferay-frontend/liferay-portal/pull/752
    
-   @antonio-ortega's assessment in the linked PTR:
    
    > Finally, and although is not the goal of this PTR, original's Roland proposal was rejected because it was not fixing the actual root case, but as well because the code he was suggesting to change is rooted deep enough in the platform infrastructure. Why not to carry out this change only for AssetPublisher? You can make use of `onClick` attribute in `liferay-ui:icon` taglib and pass it something like what Roland suggested ... Being honest, that's adding a patch rather than getting the actual root cause, but at least it's a change whose scope is that specific icon in Asset Publisher and it's not going to affect every use of `liferay-ui:icon` as it was suggested in the original pull request.

Will assign this to @jbalsas to see if he is happy with that compromise.

**Comment by jbalsas** [comment]
> Will assign this to @jbalsas to see if he is happy with that compromise.

To be honest, no, I'm not particularly happy with this... I think I got to the bottom of this but I'm not sure when it started happening.
 
### The problem

We're apparently doing some double submission for some reason I fail to understand. The thing is:

- [IconTag](https://github.com/liferay/liferay-portal/blob/master/util-taglib/src/com/liferay/taglib/ui/IconTag.java#L312-L322) generates a specific `onClick` payload to trigger a `submitForm` 
- At the same time, it [registers an icon](https://github.com/liferay/liferay-portal/blob/master/portal-web/docroot/html/taglib/ui/icon/page.jsp#L79-L95) which will listen to clicks in `document` and will trigger another [`submitForm`](https://github.com/liferay/liferay-portal/blob/master/modules/apps/frontend-js/frontend-js-aui-web/src/main/resources/META-INF/resources/liferay/util.js#L364) via [`forcePost`](https://github.com/liferay/liferay-portal/blob/master/modules/apps/frontend-js/frontend-js-aui-web/src/main/resources/META-INF/resources/liferay/icon.js#L30)

So, for some reason we actually attempt to do a double form submission every time we click on those icons when SPA is disabled which fails in Safari. I haven't seen obvious changes in the past years that indicate that this behaviour is new other than the fact that we [moved from explicit listener declaration to a delegation mechanism](https://github.com/liferay/liferay-portal/commit/e3804a1cc77c7a323d14ea61b113e1f17a5c9d32) but I doubt this was the case.

Now, the trick part is that in this case, the second submission goes through the [`Liferay.Util.forcePost`](https://github.com/liferay/liferay-portal/blob/master/modules/apps/frontend-js/frontend-js-aui-web/src/main/resources/META-INF/resources/liferay/util.js#L349-L367) method, which does:

```javascript
const url = currentElement.getAttribute('href');

[…]

submitForm(hrefFm, url, !newWindow);
```

Which, based on [IconTag](https://github.com/liferay/liferay-portal/blob/master/util-taglib/src/com/liferay/taglib/ui/IconTag.java#L344)'s processing, turns out to be `javascript:;`.

From this I infer that Safari will abort the first submission (the one that's actually correct and defined in the link `onClick` attribute) and attempt the second one which unfortunately goes nowhere as `action` becomes `javascript:;`.

Hope this provides more context as to what the problem seems to be.


### Next steps

As for next steps, ideally we'd avoid this weird double submission case, but as everything so legacy it's hard to predict its implications. Hence, knowing that the `forcePost` submission seems to be likely at fault, I'd suggest:
- Figure out a way to preserve the right action url in the link and set it using `data-href` or similar patterns that we already employ
- Use it in `forcePost` instead of the dummy value we currently have

@antonio-ortega, @NemethNorbert, @rolandpakai, could you give this another try?

**Comment by jbalsas** [comment]
An even simpler solution would be to simply return early within `forcePost` to avoid going through `submitForm`. 

```javascript
// since we know submitForm(form, 'javascript:;') does nothing
if (url === 'javascript:;') {
    return;
}
```

This should be a considerably simpler fix.

Going to close here and update the ticket reassigning to @NemethNorbert since he was the last one working on it, but feel free to pick it up as you see fit now that it should be clearer!

**Pull request closed without merging**
