### PR TITLE
LPS-168469 Use newer npm-scripts

### PR DESCRIPTION
**Pull request by izaera**
So that source maps are generated correctly for ESM modules.

### CODE REVIEW

**Comment by izaera** [comment]
ci:forward

**Comment by john-co** [comment]
ci:test:sf

**Comment by izaera** [comment]
ci:test:relevant

**Comment by mateusralv** [comment]
Hi @izaera the failures are not related to your PR 🎉 
[comparison run ](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=2&testrayRunIdB=2072725355&testrayRunIdA=2071633178&statusB=3)

**Comment by izaera** [comment]
Forwarding this manually

**Comment by izaera** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/126790

**Pull request closed without merging**
