### PR TITLE
LPS-130722 Using rowId as part of id HTML attribute for every row in search container

### PR DESCRIPTION
**Pull request by antonio-ortega**
Previously at:

- https://github.com/liferay-frontend/liferay-portal/pull/975 
- https://github.com/liferay-frontend/liferay-portal/pull/986

And updated to accommodate [Brian's feedback from #101142](https://github.com/brianchandotcom/liferay-portal/pull/101142#issuecomment-827609708).

### CODE REVIEW

**Comment by wincent** [comment]
ci:forward

**Comment by wincent** [comment]
Re-opening due to feedback:

> @antonio-ortega what is the difference between
>
> liferay-ui:search-container-row:rowId
>
> and
>
> liferay-ui:search-container-row:rowIdProperty
>
> Type
>
> git grep "liferay-ui:search-container-row:rowId"
>
> And what is the difference between
> 
> 			Object rowIdObject = BeanPropertiesUtil.getObjectSilent(
> 				model, _rowIdProperty);
> 
> 			if (Validator.isNull(rowIdObject)) {
> 				rowId = String.valueOf(_rowIndex + 1);
> 			}
> 			else {
> 				rowId =
> 					FriendlyURLNormalizerUtil.normalizeWithPeriodsAndSlashes(
> 						String.valueOf(rowIdObject));
> 			}
> 
> 			request.setAttribute(
> 				"liferay-ui:search-container-row:rowIdProperty", rowId);
> rowId and _rowIdProperty (we seem to be swapping the names here)
>
> Please resend.

**Review by kresimir-coko — APPROVED** [review]
LNHTM 👍

**Comment by wincent** [comment]
@antonio-ortega

ping-steve-jobs

**Comment by antonio-ortega** [comment]
Fixed, rebased and completed (with an extra commit for a new case) in #1026

**Pull request closed without merging**
