### PR TITLE
LPD-22246 Fix saving behavior while no field is selected

### PR DESCRIPTION
**Pull request by chestofwonders**
Task: https://liferay.atlassian.net/browse/LPD-22246

Fixes:

- The user can save List and Cards assignment modals without fields selected
- List and Cards assignment modals save button no longer crashes 

See complete review: https://liferay.atlassian.net/browse/LPD-15145?focusedCommentId=2618686

### CODE REVIEW

**Review by juanjofgliferay — APPROVED** [review]
LGTM :ok_hand:

**Comment by chestofwonders** [comment]
ci:forward

**Comment by chestofwonders** [comment]
ci:report:2558533733

**Comment by chestofwonders** [comment]
ci:forward:force

**Pull request closed without merging**
