### PR TITLE
LPS-132714 Upgrade ckeditor to v4.16.0-liferay.2

### PR DESCRIPTION
**Pull request by markocikos**
JIRA ticket: https://issues.liferay.com/browse/LPS-132714

@julien @jonmak08 

In addition to ckeditor version increase, we are running `yarn` on `modules` in https://github.com/liferay-frontend/liferay-portal/commit/159bb48d44a7f82f3c9ea1e02a9e9bab653cb29d.

Changelog:
### :wrench: Bug fixes

-   fix: remove unneeded styles ([\#176](https://github.com/liferay/liferay-ckeditor/pull/176))
-   fix: update @clayui/css to latest and add more icons ([\#175](https://github.com/liferay/liferay-ckeditor/pull/175))
-   fix: add null check ([\#168](https://github.com/liferay/liferay-ckeditor/pull/168))

### CODE REVIEW

**Comment by julien** [comment]
Hi @markocikos,

The [change in `package.json`](https://github.com/liferay-frontend/liferay-portal/blob/708cf547ede8a4dbab200db68d15b0dd91ae895b/modules/apps/frontend-editor/frontend-editor-ckeditor-web/package.json) looks good to me, but [as discussed on Slack](https://liferay.slack.com/archives/C3JBR21HA/p1621871657288400?thread_ts=1621852252.256100&cid=C3JBR21HA), we should coordinate with @nhpatt to avoid conflicts in the [`yarn.lock`](https://github.com/liferay-frontend/liferay-portal/pull/1098/commits/159bb48d44a7f82f3c9ea1e02a9e9bab653cb29d) file (additionally I think that the commit message is a little bit confusing because *"Update yarn on dxp"*, could mean that we're actually updating yarn and not the `yarn.lock` file)

**Comment by nhpatt** [comment]
It's Ok for my part, we agreed on committing it here, not going to send anything :)

**Comment by julien** [comment]
@nhpatt ah ok, no worries then - sorry for the confusion.
I also had a look at the test failures and they don't see related.

**Review by julien — APPROVED** [review]

**Comment by markocikos** [comment]
@john-co @manoelcyreno can you please take a look the failure, it looks unrelated.

The [failing test](https://github.com/liferay/liferay-portal/blob/master/portal-web/test/functional/com/liferay/portalweb/functions/WaitForSPARefresh.function#L7-L13) looks wrong. I don't think we should be checking for `height: 82px;` in a functional test. This is something that can very easily change.

**Comment by nkkwon** [comment]
Just started reviewing :)

**Comment by nkkwon** [comment]
**Analysis Details**
@markocikos 

LocalFile.PortalSmokeUpgrade#ViewPortalSmokeArchive621021 - It looks like it's a flaky issue, has the same error occur in a recent [acceptance ](https://testray.liferay.com/home/-/testray/case_results/1534758735?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcases%2F1310700773%2Fview%3FtestrayCaseId%3D1310700773%26cur%3D2%26delta%3D200%26orderByCol%3DcreateDate_sortable%26orderByType%3Ddesc%26resetCur%3Dfalse)run and looks like some other PR are being affected by it

**Comment by john-co** [comment]
cc/ @vicnate5 see flaky PortalSmokeUpgrade#ViewPortalSmokeArchive621021 reported above.

**Comment by john-co** [comment]
ci:test:relevant

**Comment by john-co** [comment]
Trying relevant again so hopefully it passes and ready by morning. If not, ok to manually forward if test failure doesn't look related.

**Comment by markocikos** [comment]
I'm a bit worried about forwarding manually, since we are updating a lot of dependencies in this PR. First CI fail was very on, and second one was aborted build. I'll try forwarding one more time.

**Comment by markocikos** [comment]
ci:forward

**Comment by nhpatt** [comment]
I can split updating the package.json in another PR if it fails again.

**Pull request closed without merging**
