### PR TITLE
LPS-194121 Apply new renderer public API on FDS

### PR DESCRIPTION
**Pull request by markocikos**
### References

- [LPS-189354 Standardize renderer APIs](https://issues.liferay.com/browse/LPS-189354)
- new public API: https://github.com/liferay/liferay-frontend-projects/pull/1157

### What is the goal of this PR?

We are applying new renderers API, along with new naming conventions.

After this PR, we'll be able to safely remove old API from `js-api/data-set/index.ts`

Testing this locally will result in an error, caused by https://github.com/liferay-frontend/liferay-portal/pull/3611 . I did test this with commit from the other PR, and all works fine. 

### What does it look like?

No changes in UI

### CODE REVIEW

**Review by bryceosterhaus — APPROVED** [review]
LGTM!

Will this conflict with https://github.com/brianchandotcom/liferay-portal/pull/139944?

**Comment by markocikos** [comment]
> Will this conflict with https://github.com/brianchandotcom/liferay-portal/pull/139944?

I'm quite sure it won't. To test this PR locally, I had to cherry pick commit from that PR.

**Comment by markocikos** [comment]
ci:test:relevant

**Comment by markocikos** [comment]
@bryceosterhaus While updating docs for this, I noticed an oversight, we are still [coupling renderer types with FDS](https://github.com/liferay/liferay-portal/blob/master/modules/apps/frontend-js/frontend-js-web/src/main/resources/META-INF/resources/renderer/types.ts#L10). This would become an issue when we apply filters CX. I added the change for this in a new commit, https://github.com/liferay-frontend/liferay-portal/pull/3624/commits/aa97eb47848a25de13161240efe24d34dcae5e1c, to use generic interface for `HTMLElementBuilder`. I am not sure if this is better, or to add it in `js-api`, but it looks like TS is smart enough to resolve these as compatible, and it's probably better to have a set or more specific interfaces in public API. What do you think?

**Comment by markocikos** [comment]
ci:test:relevant

**Comment by markocikos** [comment]
@bryceosterhaus Interesting issue here, repeating CI failures with
```js
src/index.ts(6,14): error TS2305: Module '"@liferay/js-api/data-set"' has no exported member 'FDSFilterHTMLElementBuilder'.
```

I believe the root cause of this is that dependency version in PR is `^0.2.0-pre.0"`. I left in the caret without much thought, but it keeps resolving to `0.3.0-pre.0`. It seems that after you released 0.4.0, [0.3.0 still counts as the latest version](https://www.npmjs.com/package/@liferay/js-api?activeTab=versions). Maybe you put some prerelease flag on 0.4.0, that we didn't set on 0.3.0?

I'll push the dependency without the caret, so it is the same as in `frontend-js-dependencies-web`. I guess it makes sense in general, as prerelease versions should be fine to have breaking changes even between minor versions.

**Comment by markocikos** [comment]
ci:test:relevant

**Comment by andreluis2022** [comment]
Hey @markocikos  I'll take a look at the failures when I finish the relevant

**Comment by markocikos** [comment]
@andreluis2022 I'm quite sure that the one repeating failure is related. I'm not quite sure how to fix it :thinking:

**Comment by markocikos** [comment]
I think I've figured it out. I didn't update the version on `liferay-sample-fds-filter`. This injects the 0.3.0 version, that keeps wining the import resolve.

**Comment by markocikos** [comment]
ci:test:relevant

**Comment by markocikos** [comment]
@andreluis2022 OK, failures in https://github.com/liferay-frontend/liferay-portal/pull/3624#issuecomment-1702980845 look like they are likely unrelated

**Comment by markocikos** [comment]
ci:forward

**Comment by markocikos** [comment]
ci:forward

**Review by kresimir-coko — APPROVED** [review]
LNHTM 👍

**Comment by andreluis2022** [comment]
I'm work on it

**Comment by markocikos** [comment]
ci:forward

**Pull request closed without merging**
