### PR TITLE
LPS-136048 The staging indicator drop-down menu is displayed unstyled in the upper left corner

### PR DESCRIPTION
**Pull request by boton**
https://issues.liferay.com/browse/LPS-136197

**How to reproduce**
1. Add a new Asset Library: Open applications menu > Content > Asset Libraries > [ + ] Add
2. Enable staging for this Asset Library:  Click in the name of new Asset Library > Staging > Select local live
image
3. Assert the staging indicator drop-down menu

---

**Before this PR**
image

**After this PR**
image

### CODE REVIEW

**Comment by pat270** [comment]
The scss LGTM! Thanks @boton.

**Comment by boton** [comment]
ci:test:relevant

**Comment by boton** [comment]
ci:reevaluate:1287401_180

**Comment by boton** [comment]
ci:reevaluate:1287401_180

**Comment by diegonvs** [comment]
ci:test:relevant

**Comment by boton** [comment]
ci:test:relevant

**Comment by nhpatt** [comment]
ci:forward

**Pull request closed without merging**
