### PR TITLE
LPD-36212, LPD-37203, LPD-36188 Allow using directive script-src-attr 'none' by removing inline handlers

### PR DESCRIPTION
**Pull request by izaera**
Comes from https://github.com/liferay-frontend/liferay-portal/pull/4459

### CODE REVIEW

**Comment by izaera** [comment]
ci:test:stable

**Comment by izaera** [comment]
If this passes stable I will forward it manually since we have only changed SF stuff.

**Comment by izaera** [comment]
CC: @ling-alan-huang

**Comment by izaera** [comment]
Continues at https://github.com/brianchandotcom/liferay-portal/pull/154759

**Comment by dsanz** [comment]
ci:test:commerce

**Pull request closed without merging**
