### PR TITLE
LPS-183502 LPS-18665 Enable sorting by create date in the list of Datasets

### PR DESCRIPTION
**Pull request by thektan**
**Story:** https://issues.liferay.com/browse/LPS-183502
**Subtask:** https://issues.liferay.com/browse/LPS-186653

In the Datasets Table:
- Default sorts by create date
- Allows columns to be sortable (excluding the "Views" column)

### Demo

https://github.com/liferay-frontend/liferay-portal/assets/4496722/945ff048-ee56-47c6-a2b2-60bf42c8f94f

### CODE REVIEW

**Comment by dsanz** [comment]
LGTM!

**Comment by dsanz** [comment]
@mateusralv can we know if failing tests are related to the dataset app? Thank you

**Comment by deborasoliveira** [comment]
I'll take a look at the relevant results.

**Comment by deborasoliveira** [comment]
I'll continue the analysis tomorrow.

**Comment by deborasoliveira** [comment]
One of the failures is a test fix case but the others seem to be unrelated to the PR.

[Comparison run](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=2&testrayRunIdB=2342595127&testrayRunIdA=2342463070&statusB=3)

**Comment by thektan** [comment]
After test fixes are made, this can be forwarded. Feel free to open a new PR with your test fixes combined if you're able to push onto my branch.

**Comment by mateusralv** [comment]
Hi @thektan and @dsanz I have sent a new PR adding an ignore to the test and created a task for the fix to be done ( [LPS-187299](https://issues.liferay.com/browse/LPS-187299)). This way we can continue with this PR :)

**Comment by mateusralv** [comment]
Continue: https://github.com/liferay-frontend/liferay-portal/pull/3432

**Pull request closed without merging**
