### PR TITLE
LPS-125066 Fix <clay:management-toolbar-v2> not rendering the component

### PR DESCRIPTION
**Pull request by wincent**
Based on repro:

1. Content & Data > Kaleo Forms Admin
2. Create a new Process
3. Create and Choose a FieldSet
4. Choose a Workflow Definition
5. Assign a form to any workflow task

You can see this error in the console:

    Uncaught TypeError: Cannot read property '_com_liferay_dynamic_data_mapping_web_portlet_DDMPortlet_keywords' of undefined

It seems that we need to wait for the component to be rendered client-side before trying to focus the field. So, register a component ID and wait for it, using the [same pattern as in the neighboring `select_structure.jsp`](https://github.com/liferay/liferay-portal/blob/9c0936516180b28b6db2830e6b7fcac3ea3de1a9/modules/apps/dynamic-data-mapping/dynamic-data-mapping-web/src/main/resources/META-INF/resources/select_structure.jsp#L110-L116), which was added in [liferay-frontend/liferay-portal#614](https://github.com/liferay-frontend/liferay-portal/pull/614/files#diff-16b5273d20da4f6733a2d2aedd18f086b57bc183d9df0b355965d9425eddfe54).

Here's proof of the management toolbar rendering after this fix:

Screenshot 2020-12-18 -111047-aC80aeOa@2x

### CODE REVIEW

**Comment by wincent** [comment]
cc @albinojunior

**Comment by wincent** [comment]
ci:test:bundle

**Review by markocikos — APPROVED** [review]
LGTM!

SF is a bit different compared to https://github.com/liferay-frontend/liferay-portal/pull/614/files#diff-16b5273d20da4f6733a2d2aedd18f086b57bc183d9df0b355965d9425eddfe54 , we probably should be consistent one way or another :)

**Comment by wincent** [comment]
> we probably should be consistent one way or another :)

What do you suggest we do? I'm guessing you're referring to the fact that this one has two consecutive `<aui:script>` tags? I wanted to make the minimal change, so I left the consecutive tags in-place. Or maybe you're talking about how the other one receives the `managementToolbar` parameter but doesn't use it (I omitted it because it's unused). Am I missing something else?

**Comment by markocikos** [comment]
Yeah, I didn't spot the omitted `managementToolbar`, thought you just removed few line breaks. All good :+1:

**Review by julien — APPROVED** [review]

**Comment by julien** [comment]
ci:forward

**Pull request closed without merging**
