### PR TITLE
LPD-38600 Adjust z-index css

### PR DESCRIPTION
**Pull request by fortunatomaldonado**
Addition Commit for https://liferay.atlassian.net/browse/LPD-38600

Needed to specify the css to `.cke_panel.cke_combopanel.lfr-maximized` and change the z-index.

Please let me know if there are any questions or comments about this.
Than you!

### CODE REVIEW

**Review by markocikos — APPROVED** [review]
@fortunatomaldonado LGTM! :sparkles:

**Comment by fortunatomaldonado** [comment]
ci:test:sf

**Comment by fortunatomaldonado** [comment]
ci:test:relevant

**Comment by fortunatomaldonado** [comment]
ci:test:relevant

**Comment by fortunatomaldonado** [comment]
ci:forward

**Pull request closed without merging**
