### PR TITLE
LPS-172167 | Fix for ClayAlertToast#AutoclosesWhenNotHoveredOver 

### PR DESCRIPTION
**Pull request by mateusralv**
Background:
Investigate failure and create a fix for testcase.

JIRA Link:
https://issues.liferay.com/browse/LPS-172167

### CODE REVIEW

**Comment by mateusralv** [comment]
ci:test:sf

**Comment by mateusralv** [comment]
ci:test:frontend-clay

**Comment by mateusralv** [comment]
ci:test:frontend-clay

**Comment by mateusralv** [comment]
ci:test:frontend-clay

**Comment by mateusralv** [comment]
ci:test:sf

**Review by john-co — APPROVED** [review]
Looks good to me! :sunglasses:

**Comment by john-co** [comment]
ci:forward

**Pull request closed without merging**
