### PR TITLE
LPD-21277 Quarantine failing frontend infra tests

### PR DESCRIPTION
**Pull request by john-co**
**Description**
Some tests have been failing at a high rate and will be quarantined to reduce impact on release testing analysis. Please unquarantine the tests as each fix is implemented in their respective follow up tickets.

**JIRA Ticket**
https://liferay.atlassian.net/browse/LPD-21277

### CODE REVIEW

**Comment by izaera** [comment]
Most probably the vast majority of these tests will be rewritten in Playwright so I think it's OK to forward this.

However, since this is totally new to me (a PR sent to us to quarantine tests) I'm unsure what to do... :thinking: 

Should we forward it directly? @john-co ?

**Comment by john-co** [comment]
Please forward directly if it's ok.

**Comment by izaera** [comment]
ci:forward

**Comment by izaera** [comment]
@john-co still fails? Feel free to fix and/or force-forward it, since I'll be off until next Monday (public holiday) and I'm unsure whether this can be force-forwarded. Thx.

**Comment by markocikos** [comment]
ci:forward

**Comment by markocikos** [comment]
ci:report:2557854206

**Comment by markocikos** [comment]
No unique failures, based on https://github.com/liferay-frontend/liferay-portal/pull/4088#issuecomment-2036880982.

I feel like we can push this. It may not fix all the cases, but it fixes many of them, improving CI.

**Comment by markocikos** [comment]
ci:test:stable

**Comment by markocikos** [comment]
ci:test:stable

**Comment by markocikos** [comment]
ci:test:stable

**Comment by john-co** [comment]
ci:test:stable

**Comment by john-co** [comment]
ci:test:sf

**Comment by john-co** [comment]
The compile test failure on stable was related. I force pushed a fix.

**Comment by john-co** [comment]
ci:forward:force

**Pull request closed without merging**
