### PR TITLE
LPS-135068 Allow users to subscribe to tags

### PR DESCRIPTION
**Pull request by javierdearcos**
Provide the service infrastructure to subscribe/unsubscribe to AssetTags.

Create endpoints to subscribe and unsubscribe to a keyword (AssetTag).

PR to discuss the approach (it seems very straightforward). Then maybe it is better to divide in two PRs, one for service changes and another for APIs

### CODE REVIEW

**Comment by nhpatt** [comment]
Mmm... but you are using the deprecated services, right? Should we do it? Are we the only ones?

**Review by nhpatt — COMMENTED** [review]
Everything looks perfect but we are using some deprecated funcionality and I think we are the only ones doing it :( There is a module for subscriptions outside kernel.

**Comment by javierdearcos** [comment]
Yes... I forgot to ask you... I notice that we have a new subscription service but as the AssetTag services are inside the kernel, I thought it wasn't a good idea to make a dependency from kernel to anywhere else.

Another option I thought about is to extract the services from the kernel to the asset modules but I don't know if it is something we can do (I've heard Brian several times against expending more effort modularizing)

**Comment by nhpatt** [comment]
> I notice that we have a new subscription service but as the AssetTag services are inside the kernel, I thought it wasn't a good idea to make a dependency from kernel to anywhere else.

I don't think we can do it directly, it won't compile/work, only indirectly.

> Another option I thought about is to extract the services from the kernel to the asset modules but I don't know if it is something we can do (I've heard Brian several times against expending more effort modularizing)

This we should ask the product team responsible before doing anything. And is... core infra? echo?

That's why this task is "hard"... because if we are the only ones using the deprecated services we should not do it... we should find another way, either using the notification module somehow without adding a required dependency or by extracting if we get the permission, or maybe interacting with an API... it's a arquitectural problem, core can not depend on a module.

**Comment by javierdearcos** [comment]
Understood. I'll explore these options and figure out which team is responsible for this service. Thank you!

**Comment by javierdearcos** [comment]
Reimplemented the feature using ServiceWrapper, an idea powered by @jkappler (thank you so much ❤️ ).

**Comment by javierdearcos** [comment]
ci:test:sf

**Comment by nhpatt** [comment]
Perfect solution, very nice approach, thank you @jkappler and @javierdearcos.

This is not urgent but I think it has 0 risk of breaking other things in the portal, so forwarding...

**Comment by nhpatt** [comment]
ci:forward

**Review by nhpatt — APPROVED** [review]
👏 👏 👏

**Pull request closed without merging**
