### PR TITLE
LPS-198123 Modified detailed msg for ClientExtensionEntryTypeSettingsException

### PR DESCRIPTION
**Pull request by ethib137**
Resent from https://github.com/liferay-frontend/liferay-portal/pull/3775

https://liferay.atlassian.net/browse/LPS-198123

@SelenaAungst I reviewed with Marcos Castro what we want the error messages to be. Can you make sure it looks and works okay.

### CODE REVIEW

**Comment by SelenaAungst** [comment]
Hi @ethib137,
I tested this, everything works well and looks great! Thanks again for your help on this one.

**Comment by SelenaAungst** [comment]
ci:test:relevant

**Comment by SelenaAungst** [comment]
@izaera Please let me know if there is anything else I can do for this one to pass review. Thanks!

**Comment by izaera** [comment]
@SelenaAungst I've asked FI QA to review the failures. If they give the approval, you can use `ci:forward:force` (or forward it manually if that fails) to send it to Brian.

**Comment by mateusralv** [comment]
Hi @SelenaAungst and @izaera I had a look and found no regression, just an update to the semantic module. It also seems safe to forward.

```
  [exec] com.liferay.semantic.versioning.SemanticVersioningTest > testSemanticVersioning[/apps/client-extension/client-extension-api] FAILED
     [exec]     java.lang.AssertionError:   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec]     = ================================================== ========== ========== ========== ========== ==========
     [exec]     * com.liferay.client.extension.exception             MAJOR      4.1.0      4.1.0      5.0.0      VERSION INCREASE REQUIRED
     [exec]     	>   class      com.liferay.client.extension.exception.ClientExtensionEntryTypeSettingsException
     [exec]     		-   method     <init>(java.lang.String,java.lang.Object[])
     [exec]     			-   return     void
     [exec]     		+   method     <init>(java.lang.String,java.lang.String,java.lang.Object[])
     [exec]     			+   return     void
     [exec]     [Baseline Warning] Bundle Version Change Recommended: 11.0.0
```

[Testray Comparison](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=2&testrayRunIdB=2448310935&testrayRunIdA=2447500155&statusB=3)

**Comment by izaera** [comment]
So @SelenaAungst , just run `gradle baseline` in `client-extension-api`, commit the change, push it, and you are good to `ci:forward:force` or manual forward of the PR...

**Comment by SelenaAungst** [comment]
@izaera Added and resent here: https://github.com/liferay-frontend/liferay-portal/pull/3796

**Comment by bryceosterhaus** [comment]
closing because it was sent elsewhere

**Pull request closed without merging**
