### PR TITLE
COMMERCE-4701 Fixed dataset action urls

### PR DESCRIPTION
**Pull request by Commando18**

### CODE REVIEW

**Comment by Commando18** [comment]
ci:test:relevant

**Comment by Commando18** [comment]
ci:test:sf

**Comment by jbalsas** [comment]
Hi @Commando18, good to see you contributing here with us for the first time!!

In order to improve our review workflow, we ask that you help us out by following some these recomendations:
- [Frontend Infrastructure Team code review process](https://github.com/liferay/liferay-frontend-guidelines/blob/master/dxp/code_review.md)
- [Pull Request Etiquette](https://github.com/liferay/liferay-frontend-guidelines/blob/master/general/pull_requests.md)

Most importantly:
- Provide a meaningful PR title (✔️)
- Provide a meaningful PR description (✖️)
    - Describe the observed problem
    - Add a technical explanation of the issue
    - Describe the solution and why it's the right one
    - Comment any technical considerations, things you tried, cases you considered...
- Include a test plan (✖️)

While some of these might seem redundant and the information might be in the LPS, writing all that down here helps us focus on the review and track everything better through the workflow, so we really appreciate you taking the time to make this easier for us 🤗 

Please, reach out to @FabioDiegoMastrorilli or @gianmarcobrunialti if you need some clarification or let us know here so we can move this forward!

**Comment by brunobasto** [comment]
ci:test:relevant

**Comment by FabioDiegoMastrorilli** [comment]
Action URLs may contain strings like `id={id}`. In this cases, the formatter will check the current item, will take `items[x].id` value and will build the url.
We could also have `productId={product.id}`. The value which will end up in the url will be `items[i].product.id`.

The `.` separator has changed while the migration was going on (before it was `|`).

**Comment by brunobasto** [comment]
Thanks @FabioDiegoMastrorilli and @Commando18 

I'm forwarding this because it looks like a simple change and Marco Leo asked me if we could get this merged today. If there are any concerns I'm sure we an fix them in follow up PRs.

**Comment by brunobasto** [comment]
ci:forward

**Pull request closed without merging**
