### PR TITLE
LPS-184467 Implement a fragment showing FDS View v3

### PR DESCRIPTION
**Pull request by markocikos**
### References

- [LPS-184467 Implement a fragment showing FDS View](https://issues.liferay.com/browse/LPS-184467)
- A followup on https://github.com/liferay-frontend/liferay-portal/pull/3372
- A followup on https://github.com/liferay-frontend/liferay-portal/pull/3382

### What is the goal of this PR?

For the goal of the task, see original PR.

In this followup, we are mass renaming `Dataset` to `Data Set` **everywhere** in DXP, based on https://github.com/brianchandotcom/liferay-portal/pull/135675#issuecomment-1570631599 and discussions after. This includes:
- `frontend-data-set` app, code and tests
- `commerce`
- lang keys

As we are already changing event names, I took the opportunity to tweak export name, resulting in a minor change in `frontend-taglib`.

Most of changes in followup are renames, with no need for peer review. However, it might be wise for commerce QA to check if everything is working, and FI QA to check changes on tests. Specially the auto-generated change on test, that one looks suspicious.

### CODE REVIEW

**Comment by CarlosBrichete** [comment]
ci:test:relevant

**Comment by markocikos** [comment]
ci:test:relevant

**Review by bryceosterhaus — APPROVED** [review]
LGTM!

**Comment by markocikos** [comment]
ci:forward

**Comment by markocikos** [comment]
ci:forward

**Comment by mateusralv** [comment]
Hi @markocikos I found POSHI failures related to this PR.

```
 [exec] 42 errors in POSHI

  [exec] 42 errors in POSHI
     [exec] 
     [exec] Invalid macro command FrontendDataSetAdmin#deleteAllDatasetEntries at:
     [exec] /opt/dev/projects/github/liferay-portal/portal-web/test/functional/com/liferay/portalweb/tests/enduser/frontendinfrastructure/uiinfrastructure/frontenddataset/datamanagment/DatasetSorting.testcase:48
     [exec]   41 |    }
     [exec]   42 |
     [exec]   43 |    tearDown {
     [exec]   44 |        var testPortalInstance = PropsUtil.get("test.portal.instance");
     [exec]   45 |
     [exec]   46 |        FrontendDataSetAdmin.deleteAllDatasetViews();
     [exec]   47 |
     [exec] > 48 |        FrontendDataSetAdmin.deleteAllDatasetEntries();
     [exec]   49 |
     [exec]   50 |        if (${testPortalInstance} == "true") {
     [exec]   51 |            PortalInstances.tearDownCP();
     [exec]   52 |        }
     [exec]   53 |    }
     [exec]   54 |
     [exec]   55 |    @description = "LPS-185324. Confirm that the new default classification modal is displayed, the field is required."
     [exec] 
     [exec] 
     [exec] Invalid macro command FrontendDataSetAdmin#goToDatasetAdminPage at:
     [exec] /opt/dev/projects/github/liferay-portal/portal-web/test/functional/com/liferay/portalweb/tests/enduser/frontendinfrastructure/uiinfrastructure/frontenddataset/datamanagment/DatasetSorting.testcase:17
     [exec]   10 |
     [exec]   11 |    setUp {
     [exec]   12 |        TestCase.setUpPortalInstance();
     [exec]   13 |
     [exec]   14 |        User.firstLoginPG();
     [exec]   15 |
     [exec]   16 |        task ("When Create a DataSet ") {
     [exec] > 17 |            FrontendDataSetAdmin.goToDatasetAdminPage();
     [exec]   18 |
     [exec]   19 |            FrontendDataSetAdmin.createDataSet(
     [exec]   20 |                key_name = "Test Dataset",
     [exec]   21 |                key_type = "/c/fdssorts");
     [exec]   22 |
     [exec]   23 |            Refresh();
     [exec]   24 |        }
     ...
```

**Comment by markocikos** [comment]
@mateusralv @CarlosBrichete I removed from the PR all changes on `frontend-data-set-test`, as it looks they are not immediately applied. I see in https://github.com/liferay-frontend/liferay-portal/pull/3389#issuecomment-1576816069  `FrontendDataSetAdmin.goToDatasetAdminPage` that I changed in the PR. Hopefully test module does not count for change "everywhere" :crossed_fingers:

**Comment by markocikos** [comment]
ci:forward

**Comment by markocikos** [comment]
Oh I see, there are additional tests in `portal-web`. I only looked in `frontend-data-set-test`.

Let's see if PR goes through as it is. We can make a mass update on tests in a followup.

**Comment by markocikos** [comment]
Force-pushed! Changes:
- @CarlosBrichete @mateusralv Some of the failures in https://github.com/liferay-frontend/liferay-portal/pull/3389#issuecomment-1577505036 were related, we need to update tests along with PR. I put back my previous commits with changes on tests and added changes to Poshi tests as well.
- Some additional changes in commerce, completely removing all mentions of `Dataset` there.

**Comment by markocikos** [comment]
ci:forward

**Comment by markocikos** [comment]
Force-pushed, fixing a minor conflict. In addition, added unrelated auto-SF.

**Comment by markocikos** [comment]
ci:forward

**Comment by markocikos** [comment]
ci:test:relevant

**Comment by markocikos** [comment]
ci:test:sf

**Comment by markocikos** [comment]
ci:test:sf

**Comment by dsanz** [comment]
@markocikos yeah we need this merged to unblock other stuff

**Pull request closed without merging**
