### PR TITLE
LPS 175500

### PR DESCRIPTION
**Pull request by ealonso**
Motivation
-----
It removes old taglibs AssetCategories and AssetTags since those were deprecated in 7.3. Also, it removes toggle-card type from input taglib since it is no used around portal.

### CODE REVIEW

**Comment by bryceosterhaus** [comment]
Love these PRs. If tests pass, this LGTM!

**Comment by ealonso** [comment]
ci:forward

**Comment by dsanz** [comment]
Yeah, LGTM

**Comment by ealonso** [comment]
Manually forward see: https://github.com/brianchandotcom/liferay-portal/pull/130247

**Pull request closed without merging**
