### PR TITLE
LPD-43223 - Predefined value table is either not visible or non interactive on object Actions when Clay table FF is enabled

### PR DESCRIPTION
**Pull request by ethib137**
Resending from: https://github.com/liferay-platform-experience/liferay-portal/pull/865

https://liferay.atlassian.net/browse/LPD-43223

The main approach here requires switching the table to a controlled component. Otherwise inline editable cells will not work correctly since they need to pass in the updated html that results from editing.

This also reveals another bug in the Clay Table. [This](https://github.com/liferay/clay/blob/961c6715dfbc08da721fb1b8c97033bcd450958c/packages/clay-core/src/table/Head.tsx#L75) is only called at first render, but we need this to be called every time the collection changes. This results in an extra cell added to the body rows of the table when you hide a column. This issue can be reproduced by navigating to Commerce products and hiding a column in the table. 

Screenshot 2024-12-16 at 9 11 38 PM

This is caused by the collection sizing not being updated correctly which causes [this](https://github.com/liferay/clay/blob/961c6715dfbc08da721fb1b8c97033bcd450958c/packages/clay-core/src/table/Row.tsx#L247) to evaluate to true when it shouldn't. As a result an extra cell is added to the body that is not in the header.

This will be fixed by: https://github.com/liferay/clay/pull/5903

### CODE REVIEW

**Review by markocikos — APPROVED** [review]
@ethib137 LGTM! Couple of notes:
- Inline editing, as far as I know, it not used anywhere is DXP. It is an unfinished feature in FDS, abandoned long time ago. We have an epic to implement it eventually, so I'm glad you are taking it for consideration.
- Mechanism of persisting visible columns is something we plan to completely rewrite, as a part of custom views and/or statefull URL. So any tweak or bugfix on current solution, even if it is not the most elegant solution, is more than fine.
- I'll handle the conflicts with https://github.com/liferay-frontend/liferay-portal/pull/4624. This one should be far more straightforward to push.
- Failures in https://github.com/liferay-frontend/liferay-portal/pull/4625#issuecomment-2551476453 look related.

**Comment by ethib137** [comment]
ci:test:sf

**Comment by ethib137** [comment]
ci:test:sf

**Comment by ethib137** [comment]
ci:test:relevant

**Comment by markocikos** [comment]
@ethib137  Yeah, if review is green and you are ok with final version, feel free to forward.

**Comment by ethib137** [comment]
ci:forward

**Pull request closed without merging**
