### PR TITLE
LPS-121699 Update @liferay/npm-scripts to v33.1.2

### PR DESCRIPTION
**Pull request by wincent**
Release notes are here:

- https://github.com/liferay/liferay-frontend-projects/releases/tag/npm-scripts%2Fv33.1.0
- https://github.com/liferay/liferay-frontend-projects/releases/tag/npm-scripts%2Fv33.1.1
- https://github.com/liferay/liferay-frontend-projects/releases/tag/npm-scripts%2Fv33.1.2

Most notable changes are:

- Updated dependencies, which may produce some small changes or require some small tweaks (I'll apply those on top of this commit).
- Linting and formatting of TypeScript

### CODE REVIEW

**Comment by wincent** [comment]
Draft because I need to actually fix lints and formatting in a small number of files, as well as configure our globs to hit TS files.

**Comment by wincent** [comment]
Taking this out of draft status and running the tests. This is going to conflict with https://github.com/liferay-frontend/liferay-portal/pull/410 (due to the formatting changes) so if that one gets forwarded first I'll rebase this one on top (cc @julien).

**Comment by wincent** [comment]
ci:test:sf

**Comment by wincent** [comment]
ci:test:relevant

**Comment by wincent** [comment]
ci:stop

**Comment by wincent** [comment]
ci:test:sf

**Comment by wincent** [comment]
ci:test:relevant

**Comment by wincent** [comment]
I'd seen [those warnings](https://github.com/liferay-frontend/liferay-portal/pull/415#issuecomment-702820068) but had forgotten that SF treats warnings as errors (fair enough, because otherwise they get ignored). I'll fix those and rebase today.

**Comment by wincent** [comment]
Updated this with the newer version of `npm-scripts`, fixed the remaining warnings (really just suppressed them, because they are subtle and I don't want to break anything), rebased this on top of #410, which has already been forwarded on [here](https://github.com/brianchandotcom/liferay-portal/pull/94760), after rebasing the commits in #410 because they were 3 days old.

If Brian merges that one, I _think_ I can forward this one without the "duplicate" commits being a problem (even though I rebased them on top of current `upstream/master`, I believe Git should be smart enough to ignore them via the magic of `git patch-id`, but I guess we'll see). Ideally, I won't have to rebase and then wait for tests to re-run if I forward after the PR gets cherry-picked.

Going to re-run the tests now.

**Comment by wincent** [comment]
ci:test:sf

**Comment by wincent** [comment]
ci:test:relevant

**Comment by wincent** [comment]
> @wincent They were there from an old implementation that was not using the `render` from `frontend-js-react-web` and were probably left there to take control of the App component for further extensions. As far as I've noticed all around the module and within it, there are no such extensions, external controls and further usages of the component, so I guess it'll make sense to remove it as soon as some refactor of that component takes place. Thanks!

Cool. Thanks for clarifying!

**Comment by wincent** [comment]
I am pretty sure the one "unique failure" reported here is not actually an issue caused by this PR, but seeing as https://github.com/brianchandotcom/liferay-portal/pull/94760 got merged upstream, I am going to do a rebase and retry.

**Comment by wincent** [comment]
ci:forward

**Comment by wincent** [comment]
ci:test:bundle

**Comment by wincent** [comment]
Different "unique" failure this time, which I also expect is nothing to do with this PR. Here are the two runs:

- https://github.com/liferay-frontend/liferay-portal/pull/415#issuecomment-703721661
- https://github.com/liferay-frontend/liferay-portal/pull/415#issuecomment-703830417

cc @PablitoBonito and @john-co

I'm going to rebase just to make sure this isn't getting stale and keep retrying.

**Comment by wincent** [comment]
ci:forward

**Comment by wincent** [comment]
ci:test:bundle

**Comment by john-co** [comment]
Hi @wincent, 
I took a look at the two "unique" failures, and agree they seem unrelated.
- The Upgrade test looks like a flaky issue, possibly related to https://issues.liferay.com/browse/LPS-121255. cc/ @vicnate5 could you confirm if that's the case? Do we need to turn off test from acceptance so it doesn't affect other PRs? Testray history: https://testray.liferay.com/home/-/testray/cases/1012027238 
- The Staging test seems to be a fluke.

**Comment by wincent** [comment]
Thank you @john-co!

**Pull request closed without merging**
