### PR TITLE
LPS-113257 Fix style page-theme-image-preview

### PR DESCRIPTION
**Pull request by eduardoallegrini**
Markup update following the Clay specification https://clayui.com/docs/components/card.html#images

**Before:**

Screenshot 2020-07-20 at 17 30 57

**After:**

Screenshot 2020-07-20 at 17 30 35

### CODE REVIEW

**Comment by eduardoallegrini** [comment]
ci:test:sf

**Comment by eduardoallegrini** [comment]
ci:test:relevant

**Comment by carloslancha** [comment]
Can't we use clay card tag here?

**Comment by eduardoallegrini** [comment]
@carloslancha do you know if the card-taglib has been updated?  I can't find it in the [epic](https://issues.liferay.com/browse/LPS-112371) or in [clay](https://clayui.com/docs/components/card.html)

**Comment by carloslancha** [comment]
@eduardoallegrini looks like it's not been updated yet, so the answer is "No, we can't use it" xD

**Comment by carloslancha** [comment]
LGTM

**Comment by eduardoallegrini** [comment]
ci:forward

**Pull request closed without merging**
