### PR TITLE
LPS-169150 | master

### PR DESCRIPTION
**Pull request by rolandpakai**
Hi Team,

could you please review my fix?

**Issue description:**
Customer noticed that when Google Analytics is enabled, the requests to google have a wrong dp (document path) parameter, which does not comply with the description at https://developers.google.com/analytics/devguides/collection/protocol/v1/parameters : "The path portion of the page URL. Should begin with '/'."
This parameter always includes the host as well, when accessing pages through the navigation menu.

**Steps to reproduce:**
1. Go to Site Settings for the default site, Configuration/Analytics and write your GA tracking ID in the Google Analytics ID field 
2. Add 2 pages to the site: page1 and page2.
3. Open the browser with the inspecting tools (F12), Network tab enabled. Access localhost:8080
4. Filter for "google" in the developer tools below, so you can only see the requests related to google analytics.
5. Click back and forth between page1 and page2 in the navigation menu at the top and each time click below on the created google request and inspect the right side (click on the request on the right side to reveal the parameters)
**Result:** the dp parameter always looks like http://localhost:8080/page1 or http://localhost:8080/page2 (see screenshot)
**Expected:** It should look like /page1 or /page2

**Fix:** Set page value with Liferay.ThemeDisplay.getLayoutRelativeURL()

https://issues.liferay.com/browse/LPS-169150

Thanks, Roland

### CODE REVIEW

**Comment by rolandpakai** [comment]
ci:forward

**Comment by rolandpakai** [comment]
Hi @georgel-pop-lr

could you plesse check my PR and push it forward?

Thanks, Roland

**Comment by georgel-pop-lr** [comment]
> Hi @georgel-pop-lr
> 
> could you plesse check my PR and push it forward?
> 
> Thanks, Roland

Hi @rolandpakai,

I would like to clarify that pulls for master branch are normally not SME responsibility, so we don't need to verify them. In these case, we need to wait for the team to approve it. SME is in charge only for the maintenance branches but not master.

There are special cases when the team asks us to look at a master pull, and then we will.

I hope is clear now.

Regards.

**Review by markocikos — APPROVED** [review]
LGTM!

**Comment by markocikos** [comment]
ci:forward

**Comment by rolandpakai** [comment]
ci:forward

**Comment by rolandpakai** [comment]
Hi @markocikos 

coukd you please push this forward?

Thanks, Roland

**Comment by mateusralv** [comment]
I'm taking a look 🕵🏽  Thanks @markocikos!

**Comment by mateusralv** [comment]
Hi @rolandpakai and @markocikos the failures are not related, safe to forward from QA perspective. 🚀 

[comparison run](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1669662469733&testrayRunIdA=2080608860&testrayRunIdB=2081939932)

Some tests failed only in this PR but were flaky failures, to confirm rode locally and passed 🟢

**Pull request closed without merging**
