### PR TITLE
LPS-177495 | Test Fix for ClayCheckbox#VerifyDefaultUI

### PR DESCRIPTION
**Pull request by abhnerramos**
**Background**
Test shouldn't have sikuli assertion until fix in LRQA-65984. So, sikuli assertions were temporarily removed.

**JIRA Ticket**
https://issues.liferay.com/browse/LPS-177495

### CODE REVIEW

**Comment by abhnerramos** [comment]
@mateusralv

**Comment by mateusralv** [comment]
ci:test:frontend-clay

**Comment by mateusralv** [comment]
ci:test:frontend

**Review by mateusralv — APPROVED** [review]
God Job @abhnerramos!

**Comment by mateusralv** [comment]
The fix works 🎉 The test are passing in CI ([LocalFile.ClayCheckbox#VerifyDefaultUI](https://testray.liferay.com/home/-/testray/case_results/2223750433?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2223747742%26testrayRunId%3D2223749604%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc)) Thanks!

**Comment by mateusralv** [comment]
ci:forward

**Pull request closed without merging**
