### PR TITLE
[7.4-only] LPS-102102, LPS-102114 and LPS-102109 - Remove compat-layer splitter, pager and progress-bars

### PR DESCRIPTION
**Pull request by marcoscv-work**
[7.4-only] - Only master
---
This PR removes:
- Splitter
- Tables
- Progress-bars

From the compatibility layer

--- 

## Previous PR::
https://github.com/liferay-frontend/liferay-portal/pull/580

---

To test the PR:

- Global smoke test along portal, tables, progress-bars, and pager should work fine with some possible visual difference, if we find out a difference, please report ita

### CODE REVIEW

**Comment by marcoscv-work** [comment]
ci:test:sf

**Comment by marcoscv-work** [comment]
ci:test:relevant

**Comment by marcoscv-work** [comment]
ci:test:build

**Comment by marcoscv-work** [comment]
I'm about to cry :_(

cc @john-co

**Comment by jbalsas** [comment]
These failures look indeed unrelated. Let's try one more time and I can forward manually later today if it still is not green and tests look good.

Don't cry @marcoscv-work!!

yourebreathtaking

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by marcoscv-work** [comment]
@john-co any suggestion to go ahead with it?

**Comment by john-co** [comment]
Just started reviewing :)

**Comment by john-co** [comment]
Reviewed. Test failures are unrelated. :heavy_check_mark: 
This can just be manually forwaded.

**[Unrelated]**
- WebContent#ViewWebContentArticleUsages - looks like we ran into two flaky issues cc/ @david-gutierrez-mesa 
screenshot_14


- Upgrade test - seems like a fluke relating to a network connection issue with mysql database cc/ @vicnate5
```
allel] 15:06:28,705 ERROR [main][HikariPool:541] HikariPool-1 - Exception during pool initialization.
 [parallel] com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure
 [parallel] 
 [parallel] The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
 [parallel] 	at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:174)
 [parallel] 	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64)
 [parallel] 	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:836)
 [parallel] 	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:456)
 [parallel] 	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:246)
 [parallel] 	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:197)
 [parallel] 	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:112)
 [parallel] 	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:118)
 [parallel] 	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:358)
 [parallel] 	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201)
 [parallel] 	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:443)
 [parallel] 	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:514)
 [parallel] 	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:111)
 [parallel] 	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:97)
 [parallel] 	at com.liferay.portal.dao.jdbc.util.DBInfoUtil.lambda$getDBInfo$0(DBInfoUtil.java:47)
 [parallel] 	at com.liferay.petra.concurrent.ConcurrentMapperHashMap.lambda$computeIfAbsent$1(ConcurrentMapperHashMap.java:114)
 [parallel] 	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
 [parallel] 	at com.liferay.petra.concurrent.ConcurrentMapperHashMap.computeIfAbsent(ConcurrentMapperHashMap.java:111)
 [parallel] 	at com.liferay.portal.dao.jdbc.util.DBInfoUtil.getDBInfo(DBInfoUtil.java:44)
 [parallel] 	at com.liferay.portal.spring.hibernate.DialectDetector.getDialect(DialectDetector.java:51)
 [parallel] 	at com.liferay.portal.dao.init.DBInitUtil.init(DBInitUtil.java:60)
 [parallel] 	at com.liferay.portal.spring.context.PortalContextLoaderListener.contextInitialized(PortalContextLoaderListener.java:252)
 [parallel] 	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4678)
 [parallel] 	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5139)
 [parallel] 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
 [parallel] 	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:717)
 [parallel] 	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:690)
 [parallel] 	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:705)
 [parallel] 	at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:631)
 [parallel] 	at org.apache.catalina.startup.HostConfig$DeployDescriptor.run(HostConfig.java:1830)
 [parallel] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
 [parallel] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
 [parallel] 	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
 [parallel] 	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112)
 [parallel] 	at org.apache.catalina.startup.HostConfig.deployDescriptors(HostConfig.java:526)
 [parallel] 	at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:425)
 [parallel] 	at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1576)
 [parallel] 	at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:309)
 [parallel] 	at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123)
 [parallel] 	at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:423)
 [parallel] 	at org.apache.catalina.util.LifecycleBase.setState(LifecycleBase.java:366)
 [parallel] 	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:936)
 [parallel] 	at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:841)
 [parallel] 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
 [parallel] 	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1384)
 [parallel] 	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1374)
 [parallel] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
 [parallel] 	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
 [parallel] 	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134)
 [parallel] 	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:909)
 [parallel] 	at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:262)
 [parallel] 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
 [parallel] 	at org.apache.catalina.core.StandardService.startInternal(StandardService.java:421)
 [parallel] 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
 [parallel] 	at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:930)
 [parallel] 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
 [parallel] 	at org.apache.catalina.startup.Catalina.start(Catalina.java:738)
 [parallel] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 [parallel] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 [parallel] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 [parallel] 	at java.lang.reflect.Method.invoke(Method.java:498)
 [parallel] 	at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:342)
 [parallel] 	at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:473)
 [parallel] Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure
 [parallel] 
 [parallel] The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
 [parallel] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
 [parallel] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
 [parallel] 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
 [parallel] 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
 [parallel] 	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
 [parallel] 	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
 [parallel] 	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151)
 [parallel] 	at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:167)
 [parallel] 	at com.mysql.cj.protocol.a.NativeProtocol.negotiateSSLConnection(NativeProtocol.java:334)
 [parallel] 	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.connect(NativeAuthenticationProvider.java:164)
 [parallel] 	at com.mysql.cj.protocol.a.NativeProtocol.connect(NativeProtocol.java:1342)
 [parallel] 	at com.mysql.cj.NativeSession.connect(NativeSession.java:157)
 [parallel] 	at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:956)
 [parallel] 	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:826)
 [parallel] 	... 60 more
 [parallel] Caused by: javax.net.ssl.SSLException: Unsupported record version Unknown-0.0
 [parallel] 	at sun.security.ssl.InputRecord.checkRecordVersion(InputRecord.java:552)
 [parallel] 	at sun.security.ssl.InputRecord.readV3Record(InputRecord.java:565)
 [parallel] 	at sun.security.ssl.InputRecord.read(InputRecord.java:529)
 [parallel] 	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:973)
 [parallel] 	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
 [parallel] 	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
 [parallel] 	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
 [parallel] 	at com.mysql.cj.protocol.ExportControlled.performTlsHandshake(ExportControlled.java:336)
 [parallel] 	at com.mysql.cj.protocol.StandardSocketFactory.performTlsHandshake(StandardSocketFactory.java:188)
 [parallel] 	at com.mysql.cj.protocol.a.NativeSocketConnection.performTlsHandshake(NativeSocketConnection.java:99)
 [parallel] 	at com.mysql.cj.protocol.a.NativeProtocol.negotiateSSLConnection(NativeProtocol.java:325)
 [parallel] 	... 65 more
 [parallel] 15:06:28,771 ERROR [main][PortalContextLoaderListener:130] java.lang.NullPointerException
 [parallel] java.lang.NullPointerException
 [parallel] 	at com.liferay.portal.kernel.servlet.DirectServletRegistryUtil.clearServlets(DirectServletRegistryUtil.java:25)
 [parallel] 	at com.liferay.portal.spring.context.PortalContextLoaderListener.contextDestroyed(PortalContextLoaderListener.java:127)
 [parallel] 	at org.apache.catalina.core.StandardContext.listenerStop(StandardContext.java:4724)
 [parallel] 	at org.apache.catalina.core.StandardContext.stopInternal(StandardContext.java:5395)
 [parallel] 	at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:257)
 [parallel] 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:187)
 [parallel] 	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:717)
 [parallel] 	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:690)
 [parallel] 	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:705)
 [parallel] 	at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:631)
 [parallel] 	at org.apache.catalina.startup.HostConfig$DeployDescriptor.run(HostConfig.java:1830)
 [parallel] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
 [parallel] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
 [parallel] 	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
 [parallel] 	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112)
 [parallel] 	at org.apache.catalina.startup.HostConfig.deployDescriptors(HostConfig.java:526)
 [parallel] 	at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:425)
 [parallel] 	at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1576)
 [parallel] 	at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:309)
 [parallel] 	at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123)
 [parallel] 	at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:423)
 [parallel] 	at org.apache.catalina.util.LifecycleBase.setState(LifecycleBase.java:366)
 [parallel] 	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:936)
 [parallel] 	at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:841)
 [parallel] 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
 [parallel] 	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1384)
 [parallel] 	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1374)
 [parallel] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
 [parallel] 	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
 [parallel] 	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134)
 [parallel] 	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:909)
 [parallel] 	at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:262)
 [parallel] 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
 [parallel] 	at org.apache.catalina.core.StandardService.startInternal(StandardService.java:421)
 [parallel] 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
 [parallel] 	at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:930)
 [parallel] 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
 [parallel] 	at org.apache.catalina.startup.Catalina.start(Catalina.java:738)
 [parallel] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 [parallel] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 [parallel] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 [parallel] 	at java.lang.reflect.Method.invoke(Method.java:498)
 [parallel] 	at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:342)
 [parallel] 	at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:473)
 [parallel] 15:06:28,774 ERROR [main][PortalContextLoaderListener:137] java.lang.NullPointerException
 [parallel] java.lang.NullPointerException
 [parallel] 	at com.liferay.portal.kernel.deploy.hot.HotDeployUtil.reset(HotDeployUtil.java:50)
 [parallel] 	at com.liferay.portal.spring.context.PortalContextLoaderListener.contextDestroyed(PortalContextLoaderListener.java:134)
 [parallel] 	at org.apache.catalina.core.StandardContext.listenerStop(StandardContext.java:4724)
 [parallel] 	at org.apache.catalina.core.StandardContext.stopInternal(StandardContext.java:5395)
 [parallel] 	at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:257)
 [parallel] 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:187)
 [parallel] 	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:717)
 [parallel] 	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:690)
 [parallel] 	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:705)
 [parallel] 	at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:631)
 [parallel] 	at org.apache.catalina.startup.HostConfig$DeployDescriptor.run(HostConfig.java:1830)
 [parallel] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
 [parallel] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
 [parallel] 	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
 [parallel] 	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112)
 [parallel] 	at org.apache.catalina.startup.HostConfig.deployDescriptors(HostConfig.java:526)
 [parallel] 	at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:425)
 [parallel] 	at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1576)
 [parallel] 	at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:309)
 [parallel] 	at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123)
 [parallel] 	at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:423)
 [parallel] 	at org.apache.catalina.util.LifecycleBase.setState(LifecycleBase.java:366)
 [parallel] 	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:936)
 [parallel] 	at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:841)
 [parallel] 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
 [parallel] 	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1384)
 [parallel] 	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1374)
 [parallel] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
 [parallel] 	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
 [parallel] 	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134)
 [parallel] 	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:909)
 [parallel] 	at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:262)
 [parallel] 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
 [parallel] 	at org.apache.catalina.core.StandardService.startInternal(StandardService.java:421)
 [parallel] 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
 [parallel] 	at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:930)
 [parallel] 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
 [parallel] 	at org.apache.catalina.startup.Catalina.start(Catalina.java:738)
 [parallel] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 [parallel] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 [parallel] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 [parallel] 	at java.lang.reflect.Method.invoke(Method.java:498)
 [parallel] 	at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:342)
 [parallel] 	at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:473)
 [parallel] 15:06:28,778 ERROR [main][PortalBeanLocatorUtil:66] BeanLocator is null
```

**Comment by john-co** [comment]
ci:forward

**Comment by john-co** [comment]
It's the end of my day here so I'm running `ci:forward` as a last effort today. If still not work, @marcoscv-work you can go ahead and manually forward to BChan.

Also, what's a good process we have to manually forward this PR to BChan?  I use node gh but that only works for PRs sent to me or local branches. So, if I was to try to fetch this PR then I'd have to retype the description comment and title to preserve that info. So was wondering how reviewers push the PRs up more efficiently.

**Comment by marcoscv-work** [comment]
merged after manual forward:
https://github.com/brianchandotcom/liferay-portal/pull/96710

**Pull request closed without merging**
