### PR TITLE
Giulio Commerce 6905 - With this PR we introduce the fetch to Pins' Rest API in order to GET pins from DB

### PR DESCRIPTION
**Pull request by andrea-ale-sbarra**
resend og this from @garofalog https://github.com/liferay-frontend/liferay-portal/pull/1303

### CODE REVIEW

**Comment by andrea-ale-sbarra** [comment]
ci:forward

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by garofalog** [comment]
ci:reevaluate:1307401_144

**Comment by bryceosterhaus** [comment]
@andrea-ale-sbarra @garofalog, please try to follow our [pull request guidelines](https://github.com/liferay/liferay-frontend-projects/blob/master/guidelines/general/pull_requests.md#when-sending-a-pull-request) for future PRs. It especially helps the review process to have [useful titles and descriptions](https://github.com/liferay/liferay-frontend-projects/blob/master/guidelines/general/pull_requests.md#write-useful-descriptions-and-titles).

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by garofalog** [comment]
ci:test:sf

**Comment by garofalog** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
ci:forward

**Comment by andrea-ale-sbarra** [comment]
ci:forward

**Comment by andrea-ale-sbarra** [comment]
ci:stop

**Comment by andrea-ale-sbarra** [comment]
ci:test:stop

**Comment by andrea-ale-sbarra** [comment]
ci:close

**Pull request closed without merging**
