### PR TITLE
LPS-137330 patch apis

### PR DESCRIPTION
**Pull request by nhpatt**
Add patch endpoints for both Object APIs. Generated implementation works flawlessly.

I noticed that Field tests were ignored so I implemented them.

### CODE REVIEW

**Comment by nhpatt** [comment]
ci:test:relevant

**Review by LuismiBarcos — APPROVED** [review]

**Comment by nhpatt** [comment]
ci:forward

**Comment by brianchandotcom** [comment]
@nhpatt I merged this, but I had to ignore 2 tests.

See 03959b49c8d29bdff44c353e6b8c79c889b64ae1

**Comment by nhpatt** [comment]
-- Merged directly.

**Pull request closed without merging**
