### PR TITLE
LPS-131494 Add RemoveFormat to our simple toolbar as well

### PR DESCRIPTION
**Pull request by antonio-ortega**
Hey guys,

What do you think about this pull request?

In the end, this is a product design decision. Shall we add that button to our toolbar to provide such functionality?

Otherwise, we can add this button only for web content or wherever we want to have it or assume this as a product limitation.

Thanks.

Regards.

/cc @NemethNorbert

### CODE REVIEW

**Comment by wincent** [comment]
cc'ing @ambrinchaudhary and @julien to take a first look, but like you say:

> this is a product design decision

so I expect we might need to ask @dsanz or @drakonux to give us a pointer (either an opinion on the removal in this PR, or a reference to somebody else who we should be asking).

**Comment by drakonux** [comment]
It's ok. The icon is already prepared, thus use the _remove-style_ icon.

Basic Preset
_Basic preset_

**Comment by julien** [comment]
@antonio-ortega LGTM

I don't see why having a "remove format" button on the editor's toolbar would be a bad thing.

**Review by ambrinchaudhary — APPROVED** [review]

**Comment by ambrinchaudhary** [comment]
ci:forward

**Comment by jbalsas** [comment]
Hey, @antonio-ortega, @julien, @ambrinchaudhary, I was going to say that these are pre-defined presets coming from https://docs.google.com/document/d/1I6PbEA11qC_RpriSdMOmc0ohVPLQQCohQXRoqrOr-DE/edit#heading=h.ft1atl74fl2a

For some reason, I see @drakonux just added `Clear Format` to the basic presets, but I don't see a way to track why was that done. @drakonux, could you add some explanation to this? Did you all talk about it and decided to add it? If so, that's some key piece of information that would be good to convey.

Since I'm not sure what was discussed, just adding here that content can usually be pasted without format with `Paste and Match Style (cmd+shift+v)`. Adding an extra button to the simple toolbar will make small editors (sidebars) wrap even more in height because they won't fit in a single line. That's something to be considered since we aren't likely to be able to implement [CKEditor's toolbar wrapping behaviour](https://issues.liferay.com/browse/LPS-121554) anytime soon.

**Comment by NemethNorbert** [comment]
> Hey, @antonio-ortega, @julien, @ambrinchaudhary, I was going to say that these are pre-defined presets coming from https://docs.google.com/document/d/1I6PbEA11qC_RpriSdMOmc0ohVPLQQCohQXRoqrOr-DE/edit#heading=h.ft1atl74fl2a
> 
> For some reason, I see @drakonux just added `Clear Format` to the basic presets, but I don't see a way to track why was that done. @drakonux, could you add some explanation to this? Did you all talk about it and decided to add it? If so, that's some key piece of information that would be good to convey.
> 
> Since I'm not sure what was discussed, just adding here that content can usually be pasted without format with `Paste and Match Style (cmd+shift+v)`. Adding an extra button to the simple toolbar will make small editors (sidebars) wrap even more in height because they won't fit in a single line. That's something to be considered since we aren't likely to be able to implement [CKEditor's toolbar wrapping behaviour](https://issues.liferay.com/browse/LPS-121554) anytime soon.

Pasting with cmd+shift+v within source mode does not resolve the issue, it will past all the Microsoft specific styles and there won't be any way to remove them with the current toolbar setup

**Comment by drakonux** [comment]
> For some reason, I see @drakonux just added `Clear Format` to the basic presets, but I don't see a way to track why was that done. @drakonux, could you add some explanation to this? Did you all talk about it and decided to add it? If so, that's some key piece of information that would be good to convey.
> 
You were requesting to have it, and I've added it. There is no more reason like that. I mean, We don't own a product, so... if you don't see it's useful or needed. Say it, in our opinion it's an option rarely used but as I said... we don't have the information to conclude that.

**Comment by ambrinchaudhary** [comment]
Hey @drakonux, I'm a bit lost now... so you mean... this` Clear Format` button should not be in the basic present by default. Instead, each portlet or whereever it is needed should add it, isn't it?? If you confirm me this, I'll close the pull forwarded to Brian and reopen this so @NemethNorbert or @antonio-ortega can fix it.

**Comment by drakonux** [comment]
> Hey @drakonux, I'm a bit lost now... so you mean... this` Clear Format` button should not be in the basic present by default. 
Exactly.

> Instead, each portlet or wherever it is needed should add it, isn't it?? If you confirm this, I'll close the pull forwarded to Brian and reopen this so @NemethNorbert or @antonio-ortega can fix it.

Yes, you can close the pull, our opinion is that it should be something to added depending on each scenario, we don't manage enough business information to validate this preset change.

**Comment by ambrinchaudhary** [comment]
ci:reopen

**Comment by dsanz** [comment]
> Yes, you can close the pull, our opinion is that it should be something to added depending on each scenario, we don't manage enough business information to validate this preset change.

Fully agree with this. Adding the button to that method also adds the button to a lot of toolbars (phone included). We may consider using toolbar_text_advanced for those use cases instead.

**Comment by jbalsas** [comment]
> Pasting with cmd+shift+v within source mode does not resolve the issue, it will past all the Microsoft specific styles and there won't be any way to remove them with the current toolbar setup

Hey @NemethNorbert, this sounds like a rather exotic workflow. I'm sure this is important to the customer, but we're talking about possibly making the user experience of every customer and every workflow worse to benefit a specific edge case. We should be very conscious about these kind of changes and try to present the alternatives in proper light so the benefits of a fix don't outweigh the cons.

As I see it, there's currently 2 alternatives that might already work for the customer:
- Paste without styles, not in the source code view, then edit in the source code view
- Add the desired button (`Clear Format`) using the [Modifying an Editor's Configuration](https://help.liferay.com/hc/en-us/articles/360017882652-Modifying-an-Editor-s-Configuration)
- Pick a different prest(`text_advanced`) using the [Modifying an Editor's Configuration](https://help.liferay.com/hc/en-us/articles/360017882652-Modifying-an-Editor-s-Configuration)

[Make CKEditor toolbars configurable via settings](https://issues.liferay.com/browse/LPS-130262) is our attempt to make the second option easier (no development) and I think this is proof that we should work on this asap.

**Comment by NemethNorbert** [comment]
Thanks @jbalsas,

It all makes sense, and its very easy to achieve the desired behaviour from the customer side as well. I also closed the ticket as won't fix as its agreed we won't make this change in our base ckeditor configuration.

Thanks,

**Comment by jbalsas** [comment]
Thanks @NemethNorbert ❤️ 

@dsanz, I think we should take this cue to remember to prioritize [Make CKEditor toolbars configurable via settings](https://issues.liferay.com/browse/LPS-130262)! :)

**Comment by dsanz** [comment]
> Thanks @NemethNorbert 
> 
> @dsanz, I think we should take this cue to remember to prioritize [Make CKEditor toolbars configurable via settings](https://issues.liferay.com/browse/LPS-130262)! :)

I've added this discussion to the epic to remind ourselves!

**Pull request closed without merging**
