### PR TITLE
LPS-169908 | Fix to be able to reset values for OpenID Connect

### PR DESCRIPTION
**Pull request by sontruongces**
Hi team,

This is the fix for the [LPS-169908](https://issues.liferay.com/browse/LPS-169908), the original has passed my review at sontruongces#65. Please help me to review and give feedback.

Thanks!
cc: @tototrinh

### CODE REVIEW

**Comment by mateusralv** [comment]
Hi @sontruongces, I took a look at the failures and don’t seem related to your PR 😄 

[comparison run](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1669947087186&testrayRunIdA=2090162416&testrayRunIdB=2091740581)

**Review by markocikos — APPROVED** [review]
@sontruongces Sorry for the extremely long review delay!

The solution is good! I tested, it fixes the issue correctly.

It was surprising to me that the original code does not work. It is a common and valid practice to pass in function name as `onClick` value. The root cause, as it turns out, is our poor implementation of icon tag. By [adding a semicolon](https://github.com/liferay/liferay-portal/blob/master/util-taglib/src/com/liferay/taglib/ui/IconTag.java#L296-L298), JS will always interpret function name as an executable line of code. As this is an ancient legacy tag (8yo code), I don't think it's worth changing the behavior now. We may run into some weird regressions. The proper solution will be to will migrate `<liferay-ui:icon>` to `<clay:icon>`, or to full on React. One day :crossed_fingers:  /cc @dsanz

**Comment by markocikos** [comment]
ci:forward

**Comment by markocikos** [comment]
ci:forward

**Comment by markocikos** [comment]
ci:forward

**Comment by markocikos** [comment]
ci:forward

**Pull request closed without merging**
