### PR TITLE
LPS-124287 Stabilize build until the new webpack release is made

### PR DESCRIPTION
**Pull request by izaera**
This is the server counterpart of https://github.com/liferay/liferay-frontend-projects/pull/375

With these changes we effectively hide our internal support for module loading (`Liferay.require` doesn't exist any more) and tweak `npm-scripts` to generate code for this change.

Once webpack is released, fixing a current bug that prevents the [entire PR](https://github.com/brianchandotcom/liferay-portal/pull/97237) from being merged, I will send a follow up PR.

### CODE REVIEW

**Comment by izaera** [comment]
Note that this will fail the tests until I release version 36.7.0 of `npm-scripts`.

**Comment by izaera** [comment]
I also have to push force an ammend of the [first commit](https://github.com/liferay-frontend/liferay-portal/pull/660/commits/ab091a6f1ac9c4aadf117440057db71a3d3036eb) so that `yarn.lock` is correctly updated.

**Comment by izaera** [comment]
ci:test:sf

**Comment by izaera** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
The changes in `yarn.lock` seemed odd, but since this is green, let's get this through and take a closer look.

**Comment by jbalsas** [comment]
ci:forward

**Comment by izaera** [comment]
The changes in the yarn.lock are due to the big increase in npm-scripts version, I believe. Also I think the current yarn.lock in portal wasn't deduplicated (but I didn't test this hypothesis yesterday).

**Comment by wincent** [comment]
> Also I think the current yarn.lock in portal wasn't deduplicated (but I didn't test this hypothesis yesterday).

Possible... I generally deduplicate any time I do an update, especially if I see big changes in the lock, but I haven't done an update in a while. Haven't looked deeply at the changes but in a quick glance I see a lot of duplicate Clay packages, that in the past have been due to Commerce having divergent deps _and_ source formatter suppressions that hide the divergence.

**Pull request closed without merging**
