### PR TITLE
LPD-15854 Creation Actions testing

### PR DESCRIPTION
**Pull request by chestofwonders**
Issue: https://liferay.atlassian.net/browse/LPD-15854

This task implements testing for creating Creation Actions and test that actions are present in a fragment (both by a single '+' button and a dropdown menu) and are actionable

### CODE REVIEW

**Comment by chestofwonders** [comment]
ci:test:playwright

**Comment by chestofwonders** [comment]
ci:test:playwright

**Review by juanjofgliferay — APPROVED** [review]
LGTM :rocket:

**Comment by chestofwonders** [comment]
ci:forward

**Pull request closed without merging**
