### PR TITLE
LPS-201924 Fix FrontendDataSetFilters#WillRenderAsInitialState functional test

### PR DESCRIPTION
**Pull request by mateusralv**
**JIRA Ticket:**
https://liferay.atlassian.net/browse/LPS-201924

### CODE REVIEW

**Comment by mateusralv** [comment]
ci:test:frontend-data-set

**Comment by mateusralv** [comment]
The fix works in CI 🎉 
[LocalFile.FrontendDataSetFilters#WillRenderAsInitialState](https://testray.liferay.com/home/-/testray/case_results/2466957251?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2466877817%26testrayRunId%3D2466956178%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc)

**Review by CarlosBrichete — APPROVED** [review]
LGTM :)

**Comment by mateusralv** [comment]
ci:forward

**Pull request closed without merging**
