### PR TITLE
[7.4-only]LPS-102102 Fix modal footer style

### PR DESCRIPTION
**Pull request by edalgrin**
Compat-layer:modals removal

### CODE REVIEW

**Comment by edalgrin** [comment]
ci:test:stop

**Comment by edalgrin** [comment]
ci:stop

**Comment by edalgrin** [comment]
ci:test:relevant

**Comment by marcoscv-work** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcoscv-work** [comment]
It looks good to me!!!

image

**Comment by marcoscv-work** [comment]
@zhangyan0701 could you check this one? @edalgrin and I think it's fine, we found no problems in this PR

**Comment by zhangyan0701** [comment]
Hi @marcoscv-work 

From the screenshot in the test report, the Select File modal is smaller, looks like display on mobile device:
after7

Is this some indented change?

**Comment by edalgrin** [comment]
> Hi @marcoscv-work
> 
> **From the screenshot in the test report, the Select File modal in Web Content is smaller, looks like display on mobile device:**
> 
> after7
> 
> Steps:
> 
> 1. Add a Web Content Structure with an image field.
> 2. Add a new Web Content based on the structure.
> 3. Click the Select button in the image field to open the Select File modal.
> 
> On upsteam the modal looks like below:
> upstream

Thanks for the help! I tried to look at it but the bug is generated by the "wrong" structure of the modal. I honestly prefer to wait for the fix rather than add a temporary fix in CSS - I'll keep investigating!

**Comment by edalgrin** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
ci:forward

**Pull request closed without merging**
