### PR TITLE
LPS-187488 - getPathControlPanelSpritemap should return the spritemap from the admin-theme

### PR DESCRIPTION
**Pull request by bryceosterhaus**
Rather than just referencing the clay spritemap, this updates it so that we ensure the returned path is always from the 
admin-theme.

### CODE REVIEW

**Comment by bryceosterhaus** [comment]
ci:test:sf

**Comment by bryceosterhaus** [comment]
ci:stop

**Comment by bryceosterhaus** [comment]
ci:test:sf

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Review by markocikos — APPROVED** [review]
@bryceosterhaus LGTM! :sparkles:

**Comment by mateusralv** [comment]
Hi @bryceosterhaus the failures are not related. 🚀 

[Testray Comparison](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1686933556322&testrayRunIdA=2352439361&testrayRunIdB=2352755387)

**Comment by bryceosterhaus** [comment]
ci:forward:force

**Pull request closed without merging**
