### PR TITLE
LPS-153256 Import translation submit isn't working

### PR DESCRIPTION
**Pull request by boton**
**Issue:** https://issues.liferay.com/browse/LPS-153256

I'm not sure of the cause of losing submit, but digging with @AliciaGarciaGarcia with the git bisect 🪄  help of @adolfopa.

The problem, in this case, is the `events.js` changes on d8046576eb74707930691684a74448cd22224735.

### CODE REVIEW

**Comment by boton** [comment]
ci:test:relevant

**Comment by dsanz** [comment]
@kresimir-coko pls help boton on this

**Comment by boton** [comment]
IMHO I would forward the revert and then calmly analyze the problem.

**Comment by ambrinchaudhary** [comment]
I agree with @boton. Please note that this is marked as a blocker for the release and it is causing several regressions. Thanks!

**Comment by kresimir-coko** [comment]
Yea, @boton @ambrinchaudhary just revert now and I'll reopen the task on my end and try fixing it again soon

**Review by markocikos — APPROVED** [review]

**Comment by markocikos** [comment]
ci:forward

**Pull request closed without merging**
