### PR TITLE
LRQA-80283 | Test Fix for ClassicTheme#CanConfigureLookAndFeelSettingsOnSinglePage

### PR DESCRIPTION
**Pull request by abhnerramos**
**Description**
Element is not present in ClassicTheme#CanConfigureLookAndFeelSettingsOnSinglePage.

**JIRA Ticket**
https://issues.liferay.com/browse/LRQA-80283

### CODE REVIEW

**Comment by abhnerramos** [comment]
ci:stop

**Comment by abhnerramos** [comment]
@mateusralv LGTM! Could you take a look?

**Comment by abhnerramos** [comment]
This forced push was only to rebase with master and avoid conflicts.

**Review by mateusralv — APPROVED** [review]
Great!!!

**Comment by mateusralv** [comment]
ci:forward

**Pull request closed without merging**
