### PR TITLE
LPD-34946 - Update liferay-ckeditor to 4.21.0-liferay.4

### PR DESCRIPTION
**Pull request by bryceosterhaus**

### CODE REVIEW

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Review by markocikos — COMMENTED** [review]
@bryceosterhaus The ckeditor version bump LGTM! I don't quite understand the yarn.lock changes, that's an unrelated cleanup?

**Comment by bryceosterhaus** [comment]
@markocikos good catch. I think my node_modules were generated from an older branch and yarn got confused

**Comment by bryceosterhaus** [comment]
ci:forward

**Pull request closed without merging**
