### PR TITLE
LPS-186659 Add tests for sorting Data Set

### PR DESCRIPTION
**Pull request by JerryAdrianoo**
**Description:**
 Add tests for sorting data set entries.
 
 **Jira Ticket:**
 https://liferay.atlassian.net/browse/LPS-186659

### CODE REVIEW

**Comment by JerryAdrianoo** [comment]
ci:test:frontend-data-set

**Comment by JerryAdrianoo** [comment]
cc: @CarlosBrichete

**Comment by JerryAdrianoo** [comment]
ci:test:frontend-data-set

**Comment by JerryAdrianoo** [comment]
These failures are not related

**Review by CarlosBrichete — APPROVED** [review]

**Comment by JerryAdrianoo** [comment]
ci:forward

**Pull request closed without merging**
