### PR TITLE
LPS-168762 - HR_442 Skip to content link not working on the roles page

### PR DESCRIPTION
**Pull request by ethib137**
Resent PR from https://github.com/liferay-peds/liferay-portal/pull/28

https://issues.liferay.com/browse/LPS-168762

The main issues with skip to content take place in the control panel. When in the control panel portlets are in a maximized state so we can move the main content in this scenario to wrap the portlet. This way the control panel is not included inside the main-content section.

The check in max.ftl to see if it is a control panel layout may look a little odd. This is because it's written in velocity even though the template should be freemarker. This is being incorrectly interpreted as a freemarker template so I've created an issue for that here: https://issues.liferay.com/browse/LPS-183098

It's important to only apply this to control panel since the max.ftl template is also used in the full page application template which does not use the admin theme.

This fix will result in skip to main content taking the user directly to the portlet skipping the control panel as seen in the screenshot:
image

cc: @veroglez @marcoscv-work

### CODE REVIEW

**Comment by ethib137** [comment]
Hey @izaera would you be able to review this PR. Specifically the part that the max.ftl template is being interpreted as velocity instead of freemarker, which is why the if statement looks different. I believe you had worked on migrating our templates from velocity to freemarker so I figured you'd have a good idea if adding this would be problematic. I also created [this ticket](https://issues.liferay.com/browse/LPS-183098) for tracking the issue related to velocity.

**Comment by izaera** [comment]
> I believe you had worked on migrating our templates from velocity to freemarker

@ethib137 nope. I removed the template engine at the low level, but haven't touched the templates ever. Sorry :-(

**Comment by ethib137** [comment]
Hey @izaera , "at the low level" is what I mean. The max.ftl template based on it's name should be interpreted as freemarker but actually it's being interpreted as velocity. IE: [this ticket](https://issues.liferay.com/browse/LPS-183098) It seems that not everything at the low level was converted, right?

**Comment by izaera** [comment]
So, after an [internal conversation with @dsanz](https://liferay.slack.com/archives/CNBG06JS3/p1683643175884459?thread_ts=1683639711.675249&cid=CNBG06JS3), we are OK with this PR being merged, but we will need to migrate the changes in this PR to Freemarker when https://issues.liferay.com/browse/LPS-183098 is implemented.

**Comment by john-co** [comment]
Just started reviewing :)

**Comment by john-co** [comment]
[Related]
[LocalFile.WikiAdmin#CanViewImportedPages ](https://testray.liferay.com/home/-/testray/case_results/2290286470) 
[SecurityUsecase#ViewNoInvokedPortletViaURL](https://testray.liferay.com/home/-/testray/case_results/2291602822)

Error message:
```
Element is not present at "//div[@id='main-content']//section[contains(@id,'portlet')]"
```
Many other tests failing with this error message


Looks like a test fix is needed for the path Portlet#PORTLET_SECTION since the html changed from `<div>` to `<main>`. See screenshot:
screenshot_62


Also Message#INFO_MAIN_CONTENT may need to be updated too for [SecurityUsecase#ViewNoInvokedPortletViaURL](https://testray.liferay.com/home/-/testray/case_results/2291602822)
image

To be thorough with this fix, we may want to also evaluate and update all other paths that target `@id='main-content`. Instead of `//div[@id='main-content']` I'd recommend changing all these poshi paths to be more general like `//*[@id='main-content']`.  If this is a sweeping change across all `@id='main-content'`, a possibly better option could be to replace with  `//main[@id='main-content']` since `main` is a [good semantic html element](https://www.w3schools.com/html/html5_semantic_elements.asp). btw  @ethib137 ,
I've been waiting for more semantic html element usage within portal so it's exciting for me to see this change. :+1: :raised_hands: 

image

**Comment by john-co** [comment]
> If this is a sweeping change across all `@id='main-content'`

@ethib137 , could you confirm if that's what the code change would do? It would affect all elements that use `@id='main-content'`?

**Comment by john-co** [comment]
This looks like a possible regression for usecase test [SecurityUsecase#ViewNoInvokedPortletViaURL](https://testray.liferay.com/home/-/testray/case_results/2291602822). Could you double check this @ethib137 ?

screenshot_63

`#if(!$layout.istypecontrolpanel())id="main-content"` and `#end style=` is found in the HTML DOM

**Comment by ethib137** [comment]
Hey @john-co regarding switching from `<div id="main-content" role="main">` to `<main id="main-content">`, we do want to make that switch but I think we should probably add that separately. I updated this commit to keep the div for now, and I've created [this ticket](https://issues.liferay.com/browse/LPS-183110) to make the switch later. Hopefully we can minimize the impact by doing it this way.

**Comment by ethib137** [comment]
> This looks like a possible regression for usecase test [SecurityUsecase#ViewNoInvokedPortletViaURL](https://testray.liferay.com/home/-/testray/case_results/2291602822). Could you double check this @ethib137 ?

Yep, this will force us to wait for another ticket to be fixed first. More details here: https://issues.liferay.com/browse/LPS-168762?focusedCommentId=2906237&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-2906237

**Comment by ethib137** [comment]
ci:test:relevant

**Comment by john-co** [comment]
Just started reviewing :)

**Comment by john-co** [comment]
[Related]
[ExportImport#ExportImportWebContentFolderWithWorkflow](https://testray.liferay.com/home/-/testray/case_results/2299889345) - several other tests fail on this similar issue. `@id=main-content` does not include the `control-menu-container` element. So the poshi path skips the ellipsis icon in the control menu container and clicks on the asset row ellpisis icon instead. And then the test fails on finding Export Import dropdown.

screenshot_64

screenshot_65


Seems like a test fix since it seems more intuitive to exclude the control menu from the main section. I can work on a possible fix to adjust the poshi path/macro.

**Comment by john-co** [comment]
Testing out the fix here: https://github.com/john-co/liferay-portal/pull/501

**Comment by john-co** [comment]
ci:test:relevant

**Comment by john-co** [comment]
ci:test:sf

**Comment by john-co** [comment]
Reviewed relevant test suite. Only [SecurityUsecase#ViewNoInvokedPortletViaURL](https://testray.liferay.com/home/-/testray/case_results/2302009369) is left as an affected test pending fix from [LPS-168762](https://issues.liferay.com/browse/LPS-168762?focusedCommentId=2906237&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-2906237). All other test failures are unrelated. :tada: 

[Testray Comparison](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=3&testrayRunIdB=2301080995&testrayRunIdA=2301998082&statusB=2)

**Comment by izaera** [comment]
PR for LPS-183098 forwarded to Brian -> https://github.com/brianchandotcom/liferay-portal/pull/134767

**Comment by ethib137** [comment]
Updated with a freemarker if statement thanks to @izaera 's change.

**Comment by ethib137** [comment]
ci:test:sf

**Comment by ethib137** [comment]
ci:test:relevant

**Comment by john-co** [comment]
ci:test:relevant

**Comment by john-co** [comment]
ci:test:stable

**Comment by john-co** [comment]
Looks like there's a related startup error:

[Full jenkins log](https://testray.liferay.com/reports/production/logs/2023-05/test-1-37/test-portal-acceptance-pullrequest(master)/11464/functional-smoke-tomcat90-mysql57-jdk8_stable/0/0/jenkins-console.txt.gz?authuser=0)

```
[beanshell] 2023-05-15 20:39:36.928 ERROR [main][runtime:59] Error executing FreeMarker template
[beanshell] freemarker.core.InvalidReferenceException: The following has evaluated to null or missing:
[beanshell] ==> layout  [in template "null_STANDARD_max" at line 1, column 32]
[beanshell] 
[beanshell] ----
[beanshell] Tip: If the failing expression is known to legally refer to something that's sometimes null or missing, either specify a default value like myOptionalVar!myDefault, or use <#if myOptionalVar??>when-present<#else>when-missing</#if>. (These only cover the last step of the expression; to cover the whole expression, use parenthesis: (myOptionalVar.foo)!myDefault, (myOptionalVar.foo)??
[beanshell] ----
[beanshell] 
[beanshell] ----
[beanshell] FTL stack trace ("~" means nesting-related):
[beanshell] 	- Failed at: #if !layout.isTypeControlPanel()  [in template "null_STANDARD_max" at line 1, column 26]
[beanshell] ----
[beanshell] 	at freemarker.core.InvalidReferenceException.getInstance(InvalidReferenceException.java:134) ~[?:?]
[beanshell] 	at freemarker.core.UnexpectedTypeException.newDescriptionBuilder(UnexpectedTypeException.java:85) ~[?:?]
[beanshell] 	at freemarker.core.UnexpectedTypeException.<init>(UnexpectedTypeException.java:48) ~[?:?]
[beanshell] 	at freemarker.core.NonHashException.<init>(NonHashException.java:49) ~[?:?]
[beanshell] 	at freemarker.core.Dot._eval(Dot.java:48) ~[?:?]
[beanshell] 	at freemarker.core.Expression.eval(Expression.java:101) ~[?:?]
[beanshell] 	at freemarker.core.MethodCall._eval(MethodCall.java:55) ~[?:?]
[beanshell] 	at freemarker.core.Expression.eval(Expression.java:101) ~[?:?]
[beanshell] 	at freemarker.core.Expression.evalToBoolean(Expression.java:179) ~[?:?]
[beanshell] 	at freemarker.core.Expression.evalToBoolean(Expression.java:165) ~[?:?]
[beanshell] 	at freemarker.core.NotExpression.evalToBoolean(NotExpression.java:34) ~[?:?]
[beanshell] 	at freemarker.core.ConditionalBlock.accept(ConditionalBlock.java:48) ~[?:?]
[beanshell] 	at freemarker.core.Environment.visit(Environment.java:331) ~[?:?]
[beanshell] 	at freemarker.core.Environment.visit(Environment.java:337) ~[?:?]
[beanshell] 	at freemarker.core.Environment.process(Environment.java:310) ~[?:?]
[beanshell] 	at freemarker.template.Template.process(Template.java:383) ~[?:?]
[beanshell] 	at com.liferay.portal.template.freemarker.internal.FreeMarkerTemplate.lambda$processTemplate$0(FreeMarkerTemplate.java:157) ~[?:?]
[beanshell] 	at com.liferay.portal.template.freemarker.internal.FreeMarkerManager.render(FreeMarkerManager.java:382) ~[?:?]
[beanshell] 	at com.liferay.portal.template.freemarker.internal.FreeMarkerTemplate.processTemplate(FreeMarkerTemplate.java:144) ~[?:?]
[beanshell] 	at com.liferay.portal.template.engine.BaseTemplate.processTemplate(BaseTemplate.java:126) ~[?:?]
[beanshell] 	at com.liferay.portal.service.impl.LayoutTemplateLocalServiceImpl._getColumns(LayoutTemplateLocalServiceImpl.java:518) ~[portal-impl.jar:?]
[beanshell] 	at com.liferay.portal.service.impl.LayoutTemplateLocalServiceImpl.readLayoutTemplate(LayoutTemplateLocalServiceImpl.java:390) ~[portal-impl.jar:?]
[beanshell] 	at com.liferay.portal.service.impl.LayoutTemplateLocalServiceImpl._readLayoutTemplates(LayoutTemplateLocalServiceImpl.java:589) ~[portal-impl.jar:?]
[beanshell] 	at com.liferay.portal.service.impl.LayoutTemplateLocalServiceImpl.init(LayoutTemplateLocalServiceImpl.java:261) ~[portal-impl.jar:?]
[beanshell] 	at com.liferay.portal.service.impl.LayoutTemplateLocalServiceImpl.init(LayoutTemplateLocalServiceImpl.java:248) ~[portal-impl.jar:?]
[beanshell] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
[beanshell] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_121]
[beanshell] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
[beanshell] 	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
[beanshell] 	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:50) ~[portal-impl.jar:?]
[beanshell] 	at com.liferay.portal.spring.aop.AopInvocationHandler.invoke(AopInvocationHandler.java:49) ~[portal-impl.jar:?]
[beanshell] 	at com.sun.proxy.$Proxy209.init(Unknown Source) ~[?:?]
[beanshell] 	at com.liferay.portal.kernel.service.LayoutTemplateLocalServiceUtil.init(LayoutTemplateLocalServiceUtil.java:84) ~[portal-kernel.jar:?]
[beanshell] 	at com.liferay.portal.internal.servlet.MainServlet.lambda$_initLayoutTemplates$2(MainServlet.java:801) ~[portal-impl.jar:?]
[beanshell] 	at com.liferay.portal.kernel.module.util.ServiceLatch$CapturingServiceTrackerCustomizer.addingService(ServiceLatch.java:121) [portal-kernel.jar:?]
[beanshell] 	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:943) [org.eclipse.osgi.jar:?]
[beanshell] 	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:1) [org.eclipse.osgi.jar:?]
[beanshell] 	at org.osgi.util.tracker.AbstractTracked.trackAdding(AbstractTracked.java:256) [org.eclipse.osgi.jar:?]
[beanshell] 	at org.osgi.util.tracker.AbstractTracked.trackInitial(AbstractTracked.java:183) [org.eclipse.osgi.jar:?]
[beanshell] 	at org.osgi.util.tracker.ServiceTracker.open(ServiceTracker.java:321) [org.eclipse.osgi.jar:?]
[beanshell] 	at org.osgi.util.tracker.ServiceTracker.open(ServiceTracker.java:264) [org.eclipse.osgi.jar:?]
[beanshell] 	at com.liferay.portal.kernel.module.util.ServiceLatch.openOn(ServiceLatch.java:45) [portal-kernel.jar:?]
[beanshell] 	at com.liferay.portal.internal.servlet.MainServlet._initLayoutTemplates(MainServlet.java:791) [portal-impl.jar:?]
[beanshell] 	at com.liferay.portal.internal.servlet.MainServlet.init(MainServlet.java:311) [portal-impl.jar:?]
[beanshell] 	at javax.servlet.GenericServlet.init(GenericServlet.java:158) [servlet-api.jar:4.0.FR]
[beanshell] 	at com.liferay.shielded.container.internal.proxy.ServletWrapper.init(ServletWrapper.java:91) [com.liferay.shielded.container.impl.jar:?]
[beanshell] 	at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1106) [catalina.jar:9.0.73]
[beanshell] 	at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:963) [catalina.jar:9.0.73]
[beanshell] 	at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:4672) [catalina.jar:9.0.73]
[beanshell] 	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:4973) [catalina.jar:9.0.73]
[beanshell] 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) [catalina.jar:9.0.73]
[beanshell] 	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:683) [catalina.jar:9.0.73]
[beanshell] 	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:658) [catalina.jar:9.0.73]
[beanshell] 	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:662) [catalina.jar:9.0.73]
[beanshell] 	at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:689) [catalina.jar:9.0.73]
[beanshell] 	at org.apache.catalina.startup.HostConfig$DeployDescriptor.run(HostConfig.java:1888) [catalina.jar:9.0.73]
[beanshell] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_121]
[beanshell] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_121]
[beanshell] 	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75) [tomcat-util.jar:9.0.73]
[beanshell] 	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112) [?:1.8.0_121]
[beanshell] 	at org.apache.catalina.startup.HostConfig.deployDescriptors(HostConfig.java:582) [catalina.jar:9.0.73]
[beanshell] 	at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:472) [catalina.jar:9.0.73]
[beanshell] 	at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1617) [catalina.jar:9.0.73]
[beanshell] 	at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:318) [catalina.jar:9.0.73]
[beanshell] 	at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123) [catalina.jar:9.0.73]
[beanshell] 	at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:423) [catalina.jar:9.0.73]
[beanshell] 	at org.apache.catalina.util.LifecycleBase.setState(LifecycleBase.java:366) [catalina.jar:9.0.73]
[beanshell] 	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:898) [catalina.jar:9.0.73]
[beanshell] 	at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:795) [catalina.jar:9.0.73]
[beanshell] 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) [catalina.jar:9.0.73]
[beanshell] 	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1332) [catalina.jar:9.0.73]
[beanshell] 	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1322) [catalina.jar:9.0.73]
[beanshell] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_121]
[beanshell] 	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75) [tomcat-util.jar:9.0.73]
[beanshell] 	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134) [?:1.8.0_121]
[beanshell] 	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:871) [catalina.jar:9.0.73]
[beanshell] 	at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:249) [catalina.jar:9.0.73]
[beanshell] 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) [catalina.jar:9.0.73]
[beanshell] 	at org.apache.catalina.core.StandardService.startInternal(StandardService.java:428) [catalina.jar:9.0.73]
[beanshell] 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) [catalina.jar:9.0.73]
[beanshell] 	at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:917) [catalina.jar:9.0.73]
[beanshell] 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) [catalina.jar:9.0.73]
[beanshell] 	at org.apache.catalina.startup.Catalina.start(Catalina.java:772) [catalina.jar:9.0.73]
[beanshell] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
[beanshell] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_121]
[beanshell] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
[beanshell] 	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
[beanshell] 	at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:347) [bootstrap.jar:9.0.73]
[beanshell] 	at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:478) [bootstrap.jar:9.0.73]
[beanshell] 2023-05-15 20:39:36.944 ERROR [main][LayoutTemplateLocalServiceImpl:523] Unable to get layout template columns
[beanshell] com.liferay.portal.kernel.template.TemplateException: Unable to process template null_STANDARD_max
[beanshell] 	at com.liferay.portal.template.engine.BaseTemplate.processTemplate(BaseTemplate.java:131) ~[?:?]
[beanshell] 	at com.liferay.portal.service.impl.LayoutTemplateLocalServiceImpl._getColumns(LayoutTemplateLocalServiceImpl.java:518) ~[portal-impl.jar:?]
```

**Comment by ethib137** [comment]
ci:test:sf

**Comment by ethib137** [comment]
ci:test:relevant

**Comment by ethib137** [comment]
ci:test:relevant

**Comment by john-co** [comment]
Reviewed. Test failures are unrelated. :heavy_check_mark: 

Ok to `ci:forward:force` from QA perspective. Pending dev approval.

**Comment by ethib137** [comment]
ci:forward:force

**Comment by john-co** [comment]
ci:forward:force

**Comment by john-co** [comment]
`ci:forward:force` currently not working. Even with the api limit flushed, it will prob not work since our last `ci:test:stable` didn't pass. See https://liferay.slack.com/archives/CL3TWSMHQ/p1684276682600109?thread_ts=1684274303.242689&cid=CL3TWSMHQ for details. 

Will manually forward.

**Comment by john-co** [comment]
manually forwarded in https://github.com/brianchandotcom/liferay-portal/pull/134931

**Pull request closed without merging**
