### PR TITLE
LPS-137900 Do not emit custom element scripts to HTML unless needed

### PR DESCRIPTION
**Pull request by izaera**
Manually tested by [registering a custom element source + widget](https://github.com/liferay-frontend/liferay-portal/pull/1297#issue-700207313) and inspecting the rendered DOM: both the JS and the CSS files are rendered in the `<head>` section of the HTML and only when the widget is present in the page.

### CODE REVIEW

**Comment by izaera** [comment]
ci:test:sf

**Comment by izaera** [comment]
ci:test:relevant

**Comment by nhpatt** [comment]
LGTM :)

**Comment by izaera** [comment]
QA errors seem unrelated.

**Comment by izaera** [comment]
ci:test:relevant

**Comment by izaera** [comment]
ci:forward

**Pull request closed without merging**
