### PR TITLE
LPS-155911 Move ScriptData implementation to OSGi land

### PR DESCRIPTION
**Pull request by izaera**
Follow up of https://github.com/brianchandotcom/liferay-portal/pull/123414

### CODE REVIEW

**Comment by izaera** [comment]
ci:forward

**Comment by mateusralv** [comment]
I'm taking a look 🕵🏽

**Comment by mateusralv** [comment]
Hey @izaera, I analyzed the results and they don’t seem related to your PR 🎉 🟢 

A summary of what I found:

### Flaky failures:

1. com.liferay.blogs.asset.test.BlogsEntryAssetSearchTest
2. LocalFile.PortalSmokeUpgrade#ViewPortalSmokeArchive7413

---

The other failures are also occurring in the master. ([comparison run with master](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1663762445170&testrayRunIdA=1985175907&testrayRunIdB=1985219254))

**Comment by izaera** [comment]
I'll send it manually

**Comment by izaera** [comment]
Sent as https://github.com/brianchandotcom/liferay-portal/pull/123483

**Comment by john-co** [comment]
cc/ @susanchen3 @vicnate5 fyi, upgrade test still flaky and impacting PRs from time to time.

**Pull request closed without merging**
