### PR TITLE
LPD-29352 Migrate CanChangeFilterWithClientExtension to playwright

### PR DESCRIPTION
**Pull request by kresimir-coko**
Jira ticket: https://liferay.atlassian.net/browse/LPD-29352

This test is checking if an apple emoji exists as a content of a cell inside the FDS

### CODE REVIEW

**Comment by kresimir-coko** [comment]
ci:test:frontend

**Comment by kresimir-coko** [comment]
ci:test:playwright

**Comment by kresimir-coko** [comment]
ci:reevaluate:1397401_11318

**Comment by kresimir-coko** [comment]
ci:test:frontend-data-set

**Comment by kresimir-coko** [comment]
ci:report:2179895

**Comment by kresimir-coko** [comment]
ci:report:21694193

**Comment by kresimir-coko** [comment]
ci:test:sf

**Comment by kresimir-coko** [comment]
ci:test:sf

**Comment by kresimir-coko** [comment]
ci:test:frontend-data-set

**Comment by kresimir-coko** [comment]
ci:report:22435703

**Comment by kresimir-coko** [comment]
No unique failures, waiting for review and then will manually forward

**Review by markocikos — APPROVED** [review]
@kresimir-coko LGTM! :green_heart:

**Comment by kresimir-coko** [comment]
ci:forward

**Pull request closed without merging**
