### PR TITLE
LPS-125356 - Update clayui/* dependencies

### PR DESCRIPTION
**Pull request by bryceosterhaus**
Updates:
 - @clayui/alert@3.5.1
 - @clayui/autocomplete@3.2.4
 - @clayui/breadcrumb@3.3.4
 - @clayui/card@3.6.4
 - @clayui/color-picker@3.4.4
 - @clayui/css@3.23.0
 - @clayui/data-provider@3.3.8
 - @clayui/date-picker@3.7.0
 - @clayui/drop-down@3.8.4
 - @clayui/form@3.14.2
 - @clayui/label@3.4.1
 - @clayui/layout@3.3.0
 - @clayui/list@3.4.5
 - @clayui/localized-input@3.2.4
 - @clayui/management-toolbar@3.3.0
 - @clayui/modal@3.8.3
 - @clayui/multi-select@3.9.2
 - @clayui/multi-step-nav@3.3.4
 - @clayui/nav@3.4.3
 - @clayui/navigation-bar@3.3.3
 - @clayui/pagination-bar@3.2.4
 - @clayui/pagination@3.3.4
 - @clayui/panel@3.3.3
 - @clayui/popover@3.5.3
 - @clayui/shared@3.4.0
 - @clayui/tabs@3.3.3
 - @clayui/time-picker@3.2.4
 - @clayui/toolbar@3.0.4
 - @clayui/tooltip@3.4.3
 - @clayui/upper-toolbar@3.1.12

### CODE REVIEW

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
ci:test:bundle

**Comment by john-co** [comment]
It looks like from the test screenshots that the buttons in the sidepanel are missing.

Actual:
screenshot_16

Expected:
screenshot_17

Downloading the test bundle to verify manually.

**Comment by john-co** [comment]
Able to reproduce the issue locally, the buttons are not visible by default when first trying to create a WC Template. User has to click twice on the buttonlist toggle to have the buttons appear correctly.

Peek 2021-01-14 11-15

**Comment by john-co** [comment]
cc/ @PablitoBonito

**Comment by bryceosterhaus** [comment]
This is an issue with the new @clayui/panel component. I am fixing it right now and then I will cut a new release and add to this PR

**Comment by bryceosterhaus** [comment]
ci:stop

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
ci:stop

**Comment by bryceosterhaus** [comment]
ci:test:sf

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by john-co** [comment]
Reviewed. Test failures are unrelated. :heavy_check_mark: 
- WorkflowMetrics#VerifyAllItemsFilterFromMetrics - looks like a fluke, looks like the modal wasn't closed before WaitForLiferayEvent.initializeLiferayEventLog();
- modules integration failure seems recently flaky with testGetSiteContentTemplatesPageWithFilterStringEquals cc/ @david-gutierrez-mesa , @Tim-Cao 
https://liferay.spiraservice.net/16/TestCase/230394.aspx

**Comment by john-co** [comment]
ok to manually forward

**Comment by Tim-Cao** [comment]
Hi @john-co  testGetSiteContentTemplatesPageWithFilterStringEquals belongs to Headless team. It's reported https://issues.liferay.com/browse/LRQA-64155

**Comment by bryceosterhaus** [comment]
forwarded at https://github.com/brianchandotcom/liferay-portal/pull/97758

**Pull request closed without merging**
