### PR TITLE
[Only for testing] LPS-184467 Implement a fragment showing FDS View v3 (II)

### PR DESCRIPTION
**Pull request by mateusralv**
### Do not forward!

**Description:**
I am testing SF and other suites in this PR to leave the original cleaner :) 

**Original PR:** https://github.com/liferay-frontend/liferay-portal/pull/3422

---

I've rebased @/markocikos work  on top of current master

Let's see what CI says...

### CODE REVIEW

**Comment by mateusralv** [comment]
ci:test:sf

**Comment by mateusralv** [comment]
ci:test:sf

**Comment by mateusralv** [comment]
ci:test:sf

**Comment by mateusralv** [comment]
ci:test:sf

**Comment by mateusralv** [comment]
ci:test:frontend-data-set

**Comment by mateusralv** [comment]
ci:test:relevant

**Comment by mateusralv** [comment]
ci:test:sf

**Comment by mateusralv** [comment]
ci:test:relevant

**Comment by mateusralv** [comment]
ci:test:frontend-data-set

**Comment by mateusralv** [comment]
ci:help

**Comment by mateusralv** [comment]
ci:test:sf

**Comment by dsanz** [comment]
@markocikos @mateusralv we also have https://github.com/liferay-frontend/liferay-portal/pull/3439. Does it make sense to close this?

**Comment by dsanz** [comment]
see https://github.com/liferay-frontend/liferay-portal/pull/3439

**Comment by markocikos** [comment]
@mateusralv After https://github.com/brianchandotcom/liferay-portal/pull/136264 is merged, please review all tests. I had to fix some odd conflicts on tests, with deletions caused by moves from both sides. I always chose deletion, to be on the safe side. It is likely that some tests were not moved, or some recent additions on moved tests got lost.

**Comment by mateusralv** [comment]
Hi @dsanz I was in doubt as to how these modifications could affect other teams' tests and left it open only to confirm with the result of the `ci:test:acceptance-functional`, 

And @markocikos I think it may give conflict because this PR was merged by Brian 4h ago 🤔 

https://github.com/liferay-frontend/liferay-portal/pull/3418

**Pull request closed without merging**
