### PR TITLE
[TS] LPS-145240 Remove unused look.and.feel.modifiable portal property

### PR DESCRIPTION
**Pull request by orsolyaDekany**
Hi Team,

I removed **"look.and.feel.modifiable"** portal property since it seems to be obsoleted.

The reason why this came up is because of a BLADE upgradeProps command during upgrading which analyzes the old portal-ext.properties and the newly installed 7.x server to show the properties moved to OSGi configuration files or removed from the product. (https://help.liferay.com/hc/en-us/articles/360029147071-Blade-CLI)
The command asks for the property and therefore causing confusion.

Looks like the property was used in [5.1 version](https://files.liferay.com/private/ee/portal/5.1.3/) and was removed from 6.1.
LPS: https://issues.liferay.com/browse/LPS-145240
PR: https://github.com/georgel-pop-lr/liferay-portal/pull/26

Could you please review it?
Thank you!
cc. @georgel-pop-lr

### CODE REVIEW

**Comment by orsolyaDekany** [comment]
ci:test:sf

**Comment by orsolyaDekany** [comment]
ci:test:relevant

**Comment by sergiojimcos** [comment]
Hi @orsolyaDekany! I have reviewed you PR and I can see that all failed tests are unrelated to your changes. One of them is a flaky. For that reason, you can forward it!

**Comment by orsolyaDekany** [comment]
Hi @sergiojimcos , I do not have the authorization to forward a PR. The normal workflow usually is that the PR is forwarded by the reviewer Team after approval. Could you do that please? Thanks again! :)

**Comment by sergiojimcos** [comment]
Hi @orsolyaDekany! I saw again the PR and I have seen that there is a problem with the semantic version, you have to do a Baseline in` portal-kernel` to update the version. For the rest, it is ready to forward!

**Comment by orsolyaDekany** [comment]
Hi @sergiojimcos , looks like this change would cause a major version change meaning that the change could not be backported. In the meantime, I have found an ongoing story ticket that is about removing obsolete properties and this property is one of the task: https://issues.liferay.com/browse/LPS-144661. I am going to follow that up and closing this pull request. Thanks!

**Pull request closed without merging**
