### PR TITLE
LPS-129626 Center CKEditor dialogs

### PR DESCRIPTION
**Pull request by julien**
Related to #934

### CODE REVIEW

**Comment by marcosapmf** [comment]
Just started reviewing :)

**Comment by marcosapmf** [comment]
Hey @julien,
it works perfectly for me. Just adding an evidence below:

https://user-images.githubusercontent.com/59578743/112680290-f50ea080-8e4b-11eb-85a9-ef7bb14e7261.mov

Thank you very much for your help 😃

**Review by jbalsas — COMMENTED** [review]
Hey @julien, since this seems to basically just remove an `if` clause.. could you add an explanation as to why do you think this is safe? Did you check why that condition was added and double-checked if that whatever issue that tried to fix won't be reproducible after this?

My main concern here is that `CKEDITOR.on('dialogDefinition')` events might stick and with several editors on a same page there'll be multiple executions. It might be safe since we only use `event.editor`, so it shouldn't make a difference if we run this code 1, 2 or ♾️ times for the same editor, but we should know how this is going to work.

I think in the past `CKEDITOR` was stickier and not properly cleared on page navigation which could make this more dangerous than it is now... 🤔

**Comment by julien** [comment]
@jbalsas, the only commit related to this I found is this [one](https://github.com/liferay/liferay-portal/commit/a4df2c65a8fb39c139e0e9781078b2092c868f68).

As far as I saw in [Jira](https://issues.liferay.com/browse/LPS-55518), that change was made to organize ckeditor functionality and not concerning a specific bug.

I thought removing this `if` statement was a good idea, because the `ckEditor` variable is created [here](https://github.com/liferay/liferay-portal/blob/4f11164a2f12528a0e502c8b76d942ae1c023f10/modules/apps/frontend-editor/frontend-editor-ckeditor-web/src/main/resources/META-INF/resources/ckeditor.jsp#L488), 
which means that "centering dialogs" would only work with editors created via tags, but not `ClassicEditor` instances.

> My main concern here is that CKEDITOR.on('dialogDefinition') events might stick and with several editors on a same page there'll be multiple executions. 

I've added a `console.count` inside the `dialogDefinition` event listener, to see what would happen and for each editor the (listener) function is executed once and then "cached" like it's [explained here](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR.html#event-dialogDefinition)

(but I'm not entirely sure that this is what you were asking for)

When testing this change in Web Content, where there are several editors, each editor has it's dialogs centered and when navigating away, I observed that the CKEDITOR variable does get cleared, so that looks OK but I'm going to test more.

**Comment by jbalsas** [comment]
Let's take this out of draft and forward it then, @julien !

**Comment by julien** [comment]
ci:test:sf

**Comment by julien** [comment]
ci:test:relevant

**Comment by julien** [comment]
ci:forward

**Pull request closed without merging**
