### PR TITLE
LPD-25320 Fix/quarantine `creator` related tests in DataSetViewFilters.testcase

### PR DESCRIPTION
**Pull request by kresimir-coko**
https://liferay.atlassian.net/browse/LPD-25320

The quarantined tests are failing due to Picklist UI being different, specifically the `+` to add a picklist doesn't directly open a modal but instead offers options.

### CODE REVIEW

**Comment by kresimir-coko** [comment]
ci:test:frontend

**Comment by kresimir-coko** [comment]
ci:report:2567688829

**Comment by kresimir-coko** [comment]
Testray reports no unique failures

**Review by markocikos — APPROVED** [review]
@kresimir-coko LGTM! :sparkles:

**Pull request closed without merging**
