### PR TITLE
LPS-143946 Update netty version to 4.1.72.Final

### PR DESCRIPTION
**Pull request by victorg1991**
From version 4.1.69.Final on, netty-all doesn't include the jars of all the dependant libraries, they are declared as transitive dependencies. This means that we cannot use netty-all as an umbrella package to bring all the jars. 

Because of that, in order to update the netty versions to the 4.1.72.Final, I have change the approach a bit. I have included in the core only the versions needed for the core to work, and, on the other modules, I have included the needed packages as a compileInclude. This way we avoid having to have all the netty modules included in the core.

I'm not super familiar with dependencies stuff, so I'm not sure this is the best approach, but it works. 

Other alternatives may be:
* Declare in the core all the netty packages (There are like 2x packages)
* Maybe create a patched version of the netty and build a fat jar like it used to be? 🤔 

What do you think?

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
😡

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
ci:test:relevant

**Review by javierdearcos — APPROVED** [review]
Thanks a lot @victorg1991 ! I know from my experience these issues are a pain...

Makes total sense. It's a pity we don't have the chance to have the netty-all umbrella anymore but this will also give us more control about what dependencies we add.

**Comment by javierdearcos** [comment]
> I'm not super familiar with dependencies stuff, so I'm not sure this is the best approach, but it works.
>
>Other alternatives may be:
>
>Declare in the core all the netty packages (There are like 2x packages)
>Maybe create a patched version of the netty and build a fat jar like it used to be? 🤔
>What do you think?

I think the solution proposed is enough. Let's start with these dependencies and add more if we need them.

Declare all packages or create our own version seems like too much and something that could give us more problems or work

**Comment by javierdearcos** [comment]
ci:forward

**Comment by victorg1991** [comment]
Those test are related, I'll fix

**Comment by victorg1991** [comment]
Should be fixed now 😇

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
ci:test:relevant

**Review by LuismiBarcos — APPROVED** [review]
Thanks victor for taking care of this 😊 😊 😊

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by javierdearcos** [comment]
Thanks @victorg1991 !! ❤️

**Pull request closed without merging**
