### PR TITLE
LPS-118971 Update alloyeditor package to v2.11.12

### PR DESCRIPTION
**Pull request by wincent**
Release notes:

https://github.com/liferay/alloy-editor/releases/tag/v2.11.12

We never applied the v2.11.11 update to liferay-portal, so you can see the full diff between v2.11.10 and v2.11.12 here:

https://github.com/liferay/alloy-editor/compare/v2.11.10...v2.11.12

Of principal interest, fixes this:

https://issues.liferay.com/browse/LPS-110423

cc @diegonvs

### CODE REVIEW

**Comment by wincent** [comment]
ci:test:sf

**Comment by wincent** [comment]
ci:test:relevant

**Comment by wincent** [comment]
ci:test:bundle

**Comment by wincent** [comment]
Manual test is ✅ 

demo

**Comment by diegonvs** [comment]
ci:test:forward

**Comment by diegonvs** [comment]
ci:forward

**Pull request closed without merging**
