### PR TITLE
LPS-134174 add tests & client project in Object APIs, allow posting dates and small cosmetic improvements

### PR DESCRIPTION
**Pull request by nhpatt**
Several things in this PR related to Object Admin APIs:

- Remove dates in ObjectFields as they don't provide a lot of information
- Add documentation to reflect the basic types that we can create
- Exception Mappers to return BAD_REQUEST instead of SERVER_ERROR because the User always is the problem
- Client and test project
- Small fix to not crash when description is not set in the OpenAPI profile

### CODE REVIEW

**Comment by nhpatt** [comment]
ci:test:sf

**Review by javierdearcos — APPROVED** [review]

**Comment by javierdearcos** [comment]
I don't forward it because it seems to have a conflict in REST Builder class

**Comment by nhpatt** [comment]
ci:forward

**Comment by nhpatt** [comment]
ci:forward

**Comment by nhpatt** [comment]
ci:forward

**Comment by nhpatt** [comment]
ci:test:sf

**Comment by nhpatt** [comment]
ci:stop

**Comment by nhpatt** [comment]
ci:test:relevant

**Comment by nhpatt** [comment]
ci:forward

**Comment by nhpatt** [comment]
ci:forward

**Pull request closed without merging**
