### PR TITLE
LPS-129243 Remove unnecessary metal imports

### PR DESCRIPTION
**Pull request by kresimir-coko**
Fixes [LPS-129243](https://issues.liferay.com/browse/LPS-129243).

Super simple, removes `metal-soy` and `metal-component` dependencies from modules that no longer use them, as listed in the task.

### CODE REVIEW

**Review by wincent — APPROVED** [review]
Nice to see 0.001% less cruft in the codebase. 🎉 

Feel free to forward once you see CI green.

**Comment by jbalsas** [comment]
Let's just manually forward this and let CI breathe a little 👍

**Review by jbalsas — APPROVED** [review]

**Comment by wincent** [comment]
Manual forward here: https://github.com/brianchandotcom/liferay-portal/pull/99993

**Comment by wincent** [comment]
Because you added another commit to the branch @kresimir-coko the manual forward got closed and locked. Going to do it again: https://github.com/brianchandotcom/liferay-portal/pull/99999

**Comment by kresimir-coko** [comment]
Okay @wincent thank you. I didn't see that you guys started forwarding until after I pushed it, as I caught another instance that might be removed (that wasn't on the list in the task), but I'll go over it all tomorrow and see if we missed more.

**Pull request closed without merging**
