### PR TITLE
LPS-182247 | Adding a 'for' function on createDataSet macro

### PR DESCRIPTION
**Pull request by abhnerramos**
**Description**
Adding a 'for' function on createDataSet macro.

**JIRA Ticket**
https://issues.liferay.com/browse/LPS-182247

### CODE REVIEW

**Comment by abhnerramos** [comment]
ci:stop

**Comment by abhnerramos** [comment]
@mateusralv LGTM! Could you take a look, please?

**Comment by abhnerramos** [comment]
ci:test:sf

**Comment by abhnerramos** [comment]
ci:test:frontend

**Comment by abhnerramos** [comment]
ci:test:frontend-data-set

**Comment by mateusralv** [comment]
ci:test:sf

**Comment by mateusralv** [comment]
ci:test:frontend

**Comment by mateusralv** [comment]
ci:test:sf

**Comment by mateusralv** [comment]
ci:test:frontend

**Comment by mateusralv** [comment]
ci:help

**Comment by mateusralv** [comment]
ci:test:sf

**Comment by mateusralv** [comment]
ci:test:sf

**Comment by mateusralv** [comment]
ci:forward

**Pull request closed without merging**
