### PR TITLE
LPS-146978 Update dateFormat in rest builder

### PR DESCRIPTION
**Pull request by LuismiBarcos**
Related ticket [LPS-146978](https://issues.liferay.com/browse/LPS-146978)
___
With this PR the idea is to fix the incompatibility that we have in our java client generated by the REST Builder.
We realized that the problems come when using the java client using Dates formatted with offset. With this new pattern, this should not pass.

### CODE REVIEW

**Comment by LuismiBarcos** [comment]
cc/ @javierdearcos @samanzanedo

**Comment by javierdearcos** [comment]
ci:reevaluate:1267401_1874

**Comment by javierdearcos** [comment]
🤞

**Comment by javierdearcos** [comment]
ci:test:relevant

**Comment by LuismiBarcos** [comment]
Rebased

**Comment by LuismiBarcos** [comment]
ci:test:relevant

**Comment by LuismiBarcos** [comment]
ci:test:sf

**Comment by javierdearcos** [comment]
I'm analyzing the errors and some of them are somehow related to dates. Filtering with dates specifically. Although they seemed flaky.

Maybe it is worth to give them a look before trying again. You can focus on [com.liferay.headless.admin.list.type.resource.v1_0.test.ListTypeDefinitionResourceTest.testGetListTypeDefinitionsPageWithFilterDateTimeEquals](https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=9/24064//testReport/com.liferay.headless.admin.list.type.resource.v1_0.test/ListTypeDefinitionResourceTest/testGetListTypeDefinitionsPageWithFilterDateTimeEquals) and try to run it several times to check if it fails sometimes and the possible cause

**Comment by LuismiBarcos** [comment]
I'm not able to reproduce the failing tests locally. Everything seems to work.
Rebased (again) and trying again 😓

**Comment by LuismiBarcos** [comment]
ci:test:relevant

**Comment by javierdearcos** [comment]
These ones are not related to the PR for sure...

What a pity that it didn't give us the chance to run reevaluate...

**Comment by javierdearcos** [comment]
ci:forward

**Comment by javierdearcos** [comment]
ci:test:relevant

**Comment by javierdearcos** [comment]
ci:test:relevant

**Comment by LuismiBarcos** [comment]
ci:reevaluate:1317401_2371

**Comment by LuismiBarcos** [comment]
Rebase and try again

**Comment by LuismiBarcos** [comment]
ci:test:relevant

**Comment by javierdearcos** [comment]
We need to talk with QA about this one. Check if they can do something or, if not, send it to Brian directly

**Comment by magjed4289** [comment]
Reviewed. Test failures are unrelated. ✔️
Ok to manually forward.

**Comment by javierdearcos** [comment]
Thank you @magjed4289 !

**Pull request closed without merging**
