### PR TITLE
LPS-117833 apply markup changes to components

### PR DESCRIPTION
**Pull request by carloslancha**
This is a massive structure change necessary for the required restyle.

I've removed all the extra classes and the `!important utility classes`

I've created a temporary `<PlaceholderSites>` "component" to work on the style but we'll need it make the original `<Sites>` dynamic following  the [Figma file](https://www.figma.com/file/IWV8DgAZdoyzfHAGLGY5JN/Applications-Menu-Visual-changes-7.3-release?node-id=115%3A4410) specifications

@carloslancha can you help me?

edit: and perhaps divide the whole in sections `<ApplicationsMenuHeader>`, `<ApplicationsMenuFooter>`, etc

---

**Current result:**

Screenshot 2020-07-27 at 18 55 26
Screenshot 2020-07-27 at 18 56 23

/cc @jbalsas @marcoscv-work @victorvalle

### CODE REVIEW

**Comment by carloslancha** [comment]
`current` label won't appear since it should be render only if the site has no `url`, but all of them always have it. Asked to `team-echo` if that's the right logic, waiting for response.

**Comment by carloslancha** [comment]
`current` property added but not working in `staging`

cc @jkappler

**Comment by eduardoallegrini** [comment]
@carloslancha do you think we could forward this and add the fix for the current website later?

**Comment by carloslancha** [comment]
> @carloslancha do you think we could forward this and add the fix for the current website later?

Yes, I'm waiting for Jürgen's ok to the java code :)

**Comment by carloslancha** [comment]
> My only concern is the number recent sites, we didn't define it but I think it should be 3

Didn't see anywhere that defined and, in any case, I think that's something that should be managed in the backend (and do not send more than 3 recent sites if that's the logic)

**Comment by jkappler** [comment]
@eduardoallegrini, @carloslancha, all seems good. If (if) this is merged, I'll send a fix for staging sites tomorrow. If not, I'll add a commit with the fix tomorrow :D

**Comment by carloslancha** [comment]
ci:test:sf

**Comment by carloslancha** [comment]
ci:test:relevant

**Comment by carloslancha** [comment]
ci:stop

**Comment by carloslancha** [comment]
ci:test:sf

**Comment by carloslancha** [comment]
ci:test:relevant

**Comment by carloslancha** [comment]
@john-co could you please take a look? I'm not sure if this os something that needs tonbe updated in the tests or it's something we broke (or both). Thx!!

**Comment by john-co** [comment]
Looks like html structure changed so path locator needs to be updated for Global App > Sites, possibly others?:

```
Element is not present at "//li[contains(@class,'applications-menu-nav-header') and contains(.,'System')]/following-sibling::li//span[normalize-space(text())='Virtual Instances']"
```

cc/ @zhangyan0701 please could you follow up with this?

**Comment by zhangyan0701** [comment]
ci:test:bundle

**Comment by zhangyan0701** [comment]
[Testfix] - Locator ApplicationsMenu#PORTLET need to be updated like John said. All tests failed with this same reason.

Create ticket https://issues.liferay.com/browse/LPS-118265 for it, and will work a fix.

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by zhangyan0701** [comment]
@carloslancha ,

I sent the test fix to you:
https://github.com/carloslancha/liferay-portal/pull/277
This should fix the failed test.

/cc @john-co

**Comment by carloslancha** [comment]
Thanks @zhangyan0701 !

Added that commit to this pr :)

**Comment by carloslancha** [comment]
ci:test:sf

**Comment by carloslancha** [comment]
ci:test:relevant

**Comment by carloslancha** [comment]
ci:forward

**Pull request closed without merging**
