### PR TITLE
LPS-168065 HR_289 SR reads the remove button as "Unlabeled 1 button"

### PR DESCRIPTION
**Pull request by veroglez**
It fixes https://issues.liferay.com/browse/LPS-168065

### CODE REVIEW

**Review by bryceosterhaus — APPROVED** [review]
LGTM!

**Comment by eltonccdantas** [comment]
Hey @veroglez , It is all green now, you may forward it if no other dev review is needed.

**Comment by dsanz** [comment]
ci:forward

**Comment by markocikos** [comment]
ci:forward

**Pull request closed without merging**
