### PR TITLE
[7.4-only] LPS-122449 Replace usages of dom.delegate in layout modules

### PR DESCRIPTION
**Pull request by kresimir-coko**
This PR removes usages of `dom.delegate` from files found inside the `layout` module and replaces those usages with the modern `delegate` utility.

Continuation of #531

### CODE REVIEW

**Comment by kresimir-coko** [comment]
ci:test:relevant

**Review by wincent — APPROVED** [review]
lg2m


cc @liferay-echo (don't know if anybody actually reads these notifs, so will mention some frontend peeps as well: @p2kmgcl, @victorg1991, @sandrodw3, @veroglez)

I'll run `ci:forward` on this in the meantime and hopefully not break anything because CI is green, right? 😁

**Comment by wincent** [comment]
ci:forward

**Comment by wincent** [comment]
Ha. I see we never ran `ci:test:sf` — I give this a 50% chance. 😂

**Comment by kresimir-coko** [comment]
@wincent 
>I give this a 50% chance.

I'll throw in another 50%, so we got 75% at least.

**Comment by victorg1991** [comment]
Changes seems alright :) 
I was afraid about the lack of event.delegateTarget in the new delegate function, but I'm glad to realise it was added recently 👏

**Pull request closed without merging**
