### PR TITLE
LPS-124430 Saves tooltip trigger title on show events

### PR DESCRIPTION
**Pull request by jbalsas**
From the commit itself:

> Before, the change of `title` to `data-restore-title` happened based on the component rendering and state, making it fail to execute under certain conditions.
>
> With this change, anytime the mouse moves over a tooltip trigger, its `title` attribute is moved to a `data-restore-title` attribute avoiding unnecessary rendering of the native tooltip.

The effect can be seen in this screencast and it happened to all tooltips in DXP:

tooltip

**The Problem**
To take over the native tooltips, we move `title` attributes to `data-restore-title` when we enter a trigger element. This attribute is then restored back to `title` when we abandon it.

Previous logic depended on a `useEffect(... [target])` and some internal conditions to execute the `saveTitle` method while `restoreTitle` was running unconditionally when the trigger was abandoned (like to move into the tooltip).

**The Fix**
We simply move the `saveTitle` execution to the initial show trigger. This means there are more DOM changes but the DOM state remains consistent through interactions.

**Test Plan**
- Hover over an icon in DXP and wait until the tooltip shows
- Move the mouse over the tooltip
- Move it back over the icon
- Wait for the native tooltip to appear

**Additional Reference**
Just because I've kept this around all this time, in case someone goes into the implementation and wonders what's with all the craziness... this is the tooltip state diagram:

tooltip

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:stop

**Comment by jbalsas** [comment]
I somehow managed to mangle a one-line commit 🙈

**Comment by jbalsas** [comment]
ci:stop

**Comment by jbalsas** [comment]
ci:test:sf

**Comment by jbalsas** [comment]
ci:test:relevant

**Review by julien — APPROVED** [review]

**Comment by julien** [comment]
@jbalsas the other day between two tasks, I saw this one on the issue board and have the exact same change in a branch

**Comment by julien** [comment]
@jbalsas how did you generate that diagram?

**Comment by jbalsas** [comment]
> @jbalsas the other day between two tasks, I saw this one on the issue board and have the exact same change in a branch

Next time assign the issue to yourself then so we know someone's looking at it! 👀 

> @jbalsas how did you generate that diagram?

I can't quite remember 😂

**Comment by julien** [comment]
> Next time assign the issue to yourself then so we know someone's looking at it! 

That was my idea and I'll do that next time, I just forgot.

**Comment by wincent** [comment]
Top Giphy result for "state machines":

state-machines

**Comment by jbalsas** [comment]
I don't see how that test can be related... let's give this another 2 and a half hours of our lives just to be sure!

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by wincent** [comment]
> I don't see how that test can be related... let's give this another 2 and a half hours of our lives just to be sure!

funny

**Comment by jbalsas** [comment]
@john-co, @PablitoBonito could you see if this related after all? Failed twice in a row, so it's either that or already broken upstream 🤔

**Comment by jbalsas** [comment]
Same issue also seen at https://github.com/liferay-frontend/liferay-portal/pull/636, so forwarding manually!

**Comment by jbalsas** [comment]
Forwarded at https://github.com/brianchandotcom/liferay-portal/pull/97047

**Comment by wincent** [comment]
And https://github.com/liferay-frontend/liferay-portal/pull/632 → https://github.com/brianchandotcom/liferay-portal/pull/97050

**Comment by john-co** [comment]
Reviewed. Test failures are unrelated. :heavy_check_mark: 

Confirmed issue already exists in upstream: https://liferay.spiraservice.net/16/TestCase/191632.aspx

**Pull request closed without merging**
