### PR TITLE
LPS-119597 Sets proper value to hide the widget and prevent it being added to layouts

### PR DESCRIPTION
**Pull request by jbalsas**
Based on [RTL Localization - Adding a Remote Web app portlet creates a loader side panel](https://issues.liferay.com/browse/LPS-119597), discovered that it was possible to add Remote Apps Admin to a layout. That should not be the case.

**The Fix**
Set the proper `category.hidden` value to the `com.liferay.portlet.display-category` property

**Test Plan**
- Edit a Content Page
- Inside the `Fragments & Widgets` section type "remote` or try to locate the "Remote Apps" widget

**Expectation**
The Remote Apps widget (that shows a list of registered remote apps) should not appear and should not be allowed in a layout.

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:test:sf

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
ci:forward

**Comment by wincent** [comment]
Haha, funnily I knew this was possible and had thought it was a bit odd that you'd want to have this in a page, but I figured it was by design. 😂

why-not

**Pull request closed without merging**
