### PR TITLE
LPS-134200 Improve search_container's addRow function to make new cell similar to existing ones

### PR DESCRIPTION
**Pull request by antonio-ortega**
Hey guys,

Since @manuel-rives is OoO today I'm rebasing and resending [his pull request](https://github.com/liferay-frontend/liferay-portal/pull/1172).

Thanks.

Regards.

### CODE REVIEW

**Comment by diegonvs** [comment]
Hey @antonio-ortega, could you bring more details about how to reproduce this issue?

When taking a look on the ticket:

Steps to reproduce:

1. Start Liferay.
2. Deploy some portlet which creates a Search Container including some CSS Class on every column.
3. Add new rows to the search container programatically, i.e., using browser console.

How can We add new rows just using browser's console?

**Comment by antonio-ortega** [comment]
Hi @diegonvs ,

I've just updated LPS' description with all that information so it is available for QA team as well when they need to validate the solution.

Let me know if you need anything else.

Thanks.

Regards.

**Review by kresimir-coko — APPROVED** [review]
Don't see anything wrong with the code, haven't tested it myself.

**Comment by antonio-ortega** [comment]
Hey guys,

It's been a week since we sent this pull request. Could you move it forward or let us know why is being delayed, please?

Thanks.

Regards.

**Comment by bryceosterhaus** [comment]
@antonio-ortega the do you have an example of how or where this new API is used? I don't really have the context for how we use  search_container.js, but in the LPS it says "Columns on new rows contains same CSS Classes for columns" and I'm not seeing where we are actually passing the classes to these columns. The code itself seems fine, but I don't fully understand how it satisfies the LPS, could be due to lack of context of how we use `addRow`

**Comment by manuelRives** [comment]
HI @bryceosterhaus

The clone() instruction is the one that makes the new cells have the same cssClaass as the previous row did. Instead of cloning the template row (wich don't have the cssClasses of the other rows) now it has been modified to clone the previous existing row if it exists.

The usage is basically what appears on the LPS. Just call addRow with the content of the cells of the new row and it will ad the new row to the searchContainer.

**Comment by bryceosterhaus** [comment]
@manuelRives ah I see, that makes sense to me. Sorry, I didn't realize the original PR was linked in the description and could have just read that to get context, my bad!

Forwarding now

**Comment by bryceosterhaus** [comment]
ci:forward

**Pull request closed without merging**
