### PR TITLE
LPS-185909 Empty values ​​in "On after add" and "On after update" actions

### PR DESCRIPTION
**Pull request by markocikos**
### References

- [LPS-185909 Empty values ​​in "On after add" and "On after update" actions](https://issues.liferay.com/browse/LPS-185909)
- Caused by https://github.com/liferay-frontend/liferay-portal/pull/3362

### What is the goal of this PR?

A regression bugfix. The intent in the task that caused the issue was to make the component more robust to invalid inputs, to make it show empty cell instead of breaking. I did not cover one case of a valid input, when value is a React element. This PR fixes it.

This case is only possible when FDS is used as a controlled component. Normally, values are taken from data JSON, built in backend. I guess you can technically build a valid React element object in backend, but that's extremely unlikely, and definitely not something we are doing in DXP.

#### Before PR

See movie in JIRA ticket.

#### After PR

screen

### Steps to reproduce

See steps in JIRA ticket.

### CODE REVIEW

**Comment by markocikos** [comment]
Pushed auto-fix for SF error caused by some unrelated PR directly merged.

**Comment by markocikos** [comment]
ci:test:sf

**Comment by markocikos** [comment]
ci:test:relevant

**Comment by deborasoliveira** [comment]
I'll check the relevant result.

**Review by bryceosterhaus — APPROVED** [review]
LGTM!

**Comment by markocikos** [comment]
ci:forward

**Comment by markocikos** [comment]
ci:forward

**Review by dsanz — APPROVED** [review]

**Comment by markocikos** [comment]
ci:forward

**Pull request closed without merging**
