### PR TITLE
LPS-123965 Migrate instances of AlloyEditor in Commerce commerce-payment-method-money-order

### PR DESCRIPTION
**Pull request by julien**
The `editorName` attribute has been removed from the
`<liferay-ui:input-localized>` tag instance, so that it uses
`_EDITOR_WYSIWYG_DEFAULT`, which is `ckeditor`.

**Test plan**

- Deploy the `commerce-payment-method-money-order` module
- From the global menu, select the **Control Panel** tab
- Navigate to **Sites**
- Create a new site based on the **Speedwell** template
- From the global menu, select the **Commerce** tab
- Under **Store management** select **Channels**
- Select **Commerce Portal**
- Scroll down the **Payment Methods** panel
- Click the **Edit** button next to **Money Order**
- Toggle the **Active** check box
- Click on **Save**
- Select the **Configuration** tab
- Toggle the **Show Message Page** check box

**Before**

**After**

**PS**
Sending this for an internal review, before sending it @liferay-commerce

### CODE REVIEW

**Review by jbalsas — APPROVED** [review]
LGTM!

**Comment by julien** [comment]
ci:stop

**Comment by julien** [comment]
ci:close

**Comment by julien** [comment]
Submitted [here](https://github.com/liferay-commerce/liferay-portal/pull/446)

**Pull request closed without merging**
