### PR TITLE
LPS-123894 - container-fluid-1280 class rename

### PR DESCRIPTION
**Pull request by marcoscv-work**
This PR fixes some alignation problems with the old class 'container-fluid-1280':

image

---

For testing:

- Go to content & data > web content

### CODE REVIEW

**Comment by marcoscv-work** [comment]
ci:test:relevant

**Comment by marcoscv-work** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
❤️

**Review by eduardoallegrini — APPROVED** [review]

**Comment by jbalsas** [comment]
Hey @marcoscv-work, @eduardoallegrini, this seems like a big enough breaking change that we'd want to notify it.

Could you please add an entry in the `BREAKING_CHANGES.md` file with information about what was done and the steps to fix it? (replace the class with `fluid-max-xl` or re-add the compat layer).

**Comment by marcoscv-work** [comment]
relevant worked fine here:
https://github.com/marcoscv-work/liferay-portal/pull/348

**Comment by eduardoallegrini** [comment]
Just started reviewing :)

**Comment by eduardoallegrini** [comment]
ci:test:relevant

**Comment by marcoscv-work** [comment]
@john-co could you help us with this PR? I don't understand why is failing, main commit worked here:
https://github.com/marcoscv-work/liferay-portal/pull/348

**Comment by marcoscv-work** [comment]
we would like to forward as soon as possible because is a visual bug present in 138 pages (actually jsps, I'm not sure how a number of pages are they)

**Comment by eduardoallegrini** [comment]
John is on PTO, maybe @zhangyan0701 or @PablitoBonito could help us?

**Comment by zhangyan0701** [comment]
The failed test LocalFile.NavigationMenuWidgetUsingPageHierarchy#AddChildPage seems a flaky, I see it happened inconsistently  on master upstream and other pull requests.

**Comment by marcoscv-work** [comment]
> The failed test LocalFile.NavigationMenuWidgetUsingPageHierarchy#AddChildPage seems a flaky, I see it happened inconsistently on master upstream and other pull requests.

Thanks @zhangyan0701  !

We are going to rebase and try one more time!

**Comment by marcoscv-work** [comment]
ci:test:relevant

**Comment by marcoscv-work** [comment]
@zhangyan0701 some idea about how to skip this flaky? :-D

**Comment by zhangyan0701** [comment]
@marcoscv-work  Can we manually send to BChan since the failures are unrelated?

**Comment by marcoscv-work** [comment]
ci:forward

**Comment by marcoscv-work** [comment]
ci:stop

**Comment by marcoscv-work** [comment]
Sent directly here: https://github.com/brianchandotcom/liferay-portal/pull/96293

**Pull request closed without merging**
