### PR TITLE
LPS-174054 Add Autom. Test FrontendDataSetAdmin#CanDisplayHeadlessDeliveryAPIResources

### PR DESCRIPTION
**Pull request by eltonccdantas**
FrontendDataSetAdmin#CanDisplayHeadlessDeliveryAPIResources
Test Plan

- **Given** access Datasets admin page
- **When** go to add Datasets
- **Then** displays list of headless resources

**Jira Ticket:**
https://issues.liferay.com/browse/LPS-174054

[Poshi Report](https://drive.google.com/file/d/1Ao24vvF_uMIWbZ8wuLPBRkRYAuEcmBhA/view?usp=share_link)

### CODE REVIEW

**Comment by john-co** [comment]
Looks good to me! :sunglasses:

**Comment by eltonccdantas** [comment]
CC/ @markocikos

**Comment by john-co** [comment]
Closing for now, the test commits would ideally need to be included in the working PR: https://github.com/liferay-frontend/liferay-portal/pull/3031

**Comment by john-co** [comment]
ci:help

**Pull request closed without merging**
