### PR TITLE
[TS] LPP-46273 > LPS-161050 Keep track on the fieldset's fields on rendering

### PR DESCRIPTION
**Pull request by hongvo2308**
Hi,
This is a PR for fixing the issue in the ticket https://issues.liferay.com/browse/LPP-46273
Please review this and leave your comments.
Thank you.

### CODE REVIEW

**Comment by hongvo2308** [comment]
ci:test:bundle

**Comment by susanchen3** [comment]
SF failure 
```
     [exec] apps/data-engine/data-engine-js-components-web/src/main/resources/META-INF/resources/js/core/components/PageRenderer/Page.es.js: BAD
     [exec] Prettier checked 1 file, 1 file has problems
     [exec] 
     [exec] 1 of 3 jobs failed
     [exec] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
     [exec] error Command failed with exit code 1.
     [exec] 
     [exec] > Task :packageRunCheckFormat FAILED
     [exec] Gradle build finished at 2022-08-19 09:37:11.997.
     [exec] 3 actionable tasks: 2 executed, 1 up-to-date
```

**Comment by susanchen3** [comment]
Hey @hongvo2308! 
I think `liferay-bravo` would be better suited to review this PR as `data-engine` falls under them :)

**Comment by hongvo2308** [comment]
Hi @susanchen3 
I have created another PR at https://github.com/liferay-bravo/liferay-portal/pull/6. I will close this.
Thank you.

**Pull request closed without merging**
