### PR TITLE
LPS-136580 Notify tags subscribers when a new Web content, Blog, KB Article, Wiki Page, Message and Document are created

### PR DESCRIPTION
**Pull request by javierdearcos**
I've added a new method in the SubscriptionSender to add the persisted subscribers that are related to the given asset entry.

I've tried to add the logic in the initialize method to be automatic and smarter but it was not possible as there are cases where we are using ids that does not correspond with the resource primary key used in the AssetEntry table.

I think this way the logic is in one place and the usage is clean enough

### CODE REVIEW

**Comment by javierdearcos** [comment]
This comes from Brian comments at https://github.com/brianchandotcom/liferay-portal/pull/105143

Try to explain the advantages and disadvantages to decide the final approach. In my opinion, it might be better to go for the intermediate solution, having an explicit method in SubscriptionSender (At the first time I totally forgot about using LocalServiceUtil so we can have this intermediate solution the first time)

**Comment by nhpatt** [comment]
This sentence is really confusing: 

> Add a new step in the SubscriptionSender initialize method, to add the persisted subscribers related to the AssetEntry linked to the SubscriptionSender's subject.

**Comment by nhpatt** [comment]
This too:

>Due to the notifySubscribers logic inside MBMessageLocalServiceImpl, everytime message is created, the notification is sent twice because it creates to SubscriptionSenders with the same information, one for the message and another to notify the mailing list subscriptors of the MBCategory

**Review by nhpatt — APPROVED** [review]
With those drawbacks I prefer the first solution, let's see what Brian thinks.

**Comment by nhpatt** [comment]
ci:forward

**Comment by javierdearcos** [comment]
I've updated the description trying to clarify the sentences that were confusing

**Comment by javierdearcos** [comment]
ci:test:sf

**Comment by javierdearcos** [comment]
ci:test:relevant

**Comment by javierdearcos** [comment]
I've updated the code with another approach as the old one was giving problems because of old inconsistencies about how the SubscriptionSenders are configured

**Review by nhpatt — APPROVED** [review]
LGTM :D

**Comment by nhpatt** [comment]
ci:forward

**Pull request closed without merging**
