### PR TITLE
LPS-194485 Add arrow to publish button

### PR DESCRIPTION
**Pull request by sofiamendozalr**
See https://github.com/liferay-lima/liferay-portal/pull/4670.

Hello guys! Could you help us? We don't know if attribute name (`iconRight`) is a bit confusing because the position of the icon (left or right) depends on who is the user or the developer. So maybe `sideIcon` is more accurate. What do you think? Thank you all!

### Description
1. When there is an icon and it should be on the right in LR languages and on the left in RL languages (`iconRight==true`) 
iconRightTrue(LR)
iconRightTrue(RL)

2. When there is an icon and it should be on the left in LR languages and on the right in RL languages (`iconRight==false`)
iconRightFalse(LR)
iconRightFalse(RL)

3. When there is no icon
withoutIcon(LR)
withoutIcon(RL)

### CODE REVIEW

**Review by bryceosterhaus — COMMENTED** [review]
The code looks fine to me.

As for naming... It is a little confusing. I would assume that `iconRight` means that there is an icon on the right side when the value is true. However if the value is `false` I would almost expect no icon to be shown at all. Perhaps a better name would be like `swapIconSide`? That infers in both the `true` and `false` case that a icon is still present.

Would that make more sense?

**Comment by sofiamendozalr** [comment]
> The code looks fine to me.
> 
> As for naming... It is a little confusing. I would assume that `iconRight` means that there is an icon on the right side when the value is true. However if the value is `false` I would almost expect no icon to be shown at all. Perhaps a better name would be like `swapIconSide`? That infers in both the `true` and `false` case that a icon is still present.
> 
> Would that make more sense?

Yes, thank you, we think it is the best solution!

**Comment by ambrinchaudhary** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
ci:reevaluate:1397401_7307

**Comment by ambrinchaudhary** [comment]
Could someone from QA confirm if test failures are related to this pull? If not, could this pull be manually forwarded? 
Thanks.

**Comment by ambrinchaudhary** [comment]
ci:test:relevant

**Comment by JerryAdrianoo** [comment]
Hey @ambrinchaudhary, when the ci:test:relevant finishes and returns the testray build, I'll take a look.

**Comment by JerryAdrianoo** [comment]
ci:stop

**Comment by ambrinchaudhary** [comment]
ci:stop

**Comment by ambrinchaudhary** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
ci:test:relevant

**Comment by JerryAdrianoo** [comment]
Hey @sofiamendozalr, I found this issue related with your changes. Can you take a look, please?


```
     [exec] > Task :apps:application-list:application-list-taglib:validateTLD FAILED
     [exec] 
     [exec] > Task :apps:asset:asset-taglib:validateTLD
     [exec] [ant:schemavalidate] /opt/dev/projects/github/liferay-portal/definitions/javaee_5.xsd:742:55: InvalidRegex: Pattern value '($|_|\p{L})(\p{L}|\p{Nd}|_|$)*' is not a valid regular expression. The reported error was: 'Unknown property.' at column '{2}'.
     [exec] > Task :apps:asset:asset-display-page-api:javadoc
     [exec] > Task :apps:asset:asset-display-page-api:jarJavadoc
```

**Comment by ambrinchaudhary** [comment]
> Hey @sofiamendozalr, I found this issue related with your changes. Can you take a look, please?

That doesn't make much sense, that module was not changed and the current changes should not affect it. I'm going to fire again the relevant tests

**Comment by ambrinchaudhary** [comment]
ci:test:relevant

**Comment by JerryAdrianoo** [comment]
> > Hey @sofiamendozalr, I found this issue related with your changes. Can you take a look, please?
> 
> That doesn't make much sense, that module was not changed and the current changes should not affect it. I'm going to fire again the relevant tests

Yes, I also thought it was strange when I analyzed it, but as it was a unique error, I decided to let you know.
Probably some inconsistency in the CI.

**Comment by ambrinchaudhary** [comment]
ci:reevaluate:1267401_11061

**Review by bryceosterhaus — APPROVED** [review]
LGTM!

**Comment by JerryAdrianoo** [comment]
It didn't return the Testray Build. So I'll ci:run relevant again.

**Comment by JerryAdrianoo** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
Now different tests are failing. Could we force forward?

**Comment by JerryAdrianoo** [comment]
@ambrinchaudhary Now the results of the inconsistencies have disappeared! These failures are not related to your changes.
See [Test Comparison.](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1695138024174&testrayRunIdA=2427188346&testrayRunIdB=2427424399)
Please, feel free to forward it.

**Comment by ambrinchaudhary** [comment]
ci:forward:force

**Comment by ambrinchaudhary** [comment]
ci:forward:force

**Comment by ambrinchaudhary** [comment]
ci:stop

**Comment by ambrinchaudhary** [comment]
ci:close

**Comment by ambrinchaudhary** [comment]
I fixed the rebase errors and as this is already approved, it will be handled by Lima in https://github.com/liferay-lima/liferay-portal/pull/4708

**Pull request closed without merging**
