### PR TITLE
LPS-145293 Add support for deployment of custom elements as ES modules

### PR DESCRIPTION
**Pull request by izaera**
⚠⚠ NO NEED TO REVIEW THIS, IT WAS ALREADY REVIEWED IN A PREVIOUS PR ⚠⚠

-----

This adds a new boolean field so that custom element remote apps may be bootstrapped using `<script type="module">` as opposed to plain vanilla JavaScript.

This is needed for:

1. The new JS Toolkit build for Remote Apps that lets developers consume `react` from the portal
2. Angular projects for version >=13 that need this feature
3. Any other deployment that wants to leverage ESM

----

The simplest way to test that this works would be creating a new remote app, checking "Use ES modules":

image

and then looking at how the `<script>` tag is rendered:

image

### CODE REVIEW

**Comment by izaera** [comment]
ci:test:sf

**Comment by magjed4289** [comment]
Just started reviewing :)

**Comment by magjed4289** [comment]
ci:test:sf

**Comment by magjed4289** [comment]
ci:test:sf

**Comment by magjed4289** [comment]
ci:test:relevant

**Comment by izaera** [comment]
ci:test:relevant

**Comment by izaera** [comment]
ci:forward

**Comment by magjed4289** [comment]
ci:reevaluate:1297401_1752

**Comment by magjed4289** [comment]
ci:test:relevant

**Comment by magjed4289** [comment]
Reviewed. Test failures are unrelated. ✔️
Ok to manually forward.

**Comment by magjed4289** [comment]
ci:test:stable

**Comment by magjed4289** [comment]
Reviewed again. Test failures are unrelated. ✔️
Ok to manually forward.

**Comment by izaera** [comment]
Forwarded as https://github.com/brianchandotcom/liferay-portal/pull/113562

**Pull request closed without merging**
