### PR TITLE
LPS-204464 Remove FF for CSPs nonces

### PR DESCRIPTION
**Pull request by izaera**

### CODE REVIEW

**Review by dsanz — APPROVED** [review]
LGTM ;)

**Comment by izaera** [comment]
ci:forward:force

**Comment by izaera** [comment]
ci:forward:force

**Comment by izaera** [comment]
ci:forward:force

**Comment by izaera** [comment]
ci:forward:force

**Comment by izaera** [comment]
ci:test:sf

**Comment by izaera** [comment]
Sending manually to Brian as the SF error is due to some problems with SF and CI.

**Comment by izaera** [comment]
Sent manually as https://github.com/brianchandotcom/liferay-portal/pull/146079

**Pull request closed without merging**
