### PR TITLE
LPS-181120 | Test Fix for FDSEntries#WithSpecialCharacters

### PR DESCRIPTION
**Pull request by abhnerramos**
**Description:**
Create new test Test to create a new dataset (name with special characters)

**Steps**
> Given access to Datasets admin page
> When The user goes to add Datasets
> Then Confirm that the dataset is created

**JIRA Ticket:**
https://issues.liferay.com/browse/LPS-181120

### CODE REVIEW

**Comment by abhnerramos** [comment]
ci:stop

**Comment by abhnerramos** [comment]
ci:test:frontend

**Comment by abhnerramos** [comment]
ci:test:sf

**Comment by abhnerramos** [comment]
ci:test:frontend

**Comment by abhnerramos** [comment]
hey @mateusralv  could you check this? LGTM

**Review by mateusralv — APPROVED** [review]
Good job! Thank you 😄

**Comment by mateusralv** [comment]
ci:forward

**Pull request closed without merging**
