### PR TITLE
LPS-197289 every search-container should have an unique id

### PR DESCRIPTION
**Pull request by thiago-buarqque**
This is a fix for the release blocker [LPS-197289](https://liferay.atlassian.net/browse/LPS-197289).

### What caused the issue
My fix was assuming we did not have two search_containers with the same id in the same page (if so, that sounds like the content in them are the same, so why does it display two times?).

### The fix
I checked with @markocikos and my assumption was correct. Because of that, I simply added an unique id for each search_container rendered in the broken page. As you can see, an id wasn't being created so the default (SearchContainer) id was given.

### Other notes
I'm keeping the same changes that were reverted by Brian to unblock the release, they are correct. They are assuming an unique search_container is being provided. **In case this is wrong, please let me know, I'll just change the fix to generate a unique id in [SearchContainerRowTag.java](https://github.com/liferay/liferay-portal/blob/master/util-taglib/src/com/liferay/taglib/ui/SearchContainerRowTag.java#L314) using `System.currentTimeMillis()` (so every row would have a unique id even if the search-containers have the same id.**

### CODE REVIEW

**Review by markocikos — APPROVED** [review]
@thiago-buarqque LGTM! :sparkles:

**Comment by thiago-buarqque** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
@thiago-buarqque merged to master and U96

**Comment by brianchandotcom** [comment]
@thiago-buarqque compile error at

```
     [echo] Note: Recompile with -Xlint:unchecked for details.
     [echo] /home/me/dev/projects/liferay-portal/modules/apps/staging/staging-bar-web/build/jspc/org/apache/jsp/view_005flayout_005frevisions_jsp.java:522: error: illegal start of expression
     [echo]             _jspx_th_liferay$1ui_search$1container_0.setId( liferayPortletResponse.getNamespace() %>layoutRevisionsSearchContainer_<%= i );
     [echo]                                                                                                    ^
     [echo] /home/me/dev/projects/liferay-portal/modules/apps/staging/staging-bar-web/build/jspc/org/apache/jsp/view_005flayout_005frevisions_jsp.java:522: error: illegal start of expression
     [echo]             _jspx_th_liferay$1ui_search$1container_0.setId( liferayPortletResponse.getNamespace() %>layoutRevisionsSearchContainer_<%= i );
     [echo]                                                                                                                                     ^
     [echo] 2 errors
     [echo] Note: /home/me/dev/projects/liferay-portal/modules/apps/template/template-web/src/main/java/com/liferay/template/web/internal/webdav/TemplateWebDAVStorageImpl.java uses unchecked or unsafe operations.
     [echo] Note: Recompile with -Xlint:unchecked for details.
     [echo] Note: Some input files use or override a deprecated API.
     [echo] Note: Recompile with -Xlint:deprecation for details.
     [echo] Note: Some input files use unchecked or unsafe operations.
     [echo] Note: Recompile with -Xlint:unchecked for details.
     [echo] Note: /home/me/dev/projects/liferay-portal/modules/apps/template/template-service/src/main/java/com/liferay/template/service/persistence/impl/TemplateEntryPersistenceImpl.java uses or overrides a deprecated API.
     [echo] Note: Recompile with -Xlint:deprecation for details.
     [echo] Note: Some input files use unchecked or unsafe operations.
     [echo] Note: Recompile with -Xlint:unchecked for details.
     [echo] Note: /home/me/dev/projects/liferay-portal/modules/apps/translation/translation-service/src/main/java/com/liferay/translation/service/persistence/impl/TranslationEntryPersistenceImpl.java uses or overrides a deprecated API.
     [echo] Note: Recompile with -Xlint:deprecation for details.

```

I fixed it at fc94d18402bb97fe94c234a577421f8e0a2eb37a

**Comment by thiago-buarqque** [comment]
> @thiago-buarqque merged to master and U96

Closing since it was already merged

**Pull request closed without merging**
