### PR TITLE
LPS-182763 Add sheet classes only if not in a pop up

### PR DESCRIPTION
**Pull request by claraizquierdo**
Motivation
=======
[Link to story or ticket](https://issues.liferay.com/browse/LPS-182763)

Proposed Solution
========
Check `!themeDisplay.isStatePopUp() `to add sheet styles to de form content.

Steps to Verify:
----------------

1. Navigation to Design->Fragments
2. In fragment sets click on the three dots icon -> Import
3. Check the form styles

### CODE REVIEW

**Comment by claraizquierdo** [comment]
ci:reopen

**Review by bryceosterhaus — APPROVED** [review]
LGTM!

**Comment by claraizquierdo** [comment]
Thank you @bryceosterhaus ! Should I forward the PR?

**Review by markocikos — APPROVED** [review]
LGTM!

**Comment by markocikos** [comment]
ci:forward

**Pull request closed without merging**
