### PR TITLE
LPS-144879 Include sample clay toast alert message for testing

### PR DESCRIPTION
**Pull request by john-co**
**Description**
Include a sample clay toast alert message which will be followed up with end to end testing.

**Test Plan**
1.  Add Clay Sample Portlet to page
2. Click on `Success Submit` button
3. Assert success toast message displays
4. Click on `Fail Submit` button
5. Assert failed toast message displays
6. Assert success toast message remains present indefinitely
7. Assert fail toast message disappears after 20 seconds

https://user-images.githubusercontent.com/35235266/164793070-869f0d7a-4ef4-4677-a7a6-07df44856157.mp4

**JIRA TICKET**
https://issues.liferay.com/browse/LPS-144879

### CODE REVIEW

**Comment by john-co** [comment]
cc/ @susanchen3 fyi, take some time to study this to become familiar with adding clay component to sample portlet.

cc/ @matuzalemsteles Please review if looks ok.

**Comment by john-co** [comment]
ci:test:frontend-clay:nocompile

**Comment by magjed4289** [comment]
Reviewed. Test failures are unrelated. ✔️
Ok to manually forward.

**Comment by matuzalemsteles** [comment]
Sorry for long delay, I got back from PTO today and I'm seeing this now, this is good to go.

**Comment by john-co** [comment]
ci:forward

**Comment by diegonvs** [comment]
ci:forward

**Comment by john-co** [comment]
will manually forward this since test failures not related

**Comment by john-co** [comment]
manually forwarded https://github.com/brianchandotcom/liferay-portal/pull/116683

**Pull request closed without merging**
