### PR TITLE
LPD-41517 Make CKEditor 5 available to be used in DXP (II)

### PR DESCRIPTION
**Pull request by dsanz**
This is an attempt to unblock the test errors we got in https://github.com/liferay-frontend/liferay-portal/pull/4544, just by loading the RichText component in a different way while testing

### CODE REVIEW

**Comment by dsanz** [comment]
ci:test:stable

**Comment by dsanz** [comment]
cc @markocikos @bryceosterhaus this made [test pass](https://github.com/liferay-frontend/liferay-portal/pull/4581#issuecomment-2501911568), here is the [editor test report](https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1264140/testReport/data-engine.data-engine-taglib.test.js.data-layout-builder.components.rules/editor/). This is hacky but leverages the imported component in the test.

I've not managed to run the test locally though. Pls check on your side and let me know

**Comment by bryceosterhaus** [comment]
@dsanz unfortunately it doesn't resolve the React 18 issues, but glad it can help for CKeditor

**Comment by markocikos** [comment]
ci:test:sf

**Comment by markocikos** [comment]
ci:test:relevant

**Comment by dsanz** [comment]
> @dsanz unfortunately it doesn't resolve the React 18 issues, but glad it can help for CKeditor

In its current form, it shall not. The idea I had in mind is to apply this pattern to the loading of react itself. I'll discuss this with you internally to check

**Comment by dsanz** [comment]
ci:test:relevant

**Comment by dsanz** [comment]
@markocikos not sure if you want to tidy up this a little bit more. Otherwise, feel free to forward

**Comment by markocikos** [comment]
ci:forward

**Pull request closed without merging**
