### PR TITLE
LPS-117363 - Add new two spacers to custom properties

### PR DESCRIPTION
**Pull request by marcoscv-work**
This PR adds new two spacers:

It is related to:
https://github.com/liferay/clay/issues/3521

***and It cannot be merged until this first PR in Clay be ready in portal (next version).***

---

To test it:
Use any spacer class: for example: `mt-10` or `p-10` and check the class make its changes

### CODE REVIEW

**Comment by marcoscv-work** [comment]
ci:test:sf

**Comment by marcoscv-work** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
Screen Shot 2020-07-17 at 18 58 18

I was going to forward this... but no. Please, add description on what's this and why should we merge it! 😉

**Comment by pat270** [comment]
I'm leaving the same update here as I did at https://github.com/liferay/clay/pull/3522.

This adds 18kb to atlas.css, 2kb zipped. Are we good with that size increase? Other than that it's good with me.

**Comment by wincent** [comment]
> Screen Shot 2020-07-17 at 18 58 18
> 
> I was going to forward this... but no.

shame-cube

**Comment by marcoscv-work** [comment]
Monday morning.. open the mac and....

image

**Comment by jbalsas** [comment]
Screen Shot 2020-07-20 at 08 50 43

Lucky we didn't merge it, then :)

**Comment by marcoscv-work** [comment]
yes! sorry!
image

**Comment by jbalsas** [comment]
Converted to Draft to make sure we don't merge it. @marcoscv-work, please use this when creating PRs that are not meant to be merged and turn them into regular PRs and comment on here once they're ready!

**Comment by wincent** [comment]
@marcoscv-work, this is how I imagine you taking that screenshot 😂:

old-camera

**Comment by jbalsas** [comment]
@pat270, @bryceosterhaus, is https://github.com/liferay/clay/issues/3521 in `master` already so we can take this out of Draft and in da product?

**Comment by jbalsas** [comment]
ci:test:sf

**Comment by bryceosterhaus** [comment]
@jbalsas its in master of clay, but that version is still waiting to be merged into portal at https://github.com/liferay-frontend/liferay-portal/pull/181

**Comment by jbalsas** [comment]
Thanks @bryceosterhaus! I'll move this back to Draft then... and mind if I assign it to you so you can forward it when the other one makes it in? Or feel free to merge them both if you still have to work on the other one :)

**Comment by bryceosterhaus** [comment]
@jbalsas Sounds good, once the clay updates go in I'll go ahead and forward this.

**Comment by bryceosterhaus** [comment]
ci:forward

**Pull request closed without merging**
