### PR TITLE
LPS-151951 Misalignment in the notification of an asset type deleted

### PR DESCRIPTION
**Pull request by michaelmdelcavalcanti**
<strong>Issue</strong>: [LPS-151951](https://issues.liferay.com/browse/LPS-151951)

<strong>Description</strong>: Added to component style: display: flex and justify-content: space-between.

<strong>Before</strong>:
image

<strong>After</strong>:
image

### CODE REVIEW

**Comment by michaelmdelcavalcanti** [comment]
ci:test:relevant

**Comment by brunofalc** [comment]
@zhangyan0701 Hey Summer, could you help us to check this PR?

**Comment by zhangyan0701** [comment]
Hi @Hijky, please check the test results, thanks!

**Comment by Hijky** [comment]
@brunofalc 
For my check, It seems not related to your PR.
CC: @zhangyan0701

**Comment by diegonvs** [comment]
Hey, I was trying to see where the classes were defined, but I couldn't find it on [alloy-ui](https://cs.github.com/liferay/liferay-frontend-projects?q=lfr-queue) and [liferay-portal](https://cs.github.com/liferay/liferay-portal?q=lfr-queue). 

Ideally, we shouldn't add these styles inline unless there is an issue related to precedence.

Taking a look at the Styles tab at DevTools, I can't see any definition for:

`lfr-undo-queue` -> https://github.com/liferay-frontend/liferay-portal/blob/16db69fe17b3c35027c53bb062a3e8ce7f9f879f/modules/apps/frontend-js/frontend-js-aui-web/src/main/resources/META-INF/resources/liferay/undo_manager.js#L30

`lfr-queue-empty` -> `https://github.com/liferay-frontend/liferay-portal/blob/16db69fe17b3c35027c53bb062a3e8ce7f9f879f/modules/apps/frontend-js/frontend-js-aui-web/src/main/resources/META-INF/resources/liferay/undo_manager.js#L32`
...

@edalgrin, did we removed/moved aui-web classes during the migration?

-----

To make it less dirty, I suggest to you, @michaelmdelcavalcanti, use Clay functional classes. In your case, you can add:

`d-flex justify-content-between` on `CSS_QUEUE` constant instead of using setStyle. What do you think? :)

**Review by diegonvs — CHANGES_REQUESTED** [review]
To make it less dirty, I suggest to you, @michaelmdelcavalcanti, use Clay functional classes. In your case, you can add:

`d-flex justify-content-between` on `CSS_QUEUE` constant instead of using setStyle. What do you think? :)

**Comment by michaelmdelcavalcanti** [comment]
@diegonvs, It's a valid suggestion, but I don't know if it's the best option, because when adding styles to the CSS_QUEUE constant, the component is always active, instead of appearing only when necessary, I have no knowledge about the cause of this happening.
Resulted with your suggestion:
image
It is possible to observe that even if there is no change to be undone, the component is still active on the screen.
Any other suggestions to fix this?

**Comment by diegonvs** [comment]
> the component is always active
Oh, :'(

What happens if you add these classes to `CSS_ITEMS_LEFT`?

**Comment by michaelmdelcavalcanti** [comment]
@diegonvs, After analyzing the code a bit and carrying out some tests taking into account your suggestions, the only solution that apparently worked the way you wanted is committed to make it easier to explain.
The logic I followed was as follows:
the CSS_QUEUE_SINGLE tag only executed when we had only one undo, not serving many.
I changed the code so that it worked for one or more.
I also removed the lfr-queue-single class, because I didn't see any use in it, if this class has any purpose I can put it again.
I await your feedback for this solution.

**Comment by diegonvs** [comment]
Nice! Let's see what CI says for us. If it returns green We can forward :)

**Comment by diegonvs** [comment]
ci:test:relevant

**Comment by diegonvs** [comment]
ci:test:sf

**Comment by michaelmdelcavalcanti** [comment]
ci:test:relevant

**Comment by diegonvs** [comment]
ci:test:relevant

**Comment by diegonvs** [comment]
ci:test:sf

**Comment by susanchen3** [comment]
Reviewed, [test failures](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=2&testrayRunIdB=1953841169&testrayRunIdA=1953411623&statusB=3) are unrelated :) Looks good to manually forward from QA perspective :rocket:

**Comment by diegonvs** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/122116
Thanks, @michaelmdelcavalcanti and @susanchen3! 💖

**Pull request closed without merging**
