### PR TITLE
LPS-195533 - Validate default language translation and provide default

### PR DESCRIPTION
**Pull request by juanjofgliferay**
Related: 
- Story [LPS-176962](https://liferay.atlassian.net/browse/LPS-176962) Allow users to add translations to the field data
- Task [LPS-195533](https://liferay.atlassian.net/browse/LPS-195533) Identify column name as required

Needs:
- Feature Flag = `LPS-172017` and fresh DB setup

## Problem
Admin users could provide translations to label fields (FDS column headers). However, if they do not provide translation for a given language, when the page loads the Dataset, we will display an empty header.
Objects API does not allow creating required localizable fields.

## Proposed solution
Identify label fields as required and validate the existence of default language translation in the frontend, informing the user that the field is required and providing a fallback when someone request the Dataset in a different language.

Screenshot from 2023-09-11 11-55-37

### CODE REVIEW

**Review by markocikos — COMMENTED** [review]
@juanjofgliferay a small tweak inline. Other than that, looks good!

**Comment by juanjofgliferay** [comment]
ci:test:stable

**Comment by juanjofgliferay** [comment]
ci:test:relevant

**Comment by juanjofgliferay** [comment]
ci:reevaluate:1387401_8945

**Comment by JerryAdrianoo** [comment]
Hey @juanjofgliferay I found some failings related to your changes.
 I'll leave a print and video below showing what happened when I tried to save any changes by editing a field.
 
PR-Bug Photo

------------------------------------------------------------------------------------------------------------------------------------------------------------------------


https://github.com/liferay-frontend/liferay-portal/assets/99041514/7edfb5b4-4de4-4c35-8582-ae94e17c7897


[Testray Comparison](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=2&testrayRunIdB=2422463128&testrayRunIdA=2420185341&statusB=3)

**Comment by JerryAdrianoo** [comment]
@juanjofgliferay I'll send a fix and run ci:relevant again.

**Comment by JerryAdrianoo** [comment]
ci:test:relevant

**Comment by JerryAdrianoo** [comment]
Now ci:test:relevant is ok. I'll run stable again because it didn't return the Testray Build.

**Comment by JerryAdrianoo** [comment]
ci:test:stable

**Comment by JerryAdrianoo** [comment]
@juanjofgliferay Everything is fine. You can forward it. Thanks.
See [Testray Comparison](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1694604742807&testrayRunIdA=2422541312&testrayRunIdB=2423197609)

**Comment by juanjofgliferay** [comment]
ci:forward

**Comment by juanjofgliferay** [comment]
ci:forward:force

**Pull request closed without merging**
