### PR TITLE
LPS-116730 - Update @clayui/modal dependency

### PR DESCRIPTION
**Pull request by bryceosterhaus**
Updating @clayui/modal dependency. This includes the fix of https://github.com/liferay/clay/pull/3515

### CODE REVIEW

**Comment by bryceosterhaus** [comment]
ci:test:sf

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
trying to debug this locally at the moment...

**Comment by bryceosterhaus** [comment]
ci:test:sf

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
ci:test:sf

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
ci:test:sf

**Comment by carloslancha** [comment]
ci:test:relevant

**Comment by wincent** [comment]
Probably overdue to ask for help from QA to interpret these failures. I have no idea why the:

```
Build was aborted
```

keeps cropping up, which means I am not sure whether to ask in `#ci` or `#d-quality-assurance` on Slack. cc @john-co @PablitoBonito

**Comment by john-co** [comment]
WorkflowMetrics#ReassignWorkflowInstance looks related. Other test failures seem unrelated. Will ping ci channel for`modules-integration-mysql57-jdk8`

cc/ @zhangyan0701, can you investigate WorkflowMetrics#ReassignWorkflowInstance further?

**Comment by john-co** [comment]
ci:test:bundle

**Comment by john-co** [comment]
the modules-integration-mysql57-jdk8 already has the same `Unsupported field name actions` errors in upstream, so it looks unrelated.

https://test-1-2.liferay.com/job/test-portal-acceptance-upstream-batch(master)/60642/#showFailuresLink

cc/ @kenjiheigel should this have been reported as common failure?

**Comment by zhangyan0701** [comment]
- Test LocalFile.WorkflowMetrics#ReassignWorkflowInstance should be a Test Fix.

 The modal should to be closed first before opening user dropdown menu. I think this is more reasonable than clicking something under the modal when the modal is still present.

Create https://issues.liferay.com/browse/LPS-117984 for this.

**Comment by zhangyan0701** [comment]
Send the Test Fix to @bryceosterhaus :
https://github.com/bryceosterhaus/liferay-portal/pull/75

**Comment by john-co** [comment]
cc/ @rodrigocunhaa please see test fix for WorkflowMetrics test.

**Comment by john-co** [comment]
@zhangyan0701 says that the test passes locally with test fix bryceosterhaus#75.

If this PR is ready, then I recommend manually forwarding this with the test fix to save CI resources. Not worth rerunning another 190+ jobs...

**Comment by bryceosterhaus** [comment]
sent at https://github.com/brianchandotcom/liferay-portal/pull/91925

**Pull request closed without merging**
