### PR TITLE
LPS-116361 Remote Web Apps Admin - Resend

### PR DESCRIPTION
**Pull request by brunobasto**
This is a resend of https://github.com/liferay-frontend/liferay-portal/pull/162 to [apply](https://github.com/liferay-frontend/liferay-portal/commit/d3815b07508951129f1fecdaa614bc49185803ad) some [guidance](https://liferay.slack.com/archives/G3JBR21HA/p1596471604321400?thread_ts=1596197476.296800&cid=G3JBR21HA) from @john-co to keep this out of release but still include in the build process.

### CODE REVIEW

**Comment by brunobasto** [comment]
ci:test:sf

**Comment by brunobasto** [comment]
ci:test:sf

**Comment by john-co** [comment]
Hi @jpince is there something else we're missing to make SF happy? We wanted to make sure a module was not included in release bundle.

**Comment by jpince** [comment]
I would suggest setting bundle = true and using `.lfrbuild-releng-ignore` instead. You get the benefit of additional testing (lpkg-* batches) and you don't have to change the app.bnd when you're ready to release, just delete the `.lfrbuild-releng-ignore` files. This is also better because it will block Brian from publishing the jars to Nexus. I just found an app today that didn't have an app.bnd but was being published in some circumstances.

If you really want to set bundle = false, look in the code for other examples. I'm not sure what the minimum is, you can look at the logic in SF, I think it's in `BNDBundleCheck.java`. My guess is that `Fix-Delivery-Method` and `Suite` need to be blank, maybe `Portal-Required` also needs to be false. 
```
modules/apps (master) $ git grep "Liferay-Releng-Bundle: false"
asset-tags-validator/app.bnd:Liferay-Releng-Bundle: false
bookmarks/app.bnd:Liferay-Releng-Bundle: false
document-library-google-docs/app.bnd:Liferay-Releng-Bundle: false
hello-velocity/app.bnd:Liferay-Releng-Bundle: false
journal-properties-transformer-listener/app.bnd:Liferay-Releng-Bundle: false
microblogs/app.bnd:Liferay-Releng-Bundle: false
my-subscriptions/app.bnd:Liferay-Releng-Bundle: false
portal-mobile-device-detection-fiftyonedegrees/app.bnd:Liferay-Releng-Bundle: false
portal-search-elasticsearch6/app.bnd:Liferay-Releng-Bundle: false
portal-search-solr7/app.bnd:Liferay-Releng-Bundle: false
portal-security-sso-google/app.bnd:Liferay-Releng-Bundle: false
portal-security-sso-ntlm/app.bnd:Liferay-Releng-Bundle: false
portal-security-sso-openid/app.bnd:Liferay-Releng-Bundle: false
push-notifications/app.bnd:Liferay-Releng-Bundle: false
social-bookmarks/app.bnd:Liferay-Releng-Bundle: false
sync/app.bnd:Liferay-Releng-Bundle: false
```
```
modules/apps (master) $ cat asset-tags-validator/app.bnd
Liferay-Releng-App-Description: %liferay-releng-app-description
Liferay-Releng-App-Title: ${liferay.releng.app.title.prefix} Asset Tags Validator
Liferay-Releng-Bundle: false
Liferay-Releng-Category: Utility
Liferay-Releng-Demo-Url:
Liferay-Releng-Deprecated: true
Liferay-Releng-Fix-Delivery-Method:
Liferay-Releng-Labs: true
Liferay-Releng-Marketplace: false
Liferay-Releng-Portal-Required: false
Liferay-Releng-Public: ${liferay.releng.public}
Liferay-Releng-Restart-Required: true
Liferay-Releng-Suite:
Liferay-Releng-Support-Url: http://www.liferay.com
Liferay-Releng-Supported: ${liferay.releng.supported}
```

**Comment by john-co** [comment]
Thanks @jpince !

@brunobasto I'd go with what Jason suggested and create an empty file named .lfrbuild-releng-ignore instead.

**Comment by brunobasto** [comment]
Awesome! Thank you @john-co and @jpince

**Comment by brunobasto** [comment]
ci:test:sf

**Comment by jpince** [comment]
Thanks for bringing this to my attention. I've updated the documentation in https://grow.liferay.com/people/App.bnd to reflect the recommended approach with `.lfrbuild-releng-ignore`.

**Comment by brunobasto** [comment]
ci:test:relevant

**Comment by jpince** [comment]
@john-co @brunobasto @jbalsas don't forget app.properties once this has been merged! Reference: https://liferay.slack.com/archives/C03BTCQBQ/p1595369129175300

cc/ @esanzp

**Comment by brunobasto** [comment]
ci:test:relevant

**Comment by brunobasto** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
Hey @jpince 

> @john-co @brunobasto @jbalsas don't forget app.properties once this has been merged! Reference: https://liferay.slack.com/archives/C03BTCQBQ/p1595369129175300

We actually don't want this released yet... is the `app.properties` still needed? This process is getting more and more cumbersome by the day, it's already hard enough to figure out which files to use for what and which properties to set to add even more 😢 

Is there anything we could do about this? Maybe having all this documented somewhere to use as reference would at least alleviate the pain.

**Comment by wincent** [comment]
Not sure if it is a local quirk of my set-up, but trying to test this one, I don't see it in my portal instance after building/deploying `remote-web-app-web`, `remote-web-app-uad`, `remote-web-app-service`, `remote-web-app-api`, and `frontend-taglib-clay` (ie. the modules touched/added in this PR) with a clean DB. Gogo shell `lb` only shows me this:

    669|Active     |   10|Liferay Remote Web App API (1.0.0)|1.0.0

but not, `Liferay Remote Web App Service`, `Liferay Remote Web App UAD`, `Liferay Remote Web App Web`...

I was going to try the usual trouble-shooting tricks but in the tomcat log I see:

```
com.liferay.portal.kernel.upgrade.UpgradeException: Bundle com.liferay.remote.web.app.service_1.0.0 [1092] has invalid content in indexes.sql:_create unique index IX_4665BCBC on RemoteWebAppEntry (companyId, url[$COLUMN_LENGTH:75$]);_create index IX_6F970604 on RemoteWebAppEntry (name[$COLUMN_LENGTH:75$]);_create index IX_E166F8B9 on RemoteWebAppEntry (uuid_[$COLUMN_LENGTH:75$], companyId); [Sanitized]
```

But, after deleting the DB and restarting, same kind of thing during start-up:

```
2020-08-04 10:15:27.150 ERROR [main][ReleaseManagerOSGiCommands:93] bundle com.liferay.portal.upgrade.impl:4.0.9 (229)[com.liferay.portal.upgrade.internal.release.osgi.commands.ReleaseManagerOSGiCommands(564)] : The activate method has thrown an exception
com.liferay.portal.kernel.upgrade.UpgradeException: Bundle com.liferay.remote.web.app.service_1.0.0 [563] has invalid content in indexes.sql:_create unique index IX_4665BCBC on RemoteWebAppEntry (companyId, url[$COLUMN_LENGTH:75$]);_create index IX_6F970604 on RemoteWebAppEntry (name[$COLUMN_LENGTH:75$]);_create index IX_E166F8B9 on RemoteWebAppEntry (uuid_[$COLUMN_LENGTH:75$], companyId); [Sanitized]
```

**Comment by brunobasto** [comment]
ci:test:sf

**Comment by brunobasto** [comment]
ci:test:relevant

**Comment by wincent** [comment]
@csierra: FYI, this is the "Step 0" we were talking about on the call today. Basically just a registry of apps that can be rendered inside widgets.

Step 1 (now). Client-side JS SDK to allow such a widget rendered in an iframe to communicate with parent liferay-portal instance.

Step 2 (future). Integration with OAuth flow so that remote web app can make requests to portal instance (ie. for server-side rendering); expect the list of granted scopes to be restrictive by default.

Step 3 (future future). Potentially selectively apply "Trusted Apps" flow to remove friction from per-user, per-widget OAuth flows.

cc @jbalsas

**Comment by jbalsas** [comment]
>Step 1 (now). Client-side JS SDK to allow such a widget rendered in an iframe to communicate with parent liferay-portal instance.
>
>Step 2 (future). Integration with OAuth flow so that remote web app can make requests to portal instance (ie. for server-side rendering); expect the list of granted scopes to be restrictive by default.
>
>Step 3 (future future). Potentially selectively apply "Trusted Apps" flow to remove friction from per-user, per-widget OAuth flows.

sealofapproval

**Comment by jpince** [comment]
@jbalsas no, the `app.properties` doesn't need to be committed right away, only before you want to publish/release the app. So here are your options:

Option 1: commit app.properties later
* Benefit: don't have to think about it now
* Risk: If we forget to add app.properties later, we will find out when trying to create a release build. Then, we will have to add app.properties in portal, which means a new build hash with additional commits/risk. Also, I don't have the bandwidth to keep track of every new app, so the product team would need to keep track of this task.

Option 2: commit app.properties now
* Benefit: The app will not be published or released due to the `.lfrbuild-releng-ignore` file. When you are ready to release, you just remove the `.lfrbuild-releng-ignore` file
* Drawback: Writing and keeping track of a ticket now when we're not even ready to release the app.

This is documented in https://grow.liferay.com/people/How+to+add+a+new+app+to+the+release+bundle. I will adapt it to clarify the point I made above. I have drafted the details on the full release process but have not had time to finish it yet. 

I'll make a note to talk to you about this during our Thursday meeting, to get your input on the communication and see what else is needed to help make the process smoother. Thanks for your guys' patience in this.

**Comment by brunobasto** [comment]
fixed JSP compilation issue and force pushed

**Comment by brunobasto** [comment]
ci:test:relevant

**Comment by brunobasto** [comment]
Ok. I think I figured out the problem. Force pushed and fingers crossed this time.

**Comment by brunobasto** [comment]
ci:test:relevant

**Comment by brunobasto** [comment]
ci:test:relevant

**Comment by brunobasto** [comment]
ci:test:relevant

**Comment by brunobasto** [comment]
ci:forward

**Pull request closed without merging**
