### PR TITLE
LCD 26595

### PR DESCRIPTION
**Pull request by allen-ziegenfus**
@bryceosterhaus  similar to https://github.com/liferay-frontend/liferay-portal/pull/3392 this one is also failing to render due to imports - you'll probably cringe at my solution but was just trying to get it to work.

cc: @gamerson

### CODE REVIEW

**Comment by gamerson** [comment]
cc @bryceosterhaus @kevenleone could someone help with a review?

**Comment by bryceosterhaus** [comment]
@allen-ziegenfus see https://github.com/liferay-frontend/liferay-portal/pull/3392#issuecomment-1580421878

We can just disable the rule in all of workspaces

**Comment by ipeychev** [comment]
@bryceosterhaus @kevenleone  Allen will be on PTO till the second week of **July**. We really don't want to wait for a month until he returns, and then to proceed.
Can't we move on with this PR? For example, can't someone of you add the required changes and merge it, please?

**Comment by kevenleone** [comment]
Just starting reviewing :)

**Comment by kevenleone** [comment]
resent: https://github.com/liferay-frontend/liferay-portal/pull/3392#issuecomment-1589947869

**Comment by kevenleone** [comment]
ci:close

**Comment by ipeychev** [comment]
And where was this PR resent? @kevenleone

**Pull request closed without merging**
