### PR TITLE
LPS-122793 Avoid throwing null pointer exception for themes that doesn't have token definition

### PR DESCRIPTION
**Pull request by victorg1991**
A check for null was missing for when the theme doesn't have frontend token definition when generating the default token css variables

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by jbalsas** [comment]
Hey @victorg1991, could you please run `baseline` on this module and update it?

For some reason @izaera made a major increase which is apparently not needed. We have https://github.com/liferay-frontend/liferay-portal/pull/457 to update it to `1.0.0` but this PR seems to ask for `1.1.0`, so maybe we can fix it all here.

Thanks!

**Comment by victorg1991** [comment]
Doing that!

**Comment by victorg1991** [comment]
Done @jbalsas

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by jbalsas** [comment]
Thanks @victorg1991!! ❤️

**Comment by jbalsas** [comment]
@izaera was busy today, and this looks okay-ish enough to me, so I'm going to forward it and we can followup if needed.

**Comment by jbalsas** [comment]
ci:forward

**Comment by izaera** [comment]
:ok_hand:

**Pull request closed without merging**
