### PR TITLE
LPD-25332 - poshi - remove tests covered by Clay and change wording of a test to be more precise

### PR DESCRIPTION
**Pull request by kresimir-coko**
The removed poshi tests are covered by Clay's Autocomplete + MultiSelect tests:
- https://github.com/liferay/clay/blob/master/packages/clay-autocomplete/src/__tests__/IncrementalInteractions.tsx
- https://github.com/liferay/clay/blob/master/packages/clay-multi-select/src/__tests__/IncrementalInteractions.tsx

The renamed test was (before this PR) duplicated for Single and Multiple selection but it was testing if items added to the Picklist would be present in the MultiSelect component

### CODE REVIEW

**Comment by kresimir-coko** [comment]
ci:test:frontend

**Comment by kresimir-coko** [comment]
ci:report:28671921

**Comment by kresimir-coko** [comment]
ci:test:frontend

**Comment by kresimir-coko** [comment]
ci:report:29304720

**Review by markocikos — APPROVED** [review]
@kresimir-coko LGTM! :sparkles: 

image 
:heart_eyes:

**Comment by kresimir-coko** [comment]
ci:report:29304720

**Comment by kresimir-coko** [comment]
No unique failures reported

**Comment by kresimir-coko** [comment]
ci:forward

**Pull request closed without merging**
