### PR TITLE
LPS-170575 | Adjust 'Disappears After 5 Seconds' button

### PR DESCRIPTION
**Pull request by deborasoliveira**
Adjusting the [LPS-170575](https://issues.liferay.com/browse/LPS-170575) button, putting space between words, and adding the button keyword to other `Language.properties` files.

### CODE REVIEW

**Comment by deborasoliveira** [comment]
ci:test:sf

**Comment by deborasoliveira** [comment]
ci:test:frontend

**Comment by deborasoliveira** [comment]
ci:test:frontend

**Comment by john-co** [comment]
Just started reviewing :)

**Comment by john-co** [comment]
nvm, I think you're still working on this. Will set to `draft`, let us know when ready for review.

**Comment by deborasoliveira** [comment]
ci:test:sf

**Comment by deborasoliveira** [comment]
ci:test:frontend

**Comment by deborasoliveira** [comment]
ci:test:sf

**Comment by deborasoliveira** [comment]
ci:test:frontend

**Review by john-co — APPROVED** [review]
Looks good to me! :sunglasses:

**Comment by john-co** [comment]
ci:forward

**Review by mateusralv — APPROVED** [review]

**Comment by mateusralv** [comment]
ci:forward

**Comment by john-co** [comment]
Hi @mateusralv , please manually forward this to BChan.

**Comment by mateusralv** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/129417 🚀

**Pull request closed without merging**
