### PR TITLE
LPS-149398 Support adding icons in dropdown menu tag

### PR DESCRIPTION
**Pull request by DiegoHu97**
Hello, this is a PR related to the story https://issues.liferay.com/browse/LPS-14529, which calls for adding icons to dropdowns (for example: in documents and media). 

For this request, I have created another subtask (LPS-149398) which supports adding icons to the dropdown menu tag.
In the beginning, if you set an icon in the dropdown menu object, it was not rendering the react component. So I have added the property **"symbolLeft"** to the function _normalize_dropdown_items.spreadDataAttributes_. And then, I have changed the name of the function to **"updateItemProps"**. I only have added the property **"symbolLeft"** because for this case we only need the icon to be on the left side. If in the future we need to add a **"symbolRight"**, we can change the function, but we do not need it yet.

Tell me if I have to change something else. 

Thanks!.

### CODE REVIEW

**Review by kresimir-coko — APPROVED** [review]
Simple enough, looks good. I haven't tested it myself, but the code looks good 👍

**Comment by zhangyan0701** [comment]
After comparing the test results with upstream, there is one test failure related:
[LocalFile.ManagementToolbar#MoreActionsButtonRenderQuickActions](https://testray.liferay.com/home/-/testray/case_results/1636422876)

The icon for dropdown item 'Edit' is missing in Clay Sample Portlet:


Then I check the options dropdown items of Web Content, only 'Move' has its icon:


Is this expected behavior? Will the icons for all items be added in the future? As right now it doesn't look very well on UI.

**Comment by DiegoHu97** [comment]
Hello @zhangyan0701, I have revised and fixed the failed test. 
Regarding the Web Content drop-down icons, in this story (https://issues.liferay.com/browse/LPS-145292) you can find the task to add the icons to all the drop-downs. Also, during this afternoon, I will upload a PR where all the icons are added to the Web Content drop-down.

Best regards.

DIego.

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
> Hello @zhangyan0701, I have revised and fixed the failed test. Regarding the Web Content drop-down icons, in this story (https://issues.liferay.com/browse/LPS-145292) you can find the task to add the icons to all the drop-downs. Also, during this afternoon, I will upload a PR where all the icons are added to the Web Content drop-down.

Thanks a lot for the info and fixing the test!

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:stop

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by john-co** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
The relevant test results are unrelated.

**Comment by DiegoHu97** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
The failures in the most recently relevant test are unrelated.

**Comment by victorg1991** [comment]
Many thanks @zhangyan0701 😍

Sent this directly to brian here: https://github.com/brianchandotcom/liferay-portal/pull/115487

**Comment by victorg1991** [comment]
ci:close

**Pull request closed without merging**
