### PR TITLE
LPS-119792 Fix container-max in ccp-layer

### PR DESCRIPTION
**Pull request by eduardoallegrini**
This PR fixes the container-max CSS Custom Property

ezgif com-video-to-gif

**How to test it:**

- Create a page with and html fragment and insert the following code:
```html
<div class="container-fluid container-fluid-max-xl">
	<div class="bg-primary text-white">container-fluid-max-xl</div>
</div>
<div class="container-fluid container-fluid-max-lg">
	<div class="bg-success text-white">container-fluid-max-lg</div>
</div>
<div class="container-fluid container-fluid-max-md">
	<div class="bg-dangee text-white">container-fluid-max-md</div>
</div>
<div class="container-fluid container-fluid-max-sm">
	<div class="bg-warning text-white">container-fluid-max-sm</div>
</div>
```
- Go to ProductMenu > Design > StyleBook and create a new one
- Go to the Layout option on the right sidebar and edit the values

### CODE REVIEW

**Comment by eduardoallegrini** [comment]
We should consider creating a function to automatically transform SCSS variable-maps into CCP variable-maps

**Comment by jbalsas** [comment]
This looks good to me @eduardoallegrini... is this ready for review!? or test? maybe @pat270 can give us a hand here!

**Comment by eduardoallegrini** [comment]
I'm not sure I couldn't test in my portal but yeah the code should be ok, can anyone test it? 😁

**Comment by pat270** [comment]
Taking a look now.

**Comment by pat270** [comment]
This LGTM.

Unrelated: I deployed a theme based on styled and style books broke. I was wondering if this is intended.

style-book

**Comment by pat270** [comment]
ci:test:sf

**Comment by pat270** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
> Unrelated: I deployed a theme based on styled and style books broke. I was wondering if this is intended.

I think the team still needs to adjust some things for when the themes don't have a `tokenDefinition`

**Comment by marcoscv-work** [comment]
I tested this PR and looks perfect!

**Comment by marcoscv-work** [comment]
ci:forward

**Pull request closed without merging**
