### PR TITLE
LPD-30356 - migrate a test for cancelling creation of an item action

### PR DESCRIPTION
**Pull request by kresimir-coko**
https://liferay.atlassian.net/browse/LPD-30356

### CODE REVIEW

**Comment by kresimir-coko** [comment]
ci:test:frontend

**Comment by kresimir-coko** [comment]
ci:report:34689183

**Comment by kresimir-coko** [comment]
ci:report:34689183

**Comment by kresimir-coko** [comment]
There seems to be one unique failure: 
```
LocalFile.DataSetFragment#ConfirmDefaultSort

https://testray.liferay.com/#/project/34754/routines/34756/build/34689183/case-result/34704159/history

java.lang.Exception: Element is not present at "//button[contains(@class. "btn-sorting") and contains(text(). "id")]"
```

What do you think we should do @dsanz it shouldnt be related

**Comment by dsanz** [comment]
yep, go ahead

**Comment by dsanz** [comment]
ci:forward

**Pull request closed without merging**
