### PR TITLE
LPS-201972 Adds component FeatureIndicator

### PR DESCRIPTION
**Pull request by pat270**
https://liferay.atlassian.net/browse/LPS-201972

Hey @liferay-frontend ,

This replaces BetaBadge and BetaButton with FeatureIndicator. You can test this by deploying `/modules/apps/frontend-js/frontend-js-clay-sample-web/`. Navigate to the Page Editor and deploy JS Clay Sample to the page and publish.

featureIndicator

I have an issue with the JS version of `FeatureIndicator`. I'm not sure how to get the `LearnMessage` to show. I'm not sure how to import the `learnResourceContext`. I also have no idea about how to add a message for the deprecated button.

Lastly, I will need to remove BetaBadge and BetaButton, but I think it will be better to include it in a separate pr.

The syntax for JS files is:

BetaBadge
```
<FeatureIndicator type="beta" />
<FeatureIndicator type="deprecated" />
```

BetaButton
```
<FeatureIndicator interactive type="beta" />
<FeatureIndicator interactive type="deprecated" />
```

### CODE REVIEW

**Comment by pat270** [comment]
ci:test:sf

**Comment by pat270** [comment]
ci:test:sf

**Comment by pat270** [comment]
ci:test:relevant

**Comment by pat270** [comment]
ci:test:relevant

**Comment by ethib137** [comment]
Hey @pat270 I'll send an updated PR with the learn message.

**Pull request closed without merging**
