### PR TITLE
LPS-116361 Adds Admin Portlet for Remote Apps

### PR DESCRIPTION
**Pull request by brunobasto**
Originally #200
Previously https://github.com/liferay-frontend/liferay-portal/pull/231 and then https://github.com/liferay-frontend/liferay-portal/pull/235 and then https://github.com/liferay-frontend/liferay-portal/pull/245 then https://github.com/liferay-frontend/liferay-portal/pull/248 then https://github.com/liferay-frontend/liferay-portal/pull/252

### CODE REVIEW

**Comment by brunobasto** [comment]
ci:test:sf

**Comment by matuzalemsteles** [comment]
Good luck!

**Comment by brunobasto** [comment]
ci:test:relevant

**Comment by brunobasto** [comment]
> Good luck!

**Comment by brunobasto** [comment]
ci:forward

**Pull request closed without merging**
