### PR TITLE
LPS-176146 Fix display of Objects headless resources in FDS Views Manager

### PR DESCRIPTION
**Pull request by markocikos**
### References

- [LPS-176146 Fix display of Objects headless resources in FDS View Manager](https://issues.liferay.com/browse/LPS-176146)

### What is the goal of this PR?

Headless resources created with Objects API have a special format of `entityClassName`. We need to parse in a distinct way.

Note:
- There is still a bug with duplicate entries in search results, that break React component. We will fix this in [a separate ticket](https://issues.liferay.com/browse/LPS-178414).

#### Before PR
before

#### After PR
after

### Steps to reproduce

1. Add `feature.flag.LPS-164563=true` to `portal-ext.properties`. This enables FDS Views Manager.
1. Open Global Menu > Control Panel > Object > Datasets

### CODE REVIEW

**Comment by eltonccdantas** [comment]
I'll take a look at it

**Comment by eltonccdantas** [comment]
Hey @markocikos , the failures are unrelated to your pull request. You may forward it if no other dev review is needed.

[Comparison run](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=2&testrayRunIdB=2234733466&testrayRunIdA=2234300887&statusB=3)

**Review by kresimir-coko — APPROVED** [review]

**Comment by markocikos** [comment]
I'll give it one or two tries before manual forward :crossed_fingers:

**Comment by markocikos** [comment]
ci:forward

**Review by dsanz — APPROVED** [review]

**Comment by markocikos** [comment]
ci:open

**Pull request closed without merging**
