### PR TITLE
LPS-152608 Add pathContext parameter in REST Builder to generate it in the resource client

### PR DESCRIPTION
**Pull request by ccorreagg**
This PR contains the REST Builder code to autogenerate, for each Java client, a new parameter in the `Resource Builder` to set optionally the path context of the URL.

**Before the PR:**

It was not possible to set the path context between the `host:port` and the `/o/....`

```
StructuredContentResource.Builder builder = StructuredContentResource.builder();

structuredContentResource = builder.authentication(
	"test@liferay.com", "test"
).locale(
	LocaleUtil.getDefault()
).build();
```
Then, the path context will not be included when building the URL:
```
httpInvoker.path(
	_builder._scheme + "://" + _builder._host + ":" +
	_builder._port + 
	"/o/headless-delivery" ......
```

**After the PR:**

```
StructuredContentResource.Builder builder = StructuredContentResource.builder();

structuredContentResource = builder.authentication(
	"test@liferay.com", "test"
).locale(
	LocaleUtil.getDefault()
).pathContext(
	"path-context"
).build();
```
Then, the path context will be included when building the URL:
```
httpInvoker.path(
	_builder._scheme + "://" + _builder._host + ":" +
	_builder._port +
	_builder._port + _builder._pathContext +
	"/o/headless-delivery" ......
```

### CODE REVIEW

**Comment by ccorreagg** [comment]
ci:test:relevant

**Review by LuismiBarcos — APPROVED** [review]
LGTM :)
Good job 🙂

**Comment by ccorreagg** [comment]
ci:forward

**Comment by ccorreagg** [comment]
PR forwarded manually: https://github.com/brianchandotcom/liferay-portal/pull/118645

Closing PR...

**Comment by LuismiBarcos** [comment]
CI hates you 😅

**Pull request closed without merging**
