### PR TITLE
LPS-194137 Element not present in ClientExtension#CanBeAssignedAPortletCategory

### PR DESCRIPTION
**Pull request by andreluis2022**
**Description**:
Element not present in ClientExtension#CanBeAssignedAPortletCategory

**JIRA Ticket:**
[LPS-194137](https://liferay.atlassian.net/browse/LPS-194137) Fixed

### CODE REVIEW

**Comment by andreluis2022** [comment]
ci:help

**Comment by andreluis2022** [comment]
ci:test:frontend-client-extensions

**Comment by andreluis2022** [comment]
Hey @CarlosBrichete What do you think this fix?

**Review by CarlosBrichete — APPROVED** [review]
LGTM

**Comment by andreluis2022** [comment]
ci:forward

**Pull request closed without merging**
