### PR TITLE
LPS-138140

### PR DESCRIPTION
**Pull request by wanderlast**
https://issues.liferay.com/browse/LPS-138140

From @Odrakir1:
> The issue was causing a misplacement of the tooltip text when the screen was smaller than 1250px. I have changed the tooltip alignment value for that it won't get affected when the screen is shrinked.

### CODE REVIEW

**Comment by diegonvs** [comment]
Hey @wanderlast and @Odrakir1, We have some [guidelines](https://github.com/liferay/liferay-frontend-projects/blob/master/guidelines/general/pull_requests.md#when-sending-a-pull-request) that you guys can follow before sending pull requests and that can help us to understand better this change, like providing a more detailed description about the issue :)

**Comment by diegonvs** [comment]
Taking a look in the issue, this change will just affect places where clay:data-set-display taglib is being used, like Remote Web Apps widget but not for others.

Is this the objective? I saw a comment made by John where he is mentioning this error occurs in Synonyms too, where it is not using clay:data-set-display.

Pinging @matuzalemsteles and @julien here to ask if this change of positioning can be done in Clay side :p

**Comment by diegonvs** [comment]
Taking a look in `*tooltip-support-web` where this module is responsible for providing this tooltip singleton [it is using Clay directly](https://github.com/liferay/liferay-portal/blob/c406508139ee68d8938a2076c9afa7e56bb47b38/modules/apps/frontend-js/frontend-js-tooltip-support-web/src/main/resources/META-INF/resources/index.tsx), So, I think the fix will be in Clay side. 

/cc @matuzalemsteles @julien

**Comment by carloslancha** [comment]
I agree with @diegonvs , changing the alignment for this particular case may work here but the problem seems to lay deeper in Clay, so I'd fix it there.

**Comment by matuzalemsteles** [comment]
Hey guys, looking at the bug, I don't know if it's Clay related, actually that would be the expected behavior of `dom-align` for example, it won't be able to align the tooltip on the element because it doesn't have room to position properly, so it will align in the best position, this doesn't reflect the arrow's placement because it's a static value and it's set, the recommended thing would be to actually change the placement in that case where the tooltip might appear too close to the edge.

@julien even investigated a similar case https://github.com/liferay/clay/issues/4249.

**Comment by carloslancha** [comment]
We should investigate if we can position the arrow in the best position if there's no space. IMHO we shouldn't force the user to deal with this since the same tooltip should appear in different ways depending on the screen size:

Current tooltip in desktop view (correct behavior):
image

Current tooltip in mobile view (incorrect behavior):
image

**Comment by matuzalemsteles** [comment]
@carloslancha yeah, I think we can investigate if we can do the same for the arrows, maybe we can, if I'm not mistaken `dom-align` returns the element's position but the best case would be not to change the arrow's position because it still might not be aligned but actually changing the `align` API.

**Review by diegonvs — APPROVED** [review]
This issue is being investigated in Clay side(see https://github.com/liferay/clay/issues/4249) and I think We are safe to forward this. As it solves this issue, partially, in this CreationMenu component.

**Comment by diegonvs** [comment]
@carloslancha, @markocikos, @matuzalemsteles would someone "hit" the forward button?

**Comment by matuzalemsteles** [comment]
Yeah, I think we can partially fix it by changing the position here, it still requires a deeper analysis of what behavior we should follow, as I mentioned there's no way to change the arrow's position because it's via CSS, so we'd have to change the position of the whole tooltip instead of just adjusting the arrow.

Just one thing I noticed instead of upgrading to `top-left` wouldn't it be `top-right`?

**Comment by carloslancha** [comment]
Since this is a priority 3 bug I wouldn't forward this if we can fix it in clay, but your call guys :)

**Comment by wanderlast** [comment]
@matuzalemsteles I'm more than willing to defer to your team's judgement. We can keep this on hold for now until we have results from Clay's own side to see if it's something that needs fixing on their end instead.

CC: @Odrakir1

**Comment by nhpatt** [comment]
I would keep it on hold too

**Comment by matuzalemsteles** [comment]
I sent a fix for this https://github.com/liferay/clay/pull/4273, it will be available in the next release next week, we still don't know if we will send the next releases to DXP until we finish the DXP release process to avoid possible problems.

**Comment by julien** [comment]
@matuzalemsteles I'm currently testing the [change](https://github.com/liferay/clay/pull/4273) in liferay-portal/dxp, and I'm not sure it completely fixes the issue.
 For "short" labels like "Add" there doesn't seem to be a problem, but in other cases the tooltip isn't positioned correctly.

Here's an example


I think it's still better than the current behavior, but I thought I'd report here.

**Comment by matuzalemsteles** [comment]
Hmm weird, thanks for reporting @julien, I'm going to test this today on DXP. Maybe it's because the Y position has changed too...

**Comment by matuzalemsteles** [comment]
Ok, I checked this today and it really wasn't working I ended up disabling an option and commenting together in the previous PR, I sent a new fix https://github.com/liferay/clay/pull/4290

**Comment by julien** [comment]
@matuzalemsteles I tested your latest changes and it works fine, thanks. Here's a .gif for anyone interested (note that I couldn't test in "Remote Apps" because for some reason it doesn't work properly on the `master` branch, but it should behave exactly like on the other apps).

**Comment by julien** [comment]
This should be fixed with the latest version of clay (already in `liferay-portal`), @wanderlast could you please confirm and close this pull request when you get a chance? Thanks

**Comment by wanderlast** [comment]
@julien I can confirm that it's fixed. Closing this PR, thanks everyone!

**Pull request closed without merging**
