### PR TITLE
LPS-143364 remove related questions

### PR DESCRIPTION
**Pull request by javiergamarra**
Following Olaf's request, related questions are not very useful as they are right now. There is an Elastic query that can return "related" resources and it can be launched in portal (it's in my paw workspace) and we should support it in the future.

Until then related questions have introduced 2 bugs because they query random questions unrelated to the question being shown (they were responsible of the failure to render when the creator was 0 because GDPR changes)

I suggest we should kill them.

Quite probably tests are broken.

### CODE REVIEW

**Comment by javiergamarra** [comment]
ci:forward

**Comment by LuismiBarcos** [comment]
ci:forward

**Comment by LuismiBarcos** [comment]
@javiergamarra 
Alt Text

:trollface: :trollface: 

Thanks for your help 😊 😊 😊

**Comment by victorg1991** [comment]
Nice try @javiergamarra 😏

**Comment by jkappler** [comment]
@LuismiBarcos, well done, fatality

**Comment by javiergamarra** [comment]
Had to try ¯\_(ツ)_/¯

**Comment by julien** [comment]
@javiergamarra since you seem to have a lot of free time these days, could you take care of fixing the CI? thanks

**Pull request closed without merging**
