### PR TITLE
LPS-186728 Add automations for Data Sets

### PR DESCRIPTION
**Pull request by JerryAdrianoo**
**Description:**
 Add tests for Rename option on Data Sets.
 
 **Jira Ticket:**
 https://liferay.atlassian.net/browse/LPS-186728

### CODE REVIEW

**Comment by JerryAdrianoo** [comment]
ci:help

**Comment by JerryAdrianoo** [comment]
ci:test:frontend-data-set

**Comment by JerryAdrianoo** [comment]
cc@CarlosBrichete

**Review by CarlosBrichete — APPROVED** [review]
LGTM

**Comment by JerryAdrianoo** [comment]
ci:test:sf

**Comment by JerryAdrianoo** [comment]
ci:forward

**Pull request closed without merging**
