### PR TITLE
LPS-128463 - Fix social icons misalignment

### PR DESCRIPTION
**Pull request by marcoscv-work**
This PR fixes a misalignment that was previously fixed in an incorrect way in the compact layer.

image

Clay does not have vertically centered links with class `btn-monospaced`, since they were defined to be localized-input in two lines, flag, and text:
https://clayui.com/docs/components/localized-input.html

So, in general, to fix this with `btn-sm` we will use `c-px-2`.

---

How to test this PR:

- Add the blog portlet to the page.
- Create a blog entry.

Result:

image

### CODE REVIEW

**Comment by marcoscv-work** [comment]
cc @boton

**Comment by boton** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by boton** [comment]
tested and working LGTM

**Comment by marcoscv-work** [comment]
ci:forward

**Comment by jbalsas** [comment]
Hey @marcoscv-work, is this really the way to fix this? I think it's going to be hard to train every developer to remember that if they use `btn-sm` they have to also use `c-px-2`... feels like we should figure out a way to make this transparent so the system works properly on its own 🤔

**Comment by marcoscv-work** [comment]
Hey @jbalsas this is a really not usual case, the combination of a `link` with` btn-sm` and `btn-monospaced` is not something normal, those links should be what looks like: a button, using buttons we will not get alignment issues, but with links, we are expecting to have a combination of icon + text, like a localized Input.
If the pattern starts to be something we need be remembered, I agree, this wouldn't be the way

**Comment by pat270** [comment]
There is an alternative where you can use the `btn-group btn-group-item` pattern on the `ul li` elements. It would look like:

```
<ul class="btn-group list-unstyled">
    <li class="btn-group-item taglib-social-bookmark"></li>
    <li class="btn-group-item taglib-social-bookmark"></li>
    <li class="btn-group-item taglib-social-bookmark"></li>
    <li class="btn-group-item taglib-social-bookmark"></li>
</ul>
```

It adds 0.5rem spacing between buttons.

**Pull request closed without merging**
