### PR TITLE
LPS-165655 Bump liferay-ckeditor version

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by dsanz** [comment]
ci:test:relevant

**Comment by dsanz** [comment]
ci:test:relevant

**Comment by dsanz** [comment]
ci:test:relevant

**Comment by dsanz** [comment]
ci:test:relevant

**Comment by john-co** [comment]
Reviewed. Test failures are unrelated. :heavy_check_mark: 

Ok to manually forward from QA perspective. Pending dev approval.

[Testray Comparison](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=3&testrayRunIdB=2018383266&testrayRunIdA=2020180600&statusB=2) - the unique test failures don't look related to this PR.

**Comment by dsanz** [comment]
ci:test:relevant

**Comment by john-co** [comment]
Hi @dsanz, we can just manually forward this if it looks good to us. No need to keep rerunning `ci:test:relevant` imo https://github.com/liferay-frontend/liferay-portal/pull/2821#issuecomment-1293877219

**Comment by john-co** [comment]
cc/ @gaborlovasdotcom @JoyceWang08211 the oauth2 modules tests have been inconsistently failing and impacting this PR among others.

**Comment by dsanz** [comment]
ci:test:relevant

**Comment by gaborlovasdotcom** [comment]
@john-co , thank you for notifying us, this issue is filed under LRQA-73764.

**Comment by dsanz** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/125448

**Pull request closed without merging**
