### PR TITLE
LPS-152145 Add margin between notifications

### PR DESCRIPTION
**Pull request by boton**
Issue: https://issues.liferay.com/browse/LPS-152145

The notifications stacked do not have a margin.

**How to reproduce:**
It's difficult to get notifications stacked but we can call some on the console.

```js
[...Array(3)].forEach(() =>
    Liferay.Util.openToast({
        autoClose: false, 
        message: 'Lorem ipsum dolor sit amet'
    })
)
```

Execute the code above in the console.

**Before this PR**
image

**After this PR**
image

### CODE REVIEW

**Comment by carloslancha** [comment]
Hey @boton LGTM. @diegonvs could you check this? I see that you fixed this issue a couple of years ago but seems that the margin was being applied to the container, not to each alert.

Thx!

**Comment by carloslancha** [comment]
@liferay-lexicon could you take a look too please? Thx!

**Comment by boton** [comment]
> @diegonvs could you check this? I see that you fixed this issue a couple of years ago but seems that the margin was being applied to the container, not to each alert.

It was applied to the container of each alert but doesn't work maybe some change on the CSS or something 🤔

**Comment by emiliano-cicero** [comment]
hey @carloslancha, the space between alerts should be 16px, here's a direct link to the [stacking behaviour](https://liferay.design/lexicon/core-components/alerts/#toast-stacking-behavior).

**Comment by diegonvs** [comment]
> I see that you fixed this issue a couple of years ago but seems that the margin was being applied to the container

As @boton said, maybe something changed on clay css side but the fix looks fine. Thanks Jorge :)

**Comment by matuzalemsteles** [comment]
Hey guys, apparently on the Clay side, this is working fine, maybe this isn't some other CSS that is stripping the elements' margin-bottom? in Clay CSS it is added to margin via `.alert-notifications .alert`.

**Comment by pat270** [comment]
The alerts are wrapped in `lfr-tooltip-scope`. I'm guessing `overflow: hidden` was removed from it somewhere in https://issues.liferay.com/browse/LPS-127085. The alerts will work as is if we can remove the `<div class="mb-3 lfr-tooltip-scope">`.

**Pull request closed without merging**
