### PR TITLE
LPS-156749 Update `clay-css` dependencies to v2.24.3

### PR DESCRIPTION
**Pull request by georgel-pop-lr**
LPS-156749 Update `clay-css` dependencies to v2.24.3

### CODE REVIEW

**Comment by georgel-pop-lr** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by georgel-pop-lr** [comment]
ci:test:relevant

**Comment by georgel-pop-lr** [comment]
ci:forward

**Comment by georgel-pop-lr** [comment]
ci:test:sf

**Comment by georgel-pop-lr** [comment]
ci:test:relevant

**Comment by georgel-pop-lr** [comment]
Reopen https://github.com/liferay-frontend/liferay-portal/pull/2443

**Pull request closed without merging**
