### PR TITLE
LPS-130144 Fix auto-generated file

### PR DESCRIPTION
**Pull request by edalgrin**
This PR fixes the modified auto-generated file and add the same dependency using another file

### CODE REVIEW

**Comment by wincent** [comment]
Hopefully something a `cd portal-impl && ant format-source-current-branch` (or a `gradlew formatSource` in `dynamic-data-mapping-taglib`) can fix. 🤞

**Comment by edalgrin** [comment]
ci:test:sf

**Comment by edalgrin** [comment]
ci:test:sf

**Comment by edalgrin** [comment]
ci:test:relevant

**Comment by wincent** [comment]
easy

I'd say you can take this out of draft and `ci:forward` it.

**Comment by edalgrin** [comment]
ci:forward

**Pull request closed without merging**
