### PR TITLE
LPD-40979 - Frontend Data Set with Clay Table is not properly rendering nested rows for Commerce Product bundle.

### PR DESCRIPTION
**Pull request by ethib137**
https://liferay.atlassian.net/browse/LPD-40979

## Steps to Reproduce:
1. Enable the Feature Flag LPS-193005
2. Create a new site using the Minium template in order to propagate commerce products.
3. Follow the steps here to create a Commerce Product Bundle.
4. Add the product bundle to your cart and check out.
5. Navigate to Pending Orders.
6. Select the created order.
7. Scroll down to view the products contained in the order and try to expand the Product Bundle.

## How it was fixed
The Clay Table api was updated to allow for entries to have unique keys identified by properties other than `id`. For instance Commerce uses `orderItemId`. This key can be passed into the Clay Table via the `itemIdKey` prop. When this prop is used with nested rows we have to remove the `key` prop from the `Row` since this overrides the key provided via `itemIdKey`.

### CODE REVIEW

**Comment by ethib137** [comment]
ci:test:relevant

**Review by markocikos — APPROVED** [review]
@ethib137 LGTM! :sparkles:

**Comment by markocikos** [comment]
@ethib137 Does this need a test, or is it covered by commerce tests?

**Comment by ethib137** [comment]
@markocikos since this is still just a part of the migration to the ClayTable, I would assume that it should be covered by existing FDS tests or Commerce tests. We aren't adding any new functionality.

**Comment by ethib137** [comment]
ci:test:relevant

**Comment by ethib137** [comment]
Failures are unrelated. I'm going to manually forward to Brian.

**Comment by ethib137** [comment]
Manually forwarded to https://github.com/brianchandotcom/liferay-portal/pull/156725

**Comment by markocikos** [comment]
@ethib137 PW failure in https://github.com/liferay-frontend/liferay-portal/pull/4597#issuecomment-2522755935is likely related, but it's fine since we'll be updating all FDS tests after switch to clay table.

**Comment by ethib137** [comment]
Hey @markocikos what does PW stand for in this case? Also, I don't think any of these failures could be related because we don't have any tests running with the ClayTable feature flag enabled and all of these changes are behind a feature flag.

**Comment by markocikos** [comment]
@ethib137 Yeah, you're right, it's unrelated for sure :+1:

**Pull request closed without merging**
