### PR TITLE
[7.4+][PART 1] LPS-134071 Migrate frontend-theme-styled CSS

### PR DESCRIPTION
**Pull request by edalgrin**
This PR removes all the unused and third-party CSS from `frontend-theme-styled`
- [Original PR](https://github.com/liferay-frontend/liferay-portal/pull/1877#issuecomment-1064926374)
- [Strategy](https://liferay.atlassian.net/wiki/spaces/ENGFRONTENDINFRA/pages/1341882669/LPS-127086+-+Analyze+and+prototype+possible+theme+optimizations?focusedCommentId=1969652346#comment-1969652346)
- [Changelog](https://docs.google.com/spreadsheets/d/1IG7o3hAn9w91-sg_vXQZeWhJsRBSSMTrGUi-EVfQ6H8/edit#gid=0)
- [Module testing](https://docs.google.com/spreadsheets/d/1IG7o3hAn9w91-sg_vXQZeWhJsRBSSMTrGUi-EVfQ6H8/edit#gid=1130153366)

### CODE REVIEW

**Comment by edalgrin** [comment]
I think the SF is not related, running `ant format-source-current-branch` it removes a library "DATE" from `commerce-product-content-web` which seems to be the error - if necessary will push the change after the ci:relevant

**Comment by edalgrin** [comment]
Hey @john-co @Esther-OC , I've tried to modify as much as I could in order to prevent JS and CI errors, but at this point I'm running out of ideas. Can you please take a second look and modify the tests if necessary or tell me how to fix it "on my side"?

/cc @carloslancha

**Comment by carloslancha** [comment]
@Esther-OC do we have any more failing tests?

**Comment by edalgrin** [comment]
Upgraded  the PR starting from the master and cherry-picking the necessary commits from the original PR, it's now building in local

image

**Comment by edalgrin** [comment]
ci:test:relevant

**Comment by john-co** [comment]
@zhangyan0701 can you also help with this PR test analysis?

**Comment by Esther-OC** [comment]
Here you have the [comparison](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=3&testrayRunIdB=1644782382&testrayRunIdA=1645847381&statusB=2) of the PR with upstream for the unique failures.

I have started to analyze it, by any help will be welcome 😉. Thanks!
I'm going to summarize our discoveries or planned actions, just to have them handy and to put in context to anybody who can help with the PR analysis.

After taking a first quick look with @edalgrin, we have to analyze the following tests, but we don't know how to handle some of them:
- [LocalFile.DMPermissions#ViewDocumentWithGlobalScope](https://testray.liferay.com/home/-/testray/case_results/1645849492 ) --> error `DevToolsActivePort file doesn't exist`, which we have seen also in the [PART-5 pull/2008](https://github.com/liferay-frontend/liferay-portal/pull/2008#issuecomment-1075162718):  test case [LocalFile.DisplayPageTemplatesForWebContentArticle#NavigateToDisplayPageTemplateViaFriendlyURL](https://testray.liferay.com/home/-/testray/case_results/1635512162) and we don't know if it's ok to consider it flaky or not.

- For Java issues like  [LocalFile.DMPermissions#ViewDMDocumentNoGuestRole](https://testray.liferay.com/home/-/testray/case_results/1645849449) and similar with `java.lang.NullPointerException`also seen in  [PART-5 pull/2008](https://github.com/liferay-frontend/liferay-portal/pull/2008#issuecomment-1075162718), we have planned to ask tomorrow our FI colleagues to see if they can give us any clue.

- [https://testray.liferay.com/home/-/testray/case_results/1645853525](https://testray.liferay.com/home/-/testray/case_results/1645853525) --> ideas?

- Two related to headless:  [com.liferay.headless.commerce.machine.learning.resource.v1_0.test.SkuForecastResourceTest
](https://testray.liferay.com/home/-/testray/case_results/1645853903) and [com.liferay.headless.delivery.resource.v1_0.test.MessageBoardSectionResourceTest
](https://testray.liferay.com/home/-/testray/case_results/1645853464) --> we planned to ask Headless team tomorrow for help.

- The one related to [modules-semantic-versioning-jdk8/0/0](https://testray.liferay.com/home/-/testray/case_results/1645853670) --> it's not related to the PR, but what worries me is that is always present in our PRs for the css changes and in other PRs it works fine.  But my knowledge regarding `jdk8` is quite limited with it to understand and see if there is a problem.

- There are several test cases (like [LocalFile.DMFileEntry#CanCheckInAsMajorVersion](https://testray.liferay.com/home/-/testray/case_results/1645849326)) that are failed due to `Failed prior to running test`but only in this PR, not in other PRs around the same date or previous/following --> we are commenting it in our FI QA group.

**Comment by zhangyan0701** [comment]
I also take a look at the results, looks like the failures are all unrelated to this PR.

1. [LocalFile.DMPermissions#ViewDocumentWithGlobalScope](https://testray.liferay.com/home/-/testray/case_results/1645849492) - This one should be a chrome webdriver problem. More like a flaky.
2. [LocalFile.DMPermissions#ViewDMDocumentNoGuestRole](https://testray.liferay.com/home/-/testray/case_results/1645849449) - Also looks like flaky, there is a ticket for the same error: [LRQA-70132](https://issues.liferay.com/browse/LRQA-70132).
3. [com.liferay.journal.asset.test.JournalArticleAssetSearchTest](https://testray.liferay.com/home/-/testray/case_results/1645853525) - An known issue of Web Content: [LPS-138481](https://issues.liferay.com/browse/LPS-138481)
4. [modules-semantic-versioning-jdk8/0/0](https://testray.liferay.com/home/-/testray/case_results/1645853670) - The error in test is for a Commerce module: [COMMERCE-8866](https://issues.liferay.com/browse/COMMERCE-8866).
5. The error `Failed prior to running test` in some DM tests should be a Jenkins problem.

**Comment by john-co** [comment]
Looks like it's ok to manually forward from QA side. :heavy_check_mark:

**Comment by Esther-OC** [comment]
Yes, just to mention that our colleagues from Commerce have check the one related to them and they confirmed that it is a fluke, as expected.

So please go ahead with the manual forward.

**Comment by edalgrin** [comment]
Thank you all, I'll proceed with the manual forward.

**Comment by edalgrin** [comment]
ci:test:sf

**Comment by edalgrin** [comment]
Manual forwarded to https://github.com/brianchandotcom/liferay-portal/pull/115241

**Pull request closed without merging**
