### PR TITLE
LPD-34947 Update AlloyUI to v3.1.0-deprecated.120

### PR DESCRIPTION
**Pull request by igor-franca**
Related [ticket](https://liferay.atlassian.net/browse/LPD-34947)

### CODE REVIEW

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Review by markocikos — APPROVED** [review]
@igor-franca LGTM! :sparkles:

**Comment by igor-franca** [comment]
Thanks for the review team, I will forward the changes 😄

**Comment by igor-franca** [comment]
ci:forward

**Pull request closed without merging**
