### PR TITLE
LPS-201102 Unable to save client extensions that deploy portlets when database partitioning is on (all companies)

### PR DESCRIPTION
**Pull request by dsanz**
This is a followup of https://github.com/liferay-frontend/liferay-portal/pull/3811 where we fix the issue for all companies. Previous fix was working in the default virtual instance, and only if there were no more virtual instances in the system.

When more than one virtual instance is created, DB partition executes some logic across all of them, which entails new flush operations, bringing back the faulty behavior when it comes to update a client extension. This happened on all companies, even the default one.

In this PR we are obeying the same order of things for all Client Extension service methods involving deployment, which is:

1. Persist the `ClientExtensionEntry` model
2. Deploy it

This natural order was being followed in the add/remove operations already, but not in the update one. With this change, updating a client extension entry via UI prevents the changes on the persistence layer caused by deployment from interfering with the client extension entry update itself.

Additional notes:
 * We discovered some potential optimizations while deploying the CET portlet as it should only apply to the current company, meaning there is no need to create portlet resources for all of them
 * A side effect of this change is that `CETFactory`  now takes an updated version of the `ClientExtensionEntry` model object, which is the right thing to expect. Prior to this, the model object used by the factory was not the one we ended up persisting. Probably, nobody noticed this because the affected model attributes (`status` and others) are not useful for the purposes of building a functional `CET` object
 * I'm keeping all the previous commits (both @achaparro and mine) because, even if they don't solve the issue entirely, they leave things in a better state and are still valuable

cc @achaparro @izaera @mateusralv @CarlosBrichete

### CODE REVIEW

**Comment by dsanz** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
@dsanz merged to master and Q4

**Comment by dsanz** [comment]
@CarlosBrichete @mateusralv this is now merged so I'm closing this pull, and set https://liferay.atlassian.net/browse/LPS-201102 in "ready for testing"

**Comment by mateusralv** [comment]
Hi @dsanz thanks I'll work on it.

**Pull request closed without merging**
