### PR TITLE
LPS-169672 | Test a fix for #2993

### PR DESCRIPTION
**Pull request by mateusralv**
Background: 
I could not add the commit (https://github.com/liferay-frontend/liferay-portal/commit/7562111551a23fd61f8dd0d1fd3f5d0c42ab5c85)  so I solved the problems that I found in the test log and I sent this PR.
PR original: https://github.com/liferay-frontend/liferay-portal/pull/2993

### CODE REVIEW

**Comment by mateusralv** [comment]
ci:test:sf

**Comment by mateusralv** [comment]
ci:test:relevant

**Comment by mateusralv** [comment]
ci:test:relevant

**Comment by mateusralv** [comment]
cc: @john-co

**Comment by mateusralv** [comment]
ci:test:relevant

**Comment by mateusralv** [comment]
ci:test:sf

**Comment by mateusralv** [comment]
ci:test:relevant

**Comment by dsanz** [comment]
ci:test:frontend-remote-apps

**Comment by dsanz** [comment]
Hi @mateusralv we have some remote apps not passing, could you pls take a look?
Thank you

**Comment by mateusralv** [comment]
I see that the repair helped us, I will take a look at the new results 👓

**Comment by dsanz** [comment]
ci:test:relevant

**Comment by mateusralv** [comment]
Hi @dsanz I took a look at the results and found this: 
The failures from ci:test:relevant (https://github.com/liferay-frontend/liferay-portal/pull/2994#issuecomment-1402963386)  are not related 
[Testray comparison ](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1674680415514&testrayRunIdA=2172201487&testrayRunIdB=2172374831)

and

The failures from ci:test:frontend-remote-apps (https://github.com/liferay-frontend/liferay-portal/pull/2994#issuecomment-1403332179) are also unrelated to this PR. 
[Testray comparison](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1674680699410&testrayRunIdA=2172536166&testrayRunIdB=2172694334)

**Comment by mateusralv** [comment]
ci:test:frontend-remote-apps

**Comment by john-co** [comment]
Looks like only test left that looks related is [LocalFile.ClientExtension#ErrorAppearsWhenHTMLBlank](https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/144947//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_ClientExtension_ErrorAppearsWhenHTMLBlank_)

cc/ @dsanz can someone confirm if this an intentional change or if this is ok? It looks like the change from this PR which was meant for IFrame affected a different client extension type Custom Element. It looks like a slightly less informative error message is provided compared to existing behavior.

Actual:
`HTML Element field is required` 

Expected:
`HTML element name is empty`

screenshot_58

**Comment by edalgrin** [comment]
In some ways it is an intentional change. We changed the type of validation of these fields from "server side" to "browser side" and we are using the default error for an empty field. I believe we still have the original "HTML element name is empty" but it's not being triggered (and it's not supposed to be) because of these changes.

**Comment by dsanz** [comment]
@john-co thanks for discovering this. Yes, this PR includes changes in the translations, as requested by Bchan [here](https://github.com/brianchandotcom/liferay-portal/pull/127864#issuecomment-1379844751). So I revamped all the texts to make them look similar. 

Anyways , the change that made that field validation look different is related to [this commit](https://github.com/liferay-frontend/liferay-portal/pull/2994/commits/40cb3220ba4a699bab02721ae6b9026040bdec36) where we delegated mandatoryness validation to the <aui:input> in the frontend side, as Edu says

So, the change intentional. 

Nevertheless, probably this should read "HTML Element name field is required" instead of jsut "HTML Element field is required", but considering the time this PR has been around, I'm very reluctant to make any change not related to the failing test.

**Comment by mateusralv** [comment]
ci:test:frontend-remote-apps

**Comment by mateusralv** [comment]
ci:help

**Comment by mateusralv** [comment]
ci:test:frontend-client-extensions

**Comment by mateusralv** [comment]
The suite to run the remote apps tests changed because this PR https://github.com/liferay-frontend/liferay-portal/pull/2996 was merged.

**Comment by dsanz** [comment]
Hi @mateusralv so is it safe to forward even if the remote apps suite fails?

**Comment by mateusralv** [comment]
Hi @dsanz Are you talking about these results here https://github.com/liferay-frontend/liferay-portal/pull/2994#issuecomment-1405374273? The only failure is not unique and is not related.

[Testray comparison](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1674774466664&testrayRunIdA=2174531047&testrayRunIdB=2174861443)

**Comment by dsanz** [comment]
ci:forward:force

**Comment by john-co** [comment]
ci:test:sf

**Comment by john-co** [comment]
Manually forwarded to https://github.com/brianchandotcom/liferay-portal/pull/129331

Waiting for SF test suite to pass here and will reopen that PR.

**Comment by dsanz** [comment]
thanks a log @mateusralv @john-co

**Pull request closed without merging**
