### PR TITLE
LPD-44097 Deprecated Badge Adjustments

### PR DESCRIPTION
**Pull request by BarbaraCabrera**
## Motivation

Hello, team!

I am sending this pr to solve some design differences that we have found between the Feature Indicator component we have and the design of it in figma. It has been just adjust some margins and use capital letters for the button text as we use it for the Clay Badge.

[LPD-44097](https://liferay.atlassian.net/browse/LPD-44097)

## Changes

Adapt styles to match the figma component

## Steps

Activate the FF [LPD-40529](https://liferay.atlassian.net/browse/LPD-40529)
Navigate to Fragments in the Product Menu

## Results

image
image

[LPD-44097]: https://liferay.atlassian.net/browse/LPD-44097?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LPD-40529]: https://liferay.atlassian.net/browse/LPD-40529?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by BarbaraCabrera** [comment]
ci:test:sf

**Comment by BarbaraCabrera** [comment]
ci:test:sf

**Review by markocikos — APPROVED** [review]
@BarbaraCabrera LGTM! :sparkles:

**Comment by BarbaraCabrera** [comment]
ci:forward

**Comment by markocikos** [comment]
@BarbaraCabrera It's your call, PR is green so you can do what you like. I'd check that semantic versioning error, update might be needed on a related module to it even if it's not strictly related to this PR.

**Comment by BarbaraCabrera** [comment]
ci:forward

**Comment by BarbaraCabrera** [comment]
see: https://github.com/brianchandotcom/liferay-portal/pull/156988

**Pull request closed without merging**
