### PR TITLE
LPS-119592 use map-get for correct margin

### PR DESCRIPTION
**Pull request by antonio-ortega**
Hi guys,

Can you review this pull request, please?

In the description of issue [LPS-119592](https://issues.liferay.com/browse/LPS-119592) you can find some useful information about reproduction steps, root cause and solution.

Thanks.

Regards.

/cc @SamZiemer @brianikim

### CODE REVIEW

**Review by eduardoallegrini — APPROVED** [review]

**Comment by jbalsas** [comment]
ci:test:sf

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
@pat270, @eduardoallegrini don't be afraid of running tests and forwarding PRs if they look good! 😉

**Comment by pat270** [comment]
> @pat270, @eduardoallegrini don't be afraid of running tests and forwarding PRs if they look good! 😉

👍

**Comment by jbalsas** [comment]
ci:forward

**Pull request closed without merging**
