### PR TITLE
LPS-161586 - Update alloy-ui to 3.1.0-deprecated.103

### PR DESCRIPTION
**Pull request by chileces**
Dear Team,
This PR is to update alloy-ui to 3.1.0-deprecated.103 due to a request from https://github.com/liferay/liferay-frontend-projects/pull/993
Please review it and leave comments if any.
Thanks

### CODE REVIEW

**Review by diegonvs — APPROVED** [review]

**Comment by diegonvs** [comment]
ci:test:relevant

**Comment by diegonvs** [comment]
ci:forward

**Comment by mateusralv** [comment]
I'm taking a look [this](https://github.com/liferay-frontend/liferay-portal/pull/2678#issuecomment-1241123453) failures 🕵🏽

**Comment by mateusralv** [comment]
Hey @chileces, I made a [comparison with master](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1662671535527&testrayRunIdA=1970739223&testrayRunIdB=1968772674) and analyzed the results, the failures do not seem related to your pr. 🎉 

A short summary of the failures I analyzed: 

Failure unique, but seems flake:
LocalFile.BlogsNotifications#EmailIsReceivedWhenUpdateReachesScheduledTime

---
Aborted:
ContentPagesWithContentsPanel#ResizeDisplayedImageViaImageEditor
ContentPagesWithContentsPanel#RotateDisplayedImageViaImageEditor
ContentPagesWithContentsPanel#SearchDisplayedAssetsByKeyword
ContentPagesWithContentsPanel#ViewDashedOutlineOfEditableFieldWhenHoverOnInlineTextItems

---
Failures, not unique:
DatabasePartitioning#CanAddCompanyWithPortalInstancesAdminUI
ObjectPortlet#CanAddEntryWithoutSelectingPicklist
ObjectsPopulating#CanMapStringTypeAndViewEntries

---
Failure prior to running:
ImportExport#CannotImportWithoutRequiredFields
ImportExport#CanSaveTemplateDuringImport
ImportExport#CanSearchExecutions
ImportExport#CanSearchTemplates
ImportExport#CanViewExportNotifications
ImportExport#CanViewImportErrorReport
ImportExport#CanViewImportNotifications

---
Null point Exception:
ExternalVideo#DisplayVideoFromDocumentsAndMediaInExternalVideo

**Comment by bryceosterhaus** [comment]
manual forward https://github.com/brianchandotcom/liferay-portal/pull/122851

**Pull request closed without merging**
