### PR TITLE
LPS-115680 - Add clay empty-state reorder dual-listbox and slideout components

### PR DESCRIPTION
**Pull request by marcoscv-work**
Some new Clay components are not been including in Liferay portal themes.
After this adding we should be able to apply new components markup like:

https://clayui.com/docs/components/empty-state.html
https://clayui.com/docs/components/dual-list_box.html

### CODE REVIEW

**Comment by marcoscv-work** [comment]
ci:test:sf

**Comment by marcoscv-work** [comment]
ci:test:stable

**Comment by marcoscv-work** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
Hey @pat270, @bryceosterhaus, this is very common everytime we add a new CSS component and bring it over to DXP. 

Because we had to overwrite some files (`_components.scss`), we always need to account for that the first time a new CSS component makes it in.

I see some additional actions we might/could take:
- Review if there's a better approach for us to stop overwriting `_components.scss`... @marcoscv-work , @eduardoallegrini ?
- Add some additional item to the checklist so we remember to do this when updating Clay in DXP. @pat270, @bryceosterhaus ?

**Comment by wincent** [comment]
> I'm not entirely sure how we can streamline this more than just mental overhead or a checklist, which is never great to rely on. Ill think on this more...

A checklist, while very low tech, is still a good tool. IANAP (I Am Not A Pilot), but I understand that a huge part of flying is just running through checklists.

IHNRIMBIHIG (I Have Not Read It Myself But I Hear It's Good), I believe [The Checklist Manifesto](https://www.amazon.com/Checklist-Manifesto-How-Things-Right-ebook/dp/B0030V0PEW) goes into this kind of thing a bit.

**Comment by pat270** [comment]
I think the do as little as possible option for components is change https://github.com/liferay-frontend/liferay-portal/blob/4ad7ee3d55cc70c52975ea59c6a20121b36521b8/modules/apps/frontend-theme/frontend-theme-unstyled/build.gradle#L69-L75 to:
```
@import "compat/components";

@import "../liferay_variables_custom";
@import "../liferay_variables";
@import "bourbon";
@import "../clay_custom";
@import "../liferay_custom";
```
We don't need `@import "variables";` that is a duplicate import. Clay's `_variables.scss` is imported 6 lines above that. This change should only happen to `atlas.scss` and `base.scss` unless we want to break the way `bootstrap.scss` currently works.

For `compat/_variables.scss`, I can add the comment `// INSERT COMPAT VARIABLES` to `atlas-variables.scss`, `atlas.scss`, `base-variables.scss`, and `atlas.scss` then we can add a rule in unstyled `build.gradle` to replace that line with `@import "compat/variables";`.

#### Unrelated Source Formatting Issue:

One thing I'd like to see changed is to be as specific as possible with our Sass imports. We have so many. It's hard to understand which file an `@import` directive is importing. We should rewrite the above imports to:

```
@import "compat/_components.scss";

@import "../_liferay_variables_custom.scss";
@import "../_liferay_variables.scss";
@import "bourbon";
@import "../_clay_custom.scss";
@import "../_liferay_custom.scss";
```

**Comment by marcoscv-work** [comment]
Yeah, the reason we need to modify the file `components.scss` and `_variables.scss` (variables for components). Is the compatibility layer which needs to be load in Clay CSS.

As Patrick mentioned we could add the import by compilation process but probably it would make the line adds a little bit hidden.

**Comment by jbalsas** [comment]
@marcoscv-work, just FYI, this is still waiting for your answer and or additional work to https://github.com/liferay-frontend/liferay-portal/pull/27#pullrequestreview-433131648

**Comment by marcoscv-work** [comment]
> Hey @marcoscv-work, don't we need to add them also to [clay/atlas_variables.scss](https://github.com/liferay/liferay-portal/blob/master/modules/apps/frontend-theme/frontend-theme-styled/src/main/resources/META-INF/resources/_styled/css/clay/atlas/_variables.scss).
> 
> I always forget, but I seem to remember that was needed as well...

Yes, sorry, I will resend it, I was looking at the reason of the vars duplication which @pat270 mentioned.
We can close this.

**Comment by marcoscv-work** [comment]
Resend:
https://github.com/liferay-frontend/liferay-portal/pull/37

**Pull request closed without merging**
