### PR TITLE
[7.4-only] LPS-102098 - Remove compat-layer icons

### PR DESCRIPTION
**Pull request by marcoscv-work**
This PR removes compat-layer icons support

For this, we had to move some essential styles to `taglib` > `icons`

---

To test the PR:

- You should not notice any visual change in icons

### CODE REVIEW

**Comment by marcoscv-work** [comment]
ci:test:sf

**Comment by marcoscv-work** [comment]
ci:test:relevant

**Comment by marcoscv-work** [comment]
Probably not-related test-fail, we would need to double-check, @john-co @zhangyan0701

@eduardoallegrini you can add the first commit to your PR: https://github.com/liferay-frontend/liferay-portal/pull/588 and add your own commit to remove icons imports and variables.

**Comment by john-co** [comment]
Reviewed. Test failures are unrelated. :heavy_check_mark: 

looks like the same issue here: https://liferay.slack.com/archives/CL84ZPHAT/p1607614841469600
has been fixed here: https://github.com/brianchandotcom/liferay-portal/pull/96806

Should pass if run `ci:test:relevant` again.

**Comment by pat270** [comment]
LGTM

**Comment by jbalsas** [comment]
I'll just forward manually, I don't think it makes sense to waste CI resources on this

**Comment by jbalsas** [comment]
Forwarded to https://github.com/brianchandotcom/liferay-portal/pull/96809

**Comment by jbalsas** [comment]
@marcoscv-work, rebase errors probably with another PR of our own, so I guess @eduardoallegrini or @pat270 will need to rebase once upstream is up to date 😢

**Comment by eduardoallegrini** [comment]
Just started reviewing :)

**Comment by eduardoallegrini** [comment]
PR rebased and conflicts solved. Trying to fix https://github.com/liferay-frontend/liferay-portal/pull/588, if I can't fix it by the end of the day I'll send this on its own.

**Comment by marcoscv-work** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcoscv-work** [comment]
Forwarded to https://github.com/brianchandotcom/liferay-portal/pull/96865

**Comment by marcoscv-work** [comment]
Merged

**Pull request closed without merging**
