### PR TITLE
LPS-169672 Provide users with clear information to register iFrame client extensions

### PR DESCRIPTION
**Pull request by dsanz**
I rebased https://github.com/liferay-frontend/liferay-portal/pull/2969 and excuded all tests, to see what CI thinks about this.

Then, with the help of @mateusralv, we'll add the test commits and see

### CODE REVIEW

**Comment by dsanz** [comment]
ci:test:sf

**Comment by mateusralv** [comment]
Hi @dsanz The relevant keeps returning many failures in this pr (+3k) The idea will be to retain more committees and send a new PR? T[estray comparison](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1674522350679&testrayRunIdA=2170279151&testrayRunIdB=2170988903)

**Comment by dsanz** [comment]
@mateusralv yes, this first round does not include the tests. Now I'm pushing them at the end of the pull. I'd like to compare the results before and after these commits, to determine if we can forward or we need to adjust tests for client extensions

**Comment by dsanz** [comment]
ci:test:relevant

**Comment by dsanz** [comment]
ci:test:frontend-remote-apps

**Comment by dsanz** [comment]
@mateusralv looks like numbers we get before and after the tests are the same. I've launched the remote-apps suite to focus on it only

**Comment by mateusralv** [comment]
I will analyze some failures to try to find a clue :thinking:

**Comment by mateusralv** [comment]
Hey @dsanz  I found a clue, the poshi tests are failing because the modifications of this commit  https://github.com/liferay-frontend/liferay-portal/pull/2959/commits/7562111551a23fd61f8dd0d1fd3f5d0c42ab5c85 are missing in this PR. I believe it can solve help to solve these poshi failures. 
```
 [exec] Invalid path locator ClientExtensionEntry#REMOTE_APPS_PORTLET_CATEGORY_NAME at:
     [exec] /opt/dev/projects/github/liferay-portal/portal-web/test/functional/com/liferay/portalweb/macros/ClientExtensionEntry.macro:120
     [exec]   113 |                key_id = "ClientExtensionAdminPortlet_htmlElementName",
     [exec]   114 |                locator1 = "RemoteAppsEntry#URL",
     [exec]   115 |                value1 = "${entryHTMLElementName}");
     [exec]   116 |        }
     [exec]   117 |    }
     [exec]   118 |
     [exec]   119 |    macro addPortletCategory {
     [exec] > 120 |        Select(
     [exec]   121 |            locator1 = "ClientExtensionEntry#REMOTE_APPS_PORTLET_CATEGORY_NAME",
     [exec]   122 |            value1 = "${categoryName}");
     [exec]   123 |    }
     [exec]   124 |
     [exec]   125 |    macro addURLRow {
     [exec]   126 |        Click(
     [exec]   127 |            key_id = "ClientExtensionAdminPortlet__urls",
     [exec] 
     [exec] 
     [exec] Duplicate variable name: entryHTMLElementName at:
     [exec] /opt/dev/projects/github/liferay-portal/portal-web/test/functional/com/liferay/portalweb/macros/ClientExtensionGeneral.macro:14
     [exec]    7 |
     [exec]    8 |        var externalReferenceCodeValue = StringUtil.extractFirst("${findWhereIdBegins}", "&_com_liferay_client_extension_web_internal_portlet_ClientExtensionAdminPortlet_redirect");
     [exec]    9 |
     [exec]   10 |        JSONClientExtension.deleteIFrameRemoteAppEntry(externalReferenceCode = "${externalReferenceCodeValue}");
     [exec]   11 |    }
     [exec]   12 |
     [exec]   13 |    macro addApp {
     [exec] > 14 |        ClientExtensionEntry.addEntry(
     [exec]   15 |            entryHTMLElementName = "${entryHTMLElementName}",
     [exec]   16 |            entryName = "${entryName}",
     [exec]   17 |            entryURL = "${entryURL}",
     [exec]   18 |            mainURL = "${mainURL}",
     [exec]   19 |            entryHTMLElementName = "${entryHTMLElementName}");
     [exec]   20 |
     [exec]   21 |        PortletEntry.publish();
     [exec] 
     [exec] 
     [exec] Invalid path name RemoteAppsEntry at:
     [exec] /opt/dev/projects/github/liferay-portal/portal-web/test/functional/com/liferay/portalweb/macros/ClientExtensionEntry.macro:112
     [exec]   105 |            Type(
     [exec]   106 |                key_id = "ClientExtensionAdminPortlet_url",
     [exec]   107 |                locator1 = "ClientExtensionEntry#URL",
     [exec]   108 |                value1 = "${entryURL}");
     [exec]   109 |        }
     [exec]   110 |
     [exec]   111 |        if (isSet(entryHTMLElementName)) {
     [exec] > 112 |            Type(
     [exec]   113 |                key_id = "ClientExtensionAdminPortlet_htmlElementName",
     [exec]   114 |                locator1 = "RemoteAppsEntry#URL",
     [exec]   115 |                value1 = "${entryHTMLElementName}");
     [exec]   116 |        }
     [exec]   117 |    }
     [exec]   118 |
     [exec]   119 |    macro addPortletCategory {
     [exec] 
     [exec] 
     [exec] 
     [exec] 
     [exec] > Task :writePoshiProperties FAILED
     [exec] Gradle build finished at 2023-01-24 08:06:47.748.
```

**Comment by mateusralv** [comment]
To test this I will create a new  PR from this and add the commit.

**Comment by mateusralv** [comment]
@dsanz I could not add the commits, so I solved the problems I found in the test log and sent a PR. https://github.com/liferay-frontend/liferay-portal/pull/2994 and ran the relevant, let’s see if that was it...

**Pull request closed without merging**
