### PR TITLE
[7.4-only] LPS-122449 Replace usages of dom.delegate and fix related bug

### PR DESCRIPTION
**Pull request by kresimir-coko**
This PR replaces the only remaining usage of `dom.delegate` found in `dynamic-data-mapping-form-web` and fixes a bug introduced earlier where `.dispose()` was called on an invalid event handler.

This is the only remaining usage provided #566 goes smoothly.

/cc @julien, here I've sent a fix to the `.removeAllListeners()` change I introduced that we talked about. Note: I didn't manually test this as this specific change is very difficult to test.

### CODE REVIEW

**Comment by kresimir-coko** [comment]
ci:test:sf

**Comment by kresimir-coko** [comment]
ci:test:relevant

**Review by wincent — COMMENTED** [review]
These really should have been two separate commits, one to fix the bug and the other to do the migration in DDM (in general "and" in a commit title is a bit of a red flag).

Want to take a stab at splitting them?

```
git reset HEAD~
git commit -- modules/frontend-js-web
git commit -- modules
```

**Comment by kresimir-coko** [comment]
@wincent On it!

**Comment by kresimir-coko** [comment]
ci:test:relevant

**Comment by kresimir-coko** [comment]
@wincent It's 🟢 should be reviewable

**Comment by jbalsas** [comment]
ci:forward

**Pull request closed without merging**
