### PR TITLE
LPS-134166 - Update @liferay/npm-scripts to v46.0.1 and fix new lint errors

### PR DESCRIPTION
**Pull request by bryceosterhaus**
https://issues.liferay.com/browse/LPS-134166

This updates npm-scripts to use the new eslint-config which introduces three new rules

-   feat(eslint-config): Add lint to catch common abbreviations ([\#564](https://github.com/liferay/liferay-frontend-projects/pull/564))
-   feat(@liferay/eslint-config): add rule to prevent developers from using createPortal directly from react-dom. ([\#575](https://github.com/liferay/liferay-frontend-projects/pull/575))
-   feat(eslint-config): Enable spaced-comment rule ([\#567](https://github.com/liferay/liferay-frontend-projects/pull/567))

### CODE REVIEW

**Comment by bryceosterhaus** [comment]
ci:test:sf

**Comment by bryceosterhaus** [comment]
ci:test:sf

**Comment by bryceosterhaus** [comment]
ah yes, the joys of SF passing locally and then failing on ci.

**Comment by bryceosterhaus** [comment]
ci:test:sf

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by nhpatt** [comment]
SF ⬇️

**Comment by bryceosterhaus** [comment]
@nkkwon Could you check out these test failures? They seem flakey and similar to flakey tests we ran into yesterday.

**Comment by bryceosterhaus** [comment]
ci:test:sf

**Comment by bryceosterhaus** [comment]
ci:test:sf

**Comment by bryceosterhaus** [comment]
ci:test:sf

**Comment by bryceosterhaus** [comment]
ci:test:sf

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
ci:reevaluate:1257401_1479

**Comment by bryceosterhaus** [comment]
@nkkwon I fixed the ones you mentioned above and re-ran the tests. I just went through this new set of failures and can't quite pinpoint what the issue is. Can you help verify again for me?

**Comment by nkkwon** [comment]
Just started reviewing!

**Comment by nkkwon** [comment]
**Analysis Details**
@bryceosterhaus  These failures seem to be CI flaky issues and I've also tried testing these and they pass locally for me. Looks good to manually forward!

**Comment by bryceosterhaus** [comment]
Thanks @nkkwon!

Manual forward at https://github.com/brianchandotcom/liferay-portal/pull/103346

**Pull request closed without merging**
