### PR TITLE
LPS-135071 Solve REST conflicts using an Object Definition Registry

### PR DESCRIPTION
**Pull request by javierdearcos**

### CODE REVIEW

**Review by nhpatt — APPROVED** [review]

**Comment by javierdearcos** [comment]
ci:forward

**Comment by javierdearcos** [comment]
ci:forward

**Comment by javierdearcos** [comment]
ci:forward

**Comment by javierdearcos** [comment]
ci:stop

**Comment by javierdearcos** [comment]
ci:forward

**Comment by javierdearcos** [comment]
ci:stop

**Comment by javierdearcos** [comment]
Already merged in the GraphQL follow up PR, that was forwarded erlier

**Pull request closed without merging**
