### PR TITLE
LPS-167672: Ensure panel collapse listener is unregistered on navigate event

### PR DESCRIPTION
**Pull request by matthiasblaesing**
The problem was observed in the documents and media administration panel: Every time the detail view of a file is opened a new collapse state save handler is registered. These handlers need to be unregistered when a navigation event happens.

### CODE REVIEW

**Comment by boton** [comment]
ci:test:sf

**Comment by matthiasblaesing** [comment]
@boton I can't access the test results, so I don't know if there are problematic results in them or if they just need a restart (which I also can't do). Could you have a look?

**Comment by boton** [comment]
ci:test:relevant

**Comment by boton** [comment]
@matthiasblaesing it looks like the failures aren't related to your changes, I relaunch the test suit 🤞

**Comment by matthiasblaesing** [comment]
@boton The result from the test was recorded as failure, but from the few fragments I can read this looks like a timeout error. Would you mind having a look and if necessary restart the test?

**Comment by boton** [comment]
ci:test:relevant

**Comment by matthiasblaesing** [comment]
@boton could you have another look? If it helps, I can rebase the changes onto current master and I can also look into test errors, if I know, that they exists.

**Comment by boton** [comment]
ci:test:relevant

**Comment by matthiasblaesing** [comment]
@boton could you please check again?

**Comment by boton** [comment]
ci:reevaluate:1307401_5379

**Comment by matthiasblaesing** [comment]
@boton not sure what to make from the CI bot reply. My understanding is, that the liferay CI system runs tests in multiple branches and fails in PRs, that are also present in the upstream branch are to be ignored. So a reevaluation should only compare results, which should be fast.

So either there is an error the CI system considers real or something else is fishy. Sorry that I have to bother you again.

**Comment by deborasoliveira** [comment]
ci:test:relevant

**Comment by deborasoliveira** [comment]
@matthiasblaesing and @boton I took a look at the errors and they seem unrelated to the PR, according to the [comparison](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=2&testrayRunIdB=2068954006&testrayRunIdA=2070187202&statusB=3).
Some of the failures came from tests that were aborted, and the others seem to be related to tests that need to be fixed. If no other dev review is needed you can manually forward it. 👍🏽 

cc: @mateusralv

**Comment by boton** [comment]
@deborasoliveira LGTM but impacts across the portal I prefer that someone at @liferay-frontend review the code. 
Thank you, guys!

**Review by markocikos — APPROVED** [review]
LGTM!

**Comment by markocikos** [comment]
ci:forward

**Comment by markocikos** [comment]
ci:forward

**Comment by mateusralv** [comment]
Hi @markocikos and @matthiasblaesing safe to forward manually from QA perspective, can I forward your PR?

**Comment by markocikos** [comment]
Manual forward: https://github.com/brianchandotcom/liferay-portal/pull/126983

**Comment by boton** [comment]
@matthiasblaesing thanks you for your contribution and your patience ❤️ 
Sorry again for the delay.

**Comment by matthiasblaesing** [comment]
@boton @mateusralv @markocikos thank you all for helping getting this in.

**Pull request closed without merging**
