### PR TITLE
LPS-189049 Turn data set app data model into system objects

### PR DESCRIPTION
**Pull request by dsanz**
Rebased followup of https://github.com/liferay-frontend/liferay-portal/pull/3508

In this PR we are changing the way we create the object definitions supporting dataset manager persistence model. We are using System object definitions now.

This has implications in:
* The API we use to create the definitions
* The naming of the headless endpoints (context path)
* The naming of the object definitions themselves, which affects how we calculate the class name in various places

Other notes:
* There is no upgrade process as application is under FF
* We are not renaming the object definitions to the UI/user friendly abstractions and therefore the endpoint names don't change (just the context path does)

### CODE REVIEW

**Comment by dsanz** [comment]
ci:test:stable

**Comment by dsanz** [comment]
@mateusralv as we agreed I'm rebasing this without the baseline commit

**Comment by dsanz** [comment]
@mateusralv we already have the results, pls check relevant, thanks a lot!

**Comment by mateusralv** [comment]
I'm on it 🏃🏽

**Comment by mateusralv** [comment]
Hi @dsanz We have no related failures. The failure related to the version we talked about yesterday seems to have been fixed and is not present here.

[Testray comparison](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1688478415497&testrayRunIdA=2369774879&testrayRunIdB=2369811686)

**Comment by dsanz** [comment]
ci:forward:force

**Pull request closed without merging**
