### PR TITLE
[7.4-Only]LPS-125350 Fix js width on sidebars

### PR DESCRIPTION
**Pull request by edalgrin**
Remove the JS script that set the sidebar to a fixed value. We don't need it with the [new classes](https://github.com/brianchandotcom/liferay-portal/pull/96511).

ezgif com-gif-maker (2)

### CODE REVIEW

**Comment by wincent** [comment]
Yay for deleting code. Linter says you can delete even more:


```
     [exec] \$ liferay-npm-scripts check
     [exec] Prettier checked 1 file
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/frontend-js/frontend-js-web/src/main/resources/META-INF/resources/liferay/side_navigation.es.js
     [exec]   466:9  error  'body' is assigned a value but never used.  no-unused-vars
     [exec]   467:9  error  'header' is assigned a value but never used.  no-unused-vars
     [exec]   472:9  error  'width' is assigned a value but never used.  no-unused-vars
```

**Comment by edalgrin** [comment]
ci:test:sf

**Comment by jbalsas** [comment]
Hey @edalgrin, if I'm not mistaken, this was added recently in https://github.com/liferay-frontend/liferay-portal/pull/651 to fix [Side navigation width transition causes strange text wrapping behavior](https://issues.liferay.com/browse/LPS-125214)

Can you confirm that the linked LPS does not regress after this?

If this issue is bigger than the other one we can go this way, but then need to figure out another solution for the other bug.

**Comment by edalgrin** [comment]
ci:test:relevant

**Comment by edalgrin** [comment]
> Hey @edalgrin, if I'm not mistaken, this was added recently in #651 to fix [Side navigation width transition causes strange text wrapping behavior](https://issues.liferay.com/browse/LPS-125214)
> 
> Can you confirm that the linked LPS does not regress after this?
> 
> If this issue is bigger than the other one we can go this way, but then need to figure out another solution for the other bug.

Right, this fix is nullifying the previous one. I'm going to put it on hold and take a second look

**Comment by jbalsas** [comment]
Hey @holatuwol, I think this issue is more significant that the one we addressed in https://github.com/liferay-frontend/liferay-portal/pull/651 so I'd lean towards reverting and then figuring out a different (or better approach for the first one).

Is this something you need to deliver for a customer so you'd rather we work the opposite way?

**Comment by edalgrin** [comment]
This fixes the sidebar of the image uploader, but consider this a temporary fix, we will need to review the current structure
ezgif com-gif-maker (5)

**Comment by edalgrin** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
Nice!! 👏

**Comment by marcoscv-work** [comment]
Works fine!

**Comment by pyoo47** [comment]
ci:test:relevant

**Comment by holatuwol** [comment]
> Is this something you need to deliver for a customer so you'd rather we work the opposite way?

@jbalsas We need to fix [LPS-125214](https://issues.liferay.com/browse/LPS-125214) for a customer trying to upgrade to 7.3, but since it's a cosmetic bug, it's not critical enough that we give them a fix with a known regression. It looks like @edalgrin has already found a fix that addresses it without causing the [LPS-125350](https://issues.liferay.com/browse/LPS-125350) regression, though, so thanks!

**Comment by jbalsas** [comment]
ci:forward

**Pull request closed without merging**
