### PR TITLE
LPS-186438 Show FDS View name instead of ID in fragment configuration selection

### PR DESCRIPTION
**Pull request by markocikos**
### References

- [LPS-172403 Create a fragment to show a dataset view](https://issues.liferay.com/browse/LPS-172403)
- [mockups](https://www.figma.com/file/9dL05nj2eXEM4dRIiPC2cP/lps-172443-design-fragment-to-expose-datasets?type=design&node-id=353-257097&t=wgUpCssXzu0EHdSD-0)

### What is the goal of this PR?

In fragment configuration, selected entity is presented as its title field. In objects, we can set which fields is a title field by setting `titleObjectFieldIs`. By default, this is the `id` field. In this PR, we are setting it to be the `label` field. Unfortunately, there is no API to set this as a part of `addCustomObjectDefinition()`, but we can set it separately, with `ObjectDefinitionLocalService`.

### What does it look like?

screen

### CODE REVIEW

**Comment by deborasoliveira** [comment]
The failures are unrelated to the PR according to the [comparison](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1686764627214&testrayRunIdA=2350780709&testrayRunIdB=2351096043).

**Comment by izaera** [comment]
@markocikos I've been set as reviewer, however I've never used `Objects`, so you probably know better than me about this stuff :shrug:

**Comment by markocikos** [comment]
ci:test:relevant

**Comment by markocikos** [comment]
@dsanz can we push this?

**Comment by markocikos** [comment]
ci:test:relevant

**Review by dsanz — APPROVED** [review]

**Comment by markocikos** [comment]
ci:forward

**Comment by markocikos** [comment]
ci:forward

**Pull request closed without merging**
