### PR TITLE
LPS-134678 DM Management toolbar Clear button doesn't completely clear

### PR DESCRIPTION
**Pull request by boton**
Hi @liferay-frontend,

This PR fixes a problem with the `Clear` button on the management toolbar of Documents and media.

https://issues.liferay.com/browse/LPS-134678

> When selecting multiple items in documents and media the Clear button produces a bug that in some cases doesn't de-select some of the items.

**How to test it**

1. Go to documents and media
2. Upload multiple documents or images to fill different pages 
3. Select 1 item on the first page using the checkbox in the card
4. Navigate to another page of the documents (page 2 for example)
5. Select some items
6. Click on the "Clear" action
7. Go back to Page 1

**Before this PR:**
The first item that was selected is still selected

https://user-images.githubusercontent.com/67901/124790587-91683900-df4b-11eb-947f-c443e974f9eb.mp4

**After this PR:**
The whole selection should've been cleared

https://user-images.githubusercontent.com/67901/124790808-c6748b80-df4b-11eb-8e4f-8e21c67d6511.mp4

---

I'm assuming when the `Clear` button is rendered, we always want to clear all items in the search container.

Could you please check my PR?

### CODE REVIEW

**Comment by boton** [comment]
ci:test:sf

**Comment by boton** [comment]
ci:test:relevant

**Comment by boton** [comment]
ci:test:relevant

**Comment by julien** [comment]
@boton just so you know, the failing test is similar to the one reported in #1224 so I'm assuming it's not related to your changes. Apart from that, the changes look OK to me.

**Comment by julien** [comment]
ci:test:relevant

**Comment by boton** [comment]
ci:test:relevant

**Comment by nhpatt** [comment]
ci:test:relevant

**Review by markocikos — APPROVED** [review]
LGTM!

**Comment by markocikos** [comment]
ci:forward

**Comment by markocikos** [comment]
Let me try forwarding one more time. The CI failure looks very much unrelated. @john-co @zhangyan0701 @nkkwon @Esther-OC    

The PR is very safe, we can manually forward.

**Comment by markocikos** [comment]
ci:forward

**Comment by diegonvs** [comment]
ci:forward

**Comment by markocikos** [comment]
@john-co @zhangyan0701 @nkkwon @Esther-OC I'd like to avoid manual forwarding, since we are in stabilization phase for GA. This is a bugfix of a minor issue, so there is no rush to merge the fix. From CI failures above, we can ignore semver failures, but it looks like `ClaySelect#SmokeRegularSelect` failure is persistent. This to me looks like a bug in CI tests of a relevant module. Please take a look!

**Comment by zhangyan0701** [comment]
Hi @markocikos 

We have a ticket for the test failure https://issues.liferay.com/browse/LRQA-68607, I will take a look at it and find out a fix.

**Comment by zhangyan0701** [comment]
I send a fix in https://github.com/liferay-frontend/liferay-portal/pull/1255, once it gets merged, we can run test again.

**Comment by markocikos** [comment]
ci:forward

**Comment by markocikos** [comment]
ci:stop

**Pull request closed without merging**
