### PR TITLE
LPS-102105 Adds classes `nav-item` and `nav-link` to `li` and `a` ele…

### PR DESCRIPTION
**Pull request by pat270**
…ments in product menu due to removal of compat nav styles

Caused by https://issues.liferay.com/browse/LPS-102105. This updates product menu `li` and `a` elements to use Clay 3 classes. Removing styled theme compat nav layer caused links to be too small.

### CODE REVIEW

**Comment by marcoscv-work** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcoscv-work** [comment]
ci:test:relevant

**Comment by marcoscv-work** [comment]
LGTM

image

**Review by marcoscv-work — APPROVED** [review]

**Comment by jbalsas** [comment]
Forwarded manually to https://github.com/brianchandotcom/liferay-portal/pull/97245

**Pull request closed without merging**
