### PR TITLE
[7.4.x-only][LPS-121722,LPS-121723,LPS-121724,LPS-121727,LPS-121728] Removes Internet Explorer Support (Part I)

### PR DESCRIPTION
**Pull request by jbalsas**
This is an initial bulk of work towards removing IE support from DXP 7.4 and simplify some of our build or default infrastructure by getting rid of unnecessary elements.

This initial pass includes:
* [Removing the `frontend-compatibility` app that added most of the polyfills needed by IE to work properly](https://github.com/liferay-frontend/liferay-portal/commit/0b7ef02c04db04d52bc6d0e519053277e5d18348)
* Removing unnecessary filters like [`SPAFilter`](https://github.com/liferay-frontend/liferay-portal/commit/0b483590b2160d1255fbf96c2d17ca31950983e4) or [`JSONContentTypeFilter`](https://github.com/liferay-frontend/liferay-portal/commit/b12749337f986888521fbb4fe07c872cc60e4cfa)
* Removing unnecessary [`<picture>`](https://github.com/liferay-frontend/liferay-portal/commit/5a3c245af6dafd418024fb5bf776c93c3d2d2de6) polyfill. /cc @liferay-lima
* Removing no longer useful [SPA IE configurations](https://github.com/liferay-frontend/liferay-portal/commit/ee9df382b0148b449a8b4c52b74f7956060ee620)

**Test Plan**
Since this is mostly a removal of IE specific code, the expectation is that nothing is affected and tests (not in IE) work as expected. This will likely make IE tests start to fail in CI in Windows. For that, @john-co has already requested to [Install another browser on Win2016 machines](https://issues.liferay.com/browse/LRCI-1762) as part of [Request removal of IE11 from CI environment testing](https://issues.liferay.com/browse/LPS-122115)

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:test:sf

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
I checked manually... things are apparently working and IE configuration options are no longer present in the SPA configuration screen.

Based on @bryceosterhaus joy tears and the various rocket reactions which we all know that

shipit

**Comment by jbalsas** [comment]
ci:forward

**Comment by wincent** [comment]
What a cliff-hanger... I can't wait to see Part 2.

**Comment by jbalsas** [comment]
> What a cliff-hanger... I can't wait to see Part 2.

Let's see if the channel renews this for a second season!

**Comment by jbalsas** [comment]
Updated the title to reflect that this is `7.4.x-only` and forwarding again.

**Comment by jbalsas** [comment]
ci:forward

**Comment by jbalsas** [comment]
> Closed pull request will not be forwarded.

Should've seen that coming... 🤷

**Comment by jbalsas** [comment]
ci:forward

**Pull request closed without merging**
