### PR TITLE
LPS-136119 We can't open panel elements when the table toolbar is re-rendered

### PR DESCRIPTION
**Pull request by markocikos**
Fixes: https://issues.liferay.com/browse/LPS-136119

See details and steps to reproduce in https://github.com/liferay/liferay-ckeditor/pull/188

We fixed the issue in https://github.com/liferay/liferay-ckeditor/pull/188. Newly released version of ckeditor is 4.16.1-liferay.4, we are updating it in this PR. Along with it, we are removing the code that was inadequate to fix the bug, and prevents the solution in latest ckeditor to work correctly.

### CODE REVIEW

**Review by nhpatt — APPROVED** [review]

**Comment by nhpatt** [comment]
LGTM :D

**Review by diegonvs — APPROVED** [review]
Tested with BGColor, Table Headers and Text formatting combo and Table elements panels and everything is working well.

**Comment by markocikos** [comment]
ci:stop

**Comment by markocikos** [comment]
ci:forward

**Comment by markocikos** [comment]
@john-co This `BlogsEntry#CanAddWithSubtitle` failure has been failing for a few days now. It is unrelated to his PR, happening for example in https://github.com/liferay-frontend/liferay-portal/pull/1298 and https://github.com/liferay-frontend/liferay-portal/pull/1344 as well. Can you please take a look? :pray: 

`WYSIWYGUsecase#AddWebContentArticleWithImageViaURL` is new from today, may be because of manual forward over above error :disappointed:

**Comment by john-co** [comment]
Just started reviewing :)

**Comment by john-co** [comment]
Reviewed. Test failures are unrelated. :heavy_check_mark:

Can manually forward.

[Not related] 
- [LocalFile.BlogsEntry#CanAddWithSubtitle](https://testray.liferay.com/home/-/testray/cases/1552500970) has been failing since beginning of testray history introduced on Aug 10. For some reason there's no upstream test result to compare, so it's being incorrectly tagged as unique. Recommend quarantine. cc/ @austinchiang @Hanlf @Jeremy-Ch @liuxingye 
- [WYSIWYGUsecase#AddWebContentArticleWithImageViaURL](https://testray.liferay.com/home/-/testray/cases/1311052806) looks flaky. The image hasn't fully loaded before the test tries to assert the image is present. Will need to further investigate

**Comment by liuxingye** [comment]
@john-co thank you for bringing this up, will fix it on head.

**Pull request closed without merging**
