### PR TITLE
LPS-129364 Update Clay dependencies

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
### Bug Fixes

-   **@clayui/date-picker:** Date Navigation Controls are wrong color. This adds clay css classes but also leaves btn-monospaced and btn-sm just incase. ([850286e](https://github.com/liferay/clay/commit/850286e))
-   **@clayui/date-picker:** disable focus control using the arrow keys ([d21dd7d](https://github.com/liferay/clay/commit/d21dd7d))
-   **@clayui/date-picker:** Removes `btn-sm` and `btn-monospaced` from Date Navigation controls. They're not needed. ([e70ad3c](https://github.com/liferay/clay/commit/e70ad3c))

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
ci:stop

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Review by wincent — APPROVED** [review]
Such a cute release!

kitten

I'd say forward it as soon as we see it green.

**Comment by ambrinchaudhary** [comment]
ci:stop

**Comment by ambrinchaudhary** [comment]
ci:close

**Comment by ambrinchaudhary** [comment]
ci:reopen

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
ci:test:relevant

**Comment by michaelhashimoto** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
unrelated  baseline error, trying again...

**Comment by ambrinchaudhary** [comment]
ci:forward

**Pull request closed without merging**
