### PR TITLE
[7.4-only] LPS-121975 Replace vertical-card-v2 with vertical-card

### PR DESCRIPTION
**Pull request by carloslancha**
__IMPORTANT: THIS PR IS NOT TO BE FORWARDED BUT SENT TO ECHO TEAM__

Replacing old vertical-card and horizontal-card tag uses in trash-web.

Adding support for defaultEventHandler transformation so it can accept either items or actions.

Before
image

After
image

### CODE REVIEW

**Comment by carloslancha** [comment]
ci:test:sf

**Comment by carloslancha** [comment]
ci:test:relevant

**Review by julien — APPROVED** [review]
This PR is not horrible :heart:

**Review by markocikos — APPROVED** [review]
LNHTM! :+1:

**Comment by julien** [comment]
Forwarded to https://github.com/liferay-echo/liferay-portal/pull/2957

**Pull request closed without merging**
