### PR TITLE
LPS-180479 Test Fix + Prevent aui:a to render shortcut icon if there is already …

### PR DESCRIPTION
**Pull request by mateusralv**
…an icon setup

### CODE REVIEW

**Comment by mateusralv** [comment]
ci:test:sf

**Comment by mateusralv** [comment]
ci:test:relevant:nocompile

**Comment by mateusralv** [comment]
ci:test:relevant

**Comment by mateusralv** [comment]
ci:test:sf

**Comment by mateusralv** [comment]
ci:test:relevant

**Comment by dsanz** [comment]
I'm closing this one as work seems to be happening in https://github.com/liferay-frontend/liferay-portal/pull/3202, if that's not the case, pls feel free to reopen it

**Pull request closed without merging**
