### PR TITLE
[WIP][7.4-Only] LPS-132927 and LPS-132928 Remove/Update generic_portal and generic_portlet not longer needed classes

### PR DESCRIPTION
**Pull request by marcoscv-work**
How to test this PR?

- Go to `/modules/apps/frontend-css/frontend-css-web` and `gradlew deploy -a`
- Then go to `/modules/apps/frontend-theme/frontend-theme-classic` and `gradlew deploy -a`
- Then go to `/modules/apps/frontend-theme/frontend-theme-admin` and `gradlew deploy -a`

### Now you should not see any difference in portal styles
---
This PR does not include deletions or movements to styled theme

### CODE REVIEW

**Comment by marcoscv-work** [comment]
Updated with "moving styles to style theme when needed".

Added LPS-132932

**Comment by marcoscv-work** [comment]
ci:test:sf

**Comment by marcoscv-work** [comment]
ci:test:sf

**Comment by marcoscv-work** [comment]
sf:test:sf

**Comment by marcoscv-work** [comment]
ci:test:sf

**Comment by edalgrin** [comment]
Just started reviewing :)

**Comment by edalgrin** [comment]
Continuing in https://github.com/liferay-frontend/liferay-portal/pull/1154

**Pull request closed without merging**
