### PR TITLE
[LPS-121931] Removes clay:table and already removed Clay Soy tags

### PR DESCRIPTION
**Pull request by jbalsas**
This PR removes `clay:table` and most of its supporting code.

The tag duplicates most of the features of `clay:dataset-display` which we want to enforce moving forward, so getting rid of a complex tag such as `clay:table` which never got any usage should help us concentrate on improving and standardizing on the new one.

To wrap up the [Remove unused JSP tags](https://issues.liferay.com/browse/LPS-112476), this PR also includes:
- Breaking changes announcement for all tags removed within the epic
- Removal of already removed `clay:*` soy tags. The tags are still available but backed by a different Java class. This potentially only breaks binary compatibility since the components are still available and we don't expect people to extend our Java Tag classes.

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:test:sf

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
@izaera, could you take a quick look at this, please?

**Comment by jbalsas** [comment]
Obviously unrelated failures... let's try again to see if we can forward this :(

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by izaera** [comment]
LGTM.

Deleting is always healthy and fun :tada:

**Comment by jbalsas** [comment]
Don't be shy to forward it next time then! ;)

**Comment by jbalsas** [comment]
ci:forward

**Comment by carloslancha** [comment]
<a href="https://gitme.me/image?url=https%3A%2F%2Fmedia3.giphy.com%2Fmedia%2FZxomYqy9uGtSQSSjth%2Fgiphy.gif&token=burn" data-gitmeme-token="burn"></a>

**Pull request closed without merging**
