### PR TITLE
LPS-137425 LPS-136998 Update liferay-ckeditor to 4.16.2-liferay.1

### PR DESCRIPTION
**Pull request by diegonvs**
It includes fixes to the following tickets:

https://issues.liferay.com/browse/LPS-136998
https://issues.liferay.com/browse/LPS-137425

# Changelog:

## [v4.16.2-liferay.1](https://github.com/liferay/liferay-ckeditor/tree/v4.16.2-liferay.1) (2021-08-18)

[Full changelog](https://github.com/liferay/liferay-ckeditor/compare/v4.16.1-liferay.4...v4.16.2-liferay.1)

### :wrench: Bug fixes

-   fix: LPS-137425 Focusing on balloon editor toolbar may open an additional text toolbar ([\#189](https://github.com/liferay/liferay-ckeditor/pull/189))
-   fix: Maximize plugin breaks the UI in Firefox ([\#187](https://github.com/liferay/liferay-ckeditor/pull/187))

/cc @NemethNorbert @markocikos

### CODE REVIEW

**Review by julien — APPROVED** [review]
Looks good to me - just a small detail, you forgot to edit the latest release over [here](https://github.com/liferay/liferay-ckeditor/releases)

**Review by markocikos — APPROVED** [review]
Thanks for making this release, and :+1: for bumping up base version :hugs: 

Note to self: don't forget to update lockfile next time :confounded: (I made the previous update to `4.16.1-liferay.4`)

**Comment by diegonvs** [comment]
> Looks good to me - just a small detail, you forgot to edit the latest release over here

Oops, thanks for remembering Julien!

> Thanks for making this release, and 👍 for bumping up base version 🤗

**Comment by diegonvs** [comment]
ci:test:relevant

**Comment by julien** [comment]
> Oops, thanks for remembering Julien! See https://github.com/liferay/liferay-ckeditor/releases/tag/v4.16.2-liferay.1
 @diegonvs no worries, always lots of things to do :smile:  Looks all good thanks!

**Comment by markocikos** [comment]
ci:forward

**Pull request closed without merging**
