### PR TITLE
LPS-167272 Update alloy-ui to 3.1.0-deprecated.108

### PR DESCRIPTION
**Pull request by markocikos**
## What's Changed
* fix: LPS-167272 Multiple events are being read in reverse order by @markocikos in https://github.com/liferay/liferay-frontend-projects/pull/1052
* fix: LPS-167272 set correct aria label for the next month button by @markocikos in https://github.com/liferay/yui3/pull/32

## New Contributors
* @markocikos made their first contribution in https://github.com/liferay/liferay-frontend-projects/pull/1052

**107 Changelog**: https://github.com/liferay/liferay-frontend-projects/compare/npm-scripts/v47.10.2...alloy-ui/v3.1.0-deprecated.107
**108 Changelog**: https://github.com/liferay/liferay-frontend-projects/compare/alloy-ui/v3.1.0-deprecated.107...alloy-ui/v3.1.0-deprecated.108

### CODE REVIEW

**Comment by mateussandes23** [comment]
ci:test:relevant

**Comment by mateussandes23** [comment]
Hey @markocikos , can you take a look on this modules that are failing?

[Testray comparison](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=2&testrayRunIdB=2131961272&testrayRunIdA=2131991826&statusB=3)

I rerun the relevant again but it fail again.

cc/ @john-co @mateusralv

**Comment by markocikos** [comment]
I'll try one or two forwards, manually forward after. It's going to be tough to pass, PR is safe but affects a lot a modules :slightly_smiling_face:

**Comment by markocikos** [comment]
ci:forward

**Comment by markocikos** [comment]
ci:forward

**Comment by markocikos** [comment]
Manual forward in https://github.com/brianchandotcom/liferay-portal/pull/127924

**Pull request closed without merging**
