### PR TITLE
[7.4+][PART 2] LPS-134071 Migrate frontend-theme-styled CSS

### PR DESCRIPTION
**Pull request by edalgrin**
This PR removes all the unused and third-party CSS from `frontend-theme-styled`
- [Original PR](https://github.com/liferay-frontend/liferay-portal/pull/1877#issuecomment-1064926374)
- [Strategy](https://liferay.atlassian.net/wiki/spaces/ENGFRONTENDINFRA/pages/1341882669/LPS-127086+-+Analyze+and+prototype+possible+theme+optimizations?focusedCommentId=1969652346#comment-1969652346)
- [Changelog](https://docs.google.com/spreadsheets/d/1IG7o3hAn9w91-sg_vXQZeWhJsRBSSMTrGUi-EVfQ6H8/edit#gid=0)
- [Module testing](https://docs.google.com/spreadsheets/d/1IG7o3hAn9w91-sg_vXQZeWhJsRBSSMTrGUi-EVfQ6H8/edit#gid=1130153366)

### CODE REVIEW

**Comment by edalgrin** [comment]
@john-co @Esther-OC , please tell me this is an error! it doesn't make any sense, it's the same PR I sent before and passed the tests! https://github.com/liferay-frontend/liferay-portal/pull/1998#issuecomment-1070541723

**Comment by Esther-OC** [comment]
image

**Comment by Esther-OC** [comment]
There are 4 unique failures: [comparison with upstream](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=3&testrayRunIdB=1644782382&testrayRunIdA=1645590715&statusB=2)

1. [modules-semantic-versioning-jdk8/0/0](https://testray.liferay.com/home/-/testray/case_results/1645600501) --> is failing in this and other PRs
2. [com.liferay.portal.workflow.kaleo.internal.runtime.integration.test.WorkflowTaskManagerImplTest](https://testray.liferay.com/home/-/testray/case_results/1645600929) --> related to the PR.
3. [LocalFile.FormsMultipleSelectionField#OptionsCanBeReordered](https://testray.liferay.com/home/-/testray/case_results/1645596314) --> "Failed prior to running test" but only happens in this PR, so probably related to it.
4. [LocalFile.CPCommerceProducts#ConfigureVirtualProduct](https://testray.liferay.com/home/-/testray/case_results/1645590872) --> seems flaky, as it is a window exception for a page that does not load.

So, in my opinion, we have to focus on issues 2 and 3, at least to start with them.

**Comment by john-co** [comment]
ok to manually forward from QA perspective. Are you still waiting for dev review @edalgrin?

**Comment by john-co** [comment]
@edalgrin , to explain why you may see CI tests pass on one run vs another run. It's due to functional tests and CI being flaky. Some of these are out of QA's and any person's control. We do our best to try to reduce our encounters of false positives. Please keep pinging QA if need review of PR tests.

Reasoning from stats and numbers: https://github.com/liferay-frontend/liferay-portal/pull/2006#issuecomment-1068317969

This PR's `ci:test:relevant` ran close to 2000 tests so there's bound to be some test failures that are flukes or fail due to flakiness.

**Comment by john-co** [comment]
Unfortunately, the nature of FI work is that it touches on UI of all teams who implement the frontend infra. Due to how `ci:test:relevant` works, if a module is touched, we look at the `test.properties` of that module and the PQL adds tests to the test run. That's what we have to work with right now at a base level. 

All this is to say, FI PR's will likely fail and it forces us to have someone to manually filter out the noise by analyzing the tests (QA has taken this responsibility currently).

**Comment by MarinhoFeliphe** [comment]
Just started reviewing :)

**Comment by MarinhoFeliphe** [comment]
Hi @john-co,

I pulled these changes into a local branch to run all the WorkflowTaskManagerImplTest integration tests and there aren't failed tests.

Captura de tela de 2022-03-24 17-06-35

The Zulu team (workflow manager) will take a look at this falky test

Thank you!

**Comment by edalgrin** [comment]
Thank you all, I'll proceed with the manual forward.

**Comment by edalgrin** [comment]
Manual forwarded to https://github.com/brianchandotcom/liferay-portal/pull/115242

**Pull request closed without merging**
