### PR TITLE
LPD-35237 Remove unused dependency

### PR DESCRIPTION
**Pull request by markocikos**
### References

- Parent Epic: [LPD-34072 oauth2 dependencies security vulnerabilities](https://issues.liferay.com/browse/LPD-34072)

### What is the goal of this PR?

We didn't clean up this dependency after we moved FDS from from `frontend-taglib-clay` to its own app.

### CODE REVIEW

**Comment by markocikos** [comment]
ci:test:relevant

**Comment by markocikos** [comment]
ci:stop

**Comment by markocikos** [comment]
ci:test:sf

**Comment by markocikos** [comment]
ci:test:relevant

**Review by bryceosterhaus — APPROVED** [review]
I really have no clue what the dependency is even for... so if CI passes then it is good to me!

**Comment by markocikos** [comment]
ci:forward

**Pull request closed without merging**
