### PR TITLE
LPS-147849 Assert Filter and Order buttons render individual dropdown menus

### PR DESCRIPTION
**Pull request by susanchen3**
**Background**
Create automated tests for management toolbar. 

**Test Plan**
Given a user of the portal
When the user opens any section with the management toolbar
Then 'filter' and 'order' buttons will be independent dropdowns

**JIRA Ticket:**
https://issues.liferay.com/browse/LPS-147849

### CODE REVIEW

**Comment by susanchen3** [comment]
ci:test:frontend:nocompile

**Review by john-co — APPROVED** [review]
Looks good to me! :sunglasses: 

We're trying something out with applying our gherkin syntax that we created for test scenarios directly into the poshi tasks. Let's try using this continuing forward.

**Comment by john-co** [comment]
ci:forward

**Comment by john-co** [comment]
ci:forward

**Comment by john-co** [comment]
weird, `ci:test:relevant` shouldn't run if we're only modifying poshi files.

**Pull request closed without merging**
