### PR TITLE
LPS-156881 Using lowercase 'a' as object field name is displayed as '%A'

### PR DESCRIPTION
**Pull request by TaiPhamLR**
Motivation
=======
This work solves the problem reported in the [LPS-156881](https://issues.liferay.com/browse/LPS-156881) ticket.
My solution was accepted by the liferay-object team. PR: liferay-objects#818
cc: @sontruongces

Proposed Solution
========
What we did to solve this problem.
1. Disable localize label for aui:option in object_definition/details.jsp
2. Check isLocalizeLabel for objectField and nonObjectField.

Steps to Verify
========
1. Start a clean 7.4 update 28 bundle (or master)
2. Create an Object by navigating to control panel > objects > "+"
3. Edit the newly created Object
4. From the Fields tab, add a new field with the label "a" and any
5. From the Details tab, navigate to Entry Display and select the Title Field dropdown menu.

- Expected Results: There will be a title field named "a".
- Actual Results: There is a title field named "%A".

You can also view this issue by following these additional steps after step 4.
1. From the Details tab, enable Show Widget and click Publish
2. Go to the Home Page and edit it.
3. Navigate to the widget in the sidebar and add the newly created object from the Object section by dragging it on the page. Then click Publish.
4. From the Object portlet, create a new Object with the field and click Save and then Cancel to view the Object on the Home Page.

- Expected Results: There is a table column label named "a".
- Actual Results: There is a table column label named "%A".

### CODE REVIEW

**Comment by susanchen3** [comment]
ci:stop

**Comment by susanchen3** [comment]
ci:test:relevant

**Comment by susanchen3** [comment]
Reviewed, 1 test failure is related from QA perspective. 

@markocikos mind providing dev review as well? Thanks! :heart:  

Looks like a [version increase](https://testray.liferay.com/home/-/testray/case_results/1946345491) is required 
```
     [exec] > Task :apps:frontend-data-set:frontend-data-set-api:baseline
     [exec]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec] = ================================================== ========== ========== ========== ========== ==========
     [exec] * com.liferay.frontend.data.set.view.table           MINOR      7.1.0      7.1.0      7.2.0      VERSION INCREASE REQUIRED
     [exec] 	<   class      com.liferay.frontend.data.set.view.table.BaseDateFDSTableSchemaField
     [exec] 		+   method     isLocalizeLabel()
     [exec] 			+   return     boolean
     [exec] 		+   method     setLocalizeLabel(boolean)
     [exec] 			+   return     com.liferay.frontend.data.set.view.table.FDSTableSchemaField
     [exec] 	<   class      com.liferay.frontend.data.set.view.table.DateFDSTableSchemaField
     [exec] 		+   method     isLocalizeLabel()
     [exec] 			+   return     boolean
     [exec] 		+   method     setLocalizeLabel(boolean)
     [exec] 			+   return     com.liferay.frontend.data.set.view.table.FDSTableSchemaField
     [exec] 	<   class      com.liferay.frontend.data.set.view.table.DateTimeFDSTableSchemaField
     [exec] 		+   method     isLocalizeLabel()
     [exec] 			+   return     boolean
     [exec] 		+   method     setLocalizeLabel(boolean)
     [exec] 			+   return     com.liferay.frontend.data.set.view.table.FDSTableSchemaField
     [exec] 	<   class      com.liferay.frontend.data.set.view.table.FDSTableSchemaField
     [exec] 		+   method     isLocalizeLabel()
     [exec] 			+   return     boolean
     [exec] 		+   method     setLocalizeLabel(boolean)
     [exec] 			+   return     com.liferay.frontend.data.set.view.table.FDSTableSchemaField
     [exec] 	<   class      com.liferay.frontend.data.set.view.table.StringFDSTableSchemaField
     [exec] 		+   method     isLocalizeLabel()
     [exec] 			+   return     boolean
     [exec] 		+   method     setLocalizeLabel(boolean)
     [exec] 			+   return     com.liferay.frontend.data.set.view.table.FDSTableSchemaField
     [exec] [Baseline Warning] Bundle Version Change Recommended: 11.1.0
     [exec] [Baseline Report] Mode: diff (persisted)
     [exec] Semantic versioning is incorrect while checking /opt/dev/projects/github/liferay-portal/tools/sdk/dist/com.liferay.frontend.data.set.api-11.0.1.jar against /opt/dev/projects/github/liferay-portal/.gradle/caches/modules-2/files-2.1/com.liferay/com.liferay.frontend.data.set.api/11.0.0/5fdf7ee7a1c02e0a4bf4b01c71b289ca7e71ecc4/com.liferay.frontend.data.set.api-11.0.0.jar
```

**Comment by TaiPhamLR** [comment]
I have done rebase code and resolved the conflict. I'm still waiting for reviewing and merging by @markocikos.

**Review by markocikos — APPROVED** [review]
@TaiPhamLR  LGTM!

Sorry for extremely long review delay, I just returned from PTO. Honestly, somebody else could have taken the PR :sweat_smile: 

One nit with the code, naming of `localizeLabel`. It is a widely used attribute in DXP, so the solution is fine. It's a shame we didn't call it `labelLocalized`, verb attributes always result in awkward getters (`isLocalizeLabel`). But, it is what it is.

**Comment by markocikos** [comment]
ci:forward

**Comment by diegonvs** [comment]
ci:forward

**Comment by markocikos** [comment]
@TaiPhamLR You need to update semver, before we can forward this. Please run `gradle baseline` on `frontend-data-set-api`, and add version increase as an additional commit.

**Comment by markocikos** [comment]
@TaiPhamLR Also, please run `gradle baseline` on `object-api`, and add it as an additional commit. This is unrelated to this PR, but CI [fails on it](https://github.com/liferay-frontend/liferay-portal/pull/2637#issuecomment-1238689946). It's quite possible that somebody else will duplicate this change, but git should be smart enough to ignore your commit in that case.

**Comment by TaiPhamLR** [comment]
Hi @markocikos, I've run `gradle baseline` on `frontend-data-set-api` and create a new commit. I've also run `gradle baseline` on `object-api` after rebase code, but not affected.

**Comment by markocikos** [comment]
ci:forward

**Pull request closed without merging**
