### PR TITLE
LPS-158832 Rename "Remote Apps" to "Client Extensions"

### PR DESCRIPTION
**Pull request by edalgrin**
This PR changes the remote app menu name into "Client Extensions"

### CODE REVIEW

**Comment by edalgrin** [comment]
Hello @john-co @mateusralv , is this ok to forward or do you need to add some tests like you did in the other one? https://github.com/brianchandotcom/liferay-portal/pull/127523

**Comment by john-co** [comment]
I think it will need some test fixes.

**Comment by john-co** [comment]
yea...basically all the remote app tests need an update. Those that try to navigate to Remote Apps admin will be affected.

https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=2123014317&testrayRunId=2123014362

cc/ @mateusralv would you be able to add a test fix?

**Comment by john-co** [comment]
@edalgrin once we fix the tests, would you like us to forward this? Or are there other dev reviews needed?

**Comment by edalgrin** [comment]
Hey @john-co , feel free to forward, no dev reviews necessary for this one, thanks!

**Comment by mateusralv** [comment]
Yep @john-co, as soon as finished the fix, I update the PR, run the routines and, if everything is ok, I forward it. Thanks @edalgrin

**Comment by mateusralv** [comment]
Hey @edalgrin when you have time, could you add my [commits](https://github.com/mateusralv/liferay-portal/pull/30) to this PR? Thank you :D

**Comment by edalgrin** [comment]
> Hey @edalgrin when you have time, could you add my [commits](https://github.com/mateusralv/liferay-portal/pull/30) to this PR? Thank you :D

No problem!

(you already had the permissions, for the next time)
image

**Comment by edalgrin** [comment]
Continue in https://github.com/mateusralv/liferay-portal/pull/30

**Pull request closed without merging**
