### PR TITLE
COMMERCE-5695 Dataset Display update events now match

### PR DESCRIPTION
**Pull request by FabioDiegoMastrorilli**
This PR will fix a bug that occurs when commerce modules try to interact with the dataset. 
Those modules import an event definition which is different from the one in `frontend-taglib-clay` so the interaction does not work. 

This is a temp fix. For more info please see [this closed pr](https://github.com/liferay-frontend/liferay-portal/pull/810)

### CODE REVIEW

**Comment by jbalsas** [comment]
Hey @FabioDiegoMastrorilli, what's with:

```javascript
export const DATASET_ACTION_PERFORMED = 'data-set-action-performed';
export const DATASET_DISPLAY_UPDATED = 'data-set-display-updated';
```

Don't this also exist in the commerce definition? I think it would be good to also change these ones so they stay consistent and prevent future issues even if they're not being currently used.

**Comment by FabioDiegoMastrorilli** [comment]
Hi @jbalsas those ones you found already work because the content match. 
I'll make the string consistent across all of them using `dataset` (not `data-set`) everywhere. This makes me think the bug had already been found and fixed months ago (but not entirely)

Thanks for having a look at it

**Comment by FabioDiegoMastrorilli** [comment]
@jbalsas I've pushed the new changes. Please have a look :)

cc @riccardo-alberti

**Comment by wincent** [comment]
ci:test:relevant

**Comment by wincent** [comment]
My incredibly sophisticated review heuristic here is "if change is only 5 lines long, looks sane, and CI is green" would forward. So I've kicked off CI. `#WouldForwardAgain`

**Comment by wincent** [comment]
ci:forward

**Pull request closed without merging**
