### PR TITLE
LPS-185635 Upgrade ph-css and ph-commons

### PR DESCRIPTION
**Pull request by SelenaAungst**
Upgrade ph-css and ph-commons
https://issues.liferay.com/browse/LPS-185635
Based on https://issues.liferay.com/browse/PTR-3946

### CODE REVIEW

**Comment by deborasoliveira** [comment]
I'll take a look at it.

**Comment by deborasoliveira** [comment]
The failures seem to be unrelated to the PR according to the [comparison](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=2&testrayRunIdB=2328204806&testrayRunIdA=2327898350&statusB=3).
 I investigated the _modules-semantic-versioning-jdk8/0/0_ failure but it seems to be caused by a problem during its execution.

**Comment by izaera** [comment]
Looks good to me, @SelenaAungst :+1: Thx for the fix :-)

IIRC the upgrade of versions should make the parser work again, so you can forward this PR to Brian as soon as it is green or cleared by QA. So, if semantic versioning error is not related (as @deborasoliveira says [here](https://github.com/liferay-frontend/liferay-portal/pull/3390#issuecomment-1577415616)), feel free to run `ci : forward` :tada:

**Comment by izaera** [comment]
Yeah, semantic version error is not related. However test stable is red so `ci:forward:force` won't work until that's green...

I'll try again :crossed_fingers:

**Comment by izaera** [comment]
ci:forward:force

**Comment by izaera** [comment]
ci:stop

**Comment by izaera** [comment]
Hey @SelenaAungst , this seems stuck at `ci:stable` :roll_eyes:, so it's may never be forwarded to Brian...

Can you please close this PR and send it manually to Brian ? Thx ( it's the only solution I can think of :shrug: )

**Comment by SelenaAungst** [comment]
Thank you, @izaera!
Forwarded manually: https://github.com/brianchandotcom/liferay-portal/pull/135962

**Comment by izaera** [comment]
@SelenaAungst :sweat_smile: At last... Thx a lot :raised_hands:

**Pull request closed without merging**
