### PR TITLE
LPS-174293 Update packages `@clayui/*` to v3.86.0

### PR DESCRIPTION
**Pull request by matuzalemsteles**
### Bug Fixes

-   **@clayui/core:** announce item description when opening menu in Picker component ([7509ef7](https://github.com/liferay/clay/commit/7509ef7de1a7f07fc94e79446d9a3321f5fa9a06))
-   **@clayui/core:** fix `selection.toggle` typing error ([a61329f](https://github.com/liferay/clay/commit/a61329fb0e31f3b731fcb9e3cca52512c9010a86))
-   **@clayui/core:** fix Picker accessibility error on Apple devices with VoiceOver ([b3f56b2](https://github.com/liferay/clay/commit/b3f56b20e1c96f5547eda645b86fa95576168289))
-   **@clayui/css:** Empty State add bigger margin-bottom on image ([e19f587](https://github.com/liferay/clay/commit/e19f587da161c40a376228706f81c11086057f0c))
-   **@clayui/css:** Readd text-underline and add text-none ([5f7f691](https://github.com/liferay/clay/commit/5f7f691ff69b93ead8204eed674fbd43664cc105))
-   **@clayui/css:** Text decoration utility selector typo ([8970d78](https://github.com/liferay/clay/commit/8970d78574ac9a75897646b93603e768049eca0d))
-   **@clayui/date-picker:** Date Range should be selectable with a single click ([ecd4c94](https://github.com/liferay/clay/commit/ecd4c942617244df6797bc69d5659957f7590540))

### Features

-   **@clayui/core:** adds simple implementation for LiveAnnouncer ([cd0fd12](https://github.com/liferay/clay/commit/cd0fd12f92d6d4d8ebcf506b92360acbcb0522f2))

### CODE REVIEW

**Comment by matuzalemsteles** [comment]
cc @mateusralv

**Comment by eltonccdantas** [comment]
Hey @matuzalemsteles , I'll take a look at it, right?

**Comment by matuzalemsteles** [comment]
Thanks @eltonccdantas

**Comment by mateusralv** [comment]
Hi @matuzalemsteles Relevant returned many unique failures (+200) that don’t seem related, I will run again

**Comment by mateusralv** [comment]
ci:test:relevant

**Comment by eltonccdantas** [comment]
Hey @matuzalemsteles , I found some failures related to Adaptative Media, Data Engine and other components... However, I'm not sure whether they are on your PR or not, I'll run relevant again to be sure.


CC/ @john-co , @mateusralv 


here's the [comparison](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=2&testrayRunIdB=2182452492&testrayRunIdA=2182273229&statusB=3)

Please wait for further investigation 🕵🏻

**Comment by eltonccdantas** [comment]
ci:test:relevant

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by mateusralv** [comment]
Taking a look with @eltonccdantas

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by mateusralv** [comment]
The failures are not unique and unrelated 🎉 
[Testray Comparison](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=2&testrayRunIdB=2184795140&testrayRunIdA=2183964678&statusB=3)

**Comment by mateusralv** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/129678

**Pull request closed without merging**
