### PR TITLE
LPS-130585 Update @clayui/* dependencies to v3.35.3

### PR DESCRIPTION
**Pull request by julien**
## [3.35.3](https://github.com/liferay/clay/compare/v3.35.2...v3.35.3) (2021-09-09)

 ### Bug Fixes

 -   **@clayui/css:** Forms use fixed value for $input-height-inner, $input-height-inner-half, $input-height-inner-quarter to reduce Sass errors with CSS custom properties in $input-line-height and \$input-padding-y ([2fa8ca3](https://github.com/liferay/clay/commit/2fa8ca3)), closes [#4247](https://github.com/liferay/clay/issues/4247)

### CODE REVIEW

**Review by matuzalemsteles — APPROVED** [review]
LGTM! A small release ❤️

**Comment by julien** [comment]
@matuzalemsteles :smile: yes very small, but since I hadn't cut a clay release it was worth it.

**Comment by matuzalemsteles** [comment]
Yeah no problem, that's is cool 😁!

**Comment by julien** [comment]
@john-co when you get a chance, could you please let me know if those tests are related to these changes? Thanks

**Comment by matuzalemsteles** [comment]
Looking at the tests seem unrelated, I will run the test again just to check.

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by john-co** [comment]
Just started reviewing :)

**Comment by john-co** [comment]
Reviewed. Test failures are unrelated. :heavy_check_mark: 

- WorkflowUsecase#AddDDLRecordWithDoubleApproverDefinition - The test has failed on 2 other recent test runs with same error message. The error message seems similar to but not exactly: https://issues.liferay.com/browse/LPS-136162 cc/ @rodrigocunhaa

**Comment by matuzalemsteles** [comment]
Ok, I'll send this forward, it's a very small release and also the tests passed. @julien Could you post on confluence and advertise on the channel tomorrow? anything, you can ask Bruno to do this.

**Comment by matuzalemsteles** [comment]
ci:forward

**Comment by julien** [comment]
@matuzalemsteles thanks for taking care of forwarding, I'll get in touch with @brunofernandezg for the confluence announcement

**Pull request closed without merging**
