### PR TITLE
LPD-18507 clay:select tag should output a for attribute on label

### PR DESCRIPTION
**Pull request by pat270**
- when `clay:select` has an `id` attribute and `label`, it should output a `for`
      attribute on the `label` with the value of the `id`. It associates the `label`
      with the form element.

LPD-18507 Clay Sample add unique id's to form elements

https://liferay.atlassian.net/browse/LPD-18507

multiple-select

### CODE REVIEW

**Comment by pat270** [comment]
ci:test:relevant

**Comment by ethib137** [comment]
ci:test:clay

**Comment by ethib137** [comment]
@pat270 , it looks like this change broke [this test](https://testray.liferay.com/home/-/testray/case_results/2542428424?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2542428326%26testrayRunId%3D2542428366%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc). Can you add a fix. It might make sense to use a `data-qa-id` attribute so that it's explicit that this is being used for testing.

**Review by markocikos — APPROVED** [review]
@pat270 LGTM! :sparkles:

**Comment by pat270** [comment]
ci:test:clay

**Comment by pat270** [comment]
@markocikos @ethib137 I thought this would fix the original test failure, but I was wrong. [This test](https://testray.liferay.com/reports/production/logs/2024-02/test-1-26/test-portal-acceptance-pullrequest(master)/12797/functional-tomcat90-mysql57-jdk8/0/0/LocalFile.ClaySelect_MultipleCanBeConfigured/summary.html.gz) is still failing.

I think it's trying to look for a generated image? I'm not 100% sure. You guys have any insight on this?
https://github.com/liferay/liferay-portal/blob/master/portal-web/test/functional/com/liferay/portalweb/tests/enduser/frontendinfrastructure/uiinfrastructure/clay/ClaySelect.testcase#L71

**Comment by ethib137** [comment]
Hey @pat270 the test was failing due to an assertion that is throwing an error wherever it is called. I fixed it via the [parent ticket](https://liferay.atlassian.net/browse/LPD-17672). That fix is now in master, so if you rebase and run the test again everything should pass.

**Comment by ethib137** [comment]
This last test, looks like it rebased off master. The only failing tests are unrelated so this should be fine to forward since @markocikos approved the changes.

**Comment by ethib137** [comment]
ci:test:sf

**Comment by ethib137** [comment]
ci:test:relevant

**Comment by pat270** [comment]
ci:forward

**Comment by ethib137** [comment]
ci:forward:force

**Pull request closed without merging**
