### PR TITLE
LPS-146039 Use new key for pagination

### PR DESCRIPTION
**Pull request by sandrodw3**
Hi guys!
I'm sending this because we would like to update pagination text so it fits Lexicon doc: https://liferay.design/lexicon/core-components/pagination/
Could you please take a look?
Thanks! 🥰

### CODE REVIEW

**Comment by sandrodw3** [comment]
Hi guys!
I'm sending this because we would like to update pagination text so it fits Lexicon doc: https://liferay.design/lexicon/core-components/pagination/
Could you please take a look?
Thanks! 🥰

**Comment by carloslancha** [comment]
@julien would you mind take a look? LGTM but since you created this Tag I may be missing something. Thx!

**Review by julien — APPROVED** [review]
Thanks @sandrodw3 LGTM. Just out of curiosity did you check if the Clay component was using the same format? I can check later if you want, but I'd like to be sure it matches before forwarding this.

**Comment by sandrodw3** [comment]
> Thanks @sandrodw3 LGTM. Just out of curiosity did you check if the Clay component was using the same format? I can check later if you want, but I'd like to be sure it matches before forwarding this.

Hi @julien 🥰
If you mean the `ClayPaginationBar`, I think so, it has the same format: https://clayui.com/docs/components/pagination-bar/markup.html#clay-sidebar

**Comment by julien** [comment]
@sandrodw3 thanks for checking. As far as I'm concerned, this can be forwarded. I'll just ping @carloslancha to see if he has anything to add.

**Comment by carloslancha** [comment]
ci:forward

**Pull request closed without merging**
