### PR TITLE
LPD-37556 - Migrate and delete remaining tests in the FrontendDataSetClientExtension.testcase file

### PR DESCRIPTION
**Pull request by kresimir-coko**
This PR deletes the `FrontendDataSetClientExtension.testcase` because all tests have been covered by playwright

### CODE REVIEW

**Comment by kresimir-coko** [comment]
ci:test:sf

**Comment by kresimir-coko** [comment]
ci:test:relevant

**Comment by kresimir-coko** [comment]
ci:test:frontend

**Comment by kresimir-coko** [comment]
ci:report:39303856

**Comment by kresimir-coko** [comment]
Testray reports no unique failures

**Review by markocikos — APPROVED** [review]
@kresimir-coko LGTM! :sparkles:

**Comment by kresimir-coko** [comment]
ci:forward

**Pull request closed without merging**
