### PR TITLE
LPS-148928 | Add scroll and pause to stabilize tests

### PR DESCRIPTION
**Pull request by susanchen3**
**Background**
ManagementToolbar#ResponsiveModeNewButtonTooltip is failing inconsistently because the tooltip isn't being shown. Hopefully this will stabilize it. 

**JIRA Ticket:**
https://issues.liferay.com/browse/LPS-148928

### CODE REVIEW

**Comment by susanchen3** [comment]
ci:test:frontend:nocompile

**Comment by susanchen3** [comment]
still failing...

**Comment by susanchen3** [comment]
ci:test:frontend:nocompile

**Comment by susanchen3** [comment]
Or should I use a while loop like the A11yTool testcases? 
```
		task ("Hover over the new button") {
			while (IsElementNotPresent(locator1 = "Message#TOOLTIP")) {
				MouseOver(locator1 = "ManagementBar#NEW_BUTTON_MOBILE");
			}
		}
```
cc: @john-co

**Comment by john-co** [comment]
Just started reviewing :)

**Comment by john-co** [comment]
ci:forward

**Comment by john-co** [comment]
Let's push this in for now while long term solution is being discussed and follow up on this.

**Comment by susanchen3** [comment]
contacted ci about it, will try again after lunch

**Comment by susanchen3** [comment]
ci:forward

**Pull request closed without merging**
