### PR TITLE
LPS-128988 Update @liferay/npm-scripts to v39.0.1

### PR DESCRIPTION
**Pull request by wincent**
v39.0.1 fixes build breakages on Windows ([release notes](https://github.com/liferay/liferay-frontend-projects/releases/tag/npm-scripts%2Fv39.0.1)).

And v39.0.0 adds a number of new lints ([release notes](https://github.com/liferay/liferay-frontend-projects/releases/tag/npm-scripts%2Fv39.0.0)); I'll apply the autofixes for those in a separate commit to make it clear which part of the change is automated.

### CODE REVIEW

**Comment by wincent** [comment]
cc @izaera

**Comment by wincent** [comment]
Ticket to review new lint suppressions is: https://issues.liferay.com/browse/COMMERCE-6061

I'm not actually going to create one for the suppressions in `frontend-js-aui-web` because that is a legacy module that we will surely be deleting Real Soon Now™. 😂 (Specifically, there are about three `eval` calls in the beautifully named [`liferay/deprecated.js` file](https://github.com/liferay/liferay-portal/blob/86ede804ce42ff073f9e2dc1df708a8945cdeaad/modules/apps/frontend-js/frontend-js-aui-web/src/main/resources/META-INF/resources/liferay/deprecated.js#L57-L88), which we are unlikely to ever touch in a serious way again.)

**Comment by izaera** [comment]
LGTM

**Comment by wincent** [comment]
Given [discussion on Slack](https://liferay.slack.com/archives/C3JBR21HA/p1615466551265100?thread_ts=1615459885.255800&cid=C3JBR21HA), manual forward is here: https://github.com/brianchandotcom/liferay-portal/pull/99805

`ci:test:sf` is green, this is a largely automated change (which reduces our concern for human error), and this addresses an FP5 which is currently blocking Windows users from running `ant all`.

**Pull request closed without merging**
