### PR TITLE
[TS] LPS-131067 Remove redundant aria-labelledby attributes in Menu Navigation ADTs

### PR DESCRIPTION
**Pull request by dacousalr**
Hi team, please review this PR where I tried to apply the conclusions obtained in PTR-2396. If you think that this PR should be reviewed by some other team, please let me know. Thanks in advance

### CODE REVIEW

**Comment by dacousalr** [comment]
ci:test:sf

**Comment by dacousalr** [comment]
ci:test:relevant

**Comment by wincent** [comment]
> I tried to apply the conclusions obtained in PTR-2396. If you think that this PR should be reviewed by some other team, please let me know.

Changes look to me to be in line with what was discussed on [PTR-2396](https://issues.liferay.com/browse/PTR-2396). But given that this is accessibility-related, going to assign this to @marcoscv-work for final approval.

**Comment by dacousalr** [comment]
Pushed a new commit to adapt some Poshi tests failing due to no longer valid path.

**Comment by dacousalr** [comment]
ci:test:relevant

**Review by marcoscv-work — APPROVED** [review]
LGTM!!!

**Comment by wincent** [comment]
`LocalFile.WorkflowMetrics#ViewReports` was flapping last week, but I thought it was fixed...

Going to try `ci:reevaluate:1187401_5731` but I will be _astonished_ if it works.

**Comment by wincent** [comment]
ci:reevaluate:1187401_5731

**Comment by wincent** [comment]
Going to try _le forward emmanuelle_.

**Comment by wincent** [comment]
ci:forward

**Comment by wincent** [comment]
Looking at your branch, it may be failing that Poshi test because you don't have the fix yet:

Screenshot 2021-04-27 -123157-EGHzbOn3@2x

Let's see... that test which I saw failing [here](https://github.com/liferay-lima/liferay-portal/pull/1757) was apparently fixed [here](https://github.com/brianchandotcom/liferay-portal/pull/100995), but that went in many hundreds of commits ago... oh well. 🤷

**Comment by wincent** [comment]
> Let's see... that test which I saw failing [here](https://github.com/liferay-lima/liferay-portal/pull/1757) was apparently fixed [here](https://github.com/brianchandotcom/liferay-portal/pull/100995), but that went in many hundreds of commits ago... oh well. 🤷

Test is [going to be quarantined](https://github.com/brianchandotcom/liferay-portal/pull/101154) Real Soon Now™.

**Comment by wincent** [comment]
Manual forward: https://github.com/brianchandotcom/liferay-portal/pull/101194

Because `LocalFile.WorkflowMetrics#ViewReports` is spurious and has [been quarantined](https://github.com/brianchandotcom/liferay-portal/pull/101154)) anyway.

**Comment by dacousalr** [comment]
Thank you so much, @wincent, @marcoscv-work!

**Pull request closed without merging**
