### PR TITLE
LPD-15545 - test failure DataSet#TheFieldValueIsTranslated

### PR DESCRIPTION
**Pull request by juanjofgliferay**
Related https://liferay.atlassian.net/browse/LPD-15545

Replace references to localhost:8080 to fix issues in CI environment

### CODE REVIEW

**Comment by juanjofgliferay** [comment]
ci:test:relevant

**Comment by juanjofgliferay** [comment]
ci:test:relevant

**Review by markocikos — APPROVED** [review]
@juanjofgliferay LGTM! :sparkles:

**Comment by juanjofgliferay** [comment]
ci:forward

**Comment by juanjofgliferay** [comment]
ci:stop

**Comment by juanjofgliferay** [comment]
Locked in CI

**Pull request closed without merging**
