### PR TITLE
LPD-37441 - Allow empty date field in FDS date filters

### PR DESCRIPTION
**Pull request by juanjofgliferay**
https://liferay.atlassian.net/browse/LPD-37441

### CODE REVIEW

**Comment by juanjofgliferay** [comment]
ci:test:relevant

**Review by markocikos — APPROVED** [review]
@juanjofgliferay LGTM! :sparkles:

**Comment by juanjofgliferay** [comment]
ci:test:relevant

**Comment by juanjofgliferay** [comment]
ci:reevaluate:1357401_6210

**Comment by juanjofgliferay** [comment]
ci:test:relevant

**Comment by juanjofgliferay** [comment]
ci:forward

**Pull request closed without merging**
