### PR TITLE
LPS-139870 Remove or ignore usages of A.one inside the journal module

### PR DESCRIPTION
**Pull request by kresimir-coko**

### CODE REVIEW

**Comment by bryceosterhaus** [comment]
Hey, @kresimir-coko, instead of separating each module into different PRs, can we separate it by rule? Meaning, each new rule being enabled would be its own PR.

@liferay/aui/no-node => one PR for all these changes
@liferay/aui/no-one => one PR for all of these changes

This way, we don't get SF errors from CI because CI is checking against all of DXP and not just an individual module.

**Review by bryceosterhaus — COMMENTED** [review]
~See https://github.com/liferay-frontend/liferay-portal/pull/1504#issuecomment-929431848~ meant to be on a different PR

**Comment by kresimir-coko** [comment]
> can we separate it by rule?

We can, but I don't plan on replacing all `A.one` in any reasonable amount of time, there's just too many usages, and on top of that it would be a massive PR for some of the rules.

Is there any way of getting CI green, like being more specific with which modules are affected by the rules?

**Comment by bryceosterhaus** [comment]
@kresimir-coko We may be able to enable the rule per-module. You could try disabling the rule at the top level config `modules/.eslintrc.js` and then enable the rule at the module level, but this means we would be creating numerous eslint config files which will be a headache and I don't know if those sub-configs will work when we run SF at the root level.

How many A.one uses do we have across just JS files? Is it an absurd amount? If so, maybe we should set the A.one rule to the side for now and focus on the other, easier to apply, aui rules. Let's try to tackle the easiest aui rules first and evaluate how long the hardest ones will take.

**Comment by kresimir-coko** [comment]
> How many A.one uses do we have across just JS files?
253 usages across 85 files.

I wish I knew that we would ignore jsp files here, it changes everything.


What should I do about the already open PRs then? Ones that I've tested and that have mostly JSP changes. I don't mind discarding them but it feels like a waste 🤷

**Comment by nhpatt** [comment]
> What should I do about the already open PRs then? Ones that I've tested and that have mostly JSP changes. I don't mind discarding them but it feels like a waste 🤷

All changes are useful, either because the product teams have to do it sometime (or migrate but having it replaced makes it easier) or because we have a explicit marker of what we want to change. I would try to merge them if there is not a lot of work pending to do.

**Comment by bryceosterhaus** [comment]
> What should I do about the already open PRs then?

We can still try to get them merged! We just gotta make sure it gets past CI. Now we know that we don't need the ignore comments in JSP's since the rule doesn't exist for those files. And then we can focus on just JS files. Once those are addressed, CI should be happy

**Comment by kresimir-coko** [comment]
Hey @bryceosterhaus I've merged your changes with mine and force-pushed. This one also has changes inside JSPs so it's gonna be a struggle to make it green

**Comment by bryceosterhaus** [comment]
closing in favor of https://github.com/liferay-frontend/liferay-portal/pull/1547

**Pull request closed without merging**
