### PR TITLE
LPS-116521 Fix style modal login

### PR DESCRIPTION
**Pull request by eduardoallegrini**
The HTML is the same of Clay, the only relevant difference was the property I've removed.

ezgif com-video-to-gif

### CODE REVIEW

**Comment by eduardoallegrini** [comment]
@marcoscv-work do you think this change can be a problem?

**Comment by jbalsas** [comment]
This feels weird... it is as if the modal moves rather than just the content... I think the modal should stay static and the content scroll... at least that's what I'd expect.

**Comment by eduardoallegrini** [comment]
🤔 I see what you mean but this is the behavior of the standard modal from Clay https://clayui.com/docs/components/modal.html#css and Bootstrap https://getbootstrap.com/docs/4.5/components/modal/ (should we ask lexicon?)

**Comment by carloslancha** [comment]
I'd ask Lexicon since this changes completely how a modal behaves on large contents, title gets lost on scrolling, you can't see footer buttons if you don't scroll down...

**Comment by eduardoallegrini** [comment]
I would forward this to fix the bug and then open an issue in Clay

**Comment by carloslancha** [comment]
If this is not the expected behavior Lexicon wants (don't know, we need to check) wouldn't you be causing another bug by fixing this in this way?

**Comment by eduardoallegrini** [comment]
No, with this PR I'm removing a CSS overwrite of Clay on DXP, if we are going to change it in Clay we will need to remove the CSS in DXP in any case

**Comment by marcoscv-work** [comment]
We usually have the modal with a scroll because they have an iframe inside, as Edu said Clay and Bootsrap modals by default have a general scroll.

**Comment by jbalsas** [comment]
Got it! I thought the sign-in had a scroll... forgot we get the contents and paste them as body. Let's forward it then!

**Comment by marcoscv-work** [comment]
We have a mix of different modals in portal so we need to care those changes, I've tested the PR in different modals and everything looks good

**Comment by markocikos** [comment]
LGTM! 

A brave choice, to change a style in theme. I have PTSD just from seeing somebody do this. All the more reason to applaud this change!

**Comment by markocikos** [comment]
ci:test:sf

**Comment by markocikos** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
> We have a mix of different modals in portal so we need to care those changes, I've tested the PR in different modals and everything looks good

Trusting you on this, then! 👍 

I think I share some the concerns @carloslancha voiced... but we also might be missing some context, so let's move this forward and take some time offline to think this through later!

**Comment by jbalsas** [comment]
Thanks for kicking those tests, @markocikos !

**Comment by jbalsas** [comment]
ci:forward

**Pull request closed without merging**
