### PR TITLE
LPS-148020 Fix for increasing CI coverage for frontend-theme module

### PR DESCRIPTION
**Pull request by Esther-OC**
Small fix for https://github.com/liferay-frontend/liferay-portal/pull/1960 to edit the test.properties file of [frontend-theme module](https://github.com/liferay/liferay-portal/blob/master/modules/apps/frontend-theme/test.properties) to remove one line as the component is not owned by FI team, so the frontend-theme module only shows FI components.

JIRA issue: [LPS-148020](https://issues.liferay.com/browse/LPS-148020)

### CODE REVIEW

**Comment by Esther-OC** [comment]
ci:forward

**Comment by Esther-OC** [comment]
ci:forward

**Comment by Esther-OC** [comment]
ci:forward

**Comment by john-co** [comment]
ci:forward

**Comment by Esther-OC** [comment]
ci:forward

**Comment by john-co** [comment]
ci:forward

**Pull request closed without merging**
