### PR TITLE
LPS-127052 [Impedibug] AB tests can be run with an invalid ID

### PR DESCRIPTION
**Pull request by dgarciasarai**
**Description**

With A/B Testing functionality, the user can create tests with goal Click. In those tests, is required to select a clickable element as click goal target.

**Solution**

A couple of pull requests ago, we decided to implement a new `input` to enter manually the click goal target (clickable element ID), see https://github.com/liferay-frontend/liferay-portal/pull/650. Testing this feature, we found that a user, can let the input empty, the `ID was not found.` message appear, but the target is already in DB so the user can review and run the AB Test. This is a weird behavior and we decided to change a few things:

1. If the user selects a target, the input becomes readonly
2. If the user wants to select a target:
    * If there is a selected target, he/she has to remove it first and then select the new one
    * if there isn't a selected target, he/she can select it with the highlighted ones, or enter manually the ID in the input box
3. If the user wants to remove the target:
    * Click in the `x` in the topper of the element in the page
    * Click in the `x` in the input of the AB Testing sidebar
4. If there is a selected target, this is the only element highlighted in the page, if not, every OOTB clickable element (a, button and input[submit]) is highlighted

**How to test it**

* Connect Liferay DXP with Analytics Cloud
* Create a page
* Click in the AB Test icon in the Control Menu
* Create new test with Click goal

**Screenshots**

Screenshot 2021-02-03 at 13 43 54
Screenshot 2021-02-03 at 13 43 43

### CODE REVIEW

**Comment by dgarciasarai** [comment]
Hey @liferay-frontend, can you review these changes and give me feedback? Thanks!

**Review by bryceosterhaus — APPROVED** [review]
I didn't test this locally, but the code looks good to me

**Comment by dgarciasarai** [comment]
ci:stop

**Comment by dgarciasarai** [comment]
ci:test:relevant

**Comment by dgarciasarai** [comment]
> I didn't test this locally, but the code looks good to me

Thank you for the review @bryceosterhaus. Let's wait until the CI finishes to forward the changed (yesterday, the CI was ill) 😄

**Comment by dgarciasarai** [comment]
I'm going to forward this since the pull is approved and the CI is ✅  👍

**Comment by dgarciasarai** [comment]
ci:forward

**Pull request closed without merging**
