### PR TITLE
LPS-126702 - Update @clayui dependencies to 3.25.0

### PR DESCRIPTION
**Pull request by bryceosterhaus**
https://issues.liferay.com/browse/LPS-126702

# [3.25.0](https://github.com/liferay/clay/compare/v3.24.1...v3.25.0) (2021-02-23)

### Bug Fixes

-   **@clayui/color-picker:** remove last-row classes and API that was added on accident ([d4cb8e8](https://github.com/liferay/clay/commit/d4cb8e8))
-   **@clayui/css:** Global Functions moves generated SVG icons Sass map to separate file `_lx-icons-generated.scss` ([7ffc523](https://github.com/liferay/clay/commit/7ffc523))

### Features

-   **@clayui/card:** add active state for card when it is selected ([607da9d](https://github.com/liferay/clay/commit/607da9d))
-   **@clayui/drop-down:** add util for aligning dropdown on scroll ([09dc506](https://github.com/liferay/clay/commit/09dc506))
-   **@clayui/panel:** add 'show' class to collapsable panel's button ([1e7f64a](https://github.com/liferay/clay/commit/1e7f64a))

### CODE REVIEW

**Comment by bryceosterhaus** [comment]
ci:stop

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
Not able to reproduce locally, gonna re-test and see

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by wincent** [comment]
Something wrong with CI as it didn't finish in 6 hours, so I am going to stop and retry.

**Comment by wincent** [comment]
ci:stop

**Comment by wincent** [comment]
ci:stop

**Comment by wincent** [comment]
ci:test:relevant

**Comment by wincent** [comment]
Seems to be running now after being wedged for a while — [Slack thread for reference](https://liferay.slack.com/archives/C19PWQ74J/p1614159710010500). 🤞

**Comment by pyoo47** [comment]
The load on CI has been extremely high this week so unfortunately, that means there will be significant delays in pull request tester.

**Comment by wincent** [comment]
Any of [the failures on the last run](https://github.com/liferay-frontend/liferay-portal/pull/834#issuecomment-785186766) look legit to you @john-co @zhangyan0701 @calvinctvo?

**Comment by john-co** [comment]
Reviewed. Test failures are unrelated. :heavy_check_mark: 

It looks like page crashed on ci side and some other ci issues. Previous test runs had same tests pass so this looks safe to manually forward.

**Comment by wincent** [comment]
Manual forward: https://github.com/brianchandotcom/liferay-portal/pull/99182

**Pull request closed without merging**
