### PR TITLE
LPS-102111 Remove sidebar compat layer

### PR DESCRIPTION
**Pull request by zhangyan0701**
https://issues.liferay.com/browse/LPS-102111

This is from PR https://github.com/liferay-frontend/liferay-portal/pull/524 with the fix of the tests.

### CODE REVIEW

**Comment by zhangyan0701** [comment]
ci:test:sf

**Comment by zhangyan0701** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
ci:test:relevant

**Comment by marcoscv-work** [comment]
LGTM

**Comment by marcoscv-work** [comment]
rebase and resent?

**Comment by marcoscv-work** [comment]
Commit example to correctly fix the rebase:
https://github.com/liferay-frontend/liferay-portal/pull/547/commits/fef351b469ada66591a628fabd83842a3b18bff9

**Comment by marcoscv-work** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by zhangyan0701** [comment]
ci:forward

**Comment by marcoscv-work** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcoscv-work** [comment]
Impossible to rebase, resending..
https://github.com/liferay-frontend/liferay-portal/pull/564

**Pull request closed without merging**
