### PR TITLE
[LPS-123964,LPS-124912] Migrate instances of AlloyEditor in Forms

### PR DESCRIPTION
**Pull request by julien**
AlloyEditor instances have been replaced with `<aui:input />`

**Test plan**

- Deploy the `dynamic-data-mapping-form-web` module
- Navigate to **Content & Data** > **Forms**
- Create a new form and save it

**Additional notes**

I worked on the CSS changes with @marcoscv-work

### CODE REVIEW

**Comment by julien** [comment]
Hey @john-co,

I think these test failures are all related to this change (markup has changed)

I tried running one of these tests locally with 

```sh
ant -f build-test.xml run-selenium-test -Dtest.class=LocalFile.Forms#AddFormToUserSiteAndViewNoDuplicates
```

After having edited [this line](https://github.com/liferay/liferay-portal/blob/6f7122e4b72383c34dc0852e980da01b43956dce/portal-web/test/functional/com/liferay/portalweb/paths/portlet/forms/Form.path#L38) changing to 

```html
    <td>//div[contains(@class,'ddm-form-basic-info')]//textarea[contains(@id, 'nameEditor')]</td>
```

However, I still see lots of errors such as 

```
 BUILD FAILED: Element is not present at "//span[@class='user-avatar-link']"
```

I wanted to know if you could give me a hand fixing these - if you have any good resources on understanding how this works, I'm interested.

**Comment by julien** [comment]
@john-co I see we have [LPS-125020](https://issues.liferay.com/browse/LPS-125020) which is probably related to updating tests once these changes are done - not 100% sure but since it's part of the epic I guess that would make sense.

**Comment by john-co** [comment]
ci:test:bundle

**Comment by john-co** [comment]
Hi @julien , here is a resource for debugging test failures: https://qa-compendium.readthedocs.io/en/latest/poshi/debugging/debugging-index.html hopefully this helps. LPS-125020 isn't necessarily related to updating tests, mainly to brainstorm possible new test scenarios.

Looks like this will need some test fixes.
@zhangyan0701, can you please look into this? Looks like this will need some test fixes. My machine is having trouble continuing the poshi test locally at the moment...

**Comment by john-co** [comment]
I couldn't reproduce the error:  `BUILD FAILED: Element is not present at "//span[@class='user-avatar-link']"`

But I imagine there to be more test fixes to update alloy editor paths/macros to ckeditor compatible.

cc/ @cvanut

**Comment by zhangyan0701** [comment]
All the failed Form tests are test fix.

But when I running test LocalFile.Forms#NavigateToCorrectForm with my fix locally, I saw below error in Edit Form page:
edit form

Steps:
1. Go to Content & Data > Forms.
2. Add some forms.
3. Edit those forms for several times.

Can you take a look at this?

**Comment by john-co** [comment]
> After edit forms some times, the edit form page becomes blank.

Ah, I came across this too. I was hitting this issue most of the time, about 80% of the time, so I chalked it up as something wrong with my machine.

**Comment by julien** [comment]
@zhangyan0701, @john-co I'm going to have a look to see if I can see what's going on

**Comment by julien** [comment]
@zhangyan0701 , @john-co couldn't reproduce this error - do I need to rebase with `master`?

**Comment by zhangyan0701** [comment]
Hi @julien 

Were you using the bundle that built here https://github.com/liferay-frontend/liferay-portal/pull/624#issuecomment-747637844?

I tried more testing on that bundle, and I could reproduce just refreshing the Edit Form page:

**Comment by julien** [comment]
Hi @zhangyan0701, no I didn't :facepalm: 
I'm going to try get now thanks

**Comment by julien** [comment]
@zhangyan0701 I get lots of (repeated) 404, because of the logo not being available but I still haven't been able to reproduce the error

2020-12-21-150645_1599x869_scrot

**Comment by julien** [comment]
@zhangyan0701 one thing that I'm seeing is that the JS from the bundle doesn't have the changes from this PR, which is strange.

**Comment by julien** [comment]
ci:test:bundle

**Comment by zhangyan0701** [comment]
Hi @julien 

I still could reproduce the issue on the new bundle of this PR, but looks like the same issue was happening on master before, [LPS-121664](https://issues.liferay.com/browse/LPS-121664), so I think it shouldn't related. But I don't know why I see it.

Could you resolve the conflict and re run ci test relevant with my commit https://github.com/zhangyan0701/liferay-portal/commit/eec60e74a2ec35674cdf781a758975f1aad7e844? I think tests may pass this time.

**Comment by julien** [comment]
Hi @zhangyan0701, 

Thanks for the help and update.
I'll resolve the conflict and make sure your commit is there too before running the CI tests

**Comment by julien** [comment]
ci:test:sf

**Comment by julien** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
Looks good @julien! Let's send this to @liferay-forms and add some screenshots so they can compare visually the before and after and then you can go on vacation!?

armadillo

**Comment by julien** [comment]
@jbalsas of course, 
I'll include some before/after screenshots and forward this to @liferay-forms
Merry xmas to you too

**Comment by julien** [comment]
Submitted [here](https://github.com/liferay-forms/liferay-portal/pull/83)

**Pull request closed without merging**
