### PR TITLE
LPS-147060 Update blade command to generate rest modules templates.

### PR DESCRIPTION
**Pull request by LuismiBarcos**
Related ticket -> [LPS-147060](https://issues.liferay.com/browse/LPS-147060)
____
This PR updates the rest modules generated by `blade`. For versions `7.4` and `7.3`, it uses the bom dependency `release.{product}.api`.
It is not using that dependency in the previous versions due to some problems finding it (sometimes the version requested is not released yet), making it less stable.
Also, take care of the community versions because it is possible that some dependencies are not updated due to it being updated in some FP/SP but not for the CE.

### CODE REVIEW

**Review by javierdearcos — APPROVED** [review]
Perfect 👏 

Let's see if it is enough to solve client issues

**Comment by LuismiBarcos** [comment]
ci:forward

**Comment by LuismiBarcos** [comment]
Reopen because we will send this to Lawrence Lee instead of Brian

**Comment by LuismiBarcos** [comment]
Sent [here](https://github.com/lawrence-lee/liferay-portal/pull/269)

**Pull request closed without merging**
