### PR TITLE
LPS-116165 - Add a separator line to navigation-bar-light

### PR DESCRIPTION
**Pull request by marcoscv-work**
**Only for testing and @victorvalle quick review**

This PR adds a separator line under `navigation-bar-light`

image

To test this PR we only need to go to `User and Organizations`

### CODE REVIEW

**Comment by marcoscv-work** [comment]
ci:test:sf

**Comment by marcoscv-work** [comment]
ci:test:relevant

**Comment by pat270** [comment]
LGTM!

**Comment by marcoscv-work** [comment]
ci:forward

**Pull request closed without merging**
