### PR TITLE
LPS-125168 Remove JSBundleConfigPortalWebResources

### PR DESCRIPTION
**Pull request by izaera**
This is a followup of https://github.com/brianchandotcom/liferay-portal/pull/97363#issue-547878012

I've tested it locally and couldn't make it fail, so I'm sending it to CI to see what happens.

### CODE REVIEW

**Comment by wincent** [comment]
This PR has been randomly selected so that I can test the tweaks I just made to the email notification settings on the liferay-frontend user on GitHub. The idea is to make sure we get notifications when somebody `@`-mentions us (@liferay-frontend)... Now, i think it's not going to spam us for _every_ comment on a PR sent to this user, only for mentions... but we won't know until we try, so :crossed_fingers:.

**Comment by izaera** [comment]
> This PR has been randomly selected 

Does that mean that today is my lucky day? :thinking:

**Comment by wincent** [comment]
> Does that mean that today is my lucky day? 🤔

Probably not, because I lied about it being random anyway (I picked the first).

**Comment by wincent** [comment]
First notification didn't make it, so I have tweaked another setting and am going to try again: @liferay-frontend

**Comment by wincent** [comment]
That one worked.

**Comment by jbalsas** [comment]
That one worked... and I think now `@liferay-frontend` is a watcher so we might get comments here twice if we're also subscribed? 😂

**Comment by wincent** [comment]
I tested that with my "That one worked" comment above and it _looks_ like Gmail at least threads it correctly, showing only one copy of the message:

Screenshot 2021-01-18 -121211-raSyIuHT@2x

**Comment by wincent** [comment]
Bah in the screenshot above where I say "GitHub still only shows one" I meant to write "_Gmail_ still only shows one".

**Comment by wincent** [comment]
🤦‍♂️... mysteriously, deduping of messages in a thread doesn't seem to happen 100% of the time:

Screenshot 2021-01-18 -121653-3TqH1BiJ@2x

**Comment by izaera** [comment]
Closed to address it later. See [IFI-2314](https://issues.liferay.com/browse/IFI-2314).

**Pull request closed without merging**
