### PR TITLE
LPS-165669 Add aria-label to management toolbar checkbox

### PR DESCRIPTION
**Pull request by sandrodw3**
Hi guys! Could you please review this? We are working on improving accesibility in the portal. Thanks in advance 🙂

### CODE REVIEW

**Review by diegonvs — APPROVED** [review]

**Comment by diegonvs** [comment]
ci:test:relevant

**Comment by M-IgorFranca** [comment]
ci:test:relevant

**Comment by M-IgorFranca** [comment]
ci:reevaluate:1347401_3002

**Comment by ealonso** [comment]
ci:reevaluate:1347401_3002

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by sandrodw3** [comment]
Hi guys! It seems some java tests are failing here, but we only modified js files, so I'm not sure how it is related to the changes or how to fix it. Could someone help? Thansk 🙂

**Comment by dsanz** [comment]
The failing tests have nothing to do with the PR, we're taking a look to the componentTag failing test.

**Comment by izaera** [comment]
@sandrodw3 Can you give me access to your GH repo so that I can push a commit on top of this PR?

**Comment by sandrodw3** [comment]
> @sandrodw3 Can you give me access to your GH repo so that I can push a commit on top of this PR?

Sure! Done @izaera 😄

**Comment by izaera** [comment]
I've pushed a new commit to fix the test

**Comment by izaera** [comment]
ci:forward

**Comment by john-co** [comment]
Reviewed. Test failures are unrelated. :heavy_check_mark: 

Forwarding again should work :crossed_fingers:

**Comment by john-co** [comment]
ci:

**Comment by john-co** [comment]
ci:forward

**Comment by sandrodw3** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/124928

**Pull request closed without merging**
