### PR TITLE
LPS-115019 Add a "view state" display context holder for search containers to the Clay Taglib

### PR DESCRIPTION
**Pull request by brunobasto**
Previously https://github.com/liferay-frontend/liferay-portal/pull/71

Most of the conversation is there. @jbalsas I'd like to keep it there, but 

```
ERROR: Permission to jbalsas/liferay-portal.git denied to brunobasto.
```
tenor-158179330

So I've created this new one just so that we don't have to wait longer.

### CODE REVIEW

**Comment by brunobasto** [comment]
ci:test:sf

**Comment by brunobasto** [comment]
ci:test:relevant

**Comment by brunobasto** [comment]
Conflicts. Will update and force push.

**Comment by brunobasto** [comment]
I think this baseline change is no longer needed due to recent changes in master. So conversation continues on https://github.com/liferay-frontend/liferay-portal/pull/71

**Comment by jbalsas** [comment]
> ERROR: Permission to jbalsas/liferay-portal.git denied to brunobasto.

I should be punished

**Comment by wincent** [comment]
> > ERROR: Permission to jbalsas/liferay-portal.git denied to brunobasto.
> 
> I should be punished

funny-guy

**Pull request closed without merging**
