### PR TITLE
LPS-185712 | Add ignore on WYSIWYGUsecase#CanAddBlogsEntryWithImageViaBlogsImages

### PR DESCRIPTION
**Pull request by abhnerramos**
**Description**
Add ignore on WYSIWYGUsecase#CanAddBlogsEntryWithImageViaBlogsImages

**JIRA Ticket**
https://issues.liferay.com/browse/LPS-185712

### CODE REVIEW

**Comment by abhnerramos** [comment]
ci:test:frontend

**Comment by abhnerramos** [comment]
@CarlosBrichete, could you take a look, please? Looks good to me

**Comment by abhnerramos** [comment]
ci:test:sf

**Comment by abhnerramos** [comment]
ci:test:sf

**Review by mateusralv — APPROVED** [review]

**Comment by abhnerramos** [comment]
ci:forward

**Pull request closed without merging**
