### PR TITLE
LCD 27832

### PR DESCRIPTION
**Pull request by allen-ziegenfus**
hey @bryceosterhaus  - there was a linting change done here https://github.com/liferay-frontend/liferay-portal/commit/200b1524da4ab3b4911206dffc4821988b8ec981#diff-64eef832fb0e9eec874e68091ed3eeb078167214def2403bc4cee96e21f1341e (removing .js) from the import that breaks this sample from rendering. 

I get a 404: 

```
WARN  [http-nio-8080-exec-2][code_jsp:157] {code="404", msg="ProxyServlet: /o/liferay-sample-etc-frontend-2/shared-utils", uri=/o/liferay-sample-etc-frontend-2/shared-utils}
```

I changed this back and disabled the eslint rule - is there any other way to fix this? 

cc: @gamerson

### CODE REVIEW

**Comment by gamerson** [comment]
cc @bryceosterhaus  @kevenleone could someone help with a review?

**Comment by kevenleone** [comment]
I think it's fine, not sure why the extension was needed, but if it works, it's good for me 👍🏻 

@bryceosterhaus if it could be done differently, let us know.

**Comment by bryceosterhaus** [comment]
Extension is needed if it is pure ESM I believe...

I don't see any reason why we can't remove that error Feel free to disable that lint rule for all of workspaces.

Edit `./modules/.eslintrc.js` and add `"@liferay/import-extensions": "off"` to the rules section

**Comment by gamerson** [comment]
hey @bryceosterhaus  and @kevenleone  i want to make sure I can understand the extension, no-extension thing.  It seems to get these samples over here to work we must need the extensions.  https://github.com/brianchandotcom/liferay-portal/compare/d48fd74af7...142903e542

**Comment by bryceosterhaus** [comment]
@gamerson when using `import` in the browser with script tags that have `type="module"`, you are resolving to a specific file, so it is required to have a file extension, unless that source file doesn't have an extension...

For custom-element client extensions, check the yaml and see. If `useESM` is set to true and you don't use any build process(like webpack), you'll probably need to include the extension.

I can explain more if needed, let me know.

**Comment by kevenleone** [comment]
@ipeychev I can apply the changes and send it here

**Comment by kevenleone** [comment]
Just starting reviewing :)

**Comment by kevenleone** [comment]
resent: https://github.com/liferay-frontend/liferay-portal/pull/3392#issuecomment-1589947869

**Comment by kevenleone** [comment]
ci:close

**Comment by bryceosterhaus** [comment]
@kevenleone where was this re-sent at?

**Comment by ipeychev** [comment]
Thank you @kevenleone, I really appreciate it! I see the [other PR](https://github.com/liferay-frontend/liferay-portal/pull/3393#issuecomment-1589622867) was closed too. They corresponded to the sub-tasks of [this ticket](https://issues.liferay.com/browse/LCD-26595). I don't know where you resent the PR, so I can't check their status, but does that mean we can close the sub-tasks as `Done`?

**Comment by kevenleone** [comment]
Sorry guys, I added the wrong PR on my resent comment, here: https://github.com/liferay-frontend/liferay-portal/pull/3447

**Pull request closed without merging**
