### PR TITLE
LPS-181684 | Add automations for JS Import Maps on Client Extensions

### PR DESCRIPTION
**Pull request by JerryAdrianoo**
**Description:**
Add automations for JS Import Maps on Client Extensions

**JIRA Ticket:**
https://issues.liferay.com/browse/LPS-181684

### CODE REVIEW

**Comment by JerryAdrianoo** [comment]
ci:test:sf

**Comment by JerryAdrianoo** [comment]
ci:test:frontend-client-extensions

**Comment by JerryAdrianoo** [comment]
cc:@CarlosBrichete

**Comment by CarlosBrichete** [comment]
LGTM :)

**Review by CarlosBrichete — APPROVED** [review]

**Comment by JerryAdrianoo** [comment]
ci:forward

**Pull request closed without merging**
