### PR TITLE
LPS-143885 Move remaining files and tag from frontend-taglib-clay to a dedicate module

### PR DESCRIPTION
**Pull request by LuismiBarcos**
Related ticket -> [LPS-143885](https://issues.liferay.com/browse/LPS-143885)

The purpose of this branch is to move the logic of the data-set-display from the module `frontend-taglib-clay` to `frontend-data-set` 

I copied, pasted and renamed the remaining files from frontend-taglib-clay to frontend-data-set. I set the files in the module I consider that it belongs (-api, -impl, -taglib...).

To test this I migrate two modules (not in this PR) and, doing that, I realized that other teams are adding more logic to the module `frontend-taglib-clay` doing the migration more difficult.

As we are going to do the migration of the components that are using these tags, we can take care of migrating these new files but, at the time we start to do the migration, I suppose that we have to tell the other teams that the module `frontend-data-set`  will be the new place for the logic of the data set display.

This PR is a follow up of [this request](https://github.com/brianchandotcom/liferay-portal/pull/111619#issuecomment-1002886413)

### CODE REVIEW

**Comment by LuismiBarcos** [comment]
The main changes are in the last commit. As it seems like Brian doesn't want all the logic to create the `props` in the `.jsp` I move it to the tag class and set the props (called `data` as we do in other cases) as an attribute of the request.

**Comment by LuismiBarcos** [comment]
I've just remembered that we are migrating two tags and I should make the changes requested by Brian in both of them. 😅 That's why I've added another commit 🙂

**Comment by LuismiBarcos** [comment]
ci:test:sf

**Comment by LuismiBarcos** [comment]
ci:test:relevant

**Comment by markocikos** [comment]
> I've just remembered that we are migrating two tags and I should make the changes requested by Brian in both of them.  That's why I've added another commit 

@LuismiBarcos Hmm this addition clashes with https://github.com/liferay-frontend/liferay-portal/pull/1777. In that PR, we are refactoring `headless-display` tag so that it doesn't use JSP request attributes at all. Since this PR is close to completion, I guess it is wiser to let this merge first. I'll update the other PR after.

**Review by markocikos — APPROVED** [review]

**Comment by markocikos** [comment]
ci:forward

**Comment by markocikos** [comment]
ci:forward

**Pull request closed without merging**
