### PR TITLE
COMMERCE-10564 Fix promoPrice expecting to be a string but is actually a number

### PR DESCRIPTION
**Pull request by kresimir-coko**
https://issues.liferay.com/browse/COMMERCE-10564

### CODE REVIEW

**Comment by 22LucaGiannotta22** [comment]
ci:test:commerce

**Comment by 22LucaGiannotta22** [comment]
ci:test:relevant

**Comment by 22LucaGiannotta22** [comment]
ci:test:relevant

**Comment by victoroscuro** [comment]
ci:forward

**Pull request closed without merging**
