### PR TITLE
LPS-130743 Allow make configurable the absolute maximum allowed delta | master

### PR DESCRIPTION
**Pull request by samanzanedo**
### **Description:**
Currently the absolute maximum allowed delta value is hardcoded and there is no way to change it. Its value is 200.
Thus, property `search.container.page.default.delta` can not define a value bigger than 200.

### **Steps to reproduce:**
Define  `search.container.page.default.delta=300` in _portal-ext.properties_ file.

Create 300 web content assets using the attached groovy script available in [LPS-130743](https://issues.liferay.com/secure/attachment/402079/LPS-130743-master.groovy).

**Checkpoint A**
Navigate to _Content & Data -> Web Content_

- **Observed behavior:**

>  200 assets are showed: delta = 200.

- **Expected behavior:**

> 300 assets are showed: delta = 300.

**Checkpoint B**
In a new widget page, add _Search Bar_, _Search Options_ and _Search Results_ widgets.
In _Search Options_ configuration, set _'Allow Empty Searchs'_ check.
In _Search Results_ configuration, set '_Pagination Delta_' parameter value to 300.
In _Search Bar,_ click on search with no terms (empty search) to get all assets (web contents).

- **Observed behavior:**
> 200 assets are showed: delta = 200.

- **Expected behavior:**
> 300 assets are showed: delta = 300.

### Solution proposed:
A new property is defined in _portal-ext.properties_ to set the absolute maximum allowed delta value.
The new property is **`search.container.page.max.delta`** 
This new property works together with _search.container.page.default.delta_ property in the following way:
- `search.container.page.max.delta` default value is 200.
- `search.container.page.default.delta `default value remains in 200.
 Default values apply when either property is not defined or property is defined with a value <= 0
- If `search.container.page.max.delta` > `search.container.page.default.delta` then _delta_ = `search.container.page.default.delta`
- If `search.container.page.max.delta` < `search.container.page.default.delta` then _delta_ = `search.container.page.max.delta`

So a basic example testing case would be:
- Define `search.container.page.default.delta=300` in _portal-ext.properties_ file.
- Define `search.container.page.max.delta=350` in _portal-ext.properties_ file.
- Create 400 web content assets using the referred-to groovy script.

**Checkpoint A**
Navigate to _Content & Data -> Web Content_

- **Observed and expected behavior:**
300 assets are showed: delta = 300.

**Checkpoint B**

1. In a new widget page, add _Search Bar, Search Options_ and _Search Results _widgets.
2. In _Search Options _configuration, set _'Allow Empty Searchs'_ check.
3. In _Search Results_ configuration, set '_Pagination Delta'_ parameter value to 300.
Please, note that if a value greater than `search.container.page.max.delta` is set (i.e. 400) then `search.container.page.max.delta` is used.
4. In _Search Bar_, click on search with no terms (empty search) to get all assets (web contents).

- **Observed and expected behavior:**
 300 assets are showed: delta = 300.

### References:
https://issues.liferay.com/browse/PTR-1500
https://issues.liferay.com/browse/LPS-105522
https://issues.liferay.com/browse/LPS-130743

### CODE REVIEW

**Comment by izaera** [comment]
I understand that we may want to put the default and max delta variables together but, is it a good idea to keep creating variables in `portal.properties` :thinking: ? Wouldn't it be better to move everything to OSGi configuration? I'm just thinking aloud, not requesting changes (unless we all agree it is better).

Other than that, LGTM.

**Comment by wincent** [comment]
> I understand that we may want to put the default and max delta variables together but, is it a good idea to keep creating variables in `portal.properties` 🤔 ? Wouldn't it be better to move everything to OSGi configuration? I'm just thinking aloud, not requesting changes (unless we all agree it is better).
> 
> Other than that, LGTM.

I don't know whether we have a heuristic or guidance written down anywhere for when to use properties and when to use an OSGi config. We seem to have a strong preference for OSGi config to act as a feature flag. It seems more common to see "permanent", customer-configurable stuff in properties.

But in this specific case, we're adding `search.container.page.max.delta` right next to the existing `search.container.page.default.delta`, `search.container.page.iterator.max.pages` and `search.container.page.delta.values`, along with about three other stuff in the `search.container.*` "namespace", so I'd say keeping all this together is the right call.

One of the failures (`LocalFile.WorkflowMetrics#ViewReports`) looks bogus, but the other one seems likely to fail no matter how many times we try it. @samanzanedo, would you mind rebasing this and updating it with a force push so that we can try a `ci:forward` on it?

**Comment by wincent** [comment]
Also, @samanzanedo, have a (non-ironic) gold star for writing one of the most detailed and clear PR summaries ever seen in this repo. 😁 

gold-star

**Comment by izaera** [comment]
> I don't know whether we have a heuristic or guidance written down anywhere for when to use properties and when to use an OSGi config

Obviously not :roll_eyes:  

I thought long ago infra said these properties should be moved progressively to OSGi, but it is evident (looking at portal.properties' Git history) that we are not doing it, so I guess I'm wrong.

**Comment by wincent** [comment]
> One of the failures (`LocalFile.WorkflowMetrics#ViewReports`) looks bogus, but the other one seems likely to fail no matter how many times we try it. @samanzanedo, would you mind rebasing this and updating it with a force push so that we can try a `ci:forward` on it?

Just a friendly ping @samanzanedo:

ping-steve-jobs

**Comment by samanzanedo** [comment]
@wincent, commits rebased, sorry for the delay.

And thanks for the gold star but the kudos are for @jbalsas for _mentoring_ to me about _how-to-properly-comment-PR-for-liferay-frontend_  :-)

**Comment by izaera** [comment]
ci:test:relevant

**Comment by wincent** [comment]
Same failure as before @samanzanedo:

```
     [exec]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec] = ================================================== ========== ========== ========== ========== ==========
     [exec] * com.liferay.portal.kernel.dao.search               CHANGED    8.0.0      8.0.0      8.0.1      VERSION INCREASE REQUIRED
     [exec] 	~   class      com.liferay.portal.kernel.dao.search.SearchContainer
     [exec] 		~   field      MAX_DELTA
     [exec] 			-   constant   200
     [exec] [Baseline Report] Mode: diff (persisted)
     [exec] Semantic versioning is incorrect while checking /opt/dev/projects/github/liferay-portal/portal-kernel/portal-kernel.jar against /opt/dev/projects/github/liferay-portal/.gradle/caches/modules-2/files-2.1/com.liferay.portal/com.liferay.portal.kernel/10.6.2/8e497db434409d5504e56b8310d8b71315014beb/com.liferay.portal.kernel-10.6.2.jar
```

I don't really know how all that works and how it decides when a bump is required, but my notes tell me you can fix that with `gradlew baseline` inside the module. And furthermore, Brian has [told me in the past](https://github.com/brianchandotcom/liferay-portal/pull/99083#issuecomment-784231923) that:

> for baseline, feel free to group the PRs together and send it to me in one pull directly (bypassing CI).

Which means that if you just do the baseline update and nothing else (ie. additional commit, no force-pushing) and update it here, we can do a manual forward of it without waiting for CI.

**Comment by samanzanedo** [comment]
@wincent 
I run `gradlew baseline` but it does not change/update any `packageinfo` file, neither `portal-kernel/` nor `portal-impl/`

**Comment by wincent** [comment]
> I run `gradlew baseline` but it does not change/update any `packageinfo` file, neither `portal-kernel/` nor `portal-impl/`

I think we'd better call in the cavalry (ie. QA) to help us understand the test failure, because it has happened twice in exactly the same way now; cc: @john-co @nkkwon @zhangyan0701

**Comment by john-co** [comment]
Just started reviewing :)

**Comment by john-co** [comment]
I tried gradle baseline on both master and fetching this PR and the command failed to work for me locally...

```
> Task :third-party:com-webex-schemas:cleanBuildXSDCompile UP-TO-DATE

> Task :third-party:com-webex-schemas:buildXSDCompile
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :third-party:com-webex-schemas:buildXSD
> Task :third-party:com-webex-schemas:compileJava NO-SOURCE
> Task :third-party:com-webex-schemas:copyLibs SKIPPED
> Task :third-party:com-webex-schemas:copyCSS NO-SOURCE
> Task :third-party:com-webex-schemas:buildCSS NO-SOURCE
> Task :third-party:com-webex-schemas:processResources
> Task :third-party:com-webex-schemas:classes
> Task :third-party:com-webex-schemas:zipZippableResources UP-TO-DATE

> Task :third-party:com-webex-schemas:jar FAILED
error  : Can not find JAR file 'lib/com.webex.schemas-xbean.jar'

> Task :third-party:com-webex-schemas:autoUpdateXml SKIPPED


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':third-party:com-webex-schemas:jar'.
> Bundle com.webex.schemas-6.0.0.jar has errors

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4m 2s
```

I'll check with Peter Shin about this.

**Comment by john-co** [comment]
cc/ @petershin could you help us understand the gradle baseline issue? I'm not able to reproduce it locally but am blocked by a different issue.

**Comment by petershin** [comment]
@john-co - running `ant clean jar` in `portal-impl` and `portal-kernel` will update the relevant packageinfo files. those changes will need to be committed to resolve the CI failure

**Comment by john-co** [comment]
>  running ant clean jar in portal-impl and portal-kernel will update the relevant packageinfo files.

Hi @petershin , I tried this but it didn't update any package files for me. I also tried `gw baseline` on `/modules` and still get the same issue with `third-party:com-webex-schemas:jar`

**Comment by john-co** [comment]
testing baseline fix commits in https://github.com/john-co/liferay-portal/pull/402

**Comment by john-co** [comment]
baseline fix passes ci tests. Will forward from https://github.com/john-co/liferay-portal/pull/402

**Pull request closed without merging**
