### PR TITLE
LPS-113582|LPS-113583 Replaces the usages of `Liferay.Notification` and `Liferay.Notice` with `Liferay.Util.openToast`

### PR DESCRIPTION
**Pull request by wincent**
Forwarded here from https://github.com/wincent/liferay-portal/pull/309, where it was stuck in CI hell. Let's see if we have any better luck over here.

Original description:

> Notification related things depends on review from Product Teams.
>
> Previously:
>
> 1. [diegonvs#28](https://github.com/diegonvs/liferay-portal/pull/28)
> 2. [wincent#297](https://github.com/wincent/liferay-portal/pull/297)
> 3. [jbalsas#2197](https://github.com/jbalsas/liferay-portal/pull/2179) + [wincent#307](https://github.com/wincent/liferay-portal/pull/307)

cc @diegonvs @jbalsas

### CODE REVIEW

**Comment by wincent** [comment]
Last test run on the other pull had [a fair few failures](https://github.com/wincent/liferay-portal/pull/309#issuecomment-644508288), so I'm going to run here as well just to get another sample, and we can ask @john-co to check the results.

> ci:test:relevant - 127 out of 154 jobs passed in 2 hours 40 minutes

(Failures are in functional batches, which means that even though it says "No unique failures", there might actually be legit, unique failures hidden in there, and the failed count is rather high, so we should be careful.)

**Comment by wincent** [comment]
ci:test:sf

**Comment by wincent** [comment]
ci:test:relevant

**Comment by john-co** [comment]
ci:test:bundle

**Comment by john-co** [comment]
**[unrelated]**
- modules-integration-mysql57-jdk8: https://issues.liferay.com/browse/LPS-111174

**[possibly unrelated]**
- will verify KaleoformsUsecase#CompleteProcessWithUploadedDefinition manually since it fails on a different error message. Likely will need a test fix to update the assertion to a verify to avoid possible inconsistent failure.

**Comment by john-co** [comment]
@rodrigocunhaa , I think the failng kaleoforms test is unrelated. The behavior seems to be in common with test server test-6-1-2 at GIT ID: a5641e2633f4e37e754378e298e1a37f04888f3d. There is no success message after importing a workflow definition. I didn't see this error message on testray history though. Was this recently fixed?

**Comment by john-co** [comment]
@wincent , I'm able to reproduce the failing test behavior on our test server so the failing tests look unrelated.

Reviewed. Test failures are unrelated. :heavy_check_mark: 

Seeing the amount of tests run here, there's no need to retest.

**Comment by rodrigocunhaa** [comment]
Hi @john-co , It's actually a bug. I'll open the ticket and quarantine this test. Thanks!

**Comment by wincent** [comment]
So, there are 303 comments (the majority of them are bot interaction, I think) on this PR and its 5 previous incarnations). I'll be honest and confess that I do not have the stomach to look over it all with a magnifying glass again, but it seems ok based on a quick skim. Given that the test failures are confirmed to be unrelated, I am going to try a manual forward of this.

Last call for objections, anyone? (especially @jbalsas, who commented previously) because soon this will be gone. If it turns out that that's a mistake, we can revert.

**Comment by wincent** [comment]
Manual forward is here: https://github.com/brianchandotcom/liferay-portal/pull/90226

**Comment by jbalsas** [comment]
Well... 

Screen Shot 2020-06-17 at 18 35 02

Screen Shot 2020-06-17 at 18 35 00

It definitely looks a bit daunting, all those commits for such a diff change...

**Comment by jbalsas** [comment]
LGTM overall... changes in `session.js` and `portal-web` really old components make me a bit uneasy about this. I think I remember some comments about `session` in one of the previous incarnations... 

In any case let's get this in and see if we live to fight another day 😉

**Comment by wincent** [comment]
> It definitely looks a bit daunting, all those commits for such a relatively small diff change...

It's a common pattern. Evidently I am bad at giving review feedback, and people are bad at understanding it.

**Pull request closed without merging**
