### PR TITLE
LPS-155249 [Content Dashboard] Hover actions need tooltips

### PR DESCRIPTION
**Pull request by beltranrengifo**
[Jira ticket](https://issues.liferay.com/browse/LPS-155249)

## Motivation
The quick actions offered by the Dropdown component, used in the Content Dashboard module, offer no tooltip on hover

## Solution proposed
Add title prop, using the existent label value

## Steps to validate
- Create a new site, ie. MasterClass, just to populate the CD with some content
- Navigate to Control Menu > Content > Content Dashboard
- Hover a table row, quick actions should appear at the right of the row
- Hover a quick action, ie. the pencil icon

### Expected:
- Each quick action has a tooltip
- The pencil icon should display an tooltip with "Edit" content text

### Actual result: No tooltip

This PR tries to address this problem.

## Advice

As far as I know, the quick actions are only used in Content Dashboard, so this change should have no impact in other usages of the taglib 🤔 

## Images

image

### CODE REVIEW

**Comment by beltranrengifo** [comment]
baseline command in this module has no impact
running CI again

**Comment by beltranrengifo** [comment]
ci:test:relevant

**Comment by beltranrengifo** [comment]
ci:test:relevant

**Comment by beltranrengifo** [comment]
Relaunching CI to confirm or discard errors, seem not related to the PR

**Review by kresimir-coko — APPROVED** [review]
Looks simple enough while providing a cool benefit! 👍

**Comment by beltranrengifo** [comment]
ci:test:sf

**Comment by beltranrengifo** [comment]
ci:test:relevant

**Comment by Luizcarlosqueiroz** [comment]
Hey @beltranrengifo ! Those last failures are indeed unrelated. The previous ones were related, but now those tests are fixed.

**Comment by beltranrengifo** [comment]
Triggering the CI again

**Comment by beltranrengifo** [comment]
ci:test:relevant

**Comment by beltranrengifo** [comment]
ci:test:relevant

**Comment by beltranrengifo** [comment]
Rebasing & force pushing

**Comment by beltranrengifo** [comment]
ci:test:sf

**Comment by beltranrengifo** [comment]
ci:test:relevant

**Comment by beltranrengifo** [comment]
@Luizcarlosqueiroz the content dashboard errors are back :(
https://github.com/liferay-frontend/liferay-portal/pull/2307#issuecomment-1149202628

**Comment by beltranrengifo** [comment]
updating and force pushing

**Comment by beltranrengifo** [comment]
ci:test:sf

**Comment by Luizcarlosqueiroz** [comment]
ci:test:relevant

**Comment by beltranrengifo** [comment]
Rebasing and force pushing, now with the commit from @Luizcarlosqueiroz 🤣

**Comment by beltranrengifo** [comment]
ci:test:sf

**Comment by beltranrengifo** [comment]
ci:test:relevant

**Comment by beltranrengifo** [comment]
rebase & push -f

**Comment by beltranrengifo** [comment]
ci:test:sf

**Comment by beltranrengifo** [comment]
ci:test:relevant

**Comment by beltranrengifo** [comment]
ci:test:sf

**Comment by beltranrengifo** [comment]
ci:test:relevant

**Comment by beltranrengifo** [comment]
@Luizcarlosqueiroz would you mind to take a look at this again? 🙌

**Comment by Luizcarlosqueiroz** [comment]
ci:test:relevant

**Comment by beltranrengifo** [comment]
ci:test:relevant

**Comment by beltranrengifo** [comment]
ciforward

**Comment by beltranrengifo** [comment]
ci:forward

**Comment by beltranrengifo** [comment]
ci:test:sf

**Comment by beltranrengifo** [comment]
hi @Luizcarlosqueiroz !!
the SF is failing here, can you plz take a look? I'm not been able to solve it
Thxs!!

**Comment by beltranrengifo** [comment]
rebase & force push

**Comment by beltranrengifo** [comment]
ci:test:sf

**Comment by Luizcarlosqueiroz** [comment]
ci:test:sf

**Comment by Luizcarlosqueiroz** [comment]
ci:test:sf

**Comment by Luizcarlosqueiroz** [comment]
Hey @beltranrengifo ! Now it's working.

**Comment by beltranrengifo** [comment]
ci:test:relevant

**Comment by beltranrengifo** [comment]
Failures seem not related, running again

**Comment by beltranrengifo** [comment]
ci:test:relevant

**Comment by beltranrengifo** [comment]
ci:test:relevant

**Comment by beltranrengifo** [comment]
ci:test:relevant

**Comment by beltranrengifo** [comment]
Let's try one more time

**Comment by beltranrengifo** [comment]
ci:test:relevant

**Comment by john-co** [comment]
Reviewed. Test failures are unrelated based on most recent test runs. :heavy_check_mark: 

Ok to manually forward from QA perspective. Will forward now.

**Comment by john-co** [comment]
forwarded to https://github.com/brianchandotcom/liferay-portal/pull/119391

**Comment by beltranrengifo** [comment]
@liferay-lexicon FYI this is merged 🎉

**Pull request closed without merging**
