### PR TITLE
LPS-183768 | Update NUMBER_OF_VIEWS path

### PR DESCRIPTION
**Pull request by abhnerramos**
**Description**
Update NUMBER_OF_VIEWS path
And remove ignore from two tests that were fixed

**JIRA Ticket**
https://issues.liferay.com/browse/LPS-183768

### CODE REVIEW

**Comment by abhnerramos** [comment]
ci:test:frontend-data-set

**Comment by abhnerramos** [comment]
ci:test:sf

**Comment by abhnerramos** [comment]
ci:test:Sf

**Comment by abhnerramos** [comment]
ci:test:sf

**Comment by abhnerramos** [comment]
ci:test:frontend-data-set

**Comment by abhnerramos** [comment]
hey @CarlosBrichete, LGTM! Could you take a look, please?

**Review by CarlosBrichete — APPROVED** [review]

**Comment by CarlosBrichete** [comment]
LGTM :)

**Comment by abhnerramos** [comment]
ci:forward

**Comment by abhnerramos** [comment]
ci:forward

**Pull request closed without merging**
