### PR TITLE
LPS-142327 | A11yTool - Verifies correct violation details are displayed in the popup

### PR DESCRIPTION
**Pull request by susanchen3**
**Background**
Create automated tests for the A11y tool

**Test Plan**
- Verify there are violations on the page
- Click on the icon on a violation
- Assert the rule name is displayed
- Assert the impact is displayed
- Assert a brief description is displayed
- Assert a link to the occurrence in the side panel is present

**JIRA Ticket:**
https://issues.liferay.com/browse/LPS-142327

### CODE REVIEW

**Comment by susanchen3** [comment]
ci:test:frontend:nocompile

**Comment by john-co** [comment]
Just started reviewing :)

**Review by john-co — APPROVED** [review]
Looks good to me!

**Comment by susanchen3** [comment]
ci:forward

**Pull request closed without merging**
