### PR TITLE
LPS-184403 Create a taglib for ClayPanel

### PR DESCRIPTION
**Pull request by edalgrin**
Follow up from https://github.com/liferay-frontend/liferay-portal/pull/3339

---

This PR create a DXP Tag for the ClayPanel Component and a sample to test it

ezgif com-video-to-gif

### CODE REVIEW

**Review by markocikos — APPROVED** [review]
LGTM! :sparkles:

**Comment by edalgrin** [comment]
ci:test:sf

**Comment by edalgrin** [comment]
ci:test:relevant

**Comment by mateusralv** [comment]
Hi @edalgrin The failures are not related

[Testray comparison](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1686682754756&testrayRunIdA=2349482218&testrayRunIdB=2349692352)

**Comment by edalgrin** [comment]
Thank you @mateusralv !

**Comment by edalgrin** [comment]
ci:forward:force

**Comment by dsanz** [comment]
ci:forward:force

**Pull request closed without merging**
