### PR TITLE
LPD-41252 Extract inline event handlers in <aui:a>

### PR DESCRIPTION
**Pull request by izaera**
**QA analysis**: :green_circle:   https://github.com/liferay-frontend/liferay-portal/pull/4552#issuecomment-2478741420pull/4552#issuecomment-2478638022
**Sign-off**: :green_circle: https://github.com/liferay-frontend/liferay-portal/pull/4552#pullrequestreview-2447843161

----

This is part of https://github.com/liferay-frontend/liferay-portal/pull/4466 (root PR for CSP inline event handlers).

It is in the high risk group, which is composed of infra stuff used pervasively that may break a lot of tests for different teams.

> ⚠️ Note that even though this PR may break tests it doesn't mean it breaks the product.
> Tests can break because:
>
> 1. A bug is introduced in the product, or
> 2. They rely on internals of the taglib changed in the PR

Since the taglib is used almost everywhere we don't have any specific CI test suite to run (we would need to run all of them to make sure). And since we run all tests suites every day on a batch schedule we will rely on that to detect big failures unless someone can find a better way (I'm open to suggestions).

In any case, I've tested one occurence of `<aui:a>` by hand following the procedure described at https://liferay.atlassian.net/browse/LPD-41252?focusedCommentId=2787338 to make sure it's not very badly broken.

### CODE REVIEW

**Comment by izaera** [comment]
ci:test:relevant

**Comment by izaera** [comment]
ci:test:sf

**Comment by izaera** [comment]
ci:report:68741614

**Comment by izaera** [comment]
There are too many unique failures in relevant but I don't think they are really related (or at least most of them are probably not) so I'm going to run relevant again to compare.

**Comment by izaera** [comment]
ci:report:69727810

**Comment by izaera** [comment]
QA analysis:

**First round**: There are too many unique failures in relevant but I don't think they are really related (or at least most of them are probably not) so I'm going to run relevant again to compare.

**Second round**: Found only one relevant bug :point_down: 

```
PortalLogAssertorTest#testScanXMLLog: 
Current URL /group/control_panel/manage/-/sites/sites?p_v_l_s_g_id=33647&p_p_auth=OYCbekZk generates exception: 
java.lang.NullPointerException: Cannot invoke javax.servlet.jsp.tagext.BodyContent.getString() because bodyContent is 
null java.lang.NullPointerException: Cannot invoke javax.servlet.jsp.tagext.BodyContent.getString() because bodyContent is null 
at com.liferay.taglib.aui.ATag.processEndTag(ATag.java:54) 
at com.liferay.taglib.util.IncludeTag.doEndTag(IncludeTag.java:76) 
at org.apache.jsp.view_005fentries_jsp._jspService(view_005fentries_jsp:691) 
...
```

**Comment by izaera** [comment]
ci:test:sf

**Comment by izaera** [comment]
ci:test:relevant

**Review by juanjofgliferay — APPROVED** [review]
LGTM :rocket:

**Comment by izaera** [comment]
ci:forward

**Pull request closed without merging**
