### PR TITLE
LPS-154730: Expose ERC in DocumentsFolder

### PR DESCRIPTION
**Pull request by sergiojimcos**
This PR contains some requested changes from -> https://github.com/brianchandotcom/liferay-portal/pull/121369

**JIRA Ticket:** https://issues.liferay.com/browse/LPS-154730

cc/ @4lejandrito

### CODE REVIEW

**Comment by mateusralv** [comment]
I'm taking a look 🕵🏽‍♂️

**Comment by mateusralv** [comment]
Hi @sergiojimcos, I [compared](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1660142234093&testrayRunIdA=1941666775&testrayRunIdB=1940884336) the failures in your PR with the master and analyzed the results. 

It seems the failure in [semantic-versioning-jdk8/0/0](https://testray.liferay.com/home/-/testray/case_results/1940885964?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D1940884256%26testrayRunId%3D1940884336%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc) is related: 
```
[sync-dir] Synchronizing /opt/dev/projects/github/liferay-binaries-cache-2020/.gradle/caches/modules-2/files-2.1 into /opt/dev/projects/github/liferay-portal/.gradle/caches/modules-2/files-2.1
 [sync-dir] 0 files synchronized in 577ms
     [echo] Executing Gradle task: baseline
     [exec] Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0
     [exec] > Task :classes UP-TO-DATE
     [exec] > Task :jar SKIPPED
     [exec] 
     [exec] > Task :baseline
     [exec]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec] = ================================================== ========== ========== ========== ========== ==========
     [exec] * com.liferay.portal.upgrade.v7_1_x                  MAJOR      3.0.0      3.0.0      4.0.0      VERSION INCREASE REQUIRED
     [exec] 	-   class      com.liferay.portal.upgrade.v7_1_x.UpgradeCounter
     [exec] 		-   extends    com.liferay.portal.kernel.upgrade.UpgradeProcess
     [exec] 		-   method     <init>()
     [exec] 			-   return     void
     [exec] 		-   method     clone()
     [exec] 			-   access     protected
     [exec] 			-   return     java.lang.Object
     [exec] 		-   method     doUpgrade()
     [exec] 			-   access     protected
     [exec] 			-   return     void
     [exec] 		-   method     equals(java.lang.Object)
     [exec] 			-   return     boolean
     [exec] 		-   method     finalize()
     [exec] 			-   access     protected
     [exec] 			-   return     void
     [exec] 		-   method     hashCode()
     [exec] 			-   return     int
     [exec] 		-   method     toString()
     [exec] 			-   return     java.lang.String
     [exec] 	-   class      com.liferay.portal.upgrade.v7_1_x.UpgradeDocumentLibrary
     [exec] 		-   extends    com.liferay.portal.kernel.upgrade.UpgradeProcess
     [exec] 		-   method     <init>()
     [exec] 			-   return     void
     [exec] 		-   method     clone()
     [exec] 			-   access     protected
     [exec] 			-   return     java.lang.Object
     [exec] 		-   method     doUpgrade()
     [exec] 			-   access     protected
     [exec] 			-   return     void
     [exec] 		-   method     equals(java.lang.Object)
     [exec] 			-   return     boolean
     [exec] 		-   method     finalize()
     [exec] 			-   access     protected
     [exec] 			-   return     void
     [exec] 		-   method     hashCode()
     [exec] 			-   return     int
     [exec] 		-   method     toString()
     [exec] 			-   return     java.lang.String
     [exec] 	-   class      com.liferay.portal.upgrade.v7_1_x.UpgradePasswordPolicyRegex
     [exec] 		-   extends    com.liferay.portal.kernel.upgrade.UpgradeProcess
     [exec] 		-   method     <init>()
     [exec] 			-   return     void
     [exec] 		-   method     clone()
     [exec] 			-   access     protected
     [exec] 			-   return     java.lang.Object
     [exec] 		-   method     doUpgrade()
     [exec] 			-   access     protected
     [exec] 			-   return     void
     [exec] 		-   method     equals(java.lang.Object)
     [exec] 			-   return     boolean
     [exec] 		-   method     finalize()
     [exec] 			-   access     protected
     [exec] 			-   return     void
     [exec] 		-   method     hashCode()
     [exec] 			-   return     int
     [exec] 		-   method     toString()
     [exec] 			-   return     java.lang.String
     [exec] 	-   class      com.liferay.portal.upgrade.v7_1_x.UpgradeUserGroup
     [exec] 		-   extends    com.liferay.portal.kernel.upgrade.UpgradeProcess
     [exec] 		-   method     <init>()
     [exec] 			-   return     void
     [exec] 		-   method     clone()
     [exec] 			-   access     protected
     [exec] 			-   return     java.lang.Object
     [exec] 		-   method     doUpgrade()
     [exec] 			-   access     protected
     [exec] 			-   return     void
     [exec] 		-   method     equals(java.lang.Object)
     [exec] 			-   return     boolean
     [exec] 		-   method     finalize()
     [exec] 			-   access     protected
     [exec] 			-   return     void
     [exec] 		-   method     hashCode()
     [exec] 			-   return     int
     [exec] 		-   method     toString()
     [exec] 			-   return     java.lang.String
     [exec] [Baseline Report] Mode: diff (persisted)
     [exec] Semantic versioning is incorrect while checking /opt/dev/projects/github/liferay-portal/portal-impl/portal-impl.jar against /opt/dev/projects/github/liferay-portal/.gradle/caches/modules-2/files-2.1/com.liferay.portal/com.liferay.portal.impl/49.0.0/ca78d886ebf38e1bd75bcd2c7c4e53511c48ad45/com.liferay.portal.impl-49.0.0.jar
     [exec] Gradle build finished at 2022-08-09 15:44:37.621.
```
---
### Failures in headless tests

Those headless tests are failing and doesn’t seem to be related to your PR:
1. ExposeErcFromAssetLibraryForStructuredContentFolders#CannotCreateStructuredContentFolderInAssetLibraryWithExistingErc
2. ExposeErcFromAssetLibraryForStructuredContentFolders#CannotUpdateStructuredContentFolderErcInAssetLibraryWithErcInBody
3. ExposeErcFromAssetLibraryForStructuredContentFolders#CanUpdateStructuredContentFolderNameInAssetLibraryByErc
4. ExposeErcFromAssetLibraryForStructuredContentFolders#CanUpdateSubfolderNameOfStructuredContentFolderInAssetLibraryByPutErc
5. ExposeErcFromAssetLibraryForStructuredContentFolders#GetStructuredContentFolderInAssetLibraryWithSubfolderDeletionByErc
6. ExposeErcFromAssetLibraryForStructuredContentFolders#CanReturnErrorWithGetStructuredContentFolderInAssetLibraryByNonexistentAssetLibraryId
7. ExposeErcFromAssetLibraryForStructuredContentFolders#CanReturnErrorWithGetStructuredContentFolderInAssetLibraryByNonexistentErc

They all have the same error:
```
 [exec] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':yarnInstall'.
     [exec] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:208)
     [exec] 	at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:263)
```
---
#### Flaky, not unique
1. com.liferay.document.library.change.tracking.test.DLFileVersionTableReferenceDefinitionTest
2. PortalSmokeUpgrade#ViewPortalSmokeArchive7413

cc: @john-co

**Comment by mateusralv** [comment]
Update: The [semantic-versioning-jdk8/0/0](https://testray.liferay.com/home/-/testray/case_results/1940885964?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D1940884256%26testrayRunId%3D1940884336%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc) failure started appearing in other PRs so it is not related to this PR. Safe to forward. 🚀

**Comment by 4lejandrito** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/121551. Thanks @mateusralv!

**Comment by 4lejandrito** [comment]
ci:close

**Pull request closed without merging**
