### PR TITLE
LPS-148445 Webpack based build MVP

### PR DESCRIPTION
**Pull request by izaera**
Resend of https://github.com/liferay-frontend/liferay-portal/pull/2037

### CODE REVIEW

**Comment by izaera** [comment]
ci:test:sf

**Comment by izaera** [comment]
ci:test:relevant

**Comment by izaera** [comment]
ci:test:relevant

**Comment by izaera** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
CI really doesn't like you these days 🥲

**Comment by izaera** [comment]
ci:test:relevant

**Comment by izaera** [comment]
I fixed one error. Now I'll run the CI while I check the rest...

**Comment by magjed4289** [comment]
Just started reviewing :)

**Comment by izaera** [comment]
The unique failing tests are now faling in master (at least running them locally with a fresh built master). I've rebased, pushed force and now I'll run the tests again to see if they turn green. 

Apparently, the rest of failing tests are OK :crossed_fingers:

**Comment by izaera** [comment]
ci:test:relevant

**Comment by izaera** [comment]
ci:test:relevant

**Comment by magjed4289** [comment]
Just started reviewing :)

**Comment by izaera** [comment]
OK, found the problem. It is related to the changes in AMD loader (https://github.com/liferay-frontend/liferay-portal/pull/2080/commits/1792500e3276a9d4367103781f6b85f5afd6e74c in liferay-portal, https://github.com/liferay/liferay-frontend-projects/commit/e8e612bb6dd0177e34d7eece19f28633bef412fb in amd-loader).

That change causes all AMD modules to be loaded with <script type=module> (ESM) semantics which causes issues with old code.

For example, in our case, because class name fields are read-only in ESM and throw when changed, metal is failing to execute this code -> https://unpkg.com/browse/metal@2.16.8/lib/coreNamed.js#L132

This didn't fail before because in non ESM scripts you can set a function or class name and the statement is simply ignored (ie: it's a no-op).

What I will do is change the AMD loader so that it only loads ESM->ASM bridges as <script type=module>. This way we won't break the old semantics.

**Comment by izaera** [comment]
ci:test:relevant

**Comment by izaera** [comment]
I've rebased after investigating the failing tests which, IMO, are fake. This is because I get the same error running the test locally no matter it I start a vanilla master Portal or a portal from this PR. Also, it was apparently a flakey test last Friday.

See https://liferay.slack.com/archives/C3JBR21HA/p1649666192473119 for more info

**Comment by izaera** [comment]
ci:test:relevant

**Comment by Esther-OC** [comment]
Failing issues are, as @izaera said, flaky, they were investigated and solved in [LRQA-74163](https://issues.liferay.com/browse/LRQA-74163) and the test fix has already been merged in [#115936 ](https://github.com/brianchandotcom/liferay-portal/pull/115936 ).

So if the build (still running right now when writing this comment) fails with the same issue, we will reopen the issue; but, as the PR is not related to the problem, it can be forwarded manually from QA perspective.

**Comment by izaera** [comment]
Going to manually forward this to Brian.

**Pull request closed without merging**
