### PR TITLE
LPS-184812 Set JS Import Maps Entry FF type to release

### PR DESCRIPTION
**Pull request by izaera**

### CODE REVIEW

**Comment by izaera** [comment]
ci:test:relevant

**Comment by deborasoliveira** [comment]
The failures seem to be unrelated to this PR according to the [comparison](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=2&testrayRunIdB=2307548639&testrayRunIdA=2306184818&statusB=3).

- One of the failures is flaky and the other is already linked to an issue on JIRA to be investigated.

**Comment by izaera** [comment]
Thx @deborasoliveira  :-)

**Review by bryceosterhaus — APPROVED** [review]

**Comment by izaera** [comment]
ci:forward:force

**Pull request closed without merging**
