### PR TITLE
LPS-171673 Setting a custom name for FDS View results in error on view render

### PR DESCRIPTION
**Pull request by markocikos**
### References

- [LPS-171673 Setting a custom name for FDS View results in error on view render](https://issues.liferay.com/browse/LPS-171673)

### What is the goal of this PR?

Bugfix.

### What does it look like?

No changes in UI. Sample module should continue to work normally.

### Steps to reproduce

1. Deploy `frontend-data-set-sample-web`.
2. Place `Frontend Data Set Sample` widget on any page.

### CODE REVIEW

**Comment by markocikos** [comment]
Force-pushed, to remove fork desync ugliness and simplify review. No changes in code.

**Comment by markocikos** [comment]
Force-pushed. Added commit https://github.com/liferay-frontend/liferay-portal/pull/2924/commits/71fff18284640c580b0745ad4a73596a36151116 handling a case I just noticed, where stored `activeView` may no longer exist in `views`.

**Comment by markocikos** [comment]
ci:test:sf

**Comment by markocikos** [comment]
ci:test:relevant

**Comment by markocikos** [comment]
ci:test:relevant

**Comment by mateusralv** [comment]
I'm taking a look 🕵️‍♀️

**Comment by mateusralv** [comment]
Hi @markocikos the failures are not related to your PR. 

[Testray comparison](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1673378427098&testrayRunIdA=2154383316&testrayRunIdB=2154365302)

**Comment by markocikos** [comment]
@dsanz @edalgrin @bryceosterhaus Could I get a quick review please :pray:

**Review by edalgrin — APPROVED** [review]
It seems it's working properly, LGTM!

**Comment by markocikos** [comment]
I'll try forwarding one more time, manually forward if it fails.

**Comment by markocikos** [comment]
ci:forward

**Pull request closed without merging**
