### PR TITLE
LPS-132761 Active View API: change to path parameters and add java client & test modules

### PR DESCRIPTION
**Pull request by nhpatt**
Change query parameters to path parameters because those values are required.

Add Java client and test modules. Because these are unusual APIs (receive String/Object, return response) it forces me to revamp the test/client generation to support non-schemas, like Object.

/cc @dsanz

### CODE REVIEW

**Comment by nhpatt** [comment]
ci:test:sf

**Comment by nhpatt** [comment]
ci:test:sf

**Comment by nhpatt** [comment]
ci:test:relevant

**Comment by nhpatt** [comment]
ci:test:relevant

**Review by javierdearcos — APPROVED** [review]

**Comment by nhpatt** [comment]
ci:test:relevant

**Comment by nhpatt** [comment]
ci:test:relevant

**Comment by nhpatt** [comment]
--rebased and retrying

**Comment by nhpatt** [comment]
ci:forward

**Pull request closed without merging**
