### PR TITLE
LPS-117288 Update liferay-ckeditor to 4.14.1-liferay.5

### PR DESCRIPTION
**Pull request by mateomustapic**
[Release notes](https://github.com/liferay/liferay-ckeditor/releases/tag/v4.14.1-liferay.5)

### CODE REVIEW

**Comment by mateomustapic** [comment]
ci:test:sf

**Comment by mateomustapic** [comment]
ci:test:relevant

**Comment by carloslancha** [comment]
image

Poor @wincent 😛

**Comment by mateomustapic** [comment]
> image
> 
> Poor @wincent 😛
I believe the description would be identical to commit message and PR title, so I thought there is no need for desc :D

**Comment by wincent** [comment]
> I believe the description would be identical to commit message and PR title, so I thought there is no need for desc :D

unnacceptable

In all serious, there is pretty much *always* something useful to put in a description. For example, this one could be:

> [Release notes](https://github.com/liferay/liferay-ckeditor/releases/tag/v4.14.1-liferay.5)

I'll go ahead and edit that in for you.

**Comment by wincent** [comment]
I also want to add...

outrage

**Comment by markocikos** [comment]
All green, LGTM!

**Comment by markocikos** [comment]
ci:forward

**Pull request closed without merging**
