### PR TITLE
LPS-195638 Add tests for CX - Data Set fragment

### PR DESCRIPTION
**Pull request by JerryAdrianoo**
**Description:**
Adding tests for the new CX in the Data Set fragment.

**Jira Ticket:**
https://liferay.atlassian.net/browse/LPS-195638

### CODE REVIEW

**Comment by JerryAdrianoo** [comment]
ci:test:frontend

**Comment by JerryAdrianoo** [comment]
ci:test:frontend

**Comment by JerryAdrianoo** [comment]
@CarlosBrichete failures are not related 😄

**Review by CarlosBrichete — APPROVED** [review]
LGTM :)

**Comment by JerryAdrianoo** [comment]
ci:forward

**Comment by JerryAdrianoo** [comment]
ci:test:sf

**Comment by JerryAdrianoo** [comment]
ci:test:sf

**Comment by JerryAdrianoo** [comment]
ci:forward

**Pull request closed without merging**
