### PR TITLE
LPS 156393

### PR DESCRIPTION
**Pull request by robertoDiaz**
To reproduce the issue follow the LPS steps

As explained the resulting markup is:

`<a class="btn btn-outline-borderless btn-monospaced btn-sm btn-outline-secondary lfr-portal-tooltip"href="http://www.facebook.com/sharer.php?u=xxx" title="Facebook" ><svg class="lexicon-icon lexicon-icon-social-facebook"role="presentation" viewBox="0 0 512 512" ><use xlink:href="xxx" /></svg></a>`

it produces some accessibility problems:

The expected behavior is:

`<a class="btn btn-outline-borderless btn-monospaced btn-sm btn-outline-secondary lfr-portal-tooltip" href="http://www.facebook.com/sharer.php?u=xxx" title="Facebook" ><svg class="lexicon-icon lexicon-icon-social-facebook"role="presentation" viewBox="0 0 512 512" ><use xlink:href="xxx" /></svg></a>`

cc: @antonio-ortega

### CODE REVIEW

**Review by diegonvs — APPROVED** [review]
Interesting. If we search for `p"href"` we can see the wrong string concat.

**Comment by diegonvs** [comment]
ci:forward

**Comment by john-co** [comment]
cc/ @mateusralv , please also analyze test results here.

**Comment by mateusralv** [comment]
Hi @robertoDiaz The failures don’t seem to be related to your PR.
cc: @john-co

**Pull request closed without merging**
