### PR TITLE
LPS-119771 Update @clayui/* packages to new version

### PR DESCRIPTION
**Pull request by matuzalemsteles**
Contains some more fixes related to focus manager and behavior correction with ColorPicker, I ended up using LPS-119771 to push this release.

- Diff https://github.com/liferay/clay/pull/3658

This also includes some changes to the Nav component that did not enter the PR from the last release, you can check the changes in the PR https://github.com/liferay/clay/pull/3639.

I'm having trouble running all the portal tests on my local machine, it always breaks on the App Builder tests, it only happens on my machine for some time, I don't know why 🤷‍♂️. I will wait for the CI to check which tests I need to generate a new snapshot.

### CODE REVIEW

**Comment by matuzalemsteles** [comment]
ci:test:sf

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by matuzalemsteles** [comment]
Hey @john-co and @PablitoBonito I checked these local tests and they are all passing, could you check this out?

**Comment by john-co** [comment]
ci:test:bundle

**Comment by john-co** [comment]
Reviewed. Test failures are unrelated. :heavy_check_mark: 
Forms#ChangeFieldType seems like a fluke: screenshot_7

https://liferay.spiraservice.net/16/TestCase/133994.aspx

All the other unique failing tests are failing in other PRs so they seem unrelated.
ie: 
screenshot_8

**Comment by john-co** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
ci:forward

**Pull request closed without merging**
