### PR TITLE
[7.4-only]LPS-125193 Remove $compat-popover in Classic and Admin

### PR DESCRIPTION
**Pull request by pat270**
https://issues.liferay.com/browse/LPS-125193

This removes Clay 1 / BS3 popover classes. It looks like everything has been ported over to Clay 3 already. I went ahead and removed old popover CSS that was not in use anymore.

### CODE REVIEW

**Comment by pat270** [comment]
ci:test:sf

**Comment by marcoscv-work** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcoscv-work** [comment]
LGTM !

**Comment by marcoscv-work** [comment]
ci:forward

**Comment by marcoscv-work** [comment]
do we still need [7.4-only] label? :-P

**Pull request closed without merging**
