### PR TITLE
LPS-129175 - Align header with the application bar

### PR DESCRIPTION
**Pull request by marcoscv-work**
This PR fixes the classic theme header alignment with the rest of the vertically aligned elements.

image

I've tested other solutions and I think this is the cleanest

--- 

How to test the PR:

- Open portal
- See the new awesome alignment

### CODE REVIEW

**Review by edalgrin — APPROVED** [review]

**Comment by marcoscv-work** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
Hey @marcoscv-work, what would this do to Widget Pages? Maybe we don't care about those at all anymore, but felt I needed to ask :)

**Comment by marcoscv-work** [comment]
> Hey @marcoscv-work, what would this do to Widget Pages? Maybe we don't care about those at all anymore, but felt I needed to ask :)

Oh, yeah, this was a quick fix for the release, Juan Anton is working on a new site and stylebook which will be included as default site out of the box, and after a meeting with him we decided to do this but probably in a future theme header and footer will be hidden and implemented by fragments

**Comment by marcoscv-work** [comment]
ci:forward

**Comment by jbalsas** [comment]
> Oh, yeah, this was a quick fix for the release, Juan Anton is working on a new site and stylebook which will be included as default site out of the box, and after a meeting with him we decided to do this but probably in a future theme header and footer will be hidden and implemented by fragments

I don't think you answered the question :D

What would this do to Widget Pages?

**Comment by marcoscv-work** [comment]
image

**Pull request closed without merging**
