### PR TITLE
LPS-114050 Use new Layout Tags in JSPs in ratings-taglib

### PR DESCRIPTION
**Pull request by jbalsas**
This PR just replaces current raw html markup with proper `clay:*` tags.

See below screenshots of the different display types available through the `ratings` tag:

### Thumbs
Screen Shot 2020-06-22 at 12 49 36

### Stars
Screen Shot 2020-06-22 at 12 52 28

### Stacked Stars
Screen Shot 2020-06-22 at 12 53 14

Not sure if the `(1 Vote)` misalignment is also present in `master`... will check later.

**Edit:** The component looks the same currently in `master` (unless my test was wrong), so team Lima can take that for the future if they wish.

### Like
Screen Shot 2020-06-22 at 12 53 39

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
/cc @adolfopa, @boton, @ambrinchaudhary... do you mind taking a quick look over here?

Thanks!

**Comment by jbalsas** [comment]
Seeing as this is green, I'm going to forward.

@adolfopa, @boton, @ambrinchaudhary, feel free to ask for or send any required followups after this!

**Comment by jbalsas** [comment]
ci:forward

**Comment by boton** [comment]
Look good but [we remove the <clay:button](https://github.com/liferay/liferay-portal/commit/319a4723f0cf304a877e20cf3a5da6b1ecb869ac) to avoid performance issues.

**Comment by jbalsas** [comment]
Please, read the commit description ;)

> This tag is in a hot path where performance is critical. For that reason,
we used to inline html code directly because our IncludeTag based jsp tags
had too much overhead.
>
> New `clay:*` tags extend `AttributesTagSupport` directly making them much
faster and lighter since they simply render the markup from Java on the
server side and then hydrate with JS when needed.
> 
> This particular change was used as a sample for our performance tests
and was greenlighted at slnn#483

**Comment by boton** [comment]
Sorry, I miss that, It's awesome :D

**Pull request closed without merging**
