### PR TITLE
LPS-XXXXXXX Test

### PR DESCRIPTION
**Pull request by wincent**
Please ignore. Just wanting to see whether bot will comment on a PR in this repo.

### CODE REVIEW

**Comment by wincent** [comment]
ci:test:sf

**Comment by wincent** [comment]
Going to wait a few minutes to see if that starts. At the time I issued that comment, I wasn't a collaborator yet on this repo, but I don't think that should matter because people issue comments on my fork all the time to make the bot do stuff and it still works even though they are not collaborators. Not sure whether membership in the liferay org is a prerequisite for it working (either on the part of the PR author or the fork owner).

**Comment by wincent** [comment]
One more try, but this time I will do it from the `liferay-frontend` user just to see if that makes any difference.

**Comment by liferay-frontend** [comment]
ci:test:sf

**Comment by liferay-frontend** [comment]
ci:help

**Comment by liferay-frontend** [comment]
Well, let's try something other than `ci:test:sf`.

**Comment by liferay-frontend** [comment]
ci:test:relevant

**Comment by liferay-frontend** [comment]
ci:test:sf

**Comment by wincent** [comment]
Going to try with a fresh PR as well, now that `@liferay-frontend` is in the `@liferay` org.

**Comment by wincent** [comment]
Didn't work there on first try, but I deleted and recreated the webhook to see if that makes any difference.

**Comment by wincent** [comment]
ci:test:sf

**Comment by wincent** [comment]
#4 shows the integration is now working, so going to close this.

**Pull request closed without merging**
