### PR TITLE
LPS-131179 add GraphQL update endpoint for Object 

### PR DESCRIPTION
**Pull request by nhpatt**
Let's see what happens sending PRs to this repository :D

Adding update to GraphQL Endpoint generated automatically based on the `Object` (app builder 2) registered. Previous PR adding all the GraphQL implementation did not have an update because the service did not expose it.

Added a test to check it, it can also be tested adding an `ObjectDefinition` and an `ObjectEntry` and using /o/api to update it passing the id (the name depends on the `ObjectDefinition` name).

### CODE REVIEW

**Comment by nhpatt** [comment]
ci:test:relevant

**Comment by nhpatt** [comment]
ci:forward

**Comment by jbalsas** [comment]
> Let's see what happens sending PRs to this repository :D

expecting

I see you ninja-forwarded this, that's a bold move for a first PR!

boldmove

**Comment by wincent** [comment]
> I see you ninja-forwarded this, that's a bold move for a first PR!

fast-learner

8. You ninja-forward your very first PR in the repo.

**Comment by izaera** [comment]
I was here :monocle_face:

**Pull request closed without merging**
