### PR TITLE
LPS-202556 Add tests for TranslationAdminStatusLabel

### PR DESCRIPTION
**Pull request by p2kmgcl**
Forwarded from: https://github.com/liferay-echo/liferay-portal/pull/14986
Add tests for translation components.

cc @veroglez

### CODE REVIEW

**Review by bryceosterhaus — APPROVED** [review]
LGTM!

**Comment by p2kmgcl** [comment]
ci:forward

**Comment by p2kmgcl** [comment]
ci:forward

**Comment by p2kmgcl** [comment]
None of this should be failing, we just updated unit tests.

**Comment by p2kmgcl** [comment]
ci:forward:force

**Pull request closed without merging**
