### PR TITLE
LPS-147149 Avoid rendering DropdownActionsTag

### PR DESCRIPTION
**Pull request by victorg1991**
Hey good people of frontend infra!

Yesterday this bug was reported: https://issues.liferay.com/browse/LPS-147120

After digging a bit, I've isolate the root cause and opened this one: https://issues.liferay.com/browse/LPS-147149

The reproducing steps are written in Jira, they are very large to put those here 🕯️ 

**This PR should fix the problem that may be occurring in the portal due to the bug, but it may be worth opening a new task to investigate this issue a bit more,** because it seems related to how the search container is rendering the rows. This is the simplest solution I've found. Given that the original issue was considered a blocker, it is desirable to have this merged soon.

Let me know what do you think

### CODE REVIEW

**Review by julien — APPROVED** [review]

**Comment by dsanz** [comment]
@tinycarol @julien , I asked John to forward this if he verifies that issue gets fixed. As @victorg1991 suggests, let's take a deeper look next week. Thank you!

**Comment by john-co** [comment]
Just started reviewing :)

**Comment by john-co** [comment]
ci:test:app-servers

**Comment by john-co** [comment]
ci:test:environments

**Comment by john-co** [comment]
Issue looks fixed on wildfly from manual testing for https://issues.liferay.com/browse/LPS-147149 and https://issues.liferay.com/browse/LPS-147120

I only observed 2 clay cards from following the steps in description of https://issues.liferay.com/browse/LPS-147149 but can follow up on that later since atleast it renders 2 instead of portlet being completely unavailable.
Selection_147

**Comment by john-co** [comment]
ci:forward

**Pull request closed without merging**
