### PR TITLE
LPS-128227 Links inside liferay-ui:icon-menu should contain `dropdown-item` css class

### PR DESCRIPTION
**Pull request by jbalsas**
This is basically a different way to add `dropdown-item` classes to icons within icon menus to prevent the class from being accidentally set in icons causing the issue described in [Login Modal create account and forgot password links are styled incorrectly](https://issues.liferay.com/browse/LPS-128227)

wiki-portlet

### CODE REVIEW

**Comment by jbalsas** [comment]
I'm the worst coder ever 🙈 

theworst

**Comment by jbalsas** [comment]
Luckily, I amended Patrick's comment, so it's his fault 😂

**Comment by jbalsas** [comment]
ci:stop

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by georgel-pop-lr** [comment]
Just started reviewing :)

**Comment by pat270** [comment]
@jbalsas I wish I knew about this before I made all the `linkCssClass="dropdown-item"` changes!!

About 4) in https://github.com/liferay-frontend/liferay-portal/pull/844#issuecomment-788796164. It's using `liferay-frontend:management-bar-button` to generate those buttons (they're not in a management bar). I think the reason my pr triggered the failure is due to the portlet custom styles (`padding: 0;`) + the addition of `c-inner` pattern to `aui:a`. The title and the buttons could use an overhaul it's a mix of old, new, and using tags in places they weren't meant to be used.

We have dropdown-items with icons like in Content & Data > Wiki that don't follow the lexicon pattern where the icon should be on right edge. Not many people will notice this one, but I was trying to be complete.

dropdown-with-icon

There were also a couple places where the icon was on the left and also didn't match.

- export-import-web/src/main/resources/META-INF/resources/export/processes_list/export_layouts_processes.jsp
- knowledge-base-web/src/main/resources/META-INF/resources/admin/common/article_history.jsp
- my-subscriptions-web/src/main/resources/META-INF/resources/subscription_action.jsp
- wiki-web/src/main/resources/META-INF/resources/wiki/page_history_action.jsp

The image below is due to `c-inner` generated by `aui:icon` (I added this in another pr). If you remove the `c-inner` class the icon will be aligned left, but I really think we should try and implement `c-inner` on links while we can since we had complaints about focus styles being too aggressive.

Content & Data > Knowledge Base > Click Article > Open Info Panel > Versions in Info Panel
icon-on-left

**Comment by jbalsas** [comment]
Hey @pat270!

> @jbalsas I wish I knew about this before I made all the linkCssClass="dropdown-item" changes!!

Well, you live and learn! ;)

About the other changes, I think we can try to make them once dust settles a bit. One thing with huge PRs that make many different adjustments is that they're extremely hard to:
- Push forward (many different issues from many different places)
- Undo (many interrelations between changes)
- Track (hard to understand why a change was made in the scope of a task that seems unrelated)

Ideally, we should be creating bugs for the things you see and assign them Fix Priorities as pero our Assessment Matrix. A fix, even simple ones, often comes with the risk of regressions, so low priority fixes should be looked at carefully because the cost of the regression caused might be bigger than the value of the fix (plus the things we stopped doing to fix it).

This is to say I'd recommend:
- File things you see independently
- Prioritize important issues and big tasks over small fixes
- Work on them independently one by one when taking them

**Comment by pat270** [comment]
@jbalsas this makes sense. Everything is so intertwined it seemed logical for me to do it all in one go. It's really hard having to navigate through our infrastructure to add a css class.

nesting-dolls

**Comment by jbalsas** [comment]
Hey @john-co, @calvinctvo, failures look unrelated but since this changes some markup maybe something needs test fixes. Could you take a look and forward if looks good or when fixed?

Thanks!

**Comment by calvinctvo** [comment]
ci:test:stable

**Comment by john-co** [comment]
cc/ @vicnate5 , another NPE error on upgrade test encountered today.

**Comment by calvinctvo** [comment]
Hi @jbalsas , I've checked [the history](https://testray.liferay.com/home/-/testray/case_results/1496430747?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcases%2F1310700773%2Fview%3Fcur%3D1%26delta%3D200%26testrayCaseId%3D1310700773%26orderByCol%3DcreateDate_sortable%26orderByType%3Ddesc) and I don't think this failure is related. Poshi Report doesn't show any errors besides the sign in warning. I've retrigger `ci:test:stable` and waiting for the result.

**Comment by jbalsas** [comment]
ci:forward

**Comment by john-co** [comment]
Reviewed. Test failures are unrelated. :heavy_check_mark:  Will manually forward.

Immediately upon landing page, liferay error:
```
LIFERAY_ERROR: Portlet com_liferay_configuration_admin_web_portlet_InstanceSettingsPortlet from com.liferay.configuration.admin.web_5.0.0 [626] failed to initialize
```
cc/ @vicnate5

**Comment by john-co** [comment]
manually forwarded to https://github.com/brianchandotcom/liferay-portal/pull/99569

**Pull request closed without merging**
