### PR TITLE
LPS-136580 Notify users subscribed to a tag when a new entity using the tag is created

### PR DESCRIPTION
**Pull request by javierdearcos**

### CODE REVIEW

**Review by nhpatt — APPROVED** [review]

**Comment by nhpatt** [comment]
Everything looks go, 👏 👏 👏 , forwading

**Comment by nhpatt** [comment]
ci:forward

**Comment by javierdearcos** [comment]
ci:forward

**Comment by javierdearcos** [comment]
ci:forward

**Comment by nhpatt** [comment]
Rebase ^ :(

**Comment by javierdearcos** [comment]
ci:stop

**Comment by javierdearcos** [comment]
ci:forward

**Comment by javierdearcos** [comment]
ci:reevaluate:1077401_7309

**Comment by javierdearcos** [comment]
ci:forward

**Comment by javierdearcos** [comment]
ci:forward

**Comment by javierdearcos** [comment]
ci:forward

**Comment by javierdearcos** [comment]
ci:forward

**Comment by javierdearcos** [comment]
ci:reevaluate:1287401_384

**Comment by javierdearcos** [comment]
ci:forward

**Pull request closed without merging**
