### PR TITLE
LPS-196835 Improve icon selection in Item Actions creation page v2

### PR DESCRIPTION
**Pull request by markocikos**
### References

- [LPS-196835 Improve icon selection in Item Actions creation page](https://issues.liferay.com/browse/LPS-196835)
- Followup on https://github.com/liferay-frontend/liferay-portal/pull/3772

### What is the goal of this PR?

This followup contains minor tweaks, based on https://github.com/liferay-frontend/liferay-portal/pull/3772#issuecomment-1802417047  

@JerryAdrianoo:
- The first comment about input behavior, that's a bug. I fixed this in a commit.
- The second comment about mouse cursor, I could not reproduce it. We were already setting this in code in PR, `cursor: pointer;`. You can see I have the cursor in movie below.
- I made some minor tweaks to styles, fixing glitching behavior on input and adding a bit of padding to icon items in modal. They looked to me a bit too crowded :slightly_smiling_face: 

@chestofwonders I couldn't force-push to your branch, so I'm opening a followup. Please invite me as a collaborator on your fork. I invited you on mine.

### What does it look like?

https://github.com/liferay-frontend/liferay-portal/assets/5435511/f4a11442-236f-4503-992b-a5537489948a

### CODE REVIEW

**Comment by markocikos** [comment]
ci:test:relevant

**Comment by JerryAdrianoo** [comment]
Thanks @markocikos for clarifying. When the relevant finish, I'll start working in the fixes :)

**Comment by chestofwonders** [comment]
> ### References
> * [LPS-196835 Improve icon selection in Item Actions creation page](https://issues.liferay.com/browse/LPS-196835)
> * Followup on [LPS-196835 Improve icon selection in Item Actions creation page #3772](https://github.com/liferay-frontend/liferay-portal/pull/3772)
> 
> ### What is the goal of this PR?
> This followup contains minor tweaks, based on [#3772 (comment)](https://github.com/liferay-frontend/liferay-portal/pull/3772#issuecomment-1802417047)
> 
> @JerryAdrianoo:
> 
> * The first comment about input behavior, that's a bug. I fixed this in a commit.
> * The second comment about mouse cursor, I could not reproduce it. We were already setting this in code in PR, `cursor: pointer;`. You can see I have the cursor in movie below.
> * I made some minor tweaks to styles, fixing glitching behavior on input and adding a bit of padding to icon items in modal. They looked to me a bit too crowded 🙂
> 
> @chestofwonders I couldn't force-push to your branch, so I'm opening a followup. Please invite me as a collaborator on your fork. I invited you on mine.
> 
> ### What does it look like?
>  vokoscreenNG-2023-11-09_14-18-36.mp4

Thank you @markocikos! I've added you to my repo aswell, you should be able to push now

**Comment by markocikos** [comment]
@JerryAdrianoo console log warnings are not blockers for tasks. They typically inform that the code is in a less-then-ideal, but not in a breaking way. `checkPropTypes` warnings are common culprits, they are a form of meta-data on the code. They are very safe to ignore.

**Comment by JerryAdrianoo** [comment]
@markocikos thanks for clarifying! I hope to finish the fixes today.

**Comment by JerryAdrianoo** [comment]
ci:test:relevant

**Comment by JerryAdrianoo** [comment]
@markocikos you can forward it! :)

**Comment by chestofwonders** [comment]
ci:forward

**Pull request closed without merging**
