### PR TITLE
[7.4+][PART 3] LPS-134071 Migrate frontend-theme-styled CSS

### PR DESCRIPTION
**Pull request by edalgrin**
This PR removes all the unused and third-party CSS from `frontend-theme-styled`
- [Original PR](https://github.com/liferay-frontend/liferay-portal/pull/1877#issuecomment-1064926374)
- [Strategy](https://liferay.atlassian.net/wiki/spaces/ENGFRONTENDINFRA/pages/1341882669/LPS-127086+-+Analyze+and+prototype+possible+theme+optimizations?focusedCommentId=1969652346#comment-1969652346)
- [Changelog](https://docs.google.com/spreadsheets/d/1IG7o3hAn9w91-sg_vXQZeWhJsRBSSMTrGUi-EVfQ6H8/edit#gid=0)
- [Module testing](https://docs.google.com/spreadsheets/d/1IG7o3hAn9w91-sg_vXQZeWhJsRBSSMTrGUi-EVfQ6H8/edit#gid=1130153366)

### CODE REVIEW

**Comment by Esther-OC** [comment]
Review of the failures:

PR's [comparison](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=3&testrayRunIdB=1644782382&testrayRunIdA=1645653212&statusB=2) with upstream: 1 unique failure:

[LocalFile.CPCommerceWarehouses#ConsumeBookedQuantitiesFromMultipleWarehouses](https://testray.liferay.com/home/-/testray/case_results/1645653868) --> 'java.lang.NullPointerException' that seems related to the PR.  
🧐 Fetching the PR to check it locally, I will update the comment when it's ready.

**Comment by Esther-OC** [comment]
ci:test:relevant

**Comment by Esther-OC** [comment]
Review from QA done, issues are flaky and not related to the PR.

So it can be forwarded manually.

**Comment by edalgrin** [comment]
Thank you @Esther-OC , I'll proceed with the manual forward.

**Comment by edalgrin** [comment]
Manual forwarded to https://github.com/brianchandotcom/liferay-portal/pull/115243

**Pull request closed without merging**
