### PR TITLE
LPS-135421 Add liferay-frontend:stylesheet tag

### PR DESCRIPTION
**Pull request by izaera**
This is a resend of https://github.com/liferay-frontend/liferay-portal/pull/1245, but it renders the CSS `<link>` in server. Thus, it doesn't need to rely on the AMD loader.

Care has been taken to avoid fetching CSS files twice from the server in case someone requests it from a JSP first, then from a JS module. In that case, the browser cache will avoid a second trip to the server because the CSS will be found in the cache.

This can be tested by invoking the taglib from any portlet, like this:

```
<liferay-frontend:stylesheet bundle="com.liferay.my.test.bundle" css="example.css" />
```

### CODE REVIEW

**Comment by izaera** [comment]
ci:test:sf

**Comment by izaera** [comment]
ci:test:relevant

**Comment by nhpatt** [comment]
LGTM :D

**Review by nhpatt — APPROVED** [review]

**Comment by izaera** [comment]
ci:forward

**Comment by jbalsas** [comment]
> Care has been taken to avoid fetching CSS files twice from the server in case someone requests it from a JSP first, then from a JS module. In that case, the browser cache will avoid a second trip to the server because the CSS will be found in the cache.

How does that work? I'm a bit confused by the wording here... what has been done to avoid fetching CSS files twice?

**Comment by nhpatt** [comment]
> I see the WebKeys.PAGE_TOP usage, so I understand we won't be printing duplicated link tags for the same resource but 
I'm not sure what other assurances are there. I guess you're referring to the fact that if the tag is used from the jsp, the link tag goes to the head and will be fetched prior to JS running? (this might depend on where the JS doing the loading is found...)

The issue we discussed was doing an import in JS + the tag and those links being generated with different logic, have different parameters, and the browser does not detect them as the same resource. We talked about change that logic to be consistent in both implementations but I understood that those changes were part of fixing a build in the toolkit with how the language is being sent (it isn't). But @izaera knows best.

**Comment by izaera** [comment]
> I see the WebKeys.PAGE_TOP usage, so I understand we won't be printing duplicated link tags for the same resource but
I'm not sure what other assurances are there. I guess you're referring to the fact that if the tag is used from the jsp, the link tag goes to the head and will be fetched prior to JS running? (this might depend on where the JS doing the loading is found...)

As @nhpatt says, the problem I was having with the very first version was that, by using `AbsolutePortalURLBuilder.forModuleStylesheet()`, the URL pointing to the CSS file has several extra parameters (like `languageId`, `t`, `b`, ...). On the contrary, the URLs that the toolkit makes when wrapping a CSS file don't carry any parameter, but work too.

So, what I did was using `absolutePortalURLBuilder.forModule()` in [this commit](https://github.com/liferay-frontend/liferay-portal/pull/1307/commits/213e333b2192a185f88efe4546b031e3743bd5b4) to generate a plain URL with no parameters.

That way, both the URLs generated by the toolkit and the server are identical and the browser's cache guarantees that it will be downloaded just once.

> I understood that those changes were part of another PR + fixing a build in the toolkit 

Regarding RTL, which made us think that we needed to fix the toolkit URLs, it is not necessary. This is because the RTL machinery in the portal looks for the language id inside the session too, so even in absence of the `languageId` parameter, it works.

Other parameters (as `t` and `b`) are used to make cache invalidation more resilient, but it appear to work without them too since they only address corner cases (like redeployment of OSGi modules, which should not be done in production) and nobody has complained about it ever. In fact, we also send etag headers so it is very possible that we don't need those parameters any more...

**Pull request closed without merging**
