### PR TITLE
LPS-138402 Disable isolation from categories selector

### PR DESCRIPTION
**Pull request by victorg1991**
Sending this here since I've to change Modal.js to propagate `iframeBodyCssClass`

**Steps to reproduce**:

1. Add a vocabulary
2. Add a category
3. Add a web content
4. Expand the Categorization section in sidebar
5. Click the Select button of new vocabulary
6. Select the category

**Expected result**
The category card should have blue background

Treeview styles are not being applied because the css doesn't have into account the cadmin selector. I'm disabling the isolation from the category selection because It is breaking the ui and it is not needed since It is contained in an iframe that will only have the admin theme.

cc/ @pat270 :)

### CODE REVIEW

**Comment by carloslancha** [comment]
@victorg1991 could you please add to the description the reason and the rationale of the change and some testing steps? Thx!

**Comment by pat270** [comment]
This LGTM!

**Comment by diegonvs** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
Done @carloslancha :)

**Comment by diegonvs** [comment]
Regarding this CI result: https://github.com/liferay-frontend/liferay-portal/pull/1422#issuecomment-910458447

It may be failing due to
https://github.com/liferay/liferay-portal/blob/master/portal-web/test/functional/com/liferay/portalweb/functions/SelectFrame.function#L8 ? 

/cc @john-co

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by john-co** [comment]
Some of these tests have been failing in upstream already. The handful of tests I looked at don't look related. The last test was comparing against a base branch that didn't run any tests so it caused the PR tester to mark them as unique. see [example](https://testray.liferay.com/home/-/testray/case_results/1557833887?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcases%2F1538132195%2Fview%3Fcur%3D1%26delta%3D200%26testrayCaseId%3D1538132195%26orderByCol%3DcreateDate_sortable%26orderByType%3Ddesc)

The latest acceptance run was supposed to be [this](https://testray.liferay.com/home/-/testray/case_results/1557849155?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcases%2F1538132195%2Fview%3Fcur%3D1%26delta%3D200%26testrayCaseId%3D1538132195%26orderByCol%3DcreateDate_sortable%26orderByType%3Ddesc) so I'm not sure why it didn't compare against it...will ask CI team to take a look.

**Comment by john-co** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by john-co** [comment]
Just glancing at the PR test results, I'm pretty sure the test failures are unrelated since each test run is failing on different set of tests. Ok to manually forward.

**Comment by ealonso** [comment]
ci:reevaluate:1297401_140

**Comment by ealonso** [comment]
ci:reevaluate:1297401_140

**Comment by victorg1991** [comment]
sent to brian: https://github.com/brianchandotcom/liferay-portal/pull/106635 since the failures were not related

**Pull request closed without merging**
