### PR TITLE
LPS-155911 Move ScriptData implementation to OSGi land

### PR DESCRIPTION
**Pull request by izaera**
This is necessary to continue with the portal's migration to a full webpack based build.

This PR moves ScriptData rendering to OSGi land to ease maintainability in the future and adds support for ES modules (in addition to the already existing AMD and AUI support).

### CODE REVIEW

**Comment by izaera** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
I'm not the best to review the code, but nothing looks too concerning to me here. LGTM

**Comment by izaera** [comment]
The failed tests suggest that the portal cannot even be accessed but that doesn't seem true (I've checked it locally with and w/o combo servlet and it works correctly in both cases).

**Comment by izaera** [comment]
Failures are not legit IMO

**Comment by izaera** [comment]
ci:test:relevant

**Comment by izaera** [comment]
ci:test:stable

**Comment by izaera** [comment]
ci:test:sf

**Comment by izaera** [comment]
ci:forward

**Comment by john-co** [comment]
Reviewed. There are related test failures :x: 

- Login UI is not editable
Selection_289

- Possible other failures related to path locator on application menu, unable to manually verify due to login issue
image

**Comment by john-co** [comment]
The login issue wasn't reproducible when I built the bundle using `ant all`. It's reproducible using the bundle attached to the `ci:test:relevant` [result comment](https://files.liferay.com/private/bundles/test-1-32/jobs/test-portal-acceptance-pullrequest(master)/builds/4444/liferay-portal-bundle-tomcat.tar.gz)


While testing on `ant all` bundle, I saw a strange UI glitch when adding site membership to created user...this concerns me about overall stability and would recommend `ci:test:upstream-functional` run and request exploratory testing to check for other glitches...

https://user-images.githubusercontent.com/35235266/175607527-2e335144-65e9-4dce-af60-1775f35d4ba3.mp4

**Comment by izaera** [comment]
The new commit I've pushed fixed the [glitch mentioned above](https://github.com/liferay-frontend/liferay-portal/pull/2368#issuecomment-1165762496) and should -most probably- stabilize other parts of the portal a lot.

I'll run the tests again to see what happens. If they seem stable I would forward this because we need it to unblock the webpack epic and, as far as we've seen, all the errors that appear due to this PR (after some stabilization has been done) are minox glitches that may be fixed with small modifications to the failing code or to the ScriptData machinery itself. What do you think @john-co?

**Comment by izaera** [comment]
ci:test:sf

**Comment by izaera** [comment]
First SF so that it fails once as it always happens with my PRs :roll_eyes:

**Comment by izaera** [comment]
ci:test:relevant

**Comment by izaera** [comment]
ci:test:bundle

**Comment by izaera** [comment]
ci:bundle

**Comment by izaera** [comment]
I've managed to reproduce the login issue with my local master copy, by using the portal-ext.properties settings found in the CI bundle (at `bundles/tomcat-9.0.56/webapps/ROOT/WEB-INF/classes`). Now I need to find out what's happening...

**Comment by izaera** [comment]
ci:test:sf

**Comment by izaera** [comment]
ci:test:relevant

**Comment by izaera** [comment]
ci:test:sf

**Comment by izaera** [comment]
ci:test:relevant

**Comment by izaera** [comment]
ci:reevaluate:1297401_3724

**Comment by susanchen3** [comment]
Taking a look now :detective: Looking this [run](https://github.com/liferay-frontend/liferay-portal/pull/2368#issuecomment-1187091551) because I don't think the reevaluate triggered a new testray report

**Comment by susanchen3** [comment]
Based on this [comparison run](https://testray.liferay.com/home/-/testray/case_results/index?statuses=3&testrayBuildId=1909880351&testrayRunId=1909880939&cur=1&delta=200&status=3&orderByCol=testrayComponentName_sortable&orderByType=asc), I'm unable to interact with some parts of portal. Some parts I can't interact with on first visit, but when I refresh I am able to (but this isn't ideal).

### Unable to save:

**Permissions:**
All permissions, not just account roles.

1. Control Panel > Roles > Account Roles
2. Create new account role > Save 
3. Define Group Scope Permissions > Site and Asset Library Administration > Applications > Account Management 
4. Check all boxes > Save 

**Email domains:** 

1. Control Panel > System Settings > Accounts > Toggle "Enable Email Domain Validation" > Save
2. Control Panel > Accounts > Create new account 
3. Add new valid domain (ex. liferay.com) > Save 

**Announcements:**

1. Application Menu > Announcements and Alerts
2. Create new announcement > Save

**Content Dashboard:**

1. Application Menu > Content Dashboard
2. Configure Chart > Move "Stage (Global)" to Available > Save

-----

### Unable to create new process in local/remote staging:

1. Product Menu > Publishing > Staging 
2. Enable local live > Add a new publish process (if you refresh, you can add one)
3. Publish to Live

-----

### Unable to click on 3 ellipsis on widgets:

1. Create a widget page/content page > Add widget to the page 
2. Hover and click on the 3 ellipsis to open dropdown menu

-----

### Unable to change table view:

1. Create a widget page > Add Documents and Media widget to the page 
2. Click on the show view options to change to list view

-----

### Calendar widget:

1. Create a widget page > Add Calendar widget to the page 
     - Calendar widget doesn't display [any calendars](https://imgur.com/K7hkgK2)
     - Unable to click on the down arrow in the button to open dropdown menu 
     - Unable to click on "Other Calendars" to collapse "Add other calendars" 
     - Unable to click on "Add Event" button 
     - Navigate to "Resources" tab > Add new resource

-----

### Unable to interact with workflow process dropdown menu:

1. Application Menu > Process Builder > Configuration > Set "Single Approver" for Blogs Entry
2. Create a blog post > Submit for Publication
5. User dropdown > My Workflow Tasks > Assigned to My Roles 
6. Click on 3 ellipsis > Assign to Me / Assign to... / Update Due Date

-----

### Vocabularies / Categories:

1. Product Menu > Categorization > Categories 
    - Add new vocabulary (didn't let me on first try, had to refresh)
    - Give name and visibility is set to Public > Save
    - A alert should pop up with "Are you sure you want to create this vocabulary with public visibility?"

2. Navigate to http://localhost:8080/group/global/~/control_panel/manage/-/categories_admin
     - Add a new category > Click "Save and Add a New One"

-----

### Unable to add new user to Asset Library:

1. Application Menu > Asset Libraries > Create asset library
2. Memberships > Add new user > Done 

-----

### Unable to add additional metadata fields:

1. Product Menu > Content & Data > Documents and Media > Document Types
2. Add new document type > Click on "Additional Metadata Fields" on the right side (3rd icon) > Select

-----

### Unable to add DDM list:

1. Product Menu > Content & Data > Dynamic Data Lists
2. Add new list > Save

-----

### Unable to interact with Forms:

1. Product Menu > Content & Data > Forms
     - Add new form > Add some languages > Preview > Click on translation manager
     - Add new form > Select from List > Preview > Should be able to select from list (forms is grayed out)

**Comment by susanchen3** [comment]
These are just some bugs I identified from going through half of the functional tests, there are more so I will continue investigating tomorrow :detective:

**Comment by izaera** [comment]
@susanchen3 It's OK. If you can confirm bugs, I need to recheck and fix them, and that can cause new bugs to trigger, so there's no need to find more (one confirmed bug is enough) :sweat_smile: . This is because this is so low level that after any change, things can vary a lot...

I don't know if we will ever get this PR through CI... :sob:

**Comment by susanchen3** [comment]
:sob: oki just let me know when this PR is ready for another round of analysis! we can get through CI :muscle: one day...

**Comment by izaera** [comment]
I've fixed the "Unable to click on 3 ellipsis on widgets" error. Since it is possible that the changes fix more errors, I'm running test relevant again while I keep analyzing the other errors locally.

**Comment by izaera** [comment]
ci:test:relevant

**Comment by izaera** [comment]
All [the errors reported by @susanchen3](https://github.com/liferay-frontend/liferay-portal/pull/2368#issuecomment-1188460699) have been fixed (verified locally by me) with the last 5 commits :tada:

**Comment by izaera** [comment]
ci:test:relevant

**Comment by izaera** [comment]
ci:test:relevant

**Comment by susanchen3** [comment]
Taking a look now! :detective:

**Comment by susanchen3** [comment]
[**Comparison run:**](https://testray.liferay.com/home/-/testray/runs/compare?view=details&testrayRunIdA=1917616186&testrayRunIdB=1917401046&statusA=2&statusB=3&cur=1&delta=20&orderByCol=testrayComponentName&orderByType=asc)

### Bunch of Elasticsearch integration tests are failing with
```
     [exec] > Task :apps:frontend-js:frontend-js-web:compileTestJava FAILED
     [exec] 
     [exec] > Task :apps:frontend-js:frontend-js-web:processTestResources NO-SOURCE
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/frontend-js/frontend-js-web/src/test/java/com/liferay/frontend/js/web/internal/servlet/taglib/aui/PortletDataRendererImplTest.java:51: error: incompatible types: inference variable T has incompatible bounds
     [exec] 				Arrays.asList(
     [exec] 				             ^
     [exec]     equality constraints: ESImport
     [exec]     lower bounds: AMDRequire
     [exec]   where T is a type-variable:
     [exec]     T extends Object declared in method <T>asList(T...)
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/frontend-js/frontend-js-web/src/test/java/com/liferay/frontend/js/web/internal/servlet/taglib/aui/PortletDataRendererImplTest.java:73: error: incompatible types: inference variable T has incompatible bounds
     [exec] 				Arrays.asList(
     [exec] 				             ^
     [exec]     equality constraints: ESImport
     [exec]     lower bounds: AMDRequire
     [exec]   where T is a type-variable:
     [exec]     T extends Object declared in method <T>asList(T...)
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/frontend-js/frontend-js-web/src/test/java/com/liferay/frontend/js/web/internal/servlet/taglib/aui/PortletDataRendererImplTest.java:97: error: incompatible types: inference variable T has incompatible bounds
     [exec] 				Arrays.asList(new AMDRequire("var!")), null, "content"));
     [exec] 				             ^
     [exec]     equality constraints: ESImport
     [exec]     lower bounds: AMDRequire
     [exec]   where T is a type-variable:
     [exec]     T extends Object declared in method <T>asList(T...)
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/frontend-js/frontend-js-web/src/test/java/com/liferay/frontend/js/web/internal/servlet/taglib/aui/PortletDataRendererImplTest.java:116: error: incompatible types: inference variable T has incompatible bounds
     [exec] 				Arrays.asList(new AMDRequire("frontend-js-web")),
     [exec] 				             ^
     [exec]     equality constraints: ESImport
     [exec]     lower bounds: AMDRequire
     [exec]   where T is a type-variable:
     [exec]     T extends Object declared in method <T>asList(T...)
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/frontend-js/frontend-js-web/src/test/java/com/liferay/frontend/js/web/internal/servlet/taglib/aui/PortletDataRendererImplTest.java:126: error: incompatible types: inference variable T has incompatible bounds
     [exec] 				Arrays.asList(new AMDRequire("frontend-js-web")),
     [exec] 				             ^
     [exec]     equality constraints: ESImport
     [exec]     lower bounds: AMDRequire
     [exec]   where T is a type-variable:
     [exec]     T extends Object declared in method <T>asList(T...)
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/frontend-js/frontend-js-web/src/test/java/com/liferay/frontend/js/web/internal/servlet/taglib/aui/PortletDataRendererImplTest.java:138: error: incompatible types: inference variable T has incompatible bounds
     [exec] 				Arrays.asList(
     [exec] 				             ^
     [exec]     equality constraints: ESImport
     [exec]     lower bounds: AMDRequire
     [exec]   where T is a type-variable:
     [exec]     T extends Object declared in method <T>asList(T...)
     [exec] Note: Some messages have been simplified; recompile with -Xdiags:verbose to get full output
     [exec] 6 errors
```
-----

### Can't edit in Oauth2

1. Control Panel > OAuth 2 Administration > Add 
2. Enter name and URI > Save
3. Edit Client ID or Client Secret

----

### Can't assign users/organizations to a site

1. Add user/organization  
2. Product Menu > Memberships > Add
3. Select new user/organization > Done

----

### Can't add event on Calendar widget

1. Add widget page > Add Calendar widget to page 
2. Click "Add Event" or "My Calendars" dropdown (if it works the first time, refresh and then it won't work)

----

### Can't add workflow in Kaleo Forms Admin

1. Product Menu > Kaleo Forms Admin > Add
2. Navigate to step 3 
3. Add Workflow (unable to interact with title, translation, doesn't have startnode or endnode in diagram)

**Comment by susanchen3** [comment]
These tests are also unique to this PR, but I'm not sure why they are failing :\

**Seems to be the same bug:** 
- [OAuth2#AuthorizationCanBeIssuedWhenTokenIssuerMatchesWithSystemLevelOrInstanceLevel](https://testray.liferay.com/home/-/testray/case_results/1917407506)
- [SAML#AssertAuthorizationOnOAuth2WithSAMLConnectionWithExistingUser](https://testray.liferay.com/home/-/testray/case_results/1917401151)

**Seems like it can't click on edit, but I am able to manually** 
- [OAuth2#ExternalApplicationCanBeAddedAndEdited ](https://testray.liferay.com/home/-/testray/case_results/1917407508)

**Comment by izaera** [comment]
I'm closing this, since it is very probable that we don't take this path (globalDeclaration attribute in <aui:script>)

**Pull request closed without merging**
