### PR TITLE
LPS-184321 | Update DataSet names (entries and views) that have comma in it

### PR DESCRIPTION
**Pull request by abhnerramos**
**Description**
Update DataSet names (entries and views) that have comma in it, by removing the comma and the ignore from the test

**JIRA Ticket**
https://issues.liferay.com/browse/LPS-184321

### CODE REVIEW

**Review by mateusralv — APPROVED** [review]

**Comment by mateusralv** [comment]
ci:forward

**Comment by mateusralv** [comment]
ci:forward:stop

**Comment by abhnerramos** [comment]
ci:open

**Comment by abhnerramos** [comment]
ci:reopen

**Comment by abhnerramos** [comment]
ci:test:sf

**Comment by abhnerramos** [comment]
ci:test:frontend-data-set

**Comment by abhnerramos** [comment]
ci:test:sf

**Comment by abhnerramos** [comment]
ci:test:frontend-data-set

**Comment by mateusralv** [comment]
ci:forward

**Pull request closed without merging**
