### PR TITLE
LPS-155271 | Add Minified#VerifyErroWhenJQueryEnabled poshi test

### PR DESCRIPTION
**Pull request by mateusralv**
Original PR: https://github.com/mateusralv/liferay-portal/pull/42

---
My Ticket:
https://issues.liferay.com/browse/LPS-155271

Description:
Create Automated tests

Minified#VerifyErroWhenJQueryEnabled

### CODE REVIEW

**Comment by mateusralv** [comment]
ci:test:frontend:nocompile

**Comment by mateusralv** [comment]
ci:test:frontend:nocompile

**Comment by mateusralv** [comment]
ci:test:sf

**Comment by mateusralv** [comment]
ci:test:frontend

**Comment by abhnerramos** [comment]
ci:test:sf

**Comment by abhnerramos** [comment]
ci:test:sf

**Comment by abhnerramos** [comment]
ci:test:frontend

**Comment by mateusralv** [comment]
ci:test:frontend

**Comment by mateusralv** [comment]
ci:test:frontend

**Comment by mateusralv** [comment]
ci:test:frontend

**Comment by mateusralv** [comment]
ci:test:sf

**Comment by mateusralv** [comment]
ci:test:frontend

**Comment by mateusralv** [comment]
ci:forward

**Pull request closed without merging**
