### PR TITLE
LPD-41968 Remove FF LPD-19787 from code and tests

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
https://liferay.atlassian.net/browse/LPD-41968

Hey @dsanz, here we are removing the FF that was introduced recently in story https://liferay.atlassian.net/browse/LPD-35510 (Improve the permissions configuration experience when uploading files) that we have been discussing recently, so we can deliver this through hotfix in https://liferay.atlassian.net/browse/LPP-56683
Thank you very much for your review

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
ci:test:relevant

**Review by markocikos — APPROVED** [review]
@ambrinchaudhary The code in `portal-web/docroot/html/taglib/ui/input_permissions/*` LGTM! :sparkles:

**Comment by ambrinchaudhary** [comment]
ci:forward

**Pull request closed without merging**
