### PR TITLE
LPS-174963 | Autom. ClientExtension#UILabelIsPresent

### PR DESCRIPTION
**Pull request by abhnerramos**
- My ticket

https://issues.liferay.com/browse/LPS-174963

- Description

Add Automation for test ClientExtension#UILabelIsPresent

### CODE REVIEW

**Comment by abhnerramos** [comment]
ci:test:sf

**Comment by mateusralv** [comment]
Hi @abhnerramos Could you solve the rebase conflict?

**Comment by mateusralv** [comment]
ci:test:frontend

**Comment by john-co** [comment]
Besides the rebase conflict, looks good to me! :sunglasses:

**Comment by abhnerramos** [comment]
I'll work on the rebase conflict and send it again!

**Comment by abhnerramos** [comment]
ci:test:sf

**Comment by abhnerramos** [comment]
ci:test:sf

**Comment by abhnerramos** [comment]
ci:test:client-extensions:nocompile

**Comment by abhnerramos** [comment]
@mateusralv apparently, ci:test:client-extensions:nocompile didn't run, which command should I use?

**Comment by abhnerramos** [comment]
@mateusralv apparently, ci:test:client-extensions:nocompile didn't run. Which command should I use?

**Comment by mateusralv** [comment]
ci:test:frontend

**Comment by abhnerramos** [comment]
how should we proceed @mateusralv ?

**Comment by deborasoliveira** [comment]
ci:test:frontend-client-extensions:nocompile

**Comment by john-co** [comment]
Looks good to me! :sunglasses:

[test passes](https://testray.liferay.com/home/-/testray/case_results/2191697343?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2191697140%26testrayRunId%3D2191697242%26cur%3D2%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc%26resetCur%3Dfalse)

**Comment by john-co** [comment]
ci:forward

**Pull request closed without merging**
