### PR TITLE
[TS] LPS-130813

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-130813

Resent from https://github.com/liferay-frontend/liferay-portal/pull/1727 with naming convention updated.

Original message:

> Resent from https://github.com/liferay-frontend/liferay-portal/pull/1689
> 
> I've managed to fix the failures here https://github.com/liferay-frontend/liferay-portal/pull/1689#issuecomment-986982633, however a few of [the error messages in the console](https://github.com/liferay-frontend/liferay-portal/pull/1689#issuecomment-987044546) still persist (at least the first one).  the last error message was caused by my changes, so it should be gone now.

CC @kresimir-coko

### CODE REVIEW

**Comment by ChrisKian** [comment]
Hi @liferay-frontend, are there any updates for this PR?

**Comment by bryceosterhaus** [comment]
@ChrisKian the changes look fine to me. We just need a passing "relevent" test before we can forward. Or if you think the failures aren't related, we can ping QA to investigate the results.

Also, looks like there are some conflicts that need to be added. I'll keep an eye on this PR for any updates and get it forwarded once those are addressed.

**Comment by ChrisKian** [comment]
Rebased and force-pushed changes.  Retesting now.

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by ChrisKian** [comment]
Hi @liferay-frontend,
The current failing relevant test looks unrelated, and is different than the previous failure, even though my code changes are the same.  Can we please include QA to confirm/deny the failure is with my changes?  Thanks!

**Comment by john-co** [comment]
Reviewed. Test failures are unrelated. :heavy_check_mark: 
Ok to manually forward by QA perspective if ready on dev side.

**Comment by bryceosterhaus** [comment]
manual forward https://github.com/brianchandotcom/liferay-portal/pull/112137

**Pull request closed without merging**
