### PR TITLE
LPS-197771 - Create generic creation button actions

### PR DESCRIPTION
**Pull request by juanjofgliferay**
Follow up https://github.com/liferay-frontend/liferay-portal/pull/3749

## Info
Related Story/Task: [LPS-186875](https://liferay.atlassian.net/browse/LPS-186875) / [LPS-197771](https://liferay.atlassian.net/browse/LPS-197771)
Related documentation: [Research for actions confluence page](https://liferay.atlassian.net/wiki/spaces/ENGFRONTENDINFRA/pages/2418148860/LPS-186947+-+Tech+research+for+actions+in+dataset+views)
UI: [Creation Actions](https://www.figma.com/file/ThsIousIfUrvJXgy4bfX3j/LPS-193209-design-how-to-define-generic-actions?type=design&node-id=201-55288&mode=design&t=lSok6SosJ9wQFJdL-0)
Feature Flag: `LPS-194395`
Followup on https://github.com/liferay-frontend/liferay-portal/pull/3727

## Story
We need to allow admin users to define actions that apply to the items in a Dataset (actions in the :heavy_plus_sign: button in the FDS component).
The story covers the addition of new item actions (modal & side panel) as well as edition, deletion and sorting of both types of actions.

## UI

[Screencast from 2023-10-05 10-25-38.webm](https://github.com/liferay-frontend/liferay-portal/assets/132653342/b740617d-f153-4f8a-b220-00bcef7b16e8)

## Concerns & Questions
- Naming. Find some differences between the research document and the design implementation
- ~~`ItemActionForm` could be reused so we could rename to a generic `ActionForm` (not renamed to allow clear review)~~ **done**
- Mixing of tabs (number index based) and sections (text based) make UI complex. I need to think of a better way to handle it.
- Need to change `<ClaySelectWithOption>` by `<Picker>` to match the design
- Do we need to validate `url` format?

### CODE REVIEW

**Comment by juanjofgliferay** [comment]
ci:test:relevant

**Comment by JerryAdrianoo** [comment]
Hey @juanjofgliferay, these failures are not related to your changes 🎊 
[Test Comparison.](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1697552878939&testrayRunIdA=2440865274&testrayRunIdB=2442054124)

**Comment by juanjofgliferay** [comment]
ci:forward:force

**Comment by juanjofgliferay** [comment]
ci:test:sf

**Comment by juanjofgliferay** [comment]
ci:test:relevant

**Pull request closed without merging**
