### PR TITLE
LPS-188246 Add alternative text to image viewer for those cases when using Carousel

### PR DESCRIPTION
**Pull request by antonio-ortega**
Changes introduced in AUI can be seen [here](https://github.com/liferay/liferay-frontend-projects/commit/111f1160c1c99923e8d845e7c86fbe215b561fb9).

### CODE REVIEW

**Comment by markocikos** [comment]
ci:forward

**Comment by markocikos** [comment]
ci:forward

**Comment by mateusralv** [comment]
Hi @antonio-ortega the failures are not related 😄 

[Testray Comparison](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1688092156924&testrayRunIdA=2364485102&testrayRunIdB=2364947056)

**Comment by antonio-ortega** [comment]
ci:forward:force

**Comment by markocikos** [comment]
ci:forward:force

**Comment by antonio-ortega** [comment]
Manually forwarded to brianchandotcom#137198

**Pull request closed without merging**
