### PR TITLE
LPS-167124 Use newer npm-scripts versions

### PR DESCRIPTION
**Pull request by izaera**
This newer version doesn't rewrite function/class names when minifying JS code in liferay-portal

### CODE REVIEW

**Comment by mateusralv** [comment]
Hey @izaera I took a look at `ci:test:relevant` results and the failures are not related to your PR. 😃

**Comment by izaera** [comment]
Thx @mateusralv . I'll wait for @bryceosterhaus PR https://github.com/liferay-frontend/liferay-portal/pull/2825 to be merged to send this one, because this one's npm-scripts are based on the ones in that PR.

**Comment by izaera** [comment]
I'll manually forward this tomorrow :rocket:

**Comment by izaera** [comment]
Sent manually https://github.com/brianchandotcom/liferay-portal/pull/125698

**Pull request closed without merging**
