### PR TITLE
LPS-188818 Pagination info is lost when navigating

### PR DESCRIPTION
**Pull request by andreluis2022**
**Description:**
Product QA | Functional Automation - LPS-188818 Pagination info is lost when navigating

**JIRA Ticket:**
[LPS-188818](https://liferay.atlassian.net/browse/LPS-188818)

### CODE REVIEW

**Comment by andreluis2022** [comment]
ci:stop:sf

**Comment by andreluis2022** [comment]
ci:test:sf

**Comment by andreluis2022** [comment]
ci:test:stable

**Comment by andreluis2022** [comment]
ci:test:frontend-data-set

**Comment by andreluis2022** [comment]
Hey @CarlosBrichete  can you take a look in this test?

**Review by CarlosBrichete — APPROVED** [review]
LGTM :)

**Comment by andreluis2022** [comment]
ci:forward

**Pull request closed without merging**
