### PR TITLE
LPS-165783 - Add new npm-scripts build cache to .gitignore and exclude from ant clean

### PR DESCRIPTION
**Pull request by bryceosterhaus**
This adds the new version of npm-scripts which includes a caching mechanism between builds.

https://issues.liferay.com/browse/LPS-165783

Here is how it works

First build:
- Stores built files at `./modules/.npmscripts/build/artifacts/${MODULE_NAME}/build/**`
- Hashes src and built files at `./modules/.npmscripts/build/artifacts/${MODULE_NAME}/buildinfo.json`

- Before running babel, bundler, webpack, etc. we check if any previous build exists
    - Checks `./modules/.npmscripts/build/artifacts/${MODULE_NAME}/buildinfo.json`
    - Checks `./modules/.npmscripts/build/artifacts/${MODULE_NAME}/build/**` ()

Subsequent builds:
Check...
- previous build info doesn't exist -> REBUILD
- can't read previous build info -> REBUILD
- number of source files change -> REBUILD
- src files content changes -> REBUILD
- src files content doesn't change
    - build file doesn't exist -> copy previous build from cache
    - previous build files exist
         - file is same as last build -> DO NOTHING
         - file has changed -> REBUILD

Use can also force a build with `yarn build --force` or by deleting the `./modules/.npmscripts` directory.

The only change needed in DXP is adding `./modules/.npmscripts` to .gitignore and also excluding it from `ant clean`.

### CODE REVIEW

**Comment by bryceosterhaus** [comment]
Just discovered commerce-js-web is providing 32,000 files in the build folder for packageRunBuild.... Gonna need to look into this next week because it's causing a siginificant slow down and definitely shouldn't have that many files

**Comment by bryceosterhaus** [comment]
ci:test:sf

**Comment by bryceosterhaus** [comment]
ci:test:sf

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
ci:test:sf

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by mateusralv** [comment]
I'm taking a look 🕵🏽‍♂️

**Comment by john-co** [comment]
central requirements test failure looks related

```
    [junit] Testcase: testScanIgnoreFiles(com.liferay.portal.modules.ModulesStructureTest):	FAILED
    [junit] Incorrect modules/etl/mulesoft/.gitignore expected:<...on
    [junit] .gradle/
    [junit] .idea/
    [junit] .[npmscripts/
    [junit] .]project
    [junit] .sass-cache/...> but was:<...on
    [junit] .gradle/
    [junit] .idea/
    [junit] .[]project
    [junit] .sass-cache/...>
    [junit] junit.framework.AssertionFailedError: Incorrect modules/etl/mulesoft/.gitignore expected:<...on
    [junit] .gradle/
    [junit] .idea/
    [junit] .[npmscripts/
    [junit] .]project
    [junit] .sass-cache/...> but was:<...on
    [junit] .gradle/
    [junit] .idea/
    [junit] .[]project
    [junit] .sass-cache/...>
    [junit] 	at com.liferay.portal.modules.ModulesStructureTest._testGitRepoIgnoreFiles(ModulesStructureTest.java:1174)
    [junit] 	at com.liferay.portal.modules.ModulesStructureTest.access$900(ModulesStructureTest.java:68)
    [junit] 	at com.liferay.portal.modules.ModulesStructureTest$5.preVisitDirectory(ModulesStructureTest.java:444)
    [junit] 	at com.liferay.portal.modules.ModulesStructureTest$5.preVisitDirectory(ModulesStructureTest.java:425)
    [junit] 	at java.nio.file.Files.walkFileTree(Files.java:2677)
    [junit] 	at java.nio.file.Files.walkFileTree(Files.java:2742)
    [junit] 	at com.liferay.portal.modules.ModulesStructureTest.testScanIgnoreFiles(ModulesStructureTest.java:423)

```

**Comment by john-co** [comment]
https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=2&testrayRunIdB=2027439268&testrayRunIdA=2027399333&statusB=3

cc/ @magjed4289 @yanan @Hijky @austinchiang @Hanlf @Jeremy-Ch @liuxingye looks like a lot of inconsistent failing integration tests for data integration, and depot and online editing impacting this PR. Please take a look to see if we can stabilize/quarantine the tests.

**Comment by bryceosterhaus** [comment]
ci:test:sf

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
@john-co all the unique test failures from Lima are caused by the same issue https://issues.liferay.com/browse/LRCI-3328 Presumably this affects other components as well

**Comment by bryceosterhaus** [comment]
@john-co is this good to forward now that the central requirements test is fixed?

**Comment by magjed4289** [comment]
Checked the newest run. Test failures are not related, error that @john-co mentioned does not appear anymore. OK to manually forward ✅

**Comment by bryceosterhaus** [comment]
manual forward at https://github.com/brianchandotcom/liferay-portal/pull/125651

**Pull request closed without merging**
