### PR TITLE
LPS-130563 Update @clayui/* dependencies to v3.27.0

### PR DESCRIPTION
**Pull request by matuzalemsteles**
I also made the changes that are necessary on the DXP side, like updating the Management Toolbar icon (https://github.com/liferay/clay/issues/4023) but I didn't make the other changes reported by @dsanz, waiting for a design analysis to check the use cases... we can leave to fix that on another ticket as well.

### Bug Fixes

-   **@clayui/css:** Date Picker previous-month-date and next-month-date active should be lighter ([51a24f3](https://github.com/liferay/clay/commit/51a24f3))
-   **@clayui/css:** Menubar convert old Sass map keys to key names so older keys used by previous versions will win ([9a1a73a](https://github.com/liferay/clay/commit/9a1a73a))
-   **@clayui/css:** Menubar update `$menubar-vertical-expand-md` and `$menubar-vertical-expand-lg` to use new keys. Older keys will still win over new keys to preserve backward compatibility. ([12b9636](https://github.com/liferay/clay/commit/12b9636))
-   **@clayui/css:** Mixins `clay-form-control-variant` old keys should win over new keys ([8986a81](https://github.com/liferay/clay/commit/8986a81)), closes [#3987](https://github.com/liferay/clay/issues/3987)
-   **@clayui/css:** Mixins `clay-menubar-vertical-expand` use `clay-css` mixin pattern ([6a9ba26](https://github.com/liferay/clay/commit/6a9ba26))
-   **@clayui/css:** Mixins `clay-menubar-vertical-variant` moves default styles to variables. The mixin should only output styles if values are given. ([703b76e](https://github.com/liferay/clay/commit/703b76e))
-   **@clayui/css:** Progress Bar sets a `min-width` on `progress-group-addon` to prevent resizing progress bar when numbers are changed to icons ([63e63c0](https://github.com/liferay/clay/commit/63e63c0)), closes [#4024](https://github.com/liferay/clay/issues/4024)
-   **@clayui/css:** Sass maps passed into `clay-form-control-variant` mixin should use new keys. This allows variable theme overwrites using deprecated keys to still win. ([f3be2d6](https://github.com/liferay/clay/commit/f3be2d6)), closes [#3987](https://github.com/liferay/clay/issues/3987)
-   **@clayui/date-picker:** DatePickerDayNumber use the classes `previous-month-date` and `next-month-date` to style day outside the month instead of `disabled` ([f25ab71](https://github.com/liferay/clay/commit/f25ab71)), closes [#4036](https://github.com/liferay/clay/issues/4036)
-   **@clayui/shared:** add unit test for FocusScope ([f84332f](https://github.com/liferay/clay/commit/f84332f))
-   **@clayui/shared:** update and simplify logic for focus management when focus moves in and out of the react tree ([e3a100f](https://github.com/liferay/clay/commit/e3a100f))

### Features

-   **@clayui/css:** SVG Icons add rotate ([0fec9ce](https://github.com/liferay/clay/commit/0fec9ce))
-   **@clayui/css:** SVG Icons adds `order-list-down` and `order-list-up` ([f80f8a0](https://github.com/liferay/clay/commit/f80f8a0)), closes [#4021](https://github.com/liferay/clay/issues/4021)
-   **@clayui/multi-select:** add async functionality for source items ([548aa2d](https://github.com/liferay/clay/commit/548aa2d))
-   **@clayui/panel:** adds the small API to Panel.Group ([b8428dc](https://github.com/liferay/clay/commit/b8428dc))
-   **@clayui/popover:** add observeRect to align the popover on the scroll ([8bedd2f](https://github.com/liferay/clay/commit/8bedd2f))

### Updated packages

- `@clayui/autocomplete` v3.25.1 to v3.27.0
- `@clayui/breadcrumb` v3.25.1 to v3.27.0
- `@clayui/card` v3.25.1 to v3.27.0
- `@clayui/color-picker` v3.25.1 to v3.27.0
- `@clayui/data-provider` v3.3.10 to v3.27.0
- `@clayui/data-picker` v3.26.0 to v3.27.0
- `@clayui/data-down` v3.25.1 to v3.27.0
- `@clayui/form` v3.14.4 to v3.27.0
- `@clayui/list` v3.25.1 to v3.27.0
- `@clayui/localized-input` v3.25.1 to v3.27.0
- `@clayui/modal` v3.8.5 to v3.27.0
- `@clayui/multi-select` v3.25.3 to v3.27.0
- `@clayui/multi-step-nav` v3.25.1 to v3.27.0
- `@clayui/nav` v3.4.5 to v3.27.0
- `@clayui/navigation-bar` v3.3.5 to v3.27.0
- `@clayui/pagination` v3.25.1 to v3.27.0
- `@clayui/pagination-bar` v3.25.1 to v3.27.0
- `@clayui/panel` v3.25.0 to v3.27.0
- `@clayui/popover` v3.5.5 to v3.27.0
- `@clayui/shared` v3.5.1 to v3.27.0
- `@clayui/tabs` v3.3.5 to v3.27.0
- `@clayui/time-picker` v3.2.6 to v3.27.0
- `@clayui/toolbar` v3.0.6 to v3.27.0
- `@clayui/tooltip` v3.4.5 to v3.27.0
- `@clayui/upper-toolbar` v3.1.14 to v3.27.0

### DXP Changes

- Updates the `order by` icon of the Management Toolbar (90acdd5c24c75abd8185ca7c40bbe5e9dba26aa6, 6cd1dd1bd6cc5c9005a2238c4cfdc143cd17f05c)
- Remove the use of the `filter` prop and filter the results of `sourceItems` from ClayMultiSelect (6cd1dd1bd6cc5c9005a2238c4cfdc143cd17f05c)

### CODE REVIEW

**Comment by matuzalemsteles** [comment]
Hey @pat270 with the introduction of some changes from https://github.com/liferay/clay/issues/3987 is it necessary to make any updates to any theme module?

**Comment by bryceosterhaus** [comment]
@matuzalemsteles I think you will also need to update the uses of MultiSelect to no longer rely on the internal filter. I think you can just use this commit, bryceosterhaus/liferay-portal@78adf83

**Comment by matuzalemsteles** [comment]
@bryceosterhaus yeah, I ended up forgetting myself. Thanks for remembering, I will update them. Apparently, the components they use have no tests and didn't break when I run 🤷‍♂️

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by matuzalemsteles** [comment]
ci:test:sf

**Comment by dsanz** [comment]
> ([liferay/clay#4023](https://github.com/liferay/clay/issues/4023)) but I didn't make the other changes reported by @dsanz, waiting for a design analysis to check the use cases... we can leave to fix that on another ticket as well.

That's ok Matu, we can create a separate ticket for these.

I think they already gave the ok via thumbs up in the comment, but, to double check @drakonux , shall we sit together an decide on the cases I list [here](https://github.com/liferay/clay/issues/4023#issuecomment-829293507)? They're not exactly the same, so I'd understand if you guys prefer to create a ticket and analyze.

Best

**Comment by wincent** [comment]
ci:reevaluate:1167401_8271

**Comment by matuzalemsteles** [comment]
@dsanz Yeah, I was wondering about the use case where the order is not set by default or the other if we should keep only one button, both will change some behaviors, so it was not very clear to me how I should proceed with this. I think it would be better to have a ticket for that and I can work right later.

**Comment by wincent** [comment]
Going to try the tests again, and in the meantime invoke @john-co, @nkkwon, @zhangyan0701 to take a look at previous (and possible future) failures. At least some of the "unique" failures are very obviously unrelated (eg. `org.junit.ComparisonFailure`) and others are flakey infra (eg. `Build was aborted`).

**Comment by wincent** [comment]
ci:test:relevant

**Comment by nkkwon** [comment]
Just started reviewing :)

**Comment by nkkwon** [comment]
**Analysis Details:**
@matuzalemsteles 

com.liferay.dynamic.data.mapping.service.test.DDMStructureLocalServiceTest.testSearchByKeywords1 - Seems like a flaky issue, has same failure occurring in [acceptance ](https://testray.liferay.com/home/-/testray/case_results/1530306236?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcases%2F1518350445%2Fview%3Fcur%3D1%26delta%3D200%26testrayCaseId%3D1518350445%26orderByCol%3DcreateDate_sortable%26orderByType%3Ddesc)previously 

LocalFile.DisplayPageTemplatesWithViewUsage#ViewAssetsOrderInViewUsagesOfDisplayPageTemplate - Looking at the [commit here ](https://github.com/liferay-frontend/liferay-portal/pull/1023/commits/21636f7b48c645c3f7b6939820bac8b2da802a06) it looks like the changes to the filter controls has caused the failure to the [test](https://testray.liferay.com/reports/production/logs/2021-05/test-1-16/test-portal-acceptance-pullrequest(master)/8271/functional-tomcat90-mysql57-jdk8/4/1/LocalFile.DisplayPageTemplatesWithViewUsage_ViewAssetsOrderInViewUsagesOfDisplayPageTemplate/index.html.gz). `symbol="order-arrow"` was removed and the path for ORDER_ICON_GENERIC is looking for the class `icon-order-arrow`
This is likely a Test Fix and will investigate the bundle further to see if the HTML was changed

**Comment by nkkwon** [comment]
**Further Analysis**
LocalFile.DisplayPageTemplatesWithViewUsage#ViewAssetsOrderInViewUsagesOfDisplayPageTemplate -
g3r5yxt
Currently the icon for the filter is shown as this with the class `lexicon-icon-order-arrow` and this is what the path in the test searches for.

ZfsvoHL
The [commit ](https://github.com/liferay-frontend/liferay-portal/pull/1023/commits/21636f7b48c645c3f7b6939820bac8b2da802a06) changes the icon and it now has the class `lexicon-icon-order-list-up` so it's something that can be resolved by a Test Fix

**Comment by matuzalemsteles** [comment]
Hey @nkkwon thanks for the details, I think I can correct the selector, I will do it ah unless you have something in mind in this change.

**Comment by john-co** [comment]
Hi @matuzalemsteles , I think there's other tests/xpaths that may be affected. I have a general idea of a simple mass fix since it sounds like this is an intentional change on management toolbar. We'll send a commit with the fix.

**Comment by matuzalemsteles** [comment]
> I think there's other tests/xpaths that may be affected. I have a general idea of a simple mass fix since it sounds like this is an intentional change on management toolbar. We'll send a commit with the fix.

Oh okay, thanks @john-co, let me know to add the commit along with the PR, thanks for the info.

**Comment by john-co** [comment]
Hi @matuzalemsteles, couple questions:

1. Noticed a flickering between the old order-arrow icon and the added list-up/down icon. Looks like a slight UI regression, are we ok with this?:

https://user-images.githubusercontent.com/35235266/117350011-e7900180-ae60-11eb-94e1-a879110891ab.mp4


2. I noticed AppBuilder does not have their order-arrow updated. Is this within our scope to update as well? Or maybe they configured management toolbar differently.
AppBuilder_notUsingListUpIcon

**Comment by matuzalemsteles** [comment]
@john-co answering your questions:

> Noticed a flickering between the old order-arrow icon and the added list-up/down icon. Looks like a slight UI regression, are we ok with this?:

Hmm I think this may be related to the server side rendering that is done via Java, I'll fix that too, I had forgotten about that.

> I noticed AppBuilder does not have their order-arrow updated. Is this within our scope to update as well? Or maybe they configured management toolbar differently.

I think they created their own implementation of the Management Toolbar using Clay's low-level layer. Well, I can change that but as far as I know, problems related to App Builder are being pushed aside once it has been frozen ⚰️ and if I am not mistaken the source code will be removed soon (Well I just learned that there is already a PR that will remove, I think we can discard that).

**Comment by john-co** [comment]
@matuzalemsteles could you invite me as a collaborator for your repo? I can directly push the test fix commit to your branch.

**Comment by john-co** [comment]
The other test failures from the last test run https://github.com/liferay-frontend/liferay-portal/pull/1023#issuecomment-833765920 doesn't look related to this PR. We can rerun `ci:test:relevant` after adding this fix:

> 
> Noticed a flickering between the old order-arrow icon and the added list-up/down icon. Looks like a slight UI regression, are we ok with this?:
> 
> Hmm I think this may be related to the server side rendering that is done via Java, I'll fix that too, I had forgotten about that.

**Comment by matuzalemsteles** [comment]
ci:test:sf

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by matuzalemsteles** [comment]
ci:test:sf

**Comment by matuzalemsteles** [comment]
@john-co you could take a look at it, apparently it’s not related 🤔

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by john-co** [comment]
Hi @matuzalemsteles yea it seems like most of the issues are unrelated...not quite sure what tripped up all the tests but let's see how the next run goes.

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by nkkwon** [comment]
Hey @matuzalemsteles It looks like these issues aren't related. I'm seeing in the poshi reports that the tests aren't able to load a page or it errors out. I'm assuming that there's a CI issue which could also explain why this relevant took so long to run. 
I'll keep an eye out for when the next relevant finishes and check that too

**Comment by matuzalemsteles** [comment]
Hey @john-co or @nkkwon, apparently, the same errors, if this is not really related, I am thinking of forwarding manually.

**Comment by matuzalemsteles** [comment]
Hi @nkkwon this is interesting, I'll take a look at it.

**Comment by matuzalemsteles** [comment]
Okay, I made the fixes, running the tests again.

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by matuzalemsteles** [comment]
It seems that this resolved and the CI is green. I'll go ahead with this 🙂

**Comment by matuzalemsteles** [comment]
ci:forward

**Pull request closed without merging**
