### PR TITLE
LPS-128596 Align back button web content title and action button in Asset Publisher

### PR DESCRIPTION
**Pull request by georgel-pop-lr**
LPS-128596 Align back button web content title and action button in Asset Publisher when selecting a content

Not sure why isn't happening in 7.3.x as is having same changes, this affects only master.

### CODE REVIEW

**Comment by kresimir-coko** [comment]
@georgel-pop-lr can you provide a before and after screenshot, and also make sure it behaves as expected on all resolutions? It's a tiny change but we wouldn't want to have unexpected consequences that are easily avoided.

**Comment by georgel-pop-lr** [comment]
> @georgel-pop-lr can you provide a before and after screenshot, and also make sure it behaves as expected on all resolutions? It's a tiny change but we wouldn't want to have unexpected consequences that are easily avoided.

Hi @kresimir-coko,

I have analysed this again because with the same changes seems that 7.3.x wasn't affected, so I concluded that the problem is related to a change in modules/apps/asset/asset-publisher-web/src/main/resources/META-INF/resources/view_asset_entry_full_content.jsp  in this code:
```
<c:if test="<%= showBackURL && Validator.isNotNull(redirect) %>">
   <liferay-ui:icon
      cssClass="header-back-to"
      icon="angle-left"
      markupView="lexicon"
      url="<%= redirect %>"
   />
</c:if>
```
Now the link element a has a new class dropdown-item that has in the CSS styles display:block; if you remove this class everything looks good.
image

My solution works as forces the parent CSS to become display: inline-flex !important; 

Now I'm not totally convince that this should be the fix as I don't yet understand why this class was added and if we need to fix it in liferay-ui:icon as it's being used everywhere.

Not sure yet how this code gets generated.

Do you have any ideas? 

This is before the fix:
image

After my fix is applied:
image


Regards.

**Comment by jbalsas** [comment]
Hey @georgel-pop-lr, can you see if https://github.com/liferay-frontend/liferay-portal/pull/862 fixes this issue?

**Comment by georgel-pop-lr** [comment]
> Hey @georgel-pop-lr, can you see if #862 fixes this issue?
> 
> I think it should do the trick based on your comment:
> 
> > Now the link element a has a new class dropdown-item that has in the CSS styles display:block; if you remove this class everything looks good.

Hi @jbalsas,

Yes, this gets fixed by #862 
So I guess we can close this one.

Regards.

**Comment by jbalsas** [comment]
Awesome, thanks for verifying @georgel-pop-lr! 🤗

**Pull request closed without merging**
