### PR TITLE
LPS-121190 Fix button style in custom-properties

### PR DESCRIPTION
**Pull request by eduardoallegrini**
This PR fixes 2 related bugs of the button style
- https://issues.liferay.com/browse/LPS-121190
- https://issues.liferay.com/browse/LPS-121004

Screenshot 2020-09-29 at 12 34 19
Screenshot 2020-09-29 at 13 33 26

### CODE REVIEW

**Review by marcoscv-work — APPROVED** [review]

**Comment by marcoscv-work** [comment]
LGTM !!!

**Comment by eduardoallegrini** [comment]
ci:test:sf

**Comment by eduardoallegrini** [comment]
ci:test:relevant

**Comment by eduardoallegrini** [comment]
ci:forward

**Pull request closed without merging**
