### PR TITLE
LPS-197444 Make the wrapped request behave as a real one

### PR DESCRIPTION
**Pull request by izaera**
Since we are delegating in the usual portal request dispatching from ComboServlet, we need to make the rest of the portal think that the requests from ComboServlet are real.

Because we are using RequestDispatcher.include, the request that the portal sees (unless we do something to remediate it) is for /combo, not for the subresources the combo is trying to gather together.

In this commit we override some of the wrapped request methods to make portal think the request is a normal one.

### CODE REVIEW

**Comment by izaera** [comment]
ci:test:relevant

**Review by bryceosterhaus — APPROVED** [review]
LGTM

**Comment by deborasoliveira** [comment]
I'll take a look at the relevant result.

**Comment by deborasoliveira** [comment]
ci:test:relevant

**Comment by mateusralv** [comment]
ci:reevaluate:1267401_11290

**Comment by deborasoliveira** [comment]
ci:test:relevant

**Comment by izaera** [comment]
Running relevant again to save some time because [latest attempt](https://github.com/liferay-frontend/liferay-portal/pull/3715#issuecomment-1745676440) seems to have crashed due to CI issues...

**Comment by izaera** [comment]
ci:test:relevant

**Comment by deborasoliveira** [comment]
I'm checking relevant result again.

**Comment by deborasoliveira** [comment]
The failures are unrelated to the PR.

[Comparison run](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=2&testrayRunIdB=2436154167&testrayRunIdA=2435187856&statusB=3)

**Comment by izaera** [comment]
ci:forward:force

**Pull request closed without merging**
