### PR TITLE
LPS-121852 Duplicates clay:management-toolbar

### PR DESCRIPTION
**Pull request by jbalsas**
This is just the preparation PR to fork the `clay:management-toolbar` tag and be able to start working on the replacement for [Update clay:management-toolbar to Clay 3](https://issues.liferay.com/browse/LPS-112468) 

In this PR:
- We create a **temporary `clay:management-toolbar-v2`** tag
- We **update all current usages** so we can safely work on a new version of the tag and migrate all applications without introducing a lot of instability.

**This PR should introduce no logical nor functional changes 🤞**

### CODE REVIEW

**Comment by jbalsas** [comment]
I think I only did the first thing I said this did 😂

**Review by carloslancha — APPROVED** [review]
Wow, 195 usages

**Comment by jbalsas** [comment]
ci:test:sf

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by carloslancha** [comment]
Oh, sorry:

This pr is not horrible

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
ci:test:sf

**Comment by jbalsas** [comment]
ci:test:sf

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
Based on the [Poshi report](https://testray.liferay.com/reports/production/logs/test-1-22/1604573303760/test-portal-acceptance-pullrequest(master)/7481/functional-tomcat90-mysql57-jdk8/1/14/LocalFile.WebContentSearch_SearchWebContentTag/index.html.gz), [LocalFile.WebContentSearch#SearchWebContentTag](https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=14,label_exp=!master/370203//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_WebContentSearch_SearchWebContentTag_) looks like a fluke caused by some race condition.

The other two seem unrelated.

Going to re-run this one time to verify.

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
@john-co, @PablitoBonito, can any you make something out of this gibberish? 😂

**Comment by john-co** [comment]
Looks like it was having trouble trying to find some cached branches. Bad luck?

```
[beanshell] Executing commands: git ls-remote -h -t git@cloud-10-0-0-35:liferay/liferay-portal-ee.git cache-liferay-8d22a791300569a6c92e7b9152e6ae1c6bdc863a-liferay-8d22a791300569a6c92e7b9152e6ae1c6bdc863a
[beanshell] getRemoteGitRefs found 0 refs at git@cloud-10-0-0-35:liferay/liferay-portal-ee.git.
[beanshell] Retrying: Unable to fetch cached remote Git branch cache-liferay-8d22a791300569a6c92e7b9152e6ae1c6bdc863a-liferay-8d22a791300569a6c92e7b9152e6ae1c6bdc863a
[beanshell] Unable to find required branch cache-liferay-8d22a791300569a6c92e7b9152e6ae1c6bdc863a-liferay-8d22a791300569a6c92e7b9152e6ae1c6bdc863a from remote URL git@cloud-10-0-0-35:liferay/liferay-portal-ee.git
[beanshell] Executing commands: git ls-remote -h -t git@cloud-10-0-0-16:liferay/liferay-portal-ee.git cache-liferay-8d22a791300569a6c92e7b9152e6ae1c6bdc863a-liferay-8d22a791300569a6c92e7b9152e6ae1c6bdc863a
[beanshell] getRemoteGitRefs found 0 refs at git@cloud-10-0-0-16:liferay/liferay-portal-ee.git.
[beanshell] Retrying: Unable to fetch cached remote Git branch cache-liferay-8d22a791300569a6c92e7b9152e6ae1c6bdc863a-liferay-8d22a791300569a6c92e7b9152e6ae1c6bdc863a
[beanshell] Unable to find required branch cache-liferay-8d22a791300569a6c92e7b9152e6ae1c6bdc863a-liferay-8d22a791300569a6c92e7b9152e6ae1c6bdc863a from remote URL git@cloud-10-0-0-16:liferay/liferay-portal-ee.git
```

**Comment by john-co** [comment]
ci:test:relevant

**Comment by john-co** [comment]
asked for help from ci to interpret: https://liferay.slack.com/archives/C19PWQ74J/p1604602528130800

**Comment by john-co** [comment]
where did the test result go?... :confused:

**Comment by john-co** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
This is starting to be absurd...

**Comment by jbalsas** [comment]
Can't even get the tests to run locally

```
     [exec]     BUILD FAILED: Error on line 14232 of document  : The element type "log4j" must be terminated by the matching end-tag "</log4j>".
     [exec]     /Users/jose.balsas/dev/liferay/portal/master/portal/portal-web/test/functional/com/liferay/portalweb/macros/Navigator.macro[openURL]:291
     [exec]     /Users/jose.balsas/dev/liferay/portal/master/portal/portal-web/test/functional/com/liferay/portalweb/macros/User.macro[firstLoginPG]:1799
     [exec]     /Users/jose.balsas/dev/liferay/portal/master/portal/portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/layout/contentpage/ContentPagesWithEditMode.testcase[set-up]:12
     [exec] 
     [exec] 
     [exec] com.liferay.poshi.runner.PoshiRunner > test[LocalFile.ContentPagesWithEditMode#OnlyCanEditContentWhenSelectContentEdition] STANDARD_ERROR
     [exec]     org.dom4j.DocumentException: Error on line 14232 of document  : The element type "log4j" must be terminated by the matching end-tag "</log4j>".
     [exec]     	at org.dom4j.io.SAXReader.read(SAXReader.java:511)
     [exec]     	at org.dom4j.io.SAXReader.read(SAXReader.java:392)
     [exec]     	at com.liferay.poshi.runner.selenium.LiferaySeleniumUtil.assertConsoleErrors(LiferaySeleniumUtil.java:103)
     [exec]     	at com.liferay.poshi.runner.selenium.BaseWebDriverImpl.assertLiferayErrors(BaseWebDriverImpl.java:482)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec]     	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec]     	at java.lang.reflect.Method.invoke(Method.java:498)
     [exec]     	at com.liferay.poshi.runner.PoshiRunnerExecutor$1.call(PoshiRunnerExecutor.java:1190)
     [exec]     	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
     [exec]     	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
     [exec]     	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
     [exec]     	at java.lang.Thread.run(Thread.java:745)
     [exec]     Caused by: org.xml.sax.SAXParseException; lineNumber: 14232; columnNumber: 3; The element type "log4j" must be terminated by the matching end-tag "</log4j>".
```

and

```
     [exec]     BUILD FAILED: FAIL. Cannot find group.
     [exec]     /Users/jose.balsas/dev/liferay/portal/master/portal/portal-web/test/functional/com/liferay/portalweb/macros/json/group/JSONGroupAPI.macro[_getGroupIdByName]:175
     [exec]     /Users/jose.balsas/dev/liferay/portal/master/portal/portal-web/test/functional/com/liferay/portalweb/macros/json/group/JSONGroupSetter.macro[setGroupId]:38
     [exec]     /Users/jose.balsas/dev/liferay/portal/master/portal/portal-web/test/functional/com/liferay/portalweb/macros/json/group/JSONGroup.macro[deleteGroupByName]:84
     [exec]     /Users/jose.balsas/dev/liferay/portal/master/portal/portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/layout/contentpage/ContentPagesWithEditMode.testcase[tear-down]:27
```

@john-co, @PablitoBonito, @manoelcyreno, I'm this close to manually push this... thoughts?

**Comment by john-co** [comment]
Some of the tests failing with modal iframe will be fixed by https://issues.liferay.com/browse/LPS-123172. So once that's merged, we can rerun the tests.

In regards to the local poshi test failures you're experiencing, seems like there's an issue with log file. Maybe can try deleting the files in your bundle/logs folder or try a new bundle?

I'm not sure about the 2nd failure. It looks like it failed on the teardown phase of the test but I need more of the console to determine if anything else failed during the test (prior to teardown phase).

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
Hey @john-co, looks like you pushed a bad merge commit. I'll rebase and manually forward this in a minute.

**Comment by jbalsas** [comment]
As promised ;) 

https://github.com/brianchandotcom/liferay-portal/pull/95757

**Pull request closed without merging**
