### PR TITLE
LPS-124112 Fix creation of child article for Knowledge Base with ERC

### PR DESCRIPTION
**Pull request by LuismiBarcos**
Take into account all the possibilities when creating a knowledge base article:
* KB could be independent
* KB could be inside a KBFolder
* KB could be the child of a KBArticle

### CODE REVIEW

**Comment by LuismiBarcos** [comment]
ci:forward

**Review by nhpatt — APPROVED** [review]
ci:forward

**Comment by LuismiBarcos** [comment]
Added check to prevent invalid `getParentKnowledgeBaseArticleId`

**Comment by LuismiBarcos** [comment]
ci:test:relevant

**Comment by LuismiBarcos** [comment]
ci:test:sf

**Review by nhpatt — APPROVED** [review]

**Comment by LuismiBarcos** [comment]
ci:forward

**Pull request closed without merging**
