### PR TITLE
LPS-153899 Adjust openAlert/Confirm modals UX to match designs

### PR DESCRIPTION
**Pull request by diegonvs**
References: https://www.figma.com/file/1USvQ60ZHiq7strGCfpfe3/Dialogues, https://issues.liferay.com/browse/LPS-153899

# What this PR does?

* Aligns it vertically
* Remove Header section of the Modal from openModal utility when rendering those dialogs

# Screenshots

openConfirmModal
image

openAlertModal
image

# Comments

I decided to two flags on openModal

`disableHeader` A flag responsible for removing the Header section on the Modal created by openModal
`center` it derives from ClayModal's center. See [on Clay docs](https://clayui.com/docs/components/modal/api.html#center)

### CODE REVIEW

**Comment by diegonvs** [comment]
Push force for squashing missing propTypes

**Comment by diegonvs** [comment]
ci:stop

**Comment by diegonvs** [comment]
ci:test:relevant

**Comment by diegonvs** [comment]
ci:test:sf

**Comment by michaelhashimoto** [comment]
ci:forward - Failed due to [Testray Outage](https://liferay.slack.com/archives/C19PWQ74J/p1660253108886939).

**Comment by diegonvs** [comment]
ci:forward

**Pull request closed without merging**
