### PR TITLE
LPS-137359 Fix siteId parameter casting and support Asset Libraries and related entities in Batch method generation

### PR DESCRIPTION
**Pull request by javierdearcos**

### CODE REVIEW

**Comment by javierdearcos** [comment]
Not sure about the order of the modified conditions in the template. I put it like this because it is specific to a concrete value, but in alphabetical order should be the second evaluation

**Review by nhpatt — APPROVED** [review]
Did you check with batch and directly with the APIs? Are asset libraries affected to?

LGTM, but it's a tricky area with many different ways of calling the code. If you did, go ahead with the ci:forward?

**Comment by javierdearcos** [comment]
I was confident in the change of behavior Igor told in the ticket. I'll make some checks and forward it if everything is ok

**Comment by javierdearcos** [comment]
the old generation was not prepared to work with asset libraries and I'm trying to find a way to find with every case (sites, asset libraries, and related entities). I hope to get it right tomorrow

**Comment by javierdearcos** [comment]
Finish regenerating all cases and testing the solution. Please, recheck the code to see if you agree with this approach

**Review by nhpatt — APPROVED** [review]

**Comment by nhpatt** [comment]
ci:forward

**Comment by javierdearcos** [comment]
ci:forward

**Comment by javierdearcos** [comment]
ci:forward

**Comment by javierdearcos** [comment]
ci:forward

**Comment by nhpatt** [comment]
ci:forward

**Pull request closed without merging**
