### PR TITLE
LPS-158214 Expose extended properties in OpenAPI for schemas/DTOs that are extended by ExtensionProviders

### PR DESCRIPTION
**Pull request by ccorreagg**
This PR contains the code to expose the Extended Properties in the OpenAPI file. Those properties are exposed in the Schemas whose DTO class is extended by a list of ExtensionProvider.

For that, a new method has been created in the `OpenAPIResource` Vulcan interface and in its implementation `OpenAPIResourceImpl` with the following header:

```
public Response getOpenAPI(
    long companyId, Map<Class<?>, Class<?>> resourceDTOClasses, String type, UriInfo uriInfo)
```
Based on the `PropertyDefinition` objects returned by the `ExtensionProvider` interfaces, the properties will be exposed in the OpenAPI as follows:

- For "basic" properties (`PropertyType in [BIG_DECIMAL, BOOLEAN, DATE_TIME, DECIMAL, DOUBLE, INTEGER, LONG, TEXT]`): the property will be added to the current Schema with the name provided by the field `PropertyDefinition.propertyName`.

- For a Single element property (`PropertyType == SINGLE_ELEMENT`) (for example, a Custom Object related to a System Object with a 1toM or 1to1 relationship):
  - A schema will be created with the name provided by the field `PropertyDefinition.propertyClassName` (or with the prefix "C." in case there is another existing Schema with that name). 
  - A property with type = "object" with a reference to the recently created schema and whose name is provided by the field `PropertyDefinition.propertyName`.

- For a Multiple element property (`PropertyType == MULTIPLE_ELEMENT`) (for example, a Custom Object related to a System Object with a Mto1 or MtoM relationship):
  - A schema will be created with the name provided by the field `PropertyDefinition.propertyClassName` (or with the prefix "C." in case there is another existing Schema with that name). 
  - A property with type = "array" with a reference to the recently created schema and whose name is provided by the field `PropertyDefinition.propertyName`.

---

### Example with a possible Extension with Objects:

Given an ExtensionProvider for managing Objects, and the System Object **UserAccount** of the **Headless Admin User** API, having the following fields and relationships:
- `additionalName_ext`: String field
- `emailAddress_ext`: String field
- `givenName_ext`: String field
- `uuid_ext`: String field
- `universityUsers`: 1 to Many relationship between the Custom Object `University` and the System Object `UserAccount`
- `usersSubjects`: Many to Many relationship between the Custom Object `Subject` and the System Object `UserAccount`.

For that case:

1. The fields `additionalName_ext`, `emailAddress_ext`, `givenName_ext` and `uuid_ext` are added to the existing schema `UserAccount` in the OpenAPI
2. A new Schema `University` is created with the properties of the Custom Object `University`.
image
3. A new Schema `Subject` is created with the properties of the Custom Object `Subject`.
image
4. A new field `universityUsers` of type `object` is added to the existing Schema `UserAccount` in the OpenAPI.
5. A new field `usersSubjects` of type `array` is added to the existing Schema `UserAccount` in the OpenAPI.

image

### CODE REVIEW

**Comment by ccorreagg** [comment]
cc/ @LuismiBarcos

**Review by javierdearcos — APPROVED** [review]
Very nice work 🚀 

Let's leave the ExtensionUtil for now as it is an internal class and we will always have time to change it in the future

**Comment by javierdearcos** [comment]
I was going to fix the baseline error but we need to check the others too. I find especially weird the vulcan compilation error.

**Comment by ccorreagg** [comment]
> I was going to fix the baseline error but we need to check the others too. I find especially weird the vulcan compilation error.

I needed to update the tests that were using an old constructor (included in the rebased commit 62cd6408850ead46355f508aef68b15031698b1e)

For the new version, I included a new baseline commit 1a1f57b55161de56f65f70405b4e8b424b6969cb

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by javierdearcos** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
ci:forward

**Pull request closed without merging**
