### PR TITLE
LPD-25334 - poshi - replace `creator` with `externalReferenceCode` in `DataSetFragmentFilters.testcase`

### PR DESCRIPTION
**Pull request by kresimir-coko**
https://liferay.atlassian.net/browse/LPD-25334

### CODE REVIEW

**Comment by kresimir-coko** [comment]
ci:test:frontend

**Comment by kresimir-coko** [comment]
ci:report:2569091512

**Comment by kresimir-coko** [comment]
Testray reports a lot of unique failures, but it seems fishy. @dsanz @markocikos 

There are 3 failures related to data sets:
1. [DataSetViewSorting#AssertDeleteSortingMessage](https://testray.liferay.com/home/-/testray/case_results/2569093931)
2. [DataSetViewSorting#AssertEditSortingOptions](https://testray.liferay.com/home/-/testray/case_results/2569093763)
3. [DataSetFragmentFilters#CanApplyFilter](https://testray.liferay.com/home/-/testray/case_results/2569093732/)

Note that the last one (`DataSetFragmentFilters#CanApplyFilter`) isn't related to any tests I am changing in the PR.

**Review by markocikos — APPROVED** [review]
@kresimir-coko The changes in tests LGTM! I don't know what's going on with CI reports :thinking:

**Comment by dsanz** [comment]
ci:test:frontend

**Comment by kresimir-coko** [comment]
ci:test:frontend

**Comment by kresimir-coko** [comment]
ci:report:2570242562

**Comment by kresimir-coko** [comment]
ci:report:2570242562

**Comment by kresimir-coko** [comment]
It would seem all 3 changed tests still fail:
### AssertExcludeSingleSelectionPrePopulatedFilterIsDisplayed
```
java.lang.Exception: 
Element is not present at "//button[contains(@class, 'filter-resume') 
and contains(., 'Filter Transport: (Exclude) bike')]"
```
### AssertIncludeMultipleSelectionPrePopulatedFilterIsDisplayed
```
java.lang.Exception: 
Element is not present at "//button[contains(@class, 'filter-resume') 
and contains(., 'Filter Transport: car, bus, bike')]"
```
### AssertSingleSelectionFilterIsDisplayed
```
com.liferay.poshi.runner.exception.ElementNotFoundPoshiRunnerException: 
Element is not present at "//div[contains(@class,'table-list-title') 
and contains(.,'Filter Transport')]"```

I will look into fixing this @dsanz, if I don't find an easy fix we can reconsider

**Comment by dsanz** [comment]
I see. Checking test story we can see that:

- 
[LocalFile.DataSetFragmentFilters#AssertExcludeSingleSelectionPrePopulatedFilterIsDisplayed](https://testray.liferay.com/home/-/testray/case_results/2570242957/history?tab=result&hideFilterPin=true)

**Comment by kresimir-coko** [comment]
ci:forward

**Comment by dsanz** [comment]
ci:forward

**Comment by kresimir-coko** [comment]
ci:forward

**Pull request closed without merging**
