### PR TITLE
LPS-193107 Adding test for the Actions tab in Data Set

### PR DESCRIPTION
**Pull request by JerryAdrianoo**
**Description:**
Adding test to validate the cancel button in the Actions tab.

**Jira Ticket:**
https://liferay.atlassian.net/browse/LPS-193107

### CODE REVIEW

**Comment by JerryAdrianoo** [comment]
ci:stop

**Comment by JerryAdrianoo** [comment]
ci:test:frontend-data-set

**Comment by JerryAdrianoo** [comment]
ci:test:sf

**Comment by JerryAdrianoo** [comment]
ci:test:frontend-data-set

**Comment by JerryAdrianoo** [comment]
ci:stop

**Comment by JerryAdrianoo** [comment]
ci:test:frontend-data-set

**Comment by JerryAdrianoo** [comment]
@CarlosBrichete these failures are not related 😄

**Comment by JerryAdrianoo** [comment]
ci:test:sf

**Review by CarlosBrichete — APPROVED** [review]
LGTM :)

**Comment by JerryAdrianoo** [comment]
ci:forward

**Pull request closed without merging**
