### PR TITLE
LPS-157201 - Update alloy-ui to 3.1.0-deprecated.97

### PR DESCRIPTION
**Pull request by georgel-pop-lr**
Fixes https://github.com/liferay/liferay-frontend-projects/pull/966

### CODE REVIEW

**Comment by georgel-pop-lr** [comment]
ci:forward

**Comment by georgel-pop-lr** [comment]
ci:test:relevant

**Comment by georgel-pop-lr** [comment]
ci:test:relevant

**Comment by georgel-pop-lr** [comment]
ci:test:sf

**Comment by georgel-pop-lr** [comment]
ci:test:relevant

**Comment by georgel-pop-lr** [comment]
Hi @john-co could you please provide me some help with this pull.

Regards.

**Comment by john-co** [comment]
Reviewed. Test failures are unrelated. :heavy_check_mark: 

Ok to manually forward from QA perspective.

**Comment by susanchen3** [comment]
Closing PR because it was merged upstream: https://github.com/brianchandotcom/liferay-portal/pull/120117

**Pull request closed without merging**
