### PR TITLE
LRQA-82684 Element is not present in ManagementToolbar#OrderButtonAsAToggleCanDisplayTooltip

### PR DESCRIPTION
**Pull request by andreluis2022**
**Description:**
Element is not present in ManagementToolbar#OrderButtonAsAToggleCanDisplayTooltip

**JIRA Ticket:**
[LRQA-82684](https://liferay.atlassian.net/browse/LRQA-82684) FIX

### CODE REVIEW

**Comment by andreluis2022** [comment]
ci:test:frontend-data-set

**Comment by andreluis2022** [comment]
Hey @CarlosBrichete can you take a look in this fix ?

**Review by CarlosBrichete — APPROVED** [review]
LGTM :)

**Comment by andreluis2022** [comment]
ci:forward

**Pull request closed without merging**
