### PR TITLE
[WIP] Simple move clay load to main.scss

### PR DESCRIPTION
**Pull request by marcoscv-work**
Moving `clay.scss` file in `main.scss`

It looks like:

image

Exactly the same.

We go from:

- clay.css -  628 KB (not compressed)
- main.css -  233 KB (not compressed)

to: 

- main.css -  862 KB (not compressed)

### CODE REVIEW

**Comment by marcoscv-work** [comment]
ci:stop

**Comment by jbalsas** [comment]
Hey @marcoscv-work, can you outline what's the reason for this change and how would it be benefitial?

**Comment by edalgrin** [comment]
I'm not sure which direction he's trying but I'm also exploring a first "unification method" for main.css (many reasons WIP…)

I was wondering, is *theme/clay.css ever imported in Portal without *theme/main.css ?

**Comment by markocikos** [comment]
@marcoscv-work Are you still working on this? Does the task have an LPS? Is it still in analysis (https://github.com/liferay-frontend/liferay-portal/pull/748#issuecomment-773223405)? Maybe it makes sense to close this PR and open when we have a clearer objective.

**Comment by jbalsas** [comment]
Going to close here for cleaning purposes. We can discuss about this later this week as we work through our next steps.

> I was wondering, is *theme/clay.css ever imported in Portal without *theme/main.css ?

@edalgrin, did you manage to answer that question yourself? I think you have a fair understanding by now of what are we loading, so you might already know ;)

**Pull request closed without merging**
