### PR TITLE
LPS-125753 - Fix vertical space

### PR DESCRIPTION
**Pull request by marcoscv-work**
This PR fix a wrong space on `default_user_associations.jsp`:

image

---

To test this PR:

- Product Menu > Configuration > Site Settings > (tab) Advanced
- Amazed by the great visual result

### CODE REVIEW

**Review by edalgrin — APPROVED** [review]
Quick review 👌

**Comment by marcoscv-work** [comment]
ci:test:relevant

**Comment by pat270** [comment]
@marcoscv-work Can we get rid of `button-holder` and just replace with `form-group`? Also there is a `button-holder` on https://github.com/liferay-frontend/liferay-portal/pull/704/commits/c714334981a92303d4fccd94c4b521c60a3f0efa#diff-db94763aab366829470bb278a7a86bee20a94b0ca3c0b44656ae3ef2a295f27bR140

**Comment by marcoscv-work** [comment]
> Can we get rid of `button-holder` and just replace with `form-group`? Also there is a `button-holder` on

The first thing I tried is to replace all `button-holder` and I get some errors because there is a lot of custom CSS over that class so I changed to fix only this specific problem but yeah, I totally agree with removing support for all `button-holder`.

Do we go ahead with this fast fix and then planning a total removal?

**Comment by pat270** [comment]
Fast fix is ok if we are planning on total removal.

**Comment by marcoscv-work** [comment]
ci:forward

**Pull request closed without merging**
