### PR TITLE
LPS-173626 | Change Remote Apps to Client Extension in .properties files related to poshi test

### PR DESCRIPTION
**Pull request by mateusralv**
Description: 
Change Remote Apps to Client Extension in .properties files related to poshi test

JIRA LINK: 
https://issues.liferay.com/browse/LPS-173626

### CODE REVIEW

**Comment by mateusralv** [comment]
ci:test:sf

**Comment by mateusralv** [comment]
ci:test:sf

**Comment by mateusralv** [comment]
ci:test:relevant

**Review by john-co — COMMENTED** [review]
Use `client extensions` with an `s` to match JIRA and the app name displayed in portal UI. Besides that looks good!

**Comment by john-co** [comment]
ci:test:sf

**Comment by john-co** [comment]
ci:test:frontend-client-extensions:nocompile

**Comment by mateusralv** [comment]
Looks like the changes worked, all right to forward? @john-co

**Comment by john-co** [comment]
yes all good to go :rocket:

**Comment by john-co** [comment]
ci:forward

**Pull request closed without merging**
