### PR TITLE
LPS-169541 FDS dropdown item async action has incorrect error handling

### PR DESCRIPTION
**Pull request by markocikos**
### References

- [LPS-169541 FDS dropdown item async action has incorrect error handling](https://issues.liferay.com/browse/LPS-169541)

### What is the goal of this PR?

The main goal is fixing error handling of FDS actions. 

In addition:
- we are fixing styles when action loading indicator is active.
- we are adding samples for action success and two types of errors.

Notes:
- `delay(500)` and related code was a (pretty ugly) fix for the case where loading indicator state was set during data refresh. Instead of this, we are no longer updating loading indicator on action success; data refresh does this by refreshing entire table.
- I equalized styles by setting fixed min height. This may not be ideal solution, but I see no cleaner way of equalizing loading indicator and dropdown ellipsis icon.

#### Before PR

https://user-images.githubusercontent.com/5435511/203831550-864e78c6-2d16-4e79-a4af-ec8c101fb48c.mp4

#### After PR

https://user-images.githubusercontent.com/5435511/203831567-716090ad-fbeb-49ef-a3d9-1ee2f8fbd9e4.mp4

### CODE REVIEW

**Comment by markocikos** [comment]
Force-pushed! The CI error in https://github.com/liferay-frontend/liferay-portal/pull/2881#issuecomment-1326787652 was related. I prettified sample module a bit, and left in an item with `#test-pencil`.

**Comment by markocikos** [comment]
@john-co the three cases in this PR could be valuable CI tests:
1. successful request --> results in success toast
2. error connection refused --> results in error toast
3. error 404 --> results in error toast

I used `http:localhost` to simulate requests. This will very likely work in CI environment, but I'm not completely sure.

**Comment by markocikos** [comment]
ci:test:relevant

**Comment by markocikos** [comment]
I see, all existing four are used in a test for quick actions cutoff. Adding new actions to the end!
screen

**Comment by markocikos** [comment]
ci:test:relevant

**Review by tinycarol — APPROVED** [review]
LGTM!

**Comment by markocikos** [comment]
ci:forward

**Comment by john-co** [comment]
> @john-co the three cases in this PR could be valuable CI tests:
> 
> successful request --> results in success toast
> error connection refused --> results in error toast
> error 404 --> results in error toast
> I used http://localhost to simulate requests. This will very likely work in CI environment, but I'm not completely sure.


Thanks! I'll create a task for this so QA can create the automation tests.

**Pull request closed without merging**
