### PR TITLE
LPS-140411 filter in admin APIs

### PR DESCRIPTION
**Pull request by javierdearcos**
Resending because original PR seems stuck in the CI.

/cc @nhpatt 

Original PR: https://github.com/liferay-frontend/liferay-portal/pull/1559

### CODE REVIEW

**Comment by javierdearcos** [comment]
ci:forward

**Comment by nhpatt** [comment]
ci:test:relevant

**Comment by nhpatt** [comment]
-- rebased

**Comment by nhpatt** [comment]
ci:test:relevant

**Comment by nhpatt** [comment]
ci:test:relevant

**Comment by nhpatt** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
@javierdearcos @nhpatt I merged this in manually

@javierdearcos can you modify the manually written test?

```
	@Override
	@Test
	public void testGetObjectDefinitionsPageWithSortString() throws Exception {
		ObjectDefinition objectDefinition1 = randomObjectDefinition();

```

You can fix it simply by overriding 

		objectDefinition1 = testGetObjectDefinitionsPage_addObjectDefinition(
			objectDefinition1);

and adding a counter.

So set a counter at the class level

private int _count;

so that it's reset at every test

Then, everytime you call

testGetObjectDefinitionsPage_addObjectDefinition

do _count++

and if _count == 1, set the name to "B"

**Comment by nhpatt** [comment]
Closing as it is already merged.

**Pull request closed without merging**
