### PR TITLE
LPS-119791 Page elements in the footer of the permissions iframe are offset

### PR DESCRIPTION
**Pull request by boton**
`.table-responsive` were lost margin bottom in @clayui/css@3.13.0 (current now) in portal version 7.2.1-ga2 @clayui/css@3.0.1 works great.

**Steps to reproduce:**

Show any permissions modal, for example:

1. Navigate to Control Panel > Roles > Asset Library Roles
2. Click on any default role's action icon > Permissions
3. View iframe

---

**Before the fix:**
image

**After the fix:**
image

### CODE REVIEW

**Comment by boton** [comment]
ci:test:sf

**Comment by boton** [comment]
ci:test:relevant

**Comment by boton** [comment]
Maybe other tables also lost the margin 🤔 

`git grep "table-responsive" -- '*.jsp' '*.jspf'`

**Comment by carloslancha** [comment]
Hey @eduardoallegrini could you please take a look to see if this is a clay issue or something we need to change in portal (add classes, rows, cols, wrap the pagination somehow...)? Thx!

**Comment by pat270** [comment]
@carloslancha @eduardoallegrini This is a Clay CSS issue. Looks like I deleted it when I took over Bootstrap CSS. We can close this once I patch it.

**Comment by pat270** [comment]
Going to close this, this will be fixed by https://github.com/liferay/clay/pull/3662

**Comment by carloslancha** [comment]
Thx @pat270 !

**Pull request closed without merging**
