### PR TITLE
[7.4-only]LPS-102106 Remove compat-layer:pager

### PR DESCRIPTION
**Pull request by eduardoallegrini**
Remove compat-layer:pager and upgrade the legacy code

### CODE REVIEW

**Comment by pat270** [comment]
`liferay-ui:page-iterator` markup LGTM!

**Comment by marcoscv-work** [comment]
LGTM !

**Comment by markocikos** [comment]
ci:test:sf

**Comment by markocikos** [comment]
ci:test:relevant

**Comment by marcoscv-work** [comment]
I'll merge this one in a bigger PR!

**Comment by marcoscv-work** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcoscv-work** [comment]
ci:test:stop

**Comment by marcoscv-work** [comment]
Merged fixe SF and rebased here:
https://github.com/liferay-frontend/liferay-portal/pull/584

**Pull request closed without merging**
