### PR TITLE
[TS] LPS-146513

### PR DESCRIPTION
**Pull request by magjed4289**
Continuation of https://github.com/liferay-frontend/liferay-portal/pull/1920
https://issues.liferay.com/browse/LPS-146513

### CODE REVIEW

**Comment by magjed4289** [comment]
ci:test:sf

**Comment by magjed4289** [comment]
ci:test:stable

**Comment by magjed4289** [comment]
ci:test:relevant

**Comment by magjed4289** [comment]
ci:test:sf

**Comment by magjed4289** [comment]
ci:test:stable

**Comment by magjed4289** [comment]
ci:test:relevant

**Comment by crodriguezy** [comment]
ci:test:sf

**Comment by magjed4289** [comment]
ci:reevaluate:1277401_1973

**Comment by magjed4289** [comment]
ci:test:relevant

**Comment by magjed4289** [comment]
ci:test:stable

**Comment by magjed4289** [comment]
ci:test:sf

**Comment by magjed4289** [comment]
ci:help

**Comment by magjed4289** [comment]
ci:test:upstream-functional

**Comment by magjed4289** [comment]
ci:close

**Comment by magjed4289** [comment]
another update will be sent in a different PR

**Pull request closed without merging**
