### PR TITLE
LPS-115271 Adds IntersectionObserver polyfill for IE

### PR DESCRIPTION
**Pull request by brunobasto**
Added the polyfill from https://github.com/w3c/IntersectionObserver/blob/b4bfbbc8e8a62b7e0ad3e4b182b3e35d7eb46afd/polyfill/package.json 

Detailed information can be found at https://github.com/w3c/IntersectionObserver/blob/master/explainer.md

Previous discussions: 
https://issues.liferay.com/browse/FOSS-64
https://issues.liferay.com/browse/LWM-1274
https://github.com/wincent/liferay-portal/pull/319#discussion_r436885019

### CODE REVIEW

**Comment by brunobasto** [comment]
ci:test:sf

**Comment by brunobasto** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
LGTM!

**Review by jbalsas — APPROVED** [review]

**Comment by brunobasto** [comment]
ci:forward

**Pull request closed without merging**
