### PR TITLE
LPS-165426 Make sure to always close the modal if the user press the done button

### PR DESCRIPTION
**Pull request by victorg1991**
Related ticket: https://issues.liferay.com/browse/LPS-165426

This PR make sure that the modal is closed when the done button is clicked by the user. Otherwise we may end up in a situation where the button is enabled and doesn't do anything

Let me know what do you think 🤔  It may be other ways to fix this like disabling the button if the user hasn't selected any option, but that may be hard since there are a lot of implementations of the selectors

### CODE REVIEW

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by dsanz** [comment]
LGTM, jsut for the sake of clarity, this fixes the ability to close the modal via "enter" key even  if no selection is made. This is already possible using the mouse. 

We will need to revisit the UX to determine whether an empty selection can be "confirmed" with the Done button in all cases, some, or none of them, so that the modal component can be adapted accordingly.

**Comment by dsanz** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
