### PR TITLE
LPD-41116 Update of client extensions through the UI can randomly fail in clustered environments

### PR DESCRIPTION
**Pull request by izaera**
Comes from: https://github.com/brianchandotcom/liferay-portal/pull/156337
**LPP Related**: https://liferay.atlassian.net/browse/LPP-56124
**Owner Team Review Needed**: CI, then Core Infrastructure
QA status: 🟢 https://github.com/liferay-frontend/liferay-portal/pull/4584#issuecomment-2548333650

----

### CODE REVIEW

**Comment by izaera** [comment]
ci:test:playwright

**Comment by izaera** [comment]
ci:test:playwright

**Comment by izaera** [comment]
ci:stop

**Comment by izaera** [comment]
ci:test:playwright

**Comment by izaera** [comment]
ci:test:playwright

**Comment by izaera** [comment]
ci:test:playwright

**Comment by izaera** [comment]
I've reordered the code, will retest again and if PW tests for clustering work I will send this to CI team for review, before sending it to Brian.

**Comment by izaera** [comment]
ci:test:playwright

**Comment by izaera** [comment]
ci:test:playwright

**Comment by izaera** [comment]
ci:test:playwright

**Comment by izaera** [comment]
ci:test:playwright

**Comment by izaera** [comment]
ci:test:playwright

**Comment by izaera** [comment]
ci:test:playwright

**Comment by izaera** [comment]
ci:test:playwright

**Comment by izaera** [comment]
ci:test:playwright

**Comment by izaera** [comment]
ci:test:playwright

**Comment by izaera** [comment]
ci:test:playwright

**Comment by izaera** [comment]
ci:stop

**Comment by izaera** [comment]
ci:test:playwright

**Comment by izaera** [comment]
ci:test:playwright

**Comment by izaera** [comment]
ci:stop

**Comment by izaera** [comment]
ci:forward:force

**Comment by izaera** [comment]
ci:stop

**Comment by izaera** [comment]
ci:test:playwright

**Comment by izaera** [comment]
ci:test:playwright

**Comment by izaera** [comment]
ci:stop

**Comment by izaera** [comment]
ci:test:playwright

**Comment by izaera** [comment]
ci:test:playwright

**Comment by izaera** [comment]
ci:test:playwright

**Comment by izaera** [comment]
ci:test:playwright

**Comment by izaera** [comment]
ci:test:playwright

**Comment by izaera** [comment]
OK, this has passed playwright tests with cluster support :partying_face:

**Comment by kenjiheigel** [comment]
Reviewed the shell script portion and resent here: 
https://github.com/liferay-frontend/liferay-portal/pull/4638

**Comment by izaera** [comment]
closing. continues at https://github.com/liferay-frontend/liferay-portal/pull/4638

**Pull request closed without merging**
