### PR TITLE
LPS-146457 Update `@clayui/*` packages to v3.46.0

### PR DESCRIPTION
**Pull request by matuzalemsteles**
# [3.46.0](https://github.com/liferay/clay/compare/v3.45.1...v3.46.0) (2022-02-09)

### Bug Fixes

-   **@clayui/color-picker:** fixes error when not syncing the field state with the editor when there are no palettes ([097b76a](https://github.com/liferay/clay/commit/097b76a4379c2d59e14a89d5067725af762d1962))
-   **@clayui/core:** fix error when selecting parent nodes and controlling intermediate state in multiple selection ([2174128](https://github.com/liferay/clay/commit/2174128202457d54be34ee99d3ffd65281e40ed2))
-   **@clayui/css:** Buttons fix alignment of icons in flex items ([72993f2](https://github.com/liferay/clay/commit/72993f20c77b33e7985464fc4b710a9afc4d3c03))
-   **@clayui/css:** Mixins `clay-button-variant` customize `.btn .inline-item .lexicon-icon` ([baf9e10](https://github.com/liferay/clay/commit/baf9e1026efc7eb1c422b19c75a359c09669b21c))
-   **@clayui/date-picker:** Adding some changes related to time reset and refactoring code ([dd4d2e8](https://github.com/liferay/clay/commit/dd4d2e835ec5ff5ca8068ddc04255ac1712e8d48))
-   **@clayui/date-picker:** fix bug when not changing time to current time when clicking on dot button ([5daa1f1](https://github.com/liferay/clay/commit/5daa1f10a12a426caea6c6ffffa6e6e719d8859e))
-   **@clayui/date-picker:** fix error in always adding ampm when user is typing ([d5502e4](https://github.com/liferay/clay/commit/d5502e4cff31c1db56981d33dafdf794e8a4029d))
-   **@clayui/date-picker:** fix error when formatting time using 12 hours ([8061529](https://github.com/liferay/clay/commit/8061529170f421cf30d2133a1b8570deaf178a5a))
-   **@clayui/date-picker:** Removing initialized variables ([997e10f](https://github.com/liferay/clay/commit/997e10f0743e06b95ed360d47614e35c15c9b655))
-   **@clayui/date-picker:** Reset actual date when input string is empty ([94de1ae](https://github.com/liferay/clay/commit/94de1ae27a83e328a173481b3c1a3705b9fb0e93))
-   **@clayui/multi-select:** fix error when adding labels with whitespace ([1a8a166](https://github.com/liferay/clay/commit/1a8a1664be7541e1ca2173334db83e07562996bd))

### Features

-   **@clayui/core:** allow configuring the drag and drop context ([59f9f58](https://github.com/liferay/clay/commit/59f9f583a589dfb1494eb82ad2ca0e0fa7e2ed1d))
-   **@clayui/css:** Aspect Ratio adds `aspect-ratio-8-to-3` (37.5%) ([7b7f9c2](https://github.com/liferay/clay/commit/7b7f9c2f7b49ed1a72cdf41b2d160e69a14ab83b))
-   **@clayui/css:** Cadmin Aspect Ratio adds `aspect-ratio-8-to-3` (37.5%) ([5705ad5](https://github.com/liferay/clay/commit/5705ad5a16f6185ce9573000fe7cb741e01e7a35))
-   **@clayui/css:** Cadmin Type convert `.display-*` components to `clay-css` mixin pattern ([3de7a63](https://github.com/liferay/clay/commit/3de7a6345835e43050cde76ed0b8eeb4b04c4a71))
-   **@clayui/css:** Cadmin Type convert h1-h6 to clay-css mixin pattern ([332f1fa](https://github.com/liferay/clay/commit/332f1faedf9ab5f1ca4337fd7a15be2ad44a5bf1))
-   **@clayui/css:** Cadmin Utilities adds `text-1` through `text-11` for font-sizes ([80e1097](https://github.com/liferay/clay/commit/80e109719293f27d12eb6d5ece2a28a7eaf99993))
-   **@clayui/css:** Mixins Grid adds `clay-generate-media-breakpoints` ([c18ebd2](https://github.com/liferay/clay/commit/c18ebd2c78bbce463687edb03c0d4f651b0e03d6))
-   **@clayui/css:** SVG Icons adds export ([0e67571](https://github.com/liferay/clay/commit/0e67571dd6af05cc9fa2fd703e041b6606ec0a1f))
-   **@clayui/css:** Type convert `.display-*` components to `clay-css` mixin pattern ([e201fcc](https://github.com/liferay/clay/commit/e201fcc2ebec60880190d5f288a1c6e16d554e33))
-   **@clayui/css:** Type convert h1-h6 to clay-css mixin pattern ([19dcfc3](https://github.com/liferay/clay/commit/19dcfc3e1c73c2d61c49d361f18310b79970da1d))
-   **@clayui/css:** Utilities adds `text-1` through `text-11` for font-sizes ([4ce046c](https://github.com/liferay/clay/commit/4ce046c7c3b2b06523105afce664a563f69bc069))
-   **clay-pagination:** allow disabling ellipsis button in pagination ([4e4e84c](https://github.com/liferay/clay/commit/4e4e84c73120ff110acd777a409d8d370361f909))

### CODE REVIEW

**Comment by matuzalemsteles** [comment]
ci:test:frontend-clay

**Comment by matuzalemsteles** [comment]
ci:test:functional-acceptance

**Comment by matuzalemsteles** [comment]
ci:test:acceptance-functional

**Review by julien — APPROVED** [review]

**Comment by julien** [comment]
ci:test:relevant

**Comment by julien** [comment]
@john-co @Esther-OC the CI errors don't seem related to these changes - but it seems we had CI issues yesterday. I'll give it another try before asking for further assistance.

**Comment by julien** [comment]
@john-co @Esther-OC seems we're out of luck today, could you please confirm that these changes are not causing the CI errors? Thanks.

**Comment by john-co** [comment]
ci:test:relevant

**Comment by john-co** [comment]
Reviewed. js unit test failures look related. They failed on the same tests and I couldn't find evidence of test flakiness

----

- :apps:dynamic-data-mapping:dynamic-data-mapping-form-field-type:packageRunTest
```
     [exec] Summary of all failing tests
     [exec] FAIL test/js/DatePicker/DatePicker.es.js (5.345s)
     [exec]   ??? DatePicker ??? fills the input date and time according to the locale
     [exec] 
     [exec]     expect(element).toHaveValue(09/02/2022 23:30)
     [exec] 
     [exec]     Expected the element to have value:
     [exec]       09/02/2022 23:30
     [exec]     Received:
     [exec]       09/02/2022 17:54
     [exec] 
     [exec]       144 | 		userEvent.click(screen.getByLabelText('Select current date'));
     [exec]       145 | 
     [exec]     > 146 | 		expect(container.querySelector('[type=text]')).toHaveValue(
     [exec]           | 		                                               ^
     [exec]       147 | 			moment().format('DD/MM/YYYY [23:30]')
     [exec]       148 | 		);
     [exec]       149 | 	});
     [exec] 
     [exec]       at Object.<anonymous> (test/js/DatePicker/DatePicker.es.js:146:50)
     [exec]       at processTicksAndRejections (node:internal/process/task_queues:96:5)
     [exec] 
     [exec]   ??? DatePicker ??? calls the onChange callback with a valid date and time
     [exec] 
     [exec]     expect(jest.fn()).toHaveBeenCalledWith(...expected)
     [exec] 
     [exec]     - Expected
     [exec]     + Received
     [exec] 
     [exec]       {},
     [exec]     - "2022-02-09 23:30",
     [exec]     + "2022-02-09 17:54",
     [exec] 
     [exec]     Number of calls: 1
     [exec] 
     [exec]       169 | 		userEvent.click(screen.getByLabelText('Select current date'));
     [exec]       170 | 
     [exec]     > 171 | 		expect(onChange).toHaveBeenCalledWith(
     [exec]           | 		                 ^
     [exec]       172 | 			{},
     [exec]       173 | 			moment().format('YYYY-MM-DD [23:30]')
     [exec]       174 | 		);
     [exec] 
     [exec]       at Object.<anonymous> (test/js/DatePicker/DatePicker.es.js:171:20)
     [exec]       at processTicksAndRejections (node:internal/process/task_queues:96:5)
     [exec] 
     [exec] 
     [exec] Test Suites: 1 failed, 20 passed, 21 total
     [exec] Tests:       2 failed, 3 skipped, 275 passed, 280 total
     [exec] Snapshots:   126 passed, 126 total
     ```
     
- :dxp:apps:portal-search-tuning:portal-search-tuning-rankings-web:packageRunTest  
   
```
    [exec] > Task :dxp:apps:portal-search-tuning:portal-search-tuning-rankings-web:packageRunTest
     [exec] FAIL test/js/components/ResultRankingsForm.es.js (67.597s)
     [exec]   ??? ResultRankingsForm ??? renders blank alias
     [exec] 
     [exec]     expect(received).toBe(expected) // Object.is equality
     [exec] 
     [exec]     Expected: ""
     [exec]     Received: " "
     [exec] 
     [exec]       104 | 		});
     [exec]       105 | 
     [exec]     > 106 | 		expect(input.getAttribute('value')).toBe('');
     [exec]           | 		                                    ^
     [exec]       107 | 
     [exec]       108 | 		const tagsElement = container.querySelectorAll('.label-item-expand');
     [exec]       109 | 
     [exec] 
     [exec]       at test/js/components/ResultRankingsForm.es.js:106:39
     [exec]       at processTicksAndRejections (node:internal/process/task_queues:96:5)
     [exec] 
     [exec] Test Suites: 1 failed, 16 passed, 17 total
     [exec] Tests:       1 failed, 2 skipped, 118 passed, 121 total
     [exec] Snapshots:   0 total
     ```

**Comment by matuzalemsteles** [comment]
Thanks @john-co, I'll take a look.

**Comment by matuzalemsteles** [comment]
Hey @john-co fixes the tests related to the new behavior for MultiSelect and the DatePicker that the behavior test was wrong.

**Comment by julien** [comment]
ci:test:relevant

**Comment by john-co** [comment]
Datepicker js unit test still failing
- **:apps:dynamic-data-mapping:dynamic-data-mapping-form-field-type:packageRunTest**
```
     [exec] FAIL test/js/DatePicker/DatePicker.es.js (8.9s)
     [exec]   ??? DatePicker ??? fills the input date and time according to the locale
     [exec] 
     [exec]     expect(element).toHaveValue(11/02/2022 23:30)
     [exec] 
     [exec]     Expected the element to have value:
     [exec]       11/02/2022 23:30
     [exec]     Received:
     [exec]       11/02/2022 03:30
     [exec] 
     [exec]       145 | 		userEvent.type(minutes, '30');
     [exec]       146 | 
     [exec]     > 147 | 		expect(container.querySelector('[type=text]')).toHaveValue(
     [exec]           | 		                                               ^
     [exec]       148 | 			moment().format('DD/MM/YYYY [23:30]')
     [exec]       149 | 		);
     [exec]       150 | 	});
     [exec] 
     [exec]       at Object.<anonymous> (test/js/DatePicker/DatePicker.es.js:147:50)
     [exec]       at processTicksAndRejections (node:internal/process/task_queues:96:5)
     [exec] 
     [exec] Summary of all failing tests
     [exec] FAIL test/js/DatePicker/DatePicker.es.js (8.9s)
     [exec]   ??? DatePicker ??? fills the input date and time according to the locale
     [exec] 
     [exec]     expect(element).toHaveValue(11/02/2022 23:30)
     [exec] 
     [exec]     Expected the element to have value:
     [exec]       11/02/2022 23:30
     [exec]     Received:
     [exec]       11/02/2022 03:30
     [exec] 
     [exec]       145 | 		userEvent.type(minutes, '30');
     [exec]       146 | 
     [exec]     > 147 | 		expect(container.querySelector('[type=text]')).toHaveValue(
     [exec]           | 		                                               ^
     [exec]       148 | 			moment().format('DD/MM/YYYY [23:30]')
     [exec]       149 | 		);
     [exec]       150 | 	});
     [exec] 
     [exec]       at Object.<anonymous> (test/js/DatePicker/DatePicker.es.js:147:50)
     [exec]       at processTicksAndRejections (node:internal/process/task_queues:96:5)
     [exec] 
     [exec] 
     [exec] Test Suites: 1 failed, 20 passed, 21 total
     [exec] Tests:       1 failed, 3 skipped, 277 passed, 281 total
     [exec] Snapshots:   126 passed, 126 total
```

All other unique test failures are unrelated

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by john-co** [comment]
ci:test:frontend

**Comment by john-co** [comment]
ci:test:frontend

**Comment by john-co** [comment]
ci:test:frontend

**Comment by john-co** [comment]
Just started reviewing :)

**Comment by john-co** [comment]
Reviewed. Test failures are unrelated. :heavy_check_mark: 
- js unit test now passes
- other functiona/integration tests failed prior to test starting

**Comment by john-co** [comment]
Manually forwarded to https://github.com/brianchandotcom/liferay-portal/pull/113402

**Pull request closed without merging**
