### PR TITLE
LPS-155345 Update packages `@clayui/*` to v3.60.0

### PR DESCRIPTION
**Pull request by matuzalemsteles**
### Bug Fixes

-   **@clayui/css:** Buttons removes extensions `loading-animation` variants ([c9d73ed](https://github.com/liferay/clay/commit/c9d73edd317bd317e175ea63fb3f229b7c1b10bd))
-   **@clayui/css:** c-slideout should use display: flex on tbar-stacked for show/transition ([0a95c59](https://github.com/liferay/clay/commit/0a95c592cbaaf604221a804d585507c33909045a))
-   **@clayui/css:** Cadmin Buttons removes extensions `loading-animation` variants ([ed9e0dd](https://github.com/liferay/clay/commit/ed9e0dd84d14f5e7a4f308458bdc1be4284a25c4))
-   **@clayui/css:** Cadmin Utilities unset `font-size` on `.inline-item .loading-animation` ([57b4602](https://github.com/liferay/clay/commit/57b4602eb8e901e2292f34438900eb63f6a4c114))
-   **@clayui/css:** Mixins clay-slideout-variant remove setter functions ([e21665d](https://github.com/liferay/clay/commit/e21665de62a7efa1649fcfdd988472d2b7047935))
-   **@clayui/css:** Updates content property values to conform to what is allowed by OAW Tracker ([77dd43a](https://github.com/liferay/clay/commit/77dd43a3ae68233914d406c5613da64cd6e1f77b))
-   **@clayui/css:** Utilities unset `font-size` on `.inline-item .loading-animation` ([f1106e3](https://github.com/liferay/clay/commit/f1106e376a0287572b41439187e1f304b9f9a4e5))
-   **@clayui/loading-indicator:** Deprecate small and light attributes ([4011083](https://github.com/liferay/clay/commit/40110837162ccc2e1da760e762e17cb3c2fa2f15))
-   storybook LoadingIndicator adds displayType, shape, and size ([6a98f20](https://github.com/liferay/clay/commit/6a98f201da7e9bce4932e2eec5f3be22f3f39755))

### Features

-   **@clayui/core:** adds the implementation of the Vertical Bar component ([23a1637](https://github.com/liferay/clay/commit/23a1637e8ebac46d9815d334bae1296736979542))
-   **@clayui/css:** Cadmin Loaders updates dotted styles to be circle thing with gradient and add `loading-animation-squares` ([82f7a0f](https://github.com/liferay/clay/commit/82f7a0fe9e467074a1d8aad446cc20c8d20ad539))
-   **@clayui/css:** Global `clay-css` mixin accept more properties ([e1e8dc8](https://github.com/liferay/clay/commit/e1e8dc8d68a4dd3118b099914f6e82f4eef2e698))
-   **@clayui/css:** Loaders updates dotted styles to be circle thing with gradient and add `loading-animation-squares` ([aae79ad](https://github.com/liferay/clay/commit/aae79adaabf68938c83c9ef3e170232ab49478f1))
-   **@clayui/css:** Mixins Loaders adds `clay-spinner-variant` ([1865a1d](https://github.com/liferay/clay/commit/1865a1d818f6b3e182037d21c363c27691dc390b))
-   **@clayui/loading-indicator:** Adds more attributes ([0b7627a](https://github.com/liferay/clay/commit/0b7627a4cd1d887b3bc2b1c12dcd0b63795e2f62))

### BREAKING CHANGES

-   **@clayui/css:** `loading-animation` received a breaking style update. See https://clayui.com/docs/components/loading-indicator/markup.html on how to revert back to the dotted style.

### CODE REVIEW

**Comment by susanchen3** [comment]
Reviewed. Test failures are unrelated :heavy_check_mark: 

[**Comparison run:**](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=2&testrayRunIdB=1870447120&testrayRunIdA=1870803951&statusB=3)
- LocalFile.AssetsBlogs#ViewAllBlogsShownInAssetList, LocalFile.AssetsDocumentsAndMedia#VisitorBehaviorCardShowsExpectedAmountOfPreviewsInDM, LocalFile.FormsColorField#PredefinedValueCanBeAdded are not unique to this PR
- LocalFile.ObjectAutoGeneratedView#CanDisplayEmptyDateValue and LocalFile.Accounts#AddingSecondUserToPersonAccountWillReplaceFirstUser are flaky, passes locally 

----

Although with the new loading animation, I noticed some weird loading issues on the [bundle](https://github.com/liferay-frontend/liferay-portal/pull/2315#issuecomment-1148177881). 
startup

I'm currently ant-alling this PR to see if its reproducible.

**Comment by susanchen3** [comment]
Yep on the ant-all bundle I was able to recreate the product menu loading issue. Sometimes when I first open the Sign In popup, the loading animation bounces up and down. 

loading

As well when I when I open the "Add" panel on widget pages, the loading animation briefly had a scroll bar. :thinking: 
loading bar

cc: @matuzalemsteles

**Comment by matuzalemsteles** [comment]
Thanks @susanchen3! @pat270 do you think this could be something from the loading indicator or a side effect in DXP maybe? I'll try to fix it from the DXP side.

**Comment by matuzalemsteles** [comment]
@pat270 I think this is a side effect of the new animation that needs to rotate, as we basically use a `margin auto` to position the animation in the center this ends up creating the margin and rotating the element itself by 360% creates this scroll but this seems to be a side effect also of cadmin's own reset that sets the margin to 0.

I think the best thing here would be to create a ticket for us to fix this, I'm not sure if it needs to be an LPS or just an issue on Clay's Github that needs to be fixed there. @pat270 what do you think?

**Comment by pat270** [comment]
Sorry I missed this today, it got lost in all the email notifications. I think we need to fix this in DXP and Clay. I'm using both pseudo elements for `loading-animation` and it would be a waste to create a separate animation for the dot at the beginning of the indicator. I'll take a closer look tomorrow and send some fixes.

**Comment by matuzalemsteles** [comment]
Thanks @pat270!

**Comment by pat270** [comment]
@matuzalemsteles actually nm my last comment. I was able to use the same animation for both pseudo elements. I'll send a fix to the clay repo.

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by matuzalemsteles** [comment]
ci:test:sf

**Comment by matuzalemsteles** [comment]
A new CSS package release has been released that fixes this issue, I just submitted a commit updating to the newest version.

cc @susanchen3

**Comment by susanchen3** [comment]
taking a look now!

**Comment by susanchen3** [comment]
hmmm.. the product menu and add side panel bugs are still present for me. and things seem to take a while to load, not sure if it's just my laptop though..

cc: @matuzalemsteles @pat270

**Comment by matuzalemsteles** [comment]
@susanchen3 I'm checking, I think the loading delay must not be related to the loading indicator.

**Comment by susanchen3** [comment]
The [test failures](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=2&testrayRunIdB=1872544053&testrayRunIdA=1872555820&statusB=3) are unrelated, but [LocalFile.ObjectAutoGeneratedView#CanDisplayEmptyDateValue](https://testray.liferay.com/home/-/testray/case_results/1872549732) seems pretty unique to this PR, However, I am unable to consistently reproduce it locally. Seems like a slow loading issue to me.

**Comment by pat270** [comment]
I'm checking also. Not sure why the loading indicator would cause:

> java.lang.Exception: Element is not present at "//div[contains(@class,'dnd-tbody')]//*[contains(text(),'')]"

We didn't change any markup, just the CSS.

**Comment by matuzalemsteles** [comment]
Apparently, despite @pat270 improving on the Clay side, we have to fix it on the DXP side too, at least add a height on the parent so that the circle rotation doesn't create a scroll, I think this creates a scroll due to the reset of the cadmin. Any idea how we could try to avoid this? maybe correcting one by one?

For the product menu, I think because the color of the loading indicator is the same, so it should use `light` mode, we have to update there too.

**Comment by susanchen3** [comment]
Yeah I don't think the loading indicator is causing that test to fail, I think the test is just moving to the next step too fast which causes it to fail. The test works when I manually test it so I don't think it is a concern.

**Comment by pat270** [comment]
@matuzalemsteles I understand now, we probably could add `overflow: hidden` on `.loading-animation`. It would prevent the rotation of the pseudo element boxes to cause an overflow. At 90deg rotation the diagonal of the square is taller than at 0 deg. I'm still building, can someone test this and I'll send another pr? 😿

**Comment by matuzalemsteles** [comment]
@pat270 yeah, adding `overflow: hidden;` to `.loading-animation` works fine, I was able to test it. No problem I can make a new release.

**Comment by pat270** [comment]
For the loading animation being the wrong color, we can set it in DXP. The product menu should default to a light text color anyway.

**Comment by pat270** [comment]
Adding `color: $cadmin-white` at https://github.com/liferay/liferay-portal/blob/master/modules/apps/product-navigation/product-navigation-product-menu-theme-contributor/src/main/resources/META-INF/resources/product_navigation_product_menu.scss#L46 should make everything good.

**Comment by susanchen3** [comment]
ci:test:bundle

**Comment by susanchen3** [comment]
loading animation is present in product menu now :tada: 
scroll

**Comment by pat270** [comment]
@susanchen3 the scrollbars are still visible on your machine. After we get this pr through, can you file an issue for it? I'll look into it.

**Comment by matuzalemsteles** [comment]
Hey @pat270 this seems to work fine with `overflow:hidden`, I did a test today with the update. I submitted a PR to update on Clay and made a new clay CSS release for 3.60.2 which includes this fix. Are you thinking of fixing it another way?

**Comment by susanchen3** [comment]
I see them on ubuntu, but I can double check on my mac

**Comment by pat270** [comment]
It's ok you don't need to check your mac. I have a feeling this existed before our changes.

**Comment by matuzalemsteles** [comment]
Oh I see @pat270, thanks for the clarification! Hmm, maybe we can create a specific ticket for this?

**Comment by susanchen3** [comment]
:scream:  nooooo network disruption... going to manually check and forward if it looks good.. and create a ticket for the scroll bar.

**Comment by susanchen3** [comment]
I no longer see a scroll bar on the latest run.. do you guys still want a ticket? I think this is good to forward now :)

**Comment by matuzalemsteles** [comment]
@susanchen3 It doesn't show up for me either! At least on Mac.

**Comment by susanchen3** [comment]
Will manually forward, not open a ticket, and pray there are no issues when merged :pray: :sweat_smile:

**Pull request closed without merging**
