### PR TITLE
LPS-122389 Remove {addClasses, hasClass, toggleClasses, removeClasses} usages of metal-dom

### PR DESCRIPTION
**Pull request by bryceosterhaus**
Follow up from https://github.com/liferay-frontend/liferay-portal/pull/440

This should address the issues from CI

### CODE REVIEW

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
ci:test:sf

**Comment by bryceosterhaus** [comment]
@john-co, @PablitoBonito, @zhangyan0701, @manoelcyreno, could you verify these failures? Original PR at https://github.com/liferay-frontend/liferay-portal/pull/440

**Comment by john-co** [comment]
Just started reviewing :)

**Comment by john-co** [comment]
ci:test:bundle

**Comment by john-co** [comment]
It looks like all the functional tests are failing due to the sign in modal's form fields not being editable (grayed out and can't type anything into the email and password fields).

image

**Comment by bryceosterhaus** [comment]
@john-co I can't seem to reproduce this locally at all. Could this potentially be something with CI?

**Comment by john-co** [comment]
I'll take a look at the test bundle to see if I can reproduce the issue.

**Comment by john-co** [comment]
I wasn't able to reproduce the issue locally either. Let's run the tests again and see what happens...

**Comment by john-co** [comment]
ci:test:relevant

**Comment by john-co** [comment]
It looks like an issue with Chrome 65 browser. This is the chromium version that CI and poshi automation uses.

image

**Comment by bryceosterhaus** [comment]
@john-co we are on Chrome 65? Can we use more up to date versions of chrome? I believe the latest version released is 86, meaning we are over 20 versions behind.

cc @jbalsas if we are looking to adopt modern javascript, we are going to run into a lot of issues with CI if we are on older versions.

**Comment by john-co** [comment]
I'll make a request to update our test browser versions.

**Comment by jbalsas** [comment]
> I'll make a request to update our test browser versions.

Thanks @john-co!! I quickly grabbed @david-truong. It seems we should've updated browsers for `7.3` but we forgot. Made no difference since we were supporting IE11 anyways...

He says we can update to [latest](https://chromeenterprise.google/browser/download/) right now, since it's stable and then set up a schedule to update CI rather than find out in situations like this. 

How long could the update take? What should we do in the meantime? There's a lot of work we'll need to put on hold 😢 

/cc @vicnate5

**Comment by john-co** [comment]
Requested in https://liferay.slack.com/archives/CL3TWSMHQ/p1604515014066500. This may take a few weeks to update the browser version on CI.

The only option we see is to get a preview by running the ci tests on a PR, but if we run into compatibility issues with browser version we'll have to put merging the code on hold until CI team updates Chrome.

**Comment by vicnate5** [comment]
CI team has agreed to prioritize the request to update Chrome so we can unblock this team.

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
I removed some of the es6 syntax for now to see if it might help get through the tests. Browser upgrade still needed for other PRs in the queue though.

**Comment by jbalsas** [comment]
ci:forward

**Comment by jbalsas** [comment]
Let's enjoy this small victory!!

**Pull request closed without merging**
