### PR TITLE
LPD-20981 Update sorting tab to store FDS Sorting Dropdown data instead of default sorting v2

### PR DESCRIPTION
**Pull request by markocikos**
### References

- Parent story: [LPD-20584 Use DSM Sorting Tab to store the FDS Sorting Dropdown data](https://issues.liferay.com/browse/LPD-20584)
- This is a followup on https://github.com/liferay-frontend/liferay-portal/pull/4085

### What is the goal of this PR?

Some minor improvements, fixes and polishing.

Changes from previous version are in added commits:
- fixes: import, FF logic, doing tests on new UI
- improvements: avoiding flakiness, by assuring loading indicator is no longer present. Not bulletproof, but should help.
- some minor nits like tags and grouping of pages in a dir

image

There is no need for additional peer review on this PR.

:warning: After this PR, story will still not be complete. What is missing is test on fragment. I'm having difficulties with all fragment tests locally, so I decided to first push everything except it.

### CODE REVIEW

**Comment by markocikos** [comment]
ci:test:sf

**Comment by markocikos** [comment]
ci:test:playwright

**Comment by markocikos** [comment]
ci:test:relevant

**Comment by markocikos** [comment]
ci:test:playwright

**Comment by markocikos** [comment]
ci:test:sf

**Comment by markocikos** [comment]
ci:test:playwright

**Comment by markocikos** [comment]
ci:forward

**Comment by markocikos** [comment]
ci:forward

**Comment by markocikos** [comment]
ci:report:2562195200

**Comment by markocikos** [comment]
No unique failures, based on https://github.com/liferay-frontend/liferay-portal/pull/4140#issuecomment-2067223818
No related PW failures, based on https://github.com/liferay-frontend/liferay-portal/pull/4140#issuecomment-2066439580

**Comment by thektan** [comment]
Thanks for these additional changes @markocikos! 🙇‍♂️

**Pull request closed without merging**
