### PR TITLE
[TS] LPS-177032 Protobuf Vulnerability Detected in closure-compiler v20180204

### PR DESCRIPTION
**Pull request by mbowerman**
Notes from @javalosjr96:

> Previous PR:
> https://github.com/mbowerman/liferay-portal/pull/144
> 
> Ticket:
> [LPS-177032](https://issues.liferay.com/browse/LPS-177032)
> Issue:
> There is a protobuf component within this library that is being flagged by a customers third-party scanner(Dynatrace).
> 
> Solution:
> Update closure-compiler to v20220601 as protobuf no longer is in the library.
> 
> Notes:
> Initially the solution was to update to the latest version, however due to library being deprecated for Java 8(only available on Java 11) we could not update it to the latest version. v20220601 is the latest Java 8 version, but also does NOT contain protobuf which should cover this vulnerability.
> 
> 
> Additional Notes:
> Some errors were present in 7.3.x that do not occur in 7.4.
> The failing test in the previous PR also fails in the latest master.

### CODE REVIEW

**Comment by javalosjr96** [comment]
I have some questions for the reviewer.

I backported this fix to 7.3.x and while the portal was functional, there was a new error that kept being displayed when you attempt to add a new site.

`(/o/js/resolved-module/frontend-taglib-clay$clay-radio@2.24.1/lib/ClayRadio.soy.js:62): Closure primitive methods (goog.provide, goog.require, goog.define, etc) must be called at file scope. [JSC_INVALID_CLOSURE_CALL_ERROR]`

Which is caused when compiling a front end component:
```
    var templates;
    goog.loadModule(function (exports) {
      var soy = goog.require('soy');

      goog.require('soydata');

      // This file was automatically generated from ClayDropdownLabel.soy.
      // Please don't edit this file by hand.

      /**
       * @fileoverview Templates in namespace ClayDropdownLabel.
       * @public
       */

      goog.module('ClayDropdownLabel.incrementaldom');

      goog.require('goog.soy.data.SanitizedContent');
      goog.require('soy.asserts');
      var soyIdom = goog.require('soy.idom');
```
The exact cause is because the goog.require is created as a global variable, which is not encouraged.  

I suppressed this error in my 7.3 instance by adding the ERROR to the list of ignorableErrors:

```
	private static final Set<String> _ignoredErrors = new HashSet<>(
		Arrays.asList(
			"JSC_BAD_JSDOC_ANNOTATION", "JSC_DUPLICATE_OBJECT_KEY",
			"JSC_GOOG_MODULE_IN_NON_MODULE", "JSC_INVALID_PARAM",
			"JSC_JSDOC_IN_BLOCK_COMMENT", "JSC_JSDOC_MISSING_BRACES_WARNING",
			"JSC_MISPLACED_ANNOTATION","JSC_INVALID_CLOSURE_CALL_ERROR"));
```

Is this the correct method of resolving this?

**Comment by mateusralv** [comment]
ci:test:relevant

**Comment by dsanz** [comment]
Hi @javalosjr96 your findings are consistent as we don't have soy components in 7.4. Also, in 7.4 the minification process has been moved to build-time. There is no liferay resource being minified at runtime.

Solution you propose is fine, as long as it passes 7.3 branch tests.

**Comment by javalosjr96** [comment]
@mbowerman 
The failures are related to depot, so unrelated.  

@dsanz 
Thanks for your input!

**Comment by mateusralv** [comment]
Hi guys, I had a look and the failures are not related. 

[testray comparison](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1678487783374&testrayRunIdA=2225028894&testrayRunIdB=2226661724)

**Comment by javalosjr96** [comment]
ci:test:sf

**Comment by javalosjr96** [comment]
ci:forward

**Comment by javalosjr96** [comment]
ci:reevaluate:1287401_6020

**Comment by javalosjr96** [comment]
ci:forward:force

**Pull request closed without merging**
