### PR TITLE
LPS-175939 Upgrade AlloyUI version to generate alternative text in thumbnails

### PR DESCRIPTION
**Pull request by antonio-ortega**
Hi guys,

This is just to update AlloyUI version to latest version.

Thanks.

Regards.

### CODE REVIEW

**Comment by antonio-ortega** [comment]
ci:test:relevant

**Comment by deborasoliveira** [comment]
I'll take a look at it 🧐

**Comment by deborasoliveira** [comment]
ci:test:relevant

**Comment by deborasoliveira** [comment]
I'll continue the analysis tomorrow because there's something related to the failures that I need to confirm through the new relevant results.

**Comment by deborasoliveira** [comment]
Hi @antonio-ortega! I've analyzed the failures and they seem to be flaky failures, unrelated to this PR according to the [comparison](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=2&testrayRunIdB=2212700504&testrayRunIdA=2210260587&statusB=3). 

cc: @mateusralv

**Comment by dsanz** [comment]
ci:forward:force

**Comment by dsanz** [comment]
ci:forward:force

**Comment by dsanz** [comment]
ci:forward:force

**Comment by dsanz** [comment]
ci:forward:force

**Comment by dsanz** [comment]
ci:forward:force

**Comment by dsanz** [comment]
ci:forward:force

**Comment by eltonccdantas** [comment]
Hey @antonio-ortega and @dsanz, I see this PR is stuck for a long time, is there anything I can do for helping from a QA perspective?

**Comment by markocikos** [comment]
Closing, higher version is already merged.

**Pull request closed without merging**
