### PR TITLE
LPS-152229 Replace and deprecate `listSelect` with new `getSelectedOptionValues` utility

### PR DESCRIPTION
**Pull request by kresimir-coko**
## Overview

`listSelect` is a utility that accepts a `<select>` element, and an optional `delimiter` argument. It returns a CSV string consisting of values of `<option>` elements that are children of the `<select>` element.

I've decided to rename this utility as it doesn't do what the name `listSelect` suggests but instead it gets the selected options inside the provided select element. 

🧪 This util can be tested by dragging the `Documents & Media` portlet onto the landing page and going to its Configuration. Once there, click Save and the util will be invoked.

### CODE REVIEW

**Comment by kresimir-coko** [comment]
ci:test:relevant

**Comment by kresimir-coko** [comment]
ci:test:relevant

**Review by bryceosterhaus — APPROVED** [review]

**Comment by diegonvs** [comment]
ci:test:relevant

**Comment by kresimir-coko** [comment]
ci:reevaluate:1267401_2983

**Comment by kresimir-coko** [comment]
Hey @magjed4289 I can't figure out where exactly this is failing. Looking at this [report](https://testray.liferay.com/reports/production/logs/2022-05/test-1-26/test-portal-acceptance-pullrequest(master)/2983/functional-tomcat90-mysql57-jdk8/4/12/LocalFile.DMWidget_CanRemoveCurrentDisplayStyleViews/summary.html.gz) I can see its somewhere around Documents & Media, but I can't find the `Any` button mentioned.

**Comment by magjed4289** [comment]
Just started reviewing :)

**Comment by kresimir-coko** [comment]
I think I found the culprit. In this specific case, returning nothing (instead of an empty string) was causing the issue where the form would get successfully submitted when it wasn't supposed to.

I've pushed a commit that removes that check/return.

**Comment by kresimir-coko** [comment]
ci:test:sf

**Comment by kresimir-coko** [comment]
ci:test:relevant

**Comment by magjed4289** [comment]
ci:test:acceptance:functional

**Comment by kresimir-coko** [comment]
ci:reevaluate:1257401_2766

**Comment by kresimir-coko** [comment]
ci:test:acceptance:functional

**Comment by kresimir-coko** [comment]
@magjed4289 
> The CI test suite 'functional' is not a valid test suite.

**Comment by kresimir-coko** [comment]
ci:forward

**Pull request closed without merging**
