### PR TITLE
[TS] LPS-148762 Remove buildNumber from the static resources URLs, timestamp should be enough to invalidate browser's cache in a upgrade of version

### PR DESCRIPTION
**Pull request by jcampoy**
https://issues.liferay.com/browse/LPS-148762

buildNumber was introduced in https://issues.liferay.com/browse/LPS-13514 to control the browser cache in a upgrade, but having the timestamp it should not be necessary the buildNumber and also it is a security weakness that users are reporting

### CODE REVIEW

**Comment by jcampoy** [comment]
ci:test:relevant

**Comment by jcampoy** [comment]
ci:test:sf

**Comment by jcampoy** [comment]
ci:test:sf

**Comment by istvansajtos** [comment]
Thanks for working on this @jcampoy ! I've found one more reference to "b" parameter, could you please remove it as well?
https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portal/servlet/ComboServlet.java#L535

**Comment by izaera** [comment]
LGTM

**Comment by jcampoy** [comment]
> Thanks for working on this @jcampoy ! I've found one more reference to "b" parameter, could you please remove it as well? https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portal/servlet/ComboServlet.java#L535

Done!

**Comment by jcampoy** [comment]
ci:test:sf

**Comment by jcampoy** [comment]
ci:test:relevant

**Comment by jcampoy** [comment]
good morning @izaera , could we move forward with this change?

Best regards

**Comment by izaera** [comment]
@jcampoy Of course, I gave the LGTM long ago :-) (https://github.com/liferay-frontend/liferay-portal/pull/1985#issuecomment-1061515411)

Once it's approved anyone can forward it to Brian...

**Comment by izaera** [comment]
ci:forward

**Pull request closed without merging**
