### PR TITLE
LPS-130722 Using rowId as part of id HTML attribute for every row in search container

### PR DESCRIPTION
**Pull request by antonio-ortega**
Hi guys,

This is a new clean pull request for liferay-frontend#975 where I'm trying to follow your suggestions:

- We are only adding the id in case rowIdProperty has been informed.
- Such id is including portlet:namespace, searchContainerId and rowId.
- Such id is a valid id HTML value.

Let me know if you need anything else.

Thanks.

Regards.

### CODE REVIEW

**Comment by wincent** [comment]
- `LocalFile.WorkflowMetrics#ViewReports` is unrelated (seeing it [over here too](https://github.com/liferay-lima/liferay-portal/pull/1757)). 
- `LocalFile.PortalSmoke#Smoke` seems unreliable ("no such session")

Given that we don't want to risk any regressions, I think we should wait until the GA is out, but the change does look superficially correct (without understanding the details of where we set the `id` variable in the JSP context etc).

In the meantime, going to re-run tests to see if I fluke a green run.

**Comment by wincent** [comment]
ci:test:relevant

**Comment by wincent** [comment]
Ok, so only failure was that spurious `LocalFile.WorkflowMetrics#ViewReports` thing. I think we can manually forward this (and avoid a whole new CI run), so I'm going to.

**Comment by wincent** [comment]
Manual forward here: https://github.com/brianchandotcom/liferay-portal/pull/101142

**Comment by wincent** [comment]
Re-opening due to feedback: https://github.com/brianchandotcom/liferay-portal/pull/101142#issuecomment-827609708

> @antonio-ortega
>
> ```
> request.setAttribute("rowIdProperty", rowId)
> ```
>
> If you do that, you need to prefix it or use a WebKey*
> 
> Type
> 
> git grep "equest.setAttribute("" **.java
> 
> @wincent fyi

**Comment by antonio-ortega** [comment]
Rebased and resent #1006

**Pull request closed without merging**
