### PR TITLE
LPS-188569 - Add checkFormat script for checking SF in workspaces directory

### PR DESCRIPTION
**Pull request by bryceosterhaus**
https://liferay.atlassian.net/browse/LPS-188569

Context: https://liferay.slack.com/archives/C1SJ64S9X/p1687501019250309

### CODE REVIEW

**Comment by bryceosterhaus** [comment]
This first SF test should fail...

**Comment by bryceosterhaus** [comment]
pushing now without the SF failing commit

**Comment by bryceosterhaus** [comment]
ci:test:sf

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by mateusralv** [comment]
I'm taking a look 🕵🏽

**Comment by mateusralv** [comment]
Hey @bryceosterhaus The failures are not unique and are not related 😄 

[Testray Comparison](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1687524660970&testrayRunIdA=2359554513&testrayRunIdB=2359604454)

**Comment by bryceosterhaus** [comment]
ci:forward:force

**Comment by bryceosterhaus** [comment]
Manual forward https://github.com/brianchandotcom/liferay-portal/pull/136839

If any changes are needed from review I will send in follow up PR

**Pull request closed without merging**
