### PR TITLE
LPS-198796 Test Fix: ClientExtension#ErrorAppearsWhenHTMLBlank

### PR DESCRIPTION
**Pull request by mateusralv**
**Description:**
Fix for the tests: 
ClientExtension#ErrorAppearsWhenHTMLBlank
DataSet#AssertTheNewFieldTranslation -> DataSetViewFields#AssertTheNewFieldTranslation (this test is related to view fields) 

**Jira Ticket:**
https://liferay.atlassian.net/browse/LPS-202751
https://liferay.atlassian.net/browse/LPS-198796

### CODE REVIEW

**Comment by mateusralv** [comment]
ci:test:sf

**Comment by mateusralv** [comment]
ci:test:frontend

**Review by CarlosBrichete — APPROVED** [review]
LGTM :) But maybe you will have to wait for this PR to be merged so you can rebase the changes https://github.com/liferay-frontend/liferay-portal/pull/3869

**Comment by JerryAdrianoo** [comment]
ci:forward

**Pull request closed without merging**
