### PR TITLE
LPS-124473 Info Panels should have white background

### PR DESCRIPTION
**Pull request by pat270**
https://issues.liferay.com/browse/LPS-124473
fixes:
- Info Panel Subscribe Button text intended for screen readers is causing horizontal overflow
- Info Panel has transparent background in documents and media
- Info Panel has transparent background in Applications > App Builder > Apps > Workflow Powered and try to create a new app (or choose one that already exists)

The remove compat sidebar pr made info panels transparent. Not sure why we need transparent info panels at screen sizes sm and up, but I'm guessing it might be related to the gap between management-bar, info-panel, and bottom of page.

### CODE REVIEW

**Comment by pat270** [comment]
ci:test:sf

**Comment by pat270** [comment]
ci:test:relevant

**Comment by john-co** [comment]
Reviewed. Test failures are unrelated. :heavy_check_mark: 

cc/ @vicnate5 flaky upgrade test occurence

**Comment by john-co** [comment]
Rerunning test would hopefully pass. But can manually forward if encounter more test flakiness.

**Comment by john-co** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
@john-co We added re-run to the upgrade test, it failed twice in a row for the same reason :( will look into this

**Comment by jbalsas** [comment]
ci:forward

**Pull request closed without merging**
