### PR TITLE
LPD-30822 Fix accessibility in Cookie Banner

### PR DESCRIPTION
**Pull request by fortunatomaldonado**
https://liferay.atlassian.net/browse/LPD-30822
https://liferay.atlassian.net/browse/LPP-54586

This fixes accessibility in cookie banner.
The fix was suggested here by Marcos Castro: https://liferay.atlassian.net/browse/PTR-5088?focusedCommentId=2679072

Please let me know if there are any questions or comments about this.
Thank you!

### CODE REVIEW

**Comment by fortunatomaldonado** [comment]
ci:test:sf

**Comment by fortunatomaldonado** [comment]
ci:test:relevant

**Comment by chestofwonders** [comment]
As far as I see, looks good, but I not sure how to give my approval without being in reviewer's list

**Comment by fortunatomaldonado** [comment]
ci:forward

**Pull request closed without merging**
