### PR TITLE
LPS-143363 - Add TS support for global liferay object

### PR DESCRIPTION
**Pull request by bryceosterhaus**
https://issues.liferay.com/browse/LPS-143363

This introduces greater TS support for our global Liferay object.

We also provided a mechanism for contributing global types in liferay-portal. All you need to do is create *.d.ts file in your src and then reference that file in our root `global.d.ts` file via triple-slash reference.

### CODE REVIEW

**Comment by julien** [comment]
@kresimir-coko once this gets merged, I'd like you to give us a "talk" about how this migration from JS to TS went, and how you feel about it :)

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by kresimir-coko** [comment]
> @kresimir-coko once this gets merged, I'd like you to give us a "talk" about how this migration from JS to TS went, and how you feel about it :)

@julien I'll start writing up a Confluence article if I can still remember everything 👍

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
ci:test:sf

**Comment by susanchen3** [comment]
Failures look unrelated. :+1: Ok to manually forward from QA :D

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
ci:test:sf

**Comment by john-co** [comment]
ci:test:upstream-acceptance

**Comment by john-co** [comment]
ci:test:acceptance-functional

**Comment by john-co** [comment]
Reviewed. Test failures are unrelated for both relevant and acceptance-functional test suites. :heavy_check_mark: 
May manually forward from QA perspective.

**Comment by bryceosterhaus** [comment]
Manual forward: https://github.com/brianchandotcom/liferay-portal/pull/112878

**Pull request closed without merging**
