### PR TITLE
LPS-156538 Update packages `@clayui/*` to v3.63.0

### PR DESCRIPTION
**Pull request by matuzalemsteles**
### Bug Fixes

-   **@clayui/css:** fix syntax error in conditional declaration ([3d19936](https://github.com/liferay/clay/commit/3d199365de3eed8decf2b48301abbde89dc308a9))
-   **@clayui/css:** Grid compare the breakpoint positions instead of the `$cadmin-container-max-widths` values ([1e0782c](https://github.com/liferay/clay/commit/1e0782c475aea4b837d1dea952fcb1026889934b))
-   **@clayui/css:** Grid compare the breakpoint positions instead of the `$container-max-widths` values ([89aaeee](https://github.com/liferay/clay/commit/89aaeee54c42b2a4a4236cafa3fa83e47941b164))
-   **@clayui/css:** Loaders and Cadmin Loaders don't generate placeholders for `$loading-animation-palette` ([d762f00](https://github.com/liferay/clay/commit/d762f0064fb46b7b43b0adc308b92002ddf470f4))

### Features

-   **@clayui/css:** SVG Icons adds no-bot.svg ([94b69f0](https://github.com/liferay/clay/commit/94b69f0d46c330a2a078bdb17e04020fcab3d737))

### CODE REVIEW

**Comment by matuzalemsteles** [comment]
ci:stop

**Comment by susanchen3** [comment]
Taking a look! :detective:

**Comment by susanchen3** [comment]
The radio button looks slighty misaligned on the Clay Sample portlet 

**This PR:** 
image

**Master:**
image

**Comment by matuzalemsteles** [comment]
@susanchen3 Oh, I'll check maybe it could be some DXP CSS generating some conflict. Apparently Chromatic didn't catch this and also doesn't seem to reproduce it in https://storybook.clayui.com/?path=/story/design-system-components-radio--default.

**Comment by susanchen3** [comment]
Thanks! Other than that, the test failures look unrelated :heavy_check_mark: I can manually forward when ready and fix the rebase conflicts :)

[**Comparison run:**](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=2&testrayRunIdB=1890306930&testrayRunIdA=1890661549&statusB=3) 
- LocalFile.DMPermissions#DeleteDMFolderRegRoleInline: Passes locally
- LocalFile.FormsColorField#PredefinedValueCanBeAdded: Flaky, passes locally
- LocalFile.PortalSmokeUpgrade#ViewPortalSmokeArchive70106: Possible fluke

**Comment by susanchen3** [comment]
hmmm... I am able to reproduce this on my master, but I asked someone else to check and they are unable to reproduce it. Maybe it is just something on my end. What do you think? @matuzalemsteles

**Comment by matuzalemsteles** [comment]
@susanchen3 I'm going to do an ant all again here and check if this happens on my machine too.

**Comment by matuzalemsteles** [comment]
Hey @susanchen3 I can't reproduce this on my machine, for me it's showing aligned.

Screen Shot 2022-06-28 at 5 32 58 PM

**Comment by susanchen3** [comment]
yeah I think its just an issue on my end :disappointed: So I think the PR looks good :green_circle: I will manually forward now :rocket:

**Comment by susanchen3** [comment]
manually forwarded to bchan: https://github.com/brianchandotcom/liferay-portal/pull/119551

Thanks!

**Pull request closed without merging**
