### PR TITLE
LPS-124744 [Content Performance] Change PieChart size

### PR DESCRIPTION
**Pull request by dgarciasarai**
**Description**

The PieChart size is too small to interact with.

**Solution**

Make the PieChart bigger.

### CODE REVIEW

**Comment by dgarciasarai** [comment]
Any feedback here? Or we are ready to go? 😄

**Comment by julien** [comment]
@dgarciasarai I don't see anything strange concerning the code changes.
Is there any way to test this?

**Comment by julien** [comment]
Hey @dgarciasarai, 

After trying to figure out how to use the content dashboard for about 30 minutes, I still have no idea of how I can test this, so as far as I'm concerned I'd say that I can't review this pull request entirely:  if you can add a test plan, that would make it easier. However, I can confirm that these changes don't look dangerous.

There are just two things I wanted to discuss with you:

Why is this component called [`EmptyPieChart`](https://github.com/liferay-frontend/liferay-portal/blob/fa8d41aab03b42e29b3767e6acf7b0c1177e5f34/modules/dxp/apps/analytics/analytics-reports-web/src/main/resources/META-INF/resources/js/components/EmptyPieChart.js)?
Using `Empty` for the name suggests that this chart will be empty, and made me wonder why (and how) you'd  display  an "empty" chart ... I find it slightly confusing (that's not a blocker, I'm just curious)

[Here](https://github.com/liferay-frontend/liferay-portal/blob/fa8d41aab03b42e29b3767e6acf7b0c1177e5f34/modules/dxp/apps/analytics/analytics-reports-web/src/main/resources/META-INF/resources/js/components/EmptyPieChart.js#L45), `proptypes` should be `propTypes` (note the capital `T`)

**Comment by wincent** [comment]
> [Here](https://github.com/liferay-frontend/liferay-portal/blob/fa8d41aab03b42e29b3767e6acf7b0c1177e5f34/modules/dxp/apps/analytics/analytics-reports-web/src/main/resources/META-INF/resources/js/components/EmptyPieChart.js#L45), `proptypes` should be `propTypes` (note the capital `T`)

[What a catch!](https://www.youtube.com/watch?v=iZ4tEDj20oE)

**Comment by dgarciasarai** [comment]
Hey @julien, thank you so much for your feedback.

These changes are for the PieChart in the Content Performance panel (a connection with Analytics Cloud is required). I think that's the reason you didn't find it (also because you were looking in the Content Dashboard 😛 ).

> Using Empty for the name suggests that this chart will be empty, and made me wonder why (and how) you'd display an "empty" chart ... I find it slightly confusing (that's not a blocker, I'm just curious)

The EmptyPieChart is used when the content was published today and there is no data yet, or there was an error with some traffic sources endpoints, it's like a PieChart "placeholder".

> Here, proptypes should be propTypes (note the capital T)

I'm going to fix that and i'll update the pull request. I think with that is not dangerous to forward these changes because it's an attribute's rename and change the size of the PieChart.

Thanks!

**Comment by dgarciasarai** [comment]
ci:test:sf

**Comment by julien** [comment]
Hey @dgarciasarai no problem, reviewing PRs is always interesting

> These changes are for the PieChart in the Content Performance panel (a connection with Analytics Cloud is required). I think that's the reason you didn't find it (also because you were looking in the Content Dashboard stuck_out_tongue ).

Yes, that's the reason haha. You once helped me with to get the Analytics Cloud connection properly configured but I already forgot, and wasn't able to find it anywhere (searching in Slack isn't the best feature).  Given the (small) changes I don't think it's a big deal.

> The EmptyPieChart is used when the content was published today and there is no data yet, or there was an error with some traffic sources endpoints, it's like a PieChart "placeholder".

Got it, and now it makes sense: I know that naming things is hard and `EmptyPieChart` for a placeholder doesn't seem that "strange" so I don't have any "objection" :smile: 

Concerning the rest, I agree with you, as long as fix that tiny typo, this should be good to forward

**Comment by dgarciasarai** [comment]
@julien "tiny" typo 😬 05305c5 and also props was complaining in the tests so I fix it too 44c2548.

**Comment by dgarciasarai** [comment]
ci:test:relevant

**Comment by julien** [comment]
@dgarciasarai the error doesn't seem related with your changes.
 I know @john-co would be able to confirm (when he gets a chance), and in that case I can forward this.

**Comment by dgarciasarai** [comment]
@julien thanks! Should we restart the CI? 🤔

**Comment by dgarciasarai** [comment]
ci:forward

**Comment by julien** [comment]
Sorry @dgarciasarai I was busy and couldn't reply fast enough :-)
Good move on forwarding the PR

**Comment by john-co** [comment]
Agree, looks unrelated.

cc/ @vicnate5 another lpkg base test suite issue. Seems different from the other one yesterday. Not sure if fluke or there's something with gradle memory that needs to be addressed for this.

**Comment by julien** [comment]
Thanks @john-co :+1:

**Comment by john-co** [comment]
[Unrelated]
- Segmentation test failure looks like a fluke
- lpkg base error is recently failing in upstream with the same error: https://testray.liferay.com/home/-/testray/case_results/1529548026

**Comment by dgarciasarai** [comment]
ci:reevaluate:1017401_6611

**Comment by dgarciasarai** [comment]
ci:forward

**Comment by dgarciasarai** [comment]
@carlosbrichete, we have a Segmentation flaky test. See https://github.com/liferay-frontend/liferay-portal/pull/1004#issuecomment-829658505. Can you take a look? Thanks

**Comment by dgarciasarai** [comment]
ci:forward

**Comment by CarlosBrichete** [comment]
ci:forward

**Comment by CarlosBrichete** [comment]
> The SegmentationCreateSegment#SegmentationCheckMembers has failed in the past 3 runs and I don't see the same issue in [other recent test runs](https://testray.liferay.com/home/-/testray/cases/1479686740) so it's making me think that it's related and not a fluke/flaky given this new data...
> 
> @CarlosBrichete, could you investigate further?

I've executed this test in local in master and it failed one time and then it is passing all the runs... It's weird because this test does not fail in CI...

**Comment by CarlosBrichete** [comment]
ci:test:tango

**Pull request closed without merging**
