### PR TITLE
LPS-129247 Update PagesTreeEventHandler to avoid extending from metal-component

### PR DESCRIPTION
**Pull request by kresimir-coko**
Fixes [LPS-129247](https://issues.liferay.com/browse/LPS-129247).

I have renamed `attached` to `constructor` to keep the initial event listener and because, well, `attached` is a `metal-component` specific method. Also renamed `disposed` to `dispose` because `disposed` is `metal-component` specific.

I've tested this component to make sure it functions as it did before this PR.

You can test it yourself by opening the `Page Tree` in the left sidebar and clicking on any of the ellipsis buttons.

### CODE REVIEW

**Comment by jbalsas** [comment]
Hey @kresimir-coko, I think this should do the trick, but it could also benefit from removing the `metal-state` dependency in the `package.json` file in this module.

Additionally... if you check [pages_tree.jsp](https://github.com/liferay/liferay-portal/blob/master/modules/apps/product-navigation/product-navigation-product-menu-web/src/main/resources/META-INF/resources/portlet/pages_tree.jsp#L171-L179), this shows the only usage for both this component and [PagesTree](https://github.com/liferay/liferay-portal/blob/master/modules/apps/product-navigation/product-navigation-product-menu-web/src/main/resources/META-INF/resources/js/PagesTree.es.js) which also appears to be a simple event handle... maybe this could be merged into the other one?

We should at least clean up `package.json` and then either do the other or send to team echo for them to decide.

**Comment by kresimir-coko** [comment]
@jbalsas I've done some extensive testing on this and concluded that [PagesTreeEventHandler.es.js](https://github.com/liferay/liferay-portal/blob/master/modules/apps/product-navigation/product-navigation-product-menu-web/src/main/resources/META-INF/resources/js/PagesTreeEventHandler.es.js) is obsolete. Here's why:
- It's purpose is to call `Liferay.DropdownProvider.hide();` when you click outside of the dropdown menu,
- But, if the condition (defined in `PagesTreeEventHandler.es.js`) is met, the `hide` method is being called twice `PagesTreeEventHandler.es.js`, so
- I removed the `PagesTreeEventHandler.es.js` class entirely and it resulted in `hide` being called once, and the functionality being preserved as it was before the change

I've done all my testing in this sidebar:
image

**Comment by wincent** [comment]
> I've done some extensive testing on this and concluded that [etc...]

Info like this is valuable and probably belongs in the commit message (instead of what you currently have, which is just "Remove PagesTreeEventHandler class and its usage"). The sad reality is that somebody looking at the repo in the future is not going to look up "LPS-129247" on Brian's fork, then traverse the back-link to this PR in order to find this explanation. If you put it in the commit message, it is only a short `git blame` or `git log` away. No need to force-push this and update it this time, but it's something to bear in mind for next time.

**Comment by jbalsas** [comment]
Sounds reasonable! 

I think we can send this directly to @liferay-echo adding all this info (both in the commit and in the PR description) so they can verify and push it forward 👍

**Comment by kresimir-coko** [comment]
> @jbalsas I think we can send this directly to @liferay-echo

Sure, I'll forward it to Eudaldo, right?

**Comment by jbalsas** [comment]
> Sure, I'll forward it to Eudaldo, right?

To @liferay-echo

**Pull request closed without merging**
