### PR TITLE
COMMERCE-4699 headless actions fixed on data set display

### PR DESCRIPTION
**Pull request by FabioDiegoMastrorilli**
This PR fixes a typo, updates the action param keys in the dataset (props included) to align them to the server side and fixes a url formatting issue when there was only one action per item.

### CODE REVIEW

**Comment by FabioDiegoMastrorilli** [comment]
ci:test:sf

**Review by brunobasto — APPROVED** [review]
LGTM

**Comment by brunobasto** [comment]
ci:test:relevant

**Comment by brunobasto** [comment]
ci:forward

**Pull request closed without merging**
