### PR TITLE
LPS-187259 Avoid introducing dates with more than 4 digits

### PR DESCRIPTION
**Pull request by antonio-ortega**

### CODE REVIEW

**Comment by antonio-ortega** [comment]
ci:test:sf

**Comment by antonio-ortega** [comment]
ci:test:relevant

**Review by bryceosterhaus — APPROVED** [review]
LGTM!

**Comment by antonio-ortega** [comment]
Yep, if you debug it you can see that `%Y` is basically accepting any year within the range admitted by Javascript's Date object, so you can introduce whichever year until 275760.

**Comment by mateusralv** [comment]
Hi @antonio-ortega The failures are not related to your PR, safe to forward. 

[Testray Comparison](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1686660440987&testrayRunIdA=2347769989&testrayRunIdB=2347929862)

**Comment by antonio-ortega** [comment]
ci:forward:force

**Comment by antonio-ortega** [comment]
ci:forward:force

**Comment by antonio-ortega** [comment]
ci:forward:force

**Comment by antonio-ortega** [comment]
ci:forward:force

**Comment by antonio-ortega** [comment]
ci:forward:force

**Comment by markocikos** [comment]
Manual forward: https://github.com/brianchandotcom/liferay-portal/pull/136440

**Pull request closed without merging**
