### PR TITLE
LPS-125559 Update liferay-ckeditor to v4.14.1-liferay.15

### PR DESCRIPTION
**Pull request by julien**
[Release notes](https://github.com/liferay/liferay-ckeditor/releases/tag/v4.14.1-liferay.15)

### CODE REVIEW

**Comment by julien** [comment]
The CI error doesn't look related to this change.

**Comment by julien** [comment]
ci:test:relevant

**Review by carloslancha — APPROVED** [review]
lgtm!

**Comment by jbalsas** [comment]
@carloslancha, please forward if you already reviewed so PRs don't get stuck in review limbo! ;)

**Comment by jbalsas** [comment]
@julien, I wouldn't mind if next time we expand the Release Notes into the description itself so it's easier to have a sense of what we're forwarding here! ;)

**Comment by jbalsas** [comment]
ci:forward

**Comment by julien** [comment]
> @julien, I wouldn't mind if next time we expand the Release Notes into the description itself so it's easier to have a sense of what we're forwarding here! ;)

Of course, I'll remember to do that next time :+1:

**Pull request closed without merging**
