### PR TITLE
LPS-136282 Add missing translation to frontend-theme-classic-style-guide-sample-web

### PR DESCRIPTION
**Pull request by edalgrin**
This PR fixes a minor visual bug on the text-muted of the frontend-theme-classic-style-guide-sample-web widget and adds the buttons sample

image

### CODE REVIEW

**Comment by marcoscv-work** [comment]
LGTM!

**Comment by edalgrin** [comment]
Just started reviewing :)

**Comment by nhpatt** [comment]
ci:forward

**Review by nhpatt — APPROVED** [review]
LGTM :D

**Pull request closed without merging**
