### PR TITLE
[LPS-118213, LPS-118284] Set CKEditor by default for DDM_HTML fields and provide better default presets

### PR DESCRIPTION
**Pull request by jbalsas**
This PR includes:

#### [Provide default CKEditor presets](https://issues.liferay.com/browse/LPS-118213)

This makes it so our default CKEditor preset configurations match Lexicon recommendations based on the analysis of existing and used features. It reduces the different variants in presets to a manageable and well defined set that we can further built upon to provide an easier system to configure editors

#### [Migrate Legacy DDM text editor to CKEditor](https://issues.liferay.com/browse/LPS-118284)

See [Proposal for Web Content Migration to CKEditor](https://docs.google.com/document/d/1VKtDrRnm2Iq3GjubSYsabGl4pJDGD3U0j1WRnfZAKNs) for prior analysis on the feasibility and impact of this change.

This basically means that default `Web Content` and other DDM structures with HTML fields will now be edited via CKEditor instead of AlloyEditor. Presets were defined based on usage so there should be no loss of functionality with this change.

Some pending work to complete the migration is reflected in other ongoing issues that are not included here:
- [Provide an improved Source plugin to CKEditor instances](https://issues.liferay.com/browse/LPS-118290)
- [Apply Lexicon visual definition to CKEditor dialogs](https://issues.liferay.com/browse/LPS-118292)
- [Allow "Browse Server" for links and images in CKEditor](https://issues.liferay.com/browse/LPS-119207)

To reproduce, mainly go to `Content & Data > Web Content` and create a new `Basic Web Content`.
Screen Shot 2020-08-17 at 17 13 57

/cc @liferay-echo, in case you get a chance to look at this... I will reach out to Tarik tomorrow, not sure if he's still on PTO but I'm assuming we have approval prior to this both from himself and @JorgeFerrer

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:test:sf

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
@brunobasto, could you reach out to DDM to inform them of this upcoming change in case they have any doubts about it?

**Comment by jbalsas** [comment]
Hey @john-co, these also feel like test fixes... could you please take a look? I'll push the SF changes once the rest is clear, so no need to worry about that one.

**Comment by john-co** [comment]
ci:test:bundle

**Comment by jbalsas** [comment]
ci:test:sf

**Comment by john-co** [comment]
ci:test:bundle

**Comment by john-co** [comment]
cc/ @zhangyan0701 could you please look into this? Looks like we just need to replace alloyeditor to ckeditor macros.

**Comment by zhangyan0701** [comment]
Send the Test Fix to @jbalsas .
https://github.com/jbalsas/liferay-portal/pull/2228

Update tests to use CKEditor locator.

**Comment by jbalsas** [comment]
ci:test:sf

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
Tests look good.. putting `On Hold` until we get proper approval from teams.

**Comment by brunobasto** [comment]
> @brunobasto, could you reach out to DDM to inform them of this upcoming change in case they have any doubts about it?

Sorry, I must have missed that yesterday. Contacting them now..

**Comment by alexcandidos** [comment]
Just started reviewing :)

**Comment by alexcandidos** [comment]
Hi guys, I was just managed to take a look now, I'm sorry for the delay. From a quick look in the CKEditor via the HTML field added to a Data Definition and explored when adding a DDL entry, it seems to be okay.

Below is a screenshot containing what I played around:
image



cc: @brunobasto @jeyvison @john-co

**Comment by jeyvison** [comment]
Thanks @alexcandidos  =D

It's a green light from our side @jbalsas  :)

**Comment by jbalsas** [comment]
Thanks @alexcandidos, @jeyvison! 

We also got offline approval from @liferay-echo, and since we already reviewed this, going to forward! 🤞

**Comment by jbalsas** [comment]
ci:forward

**Pull request closed without merging**
