### PR TITLE
LPD-27487 Delete DatasetAPI.testcase

### PR DESCRIPTION
**Pull request by dsanz**
In this PR we are:

- deleting `DatasetAPI.testcase` as it's already being covered
- adding a pw test to create a parameterized data set (against blog posting endpoint)
- removing another bunch of redundant poshi tests

Reference: https://liferay.atlassian.net/browse/LPD-27487

### CODE REVIEW

**Comment by dsanz** [comment]
ci:test:playwright

**Comment by dsanz** [comment]
ci:test:playwright

**Comment by dsanz** [comment]
All added PW tests are green....

**Review by juanjofgliferay — APPROVED** [review]
LGTM :fire:

**Comment by dsanz** [comment]
ci:forward

**Pull request closed without merging**
