### PR TITLE
LPS-176046 Removes missing occurrences

### PR DESCRIPTION
**Pull request by ealonso**
Motivation
-----
There's still some bits using the old FF mechanism (Liferay.FeatureFlags['LPS-148659'])). Goal of this task is to remove them so that all DXP code makes use of the Liferay.Util.openAlertModal() function unconditionally

Proposed Solution
-----
Removes FF code as the Liferay.Util.openAlertModal() function is already checking the settings

### CODE REVIEW

**Comment by dsanz** [comment]
LGTM ;)

**Comment by mateusralv** [comment]
I'm taking a look 🕵🏽

**Comment by mateusralv** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by dsanz** [comment]
@mateusralv could you pls take a look and let us know if failures are related?

Thank you

**Comment by ealonso** [comment]
Manual forward: https://github.com/brianchandotcom/liferay-portal/pull/130627

**Pull request closed without merging**
