### PR TITLE
LPS-140854 Change z-index to remove overlap

### PR DESCRIPTION
**Pull request by eli-rlima**
Hi, guys :)

This change is related to an issue with Objects team. You can see in: [LPS-140854](https://issues.liferay.com/browse/LPS-140854). I had a previous discussion about this issue in slack with @matuzalemsteles and @pat270. 

This is a fix to this behavior.

Thanks for your review time!

### CODE REVIEW

**Comment by eli-rlima** [comment]
ci:stop

**Comment by eli-rlima** [comment]
ci:test:sf

**Comment by diegonvs** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
ci:stop

**Comment by guilhermedcamacho** [comment]
ci:reevaluate:1077401_7407

**Review by diegonvs — APPROVED** [review]

**Comment by diegonvs** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
ci:test:relevant

**Comment by carloslancha** [comment]
Hey! I'd like @pat270 or @matuzalemsteles to approve this pr before forwarding since they talked with Eli about the solución. Thx guys!

**Review by matuzalemsteles — APPROVED** [review]
LGTM!

**Comment by carloslancha** [comment]
ci:forward

**Pull request closed without merging**
