### PR TITLE
LPS-122099 Move ARIA information about the landmark to parent nav element so every navigation landmark in the page describes the purpose of the links contained in each

### PR DESCRIPTION
**Pull request by marcoscv-work**
Rebased!

image

### CODE REVIEW

**Comment by marcoscv-work** [comment]
ci:test:sf

**Comment by marcoscv-work** [comment]
ci:test:relevant

**Comment by marcoscv-work** [comment]
I'm not sure if this FAILED is really related to the PR, can someone help us?

**Comment by marcoscv-work** [comment]
ci:test:relevant

**Comment by marcoscv-work** [comment]
ci:forward

**Comment by wincent** [comment]
> I'm not sure if this FAILED is really related to the PR, can someone help us?

If you want help from QA it is best to mention them directly (`@john-co` and `@PablitoBonito`) but if it is CI infra thing, then posting in `#ci` on Slack seems like the best bet.

**Pull request closed without merging**
