### PR TITLE
LPS-168309 baseline

### PR DESCRIPTION
**Pull request by ealonso**
## Motivation

[Link to bug](https://issues.liferay.com/browse/LPS-168309)

Actually we have two taglibs in product called:

* <aui:fieldset-group>
* <liferay-frontend:fieldset-group>

Those taglibs are adding the following logic:

**<aui:fieldset-group>**

```html
<div class="sheet">
	<div aria-multiselectable="true" class="panel-group panel-group-flush" role="tablist">
             {Your logic here}    
        </div>
</div>
```

**<liferay-frontend:fieldset-group>**
```html
<div aria-multiselectable="true">
    {Your logic here}
</div>
```
As you can see in both taglibs we are adding **aria-multiselectable** even if it is not necessary, also for aui taglib we are adding **role="tablist"**

## Proposed Solution

Since we are adding those attributes to all places even if it is not necessary, removes taglib usages for **<liferay-frontend:fieldset-group>** and replace **<aui:fieldset-group>** with custom html in all portal.

```html
<div class="sheet">
	<div class="panel-group panel-group-flush">
             {Your logic here}    
        </div>
</div>
```

In that way if an aria attribute or role is needed we should add it case by case instead of adding it in a common place, since the developers using those taglibs are not aware about it.

Please let me know if you have any question.

### CODE REVIEW

**Review by markocikos — APPROVED** [review]
@ealonso I didn't check each change in the PR, there are way too many. But the explanation in opening comment sounds good to me!

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:sf

**Comment by ealonso** [comment]
ci:test:sf

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by mateusralv** [comment]
Hi @markocikos I'm taking a look 🕵🏽

**Comment by mateusralv** [comment]
Hi @ealonso and @markocikos the failures are not related 🚀 🎉 

[comparison run](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1669660964890&testrayRunIdA=2080608860&testrayRunIdB=2082031071)

### Unique failures, but flake 🟢 
These tests have unique failures in the last run of the relevant but tested locally and are passing.
1. LookAndFeel#ConfigureLookAndFeelOfWidget
2. LocalFile.BlogsEntry#CanSearchByContent

### The others failures are not unique 🟢

**Comment by ealonso** [comment]
see: https://github.com/brianchandotcom/liferay-portal/pull/126961

**Pull request closed without merging**
