### PR TITLE
LPD-26732 - Fix test failure in Frontend Data Set tests due to lack of Sort By creator dropdown option

### PR DESCRIPTION
**Pull request by juanjofgliferay**
## Story / Task
[LPD-26731](https://liferay.atlassian.net/browse/LPD-26731) / [LPD-26732](https://liferay.atlassian.net/browse/LPD-26732)

## Issue
Locator does not find `creator` in the Field options.

## Fix
Replace `creator` by `label`.

- [x] LocalFile.DataSetViewSorting#CanCreateDefaultSort
- [x] LocalFile.DataSetViewSorting#CanDeleteSorting	
- [x] LocalFile.DataSetViewSorting#CanSaveEditSorting	
- [x] LocalFile.DataSetViewSorting#CanCancelDeleteSorting	
- [x] LocalFile.DataSetViewSorting#CanCancelEditSorting	
- [x] LocalFile.DataSetViewSorting#CanSearchSortingInSearchBar	
- [x] LocalFile.DataSetViewSorting#CantEditField	
- [x] LocalFile.DataSetViewSorting#AssertDeleteSortingMessage	
- [x] LocalFile.DataSetViewSorting#AssertEditOptionAppears	
- [x] LocalFile.DataSetViewSorting#AssertEditSortingOptions	
- [ ] LocalFile.DataSetViewSorting#SortingChangesAreAutosaved (fails due to a different reason -> related bug open)

### CODE REVIEW

**Comment by juanjofgliferay** [comment]
ci:test:frontend

**Comment by juanjofgliferay** [comment]
ci:test:sf

**Comment by juanjofgliferay** [comment]
ci:test:sf

**Comment by juanjofgliferay** [comment]
ci:test:frontend

**Comment by dsanz** [comment]
ci:test:stable

**Comment by juanjofgliferay** [comment]
ci:test:frontend

**Review by markocikos — APPROVED** [review]
@juanjofgliferay LGTM! :sparkles:

**Comment by juanjofgliferay** [comment]
ci:test:frontend

**Comment by juanjofgliferay** [comment]
ci:forward

**Pull request closed without merging**
