### PR TITLE
LPS-177101 | Test Fix for ClaySmoke#CanRenderUi

### PR DESCRIPTION
**Pull request by abhnerramos**
**Description**
Check if each nav section of clay sample portlet looks normal from screenshot

**Test Plan**
- Set browser window size
- Change tabs through Clay Sample Portlet and take a screenshot

**JIRA Ticket**
https://issues.liferay.com/browse/LPS-177101

### CODE REVIEW

**Comment by abhnerramos** [comment]
ci:help

**Comment by abhnerramos** [comment]
ci:test:frontend-clay

**Comment by abhnerramos** [comment]
@mateusralv

**Comment by abhnerramos** [comment]
ci:test:sf

**Comment by abhnerramos** [comment]
ci:test:sf

**Comment by abhnerramos** [comment]
ci:test:sf

**Comment by mateusralv** [comment]
ci:test:frontend-clay

**Comment by mateusralv** [comment]
ci:test:frontend-clay

**Review by mateusralv — APPROVED** [review]
God Job!

**Comment by mateusralv** [comment]
ci:forward

**Pull request closed without merging**
