### PR TITLE
[LPS-123964,LPS-124912] Migrate instances of AlloyEditor in Forms

### PR DESCRIPTION
**Pull request by jbalsas**
Ping-ponged from https://github.com/liferay-forms/liferay-portal/pull/83 with explicit acceptance from @natocesarrego:

> I'll close this pull due to the conflicts, but feel free to forward it to Brian.

I've simply rebased and will retest here prior to forwarding to Brian.

> **LPS-123964**
> In [`edit_form_instance.jsp`](https://github.com/liferay/liferay-portal/blob/f1dbd869c1036f3bc6379585b4c2a0293877d389/modules/apps/dynamic-data-mapping/dynamic-data-mapping-form-web/src/main/resources/META-INF/resources/admin/edit_form_instance.jsp), AlloyEditor instances
> have been replaced with `<aui:input />`
> 
> **Test plan**
> 
> * Deploy the `dynamic-data-mapping-form-web` module
> * Navigate to **Content & Data** > **Forms**
> * Create a new form and save it
> 
> **Before**
> LPS-123964-before
> 
> **After**
> LPS-123964-after
> 
> **LPS-124912**
> In [`edit_element_set.jsp`](https://github.com/liferay/liferay-portal/blob/f1dbd869c1036f3bc6379585b4c2a0293877d389/modules/apps/dynamic-data-mapping/dynamic-data-mapping-form-web/src/main/resources/META-INF/resources/admin/edit_element_set.jsp), AlloyEditor instances
> have also been replaced with `<aui:input />`
> 
> **Test plan**
> 
> * Deploy the `dynamic-data-mapping-form-web` module
> * Navigate to **Content & Data** > **Forms**
> * Select the **Element Sets** tab
> * Create a new form and save it
> 
> **Before**
> LPS-124912-before
> 
> **After**
> LPS-124912-after
> 
> **Additional notes**
> Initially reviewed by the @liferay-frontend team [here](https://github.com/liferay-frontend/liferay-portal/pull/624)

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
🤔 

@julien? 😂

**Comment by julien** [comment]
sorry @jbalsas I think I deleted the branch and restored it.
Let me take care of this PR, I'll rebase with `master` and try to get the test to pass

**Comment by julien** [comment]
ci:test:sf

**Comment by julien** [comment]
ci:test:relevant

**Comment by julien** [comment]
ci:forward

**Pull request closed without merging**
