### PR TITLE
[DRAFT] LPS-172771 Implement selection storage with sessionStorage

### PR DESCRIPTION
**Pull request by NemethNorbert**
Hey,

This is the second Draft for [LPS-172771](https://issues.liferay.com/browse/LPS-172771)
Previous Draft: https://github.com/liferay-frontend/liferay-portal/pull/2964
(I went into more details about the implementation and the intent behind it on the previous PR, please check it as it still applies)

Improvements I made:
I moved the selection storing and retrieving logic to search_container_select.js

Notes:
I also looked into wether I could clean the sessionStorage when the user navigates away, by listening on the window 'beforeunload' event. However I was not able to differentiate between the navigations. For example a pagination, a reload or the case where the user indeed navigates away.

Could you offer some help regarding that?

Thanks,

cc/ @markocikos @dsanz

### CODE REVIEW

**Comment by markocikos** [comment]
@NemethNorbert 

>I also looked into wether I could clean the sessionStorage when the user navigates away, by listening on the window 'beforeunload' event. However I was not able to differentiate between the navigations. For example a pagination, a reload or the case where the user indeed navigates away.
Could you offer some help regarding that?

One thing you can do is to check the last focused element:
```js
window.addEventListener('beforeunload', () => {
	if (!document.activeElement.classList.contains('page-link')) {
		// clean storage
	}
});
```

**Comment by NemethNorbert** [comment]
> @NemethNorbert
> 
> > I also looked into wether I could clean the sessionStorage when the user navigates away, by listening on the window 'beforeunload' event. However I was not able to differentiate between the navigations. For example a pagination, a reload or the case where the user indeed navigates away.
> > Could you offer some help regarding that?
> 
> One thing you can do is to check the last focused element:
> 
> ```js
> window.addEventListener('beforeunload', () => {
> 	if (!document.activeElement.classList.contains('page-link')) {
> 		// clean storage
> 	}
> });
> ```
> 
> This would not work in 100% of cases, as events and behaviors can be triggered through code, without focusing. But, it would cover large majority of cases, normal pagination with mouse, keyboard or touch.

It looks like this would not work in case the user is interacting with the managementbar in any way. I wonder how heavily can we rely on css classes to decide wether the user intents to navigate away. 
For example changing the ordering with the navigationBar we will have the 'nav-link' css class to decide, however this is the same with any navigation item on the Product Menu.
In case the user wants to clear a filtering, by clicking on the 'x' icon on the resultBars, the only css class will be 'close'

I decided to start checking wether the active element is within the searchcontainer or managementtoolbar or resultsbar.
I pushed the commit

**Comment by NemethNorbert** [comment]
An additional issue I came across:
 In case the user initiates an action on a single element, meaning the user is using the dropdown on the item itself and selects an action, we don't clear the selection. This is a scenario that needs to be handled

**Comment by NemethNorbert** [comment]
I close this PR as I created a new one with the recent changes

**Pull request closed without merging**
