### PR TITLE
LPS-163589 - Update to latest npm-scripts and fix TS generation

### PR DESCRIPTION
**Pull request by bryceosterhaus**
https://issues.liferay.com/browse/LPS-163589

This PR updates npm-scripts and eslint-plugin to latest versions and fixes how typescript gets generated. This PR also adds some new eslint rules but are disabled for now.

### CODE REVIEW

**Comment by bryceosterhaus** [comment]
ci:test:sf

**Comment by bryceosterhaus** [comment]
ci:test:sf

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by mateusralv** [comment]
I'm taking a look 🕵🏽

**Comment by mateusralv** [comment]
Hi @bryceosterhaus, I made a [comparison with the failures of the master](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1665695907218&testrayRunIdA=2005340474&testrayRunIdB=2005415579) and most are also occurring in the master :D 

The other errors are also not related to your PR, I’m doubting only in one module:

1. [modules-semantic-versioning-jdk8/0/2](https://testray.liferay.com/home/-/testray/case_results/2005424572)
```
 [exec] com.liferay.semantic.versioning.SemanticVersioningTest > testSemanticVersioning[/apps/user-associated-data/user-associated-data-api] FAILED
     [exec]     java.lang.AssertionError:   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec]     = ================================================== ========== ========== ========== ========== ==========
     [exec]     * com.liferay.user.associated.data.exporter          MAJOR      1.1.1      1.1.1      2.0.0      VERSION INCREASE REQUIRED
     [exec]     	>   class      com.liferay.user.associated.data.exporter.DynamicQueryUADExporter
     [exec]     		>   method     toXmlString(com.liferay.portal.kernel.model.BaseModel)
     [exec]     			+   access     abstract
     [exec]     [Baseline Warning] Bundle Version Change Recommended: 7.0.0
     [exec]         at org.junit.Assert.fail(Assert.java:88)
     [exec]         at org.junit.Assert.assertTrue(Assert.java:41)
```
and
```
 [exec] com.liferay.semantic.versioning.SemanticVersioningTest > testSemanticVersioning[/dxp/apps/search-experiences/search-experiences-api] FAILED
     [exec]     java.lang.AssertionError:   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec]     = ================================================== ========== ========== ========== ========== ==========
     [exec]     * com.liferay.search.experiences.exception           MINOR      2.0.0      2.0.0      2.1.0      VERSION INCREASE REQUIRED
     [exec]     	+   class      com.liferay.search.experiences.exception.SXPBlueprintConfigurationJSONException
     [exec]     		+   extends    com.liferay.portal.kernel.exception.PortalException
     [exec]     		+   method     <init>()
     [exec]     			+   return     void
     [exec]     		+   method     <init>(java.lang.String)
     [exec]     			+   return     void
     [exec]     		+   method     <init>(java.lang.String,java.lang.Throwable)
     [exec]     			+   return     void
     [exec]     		+   method     <init>(java.lang.Throwable)
     [exec]     			+   return     void
     [exec]     		+   method     clone()
     [exec]     			+   access     protected
     [exec]     			+   return     java.lang.Object
     [exec]     		+   method     equals(java.lang.Object)
     [exec]     			+   return     boolean
     [exec]     		+   method     finalize()
     [exec]     			+   access     protected
     [exec]     			+   return     void
     [exec]     		+   method     hashCode()
     [exec]     			+   return     int
     [exec]     		+   method     toString()
     [exec]     			+   return     java.lang.String
     [exec]     	+   class      com.liferay.search.experiences.exception.SXPElementElementDefinitionJSONException
     [exec]     		+   extends    com.liferay.portal.kernel.exception.PortalException
     [exec]     		+   method     <init>()
     [exec]     			+   return     void
     [exec]     		+   method     <init>(java.lang.String)
     [exec]     			+   return     void
     [exec]     		+   method     <init>(java.lang.String,java.lang.Throwable)
     [exec]     			+   return     void
     [exec]     		+   method     <init>(java.lang.Throwable)
     [exec]     			+   return     void
     [exec]     		+   method     clone()
     [exec]     			+   access     protected
     [exec]     			+   return     java.lang.Object
     [exec]     		+   method     equals(java.lang.Object)
     [exec]     			+   return     boolean
     [exec]     		+   method     finalize()
     [exec]     			+   access     protected
     [exec]     			+   return     void
     [exec]     		+   method     hashCode()
     [exec]     			+   return     int
     [exec]     		+   method     toString()
     [exec]     			+   return     java.lang.String
     [exec]         at org.junit.Assert.fail(Assert.java:88)
```
It may be a flaky failure, but could you take a look when you have time? 

---
### Failures not unique:

1. com.liferay.headless.commerce.machine.learning.resource.v1_0.test.SkuForecastResourceTest
2. com.liferay.layout.exportimport.service.test.ExportImportLocalServiceTest
3. LocalFile.CPKaleoformsadmin#EditProcessNewWorkflowViaSourceTab
4. com.liferay.oauth2.provider.client.test.ScopeCheckerGuestAllowedTest
5. com.liferay.oauth2.provider.token.endpoint.test.JWTAssertAuthorizationGrantTest

**Comment by bryceosterhaus** [comment]
@mateusralv I believe those are flakey, as I haven't touched anything to do with a semver update for any modules.

I am going to rebase off of latest and run SF. If that passes I will manually forward since there doesn't seem to be unique failrues

**Comment by bryceosterhaus** [comment]
ci:test:sf

**Comment by bryceosterhaus** [comment]
ci:test:sf

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Pull request merged**
