### PR TITLE
LPS-154724 Fix remote-apps repeatable fields style

### PR DESCRIPTION
**Pull request by edalgrin**
This PR fixes the style of the repeatable fields in remote-apps (client-extensions)

localhost_8080_group_guest___control_panel_manage_p_p_id=com_liferay_client_extension_web_internal_portlet_ClientExtensionAdminPortlet p_p_lifecycle=0 p_p_state=maximized p_p_mode=view _com_liferay_client_extension_web_internal_portlet_Clie

### CODE REVIEW

**Comment by susanchen3** [comment]
Reviewed, one related [test failure](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=2&testrayRunIdB=1953490009&testrayRunIdA=1951811446&statusB=3) :heavy_check_mark: I send a test fix for it, if you would like to cherry pick it :) https://github.com/susanchen3/liferay-portal/pull/68

**Comment by susanchen3** [comment]
ci:test:relevant

**Comment by susanchen3** [comment]
Taking a look now! :detective:

**Comment by susanchen3** [comment]
Reviewed, test failures are unrelated :heavy_check_mark: Looks good to manually forward :rocket:

**Comment by edalgrin** [comment]
Ok, thank you @susanchen3 !

**Pull request closed without merging**
