### PR TITLE
LPS-146578 Generate Headless Batch Engine client

### PR DESCRIPTION
**Pull request by javierdearcos**
Add skeleton and REST Builder config to generate REST Builder client for Headless Batch Engine

### CODE REVIEW

**Comment by javierdearcos** [comment]
ci:stop

**Comment by javierdearcos** [comment]
ci:test:sf

**Comment by javierdearcos** [comment]
ci:test:relevant

**Review by LuismiBarcos — APPROVED** [review]
👏 👏 👏

**Comment by LuismiBarcos** [comment]
ci:forward

**Comment by javierdearcos** [comment]
ci:forward

**Comment by LuismiBarcos** [comment]
The CI ignore even [my forwards](https://github.com/liferay-frontend/liferay-portal/pull/1881#issuecomment-1027813613)

**Pull request closed without merging**
