### PR TITLE
LPS-179090 | Test Fix for Cadmin#CanDisplayDefaultTheme

### PR DESCRIPTION
**Pull request by abhnerramos**
**Description**
Text fix for Cadmin#CanDisplayDefaultTheme. Path that was breaking the code was updated.

**JIRA Ticket**
https://issues.liferay.com/browse/LPS-179090

### CODE REVIEW

**Comment by abhnerramos** [comment]
ci:test:frontend

**Comment by abhnerramos** [comment]
@mateusralv could you check this one, please?

**Comment by mateusralv** [comment]
ci:help

**Comment by mateusralv** [comment]
ci:test:acceptance-functional

**Comment by mateusralv** [comment]
Hi @abhnerramos Your fix is broking other tests:

See: [Testray comparison](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=2&testrayRunIdB=2241325039&testrayRunIdA=2241258362&statusB=3)

Could you take a look?

**Comment by abhnerramos** [comment]
ci:test:sf

**Comment by abhnerramos** [comment]
ci:test:relevant

**Comment by mateusralv** [comment]
ci:test:acceptance-upstream

**Comment by mateusralv** [comment]
The failures are not related! 

ci:test:acceptance-upstream: https://github.com/liferay-frontend/liferay-portal/pull/3151#issuecomment-1481786562 🟢 

[Testray comparison](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1679602609991&testrayRunIdA=2242535505&testrayRunIdB=2243187262)

acceptance-upstream: https://github.com/liferay-frontend/liferay-portal/pull/3151#issuecomment-1481770798 🟢 

[Testray comparison](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=2&testrayRunIdB=2243137424&testrayRunIdA=2242535505&statusB=3)

**Comment by mateusralv** [comment]
ci:forward

**Comment by abhnerramos** [comment]
ci:test:sf

**Comment by abhnerramos** [comment]
ci:test:acceptance-functional

**Comment by abhnerramos** [comment]
ci:test:acceptance-upstream

**Comment by abhnerramos** [comment]
fixed on [LPS-179265](https://issues.liferay.com/browse/LPS-179265)

**Pull request closed without merging**
