### PR TITLE
LPS-144916 Removing property skip.portal.instance

### PR DESCRIPTION
**Pull request by CarlosBrichete**
**JIRA ticket:**
LPS-144916

**Motivation:**
Removing property skip.portal.instance to check if they need it or not.

### CODE REVIEW

**Comment by CarlosBrichete** [comment]
ci:test:frontend

**Comment by CarlosBrichete** [comment]
ci:test:sf

**Comment by CarlosBrichete** [comment]
ci:test:frontend

**Comment by CarlosBrichete** [comment]
ci:test:frontend

**Comment by CarlosBrichete** [comment]
ci:test:frontend

**Comment by CarlosBrichete** [comment]
ci:test:sf

**Comment by CarlosBrichete** [comment]
Hey @manoelcyreno, could you review it? The tests failing are the same that are failing right now in the daily routine :)

**Comment by manoelcyreno** [comment]
LGTM

**Comment by manoelcyreno** [comment]
ci:forward

**Pull request closed without merging**
