### PR TITLE
LPS-131542 use constants

### PR DESCRIPTION
**Pull request by nhpatt**
Changing hardcoded strings to constants. This is the first part of the ticket... "Write test to check flatten support and review usage of strings in search methods". I was expecting `flatten` feature/tests to fail because echo and lima told me that they removed indexing of `treePath` (and that's the reason behind this task) but it's working... and the stories are supposed to be completed: https://issues.liferay.com/browse/LPS-130375.

So... I'll ask them tomorrow because nothing makes sense. But this has value so we can go ahead removing the strings.

### CODE REVIEW

**Comment by nhpatt** [comment]
ci:test:relevant

**Comment by nhpatt** [comment]
Ups, not going to modify headless-admin-user, it belongs to US&M now.

**Comment by nhpatt** [comment]
ci:test:relevant

**Comment by nhpatt** [comment]
ci:stop

**Comment by nhpatt** [comment]
ci:stop

**Comment by nhpatt** [comment]
ci:test:relevant

**Review by jbalsas — APPROVED** [review]
sealofapproval

Looks like something even @wincent could approve 😂

**Comment by nhpatt** [comment]
I'll go ahead, let's simplify @javierdearcos stressful week a bit.

**Comment by nhpatt** [comment]
ci:forward

**Pull request closed without merging**
