### PR TITLE
LPS-157378: Expose content elements (name and contentURL) in navigation menus APIs

### PR DESCRIPTION
**Pull request by 4lejandrito**
Follow up of https://github.com/liferay-frontend/liferay-portal/pull/2618.

### CODE REVIEW

**Comment by 4lejandrito** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
ci:test:sf

**Review by LuismiBarcos — APPROVED** [review]
LGTM :) 👏 👏 👏 👏 
I didn't think in add this to the DTOConverter, it is a great idea as it is a link to get the DTO itself, make senses to add it there.

**Comment by LuismiBarcos** [comment]
Feel free to reorganize the git log if you want or send it like this.

**Comment by 4lejandrito** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
ci:test:relevant

**Comment by sergiojimcos** [comment]
ci:test:relevant

**Comment by sergiojimcos** [comment]
ci:test:relevant

**Comment by mateusralv** [comment]
I'm taking a look 🕵🏽

**Comment by mateusralv** [comment]
Hey @sergiojimcos and @4lejandrito The failures are not unique to your PR and seems unrelated. 🎉

**Comment by sergiojimcos** [comment]
ci:forward

**Comment by susanchen3** [comment]
ci:forward

**Pull request closed without merging**
