### PR TITLE
LPS-146465 - Migrate Documents and Media to use new MT filter and order

### PR DESCRIPTION
**Pull request by tinycarol**
### References

- [LPS-146465](https://issues.liferay.com/browse/LPS-146465)

### What is the goal?

* Add example of migration to new MT filter and order
   * I had to rename the FF because the `FFManagementToolbarConfigurationUtil` class was only accessible from inside the `frontend-taglib-clay` module, and I needed to use it in the `document-library-web` module

#### Before migration (FF disabled)

https://user-images.githubusercontent.com/6642927/151997697-9a5bb961-cb26-4c73-9a84-65add470d119.mov

#### After migration (FF enabled)

https://user-images.githubusercontent.com/6642927/151949165-972db277-199e-4df9-938c-9a54de054379.mov

### How to replicate

* Enable feature flag
   * Download [this flag](https://issues.liferay.com/secure/attachment/439935/com.liferay.frontend.taglib.clay.servlet.taglib.configuration.FFManagementToolbarConfiguration.config)
   * Move it to `bundles/osgi/config`
   * Restart portal
* Go to `Content & Data > Documents and Media`
* See that the `Filter and order` dropdown is now two different dropdowns
* Create at least two documents/folders with different names
* Click on order dropdown, select `Name`
* See that if you select a different order direction, the order changes

### CODE REVIEW

**Comment by tinycarol** [comment]
ci:test:relevant

**Comment by tinycarol** [comment]
> image
image

**Comment by tinycarol** [comment]
ci:test:relevant

**Comment by tinycarol** [comment]
ci:stop

**Comment by tinycarol** [comment]
ci:test:sf

**Comment by tinycarol** [comment]
ci:test:relevant

**Comment by carloslancha** [comment]
Overall LGTM! Could we send this to liferay-lima so they can take a look since this affects their components? Thx!!

**Comment by carloslancha** [comment]
ci:relevant

**Comment by carloslancha** [comment]
ci:test:relevant

**Comment by tinycarol** [comment]
Sent to Lima, see https://github.com/liferay-lima/liferay-portal/pull/2710

**Pull request closed without merging**
