### PR TITLE
[TS] LPS-128028 Preventing curParam from being removed in the URL, so it can ensure independent pagination between Search Container

### PR DESCRIPTION
**Pull request by orsolyaDekany**
Hi Team,

Search containers do not ensure independent pagination currently, however different _curParam_ variables are included in the search containers _liferay-ui:search-container_ taglib for example [here](https://github.com/liferay/liferay-portal/blob/master/modules/apps/users-admin/users-admin-web/src/main/resources/META-INF/resources/user/user_groups.jsp#L75) .

**Root cause** analysis: _curParam_, that ensures independent pagination, is not included in the _iteratorURL_ when multiple search container pagination is being used on a site. Therefore, the cur value will be reset and set to the default value.
The _curParam_ is set to null [here ](https://github.com/liferay/liferay-portal/blob/master/portal-web/docroot/html/taglib/ui/search_paginator/lexicon/page.jsp#L36) that prevents the parameter being included in the URL.

**Fix**:   _curParam_ will be included in the URL by removing the code from search_paginator.

Please see more information on PTR: https://issues.liferay.com/browse/PTR-2221

LPS: https://issues.liferay.com/browse/LPS-128028

Cc. @antonio-ortega

### CODE REVIEW

**Comment by jbalsas** [comment]
Looks reasonable and @antonio-ortega validated this, so I'd generally just push this forward.

I'm not particularly happy with the amount of tests that ran here, though, so I'm going to trigger a full test suite and decide based on that.

**Comment by jbalsas** [comment]
ci:test

**Comment by jbalsas** [comment]
Hey @orsolyaDekany, @antonio-ortega, failures here seem potentially related:

** AssetPublisherUseCase#AssetPublisherCategoriesNavigation**: It's expecting to be in `Page 2 of 2` but finds itself in `Page 1 of 2`:

> Element is not present at "//div[@class='lfr-pagination-page-selector']/div/a[contains(.,'Page 2 of 2')]"

**AssetPublisherUseCase#ViewAssetPaginationAndShowContentAddButtonViaAP** Same thing

Could you please take a look and verify if these changes make that happen and see if you can reconcile the 2 issues?

Thanks!

**Comment by orsolyaDekany** [comment]
Hi @jbalsas @antonio-ortega ,
it is a real issue. The asset publisher pagination cur value does not change from 1 to 2. 

I have tested web content, media&documents, blogs, navigation menus and multiple search container in user&admin for instance, but not the asset publisher. Looks like I have tested the lexicon based pagination-bar only.

If I remove the code from search_paginator\lexicon\page.jsp only and leave the code in search_paginator\page.jsp, then no issues in asset publisher and lexicon based pagination either.
I am not sure at the moment why the search_paginator\page.jsp needs that line of code, but I can make some investigation.

**Comment by jbalsas** [comment]
> I am not sure at the moment why the search_paginator\page.jsp needs that line of code, but I can make some investigation.

Hey @orsolyaDekany, I'd appreciate it if you could do that, it would help us understand better what's going on and what could be the impact of the changes we need to make.

Let us know if you can't get somewhere within a reasonable amount of time so we can figure out how to proceed.

Thanks!

**Comment by orsolyaDekany** [comment]
Hi @antonio-ortega @jbalsas ,
I made some investigation:
Differently to the lexicon based pagination, the asset publisher pagination has default/standard markup. The Lexicon "pagination-bar" is using the **page_iterator/start.jsp** folder when iterating through the pages while the default/standard pagination is using **page_iterator/lexicon/start.jsp**. 

[This part of code](https://github.com/liferay/liferay-portal/blob/master/portal-web/docroot/html/taglib/ui/page_iterator/lexicon/start.jsp#L377) in __getHREF_ method is adding key parameters (curParam) to the URL in lexicon/start.jsp (as Antonio already mentioned it in the PTR). In the history, I found that HttpUtil.addParameter was added for generating valid URL with [this commit](https://github.com/brianchandotcom/liferay-portal/pull/55804/commits/c7dc506fe32d889e436f8d06ea183c5546638ae6). 
We could add the whole line `HtmlUtil.escapeHREF(HttpUtil.addParameter(HttpUtil.removeParameter(url, curParam) + urlAnchor, curParam, cur));
` [here](https://github.com/liferay/liferay-portal/blob/master/portal-web/docroot/html/taglib/ui/page_iterator/start.jsp#L330) including also escapeHREF, so it is safer to use (referring to [LPS-105723](https://issues.liferay.com/browse/LPS-105723)). 

From readability point of view, it would be better to remove `iteratorURL.setParameter(searchContainer.getCurParam(), (String)null);`  in **search_paginator/page.jsp** and **search_paginator/lexicon/page.jsp** and add this line of code in start.jsp.
I tested the multiple search container's pagination and asset publisher and it works without issues.

Please let me know your opinion and comment on this.
Thank you!

**Comment by antonio-ortega** [comment]
Hi @orsolyaDekany ,

Your suggestion makes sense to me. Please, add a new commit with those changes, push it to this branch and we'll re-run our test suite.

Thanks.

Regards.

Ps: I've checked [this](https://github.com/liferay/liferay-portal/blob/master/modules/apps/asset/asset-publisher-web/src/main/resources/META-INF/resources/view.jsp#L151-L156) is the point in Asset Publisher where we are not defining lexicon as `markupView` so it is shown with the default markup. Having a quick look at the code, there are multiple places where we are using that same `liferay-ui:search-paginator` taglib with default markup ([microblogs](https://github.com/liferay/liferay-portal/blob/master/modules/apps/microblogs/microblogs-web/src/main/resources/META-INF/resources/microblogs/view.jsp#L163-L166), [knowledge base](https://github.com/liferay/liferay-portal/blob/master/modules/apps/knowledge-base/knowledge-base-web/src/main/resources/META-INF/resources/section/view.jsp#L111-L113), [blogs aggregator](https://github.com/liferay/liferay-portal/blob/master/modules/apps/blogs/blogs-web/src/main/resources/META-INF/resources/blogs_aggregator/view_entries.jspf#L75-L77)...), so it is better to keep it as it is since Asset Publisher is not a single exception in the whole portal as we could thought as a result of our tests.

**Comment by orsolyaDekany** [comment]
Hi @antonio-ortega ,
Thanks for your answer. PR is updated with the commit.

**Comment by orsolyaDekany** [comment]
I sent a new PR, continuation on PR https://github.com/liferay-frontend/liferay-portal/pull/838

**Pull request closed without merging**
