### PR TITLE
LPS-122697 Avoid infinite loop in Content Performance

### PR DESCRIPTION
**Pull request by dgarciasarai**
**Description**
When the user has the Content Performance panel open and suddenly the network connection is lost but the user performs an action on the panel, there is an infinite loop calling three different endpoints: `getTotalViews`, `getTotalReads` and `getTrafficSources`. 

After a little research, we saw that the problem was the `addWarning` custom hook that we use in the `catch` part of the calls. See:
- `addWarning` in TotalCount component (for total views and total reads): https://github.com/liferay/liferay-portal/blob/afb229df01a027b6f438bf1628290d9470d1e4d8/modules/dxp/apps/analytics/analytics-reports-web/src/main/resources/META-INF/resources/js/components/TotalCount.js#L46
- `addWarning` in TrafficSources component (for traffic sources): https://github.com/liferay/liferay-portal/blob/afb229df01a027b6f438bf1628290d9470d1e4d8/modules/dxp/apps/analytics/analytics-reports-web/src/main/resources/META-INF/resources/js/components/TrafficSources.js#L69

**Solution**
To avoid the infinite loop, I add a check in the custom hook action to not change the state if there is already a warning in the panel. A warning is displayed if the call to an endpoint failed.

### CODE REVIEW

**Comment by dgarciasarai** [comment]
ci:test:sf

**Review by wincent — APPROVED** [review]
Seems... legit

legit

**Comment by dgarciasarai** [comment]
Wow, so fast @wincent. Thank you! Let's run the CI then 😄

**Comment by dgarciasarai** [comment]
ci:test:relevant

**Comment by wincent** [comment]
ci:forward

**Pull request closed without merging**
