### PR TITLE
LPD-39583 - Check if selectedItem exists before referencing it

### PR DESCRIPTION
**Pull request by kresimir-coko**
[Jira ticket](https://liferay.atlassian.net/browse/LPD-39583)

`TranslationManager` Poshi tests were failing, I think I figured out why. The fix is in the commit, locally all tests pass. Time to see what CI has to say

image

### CODE REVIEW

**Comment by kresimir-coko** [comment]
ci:test:relevant

**Comment by kresimir-coko** [comment]
Seems that the fix to the implementation was enough @dsanz

**Comment by juanjofgliferay** [comment]
@kresimir-coko Your fix is working, as it removes the errors that throws the component. However, I would say that there is still a hidden bug.
In the first example of the React component (frontend-js-components-sample-web) the button does not show the flag, but it has selected a default language. 

image

It seems that the problem could be related with the `selectedItem` of the component when `adminMode` is off, see https://github.com/liferay-frontend/liferay-portal/pull/4510/files#diff-12217acb262642b4fc9915a451195df883d248a1e003fadd9909426c5f0f2fe1R220

Using the `defaultLanguageId` as fallback seems to fix the component errors and it displays the flag.

```
   selectedItem={activeLocales.find(
	(locale) => locale.id === selectedLanguageId || locale.id === defaultLanguageId
   )}
```

**Comment by kresimir-coko** [comment]
Good catch @juanjofgliferay I'll improve the solution 👍

**Review by juanjofgliferay — APPROVED** [review]
LGTM

**Comment by kresimir-coko** [comment]
ci:forward

**Pull request closed without merging**
