### PR TITLE
LPS-115278 Editing permanent redirect information about caching always appears

### PR DESCRIPTION
**Pull request by boton**
This PR adds `cssClass` attribute to recover the CSS class in the HTML render of `<clay:alert`. 
It is like #46 but in <clay:alert.

**Steps to reproduce:**

1. Go to Configuration -> Redirection 
2. Click on add button [+]
3. Type the source URL and destination URL
4. Select Type: Permanent (301)
5. Click Create
6. Edit this redirection

**Before the fix:**
Info about caching is on the page by default.
The `<clay:alert` HTML has a wired attribute `cssClass="hide"`.

image

**After the fix:**
No info alert about caching render by default.
The `<clay:alert` HTML has a new css class `hide` in the `class` attribute.

image

### CODE REVIEW

**Comment by boton** [comment]
ci:test:sf

**Comment by boton** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
Nice catch @boton!

**Comment by jbalsas** [comment]
ci:forward

**Pull request closed without merging**
