### PR TITLE
LPS-155974 Update packages `@clayui/*` to v3.62.0

### PR DESCRIPTION
**Pull request by matuzalemsteles**
### Bug Fixes

-   **@clayui/css:** Cadmin Clay Multi Select should have small size ([e256838](https://github.com/liferay/clay/commit/e256838046b41f885ab0b7f70afd4b58582d8314))
-   **@clayui/css:** Cadmin Reference Mark vertical alignment when it is used directly on the icon ([f530f47](https://github.com/liferay/clay/commit/f530f478133ac9548e94ebcf499ec4dc064bd202))
-   **@clayui/css:** Clay Multi Select should have small size ([818621f](https://github.com/liferay/clay/commit/818621fa0a5abf68abfcc2af8b07bd4b9d6eec04))
-   **@clayui/css:** Global Functions add fallback value for $cadmin variables ([a12777a](https://github.com/liferay/clay/commit/a12777a399d619cd205a7f73caabe02eec70798b)), closes [#4925](https://github.com/liferay/clay/issues/4925)
-   **@clayui/css:** Mixins `clay-button-variant` directly use `clay-unset-placeholder` to clear `[@extend](https://github.com/extend)` ([dcd3999](https://github.com/liferay/clay/commit/dcd39997a5f63ba476d0a66e9089c447e546a35e))
-   **@clayui/css:** Reference Mark vertical alignment when it is used directly on the icon ([e014a8c](https://github.com/liferay/clay/commit/e014a8c6e49fcb90916a3b3a412e30ae02636054))
-   **@clayui/drop-down:** fix bug of calling setActive method when the menu is invisible ([1e3efcf](https://github.com/liferay/clay/commit/1e3efcfcd126f44c0f98547fe9416801d9da5641))
-   **@clayui/multi-select:** Adds small example to storybook ([8bdf156](https://github.com/liferay/clay/commit/8bdf1562cc0d4b25625fc11f720b6c46cbf74c70))
-   **@clayui/multi-select:** fix error when you have a ref declared it is not possible to delete the label by pressing backspace ([685588c](https://github.com/liferay/clay/commit/685588cfabaa3f07503ac123bf8333bc23254c3c))

### Features

-   **@clayui/autocomplete:** Support menu alignment by Viewport ([1409c4b](https://github.com/liferay/clay/commit/1409c4b8d22073e642e12f951ebdcb76c9474669))
-   **@clayui/css:** Global Functions provide default grid breakpoints map for breakpoint functions ([66ad9e1](https://github.com/liferay/clay/commit/66ad9e19d9b966c0058385e76b2b61f64e025af0))
-   **@clayui/css:** Mixins clay-form-control-variant adds more configuration items ([6689c99](https://github.com/liferay/clay/commit/6689c996609585c6ae2e93791cfbbee5edbf4a37))
-   **@clayui/css:** Mixins clay-input-group-item-variant moved .label to clay-form-control-variant ([2a22cf3](https://github.com/liferay/clay/commit/2a22cf3ee22b6c1ef0bc6684f731c3ace5090ef8))
-   **@clayui/css:** Mixins provide a default value if cadmin variables don't exist ([11e026b](https://github.com/liferay/clay/commit/11e026bf34ad9db4a166a7b2fd7ae671c285afc3))

### CODE REVIEW

**Comment by matuzalemsteles** [comment]
ci:test:sf

**Comment by matuzalemsteles** [comment]
Hey @pat270 apparently, some change we made to the CSS is causing a build error in the `frontend-taglib-clay` module, strange that the build doesn't fail in the Clay module itself.

```
BUILD SASS: Built build/node/packageRunBuild/resources/.sass-cache/management_toolbar/CreationMenu.css
Error: expected "(".
    ╷
155 │                     if
    │                       ^
    ╵
  ../../../node_modules/@clayui/css/src/scss/mixins/_badges.scss 155:8                 @import
  ../../../node_modules/@clayui/css/src/scss/_mixins.scss 10:9                         @import
  ../../../node_modules/@clayui/css/src/scss/atlas-variables.scss 13:9                 @import
  src/main/resources/META-INF/resources/management_toolbar/ManagementToolbar.scss 1:9  root stylesheet
    at Object._newRenderError (/Users/matuzalemteles/work/liferay-workspace/liferay-portal/modules/node_modules/sass/sass.dart.js:13537:19)
    at Object._wrapException (/Users/matuzalemteles/work/liferay-workspace/liferay-portal/modules/node_modules/sass/sass.dart.js:13374:16)
    at StaticClosure._renderSync (/Users/matuzalemteles/work/liferay-workspace/liferay-portal/modules/node_modules/sass/sass.dart.js:13349:18)
    at Object.Primitives_applyFunction (/Users/matuzalemteles/work/liferay-workspace/liferay-portal/modules/node_modules/sass/sass.dart.js:1089:30)
    at Object.Function_apply (/Users/matuzalemteles/work/liferay-workspace/liferay-portal/modules/node_modules/sass/sass.dart.js:6007:16)
    at _callDartFunctionFast (/Users/matuzalemteles/work/liferay-workspace/liferay-portal/modules/node_modules/sass/sass.dart.js:7676:16)
    at Object.renderSync (/Users/matuzalemteles/work/liferay-workspace/liferay-portal/modules/node_modules/sass/sass.dart.js:7654:18)
    at buildSass (/Users/matuzalemteles/work/liferay-workspace/liferay-portal/modules/node_modules/@liferay/npm-scripts/src/sass/build.js:56:22)
    at main (/Users/matuzalemteles/work/liferay-workspace/liferay-portal/modules/node_modules/@liferay/npm-scripts/src/sass/build.js:188:34)
    at module.exports (/Users/matuzalemteles/work/liferay-workspace/liferay-portal/modules/node_modules/@liferay/npm-scripts/src/scripts/build.js:245:4)
    at Object.build (/Users/matuzalemteles/work/liferay-workspace/liferay-portal/modules/node_modules/@liferay/npm-scripts/src/index.js:21:4)
    at module.exports (/Users/matuzalemteles/work/liferay-workspace/liferay-portal/modules/node_modules/@liferay/npm-scripts/src/index.js:101:4)
    at main (/Users/matuzalemteles/work/liferay-workspace/liferay-portal/modules/node_modules/@liferay/npm-scripts/bin/liferay-npm-scripts.js:12:2)
 {
  formatted: 'Error: expected "(".\n' +
    '    ╷\n' +
    '155 │                     if\n' +
    '    │                       ^\n' +
    '    ╵\n' +
    '  ../../../node_modules/@clayui/css/src/scss/mixins/_badges.scss 155:8                 @import\n' +
    '  ../../../node_modules/@clayui/css/src/scss/_mixins.scss 10:9                         @import\n' +
    '  ../../../node_modules/@clayui/css/src/scss/atlas-variables.scss 13:9                 @import\n' +
    '  src/main/resources/META-INF/resources/management_toolbar/ManagementToolbar.scss 1:9  root stylesheet',
  line: 155,
  column: 8,
  file: '/Users/matuzalemteles/work/liferay-workspace/liferay-portal/modules/node_modules/@clayui/css/src/scss/mixins/_badges.scss',
  status: 1
}
Received 1
```

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by susanchen3** [comment]
Test failures unrelated :heavy_check_mark: Will manually forward :+1: 

[Comparison run](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=2&testrayRunIdB=1884816722&testrayRunIdA=1884835872&statusB=3): 
- **AssetsBlogs#ViewAllBlogsShownInAssetList**: Not unique, Flaky

**Comment by susanchen3** [comment]
forwarded to bchan: https://github.com/brianchandotcom/liferay-portal/pull/119217

**Pull request closed without merging**
