### PR TITLE
LPD-31812 Remove LPD-10754 Feature Flag

### PR DESCRIPTION
**Pull request by dsanz**
In this PR we are removing all usages of `LPD-10754` feature flags, which controls the REST API headless selection filter management in the DSM

This has some implications:

- Data model compatibility: as this changes the way we generate data model, old models created before this FF was created (or when it was off) are no longer compatible
- Testing: some poshi tests related to picklist filters are going to break. This is a temporary situation, which we are managing under https://liferay.atlassian.net/browse/LPD-29346 in charge of migrating them

### CODE REVIEW

**Review by markocikos — COMMENTED** [review]
@dsanz LGTM, we're only missing to remove it from `portal.properties`. Is that causing the SF error, the fact that it is unused?

**Comment by dsanz** [comment]
sorry, I'd swear I committed that one too, but looks like I forgot. I've just force-pushed, thank you!

**Comment by dsanz** [comment]
ci:test:sf

**Review by markocikos — APPROVED** [review]
@dsanz LGTM! :sparkles:

**Comment by dsanz** [comment]
ci:forward

**Comment by dsanz** [comment]
ci:forward:force

**Pull request closed without merging**
