### PR TITLE
LPS-197299 Improve the FDS Filter client extension contract

### PR DESCRIPTION
**Pull request by izaera**
Resend of https://github.com/brianchandotcom/liferay-portal/pull/143713

As per https://github.com/brianchandotcom/liferay-portal/pull/143713#issuecomment-1809041354

### CODE REVIEW

**Comment by izaera** [comment]
ci:test:sf

**Comment by izaera** [comment]
Since this is a resend of something that has been already tested I'm force-forwarding

**Comment by izaera** [comment]
ci:forward:force

**Comment by izaera** [comment]
ci:forward:force

**Comment by markocikos** [comment]
@izaera aww no go for `cx` :cry:

**Comment by markocikos** [comment]
ci:forward:force

**Pull request closed without merging**
