### PR TITLE
LPS-116716 Revert "LPS-113561 Avoid Liferay.provide in protal-workfow-kaleo-designer-web"

### PR DESCRIPTION
**Pull request by julien**
This reverts commits:
[7c2f6776fa58d93059a74c57cadb46eb848b460b](https://github.com/liferay/liferay-portal/commit/7c2f6776fa58d93059a74c57cadb46eb848b460b)
[565ab7ee61e0347e16643466e8f9cb10e48cca07](https://github.com/liferay/liferay-portal/commit/565ab7ee61e0347e16643466e8f9cb10e48cca07)
[df1c93d78ea501ec9ef88aa17a71109657a2a114](https://github.com/liferay/liferay-portal/commit/df1c93d78ea501ec9ef88aa17a71109657a2a114)
[450c69ab486447b20b4ce70b4481b3a9a5c80592](https://github.com/liferay/liferay-portal/commit/450c69ab486447b20b4ce70b4481b3a9a5c80592)
[a9e1fcf3ba03e3d14112f47c49fc893b1814fe54](https://github.com/liferay/liferay-portal/commit/a9e1fcf3ba03e3d14112f47c49fc893b1814fe54)

### CODE REVIEW

**Comment by julien** [comment]
ci:test:sf

**Comment by julien** [comment]
ci:test:relevant

**Comment by julien** [comment]
> I am not sure how you got to this behavior, I cannot reproduce it.

I just did an `ant all` (previously I did `ant setup-profile-dxp`) and reproduced the step described in the ticket

**Comment by markocikos** [comment]
> I just did an `ant all` (previously I did `ant setup-profile-dxp`) and reproduced the step described in the ticket

This may then be a completely separate issue from the one described in https://issues.liferay.com/browse/LPS-116176. What I am getting completely matches description in the ticket and the screenshots, the issue is that source editor is not displaying.

**Comment by julien** [comment]
> This may then be a separate issue from the one described in https://issues.liferay.com/browse/LPS-116176. What I am getting completely matches description in the ticket and the screenshots, the issue is that source editor is not displaying.

I am also getting exactly the same issue as the one described in the ticket, screenshots and everything match as well

**Comment by markocikos** [comment]
@julien @jbalsas Ok, I think I got to the bottom of this. The height and width calculations in ACE editor are thrown off by the loading indicator what we are always inserting with `openModal`. The height is calculated eagerly, while DOM is still not there. We had a similar issue with the fixed header in properties modal.

The solution there was a bit complex, so it might be here as well. If you wish, we can revert this for now, followup later with a full solution.

**Comment by markocikos** [comment]
Closing, alternative in https://github.com/liferay-frontend/liferay-portal/pull/63

**Pull request closed without merging**
