### PR TITLE
LPS-132672 XSS vulnerability in management toolbar search

### PR DESCRIPTION
**Pull request by markocikos**
Fixes: https://issues.liferay.com/browse/LPS-132672

See ticket for test cases and description.

In this PR, we are escaping the search value rendered by management toolbar SSR.

After PR:
after

### CODE REVIEW

**Comment by bryceosterhaus** [comment]
LGTM!

**Comment by markocikos** [comment]
CI failure is unrelated, we are not updating `com.liferay.portlet.expando.model.impl.ExpandoRowBaseImpl` in this PR.

**Comment by markocikos** [comment]
ci:forward

**Comment by markocikos** [comment]
Failures are clearly unrelated. I'll try one more time, will manually forward if it fails. This is a very safe PR.

**Comment by markocikos** [comment]
ci:forward

**Comment by diegonvs** [comment]
This PR looks safe to me too. I'll try forward this PR again to make @markocikos happy on Monday without needing to manually forward 😛

**Comment by diegonvs** [comment]
ci:forward

**Pull request closed without merging**
