### PR TITLE
LPS-159740: An inconsistency in the behavior about wikiPage of API Explorer

### PR DESCRIPTION
**Pull request by sergiojimcos**
**What is new?:**

- Add new method (`getPageByResourcePrimKey`) in `WikiPageServiceImpl` to retrive a wiki page given a WikiPage resource Primary Key:

```
	public WikiPage getPageByResourcePrimKey(long resourcePrimKey)
		throws PortalException {

		WikiPage page = wikiPageLocalService.getPage(resourcePrimKey);

		_wikiPageModelResourcePermission.check(
			getPermissionChecker(), page, ActionKeys.VIEW);

		return page;
	}
```
- Update `WikiPageAttachmentsResourceImpl` using the new method.
- Update `WikiPageAttachmentResourceTest` retrieving the wikiPage resource Primary Key.

**SCENARIO** 

Once I create a wikiPage with attachments when I use getWikiPageWikiPageAttachmentsPage with wikiPageId.

**Before changes**
Response return "No WikiPage exists with the primary key"

**After changes**
Response 200 OK

**Ticket JIRA**
https://issues.liferay.com/browse/LPS-159740

cc/ @4lejandrito

### CODE REVIEW

**Comment by ccorreagg** [comment]
Could we create an integration test to test this functionality?

**Comment by sergiojimcos** [comment]
> Could we create an integration test to test this functionality?

I've updated the integration test in the API part. Do you mean if we should create a integration test when we don't use the resourcePrimKey?

**Review by ccorreagg — APPROVED** [review]

**Review by LuismiBarcos — APPROVED** [review]
LGTM :)
Should we send this to the Lima team as we add some methods?
Or add tests for that new method?

**Comment by sergiojimcos** [comment]
> LGTM :) Should we send this to the Lima team as we add some methods? Or add tests for that new method?

To be sure, we could send this PR to Lima team. About adding tests, I think that is covered because I've just updated all tests to make sure that they will not fail

**Comment by LuismiBarcos** [comment]
> About adding tests, I think that is covered because I've just updated all tests to make sure that they will not fail

Yes, I saw it. What I meant is to create tests for [this new method](https://github.com/liferay-frontend/liferay-portal/pull/2604/commits/eded7ec99a7a43dc3863c9f6ba5cce9b33ff1ca2) in wiki-test. Don't know if there is a test class for the remotes, that's why I asking 😅

**Comment by sergiojimcos** [comment]
> Yes, I saw it. What I meant is to create tests for [this new method](https://github.com/liferay-frontend/liferay-portal/pull/2604/commits/eded7ec99a7a43dc3863c9f6ba5cce9b33ff1ca2) in wiki-test. Don't know if there is a test class for the remotes, that's why I asking

There isn't any remote test class, should I have to create a test case in the local test class?

**Comment by sergiojimcos** [comment]
This PR will be closed to be reviewed by Lima team: https://github.com/liferay-lima/liferay-portal/pull/3335

**Pull request closed without merging**
