### PR TITLE
LPS-144537 - Keep MT info button fixed to the right

### PR DESCRIPTION
**Pull request by tinycarol**
If this rings a bell, it's because I'm resending this PR because the previous one didn't use a feature flag

### References

- [LPS-144537](https://issues.liferay.com/browse/LPS-144537)

### What is the goal?

* Move Management Toolbar info button to the right, both in normal and contextual mode
* Add separator to the left of MT info button in contextual mode
* Hide info button in mobile
* Use epic FF to hide these changes

### What does it look like?

https://user-images.githubusercontent.com/6642927/147652937-fec55f54-3376-4239-b5be-646d7b40ebf0.mov

### How to replicate
* Enable the feature flag
   * Download the FF file [from this epic](https://issues.liferay.com/browse/LPS-144527)
   * Paste that file in `/bundles/osgi/configs/`  
* Log into portal, go to `Content & Data > Web Content` 
* See that the rightmost element in the toolbar at the top is now the info button
* Click on select all, see that the rightmost element is still the info button
* Shrink window to mobile size, see that the info button is not visible
* Click again on select all, see that the info button is not visible either

### CODE REVIEW

**Review by carloslancha — APPROVED** [review]
<a href="https://gitme.me/image?url=https%3A%2F%2Fmedia1.giphy.com%2Fmedia%2Fd2ZeMUDQSSsCP9FC%2Fgiphy.gif&token=looksgood" data-gitmeme-token="looksgood"></a>

**Comment by bryceosterhaus** [comment]
Shout out @tinycarol for writing some of the best PR descriptions of all time. I am probably the worst offender of short and not entirely helpful descriptions, so I aspire to write better descriptions after seeing yours. 🏆

**Comment by tinycarol** [comment]
Thanks @bryceosterhaus! ❤️  IMO, [PR templates](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository) help a lot and basically do half the job. I know it's not possible to add one to this repo, but maybe it would help in other FI repos.

**Comment by tinycarol** [comment]
ci:forward

**Comment by magjed4289** [comment]
ci:help

**Pull request closed without merging**
