### PR TITLE
LPS-136195 Update liferay-ckeditor to 4.16.1-liferay.3

### PR DESCRIPTION
**Pull request by diegonvs**
It includes fixes to the following tickets:

https://issues.liferay.com/browse/LPS-136195

# Changelog:

## [v4.16.1-liferay.3](https://github.com/liferay/liferay-ckeditor/tree/v4.16.1-liferay.3) (2021-07-29)

[Full changelog](https://github.com/liferay/liferay-ckeditor/compare/v4.16.1-liferay.2...v4.16.1-liferay.3)

### :wrench: Bug fixes

-   fix: CodeMirror plugin cannot handle multiple instances ([\#185](https://github.com/liferay/liferay-ckeditor/pull/185))

More details in [CHANGELOG.md](https://github.com/liferay/liferay-ckeditor/blob/master/CHANGELOG.md)

/cc @NemethNorbert

### CODE REVIEW

**Comment by diegonvs** [comment]
Push force for adding the changelog in commit_msg...

**Comment by diegonvs** [comment]
ci:test:sf

**Comment by diegonvs** [comment]
ci:test:relevant

**Review by markocikos — APPROVED** [review]
LGTM!

**Comment by markocikos** [comment]
ci:forward

**Pull request closed without merging**
