### PR TITLE
LPS-116592 Upgrade float classes in account-admin-web

### PR DESCRIPTION
**Pull request by eduardoallegrini**
This is similar to https://github.com/liferay-frontend/liferay-portal/pull/185.

I've looked for `.pull-left` and `.pull-right` classes in Portal and I found these 3 cases, I think we can upgrade them

**Result for portal-workflow-kaleo-forms-web:**
Screenshot 2020-07-30 at 19 02 21

**Result for account-admin-web:**
I couldn't find the class in the UI but I trust it will work, since originally `.pull-right` extends `.float-right` https://github.com/liferay/liferay-portal/blob/master/modules/apps/frontend-theme/frontend-theme-styled/src/main/resources/META-INF/resources/_styled/css/compat/components/_utilities.scss#L11

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:test:sf

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
LGTM

**Comment by marcoscv-work** [comment]
LGTM

**Comment by jbalsas** [comment]
99.99% this is unrelated. @john-co, business as usual means a lot of overhead for us to manually submit... going to retry 1 time to see if we can avoid that.

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
We keep getting failures in `LocalFile.WorkflowMetrics`, but different ones, so maybe all of those are flaky.

Running one last time to se if any repeat.

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
idk_keanu

**Comment by jbalsas** [comment]
ci:forward

**Comment by john-co** [comment]
> We keep getting failures in LocalFile.WorkflowMetrics, but different ones, so maybe all of those are flaky.

cc/ @rodrigocunhaa can you please check on these?

**Pull request closed without merging**
