### PR TITLE
LPD-37467 -  Update relationship property names

### PR DESCRIPTION
**Pull request by juanjofgliferay**
https://liferay.atlassian.net/browse/LPD-37467

### CODE REVIEW

**Comment by juanjofgliferay** [comment]
ci:test:relevant

**Review by markocikos — APPROVED** [review]
@juanjofgliferay LGTM! :sparkles:

**Comment by juanjofgliferay** [comment]
ci:forward

**Review by dsanz — APPROVED** [review]
LGTM ;) thanks @juanjofgliferay

**Comment by juanjofgliferay** [comment]
ci:forward:force

**Pull request closed without merging**
