### PR TITLE
LPS-154649 Refactor TestSampleWalkthrough

### PR DESCRIPTION
**Pull request by diegonvs**
It was necessary because https://github.com/liferay/liferay-portal/commit/97b4e8d697499b8e9854e711ad933353bfd311fe changes were introduced when https://github.com/liferay-frontend/liferay-portal/pull/2414 changed the JSON API and the module where Walkthrough component should be imported.

### CODE REVIEW

**Comment by diegonvs** [comment]
ci:stop

**Comment by diegonvs** [comment]
@matuzalemsteles brought a `.lfrbuild-portal` file that should be included inside the walkthrough-web module to make the module active and available to be imported inside the frontend-js-components-sample-web module.

/cc @dsanz

**Comment by diegonvs** [comment]
ci:test:relevant

**Comment by susanchen3** [comment]
ci:test:frontend

**Comment by diegonvs** [comment]
ci:reevaluate:1387401_2103

**Comment by susanchen3** [comment]
Hey @diegonvs 

[LocalFile.WalkthroughPopover#FinalStepCanTransitionToHotSpotMode](https://testray.liferay.com/home/-/testray/case_results/1898649451) is failing because the hotspot element doesn't appear when clicking the `Close` button on the last step, but it does appear when clicking on the `x`. I'm not sure if this is intention behavior now cause then I gotta modify the test :) Thanks!

**Comment by susanchen3** [comment]
Thanks for the clarification! :D 

Sent in a test fix for the new behavior [here](https://github.com/susanchen3/liferay-portal/pull/61). Doing one last check for the tests to pass. Can either cherrypick my test fix commit to this PR or I can manually forward this PR with the test fix to bchan. :)

**Pull request closed without merging**
