### PR TITLE
LPS-135097 simplify object mapper

### PR DESCRIPTION
**Pull request by nhpatt**
Seems that the code that generates the `Page` object manually for XML requests is not being executed any more (after adding a generic in a source format global change :|) but underlying issue (several <items><items> anidated) seems fixed, so we should remove the code and remove the conditional.

### CODE REVIEW

**Comment by nhpatt** [comment]
ci:test:relevant

**Comment by nhpatt** [comment]
ci:test:relevant

**Review by javierdearcos — APPROVED** [review]

**Comment by nhpatt** [comment]
ci:forward

**Comment by nhpatt** [comment]
ci:test:relevant

**Comment by nhpatt** [comment]
ci:forward

**Comment by nhpatt** [comment]
ci:test:relevant

**Comment by nhpatt** [comment]
ci:forward

**Pull request closed without merging**
