### PR TITLE
LPD-44091 - Add deprecation FF for walkthrough

### PR DESCRIPTION
**Pull request by bryceosterhaus**
This doesn't add any of the UI elements, as those are not yet supported by site settings config or the portlet header

### CODE REVIEW

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Review by izaera — APPROVED** [review]
LNHTM

**Comment by bryceosterhaus** [comment]
ci:forward

**Pull request closed without merging**
