### PR TITLE
LPS-191776 Standardize renderer TS types, components and utilities

### PR DESCRIPTION
**Pull request by markocikos**
### References

- [LPS-189354 Standardize renderer APIs](https://issues.liferay.com/browse/LPS-189354)

### What is the goal of this PR?

Currently, we have inconsistencies in the code, naming different things "renderers". The scope of renderer types, components and utilities is not right, as they don’t need to be coupled with FDS or DSM. In several previous PRs, like [here](https://github.com/liferay-frontend/liferay-portal/pull/3356#issuecomment-1564161583), this came up as topic of discussion, where we delayed restructure for a followup. This is it.

In this PR:
- We are solidifying "Renderer" as an object containing:
  - `type` property, [discriminating](https://www.typescriptlang.org/docs/handbook/2/narrowing.html#discriminated-unions) between types of Renderers. Currently there are two: "Internal Renderer" and "Client Extension Renderer".
  - React component (`component` property), or an HTML Builder function (`htmlBuilder` property), for their respective types
     - we are introducing "HTML Builder", rebranding from current "renderer"
  -  metadata, such as `name`, `url`, etc.
- We are defining renderer TS types to a common location, in `frontend-js-web`. I'm not sure of there is a better place for "global TS types".
- We are renaming and moving renderer getter to `frontend-js-web`.
  - I chose to put `renderer` dir in the root resource folder, instead of somewhere in `liferay`. I'm assuming `liferay` dir convention comes from exposing to global `Liferay`. I doubt that we will ever want to do that, to use this outside of React context. If we ever do, we can easily move it internally.  
- We are renaming and moving standard client extension component to `frontend-js-components-web`.

### What does it look like?

No changes in UI.

### CODE REVIEW

**Comment by izaera** [comment]
TBH, I've lost track of FDS a long time ago, so I don't feel qualified to review the refactor.

I've seen that it removes some imports of `@liferay/js-api/data-set` but then it adds them in another files. As long as we don't break those contracts (which are the customer/CXs contracts) we are OK since no code from the outside world will break.

Keep in mind that, if you want, we can still rename the types in `@liferay/js-api/data-set` since they have not been released as GA yet. However, if you decide to do that, all sample CXs must be updated to reflect the change and we should notify people too (=> expect questions and issues from internal teams that are already testing this functionality :grimacing: ).

**Comment by markocikos** [comment]
> Keep in mind that, if you want, we can still rename the types in @liferay/js-api/data-set since they have not been released as GA yet. However, if you decide to do that, all sample CXs must be updated to reflect the change and we should notify people too (=> expect questions and issues from internal teams that are already testing this functionality 😬 ).

I do plan on doing that, but in a [separate subtask](https://liferay.atlassian.net/browse/LPS-191779).

**Comment by bryceosterhaus** [comment]
Looks fine to me. I have the same concern as @izaera, we just need to make sure that this doesn't cause any break for CX in our samples or for customers.

**Comment by markocikos** [comment]
Is is CETs or CXs? :joy:  I got used to calling them CETs, because that's the abbreviation in Java.

This PR does not change client extensions public API, only places where cell client extension is applied. I believe this should be safe. Client extensions in our sample module is working fine:
image

**Comment by markocikos** [comment]
ci:forward

**Comment by izaera** [comment]
> Is is CETs or CXs? joy I got used to calling them CETs, because that's the abbreviation in Java.

CET in the code, CX inside Liferay, Client Extension in the docs.

As in:

- Layout/Page
- Portlet/Widget
- Company/Virtual instance
- Group/Site

Etc.

[yatusabe...](https://www.youtube.com/watch?v=p1hDM_VfkCg)

(*) yatusabe is a "fake" Spanish word built by merging ya (yet), tu (you), sabe' (know, it should be "sabes"). Thus yatusabe -> yetyouknow

**Comment by bryceosterhaus** [comment]
I just use whatever comes to mind first and put the burden on the reader to understand 😂

**Pull request closed without merging**
