### PR TITLE
LPS-126065 Pages with info-panel aren't laid out correctly

### PR DESCRIPTION
**Pull request by pat270**
https://issues.liferay.com/browse/LPS-126065

Move container-fluid inside sidenav-content so the Info Panel isn't rendered right against the content. There are vertical gaps between info panel and navigation in Documents and Media and Knowledge Base view_article.jsp that are not related to this pr.

- Adaptive Media Web
- Bookmarks Web
   - change typo on css class bookmakrs-breadcrumb to bookmarks-breadcrumb
- Commerce Product Options Web
- Commerce Product Type Grouped Web
- Journal Web
- Knowledge Base Web
- Portal Workflow Web
- Redirect Web
- Site Admin Web
- Site Memberships Web
- Trash Web
- User Associated Data Web
- Wiki Web
- Askimet Web

What it looks like now:
info-panel-fix

### CODE REVIEW

**Comment by wincent** [comment]
CI error in `modules/dxp/apps/portal-workflow/portal-workflow-kaleo-designer-web/src/main/resources/META-INF/resources/designer/edit_kaleo_definition_version.jsp` looks legit; there are two closing tags in there.

**Comment by pat270** [comment]
ci:test:relevant

**Comment by pat270** [comment]
Thanks @wincent, just pushed up correction.

**Comment by pat270** [comment]
@john-co @zhangyan0701 is this failure related to changes I made?

**Comment by john-co** [comment]
Just started reviewing :)

**Comment by john-co** [comment]
ci:test:bundle

**Comment by john-co** [comment]
Hi @pat270, what I found:

[Unrelated]
- Kaleodesigner#AddJoinXORWorkflowDefinitionViaViewTab - Seems like a flaky test based on recent test history: https://liferay.spiraservice.net/16/TestCase/219514.aspx @rodrigocunhaa would this test be ok to quarantine so it doesn't affect our future PRs?

Will re-run ci:test:relevant but if another test fails, it is ok to manually forward.

**Comment by john-co** [comment]
ci:test:relevant

**Comment by rodrigocunhaa** [comment]
Hi @john-co,

No problem. Just please fill a LRQA ticket and assign it to me, so I can keep track of it?

Thanks!

**Comment by john-co** [comment]
Thanks @rodrigocunhaa , I created quarantine task: https://issues.liferay.com/browse/LRQA-64622

**Comment by pat270** [comment]
ci:forward

**Pull request closed without merging**
