### PR TITLE
LPS-122392 Remove {closest, contains, match} usages of metal-dom

### PR DESCRIPTION
**Pull request by diegonvs**
Previously opened on https://github.com/diegonvs/liferay-portal/pull/39 to see if CI cries.

CI cried 😭 

> 						<h1>Unable to generate test report.</h1><p>Jenkins encountered the following error while generating test report:</p><pre><code>Sourced file: inline evaluation of: `` 						 							import com.liferay.jenkins.results.parser.Build; 							import co . . . '' : TargetError : at Line: 48 : in file: inline evaluation of: `` 						 							import com.liferay.jenkins.results.parser.Build; 							import co . . . '' : throw e ; 

I'll re-run tests again

## Found usages by grepping: 

* `git grep "contains(" -- '*.js*'`

* `git grep "closest(" -- '*.js*'`

* `git grep "match(" -- '*.js*'`

and replaced 

[domNamed contains](https://github.com/metal/metal.js/blob/466812085dd29e37c90b835c64cb49555d76a294/packages/metal-dom/src/domNamed.js#L218..L225) with native [contains](https://developer.mozilla.org/en-US/docs/Web/API/Node/contains)

[domNamed closest](https://github.com/metal/metal.js/blob/466812085dd29e37c90b835c64cb49555d76a294/packages/metal-dom/src/domNamed.js#L163..L167) with native [closest](https://developer.mozilla.org/en-US/docs/Web/API/Element/closest).

[domNamed match](https://github.com/metal/metal.js/blob/466812085dd29e37c90b835c64cb49555d76a294/packages/metal-dom/src/domNamed.js#L418) with [matches](https://developer.mozilla.org/en-US/docs/Web/API/Element/matches)

## Test Case:

contains/closest when using [clickOutside.es.js](https://github.com/diegonvs/liferay-portal/blob/9e150a71e252c3eee2b5c2739d2858085f6e62c3/modules/apps/app-builder/app-builder-web/src/main/resources/META-INF/resources/js/utils/clickOutside.es.js)

1. Global Menu -> Applications -> App Builder -> Objects
2. Click on plus button for creating a new custom object and then click outside the panel to close it

matches

TDB

## Questions

Considering the previous PR, I blacklisted(to not be touched) the following modules:

`frontend-image-editor`

`site-navigation-admin-web`

[I notice We have the same implementation of clickOutside related things everywhere](https://gist.github.com/diegonvs/81678850b2f02d9f9e0d60418d350b81). Should We consider creating a utility for that?

As a suggestion, on React-side We can create a util like [this one](https://elastic.github.io/eui/#/utilities/outside-click-detector) and may create a pure-js implementation too.

### CODE REVIEW

**Comment by diegonvs** [comment]
ci:test:sf

**Comment by diegonvs** [comment]
ci:test:relevant

**Comment by wincent** [comment]
> [I notice We have the same implementation of clickOutside related things everywhere](https://gist.github.com/diegonvs/81678850b2f02d9f9e0d60418d350b81). Should We consider creating a utility for that?
> 
> As a suggestion, on React-side We can create a util like [this one](https://elastic.github.io/eui/#/utilities/outside-click-detector) and may create a pure-js implementation too.

Yes, we should create a ticket for that (didn't we have a ticket somewhere for this already?), but I wouldn't actually implement it yet, so that we can stay focus on the existing tech debt tasks (which are about removing legacy code, not reducing duplication or near duplication).

I only very briefly skimmed the code because the CI looks a bit red (the poshi tests), but my at-a-glance assessment is that this looks good.

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
going to re-test and if its still red, I'll dig into the tests more

**Comment by bryceosterhaus** [comment]
Looking into the failures now...

**Comment by bryceosterhaus** [comment]
Follow up at https://github.com/liferay-frontend/liferay-portal/pull/474

**Pull request closed without merging**
