### PR TITLE
LPS-127202 [Content Performance] Hide TimeSpanSelector in Referral traffic channel detail

### PR DESCRIPTION
**Pull request by dgarciasarai**
**Description**

The information needed for the `TimeSpanSelector` component to work in Referral traffic detail view is not provided by the Analytics Cloud endpoint yet, so we decided to hide that component until it's ready.

**Screenshot**

_Note: This image was created using mock data because we need 24h to process AC data._

Screenshot 2021-02-10 at 16 29 56

### CODE REVIEW

**Comment by dgarciasarai** [comment]
ci:stop

**Comment by dgarciasarai** [comment]
Applied the same feedback as in https://github.com/liferay-frontend/liferay-portal/pull/781#discussion_r573980700. cc: @bryceosterhaus. Thanks!

**Comment by dgarciasarai** [comment]
ci:test:sf

**Review by bryceosterhaus — APPROVED** [review]
LGTM! I'll forward once tests pass

**Comment by bryceosterhaus** [comment]
ci:forward

**Comment by dgarciasarai** [comment]
ci:test:relevant

**Comment by dgarciasarai** [comment]
Thanks!!! ❤️

**Pull request closed without merging**
