### PR TITLE
LPS-200195 - Use refreshURL value since the url value has been modified

### PR DESCRIPTION
**Pull request by bryceosterhaus**

### CODE REVIEW

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
ci:test:sf

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by JerryAdrianoo** [comment]
None of the thousands of failures (only 2) are related, hahaha.
[Comparison](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1698407812526&testrayRunIdA=2446948333&testrayRunIdB=2447753447)

**Comment by dsanz** [comment]
ci:test:stable

**Comment by JerryAdrianoo** [comment]
Stable is ok here, only portal-license-smoke-mysql57-jdk8/0/0 returned as _Aborted prior to running test_

**Comment by bryceosterhaus** [comment]
ci:test:stable

**Comment by bryceosterhaus** [comment]
I'll give it one more run and see

**Review by markocikos — APPROVED** [review]
@bryceosterhaus LGTM! :sparkles:

**Comment by bryceosterhaus** [comment]
ci:test:stable

**Comment by bryceosterhaus** [comment]
ci:forward

**Comment by bryceosterhaus** [comment]
ci:stop

**Comment by bryceosterhaus** [comment]
ci:forward:force

**Comment by bryceosterhaus** [comment]
ci:stop

**Comment by bryceosterhaus** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/143071

**Pull request closed without merging**
