### PR TITLE
LPS-155889 Use new Cookie API in session.js

### PR DESCRIPTION
**Pull request by tinycarol**
### References

- [LPS-155889](https://issues.liferay.com/browse/LPS-155889)

### What is the goal?

* Use new Cookie API in session.js to get/set session cookie values

### CODE REVIEW

**Comment by mateusralv** [comment]
ci:test:relevant

**Comment by tinycarol** [comment]
ci:test:relevant

**Comment by mateusralv** [comment]
I'm taking a look at the failures.

**Comment by mateusralv** [comment]
Hi @tinycarol, the failures don't seem related to your PR :). Most failures also occurring on the master. ([Comparison run](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=2&testrayRunIdB=1906795486&testrayRunIdA=1904940329&statusB=3))

- The failure for `empty-temp-dir-jdk8/0/0` It looks like a fluke failure
 `[junit] Testcase: testScanXMLLog(com.liferay.portal.log.assertor.PortalLogAssertorTest):	FAILED
    [junit] 
    [junit] Portal log assert failure, see above log for more information: 
    [junit] HHH000315: Exception executing batch [java.sql.BatchUpdateException: Duplicate entry '20097-com.liferay.portal.kernel.model.LayoutPrototype-4-com.life' for key 'IX_A9FF4B2C'], SQL: insert into ResourcePermission (mvccVersion, ctCollectionId, companyId, name, scope, primKey, primKeyId, roleId, ownerId, actionIds, viewActionId, resourcePermissionId) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`

- The failure for `PGStaging#ActivateRemoteStaging` it's a poshi error, but we can see in the [poshi report ](https://testray.liferay.com/reports/production/logs/2022-07/test-1-38/test-portal-acceptance-pullrequest(master)/2305/functional-tomcat90-mysql57-jdk8/0/19/LocalFile.PGStaging_ActivateRemoteStaging/index.html.gz?authuser=0)that it's not related to your PR because the alert message is present.
`com.liferay.poshi.runner.exception.ElementNotFoundPoshiRunnerException: Element is not present at "//div[contains(@class,'alert') and contains(@class,'alert-success')]"`

cc: @john-co

**Comment by carloslancha** [comment]
Depends on https://github.com/liferay-frontend/liferay-portal/pull/2545

**Comment by carloslancha** [comment]
ci:forward

**Comment by john-co** [comment]
ci:test:sf

**Comment by john-co** [comment]
SF conflict against master?

**Comment by tinycarol** [comment]
ci:stop

**Comment by tinycarol** [comment]
ci:test:sf

**Comment by tinycarol** [comment]
ci:test:relevant

**Comment by tinycarol** [comment]
ci:test:relevant

**Comment by tinycarol** [comment]
ci:test:relevant

**Review by carloslancha — APPROVED** [review]

**Comment by john-co** [comment]
ci:test:security

**Comment by john-co** [comment]
Just started reviewing :)

**Comment by john-co** [comment]
Reviewed. Test failures are unrelated. :heavy_check_mark: 

Ok to manually forward from QA perspective.

**Comment by john-co** [comment]
Forwarded to https://github.com/brianchandotcom/liferay-portal/pull/122076

**Pull request closed without merging**
