### PR TITLE
LPS-130836 Fix header and background page disappear when opening a modal using ItemSelectorDialog

### PR DESCRIPTION
**Pull request by georgel-pop-lr**
LPS-130836 Fix header and background page disappear when opening a modal using ItemSelectorDialogdal when there is a scroll on the page

First fix `modal.render('body > div:last-child');` is making modal render in a separate DIV element at the end, in the body and not first as now.

Second we change the overflow added on the html element and on the modal. 
We leave overflow:hidden only on the body.

https://user-images.githubusercontent.com/59687465/115567487-9b1ec080-a2bb-11eb-93b0-6dffc62b0f06.mp4

### CODE REVIEW

**Comment by georgel-pop-lr** [comment]
ci:test:sf

**Review by markocikos — COMMENTED** [review]
@georgel-pop-lr I don't think we should forward this.

Please see https://github.com/liferay-frontend/liferay-portal/pull/976. In that PR, we are replacing the `ItemSelectorDialog` from the ticket test case with new React-based `openSelectionModal`. In the [ongoing epic](https://issues.liferay.com/browse/LPS-129246) we will replace all  `ItemSelectorDialog`s. New modal does not have this bug.

Sidenotes:
- This would be a pretty scary change, since we are globally modifying CSS classes used in multiple modules.
- I am kinda surprised that this is FP3 bug, it is very minor in my opinion :slightly_smiling_face:

**Comment by rolandpakai** [comment]
Hi @markocikos 

thank you for letting we known about the ongoing changes regarding the ItemSelectorDialog.

For this issue we have an https://issues.liferay.com/browse/LPP-40796 and a customer ticket too: https://liferay-support.zendesk.com/agent/tickets/42779

Do you think we need to backport to 73x the whole LPS-129246 Epic, or we can go only with the LPS-130706 Migrate asset categories selection modals ? 

Thanks, Roland

**Comment by markocikos** [comment]
> Do you think we need to backport to 73x the whole LPS-129246 Epic, or we can go only with the LPS-130706 Migrate asset categories selection modals ?

@rolandpakai Only asset categories modals, https://github.com/liferay-frontend/liferay-portal/pull/976, would not be enough. From the epic tasks, you would need to port any commits that modified the [openSelectionModal utility in Modal.js](https://github.com/liferay/liferay-portal/blob/master/modules/apps/frontend-js/frontend-js-web/src/main/resources/META-INF/resources/liferay/modal/Modal.js)

**Comment by rolandpakai** [comment]
I see. Thank you @markocikos 
And do you known when will be the LPS-130706  merged into Master?
And the Product Team is planning to backport some changes to 73x?

**Comment by wincent** [comment]
> And do you known when will be the LPS-130706 merged into Master?

As far as I know, all forwarding on tasks under that epic is paused, because the release has been delay many, many times due to regressions (blockers). Has happened to teams across the company, but in Frontend we've had it happen to us specifically. It is very clear to me that our CI coverage is inadequate (either tests don't exist, or if they do, they are not run in the name of speeding up the results or eliminating sources of flakiness) — so basically, until the GA is out and confirmed we run the risk of literally any change we make leading to unintended breakage, even if it fixes a different issue.

All of which is to say, we have to be patient in the short term, and in the long term continue working on making our automated tests better, faster, more robust etc.

**Comment by rolandpakai** [comment]
Thank you @wincent for the information.

Regarding the customer issue: 
https://issues.liferay.com/browse/LPP-40796 
https://liferay-support.zendesk.com/agent/tickets/42779

Do you think we need to create a unique fix for 73x or the Epic LPS-129246 will be backported to 73x?

Thanks, Roland

**Comment by wincent** [comment]
> Do you think we need to create a unique fix for 73x or the Epic LPS-129246 will be backported to 73x?

I would assume that the entire epic would not be backported unless there is strong evidence that doing so will eliminate an entire category of bugs. Conversely, I can imagine backporting specific migration tasks to address isolated bugs (which seems to be what you're facing here) is much more likely.

But I am just a drive-by commenter here. I think @markocikos has a better handle on what the right strategy would be here.

**Comment by rolandpakai** [comment]
Based on @markocikos comment for solving the customer issue on 7.3 the LPS-130706 will be not enough, we will need any commits that modified the openSelectionModal utility in Modal.js

**Comment by markocikos** [comment]
> Do you think we need to create a unique fix for 73x or the Epic LPS-129246 will be backported to 73x?

I'd recommend backporting https://github.com/liferay-frontend/liferay-portal/pull/976 and few commits from LPS-129246, like https://github.com/brianchandotcom/liferay-portal/pull/100629/commits/5a3819f2a7937beb96014f26e8487affbaf4417a, https://github.com/brianchandotcom/liferay-portal/pull/100629/commits/9e97c89fd9541b70ddc6fd8919b48662cbee083a and https://github.com/brianchandotcom/liferay-portal/pull/100629/commits/cef980a3ccaa16c49790cddf041924b54b4862ad. There might be others with minor changes on `Modal.js`. I don't know if you can port only some commits or need to port whole tasks. If latter, then port LPS-130099 and any other that modify `Modal.js`.
- This should be safe, as `openSelectionModal` [does exist](https://github.com/liferay/liferay-portal/blob/7.3.x/modules/apps/frontend-js/frontend-js-web/src/main/resources/META-INF/resources/liferay/modal/Modal.js#L328-L424) on 7.3.x , and new changes are backwards-compatible.
- There shouldn't be any major conflicts, as the utility wasn't changed for a long time before this epic.
- A specific CSS-based fix may be risky, it can be done of course, but we would need to carefully test it.

I would only recommend creating a unique fix on 7.3.x if you need to fix this bug as quickly as possible. https://github.com/liferay-frontend/liferay-portal/pull/976 is on hold until release, and then it goes to product team review, so it'll be couple of days until merged for sure. The safest route would be to wait for epic to be complete and QA tested, there might be some bugs that we are not aware of yet. It's up to you really.

**Comment by georgel-pop-lr** [comment]
> > Do you think we need to create a unique fix for 73x or the Epic LPS-129246 will be backported to 73x?
> 
> I'd recommend backporting #976 and few commits from LPS-129246, like [brianchandotcom@5a3819f](https://github.com/brianchandotcom/liferay-portal/commit/5a3819f2a7937beb96014f26e8487affbaf4417a), [brianchandotcom@9e97c89](https://github.com/brianchandotcom/liferay-portal/commit/9e97c89fd9541b70ddc6fd8919b48662cbee083a) and [brianchandotcom@cef980a](https://github.com/brianchandotcom/liferay-portal/commit/cef980a3ccaa16c49790cddf041924b54b4862ad). There might be others with minor changes on `Modal.js`. I don't know if you can port only some commits or need to port whole tasks. If latter, then port LPS-130099 and any other that modify `Modal.js`.
> 
> * This should be safe, as `openSelectionModal` [does exist](https://github.com/liferay/liferay-portal/blob/7.3.x/modules/apps/frontend-js/frontend-js-web/src/main/resources/META-INF/resources/liferay/modal/Modal.js#L328-L424) on 7.3.x , and new changes are backwards-compatible.
> * There shouldn't be any major conflicts, as the utility wasn't changed for a long time before this epic.
> * A specific CSS-based fix may be risky, it can be done of course, but we would need to carefully test it.
> 
> I would only recommend creating a unique fix on 7.3.x if you need to fix this bug as quickly as possible. #976 is on hold until release, and then it goes to product team review, so it'll be couple of days until merged for sure. The safest route would be to wait for epic to be complete and QA tested, there might be some bugs that we are not aware of yet. It's up to you really.

Hi @markocikos,

I understand your point of view, but I check and the `openSelectionModal` would not be impacted by this CSS changes because it is not adding to the HTML element the class modal-open as ItemSelectorDialog is doing, from my tests everything seems to work just fine.

From my point of view I see it risky to backport something in a client branch without being fully tested or finished and this looks like a big epic with many changes that are still being reviewed.

IMHO I think we can move this fix only into the branch of 7.3.x but not in master as we already work into changing it. Then @rolandpakai can give it to the client in a patch, this after he tests and confirm that everything works well, and we wait until this epic is fully done and tested, so we can backported. 

Let me know what you all think about this.

Regards.

**Comment by rolandpakai** [comment]
Hi @georgel-pop-lr , @markocikos 

let me summarize it:

- the "LPS-130836 Fix header and background page disappear when opening a modal using ItemSelectorDialog and there is a scroll on the page" commit should be a unique fix on 73x
- the LPS-130836 can be provided in a hotfix for the customer
- later backport the whole Epic LPS-129246 Or only just a few task fE: LPS-130706, LPS-130099 and any other that modify Modal.js.

Thanks, Roland

**Comment by markocikos** [comment]
> * the "LPS-130836 Fix header and background page disappear when opening a modal using ItemSelectorDialog and there is a scroll on the page" commit should be a unique fix on 73x
> * the LPS-130836 can be provided in a hotfix for the customer
> * later backport the whole Epic LPS-129246 Or only just a few task fE: LPS-130706, LPS-130099 and any other that modify Modal.js.

Sounds good!

I'll close the PR, as we are in agreement that we don't want to merge to master.

**Pull request closed without merging**
