### PR TITLE
LPS-137320 Adjust relevant test suite filters for FI modules to run only acceptance tests

### PR DESCRIPTION
**Pull request by john-co**
**Description**
Based on discussion with CI team member [here](https://liferay.slack.com/archives/CL3TWSMHQ/p1628796204046000?thread_ts=1628788079.026700&cid=CL3TWSMHQ), it's not feasible to have comparison unique failure logic in PR tester against non-acceptance tests. Therefore, we need to modify our relevant test suite filters to exclude non-acceptance tests.

**Test Plan**
1. Run relevant test suites for FI module changes, they only run acceptance tests.

**JIRA Ticket**
https://issues.liferay.com/browse/LPS-137320

### CODE REVIEW

**Comment by john-co** [comment]
ci:test:sf

**Comment by john-co** [comment]
Reviewed. Test failures are unrelated. :heavy_check_mark:

**Comment by john-co** [comment]
Hi @iovaneale @Pietro69 @lorenzolapescara , could you please take a look at the two failing commerce tests? They've been failing since a couple work days ago. I've identified that they're not related to the PR, just wanted to let you guys know since it impacted our team's `ci:forward`

**Comment by lorenzolapescara** [comment]
Hi @john-co a fix for these 2 failing tests has been sent [here](https://github.com/liferay-commerce/liferay-portal/pull/1578). Thanks!

**Comment by john-co** [comment]
Pushed to https://github.com/brianchandotcom/liferay-portal/pull/105646

**Pull request closed without merging**
