### PR TITLE
LPS-115880 - Fix global menu horizontal scroll

### PR DESCRIPTION
**Pull request by marcoscv-work**
This PR solves the error with the unwanted horizontal scroll in the Global menu by adjusting the spacing:
image

---

**Usage Tests:**

To test the fix it is necessary to have a mouse connected to your mac / windows / linux, then you just have to start Liferay portal and click on the Global Menu icon:

image

The menu will appear without the horizontal scroll:

image

### CODE REVIEW

**Comment by jbalsas** [comment]
@marcoscv-work, please read through our [Code Review Guidelines](https://github.com/liferay/liferay-frontend-guidelines/blob/master/dxp/code_review.md) and fix this PR so we can all have an easier time processing it.

**Comment by marcoscv-work** [comment]
sorry, I had to leave urgently while writing description, I'will try to write the description before sending the PR

**Comment by marcoscv-work** [comment]
ci:test:sf

**Comment by marcoscv-work** [comment]
ci:test:stable

**Comment by marcoscv-work** [comment]
ci:test:relevant

**Comment by marcoscv-work** [comment]
> I don't see any problem with the change. That irregular padding is a bit specific but I think this is an unique case.

image

The reason is the space between menu text on the left side vs the margin until gray block on the right side, the columns and list have its own spacers.
Finally, with the custom paddings, everything is on its side

**Comment by marcoscv-work** [comment]
ci:test:relevant

**Comment by marcoscv-work** [comment]
ci:test:relevant

**Comment by marcoscv-work** [comment]
@john-co could you help us with this test? It does not look related

**Comment by john-co** [comment]
Reviewed. Test failures are unrelated. :heavy_check_mark: 

image

The test is failing in base branch (failure in common with upstream) and looks like failing on same error so likely not related.

Fix was recently merged https://github.com/brianchandotcom/liferay-portal/pull/90409

**Comment by jbalsas** [comment]
ci:forward

**Comment by jbalsas** [comment]
Ok, not forwarding either... will forward manually again :(

**Comment by jbalsas** [comment]
ci:stop

**Comment by john-co** [comment]
ci:stop

**Comment by john-co** [comment]
ci:stop

**Comment by jbalsas** [comment]
Forwarded manually to https://github.com/brianchandotcom/liferay-portal/pull/90434

**Pull request closed without merging**
