### PR TITLE
LPS-116884 Fix style of navigation-bar in form-builder

### PR DESCRIPTION
**Pull request by eduardoallegrini**
The visual bug was introduced by the new `<clay:navigation-bar>` taglib https://issues.liferay.com/browse/LPS-112470. In order to work with React it needs to be wrapped in a `<div>`.

**INPUT**
```jsp
<div>
   <clay:navigation-bar />
</div>
```
**OUTPUT BEFORE THE UPDATE**
```jsp
<div class="navigation-bar ... " >...</div>
```

**OUTPUT AFTER THE UPDATE**
```jsp
<div>
   <div class="navigation-bar ... " >...</div>
</div>
```
The CSS property `position: sticky` needs to be outside the `<div>` to works fine.

The proposed solution is to move [the sticky class](https://github.com/liferay/liferay-portal/blob/master/modules/apps/dynamic-data-mapping/dynamic-data-mapping-form-web/src/main/resources/META-INF/resources/admin/css/_general.scss#L214) `.forms-navigation-bar` outside the  navigation `<clay:navigation-bar>` taglib

**Result:**
ezgif com-video-to-gif

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
ci:test:sf

**Comment by jbalsas** [comment]
Well... this is a bit unfortunate, but better have it fixed and we can see if there's a better way to handle hydration wrappers in the future...

@brunobasto, @wincent, objections to this?

**Comment by jbalsas** [comment]
One thing I'd like to point out one last time is that the other navigation bars don't stick... so maybe this one shouldn't either and the only thing to fix should be the application-bar top position... we can deal with that in a followup, but might be something worth discussing with the Forms team.

@drakonux, thoughts?

**Comment by wincent** [comment]
> Well... this is a bit unfortunate, but better have it fixed and we can see if there's a better way to handle hydration wrappers in the future...
> 
> @brunobasto, @wincent, objections to this?

No objections, especially because there seems to be exactly one place where we need this special casing.

**Comment by brunobasto** [comment]
> One thing I'd like to point out one last time is that the other navigation bars don't stick... so maybe this one shouldn't either and the only thing to fix should be the application-bar top position... we can deal with that in a followup, but might be something worth discussing with the Forms team.

Yeah, I think we should get in touch with Felipe about that.

> @brunobasto, @wincent, objections to this?

Nope. It is what it is. If more stuff like this comes up, we might want to consider giving more control to the wrapper element? 

```jsp
<clay:navigation-bar
	id="formsNavigationBar"
        inverted="<%= true %>"
        navigationItems="<%= ddmFormAdminDisplayContext.getFormBuilderNavigationItems() %>"
        wrapperSelector="#myWrapper"
/>
```

or maybe just

```jsp
<clay:navigation-bar
	id="formsNavigationBar"
        inverted="<%= true %>"
        navigationItems="<%= ddmFormAdminDisplayContext.getFormBuilderNavigationItems() %>"
        wrapperCssClass="forms-navigation-bar"
/>
```

but I'm pretty sure we already discussed that previously. I just can't find the PR.

**Comment by drakonux** [comment]
Well, I don't like it (it's too much vertical space lost) and I couldn't find a benefit anchoring the navbar too. 

Normally, the convention it's to have sticky the part of a UI that is more or less essential when the user scrolls (main navigation and/or key actions).

But maybe this is ok for team-forms.

**Comment by jbalsas** [comment]
I was looking at the errors, thinking they were probably unrelated but saw this screenshot:

before0

Toolbar looks off... so holding this till we can investigate

**Comment by eduardoallegrini** [comment]
it depends on the `autosave-feedback`, when the screen size is small it takes a whole row

image

I've compared it with the latest stable version (7.3.2 CE GA3) and it's different

image

@jbalsas what's the best way to proceed?

**Comment by eduardoallegrini** [comment]
caused by https://issues.liferay.com/browse/LPS-117034 > https://github.com/natocesarrego/liferay-portal/pull/667 > https://github.com/brianchandotcom/liferay-portal/pull/91277

**Comment by jbalsas** [comment]
> @jbalsas what's the best way to proceed?

Is there anything we can do to fix this?

**Comment by eduardoallegrini** [comment]
> Is there anything we can do to fix this?

I would forward the current PR that fixes the reported issue and add a comment in Jira asking to open a new ticket for the new bugs explaining what we saw and why we think is happening

**Comment by jbalsas** [comment]
So this fix does not cause the issue? It wasn't clear to me :D

**Comment by eduardoallegrini** [comment]
> So this fix does not cause the issue?

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
ci:forward

**Pull request closed without merging**
