### PR TITLE
LPS-163590 - Update bundler and add package.json dependencies back in

### PR DESCRIPTION
**Pull request by bryceosterhaus**
https://issues.liferay.com/browse/LPS-163590

We previously declared all dependencies in package.json files but then realized this was causing significant slow down in build times because we were re-bundling dependencies that were already provided to the platform. So with this change, we now look to the global npmscripts.config.js for the bundler config and only bundle the dependency if it isn't already provided by another module.

With this change, we can disable and remove the [SF rule](https://issues.liferay.com/browse/LPS-148049) that removed all of the package.json dependencies.

cc @ling-alan-huang please take a look at this and see if I need to do anything else with the SF rule.

cc @natocesarrego since you originally discoevered the slow down of build times, could you verify here that by adding back in dependencies that we aren't slowing down the build times again? I tested it myself and it was consistent with current master builds, but just want you to verify as well in case you have more sophisticated tools for checking build speeds.

### CODE REVIEW

**Comment by izaera** [comment]
:ok_hand:

**Comment by bryceosterhaus** [comment]
@kresimir-coko yeah going forward we would add all dependencies to package.json, including frontend-js-web. However, even if this PR gets merged and you forget to add `frontend-js-web` it will still work as it did before this PR. This just allows us to be more verbose in our dependency list. So I don't think it'll bring any issues with it

**Comment by natocesarrego** [comment]
Hi @bryceosterhaus,

I just finished to run the script created by Brian and I realized the following:

- After a `git clean -fdx`, `master` was a little more than 1 minute **faster**
- Without Gradle cache only, `master` was 24s **faster**
- With all caches, `master` was 5s **slower**

Please check the evidences below:



 
Sorry about the quality of the images, but I've had some issues to take screen shots. :grin: 

Therefore, the impact of merging the `LPS-163590` will be realized only when there are no caches available on the machine running `ant all`.

@bryceosterhaus, feel free to share this analysis with Brian if he asks about perfomance decrease related to this pull request.

Thanks

**Comment by natocesarrego** [comment]
Hi @bryceosterhaus,

Answering your questions:
> Am I correct in seeing that?

Yes

> That seems like a really large separation, especially when considered against your other tests. Do you think the 7 minute difference is really due to my changes or do you think it stems from the other processes that were going on?

Honestly, I don't think your proposed changes are causing the 7 minutes delay, probably, it might be caused by a high load in the network traffic. IMHO, we can consider [my latest runs](https://github.com/liferay-frontend/liferay-portal/pull/2753#issuecomment-1262879241) as a performance analysis. Even though, I believe that it worth take a look on the reports mentioned [here](https://github.com/liferay-frontend/liferay-portal/pull/2753#issuecomment-1262334792), since they can assist us identify the biggest build time offenders. :slightly_smiling_face:

Thanks for your partnership!

**Comment by izaera** [comment]
Just wanted to note some things about the tests...

1. 8 seconds out of 8 minutes is small enough to be a normal deviation
2. The tests should be run without any other user interaction in the system, since that tends to make times much faster and deviate a lot from the mean.
3. If we wanted to do this correctly (statistically speaking) at the very least we should run several ant alls with and without the LPS and make an statistical check of both data sets to see if the difference is significant. We may also want to check the statistical power of the experiment (https://www.scribbr.com/statistics/statistical-power/).

3 may sound overkill but it's the only correct way to check these things :shrug: 

Note that I admit that I haven't done it that way either when I've made performance changes, but maybe we should start doing it :thinking: In the end, we are talking about hundreds of machines running ant all every day...

**Comment by bryceosterhaus** [comment]
> 1. 8 seconds out of 8 minutes is small enough to be a normal deviation

Yeah I agree, 8 seconds seems pretty negligible compared to 8min.

> 2. The tests should be run without any other user interaction in the system, since that tends to make times much faster and deviate a lot from the mean.

I am getting a VM for running nightly performance tests, and one thing we could also add on that machine is testing how long the bundle process takes in DXP. That way we could track larger deviations. The nightly performance checks should only be run once or twice a day, so we can utilize the other machine time with build times for our FE tools.

> 4. If we wanted to do this correctly (statistically speaking) at the very least we should run several ant alls with and without the LPS and make an statistical check (eg: https://online.stat.psu.edu/statprogram/reviews/statistical-concepts/hypothesis-testing/p-value-approach) of both data sets to see if the difference is significant. We may also want to check the statistical power of the experiment (https://www.scribbr.com/statistics/statistical-power/).

I've run some tests to iterate several `ant all`'s and log the times, but the deviation between runs(both master and the LPS) could be upwards of 3-4 minutes, so I couldn't ever get anything conclusive for comparing before/after. I suspect I would need to run this in a more efficient machine without any other process going on.

**Comment by bryceosterhaus** [comment]
ci:test:sf

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by izaera** [comment]
All this -> https://github.com/liferay-frontend/liferay-portal/pull/2753#issuecomment-1266446555 sounds quite good :clap: 

I've also experienced huge variations from time to time. I suspect they are due to network, but it could be disk I/O too...

Once you setup the machine for tests, maybe we could try to run the builds without network access so that we can get rid of that source of variation... :thinking:

**Comment by bryceosterhaus** [comment]
ci:test:sf

**Comment by bryceosterhaus** [comment]
So I ran some custom tests just to test the total `yarn build` times and the comparison with master and this LPS is negligible, so I think this is safe to merge in terms of build times. 

As for CI, I will try to get that cleared up today and then forward

**Comment by natocesarrego** [comment]
Hey fellows,

I totally agree with you, @izaera, about the ideal way to measure performance! :slightly_smiling_face:

Actually, I told Brian Chan that, in my opinion, we should check performance increase/decrease after each commit merged or, at least, every day, otherwise track performance changes will be harder. :disappointed: I started to work on a way to measure it through https://issues.liferay.com/browse/LPS-150619, however I wasn't able to move on with it due to other priorities of Hotel Team.

In addition, just to let you guys know, [my last tests using Brian's script](https://github.com/liferay-frontend/liferay-portal/pull/2753#issuecomment-1262879241) were performed just running `ant all`, e.g., no other processes were running on my machine.

I hope the information above can help and I'm also opened to contribute with you regarding this matter. :smile:

**Comment by bryceosterhaus** [comment]
ci:test:sf

**Comment by bryceosterhaus** [comment]
ci:test:sf

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by mateusralv** [comment]
I'm taking a look 🕵🏽

**Comment by mateusralv** [comment]
Hi @bryceosterhaus I made a [comparison run with master ](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1665065171980&testrayRunIdA=1998268182&testrayRunIdB=1998170147) and the most failures is not relates to your PR, but one test seems related as it's only failing this PR, when you have time could you check it out? Thanks advance :)

### Unique failure: 
[com.liferay.headless.admin.taxonomy.resource.v1_0.test.TaxonomyCategoryResourceTest](https://testray.liferay.com/home/-/testray/case_results/1998179869)
I ran the test locally and it returned the error:
```
com.liferay.headless.admin.taxonomy.resource.v1_0.test.TaxonomyCategoryResourceTest > classMethod FAILED
    java.net.ConnectException: Connection refused (Connection refused)
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at java.net.Socket.connect(Socket.java:538)
        at java.net.Socket.<init>(Socket.java:434)
        at java.net.Socket.<init>(Socket.java:244)
        at com.liferay.arquillian.extension.junit.bridge.client.FrameworkState.connect(FrameworkState.java:62)
        at com.liferay.arquillian.extension.junit.bridge.client.ClientState.open(ClientState.java:76)
        at com.liferay.arquillian.extension.junit.bridge.junit.Arquillian.run(Arquillian.java:120)
        at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
        at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
        at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
        at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
        at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
        at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
        at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
        at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:119)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
        at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
        at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:414)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
        at java.lang.Thread.run(Thread.java:748)

1 test completed, 1 failed
There were failing tests. See the report at: file:///home/me/dev/projects/liferay-portal/modules/apps/headless/headless-admin-taxonomy/headless-admin-taxonomy-test/build/reports/tests/testIntegration/index.html

```
---

### Failures, not unique or flaky: 

1. js-unit-jdk8/0/0
2. LocalFile.DisplayPageTemplatesWithMapping#ViewTypesDuringCreation
3. com.liferay.headless.admin.taxonomy.resource.v1_0.test.TaxonomyCategoryResourceTest
4. com.liferay.oauth2.provider.client.test.AnnotationsAndHttpPrefixApplicationClientTest
5. com.liferay.oauth2.provider.token.endpoint.test.RefreshTokenAuthorizationGrantTest
6. LocalFile.ObjectPermission#CanDeleteSingleObjectEntryWithDeletePermission
7. LocalFile.ObjectPermission#CanEditItsOwnEntryWithOnlyAddPermission
8. LocalFile.ObjectPermission#CanViewSingleObjectEntryWithViewPermission

**Comment by bryceosterhaus** [comment]
@mateusralv I just ran the test locally and it seems to pass for me. I also wouldn't expect that test to fail either because I haven't updated any code that would reflect in the UI, all my changes here would just be at build time

**Comment by bryceosterhaus** [comment]
ci:test:sf

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
ci:test:sf

**Comment by bryceosterhaus** [comment]
Because this PR touches pretty much every module and triggers so many tests in portal, I think it makes sense to forward to BChan once SF is green. The previous unique failure seemed to be flakey, as it passed locally for me.

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
manual forward at https://github.com/brianchandotcom/liferay-portal/pull/124234

**Comment by bryceosterhaus** [comment]
I additionally spawned this issue, https://github.com/liferay/liferay-frontend-projects/issues/1026 to investigate

**Comment by john-co** [comment]
Reviewed. Test failures are unrelated. :heavy_check_mark: 

Ok to manually forward from QA perspective.

[Testray Comparison
](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=3&testrayRunIdB=2003359691&testrayRunIdA=2003425622&statusB=2
)

cc/ @gaborlovasdotcom @JoyceWang08211 Oauth2 tests look somewhat inconsistently failing.

cc/ @timpak [ObjectPortlet#CannotViewOtherUsersEntryWithOnlyAddPermission](https://testray.liferay.com/home/-/testray/cases/1575708291) is sporadically failing

**Pull request closed without merging**
