### PR TITLE
LPS-169287 HR_322 Dynamic Loading spinner has no equivalent alt-text

### PR DESCRIPTION
**Pull request by ethib137**
Resending from: https://github.com/liferay-frontend/liferay-portal/pull/3275

Fixes https://issues.liferay.com/browse/LPS-169287

I'm sending this fix because JAWS is not reading correctly the status message. It's necessary to take into account the loading status inside the StatusMessage component to ensure that the screen reader reads the message.

cc @eltonccdantas

### CODE REVIEW

**Comment by ethib137** [comment]
ci:test:relevant

**Comment by mateusralv** [comment]
hi @ethib137 The failures are not related, seems safe to forward 🚀 

[Testray Comparison](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1683139489761&testrayRunIdA=2287196876&testrayRunIdB=2288122956)

**Comment by mateusralv** [comment]
Hi @ethib137 Can we forward this PR?

**Comment by eltonccdantas** [comment]
> If this has been approved by frontend infra we can forward it. I didn't see a review by frontend infra though. @eltonccdantas Has this been approved by FI? You seem to indicate it already has [here](https://liferay.slack.com/archives/CNBG06JS3/p1683640110675429?thread_ts=1683639711.675249&cid=CNBG06JS3).

Hey @ethib137 , it seems safe to forward it from a QA perspective.

What do you think @markocikos , is that ok from a developer's perspective?

**Review by markocikos — APPROVED** [review]
@ethib137  LGTM! :sparkles: 

A question inline, not blocking. Feel free to forward if you prefer to keep PR as it is.

**Comment by ethib137** [comment]
ci:forward:force

**Comment by ethib137** [comment]
ci:forward:force

**Pull request closed without merging**
