### PR TITLE
LPS-165847 Investigation into testing failures of the WalkthroughSiteLevel file 

### PR DESCRIPTION
**Pull request by mateusralv**
Description
Some tests of the WalkthroughSiteLevel file are unstable, as discussed in this [thread](https://liferay.slack.com/archives/CD7939WBE/p1668444591251979) the problem may be caused in the osgi module that is doing the deploy. The idea was to reduce the dependency of this module, using only for a sample (frontend-js-walkthrough-sample-web).  

Test Plan

- [x] Run fix on RCA [#7​74​3](https://test-1-1.liferay.com/job/root-cause-analysis-tool/7743/): failed 8% 

 
JIRA TICKET
https://issues.liferay.com/browse/LPS-165847

### CODE REVIEW

**Comment by mateusralv** [comment]
ci:test:frontend:nocompile

**Comment by john-co** [comment]
ci:test:frontend:nocompile

**Comment by john-co** [comment]
ci:test:frontend:nocompile

**Comment by mateusralv** [comment]
ci:forward

**Pull request closed without merging**
