### PR TITLE
LPS-145311: Batch methods created by the buildREST task don't account for deprecation

### PR DESCRIPTION
**Pull request by sergiojimcos**
**What is new?**
- Set deprecated Batch method if its parent method is in `ResourceOpenAPIParser`.

**Steps to reproduce:**

1. Go to headless-forms-impl's rest-openapi.yaml, path "/forms/ {formId}/form-records"'s post method and check that it is deprecated;
2. Run the task gw buildREST in the module;
3. Check BaseFormRecordResourceImpl's method postFormFormRecordBatch.

**BEFORE PR:**
The batch method is not deprecated.

**AFTER PR**
The batch method should be deprecated as the one which originated it.

**JIRA Ticket:**
https://issues.liferay.com/browse/LPS-145311

cc/ @4lejandrito

### CODE REVIEW

**Comment by 4lejandrito** [comment]
Awesome @sergiojimcos! 👍

**Comment by sergiojimcos** [comment]
ci:test:relevant

**Comment by susanchen3** [comment]
Reviewed, test failures are unrelated! Looks good to manually forward from QA perspective :) :heavy_check_mark:

**Comment by sergiojimcos** [comment]
> Reviewed, test failures are unrelated! Looks good to manually forward from QA perspective :) heavy_check_mark

Thanks Susan!! :blush:

**Comment by sergiojimcos** [comment]
ci:forward

**Review by LuismiBarcos — APPROVED** [review]
LGTM :) 👏 👏 👏

**Comment by sergiojimcos** [comment]
Manual forwarding: https://github.com/brianchandotcom/liferay-portal/pull/121985

**Pull request closed without merging**
