### PR TITLE
LPS-154538 Export PortletURL utils and import them throughout the codebase

### PR DESCRIPTION
**Pull request by kresimir-coko**
Reopening a PR ([original PR](https://github.com/liferay-frontend/liferay-portal/pull/2355)) after sorting the type definition properly, [prompted by Brian here](https://github.com/brianchandotcom/liferay-portal/pull/118909/#issuecomment-1156914512).

### CODE REVIEW

**Comment by kresimir-coko** [comment]
ci:test:relevant

**Review by bryceosterhaus — APPROVED** [review]
LGTM!

**Comment by kresimir-coko** [comment]
ci:test:relevant

**Comment by kresimir-coko** [comment]
ci:forward

**Comment by kresimir-coko** [comment]
ci:stop

**Comment by kresimir-coko** [comment]
ci:forward

**Comment by kresimir-coko** [comment]
ci:reopen

**Comment by kresimir-coko** [comment]
ci:forward

**Comment by kresimir-coko** [comment]
Manually forwarded https://github.com/brianchandotcom/liferay-portal/pull/119359

**Pull request closed without merging**
