### PR TITLE
LRQA-63724 - Add a base workflow metrics test to environment acceptance

### PR DESCRIPTION
**Pull request by john-co**
Ok to backport in 7.x branches.

**Description**
This aims to fix a regression test gap between workflow metrics and FI modules. Since some FI modules target only environment.acceptance tests and no workflow metrics test cases had set that property, it allowed a FP5 regression to get past `ci:test:relevant` testing. I contacted @rodrigocunhaa (Workflow QA) and we agreed that WorfklowMetrics#ViewReports would be a good smoke test to include in environment.acceptance.

**Test Plan**
1. Edit some code in frontend-js directory
2. Run ci:test:relevant in PR
3. Assert that a base workflow metrics test was included in test result

**JIra Ticket**
https://issues.liferay.com/browse/LRQA-63724

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:forward

**Comment by jbalsas** [comment]
> This aims to fix a regression test gap between workflow metrics and FI modules

Forwarding on the basis that @rodrigocunhaa agreed, but I don't think this is the right approach long-term. 

I don't see how there's such a thing as a gap between workflow metrics and FI modules. To me, there's simply a gap in testing FI modules. That's completely unrelated from Workflow Metrics. If we broke something, we should find a way to test it independently of Metrics. 

What happens if the workflow metrics app changes? Chances are whatever it is incidentally testing now, won't be in the future. We've only temporarily patched the gap because the fix is not under our control. Furthermore, we're artificially changing the relevance of a Product Team's test.

Summarizing my thoughts.
- Adding a Worfklow Metrics test to acceptance sounds okay. It should be something the PT decides, though.
- We should not depend on Product Team tests to test Infrastructure. Doing so does not cover gaps in FI testing.

/cc @manoelcyreno, @PablitoBonito

**Comment by manoelcyreno** [comment]
@john-co , please add this use case to your gap list, this is one example of a gap that we need to work to prevent for the future ...
If we need to talk with the PT teams to understand better "how they are using our libraries", let's do it, to create more clear and real tests...

**Comment by john-co** [comment]
added to test gap list.

**Pull request closed without merging**
