### PR TITLE
LPS-142100 - Update @liferay/eslint-plugin and apply SF changes

### PR DESCRIPTION
**Pull request by bryceosterhaus**
https://issues.liferay.com/browse/LPS-142100

This is a collection of all the new rules we have applied to our eslint-plugin in v1.1.0.

- adds new rule to check for null before typeof object
- adds new rule to disalllow anonymous functions as exports
- adds new rule to disallow 'use strict' in es modules
- adds one-var rule to our rulelist
- adds plugin to enforce 'catch' for every promise
- adds rule for enforcing useState naming pattern
- adds rule for useRef naming pattern
- adds rule to avoid explicit references to localhost
- adds rule to make sure expect() has an assertion
- adds rule to prefer dataset
- apply new sorting rule
- enable eqeqeq rule to enforce type-safe equality operators
- enable rule for sorting interface keys
- enable valid-typeof rule

A few notes:
- `eqeqeq` rule
    - To ensure safety, I added some additional checks in the code. These are not meant to be prescriptive for future code, but trying to protect from regressions with a large refactor like this. Examples:
        - `someVal == null` -> `someVal === null || someVal === undefined`
        - `someVal == 1` -> `Number(someVal) === 1`
- `no-anonymous-functions` 
    - This helps debugging to have all exported functions named.
        - "MyFileName.js" `export default () => {}` -> `export default function MyFileName() {}`
        - "index.js" `export default () => {}` -> `export default function main() {}`
- I've disabled the promise rule for now. It was going to require 300 manual changes and it just didn't seem worth it right now.

### CODE REVIEW

**Comment by bryceosterhaus** [comment]
ci:test:sf

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by nhpatt** [comment]
ci:test:sf

**Comment by bryceosterhaus** [comment]
@nhpatt what sort of magic do you possess? CI does whatever you ask

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by nhpatt** [comment]
@bryceosterhaus it's CI karma, you have to get 100000 rejections until it starts passing every time.

Good luck with the ci:test:relevant, it's impossible that it will pass, as you are executing all the modules with those 1200 files changed. I'd say that a quick review of the results, see if there is any possible breaking change and send directly... if we wait for the "release" we'll have many conflicts. If we don't wait we could potentially break something... but I don't think we're close to a "release". Time will tell :)

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
ci:test:sf

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by john-co** [comment]
@magjed4289 can you check on the unique test failures?

**Comment by john-co** [comment]
Created a wiki article on the Testray comparison tool I showed @magjed4289 : https://liferay.atlassian.net/wiki/spaces/QA/pages/1932827110/How+to+Use+Testray+Comparison+Tool

cc/ @Esther-OC

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
ci:test:sf

**Comment by john-co** [comment]
Just started reviewing :)

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
ci:stop

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by john-co** [comment]
The test failures do seem related to the PR but I didn't get a chance to look in detail to try and reproduce the issue and understand what's going on yet. Maybe @Esther-OC or @magjed4289 can follow up on this. If not I can take a look tomorrow morning.

**Comment by Esther-OC** [comment]
Failures review analysis started.

**Comment by Esther-OC** [comment]
After comparing some runs, we can conclude that there are 68 unique failures related to the PR.  Focusing on some FI components, there are tests that belong to the same group and seems that they are failing for the same reason, not related specifically to the test but to a behaviour or action that is not executed as expected.

### User Interface:
**Balloon Editor and WYSIWYG:**  
Some steps of this group of tests cannot be performed because the balloon editor toolbar is not displayed.  So, without it, it is not possible to continue with the correct performance as the next steps are related to actions in this toolbar.


### Translations Management:
**Translations:** 
The problem in these tests seems that change of the locale is not well performed, although the step passes:
```
PortletEntry#changeLocale --> PASSED
Assert that '//fieldset[@disabled]' is not available --> PASSED
Click on 'LOCALIZATION_GENERIC' --> PASSED
Click on 'LOCALIZATION_NAME' --> PASSED
```
As the locale has not been changed,the next steps are not executed correctly.  For instance, the title cannot match because the expected text is supposed to be in Spanish but it remains in English due to the locale is still ‘en-US’.

cc: @bryceosterhaus

**Comment by bryceosterhaus** [comment]
@Esther-OC was this compared against `liferay/liferay-portal` upstream or `brianchandotcom/liferay-portal` upstream? 

I am working off of Brian's base since the possibility of merge conflict is so high.

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
ci:stop

**Comment by bryceosterhaus** [comment]
closing and going to reopen in a new PR

**Comment by bryceosterhaus** [comment]
https://github.com/liferay-frontend/liferay-portal/pull/1673

**Comment by magjed4289** [comment]
ci:help

**Pull request closed without merging**
