### PR TITLE
LPD-40977 Fix ContentSecurityPolicy tests

### PR DESCRIPTION
**Pull request by jgarcialr**
Hi @liferay-frontend  team,
https://liferay.atlassian.net/browse/LPD-40977

I've sent this PR because the latest changes in ContentSecurityPolicy makes this test fails.
Could you review the PR and let me know if there are further changes to make?

I've already launched ci:test:security suite for this PR and with the changes, the tests now pass.
https://github.com/liferay-appsec/liferay-portal/pull/2073#issuecomment-2486051769

Thanks in advance :)

### CODE REVIEW

**Comment by jgarcialr** [comment]
ci:test:relevant

**Comment by izaera** [comment]
As agreed in Slack conversations, @jgarcialr is taking care of this PR since it is changing poshi tests owned by App Sec itself. Currently suggested options are removing the tests, or moving them to integration if possible, but we will wait for Stian to see what he thinks.

**Comment by stian-sigvartsen** [comment]
The ownership continues to be discussed, but the changes @jgarcialr have made do not change the expectations so we will forward them to avoid having a continuously failing test in the mean time.

**Comment by stian-sigvartsen** [comment]
ci:forward:force

**Pull request closed without merging**
