### PR TITLE
LPS-128886 The display style of the assign user will be affected when editing the display style of users

### PR DESCRIPTION
**Pull request by markocikos**
Fixes: https://issues.liferay.com/browse/LPS-128886

See description and test case in the linked JIRA ticket.

The bug was that two search containers stored the display styles under the same key. In this PR, we are making them unique.

After fix, the display style in user selection remains saved:
after

/cc @ealonso @jbalsas

### CODE REVIEW

**Comment by jbalsas** [comment]
Hey @markocikos, just to confirm, one of the described effects in the issue was that that ManagementToolbar state was inconsistent with the style displayed in the searchContainer. Could you verify if that is indeed fixed by this and we're passing the proper state to both components in sync?

**Comment by markocikos** [comment]
> Hey @markocikos, just to confirm, one of the described effects in the issue was that that ManagementToolbar state was inconsistent with the style displayed in the searchContainer. Could you verify if that is indeed fixed by this and we're passing the proper state to both components in sync?

@jbalsas Yes, I was able to verify what you are describing. It is not fixed with this PR. It is a separate issue, unrelated to the one this ticket is describing.

This ticket is describing how the display style is incorrect in the item selector. This is unrelated to management toolbar. The issue comes from the fact that two search containers, more specifically two display contexts, saved the display type under the same key.

A separate issue is that management toolbar is not displaying the stored display type. I'll work on this today, but it might be tricky. On first glance, this looks like something that would require extending management toolbar API and updating all usages.

I'd recommend pushing this PR as it is, as it fixes the described issue, and working on management toolbar bug in a separate ticket.

**Comment by jbalsas** [comment]
> I'd recommend pushing this PR as it is, as it fixes the described issue, and working on management toolbar bug in a separate ticket.

Sounds good to me, could you create such a ticket and get on with it? 🙏

**Comment by markocikos** [comment]
Opened https://issues.liferay.com/browse/LPS-129169

**Comment by jbalsas** [comment]
ci:forward

**Pull request closed without merging**
