### PR TITLE
[dont merge yet] LPD-37109 Prevent "Custom Javascript" injection from interfering with other injected JS in the page

### PR DESCRIPTION
**Pull request by dsanz**
References:
 *  [LPD-37109](https://liferay.atlassian.net/browse/LPD-37109)
 * https://stackoverflow.com/questions/42036349/uncaught-typeerror-intermediate-value-is-not-a-function

In this PR we are IIFE'ing custom JS snippets added to the page. This way we prevent them to be interpreted in wrong ways.

### Before
image

Note I did not want to use `sandbox="true"` feature in aui:script because it adds 2 variables to the IIFE (see second red box in above screenshot), which sounds like a terrible idea as snippet is not expecting it.

### After
image

DO NOT MERGE: this PR is to validate approach, tests are missing

### CODE REVIEW

**Comment by dsanz** [comment]
@bryceosterhaus @izaera Is this proposal aligned with what you had in mind?

**Comment by izaera** [comment]
@dsanz Yes. Only caveat is I'm not sure if you need the IIFE is you are using different `<aui:script>` invocations for each snippet... IIRC you could simply use `sandbox`. In any case I don't care too much if we use an IIFE vs using sandbox... :shrug:

**Comment by dsanz** [comment]
>  IIRC you could simply use `sandbox`. In any case I don't care too much if we use an IIFE vs using sandbox... 🤷
I did not choose sandbox because this is introducing a bigger problem: 2 variables
```
var $ = AUI.$;var _ = AUI._;		
// function code goes here
```

@fortunatomaldonado let's think about how to add tests here so that we can complete the PR. If in doubt pls ping me

**Comment by fortunatomaldonado** [comment]
@dsanz, yeah I believe we can do this by checking the console for errors. 
Only question is which component should we add this too in playwright?

**Comment by dsanz** [comment]
After some thoughts perhaps the best place is to create a `portal-web` folder  in pw tests. Makes sense @izaera ? any better idea?

**Comment by dsanz** [comment]
@fortunatomaldonado pls move forward with adding the `portal-web` as we spoken. I've confirmed with @izaera that it's the option we prefer

**Comment by fortunatomaldonado** [comment]
Hello @dsanz

It turns out that the error is not showing up when trying to reproduce with playwright. I am able to get the error when regular browser.

This is the error that I am looking for.
`Uncaught TypeError: (intermediate value)(...) is not a function`

I'm not sure how else to test for this fix without the error.

**Comment by fortunatomaldonado** [comment]
I created playwright test and fwd https://github.com/liferay-frontend/liferay-portal/pull/4457

**Pull request closed without merging**
