### PR TITLE
LPS-160134 Bring back state management to the GoogleMapsDialog class

### PR DESCRIPTION
**Pull request by kresimir-coko**
As per @bryceosterhaus's comment https://github.com/liferay-frontend/liferay-portal/pull/2679#pullrequestreview-1100208946

### CODE REVIEW

**Review by bryceosterhaus — APPROVED** [review]
LGTM!

**Comment by kresimir-coko** [comment]
ci:forward

**Comment by bryceosterhaus** [comment]
@kresimir-coko you can just manually forward since QA gave approval on slack

**Comment by kresimir-coko** [comment]
ci:stop

**Comment by kresimir-coko** [comment]
Manually forwarded to https://github.com/brianchandotcom/liferay-portal/pull/122857

**Comment by john-co** [comment]
cc/ @vicnate5 fyi probably flaky upgrade test impacted `ci:test:relevant`

**Pull request closed without merging**
