### PR TITLE
LPS-130629 clay:button is not adding type="button" as before

### PR DESCRIPTION
**Pull request by markocikos**
Fixes: https://issues.liferay.com/browse/LPS-130629

See descriptions and steps to reproduce in the ticket.

In `ClayButton`, we are [setting](https://github.com/liferay/clay/blob/master/packages/clay-button/src/Button.tsx#L62) `type="button"` as default. This is a good default behavior, as we are preventing unintended form submissions.

But, `<clay:button>` tag does not always use `ClayButton` to hydrate. If we [don't have a reason to](https://github.com/liferay/liferay-portal/blob/master/modules/apps/frontend-taglib/frontend-taglib-clay/src/main/java/com/liferay/frontend/taglib/clay/servlet/taglib/ButtonTag.java#L146-L148), we are only doing server-side rendering. This optimization makes sense, as we are almost always rendering simple buttons. The problem is that SSR does not set `type="button"` as default. In this PR, we are adding that, matching SSR with Clay markup.

### CODE REVIEW

**Review by jbalsas — APPROVED** [review]
LGTM! 

sealofapproval

**Comment by julien** [comment]
Change looks good to me too - and the explanation is clear.

Just adding these .gifs, to show the difference between before and after these changes.

**Before**


**After**

**Review by julien — APPROVED** [review]

**Comment by wincent** [comment]
Seeing as other people approve... I feel the urge to join in.

kylo-approves

**Comment by markocikos** [comment]
@john-co The unique failure seems unrelated. Can we push this manually?

**Review by ambrinchaudhary — APPROVED** [review]

**Comment by markocikos** [comment]
ci:forward

**Comment by john-co** [comment]
sorry was out of office last Friday. But looks like the last `ci:forward` got through :raised_hands:

**Pull request closed without merging**
