### PR TITLE
COMMERCE-9809 DI - BatchEngine - nested objects in CSV/XLS

### PR DESCRIPTION
**Pull request by igorbeslic**

### CODE REVIEW

**Comment by igorbeslic** [comment]
s-headless

**Comment by 4lejandrito** [comment]
Hi @igorbeslic,

When I try to export an Object from objects I get a null pointer exception:

```
java.lang.NullPointerException: null
	at com.liferay.batch.engine.internal.writer.ColumnValuesExtractor._getColumnDescriptors(ColumnValuesExtractor.java:135) ~[?:?]
```

This is because `fieldNames` contains "createdDate" but `fieldMap` only contains "dateCreated" 🤷 . Should we ignore those missing fields? or is it a symptom of something much worse?

**Comment by igorbeslic** [comment]
@4lejandrito you did test with Liferay Object - lets sync up with this.
I had warned PMs about this.

**Comment by 4lejandrito** [comment]
@igorbeslic you cand send this to liferay-headless/liferay-portal.

**Comment by igorbeslic** [comment]
will redirect to headless-liferay

**Pull request closed without merging**
