### PR TITLE
LPS-120700 Fix inserting images in IE

### PR DESCRIPTION
**Pull request by julien**
This fixes [LPS-120700](https://issues.liferay.com/browse/LPS-120700), what was happening is that in IE when inserting an image, only a `<br>` tag was inserted.

before:

after:

### CODE REVIEW

**Comment by julien** [comment]
ci:test:sf

**Comment by julien** [comment]
ci:test:relevant

**Comment by julien** [comment]
ci:test:relevant

**Review by jbalsas — COMMENTED** [review]
I see a lot of code being removed here which makes we worry. I don't remember exactly what everything was doing, but I think for the most part some of it is ensuring that a new line is consistently inserted after the image and the cursor position is correct after the insertion.

Ideally we should track down when these changes were introduced and see if the issues that made us add them are either:
- No longer relevant
- No longer reproducible with the new code

**Comment by julien** [comment]
@jbalsas you're right, in [LPS-97889](https://issues.liferay.com/browse/LPS-97889) we fixed a bug where inserted images were duplicated in IE - I've tested using both ckeditor  and alloyeditor and this change does not re-introduce the issue

**Comment by jbalsas** [comment]
What about:
- [LPS-85966 IE11 - Cannot click drag handle of wide image in AlloyEditor](https://issues.liferay.com/browse/LPS-85966)
- [LPS-89414 Duplicate Image added via CKEditor in IE11/Cannot add image in AlloyEditor](https://issues.liferay.com/browse/LPS-89414)
- [IE11 AlloyEditor toolbar automatically appears after adding an image](https://issues.liferay.com/browse/LPS-94904)

**Comment by jbalsas** [comment]
Hey @julien, any comments on the other issues? Do you feel confident with this PR?

**Comment by julien** [comment]
@jbalsas I've been analyzing the issue and what might have caused it, I'm sorry for the delay, testing all this in IE11 inside VirtualBox does take some time. If you don't mind I'd like to keep on looking at this just enough to report what I've seen to be able to take a reasonable decision.

**Comment by julien** [comment]
I wanted to understand what was going on and that's why I took so long to reply:

I noticed that we changed the modals, in https://github.com/liferay-frontend/liferay-portal/pull/263, and I thought that it might have caused the issue, but that's not the case. 

With the current code in `master` the behaviour in IE11 is different than in Chrome or Firefox (not suprising)

When an image is selected in IE11, the Modal's [`onSelect`](https://github.com/liferay/liferay-portal/blob/32a093f36ac89639601447e22fa8b0211f5ae70c/modules/apps/frontend-js/frontend-js-web/src/main/resources/META-INF/resources/liferay/modal/Modal.js#L125) callback is invoked but the [`processClose`](https://github.com/liferay/liferay-portal/blob/32a093f36ac89639601447e22fa8b0211f5ae70c/modules/apps/frontend-js/frontend-js-web/src/main/resources/META-INF/resources/liferay/modal/Modal.js#L127) function never gets called which explains why the modal stays open even though "some" content is inserted in the editor.

The other thing I saw is that the code in [this](https://github.com/liferay/liferay-portal/blob/32a093f36ac89639601447e22fa8b0211f5ae70c/modules/apps/adaptive-media/adaptive-media-image-js-web/src/main/resources/META-INF/resources/ckeditor/plugins/adaptivemedia/plugin.js#L171) `if` block is never executed, and I can't explain it. I was lucky enough to have a laptop with Windows and IE11 and it behaves exactly the same way as when testing with IE11 in VirtualBox - that explains why in the ticket they mention that no image is inserted and that's also why I decided to change it. 

Concerning the other issues:

- [LPS-89414 Duplicate Image added via CKEditor in IE11/Cannot add image in AlloyEditor](https://issues.liferay.com/browse/LPS-89414):
  Not reproducible with my latest changes

  

- [LPS-85966 IE11 - Cannot click drag handle of wide image in AlloyEditor](https://issues.liferay.com/browse/LPS-85966):
  Not reproducible

- [LPS-94904 IE11 AlloyEditor toolbar automatically appears after adding an image](https://issues.liferay.com/browse/LPS-94904):
Not reproducible


> Do you feel confident with this PR?

Yes, I do

**Comment by carloslancha** [comment]
> Yes, I do

<a href="https://gitme.me/image?url=https%3A%2F%2Fmedia2.giphy.com%2Fmedia%2FNEvPzZ8bd1V4Y%2Fgiphy-downsized-medium.gif&token=yes" data-gitmeme-token="yes"></a>

**Comment by jbalsas** [comment]
> > Do you feel confident with this PR?
> 
> Yes, I do

chandlermustache

**Comment by jbalsas** [comment]
ci:forward

**Comment by julien** [comment]
ci:forward

**Comment by julien** [comment]
ci:test:sf

**Comment by julien** [comment]
ci:test:relevant

**Comment by julien** [comment]
ci:test:relevant

**Comment by julien** [comment]
ci:forward

**Pull request closed without merging**
