### PR TITLE
LPS-181648 | Test fix for FDSCustomView#CanCreateMultiple

### PR DESCRIPTION
**Pull request by abhnerramos**
**Description**
Investigate failure in FDSCustomView#CanCreateMultiple

**JIRA Ticket**
https://issues.liferay.com/browse/LPS-181648

### CODE REVIEW

**Comment by abhnerramos** [comment]
ci:stop

**Comment by abhnerramos** [comment]
ci:test:frontend

**Review by mateusralv — APPROVED** [review]
Good Job Abhner, Once ci:tes:frontend is finished and the test passes we can forward 🎉

**Comment by abhnerramos** [comment]
ci:test:frontend

**Comment by abhnerramos** [comment]
ci:test:sf

**Comment by abhnerramos** [comment]
ci:test:frontend

**Comment by abhnerramos** [comment]
ci:test:frontend

**Comment by abhnerramos** [comment]
ci:test:forward

**Pull request closed without merging**
