### PR TITLE
LPS-143394 RTL causes Sidebar Panel to be visible

### PR DESCRIPTION
**Pull request by oliv-yu**
https://issues.liferay.com/browse/LPS-143394

Search QA had noticed that a large side panel was visible in RTL, and it looks like it's not just in Search Experiences. Please review and let me know what you think?

Thank you!

---

Quick way to test it

* Go to apps menu -> Objects
* Click user
* Click Fields tab
* Click eye icon
* Switch to RTL adding /ar/ in the url

### CODE REVIEW

**Comment by victorg1991** [comment]
Hey @oliv-yu Can you provide us an example of this behaviour? It seems that search experience web is not available in master, how can we enable it?

Thanks :)

**Comment by lipusz** [comment]
Hi @victorg1991
1. Switch to DXP profile: `ant setup-profile-dxp`
2. Go to `modules/dxp/apps/search-experiences`
3. Run `gradlew clean deploy`

**Comment by oliv-yu** [comment]
Hi! Also I think another example you can check with is Liferay Objects.

**Comment by victorg1991** [comment]
@oliv-yu got it :) 

It works fine, LGTM

**Review by victorg1991 — APPROVED** [review]

**Comment by susanchen3** [comment]
Failures look unrelated to the PR, looks good to manually forward from QA side :D

**Comment by lipusz** [comment]
Can you guys try forwarding it? We need this for Blueprints. Thank you! :-)

**Comment by marcoscv-work** [comment]
LGTM!

**Review by edalgrin — APPROVED** [review]
About the CSS part: with the [new RTL Converter](https://github.com/liferay-frontend/liferay-portal/pull/1413) it should be fine 👍

**Comment by victorg1991** [comment]
ci:forward

**Pull request closed without merging**
