### PR TITLE
LPS-183569 | Test fix for Theme#CanBeAppliedToPage

### PR DESCRIPTION
**Pull request by abhnerramos**
**Description**
Test fix for Theme#CanBeAppliedToPage

**JIRA Ticket**
https://issues.liferay.com/browse/LPS-183569

### CODE REVIEW

**Comment by abhnerramos** [comment]
ci:stop

**Comment by abhnerramos** [comment]
ci:test:frontend

**Comment by abhnerramos** [comment]
@mateusralv LGTM! The failures are not related, could you take a look, please?

**Review by mateusralv — APPROVED** [review]

**Comment by mateusralv** [comment]
ci:forward

**Pull request closed without merging**
