### PR TITLE
LPS-178414 |Add ignore to FrontendDataSetAdminSearch#CanReturnNoMatchedResults

### PR DESCRIPTION
**Pull request by alexmds2004**
**Description:**
**Bug related:**
This test is failing because of this bug:
https://issues.liferay.com/browse/LPS-178414

### CODE REVIEW

**Comment by alexmds2004** [comment]
ci:test:sf

**Comment by alexmds2004** [comment]
ci:test:frontend

**Comment by alexmds2004** [comment]
@mateusralv have a look to see if it's right?

**Comment by alexmds2004** [comment]
ci:test:sf

**Comment by alexmds2004** [comment]
ci:test:frontend

**Comment by mateusralv** [comment]
Hey @alexmds2004 Could you change the commit message to LPS-178414? Thank you 😄

**Comment by alexmds2004** [comment]
> Ei@alexmds2004Você poderia mudar a mensagem?

**Comment by alexmds2004** [comment]
> Hey @alexmds2004 Could you change the message?

would the message be the title or the description?

**Comment by alexmds2004** [comment]
ci:test:sf

**Review by mateusralv — APPROVED** [review]
Good Job! Thanks 🚀 🎉

**Comment by mateusralv** [comment]
ci:forward

**Pull request closed without merging**
