### PR TITLE
LPS-147280 LPS-147278 Change way of validating PathParam annotation values for matching with Java 8 and Java 11

### PR DESCRIPTION
**Pull request by ccorreagg**
Related tickets:

- [LPS-147278](https://issues.liferay.com/browse/LPS-147278)
- [LPS-147280](https://issues.liferay.com/browse/LPS-147280)

This PR contains a change on the way of validating if an Annotation is related to a desired one with a specified value. In Java 8 it was working perfectly but in Java 11 the toString() method returned a different String.

It can be tested by launching the Integration Test **StructuredContentResourceTest.testGetAssetLibraryStructuredContentPermissionsPage**

Before the PR:

- In Java 8 this method:
```
annotation.toString()
```
returned the text `@javax.ws.rs.PathParam(value=assetLibraryId)`

- In Java 11 this method:
```
annotation.toString()
```
returned the text `@javax.ws.rs.PathParam(value="assetLibraryId")`

After the PR: **It is independent of the toString implementation**

### CODE REVIEW

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
ci:stop

**Comment by ccorreagg** [comment]
ci:test:relevant

**Review by javierdearcos — APPROVED** [review]
Perfect! Great job making it independent of the toString implementation.

Also finding the StringUtils.equalsAny. I didn't know about it and it is a very useful method

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by susanchen3** [comment]
- `yarnInstall` failed twice in a row, but CI was having issues earlier so I think its unrelated. Plus it didn't fail on a [previous run](https://github.com/liferay-frontend/liferay-portal/pull/2009#issuecomment-1069045987).   
- `lpkg-base-jdk8/0/0` keeps failing, but based on the [history](https://testray.liferay.com/home/-/testray/cases/1328274400) it looks like its failing for every PR :confused: 

Reviewed :heavy_check_mark: Looks good to forward :+1:

**Comment by ccorreagg** [comment]
Thank you @susanchen3 !

**Comment by ccorreagg** [comment]
PR sent to Brian https://github.com/brianchandotcom/liferay-portal/pull/114763
Closing this PR

**Pull request closed without merging**
