### PR TITLE
LPD-32489 Add PUT method to `Async` actions in DSM

### PR DESCRIPTION
**Pull request by markocikos**
### References

- Parent Story: [LPD-29358 [DataSetViewActions.testcase] Delete poshi](https://issues.liferay.com/browse/LPD-29358)
- Requires PR to be merged: https://github.com/liferay-frontend/liferay-portal/pull/4343

### What is the goal of this PR?

A small change in DSM, adding an option in select, bit of improvement. Further migration of action tests.

:warning: I'm opening this as a draft, as it requires https://github.com/liferay-frontend/liferay-portal/pull/4343 to be merged

### What does it look like?

image

image

### CODE REVIEW

**Comment by juanjofgliferay** [comment]
@markocikos LGTM. Just a minor thing. 
Would you mind adding the `DEFAULT_FETCH_HEADERS` to each fetch request in both `Actions.tsx` and `ActionsForm.tsx` files?

**Comment by markocikos** [comment]
Force-pushed, after https://github.com/liferay-frontend/liferay-portal/pull/4343 finally synced. Changes:
- Applied `DEFAULT_FETCH_HEADERS` to actions @juanjofgliferay 
- We're using `aria-label` in tab panes, instead of incorrect and previously removes `aria-labelledby`. There is no default ID in this case, so I think using `aria-label` simpler than adding `ID`. @dsanz 

I'll (try to) forward this right away, as I think changes are pretty straightforward. I am already working on a followup, so if you think anything else is needed, I'll include it in that one.

**Comment by markocikos** [comment]
ci:forward

**Review by juanjofgliferay — APPROVED** [review]
LGTM :rocket:

**Pull request closed without merging**
