### PR TITLE
LPS-198500 Make asteriks also conditional on required

### PR DESCRIPTION
**Pull request by sandrodw3**
Resent from https://github.com/liferay-frontend/liferay-portal/pull/3831 🚀

@patriciajeanperez I think I fixed all the issues you mentioned, thanks for catching them. Could you please test it and confirm it? Thanks a lot 😄

### CODE REVIEW

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by patriciajeanperez** [comment]
ci:test:workflow

**Comment by mateusralv** [comment]
Hi @sandrodw3 and @patriciajeanperez I took a look at both routines and found no related failures.

1. [ci:test:workflow](https://github.com/liferay-frontend/liferay-portal/pull/3845#issuecomment-1823676206) ✅

2. [ci:test:relevant](https://github.com/liferay-frontend/liferay-portal/pull/3845#issuecomment-1823605914) ✅ 

[Testray Comparison](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1700767317575&testrayRunIdA=2463775544&testrayRunIdB=2463871144) -> ci:test:workflow

[Testray Comparison ](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1700761803878&testrayRunIdA=2463775544&testrayRunIdB=2463838313) -> ci:test:relevant

**Comment by ealonso** [comment]
@mateusralv 

Could you please manual forward it?

Thanks!!

**Comment by ealonso** [comment]
ci:test:stable

**Comment by sandrodw3** [comment]
Forwarded manually: https://github.com/brianchandotcom/liferay-portal/pull/144354

**Pull request closed without merging**
