### PR TITLE
LPS-199447 Search Container list and description views should use Cla…

### PR DESCRIPTION
**Pull request by pat270**
…y checkbox markup

https://liferay.atlassian.net/browse/LPS-199447

This updates search iterator? to use Clay checkbox markup.

site-templates

### CODE REVIEW

**Comment by pat270** [comment]
ci:test:sf

**Comment by pat270** [comment]
ci:test:relevant

**Review by markocikos — APPROVED** [review]
@pat270 LGTM! :sparkles:

**Comment by markocikos** [comment]
@pat270 If the code looks good to you, feel free to `ci : forward`. If CI failures look unrelated to you, feel free to `ci : forward : force`.

**Comment by markocikos** [comment]
ci:forward

**Comment by markocikos** [comment]
ci:report:2488786506

**Comment by markocikos** [comment]
ci:forward

**Comment by markocikos** [comment]
ci:report:2494175977

**Comment by markocikos** [comment]
Based on report in https://github.com/liferay-frontend/liferay-portal/pull/3888#issuecomment-1899915897, the only unique failure is (flalky) smoke test. If stable passes, I'll forward this.

**Comment by markocikos** [comment]
ci:test:stable

**Comment by markocikos** [comment]
ci:test:stable

**Comment by markocikos** [comment]
ci:test:stable

**Comment by markocikos** [comment]
ci:forward:force

**Comment by markocikos** [comment]
ci:forward:force

**Pull request closed without merging**
