### PR TITLE
LPS-199532 Refactor NPMJavaScriptAwarePortalWebResources component

### PR DESCRIPTION
**Pull request by MrJohn1911**
Previous pull: https://github.com/liferay-core-infra/liferay-portal/pull/6029

Hi guys, this pull is related to this epic: https://liferay.atlassian.net/browse/LPS-197817

I am sending it here because in this pull I removed an interface that probably used as a extension point for other components, so I am not 100% sure if this removal causes any problems.

I already talked with @dsanz and with @izaera [here](https://liferay.slack.com/archives/CNBG06JS3/p1698257156107269), but I am resending it here just to make sure everything it's ok. 

If you have any questions, you can talk with me or with @rafaprax.

Thanks in advance.

### CODE REVIEW

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by izaera** [comment]
This is the PR where the removed interface was added -> https://github.com/brianchandotcom/liferay-portal/pull/89906

**Comment by izaera** [comment]
Since I wasn't involved in any of the developments related to those classes I have not much to say. I know/remember the same about these classes as you :shrug: 

In any case, looking at the code of the PR it looks safe and looking at the linked PR it seems that the interface you are removing was not created to be used by customers, but by DXP internally so, as long as your PR doesn't break anything I assume we are safe.

**Review by izaera — APPROVED** [review]

**Comment by MrJohn1911** [comment]
In the last push, I just added a breaking change to the commit message.

**Comment by rafaprax** [comment]
ci:forward

/cc @dantewang

**Pull request closed without merging**
