### PR TITLE
LPS-181454 Add a new dependencies client extension to expose libraries to be used from other extensions

### PR DESCRIPTION
**Pull request by izaera**
# :warning: This was already reviewed. No need to review again :warning: 

Resend of https://github.com/brianchandotcom/liferay-portal/pull/133515

It fixes https://issues.liferay.com/browse/LPS-182182 too

### CODE REVIEW

**Comment by izaera** [comment]
ci:forward

**Comment by izaera** [comment]
ci:forward

**Comment by izaera** [comment]
I've fixed the baseline errors

**Comment by manoelcyreno** [comment]
ci:test:relevant

**Comment by manoelcyreno** [comment]
ci:forward

**Comment by izaera** [comment]
ci:forward

**Pull request closed without merging**
