### PR TITLE
LPS-139262 | Refactor and unquarantine ClayMultiselect test

### PR DESCRIPTION
**Pull request by john-co**
**Description**
Unquarantine failing test and refactor setup phase to scared model.

**Test Plan**
- [x] ClayMultiselect test passes

**JIRA Ticket**
https://issues.liferay.com/browse/LPS-139262

### CODE REVIEW

**Comment by john-co** [comment]
ci:test:frontend:nocompile

**Comment by john-co** [comment]
ci:test:frontend

**Comment by john-co** [comment]
ci:forward

**Comment by john-co** [comment]
gonna go ahead and forward. cc/ @zhangyan0701 , let me know if I missed something.

**Comment by zhangyan0701** [comment]
> gonna go ahead and forward. cc/ @zhangyan0701 , let me know if I missed something.

Looks good to me! 

Sorry for not replying in time! I forgot to check emails.

**Pull request closed without merging**
