### PR TITLE
LPS-188645 Hide FDSEntry sorting and filtering behind an FF 

### PR DESCRIPTION
**Pull request by dsanz**
Followup of https://github.com/liferay-frontend/liferay-portal/pull/3510, with an extra SF commit

### CODE REVIEW

**Comment by kresimir-coko** [comment]
Thanks @dsanz

**Comment by mateusralv** [comment]
ci:test:sf

**Comment by dsanz** [comment]
ci:test:relevant

**Comment by mateusralv** [comment]
ci:test:frontend-data-set

**Comment by mateusralv** [comment]
The failures of `ci:test:frontend-data-set` are not related ✅  

Waiting for the relevant results...

**Comment by dsanz** [comment]
ci:reevaluate:1277401_8984

**Comment by mateusralv** [comment]
Hi @dsanz the failures are not related!

[Testray Comparison](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1688154022152&testrayRunIdA=2366499659&testrayRunIdB=2366687187)

**Comment by dsanz** [comment]
ci:forward:force

**Comment by dsanz** [comment]
ci:forward:force

**Pull request closed without merging**
