### PR TITLE
LPS-122094 Update to @liferay/npm-scripts v37.0.0

### PR DESCRIPTION
**Pull request by wincent**
[Release notes](https://github.com/liferay/liferay-frontend-projects/releases/tag/npm-scripts%2Fv37.0.0)

This is going to change our lint rules when on 7.4 and above, so I am splitting this into two commits: one updates the package, and the next one applies somewhat over 1,000 autofixes.

Specifically, on 7.4 and above, we no longer need to support IE so we can enforce the same preference for arrow function callbacks in our JSPs that we do in our JS files. (The JS files could do this even on earlier branches because those get transpiled.)

### CODE REVIEW

**Comment by wincent** [comment]
Note: some commits in here from `brianchandotcom/liferay-portal`'s `master` branch because this includes a big auto-fix and I want to avoid merge conflicts if I can help it. 🤞

**Comment by jbalsas** [comment]
LGTM, I'd say we might even want to push this directly as to reduce the possibility of conflicts, but waiting on CI is good as well, specially to see SF green ;)

**Comment by wincent** [comment]
`java.lang.RuntimeException: Unable to execute bash commands: [git checkout -f master]` is pretty obviously bogus. Worth a re-run? 🤷

**Comment by jbalsas** [comment]
> java.lang.RuntimeException: Unable to execute bash commands: [git checkout -f master] is pretty obviously bogus. Worth a re-run? 🤷

Since changes are auto-fixes and this has absurdly huge chances of conflicts I would go with a manual forward and see if something happens.

I can take care of that

**Comment by wincent** [comment]
Manual forward: https://github.com/brianchandotcom/liferay-portal/pull/98821

**Pull request closed without merging**
