### PR TITLE
LPD-27160 Implement a routine to check which files have been modified in a PR and run typescript checks only for the changed modules

### PR DESCRIPTION
**Pull request by izaera**

### CODE REVIEW

**Comment by izaera** [comment]
ci:test:sf

**Comment by izaera** [comment]
ci:test:relevant

**Comment by izaera** [comment]
ci:test:sf

**Comment by izaera** [comment]
ci:test:sf

**Comment by izaera** [comment]
ci:test:relevant

**Comment by izaera** [comment]
ci:forward:force

**Comment by bryceosterhaus** [comment]
ci:report:13839897

**Pull request closed without merging**
