### PR TITLE
LPS-179284 Add REST context path to FDS Entry

### PR DESCRIPTION
**Pull request by markocikos**
### References

- [LPS-179284 Add REST context path to FDS Entry](https://issues.liferay.com/browse/LPS-179284)
- Fixes [LPS-178414 Search box returns wrong results](https://issues.liferay.com/browse/LPS-178414)

### What is the goal of this PR?

Goals of this PR:
- Add REST context path to FDS Entry
  - do this in a way that we support Object entries
- Scrap `entityClassName` as a unique identifier of a headless resource. It is not, that was causing LPS-178414.

:warning: There are a few quite ugly solutions in this PR. Viewer discretion is advised.

Technical notes:
- We are defining `restContextPath` as the final URL for FDS data endpoint.
  - `openapiResourcePath` is the path to the REST application. This follows convention in DXP.
- We are renaming headless resource `name` to `schema`. This follows OpenAPI naming convention.
- `openapiResourcePath` and  `entityClassName`/`schema` are wired over `osgi.jaxrs.application.select` property.
  - This is **not** true for Objects. For Objects, we need to find object definition and `getRESTContextPath` from it. 
- Another complication for Objects was that `entityClassName`, `version` and `bundle` are not unique, even when put together. This is because we have `ObjectEntryResource` and `ObjectEntryRelatedObjectsResource`. In this PR, we are explicitly discarding service reference of the relationship object. /cc @gabrielwas @guilhermedcamacho
- Regarding `entityClassName`, my initial intent was to replace it with a composite of properties from last point. In the end, I opted for alternative where I removed need for a unique identifier. I achieved this with adding `Provider` label to FDS Entry persistence. This way, we don't need to reconstruct headless resource from a complex custom identifier. Continuing with that approach ended up quickly growing in complexity.
- A challenge in this task was how to get from `schema` to relevant part of the REST context path. For example, `analytics-settings-rest` REST application has `CommerceChannel` schema. We can get that from `osgi.jaxrs.application.select` wiring in backend, or `components.schemas` wiring in OpenAPI frontend. But then, how do we get from `CommerceChannel` to  `commerce-channels` part of `/o/analytics-settings-rest/v1.0/commerce-channels`? I found no clean way of doing this, in either backend or frontend. In this PR, we are directly covering string, from `TitleCase` to `title-cases`, including `s` on the end. /cc @matijapetanjek @4lejandrito
- The fact that we are constructing the endpoint in correct format does not mean that this endpoint exists. In a followup task, it should be possible to filter out non-existing endpoints by comparing them to all paths in respective REST applications. 

/cc @pablo-agulla  

### What does it look like?
screen

https://user-images.githubusercontent.com/5435511/228561040-3ae26968-0ade-4d7c-a94c-4ba5314c1166.mp4
### Steps to reproduce

1. Add `feature.flag.LPS-164563=true` to `portal-ext.properties`. This enables FDS Views Manager.
1. Add `feature.flag.LPS-161364=true` to `portal-ext.properties`. This enables Objects relationships nested fields, used by FDS Views Manager.
1. :warning: If you previously opened Datasets page, drop database and create a new one. This PR changes persistence layer.
1. Start DXP
1. Open Global Menu > Control Panel > Object > Datasets

### CODE REVIEW

**Comment by 4lejandrito** [comment]
As discussed with @dsanz yesterday I think you guys should split the selection in 3 steps:

1. **Headless Application** (headless-delivery, headless-admin-taxonomy...). This way you won't see those ugly duplicate schemas (like Account).
2. **Schema**. 
3. **Endpoint** as there could be several page endpoints available for the same schema, and the user should be able to pick the desired one.

This way you don't need to infer the name of the endpoints (the plural issue you're having). You can just list all the endpoints that return a Page<Schema> and let the user select the desired one.  

You can get all that info just from the frontend by using this request as a start:

```
curl 'http://localhost:8080/o/openapi' -H 'accept: application/json' -u 'test@liferay.com:test'
```

It is basically the same mechanism used by the API Explorer.

@ccorreagg can you have a look?

**Comment by ccorreagg** [comment]
I agree with Alex; it is weird the way the entities are duplicated. To add more info, even though the name of the entities are the same, it could be related to a completely different entity; so I guess it is more accurate if we provide first the REST API desired and then, the desired schema inside the selected API

**Comment by markocikos** [comment]
@ugeortiz There are few UX considerations here:
1. Would it be acceptable if we split selection into two steps? One for REST application, the other for entities, populated asynchronously after application selection.
2. Would it be acceptable if we split selection into three steps? The third step would be endpoint, presented by it's path. We may not necessarily need to do this, I believe we can look for a `Page` + schema response in endpoint. There might be some edge cases where this doesn't work, so we may need the foolproof selection.
3. Some people (*cough*) appear to find multiple entities in selection ugly. Poor aesthetics or reason to change?

**Comment by ugeortiz** [comment]
Hey, @markocikos I think it shouldn't be a problem to change the way people select the provider. The only problem I see is that we would probably lose the way to look in the same autocomplete selector. This helps to find anything easily. If we decide to use for example selectors to filter it would be harder to get the same results without knowing them.

**Comment by ugeortiz** [comment]
One idea coming to my mind is to change the way we order the results. We will have duplicates but everything would be easily differentiable. 


Screenshot 2023-03-30 at 12 17 47

**Pull request closed without merging**
