### PR TITLE
LPS-203203 Fix NPE if CSP configuration has not been set

### PR DESCRIPTION
**Pull request by izaera**
Some of the requests won't pass through the CSP filter and the CSP configuration won't be stored in the request. For those, we set the nonce to '' as if CSP hadn't been configured.

### CODE REVIEW

**Comment by izaera** [comment]
ci:test:relevant

**Comment by gaborlovasdotcom** [comment]
ci:test:saml

**Comment by gaborlovasdotcom** [comment]
SAML functional tests are passsing.

**Comment by mateusralv** [comment]
The relevant failures are not related.

**Pull request closed without merging**
