### PR TITLE
LRQA-74339 Add refresh to load in portlet

### PR DESCRIPTION
**Pull request by susanchen3**
**Background**
Test is flaky because the FDS sample portlet wouldn't load on ci. Adding a Refresh() helps it load in.

**JIRA Ticket:**
https://issues.liferay.com/browse/LRQA-74339

### CODE REVIEW

**Comment by susanchen3** [comment]
ci:test:frontend:nocompile

**Comment by john-co** [comment]
Thanks, how did you test that this fix works on CI?  Were there any JS errors thrown when it couldn't load on CI?

cc/ @beltranrengifo , is there perhaps a potential fix to stabilize the FDS sample portlet?

**Comment by susanchen3** [comment]
@john-co I did a lot of testing between these two PRs: [#33 ](https://github.com/susanchen3/liferay-portal/pull/33) and [#29](https://github.com/susanchen3/liferay-portal/pull/29)

I tried: 
- WaitForElementPresent()
- WaitForPageLoad()
- LiferayEvent.waitForPortletReady()
- WaitForLiferayEvent.initializeLiferayEventLog()
- WaitForLiferayEvent(attributeName = "type", attributeValue = "allPortletsReady", eventName = "allPortletsReady")
- Pausing for 15, 20, and 30 secs (30s gave me a out of memory error if i remember correctly)

I didn't really know how to view JS errors when it didn't pass on CI, but when I tried that LiferayEvent functions they would pass that step but continue not to load in ([example](https://testray.liferay.com/reports/production/logs/2022-04/test-1-37/test-portal-acceptance-pullrequest(master)/1725/functional-tomcat90-mysql57-jdk8/0/0/LocalFile.FrontendDataSet_ActionsCanBeCustomized/index.html.gz?authuser=0))

**Comment by john-co** [comment]
Looks good to me! :sunglasses: 

I'll forward this for now so we atleast have some test coverage on FDS module.

**Comment by john-co** [comment]
ci:forward

**Comment by beltranrengifo** [comment]
> Thanks, how did you test that this fix works on CI? Were there any JS errors thrown when it couldn't load on CI?
> 
> cc/ @beltranrengifo , is there perhaps a potential fix to stabilize the FDS sample portlet without a page refresh?

Hi!
If I've understood correctly, the [reload command](https://github.com/susanchen3/liferay-portal/blob/72e993e75f2614b6085a27f66d5b09c59179447d/portal-web/test/functional/com/liferay/portalweb/tests/enduser/frontendinfrastructure/uiinfrastructure/frontenddataset/FrontendDataSet.testcase#L32) inside the setup block should not be needed, right?

**Comment by susanchen3** [comment]
@beltranrengifo yep!

**Comment by john-co** [comment]
fyi @susanchen3 follow up fix: https://issues.liferay.com/browse/LPS-152038

see https://liferay.slack.com/archives/C3JBR21HA/p1650635920639119 for details

**Pull request closed without merging**
