### PR TITLE
LPS-179151 Functional Automation - LPS-179151 - Define which columns are sortable in a dataset view

### PR DESCRIPTION
**Pull request by andreluis2022**
**Description:**
Create new automations for DataSetViewFields / Define which columns are sortable in a dataset view

**JIRA Tickets:**
[LPS-179151](https://liferay.atlassian.net/browse/LPS-179151) History

### CODE REVIEW

**Comment by andreluis2022** [comment]
ci:test:sf

**Comment by andreluis2022** [comment]
ci:test:frontend-data-set

**Comment by andreluis2022** [comment]
LGTM! Hey @CarlosBrichete what do you think?

**Comment by andreluis2022** [comment]
ci:test:frontend-data-set

**Review by CarlosBrichete — APPROVED** [review]

**Comment by CarlosBrichete** [comment]
LGTM

**Comment by andreluis2022** [comment]
ci:forward

**Pull request closed without merging**
