### PR TITLE
LPD-19872 Don't add duplicate JS modules to `FlatJSPackage`s

### PR DESCRIPTION
**Pull request by izaera**

### CODE REVIEW

**Comment by izaera** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
ci:help

**Comment by bryceosterhaus** [comment]
ci:test:echo

**Comment by bryceosterhaus** [comment]
just gonna run echo to get a few more tests run to check against

**Comment by izaera** [comment]
Going to run failed tests locally to see if I can find out anything...

**Comment by izaera** [comment]
Bad news. I'm still seeing the duplicated JS module error locally:

image

**Comment by izaera** [comment]
It turns out the message was from an old log from yesterday.

I've run the `LocalFile.WidgetPagesWithContentPanel#AddWebContentViaContentPanel` test locally on master and it fails in the same way.

I'll send a test PR without the fix commit to run echo tests again just in case, but I think this is safe to forward...

**Comment by izaera** [comment]
The test PR -> https://github.com/liferay-frontend/liferay-portal/pull/4057

**Comment by izaera** [comment]
ci:report:2547743368

**Comment by izaera** [comment]
So, test `NavigationMenuWidget#ConfigureDisplayTemplateOfNavigationMenuWidget` fails here but not in master (tested locally). I'm going to run it locally to see if I can find anything...

**Comment by izaera** [comment]
It doesn't fail locally.

**Comment by izaera** [comment]
I'm going to force forward this after agreeing it with @dsanz .

If the change was deeply incorrect it would break the portal in very noticeable ways. Otherwise, if it breaks for some corner case that we cannot detect, it won't be as bad as it is now, so it's a step forward.

**Comment by izaera** [comment]
ci:forward:force

**Pull request closed without merging**
