### PR TITLE
LPS-122725 fix input-date prefilling on mobile

### PR DESCRIPTION
**Pull request by dbagrey**
https://issues.liferay.com/browse/LPS-122725

**Problem overview:**
liferay-ui: input-date is pre-filled when viewed from a mobile device

**Steps to Reproduce:**
- Place the liferay-ui: input-date tag with an empty value on the jsp page
- Deploy portlet with jsp page
- Open page with portlet on a mobile device

**Expected Results:**
Input contain empty value

**Actual Results:**
input is prefilled

### CODE REVIEW

**Comment by jbalsas** [comment]
Hey @dbagrey, thanks for the contribution, I see you signed our CLA based on the checks at https://github.com/liferay/liferay-portal/pull/3990

Since this is a pretty old tag we probably want to be extra careful with changes.

I'm going to ping @antonio-ortega and @dsanz to make a quick assessment on this when they have the chance and trigger our tests in the meantime.

**Comment by jbalsas** [comment]
ci:test:sf

**Comment by jbalsas** [comment]
Hey @dbagrey, as you can see by https://github.com/liferay-frontend/liferay-portal/pull/453#issuecomment-724727801, you added an [unnecessary extra line](https://github.com/liferay-frontend/liferay-portal/pull/453/files#diff-38dc9ea938856268a239c2ded3d9346c2a7680c6edcd954a0dfd549e48b6e9a7R360) at the end of that jsp. This is a bit of a quirk of us in the liferay repo.

Could you remove it and push force the change since it's small enough so this is ready in case the other checks are satisfactory?

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by dbagrey** [comment]
Hi @jbalsas, i remove the empty line

**Comment by jbalsas** [comment]
ci:test:sf

**Comment by dbagrey** [comment]
@jbalsas, please tell me how to fix an error [in the tests](https://github.com/liferay-frontend/liferay-portal/pull/453#issuecomment-724794584)

**Comment by wincent** [comment]
Try rebasing and rerunning. If it happens again, I'd report the problem in `#ci` on Slack seeing as a message like:

```
fatal: Not a valid branch point: '1740ae8de5376064679f119d8ee7356c230f37ba'.
```

could mean a transitory CI infra failure, or not...

**Comment by wincent** [comment]
In the meantime, I am going to kick off a re-run just in case it was your force-push that confused the infra.

**Comment by wincent** [comment]
ci:test:sf

**Comment by wincent** [comment]
ci:test:relevant

**Comment by wincent** [comment]
I'm going to take @jbalsas' prior comments on this as tacit approval and forward this.

burn

**Comment by wincent** [comment]
ci:forward

**Pull request closed without merging**
