### PR TITLE
LPS-139408 Edit language dropdown menu opens in wrong position when editing a picklist item

### PR DESCRIPTION
**Pull request by GabrielHenriquedev**
Motif [LPS-139408](https://issues.liferay.com/browse/LPS-139408)

The language drop-down menu opens in the wrong position when editing a selection list item.
When the language menu was selected for the first time it was created from an `if`, and on the next clicks it was called again from the else, but the positions of `if` and `else` were being added together and this caused the component to be created in a random position.

My proposal to solve the bug was to remove the `if` and what caused the selection menu to break, with the exclusion of `if` and `else` the selection menu works as expected and its position doesn't change.

LPS-139408

### CODE REVIEW

**Comment by GabrielHenriquedev** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by GabrielHenriquedev** [comment]
ci:test:relevant

**Comment by mateusralv** [comment]
I made a [comparison with the master](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1660159412169&testrayRunIdA=1941666775&testrayRunIdB=1941248221) and seems the failures is not related your PR. 

cc: @john-co

**Comment by carloslancha** [comment]
Hi @GabrielHenriquedev it looks weird to me that this dropdown adds an overlay when it's opened. Are we sure that's the expected behavior?

**Comment by GabrielHenriquedev** [comment]
Hello [carloslancha](https://github.com/carloslancha), this behavior happened before the bug was fixed, because the else that called the language menu again ended up creating the menu again in a random position, so it was not an expected result.

**Comment by carloslancha** [comment]
@GabrielHenriquedev What I mean is that behavior seems strange to me. I'd ask someone from design (@drakonux maybe, or maybe him could redirect us to the correct one) to review this so we can find out if that overlay should appear or not when the dropdown is opened.

If that's the expected behavior we should check if we're not breaking anything with the fix since we're changing the base menu component and it will affect to all the usages. If it's not the expected behavior maybe the solution could be to try to configure the usage properly so the overlay doesn't appear and check if that fixes the position stuff.

**Comment by drakonux** [comment]
As @carloslancha said, a dropdown menu should not add an overlay layer. This behavior is used for modal windows/panels to focus the user on the UI element. But no for regular dropdown menus or platform components that use them, such as the translation manager. 

Thus, as far as I can review using the information given, it would create inconsistency, so there is no reason for adding it. 

cc\ @ugeortiz

**Comment by GabrielHenriquedev** [comment]
OK, I understand that the overlay shouldn't be in that place, but it already existed before my modification.
My solution just fix the position where the dropdown is displayed (by removing the condition that in my opinion doesn't make sense for the button call).
That is the behavior that this bug is about.
But anyways, how do you think we should proceed with this Pull request?

cc: @carloslancha @drakonux

**Pull request closed without merging**
