### PR TITLE
LPS-116201 Update liferay-ckeditor to 4.14.1-liferay.6

### PR DESCRIPTION
**Pull request by carloslancha**
Updating liferay-ckeditor to 4.14.1-liferya.6 version.

In this version:
- Review from [LPS-116201](https://issues.liferay.com/browse/LPS-116201) is applied
- [LPS-118624](https://issues.liferay.com/browse/LPS-118624) RTL issue is fixed
- [LPS-118249](https://issues.liferay.com/browse/LPS-118249) icons issue in IE11 is fixed

### CODE REVIEW

**Comment by carloslancha** [comment]
ci:test:sf

**Comment by carloslancha** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
Might still make it in time for the initial GA5 release cut... 🤞

**Comment by jbalsas** [comment]
ci:forward

**Comment by carloslancha** [comment]
Thx @jbalsas

**Comment by jbalsas** [comment]
GO TO BED @carloslancha !!!

gotobed

**Comment by carloslancha** [comment]
I was in bed @jbalsas what is your excuse?

**Comment by jbalsas** [comment]
I don't have a bed

**Comment by carloslancha** [comment]
😮 😮 😮 😮 😮 😮 😮

**Pull request closed without merging**
