### PR TITLE
LPS-204424 - Remove sorting direction for relevance column

### PR DESCRIPTION
**Pull request by juanjofgliferay**
## Related task
https://liferay.atlassian.net/browse/LPS-204424

## Issue
Changing sort direction (Ascending, Descending) when search results are ordered by "Relevance" is not working. This happens in Web Content and Blogs. 
Web Content does not return information about the sorting direction but Blogs does. However, neither of them work so  the idea is to remove this options if when the `sortingOrder` prop is null or empty in the ManagementToolbar component

## UI before
[sorting_with_direction.webm](https://github.com/liferay-frontend/liferay-portal/assets/132653342/08738b3c-1bb2-44ce-8555-ec6e98c17cb7)

## UI after
[Screencast from 2024-01-16 08-39-43.webm](https://github.com/liferay-frontend/liferay-portal/assets/132653342/d6689734-1fdf-4f9a-a07c-ffe51fba4551)

### CODE REVIEW

**Comment by juanjofgliferay** [comment]
ci:test:relevant

**Comment by juanjofgliferay** [comment]
ci:test:stable

**Comment by juanjofgliferay** [comment]
ci:test:relevant

**Comment by juanjofgliferay** [comment]
ci:reevaluate:1327401_3399

**Comment by juanjofgliferay** [comment]
ci:test:relevant

**Comment by juanjofgliferay** [comment]
ci:test:relevant

**Comment by juanjofgliferay** [comment]
ci:test:relevant

**Comment by juanjofgliferay** [comment]
ci:test:relevant

**Comment by dsanz** [comment]
ci:forward

**Review by markocikos — APPROVED** [review]
@juanjofgliferay LGTM! :sparkles:

**Comment by juanjofgliferay** [comment]
ci:forward

**Comment by juanjofgliferay** [comment]
ci:reevaluate:1377401_15970

**Comment by juanjofgliferay** [comment]
ci:test:relevant

**Comment by juanjofgliferay** [comment]
ci:test:relevant

**Comment by juanjofgliferay** [comment]
ci:forward:force

**Pull request closed without merging**
