### PR TITLE
LPS-156142 Replace pause with waitfors from FI tests

### PR DESCRIPTION
**Pull request by yanan**
Affected FI tests in source-formatter-suppressions.xml:
	Theme.testcase
	ClayAlert.testcase
	RemoteApps.testcase
	WYSIWYGUsecase.testcase

Steps:
	Go to one of the files that you own in the suppressions and remove the suppression
	Fix all the pauses within that file
	Find a solution with waitfors and not pauses.

JIRA Ticket:
	[https://issues.liferay.com/browse/LPS-156142](https://issues.liferay.com/browse/LPS-156142)

### CODE REVIEW

**Comment by yanan** [comment]
ci:test:sf

**Comment by yanan** [comment]
ci:test:frontend-clay

**Comment by yanan** [comment]
ci:test:frontend

**Comment by yanan** [comment]
Hello @john-co , the failed tests are not related to the updated tests in this pr after checking the test report, please help review, thanks.
 frontend failed tests:
- Blueprints 
- ManagementToolbar LRQA-75424
- RemoteAppsUpgrade LPS-152615

**Comment by john-co** [comment]
Looks good to me! :sunglasses:

Thanks @yanan !

**Comment by john-co** [comment]
ci:forward

**Pull request closed without merging**
