### PR TITLE
LPS-184679 Export / Import FrontEnd Client Extensions individually (resend)

### PR DESCRIPTION
**Pull request by izaera**
Resend of https://github.com/brianchandotcom/liferay-portal/pull/136096

### CODE REVIEW

**Comment by mateusralv** [comment]
Hi @izaera The failures are not related.

[Testray comparison](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1686677895918&testrayRunIdA=2349259427&testrayRunIdB=2349405466)

**Comment by izaera** [comment]
Oops, didn't see your comment @mateusralv :sweat_smile:

**Comment by izaera** [comment]
ci:forward:force

**Comment by izaera** [comment]
ci:forward:force

**Comment by izaera** [comment]
I'll try again :crossed_fingers:

**Pull request closed without merging**
