### PR TITLE
LPS-112982 Update to liferay-ckeditor@4.14.1-liferay.2

### PR DESCRIPTION
**Pull request by julien**
This version of `liferay-ckeditor` was built with this [patch](https://github.com/liferay/liferay-ckeditor/blob/cb0284ba92bab29b2a06ffa462b9c05e7eae5f68/patches/0005-LPS-112982-Add-additional-resource-URL-parameters.patch) which allows adding additional parameters for resource URLs.

### CODE REVIEW

**Comment by julien** [comment]
ci:test:sf

**Comment by julien** [comment]
ci:test:relevant

**Comment by carloslancha** [comment]
Could you please set latest version to `4.14.1-liferay.2`, remove prerelease one and add related changelog torelease notes in https://github.com/liferay/liferay-ckeditor/releases?

**Comment by carloslancha** [comment]
LGTM

**Comment by julien** [comment]
> Could you please set latest version to 4.14.1-liferay.2, remove prerelease one and add related changelog to release notes in https://github.com/liferay/liferay-ckeditor/releases?

Sure

**Comment by carloslancha** [comment]
ci:forward

**Pull request closed without merging**
