### PR TITLE
LPS-155310 Add test FilterCanBeSearched

### PR DESCRIPTION
**Pull request by susanchen3**
**Background**
Create automated tests for FDS filters.

**Test Plan**
Given Sample FDS portlet deployed
And entering on a page which uses FDS
When clicking on the filter button
And typing a key word in the category search box
And there is a matching filter 
Then the results will be displayed updated accordingly to it
And the Filters Summary boxes will be updated accordingly to it

**JIRA Ticket:**
https://issues.liferay.com/browse/LPS-155310

### CODE REVIEW

**Comment by susanchen3** [comment]
ci:test:frontend:nocompile

**Comment by john-co** [comment]
Just started reviewing :)

**Review by john-co — APPROVED** [review]
Looks good to me! :sunglasses:

**Comment by john-co** [comment]
ci:forward

**Pull request closed without merging**
