### PR TITLE
LPS-155313 Add test FDSFilters#ExcludeCanBeEnabled

### PR DESCRIPTION
**Pull request by susanchen3**
**Background**
Create automated tests for FDS Filters.

**Test Plan**
Given Sample FDS portlet deployed
And entering on a page which uses FDS
When clicking on the filter button
And adding an option from the status list filter
And the exclude option is active
Then the filter will be added the Filters Summary
And the results will be displayed updated accordingly to it

**JIRA Ticket:**
https://issues.liferay.com/browse/LPS-155313

### CODE REVIEW

**Comment by susanchen3** [comment]
ci:test:sf

**Comment by susanchen3** [comment]
ci:test:frontend:nocompile

**Comment by john-co** [comment]
Just started reviewing :)

**Review by john-co — APPROVED** [review]
Looks good to me! :sunglasses:

**Comment by john-co** [comment]
ci:forward

**Pull request closed without merging**
