### PR TITLE
LPS-175104 Remove obsolete AUI components for the Item Selector

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
Issue: https://issues.liferay.com/browse/LPS-175104

Originally the [task](https://issues.liferay.com/browse/LPS-126775) was about to remove Metal from `ItemSelectorRepositoryEntryBrowser.es.js`, but this was previously done and moved to React, and this file no longer exists. 

So in this pull I want to delete all the previous AUI components related to the Item Selector that were first replaced by Metal components but are currently replaced by React components.

- item_selector_repository_entry_browser.js -> ItemSelectorRepositoryEntryBrowser.js
- item_selector_uploader.js -> SingleFileUploader.js
- item_selector_url.js -> ItemSelectorUrl.es.js
- item_selector_dialog.js not used anymore, replaced by openSelectionModal fn in Modal.js

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
This PR brings me so much joy.
Screen Shot 2023-02-09 at 12 42 26 PM

**Comment by bryceosterhaus** [comment]
So long as tests pass, this LGTM

**Comment by ambrinchaudhary** [comment]
ci:reevaluate:1277401_6852

**Comment by carloslancha** [comment]
<a href="https://gitme.me/image?url=https%3A%2F%2Fmedia2.giphy.com%2Fmedia%2F5nsiFjdgylfK3csZ5T%2Fgiphy.gif&token=fire" data-gitmeme-token="fire"></a>

**Comment by ambrinchaudhary** [comment]
CI errors seems unrelated 🤔 , trying one more time...

**Comment by ambrinchaudhary** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
ci:reevaluate:1257401_6225

**Comment by WYZ-Issac** [comment]
The above failures are not related to this PR, sent it to BChan: https://github.com/brianchandotcom/liferay-portal/pull/130232

**Comment by ambrinchaudhary** [comment]
ci:close

**Pull request closed without merging**
