### PR TITLE
LPS-158237 Allow instance admins to select the mode to show alert/confirmation messages

### PR DESCRIPTION
**Pull request by diegonvs**
# How to test it

1. Go to Global Menu -> Control Panel -> Instance Settings
2. Click on "Custom Dialogs" configuration
3. Enable it by checking and then clicking "Update" and then go back `/home` 🏠 
4. Go to Configuration -> Site Settings -> Recycle Bin and then disable it and back `/home` 🏠 
5. Go to Content & Data -> Documents and Media
6. Select an entry and then delete it

image

# Considerations

I decided to write the JS to *BottomJSPDynamicInclude and use Liferay global variable because some JSPs use cases require it. If anyone have another thought, please, share 😍

### CODE REVIEW

**Comment by diegonvs** [comment]
```
     [exec] 
     [exec] ***************
     [exec] *** WARNING ***
     [exec] ***************
     [exec] 
     [exec] Out-of-date TypeScript build artifacts at:
     [exec] 
     [exec]     apps/oauth2-provider/oauth2-provider-web/types
     [exec] 
     [exec] Please commit them.
```

🤷🏼‍♂️

**Comment by diegonvs** [comment]
ci:test:sf

**Comment by diegonvs** [comment]
ci:test:relevant

**Comment by diegonvs** [comment]
ci:test:relevant

**Comment by mateusralv** [comment]
I'm taking a look 🕵🏽

**Comment by diegonvs** [comment]
Yes, I'm fixing it. Thanks a lot Mateus 💖

**Comment by diegonvs** [comment]
ci:forward

**Comment by diegonvs** [comment]
ci:test:sf

**Comment by diegonvs** [comment]
ci:forward

**Pull request closed without merging**
