### PR TITLE
LPD-27048 - Refactor. Update reference to the correct .jsp file

### PR DESCRIPTION
**Pull request by juanjofgliferay**
## Task
https://liferay.atlassian.net/browse/LPD-27048

## Issue
Navigating with `feature.flag.LPD-15729=false` causes the Data Set Views back button to point to `fds_entries.jsp` that has been removed.

This causes some tests to fail:
[#CanGoToViewPage](https://testray.liferay.com/home/-/testray/case_results/2573078530?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2573078197%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc)
[#CanClickOnDataSetNameCreated](https://testray.liferay.com/home/-/testray/case_results/2573078519?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2573078197%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc)
[#](https://testray.liferay.com/home/-/testray/case_results/2573078519?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2573078197%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc)[CanViewCreatedDataSet](https://testray.liferay.com/home/-/testray/case_results/2573078406?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2573078197%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc)

Screenshot from 2024-05-29 08-57-28

### CODE REVIEW

**Comment by juanjofgliferay** [comment]
ci:test:frontend

**Review by markocikos — APPROVED** [review]
@juanjofgliferay LGTM! :sparkles: 

My bad on this one. I should more thoroughly test no-FF scenario :disappointed:

**Comment by juanjofgliferay** [comment]
image

[Testray Report LocalFile.DataSetView](https://testray.liferay.com/home/-/testray/case_results/index?delta=200&p_p_state=normal&orderByCol=status_sortable&orderByType=asc&testrayBuildId=2573177519&testrayRunId=2573178262&testrayCaseName=LocalFile.DataSetView) :tada:

**Comment by juanjofgliferay** [comment]
ci:forward

**Pull request closed without merging**
