### PR TITLE
LPS-157180 - Remove old uses of metal-state from classes extending PortletBase

### PR DESCRIPTION
**Pull request by bryceosterhaus**
https://issues.liferay.com/browse/LPS-157180

Removes dependency of metal.js from frontend-js-web. By doing this, we remove metal.js from our initial page load.

### CODE REVIEW

**Comment by bryceosterhaus** [comment]
ci:stop

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
ci:test:sf

**Comment by mateusralv** [comment]
I'm taking a look 🕵️

**Comment by mateusralv** [comment]
Hi @bryceosterhaus I think the tests that are failing are related to your PR. 

I tested it locally and the failure continues:
1. [Publications#RescheduleAndCancelScheduledPublication](https://testray.liferay.com/home/-/testray/case_results/1896789771?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D1896789293%26testrayRunId%3D1896789319%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc)
2. [Accounts#NoWarningDisplaysWhenAddingAUserWithValidDomain](https://testray.liferay.com/home/-/testray/case_results/1896789473?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D1896789293%26testrayRunId%3D1896789319%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc)
3. [Accounts#AddingSecondUserToPersonAccountWillReplaceFirstUser](https://testray.liferay.com/home/-/testray/case_results/1896789501?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D1896789293%26testrayRunId%3D1896789319%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc)
4. [Publications#PublishParallelPublications](https://testray.liferay.com/home/-/testray/case_results/1896789643?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D1896789293%26testrayRunId%3D1896789319%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc)
5. [Accounts#CanRemoveUserFromPersonAccount](https://testray.liferay.com/home/-/testray/case_results/1896789552?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D1896789293%26testrayRunId%3D1896789319%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc)
6. [AdaptiveMedia#CanAdaptImageInBlogsEntry](https://testray.liferay.com/home/-/testray/case_results/1896789478?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D1896789293%26testrayRunId%3D1896789319%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc)
7. [AdaptiveMedia#CanAdaptImageInWebContent](https://testray.liferay.com/home/-/testray/case_results/1896789480?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D1896789293%26testrayRunId%3D1896789319%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc)
8. [AdaptiveMedia#CanAdaptSVGImageInBlogsEntry](https://testray.liferay.com/home/-/testray/case_results/1896789481?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D1896789293%26testrayRunId%3D1896789319%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc)
9. [OpenGraphPreview#CanViewPreview](https://testray.liferay.com/home/-/testray/case_results/1896789693?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D1896789293%26testrayRunId%3D1896789319%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc)

Comparison [run](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=2&testrayRunIdB=1896789319&testrayRunIdA=1896717372&statusB=3)
cc: @john-co

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
ci:test:sf

**Review by kresimir-coko — APPROVED** [review]
I'm so unfamiliar with classes but it looks good to me!

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
ci:stop

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
ci:test:sf

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
ci:stop

**Comment by bryceosterhaus** [comment]
ci:test:sf

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by izaera** [comment]
This is fantastic :heart_eyes: 

delete everything

**Comment by bryceosterhaus** [comment]
> This is fantastic 😍

lets not get ahead of ourselves here, CI still has opinions

**Comment by izaera** [comment]
> lets not get ahead of ourselves here, CI still has opinions

:cry:

**Comment by mateusralv** [comment]
I'm taking a look at the failures 🔎

**Comment by mateusralv** [comment]
Hi @bryceosterhaus I've looked at the failures in that PR and some tests seem related, I've tested the following tests locally and keep failing.

1. [Accounts#SelectingUserWillReplaceExistingUserInPersonAccount](https://testray.liferay.com/home/-/testray/case_results/1904951670?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D1904940297%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc)
2. [Publications#PublishParallelPublications](https://testray.liferay.com/home/-/testray/case_results/1904953439?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D1904940297%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc)
3. [SitesUseCase#AddOrganizationSitesAndDeactivate](https://testray.liferay.com/home/-/testray/case_results/1904953811?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D1904940297%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc)

[Comparison run](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=2&testrayRunIdB=1904951465&testrayRunIdA=1904940329&statusB=3) with the master

cc: @john-co

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
@mateusralv could you take another look at these most recent failures? I think I addressed the ones you mentioned before.

**Comment by mateusralv** [comment]
I'm taking a look 🕵️

**Comment by mateusralv** [comment]
Hi @bryceosterhaus most of the faults are also in the master ([Comparison run](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1658405953471&testrayRunIdA=1912019687&testrayRunIdB=1913141533)). But some tests have unique failures and don't seem related to me.

- `com.liferay.blogs.asset.test.BlogsEntryAssetSearchTest` Seems to be a time out failure:
```Exception in thread "main" java.lang.RuntimeException: java.net.ConnectException: Connection timed out (Connection timed out)
	at com.liferay.jenkins.results.parser.JenkinsResultsParserUtil.getGitHubCacheHostnames(JenkinsResultsParserUtil.java:1849)
	at com.liferay.jenkins.results.parser.JenkinsResultsParserUtil.getRandomGitHubDevNodeHostname(JenkinsResultsParserUtil.java:2764)
	at com.liferay.jenkins.results.parser.GitUtil.executeBashCommands(GitUtil.java:393)```
```
- `AdaptiveMedia#ImageResolutionIsScopedToInstance` Seems to be a CI failure.

cc: @john-co

**Comment by bryceosterhaus** [comment]
@mateusralv @john-co, so is this safe to manually forward then?

**Comment by bryceosterhaus** [comment]
manual forward https://github.com/brianchandotcom/liferay-portal/pull/120799

**Pull request closed without merging**
