### PR TITLE
[TS] LPS-127302 Add event.stopPropagation() to fix onclick event on Safari…

### PR DESCRIPTION
**Pull request by rolandpakai**
Hola Team!

could you please check my fix?

The issue is only reproducable on Safari with disabled SPA (javascript.single.page.application.enabled=false)
Adding event.stopPropagation() to the onclick events fixing the issue 

Thanks, Roland

### CODE REVIEW

**Comment by rolandpakai** [comment]
ci:test:sf

**Comment by rolandpakai** [comment]
ci:test:stable

**Comment by rolandpakai** [comment]
ci:test:relevant

**Comment by wincent** [comment]
Looks reasonable although with innocuous-looking changes like this you can never know if there is going to be some unanticipated downstream effect. Also not sure why it would be Safari-only.

I gather, @rolandpakai, that you checked other browsers as well to make sure there are no regressions, right?

In the meantime, I am going to try restarting CI because it seems rather stalled.

**Comment by wincent** [comment]
ci:stop

**Comment by wincent** [comment]
ci:test:relevant

**Comment by rolandpakai** [comment]
Hi @julien 

thanks for checking my fix.
Yes, i tested my fix with and without disabling SPA on onther browsers too.

Thanks, Roland

**Comment by jbalsas** [comment]
This feels a bit off to me. Wouldn't this prevent any additional listener from running? That seems to be the case here. It means that any listener added to that node won't run because propagation has been stopped.

Maybe there's something in how different browsers run and/or register listeners and something else is going on.

I would feel more comfortable with a more in-depth analysis on why this is happening. What code is running when we don't stop propagation and how does that factor into the issue? With the information presented, this feels a bit like a blind fix and the code we're changing is rooted deep enough in the platform infrastructure to make me feel okay about moving forward with it.

**Comment by jbalsas** [comment]
Hey @rolandpakai, just pinging you in case the other mention got lost. Do you think you'll have time to take a look at my concerns? If not, please let us know so we can figure out how to unblock this.

**Comment by rolandpakai** [comment]
Hi @jbalsas 

i am using a Dell Windows notebook, so my testing in Safari with BrowserStack is very frustrating...
(Now i can feel the pain when others wants to test an IE11 issue on Mac - This is why i offered myself to work on IE11 issues on global level - Maybee you heard about that - Currently i helped out the Commerce team with IE11 issues) 
So i would appreciate it if the produt team could take over this investigation.

What i did in BrowserStack is i tryed to add an click eventListener to the anchor where the onclick was used,
but what i experienced is no click event was registered. 

Thanks, Roland

**Comment by jbalsas** [comment]
Just to add something in case it helps, I did a quick test and I'm confident this is some type of race condition happening in Safari.

If you add a breakpoint inside [`submitForm`](https://github.com/liferay-frontend/liferay-portal/blob/master/modules/apps/frontend-js/frontend-js-aui-web/src/main/resources/META-INF/resources/liferay/util.js#L916) you'll see that after resuming the execution the action completes. That should be the first clue.

Next thing is try to see if we can pinpoint the listener that is preventing execution from going through. Most browsers show you the listeners attached to a given element and give you the option to enable/disable/debug them:

Screen Shot 2021-02-11 at 10 25 54

A bit of trial/error quickly leads to [`_handleDocClik`](https://github.com/liferay-frontend/liferay-portal/blob/master/modules/apps/frontend-js/frontend-js-aui-web/src/main/resources/META-INF/resources/liferay/icon.js#L40-L55) in [`icon.js`](https://github.com/liferay-frontend/liferay-portal/blob/master/modules/apps/frontend-js/frontend-js-aui-web/src/main/resources/META-INF/resources/liferay/icon.js).

If you follow the regular flow of that listener, you'll se it ends in `_forcePost` and this [suspiciously guilty line](https://github.com/liferay-frontend/liferay-portal/blob/master/modules/apps/frontend-js/frontend-js-aui-web/src/main/resources/META-INF/resources/liferay/icon.js#L29):

```javascript
if (!Liferay.SPA || !Liferay.SPA.app) { ... }
```

Please, even if its a little frustrating, see if you can take it from there.

Thanks!

**Comment by antonio-ortega** [comment]
Hey @rolandpakai ,

If after following the hints provided by Chema you can't find a proper solution, feel free to raise a PTR with your new finding and we can continue the work over there.

Thanks.

**Comment by rolandpakai** [comment]
Thank you @jbalsas, @antonio-ortega , i can check your findings tomorrow.

**Comment by rolandpakai** [comment]
Debugging in BrowserStack is not working for me. 
Norbert Nemeth has a MacBook, he will continue the debug in Safarai.

**Pull request closed without merging**
