### PR TITLE
LPS-117292 - Modify border overlapping

### PR DESCRIPTION
**Pull request by marcoscv-work**
This PR adds new value for border overlapping:

NavBorder

To test it, you need to go to:

1º - Open `Global menu`
2º - Navigate to `Sync Connector Admin`
3º - Navegatee between `Settings` and `Sites`
4º - Check blue line is always over and not overlapping bottom border

### CODE REVIEW

**Comment by marcoscv-work** [comment]
ci:test

**Comment by marcoscv-work** [comment]
ci:test:relevant

**Comment by marcoscv-work** [comment]
ci:test:sf

**Comment by marcoscv-work** [comment]
Local `formatSource` works fine.
CSS properties are in order Brian wants:
https://github.com/brianchandotcom/liferay-portal/pull/91236#issuecomment-657665026

**Comment by marcoscv-work** [comment]
ci:test:sf

**Comment by markocikos** [comment]
@marcoscv-work you can CI test locally
1. go to `portal-impl` dir
1. run `ant format-source-current-branch`

**Comment by marcoscv-work** [comment]
> @marcoscv-work you can CI test locally
> 
> 1. go to `portal-impl` dir
> 2. run `ant format-source-current-branch`

@markocikos nothing changed!
image

**Comment by jbalsas** [comment]
Try `ant format-source-all`. Or rebase... maybe this has been fixed upstream already as it's clearly not related.

**Comment by marcoscv-work** [comment]
rebased!

**Comment by marcoscv-work** [comment]
ci:test:sf

**Comment by markocikos** [comment]
[java] 1: ./build.properties expected:<...\
     [java]     #    dxp/apps/[]multi-factor-authent...> but was:<...\
     [java]     #    dxp/apps/[lcs,\
     [java]     #    dxp/apps/]multi-factor-authent...>

Maybe dxp needs to be built to see the error? Normal `build.properties` does not contain `lcs`. @igorbeslic @john-co

**Comment by igorbeslic** [comment]
LCS should be part of latest DXP 7.3 -> maybe CI test should be updated??? @john-co

**Comment by jbalsas** [comment]
I honestly have no idea what you did, @marcoscv-work 😂

**Comment by jbalsas** [comment]
ci:test:sf

**Comment by markocikos** [comment]
When I do `ant format-source-current-branch` on master, it builds successfully but deletes this line
```
 #    dxp/apps/lcs,\`
```

**Comment by jbalsas** [comment]
ci:forward

**Comment by jbalsas** [comment]
Trying again since [SF should be fixed upstream](https://github.com/liferay/liferay-portal/commit/56fc389f218038d4db1f551bf77b936f99dd6285). See https://liferay.slack.com/archives/C19PWQ74J/p1594995631143000 for more info.

**Pull request closed without merging**
