### PR TITLE
LPS-137760 Remove stale *EditorConfigContributor classes in Blogs

### PR DESCRIPTION
**Pull request by diegonvs**
Context: https://liferay.slack.com/archives/CLD39UKM5/p1631122808008200

These classes were leftovers of a replacement of liferay-editor tag with native elements(a.k.a inputs) in some parts of blogs.

### How to test it?

Deploy and navigate around blogs things including widget and see any error being thrown.

/cc @boton @adolfopa

It also includes the removal of stale editor classes in forms in https://github.com/liferay-frontend/liferay-portal/pull/1465/commits/9e980ca75543e5b85d5cb25290a46cc1021d5855. As agreed in https://liferay.slack.com/archives/CL8R04Z7X/p1631646432102300?thread_ts=1631645043.100700&cid=CL8R04Z7X

### CODE REVIEW

**Comment by diegonvs** [comment]
ci:reevaluate:1317401_433

**Comment by john-co** [comment]
ci:test:relevant

**Comment by john-co** [comment]
Reviewed. Test failures are unrelated. :heavy_check_mark: 
- 1% flaky test [WebContentStructures#ViewAndEditAsWellAsDeleteStructureWithAllFields](https://testray.liferay.com/home/-/testray/case_results/1561557799?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D1561557392%26testrayRunId%3D1561557523%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc ) cc/ @david-gutierrez-mesa @Tim-Cao

**Comment by diegonvs** [comment]
I'll forward to t-lima user :)

Thanks @john-co 🌳 💖

**Comment by diegonvs** [comment]
forwarded https://github.com/liferay-lima/liferay-portal/pull/2301 🎉 !

**Comment by diegonvs** [comment]
Why "forwarded" is too difficult to type?

https://user-images.githubusercontent.com/7663513/134065140-0fb9cf12-392f-4a98-af10-a60eca775fb0.mov

**Pull request closed without merging**
