### PR TITLE
LPS-127719 Clay:data-set-display tag returns sort == null

### PR DESCRIPTION
**Pull request by markocikos**
Fixes: https://issues.liferay.com/browse/LPS-127719

This is a followup on https://github.com/liferay-frontend/liferay-portal/pull/784. That PR was merged, but reverted because of a regression bug https://issues.liferay.com/browse/COMMERCE-5972

In this PR, we are still doing the same solution as concluded in https://github.com/liferay-frontend/liferay-portal/pull/784#issuecomment-790699767, implementing support for both param formats. The bug in [previous solution](https://github.com/liferay-frontend/liferay-portal/pull/784/commits/45f8dc633b77b641b789c17604f0f209a1d16647) was that we didn't handle the case when there are no sorting parameters. Code split an empty string into an array and broke on array[1].

For test case, see the the original LPP: https://issues.liferay.com/browse/LPP-39921. I tested on the provided sample module, and on a page that used to contain a regression bug.

after

### CODE REVIEW

**Review by jbalsas — CHANGES_REQUESTED** [review]
Hey @markocikos, thanks for this! I'm certain this will work, I was wondering if, while we're at it we'd want to add a couple of changes over this:

- Make `sort` the default case. Right now, we prioritize the unorthodox `sort.field` over `sort` which is apparently what we want to support by default. I'd say we want to invert the order of the conditionals to first handle `sort` and then, if not present, `sort.field`. 
- Add support for more sorting predicates. Right now, we only handle `field1:desc` as a valid value for sort, but  things like `field1:asc,field2:desc,field3:asc`. This can be seen in the [ODataParserImpl](https://github.com/liferay/liferay-portal/blob/master/modules/apps/portal-odata/portal-odata-impl/src/main/java/com/liferay/portal/odata/internal/sort/SortParserImpl.java#L79) in the initial `split` to separate the predicates before processing them.

/cc @nhpatt, @javierdearcos in case you could validate these 2 assumptions (specially the last one)

**Comment by markocikos** [comment]
> field1:asc,field2:desc,field3:asc

Would that imply sort over multiple columns? Would we apply left to right or right to left? :thinking: I don't think our [`SortFactoryUtil`](https://github.com/liferay/liferay-portal/blob/master/portal-kernel/src/com/liferay/portal/kernel/search/SortFactoryUtil.java) supports this, although there is some `ServiceProxyFactory` werdness there I don't completely understand. 

What we can easily do is support that format and apply the first or the last sort.

**Comment by jbalsas** [comment]
🤔  you're right... 

Vulcan is in fact returning `Sort[]` so not sure if we can apply this here or not.

Let's see if @javierdearcos and/or @nhpatt can help us out here to make a decission.

**Comment by jbalsas** [comment]
Going to forward since based on the current interface I don't think there's much more for us to do since we obviously only export a `Sort`. Ideally we could rework this so our `ContextProvider` manages multiple sorts, but it's starting to feel more like a feature we will want to have than a quick win here.

**Comment by jbalsas** [comment]
ci:forward

**Comment by nhpatt** [comment]
@jbalsas ups, sorry for answering late. We do support multiple sorts in headless/vulcan and it works with the elasticsearch integration. I'm not so sure about the direct service calls that go to the database, I'll check. 

I wasn't aware of the SortContextProvider in clay :)

**Comment by nhpatt** [comment]
Yeah, we also have some service/dynamicQuery calls that use Sort[].

_SortFactoryUtil_ does not support several sorts but it's called several times to build the array in the portal like: https://github.com/brianchandotcom/liferay-portal/blob/e97454173ec255d847c663823d4451b0b2e9bae4/modules/apps/knowledge-base/knowledge-base-web/src/main/java/com/liferay/knowledge/base/web/internal/KBUtil.java#L139

Odata's SortParser does not require an _EntityModel_ though. It won't do the mapping without it but it will parse the expression (basically a split by ; and several by :)

**Comment by jbalsas** [comment]
> Odata's SortParser does not require an EntityModel though. It won't do the mapping without it but it will parse the expression (basically a split by ; and several by :)

Oh, so you mean we should do `new SortParser(null).parse(sortString)`? Doesn't feel super clean... are you sure you'd want us to do this?

**Comment by nhpatt** [comment]
We should refactor it if you want to reuse it :)

I thought you were skipping supporting it atm.

**Comment by jbalsas** [comment]
> I thought you were skipping supporting it atm.

I was, but then you left 2 comments which seemed to imply we shouldn't 😂 

We have some Dataset features coming, so we can look at this when we get there.

**Pull request closed without merging**
