### PR TITLE
LPS-178066 CSP part 1 checks

### PR DESCRIPTION
**Pull request by izaera**
Follow up of #3628

### CODE REVIEW

**Comment by izaera** [comment]
ci:test:sf

**Comment by izaera** [comment]
ci:test:relevant

**Comment by mateusralv** [comment]
I'm on it 🕵🏽

**Comment by mateusralv** [comment]
Hey @izaera The failures are not related! 

[Testray comparison](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1693834432201&testrayRunIdA=2418030551&testrayRunIdB=2418230429)

**Comment by izaera** [comment]
ci:forward:force

**Comment by bryceosterhaus** [comment]
> ✔️ ci:test:stable - 31 out of 31 jobs passed in 1 hour 24 minutes

😮. Passing CI never ceases to amaze me

**Comment by izaera** [comment]
ci:forward:force

**Comment by izaera** [comment]
Sent manually -> https://github.com/brianchandotcom/liferay-portal/pull/140330

**Pull request closed without merging**
