### PR TITLE
LPS-135364 Missing colorpicker in table cell properties dialog

### PR DESCRIPTION
**Pull request by holatuwol**
https://issues.liferay.com/browse/LPS-135364

### Steps to reproduce

1. Navigate to Content & Data > Web Content
2. Use the + button to begin drafting a new web content article
3. Add a table (number of rows/columns does not matter)
4. Right click in a cell and choose to update the cell properties

Expected behavior is that the cell properties dialog offers a "choose" button next to the color selection to load a color picker.
Actual behavior is that the cell properties dialog lacks such "choose" buttons.

### Solution notes

The colordialog plugin was removed by default with liferay-ckeditor 4.14.x, in https://github.com/liferay/liferay-ckeditor/commit/cc4b314b87885823eee05a4021f6d17a5c43c158

In maintenance branches, we re-added the colordialog plugin with [LPS-125798](https://issues.liferay.com/browse/LPS-125798):

* 7.2.x: https://github.com/liferay/liferay-portal-ee/commit/ba4b0cebad5251865723a455faad3b92e07bcc75
* 7.1.x: https://github.com/liferay/liferay-portal-ee/commit/5218313220d31c6a484a34c85b405f2ad1fee7e3
* 7.0.x: https://github.com/liferay/liferay-portal-ee/commit/65a8435c6dcb32490c50f779f5b367fa5b91275e

However, these changes were not applied to master, so I thought that it would make sense to add only what we need to resolve this specific issue found by QA.

With that being said, if we intentionally removed color picker and do not need this functionality for master in the table cell properties dialog, I can let QA know that this is expected behavior in master so we can proceed with backporting the original fix where the table cell properties dialog was incomplete in the ways described in the linked ticket.

### CODE REVIEW

**Comment by holatuwol** [comment]
ci:test:sf

**Comment by bryceosterhaus** [comment]
I don't have much context for this, pinging @diegonvs & @markocikos in case they might know better

**Comment by carloslancha** [comment]
Hey @julien do I remember correctly about you setting the current active plugins for ckeditor in dxp? If so you probably have better context about this and its implications. Thx!

**Comment by julien** [comment]
@carloslancha we do have a set of default plugins enabled for ckeditor regardless of the application defined [here](https://github.com/liferay/liferay-ckeditor/blob/cc63d964e50bd4d13671bc13c993433ef1b23dbf/support/build-config.js#L35-L68), then in dxp, we also have a set of "default extra plugins", in the [file](https://github.com/liferay/liferay-portal/blob/4ceac20a949a25b57642f3a9179f556524154eb0/modules/apps/frontend-editor/frontend-editor-ckeditor-web/src/main/java/com/liferay/frontend/editor/ckeditor/web/internal/editor/configuration/CKEditorConfigContributor.java) (that was modified in this pull request) and finally each application can use a "custom editor config contributor" to add or remove plugins. 

It's been a few months since I haven't worked on anything related to ckeditor, so I'd say the best person on the team right now to know which plugins are needed in "Web Content" is @diegonvs, but if it's just for that application, then I'd say it's probably [this](https://github.com/liferay/liferay-portal/blob/4ceac20a949a25b57642f3a9179f556524154eb0/modules/apps/journal/journal-editor-configuration/src/main/java/com/liferay/journal/editor/configuration/internal/JournalMediaEditorConfigContributor.java) file that we want to update.

**Review by markocikos — COMMENTED** [review]
The question here is, what scope do we want for the change? This is a product question more than code question, so summoning @dsanz to weigh in. 

- I don't think it makes sense to apply it to **all** editors, as right-click features are disabled on Balloon Editor. Although, this may change later down the line. If this was out intent, the best course would be to update the [file on ckeditor repo](https://github.com/liferay/liferay-ckeditor/blob/cc63d964e50bd4d13671bc13c993433ef1b23dbf/support/build-config.js#L35-L68).
- I don't think it makes sense to apply this **only** to blogs. The [JIRA ticket](https://issues.liferay.com/browse/LPS-135364) mentions blogs, while testing in this PR is in journal. There is nothing in the feature that is remotely specific to either product.
- The last option is to apply it to all Classic Editors, which this PR does. I think this is fine, the color-picking feature seems useful to me in any context.

Sidenote, not a blocker for this PR: one thing I would like to do, at some point, is to migrate Classic Editor default configuration to JS. [We did this with Balloon Editor](https://github.com/liferay/liferay-portal/blob/master/modules/apps/frontend-editor/frontend-editor-ckeditor-web/src/main/resources/META-INF/resources/editor/config/DefaultBalloonEditorConfiguration.js). The way it is now, Classic Editor defaults only work if they are invoked through `<liferay-editor:editor>`. If defaults are in JS, they will be checked both thorough tag and direct React import.

**Comment by dsanz** [comment]
If we provide the table button (as we do in the "simple" toolbar, which is the default for most apps), then we have to allow users to use table properties modals, and that means to me that the colorpicker is needed to provide a much better UX.

A different discussion is whether our plugins shall be tied to the toolbars we provide, so that the resulting editor we ship to the page contains exactly what's meant to be needed, no more, no less. We might leave this discussion for future enhancements in the toolbar configurability which we have in the roadmap. As a side note, one can paste a table into a MBThread and expect the cell properties to behave properly, even if that editor does not provide table button ootb.

Said that, I agree with Marko's points. Solving it in the CKEditorContributor looks ok to me.

> Sidenote, not a blocker for this PR: one thing I would like to do, at some point, is to migrate Classic Editor default configuration to JS. [We did this with Balloon Editor](https://github.com/liferay/liferay-portal/blob/master/modules/apps/frontend-editor/frontend-editor-ckeditor-web/src/main/resources/META-INF/resources/editor/config/DefaultBalloonEditorConfiguration.js). The way it is now, Classic Editor defaults only work if they are invoked through `<liferay-editor:editor>`. If defaults are in JS, they will be checked both thorough tag and direct React import.

+1 note that down for the tech debt ;)

**Review by markocikos — APPROVED** [review]

**Comment by markocikos** [comment]
CI failure looks very much unrelated. Forwarding!

**Comment by markocikos** [comment]
ci:forward

**Pull request closed without merging**
