### PR TITLE
Commerce 3885 Implement order date filter on orders dataset display

### PR DESCRIPTION
**Pull request by luca-pellizzon**
Implementing a new filter for orders dataset display.
Currently the date range filter frontend component is ready, but the back structure is missing.

In order to do so, a new date-range filter has been added to frontend-taglib-clay and then the filter is applied to the orders dataset table.

Testing it is just a matter of filtering the dataset table used for orders list in the commerce admin section.

cc @riccardo-alberti @marco-leo @FabioDiegoMastrorilli

### CODE REVIEW

**Comment by luca-pellizzon** [comment]
https://github.com/liferay-commerce/liferay-portal/pull/396 also contains the Commerce part of the code

**Comment by luca-pellizzon** [comment]
Not able to add reviewers so tagging here @jbalsas @brunobasto 
Thank you.

**Comment by wincent** [comment]
Bruno is no longer at Liferay, and Chema is on PTO today, so I'll mention @izaera who is The Java Dude™ on the frontend infra team.

**Comment by izaera** [comment]
LGTM as long as it works :sweat_smile:

**Comment by izaera** [comment]
ci:test:sf

**Comment by izaera** [comment]
ci:test:relevant

**Comment by izaera** [comment]
ci:forward

**Pull request closed without merging**
