### PR TITLE
LPS-119211 Adds ApplicationsMenu Application Selector to Portlet Header

### PR DESCRIPTION
**Pull request by jbalsas**
This is a slight revamp of https://github.com/liferay-echo/liferay-portal/pull/1959 and the second part of the split of https://github.com/liferay-frontend/liferay-portal/pull/289 which covers the first [UX Refinement for Applications Menu](https://issues.liferay.com/browse/LPS-117782)
- [Show Application Section in Control Menu](https://issues.liferay.com/browse/LPS-119209)
- [Show Related Applications Dropdown in Control Menu](https://issues.liferay.com/browse/LPS-119211)

I tried to reduce the amount of checks we do from the previous version and testing it again I don't perceive a noticeable regression. Since the `portlet_header` is only included in admin apps, there should be no impact on performance tests either.

If we want to further improve server-side performance, we can do something similar to the `ProductsMenu` component that rather than the list of Apps gets an endpoint to retrieve it asynchronously. I didn't do it this way because we need to know in advance if we have 1 or more apps in a section in order to show a dropdown, so there's no easy way to avoid the calculation.

90763509-1f611400-e2e7-11ea-939d-8b314868759a

90763494-14a67f00-e2e7-11ea-9a99-6512ab53c240

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:test:sf

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
From https://github.com/liferay-echo/liferay-portal/pull/1987#issuecomment-678986009 by @ealonso

> Hey @jbalsas,
> 
> A normal use case that we have in portal is allow developers change the the portlet title, for example when we are editing or adding a new entity we change the portlet title, please see the following screenshots:
> 
> Test_Test_-_Edit_User_Test_Test_-_Control_Panel_-_Liferay
> 
> Add_User_-_Control_Panel_-_Liferay
> 
> Is it the expected behaviour? Could you please take a look at it?
> 
> Regards,
> Eudaldo.

@victorvalle and @ryconn888 can you weigh in on this?

**Comment by marcoscv-work** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jbalsas** [comment]
Going to forward this so we can start getting some eyes on DXP other than ours and have enough time to adjust whatever's necessary.

**Comment by jbalsas** [comment]
ci:forward

**Comment by ealonso** [comment]
Hey @jbalsas,

Who is the owner of Application Menu? If the owner of this component is the Echo team I prefer to wait for this one. 

Regards,
Eudaldo.

**Comment by jbalsas** [comment]
Sure... it was in liferay-echo#1959 and you sent it to me... do you want me to send it back to @liferay-echo again?

**Comment by ealonso** [comment]
IMHO, we should wait for the question, **Is it the expected behaviour?**

**Comment by jbalsas** [comment]
@victorvalle said `the selector seems to be ok` in the `#p-applications-menu` channel which I took as indication that this could move forward... but makes sense.

This is indeed part of Echo, so they can signal you if they're okay with this or not so you can send it.

I'm happy to apply any additional changes if necessary, just let me know.

**Comment by ealonso** [comment]
Sorry I didn't realize about Victor's comment, if it is the expected behaviour, then perfect, go ahead.

**Comment by jbalsas** [comment]
I might've been too eager to think that's what he was saying, so I don't mind waiting for definite confirmation.

**Comment by jbalsas** [comment]
Confirmed by @victorvalle that they want to think this over... reopening here so they can comment when they've made up their minds.

**Comment by victorvalle** [comment]
We see problems on the dropdown selector when navigating to applications inside Asset Libraries. For example Web Content, D&M, ...

We believe in this case it is better to remove the dropdown selector since this concrete scenario is prominent and we haven't found a suitable solution.

**Comment by jbalsas** [comment]
Understood! Closing then!

I assume we also don't want the section header on top of the title, right?

**Comment by victorvalle** [comment]
That is right, we don't want the section header on top of the title

**Pull request closed without merging**
