### PR TITLE
LPS-158083 build absolute url for custom element resources when their…

### PR DESCRIPTION
**Pull request by dsanz**
… URL is relative

### CODE REVIEW

**Comment by izaera** [comment]
:thinking_face: I think this will be "magically" fixed by this PR -> https://github.com/brianchandotcom/liferay-portal/pull/120568, which is the one moving the rendering of <script> nodes to the portlet machinery, instead of [using the DynamicInclude](https://github.com/liferay-frontend/liferay-portal/pull/2540/files#diff-0af5fa9f5880416ac7bec060b0e27d9c9ffcc95dec51bcaf2545fe9f51d19d26R65)...

I'll check if it is the case, cause I'm not 100% sure that we can rely only in the porlet headers to add the path contexts and so on...

**Comment by izaera** [comment]
Set to draft until we determine if it is really necessary

**Comment by dsanz** [comment]
yes, if we could fix it in that way, it'd be much better as we'd avoid adding the js on every page. You're fast man 
image

**Comment by izaera** [comment]
Resent as https://github.com/liferay-frontend/liferay-portal/pull/2547

**Pull request closed without merging**
