### PR TITLE
LPS-113526 - Deprecate AUI util `getAttributes`

### PR DESCRIPTION
**Pull request by kresimir-coko**
This util is only used inside the already deprecated `selectEntityHandler`, and is replaced by the vanilla JS `getAttribute` method which is why I decided against modernizing it.

### CODE REVIEW

**Comment by kresimir-coko** [comment]
ci:reevaluate:1377401_417

**Comment by kresimir-coko** [comment]
ci:test:relevant

**Comment by kresimir-coko** [comment]
ci:test:relevant

**Comment by kresimir-coko** [comment]
ci:test:relevant

**Review by bryceosterhaus — APPROVED** [review]
LGTM!

**Comment by kresimir-coko** [comment]
ci:forward

**Pull request closed without merging**
