### PR TITLE
[WIP][7.4-Only][PART-1] LPS-127085 Migrate frontend-css-web

### PR DESCRIPTION
**Pull request by edalgrin**
The scope of this PR is to remove `frontend-css-web` following the migration strategy established in https://issues.liferay.com/browse/LPS-132258 (TL;DR Remove the unused styles, move the styles to modules where possible and move the styles to frontend-theme-styled where is not possible)

This PR is the first part of the frontend-css-web migration, it removes completely the `portal` folder and contains:
- https://github.com/liferay-frontend/liferay-portal/pull/1129
- https://github.com/liferay-frontend/liferay-portal/pull/1147
- https://github.com/liferay-frontend/liferay-portal/pull/1137
- https://github.com/liferay-frontend/liferay-portal/pull/1139
- https://github.com/liferay-frontend/liferay-portal/pull/1143

<table>
    <thead>
      <tr>
        <th>Before</th>
        <th>After</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td></td>
        <td></td>
      </tr>
    </tbody>
</table>

---

**How to test this PR?**

Several modules has been slightly changed to relocate the styles from `frontend-css-web` so the easiest way to test it is to launch an `ant all`

To test the modules manually it'll be necessary to deploy:
- modules/apps/frontend-css/frontend-css-web/
- modules/apps/frontend-theme/frontend-theme-classic/
- modules/apps/frontend-theme/frontend-theme-admin/
- modules/apps/comment/comment-web/
- modules/apps/commerce/commerce-product-content-web/
- modules/apps/document-library/document-library-web/
- modules/apps/dynamic-data-lists/dynamic-data-lists-web/
- modules/apps/dynamic-data-mapping/dynamic-data-mapping-form-web/
- modules/apps/dynamic-data-mapping/dynamic-data-mapping-web/
- modules/apps/frontend-editor/frontend-editor-ckeditor-web/
- modules/apps/frontend-js/frontend-js-aui-web/
- modules/apps/frontend-taglib/frontend-taglib/
- modules/apps/item-selector/item-selector-taglib/
- modules/apps/knowledge-base/knowledge-base-web/
- modules/apps/mobile-device-rules/mobile-device-rules-web/
- modules/apps/polls/polls-web/
- modules/apps/portal-settings/portal-settings-authentication-cas-web/
- modules/apps/product-navigation/product-navigation-control-menu-web/
- modules/dxp/apps/portal-search-tuning/portal-search-tuning-rankings-web/
- portal-kernel/
- portal-web/

The result is positive when no difference can be noticed in the UI and there's a small improvement in the performance.

### CODE REVIEW

**Comment by edalgrin** [comment]
ci:test:sf

**Comment by edalgrin** [comment]
it works, so far 😄 
image

**Comment by edalgrin** [comment]
first test
image

**Comment by marcoscv-work** [comment]
A really good improvement by the moment, just to remember we come from:
https://liferay.atlassian.net/wiki/spaces/ENGFRONTENDINFRA/pages/edit-v2/1537640890

**Comment by marcoscv-work** [comment]
LGTM, ready to send!

**Comment by edalgrin** [comment]
ci:test:sf

**Comment by edalgrin** [comment]
ci:test:relevant

**Comment by edalgrin** [comment]
https://github.com/liferay-frontend/liferay-portal/pull/1186

**Pull request closed without merging**
