### PR TITLE
LPS-168787 Add role none to the list so that it is ignored by the screen reader

### PR DESCRIPTION
**Pull request by veroglez**
It fixes https://issues.liferay.com/browse/LPS-168787

### CODE REVIEW

**Comment by mateusralv** [comment]
I'm taking a look 🕵🏽

**Comment by mateusralv** [comment]
Hi @veroglez the failures are not related.

[Testray comparison ](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1680188029928&testrayRunIdA=2248034738&testrayRunIdB=2250694900)

**Review by markocikos — APPROVED** [review]
LGTM! :sparkles:

**Comment by markocikos** [comment]
ci:forward

**Pull request closed without merging**
