### PR TITLE
LPS-167608 HR_118 The description text field doesn't have any characters hints

### PR DESCRIPTION
**Pull request by veroglez**
Fixes:
- https://issues.liferay.com/browse/LPS-167608
- https://issues.liferay.com/browse/LPS-168281

### CODE REVIEW

**Comment by CarlosBrichete** [comment]
Hey @veroglez, the failures in the relevant run seem to not be related to your changes, they were failing previously :)

**Comment by ethib137** [comment]
Hey @dsanz , @veroglez is on holiday until next week, but this was just waiting on a review and approval from frontend-infra to be forwarded.

**Review by bryceosterhaus — APPROVED** [review]
LGTM!

**Comment by ethib137** [comment]
ci:forward

**Comment by ethib137** [comment]
ci:forward:force

**Comment by ethib137** [comment]
ci:forward:force

**Comment by ethib137** [comment]
Manually forwarded here https://github.com/brianchandotcom/liferay-portal/pull/134773 with minor wordsmithing.

**Comment by ethib137** [comment]
ci:close

**Pull request closed without merging**
