### PR TITLE
LPS-151954 - Fix console error in MT when FF is disabled

### PR DESCRIPTION
**Pull request by tinycarol**
### References

- [LPS-151954](https://issues.liferay.com/browse/LPS-151954)

### What is the goal?

* Fix console error in Management Toolbar when feature flag is disabled by using ternary operator instead of &&.

#### Before fix

https://user-images.githubusercontent.com/6642927/164480432-5354ba79-eaba-4b78-bdf7-bfa7d18db519.mov

#### After fix

https://user-images.githubusercontent.com/6642927/164480449-c4423bc9-675f-421f-af31-b4855931a622.mov

### How to replicate
* Go to `Content & Data > Web Content`
* Open JS console (Cmd+Opt+I in MacOS)
* See that there's no error

### CODE REVIEW

**Comment by tinycarol** [comment]
ci:reevaluate:1327401_3619

**Review by carloslancha — CHANGES_REQUESTED** [review]
LNHTM, avanti!

**Review by carloslancha — APPROVED** [review]
LNHTM! Avanti!

**Comment by carloslancha** [comment]
giphy

**Comment by tinycarol** [comment]
ci:test:sf

**Comment by tinycarol** [comment]
ci:test:relevant

**Comment by tinycarol** [comment]
ci:close

**Comment by tinycarol** [comment]
ci:close

**Pull request closed without merging**
