### PR TITLE
LRQA-60526 | master

### PR DESCRIPTION
**Pull request by john-co**
**Description**
Trying to close the alert message causes test flakiness due to auto close alert message timing issues with poshi. Also, closing the alert message is not required for a global macro to view the alert message. Therefore, we're simply removing the close button action in the macro. In general, a waitFor function or some other workaround is advised instead of using strict assertions in macros which are mostly used for test setup purposes. Component QA teams will follow up on any if at all non-acceptance tests affected by this change.

**Test Plan**
- Validate ci:test:acceptance passes or failures are unrelated

**JIRA Ticket**
https://issues.liferay.com/browse/LRQA-60526

### CODE REVIEW

**Comment by john-co** [comment]
`ci:test:acceptance` passed in https://github.com/john-co/liferay-portal/pull/364#issuecomment-754744993 :heavy_check_mark:

**Comment by john-co** [comment]
ci:test:sf

**Comment by john-co** [comment]
ci:test:relevant

**Comment by john-co** [comment]
@wincent, I'm just gonna forward this since you and Chema are out this week. It seems trivial enough, I also didn't hear any objections from other QA members the past couple days so it can be said it was reviewed by other QA.

**Comment by john-co** [comment]
ci:forward

**Comment by jbalsas** [comment]
Hey @john-co, I would expect this to cause all sorts of other flakiness.

```
	macro viewSuccessMessage {
		VerifyElementPresent(locator1 = "Message#SUCCESS_DISMISSIBLE");

		// if (IsElementPresent(locator1 = "Button#CLOSE_MESSAGE")) {
		// 	Click(locator1 = "Button#CLOSE_MESSAGE");
		// }
	}
```

Since alerts go away on a timer, now there's a chance that the verification succeeds in finding a previous instance of a success message. 

This is also another example of how tests can hamper future development. 
- What are we truly looking for here?
- What happens if tomorrow we change the way we present the information? -> we need to update all the tests

I would strongly advice to look into what means for an action to be successful (HTTP codes, SessionErrors, responses...) and use some of those ideas to validate if an action completed successfully rather than depending on an implementation specific UI.

/cc @manoelcyreno

**Comment by manoelcyreno** [comment]
What are we truly looking for here?
> Refactor the poshi code to do what he needs to do, in this case, we only want to check if the success message appears, we not want to close the success message, so we are deleting this part of the code that should not be part of this method (and for the future, we will have one method only to it).

What happens if tomorrow we change the way we present the information?
> I will consider that the success message will keep appearing, but in a different way, so we only will need to change the XPath, the logic will be the same.

**Comment by jbalsas** [comment]
> I will consider that the success message will keep appearing, but in a different way, so we only will need to change the XPath, the logic will be the same.

That's exactly what makes all this extremely fragile. The UI changes way faster than other things, so trying to rely on more stable conditions could lead to more stable tests. Once again, this is one of the main reasons why trivial changes in DXP take long time to happen or render CI useless for a while until all those need to catch up again.

> [...] we only want to check if the success message appears [...]

But why do you want to check if the success message appears?

Your main goal is not to assert if the success message appears, but to make sure a specific action completed successfully. My question is... could you figure out better ways to assert that that do not depend on a visible UI component showing? 

You skipped the fact that doing this is likely to cause all sorts of other test flakiness because you depend on a component which state now you don't control or reset.

**Comment by manoelcyreno** [comment]
> That's exactly what makes all this extremely fragile [...]
This is what we want to change, using the XPath (in the right way) the UI can change and everything will keep working, but the XPath should be written in the right way ... (this is one action that we want to encourage to our QAs in 2021)

> But why do you want to check if the success message appears? [...]
this should be the first assertion, the second should be verify in the UI if the thing was created ... 

> could you figure out better ways to assert that that do not depend on a visible UI component showing? [...]
as we have poshi right now, I don't think, for this reason, we are evaluating other automation tools (like cypress) to solve some of our problems with poshi and we are writing new "desirable" features to be implemented in poshi (or any other tool), as a database validation ...

**Comment by jbalsas** [comment]
> This is what we want to change, using the XPath (in the right way) the UI can change and everything will keep working, but the XPath should be written in the right way ... (this is one action that we want to encourage to our QAs in 2021)

I remember reading papers proving there was no such thing as a "right way" for XPath.  I'll let you figure this out. I feel like I've tried to voice my concerns multiple times over the course of many years but it feels we're doomed to end up in the same place.

I sincerely hope QA does find the right way so next time we want to change the alert position we can do it in a day rather than in a month.

**Comment by manoelcyreno** [comment]
> I sincerely hope QA does find the right way so next time we want to change the alert position we can do it in a day rather than in a month

this is was we are trying to do ... right now the cost of fix (or develop) something in poshi is very high, we are trying to find some way to decrease it ... 

I understand what you want to tell in terms of "_no such thing as a 'right way' for XPath_", but with poshi ... this is what we have right now...

**Pull request closed without merging**
