### PR TITLE
LPS-116988 Update react-dnd to v11.1.1

### PR DESCRIPTION
**Pull request by wincent**
Matches the upgrade that we prepared for the Commerce folks on 7.1.x:

- https://github.com/wincent/liferay-portal-ee/pull/9
- https://github.com/wincent/liferay-portal-ee/pull/10

What's going on here:

-  Bump version numbers from 10.0.1 to 11.1.1; there are later versions out now, but they bring nothing of value and given that we've seen 11.1.1 working on 7.1.x, I want to stay in line with that.

-  Adjust `HTML5Backend` imports; this is the breaking change in [the v10 to v11 update](https://github.com/react-dnd/react-dnd/releases/tag/v11.0.0): previously it was a default export but now it is a named export.

-  Configure `frontend-js-react-web` to get `domain` from `frontend-js-node-shims`; this is because `domain` is `require()`-ed [here](https://github.com/react-dnd/asap/blob/b6bebeb7342/src/node/raw.ts#L87), which would cause the loader to throw an error.

-  Configure `frontend-js-react-web` to get `process` from `frontend-js-node-shims`; this is because — the horror 😱 — `@react-dnd/asap` [expects it to be a global](https://github.com/react-dnd/asap/blob/b6bebeb7342/src/node/asap.ts#L24).

   We set up this global in the index of `frontend-js-react-web`, to be sure that it is set by any client that may conceivably need it.

   If we don't do this, drag-and-drop works fine, but when you try to navigate away from a page, we hit the above line and an error is thrown, breaking the transition and spewing out a bunch of red crap into the console.

-  Note that only `frontend-js-react-web` needs these imports configured. Other modules that use `react-dnd` get it from `frontend-js-react-web` and don't need to meddle with the transitive dependencies themselves; at least, in my testing of a couple of places (`segments-web` and `layout-content-page-editor-web`) I didn't see any loader errors.

-  Drop forced resolution of `dnd-core`. Previously, we were doing that in order to avoid running into all the above problems with `domain` and friends. By using an older version of `dnd-core`, we avoided the problematic `@react-dnd/asap` fork of the `asap` package, which [came into react-dnd in v10.0.2](https://github.com/react-dnd/react-dnd/commit/ada65550b75).

   We can no longer use this resolution because resolutions are a very limited tool: they allow us to control what gets installed at build time but they do not influence what happens at runtime. In other words, if a package like `dnd-core` has a dependency with a range like "^3.0.0", and we want to pin to version "3.0.1" or something else compatible, then resolutions work well. But as soon as the range changes to "^4.0.0" we can no longer useful pin to "3.0.1", even if we know it to be compatible: Yarn will install the version we require, but at runtime the loader will blow up because the dependency graph says that `dnd-core` wants "^4.0.0" and we won't have it due to the resolution.

One thought: it would be nice if we could force the various pieces of our module loading system (bundler, loader, registry) to work with react-dnd without these hacks, but that is probably beyond the scope of this task. If you look at [their package.json](https://github.com/react-dnd/asap/blob/b6bebeb7342/package.json#L15-L26), you can see how they've tried to make it work via `"main"` and `"browser"` fields, but I'm not even sure they're doing it right...

Test plan: Test drag and drop in two apps (`segments-web` and `layout-content-page-editor-web`); see it working with no errors in console. Run all JS unit tests in repo.

Mentioning reviewers:

- @julien, who worked on the last react-dnd upgrade and added the resolutions field.
- @izaera, the bundler/loader connoisseur.
- @jbalsas, the person we all turn to when looking for authorization to ship an *egregious hack*.

### CODE REVIEW

**Comment by wincent** [comment]
ci:test:sf

**Comment by wincent** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
LGTM I guess... I would forward this if green and check for smoke... what could go wrong? 🤷 

The only valuable thought I can share right now based on `react-dnd` requiring `node-shims` to run in the browser is that maybe it's time we look for a different library? 😂

**Comment by wincent** [comment]
> or could we contribute upstream and help the JS community as a whole?

They might be receptive to it (they were when [I reported the problem](https://github.com/react-dnd/react-dnd/issues/2441) with their circular dependencies). In this case, the reason why I didn't go straight there is that I am not confident about what "the right" pattern actually is for fields in the `package.json`, and it's not clear that it's not us that isn't doing something wrong...

They've got a `main` field pointing at a node-specific artifact (which is the one we're implicitly using), then they've got the `module` and `browser` fields that maps to alternative implementations in their "dist/esm/browser/" directory. Despite the "esm" in the path, those artifacts are just standard CommonJS builds. @izaera: should our bundler/loader/registry infra pick up and use `browser` overrides like that automatically?

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
Didn't stay around to forward this yesterday, so... forwarding now 🤷

**Comment by jbalsas** [comment]
@izaera, still waiting on your comments... we can always undo this if necessary

**Comment by jbalsas** [comment]
ci:forward

**Comment by izaera** [comment]
@wincent Currently we implement the `browser` field with two plugins:

- [This plugin](https://github.com/liferay/liferay-js-toolkit/tree/master/packages/babel-plugin-alias-modules) rewrites aliased require calls
- [This plugin](https://github.com/liferay/liferay-js-toolkit/tree/master/packages/liferay-npm-bundler-plugin-replace-browser-modules) replaces aliased modules

We also have this [huge issue](https://github.com/liferay/liferay-js-toolkit/issues/365) explaining how everything is implemented and why.

As far as I remember the problem is that people began using the `browser` field to distribute bundled copies to be included with a `<script>` tag but then realized that it was not intended for that. Unfortunately it was too late and different projects were using the same field for different things. Then they added the `unpkg` and `jsdelivr` to add more noise to the party.

The `react-dnd` version you are using (11.1.1) does not ship with a `browser` field so the bundler is never going to use any alternative JS file for the browser.

There's a `dist/esm` folder referenced by the `module` header, which we can't use because it's not ES5.

And there's also a `dist/umd` folder that bundles the whole library and exports it through UMD. That could do the trick (not needing shims) but nobody references it in package.json, I think. So it's never going to be used... :shrug:

**Comment by izaera** [comment]
The link you pasted above ([asap's package.json](https://github.com/react-dnd/asap/blob/b6bebeb7342/package.json#L15-L26)) only appears in the source code, not in the downloaded version of `react-dnd` that goes to `node_modules`. 

I suspect that file is used to make the UMD build. In theory it's correct and, AFAIK, it would be used by the bundler if it was in the dist version (but as I said it isn't).

**Comment by wincent** [comment]
> The `react-dnd` version you are using (11.1.1) does not ship with a `browser` field so the bundler is never going to use any alternative JS file for the browser.

@izaera: The links I provided to `@react-dnd/asap` are because *that's* the one with the problematic Node-only dependencies in it, as well as the `main`/`browser` field shenanigans. `@react-dnd/asap` is a transitive [dependency of `react-dnd`](https://github.com/react-dnd/react-dnd/blob/abd3132710bde6ce065aef9d0c50b2d5f8823598/packages/core/react-dnd/package.json#L22) ([via `dnd-core`](https://github.com/react-dnd/react-dnd/blob/abd3132710bde6ce065aef9d0c50b2d5f8823598/packages/core/dnd-core/package.json#L20)).

> As far as I remember the problem is that people began using the `browser` field to distribute bundled copies to be included with a `<script>` tag but then realized that it was not intended for that. Unfortunately it was too late and different projects were using the same field for different things. Then they added the `unpkg` and `jsdelivr` to add more noise to the party.

This pretty much confirmed my fears. Thanks for clarifying.

shit-show

**Comment by izaera** [comment]
> The links I provided to @react-dnd/asap are because that's the one with the problematic Node-only dependencies in it, as well as the main/browser field shenanigans. @react-dnd/asap is a transitive dependency of react-dnd (via dnd-core).

Ah, that explains why I couldn't find it in `node_modules`. I missed the scope part and was looking for it without `@react-dnd` in the console :sweat_smile: .

**Comment by wincent** [comment]
> Ah, that explains why I couldn't find it in `node_modules`. I missed the scope part and was looking for it without `@react-dnd` in the console 😅 .

Indeed... their package names are:

- `react-dnd`
- `react-dnd-html5-backend` 
- `@react-dnd/asap`
- `dnd-core`

And those, *naturally*, live respectively at:

- `packages/core/react-dnd` (in the react-dnd/react-dnd monorepo)
- `packages/core/html5-backend` (in the react-dnd/react-dnd monorepo)
- in react-dnd/asap fork
- `packages/core/dnd-core` (in the react-dnd/react-dnd monorepo)

And that's not even all of them...

simple

**Pull request closed without merging**
