### PR TITLE
[7.4-only] LPS-121976 Delete temporary clay:*-card-v2 tags

### PR DESCRIPTION
**Pull request by markocikos**
Fixes: https://issues.liferay.com/browse/LPS-121976

This is the last task in the [cards update epic](https://issues.liferay.com/browse/LPS-121933). :tada: 

We are deleting temporary v2 tags, and deprecating old unused tag classes.

@julien @carloslancha

### CODE REVIEW

**Comment by markocikos** [comment]
ci:test:sf

**Comment by markocikos** [comment]
ci:test:relevant

**Review by jbalsas — CHANGES_REQUESTED** [review]
Let's just **remove** these classes. We will be removing the `TemplateRenderer` and `ComponentRenderer` super classes and Soy won't be available in any case, so no need to go through the deprecation phase.

In this particular instance, the class also only serves for binary compatibility. That is, removing it will only affect people directly extending from `*CardTag` which is not something very common. Finally, the workaround for the removal is to simply copy the class to your own module. All this combined makes deprecating the classes overkill.

**Comment by wincent** [comment]
destroy

**Comment by markocikos** [comment]
ci:test:sf

**Comment by markocikos** [comment]
ci:test:relevant

**Comment by markocikos** [comment]
Force-pushed with the class deletions, and package semver update.

The https://github.com/liferay-frontend/liferay-portal/pull/605/commits/75f1e593f4a15ed511671eca735de2cbb6466fe6 commit is kernel semver update. I did an `ant all` as one more check after class selection, it generated this update. It fixes version in master, unrelated to this PR. It should fix failure in https://github.com/liferay-frontend/liferay-portal/pull/605#issuecomment-742480787. If it causes a conflict, I'll remove the commit and resend.

**Comment by markocikos** [comment]
Failure in https://github.com/liferay-frontend/liferay-portal/pull/605#issuecomment-742546769 seems unrelated. I guess we can wait a day, rebase after kernel update and retest. We could manually push, but there is probably no reason to rush.

**Comment by jbalsas** [comment]
> Failure in #605 (comment) seems unrelated. I guess we can wait a day, rebase after kernel update and retest. We could manually push, but there is probably no reason to rush.

I'd say, let's get this over with!

Remove the kernel update and push manually so we can wrap this up. There's also little point in keeping another thread open that takes away your energy and focus.

**Comment by markocikos** [comment]
Manually forwadred to https://github.com/brianchandotcom/liferay-portal/pull/96804

**Comment by jbalsas** [comment]
imnotcrying

**Pull request closed without merging**
