### PR TITLE
LPS-123559 - Update @liferay/npm-scripts to v36.0.0

### PR DESCRIPTION
**Pull request by bryceosterhaus**
https://issues.liferay.com/browse/LPS-123559

@wincent, you might have a better idea on this yarn.lock, but the amount of changes seem pretty drastic here. I assume its from all the webpack 5 stuff, but is this expected?

### CODE REVIEW

**Comment by bryceosterhaus** [comment]
ci:test:sf

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by izaera** [comment]
Set to draft because of https://liferay.slack.com/archives/G3JBR21HA/p1605543568167900

**Comment by wincent** [comment]
As [36.0.1 is now out](https://github.com/liferay/liferay-frontend-projects/releases/tag/npm-scripts%2Fv36.0.1), closing this one. @izaera said he'd prepare a new pull, and as it involves changes to the webpack set-up used by headless, we'll need to mention them on the new PR.

**Pull request closed without merging**
