### PR TITLE
[TS] LPS-122917

### PR DESCRIPTION
**Pull request by crodriguezy**

### CODE REVIEW

**Comment by crodriguezy** [comment]
Hi, these changes suggested by @antonio-ortega fix the behaviour described in https://issues.liferay.com/browse/LPS-122917:

1. Create a new page called 'test'.
2. Go to Home page and click on the dropdown menu of Menu Display -> focus moves to the options. 
3. From the Menu Display, click on 'test'.
4. Now on 'test' page, click on the dropdown menu of Menu Display -> focus does not move to the options 

Note: It is not reproducible with SPA disabled.

**Comment by crodriguezy** [comment]
Hi @liferay-frontend team,

Did you have the time to review this PR? Do you see any problem with it?

Thanks

**Comment by bryceosterhaus** [comment]
@markocikos, I think you might have some more experience with this bit of code to review it.

**Review by markocikos — COMMENTED** [review]
@crodriguezy The solution in this PR does not seem to fix the issue:
screenshot

I am testing this on mater, latest Chrome.

**Comment by crodriguezy** [comment]
Hi @markocikos ,

Could you please test the steps of [my first comment](https://github.com/liferay-frontend/liferay-portal/pull/2139#issuecomment-1105369555)?
Thank you

**Comment by markocikos** [comment]
@crodriguezy The PR fixes the case in https://github.com/liferay-frontend/liferay-portal/pull/2139#issuecomment-1105369555, but it seems to be similar but different case than the original one in https://issues.liferay.com/browse/LPS-122917.

Another problem with the solution in this PR is that we are adding event listeners, but not cleaning them. Initialization should not be done every time in `focusManager` getter, or we should explicitly cleanup listeners. I added a console log to illustrate this in gif below:

screenshot

**Comment by crodriguezy** [comment]
Hi @markocikos , thank you for pointing the event listeners problem. I think the best approach would be removing the old listeners, because of what was concluded in https://issues.liferay.com/browse/PTR-3010: basically we need to instantiate it everytime we need it to avoid this kind of problems.

Could you please suggest a way to clean them properly?

Thank you again

**Comment by crodriguezy** [comment]
Ok @markocikos 

I'll resend the PR with the temporal workaround suggested. 

About:

> It's important to note: while this fixes the case in https://github.com/liferay-frontend/liferay-portal/pull/2139#issuecomment-1105369555, it does not fix the original case in [JIRA ticket](https://issues.liferay.com/browse/LPS-122917.).

Given we've been already working on this I'll change the original steps and create a new LPS with the original ones

Thanks

**Comment by crodriguezy** [comment]
Hi @markocikos , I've added a commit to cleanUp the listeners as you suggested. However I used the opposite condition, because I think it only makes sense to clean them up if the already exists, right?

`if (focusManager) then cleanUp`

Please contact me via slack if I'm not fully understanding it.

Thank you!

**Comment by crodriguezy** [comment]
Please see https://github.com/liferay-frontend/liferay-portal/pull/2180 according to our conversation in slack.
Thanks!

**Pull request closed without merging**
