### PR TITLE
LPS-136017 SPA navigation is not prevented with custom exception selectors

### PR DESCRIPTION
**Pull request by markocikos**
Fixes: https://issues.liferay.com/browse/LPS-136017

**This PR is a bit risky. Even if reviews are green, please wait with forwarding until GA release.**

Steps to reproduce:
1. Deploy `frontend-editor-ckeditor-sample-web`
2. Place it on a page
3. Click on the link in text

Expected result: Nothing happens. CKeditor prevents normal navigation, because of `data-cke-saved-href` attribute.

What actually happens: We try SPA navigation. It fails, with error below in log.
```
LiferayApp.js:164 Uncaught TypeError: Cannot read property 'closest' of null
    at LiferayApp.isInPortletBlacklist (LiferayApp.js:164)
    at LiferayApp.onDocClickDelegate_ (LiferayApp.js:244)
    at HTMLDocument.eventHandler (delegate.es.js:58)
```

The root cause is that we don't set custom navigation exception selectors. We always use default selector 
```
"a:not([data-senna-off]):not([target=\"_blank\"])"
```
This is because [delegation for SPA](https://github.com/liferay/liferay-portal/blob/master/modules/apps/frontend-js/frontend-js-spa-web/src/main/resources/META-INF/resources/app/App.js#L1410-L1416) is defined in App.js constructor, resolving before we get the chance to [set exception selectors](https://github.com/liferay/liferay-portal/blob/master/modules/apps/frontend-js/frontend-js-spa-web/src/main/resources/META-INF/resources/app/LiferayApp.js#L61-L62). Later on, in [delegation callback](https://github.com/liferay/liferay-portal/blob/master/modules/apps/frontend-js/frontend-js-spa-web/src/main/resources/META-INF/resources/app/LiferayApp.js#L245), the selector is updated, and the `closest` breaks on `null`. This callback should not have been executed.  

In this PR, we are extending base class to expect navigation exception selectors, and pass them in before delegation declaration. After this, the selector becomes:
```html
"a:not([target=\"_blank\"]):not([data-senna-off]):not([data-resource-href]):not([data-cke-saved-href]):not([data-cke-saved-href])"
```
`data-resource-href` is used in `roles-admin-web`, so this PR will affect it. 

I would consider this only a temporary quick fix. I think the proper solution would be to merge `App.js` and `LiferayApp.js`, removing all the inheritance complications. The separation to generic API and Liferay-specific API only made sense when `App.js` was a part of standalone Senna. But that's a bigger and much riskier task, outside the scope of this PR.

### CODE REVIEW

**Comment by diegonvs** [comment]
> The separation to generic API and Liferay-specific API only made sense when App.js was a part of standalone Senna. But that's a bigger and much riskier task, outside the scope of this PR.

+1, Things may look more complicated that can be.

I would just make a question: 

When clicking twice the link, a panel opens as you can see in the following GIF:

https://user-images.githubusercontent.com/7663513/126518844-dd2735ba-6e89-4037-bb7d-8898ad2c4bea.mov

Is this panel still actionable in edit mode?

**Comment by markocikos** [comment]
> Is this panel still actionable in edit mode?

@diegonvs I'm working on this, and few other link toolbar issues, in a [separate task](https://issues.liferay.com/browse/LPS-135711). I wanted to split off this SPA bug, as it is riskier to fix than balloon editor stuff, affecting other modules.

Spoiler for future PR: I have removed that toolbar, replacing it with the one from 'linktoolbar' plugin.

**Comment by nhpatt** [comment]
Release ready, let's go forward :D

**Comment by nhpatt** [comment]
ci:forward

**Pull request closed without merging**
