### PR TITLE
LPS 129469 Fixing viewRestorePortlet macro to assert restored theme

### PR DESCRIPTION
**Pull request by calvinctvo**
**Jira Ticket:**
https://issues.liferay.com/browse/LPS-129469

**Test Plan:**

1. Add assertion to check for restored theme 
2. Remove Smoke.viewWelcomeContentPage() macro from ClassicTheme.testcase due to failure upstream fix by Echo team https://github.com/liferay-echo/liferay-portal/pull/4050/commits/ea9458b33f893a80ea93c5ee65770d264bb35e8f
3. Ticket for the failure is here: https://issues.liferay.com/browse/LPS-129064

This PR will fix the failure upstream for ClassicTheme#ConfigureLookAndFeelSettingsSinglePage https://issues.liferay.com/browse/LRQA-65990
cc/ @jbalsas Do you think we should transfer this test to echo team? Since the viewWelcomeContentPage macro is under Echo team.

### CODE REVIEW

**Comment by john-co** [comment]
> cc/ @jbalsas Do you think we should transfer this test to echo team? Since the viewWelcomeContentPage macro is under Echo team.

Not only that but my hunch is most of the test steps in ClassicTheme#ConfigureLookAndFeelSettingsSinglePage toggles display options that may not necessarily be owned by FI team.

**Review by john-co — APPROVED** [review]
looks good to me.

**Comment by calvinctvo** [comment]
ci:forward

**Comment by jbalsas** [comment]
Hey @john-co, @calvinctvo, yeah, I'd say 80% of this is not ours. 

Based on this, someone changed the Hello World portlet (not us, not ours) and that broke something the testcase for `ClassicTheme` in a step that's doing `viewRestorePortlet`. This should be a clear clue of heavy coupling and unclear test boundaries.

We're not testing classic theme so much as we are testing Hello World and other page building features.

**Comment by john-co** [comment]
Thanks @jbalsas , I think we need to better define those boundaries. What would be the 20% that FI team owns? Is it the Look and Feel configuration options and viewing that those changes take effect?

The issue was not necessarily due to the Hello World portlet changing but someone mistakenly changing the test steps on our testcase.

**Comment by jbalsas** [comment]
> Thanks @jbalsas , I think we need to better define those boundaries. What would be the 20% that FI team owns? Is it the Look and Feel configuration options and viewing that those changes take effect?

No, Look and Feel is likely echo as well, since that's stored as layout settings. The problem is that to assert that layout settings for themes work, we use the resulting HTML to verify it, thus coupling the theme and the settings test in one. Similar to what we saw with Stylebooks. The fact that themes provide settings that are accessible is what we own. How those settings are used to expose other UIs in other apps, maybe not. I haven't looked at this in detail, so that 80-20 was just a hunch, not a factual number.

> The issue was not necessarily due to the Hello World portlet changing but someone mistakenly changing the test steps on our testcase.

I think that's same issue... in the end, someone alien to the team needed to change the test steps on our testcase. Had they changed it properly, the fact would've remained that they needed to do so but we wouldn't have noticed.

**Pull request closed without merging**
