### PR TITLE
LPS-125130 Remove dependencies on metal-drag-drop from layout and site-navigation

### PR DESCRIPTION
**Pull request by kresimir-coko**
🎩  G'day sirs and madams of the frontal infostructurious organisation. I present upon you a simple PR that obliterates pesky dependencies on `metal-drag-drop` from `layout-admin-web` and `site-navigation-admin-web` modulators. The dependencies were not being used in these modulators, so I have done them a favor and deleted them from existence in this wonderful universe. Thank you for listening to my TED talk, I bid you farewell gentlesirs and gentleladies.

### CODE REVIEW

**Review by wincent — APPROVED** [review]
lovely

**Comment by wincent** [comment]
ci:forward

**Comment by wincent** [comment]
> CI is automatically triggering the following test suites:

So I wonder if it is literally going to try running the tests a second time... 🤔

**Comment by wincent** [comment]
> So I wonder if it is literally going to try running the tests a second time... 🤔

---

> CI, meet idempotency.
>
> Idempotency, this is CI

**Comment by kresimir-coko** [comment]
@wincent The fanfiction writes itself

**Pull request closed without merging**
