### PR TITLE
LPS-145971 Update liferay-ckeditor to 4.17.1-liferay.1

### PR DESCRIPTION
**Pull request by diegonvs**
**Full Changelog**: https://github.com/liferay/liferay-ckeditor/compare/v4.16.2-liferay.5...v4.17.1-liferay.1

This version bump was necessary to upgrade ckeditor base version on liferay-ckeditor

### CODE REVIEW

**Comment by diegonvs** [comment]
ci:test:sf

**Comment by diegonvs** [comment]
ci:test:relevant

**Review by markocikos — APPROVED** [review]
LGTM!

**Comment by markocikos** [comment]
ci:forward

**Pull request closed without merging**
