### PR TITLE
LPS-186911 Create the customEmptyState prop on FDS

### PR DESCRIPTION
**Pull request by rebsilva**
Related Issue: https://issues.liferay.com/browse/LPS-186911

Hi reviewer!

This PR has the objective to make possible the use of custom empty states on FDS; the necessity came from [this bug](https://issues.liferay.com/browse/LPS-186168) opened by the design team. You can also see the mockups with the expected messages [here](https://www.figma.com/file/4K3ROCpdTnKAFNTpwZNZcD/80-LPS-objects-empty-states-investigation?type=design&node-id=502-95200&t=L4AMjXenpk1UzJVl-0).

:warning: The only commit that makes changes inside FDS is [ec8abe0](https://github.com/liferay-frontend/liferay-portal/pull/3457/commits/ec8abe0d32037952b3a97ace1b53ace6a04a7fa7); all the other commits were already reviewed by the BPM team [here](https://github.com/liferay-objects/liferay-portal/pull/2226).

Please feel free to ask anything or make suggestions, thanks a lot!

**What this PR does?**

- Creates a new prop called `customEmptyState` inside the FDS; if it exists, it will be rendered instead of the default
- Creates a new React component called `CustomEmptyState` that will be used as the base for all the custom empty states
- Applies the custom empty state to the table on the Predefined Values

Screenshot from 2023-06-13 15-29-37

cc: @markocikos @dsanz

### CODE REVIEW

**Comment by rebsilva** [comment]
ci:test:relevant

**Comment by markocikos** [comment]
Hey @rebsilva we are working on this API, see https://github.com/liferay-frontend/liferay-portal/pull/3399. But, we did not consider allowing component through API. Sounds like a good idea to me! @dsanz @edalgrin What do you think? Maybe as `emptyState.component`? 

Sidenote: we have more and more React API with component or element props. We might want to name them consistently as `*.component` / `*.element`.

**Comment by rebsilva** [comment]
That's great @markocikos! We thought about the component because it gives more flexibility to create empty states that are different from the default (some don't have pictures or buttons for example).

I will put my task on hold while you decide this with your team, but please let me know if I can help in any way, thanks a lot! cc: @naraandrade

**Comment by markocikos** [comment]
@dsanz Why not all of the above? FDS, and in general higher level frontend components, could offer multiple levels of customization:
1. Default (no configuration). Opinionated or Clay defaults. 
2. API that matches Clay (`emptyState.description`, `emptyState.title` etc.)
3. Content of the component, if the Clay components supports `children` (`emptyState.contentComponent`?)
4. The component itself, that would replace the Clay component (`emptyState.component`?)

(3) and (4) only make sense in a React context, but I think would still provide a lot of value.

Typically only a part of (2) API can be supported by tags, props with primitives and serializable type. Callbacks and functions, not as much. But still, tag support does provide value.

**Comment by dsanz** [comment]
So @markocikos you're suggesting giving more choices from more to less opinionated

> 1. Default (no configuration). Opinionated or Clay defaults.

I consider this the starting point. No configurability, sensible defaults. 

> 2. API that matches Clay (emptyState.description, emptyState.title etc.)

We'd need to import the [ClayEmptyState IProps](https://github.com/liferay/clay/blob/d4285023e89107d7c17487c4f50e56e2d630a883/packages/clay-empty-state/src/index.tsx#L9) to match the API however they are not being exported. Coincidentally related discussion about this is taken place now: https://liferay.slack.com/archives/C049XG98GQL/p1686894316281519

> 3. Content of the component, if the Clay components supports children (emptyState.contentComponent?)

This one sounds to me like an extension of 2 where we just pass the children and/or individual props, all of those based on the IProps above. Hopefully we could solve most of the use cases with a combination of 2 and 3

> 4. The component itself, that would replace the Clay component (emptyState.component?)

Provided we give intermediate options (2-3) this one now makes sense to be more open for cases where existing ootb is not enough (very much what a client extension does), still for DXP apps this should be signed off by design as an exception if design system does not cover it.

If I understood your idea, what we have in this PR is just 4 so we can move forward and then add 2+3 later on. Still, @rebsilva, I'm not 100% sure about whether your usecase could be solved in a simpler way if we give the option to configure text + description + a child button as part of the standard empty state API from the FDS, what fo you think?

**Comment by edalgrin** [comment]
Nothing more to add from my part, my concerns about having a custom empty state component different from the clay one, have already been covered by your comments @dsanz @markocikos!

**Comment by rebsilva** [comment]
Hi @markocikos @dsanz and @edalgrin! First of all I want to thank you for taking some time to discuss this and think of solutions about it :tada:

I think it will be better if I explain the motives behind this PR first. The Design Team of BPM realised that all of our empty states are not accurate, as they say:

>  _"We are current using the Empty search results, where the filters or search results return zero results. But the user is not actually doing any type of search."_ 

Screenshot from 2023-06-19 13-21-50

So they opened [this bug](https://liferay.atlassian.net/browse/LPS-186168) for the devs to change the empty states starting from Objects. I elaborated this solution based on the scenario we have on Objects now, using `<FrontendDataSet>` as React Component directly; we still have some FDS calls on jsp files, but I was thinking to just call the custom empty state as a React Component there.

Since I wasn't sure what the best solution was, I thought of sending this inital ideia to you to hear your opinions on this, and I agree on all the points you have stated:

- It is indeed good to have consistency, not letting us send anything on the custom empty state
- I was trying to not polute the core FDS implementation too much, that's why I thought about sending a custom empty state as a component. But if you implement all the things we need as you can see bellow (a title, a description, a button, sometimes it has an image) I don't see a problem to only send the props to FDS directly

Screenshot from 2023-06-19 13-30-07

- To be honest I didn't thought of using regular ClayEmptyState as a wrapper and it makes a lot of sense! Totally agree with you on this
- `lfr-objects__*` are not special at all! It just a padronization we have to call classes on Objects side, and I had to use some CSS since I wasn't using the regular ClayEmptyState as a wrapper. If the clay classes already do their magic to make everything look good thats awesome, but maybe it would be good to have a way to add custom classes to the empty state (but is not necessary for the problem on hand!)

So in the end, I need a solution that works on both uses: using <FrontendDataSet> directly as a React component or being called in a jsp file. It doesn't need anything extra, only the necessary to achieve the looks on [these mockups](https://www.figma.com/file/4K3ROCpdTnKAFNTpwZNZcD/80-LPS-objects-empty-states-investigation?type=design&node-id=502-95200&t=yumEdTygGBN9pVQQ-0) as I've said before. So what is the most simple for you to do works for me!

Thanks again for all the patience and work on this, I'm here if you need anything :cherry_blossom:

**Comment by matuzalemsteles** [comment]
I don't think I have anything to add here either, I think the main concerns were discussed mainly around allowing a custom empty state that would allow accepting any JSX element or component, particularly I think we could avoid that until use cases come along where the existing APIs and the Empty State Lexicon standard are not enough because when that time comes we can engage the Lexicon to discuss whether it is something acceptable within the DXP or something to adopt globally as an improvement. Apparently the work on #3399 seems to solve the BPM issues so there seems to be no need for a custom component.

**Comment by edalgrin** [comment]
> I don't think I have anything to add here either, I think the main concerns were discussed mainly around allowing a custom empty state that would allow accepting any JSX element or component, particularly I think we could avoid that until use cases come along where the existing APIs and the Empty State Lexicon standard are not enough because when that time comes we can engage the Lexicon to discuss whether it is something acceptable within the DXP or something to adopt globally as an improvement. Apparently the work on #3399 seems to solve the BPM issues so there seems to be no need for a custom component.

The current component doesn't consider the image removal at the moment, but it might require a change on the Clay side

**Comment by rebsilva** [comment]
Hi @markocikos! 

Yes, this is enough for the stories we are working in, and for the Object empty states we will be able to fix a lot of them! We will be waiting for the `<frontend-data-set>` support in the future, but we really appreciate all your effort on this! 

Your work helped us a lot and the team is very thankful, please let us know if we can help on anything :cherry_blossom: 

I will be closing this PR since the solution is already done, thanks again!

**Pull request closed without merging**
