### PR TITLE
LPS-114068 Use new Layout Components in Components in dynamic-data-mapping

### PR DESCRIPTION
**Pull request by matuzalemsteles**
from #55

### CODE REVIEW

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by matuzalemsteles** [comment]
ci:test:sf

**Comment by brunobasto** [comment]
@matuzalemsteles Failures may be related. A bunch of Forms tests have failed.

**Comment by matuzalemsteles** [comment]
> @matuzalemsteles Failures may be related. A bunch of Forms tests have failed.

🤷‍♂️ I'll check that out tomorrow and do some manual testing.

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by matuzalemsteles** [comment]
ci:test:sf

**Comment by matuzalemsteles** [comment]
ci:test:sf

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
ci:test:sf

**Comment by jbalsas** [comment]
I think there are rebase errors, @matuzalemsteles, can you try this again? 😭 🙏

**Comment by matuzalemsteles** [comment]
> I think there are rebase errors, @matuzalemsteles, can you try this again? 😭 🙏

😭 I will do it now

**Comment by matuzalemsteles** [comment]
ci:test:sf

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by matuzalemsteles** [comment]
>      [java] java.lang.Exception: Commit message is pointing to non-existing JIRA issue: null

Can't we have more "REVERT" in the commit message before the LPS number? I had found this commit https://github.com/liferay/liferay-portal/commit/4011585759b79d3faf706665d5d868ae12fc5ba5 should that solve?

**Comment by matuzalemsteles** [comment]
ci:stop

**Comment by matuzalemsteles** [comment]
ci:test:sf

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by matuzalemsteles** [comment]
All green 🙏

Sending forward! cc @jbalsas

**Comment by matuzalemsteles** [comment]
ci:forward

**Comment by jbalsas** [comment]
godspeed

**Pull request closed without merging**
