### PR TITLE
Giulio commerce 6907 - made the tooltip work again

### PR DESCRIPTION
**Pull request by andrea-ale-sbarra**
Schermata 2021-08-12 alle 09 33 29

With this PR I removed the sku field that was causing tons of useEffect call and made the component crash. I believe the issue was on the autocomplete field

### CODE REVIEW

**Comment by andrea-ale-sbarra** [comment]
ci:test:sf

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
ci:test:sf

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
@andrea-ale-sbarra can you rebase this? We shouldn't have the `frontend-css-web` module any longer

**Comment by andrea-ale-sbarra** [comment]
ci:test:sf

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
ci:test:sf

**Pull request closed without merging**
