### PR TITLE
[WIP][7.4-Only][COMPLETE] LPS-127085 Migrate frontend-css-web

### PR DESCRIPTION
**Pull request by edalgrin**
The scope of this PR is to remove `frontend-css-web` following the migration strategy established in https://issues.liferay.com/browse/LPS-132258 

TL;DR:
1) Remove the unused styles
2) Move the styles to modules where possible
3) Move the styles to frontend-theme-styled where is not possible

Changes: https://docs.google.com/spreadsheets/d/1gWdQvLJe8KApcY70lxQb5fuvg6XKdwkfMEBLVPkigfU/edit#gid=0

---

This PR contains:
- https://github.com/liferay-frontend/liferay-portal/pull/1154
  - https://github.com/liferay-frontend/liferay-portal/pull/1129
  - https://github.com/liferay-frontend/liferay-portal/pull/1147
  - https://github.com/liferay-frontend/liferay-portal/pull/1137
  - https://github.com/liferay-frontend/liferay-portal/pull/1139
  - https://github.com/liferay-frontend/liferay-portal/pull/1143
- https://github.com/liferay-frontend/liferay-portal/pull/1155
- https://github.com/liferay-frontend/liferay-portal/pull/1160

---

**How to test this PR?**

Several modules has been slightly changed to relocate the styles from `frontend-css-web` so the easiest way to test it is to launch an `ant all`

To test the modules manually it'll be necessary to deploy:
- modules/apps/asset/asset-taglib/
- modules/apps/asset/asset-tags-navigation-web/
- modules/apps/captcha/captcha-taglib/
- modules/apps/comment/comment-web/
- modules/apps/commerce/commerce-product-content-web/
- modules/apps/document-library/document-library-web/
- modules/apps/dynamic-data-lists/dynamic-data-lists-web/
- modules/apps/dynamic-data-mapping/dynamic-data-mapping-form-web/
- modules/apps/dynamic-data-mapping/dynamic-data-mapping-web/
- modules/apps/flags/flags-taglib/
- modules/apps/frontend-css/frontend-css-web/
- modules/apps/frontend-editor/frontend-editor-ckeditor-web/
- modules/apps/frontend-js/frontend-js-aui-web/
- modules/apps/frontend-js/frontend-js-components-web/
- modules/apps/frontend-taglib/frontend-taglib/
- modules/apps/frontend-theme/frontend-theme-styled/
  - modules/apps/frontend-theme/frontend-theme-admin/
  - modules/apps/frontend-theme/frontend-theme-classic/
- modules/apps/item-selector/item-selector-taglib/
- modules/apps/knowledge-base/knowledge-base-web/
- modules/apps/mobile-device-rules/mobile-device-rules-web/
- modules/apps/polls/polls-web/
- modules/apps/portal-settings/portal-settings-authentication-cas-web/
- modules/apps/product-navigation/product-navigation-control-menu-web/
- modules/apps/site-navigation/site-navigation-directory-web/
- modules/apps/social/social-bookmarks-taglib/
- modules/apps/staging/staging-taglib/
- modules/apps/wiki/wiki-web/
- modules/dxp/apps/portal-search-tuning/portal-search-tuning-rankings-web/
- portal-kernel/
- portal-web/

The result is positive when no difference can be noticed in the UI and there's a small improvement in the performance.

<table>
    <thead>
      <tr>
        <th>Before</th>
        <th>After</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td></td>
        <td></td>
      </tr>
    </tbody>
</table>

### CODE REVIEW

**Comment by edalgrin** [comment]
ci:test:sf

**Comment by edalgrin** [comment]
ci:test:sf

**Comment by edalgrin** [comment]
ci:test:relevant

**Comment by marcoscv-work** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcoscv-work** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcoscv-work** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by edalgrin** [comment]
ci:test:relevant

**Comment by edalgrin** [comment]
ci:reevaluate:1197401_8516

**Comment by nkkwon** [comment]
Just started reviewing!

**Comment by nkkwon** [comment]
Analysis Details

NavigationMenusWithStaging#PublishEditedPrimaryNavigationMenu/ContentPagesWithMapping#MapManualURLToImageFragment - Failing with known issue in CI [LRCI-2329](https://issues.liferay.com/browse/LRCI-2329)

[LocalFile.LocalizationWithWebContentUI#AddLocalizedWebContentViaSourceEditor
](https://testray.liferay.com/reports/production/logs/2021-06/test-1-19/test-portal-acceptance-pullrequest(master)/8516/functional-tomcat90-mysql57-jdk8/6/20/LocalFile.LocalizationWithWebContentUI_AddLocalizedWebContentViaSourceEditor/index.html.gz) 
```     
[exec] com.liferay.poshi.runner.PoshiRunner > test[LocalFile.LocalizationWithWebContentUI#AddLocalizedWebContentViaSourceEditor] STANDARD_ERROR
     [exec]     org.openqa.selenium.WebDriverException: unknown error: Element <iframe src="" frameborder="0" class="cke_wysiwyg_frame cke_reset" style="width: 100%; height: 100%;" aria-describedby="cke_22" tabindex="0" allowtransparency="true" cd_frame_id_="77e7f1f9e52ccee5386921c0bc892ee3"></iframe> is not clickable at point (1086, 504). Other element would receive the click: <a aria-controls="displayPageContent" aria-expanded="false" class="collapse-icon collapsed sheet-subtitle" data-toggle="liferay-collapse" href="#displayPageContent" role="button">...</a>
     [exec]       (Session info: chrome=86.0.4240.111)
     [exec]       (Driver info: chromedriver=2.37.544315 (730aa6a5fdba159ac9f4c1e8cbc59bf1b5ce12b7),platform=Linux 4.14.138-rancher x86_64) (WARNING: The server did not provide any stacktrace information)
     [exec]     Command duration or timeout: 0 milliseconds
     [exec]     Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
     [exec]     System info: host: 'cloud-10-0-10-20.lax.liferay.com', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.14.138-rancher', java.version: '1.8.0_121'
     [exec]     Driver info: org.openqa.selenium.chrome.ChromeDriver
     [exec]     Capabilities {acceptInsecureCerts: false, acceptSslCerts: false, applicationCacheEnabled: false, browserConnectionEnabled: false, browserName: chrome, chrome: {chromedriverVersion: 2.37.544315 (730aa6a5fdba15..., userDataDir: /tmp/.org.chromium.Chromium...}, cssSelectorsEnabled: true, databaseEnabled: false, handlesAlerts: true, hasTouchScreen: false, javascriptEnabled: true, locationContextEnabled: true, mobileEmulationEnabled: false, nativeEvents: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, rotatable: false, setWindowRect: true, takesHeapSnapshot: true, takesScreenshot: true, unexpectedAlertBehaviour: ignore, unhandledPromptBehavior: ignore, version: 86.0.4240.111, webStorageEnabled: true}
```
This is failing in the CKEditor not being able to be clickable here 
image
The CK editor on the right side seems to be below other assets.

[LocalFile.NavigationMenuWidgetUseCase#ShowMoreThanTwoSublevelsWhenSelectPublicPagesHierarchyAndBarMinimallyStyled
](https://testray.liferay.com/reports/production/logs/2021-06/test-1-19/test-portal-acceptance-pullrequest(master)/8516/functional-tomcat90-mysql57-jdk8/7/2/LocalFile.NavigationMenuWidgetUseCase_ShowMoreThanTwoSublevelsWhenSelectPublicPagesHierarchyAndBarMinimallyStyled/index.html.gz) - The header path is linked to the page name Home instead of the child page
```
   [exec] com.liferay.poshi.runner.PoshiRunner > test[LocalFile.NavigationMenuWidgetUseCase#ShowMoreThanTwoSublevelsWhenSelectPublicPagesHierarchyAndBarMinimallyStyled] STANDARD_ERROR
     [exec]     java.lang.Exception: Expected text "Child Page" does not match actual text (case insensitive) "Home" at "//*[@data-qa-id='headerTitle']"
     [exec]     	at com.liferay.poshi.runner.selenium.BaseWebDriverImpl$20.assertTrue(BaseWebDriverImpl.java:4266)
     [exec]     	at com.liferay.poshi.runner.selenium.BaseWebDriverImpl$Condition.waitFor(BaseWebDriverImpl.java:4678)
     [exec]     	at com.liferay.poshi.runner.selenium.BaseWebDriverImpl$Condition.waitFor(BaseWebDriverImpl.java:4657)
     [exec]     	at com.liferay.poshi.runner.selenium.BaseWebDriverImpl.waitForTextCaseInsensitive(BaseWebDriverImpl.java:3560)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec]     	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec]     	at java.lang.reflect.Method.invoke(Method.java:498)
     [exec]     	at com.liferay.poshi.runner.PoshiRunnerExecutor$1.call(PoshiRunnerExecutor.java:1192)
     [exec]     	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
     [exec]     	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
     [exec]     	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
     [exec]     	at java.lang.Thread.run(Thread.java:745)
 ```
image

**Comment by edalgrin** [comment]
Thank you @nkkwon, you are a lifesaver! 😆 

I've update the PR commits with the fixes, hopefully it will be the last review.

image1
image2

**Comment by edalgrin** [comment]
ci:test:relevant

**Comment by edalgrin** [comment]
ci:test:relevant

**Comment by edalgrin** [comment]
Sorry @nkkwon , is this stuck?

**Comment by edalgrin** [comment]
I guess something went wrong, re-testing here https://github.com/liferay-frontend/liferay-portal/pull/1228

**Pull request closed without merging**
