### PR TITLE
LPS-194887 - Allow users to change FDS Field sortable property

### PR DESCRIPTION
**Pull request by juanjofgliferay**
[LPS-194887](https://liferay.atlassian.net/browse/LPS-194887)

## Problem
Cannot set sortable property to false from the Data Set manager UI
[Screencast from 2023-08-29 15-15-30.webm](https://github.com/liferay-frontend/liferay-portal/assets/132653342/8e4427bb-db3b-4094-98ca-37e453aa301b)

## Solution
Change sortable property to not required
[Screencast from 2023-08-30 08-22-38.webm](https://github.com/liferay-frontend/liferay-portal/assets/132653342/71ca6a49-cbd7-4b42-a703-0fe46b91b48a)

### CODE REVIEW

**Review by bryceosterhaus — APPROVED** [review]
LGTM

**Review by markocikos — APPROVED** [review]
@juanjofgliferay LGTM!

**Comment by juanjofgliferay** [comment]
ci:test:relevant

**Comment by markocikos** [comment]
ci:forward

**Pull request closed without merging**
