### PR TITLE
LPS-159442 Automation Test Creation | LPS-155870 Inform developers trying to consume batch endpoints not implemented

### PR DESCRIPTION
**Pull request by magjed4289**
https://issues.liferay.com/browse/LPS-159442

### CODE REVIEW

**Comment by magjed4289** [comment]
ci:test:headless-frontend-functional:nocompile

**Review by Hijky — APPROVED** [review]

**Review by yanan — COMMENTED** [review]
Conflicts in BlogPostingAPI.macro file in "Refactor of teardown" commit when rebasing to master.

**Comment by magjed4289** [comment]
Just started reviewing :)

**Comment by magjed4289** [comment]
Just started reviewing :)

**Comment by magjed4289** [comment]
Just started reviewing :)

**Comment by magjed4289** [comment]
ci:test:headless-frontend-functional:nocompile

**Comment by magjed4289** [comment]
ci:forward

**Pull request closed without merging**
