### PR TITLE
LPS-198114 [Removes SOY] Removes unused chart modules

### PR DESCRIPTION
**Pull request by ealonso**
Motivation
----
Removes SOY from portal, that means removes all dependencies. Since sample module is ignore and taglib modules doesn't have usages in portal remove it in order to allow us remove SOY.

Please let me know if you have any question

### CODE REVIEW

**Comment by ealonso** [comment]
ci:test:sf

**Review by markocikos — COMMENTED** [review]
@ealonso Awesome! :sparkles:  We were just considering how to handle this taglib in https://liferay.atlassian.net/browse/LPS-135308. I am 100% for removing this, but we should take into account that this is a breaking change. Recently we introduced [reporting of breaking changes through extended commit message](https://liferay.slack.com/archives/CL69D8RUG/p1695116917497289). Can you add this?

**Comment by ealonso** [comment]
Hey @markocikos,

I've already update the commit description.

Please let me know if it is ok for you. IMHO, we should delete it asap.

**Review by markocikos — APPROVED** [review]
@ealonso LGTM! :sparkles:

**Comment by markocikos** [comment]
ci:test:relevant

**Comment by markocikos** [comment]
ci:test:sf

**Comment by ealonso** [comment]
@markocikos I'm going to talk with SF team about the source formatting errors, since those seem to be related with other things.

**Comment by ealonso** [comment]
see: https://github.com/brianchandotcom/liferay-portal/pull/141892

**Pull request closed without merging**
