### PR TITLE
LPS 137750 test

### PR DESCRIPTION
**Pull request by cleydyr**
Related Issue: https://issues.liferay.com/browse/LPS-137750

This is only a complementary commit to LPS-137750 adding a test. (See https://github.com/liferay-frontend/liferay-portal/pull/1381). Please review and forward.

### CODE REVIEW

**Comment by cleydyr** [comment]
Added this SF commit to the branch https://github.com/brianchandotcom/liferay-portal-ee/commit/df5f3c48c49971f55aff32c1a7501dcf6f51998a

**Comment by carloslancha** [comment]
ci:test:sf

**Comment by carloslancha** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
ci:forward

**Comment by diegonvs** [comment]
ci:forward

**Pull request closed without merging**
