### PR TITLE
LPS-118623 Remote App - service

### PR DESCRIPTION
**Pull request by brunobasto**
This is a resend of https://github.com/liferay-frontend/liferay-portal/pull/200 applying [feedbacks](https://github.com/brianchandotcom/liferay-portal/pull/92278#issuecomment-669475551) requested by Brian.

Mainly this introduces:
1. Renaming `remote-web-app` to just `remote-app`
2. Send smaller chunk with just module boilerplate + service.xml + generated code

### CODE REVIEW

**Comment by brunobasto** [comment]
ci:test:sf

**Comment by brunobasto** [comment]
ci:test:sf

**Comment by brunobasto** [comment]
ci:test:sf

**Comment by brunobasto** [comment]
ci:test:relevant

**Comment by brunobasto** [comment]
ci:test:sf

**Comment by brunobasto** [comment]
ci:test:relevant

**Comment by wincent** [comment]
FWIW, seeing as this is split into two parts now (and this is only the first part of it, right?), I'm going to [continue building](https://github.com/wincent/liferay-portal/pull/361) off [the old iteration of this](https://github.com/liferay-frontend/liferay-portal/pull/217), and I'll wait until it's all in before adapting on top of the final version.

**Comment by brunobasto** [comment]
ci:test:relevant

**Comment by brunobasto** [comment]
ci:forward

**Pull request closed without merging**
