### PR TITLE
LPS-165414 EditorTag is not working on fragments

### PR DESCRIPTION
**Pull request by ealonso**
Motivation
----
In order to support comments taglibs on freemarker code, we should update the Editor taglibs.

[Link to the issue](https://issues.liferay.com/browse/LPS-165414)

Proposed Solution
----
Removes check for **portletId** and use an empty string to get the **EditorConfiguration**.

Steps to verify
----
 * Go to Control Panel > Configuration > System Settings > Template Engines: Freemaker Engine and delete Restricted Variables: "serviceLocator" and "staticUtil"
 * Go to default site
 * Go to Content > Web Content
 * Add a web content with the following settings

```java
Title: test content
Content: test content
Friendly URL: test_content
```

 * Go to Site Builder > Page Fragments
 * Add a Fragment Sets named "CUSTOMIZE"
 * Add a fragment named "test_frament"
 * Copy into the HTML field
```freemarker
[#assign 
  articleLocalService = serviceLocator.findService("com.liferay.journal.service.JournalArticleLocalService")
  entryLocalService = serviceLocator.findService("com.liferay.asset.kernel.service.AssetEntryLocalService")
  groupId = themeDisplay.getSiteGroupId()
  urlTitle = "test_content"
/]

[#assign article =articleLocalService.fetchLatestArticleByUrlTitle(groupId,urlTitle,0)!'' ]
[#if article?has_content ]
[#assign
  resourcePrimKey = article.getResourcePrimKey()?number
  entry=entryLocalService.fetchEntry("com.liferay.journal.model.JournalArticle",resourcePrimKey)
  userId = entry.getUserId()
/]

[@liferay_comment["discussion"] 
  className=entry.className 
	classPK=entry.classPK
	formName="fm" 
	ratingsEnabled=true
	userId=themeDisplay.userId
/]
[/#if] 
```
 * Go to Site Builder > Pages and add a content page
 * Add a "test_frament" to page and publish
→Note the comments section is displayed properly, including the input field
 * Access to the content page

### CODE REVIEW

**Review by markocikos — APPROVED** [review]
LGTM! Tested, works as expected :sparkles:

**Comment by markocikos** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:reevaluate:1297401_5017

**Comment by ealonso** [comment]
ci:reevaluate:1297401_5017

**Comment by ealonso** [comment]
ci:reevaluate:1297401_5017

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by markocikos** [comment]
ci:forward

**Pull request closed without merging**
