### PR TITLE
LPD-24044 GeoLocationField in expando-taglib isn't working (broken import)

### PR DESCRIPTION
**Pull request by boton**
# Issue: [BUG LPD-24044](https://liferay.atlassian.net/browse/LPD-24044) ([LPP-53621](https://liferay.atlassian.net/browse/LPP-53621))

Hi guys, I fixed the broken import over expando-taglib.

I think it's caused by 769a97ea98e2da79348a24f0b9ab8172566ab0cf / [LPS-206108](https://liferay.atlassian.net/browse/LPS-206108).

## Before PR
image

## After PR
image

### CODE REVIEW

**Review by markocikos — APPROVED** [review]
@boton LGTM! :sparkles:

**Comment by bryceosterhaus** [comment]
@boton can you just update it to be named exports instead of a default export. In the near future we may eliminate default exports to help build speeds (ESM doesn't like default).

**Comment by bryceosterhaus** [comment]
After that update, it looks good to me to forward

**Comment by boton** [comment]
@bryceosterhaus I tried but it isn't working I don't know why. 

image

Am I missing something on this export/import migrating from default export to named export 2fa26223f61ef3b5e6cc70ec6939ca874243a95d?

I appreciate any help you can provide. 

Ty!

> [!NOTE]
> When it is working I will merge both commits into one.

**Comment by boton** [comment]
@bryceosterhaus Sure I will check and update the ticket. 

We must backport this / workaround to fix the [consumer issue](https://liferay.atlassian.net/browse/LPP-53621). 

Do you have a plan to backport it to **release-2024.q1**?

**Comment by bryceosterhaus** [comment]
@boton I'm not sure what the backport process really is, but my guess is that it should be easy to do so

**Comment by boton** [comment]
@bryceosterhaus @dsanz ty!

**Pull request closed without merging**
