### PR TITLE
[don't forward] LPS-121875 Migrate management toolbar v2 usages in dynamic-data-mapping-web

### PR DESCRIPTION
**Pull request by markocikos**
@jonmak08 @julien @ambrinchaudhary 

See task details in https://issues.liferay.com/browse/LPS-121875

I'm opening this PR here, before forwarding to product team, because we are extending tag API. We are adding a callback on component mount. Also pinging @wincent for this part:
- Is there a more elegant solution? We cannot leave this in JSP, as there is no toolbar component instance. `PropsTransformer` is not a component, so we cannot have `useEffect` in it.
- Is there a better name than `onComponentMount`? I went with something similar to React's `componentDidMount`, but not quite the same, so it does not imply some kind of override. Is there a best practice how to refer to lifecycle moments in functional components? 

Test plan:
1. C&D > Dynamic Data Lists > Ellipsis icon > Manage Data Definitions
1. C&D > Dynamic Data Lists > Create New List > Data Definition > Select <-- **here you can see the new callback**
1. Design > Widget Templates
1. ??? Somewhere we can select a DDM template. I couldn't not find such a place. The code is identical to (2) so I have high confidence it'll work.

Search field focuses on mount:
after

### CODE REVIEW

**Review by julien — COMMENTED** [review]
I'll wait to see what @wincent has to say about the callback, but apart from that LGTM

**Comment by jbalsas** [comment]
> Is there a more elegant solution? We cannot leave this in JSP, as there is no toolbar component instance. PropsTransformer is not a component, so we cannot have useEffect in it.

An option would be to include autoFocus support by default as requested in [Add autoFocus to management toolbar](https://github.com/liferay/clay/issues/3895) by @4lejandrito which he proceeded to move to [Move autoFocus functionality to the management toolbar taglib](https://issues.liferay.com/browse/LPS-127020) per our request.

**Review by wincent — COMMENTED** [review]
> * Is there a more elegant solution? We cannot leave this in JSP, as there is no toolbar component instance. `PropsTransformer` is not a component, so we cannot have `useEffect` in it.

Makes sense. By design, the props tranformer is a generic function (not a component) for "wiring things up". So sticking an `onComponentMount` in there doesn't seem unreasonable. We're already doing things in the props transformers that resemble the kind of thing you'd do inside components (ie. defining click handlers), so this is just another step in the same direction.

> * Is there a better name than `onComponentMount`? I went with something similar to React's `componentDidMount`, but not quite the same, so it does not imply some kind of override.

I think the name is good. I like the way you avoid the React name to avoid potential confusion (and anyway, class-based components are super rare now, so it would be weird to use a function name from the class-based API when we're almost always going to be rendering functional components).

> Is there a best practice how to refer to lifecycle moments in functional components?

I don't think so because the entire concept of "lifecycle" is mostly replaced by `useEffect()` and other hooks.

> An option would be to include autoFocus support by default as requested in [Add autoFocus to management toolbar](https://github.com/liferay/clay/issues/3895) by @4lejandrito which he proceeded to move to [Move autoFocus functionality to the management toolbar taglib](https://issues.liferay.com/browse/LPS-127020) per our request.

My understanding is that there are three options:

- Add `autoFocus` to Clay.
- Add `autoFocus` to management toolbar in liferay-portal (as described [here](https://github.com/liferay/clay/issues/3895#issuecomment-767877741)).
- Add `onComponentMount` like in this PR.

I actually think any of those sounds fine, because there are all so localized to the management toolbar itself. Evidently there are advantages and disadvantages in each. For example, doing it in Clay would eliminate some repetition from this PR, at the cost of requiring releasing and integration a new Clay version. Doing it in the management toolbar would avoid the overhead of release and integration. I don't think we'd want to go running around adding `autoFocus` attributes to _all_ the lower-level focusable components, but for something "singleton" (usually exactly one on a page) like the management toolbar, for which we repeatedly see this use case coming up, it does seem reasonable to make this a feature. If you wanted a vote from me, I'd go with the second option, but I really think any of them is quite all right.

**Comment by markocikos** [comment]
I think we can safely rule out adding `autofocus` in Clay. This is because `<ClayManagementToolbar.Search>` component is [a thin wrapper around `children`](https://github.com/liferay/clay/blob/master/packages/clay-management-toolbar/src/Search.tsx#L31). Implementation containing the [input element](https://github.com/liferay/liferay-portal/blob/master/modules/apps/frontend-taglib/frontend-taglib-clay/src/main/resources/META-INF/resources/management_toolbar/SearchControls.js#L41-L48) is in DXP. We would need to significantly restructure both Clay and DXP for this, and I'm not sure we would be left with a better solution. Management toolbar is a high-level component with many DXP-specific parts, for example integration with search container. In my opinion, it is good that most of the implementation is in DXP.

The question now is, would it make sense to hardcode `autofocus` on the search input? [Lexicon](https://liferay.design/lexicon/core-components/toolbars/management-bar/) does not mention this behavior. I searched DXP and found only three focus invocations linked to management toolbar. With this in mind, it does not make sense to me to set is as default. This is a question for Lexicon; if it's a common product request, maybe we should consider it. @drakonux 

Next question, does it make sense to add it to tag API, or just have a general solution like `onComponentMount`? With three usages, I'd say this is borderline. However, all existing usages are in management toolbars in modals, where search > selection may be a frequent use case. There are more toolbars in modals, that do not implement focus, but could benefit from an easy addition. With all above in mind, it does make sense to me to extend tag API.

Lastly, how to extend API? There are few ways to do it:
1. Add `autoFocus` boolean attribute. I don't like this, as we are not focusing toolbar in general. This fits more to a lower level tag like `input`.
2. Add `searchInputAutoFocus` boolean attribute. This is the one that makes most sense to me.
3. Add `focusElement` string attribute, with selector of element to focus. For management toolbar I don't think this is necessary, as only search input makes sense to me as something we would want to focus.

So, to conclude, I think the best solution is to add `searchInputAutoFocus` tag attribute. The closely second best is to have `onComponentMount`. @jbalsas @wincent What do you think?

**Comment by 4lejandrito** [comment]
@markocikos, I don't think it changes anything from what you said but [this](https://github.com/liferay/liferay-portal/blob/8009773bf9f0008aee1f7953407574208c14bbd6/modules/apps/document-library/document-library-web/src/main/resources/META-INF/resources/document_library/search_info.jsp#L150-L160) is a use case outside of a modal.

**Comment by wincent** [comment]
> So, to conclude, I think the best solution is to add `searchInputAutoFocus` tag attribute.

Sounds about right to me. I don't have a good feel for tag attribute naming conventions, but browsing through boolean attributes in `portal-impl/src/META-INF/javadocs-all.xml` I get the sense that we like to start them with verbs, so `autoFocusSearcInput` might be a better order here.

**Comment by markocikos** [comment]
> tag attribute naming conventions

We already have `searchInputName` in management toolbar tag, along with `searchFormMethod` and `searchFormName`. `searchInputAutoFocus` is consistent with that naming.

**Comment by markocikos** [comment]
Closing this PR:
1. I'll send the tag extension under https://issues.liferay.com/browse/LPS-127020 
2. After it is merged, I'll open management toolbar migration on the product team fork

**Comment by wincent** [comment]
> We already have `searchInputName` in management toolbar tag, along with `searchFormMethod` and `searchFormName`. `searchInputAutoFocus` is consistent with that naming.

But `searchInputName`, `searchFormMethod`, and `searchFormName` aren't boolean attributes.

**Comment by drakonux** [comment]
> The question now is, would it make sense to hardcode autofocus on the search input? Lexicon does not mention this behavior. I searched DXP and found only three focus invocations linked to management toolbar. With this in mind, it does not make sense to me to set is as default. This is a question for Lexicon; if it's a common product request, maybe we should consider it. @drakonux

From our point of view clay components should not have autofocus enabled by default. 

In general this feature can confuse visually impaired people because the screen reader jumps the context leaving them out of where they are or what they can do. But, may be I'm outdated and  this is an old argument and nowadays this problem has been solved. 

So even if it's solved. We don't see the benefit to enabling it by default. It's a good feature but it should be enabled in a specific scenario where the need is clear and the context given to the user is enough to manage directly on load the focus to a field.

**Comment by julien** [comment]
> So, to conclude, I think the best solution is to add searchInputAutoFocus tag attribute. The closely second best is to have onComponentMount. @jbalsas @wincent What do you think?

Even if you didn't ask me directly, I think having `searchInputAutoFocus` is fine; but in some cases we will still need a callback when the component mounts, at least that's what I think when looking at [this]https://github.com/liferay/liferay-portal/blob/bf41ac8d3aa2dbf64656fa7c0635882079d28f09/modules/apps/roles/roles-admin-web/src/main/resources/META-INF/resources/edit_role_assignments.jsp#L127-L222)

**Pull request closed without merging**
