### PR TITLE
LPS-116970 Avoids resolving sourcemap annotations

### PR DESCRIPTION
**Pull request by jbalsas**
This PR attempts to blindly fix [Cannot add Web Content on Windows Environment if StripFilter is enabled](https://issues.liferay.com/browse/LPS-116970) since I haven't been able to even run the scenario with the infrastructure we have.

**Steps to Reproduce** (theoretical, I haven't been able to run Portal in this scenario)
- Compile portal on linux/mac machine
- Enable StripFilter in portal-ext.properties `com.liferay.portal.servlet.filters.strip.StripFilter=true`
- Start Portal on Windows machine
- Login to Portal
- Create Web Content
- Attempt to Edit Web Content Fields

**Current Result**
Java StackTrace exception probably causing errors in the client code delivery.

```
ERROR [http-nio-8080-exec-6][StripFilter:62] java.nio.file.InvalidPathException: Illegal char <:> at index 4: http://localhost:8080/group/guest/~/control_panel/manage
java.nio.file.InvalidPathException: Illegal char <:> at index 4: http://localhost:8080/group/guest/~/control_panel/manage
        at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
        at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
        at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
        at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
        at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
        at com.google.javascript.jscomp.SourceMapResolver.getRelativePath(SourceMapResolver.java:73)
        at com.google.javascript.jscomp.SourceMapResolver.extractSourceMap(SourceMapResolver.java:53)
        [...]
```

**Rationale of the fix**
Just by [blind inspection of Closure Compiler code](https://github.com/google/closure-compiler/blob/246ab429f96bff062941a4da8b8f2af01ef5eb0d/src/com/google/javascript/jscomp/JsAst.java#L165):

```java
if (result.sourceMapURL != null && compiler.getOptions().resolveSourceMapAnnotations) {
    boolean parseInline = compiler.getOptions().parseInlineSourceMaps;
    SourceFile sourceMapSourceFile =
        SourceMapResolver.extractSourceMap(sourceFile, result.sourceMapURL, parseInline);
    if (sourceMapSourceFile != null) {
        compiler.addInputSourceMap(sourceFile.getName(), new SourceMapInput(sourceMapSourceFile));
    }
}
```

So, assuming that setting `resolveSourceMapAnnotations` to false would simply skip this and save the day 🙏

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:test:bundle

**Comment by jbalsas** [comment]
ci:test:sf

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
> Now, will this break sourcemaps entirely? Or degrade them? Or no noticeable change (seeing as AFAIK they are a bit broken anyway)?

I expect this would degrade them further, since now the sourcemaps won't match the minified sources.

Chances are a new version of the closure compiler would address this as well. I tried updating to the latest version and everything seemed to work other than some broken APIs and additional errors to ignore (`JSC_UNCATCHABLE_CODE`). 

I think at this point in time, our best move is to do the bare minimum and then work to just get rid of this feature completely for `7.4`

**Comment by jbalsas** [comment]
> @wincent, do you want me to give the update a chance? I'll send a different PR to test if a newer version also presents this issue.

I gave up on this, since the new compiler catches more errors which we will need to ignore and there's no way to know in advance. The list we have now is just a compilation of the errors we saw appear on the console over time in the older version, so I'm not really eager to continue down that road for very little gain.

**Comment by wincent** [comment]
> I gave up on this, since the new compiler catches more errors which we will need to ignore and there's no way to know how many in advance. The list we have now is just a compilation of the errors we saw appear on the console over time in the older version, so I'm not really eager to continue down that road for very little gain.

wise-choice

**Comment by jbalsas** [comment]
Tests are green... and @zhangyan0701 commented offline that:

> I didn't see the issue on Win10 with the bundle from the PR following John's steps.

Also got approval from @wincent, so cheerio!

**Comment by jbalsas** [comment]
ci:forward

**Pull request closed without merging**
