### PR TITLE
LPS-154725 Add custom extensions modified date to the list details

### PR DESCRIPTION
**Pull request by carloslancha**

### CODE REVIEW

**Comment by carloslancha** [comment]
@izaera @dsanz @markocikos could you take a look? No idea what I'm missing here (not working). Thx!

**Comment by markocikos** [comment]
@carloslancha FDS part LGTM, you are correctly adding a new field. In what way is your solution is not working? I would expect all values in the new column to be empty, if data items returned by data request do not contain `modifiedDate`.

**Comment by carloslancha** [comment]
@markocikos yup, the modified date column appears but the field is empty, so I guess that data is not returned by the request but I don't know why

**Comment by markocikos** [comment]
I believe you need to find where the data is created. I'd look for `property = "fds.data.provider.key="`. In it, you need to extend `getItems` and `getItemsCount` methods.

**Comment by carloslancha** [comment]
> I believe you need to find where the data is created. I'd look for the right *FDSDataProvider.java, maybe search property = "fds.data.provider.key=". In it, you need to extend getItems and getItemsCount methods.

That's the DataProvider I'm editing here. It looks like what I was missing is to add the `getModifiedDate` method to the client extensions `CET` model.

It may be simple and straightforward to implement anything with the FDS for a backend developer but definitely is not for a frontend dev, I'm not gonna lie, I found what was missing by trial and error, but I had no idea what I was doing 😅 

I think we should have some "samples for dummies"...

**Comment by markocikos** [comment]
>I think we should have some "samples for dummies"

We do have [FDS sample module](https://github.com/liferay/liferay-portal/tree/master/modules/apps/frontend-data-set/frontend-data-set-sample-web), that includes a sample of a classic variant, along with [sample preparation of data](https://github.com/liferay/liferay-portal/blob/master/modules/apps/frontend-data-set/frontend-data-set-sample-web/src/main/java/com/liferay/frontend/data/set/sample/web/internal/provider/ClassicFDSDataProvider.java).

The complications you had were in large part specific to client extensions, and its way of organizing backend (`CET` model etc).

**Pull request closed without merging**
