### PR TITLE
LPS-195138

### PR DESCRIPTION
**Pull request by fortunatomaldonado**
https://liferay.atlassian.net/browse/LPS-195138

Hello,
I had to also revert fbbba08b1bd2d280d1e55242d50c13943ee267ec in order to revert the following three commits.
Let me know if there are any questions or comments about this.

Thank you!

### CODE REVIEW

**Comment by izaera** [comment]
In principle, everything looks good. However, let me build it and check it just in case...

**Comment by izaera** [comment]
Did you `ant all` this? :thinking: I'm getting Java compilation errors...

**Comment by izaera** [comment]
I get this:

```
     [echo] /home/ivan/Liferay/Portal/liferay-portal/modules/apps/frontend-js/frontend-js-loader-modules-extender/src/main/java/com/liferay/frontend/js/loader/modules/extender/internal/npm/JSResolveModulesNPMRegistryUpdatesListener.java:8: error: package com.liferay.frontend.js.loader.modules.extender.internal.servlet.util does not exist
     [echo] import com.liferay.frontend.js.loader.modules.extender.internal.servlet.util.JSLoaderModulesUtil;
     [echo]                                                                             ^
     [echo] /home/ivan/Liferay/Portal/liferay-portal/modules/apps/frontend-js/frontend-js-loader-modules-extender/src/main/java/com/liferay/frontend/js/loader/modules/extender/internal/npm/JSResolveModulesNPMRegistryUpdatesListener.java:22: error: cannot find symbol
     [echo] 		JSLoaderModulesUtil.resetJSLoaderProps();
     [echo] 		^
     [echo]   symbol:   variable JSLoaderModulesUtil
     [echo]   location: class com.liferay.frontend.js.loader.modules.extender.internal.npm.JSResolveModulesNPMRegistryUpdatesListener
 ```

**Review by izaera — CHANGES_REQUESTED** [review]
Requesting changes to avoid accidentally merging or forwarding this.

**Comment by fortunatomaldonado** [comment]
@izaera, sorry I somehow missed a commit. Resending. 
Thank you for taking a look!

**Pull request closed without merging**
