### PR TITLE
LPS-194253 - Properly export ClientExtension component

### PR DESCRIPTION
**Pull request by bryceosterhaus**
https://liferay.atlassian.net/browse/LPS-194253

Since this component wasn't ever properly exported, it resulted in issues where 
the returned value was undefined and couldn't render a client extension fds cell

### CODE REVIEW

**Review by markocikos — APPROVED** [review]
LGTM! :sparkles:

**Comment by bryceosterhaus** [comment]
ci:stop

**Comment by bryceosterhaus** [comment]
ci:test:sf

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by mateusralv** [comment]
I'm on it 🕵🏽

**Comment by mateusralv** [comment]
Hi @bryceosterhaus The same failures I found earlier https://github.com/liferay-frontend/liferay-portal/pull/3611#issuecomment-1691740578 are repeated in this round.

Two functional tests failed on the CI, but I ran them locally on the PR bundle and they passed, so it could be a flaky failure on the CI.

Related tests:
LocalFile.ExternalVideo#DisplayVideoFromURLInExternalVideo
LocalFile.GeneratePathStructureForEndpoints#CanLoadAPIApplicationURL

[Testray Comparison](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1693218706349&testrayRunIdA=2412731153&testrayRunIdB=2412854445)

**Comment by bryceosterhaus** [comment]
@mateusralv I am almost positive those are flakey tests if they passed for you locally, especially considering the changes I made were related to the build and so I would expect either build failures or a runtime JS error. If we don't see either of those, I am pretty confident my changes wouldn't cause those failures

**Comment by bryceosterhaus** [comment]
I'll run tests once more after a rebase just in case

**Comment by bryceosterhaus** [comment]
ci:test:sf

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by mateusralv** [comment]
I'm taking a look

**Comment by mateusralv** [comment]
Hi @bryceosterhaus Some tests keep failing on the CI, but this time when I ran them locally the tests passed.

Tests related:
com.liferay.data.engine.rest.resource.v2_0.factory.test.DataDefinitionResourceFactoryImplTest
com.liferay.dynamic.data.lists.exporter.test.DDLExporterTest
com.liferay.object.rest.internal.resource.v1_0.test.ObjectEntryRelatedObjectsResourceTest
SitetemplatesUsecase#SiteTemplatePageLinkInWebContentRedirectCorrectly
com.liferay.data.engine.rest.resource.v2_0.test.DataListViewResourceTest

So it seems safe to forward this to Brian.

[Testray Comparison](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1693327811460&testrayRunIdA=2413431560&testrayRunIdB=2414509073)

**Comment by mateusralv** [comment]
ci:forward

**Comment by bryceosterhaus** [comment]
ci:forward:force

**Pull request closed without merging**
