### PR TITLE
LPS-178155 - Update globs to allow for running format in individual modules

### PR DESCRIPTION
**Pull request by bryceosterhaus**
Updated both our ignores and simplified our glob so that format can be run on all frontend files and even when run from the individual module.

### CODE REVIEW

**Comment by izaera** [comment]
:flushed: I was convinced that it was a bug, and it was only configuration...

LGTM

**Comment by mateusralv** [comment]
I'm taking a look 🕵🏽

**Comment by mateusralv** [comment]
Hi @bryceosterhaus and @izaera the failures are unrelated and not unique. Seems safe to forward from QA perspective.

[Testray Comparison](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1678881191504&testrayRunIdA=2232488505&testrayRunIdB=2232705889)

**Comment by izaera** [comment]
Good then :+1: 
I'll manually forward it.

**Comment by bryceosterhaus** [comment]
@izaera
>   I was convinced that it was a bug, and it was only configuration...

So previously I think it accidentally worked, because we had the global config and so we just so happened to only grab DXP's globs when it was at `./modules`, but when we ran from an individual module it would pull in the default globs. So now this way we are using the same globs at both global and at the individual module.

I also realized our previous globs were missing files too, so this fixes that.

**Pull request closed without merging**
