### PR TITLE
LPP-46318 | LPS-162394

### PR DESCRIPTION
**Pull request by holatuwol**
## Steps to reproduce

1. Go to [Control Panel -> SAML Admin]
1. Add any Entity ID
1. Create Certificate
1. Add Common Name
1. Add Key Password
1. Save

## Solution notes

https://liferay.slack.com/archives/CNBG06JS3/p1649760991802989

Based on testing, the issue was introduced when we switched to the v4 loader.

* 7.0 - not reproducible
* 7.1 - reproducible if loader v4 is enabled in system settings
* 7.2 - reproducible
* 7.3 - reproducible
* 7.4 - reproducible

### CODE REVIEW

**Review by markocikos — APPROVED** [review]
LGTM! Nice solution!

**Comment by diegonvs** [comment]
ci:forward

**Comment by diegonvs** [comment]
Hey @holatuwol, CI is failing continuously with the same tests. Could you take a look? Thanks

**Comment by stian-sigvartsen** [comment]
Hey @holatuwol . I think the JavaScript is required in the modal in order for the file uploader component to work correctly. It is on the "Import certificate" tab within the modal. Did you test this already?

I haven't been able to reproduce the JS errors. Is it possible that it has been fixed upsteam?

**Comment by john-co** [comment]
Just started reviewing :)

**Comment by john-co** [comment]
> CI is failing continuously with the same tests. Could you take a look? Thanks

Agree, SAML tests look related.

[Testray Comparison](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=3&testrayRunIdB=1971415544&testrayRunIdA=1971110494&statusB=2)

**Comment by holatuwol** [comment]
Will resend after checking the failures.

**Comment by holatuwol** [comment]
> I haven't been able to reproduce the JS errors. Is it possible that it has been fixed upstream?

It's possible, but it's also not reproducible by everyone. I took over the ticket because it was reproducible on my machine but not on another developer's machine.

**Pull request closed without merging**
