### PR TITLE
LPS-168442 - Centralize js dependencies into a single module

### PR DESCRIPTION
**Pull request by bryceosterhaus**
testing CI with this. I still need to do a few more dependnecies and also add some rules for enforcing the use of the module

### CODE REVIEW

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by izaera** [comment]
Good job :clap:

**Comment by bryceosterhaus** [comment]
@mateusralv could you check these failures out? I can't seem to reproduce locally

**Comment by mateusralv** [comment]
Hi @bryceosterhaus, sure! I'm checking the latest results 🕵🏽

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by mateusralv** [comment]
Hi @bryceosterhaus I made a [comparison with the master](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1673442328298&testrayRunIdA=2154383316&testrayRunIdB=2156723858) and returned +1400 unique failures.

The  `modules-semantic-versioning-jdk8/0/0`  module returned the following failure:
```
 [exec] com.liferay.semantic.versioning.SemanticVersioningTest > testSemanticVersioning[/apps/object/object-api] FAILED
     [exec]     java.lang.AssertionError:   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec]     = ================================================== ========== ========== ========== ========== ==========
     [exec]     * com.liferay.object.service                         MINOR      36.2.0     36.2.0     36.3.0     VERSION INCREASE REQUIRED
     [exec]     	<   class      com.liferay.object.service.ObjectRelationshipLocalServiceUtil
     [exec]     		+   method     getAllObjectRelationships(long)
     [exec]     			+   access     static
     [exec]     			+   return     java.util.List
     [exec]     	<   class      com.liferay.object.service.ObjectRelationshipLocalServiceWrapper
     [exec]     		+   method     getAllObjectRelationships(long)
     [exec]     			+   return     java.util.List
     [exec]     	<   interface  com.liferay.object.service.ObjectRelationshipLocalService
     [exec]     		+   method     getAllObjectRelationships(long)
     [exec]     			+   access     abstract
     [exec]     			+   annotated  com.liferay.portal.kernel.transaction.Transactional
     [exec]     				+   property   propagation='SUPPORTS'
     [exec]     				+   property   readOnly=true
     [exec]     			+   return     java.util.List
     [exec]         at org.junit.Assert.fail(Assert.java:88)
```
---
### Failures in functional testing 

The functional tests failed because of the buttons on the home page are not working, I made a video to show the fault: 

https://user-images.githubusercontent.com/44584050/211841230-1f07656b-d954-458f-b9e1-4b8cb8b95f67.mp4

**Comment by bryceosterhaus** [comment]
Thanks @mateusralv! I realized later that the bundle I was manually testing didn't actually have my changes from this pr.. Not sure how I made that mistake. I will ping you once this PR is ready to test again.

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
ci:test:stable

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by mateusralv** [comment]
Thank you @bryceosterhaus! @nkkwon could you take a look at this PR?

**Comment by nkkwon** [comment]
[Comparison Failure](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1673546755743&testrayRunIdA=2157943358&testrayRunIdB=2159526217)

It looks like some buttons on Documents & Media Files pages don't do anything when clicked.

**Currently on master** 
Peek 2023-01-12 11-21

**After PR**
pr2944-1

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
alright, I fixed a few more things. Let's see what happens...

**Comment by mateusralv** [comment]
I am taking a look 🕵🏽

**Comment by mateusralv** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
ci:stop

**Comment by bryceosterhaus** [comment]
ci:stop

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
ci:stop

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
resent https://github.com/liferay-frontend/liferay-portal/pull/2973

**Pull request closed without merging**
