### PR TITLE
LPD-7837 - Update commerce modules to ESM

### PR DESCRIPTION
**Pull request by bryceosterhaus**
Modified commit history from https://github.com/liferay-frontend/liferay-portal/pull/4094

### CODE REVIEW

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
ci:test:commerce-functional

**Comment by bryceosterhaus** [comment]
ci:report:2558309587

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
ci:test:commerce-functional

**Comment by bryceosterhaus** [comment]
ci:test:sf

**Comment by bryceosterhaus** [comment]
ci:report:2558484949

**Comment by bryceosterhaus** [comment]
ci:report:2558484949

**Comment by bryceosterhaus** [comment]
ci:test:commerce-functional

**Comment by bryceosterhaus** [comment]
ci:report:2558825688

**Review by gianmarcobrunialti — COMMENTED** [review]
Retested everything, added annexes on top of the related per-module commits to integrate the recent developments and a couple of fixes.

Sent here: https://github.com/liferay-commerce/liferay-portal/pull/4844

**Comment by dsanz** [comment]
Continued in https://github.com/liferay-commerce/liferay-portal/pull/4844

**Pull request closed without merging**
