### PR TITLE
LPS-124391 [Content Performance] Add frontend test

### PR DESCRIPTION
**Pull request by dgarciasarai**
**Description**

- Add one more frontend test to test view more/view less button
- Test traffic values too (url and traffic value)

### CODE REVIEW

**Comment by dgarciasarai** [comment]
cc: @julien @wincent

**Review by julien — APPROVED** [review]
LGTM :+1:

**Comment by dgarciasarai** [comment]
ci:test:sf

**Comment by julien** [comment]
ci:forward

**Pull request closed without merging**
