### PR TITLE
Upgrade test to work with testing library version 12

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
This is the brian's queue https://github.com/brianchandotcom/liferay-portal/pull/111857

**Comment by bryceosterhaus** [comment]
🎉 great work @victorg1991, this will be very nice to have

**Pull request closed without merging**
