### PR TITLE
LPD-25332 - poshi - quarantine tests in DataSet that rely on "creator" field, but are using an outdated Picklist UI

### PR DESCRIPTION
**Pull request by kresimir-coko**

### CODE REVIEW

**Comment by kresimir-coko** [comment]
ci:test:sf

**Comment by kresimir-coko** [comment]
ci:test:sf

**Comment by kresimir-coko** [comment]
ci:test:frontend

**Review by markocikos — APPROVED** [review]
@kresimir-coko LGTM! :sparkles:

**Comment by kresimir-coko** [comment]
ci:report

**Comment by kresimir-coko** [comment]
ci:report

**Comment by kresimir-coko** [comment]
ci:report

**Comment by kresimir-coko** [comment]
ci:report:2568558158

**Comment by kresimir-coko** [comment]
ci:report:2568558158

**Comment by kresimir-coko** [comment]
ci:report:2568458196

**Comment by kresimir-coko** [comment]
ci:test:frontend-data-set

**Comment by kresimir-coko** [comment]
ci:report:2569076133

**Comment by kresimir-coko** [comment]
Test failures are again weird, nothing related to `creator`, there are a lot of tests failing with this:
```
com.jayway.jsonpath.PathNotFoundException: 
Expected to find an object with property ['items'] in path $ but found 'java.lang.String'. 
This is not a json object according to the JsonProvider: 'com.jayway.jsonpath.spi.json.JsonSmartJsonProvider'.
```

Unsure how to proceed

**Comment by markocikos** [comment]
ci:test:frontend-data-set

**Comment by kresimir-coko** [comment]
ci:forward

**Pull request closed without merging**
