### PR TITLE
LPS-159214 Fix misuse of aui:button taglib api resulting in incorrect styles being applied to buttons.

### PR DESCRIPTION
**Pull request by ethib137**
The first commit fixes issues where the button is incorrectly rendered as a secondary button when it is supposed to be a primary button. The second commit fixes issues where additional classes are unnecessarily added. 

Steps to reproduce are in the [ticket](https://issues.liferay.com/browse/LPS-159214).

### CODE REVIEW

**Comment by bryceosterhaus** [comment]
not sure who is the best person to look at this. Maybe @markocikos or @edalgrin ?

**Review by markocikos — APPROVED** [review]
LGTM! Nice job!

**Comment by markocikos** [comment]
ci:forward

**Comment by diegonvs** [comment]
ci:forward

**Comment by diegonvs** [comment]
ci:forward

**Comment by ethib137** [comment]
ci:forward

**Comment by ethib137** [comment]
ci:test:relevant

**Comment by diegonvs** [comment]
ci:forward

**Comment by diegonvs** [comment]
ci:forward

**Comment by diegonvs** [comment]
WTF

image

Hey @ethib137, could you send manually to Brian? Thanks :)

**Comment by ethib137** [comment]
Manually sent here: https://github.com/brianchandotcom/liferay-portal/pull/121111

**Pull request closed without merging**
