### PR TITLE
LPS-165904 | Add test fix for VirtualInstances#CanAddAndDeletePortalInstance

### PR DESCRIPTION
**Pull request by mateusralv**
Background: 
Adjust the PortalInstances.addCP macro after adding a footer in the modal of creating the virtual instance.

Tasks:

- [x] Create test fix
- [x] Confirm that repair works 
- [ ] Add commit to original PR: https://github.com/liferay-frontend/liferay-portal/pull/2892

### CODE REVIEW

**Comment by mateusralv** [comment]
ci:test:relevant

**Comment by mateusralv** [comment]
ci:test:relevant

**Review by markocikos — APPROVED** [review]
Reviewed and approved in original PR.

**Comment by mateusralv** [comment]
ci:test:relevant

**Comment by john-co** [comment]
Hi @mateusralv, what's the status of this? Looks like the test is still failing.

**Comment by mateusralv** [comment]
the test still failing, but when I run it locally the test passed 🤔

**Comment by mateusralv** [comment]
ci:test:relevant

**Comment by mateusralv** [comment]
ci:test:relevant

**Comment by mateusralv** [comment]
The test is passing locally in the Bundle of the PR, I made some changes to try to stabilize the CI 🤞🏽

**Comment by mateusralv** [comment]
The fix worked 🎉 Hi @markocikos you approve this PR before, so I'll forward it.

**Comment by mateusralv** [comment]
ci:forward

**Pull request closed without merging**
