### PR TITLE
LPS-185230 | Automation for DatasetsFields

### PR DESCRIPTION
**Pull request by abhnerramos**
**Description**
Add 4 automations for DatasetsFields testcase

**JIRA Tickets**
DatasetsFields#CanCancelAddingOnCancelButton ([LPS-185230](https://issues.liferay.com/browse/LPS-185230))
DatasetsFields#CanSearchFieldOnFieldsSearchBar ([LPS-185231](https://issues.liferay.com/browse/LPS-185231))
DatasetsFields#CanCancelAddingOnCloseButton ([LPS-185232](https://issues.liferay.com/browse/LPS-185232))
DatasetsFields#AssertComposedFieldsNotAvailableForSelection ([LPS-185233](https://issues.liferay.com/browse/LPS-185233))

### CODE REVIEW

**Comment by abhnerramos** [comment]
ci:test:frontend-data-set

**Comment by abhnerramos** [comment]
ci:test:sf

**Comment by abhnerramos** [comment]
ci:test:frontend-data-set

**Comment by abhnerramos** [comment]
ci:test:sf

**Comment by abhnerramos** [comment]
ci:test:frontend-data-set

**Comment by abhnerramos** [comment]
@CarlosBrichete, could you take a look, please? LGTM!

**Review by CarlosBrichete — APPROVED** [review]

**Comment by CarlosBrichete** [comment]
LGTM :)

**Comment by abhnerramos** [comment]
ci:forward

**Pull request closed without merging**
