### PR TITLE
LPD-43413 Target exact CKE version to prevent CI build issues

### PR DESCRIPTION
**Pull request by markocikos**
The theory behind this test is that that [^ in version of CKEditor](https://github.com/liferay/liferay-portal/blob/master/modules/apps/frontend-editor/frontend-editor-ckeditor-web/package.json#L8) might be causing CI issues, where either
1. Something went wrong with latest patch release of CKEditor - or -
1. There is a delay of dependencies resolution, so latest one is temporarily not available

Successful build of this PR would confirm (1) or (2). This one failing and https://github.com/liferay-frontend/liferay-portal/pull/4592 succeeding would confirm (1).

### CODE REVIEW

**Comment by markocikos** [comment]
ci:test:relevant

**Comment by dsanz** [comment]
If you confirm this theory, pls create the task and forward this one. Thanks for working on this Marko

**Comment by markocikos** [comment]
The results in https://github.com/liferay-frontend/liferay-portal/pull/4591#issuecomment-2514604645 are not conclusive, but I feel the change makes sense even if it is not the root cause of current CI issue. The scenarios in https://github.com/liferay-frontend/liferay-portal/pull/4591#issue-2714722559 could happen regardless. The downside is we won't be as dilegent in keepin up with patches of base editor. But it is an issue we already living with on CKE4, this is just a loss of an improvement.

**Comment by markocikos** [comment]
ci:forward

**Comment by markocikos** [comment]
ci:test:sf

**Comment by markocikos** [comment]
ci:stop

**Comment by markocikos** [comment]
ci:test:sf

**Comment by markocikos** [comment]
ci:forward

**Comment by markocikos** [comment]
ci:stop

**Comment by markocikos** [comment]
ci:test:sf

**Comment by markocikos** [comment]
ci:forward

**Comment by markocikos** [comment]
ci:test:stable

**Comment by markocikos** [comment]
ci:report:82838615

**Comment by markocikos** [comment]
ci:forward

**Pull request closed without merging**
