### PR TITLE
LPS-121938 Delete temporary clay:management-toolbar-v2 tag

### PR DESCRIPTION
**Pull request by julien**
Since all `<clay:management-toolbar-v2 />` tags have been migrated to
`<clay:management-toolbar />` as part of the [LPS-112468](https://issues.liferay.com/browse/LPS-112468)
epic, it's now time to remove the metal+soy based ManagementToolbar
component.

### CODE REVIEW

**Review by jbalsas — COMMENTED** [review]
Screen Shot 2021-03-17 at 09 28 33

awesome

@julien, did you run `baseline`? Maybe we haven't published since we added `-v2` and thus there's no change (that would be ideal), but just to be sure since we've seen baseline failures go unnoticed...

**Comment by julien** [comment]
@jbalsas ... ah I totally forgot about running `baseline` (even though when I first worked on the PR I did think about it), will do that now.

**Comment by jbalsas** [comment]
>      [exec] > file:/opt/dev/projects/github/liferay-portal/modules/apps/journal/journal-web/classes/META-INF/resources/view_more_menu_items.jsp(42,0) PWC6142: No tag "management-toolbar-v2" defined in tag library imported with prefix "clay"


Looks like we missed one 😭

**Comment by jbalsas** [comment]
Or maybe Brian's upstream hasn't merged yet 🤔

**Comment by julien** [comment]
@jbalsas now that I did run baseline, I can confirm that there are no changes in `frontend-taglib-clay`, thanks for the heads up.
That said, I'm seeing `journal-web` fails. It seems [https://github.com/brianchandotcom/liferay-portal/pull/99970](https://github.com/brianchandotcom/liferay-portal/pull/99970) still hasn't landed in "upstream".

**Review by ambrinchaudhary — APPROVED** [review]

**Review by jonmak08 — APPROVED** [review]

**Comment by jonmak08** [comment]
ci:reevaluate:1037401_9311

**Comment by jbalsas** [comment]
js_unit_test might be related... maybe we forgot to delete the old test?

**Comment by jonmak08** [comment]
Removed the JUnit tests and testing locally at https://github.com/jonmak08/liferay-portal/pull/2138 since I cannot push to this branch.

**Comment by jbalsas** [comment]
Hey @julien, could you either push @jonmak08 changes on top of this or get his branch to see if we can push this through?

**Comment by julien** [comment]
Yes, that's actually what I was going to do seeing that his PR seems "stuck in ci relevant" - but thanks for the reminder.

**Comment by julien** [comment]
ci:test:sf

**Comment by julien** [comment]
ci:test:relevant

**Comment by julien** [comment]
its green!  :green_heart:

**Comment by julien** [comment]
I'm going to forward this.

**Comment by julien** [comment]
ci:forward

**Comment by julien** [comment]
Apparently I shouldn't have forwarded ... because there's is a conflict [here](https://github.com/brianchandotcom/liferay-portal/pull/100049).

**Comment by jbalsas** [comment]
Just type `ci:close` in there to close the PR and reopen this one, rebase and forward again ;)

**Comment by julien** [comment]
:+1: Thanks for the help @jbalsas 

I  just rebased locally with [`liferay/liferay-portal`](https://github.com/liferay/liferay-portal)'s `master` branch, and I don't see conflicts ... so are you saying I should rebase with [Brian's](https://github.com/brianchandotcom/liferay-portal) remote?

**Comment by jbalsas** [comment]
@julien, it's synced now!

**Comment by julien** [comment]
ci:forward

**Pull request closed without merging**
