### PR TITLE
LPS-161554 | Add automated test SameJSONCanBeEnabledOnMultipleSites 

### PR DESCRIPTION
**Pull request by mateusralv**
**Test Plan**

**Given** two sites with the same page elements
**When** site 1 has walkthrough enabled site-level with JSON
**And When** site 2 has walkthrough enabled site-level with JSON
//same JSON as site 1
**Then** hotspot element is present on first site
**And Then** hotspot element is present on second site

**JIRA Ticket:**
https://issues.liferay.com/browse/LPS-161554

### CODE REVIEW

**Comment by mateusralv** [comment]
ci:test:frontend:nocompile

**Comment by john-co** [comment]
Just started reviewing :)

**Review by john-co — APPROVED** [review]
Looks good to me! :sunglasses:

**Comment by john-co** [comment]
ci:forward

**Pull request closed without merging**
