### PR TITLE
LPS-155297 - Fix icons for virtual instances

### PR DESCRIPTION
**Pull request by bryceosterhaus**
https://issues.liferay.com/browse/LPS-155297

This ensures that icons will work for virtual instances as well as ensures proper guarding with feature flags.

To test:

1. start up liferay
2. log in to liferay
3. create a new virtual instance
4. access the new virtual instance and log in

### CODE REVIEW

**Comment by magjed4289** [comment]
Just started reviewing :)

**Comment by john-co** [comment]
Just started reviewing :)

**Comment by john-co** [comment]
Likely unrelated test failures. Running the tests again to double check.

- integration search test - looks like a fluke
- semantic-versioning - jenkins memory issue
- modules-semantic-versioning - junit error jenkins/ci issue

**Comment by john-co** [comment]
Reviewed. Test failures are unrelated. :heavy_check_mark: 

Ok to manually forward from QA perspective.

**Comment by john-co** [comment]
Manually forwarded to https://github.com/brianchandotcom/liferay-portal/pull/118418

**Pull request closed without merging**
