### PR TITLE
[TS] LPS-130813

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-130813

Please let me know if you have any questions, thanks!

CC @holatuwol @liferay-usm

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by john-co** [comment]
ci:test:relevant

**Comment by john-co** [comment]
Looks like test failures are related to the PR.

cc/ @patriciajeanperez

**Comment by ChrisKian** [comment]
I believe these test failures are related too.  I'll close the PR now.

**Pull request closed without merging**
