### PR TITLE
LPS-115680 - Add clay CSS components

### PR DESCRIPTION
**Pull request by marcoscv-work**
Updated files as a reflection of original ones:

https://github.com/liferay/clay/blob/master/packages/clay-css/src/scss/_variables.scss
https://github.com/liferay/clay/blob/master/packages/clay-css/src/scss/atlas/_variables.scss

Main bug related to empty state fixed:

image
(markup testing in-home page)

### CODE REVIEW

**Comment by marcoscv-work** [comment]
ci:test:sf

**Comment by marcoscv-work** [comment]
ci:test:stable

**Comment by marcoscv-work** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
LGTM, forwarding!

**Comment by jbalsas** [comment]
ci:forward

**Pull request closed without merging**
