### PR TITLE
LPS-163171 Status filter is not working on FDS sample module

### PR DESCRIPTION
**Pull request by markocikos**
### References

- [LPS-163171 Status filter is not working on FDS sample module](https://issues.liferay.com/browse/LPS-163171)
- related to [LPS-158738 A data request with status field filter breaks in URI parsing](https://issues.liferay.com/browse/LPS-158738)

### What is the goal of this PR?

A bugfix. Status filter in FDS sample stopped working after a change in Objects backend. LPS-158738 was a part of the fix, but we also need to explicitly declare entity field type of the status in FDS. In addition, we are introducing constants for entity types related to FDS.

/cc @john-co 

#### Before PR
before

#### After PR
after

### Steps to reproduce

1. Deploy `frontend-data-set-sample-web`.
2. Place `Frontend Data Set Sample` widget on any page.

### CODE REVIEW

**Comment by markocikos** [comment]
ci:stop

**Comment by markocikos** [comment]
Force-pushed to fixed minor semver conflict.

**Comment by markocikos** [comment]
ci:test:sf

**Comment by markocikos** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
ci:test:relevant

**Review by ccorreagg — APPROVED** [review]
LGTM

**Comment by markocikos** [comment]
ci:forward

**Comment by markocikos** [comment]
ci:stop

**Review by LuismiBarcos — APPROVED** [review]

**Comment by diegonvs** [comment]
ci:forward

**Comment by markocikos** [comment]
ci:forward

**Comment by markocikos** [comment]
ci:forward

**Comment by markocikos** [comment]
ci:forward

**Comment by diegonvs** [comment]
ci:forward

**Comment by diegonvs** [comment]
ci:forward

**Comment by markocikos** [comment]
ci:forward

**Comment by mateusralv** [comment]
Hi @markocikos the failures are not related with your PR. 🎉 🟢 

### Failures not unique:

1. [LocalFile.SupportManyToManyRelationships#ObjectEntryDeletionImpossibleWi...](https://testray.liferay.com/home/-/testray/case_results/1990785694)
2. [LocalFile.ObjectRelationships#CanRelateManyToManyCustomObjectEntryWithNa...](https://testray.liferay.com/home/-/testray/case_results/1990786068)
3. [LocalFile.VisualizeObjectDisplayPage#ObjectEntriesAreRendered](https://testray.liferay.com/home/-/testray/case_results/1990785548)
4. [com.liferay.object.service.test.ObjectRelationshipLocalServiceTest](https://testray.liferay.com/home/-/testray/case_results/1990786694)
5. [com.liferay.object.admin.rest.resource.v1_0.test.ObjectDefinitionResourc...](https://testray.liferay.com/home/-/testray/case_results/1990786639)
6. [modules-semantic-versioning-jdk8/0/0](https://testray.liferay.com/home/-/testray/case_results/1990786644)
7. [modules-semantic-versioning-jdk8/0/0](https://testray.liferay.com/home/-/testray/case_results/1990786644)

**Pull request closed without merging**
