### PR TITLE
LPS-116752 Social bookmarks share button styles

### PR DESCRIPTION
**Pull request by boton**
We have two problems with share button

**Steps to reproduce:**

- Add a new widget page with the KB display widget
- Go to KB to add a basic article
- Go the page 
- View the share button 

**Expected Result:**

The share button can be displayed normally as below

image

**Actual Result:**

The share button can not be displayed normally as below

image

---

**Steps to reproduce:**

- Add a blog entry
- Add a blog widget in a page

**Expected results:**

The social bookmarks dropdown doesn't have a text and has a title.

image

**Actual results:**

The social bookmarks dropdown has a cut text and doesn't have a title.

image

### CODE REVIEW

**Comment by boton** [comment]
@jbalsas we need to spread the title to the dropdown trigger

**Comment by jbalsas** [comment]
Thanks @boton! I'll take this one and complete it... I think we're failing to pass the `_dynamicAttributes` as props in [`prepareProps`](https://github.com/liferay/liferay-portal/blob/master/modules/apps/frontend-taglib/frontend-taglib-clay/src/main/java/com/liferay/frontend/taglib/clay/internal/servlet/taglib/BaseContainerTag.java#L249)

**Comment by boton** [comment]
I pass the title to the clay dropdown here https://github.com/liferay-frontend/liferay-portal/pull/118/files#diff-f53cecdf213bf0d35836806f14a74211R83, but not render in the final HTML.

image

Maybe we need to filter locale to provide clean HTML.

**Comment by jbalsas** [comment]
Hey @boton! I can't push to your fork, so I've created https://github.com/liferay-frontend/liferay-portal/pull/124 to as a followup. Moving the conversation over there!

**Pull request closed without merging**
