### PR TITLE
LPS-165903 The checkbox is visible in default page

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-165903](https://issues.liferay.com/browse/LPS-165903).

Hi all, will you please look over my changes? 

The main idea here is that the result of the default `isDisabled` method of `SearchContainerManagementToolbarDisplayContext` is almost never desirable because it will disable other potentially useful functionality like the search bar and filter menu. 

You can see that there are a number of places where I removed the overrides that restored the original behavior of [`ManagementToolbarDisplayContext#isDisabled`](https://github.com/liferay/liferay-portal/blob/aabc2f3ad7b8f11b3dcb9e8325a27ff51eaa3268/modules/apps/frontend-taglib/frontend-taglib-clay/src/main/java/com/liferay/frontend/taglib/clay/servlet/taglib/display/context/ManagementToolbarDisplayContext.java#L145-L147).

Instead, the default behavior will now be to simply remove the checkbox when there is nothing to check, but leave the toolbar enabled. To me this seems like a sensible default, but I'm open to suggestions.

Please let me know if you have any questions or concerns. Thanks!

/cc @pei-jung @ces-huynguyen @sontruongces

### CODE REVIEW

**Comment by drewbrokke** [comment]
FYI @patriciajeanperez there will probably need to be some functional test updates as a result of these changes. Basically, the default for many management toolbars will now be that there is no checkbox visible when there are no results. Not sure if any functional tests assert on that but that's what to expect if this change goes through.

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
Just pushed a fix for the baseline failure.

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:reevaluate:1387401_4681

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
@liferay-frontend any updates on this one?

**Comment by mateusralv** [comment]
I'm taking a look at [these](https://github.com/liferay-frontend/liferay-portal/pull/2831#issuecomment-1309133937) failures 🕵🏽

**Comment by mateusralv** [comment]
Hi @drewbrokke the failures are not related to your PR 🎉 

[comparison run](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1668205486081&testrayRunIdA=2046948947&testrayRunIdB=2043170034)

**Comment by drewbrokke** [comment]
Thanks @mateusralv! Any objections to forwarding this one?

**Comment by mateusralv** [comment]
Hi @drewbrokke I ran ci:test:relevant again just to make sure everything is safe to forward. I'll monitor 🕵🏽

**Comment by mateusralv** [comment]
Hi @drewbrokke Most of the errors are not related to your PR. But I’m doubting about this error that is returning in the module `modules-semantic-versioning-jdk8/0/0`. Could you take a look? 
```
[exec] com.liferay.semantic.versioning.SemanticVersioningTest > testSemanticVersioning[/apps/asset/asset-display-page-api] STARTED
     [exec] 
     [exec] com.liferay.semantic.versioning.SemanticVersioningTest > testSemanticVersioning[/apps/asset/asset-display-page-api] FAILED
     [exec]     java.lang.AssertionError:   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec]     = ================================================== ========== ========== ========== ========== ==========
     [exec]     * com.liferay.asset.display.page.portlet             MAJOR      5.0.0      5.0.0      6.0.0      VERSION INCREASE REQUIRED
     [exec]     	>   class      com.liferay.asset.display.page.portlet.BaseAssetDisplayPageFriendlyURLResolver
     [exec]     		+   field      infoSearchClassMapperRegistry
     [exec]     			+   access     protected
     [exec]     			+   annotated  org.osgi.service.component.annotations.Reference
     [exec]     			+   return     com.liferay.info.search.InfoSearchClassMapperRegistry
     [exec]     		-   field      infoSearchClassMapperTracker
     [exec]     			-   access     protected
     [exec]     			-   annotated  org.osgi.service.component.annotations.Reference
     [exec]     			-   return     com.liferay.info.search.InfoSearchClassMapperTracker
     [exec]     [Baseline Warning] Bundle Version Change Recommended: 11.0.0
     [exec]         at org.junit.Assert.fail(Assert.java:88)
```
the other failures are not related. 🎉 
[comparison run](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1668631094124&testrayRunIdA=2054443870&testrayRunIdB=2053883062)
cc: @john-co

**Comment by drewbrokke** [comment]
@mateusralv I think it's unlikely that that failure is related to my change. It's probably present because I changed a file in a related module, and it runs the relevant tests, but I would suspect that failure is present in other runs in the same suite.

**Comment by bryceosterhaus** [comment]
LGTM! I think this is safe to forward, knowing that the previous relevant runs were successful

**Comment by drewbrokke** [comment]
Just rebased and force-pushed. @mateusralv any objections to forwarding this one? We can do another CI run if needed.

**Comment by mateusralv** [comment]
Thank you @drewbrokke, I'll run ci:test:relevant again

**Comment by mateusralv** [comment]
ci:test:relevant

**Comment by mateusralv** [comment]
I'm taking a look now 🕵🏽

**Comment by mateusralv** [comment]
Hi @drewbrokke I found one unique failure and I'm create a testfix for send with this PR. Could you give me permission to add commits to this PR?  

[Comparison run](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=2&testrayRunIdB=2083809026&testrayRunIdA=2080608860&statusB=3)

Unique failure: 
LocalFile.MBThread#CanLockAndUnlockThread

**Comment by drewbrokke** [comment]
@mateusralv is it possible for me to give you those permissions without granting you push access to my repo? If so I'm curious to know how. Otherwise, feel free to send a new PR based off of this one and we'll use it instead. Or you can send a PR to me and I'll apply your changes to this branch, whatever you prefer.

**Comment by mateusralv** [comment]
@drewbrokke I don’t know, just with access to repo 😄 . so I’ll send another PR and you add the PR to that. Thank u.

**Comment by mateusralv** [comment]
ci:test:frontend:nocompile

**Comment by eltonccdantas** [comment]
ci:test:frontend:nocompile

**Comment by drewbrokke** [comment]
Just force-pushed a fix for the merge conflicts. Anything I can do to help move this one forward? No further changes are needed, right?

**Comment by drewbrokke** [comment]
ci:reevaluate:1277401_6089

**Comment by john-co** [comment]
ci:test:frontend

**Comment by john-co** [comment]
Hey @mateusralv , when you have `ci:test:frontend:nocompile`, the `nocompile` means that it will run the tests using a prebuilt bundle. However, we have dev code changes that we do want to compile a bundle for and run the tests against. So we want to run interested test suites without `nocompile` to properly test the PR.

**Comment by john-co** [comment]
ci:test:relevant

**Comment by john-co** [comment]
cc/ @eltonccdantas or @mateusralv would you be able to review if anything else is needed to forward this?

**Comment by mateusralv** [comment]
I'm taking a look 🕵🏽

**Comment by mateusralv** [comment]
The failures are not related 🚀 🎉 

[comparison run ](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1670420853792&testrayRunIdA=2106004744&testrayRunIdB=2107417916)

**Comment by drewbrokke** [comment]
@mateusralv Any objections to forwarding this one?

**Comment by mateusralv** [comment]
No, it looks safe to forward. @drewbrokke

**Pull request closed without merging**
