### PR TITLE
LPS-159419 Add more classes that could instantiate certain Property Definitions

### PR DESCRIPTION
**Pull request by ccorreagg**
Related PR: https://github.com/liferay-frontend/liferay-portal/pull/2588

Given a PropertyDefinition, a PropertyDefinition is allowed to be instantiated by some different classes than before. The following cases have been added:

- **BIG_DECIMAL**: Apart from BigDecimal, **Integer**, **Double**, **Float** and **Long** have been added.
- **DECIMAL**: Apart from Float, **Integer** and **Long** have beed added.

With this, it will be possible to keep the default validation for the case of Objects

### CODE REVIEW

**Review by LuismiBarcos — APPROVED** [review]
LGTM :)

**Comment by LuismiBarcos** [comment]
ci:forward

**Comment by john-co** [comment]
ci:forward

**Comment by LuismiBarcos** [comment]
Thanks @john-co for the forward ❤️

**Pull request closed without merging**
