### PR TITLE
LPS-187105 Created stubs for new automations in Filters - LPS-176187

### PR DESCRIPTION
**Pull request by andreluis2022**
Description:
Functional Automation - LPS-176187 - Define Dynamic Selection filters for the Dataset View

JIRA Ticket:
[LPS-176187](https://issues.liferay.com/browse/LPS-176187) History
[LPS-187105](https://issues.liferay.com/browse/LPS-187105) Stubs

### CODE REVIEW

**Comment by andreluis2022** [comment]
ci:test:sf

**Comment by andreluis2022** [comment]
@mateusralv can you take a look , please ?

**Comment by mateusralv** [comment]
ci:test:sf

**Comment by mateusralv** [comment]
ci:test:sf

**Comment by andreluis2022** [comment]
ci:test:sf

**Comment by andreluis2022** [comment]
@mateusralv

**Pull request closed without merging**
