### PR TITLE
LPS-170536 | Add Autom. Test FDSAsyncItemAction#RequestInvalidIPCanReturnErrorConnectionRefused

### PR DESCRIPTION
**Pull request by eltonccdantas**
**Test Plan**

- Given: Frontend Dataset sample portlet
- When open action list dropdown menu in 1st row item
- And When access async connection refused to request invalid ip address
- Then returns unexpected error alert toast

**Jira Ticket:**
https://issues.liferay.com/browse/LPS-170536

### CODE REVIEW

**Comment by eltonccdantas** [comment]
CC/ @mateusralv

**Review by mateusralv — APPROVED** [review]
LGTM 🎉

**Comment by mateusralv** [comment]
ci:test:frontend

**Comment by mateusralv** [comment]
Committed on https://github.com/liferay-frontend/liferay-portal/pull/2911

**Pull request closed without merging**
