### PR TITLE
LPS-129456 Unable to edit Content Translations after browser window has been resized

### PR DESCRIPTION
**Pull request by IstvanD**
Dear Team,

Could you please review this pull request?

Thank you and best regards,
István

### CODE REVIEW

**Comment by IstvanD** [comment]
Dear Team,

I was wondering if you could find the time to review the pull request.
Please let me know if you need any help or explanation.

Thank you and best regards,
István

**Comment by markocikos** [comment]
@IstvanD The solution in this PR is safe and does fix the issue in ticket.

But, why does it work? :thinking:  Resize should not affect what `input.get('form')` returns. If input is in a form, this returns that form. Do we remove a form with resize? That seems wrong.

**Comment by jbalsas** [comment]
Hey @antonio-ortega, did you get eyes on this one? Maybe you can help us clarify this a little here?

**Comment by IstvanD** [comment]
hi @markocikos 

I have debugged the scenario, but I could only find that when the browser window is resized, `clearFormValidator(input)` will be unable to find the enclosing form element of textarea element with ID _com_liferay_journal_web_portlet_JournalPortlet_descriptionMapAsXMLEditor. Unfortunately, I wasn't able to find the root cause of this.

**Comment by antonio-ortega** [comment]
Hi guys,

I've seen the key of this issue is that CKEditor is firing an _instanceReady_ event when we move from mobile to desktop view or the other way around. That's making initialise our CKEditor again as you can see [here](_com_liferay_docs_mvcportlet_MyMvcPortlet_INSTANCE_ocmt_testLPS129456Editor):
```
ckEditor.on('instanceReady', () => {
    <c:choose>
        <c:when test="<%= useCustomDataProcessor %>">
            instanceReady = true;

            if (customDataProcessorLoaded) {
                initData();
            }
        </c:when>
        <c:otherwise>
            initData();
        </c:otherwise>
    </c:choose>
```
And creating a new component with the same id as you can see [here](https://github.com/liferay/liferay-portal/blob/master/modules/apps/frontend-editor/frontend-editor-ckeditor-web/src/main/resources/META-INF/resources/ckeditor.jsp#L462-L464). You can also see this just by checking the browser console and seeing the tipically ignored message about components with duplicated id.

So, although we don't realise about the change, when we move from desktop to mobile we are having a new editor which is not properly attached to our inputLocalized component and that's the reason of the error. In fact, you don't need to resize back to desktop, as soon as there is change in the view between mobile and desktop, this issue appears.

I hope this helps you to find the right solution for this case.

Regards.

**Comment by markocikos** [comment]
> CKEditor is firing an instanceReady event when we move from mobile to desktop view or the other way around. That's making initialise our CKEditor again

:scream: 

This seems wrong, a potential for many bugs in the future. Is this the default ckeditor behavior? If yes, maybe we should make sure to cleanup resources line localized input components, either on resize or on init. Or maybe `instanceReady` does not do mean what we think it means, and we shouldn't use it in initialization. Or it is a bug that `instanceReady` is thrown on resize. 

@julien does this behavior sound familiar to you?

**Comment by julien** [comment]
@markocikos I'll have a look in the issue, but of the top of my head, this isn't CKEditor's default behavior, I also know we have this [event listener](https://github.com/liferay/liferay-portal/blob/20206ada64511caf36d53e6bf5781dfe948f2f30/modules/apps/frontend-editor/frontend-editor-ckeditor-web/src/main/resources/META-INF/resources/ckeditor.jsp#L594-L620) that might be "recreating" the editor ... so I'll have a look at that.

**Comment by antonio-ortega** [comment]
Hi guys,

I just realized the analysis I carried out yesterday was not complete. What I was seeing was just part of all the process of initializing a new editor, but why are we initializing a new editor when we change between mobile and desktop view? Because of [this code](https://github.com/liferay/liferay-portal/blob/master/modules/apps/frontend-editor/frontend-editor-ckeditor-web/src/main/resources/META-INF/resources/ckeditor.jsp#L590-L621):
```
eventHandles.push(
    A.getWin().on(
        'resize',
        A.debounce(() => {
            if (currentToolbarSet != getToolbarSet(initialToolbarSet)) {
                var ckeditorInstance =
                    CKEDITOR.instances['<%= name %>'];

                if (ckeditorInstance) {
                    var currentEditor = ckeditorInstance.id;

                    if (currentEditor === initialEditor) {
                        var currentDialog = CKEDITOR.dialog.getCurrent();

                        if (currentDialog) {
                            currentDialog.hide();
                        }

                        ckEditorContent = ckeditorInstance.getData();

                        window['<%= name %>'].dispose();

                        window['<%= name %>'].create();

                        window['<%= name %>'].setHTML(ckEditorContent);

                        initialEditor =
                            CKEDITOR.instances['<%= name %>'].id;
                    }
                }
            }
        }, 250)
```

There you can see every time we change the toolbar (what happens we swap between mobile and desktop views) we initialized the whole editor. And that's the root cause of the issue reported in LPS-129456.

Sorry for the confusion I could create with my comment yesterday.

I hope this helps to clarify it.

Regards.

**Comment by julien** [comment]
Hey @antonio-ortega thanks for having a look at that.

It mostly seems to match my [previous comment](https://github.com/liferay-frontend/liferay-portal/pull/921#issuecomment-806491637). Maybe we could have the option to change the editor's toolbars without "destroying" the current editor or maybe we need to "wire" the editor with the input_localized component when we recreate this editor.

**Comment by markocikos** [comment]
Conversely, in [`ClassicEditor`](https://github.com/liferay/liferay-portal/blob/master/modules/apps/frontend-editor/frontend-editor-ckeditor-web/src/main/resources/META-INF/resources/editor/ClassicEditor.js#L110-L112), we are updating toolbar on resize by updating state, which updates `config` prop. This may not have the ideal interaction with localization, i.e. we may need to migrate the localization component as well.

I don't know if we can update it in current editor without full re-initialization. If it cannot be easily done, there is always an option of pushing this PR as a quick & dirty fix, and revisit the problem when migrating to `ClassicEditor`.

**Comment by julien** [comment]
It doesn't seem possible to update an editor's toolbars at runtime ...
I'm still trying to figure out how that input localized is connected to the editor but I haven't found anything yet.
I still want to keep looking at it because I think it would be better to fix this the proper way

**Comment by julien** [comment]
@antonio, after all you were right, it does seem to be related with the editor, and the input_localized `inputPlaceholder` property.

I've sent [https://github.com/liferay-frontend/liferay-portal/pull/939](https://github.com/liferay-frontend/liferay-portal/pull/939) because I couldn't push to @IstvanD 's remote - but if you want we can keep on discussing here.

**Comment by jbalsas** [comment]
Closing here since this seems to continue in https://github.com/liferay-frontend/liferay-portal/pull/939

**Pull request closed without merging**
