### PR TITLE
[TS] LPS-146978 | master

### PR DESCRIPTION
**Pull request by samanzanedo**
**Description**

- Our REST builder defines a [SimpleDateFormat](https://docs.oracle.com/javase/8/docs/api/java/text/SimpleDateFormat.html) object with the general pattern _yyyy-MM-dd HH:mm:ss timezone_
- But it seems there was a typo defining that pattern related to the timezone, maybe because of a quoted 'T' letter added between date and time: we did the same with 'Z' letter (it is quoted)
- So, the pattern is defined as _yyyy-MM-dd'T'HH:mm:ss'Z'_ and then, the quoted 'Z' (timezone) is not interpreted during formatting.

**Steps to reproduce**
With
`DateFormat liferayToJSONDateFormat = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss'Z'");`
we get
`2021-02-09T09:30:03Z`

Whereas with
`DateFormat liferayToJSONDateFormat = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ssZ");`
we get
`2021-02-09T09:30:03+0200`

**Solution proposed**
Unquoting de 'Z' letter to allow be interpreted as RFC 822 time zone

Best.
 Sergio.

### CODE REVIEW

**Comment by samanzanedo** [comment]
ci:test:sf

**Comment by samanzanedo** [comment]
ci:test:relevant

**Comment by samanzanedo** [comment]
ci:test:frontend

**Comment by samanzanedo** [comment]
Hi team,

Does this PR need anything else?

Regards.
 Sergio

**Comment by samanzanedo** [comment]
Hi, @liferay-frontend team

Could you give me some feedback about this? We have a customer awating a solution.

Regards.
 Sergio.

**Comment by javierdearcos** [comment]
Hello Sergio,

Sorry that we were not aware of this PR until now.

Makes sense to me.

We will need to run a REST Builder generation to apply the change in every API. You can do it running `gw buildREST` from the modules/dxp/apps folder.

I can do it tomorrow if you prefer and forward the PR then

**Comment by john-co** [comment]
cc/ @xbrianlee I've noticed flakiness with the Blueprints tests in the past week or so. Are there plans to stabilize?

**Comment by xbrianlee** [comment]
@john-co Two tickets from other teams caused Blueprints failures (and failures for other teams) - [LPS-144873](https://issues.liferay.com/browse/LPS-144873), [LPS-144442](https://issues.liferay.com/browse/LPS-144442). Both issues have since been resolved.

**Comment by LuismiBarcos** [comment]
I'm taking care of this [here](https://github.com/liferay-frontend/liferay-portal/pull/1914)
Thanks 🙂

**Pull request closed without merging**
