### PR TITLE
LPS-182055 Element is not present in FDSViews#CanCancelDeletionOnCloseButton

### PR DESCRIPTION
**Pull request by andreluis2022**
Description:
Investigated the failure caused by an element that is not present

JIRA Ticket:
https://issues.liferay.com/browse/LRQA-80301

### CODE REVIEW

**Comment by andreluis2022** [comment]
ci:test:frontend

**Comment by mateusralv** [comment]
Follow up: https://github.com/liferay-frontend/liferay-portal/pull/3238

**Comment by mateusralv** [comment]
ci:test:frontend-data-set

**Review by mateusralv — APPROVED** [review]
Good Job @andreluis2022 🎉

**Comment by mateusralv** [comment]
ci:forward

**Pull request closed without merging**
