### PR TITLE
LPD-15338 Get ride of removed files in AUI Preload list

### PR DESCRIPTION
**Pull request by antonio-ortega**
Those files were removed as part of [LPS-8169](https://liferay.atlassian.net/browse/LPD-8169) so we don't need them anymore in this preload list.

### CODE REVIEW

**Comment by antonio-ortega** [comment]
ci:test:relevant

**Review by markocikos — APPROVED** [review]
@antonio-ortega LGTM! :sparkles:

**Comment by antonio-ortega** [comment]
ci:test:relevant

**Comment by antonio-ortega** [comment]
ci:forward

**Comment by antonio-ortega** [comment]
ci:forward:force

**Pull request closed without merging**
