### PR TITLE
LPS-181575 Modify label and icon for FDSViews edit link – PART 2

### PR DESCRIPTION
**Pull request by edalgrin**
Follow up from https://github.com/liferay-frontend/liferay-portal/pull/3585

---

This PR modifies the label and the icon of the FDS Entry and View, edit and rename link

image
image

### CODE REVIEW

**Comment by thektan** [comment]
@edalgrin fyi, I created a new subtask for this PR https://liferay.atlassian.net/browse/LPS-194546

**Comment by edalgrin** [comment]
Thanks! I'll fix the conflicts, rebase on master and see if I can proceed with this ones

**Comment by edalgrin** [comment]
ci:test:sf

**Comment by edalgrin** [comment]
ci:test:relevant

**Comment by edalgrin** [comment]
ci:forward

**Pull request closed without merging**
