### PR TITLE
LPS-154636 Add WalkthroughHotspot#WillRenderAsInitialState

### PR DESCRIPTION
**Pull request by susanchen3**
**Background**
Create automated tests for Walkthrough component. 

**Test Plan**
Given: frontend-js-components-sample-web deployed to test page
When: Navigate to Walkable tab on sample portlet
Then: Hospot element is present
And Then: popover element is not present

**JIRA Ticket:**
https://issues.liferay.com/browse/LPS-154636

### CODE REVIEW

**Comment by susanchen3** [comment]
Tried testing initial state with ocular, but didn't match on CI. :( Will attempt again when next Poshi release comes out.

**Comment by susanchen3** [comment]
ci:test:sf

**Comment by susanchen3** [comment]
ci:test:frontend

**Comment by john-co** [comment]
Just started reviewing :)

**Comment by john-co** [comment]
ci:forward

**Comment by john-co** [comment]
ci:forward

**Pull request closed without merging**
