### PR TITLE
LPS-118937 - Update clay dependencies

### PR DESCRIPTION
**Pull request by bryceosterhaus**
Includes updates for both 2.x and 3.x modules.

### CODE REVIEW

**Comment by bryceosterhaus** [comment]
ci:test:sf

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by wincent** [comment]
> **Conflicting files**
>
> `modules/etl/mulesoft/.gitrepo`

wat

Not sure how that got in there?

@bryceosterhaus: In the lockfile, I see two versions of clay-css (2.21.3 and 2.21.4), so I think we should identify the cause of that and ensure that there's only one; could be as simple as running `npx yarn-deduplicate yarn.lock`, or it might be an errant version in some package.json somewhere.

@PablitoBonito: I haven't looked at the unique failures yet but would you mind taking a preliminary peek and letting us know whether anything in there looks flaky/unrelated vs legit? (Not too deep, as I believe we have to make at least two tweaks to this before retrying.)

**Comment by wincent** [comment]
@bryceosterhaus: rebased and force-pushed to your fork (dropped the commit that was causing the conflict, and deduped the lockfile); going to re-run tests.

**Comment by wincent** [comment]
ci:test:sf

**Comment by wincent** [comment]
ci:test:relevant

**Comment by wincent** [comment]
1. ci:test:relevant - 175 out of 191 jobs passed in 3 hours 35 minutes
2. ci:test:relevant - 178 out of 192 jobs passed in 3 hours 5 minutes

so-youre-telling-me-theres-a-chance

@john-co @PablitoBonito can you please help us analyze the results so we can figure out what needs to be done?

**Comment by bryceosterhaus** [comment]
Thanks for updating @wincent! Not sure how that file got in there... I also ran deduplicate before hand, did you do something else to address the clay-css dependencies?

**Comment by wincent** [comment]
> I also ran deduplicate before hand, did you do something else to address the clay-css dependencies?

This is what I did:

1. Run `yarn why clay-css` and see that the two versions were coming in via:
    - `frontend-taglib-clay`; and:
    - `frontend-editor-alloyeditor-web` → `alloyeditor`
2. Confirm that [alloyeditor's package.json](https://github.com/liferay/alloy-editor/blob/a4e8d1e9ab4a1c54f7c4858f624610575137e9a3/package.json#L90) has a loose enough version range for clay-css.
3. Run `npx yarn-deduplicate yarn.lock` from `modules/`.

So not sure why it didn't dedupe for you 🤷

**Comment by bryceosterhaus** [comment]
@wincent ah good to know. I need to keep a better eye on the yarn.lock anyways, so this is a good reminder to always look through it on updates like this.

**Comment by john-co** [comment]
Some tests are encountering areas where it's not able to detect the custom js event modalIframeLoaded in certain Modals. In the tests, we make sure that this listener is on each time the test does a click action. And checks that this event has fired when a modal has opened before continuing with the test.

https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=3&testrayRunIdB=1257108957&testrayRunIdA=1256861011&statusB=2

 `Event "modalIframeLoaded" with attribute "src" and value "dialog-iframe-popup" not fired.`

Other unique issues:
- WebContentDisplay#AddExistingPageAsDisplayPageInSiteCP
- NavigationMenuWidgetUseCase#ShowMoreThanTwoSublevelsWhenSelectPublicPagesHierarchyAndBarMinimallyStyled
- All WorkflowMetric tests have various errors
These other unique issues are a mix of mostly test fixes and a couple possible regressions as I glance through them.

@zhangyan0701 could you investigate further?

**Comment by bryceosterhaus** [comment]
@john-co I just went through these failures locally and can't seem to reproduce any from a functionality perspective. My guess is that tests need to be updated or something is being flakey

**Comment by john-co** [comment]
ci:test:relevant

**Comment by john-co** [comment]
ci:test:bundle

**Comment by john-co** [comment]
Hi @zhangyan0701, could you take a look?

**Comment by zhangyan0701** [comment]
Just started reviewing.

**Comment by zhangyan0701** [comment]
Comparison with master upstream:
https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=3&testrayRunIdB=1257440608&testrayRunIdA=1257380088&statusB=2

Besides the modalIframeLoaded error. All other tests failed because Drop down menu doesn't work properly:

Case 1: Child page dropdown in Navigation Menu protlet.
navigation menu

Case 2: When configure SLA in Workflow Metrics.
SLA

Case 3: When reassign workflow tasks in Workflow Metrics.
new assignee

Flaky Test LocalFile.DisplayPages#EditDisplayPage: passed locally.

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
So after some investigating, the dropdown issues seem to stem from a css change we added that added the `pointer-events: none;` style to `.dropdown-item.active`. This style is appropriate to add, since we don't want to be able to interact with the already active list item.

However, for some legacy dropdowns in `liferay-portal`, we add the `.active` class on mousedown via [A.Plugin.NodeFocusManage](https://github.com/liferay/liferay-portal/blob/master/modules/apps/frontend-js/frontend-js-aui-web/src/main/resources/META-INF/resources/liferay/navigation_interaction.js#L227). Because the class is add on mousedown, this essentially cancels the click action on the item. Meaning that navigating on an href or the `onClick` callback won't work.

So my proposed solution is simply overriding that style in `liferay-portal` until we can find a proper solution of either getting rid of the legacy code or finding a work around in clay. IMO, it seems really odd to add the `.active` class on mousedown, so I think we should work on removing that legacy code.

**Comment by bryceosterhaus** [comment]
cc @pat270

**Comment by jbalsas** [comment]
This is green... so...

**Comment by jbalsas** [comment]
ci:forward

**Pull request closed without merging**
