### PR TITLE
LPS-181343 | Added FDSViews automation tests 

### PR DESCRIPTION
**Pull request by andreluis2022**
Description:
Added FDSViews tests 

Linked tests with respective tickets:
[FDSViews#CanEditOrDeleteView](https://issues.liferay.com/browse/LPS-181344)
[FDSViews#AssertNumberOfCharactersInDescriptionField
](https://issues.liferay.com/browse/LPS-181349)[FDSViews#CanEditView](https://issues.liferay.com/browse/LPS-181343)
[(FDSViews#CanCreateMultipleViews - already checked)
](https://issues.liferay.com/browse/LPS-181354)

### CODE REVIEW

**Comment by andreluis2022** [comment]
ci:test:frontend

**Comment by andreluis2022** [comment]
ci:test:sf

**Comment by andreluis2022** [comment]
ci:test:frontend

**Comment by andreluis2022** [comment]
ci:test:sf

**Comment by andreluis2022** [comment]
ci:test:frontend

**Comment by andreluis2022** [comment]
ci:test:frontend

**Comment by andreluis2022** [comment]
Hey @mateusralv do you think you could take a look at this please?

**Comment by andreluis2022** [comment]
ci:test:sf

**Comment by andreluis2022** [comment]
ci:test:frontend

**Comment by mateusralv** [comment]
Continue https://github.com/liferay-frontend/liferay-portal/pull/3274

**Pull request closed without merging**
