### PR TITLE
LPS-134933 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-134933

This is only for master.

@LuismiBarcos
@liferay-frontend

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:stop

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by LuismiBarcos** [comment]
ci:forward

**Comment by LuismiBarcos** [comment]
Thank you very much @Tim-Cao

**Comment by Tim-Cao** [comment]
You're welcome @LuismiBarcos

**Pull request closed without merging**
