### PR TITLE
LPS-126038 Move dataset-display to its own module

### PR DESCRIPTION
**Pull request by jbalsas**
This is a WIP PR to move all parts of our Dataset tag to its own module.

So far, this includes:
- Creating a new `dataset` app
- Copying only the necessary classes from `frontend-taglib-clay` to `dataset-taglib`
- Extracting the JS component into its own `dataset-web` module
- Sample WIP commit in `remote-app-admin-web` portlet showing the necessary changes to apply the new tag (goal would be to make this as small as possible before the end)

Main things missing:
- Split into `dataset-api` and `dataset-impl`, specially the `JAXRS` application.
- Rename as `Dataset` instead of `DataSet`. That is:
    - `com.data.set` should be come `com.dataset`
    - `DataSet` should become `Dataset`
    - `dataSet` should become `dataset`
    - `data_set` should become `dataset`
    - ...

### CODE REVIEW

**Comment by wincent** [comment]
We can expect a splendid mid-air collision with https://github.com/liferay-frontend/liferay-portal/pull/789, at least. 😬

**Comment by jbalsas** [comment]
Yeah, but it won't be a collision as much as a possible code omision. I went with a blind copy rather than a move here (maybe we want reconsider it for history purposes...) in case we needed to keep both but maybe we can rework this somehow to make that less of an issue.

**Comment by wincent** [comment]
> I went with a blind copy rather than a move here (maybe we want reconsider it for history purposes...)

Well, it's never great/easy to do huge moves/copies, but `git-diff` and `git-log` do have:

```
       -C[<n>], --find-copies[=<n>]
           Detect copies as well as renames. See also --find-copies-harder. If n is specified, it has the
           same meaning as for -M<n>.

       --find-copies-harder
           For performance reasons, by default, -C option finds copies only if the original file of the
           copy was modified in the same changeset. This flag makes the command inspect unmodified files as
           candidates for the source of copy. This is a very expensive operation for large projects, so use
           it with caution. Giving more than one -C option has the same effect.
```

**Comment by jbalsas** [comment]
Going to close this since @izaera still needs to pick it up. Or maybe he can update this with his progress and I can pick it up again next week... 🤔

**Comment by izaera** [comment]
I've pushed tree minor fixes as a WIP commit so that we don't lose it.

**Comment by izaera** [comment]
The commit doesn't show in this PR (maybe because it's closed ?)

It's here -> https://github.com/jbalsas/liferay-portal/commits/LPS-126038-dataset

It is just three incorrect things I saw when reviewing the PR to deploy it to be able to work on it.

**Comment by jbalsas** [comment]
Ah, got it, I thought you had already separated things into `impl` and `api`...

**Pull request closed without merging**
