### PR TITLE
LPS-202924 Test Fix: DataSet#CanAssertTheEndpointObjectInDataSetCreated

### PR DESCRIPTION
**Pull request by mateusralv**
**Jira Ticket:**
https://liferay.atlassian.net/browse/LPS-202924

### CODE REVIEW

**Comment by mateusralv** [comment]
ci:test:frontend-data-set

**Review by CarlosBrichete — APPROVED** [review]
LGTM :)

**Comment by mateusralv** [comment]
The test fix works in CI 🎉

**Comment by mateusralv** [comment]
ci:forward

**Pull request closed without merging**
