### PR TITLE
LPS-170535| Add Autom. Test  FDSAsyncItemAction#RequestValidIPCanReturnSuccess

### PR DESCRIPTION
**Pull request by eltonccdantas**
**Test Plan**

- Given: Frontend Dataset sample portlet
- When open action list dropdown menu in 1st row item
- And When access async success action item to request valid ip address
- Then returns success alert toast

**Jira Ticket:**
https://issues.liferay.com/browse/LPS-170535

### CODE REVIEW

**Comment by eltonccdantas** [comment]
CC/ @mateusralv

**Review by mateusralv — APPROVED** [review]
LGTM 🎉

**Comment by mateusralv** [comment]
ci:test:frontend

**Comment by mateusralv** [comment]
commited on  https://github.com/liferay-frontend/liferay-portal/pull/2911

**Pull request closed without merging**
