### PR TITLE
LPS-159484 Makes Walkthrough localStorage keys unique depending on userId

### PR DESCRIPTION
**Pull request by diegonvs**
# Steps to reproduce

0. Create two users, User 1 and User 2
1. Enable Walkthrough enabled with multiple steps
2. User 1 navigates to Step 2
3. User 1 signs out, and User 2 signs in
4. User 2 navigates to Step 1
5. Logout and Login with User 1
Now, User 1 will be at Step 2, and then log in with User 2; it will be on Step 1.

# How I solved it

Found `themeDisplay.getUserId()` which can be useful for making localStorage keys unique depending on user.

### CODE REVIEW

**Comment by diegonvs** [comment]
ci:test:relevant

**Comment by diegonvs** [comment]
ci:test:relevant

**Comment by diegonvs** [comment]
image

**Review by matuzalemsteles — APPROVED** [review]
LGTM

**Comment by matuzalemsteles** [comment]
ci:forward

**Pull request closed without merging**
