### PR TITLE
LPS-168776 Move info button to be the last item to the right in MT

### PR DESCRIPTION
**Pull request by carloslancha**

### CODE REVIEW

**Comment by carloslancha** [comment]
ci:test:relevant

**Comment by dsanz** [comment]
ci:help

**Comment by dsanz** [comment]
ci:test:echo

**Comment by dsanz** [comment]
ci:test:echo-acceptance

**Comment by dsanz** [comment]
ci:test:lima-acceptance

**Comment by dsanz** [comment]
ci:test:roles

**Comment by dsanz** [comment]
ci:test:users

**Comment by dsanz** [comment]
ci:test:depot

**Comment by dsanz** [comment]
@mateusralv could you please help @carloslancha to understand if the failing tests I launched yesterday are related to the info icon position change? Thank you in advance

**Comment by mateusralv** [comment]
Hi @carloslancha @dsanz Sure! I'm on it 🕵🏽

**Comment by mateusralv** [comment]
Hi @carloslancha @dsanz Sure! I'm on it 🕵🏽

**Comment by mateusralv** [comment]
Weird 🤔 The relevant ran only 73 tests, I will run it again while analyzing the other routines.

**Comment by mateusralv** [comment]
Weird 🤔 The relevant ran only 73 tests, I will run it again while analyzing the other routines.

**Comment by mateusralv** [comment]
Hi @carloslancha and @dsanz took a look at all the routines and here’s what I found: 

[Testray comparison to ci:test:depot](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1677617888520&testrayRunIdA=2211014902&testrayRunIdB=2211465783) 🟢 

[Testray comparison to ci:test:lima-acceptance ](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1677618112657&testrayRunIdA=2211014902&testrayRunIdB=2211505820) 🟢 

[Testray comparison to ci:test:roles](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1677618206284&testrayRunIdA=2211014902&testrayRunIdB=2210947232) 🟢 

[Testray comparison to ci:test:users ](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1677618293835&testrayRunIdA=2211014902&testrayRunIdB=2211118586) 🟢 

[Testray comparison to ci:test:echo-acceptance](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1677618012784&testrayRunIdA=2211014902&testrayRunIdB=2211690934) 🟠 

Has a unique failure in the test: 
`com.liferay.commerce.machine.learning.recommendation.info.collection.provider.test.ProductContentCommerceMLRecommendationRelatedInfoItemCollectionProv`
But it does not seem related. Could you take a look? 

I asked in the CI channel why the relevant is returning few tests, but it is expected because no modifications were made in various files. See this [thread](https://liferay.slack.com/archives/CL3TWSMHQ/p1677616527946129)

**Comment by carloslancha** [comment]
@mateusralv we only changed the position of a button so if the failure is not in a poshi test where it doesn't find the element in the dom it shouldn't be related. Thanks!

**Comment by carloslancha** [comment]
ci:forward

**Comment by carloslancha** [comment]
ci:forward:force

**Pull request closed without merging**
