### PR TITLE
[TS] LPS-172852 Prevent widget title gets saved without clicking on '✓' icon.

### PR DESCRIPTION
**Pull request by thienquach87**
Hi Team,

Here is the PR for fixing the [LPS-172852](https://issues.liferay.com/browse/LPS-172852) / [LPP-47667](https://issues.liferay.com/browse/LPP-47667). [The original PR](https://github.com/thienquach87/liferay-portal/pull/25) was passed my review. Please help review and leave your comments.
#cc @locpham97

Thanks,
Thien

### CODE REVIEW

**Comment by deborasoliveira** [comment]
I'm taking a look at it 🧐

**Comment by deborasoliveira** [comment]
I'll have to continue the analysis tomorrow 👍🏽

**Comment by locpham97** [comment]
Thanks, @deborasoliveira for your help.

**Comment by deborasoliveira** [comment]
Hello @locpham97! I've analyzed the failures through this [comparison](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=2&testrayRunIdB=2163627637&testrayRunIdA=2164281093&statusB=3) and they look unrelated to your PR.
If no other dev review is needed, you can manually forward it.

**Comment by anishq21** [comment]
Hi @thienquach87,

Could you please let me know if there is anything remaining on this PR? Just following up here as @locpham97 is on PTO.

**Comment by rolandpakai** [comment]
ci:forward

**Comment by rolandpakai** [comment]
ci:forward

**Comment by rolandpakai** [comment]
Manually forwarded to: https://github.com/brianchandotcom/liferay-portal/pull/129152

**Comment by rolandpakai** [comment]
ci:close

**Pull request closed without merging**
