### PR TITLE
LPS-149427 Updates components that use ClayTreeView to use the new default properties

### PR DESCRIPTION
**Pull request by matuzalemsteles**
This change is due to the introduction of new `default` properties that was implemented in PR https://github.com/liferay/clay/pull/4727 according to feedback so it doesn't get confused when the property is operating as default and when it is operating as controlled.

I only needed to update in some use cases where the state of `items` was not being controlled, the other cases implement the controlled component.

To test these cases you need to add the feature flag:

- Create a new file named `com.liferay.frontend.js.components.web.internal.configuration.FFFrontendJSComponentsConfiguration.config` and with the content `enableClayTreeView="true"`
- Add to folder `osgi/configs`

### CODE REVIEW

**Comment by matuzalemsteles** [comment]
ci:test:sf

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Review by diegonvs — APPROVED** [review]

**Comment by susanchen3** [comment]
Taking a look! :)

**Comment by susanchen3** [comment]
Based on the most recent [relevant run](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=2&testrayRunIdB=1637324055&testrayRunIdA=1637374539&statusB=3)

- com.liferay.headless.delivery.resource.v1_0.test.DocumentResourceTest
- LocalFile.MBNotifications#CanViewWebsiteNotificationForUpdatedThreadInCategory
- LocalFile.MBNotifications#NoWebsiteNotificationAppearsForNewThreadInCategory
- LocalFile.MBNotifications#NoWebsiteNotificationAppearsForUpdatedThreadInCategory

are unique to this PR, but I think they are flukes and unrelated to your changes. They didn't fail the on previous `ci:test:relevant` run. 

Looks good to forward to me! :heavy_check_mark:

**Comment by john-co** [comment]
Thanks @susanchen3! I can manually forward it

**Comment by john-co** [comment]
manually forwarded to https://github.com/brianchandotcom/liferay-portal/pull/114820

**Pull request closed without merging**
