### PR TITLE
LPS-200853 Add jsPDF JavaScript to Portal

### PR DESCRIPTION
**Pull request by thektan**
https://liferay.atlassian.net/browse/LPS-200853

@bryceosterhaus originally sent: https://github.com/cgmonte/liferay-portal/pull/100

I just removed the `object-web` changes. I thought we could add these in so they could move forward with their story to add their feature https://liferay.atlassian.net/browse/LPS-201526. Even though the icons don't render (waiting for https://github.com/bubkoo/html-to-image/pull/427 to be merged) and the only workaround is to use background images, at least that can be used for now.

### CODE REVIEW

**Comment by thektan** [comment]
ci:test:relevant

**Review by bryceosterhaus — APPROVED** [review]
LGTM!

**Comment by mateusralv** [comment]
ci:test:relevant

**Comment by thektan** [comment]
@mateusralv If failures are not related, can you help forward this? Otherwise I can take a look when I return on Monday or someone else on the team can if they have bandwidth. Thanks!

**Comment by mateusralv** [comment]
Hey @thektan The failures are not related. 

[Testray Comparison](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1700746984281&testrayRunIdA=2463775544&testrayRunIdB=2463933016)

**Comment by mateusralv** [comment]
ci:forward:force

**Pull request closed without merging**
