### PR TITLE
LPS-117488 Consolidate Modal Selection UX

### PR DESCRIPTION
**Pull request by jbalsas**
Okay... so this is maybe an over-reach to fix [Flickering styles in modals](https://issues.liferay.com/browse/LPS-117488). I had this cooking for a while on the side... I'm just sad @markocikos isn't around to greenlight this 😢 

**This PR:**
- Creates a new `openSelectionModal` utility on top of our current `openModal` to simplify and consolidate item selection
    - As a first step, this simplifies `openModal` and decouples it from the `selection` logic
- Replaces existing usages of `openModal` + `selectEventName` (since the selection logic lives now up in the chain)
- Replaces usages of `ItemSelectorDialog` with `openSelectionModal` (both single and multiple selection)
    - As a side-effect, we remove completely the `ItemSelectorDialog` component and the weird 3-step invocation pattern
- Replaces usages of `Liferay.Util.selectEntity` with `openSelectionModal`
    - As a side effect, this should allow us to also deprecate this API

**Benefits:**
- Consistent item selection throughout DXP. This was a key item in `7.2` that we're in risk of regressing in `7.3`, which is what really pushed me to try to get it in.
- Reduced number of patterns to do the same thing (easier to document and enforce in the future)

**How to test it:**
After this change, this can be tested almost everywhere we "select" things, though the ones in the issue report should be enough to see the changes:

- Go to Global Menu > Content Dashboard
- Filter by Author or Subtype

- Go to Web Content
- Create a Web Content
- Select a display page template

After the change, the selection would be achieved through a Clay Modal (animation and everything) and styles won't flicker since all the css classes are in place and content is not shown until the iframe is done loading.

Going to mention some teams here today and personally tomorrow so we can validate this, but ideally we should push this asap to have enough time to stabilize.
- Hey @liferay-lima, hope you're okay with us removing the `ItemSelectorDialog` component. I know we discussed in the past where this should live, so maybe this makes sense to you? We're still using all the `ItemSelector` infra, just opening them through other means.
- Hey @bryceosterhaus, it was here where I "noticed" the iframe performance regression I mentioned at [Improve Iframe loading perceived performance](https://issues.liferay.com/browse/LPS-118805). This could be just subjective, but while I was changing modals and checking they worked, they felt slower to me. Could you maybe identify some modals here and try before and after to get a feeling for yourself?
- Hey @john-co, @PablitoBonito, I ran a couple of test suites at https://github.com/jbalsas/liferay-portal/pull/2226#issuecomment-674895777. Most of the failures are apparently just iframe locators. Could we prioritize this in a way that we can get this **merged asap**?

Thanks everyone! 🤞 

/cc @matuzalemsteles, @diegonvs, @brunobasto, could you give this a try, check test failures and see how safe this feels? :)

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:test:sf

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by john-co** [comment]
Just started reviewing :)

**Comment by john-co** [comment]
ci:test:bundle

**Comment by matuzalemsteles** [comment]
So I did some tests and I have observed some cases. Probably related to this change, still not being able to trace the real problem.

I'm watching Modal break when it opens to select Tags or anything categorized when creating Web Content, JavaScript breaks when opening [SelectCategory.es.js](https://github.com/liferay/liferay-portal/blob/master/modules/apps/asset/asset-categories-selector-web/src/main/resources/META-INF/resources/js/SelectCategory.es.js#L73-L97), it tries to get the dialog using the id, but it doesn't seem to exist, maybe we still need to pass the id to Modal?

**Comment by john-co** [comment]
ci:test:relevant

**Comment by john-co** [comment]
I was able to fix the majority of tests failing on Click.waitForMenuToggleJSClick()

However there are some other tests failing to that have an iframe within an iframe ie: LocalFile.KnowledgebaseUsecase_DeleteConfiguredKBFolder. I tried to selectFrame and target the 2nd iframe but my attempts failed. The test says the element is not present: `Element is not present at "//*[contains(@class,'modal-dialog') and contains(.,'Select Entry')]//*[contains(@class,'modal-body')]/iframe"`

HowToSelectFrame2ndIframe

Here's what I have so far: https://github.com/john-co/liferay-portal/pull/328

cc/ @zhangyan0701 @kenjiheigel do you have any ideas on how to get past this?

**Comment by john-co** [comment]
I noticed a regression as well, the contents within the modal are hidden behind the footer
ModalScroll_HidesContent

Different from current master:
image

**Comment by kenjiheigel** [comment]
@john-co, haven't dealt with iframes in a while, but maybe try this... So on that page, we have iframe 1 & iframe 2. You'd do something like this...
1. Select iframe 1 and interact with it to bring up iframe 2
2. Select iframe 2 and interact with it
3. Select iframe top to reset iframe locators stored in Poshi's WebDriver instance
4. Select iframe 1 to interact with the elements in there. 

I think the key is trying to use `SelectFrame(locator1="relative=top")` before selecting another iframe. You might even need to do it before selecting iframe 2.

**Comment by jbalsas** [comment]
Hey @john-co, we already dealt with this in the past. The problem is that the iframes are now inside the other iframe rather than outside in the `body`. So, the selector needs to look for it inside the first iframe and not directly in the document.

**Comment by ambrinchaudhary** [comment]
Hey @jbalsas! I like the change! It's good to have all the modals unified in portal. 

However, I’m a bit concern about the multiple configuration. In the past, all modals had a footer with the save/cancel buttons. Then we added this “single select” pattern, and [to avoid any breaking changes](https://github.com/liferay/liferay-portal/commit/2c6174c9aa4aa881e33a5ac8b9a0d2e1cb645fc6) for the customers, we decided that ”multiple” had to be the default configuration, and when needed and possible, singleSelect must be configured. 
With this change, now I think customers may have wrong dialogs and had to go to each multiple modal to configure that "multiple" attribute… what do you think?

**Comment by jbalsas** [comment]
> With this change, now I think customers may have wrong dialogs and had to go to each multiple modal to configure that "multiple" attribute… what do you think?

Hey @ambrinchaudhary, this doesn't change any of the existing APIs. It adds a new one that has different semantics. **Customers won't be affected unless they migrate to the new API**, in which case, they should swap the values as expected and documented.

**Comment by ambrinchaudhary** [comment]
@jbalsas Not sure about what is exactly considered an API here, but `ItemSelectorDialog.es.js` is now deleted. Any customer using that module will have to replace it to `openSelectModal`, just like you did. Isn't that a breaking change? And besides that, has to configure "multiple" attribute instead of "singleSelect"

**Comment by jbalsas** [comment]
> @jbalsas Not sure about what is exactly considered an API here, but ItemSelectorDialog.es.js is now deleted. Any customer using that module will have to replace it to openSelectModal, just like you did. Isn't that a breaking change? And besides that, has to configure "multiple" attribute instead of "singleSelect"

`ItemSelectorDialog` was not present in the previous version, so only early adopters of CE versions would've been able to migrate from the old module to the new one, so I think it would be okay to simply remove it. Customers upgrading would need to do the same process as if they were upgrading from the old AUI module. Understand the new component and make the code changes needed.

That being said... I just found out that `CategoriesSelector` is doing very nasty things with the modal dialogs... so I'm going to be forced to keep the class around at least for a little bit longer, which is pretty unfortunate, if you ask me 😢

**Comment by wincent** [comment]
> That being said... I just found out that `CategoriesSelector` is doing very nasty things with the modal dialogs... so I'm going to be forced to keep the class around at least for a little bit longer, which is pretty unfortunate, if you ask me 😢

Can you rename and/or move it to make it more obviously "private"?

**Comment by jbalsas** [comment]
> Can you rename and/or move it to make it more obviously "private"?

We'll see... I'm going to try to get this through without `CategoriesSelector` and then see what else we can do...

**Comment by jbalsas** [comment]
Okay, seeing as tests weren't so promising, I've pushed the following:
- Revert of `asset-taglib` changes so Category Selection is still done through the old `ItemSelectorDialog` component
- When not present, pass `id` to the `iframe` equals to `selectEventName` to appease trying to locate those iframes by id. We could talk about this later to see if we want to force an explicit API rather than an implicit one like this.

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
Well... not much of an improvement here... 😢 

@john-co, please focus on this, see how far we can get with those tests. If we can't see the light before EOD tomorrow we'll likely need to pushback on this, which will make me super sad 😭

**Comment by john-co** [comment]
ci:test:bundle

**Comment by john-co** [comment]
ci:test:relevant

**Comment by john-co** [comment]
There's probably other tests with an iframe within an iframe that need to be updated. Will check the next `ci:test:relevant` results to better identify.

**Comment by john-co** [comment]
Comparison:
https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=3&testrayRunIdB=1261091824&testrayRunIdA=1261102557&statusB=2

There's seems to be more test fixes on other iframes within iframes, I wasn't able to go through and fix them all. @zhangyan0701, could you continue with this?

Also I was able to identify a regression with [SiteMemberships#AddMemberAssignSiteRole](https://testray.liferay.com/home/-/testray/case_results/1261126137) Clicking on Done button when assigning a user to Site Membership does nothing.

Peek 2020-08-18 17-03

**Comment by john-co** [comment]
[Test Fixes]
- various other tests that are failing on after selectFrameTop or with inner iframe.

- SelectFrameTop not working, may need to replace with selectFrame?:
SitetemplatesUsecase#SitesDynamicTemplateInheritance

- Seems like a bad path combined with possible SelectFrameTop not working? needs further investigation @cvanut, could you take a look?  AssetPublisherShowFullContent#AddAssetTypesViaAPAndAddRespectivePortletsToSamePage

[Regressions]
- Clicking Done on Site Membership does nothing:
SiteMemberships#AddMemberAssignSiteRole
Forms#AddFormToUserSiteAndViewNoDuplicates

[Unidentified possible Regressions] - I didn't get to investigate further
- AssetPublisherUseCase#AssetPublisherFilterAndOrderByFieldType
- WorkflowWiki#ApproveFrontPageUserEdit
- FormRules#ConfigureUserBelongsToRule
- Forms#SubmitFormWithUploadField

**Comment by john-co** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
Comparison:
https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=3&testrayRunIdB=1261091824&testrayRunIdA=1261199258&statusB=2

**[Regressions]**
**1. No results in Asset Publisher after enable Filter by Field and selecting a field in Select Structure Field iframe.**
- LocalFile.AssetPublisherUseCase#AssetPublisherFilterAndOrderByFieldType
No results in AP

**2. Clicking Data Definition name does nothing in Data Definitions iframe.**
- LocalFile.AssetPublisherShowFullContent#AddAssetTypesViaAPAndAddRespectivePortletsToSamePage
cannot select data defination

**3. Clicking Site Name does nothing in Select Site iframe.**
- LocalFile.AssetPublisherWithWebContent#ViewWebContentViaAPAsGuestWithViewPermission
- LocalFile.CPUsersandorganizations#EditUserSite
- LocalFile.SitetemplatesUsecase#SitesDynamicTemplateInheritance
select site

**4. Selecting folder in Select Folder iframe doesn't work when move Web Content.**
- LocalFile.WebContent#MoveWebContentToFolderTraining
- LocalFile.WebContentExportImport#MoveImportedWebContentArticlesToFolders
move web content

**5. Same as the regression in John's comment: Clicking Done on Site Membership does nothing.**
- LocalFile.WorkflowWiki#ApproveFrontPageUserEdit

**6. Clicking Choose button does nothing when assign role to user.**
- LocalFile.FormRules#ConfigureUserBelongsToRule
assigh role

**7. Upload file doesn't work in Form.**
- LocalFile.Forms#SubmitFormWithUploadField
upload file in form

[Should be flaky] - LocalFile.Forms#CreateUntitledForm

**Comment by zhangyan0701** [comment]
Send the Test Fix to @jbalsas :
https://github.com/jbalsas/liferay-portal/pull/2229

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by john-co** [comment]
my other previous commits that I pushed got deleted somehow...

**Comment by john-co** [comment]
force pushed previous commits on top. rerunning tests

**Comment by john-co** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
Nice! I'm going to go through the regressions now!

**Comment by jbalsas** [comment]
So... I figured out the cause for most of the regressions which could be categorized in:
- Removal the `SelectEntityHandler` instances. This works well for all places with new modals, but some are left with old ones that still require them. Since **they are harmless when present, I simply reverted** the removal so everything should work regardless of the changes
- Delegation of events. In the cases where the modal has navigation, events were not properly set after navigation. We're using a basic delegation system now on the modal container so that it sticks throughout navigations
- Proper `this` resolution in `onSelect` callbacks. Because in several places I used the `onSelect() {}` syntax, usages of `this` inside them would cause errors. For simplicity, I converted them all to arrow functions and we can do a further exploration into simplifying the pattern in the future.

That should cover most of the regressions, thanks so much @zhangyan0701 for the analysis and the lovely bunny in your screen!!

Screen Shot 2020-08-19 at 18 16 56

@john-co, as you know I nuked your fixes again 😭 hope you can forgive me!

forgiveness

**Comment by john-co** [comment]
ci:test:relevant

**Comment by john-co** [comment]
ci:test:sf

**Comment by jbalsas** [comment]
Getting closer!! 💪

**Comment by jbalsas** [comment]
Ok, so:
- I've pulled to make sure I don't delete the test fixes again 😉 
- Rebased
- Fixed the issue with DM-Move-Folder... hopefully without breaking anything else 🤞 
- Reverted all changes in `dynamic-data-mapping-form-field-type` since I was not sure I could get those to work. Hopefully that will take care of the rest of unique failures since now the code remains unchanged

Let's see how this looks!

**Comment by jbalsas** [comment]
ci:test:sf

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
ci:test:bundle

**Comment by zhangyan0701** [comment]
https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=3&testrayRunIdB=1261867116&testrayRunIdA=1261819920&statusB=2

**Only one related test failure:**

No results in Asset Publisher after enable Filter by Field and selecting a field in Select Structure Field iframe.
- LocalFile.AssetPublisherUseCase#AssetPublisherFilterAndOrderByFieldType
No results in AP

**Comment by zhangyan0701** [comment]
ci:test:sf

**Comment by zhangyan0701** [comment]
Force pushed [commit ](https://github.com/liferay-frontend/liferay-portal/pull/263/commits/6d3404b357d378552d21a1d0d5ba2916c59ad8f6)to fix the SF failure.

**Comment by jbalsas** [comment]
Okay... so the `ddm_structure_field` selection was sporting a particular async item selection mechanism that entirely relied on events and me eagerly attaching listeners to the `.selector-button` items broke that rule.

Temporarily adding a way out of this via API so we can land this and then take some additional time to re-evaluate 🤞

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
Well... failures look like connectivity issues... going to retry once again and if all looks the same then I guess I'll manually forward...

@PablitoBonito, @zhangyan0701, @john-co, raise any concerns now or forever keep quiet! 😂

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
Ok, so 2 out of 2 means

shipit

**Comment by john-co** [comment]
ci:test

**Comment by john-co** [comment]
Running a full `ci:test` since I have a feeling other tests will need to be updated due to the modal within a modal. If this needs to be merged asap, then imo the other test fixes can be worked on post merge since we have `ci:test:relevant` passing.

**Comment by jbalsas** [comment]
Hey @john-co, I feel the sooner the better, so we have enough time to catch anything the tests miss and adjust if necessary.

That being said, we don't want to be opening a big hole in tests right now, so let's see how the full run goes. I'd suggest that depending on the result we:
- Forward if additionl test fixes neede aren't too many
- Give us **one** extra day if the amount of fixes is big to fix as many as possible and then forward eod tomorrow

Does that make sense?

**Comment by john-co** [comment]
makes sense :smiley: :+1:

**Comment by jbalsas** [comment]
This sounds reasonable... one possible real issue or test fix. I'll analyze tomorrow, but going to forward for today in the off-chance Brian still merges it before EOD.

**Comment by jbalsas** [comment]
ci:forward

**Pull request closed without merging**
