### PR TITLE
LPS-XXXXX Adds more editors to ckeditor-sample-web

### PR DESCRIPTION
**Pull request by diegonvs**
It adds more editors to ckeditor-sample-web

https://user-images.githubusercontent.com/7663513/151631193-3adfdefe-34d9-4787-8073-106817828abc.mov

**Why?**

I would check/test more editors when changing something in a Editor React component or internally on CKEditor(our DXP plugins or our patches under liferay-ckeditor)

It will reduce the number of issues like this one: https://github.com/liferay-frontend/liferay-portal/pull/1871

### CODE REVIEW

**Comment by markocikos** [comment]
@diegonvs This PR is stuck for a long time. Can we close it, to reduce the noise on the pulls page? The task will still eventually be valuable to do, maybe as a part of the next BE epic?

**Comment by diegonvs** [comment]
Makes sense. Can I create a ticket containing the purpose of this PR on Page Editor's BE Migration epic?

**Comment by markocikos** [comment]
Sure! Maybe, at some point, we can have a small dedicated epic for CKE sample improvements, like [we have for FDS](https://issues.liferay.com/browse/LPS-150042).

**Comment by diegonvs** [comment]
Created https://issues.liferay.com/browse/LPS-151341

**Pull request closed without merging**
