### PR TITLE
LPS-165996 Modified progress bar visibility to hidden !important.

### PR DESCRIPTION
**Pull request by fortunatomaldonado**
FWD: https://github.com/fortunatomaldonado/liferay-portal/pull/58

Please let me know if there are any questions or comments about this.
Thank you!

> [LPS-165996](https://issues.liferay.com/browse/LPS-165996) Modified progress bar visibility to hidden !important. This fixes an issue where the hidden property was overridden which caused the bar to show up over all other elements on the page.

### CODE REVIEW

**Comment by pat270** [comment]
Adding `!important` would make `.lfr-item-viewer.uploading > .progress-container` never visible (https://github.com/liferay-frontend/liferay-portal/pull/2820/files#diff-52b3e0c85335ffd6792adf937634de1eff66cd30022d2a38078ca73fc1b28417L7-L9). If `.lfr-item-viewer.uploading > .progress-container` isn't a valid style anymore, wouldn't it be better to remove that rule-set?

**Comment by fortunatomaldonado** [comment]
@SelenaAungst, I apologize for losing track of this ticket. When you have time, can you take a look at what Patrick mentioned?

**Comment by SelenaAungst** [comment]
Hi @pat270, I apologize for my delayed response! For your suggestion, do you mean deleting that whole section?

**Comment by pat270** [comment]
@SelenaAungst Sorry I totally missed this. Yes, you should remove the section if `.lfr-item-viewer .progress-container` is no longer a valid element (e.g., if they changed the upload indicator to something else). From the issue screenshot, it looks like the progress bar indicator is broken and just needs to be fixed, but I haven't looked at it that closely.

**Comment by SelenaAungst** [comment]
Hi @pat270, no worries! Thanks for getting back to me on this. I will test with removing this section and see if this still fixes the problem or if the progress bar indicator is just broken.

**Comment by SelenaAungst** [comment]
Hi @pat270,
I tested this on U63 and found that this issue is no longer present. Thanks for your help on this!

**Pull request closed without merging**
