### PR TITLE
LPS-181353 | Add FDSViews automation tests

### PR DESCRIPTION
**Pull request by alexmds2004**
**Description**
Add FDSViews Tests
Automation for FDSViews#CanCreateView
Automation for FDSViews#CanAssertNameIsRequired
Automation for FDSViews#CanAssertNameFieldIsTrunkedIfExceedCharacters
Automation for FDSViews#CanUseSpecialCharactersInNameField
Automation for FDSViews#CanSearchViewByDescription

Tests Links 
https://issues.liferay.com/browse/LPS-181339
https://issues.liferay.com/browse/LPS-181340
https://issues.liferay.com/browse/LPS-181347
https://issues.liferay.com/browse/LPS-181350
https://issues.liferay.com/browse/LPS-181353

---

Description:
Added FDSViews tests 

Linked tests with respective tickets:
[FDSViews#CanEditOrDeleteView](https://issues.liferay.com/browse/LPS-181344)
[FDSViews#AssertNumberOfCharactersInDescriptionField
](https://issues.liferay.com/browse/LPS-181349)[FDSViews#CanEditView](https://issues.liferay.com/browse/LPS-181343)
[(FDSViews#CanCreateMultipleViews - already checked)
](https://issues.liferay.com/browse/LPS-181354)

### CODE REVIEW

**Comment by alexmds2004** [comment]
ci:test:sf

**Comment by eltonccdantas** [comment]
Hey @alexmds2004 , please add a description, update the title of your pull request and resolve its conflict.

**Comment by alexmds2004** [comment]
ci:test:sf

**Comment by alexmds2004** [comment]
ci:test:sf

**Comment by alexmds2004** [comment]
ci:test:sf

**Comment by alexmds2004** [comment]
ci:test:sf

**Comment by alexmds2004** [comment]
ci:test:frontend

**Comment by mateusralv** [comment]
ci:test:sf

**Comment by mateusralv** [comment]
the failures not seems related to this PR, the failures seem to be related to data from other tests 🤔

**Comment by mateusralv** [comment]
ci:forward

**Pull request closed without merging**
