### PR TITLE
LPS-122999 Update @liferay/npm-scripts to v34.0.1

### PR DESCRIPTION
**Pull request by wincent**
A small update to incorporate a bugfix for our storybook integration.

[Release notes](https://github.com/liferay/liferay-frontend-projects/releases/tag/npm-scripts%2Fv34.0.1).

### CODE REVIEW

**Comment by wincent** [comment]
cc @oliv-yu

Will forward this once we see CI green.

**Comment by wincent** [comment]
ci:test:sf

**Comment by wincent** [comment]
ci:test:relevant

**Comment by wincent** [comment]
ci:forward

**Comment by jbalsas** [comment]
I was just coming to do this!!

hanshotfirst

**Comment by wincent** [comment]
Totally worth it for the gif.

would-again

**Pull request closed without merging**
