### PR TITLE
LPS-152326 Setting the current Liferay context for CKEditor

### PR DESCRIPTION
**Pull request by rijema**
Hi Team,

Here is the link for the issue: https://issues.liferay.com/browse/LPS-152326

I sent to the forms team but they told me to resent here.

Thanks in advance,
Richard.

### CODE REVIEW

**Comment by rijema** [comment]
ci:test:sf

**Comment by diegonvs** [comment]
Hey @rijema, could you do the same thing you done in those two files on https://github.com/liferay/liferay-portal/blob/9b4258eb305db9209d45f8542f2636b32d70e743/modules/apps/frontend-editor/frontend-editor-ckeditor-web/src/main/resources/META-INF/resources/editor/BaseEditor.js#L111 as well? For completely fix on current master :p

Thanks 😘

**Comment by rijema** [comment]
Hi @diegonvs , sorry for the delay. But I just added the changes you requested. Let me know if I have to open another PR due the force-push. Thank you for the review 🤩

**Comment by rijema** [comment]
ci:test:sf

**Comment by rijema** [comment]
ci:test:relevant

**Review by diegonvs — APPROVED** [review]
image

LGTM :)

**Comment by diegonvs** [comment]
Hey @rijema, two things:

1. Could you validate(maybe improve the description) the reproduction steps for a changed pathContext? I followed the ones provided by the ticket my tomcat crashed

I've followed this one:

* Change the ROOT folder name (under {LIFERAY_HOME}/tomcat-9.0.17/webapps/ROOT) to 'myportal'.
* Change the ROOT.xml file name (under {LIFERAY_HOME}/tomcat-9.0.17/conf/Catalina/localhost/) to 'myportal.xml'.
* Change the ROOT to 'myportal' in the tomcat-9.0.53\conf\catalina.properties file
* Clear temp and work directories under TOMCAT_HOME.
* Start the server and log in as admin
From: https://issues.liferay.com/browse/LPS-152608

and everything went well with the pathContext change :)

2. You can improve your PR description by following one of PR templates on web, an interesting one can be found at this [link](https://www.pullrequest.com/blog/writing-a-great-pull-request-description/)

```
## What?
## Why?
## How?
## Testing?
## Screenshots (optional)
## Anything Else?
```

**Comment by diegonvs** [comment]
ci:forward

**Pull request closed without merging**
