### PR TITLE
LPS-147839 | Assert the view button has a double caret icon and has a tooltip message when hovered over it

### PR DESCRIPTION
**Pull request by susanchen3**
**Background**
Create automated tests for the management toolbar

**Test Plan(s)**

- Product Menu > Content & Data > Web Content
- Assert the view button has a double caret icon
-
- Product Menu > Content & Data > Web Content
- Hover over the view button
- Assert the view button has 'Show View Options' tooltip message

**JIRA Ticket(s):**
https://issues.liferay.com/browse/LPS-147839
https://issues.liferay.com/browse/LPS-147844

### CODE REVIEW

**Comment by susanchen3** [comment]
ci:test:frontend:nocompile

**Comment by john-co** [comment]
Just started reviewing :)

**Review by john-co — COMMENTED** [review]
Looks good overall. However, would the test also work on our Clay Sample Portlet instead of using Web Content? I'd like to ideally use the sample portlets we have as much as possible and not depend on product team usages for basic checks.

**Review by Esther-OC — COMMENTED** [review]
Looks good to me too!

I also agree with @john-co, if it is possible to use sample portlet it will avoid future changes and the test will be valid for different product needs, in my opinion.

**Comment by susanchen3** [comment]
Yeah I can make the change to use the Clay Sample Portlet :), but for tests that require me to order something would I go back to using Web Content? Ex. [LPS-147851](https://issues.liferay.com/browse/LPS-147851)

cc: @john-co @Esther-OC

**Comment by susanchen3** [comment]
ci:test:sf

**Comment by susanchen3** [comment]
Also for [LPS-147849](https://issues.liferay.com/browse/LPS-147849), I noticed that 'Filter and Order' is still in the same dropdown on the Clay Sample Portlet
image
but they are rendered independent on Web Content 
image

**Comment by john-co** [comment]
> Also for [LPS-147849](https://issues.liferay.com/browse/LPS-147849), I noticed that 'Filter and Order' is still in the same dropdown on the Clay Sample Portlet

cc/ @tinycarol , is there something we need to update on the clay sample portlet to display the new management toolbar?

**Comment by john-co** [comment]
> Yeah I can make the change to use the Clay Sample Portlet :), but for tests that require me to order something would I go back to using Web Content? Ex. [LPS-147851](https://issues.liferay.com/browse/LPS-147851)

cc/ @tinycarol , is there a way we can mock data as well for our clay sample portlet so we can test out the filter order buttons? Or have some dummy assets? 

I wonder if the sample frontend dataset portlet can enable the new management toolbar. It already has some dummy assets but I'm not sure what version Management Toolbar it uses and if we'd run into the same issue that @susanchen3 is seeing on Clay Sample Portlet.

**Comment by john-co** [comment]
Our last resort if we can't get a sample portlet working to test those features, is to use Message Boards or a less worked on product usecase (not Web Content b/c it's historically been less stable from high development activity). If we can't get sample portlet configured properly sometime next week then I'd lean towards just using Message Boards for now.

**Comment by tinycarol** [comment]
Hi @john-co!
> cc/ @tinycarol , is there something we need to update on the clay sample portlet to display the new management toolbar?

From what I can see [in the sample's code](https://github.com/liferay-frontend/liferay-portal/blob/master/modules/apps/frontend-taglib/frontend-taglib-clay-sample-web/src/main/resources/META-INF/resources/partials/management_toolbars.jsp), we are not passing the `orderDropdownItems` attribute, and [in the display context](https://github.com/liferay-frontend/liferay-portal/blob/master/modules/apps/frontend-taglib/frontend-taglib-clay-sample-web/src/main/java/com/liferay/frontend/taglib/clay/sample/web/internal/display/context/ClaySampleManagementToolbarsDisplayContext.java) we are not overriding that value, so it's empty. When the MT doesn't receive this prop, it falls back to the previous behaviour (showing only the filters dropdown and the order toggle button). We should update it to add this other prop. Should I do it or can you take care of it?

>cc/ @tinycarol , is there a way we can mock data as well for our clay sample portlet so we can test out the filter order buttons? Or have some dummy assets?

That should be possible IMO, but I don't know if we should do this in this sample since it will involve using other components too, right? Maybe @carloslancha has a better idea on this.

>I wonder if the sample frontend dataset portlet can enable the new management toolbar. It already has some dummy assets but I'm not sure what version Management Toolbar it uses and if we'd run into the same issue that @susanchen3 is seeing on Clay Sample Portlet (Filter and Order not split).

I thin FDS uses a 100% custom Management Toolbar, so it doesn't have the UX improvements.

**Comment by susanchen3** [comment]
Hi @tinycarol! 

Do you mind updating the Management Toolbar? John is on PTO for the rest of the week. Thank you! :)

**Comment by tinycarol** [comment]
Hi @susanchen3! Sure, I added the necessary changes in https://github.com/liferay-frontend/liferay-portal/pull/1964. Let me know if I can help with anything else :)

**Comment by susanchen3** [comment]
gonna forward this for now because these tests don't need the new changes in Carol's PR :sweat_smile:

**Comment by susanchen3** [comment]
ci:forward

**Comment by susanchen3** [comment]
ci:forward

**Pull request closed without merging**
