### PR TITLE
LPS-195026 Test Fix Stabilizing fleaky tests

### PR DESCRIPTION
**Pull request by JerryAdrianoo**
**Description:**
- Increasing more information in API call, property inside the fleaky tests and changing old macros.

**Jira Ticket:**
https://liferay.atlassian.net/browse/LPS-195026

### CODE REVIEW

**Comment by JerryAdrianoo** [comment]
ci:test:frontend-data-set

**Comment by JerryAdrianoo** [comment]
ci:test:frontend-data-set

**Comment by JerryAdrianoo** [comment]
ci:stop

**Comment by JerryAdrianoo** [comment]
ci:test:stop

**Comment by JerryAdrianoo** [comment]
ci:test:frontend-data-set

**Comment by JerryAdrianoo** [comment]
ci:test:frontend-data-set

**Comment by JerryAdrianoo** [comment]
ci:test:frontend-data-set

**Comment by JerryAdrianoo** [comment]
Hey, @CarlosBrichete all the fleaky tests that contains errors in [items] have been resolved.
These failures are not related to the purpose of this ticket!

**Review by CarlosBrichete — APPROVED** [review]
LGMT :)

**Comment by JerryAdrianoo** [comment]
ci:forward

**Pull request closed without merging**
