### PR TITLE
LPS-154638 | master

### PR DESCRIPTION
**Pull request by WYZ-Issac**
**Background**
Create automated tests for Walkthrough component.

**Test Plan**
Given: frontend-js-components-sample-web deployed to test page
And Given: Navigate to Walkable tab on sample portlet
And Given: Click hotspot element
When: Click close icon
Then: hotspot element is present

**JIRA Ticket:**
https://issues.liferay.com/browse/LPS-154638

### CODE REVIEW

**Comment by WYZ-Issac** [comment]
ci:test:frontend:nocompile

**Comment by WYZ-Issac** [comment]
ci:test:sf

**Comment by WYZ-Issac** [comment]
ci:test:relevant

**Review by susanchen3 — APPROVED** [review]
Looks good to me! Thanks Issac! :tada:

**Comment by susanchen3** [comment]
ci:forward

**Pull request closed without merging**
