### PR TITLE
LPS-130705 and LPS-130115 Add pending threads, messages and comments to questions

### PR DESCRIPTION
**Pull request by javierdearcos**
This PR expose the status of threads and messages through the APIs and return non approved threads and messages when:
- I own the resource
- I am a content reviewer
(same logic we use in the GUI)

Add label in questions to indicate that a thread, message or comment have a non approved status

### CODE REVIEW

**Comment by javierdearcos** [comment]
ci:test:relevant

**Comment by javierdearcos** [comment]
I'll look forward for the test results and if everything is correct and you agree I can send the PR directly to Brian, because Source Formatter is complaining again about the externalReferenceCode path parameter order...

**Comment by javierdearcos** [comment]
The failed tests are the ones related to sort. That is because I ignored the sorts attribute when filter and search are null, to be able to make it work in Questions but that is incorrect... We need to implement the sorts again the database, what I think it could be possible as the QueryDefinition has an OrderByComparator argument, or change the call in the Questions app end to not use sorts

**Comment by javierdearcos** [comment]
Ignoring the MessageBoardMessage sort tests for now. On Monday I will try to implement OrderByComparator<MBMessage> for all sortable entityFields to allow sorting against the database

**Comment by javierdearcos** [comment]
ci:test:relevant

**Comment by nhpatt** [comment]
This is getting messages that are also in the trash. Because childMessages ends up calling:

```
	if (queryDefinition.getOwnerUserId() > 0) {
				queryPos.add(queryDefinition.getOwnerUserId());

				if (queryDefinition.isIncludeOwner()) {
					queryPos.add(WorkflowConstants.STATUS_IN_TRASH);
				}
			}
```

**Comment by javierdearcos** [comment]
Took the `findByThreadId` as example and I supposed that it was included as negative to not include trash items. The result query at least is like that
```
SELECT {MBMessage.*} FROM MBMessage WHERE (((NOT ?) AND (MBMessage.parentMessageId = ?)) OR ((?) AND (MBMessage.treePath LIKE ?))) AND (MBMessage.status != ?  OR  (MBMessage.userId = ? AND MBMessage.status != ?))
```

**Comment by nhpatt** [comment]
ci:forward

**Comment by nhpatt** [comment]
Yeah, I see. But there are a few issues, a conflict with Brian's code, you can not reply to pending messages but questions is allowing it and failing silently and you are not using `OrderByComparator` anywhere (the persistence does not use it internally, so you fill it for nothing) and the default ordering in questions is failing.

But let's try to get it merged and we'll solve it later.

**Comment by nhpatt** [comment]
ci:test:sf

**Review by nhpatt — APPROVED** [review]

**Comment by javierdearcos** [comment]
ci:forward

**Comment by nhpatt** [comment]
ci:forward

**Comment by javierdearcos** [comment]
ci:stop

**Comment by javierdearcos** [comment]
ci:test:sf

**Comment by javierdearcos** [comment]
I've added the logic of sorting against the database for some of the message fields and removed the ignored tests commit

**Comment by javierdearcos** [comment]
ci:forward

**Comment by nhpatt** [comment]
ci:forward

**Pull request closed without merging**
