### PR TITLE
LPS-155079 Use different filterable function in localized String fields to allow "contains" filter type

### PR DESCRIPTION
**Pull request by ccorreagg**
This PR contains the code to allow passing a different function to filter a field for the String field type different from the function passed to Sort them.

For the cases than a field is localizable, the document inserted into ElasticSearch contains a field for each localization, whose sorteable field is of the type `icu_collation_keyword`, for example for Journal Articles (see the field `title` and the different localizations):

```
      {
          [...]
          "title_en_US" : "jfehlglm",
          [...]
          "urlTitle_en_US" : "k5yidght",
          [...]
          "latest" : "true",
          "entryClassName" : "com.liferay.journal.model.JournalArticle",
          "roleId" : "20107",
          "articleId" : "44062",
          "contentLength_en_US_sortable" : 10,
          "userName" : "test test",
          "userId" : "20126",
          "urlTitle_en_US_String_sortable" : "k5yidght",
          "assetEntryId" : "44068",
          "localized_title_zh_CN" : "jfehlglm",
          "localized_title_zh_CN_sortable" : "jfehlglm",
          "localized_title_es_ES" : "jfehlglm",
          "localized_title_es_ES_sortable" : "jfehlglm",
          "localized_title_sv_SE" : "jfehlglm",
          "localized_title_sv_SE_sortable" : "jfehlglm",
          "localized_title_ja_JP" : "jfehlglm",
          "localized_title_ja_JP_sortable" : "jfehlglm",
          "localized_title_nl_NL" : "jfehlglm",
          "localized_title_nl_NL_sortable" : "jfehlglm",
          "localized_title_hu_HU" : "jfehlglm",
          "localized_title_hu_HU_sortable" : "jfehlglm",
          "localized_title_ar_SA" : "jfehlglm",
          "localized_title_ar_SA_sortable" : "jfehlglm",
          "localized_title_pt_BR" : "jfehlglm",
          "localized_title_pt_BR_sortable" : "jfehlglm",
          "localized_title_de_DE" : "jfehlglm",
          "localized_title_de_DE_sortable" : "jfehlglm",
          "localized_title_ca_ES" : "jfehlglm",
          "localized_title_ca_ES_sortable" : "jfehlglm",
          "localized_title_fi_FI" : "jfehlglm",
          "localized_title_fi_FI_sortable" : "jfehlglm",
          "localized_title_fr_FR" : "jfehlglm",
          "localized_title_fr_FR_sortable" : "jfehlglm",
          "localized_title" : "jfehlglm",
          "localized_title_en_US" : "jfehlglm",
          "localized_title_en_US_sortable" : "jfehlglm",
          [...]
        }
      }
```

If the GET endpoint is called with the contains filter over the `title` field with the following request:

```
curl -X GET -u 'test@liferay.com:test' http://localhost:8080/o/headless-delivery/v1.0/sites/20123/structured-contents?filter=contains(title,'eh')
```

**Before the PR:**

The Search engine throws an error and no values are returned. The following trace is printed:

```
Suppressed: org.elasticsearch.client.ResponseException: method [POST], host [http://127.0.0.1:9201/], URI [/liferay-20098/_search?typed_keys=true&max_concurrent_shard_requests=5&search_type=query_then_fetch&batched_reduce_size=512], status line [HTTP/1.1 400 Bad Request]
{"error":{"root_cause":[{"type":"query_shard_exception","reason":"failed to create query: [wildcard] queries are not supported on [icu_collation_keyword] fields.","index_uuid":"63WoM56XR5CTZRAcprW7yg","index":"liferay-20098"}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":0,"index":"liferay-20098","node":"ohdaYE72SIaqWUfboqrPrw","reason":{"type":"query_shard_exception","reason":"failed to create query: [wildcard] queries are not supported on [icu_collation_keyword] fields.","index_uuid":"63WoM56XR5CTZRAcprW7yg","index":"liferay-20098","caused_by":{"type":"unsupported_operation_exception","reason":"[wildcard] queries are not supported on [icu_collation_keyword] fields."}}}]},"status":400}
```

**After the PR:**

The Structured Content is returned successfully if applies

### CODE REVIEW

**Comment by LuismiBarcos** [comment]
ci:forward

**Comment by LuismiBarcos** [comment]
ci:forward

**Comment by LuismiBarcos** [comment]
The test `[com.liferay.headless.delivery.resource.v1_0.test.BlogPostingImageResourceTest.testGetSiteBlogPostingImagesPageWithFilterStringEquals](https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/26306//testReport/com.liferay.headless.delivery.resource.v1_0.test/BlogPostingImageResourceTest/testGetSiteBlogPostingImagesPageWithFilterStringEquals)`
could be related right??

**Comment by ccorreagg** [comment]
Closed because there is a current limitation regarding the localized sortable fields. The point is that those fields are being created as _icu_collation_keyword_ in elasticsearch, so wildcards are not allowed. The non sortable fields, for example _localized_title_en_US_, is configured as keyword.

**Pull request closed without merging**
