### PR TITLE
LPS-178115 | Test Fix FDSFilters#OneFilterCanBeRemoved

### PR DESCRIPTION
**Pull request by abhnerramos**
**Description**
Element was not present in FDSFilters#OneFilterCanBeRemoved.

**JIRA Ticket**
https://issues.liferay.com/browse/LPS-178115

### CODE REVIEW

**Comment by abhnerramos** [comment]
ci:test:stop

**Comment by abhnerramos** [comment]
ci:test:frontend

**Comment by abhnerramos** [comment]
ci:test:sf
ci:test:frontend

**Comment by abhnerramos** [comment]
ci:test:frontend

**Comment by abhnerramos** [comment]
ci:test:frontend

**Review by mateusralv — APPROVED** [review]

**Comment by mateusralv** [comment]
ci:forward

**Pull request closed without merging**
