### PR TITLE
LPD-20723 Clay link is translating asset titles/names by default in vertical card

### PR DESCRIPTION
**Pull request by Mikellorza**
bug: https://liferay.atlassian.net/browse/LPD-20723

Description
----------
Add isTranslating method in order to decide if we want translate clay card content or not. For the moment, it is only implemented for the title as we have for the vertical card.

### CODE REVIEW

**Comment by Mikellorza** [comment]
ci:test:sf

**Review by markocikos — APPROVED** [review]
@Mikellorza LGTM! :sparkles:

**Comment by Mikellorza** [comment]
ci:forward

**Comment by Mikellorza** [comment]
ci:forward:force

**Pull request closed without merging**
