### PR TITLE
LPS-189969 LPS-191857 Sort data set views by modified date

### PR DESCRIPTION
**Pull request by thektan**
**Story:** https://issues.liferay.com/browse/LPS-189969
**Subtask:** https://issues.liferay.com/browse/LPS-191857

- Sorts the Data Set Views page by modified date

### Demo

https://github.com/liferay-frontend/liferay-portal/assets/4496722/1f45ac23-bf6d-4417-b9d7-d4a29969d319

### CODE REVIEW

**Review by bryceosterhaus — APPROVED** [review]
LGTM!

**Comment by mateusralv** [comment]
I'm on it 🕵🏽

**Comment by mateusralv** [comment]
Hi @thektan I created the fix and sent a new PR (https://github.com/liferay-frontend/liferay-portal/pull/3567) could you add my commit here or add me as a contributor to your repository?

**Comment by mateusralv** [comment]
ci:foward

**Comment by mateusralv** [comment]
ci:test:relevant

**Comment by mateusralv** [comment]
ci:test:stable

**Comment by mateusralv** [comment]
The failures are not related! 

[Testray comparison](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1690909183514&testrayRunIdA=2397331688&testrayRunIdB=2397957522)

**Comment by mateusralv** [comment]
ci:forward:force

**Pull request closed without merging**
