### PR TITLE
Commerce 5797 dxp 3of5 with no usecontext

### PR DESCRIPTION
**Pull request by garofalog**
this belog to this [pr](https://github.com/liferay-frontend/liferay-portal/pull/1242). They differ for most recent changes and no use of React  useContext. To replace some features in future pull requests with useReducer

### CODE REVIEW

**Comment by garofalog** [comment]
ci:test:sf

**Comment by garofalog** [comment]
ci:test:relevant

**Comment by markocikos** [comment]
@garofalog If I am understanding https://github.com/liferay-frontend/liferay-portal/pull/1242#discussion_r670349716 correctly, this is a WIP that requires https://github.com/liferay-frontend/liferay-portal/pull/1242 to be merged first. As such, I'll set it as draft, until it's ready for full review.

**Comment by garofalog** [comment]
Hello @markocikos, this is not a new pr that requires #1242. This is the same pr with all the reqest changes same as #1242 but here i only removed useContext's commit because it's not useful since we're planning to use reducers to clean up more that props.
So i should merge this in #1242 or i have to close the previous one? ty

**Comment by markocikos** [comment]
> Hello @markocikos, this is not a new pr that requires #1242. This is the same pr with all the reqest changes same as #1242 but here i only removed useContext's commit because it's not useful since we're planning to use reducers to clean up more that props.
> So i should merge this in #1242 or i have to close the previous one? ty

@garofalog If this is the latest version of  #1242, a change you are confident you want to make, please force-push on it. This keeps all related discussions in one PR. This is what we commonly do with reviews. Opening new PR might makes sense, if there are significant changes in code, like rewriting code to a different solution. What are '_significant changes_' is subjective, it's up to you to make the call. But, if you are opening new PR, you should close the old one.

**Comment by garofalog** [comment]
ok fine. they differ mostly for a only commit so i'm rebasing the first one on it and i'll colse this. ty

**Pull request closed without merging**
