### PR TITLE
LRQA-73235 | Format css in main.css

### PR DESCRIPTION
**Pull request by susanchen3**
https://issues.liferay.com/browse/LRQA-73235

### CODE REVIEW

**Comment by susanchen3** [comment]
ci:test:frontend:nocompile

**Comment by john-co** [comment]
ci:test:relevant

**Comment by susanchen3** [comment]
lost connection, gonna try again
` [parallel] Failed to connect to the controller: The controller is not available at localhost:9990: java.net.ConnectException: WFLYPRT0053: Could not connect to remote+http://localhost:9990. The connection failed: WFLYPRT0053: Could not connect to remote+http://localhost:9990. The connection failed: Connection refused`

**Comment by susanchen3** [comment]
ci:test:relevant

**Comment by susanchen3** [comment]
@john-co is it ok to forward? :thinking:

**Review by john-co — APPROVED** [review]
lgtm!

**Comment by john-co** [comment]
ci:forward

**Pull request closed without merging**
