### PR TITLE
LPD-28582 When a new default sorting is saved, set other previously set default sorting as false

### PR DESCRIPTION
**Pull request by thektan**
**Bug Ticket:** https://liferay.atlassian.net/browse/LPD-25464
+
**Story:** https://liferay.atlassian.net/browse/LPD-25392
**Subtask:** https://liferay.atlassian.net/browse/LPD-28582

---

**Notes:**
- Sending with https://liferay.atlassian.net/browse/LPD-25464 to avoid any conflicts.
- Creates an `MVCResourceCommand` to batch multiple updates if a previous default needs to be set to false
- When adding or editing a sorting, the entire sorting table refetches the data, which means there will be a loading spinner before the table is displayed again to refresh any `default` value changes.

## Demo 

https://github.com/user-attachments/assets/cec9d310-1ed5-4376-ba2b-d88799489b30

### CODE REVIEW

**Comment by thektan** [comment]
Removed the language key commits since they weren't being used anymore.

**Comment by thektan** [comment]
ci:forward

**Comment by dsanz** [comment]
ci:test:stable

**Comment by thektan** [comment]
Failures don't seem related, running force forward.

**Comment by thektan** [comment]
ci:forward:force

**Pull request closed without merging**
