### PR TITLE
LPD-29982 text truncation inside an <a>, not viceversa

### PR DESCRIPTION
**Pull request by gianmarcobrunialti**
Hello guys. I hereby request your review for this change, as it'll allow the `SearchContainerColumnTextTag` to correctly display truncated text with the right HTML structure for `table-title` Clay CSS class to be applied correctly (according to [these changes](https://github.com/liferay/clay/commit/3e0ed1df192e0c4b05950fcb958cbf7b8673f8f4)).

This PR stems from [this ticket](https://liferay.atlassian.net/browse/LPD-29982), which in turn stems from [this conversation](https://liferay.slack.com/archives/CNBG06JS3/p1718616362669729) in #t-dxp-frontend-infra with @juanjofgliferay.

### CODE REVIEW

**Review by juanjofgliferay — APPROVED** [review]
LGTM

**Comment by gianmarcobrunialti** [comment]
ci:test:relevant

**Comment by gianmarcobrunialti** [comment]
ci:test:relevant

**Comment by gianmarcobrunialti** [comment]
ci:forward

**Pull request closed without merging**
