### PR TITLE
LPS-147613 Fix XSS vulnerability in Management Toolbar

### PR DESCRIPTION
**Pull request by markocikos**
### References

- [LPS-147613 Reflected XSS with filterType param in search](https://issues.liferay.com/browse/LPS-147613)

### What is the goal?

To prevent XSS attack, we need to escape label before writing to JSP.

#### Before PR
before

#### After PR
after

### How to replicate

See steps to reproduce in the JIRA ticket.

### CODE REVIEW

**Review by diegonvs — APPROVED** [review]

**Comment by diegonvs** [comment]
ci:test:relevant

**Comment by markocikos** [comment]
ci:forward

**Comment by diegonvs** [comment]
ci:forward

**Comment by markocikos** [comment]
ci:forward

**Comment by diegonvs** [comment]
ci:forward

**Comment by diegonvs** [comment]
please-work

**Comment by diegonvs** [comment]
Last three runs: 

Three different errors:

1. [LocalFile.PageAudit#LanguageCacheData](https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0/38693//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_PageAudit_LanguageCacheData_)
2. Weird Java error
3. [ContentDashboard#ApprovedAndDraftStatus](https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=8/36085//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_ContentDashboard_ApprovedAndDraftStatus_)

If this time fail, I can send manually

**Comment by diegonvs** [comment]
ci:forward

**Comment by Esther-OC** [comment]
What worries me is the [ContentDashboard#ApprovedAndDraftStatus](https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=8/36085//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_ContentDashboard_ApprovedAndDraftStatus_) error, which also appears in the list of unique errors when comparing the PR with upstream and the latest master, because it is regarding an element not present.
Can you please take a look to its [Poshi report](https://testray.liferay.com/reports/production/logs/2022-03/test-1-31/test-portal-acceptance-pullrequest(master)/2468/functional-tomcat90-mysql57-jdk8/8/8/LocalFile.ContentDashboard_ApprovedAndDraftStatus/index.html.gz?authuser=0) just in case, @diegonvs ?
Thanks!

**Comment by diegonvs** [comment]
When running locally, it thrown this error: `BUILD FAILED: Element is not present at "//button[@data-qa-id='applicationsMenu']"` :/

Also, when taking a look on POSHI report, this failure about workflow status element seems very very unrelated. But it might be because I don't have too much knowledge about content dashboard stuff

**Comment by markocikos** [comment]
ci:forward

**Comment by diegonvs** [comment]
ci:forward

**Comment by diegonvs** [comment]
Every new run, new unrelated tests are bloating. @john-co, @Esther-OC, Can I send it manually?

**Comment by markocikos** [comment]
ci:forward

**Comment by diegonvs** [comment]
ci:forward

**Comment by john-co** [comment]
Just started reviewing :)

**Comment by john-co** [comment]
I analyzed https://github.com/liferay-frontend/liferay-portal/pull/1972#issuecomment-1065356955 and bunch of tests failed prior to running the test with the following error:
```
     [exec] Directory /opt/dev/projects/github/liferay-portal/modules/sdk/project-templates/project-templates/src/testFunctional does not exist.
     [exec] [CodeBlob (0x00007f9c990fc7d0)]
     [exec] Framesize: 60
     [exec] Runtime Stub (0x00007f9c990fc7d0): handle_exception_nofpu Runtime1 stub
     [exec] Could not load hsdis-amd64.so; library not loadable; PrintAssembly is disabled
     [exec] #
     [exec] # A fatal error has been detected by the Java Runtime Environment:
     [exec] #
     [exec] #  Internal Error (sharedRuntime.cpp:834), pid=341521, tid=0x00007f9c5c8d3700
     [exec] #  fatal error: exception happened outside interpreter, nmethods and vtable stubs at pc 0x00007f9c990fc93f
     [exec] #
     [exec] # JRE version: Java(TM) SE Runtime Environment (8.0_121-b13) (build 1.8.0_121-b13)
     [exec] # Java VM: Java HotSpot(TM) 64-Bit Server VM (25.121-b13 mixed mode linux-amd64 compressed oops)
     [exec] # Core dump written. Default location: /opt/dev/projects/github/liferay-portal/portal-web/core or core.341521
     [exec] #
     [exec] # An error report file with more information is saved as:
     [exec] # /opt/dev/projects/github/liferay-portal/portal-web/hs_err_pid341521.log
     [exec] #
     [exec] # If you would like to submit a bug report, please visit:
     [exec] #   http://bugreport.java.com/bugreport/crash.jsp
     [exec] #
     [exec] 
     [exec] > Task :writePoshiProperties FAILED
     [exec] 
     [exec] 
     [exec] FAILURE: Build failed with an exception.
     [exec] 
     [exec] * What went wrong:
     [exec] Execution failed for task ':writePoshiProperties'.
     [exec] > Process 'command '/opt/java/jdk1.8.0_121-x64/bin/java'' finished with non-zero exit value 134
     [exec] 
     [exec] * Try:
     [exec] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
     [exec] 
     [exec] * Get more help at https://help.gradle.org
     [exec] 
     [exec] BUILD FAILED in 9s
     [exec] Gradle build finished at 2022-03-11 16:02:28.471.
     [exec] 1 actionable task: 1 executed
 ```
 Other tests are unrelated/flaky/already failing upstream.
 
It's weird that less tests were run in the attempts to forward earlier today.

**Comment by john-co** [comment]
Manually forwarded to https://github.com/brianchandotcom/liferay-portal/pull/114616

**Pull request closed without merging**
