### PR TITLE
LPS-139948 - Remove some uses of A.one in favor of js equivalents

### PR DESCRIPTION
**Pull request by bryceosterhaus**
I combined all of the "aui/no-one" rule prs into one. I ended up keeping the rule disabled since there are still 217 uses of [A.one](http://A.one) in js files in DXP that we need to resolve. I think it is best we address those at a later date since they seem like they could take awhile. @nhpatt @kresimir-coko what do you guys think?

### CODE REVIEW

**Comment by bryceosterhaus** [comment]
labeling with "on hold" since these aren't necessary for 7.4 release

**Comment by nhpatt** [comment]
Sounds good, disabling and merging PRs in this one.

**Comment by kresimir-coko** [comment]
I agree, good decision @bryceosterhaus

**Review by kresimir-coko — APPROVED** [review]

**Comment by bryceosterhaus** [comment]
@kresimir-coko can you look at fixing these CI errors?

**Comment by kresimir-coko** [comment]
> @kresimir-coko can you look at fixing these CI errors?

@bryceosterhaus sure, I'll prioritize it.

**Comment by kresimir-coko** [comment]
Closing in favor of https://github.com/liferay-frontend/liferay-portal/pull/1626

**Pull request closed without merging**
