### PR TITLE
LPS-184422 Consolidate FDS cell renderer definition

### PR DESCRIPTION
**Pull request by markocikos**
### References

- [LPS-184422 Consolidate FDS cell renderer definition](https://issues.liferay.com/browse/LPS-184422)
- Split off from https://github.com/liferay-frontend/liferay-portal/pull/3320
  - see some related discussions in reviews of that PR

### What is the goal of this PR?

In this PR, we are refactoring definition and API of cell renderers:
- We are rebranding "Data Renderers" into "Cell Renderers". "Data" is vague, and we plan to have renderers other then cell down the line.
- We are moving cell renderer label definitions to one central place of definition.
- We are establishing the hierarchy of interfaces `Renderer` > `CellRenderer` > `InternalCellRenderer`. I still don't fully like internal makeup of these interfaces, but the hierarchy should be clean enough to guide future tweaks.  
- We are establishing that FDS exports should have `FDS*` prefix. There is no need for such prefix in internal code.
- We are exporting an array or renderers, instead of an object.
- We are exporting a getter for internal cell renders. This getter returns default renderer by default, instead of failing.
- We are applying new API to commerce and Dataset Manager.
- We are removing the unused `list` renderer.

In this PR, we are **not**:
- dealing with inconsistencies of [our public API for renderers](https://github.com/liferay/liferay-frontend-projects/blob/master/projects/js-toolkit/packages/js-api/data-set/index.ts)
  - this should probably not be named `FDSCellRenderer`, as we established that a "Renderer" is a object containing the component as well as metadata like type and name. It should maybe be `FDSCellRendererComponent`.
  - We are still [setting this in a `renderer` property](https://github.com/liferay/liferay-portal/blob/master/modules/apps/frontend-data-set/frontend-data-set-web/src/main/resources/META-INF/resources/utils/dataRenderers.ts#L48), not a `component`. They have different types, but we can probably handle that with `ifs` in code, instead of having different properties.
- dealing with inconsistencies of custom data renderers. These could be set to `InternalCellRenderer` umbrella as well, but that change requires change of API. This is fine, I did custom data renderers API very early and with no larger picture we have today, just to enable any kind of customization to renderers. But, migration significantly extends scope of the task, so I left it out.

On the interfaces naming pattern, I'm growing more and more in favor of no restriction other than pascal case. In this PR, I though of adding an `I` to `InternalCellRenderer`, but `IInternalCellRenderer` looks quite silly :expressionless: 

### What does it look like?

No changes in UI.

### CODE REVIEW

**Comment by markocikos** [comment]
ci:test:relevant

**Comment by izaera** [comment]
> dealing with inconsistencies of [our public API for renderers](https://github.com/liferay/liferay-frontend-projects/blob/master/projects/js-toolkit/packages/js-api/data-set/index.ts)

Just a reminder that the API is not yet official, so we can do whatever we need with it.

**Comment by markocikos** [comment]
This is a rare case, to see commerce CI green :open_mouth: 

I tested it manually to double-check, works fine:
screen

**Comment by markocikos** [comment]
@bryceosterhaus @izaera can we push this?

**Comment by izaera** [comment]
> can we push this?

I don't feel qualified to give an authoritative answer for pushing, but I haven't seen anything especially problematic, so I guess you can, unless anyone else complains.

**Comment by markocikos** [comment]
Noone spoke, I guess they'll now have to forever hold their peace.

**Comment by markocikos** [comment]
ci:forward

**Pull request closed without merging**
