### PR TITLE
LRQA-66397 | Deploy clay sample portlet for clay poshi tests

### PR DESCRIPTION
**Pull request by john-co**
**Description**
The clay sample portlet is not packaged in a release bundle but is required for Clay CI poshi tests. We need a way to deploy the sample portlet when the tests are run. This adds a property to the clay tests to deploy the clay sample web module during ci testing.

**Test Plan**
- [x]  Check that the clay sample module is deployed before poshi test in CI: https://github.com/john-co/liferay-portal/pull/409#issuecomment-846318005
- [x] Locally make sure clay sample web is not included in bundle, run poshi test, and validate clay sample web is deployed before poshi test executes login

**JIRA Ticket**
https://issues.liferay.com/browse/LRQA-66397

### CODE REVIEW

**Comment by john-co** [comment]
ci:test:sf

**Comment by john-co** [comment]
cc/ @nkkwon please see the last commit for fix

**Review by zhangyan0701 — APPROVED** [review]

**Comment by john-co** [comment]
ci:forward

**Comment by john-co** [comment]
ci:forward

**Pull request closed without merging**
