### PR TITLE
LPS-118295 Improve Classic TokenDefinition labels

### PR DESCRIPTION
**Pull request by jbalsas**
Small followup on our Classic Theme Token Definition that:
- Replaces (sm), (md) and (lg) abbreviations from labels in favour of the full words
- Sorts tokens so they always follow: Base - Small - Large ... ordering
- Uses labels in token set collapsibles

Screen Shot 2020-07-31 at 13 57 39
Screen Shot 2020-07-31 at 13 57 47

### CODE REVIEW

**Comment by wincent** [comment]
ci:test:sf

**Comment by wincent** [comment]
ci:test:relevant

**Comment by wincent** [comment]
```
   26:66  error  'name' is defined but never used. Allowed unused args must match /^_/u.  no-unused-vars
```

good-point

**Comment by jbalsas** [comment]
Well, we all know the drill... rebased, removed unnecessary `name` variable and force-pushed 🙈

**Comment by jbalsas** [comment]
ci:test:sf

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
ci:test:sf

**Comment by jbalsas** [comment]
> I know you didn't ask for my review, but...

I'll take that as approval to forward this 😂

**Comment by jbalsas** [comment]
ci:forward

**Pull request closed without merging**
