### PR TITLE
LPS-128114 - Update clay-* dependencies to v.2.22.3

### PR DESCRIPTION
**Pull request by bryceosterhaus**
Jira: https://issues.liferay.com/browse/LPS-128114

Support requested a release as soon as possible to fix this customer issue, https://issues.liferay.com/browse/LPS-127879

### CODE REVIEW

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by wincent** [comment]
ci:forward

**Comment by wincent** [comment]
@bryceosterhaus So given the apparent urgency here and the fact that CI is green and the lockfile update doesn't look crazy, I forwarded this as-is, but this is a departure from how we've done v2 releases in the past (updating all packages at once); are you planning on resyncing all the v2 versions in the next bi-weekly update?

**Comment by bryceosterhaus** [comment]
@wincent thanks for forwarding!

And actually, this is still our typical 2.x release process. 2.x uses `fixed` mode for lerna and it updates every package to the next version IF there are changes or dependency changes. In past updates we normally get a lot more updates since we have a change to clay-css, so more often than not, we updated all 2.x packages.

[fixed mode](https://github.com/lerna/lerna#fixedlocked-mode-default)
> When you run lerna publish, if a module has been updated since the last time a release was made, it will be updated to the new version you're releasing. This means that you only publish a new version of a package when you need to.

**Comment by wincent** [comment]
Indeed, I looked back at the Git log and the last four updates have updated _all_ the Clay v2 packages:

- 8155ccd908cf84ed5bc11e933a07c6046117d0b8 (Feb 2021)
- a19771109f7eb48b006ecea12e800039f1aaed05 (Jan 2020)
- 7caf93151de084b5e7c003b2019a3438f944fe38 (Dec 2020)
- 7ab55b91bf12ec0f20516142dbc02dba6fdbaf45 (Aug 2020)

**Comment by bryceosterhaus** [comment]
Yeah this is a little odd. I think it may come down to the `clay-css` package and if that is updated, every other package gets bumped. I've seen instances where not every package is on the same version, in [2.22.3](https://github.com/liferay/clay/tree/v2.22.3/packages) you can see that button is at 2.22.2 and card is at 2.22.3.

From reading the lerna docs too, this is expected that not every package would get bumped every time. The only way that everything would be bumped is if  we explicitly stated the version number rather than using `--conventional-commits`. I went back to see when we started using conventional commits and found that we started that in [June 2019](https://github.com/liferay/clay/commit/b8916a7c0fd711b1b10d1378206834996b0aacc8). We also never documented our release process for 2.x until [March 2020](https://github.com/liferay/clay/commit/6576696006b06fd8acdb30780bdfa5e93f66699a#diff-eca12c0a30e25b4b46522ebf89465a03ba72a03f540796c979137931d8f92055). So with all this to say, my hypothesis is that when we used to release without using conventional commits, we would manually choose the version number and thus every package would be updated regardless if any dependency or code changes.

So the question is, should we keep releasing every package? Personally, I don't think so, I think its helpful to release with the `--conventional-commits` flag and only release packages that actually contain a change or dependency bump. Our metal.js mono-repo used to be released all at once, regardless of what changed, and I remember it to be really frustrating as a consumer of Metal because version bumps were meaningful for some packages and pointless for others but you wouldn't know until you looked at each package's changelog.

**Comment by wincent** [comment]
> So the question is, should we keep releasing every package? Personally, I don't think so, I think its helpful to release with the `--conventional-commits` flag and only release packages that actually contain a change or dependency bump. Our metal.js mono-repo used to be released all at once, regardless of what changed, and I remember it to be really frustrating as a consumer of Metal because version bumps were meaningful for some packages and pointless for others but you wouldn't know until you looked at each package's changelog.

I'd take the opposite stance. I'd rather know that "vX.Y.Z" of Clay means "the set of Clay packages that we know work well together", and liferay-portal always will have the latest (ie. the last-known/best-working version of every Clay package). We have a global changelog, so if I care to know the details, I'd look at that. Furthermore, when we update in liferay-portal, we take care of updating the version numbers in every module, so there's no burden for the consumers; they don't even need to know an update happened (especially because we don't make breaking changes). The counterscenario is that you wind up with what we currently have in v3, which is a bunch of different version numbers (as [I reported here], there are 39 different Clay v3 packages and 23 distinct v3 version numbers at once in liferay-portal) — that seems much more confusing.

Might be worth moving this to an issue in the Clay repo though if you want to discuss it further.

**Pull request closed without merging**
