### PR TITLE
LPS-126011 Migrate 'show more' feature in management toolbar creation menu

### PR DESCRIPTION
**Pull request by markocikos**
Fixes: https://issues.liferay.com/browse/LPS-126011

In this PR we are adding the 'More' button in the management toolbar creation menu, and extending `sample-web` to showcase the behavior.

Test plan:
- Place `frontend-taglib-clay-sample-web` on a page and open `Management Toolbars` tab.
- See gif on bottom.

Notes:
- The button will show if there are more than `maxTotalItems` items in the menu. By default, this is 15, taken from the [v2 implementation](https://github.com/liferay/clay/blob/2.x/packages/clay-dropdown/src/ClayCreationMenuDropdown.soy#L93).
- Menu items can be primary and secondary. There can be any number of secondary item groups. v2 implementation supported only two groups, in practice it was 'Favorites' and 'Other'. New tag supports any number of groups. I found this cleaner than duplicated code for two groups in v2 implementation, for example [here](https://github.com/liferay/clay/blob/2.x/packages/clay-dropdown/src/ClayCreationMenuDropdown.soy#L50-L62).
- Number of primary and secondary items can be limited with `maxPrimaryItems` and `maxSecondaryItems`. These along with `maxTotalItems` results in [complicated resolution](https://github.com/liferay/clay/blob/2.x/packages/clay-dropdown/src/ClayCreationMenuDropdown.soy#L50-L118) of how many items should be visible. I copied, but did not test all of the many branching cases. I tested only `maxTotalItems` setting, and it works as expected.
- By default, clicking on 'More' button shows all the items in the extended menu. See this in gif.
- If `onShowMoreButtonClick` is defined, clicking on 'More' invokes it, instead of extending menu. See this in gif, only bottom toolbar has it defined. For usages in Web Content and Documents and Media, this would open a modal with full selection.

@jbalsas Please confirm that the behavior described in last two notes matches the required behavior.

@julien @jonmak08 @carloslancha 

after

### CODE REVIEW

**Comment by markocikos** [comment]
ci:reevaluate:1032004_8970

**Comment by markocikos** [comment]
The failure is unrelated, semver of `frontend-taglib` needs to be updated.

**Comment by julien** [comment]
@markocikos make sure to ping @PablitoBonito and @john-co but yes that semver failure is marked as "common", i.e. not related to your pull request

**Comment by PablitoBonito** [comment]
ci:test:relevant

**Comment by john-co** [comment]
cc/ @vicnate5 fyi, we encountered flaky upgrade test ViewPortalSmokeArchive730.

**Review by julien — APPROVED** [review]

**Comment by markocikos** [comment]
All green and approved, pushing.

**Comment by markocikos** [comment]
ci:forward

**Comment by markocikos** [comment]
ci:forward

**Pull request closed without merging**
