### PR TITLE
LPS-180227 | Add some paths into a PATH file

### PR DESCRIPTION
**Pull request by abhnerramos**
**Description**
Initially, some specific paths were being directly called within the testcase file. However, due to validation errors in the new poshi version, it became necessary to relocate these paths into a separate PATH file.

**JIRA ticket**
https://issues.liferay.com/browse/LPS-180227

### CODE REVIEW

**Comment by abhnerramos** [comment]
ci:test:frontend

**Comment by abhnerramos** [comment]
@CalumR23

**Comment by abhnerramos** [comment]
ci:test:frontend

**Review by mateusralv — APPROVED** [review]

**Comment by mateusralv** [comment]
ci:forward

**Pull request closed without merging**
