### PR TITLE
LPS-131524 baseline

### PR DESCRIPTION
**Pull request by nhpatt**
Missing baseline :P

This solves this [QA issue](https://issues.liferay.com/browse/LRQA-67097)

### CODE REVIEW

**Comment by nhpatt** [comment]
ci:test:relevant

**Review by javierdearcos — APPROVED** [review]

**Comment by nhpatt** [comment]
ci:forward

**Comment by javierdearcos** [comment]
Unrelated error. Forwarding again

**Comment by javierdearcos** [comment]
ci:forward

**Pull request closed without merging**
