### PR TITLE
LPS-145115 - Transition feature flag from dev to release

### PR DESCRIPTION
**Pull request by bryceosterhaus**
https://issues.liferay.com/browse/LPS-145115

Screen Shot 2023-05-04 at 10 12 32 AM

### CODE REVIEW

**Comment by bryceosterhaus** [comment]
ci:stop

**Comment by bryceosterhaus** [comment]
ci:test:sf

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by manoelcyreno** [comment]
ci:reevaluate:1257401_826

**Comment by mateusralv** [comment]
Hi @bryceosterhaus The failures are not related 🚀 

[Testray Comparison](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1683194689132&testrayRunIdA=2289214584&testrayRunIdB=2289286559)

**Comment by bryceosterhaus** [comment]
forwarded https://github.com/brianchandotcom/liferay-portal/pull/134337

**Pull request closed without merging**
