### PR TITLE
LPS-173636 Adds attributes decoration, fontSize, and weight to clay-link

### PR DESCRIPTION
**Pull request by pat270**
https://issues.liferay.com/browse/LPS-173636
https://github.com/brianchandotcom/liferay-portal/pull/129251
https://github.com/liferay/clay/pull/5288

This adds the attributes `decoration`, `fontSize`, and `weight` to the `clay:link` tag. These were added in [Clay 3.85.0](https://github.com/liferay/clay/releases/tag/v3.85.0).

### CODE REVIEW

**Comment by pat270** [comment]
ci:test:relevant

**Comment by pat270** [comment]
@matuzalemsteles I'll wait until https://github.com/liferay-frontend/liferay-portal/pull/3008 gets merged due to more conflicts in versioning.

**Comment by pat270** [comment]
@matuzalemsteles looks like I don't need to bump the version in this one.

**Comment by matuzalemsteles** [comment]
@pat270 it may be that the version is bumped only according to the release, as you already did that in the other PR and we still didn't have a DXP release, it doesn't need to be done in this one.

**Comment by pat270** [comment]
@eltonccdantas is this one good to forward?

**Comment by eltonccdantas** [comment]
Hey @pat270 , Thanks for reaching out, I've just analyzed your PR and there are no errors related to it as you can see on this [comparison](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1675197678670&testrayRunIdA=2181138988&testrayRunIdB=2178010537) . You may manually forward if no other dev review is needed.

**Comment by pat270** [comment]
Thanks again @eltonccdantas !

**Comment by pat270** [comment]
ci:forward

**Comment by pat270** [comment]
ci:test:relevant

**Pull request closed without merging**
