### PR TITLE
LPS-174464 Implement improvements on performance of resolve modules servlet URL generation

### PR DESCRIPTION
**Pull request by izaera**
This is another take at LPS-174464.

It contains all the changes we rolled back:

- https://github.com/brianchandotcom/liferay-portal/pull/129834
- https://github.com/brianchandotcom/liferay-portal/pull/129910

But, additionally, it implements:

1. Full hashing of resolution state to be safer
2. Resolution state snapshots so that resolutions are stable and don't poison CDN caches

Given the problems found in previous PRs, it would be worth checking this thoroughly from a QA standpoint.

### CODE REVIEW

**Comment by izaera** [comment]
ci:test:sf

**Comment by izaera** [comment]
ci:test:relevant

**Comment by manoelcyreno** [comment]
ci:test:frontend

**Comment by izaera** [comment]
ci:test:sf

**Comment by izaera** [comment]
ci:test:relevant

**Comment by john-co** [comment]
ci:help

**Comment by john-co** [comment]
ci:test:acceptance-functional

**Comment by mateusralv** [comment]
Hi @izaera A summary of the routines I analyzed and the related failure: 

### ci:test:frontend: Has no related failures 🟢 🎉 

[Testray comparison ](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1676400538258&testrayRunIdA=2196356432&testrayRunIdB=2196654641)

---
### ci:test:relevant: had a unique failure 🔴 

Failure in fragments:

https://user-images.githubusercontent.com/44584050/218852600-a14b4d59-1953-45e3-b59b-1501134b306b.mp4

affected tests: 
LocalFile.FragmentsWithReact#ViewReactFragmentInPage

[Testray comparison](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=2&testrayRunIdB=2196653631&testrayRunIdA=2196356432&statusB=3)

**Comment by izaera** [comment]
Converted to draft to prevent accidental forwards. 

We need to merge https://github.com/liferay-echo/liferay-portal/pull/11106 before sending this.

**Pull request closed without merging**
