### PR TITLE
LPS-174464 revert

### PR DESCRIPTION
**Pull request by izaera**
Since LPS-174464 is a performance enhancement and we may need to add more changes, as I've found out during an investigation I did today, it is better to rollback now, then add it later, when/if we feel it is stable enough.

I have not rolled back [a semver commit from Shuyang](https://github.com/liferay/liferay-portal/commit/9ea2764c5ab78ada3e5ccf84c32497bde177f572)  because there was another semver commit from Brian on top. Not sure how to deal with that...

----

As per https://liferay.slack.com/archives/CNBG06JS3/p1675982109401639

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged!

**Comment by john-co** [comment]
ci:help

**Comment by john-co** [comment]
ci:test:echo-acceptance

**Comment by izaera** [comment]
Closing since it's merged

**Pull request closed without merging**
