### PR TITLE
LPS-146152 Fixes alignment on disabled Application Menu Product Menu …

### PR DESCRIPTION
**Pull request by pat270**
…items

https://issues.liferay.com/browse/LPS-146152

###### Broken
product-menu-alignment

###### Fixed
product-menu-fixed

### CODE REVIEW

**Comment by pat270** [comment]
ci:test:relevant

**Comment by matuzalemsteles** [comment]
Hey @pat270 just a question, this spacing that was created due to the side effect of is it in `cadmin` scope?

**Comment by pat270** [comment]
@matuzalemsteles not related to cadmin scope. I think the styles got messed up when we converted to Applications Menu, but I didn't dig that deep.

**Comment by matuzalemsteles** [comment]
I got it, Patrick! So, LGTM!

**Review by diegonvs — APPROVED** [review]

**Comment by diegonvs** [comment]
ci:forward

**Pull request closed without merging**
