### PR TITLE
LPS-137585 allow name in GraphQL name comparisons

### PR DESCRIPTION
**Pull request by nhpatt**
Just a quick hack. This does not solve all the GraphQL enum problems because the spec if so bad. But at least tests do not fail in several situations.

### CODE REVIEW

**Review by LuismiBarcos — APPROVED** [review]

**Comment by nhpatt** [comment]
-- rebased, retrying.

**Comment by nhpatt** [comment]
ci:forward

**Comment by nhpatt** [comment]
ci:test:relevant

**Comment by nhpatt** [comment]
ci:test:relevant

**Comment by nhpatt** [comment]
-- rebased

**Comment by nhpatt** [comment]
ci:forward

**Pull request closed without merging**
