### PR TITLE
[TS] LPS-111067 Make Display Style persist in multiple menus

### PR DESCRIPTION
**Pull request by wanderlast**
Resent as https://github.com/liferay-frontend/liferay-portal/pull/780

----

This is being sent here per @jbalsas [here](https://github.com/liferay/liferay-portal-ee/pull/22571#issuecomment-768448172).

https://issues.liferay.com/browse/LPS-111067

The issue is essentially that our current pattern used when storing the displayStyle of a portlet causes it to be lost when switching between portlets since the request parameter doesn't persist. So, for example, if I prefer to view my site memberships as all lists (and switch my display style for each to "list"), then switch to upload a document, when I return to my site memberships they will have all reverted back to their default view style (which is "icon" in some cases).

This fix adds the previous pattern, which stored the displayStyle in portalPreferences, as a backup to the current pattern so that we can persist between portlets/sessions. This logic actually appears in a handful of portlets already (see: https://github.com/liferay/liferay-portal/blame/master/modules/apps/blogs/blogs-web/src/main/java/com/liferay/blogs/web/internal/display/context/BlogEntriesDisplayContext.java#L123-L131), so this can be seen as simply applying it more broadly.

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by wincent** [comment]
CI appears to be stalled, so going to retry.

Based on @jbalsas's [comment](https://github.com/liferay/liferay-portal-ee/pull/22571#issuecomment-768448172):

> Take into consideration that Frontend Infrastructure doesn't own these apps so product team leads should be okay with this as well, but this seems a reasonably cheap measure to me based on the issue and how complex implementing a general alternative seemed to be.

I don't think it is cost-efficient to get "pre-approval" from all leads on this one. I suggest we see CI green, and forward. I will notify at least the Spanish team leads in our next integration meeting (Wednesday) of this change, and @brunofernandezg may be able to help with reaching out to any other affected teams. (Note at this stage, I have only skimmed the list of affected files, so I am not sure exactly what teams those may be.) If anything breaks, we fast-follow with a fix. Or rather, you do, @wanderlast. 😂

**Comment by wincent** [comment]
ci:stop

**Comment by wincent** [comment]
ci:test:relevant

**Comment by brunofernandezg** [comment]
>  I will notify at least the Spanish team leads in our next integration meeting (Wednesday) of this change, and @brunofernandezg may be able to help with reaching out to any other affected teams.

Agree with this

**Comment by wincent** [comment]
ci:forward

**Comment by wincent** [comment]
Closed upstream and re-opening so we can look at backend part a bit more closely.

**Comment by jbalsas** [comment]
Hey @izaera, what do you think of this? This comes after a bit of a back and forth because of all the boilerplate we need to add in so many places...

One idea we had last time was to encapsulate this logic somewhere so at least it's more straightforward for Apps to do this consistently. Could you take a look and figure out where could we place such an API so that we can make sure other apps going through this consistently (and in an easy way) apply the pattern?

Thanks!

**Comment by izaera** [comment]
I'll find a cozy place for it, though it seems a complex task... Not technically, because it's quite clear what needs to be done but, if we provide an API to save the list style, why not for saving any other common thing? :thinking: 

Do we have more widgets with state that could be saved per-user? I'm not sure if we want an agnostic API to save preferences, or an API to save widget states for example...

Or another possibility could be to embed this persistence in the very same widgets (though it sounds a bit coupled, if it is not too much state to save, it could make sense).

**Comment by jbalsas** [comment]
> Do we have more widgets with state that could be saved per-user? I'm not sure if we want an agnostic API to save preferences, or an API to save widget states for example...
>
> Or another possibility could be to embed this persistence in the very same widgets (though it sounds a bit coupled, if it is not too much state to save, it could make sense).

We went over this already. The only other obvious example is the new DatasetDisplay widget which already encapsulates the persistence logic.

This is just a temporary attempt at making the UI consistent while we migrate to the new patterns. As such, either what we have here or some sort of raw ad-hoc API for this use case should be enough.

**Comment by izaera** [comment]
> some sort of raw ad-hoc API for this use case should be enough.

I love raw ad-hoc for temporary things :heart_eyes: . They are my specialty.

I was going to say that passing this kind of API through review might become difficult, but it could also be difficult to pass this copy-paste, so... :thinking: 

I'll try to find a place for the API and I'll report my findings.

**Comment by izaera** [comment]
I can't see any logical place to put this. The only bundle that I think we could use is `frontend-taglib-util` which is very different from the functionality we have here. I only see it a a candidate because it is so empty as it is now and I think we may abuse its name :sweat_smile: .

On the other hand, this logic is only three lines and I don't think that creating a public API for it is going to make the situation better. The problem is that the display contexts are a very loose pattern that the infrastructure doesn't know.

If we have the concept of `displayStyle` that is shared among all portlets, the correct thing would be doing something automatic for all widgets (if `displayStyle` is going to be supported by infrastructure). Otherwise (if it is only a notion shared among some portlet clusters) I would place the centralizing logic in each related portlet group (i.e.: teams would put it in their "infrastructure").

But if you say this is going to be temporary, I would push it like this :shrug: .

**Comment by izaera** [comment]
Let me check one thing, though... I think we may refactor the code to make it one line IINM.

**Comment by izaera** [comment]
Nope :-(

**Comment by izaera** [comment]
Shall we forward this?

**Comment by izaera** [comment]
As agreed in a private Slack conversation with @jbalsas, we are going to create a `Util` class in `portal-kernel` to hold the code.

**Comment by izaera** [comment]
Resent as https://github.com/liferay-frontend/liferay-portal/pull/780

**Pull request closed without merging**
