### PR TITLE
LPS-168776 Focus sidebar panel on open

### PR DESCRIPTION
**Pull request by carloslancha**
https://issues.liferay.com/browse/LPS-168776

Adding docs about sidebars https://liferay.atlassian.net/wiki/spaces/PEDS/pages/2289926432/Accessible+Panel+Sidebar

With this pr we must achieve the following:

- After pressing on the toggler button the focus needs be moved to the panel
- The panel needs to have tabindex="-1", role="tabpanel" and an "aria-label" that defines what is the panel about
- The panel must have a close button. The "aria-label" of that button must be "Close". When you click on it and after the panel being closed the focus needs to be moved back to the toggler button.

Modifying sidebar Tag and it's JS component affects not only these info panels but any other usage of it, like the Product Menu, so we're implementing some things to not break stuff and to make those panels benefit of these requirements.

Also, the complete fix across portal will require that Product Teams pass a new param to the Tag to set the correct aria-label of the panel, we can't infer it otherwise. In this tickets we're fixing it only for Sites.

image
image

### CODE REVIEW

**Comment by carloslancha** [comment]
ci:stop

**Comment by carloslancha** [comment]
ci:test:sf

**Comment by carloslancha** [comment]
ci:test:sf

**Comment by carloslancha** [comment]
ci:test:sf

**Comment by carloslancha** [comment]
ci:test:sf

**Comment by carloslancha** [comment]
ci:test:relevant

**Comment by carloslancha** [comment]
ci:test:relevant

**Review by bryceosterhaus — APPROVED** [review]
LGTM!

**Comment by carloslancha** [comment]
ci:forward

**Comment by carloslancha** [comment]
<a href="https://gitme.me/image?url=https%3A%2F%2Fmedia1.giphy.com%2Fmedia%2F2oUfvvUgQHnLsQWFMW%2Fgiphy.gif&token=scream" data-gitmeme-token="scream"></a>

**Comment by carloslancha** [comment]
ci:forward

**Pull request closed without merging**
