### PR TITLE
COMMERCE-4836 New Boolean Data renderer for Data Set Display

### PR DESCRIPTION
**Pull request by FabioDiegoMastrorilli**
When headless APIs returns a boolean value, data set display should be able to display it using custom labels.

This renderer was created while the migration was in progress so it's available in the old implementations but not in the new one. I also included a small fix (the "new" keyword removal) for making Price Lists working and letting QA's testing the component in a real environment

### CODE REVIEW

**Comment by FabioDiegoMastrorilli** [comment]
ci:test:sf

**Comment by FabioDiegoMastrorilli** [comment]
ci:test:relevant

**Review by wincent — APPROVED** [review]
> I also included a small fix (the "new" keyword removal)

Probably akin to what we saw in [that other PR](https://github.com/liferay-commerce/liferay-portal/pull/328); JS won't let you use the `new` operator with an arrow function, and now that we don't support IE, the browser is seeing the real arrow function instead of the transpiled not-actually-an-arrow-function version of it. There are probably a few undetected places where we're still doing this, but hopefully we'll find them all with time.

Feel free to `ci:forward` this @FabioDiegoMastrorilli. Looks good to me.

**Comment by wincent** [comment]
I edited the PR title to include the "COMMERCE-4836" ticket prefix.

**Comment by jbalsas** [comment]
If it looks good to @wincent it looks good to me!

**Comment by jbalsas** [comment]
ci:forward

**Pull request closed without merging**
