### PR TITLE
LPS-135364 CKEditor cell properties missing options in blogs

### PR DESCRIPTION
**Pull request by holatuwol**
### Steps to reproduce

1. Set the following in portal-ext.properties to switch the editor to blogs
```properties
editor.wysiwyg.portal-web.docroot.html.portlet.blogs.edit_entry.jsp=ckeditor
```
2. Start up Liferay
3. Navigate to to Blogs
4. Click on + icon to create a new blog
5. See the ckeditor in blog content
6. Add table of any number of rows and columns
7. Click inside of a cell, and right click to load the context menu
8. Select cell -> cell properties

**Expected Behavior**:
The CKeditor still has the cell property functionality that it did in dxp-12-7110 and earlier

**Actual Behavior**:
The CKeditor has very limited cell property functionality.

### Solution overview

This was caused by a CKEditor upgrade, which includes a fix for the following issue:

https://github.com/ckeditor/ckeditor4/issues/1986

Looking at all the git blame for BlogsContentEditorConfigContributor, they were added in order to handle limitations related to alloyeditor, but BlogsContentEditorConfigContributor is used by multiple editor types.

### CODE REVIEW

**Review by markocikos — CHANGES_REQUESTED** [review]
@holatuwol Allowed content is a feature of editor, regardless of implementation (ckeditor, tinymce etc.). It holds business requirements of module, being general sanity and security buffer. For example, by removing the check like in this PR, we would be able to input a `<script>` tag in ckeditor, removing a layer of security. 

What we can do is increase scope of allowed content. Using the [rule syntax](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_allowed_content_rules.html), something like `td[*]{*}` should work.

**Comment by holatuwol** [comment]
@markocikos I've applied the suggested changes.

**Comment by markocikos** [comment]
@holatuwol Looks good! There are still some formatting issues. Please fix, we can ship this after.

**Comment by holatuwol** [comment]
Fixed source formatting issues.

**Comment by holatuwol** [comment]
ci:test:sf

**Review by markocikos — APPROVED** [review]

**Comment by markocikos** [comment]
Forwarded to Lima: https://github.com/liferay-lima/liferay-portal/pull/2054

**Pull request closed without merging**
