### PR TITLE
LPS-152217: Expose ERC in WikiPageAttachment

### PR DESCRIPTION
**Pull request by sergiojimcos**
**What is new?**
- Expose **External Reference Code** in `WikiPageAttachment`.
- Endpoint implementation of `GET` and `DELETE` by **External Reference Code**.
- Including some tests in API part.
- Implement new exception: `NoSuchWikiPageAttachment`.
- Requested changes in https://github.com/brianchandotcom/liferay-portal/pull/121987
- Requested changes in https://github.com/brianchandotcom/liferay-portal/pull/122430

## SERVICE
This PR supports the implementation of external reference code in `PortletFileRepository` service to be able to GET and DELETE by external reference code. 

**NOTE:** New Exception created if a WikiPage's ERC is wrong introduced. So the `NoSuchWikiPage` will be caught indicating that there is no wiki page associated to that ERC. The same occurs when a WikiPageAttachment's ERC is not indicated well, the `NoSuchWikiPageAttachment` will be caught.

## API
In the API section, this PR contains the new endpoints to operate using the ERC:

image

To see this new endpoint you have to follow these steps:

1. Deploy `wiki-api` and `wiki-service` in this order. Later, deploy `document-library-repository-portlet-file-repository-impl`
2. Deploy `headless-delivery-api` and `headless-delivery-impl` in this order.
3. Go to `/o/api`
4. Go to `WikiPageAttachment`

**JIRA Ticket:**
https://issues.liferay.com/browse/LPS-152217

### CODE REVIEW

**Comment by sergiojimcos** [comment]
ci:test:sf

**Comment by sergiojimcos** [comment]
ci:test:relevant

**Comment by sergiojimcos** [comment]
ci:test:sf

**Comment by sergiojimcos** [comment]
ci:test:relevant

**Comment by sergiojimcos** [comment]
ci:test:relevant

**Comment by sergiojimcos** [comment]
ci:test:relevant

**Comment by mateusralv** [comment]
Ops, hey @sergiojimcos the failures is not related to your PR, I made a [comparison run with master](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=2&testrayRunIdB=1966993778&testrayRunIdA=1966967674&statusB=3) and the result is not failures uniques. 🎉

**Comment by sergiojimcos** [comment]
> Ops, hey @sergiojimcos the failures is not related to your PR, I made a [comparison run with master](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=2&testrayRunIdB=1966993778&testrayRunIdA=1966967674&statusB=3) and the result is not failures uniques. tada

Thanks Mateus!! :heart:

**Comment by sergiojimcos** [comment]
Manual forwarding to Brian: https://github.com/brianchandotcom/liferay-portal/pull/122661

**Pull request closed without merging**
