### PR TITLE
LPS-201890 Don't route CX resources through combo servlet

### PR DESCRIPTION
**Pull request by izaera**

### CODE REVIEW

**Comment by izaera** [comment]
ci:test:relevant

**Review by bryceosterhaus — APPROVED** [review]
LGTM

**Comment by andreluis2022** [comment]
I'm on it

**Comment by andreluis2022** [comment]
Hey @izaera the flaws appear to be unrelated to your changes. You can forward them if no additional developer review is required.

**Comment by izaera** [comment]
ci:forward:force

**Pull request closed without merging**
