### PR TITLE
CLDSVCS-4198 Dashboard Users Portlet Soy template Does Not Work

### PR DESCRIPTION
**Pull request by izaera**
A simple fix to account for `void` return type in `SoyTemplateRecord` (and avoiding putting it into the `HashMap`; because if it returns `void` it's clearly not a getter).

### CODE REVIEW

**Comment by izaera** [comment]
@markocikos This is the PR I was talking about.
/CC: @igorbeslic

**Comment by izaera** [comment]
ci:test:relevant

**Comment by izaera** [comment]
@igorbeslic does this look good to you? If so, I will forward it to Brian.

**Comment by igorbeslic** [comment]
Hi @izaera it is perfect. It will speed up Soy template rendering as it won't silently persist entities in the background.

Thank you very much for prompt reaction.

**Comment by izaera** [comment]
ci:forward

**Comment by izaera** [comment]
ci:forward

**Pull request closed without merging**
