### PR TITLE
LPS-128227 Links inside liferay-ui:icon-menu should contain `dropdown-item` css class

### PR DESCRIPTION
**Pull request by pat270**
https://issues.liferay.com/browse/LPS-128227

~TODO: Bookmarks Web Move to Recycle Bin link needs `dropdown-item`~ I looked high and low for this one. I just missed adding `linkCssClass="dropdown-item"` to `liferay-ui:icon-delete` 😞 .

move-to-recycle-bin

This one is another doozy. I added the class `dropdown-item` to all `liferay-ui:icon` tags inside `liferay-ui:icon-menu`. I probably missed more cases, but I tried to do a thorough find and replace.

- `liferay-rss:rss` add attribute `linkCssClass` so we can pass in classes to the `a` tag in `liferay-ui:icon`
- `liferay-ui:icon-menu` adds attribute `menuCssClass` to declare css classes on the `ul` element
- Revert "LPS-127831 liferay-ui:icon output css class `dropdown-item` if no `linkCssClass` is declared"
- `liferay-ui:icon-deactivate` adds `linkCssClass` attribute
- `aui:a` use `c-inner` pattern to prevent focus outline from showing on click
- portal-kernel MenuItem should output the class `dropdown-item` on the `a` tag

### CODE REVIEW

**Comment by pat270** [comment]
ci:test:relevant

**Comment by pat270** [comment]
@john-co @calvinctvo @zhangyan0701  I don't think these failures are related to the pull. Is it possible to get a confirmation?

**Comment by john-co** [comment]
Looks related, the tests can't find a path locator on a sidebar nav-link. For example:

[CPRolesCPBlogs#ViewBlogsEntryRegRoleInline](https://testray.liferay.com/home/-/testray/case_results/1489469850?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcases%2F1310743781%2Fview%3Fcur%3D1%26delta%3D200%26testrayCaseId%3D1310743781%26orderByCol%3DcreateDate_sortable%26orderByType%3Ddesc) is trying to click on Default User Associations but is throwing error:
```
Element is not present at "//a[contains(.,'Virtual Instance Scope')]/following-sibling::div//*[contains(@class,'nav-link') and normalize-space(./text())='Default User Associations']"
```
but based on test [screenshot](https://testray.liferay.com/reports/production/logs/test-1-17/1614301833424/test-portal-acceptance-pullrequest(master)/7321/functional-tomcat90-mysql57-jdk8/0/8/LocalFile.CPRolesCPBlogs_ViewBlogsEntryRegRoleInline/index.html.gz), it looks like the Default User Associations is present so this leads me to think something with HTML structure changed and the path locator is no longer valid. 
Selection_014

If intentional change, @zhangyan0701 can you investigate further?

**Comment by zhangyan0701** [comment]
Comparation with master upstream:
https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=3&testrayRunIdB=1492203746&testrayRunIdA=1491127433&statusB=2

There are four issues look related:

**1. Same as the issue in John's comment: locator `SystemSettings#SCOPED_CONFIGURATION_NAME` cannot be found.**

**2. Locator of role title in Control Menu > Roles cannot be found.**
Example test: [LocalFile.AssetPublisherWithWebContent#ViewWebContentViaAPAsGuestWithViewPermission](https://testray.liferay.com/home/-/testray/case_results/1491148231)


**3. Locator Panel#PANEL matches two elements in Site Settings.**
Example test: [LocalFile.SitesUseCase#AddChildSiteFromImportedSiteTemplate](https://testray.liferay.com/home/-/testray/case_results/1491155048)


**4. [Should be a regression] List icon and View icon in Workflow Task Preview page display incorrectly.**


**Expected:**


Reproduce steps:
- Go to Product Menu > Configuration > Workflow, enable Single Approver for Blogs.
- Go to Content & Data > Blogs, add a new blog entry.
- Click the user icon on the top right to open drop down menu and go to My Workflow Tasks.
- Navigate to Assigned to My Roles tab, click the Asset Title.

For different status of the tasks, there are more icons, but they all overlapped.

**Comment by pat270** [comment]
Nice! Thanks for the detailed explanation @zhangyan0701 🙏

**Comment by jbalsas** [comment]
Hey @pat270, I've amended that last commit to make it so all `liferay-ui:icon` and also similar others that extend from it, `icon-delete`, `icon-deactivate` and `icon-help` all have the `dropdown-item` class added to `linkCssClass` when inside a `liferay-ui:icon-menu`.

In this PR I see a lot of tag changes that also are seemingly unused elsewhere which I'd suggest we drop to control the scope of the changes we're applying and make this more manageable, specially as we're seeing regressions starting to appear.

I'm going to close this PR for now and send a followup just with what I think fixes the issue to verify and then we can decide to move with either of them.

**Comment by jbalsas** [comment]
Sent https://github.com/liferay-frontend/liferay-portal/pull/862, we can continue over there.

**Pull request closed without merging**
