### PR TITLE
LPS-122456 - Use buildFragment instead of a string

### PR DESCRIPTION
**Pull request by bryceosterhaus**
This was causing a failure at https://liferay.slack.com/archives/CLCD3DQLF/p1606231990095500

`append` takes a DOMString object or a node, and not just a regular string. Using buildFragment should fix this and we can just use appendChild since it only takes a node.

This is on top of brians upstream

### CODE REVIEW

**Comment by bryceosterhaus** [comment]
ci:test:sf

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
ci:test:sf

**Comment by brianwulbern** [comment]
Merged on https://github.com/brianchandotcom/liferay-portal/pull/96264

**Pull request closed without merging**
