### PR TITLE
LPS-135874 Check for anonymous users in Questions

### PR DESCRIPTION
**Pull request by LuismiBarcos**
Related ticket -> [LPS-135874](https://issues.liferay.com/browse/LPS-135874)

Reproduce this bug in the master branch is a little bit tricky because it is necessary to create a thread and set the userId to 0.
Then, just navigate to the thread created and the application will crash. With this fix, we will avoid that crash and will show an "Anonymous User" instead of the original user.

**Explanation**
Assuming that the anonymizing process could set the userId of some questions to 0, it could generate an NPE when retrieving the creator of a question.

This PR avoids that NPE and returns an empty creator instead.

Due to this empty creator, it is necessary to handle that empty creator in Questions App and show default values in that case.

### CODE REVIEW

**Comment by LuismiBarcos** [comment]
Just remark that we are assuming that the userId of the MBThread is marked as 0 if the is a GDPR request to anonymize a user. These changes should not affect the actual behavior of Questions.

**Review by javierdearcos — APPROVED** [review]
A lot of places in the frontend to check for null creator or statistics. Good work!

**Review by nhpatt — APPROVED** [review]
LGTM, nice find :D

**Comment by nhpatt** [comment]
ci:forward

**Comment by nhpatt** [comment]
ci:forward

**Pull request closed without merging**
