### PR TITLE
Urgent Accessibility HR_56 | LPS-165503 set sidenav display to none for focus accessibility

### PR DESCRIPTION
**Pull request by fortunatomaldonado**
https://issues.liferay.com/browse/LPS-165503

The issue is we are unable to `Tab` through the page since the focus would get stuck right before the right sidenav. This is due to the sidenav `visibility: hidden`.
I was able to resolve this by setting the `display: none` to the sidenav whenever it is hidden. This allows the focus to continue through the page. When it is open, I then set the `display: block`.

Please let me know if there are any questions or comments about this.
Thank you!

### CODE REVIEW

**Comment by pat270** [comment]
@fortunatomaldonado I don't think this is a `visibility: hidden` issue. `visibility: hidden` removes the element from the tab order.

> The element cannot receive focus (such as when navigating through [tab indexes](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/tabindex)).

Reference: https://developer.mozilla.org/en-US/docs/Web/CSS/visibility#values

I'm guessing we are managing the focus order some other way (maybe with JavaScript?).

**Comment by fortunatomaldonado** [comment]
Hello @pat270,

Thank you for all the information!

Yeah that makes sense. I think the time I spent on this made me crave for anything that'll work..
Do you happen to have any leads on where I should look to fix this behavior?

Thank you again for all the info!

**Comment by pat270** [comment]
@fortunatomaldonado I just built this and can't seem to find the issue. Do you have a screenshot or recording of how to reproduce it?

**Comment by fortunatomaldonado** [comment]
Hello @pat270,

Here is the issue without the fix. I am continuously pressing `Tab` and it is stuck on the Add button.

https://user-images.githubusercontent.com/31672551/196495293-9e11901e-176b-4776-a750-38829a262175.mp4



This is with my current solution being able to Tab through.

https://user-images.githubusercontent.com/31672551/196495467-45c8d3c5-355a-443a-a8ec-2c23da24445e.mp4


Let me know if there are any questions about this.
Thank you!

**Comment by pat270** [comment]
Thanks, I can reproduce it now. I have a feeling this might have something to do with the dropdown focus manager. When I press the down arrow key on the plus button, it opens the dropdown menu for the previous button. I think this might be an issue in Clay, @matuzalemsteles should be able to confirm it.

dropdown-focus

**Comment by matuzalemsteles** [comment]
Hmm this is weird, I'll try to test this later to provide some more information but it could be something with the focus manager even crashing, it's quite likely that it's trying to focus on the sidenav that wasn't visible when it's using `visibility: hidden`, we have some built-in methods to identify if an element is focusable and one of them is to try to know if the element in the DOM is visible, this works for `display: none` maybe not for `visibility: hidden`.

**Comment by matuzalemsteles** [comment]
> There is an issue when the vertical ellipsis dropdown is open, when you reach the end of the dropdown it skips to the end of the page even if there is more reachable content after.

@pat270 yes, this seems to be reproducible elsewhere too, can you file a bug in Clay so we can look into this later?

**Comment by pat270** [comment]
@matuzalemsteles I just filed an issue for that at https://github.com/liferay/clay/issues/5147.

**Comment by matuzalemsteles** [comment]
Hey @fortunatomaldonado @pat270, I managed to reproduce this in an isolated environment to test the hypotheses, this is related to the focus manager in Clay and it's also because of the use of `visibility:hidden` that it can't know if the element is visible or not , which is why `display: none` works well because internally we can identify it.

I opened an issue https://github.com/liferay/clay/issues/5148 to fix but this fix will only be available in the next Monday release, do you need it urgently or is it ok to wait during the release?

**Comment by fortunatomaldonado** [comment]
Hello @matuzalemsteles,

Truly appreciate your efforts on this!
This is urgent but as long as we get it in by Monday it should be okay.

Thank you again!

**Comment by dsanz** [comment]
@matuzalemsteles this is part of the BofA initiative, which is being prioritized company-wide. We must make sure this goes to the next clay release as we committed to have them fixed and tested by the end of october

**Comment by matuzalemsteles** [comment]
@dsanz sure, I had sent a PR yesterday to fix this https://github.com/liferay/clay/pull/5149

**Comment by dsanz** [comment]
Thanks @matuzalemsteles @pat270 !
Do you guys think this one can be closed in favor of https://github.com/liferay/clay/pull/5149?

Also, https://github.com/liferay/clay/issues/5147 looks out of the scope of this issue, though we shall fix it too

**Comment by matuzalemsteles** [comment]
@dsanz yes this PR can be closed in favor of what was fixed in Clay. https://github.com/liferay/clay/issues/5147 It's also been fixed.

**Pull request closed without merging**
