### PR TITLE
LRQA-73996 Fix widget category locator

### PR DESCRIPTION
**Pull request by susanchen3**
**Background**
Previous path that was used was [modified](https://github.com/brianchandotcom/liferay-portal/commit/9172008c7e895816d922adb64d2637918ce9bcb1) and no longer works for this test. Created a better path to target just the category subtitle.  

**JIRA Ticket:**
https://issues.liferay.com/browse/LRQA-73996

### CODE REVIEW

**Comment by susanchen3** [comment]
ci:test:frontend:nocompile

**Comment by susanchen3** [comment]
The only failing test is the MT one, quarantining it is still in bchan's queue

**Review by john-co — APPROVED** [review]
Looks good to me! :sunglasses:

**Comment by john-co** [comment]
ci:forward

**Pull request closed without merging**
