### PR TITLE
 LPS-139948 - Remove some uses of A.one in favor of js equivalents

### PR DESCRIPTION
**Pull request by kresimir-coko**
Continuation of #1547 

I fixed conflicts and tested the calendar UI which didn't produce any errors when saving an edit, or adding a new event.

There are some weird visual errors, present on `master` which aren't related to this PR.

### CODE REVIEW

**Comment by john-co** [comment]
ci:test:relevant

**Comment by kresimir-coko** [comment]
Gonna investigate the CI errors now that I've fixed the conflicts and rebased with master

**Comment by kresimir-coko** [comment]
@john-co @bryceosterhaus Here are my discoveries. Haven't got much experience reading CI/Jenkins reports but I gave it a shot.

## [LocalFile.CalendarUpgrade#ViewCalendarArchive621021](https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/11952/AXIS_VARIABLE=1/testReport/junit/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_CalendarUpgrade_ViewCalendarArchive621021_/)

This one is failing because it expects an h3 element with a `Recurring Event` label, but we don't have it present anywhere in the code, I'm not sure where it was defined before, but now it does not exist anymore. This conclusion is the same for all 3 failing tests found under the [2nd failure](https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/11952/).

## [LocalFile.CalendarManageCalendar#SearchForOtherCalendars](https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/11174/AXIS_VARIABLE=2/testReport/junit/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_CalendarManageCalendar_SearchForOtherCalendars_/)

Same as the previous error, this one expects a div with the `calendar-portlet-event` class, and there isn't a mention of one in the code.

## [LocalFile.CalendarManageEvent#DeleteRepeatingAllFollowing](https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/11174/AXIS_VARIABLE=4/testReport/junit/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_CalendarManageEvent_DeleteRepeatingAllFollowing_/)

This test is expecting an option with the text `Daily, 2 Times` under the `Repeat Every` select element, but that option is no longer present in the code.

## [LocalFile.CalendarConfiguration#ConfigureDisplayTimeZone](https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/11174/AXIS_VARIABLE=0/testReport/junit/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_CalendarConfiguration_ConfigureDisplayTimeZone_/)

This one expects a `td` element with a `Calendar Event Title` label, and it also mentions a `div.scheduler-event-content`, neither of which exist in our codebase.

## [LocalFile.CalendarCreateEvent#AddAllDay](https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/11174/AXIS_VARIABLE=0/testReport/junit/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_CalendarCreateEvent_AddAllDay_/)

This one mentions a div element with a `scheduler-event-all-day calendar-portlet-event` classes, which we don't have in our code.

## [LocalFile.CalendarCreateEvent#AddRepeatingMonthly2Times](https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/11174/AXIS_VARIABLE=0/testReport/junit/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_CalendarCreateEvent_AddRepeatingMonthly2Times_/)

This one mentions a div element with a `scheduler-event-repeated calendar-portlet-event` classes, which we don't have in our code.

## [LocalFile.CalendarStaging#InviteUserViaUnpublishedEventAndViewNoResponse](https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/11174/AXIS_VARIABLE=0/testReport/junit/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_CalendarStaging_InviteUserViaUnpublishedEventAndViewNoResponse_/)

This one mentions a div element with a `calendar-portlet-event` class, which we don't have in our code.

## [LocalFile.CalendarManageEvent#DeleteRegular](https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/11174/AXIS_VARIABLE=3/testReport/junit/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_CalendarManageEvent_DeleteRegular_/)

This one mentions a div element with a `calendar-portlet-event` class, which we don't have in our code.

**Comment by magjed4289** [comment]
ci:test:relevant

**Comment by magjed4289** [comment]
@kresimir-coko have run the test:relevant once again, as most of the tests looked incomplete. will investigate the failures once it is completed

**Comment by magjed4289** [comment]
ci:reevaluate:1287401_930

**Comment by magjed4289** [comment]
Test failures verified:

**[Related]**

- CalendarCreateEvent#AddRepeatingMonthly2Times: test run in a PR bundle locally, gives the same error as the CI run:
image
Information from the browser console:
image

Not able to create a calendar event.

[Unrelated]

- CalendarManageEvent#DeleteRepeatingAllFollowing - [3 of 400 most recent runs failed with same error](https://testray.liferay.com/home/-/testray/cases/1319821480/view?delta=200&testrayCaseId=1319821480&orderByCol=createDate_sortable&orderByType=desc&resetCur=false&cur=2)
- CalendarConfiguration#ConfigureDisplayTimeZone [3 of 400 most recent runs failed with same error](https://testray.liferay.com/home/-/testray/cases/1319846282/view?delta=200&testrayCaseId=1319846282&orderByCol=createDate_sortable&orderByType=desc&resetCur=false&cur=2)
- CalendarUpgrade#ViewCalendarArchive625 [2 of 400 most recent runs failed with same error](https://testray.liferay.com/home/-/testray/cases/1311717284/view?testrayCaseId=1311717284&delta=200&orderByCol=createDate_sortable&orderByType=desc&resetCur=false&cur=3)
- LocalFile.CalendarUpgrade#ViewCalendarArchive621021 [2 of 400 most recent runs failed with same error](https://testray.liferay.com/home/-/testray/cases/1311725440/view?delta=200&testrayCaseId=1311725440&orderByCol=createDate_sortable&orderByType=desc&resetCur=false&cur=2)
- CalendarUpgrade#ViewCalendarArchive621021 [3 of 600 most recent runs failed with same error](https://testray.liferay.com/home/-/testray/cases/1311725440/view?testrayCaseId=1311725440&delta=200&orderByCol=createDate_sortable&orderByType=desc&resetCur=false&cur=3)
- LocalFile.CalendarUpgrade#ViewCalendarArchive621015 [3 of 600 most recent runs failed with same error](https://testray.liferay.com/home/-/testray/cases/1311720559/view?delta=200&testrayCaseId=1311720559&orderByCol=createDate_sortable&orderByType=desc&resetCur=false&cur=2)

**Comment by bryceosterhaus** [comment]
cc @kresimir-coko looks like one of the failures is related "Not able to create a calendar event."

**Comment by kresimir-coko** [comment]
ci:test:sf

**Comment by kresimir-coko** [comment]
ci:test:relevant

**Comment by kresimir-coko** [comment]
ci:test:relevant

**Comment by kresimir-coko** [comment]
ci:test:relevant

**Comment by kresimir-coko** [comment]
ci:test:relevant

**Comment by john-co** [comment]
Reviewed. Test failures are related. :bug: 

see https://liferay.slack.com/archives/C3JBR21HA/p1638301389314100?thread_ts=1638173436.228800&cid=C3JBR21HA

**Comment by kresimir-coko** [comment]
ci:test:sf

**Comment by kresimir-coko** [comment]
ci:test:relevant

**Comment by kresimir-coko** [comment]
ci:test:relevant

**Comment by john-co** [comment]
From quick review, I have a feeling these test failures are unrelated. But waiting for [Testray](https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1585970427) to populate with the last test run results so I can be more certain.

**Comment by john-co** [comment]
Reviewed. Test failures are unrelated. :heavy_check_mark: 
- the lpkg test batch error from [2nd to last run](https://github.com/liferay-frontend/liferay-portal/pull/1626#issuecomment-983619739) seems like an existing bug as seen in [other PRs](https://testray.liferay.com/home/-/testray/case_results/1585977370/history?tab=result&hideFilterPin=true)
- the test failures from last run look like a bunch of fluke/flaky tests...

Ok to manually forward if ready.

**Comment by bryceosterhaus** [comment]
LGTM. I forwarded it here, https://github.com/brianchandotcom/liferay-portal/pull/110638

**Pull request closed without merging**
