### PR TITLE
LPS-156515 Make CETConfigurationFactory refresh CETManager when configuration is updated

### PR DESCRIPTION
**Pull request by izaera**

### CODE REVIEW

**Comment by izaera** [comment]
I've run `ant format-source-current-branch` in `portal-impl` and it did nothing, so the SF failure is fake.

**Comment by izaera** [comment]
ci:test:sf

**Comment by brianchandotcom** [comment]
@izaera manually merged

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Pull request closed without merging**
