### PR TITLE
LPD-35722 Required icons should be consistent

### PR DESCRIPTION
**Pull request by antonio-ortega**
Hi,

The issue here is we were using the character * to say editor's content was required, opposite to what happens in any other required field in Liferay where they are marked with an SVG icon.

Fixing that broke that test, so I fixed it in such a way we can be sure the required mark is an SVG icon now.

I thought about creating apart a specific test for this case, but I realized it would be basically the same thing, going to a page with an editor and check for required mark, so we'd be duplicating the code.

Thanks.

Regards.

### CODE REVIEW

**Comment by antonio-ortega** [comment]
ci:test:sf

**Comment by antonio-ortega** [comment]
ci:test:sf

**Review by markocikos — APPROVED** [review]
@antonio-ortega LGTM! :sparkles:

**Comment by antonio-ortega** [comment]
ci:forward

**Pull request closed without merging**
