### PR TITLE
LPS-150996 Export `sub` and import it throughout the codebase

### PR DESCRIPTION
**Pull request by kresimir-coko**
This is a plausible experiment to try and change the approach of doing what the export PR (https://github.com/liferay-frontend/liferay-portal/pull/2133) wanted to do but in a segmented manner.

Hey @bryceosterhaus, I've added a few new commits to this PR, fixing the valid CI errors where modules were overriding our `Liferay.Util.sub`, basically not allowing us to do the simple switch to the imported sub.

### The case of object-web defining types

The object-web module is defining types for the utils it is using from `frontend-js-web`, which is kinda weird, but okay. What I did is I removed that whole segment of the file, imported `frontend-js-web` and exported the getResourceURL method in our `frontend-js-web/index.d.ts` type file.

### The possible-impossible swap to imported sub

`ddm-form-web/Report.tsx` is being tested inside `ddm-form-web/test/js/pages/Report.js` where it is assigning a mock function to `Liferay.Util.sub` and I couldn’t figure out a way of making the tests pass with the imported `sub`, atleast without havily modifying the test which isn’t the scope of this task. That’s why I decided to leave the usage as is - using `Liferay.Util.sub` instead of the the imported `sub`.

The same thing is happening in `layout-content-page-editor` has the same testing issues. Gonna need the owners of that module to adapt their tests and probably do the import swap themselves.

Same thing happening inside `translation-web`

## Previous comments

Alright, so the problem with the 2 modules was that they weren't using our new modernized version of `sub` even though they use `Liferay.Util.sub`.

The `segments-experiment-web` is using [this overridden variant of Liferay.Util.sub()](https://github.com/liferay/liferay-portal/blob/master/modules/dxp/apps/segments/segments-experiment-web/jest-setup.config.js).

The `digital-signature-web` is also using some alternate version but I haven't managed to find it. All I know is that our modern `sub` function doesn't get invoked when using `Liferay.Util.sub()` inside of the module.

### CODE REVIEW

**Comment by kresimir-coko** [comment]
ci:test:relevant

**Comment by kresimir-coko** [comment]
ci:test:relevant

**Comment by kresimir-coko** [comment]
ci:reevaluate:1287401_3121

**Review by bryceosterhaus — APPROVED** [review]
LGTM!

**Comment by kresimir-coko** [comment]
ci:forward

**Comment by john-co** [comment]
ci:test:sf

**Comment by john-co** [comment]
Reviewed. Test failure looks related to changes in [frontend-icons-web](https://github.com/liferay-frontend/liferay-portal/pull/2223/files#diff-1873f1fa5842167830ebce0b9cb273615489b184573d34d00677b1ea9df0b288L98) :x:

**Comment by kresimir-coko** [comment]
@john-co Thank you!

**Comment by kresimir-coko** [comment]
ci:test:sf

**Comment by kresimir-coko** [comment]
ci:test:relevant

**Comment by kresimir-coko** [comment]
ci:stop

**Comment by kresimir-coko** [comment]
ci:test:sf

**Comment by kresimir-coko** [comment]
The CI report above is complaining about `[exec] > Task :dxp:apps:segments:segments-experiment-web:packageRunTest FAILED` but I have no changes in that module

**Comment by kresimir-coko** [comment]
Merged and pushed to fix conflicts

**Comment by bryceosterhaus** [comment]
@kresimir-coko it looks like this is also failing and I think you modified some files in that module

`Execution failed for task ':apps:digital-signature:digital-signature-web:packageRunTest'.`

**Comment by kresimir-coko** [comment]
Yea and I was wrong about `segments` one, my stuff wasn't being sorted alphabetically so it was easy to miss.

**Comment by magjed4289** [comment]
Just started reviewing :)

**Comment by kresimir-coko** [comment]
Alright, so the problem with the 2 modules was that they weren't using our new modernized version of `sub` even though they use `Liferay.Util.sub`.

The `segments-experiment-web` is using [this overridden variant of Liferay.Util.sub()](https://github.com/liferay/liferay-portal/blob/master/modules/dxp/apps/segments/segments-experiment-web/jest-setup.config.js).

The `digital-signature-web` is also using some alternate version but I haven't managed to find it. All I know is that our modern `sub` function doesn't get invoked when using `Liferay.Util.sub()` inside of the module.

**Comment by kresimir-coko** [comment]
ci:test:sf

**Comment by kresimir-coko** [comment]
ci:test:relevant

**Comment by kresimir-coko** [comment]
ci:test:relevant

**Comment by kresimir-coko** [comment]
Hey @bryceosterhaus, I've added a few new commits to this PR, fixing the valid CI errors where modules were overriding our `Liferay.Util.sub`, basically not allowing us to do the simple switch to the imported sub.

## A couple hiccups

### The case of object-web defining types

The object-web module is defining types for the utils it is using from `frontend-js-web`, which is kinda weird, but okay. What I did is I removed that whole segment of the file, imported `frontend-js-web` and exported the getResourceURL method in our `frontend-js-web/index.d.ts` type file.

### The possible-impossible swap to imported sub

`ddm-form-web/Report.tsx` is being tested inside `ddm-form-web/test/js/pages/Report.js` where it is assigning a mock function to `Liferay.Util.sub` and I couldn’t figure out a way of making the tests pass with the imported `sub`, atleast without havily modifying the test which isn’t the scope of this task. That’s why I decided to leave the usage as is - using `Liferay.Util.sub` instead of the the imported `sub`.

**Comment by kresimir-coko** [comment]
ci:test:sf

**Comment by kresimir-coko** [comment]
ci:test:relevant

**Comment by kresimir-coko** [comment]
They are related, sadly @john-co @Hijky

**Comment by Hijky** [comment]
@kresimir-coko Sorry, I didn't reply in time, I find two problems, the one is LocalFile.FrontendDataSet#ActionsCanBeCustomized, it has a issue ticket [LPS-152885](https://issues.liferay.com/browse/LPS-152885), the other one is `Failed prop type: Tooltip: prop type allowEscapeViewBox.x is invalid; it must be a function, usually from the prop-types package, but received undefined.`

**Comment by kresimir-coko** [comment]
thanks @Hijky I'll take a look

**Comment by kresimir-coko** [comment]
I've fixed conflicts and repushed. Again, ant all is successful locally.

**Comment by kresimir-coko** [comment]
ci:test:sf

**Comment by kresimir-coko** [comment]
ci:test:relevant

**Comment by kresimir-coko** [comment]
ci:reevaluate:1277401_3515

**Comment by kresimir-coko** [comment]
ci:test:relevant

**Comment by kresimir-coko** [comment]
ci:test:relevant

**Comment by magjed4289** [comment]
ci:test:acceptance-functional

**Comment by kresimir-coko** [comment]
ci:reevaluate:1357401_1707

**Comment by kresimir-coko** [comment]
@magjed4289 what's our takeaway from this result?

**Comment by kresimir-coko** [comment]
I just rebased and pushed to fix conflicts

**Comment by magjed4289** [comment]
Just started reviewing :)

**Comment by magjed4289** [comment]
ci:test:frontend

**Comment by kresimir-coko** [comment]
Pushed to fix conflicts. @magjed4289 I don't see any connection between the errors any anything I changed.

**Comment by magjed4289** [comment]
failures not related to the PR. OK to manually forward. ✅

**Comment by kresimir-coko** [comment]
ci:sf

**Comment by kresimir-coko** [comment]
ci:test:sf

**Comment by kresimir-coko** [comment]
ci:test:sf

**Comment by kresimir-coko** [comment]
ci:forward

**Comment by kresimir-coko** [comment]
ci:stop

**Comment by kresimir-coko** [comment]
ci:close

**Comment by kresimir-coko** [comment]
ci:reopen

**Comment by kresimir-coko** [comment]
ci:forward

**Pull request closed without merging**
