### PR TITLE
LPS-152618 Run upgrade tests on release without hypersonic

### PR DESCRIPTION
**Pull request by susanchen3**
**Background**
RemoteAppsUpgrade#CanViewRemoteAppFieldsAfterUpgrade73101 and RemoteAppsUpgrade#CanViewRemoteAppCustomElementPortletAfterUpgrade7413 don't have a hypersonic db zip. 

**Test Plan:**
Have these tests running on release without the hypersonic db by setting `app.server.types` and not specifying the hypersonic `database.type`

```
    test.batch.run.property.query[functional-bundle-tomcat-hypersonic20-jdk8][portal-release][dxp]=\
        (\
            (environment.acceptance == true) AND \
            (portal.release == true)\
        ) OR \
        (\
            (app.server.types ~ tomcat) AND \
            (\
                (database.types == null) OR \
                (database.types ~ hypersonic)\
            ) AND \
            (portal.release == true)\
        )
```

**JIRA Ticket:**
https://issues.liferay.com/browse/LPS-152618

### CODE REVIEW

**Comment by susanchen3** [comment]
ci:test:frontend:nocompile

**Review by john-co — APPROVED** [review]
Looks good to me! :sunglasses:

**Comment by john-co** [comment]
hmm...the two tests we're trying to fix here failed in the last run...are they related to hypersonic db?

**Comment by john-co** [comment]
Reviewed. Test failures are unrelated. :heavy_check_mark: 

- hypersonic db not run in last test suite. Looks like flaky tests with vanilla counter and Oracle19 issue https://issues.liferay.com/browse/LPS-144918

**Comment by john-co** [comment]
ci:forward

**Pull request closed without merging**
