### PR TITLE
LPS-125269 Fix grid/container spacing in modules

### PR DESCRIPTION
**Pull request by pat270**
https://issues.liferay.com/browse/LPS-125269

Combing through portal trying to unify container classes and removing old container related css. I rearranged a lot of container classes using `container-view` and `container-form-lg` where applicable. There were so many odd uses of containers that I couldn't catch them all.

I also tried to fix the info panels not aligning all the way to the right in admin view, but I'm sure I missed some.

- liferay-ui:search-iterator use container-view to space tables, cards, and list always
- Content Dashboard Web update container classes to properly space tables and sheets according to Lexicon specs
- liferay-frontend:edit-form use container-fluid container-fluid-max-xl and remove container-view. Spacing gets really inconsistent since this tag is used in modals and regular pages. This tag should be spaced using the class lfr-form-content inside modals.
- Account Admin details should have space between sheet and navigation-bar

### CODE REVIEW

**Comment by pat270** [comment]
ci:test:sf

**Comment by pat270** [comment]
ci:test:relevant

**Comment by pat270** [comment]
ci:stop

**Comment by pat270** [comment]
ci:test:sf

**Comment by pat270** [comment]
ci:test:relevant

**Comment by pat270** [comment]
The unique failure might be related to https://github.com/liferay-frontend/liferay-portal/pull/666/commits/031a9306e09f0273dcbc35bc026ddd6455bb59fc.

**Comment by pat270** [comment]
@zhangyan0701 @PablitoBonito can we take a look at the test failure when either of you have time?

**Comment by zhangyan0701** [comment]
ci:test:bundle

**Comment by zhangyan0701** [comment]
Failure LocalFile.PGWiki#AddPageWithChildPage is a Test Fix.

Resend in https://github.com/liferay-frontend/liferay-portal/pull/690 and re run the test.

**Comment by pat270** [comment]
Thanks @zhangyan0701 ! I'm going to close this one out.

**Pull request closed without merging**
