### PR TITLE
LPS-131381 Fix site selection in asset-libraries

### PR DESCRIPTION
**Pull request by julien**
We were using the `customSelectEvent` prop in our `openSelectionModal`,
but in this case, it will cause the issue described in
[LPS-131831](https://issues.liferay.com/browse/LPS-131381).

**Before**

**After**

**Test plan**:
- From the **Global Menu**, select the **Control Panel** tab
- Navigate to **Sites** > **Sites**
- Create a new **Site**
- From the **Global Menu**, select the **Applications** tab
- Navigate to **Content** > **Asset Libraries**
- Create a new **Asset Library**
- Select the **Sites** tab
- Click on the **Add** button to the right of **Connected Sites**
- Select the **Site** you created previously
- Assert that the site you created previously is listed in the
  **Connected Sites** section.

### CODE REVIEW

**Review by kresimir-coko — APPROVED** [review]
Looks better than this frog with a strawberry on it's head 👍

**Comment by julien** [comment]
@kresimir-coko I actually find the frog with the strawberry "hat" quite cool

**Comment by kresimir-coko** [comment]
That means your PR is even cooler

**Review by markocikos — APPROVED** [review]
@julien  LCoolTM!

I was concerned that this falls under https://github.com/liferay-echo/liferay-portal/pull/4214, and we would have double events. But, it looks like those are different site selections.

@kresimir-coko let's make sure we cover all site selection usages in the next PR. Each one we miss will end up as a bug like this one, or https://issues.liferay.com/browse/LPS-130400

**Comment by julien** [comment]
> I was concerned that this falls under liferay-echo#4214, and we would have double events. But, it looks like those are different site selections.
@markocikos thanks for the info, just because I'm curious I'll have a look at that too: I was also worried we could break something I hadn't taken into account.

**Comment by markocikos** [comment]
> just because I'm curious I'll have a look at that too

@julien Sorry for not providing more details. In the migration epic, we are removing `selectEntityHandler`s, replacing them with ootb `openSelectionModal` behavior.
1. Before our epic, in this usage we were using `selectEntityHandler`. THe default `openSelectionModal` behavior was disabled,  with `customSelectEvent`.
2. Krešo removed `selectEntityHandler` but missed this usage. Usage still had disabled `openSelectionModal` behavior, so nothing happened on click.
3. The same events happened on _different_  site selection. That resulted in LPS-130400, where Echo reverted the original commit.
4. I was concerned they are the same modal. This would mean that the other site selection still has `selectEntityHandler`. After this PR, we would have two events triggering and I'm not sure what would happen. Likely some breakage.
5. But, they are not the same modal, so we're ok to move forward with this PR.
6. We should be more careful not to miss usages like in above two cases.

**Comment by julien** [comment]
@markocikos thanks a lot for the detailed "report".
Totally agree on being very careful about this in the future, I'll have it on my radar - or checklist.

**Comment by julien** [comment]
Since this fixes an FP4 and we have 2 approvals, I'm forwarding this right now, even though I said, ["I shouldn't forward my own stuff"](https://github.com/liferay-frontend/liferay-portal/pull/984#issuecomment-828519652)

**Comment by julien** [comment]
ci:forward

**Pull request closed without merging**
