### PR TITLE
LPS-125136 - Remove references to metal-promise

### PR DESCRIPTION
**Pull request by bryceosterhaus**
Removes all references to metal-promise as a dependency

https://issues.liferay.com/browse/LPS-125136

### CODE REVIEW

**Comment by john-co** [comment]
Reviewed. Test failures are unrelated. :heavy_check_mark: 
- modules semantic versioning is a recent failure affecting upstream and other PRs
https://liferay.spiraservice.net/16/TestCase/229530.aspx
- the same error is appearing on the js-unit batch which is unrelated. It appeared on a recent upstream batch but other PRs seem to be fine...so it may have been recently fixed. https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/375000/consoleFull

**Comment by bryceosterhaus** [comment]
I had missed a reference in commerce, not really sure how. rerunning tests now

**Comment by bryceosterhaus** [comment]
ci:test:sf

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Review by jbalsas — COMMENTED** [review]
Removing this without also removing it from the preset at https://github.com/liferay/liferay-frontend-projects/blob/master/projects/npm-tools/packages/npm-bundler-preset-liferay-dev/config.json#L49 can cause issues where modules will try to load `metal-promise` from `frontend-js-metal-web` but we're no longer including it.

I think some have already been forwarded, so I'd suggest just removing the whole `imports` section in the preset so we're sure that any leftover dependencies will at least be able to properly function.

This would lead to us completely removing the `frontend-js-metal-web` module once we're done, which is desirable but I think @dsanz had some concerns about it.

**Comment by bryceosterhaus** [comment]
@jbalsas are you saying remove the whole `frontend-js-metal-web` config in the preset? Or just the `metal-*` references?

**Comment by jbalsas** [comment]
> @jbalsas are you saying remove the whole frontend-js-metal-web config in the preset? Or just the metal-* references?

Yes, I would say all of it. We can start just removing one by one in case we see that causes issues. The `incr-dom` and `metal-soy` packages could be problematic but since our Soy usage is very restricted and we already applied some failsafe mechanisms in the past, it might just be ok.

**Comment by jbalsas** [comment]
Answering https://github.com/liferay-frontend/liferay-portal/pull/674#discussion_r555747197 I realized that removing the imports can break older branches if backported since the configuration will no longer share the metal imports.

Options:
- Do nothing. This means that no one can use `metal-promise` or other `metal` modules defined in the preset in `master` and moving forward
- Somehow branch https://github.com/liferay/liferay-frontend-projects/blob/master/projects/npm-tools/packages/npm-bundler-preset-liferay-dev/config.json so we can apply different presets in different versions of DXP. This could be akin to what @wincent did for formatting.

Seeing as @izaera is almost done (😂 ) with the new bundler architecture which should render `imports` useless, I'd vote to do nothing for now 🤷

**Comment by jbalsas** [comment]
ci:forward

**Comment by wincent** [comment]
> * This could be akin to what @wincent did for formatting.

That's [`getDXPVersion()`](https://github.com/liferay/liferay-frontend-projects/blob/6252b50e2082f30c6f438cf59a1b2b17d1b1e0b3/projects/npm-tools/packages/npm-scripts/src/utils/getDXPVersion.js), just in case somebody stumbles across this in the future.

**Pull request closed without merging**
