### PR TITLE
LPS-138412 Disable isolation from modals created from render_portlet

### PR DESCRIPTION
**Pull request by diegonvs**
When using `cadmin` inside modals, it can hide CKEditor portlet view

Steps to reproduce:

1. Go to Wiki/Knowledge Base
2. Click in three-dot button near user avatar button
3. Open "Configuration"
4. Select the tab "Article/Page Added Email" and see there is a missing rich text editor there.

Here is the fixed version:

Screen Shot 2021-09-02 at 17 11 23

### CODE REVIEW

**Comment by diegonvs** [comment]
ci:test:relevant

**Comment by diegonvs** [comment]
ci:reevaluate:1287401_109

**Comment by john-co** [comment]
- [Test history](https://testray.liferay.com/home/-/testray/cases/1310700773) of PortalSmokeUpgrade#ViewPortalSmokeArchive621021 shows the test has been failing with the same error message inconsistently. cc/ @vicnate5

**Comment by vicnate5** [comment]
@john-co Thanks https://issues.liferay.com/browse/LRQA-69822

**Comment by diegonvs** [comment]
Sent: https://github.com/brianchandotcom/liferay-portal/pull/106668

**Comment by diegonvs** [comment]
Reopening because I would like to hear at least one feedback before sending manually.

**Comment by diegonvs** [comment]
ci:test:relevant

**Comment by matuzalemsteles** [comment]
I took a quick look I don't see a problem with the code but I have no knowledge to say if it would be the ideal place to pass this property or there is no other place, so for me, you could send it straight to Brian.

**Comment by julien** [comment]
@diegonvs tested this change and it does fix the issue, I'm OK with this.

**Comment by diegonvs** [comment]
Sending to our beloved BC
image

Link: https://github.com/brianchandotcom/liferay-portal/pull/106714

**Pull request closed without merging**
