### PR TITLE
[7.4-only] LPS-121950 Replace horizontal-card-v2 usages in journal-web

### PR DESCRIPTION
**Pull request by carloslancha**
__IMPORTANT: THIS PR IS NOT TO BE FORWARDED BUT SENT TO ECHO TEAM__

Added here [this commit](https://github.com/liferay-frontend/liferay-portal/pull/523/commits/1b7e67f85df44d66fafcc70bf4cf7995c346cc1d), needed to make actions menu work.

Before:
image

After:
image

### CODE REVIEW

**Comment by carloslancha** [comment]
ci:test:sf

**Comment by carloslancha** [comment]
ci:test:relevant

**Comment by carloslancha** [comment]
ci:test:relevant

**Review by julien — APPROVED** [review]

**Comment by julien** [comment]
ci:test:relevant

**Review by markocikos — APPROVED** [review]
LGTM! :+1:

**Comment by carloslancha** [comment]
Will resent directly to Echo Team with other related issues once https://github.com/liferay-frontend/liferay-portal/pull/534 is merged. Closing this.

**Pull request closed without merging**
