### PR TITLE
LPS-145457 Allow UPSERT updateStrategy for Object entries

### PR DESCRIPTION
**Pull request by ccorreagg**
This PR contains the code to allow `updateStrategy == "UPSERT"` when creating Object entries from the `create` method of the `VulcanBatchEngineTaskItemDelegate` interface, for both type of objects:

- with scope field
- without scope field 

REST Builder includes the method `putByExternalReferenceCode` as one of the methods that might be invoked when trying to create a collection of elements from the Batch engine (from the `create` method of the `VulcanBatchEngineTaskItemDelegate` interface).

**Before the PR:**

1. The `create` method of the `BaseObjectEntryResourceImpl` class does not include code to manage `updateStrategy == "UPSERT"`
2. The overriden `create` method of the `ObjectEntryResourceImpl` class does not include code to manage `updateStrategy == "UPSERT"`
3. Both, with or without scope field Objects are being managed in the `ObjectEntryResourceImpl` class and the functionality from the parent is overriden completely.

**After the PR:**

1. The `create` method of the `BaseObjectEntryResourceImpl` class includes code to manage `updateStrategy == "UPSERT"` for Object entries **without scope field**.
2. The overriden `create` method of the `ObjectEntryResourceImpl` class include code to manage `updateStrategy == "UPSERT"` for Object entries **with scope field**.
3. The Objects **with scope field** are managed in the `ObjectEntryResourceImpl` and the Objects **without scope field** are managed in the parent class `BaseObjectEntryResourceImpl`

### CODE REVIEW

**Comment by ccorreagg** [comment]
cc/ @gabrielwas

**Review by LuismiBarcos — APPROVED** [review]
LGTM :)
👏 👏 👏 👏

**Comment by ccorreagg** [comment]
> Should we forward this to Brian or are we waiting for the OK of the Objects team?

I talked to Gabriel via slack and he is going to review the PR and if he agrees, he will forward to Brian

**Comment by gabrielwas** [comment]
Thanks @ccorreagg and @LuismiBarcos! Good! 👏👏

cc @marco-leo

**Comment by gabrielwas** [comment]
ci:forward

**Pull request closed without merging**
