### PR TITLE
LPS-148445 Webpack based build MVP

### PR DESCRIPTION
**Pull request by izaera**
Resend of https://github.com/liferay-frontend/liferay-portal/pull/2013

### CODE REVIEW

**Comment by john-co** [comment]
ci:test:relevant

**Comment by john-co** [comment]
ci:test:relevant

**Comment by john-co** [comment]
ci:test:sf

**Comment by john-co** [comment]
ci:test:sf

**Comment by diegonvs** [comment]
Hey @izaera, I really liked it! but when testing yesterday I notice inside type=module resources we still calling `Liferay.Loader.require`. Probably I'm missing context but why using amd-loader inside these files still necessary?

**Comment by izaera** [comment]
Hey @diegonvs, we still use the AMD loader because, until we migrate all projects in liferay-portal, we need to have some of them in AMD, others in ESM, and both models should see each other, so we have to bridge from ESM to AMD.

Once everything is migrated, we will remove those and maybe leave the AMD loader support for compatibility reasons. But we won't use it internally any more. That's the plan...

**Comment by izaera** [comment]
ci:test:relevant

**Comment by diegonvs** [comment]
> Once everything is migrated, we will remove those and maybe leave the AMD loader support for compatibility reasons. But we won't use it internally any more. That's the plan...

Interesting! :poggers:

**Comment by michaelhashimoto** [comment]
ci:stop

**Comment by michaelhashimoto** [comment]
ci:test:relevant

@izaera - I am re-running this, this will fail due to this error:
https://liferay.slack.com/archives/C19PWQ74J/p1648484921625339?thread_ts=1648463797.215559&cid=C19PWQ74J

Thanks!

**Comment by izaera** [comment]
I don't get any CI errors in my local installation so I need some help from QA again :-)

**Comment by magjed4289** [comment]
ci:test:acceptance-release

**Comment by magjed4289** [comment]
ci:reevaluate:1347401_1394

**Comment by magjed4289** [comment]
Just started reviewing :)

**Comment by magjed4289** [comment]
Just started reviewing :)

**Comment by magjed4289** [comment]
Just started reviewing :)

**Comment by izaera** [comment]
Resent as https://github.com/liferay-frontend/liferay-portal/pull/2080

**Pull request closed without merging**
