### PR TITLE
LPS-143975 Add test for related objects in GraphQL

### PR DESCRIPTION
**Pull request by LuismiBarcos**
Related ticket -> [LPS-143975](https://issues.liferay.com/browse/LPS-143975)
Requested [here](https://github.com/brianchandotcom/liferay-portal/pull/119066#issuecomment-1159344868)
____
This PR adds some tests to check the related object GraphQL queries.

To do that, it was necessary to add some logic to re-deploy the object definitions when a many-to-many relationship is created.

### CODE REVIEW

**Comment by LuismiBarcos** [comment]
Things to consider:
* I know that I am repeating code when doing the GraphQL query. I could extract that to a common method but I didn't do that because I preferred that each test was the owner of its call. I don't know if it is a good approach.
* I modify some object-service to re-deploy the object definitions when a many-to-many relationship is created. When the PR has the ok of our team, we should ping the objects team to validate that logic. I supposed that there is a better way but I am a little bit out of context 😅 
* I am a really bad name setter 😅

**Review by javierdearcos — APPROVED** [review]
Nice! 🎉

**Comment by LuismiBarcos** [comment]
@gabrielwas, before sending this, could you take a look at this [commit](https://github.com/liferay-frontend/liferay-portal/pull/2404/commits/a0210d1a8de39e202690b71c6483ed7dee954cb5)? Just to ensure that I am not breaking anything.

**Comment by LuismiBarcos** [comment]
Ok, thanks @gabrielwas 🙂

**Comment by LuismiBarcos** [comment]
ci:forward

**Comment by javierdearcos** [comment]
Mmm test failures could be related. We should give it a look (although is weird as last test execution was ok)

**Comment by LuismiBarcos** [comment]
Rebasing and trying again. I am not able to reproduce it local 🤷‍♂️

**Comment by LuismiBarcos** [comment]
ci:forward

**Comment by LuismiBarcos** [comment]
ci:forward

**Pull request closed without merging**
