### PR TITLE
LPS - 166501 | Fix path used in OrderButtonAsAToggleCanDisplayTooltip test

### PR DESCRIPTION
**Pull request by mateusralv**
**Background**
Fix related to ManagementToolbar#OrderButtonAsAToggleCanDisplayTooltip test according to this [comment](https://github.com/liferay-frontend/liferay-portal/pull/2749#issuecomment-1284645658)

**JIRA Ticket**
https://issues.liferay.com/browse/LPS-166501

### CODE REVIEW

**Comment by mateusralv** [comment]
ci:test:relevant

**Comment by john-co** [comment]
ci:test:frontend:nocompile

**Comment by john-co** [comment]
Remember to include evidence that the test passes local poshi or CI.

**Review by john-co — APPROVED** [review]
Nice. Looks good to me! :sunglasses:

**Comment by john-co** [comment]
Looks like the assertion is still failing. Possibly reverted back to Sort?

**Comment by john-co** [comment]
Reviewed. Test failures are related. :x:  

[Related]
- [LocalFile.ManagementToolbar#OrderButtonAsAToggleCanDisplayTooltip](https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/110558//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_ManagementToolbar_OrderButtonAsAToggleCanDisplayTooltip_) need to update the value to use `Order` instead of `Sort`

[Unrelated]
- [LocalFile.RemoteApps#HasMandatoryFieldErrorMessagesWhenEmpty](https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/117234//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_RemoteApps_HasMandatoryFieldErrorMessagesWhenEmpty_) - existing known failure on upstream

**Comment by john-co** [comment]
ci:test:frontend

**Comment by john-co** [comment]
ci:test:frontend:nocompile

**Comment by john-co** [comment]
Hmm...it's `Reverse Sort Direction` when I tested on local instance...this looks like a regression when I'm reviewing design docs from here: https://liferay.atlassian.net/wiki/spaces/ENGLEXICON/pages/1948713684/LEXI-1253+Split+Filter+and+Order#Case%3A-Single-Order-Field

cc/ @izaera can you include a fix for this? I'm going to change https://issues.liferay.com/browse/LPS-166501 to a bug.

**Comment by john-co** [comment]
ci:test:frontend:nocompile

**Comment by john-co** [comment]
ci:forward

**Pull request closed without merging**
