### PR TITLE
LPD-31736 - Add unit test

### PR DESCRIPTION
**Pull request by bryceosterhaus**
Follow up PR that was requested here, https://github.com/brianchandotcom/liferay-portal/pull/152437#issuecomment-2236109630

This is my first time with a java unit test, so I think I did this right, but not totally positive.

### CODE REVIEW

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by izaera** [comment]
ci:test:relevant

**Comment by izaera** [comment]
If the test works, it LGTM

**Comment by bryceosterhaus** [comment]
ci:forward

**Pull request closed without merging**
