### PR TITLE
LPS-142294 Add Frontend Data Set app release metadata

### PR DESCRIPTION
**Pull request by markocikos**
JIRA: https://issues.liferay.com/browse/LPS-142294

I tried to sneak this in as a part of https://github.com/liferay-frontend/liferay-portal/pull/1639, but that PR has [delays](https://github.com/brianchandotcom/liferay-portal/pull/109695#issuecomment-965089227). Release team needs this metadata asap.

/cc @carloslancha @tinycarol @javierdearcos

### CODE REVIEW

**Comment by markocikos** [comment]
ci:forward

**Comment by markocikos** [comment]
ci:forward

**Comment by john-co** [comment]
contacted ci channel: https://liferay.slack.com/archives/CL3TWSMHQ/p1636582827089900

**Comment by michaelhashimoto** [comment]
ci:forward

**Pull request closed without merging**
