### PR TITLE
LPS-196133 Temporarily fix issues with d3 npm package

### PR DESCRIPTION
**Pull request by izaera**
This fixes the failures in LPS-196133 by not deduplicating the d3 packages. This way the consumers of those packages will have their own copy of them in AMD format and won't be hit by LPS-196820 that only happens in ESM flavour.

When LPS-196820 is fixed we will deduplicate d3 packages again.

### CODE REVIEW

**Comment by dsanz** [comment]
LGTM ;)

**Comment by dsanz** [comment]
@CarlosBrichete would you mind checking the related failures in this PR? Thanks a lot

**Comment by riccardo-alberti** [comment]
ci:test:commerce-functional

**Comment by andreluis2022** [comment]
I'm on it!

**Comment by dsanz** [comment]
ci:reevaluate:1277401_10090

**Comment by victoroscuro** [comment]
Checking the commerce-functional suite results

**Comment by victoroscuro** [comment]
@dsanz @izaera 
Failures are unrelated to the changes made for the PR. The failed tests due to the 2 bugs now pass! This can be forwarded. Thanks.

**Comment by izaera** [comment]
ci:forward:force

**Comment by izaera** [comment]
Forwarding per https://liferay.slack.com/archives/CLA7D1CNL/p1695369003607459?thread_ts=1694596638.697389&cid=CLA7D1CNL

**Comment by CarlosBrichete** [comment]
Hey @dsanz, failures seem to be unrelated, LGTM :)

**Pull request closed without merging**
