### PR TITLE
LPS-133007 Fix Page structure tree dnd in page editor

### PR DESCRIPTION
**Pull request by victorg1991**
This pr https://github.com/liferay-frontend/liferay-portal/pull/1063 caused a regression in the page editor. It is not possible to drag and drop element in the page structure tree, which is using this Treeview component

Removing the preventDefault makes fix the regression and also doesn't cause the bug that the previous pr was solving :)

### CODE REVIEW

**Comment by markocikos** [comment]
@georgel-pop-lr please take a look. This does seem to work. Was there a reason for `preventDefault`, or was it just an optimization  to avoid focus action?

**Comment by georgel-pop-lr** [comment]
> @georgel-pop-lr please take a look. This does seem to work. Was there a reason for `preventDefault`, or was it just an optimization to avoid focus action?

Hi @markocikos,

The all idea was not to call onFocus event, but seems to work without it, I don't see the double focus as we discovered while testing.

Regards.

**Comment by markocikos** [comment]
@georgel-pop-lr Oh I understand what is happening. The mouse event we added does the proper dispatch and sets `hadFocus` to true. With that, nothing happens on focus. The original solution was controlling this on a lower lever, so we needed to break the event with `preventDefault`.

This is much better solution, where we can allow normal flow of events. If somebody asks, completely planned! :sweat_smile: 

Yeah, we can push this, no problem.

**Comment by markocikos** [comment]
ci:forward

**Review by markocikos — APPROVED** [review]

**Comment by markocikos** [comment]
Failures are clearly unrelated. I'll try one more time, will manually forward if it fails. This is a very safe PR.

**Comment by markocikos** [comment]
ci:forward

**Pull request closed without merging**
