### PR TITLE
LPS-113552 Deprecated and replaced Liferay.Alert usages with Liferay.Util.openToast

### PR DESCRIPTION
**Pull request by wincent**
Rebase of: https://github.com/liferay-frontend/liferay-portal/pull/7

To resolve conflicts with: https://github.com/brianchandotcom/liferay-portal/pull/90226

And to fix bugs; specifically, see: https://github.com/liferay-frontend/liferay-portal/commit/793a105753828283a0169eb22f6a496d6a5ef67f

cc @diegonvs

Original message follows.

---

Originally: https://github.com/wincent/liferay-portal/pull/334

Forwarding this here to keep everything under liferay-frontend user.

cc @diegonvs 

Original message follows.

---

## AUI liferay-alert Deprecation

When rendering the component, running:

```js
AUI().use('liferay-alert', () => {
   new Liferay.Alert({
        closeable: true,
        delay: {
            hide: 3000,
            show: 0,
        },
        duration: 500,
        message: 'can you hear me major tom?',
        type: 'danger',
	}).render();
});
```

I noticed that styles of Alert are very similar to openToast:

However, liferay-alert has wrong styles. So, a migration for using  `openToast` will be nicer for improving not just the style but deprecating an old AUI component.

### Finding the usages “grepping”:

- [`git grep '\bLiferay\.Alert\b'`](https://gist.github.com/diegonvs/597f519da80e4bf5d51e42c24718280c)
- [`git grep liferay-alert`](https://gist.github.com/diegonvs/319b589500c725297a3ee9e9e9fb7ce2)

`liferay-logo-editor` AUI component is currently using `liferay-alert` and was replaced with `openToast`. This alert don’t have a title, by default the `openToast` command adds a `Success` title. This behaviour was changed here: [LPS-113582|LPS-113583 Replaces the usages of `Liferay.Notification` and `Liferay.Notice`  with `Liferay.Util.openToast` by diegonvs · Pull Request #309 · wincent/liferay-portal · GitHub](https://github.com/wincent/liferay-portal/pull/309/commits/c71c41b4f5dd3fae956b8b92c67ac05545493f33#diff-112d3d1fda54125b4833c896715647c3R28)

## API Usages:

/I noticed for some examples, an element or a selector is being passed to the component (via render function) and the toast will open near this element.

Considering this, I’m using the openToast like:

```js
Liferay.Util.openToast(
	{
		message: 'aaaa',
		containerId: 		'_com_liferay_dynamic_data_mapping_form_web_portlet_DDMFormAdminPortlet_-container'
	})
```

Or 

```js
Liferay.Util.openToast(
	{
		message: 'aaaa',
		container: document.querySelector('.portlet-column')
	})
```

Or 
```js
Liferay.Util.openToast({
	message: 'aaaaaaa',
	container: instance.node
});
```

`liferay-notification` AUI Plugin also depends on `liferay-alert`. However this plugin was deprecated at https://github.com/wincent/liferay-portal/pull/309.

`ImageEditor` component was using `liferay-alert` dynamic requiring the module using `AUI().use`. The usage can be easily replaced with `openToast`.

On `journal_template.jsp`, the plugin was easily replaced. The alert element inserted to the templatePreview doesn’t have the function of Liferay.Alert and don’t depend on it.

On `add_layout.jsp`, it was very easy for change to replace and I also changed the script tag from `aui:script` to `script`. Since `liferay-alert` dependency is not being used more.

On `add_site_navigation_menu_item.jsp`, I conducted the same as the JSP above.

On `portal-workflow-web`, it was quickly replaced by `Liferay.Util.openToast`.

On `calendar-web`, I noticed that they gives a container to the Alert component. e.g `instance.get(‘rootNode) `. I solved this using `instance.get('rootNode')._node` that returns the corresponding DOM element of the Y.Node. Also, `showAlert` was changed from `Y.Alert` to openToast.

## Questions:

There are some cases using data-dismiss=“liferay-alert”. Is this alert support depending on `liferay-alert` or `aui-alert`? cc @markocikos

### CODE REVIEW

**Comment by wincent** [comment]
ci:test:sf

**Comment by wincent** [comment]
ci:test:relevant

**Comment by wincent** [comment]
I would normally forward a PR like this one that [has previously had QA folks comment on it](https://github.com/liferay-frontend/liferay-portal/pull/7) confirming that test failures are unrelated, but in this case, there were many merge conflicts during rebase and I always thinks its good to have a second pair of eyes on it.

@jbalsas: Would you mind taking a look at my changes in https://github.com/liferay-frontend/liferay-portal/pull/24/commits/793a105753828283a0169eb22f6a496d6a5ef67f to sanity check? — that's the only file that had conflicts in it. End result [looks like this](https://github.com/liferay-frontend/liferay-portal/blob/793a105753828283a0169eb22f6a496d6a5ef67f/modules/apps/frontend-js/frontend-js-web/src/main/resources/META-INF/resources/liferay/toast/commands/OpenToast.es.js).

I'm still not in love with the API of this whole thing (the way it takes `container` *or* `containerId`, the way the name `container` is so overloaded, the way we leave little turds in the DOM when showing a toast in a custom container etc). In a perfect world, we'd just make all the call sites provide a proper container. Sigh, but this thing has been baking for so long that it's hard to feel excited about working on it further.

**Comment by wincent** [comment]
Direct link to comparison showing changes relevant to this PR, ignoring stuff that is still currently only in brianchandotcom: https://github.com/liferay-frontend/liferay-portal/compare/00f476af0eef87bb093a6692880a08a8e58a22d1...793a105753828283a0169eb22f6a496d6a5ef67f

**Comment by wincent** [comment]
ci:test:bundle

**Comment by wincent** [comment]
Test failures look unrelated, but there are conflicts now anyway, so rather than analyze them further, going to fix the conflicts and re-try.

**Comment by wincent** [comment]
ci:test:sf

**Comment by wincent** [comment]
ci:test:relevant

**Comment by wincent** [comment]
[All passed](https://github.com/liferay-frontend/liferay-portal/pull/24#issuecomment-646105439), not even any failures in common with upstream, so going to forward. I am aware we also have https://github.com/liferay-frontend/liferay-portal/pull/39 in flight, which also touches `OpenToast.es.js`, but they don't look like they are going to conflict, and even if they did, that one might need a bit more discussion first. Also aware that there seem to be regression bugs open in [LPS-113582](https://issues.liferay.com/browse/LPS-113582) related to [the bit of LPS-113582 that already merged to master](https://github.com/brianchandotcom/liferay-portal/pull/90226), but I am concerned that if we let this stay in code review too long we're just going to wind up having to do it all over again. It's been baking for 12 days now (since https://github.com/wincent/liferay-portal/pull/334), so I'd rather just ship it. We still have two days left of ["stabilization"](https://liferay.slack.com/archives/CLZFQCNHW/p1590776189029200).

**Comment by jbalsas** [comment]
> Would you mind taking a look at my changes in 793a105 to sanity check?

Done, it all makes sense to me.

> In a perfect world, we'd just make all the call sites provide a proper container.

Ugh, yeah... if we'd been taking `container` from the beginning then it would've been probably much easier, but the fact that we used to take `containerId` first makes this all weird :sob:

> [...] so I'd rather just ship it. We still have two days left of "stabilization".

Let's go for it! 👍

**Comment by wincent** [comment]
ci:forward

**Pull request closed without merging**
