### PR TITLE
[TS] LPS-174303 Fix input move boxes btn-up

### PR DESCRIPTION
**Pull request by Vy-CES**
Hi team, this is a branched-off from this LPS: https://issues.liferay.com/browse/LPS-171761. 

Where we fix the reorder buttons on selecting multiple options on the left box.

Please reproducible steps: https://issues.liferay.com/browse/LPS-174303.

Please review it and give me your feedback!

Thanks,
CC: @locpham97

### CODE REVIEW

**Comment by eltonccdantas** [comment]
I'll take a look at it

**Comment by eltonccdantas** [comment]
Hey @Vy-CES , I've analyzed your pull request, according to this [comparison](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=2&testrayRunIdB=2185100418&testrayRunIdA=2183964678&statusB=3), I found some errors related to it. 
It affects the `@disabled` fieldset on some tests like:

AssetPublisher#RestoreConfigurationTemplate
AssetPublisher#SelectWebContentArticleAsAssetType
AssetPublisherUseCase#DisableShowContentAddButton
AssetPublisherUseCase#DisplayCollectionInAssetPublisher
AssetPublisherUseCase#EditMessageBoardThreadReplyViaAP
AssetPublisherUseCase#FilterAndOrderAssetsByField
AssetPublisherUseCase#FilterAssetsByCategoriesWithPagination
AssetPublisherUseCase#SetAsDefaultAssetPublisherForThisPage
AssetPublisherUseCase#ViewAssetsFromDefinedSiteScope
...


See how it works on **master**:



https://user-images.githubusercontent.com/63858122/217086490-7f1529ff-6228-44c8-9256-51a7e33ec659.mp4




I downloaded the bundle and reproduced the issue locally, check this out.


https://user-images.githubusercontent.com/63858122/217084053-6fbfde0c-330f-4fa1-8d65-a9d032b89685.mp4


CC/ @john-co , @mateusralv

**Comment by locpham97** [comment]
Hi @eltonccdantas ,
Thanks for supporting me. I will investigate more about this problem.

**Comment by locpham97** [comment]
Hi @eltonccdantas ,
I updated the fix. Could you recheck this issue?
Thanks,
Loc

**Comment by mateusralv** [comment]
ci:test:relevant

**Comment by locpham97** [comment]
Hi @mateusralv ,
Do you have any update for this ticket?
Thanks,
Loc

**Comment by mateusralv** [comment]
Hi @locpham97 sorry for the long delay 😞. I'm on it now!

**Comment by mateusralv** [comment]
ci:test:bundle

**Comment by mateusralv** [comment]
Hi @Vy-CES 

### Unique flaky failure
A poshi test had a unique failure, but I run locally in PR`s bundle and the test is passing.
LocalFile.BlogsEntry#CanChangeAScheduledEntryToThePresentAndPublish

### Semantic module 

[semantic-versioning-jdk8/0/0](https://testray.liferay.com/home/-/testray/case_results/2190518178?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2190501041%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc)

Not seems like a regression, but could you take a look at it? 
```
[beanshell]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
[beanshell] = ================================================== ========== ========== ========== ========== ==========
[beanshell] * com.liferay.layout.utility.page.kernel.constants   MAJOR      1.1.0      1.0.0      2.0.0      VERSION INCREASE REQUIRED
[beanshell] 	+   class      com.liferay.layout.utility.page.kernel.constants.LayoutUtilityPageEntryConstants
[beanshell] 		+   field      TYPE_SC_NOT_FOUND
[beanshell] 			+   access     final
[beanshell] 			+   access     static
[beanshell] 			+   constant   SC_NOT_FOUND
[beanshell] 			+   return     java.lang.String
[beanshell] 		+   field      TYPE_STATUS
[beanshell] 			+   access     final
[beanshell] 			+   access     static
[beanshell] 			+   constant   STATUS
[beanshell] 			+   return     java.lang.String
[beanshell] 		+   field      TYPE_TERMS_OF_USE
[beanshell] 			+   access     final
[beanshell] 			+   access     static
[beanshell] 			+   constant   TERMS_OF_USE
[beanshell] 			+   return     java.lang.String
[beanshell] 		+   method     <init>()
[beanshell] 			+   return     void
[beanshell] 		+   method     clone()
[beanshell] 			+   access     protected
[beanshell] 			+   return     java.lang.Object
[beanshell] 		+   method     equals(java.lang.Object)
[beanshell] 			+   return     boolean
[beanshell] 		+   method     finalize()
[beanshell] 			+   access     protected
[beanshell] 			+   return     void
[beanshell] 		+   method     hashCode()
[beanshell] 			+   return     int
[beanshell] 		+   method     toString()
[beanshell] 			+   return     java.lang.String
[beanshell] 	-   class      com.liferay.layout.utility.page.kernel.constants.LayoutUtilityPageEntryTypesConstants
[beanshell] 		-   field      LAYOUT
[beanshell] 			-   access     final
[beanshell] 			-   access     static
[beanshell] 			-   constant   LAYOUT
[beanshell] 			-   return     java.lang.String
[beanshell] 		-   field      STATUS
[beanshell] 			-   access     final
[beanshell] 			-   access     static
[beanshell] 			-   constant   STATUS
[beanshell] 			-   return     java.lang.String
[beanshell] 		-   field      TERMS_OF_USE
[beanshell] 			-   access     final
[beanshell] 			-   access     static
[beanshell] 			-   constant   TERMS_OF_USE
[beanshell] 			-   return     java.lang.String
[beanshell] 		-   method     <init>()
[beanshell] 			-   return     void
[beanshell] 		-   method     clone()
[beanshell] 			-   access     protected
[beanshell] 			-   return     java.lang.Object
[beanshell] 		-   method     equals(java.lang.Object)
[beanshell] 			-   return     boolean
[beanshell] 		-   method     finalize()
[beanshell] 			-   access     protected
[beanshell] 			-   return     void
[beanshell] 		-   method     hashCode()
[beanshell] 			-   return     int
[beanshell] 		-   method     toString()
[beanshell] 			-   return     java.lang.String
[beanshell] 	-   version    1.0.0
[beanshell] 	+   version    1.1.0
[beanshell] 
[stopwatch] [run.batch.test.action: 4.671 sec]
     [echo] Semantic versioning is incorrect.
      [get] Getting: http://test-1-31/job/test-portal-acceptance-pullrequest-downstream(master)/416309//consoleText
      [get] To: /opt/dev/projects/github/liferay-portal/20230208161636505.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/20230208161636505.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null551625560.properties
```

[Testray comparison ](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1676636716483&testrayRunIdA=2190426385&testrayRunIdB=2190501342)

**Comment by locpham97** [comment]
ci:test-relevant

**Comment by locpham97** [comment]
Hi @mateusralv ,
The differencet from my repo. I rebase to master.
Could you recheck thanks, 
Loc

**Comment by nkkwon** [comment]
ci:test:relevant

**Comment by nkkwon** [comment]
Checking with CI for this failure with relevant

**Comment by pyoo47** [comment]
ci:test:stop

**Comment by pyoo47** [comment]
ci:test:relevant

**Comment by nkkwon** [comment]
[Testray Comparison](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=3&testrayRunIdB=2202281551&testrayRunIdA=2201940040&statusB=3)
These tests failing look to be flaky issues that occur on Acceptance too, @locpham97 looks good to manually forward

**Comment by locpham97** [comment]
Hi @nkkwon ,
could you help me forward this PR?
Thanks,
Loc

**Comment by nkkwon** [comment]
ci:forward:force

**Comment by locpham97** [comment]
ci:forward

**Pull request closed without merging**
