### PR TITLE
LPS-168441 - Centralize JS dependencies

### PR DESCRIPTION
**Pull request by bryceosterhaus**
Follow up from https://github.com/liferay-frontend/liferay-portal/pull/2973, seeing if new PR makes a difference for CI cache

### CODE REVIEW

**Comment by mateusralv** [comment]
Hi Bryce, the failure in the workflow that I mentioned before continues to occur and I couldn't finish the analysis today, tomorrow I'll comment with other failures that I found.

**Comment by bryceosterhaus** [comment]
@mateusralv I am unable to reproduce the failure in workflow when I build locally, so I'm not sure how to approach a fix I can't reproduce.

Let me know if you find other failures as they may be related and I could possibly reproduce those.

**Comment by bryceosterhaus** [comment]
@mateusralv I was able to reproduce locally, had to enable our combo loader to see it. I think I have fixed it and will re-run tests

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by mateusralv** [comment]
I'm taking a look 👓

**Comment by mateusralv** [comment]
Hi @bryceosterhaus I found some failures related this PR: 

[Testray comparison](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1674738756886&testrayRunIdA=2174348318&testrayRunIdB=2174454526)

### Categories: 
The point here is the "This topic is empty." phrase that shows in master and not in PR 
PR | Master

https://user-images.githubusercontent.com/44584050/214874992-79c3a373-0a47-4e7b-8430-e003554fbc91.mp4

---
### Workflow metrics: 

https://user-images.githubusercontent.com/44584050/214875094-68874a86-5a6a-4c71-9bc6-7bea7846fe43.mp4

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by mateusralv** [comment]
ci:help

**Comment by mateusralv** [comment]
ci:stop:relevant

**Comment by mateusralv** [comment]
ci:stop:stable

**Comment by mateusralv** [comment]
ci:test:relevant

**Comment by mateusralv** [comment]
Hi @bryceosterhaus 'Questions' failures are still occurring.

Workflow metrics failures are still occurring, but now a can create a Fix and solve this failure. 
BrycePR

**Comment by bryceosterhaus** [comment]
@mateusralv 
> but now a can create a Fix and solve this failure.

I'm not sure what you mean by this. The workflow failures are a result of a broken test or something that I need to fix? I can't tell what the failure is from your screenshot, can you provide steps to reproduce?

**Comment by bryceosterhaus** [comment]
re-sent here, https://github.com/liferay-frontend/liferay-portal/pull/3011. squashed most the commits

**Pull request closed without merging**
