### PR TITLE
LPS-124871 Propagate NODE_ENV to YUI loader

### PR DESCRIPTION
**Pull request by wincent**
Our other resources are toggled between minified and non-minified form based on the value of `NODE_ENV`, so we do the same here in the name of consistency for resources that are loaded via the YUI loader.

This means we effectively ignore [the old logic](https://github.com/liferay/liferay-portal/blob/012adf4b2836179a5478bf04b5337955917fccb8/portal-web/docroot/html/common/themes/top_js.jspf#L329-L342) that consults `themeDisplay.isThemeJsFastLoad()` and the `javascript.log.enabled` property, in order to return `'raw'`, `'min'` or `'debug'` as a filter type. Now, we only ever return `'raw'` or `'min'`.

If you're curious, how these filter types are used can be seen in [the loader source](https://alloyui.com/api/files/yui3_src_loader_js_loader.js.html).

### CODE REVIEW

**Comment by wincent** [comment]
I'm still testing this manually, but sending this here early so that I can give CI a head-start on it. I'll report back with my findings.

**Review by jbalsas — APPROVED** [review]
Keanu approves!

kean_approved

**Comment by wincent** [comment]
ci:stop

**Comment by jbalsas** [comment]
> Well, you know, that's kind of disappointing. I thought this one went through Babel (it does) but forgot that it doesn't go through the bundler, which is the one responsible for setting up the plug-ins to transform. At least, that's IIRC.

Huh... I would've fell for the same

**Comment by wincent** [comment]
Fixed in https://github.com/liferay-frontend/liferay-portal/pull/632/commits/b9db3c1b71a7b3d36534a3806e9ac0ac539a58f7 and made a note in there that we might want to move this particular plugin (`babel-plugin-transform-node-env-inline`) into our `npm-scripts`-managed preset and out of the bundler, just to be safe... thoughts?

**Comment by wincent** [comment]
ci:test:sf

**Comment by wincent** [comment]
ci:test:relevant

**Comment by wincent** [comment]
ci:test:bundle

**Comment by wincent** [comment]
So with this applied I see `-min.js` files getting loaded that look like they came from the AUI loader, so I guess this works?

Screenshot 2020-12-17 -154003-nCnkGKqH@2x

**Comment by wincent** [comment]
Failure is spurious (see: https://github.com/liferay-frontend/liferay-portal/pull/636) so going to manual forward.

**Comment by wincent** [comment]
Manual forward: https://github.com/brianchandotcom/liferay-portal/pull/97050

**Pull request closed without merging**
