### PR TITLE
LPS-127020 Move autoFocus functionality to the management toolbar taglib

### PR DESCRIPTION
**Pull request by markocikos**
Task ticket: https://issues.liferay.com/browse/LPS-127020
Related discussions:
- https://github.com/liferay/clay/issues/3895
- https://github.com/liferay-frontend/liferay-portal/pull/826

Notes:
- By default, we are not auto-focusing the search input. This is because Lexicon does not state this behavior and vast majorities on usages in DXP do not auto-focus. See https://github.com/liferay-frontend/liferay-portal/pull/826#issuecomment-784141719
- There is an ongoing discussion about how to name the attribute, see https://github.com/liferay-frontend/liferay-portal/pull/826#issuecomment-784148077. In this PR I chose `searchInputAutoFocus` because
```jsp
<clay:management-toolbar
	searchInputAutoFocus="<%= true %>"
	searchInputName="mySearchInputName"
/>
```
rhymes with
```js
<ClayInput
	autoFocus={searchInputAutoFocus}
	name={searchInputName}
/>
```
- Intrestingly, React's `autoFocus`, capital `F`, is quite different from HTML `autofocus`. To prevent cross-browser inconsistencies, [they are using a polyfill to call .focus()](https://github.com/facebook/react/issues/11851#issuecomment-351672131).

/cc @wincent @4lejandrito @jbalsas @julien @jonmak08 @ambrinchaudhary 

Test sample in clay-sample-web:

after

### CODE REVIEW

**Review by wincent — APPROVED** [review]
> I chose searchInputAutoFocus because
>
> ...
>
> rhymes with
>
> ...

Sounds good enough reason to me!

**Review by julien — COMMENTED** [review]
The changes LGTM; not sure about the test failure

**Comment by markocikos** [comment]
CI failure looks unrelated. I'll try to forward it. /cc @john-co

**Comment by markocikos** [comment]
ci:forward

**Review by kresimir-coko — APPROVED** [review]

**Comment by wincent** [comment]
```
Stopping the server due to unexpected startup errors
```

I think we can forward this manually. The [other failure you saw](https://github.com/liferay-frontend/liferay-portal/pull/833#issuecomment-784412273) was a known issue, fixed yesterday.

**Comment by wincent** [comment]
Life is too short. Manual forward: https://github.com/brianchandotcom/liferay-portal/pull/99157

**Pull request closed without merging**
