### PR TITLE
[Please BACKPORT to 7.3.x]LPS-123143 - Fix input localized text

### PR DESCRIPTION
**Pull request by marcoscv-work**
This PR fixes the input localized text:

image

There is a particularity in sidebar (only for localized buttons) so that's fixed in `sidebar.scss`:

The result:

image

---

How to test it:

1º Deploy admin theme
2º Create a widget page or admin one
or
3º Create a webcontent

### CODE REVIEW

**Comment by marcoscv-work** [comment]
ci:test:sf

**Comment by marcoscv-work** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
Added **[Please Backport]** to the title since I think this is safe and probably better to have in 7.3, right?

**Comment by jbalsas** [comment]
ci:forward

**Pull request closed without merging**
