### PR TITLE
[7.4-only] LPS-121953 Migrate v2 usages of clay:user-card in segments/segments-web

### PR DESCRIPTION
**Pull request by julien**
The `segments-web` module doesn't have a `<clay:user-card />` tag but it
does open a modal window in which a `<clay:user-card />` is displayed.

**Test Plan**

- Fetch this branch, and deploy:
    `frontend-taglib-clay` and `users-admin-item-selector-web` modules

- Navigate to *People* > **Segments**

- Create a new segment, add a title (in the top) and drag and a **User**
"Property" from the right sidebar to the **Conditions** container.

- In **User with property**, click on the **Select** button.

Expected result:

- A modal window is opened displaying the list of available users

- In the top right hand corner of the modal window, click on the grid icon
(which looks like a square divided in 4 sections) and select **Cards**

- Select one or more users and click on the **Select** button

- Assert than the user names appear in the **User with property**
condition

### CODE REVIEW

**Comment by julien** [comment]
ci:test:sf

**Comment by julien** [comment]
ci:test:relevant

**Review by markocikos — APPROVED** [review]
LGTM! :+1:

**Comment by jbalsas** [comment]
Remember to send this to the User & System Mgmt team... not sure if they have a single user or if @drewbrokke should be the one routing the requests!

**Comment by julien** [comment]
@jbalsas thanks for the heads up, I'll ask @drewbrokke

**Comment by julien** [comment]
ci:test:relevant

**Comment by julien** [comment]
Sent to https://github.com/drewbrokke/liferay-portal/pull/1219

**Pull request closed without merging**
