### PR TITLE
LPS-112426 Imports Form Renderer CSS by JS

### PR DESCRIPTION
**Pull request by matuzalemsteles**
A follow-up to #108

### CODE REVIEW

**Comment by matuzalemsteles** [comment]
ci:test:sf

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by brunobasto** [comment]
Removal o Java code. Looks good!

**Comment by jbalsas** [comment]
lovingit

**Comment by jbalsas** [comment]
Green... 🤔  what should we do...

**Comment by jbalsas** [comment]
ci:forward

**Pull request closed without merging**
