### PR TITLE
LPS-182184 |Product QA | Functional Automation - Export / Import FrontEnd Client Extensions individually

### PR DESCRIPTION
**Pull request by deborasoliveira**
**JIRA Ticket:**

https://liferay.atlassian.net/browse/LPS-186730

### CODE REVIEW

**Comment by deborasoliveira** [comment]
ci:test:sf

**Comment by deborasoliveira** [comment]
ci:test:sf

**Comment by deborasoliveira** [comment]
@CarlosBrichete could you take a look at these poshi tests? 
Thanks in advance!

**Comment by deborasoliveira** [comment]
ci:test:frontend

**Comment by deborasoliveira** [comment]
ci:test:frontend

**Review by CarlosBrichete — APPROVED** [review]
LGTM :)

**Comment by deborasoliveira** [comment]
ci:test:sf

**Comment by deborasoliveira** [comment]
ci:test:sf

**Comment by deborasoliveira** [comment]
ci:forward

**Pull request closed without merging**
