### PR TITLE
LPS 119814 - Documents and media move modal size

### PR DESCRIPTION
**Pull request by boton**
Adjust the Documents and Media move modal width.

**Steps to reproduce:**
- Go to Documents & Media
- Add and item if there is none.
- Select and click the "move" icon in the Management Toolbar

**Before the fix:**
image

**After the fix:**
image

I need to pass height and size props in openSelectionModal to Modal.

### CODE REVIEW

**Comment by boton** [comment]
ci:test:sf

**Comment by boton** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
Hey @boton, `md` modals didn't have sticky footers by design. If you see the condition that makes footers stick is:

```css
@media (min-width: 768px)
.portal-popup .dialog-footer {
    position: fixed;
}
```

This is because in smaller devices fixing the footer (and the header) usually leaves very little room for the content, so we decided a long time ago that we in those cases the footer would show in place. It's unfortunate that the footer in your case is on top, but this should be happening already in previous versions if you see this view in a small device.

Seeing as this is still pretty old code (legacy Documents and Media), I think this is the best we can do for now. We should probably update those components at some point and give that UI a bit of a makeover 😉 

Going to forward this for now!

**Comment by jbalsas** [comment]
ci:forward

**Comment by boton** [comment]
cc @ambrinchaudhary

**Pull request closed without merging**
