### PR TITLE
LPS-148662 Migrate confirm uses cases to use openConfirmModal on JSPs

### PR DESCRIPTION
**Pull request by diegonvs**
From: https://github.com/brianchandotcom/liferay-portal/pull/122542 

I just want to check if there is something failing on modules I changed on https://github.com/liferay-frontend/liferay-portal/commit/a6e35dd8481c2fe5f7da340abd734b0a99d65350

### CODE REVIEW

**Comment by diegonvs** [comment]
ci:test:relevant

**Comment by diegonvs** [comment]
ci:stop

**Comment by diegonvs** [comment]
ci:test:relevant

**Comment by diegonvs** [comment]
ci:test:sf

**Comment by diegonvs** [comment]
Results are crazy as me in this year's WC finals, re-running CI again

**Comment by diegonvs** [comment]
ci:test:relevant

**Comment by mateusralv** [comment]
I'm taking a look 🕵🏽

**Comment by mateusralv** [comment]
From [comparison with master](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=2&testrayRunIdB=1967707445&testrayRunIdA=1967969934&statusB=3) most tests have nonunique failures. 

#### Test with unique failure

1. DMCache#CanConfigureCacheControlAsPrivate

The test was run locally and passed 🟢

**Pull request closed without merging**
