### PR TITLE
LPS-142295 Resend without blocking issue (hopefully)

### PR DESCRIPTION
**Pull request by izaera**
CC: @javierdearcos @brunofernandezg

### CODE REVIEW

**Comment by izaera** [comment]
CC:  @john-co @bryceosterhaus

**Comment by izaera** [comment]
ci:test:sf

**Comment by izaera** [comment]
ci:test

**Comment by john-co** [comment]
ci:test:relevant

**Comment by john-co** [comment]
ci:test:frontend

**Comment by john-co** [comment]
ci:test:acceptance-functional

**Comment by zhangyan0701** [comment]
The failure in [modules-semantic-versioning-jdk8](https://testray.liferay.com/home/-/testray/case_results/1589086645) test should be related, below error in console:
```
     [exec] com.liferay.semantic.versioning.SemanticVersioningTest > testSemanticVersioning[/apps/portal/portal-instance-lifecycle-api] STARTED
     [exec] 
     [exec] com.liferay.semantic.versioning.SemanticVersioningTest > testSemanticVersioning[/apps/portal/portal-instance-lifecycle-api] FAILED
     [exec]     java.lang.AssertionError:   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec]     = ================================================== ========== ========== ========== ========== ==========
     [exec]     * com.liferay.portal.instance.lifecycle              MINOR      2.0.0      2.0.0      2.1.0      VERSION INCREASE REQUIRED
     [exec]     	<   class      com.liferay.portal.instance.lifecycle.BasePortalInstanceLifecycleListener
     [exec]     		+   method     portalInstanceInitialized(com.liferay.portal.kernel.model.Company)
     [exec]     			+   return     void
     [exec]     	<   interface  com.liferay.portal.instance.lifecycle.PortalInstanceLifecycleListener
     [exec]     		+   method     portalInstanceInitialized(com.liferay.portal.kernel.model.Company)
     [exec]     			+   return     void
     [exec]     [Baseline Warning] Bundle Version Change Recommended: 4.1.0
```

Full console log:
https://testray.liferay.com/reports/production/logs/2021-12/test-1-34/test-portal-acceptance-pullrequest(master)/404/modules-semantic-versioning-jdk8/0/0/jenkins-console.txt.gz

Other failures are unrelated.

**Comment by izaera** [comment]
ci:test:sf

**Comment by izaera** [comment]
ci:test:relevant

**Comment by izaera** [comment]
@zhangyan0701 @john-co I've fixed the baseline error and launched test relevant again (just in case). Not sure if this can be forwarded after that or we need to do anything else... :thinking:

**Comment by zhangyan0701** [comment]
> @zhangyan0701 @john-co I've fixed the baseline error and launched test relevant again (just in case). Not sure if this can be forwarded after that or we need to do anything else... 🤔

I think we can forward this as the modules-semantic-versioning-jdk8 test has been fixed, and the change should not affect other tests since only the versions were changed.

**Comment by john-co** [comment]
I wanna run a couple other tests to be sure since we don't have automation testing on this story...

> We create a sample row pointing to our Vanilla Counter app per company,
> but only when the table is empty (ie: on fresh installations).

Does this mean localhost:8080 will have a sample remote app too? Or just additional portal instances?

> Note that this will recreate the sample if it is deleted, no other
> remote app is created and portal is restarted. PM thinks this is a fair
> behaviour but, if we see it creates any problem, we may change it in
> the future.

Is this the expected outcome?
1. Delete the sample remote app
2. Restart portal
3. Assert new sample remote app is present

**Comment by john-co** [comment]
Hi @izaera, I pushed a commit to add immediate test coverage for now to address the portal instance error. Ideally would like to add specific tests for the story specifically before pushing this up. We'll risk other regressions if we don't audit for test coverage in parallel with new stories like this.

**Comment by john-co** [comment]
ci:test:relevant

**Comment by john-co** [comment]
@susanchen3 discovered (and I verified) a stacktrace error when testing this PR locally on adding a new portal instance: https://gist.github.com/susanchen3/da0e2d707930f206aaff02a3a419be70

**Comment by susanchen3** [comment]
Using the test bundle from [this PR](https://github.com/liferay-frontend/liferay-portal/pull/1699#issuecomment-985506694), the first time I started the bundle, I got the `Unable to register remote portlet for company 42539 because it does not exist` error when creating an instance. However, restarting the bundle a couple times gave me that error alongside a similar [stack trace error log](https://gist.github.com/susanchen3/2b05b8986a460b41be38e442c8a61a12) as above.

**Comment by john-co** [comment]
Weird that the CI test didn't catch this error...https://github.com/liferay-frontend/liferay-portal/pull/1736#issuecomment-991206264

**Comment by izaera** [comment]
> Hi @izaera, I pushed a commit to your branch to add immediate test coverage for now to address the portal instance error. Ideally would like to add specific tests for the story specifically before pushing this up. We'll risk other regressions if we don't audit for test coverage in parallel with new stories like this.

@john-co That sounds great :-). However, if that is the case, maybe we should check with Brian or Shuyang first, if this is a valid solution :thinking: (CC: @dsanz and @javierdearcos so that they are aware). I modified core infra to make this work, but I'm no expert in that side of the code, so maybe there's a better way to do this and we end up discovering that after a lot of work (dev and QA) that we need then to discard...

**Comment by izaera** [comment]
I'll send this (manually) to Brian so that he can check if the approach to the solution is valid. Then we will proceed with the QA tests and all that...

**Comment by izaera** [comment]
Changing plans... For some reason I didn't see the comments regarding the new error -> https://github.com/liferay-frontend/liferay-portal/pull/1736#issuecomment-991206264 and that's why I was a bit lost in this conversation :disappointed:
I don't know if it was me or the typical scenario where GH hides some of the discussion messages :disappointed:
In any case, at the light of this, there's no point in sending anything to brian. I will first fix the error or change the PR to work, then see what I do

**Pull request closed without merging**
