### PR TITLE
LPS-195138

### PR DESCRIPTION
**Pull request by fortunatomaldonado**
https://liferay.atlassian.net/browse/LPS-195138

Hello,
I had to also revert https://github.com/liferay-frontend/liferay-portal/pull/3657/commits/d79b6cd2ceaf31e2f5935abc6686cf225ca685ff and https://github.com/liferay-frontend/liferay-portal/pull/3657/commits/104160fb57b5abbf16d6412145502f5422a4cf51 in order to revert the following three commits.
Let me know if there are any questions or comments about this.

Thank you!

### CODE REVIEW

**Comment by bryceosterhaus** [comment]
cc @izaera, I'll leave this review to you

**Review by izaera — APPROVED** [review]
LGTM

I've built it locally and I've checked that:

1. The `/o/js_resolve_modules` endpoint does not contain the hash any more
2. The `/o/js_resolve_modules` endpoint responses are correctly cached by means of ETag headers

**Comment by JerryAdrianoo** [comment]
ci:test:relevant

**Comment by JerryAdrianoo** [comment]
@fortunatomaldonado Good work! Fell free to forward it.

**Comment by fortunatomaldonado** [comment]
ci:forward

**Pull request closed without merging**
