### PR TITLE
LPS-141185 Stabilizes the analysis of violations during SPA navigation of the A11y tool

### PR DESCRIPTION
**Pull request by matuzalemsteles**
I changed some strategies here that I added in the description of each commit the reason, so it's worth reading why and I'm still marking this PR as a draft because I still need to make some improvements to finish the inconsistent analysis while browsing with SPA vs refresh a page, this is very much related to mutating the DOM elements and the scheduler that was having problems.

Some strategies I've adopted here like moving A11y to be added to `top_head` again and making the scheduler a singleton help the reliability of A11y's analytics, ie in not losing some elements to analyze.

### ToDo 

- [x] ~Improve the violations revalidation mechanism to identify if the element has already passed the test (the `axe-core` it sometimes returns the elements that are passing, we can use that for revalidation)~
- [x] Improves the funnel for identifying nodes to be analyzed (During mutation validation when a `child` change event that was added happens, we only consider the first node and not all, we may lose many elements here to be analyzed).

### CODE REVIEW

**Comment by matuzalemsteles** [comment]
ci:test:sf

**Comment by matuzalemsteles** [comment]
ci:test:sf

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by john-co** [comment]
Thanks @matuzalemsteles , can you unquarantine the A11y tests by setting `property portal.upstream = "true";` in [A11yTool.testcase](https://github.com/liferay-frontend/liferay-portal/pull/1670/commits/1a9a1b81d272f68d70a2982aaab91138f08648a2) ?

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by matuzalemsteles** [comment]
Even though the test passed I'll run it again just to check 🙂.

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by julien** [comment]
> Even though the test passed I'll run it again just to check slightly_smiling_face.

Don't hurt yourself @matuzalemsteles :joy:

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by matuzalemsteles** [comment]
💔

**Comment by john-co** [comment]
ci:test:frontend

**Comment by john-co** [comment]
ci:test:frontend

**Comment by john-co** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
The A11y tests failed due to frontend-js-a11y-sample-web failed to deploy:
```
   [exec] FAILURE: Build failed with an exception.
     [exec] 
     [exec] * What went wrong:
     [exec] Execution failed for task ':apps:frontend-js:frontend-js-a11y-sample-web:packageRunBuild'.
     [exec] > A problem occurred starting process 'command '/opt/dev/projects/github/liferay-portal/build/node/node''
     [exec] 
     [exec] * Try:
     [exec] Run with --info or --debug option to get more log output. Run with --scan to get full insights.
     [exec] 
     [exec] * Exception is:
     [exec] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':apps:frontend-js:frontend-js-a11y-sample-web:packageRunBuild'.
     [exec] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:208)
     [exec] 	at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:263)
     [exec] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:206)
     [exec] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:187)
     [exec] 	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:114)
     [exec] 	at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
     [exec] 	at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:62)
     [exec] 	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
     [exec] 	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
     [exec] 	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
     [exec] 	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
     [exec] 	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
     [exec] 	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
     [exec] 	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:409)
     [exec] 	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:399)
     [exec] 	at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:157)
     [exec] 	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:242)
     [exec] 	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:150)
     [exec] 	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:94)
     [exec] 	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
     [exec] 	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
     [exec] 	at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:41)
     [exec] 	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:372)
     [exec] 	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:359)
     [exec] 	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:352)
     [exec] 	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:338)
     [exec] 	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.lambda$run$0(DefaultPlanExecutor.java:127)
     [exec] 	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:191)
     [exec] 	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:182)
     [exec] 	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:124)
     [exec] 	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
     [exec] 	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
     [exec] 	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
     [exec] Caused by: org.gradle.process.internal.ExecException: A problem occurred starting process 'command '/opt/dev/projects/github/liferay-portal/build/node/node''
     [exec] 	at org.gradle.process.internal.DefaultExecHandle.execExceptionFor(DefaultExecHandle.java:241)
     [exec] 	at org.gradle.process.internal.DefaultExecHandle.setEndStateInfo(DefaultExecHandle.java:218)
     [exec] 	at org.gradle.process.internal.DefaultExecHandle.failed(DefaultExecHandle.java:369)
     [exec] 	at org.gradle.process.internal.ExecHandleRunner.run(ExecHandleRunner.java:87)
     [exec] 	at org.gradle.internal.operations.CurrentBuildOperationPreservingRunnable.run(CurrentBuildOperationPreservingRunnable.java:42)
     [exec] 	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
     [exec] 	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
     [exec] 	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
     [exec] Caused by: net.rubygrapefruit.platform.NativeException: Could not start '/opt/dev/projects/github/liferay-portal/build/node/node'
     [exec] 	at net.rubygrapefruit.platform.internal.DefaultProcessLauncher.start(DefaultProcessLauncher.java:27)
     [exec] 	at net.rubygrapefruit.platform.internal.WrapperProcessLauncher.start(WrapperProcessLauncher.java:36)
     [exec] 	at org.gradle.process.internal.ExecHandleRunner.startProcess(ExecHandleRunner.java:98)
     [exec] 	at org.gradle.process.internal.ExecHandleRunner.run(ExecHandleRunner.java:71)
     [exec] 	... 4 more
     [exec] Caused by: java.io.IOException: Cannot run program "/opt/dev/projects/github/liferay-portal/build/node/node" (in directory "/opt/dev/projects/github/liferay-portal/modules/apps/frontend-js/frontend-js-a11y-sample-web"): error=2, No such file or directory
     [exec] 	at net.rubygrapefruit.platform.internal.DefaultProcessLauncher.start(DefaultProcessLauncher.java:25)
     [exec] 	... 7 more
     [exec] Caused by: java.io.IOException: error=2, No such file or directory
```

Jenkins console: https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/11539/AXIS_VARIABLE=0/consoleFull

I didn't see this error occur in any other test routine, seems related.

**Comment by matuzalemsteles** [comment]
I'm going to check if this is happening locally, I can't see more information as to why the build failed and the logs back from Node.js running the build in the module.

**Comment by matuzalemsteles** [comment]
I'm not able to reproduce this error locally, I'll running the test again `ci:test:frontend`.

**Comment by matuzalemsteles** [comment]
ci:test:frontend

**Comment by matuzalemsteles** [comment]
I think errors are now related to this PR, I will investigate.

**Comment by matuzalemsteles** [comment]
ci:test:frontend

**Comment by matuzalemsteles** [comment]
Well, I had locally tested the tests but I can't reproduce the faults locally, I'll keep investigating if I can reproduce locally.

**Comment by matuzalemsteles** [comment]
I can run it manually without running the tests but it's pretty tricky to debug what the problem is, because with the console open it's always working but when it's closed sometimes for some reason the A11y doesn't render. I'm continuing to analyze and do more testing with some guesswork.

**Comment by matuzalemsteles** [comment]
ci:test:frontend

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by matuzalemsteles** [comment]
ci:test:frontend

**Comment by matuzalemsteles** [comment]
I will analyze the failures 🤞

**Comment by matuzalemsteles** [comment]
Well, I can't investigate this further to understand why this is failing, weird because testing locally I can't reproduce the first failure. @john-co can you look at this when you get the chance? you don't need to prioritize this because I'm going on vacation next week and I'm only due back at the end of January.

**Comment by john-co** [comment]
Created https://issues.liferay.com/browse/LPS-144125 to follow up. I'll be on vacation next week as well. :) Enjoy your vacation!

**Comment by matuzalemsteles** [comment]
oh that's good, enjoy your vacation too 🎉

**Comment by matuzalemsteles** [comment]
Just a status update on this PR, I should get back to it this week or next.

**Comment by edalgrin** [comment]
Just started reviewing :)

**Comment by dsanz** [comment]
I'm closing this because of a lack of activity. In light of new review of a11y priorities, work on this tool has to be reassessed. Hopefully we can get back to work at this soon

**Pull request closed without merging**
