### PR TITLE
[TS] LPS-147457 Accessibility errors caused by the use of 'content: normal' from style sheets

### PR DESCRIPTION
**Pull request by joseluisbango**
Hi team,

Can we change `content: normal` to `content: ''` to avoid the errors reported by some accessibility tools?

More info in [LPS-147457](https://issues.liferay.com/browse/LPS-147457).

Thanks

cc/ @georgel-pop-lr @pat270 @marcoscv-work

### CODE REVIEW

**Comment by pat270** [comment]
@joseluisbango You can delete lines https://github.com/liferay/liferay-portal/blame/master/modules/apps/frontend-theme/frontend-theme-styled/src/main/resources/META-INF/resources/_styled/css/portal/_dropdowns.scss#L21-L29. Bootstrap used a pseudo element to generate the `dropdown-toggle` caret styles. Clay disabled this a while ago.

If you want to go further you can delete https://github.com/liferay/liferay-portal/blame/master/modules/apps/frontend-theme/frontend-theme-styled/src/main/resources/META-INF/resources/_styled/css/portal/_dropdowns.scss#L13-L33. These styles should be controlled by Clay.

**Comment by joseluisbango** [comment]
Hi @pat270 

I have added a new commit removing those styles. Do you think both commits could be backported to 7.3.x and 7.2.x?

In addition, for those versions, `content: normal` is present in [_navbar.scss](https://github.com/liferay/liferay-portal-ee/blob/7.3.x/modules/apps/frontend-theme/frontend-theme-styled/src/main/resources/META-INF/resources/_styled/css/compat/components/_navbar.scss) and [_breadcrumbs.scss](https://github.com/liferay/liferay-portal-ee/blob/7.3.x/modules/apps/frontend-theme/frontend-theme-styled/src/main/resources/META-INF/resources/_styled/css/compat/components/_breadcrumbs.scss) too. What would be the correct way to proceed when backporting?

Thanks!

**Comment by pat270** [comment]
@joseluisbango Thanks, This LGTM!

For the navbar and breadcrumbs, we might not have to do anything. If the client is not using the compat layer (BS3 markup needs to work with BS4 CSS), they can disable it by adding the variables in `_clay_variables.scss`:

```scss
$compat-breadcrumbs: false;
$compat-navbar: false;
```

These variables will prevent that CSS from being output. They can probably disable all the compat variables [here](https://github.com/liferay/liferay-portal-ee/blob/7.3.x/modules/apps/frontend-theme/frontend-theme-styled/src/main/resources/META-INF/resources/_styled/css/compat/_variables.scss#L3-L37).

**Comment by pat270** [comment]
ci:forward

**Comment by pat270** [comment]
@joseluisbango It looks safe to do in 7.3. The styles are duplicated in the compat layer. Once deleted, the client can disable the compat layer dropdown styles to prevent it from being output.

https://github.com/liferay/liferay-portal/blob/7.3.x/modules/apps/frontend-theme/frontend-theme-styled/src/main/resources/META-INF/resources/_styled/css/portal/_dropdowns.scss

https://github.com/liferay/liferay-portal/blob/7.3.x/modules/apps/frontend-theme/frontend-theme-styled/src/main/resources/META-INF/resources/_styled/css/compat/components/_dropdowns.scss

7.2 nothing needs to be done by us. Client can disable compat layer dropdown styles from being output. There is no `content` property being applied by us in the theme `css/portal/_dropdowns.scss` or in `frontend-css-web`.

https://github.com/liferay/liferay-portal/blob/7.2.x/modules/apps/frontend-theme/frontend-theme-styled/src/main/resources/META-INF/resources/_styled/css/compat/components/_dropdowns.scss

> how can the client know if they are using the compat layer?

Compat layer is enabled by default in 7.2 and 7.3. The styles are most likely being output. Whether to find out if they are actually using it is to ask them if their theme was ever dependent on Bootstrap 3 (e.g., upgraded from 7.0 to 7.1+). You can see a table of portal releases mapped to Bootstrap versions [here](https://github.com/liferay/clay/wiki/Liferay-Portal-@clayui-css-Versions).

**Comment by joseluisbango** [comment]
Hi @pat270,

Thanks for the explanation.

For 7.2, in order to cover most scenarios and having into account that there are many customers with different use cases, could we extract those values to variables and let the customer change their values?

**Comment by pat270** [comment]
No we shouldn't extract compat layer to variables. Clients (if they are using it) should be motivated to remove dependence on it entirely. In 7.2, we can change `content: normal` to `content: none`.

same-picture

**Comment by pat270** [comment]
ci:test:relevant

**Comment by pat270** [comment]
ci:forward

**Pull request closed without merging**
