### PR TITLE
LPS-119530 Action menus not visible on Headless DataSet Display + small JS error fixes

### PR DESCRIPTION
**Pull request by brunobasto**
Fixes small errors reported by @marco-leo when using `<clay:headless-data-set-display />`. Not reproducible on master yet sine his migration of Commerce to master is not completed yet.

### CODE REVIEW

**Comment by brunobasto** [comment]
ci:test:sf

**Comment by brunobasto** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
Some of these changes seem oddly specific and a tad bit weird for an API... but let's get this unblocked and then we can work together to refine it! :)

**Comment by jbalsas** [comment]
ci:forward

**Pull request closed without merging**
