### PR TITLE
LPD-28139 - React 18 with updates from teams

### PR DESCRIPTION
**Pull request by bryceosterhaus**

### CODE REVIEW

**Comment by bryceosterhaus** [comment]
ci:test:content-management

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
ci:report:58913575

**Comment by bryceosterhaus** [comment]
ci:report:58938763

**Comment by bryceosterhaus** [comment]
ci:report:58938763

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
ci:test:frontend

**Comment by bryceosterhaus** [comment]
ci:test:relevant:norebase

**Comment by bryceosterhaus** [comment]
ci:report:59958566

**Comment by bryceosterhaus** [comment]
ci:report:59975154

**Comment by bryceosterhaus** [comment]
ci:test:headless-functional

**Comment by bryceosterhaus** [comment]
ci:report:61106057

**Comment by bryceosterhaus** [comment]
ci:test:analytics-cloud-acceptance

**Comment by bryceosterhaus** [comment]
ci:test:analytics-cloud

**Comment by bryceosterhaus** [comment]
ci:test:analytics-cloud

**Comment by bryceosterhaus** [comment]
ci:report:62587815

**Comment by bryceosterhaus** [comment]
ci:test:headless-functional

**Comment by magjed4289** [comment]
No failures related to the change. [LocalFile.ImportExport#CanRecallExportTemplate](https://testray.liferay.com/#/project/35392/routines/45357/build/63578680/case-result/63583523) passing correctly ✅ 
cc @bryceosterhaus

**Pull request closed without merging**
