### PR TITLE
LPS-195636 Wire CX filters from back to front

### PR DESCRIPTION
**Pull request by izaera**
This is the smallest change needed to make CX filters work. I will send a follow up to change the public contract a little to make it more "evolvable" (see https://github.com/liferay-frontend/liferay-portal/pull/3666#issuecomment-1733461468).

### CODE REVIEW

**Comment by izaera** [comment]
ci:forward

**Comment by izaera** [comment]
ci:test:relevant

**Comment by izaera** [comment]
ci:test:relevant

**Comment by dsanz** [comment]
LGTM ;)

**Comment by dsanz** [comment]
ci:test:relevant

**Comment by andreluis2022** [comment]
I'm on it

**Review by markocikos — APPROVED** [review]
@izaera LGTM! :sparkles:

**Comment by andreluis2022** [comment]
The failures seem to be unrelated to your PR, according to this [comparison](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=2&testrayRunIdB=2431205176&testrayRunIdA=2429962168&statusB=3)

**Comment by izaera** [comment]
ci:forward:force

**Comment by izaera** [comment]
ci:forward:force

**Pull request closed without merging**
