### PR TITLE
[7.4-only] LPS-121959 Migrate v2 usages of clay:vertical-card in blogs/blogs-web

### PR DESCRIPTION
**Pull request by julien**
**IMPORTANT** This PR needs to be sent to @liferay-lima after internal review

In this change, we replace `<clay:vertical-card-v2 />` (clay 2.x:Metal+soy) with `<clay:vertical-card />`  (clay 3.x: React)

**Test plan**:
- Navigate to **Content & Data** > **Blogs**
- Create a new Blog Entry
- Navigate to the previous page

### CODE REVIEW

**Comment by julien** [comment]
ci:test:sf

**Comment by julien** [comment]
ci:test:relevant

**Review by carloslancha — APPROVED** [review]
LGTM

**Review by markocikos — APPROVED** [review]
LGTM! :+1:

**Comment by julien** [comment]
Sent to https://github.com/liferay-lima/liferay-portal/pull/1090

**Pull request closed without merging**
