### PR TITLE
LPS-154648 Add test FinalStepCanTransitionToHotSpotMode

### PR DESCRIPTION
**Pull request by susanchen3**
**Background**
Create automated tests for Walkthrough component. 

**Test Plan**
Given: frontend-js-components-sample-web deployed to test page
And Given: Navigate to Walkable tab on sample portlet
And Given: popover mode
When: on 1st step popover
And When: Click on all next steps
**Then last step contains close button** (added to account for new behavior)
**When click on close button**
Then: transitions to hotspot mode
And Then: hotspot is on final element
And Then: popover is not present

**JIRA Ticket:**
https://issues.liferay.com/browse/LPS-154648

### CODE REVIEW

**Comment by susanchen3** [comment]
ci:test:frontend:nocompile

**Comment by john-co** [comment]
Just started reviewing :)

**Review by john-co — APPROVED** [review]
Looks good to me! :sunglasses:

**Comment by susanchen3** [comment]
ci:forward

**Comment by susanchen3** [comment]
pls work

**Comment by susanchen3** [comment]
ci:forward

**Pull request closed without merging**
