### PR TITLE
LPS-154696 Create ObjectValidationExceptionMapper and send the error message type by the user in the validation definition

### PR DESCRIPTION
**Pull request by LuismiBarcos**
Related ticket -> [LPS-154696](https://issues.liferay.com/browse/LPS-154696)
___

Due to [this PR](https://github.com/brianchandotcom/liferay-portal/pull/117690), the REST APIs do not respond with `title` information which is used to provide information about the validation in Objects.

This PR creates an exception mapper to handle that exception throw by the validator in case it fails and makes the REST API respond with the error provided by the user in the validation definition.

So now, if the user does not pass the validation, the error shown will be shown like this (_Error message_ is the message introduced by the user in the validation definition)
imagen

### CODE REVIEW

**Comment by LuismiBarcos** [comment]
I will convert this PR to draft until we finish our internal discussions because there could be a better solution

**Comment by LuismiBarcos** [comment]
Finally, we have to include this approach as this fix a blocker. Sorry for the inconvenience 😞

**Comment by LuismiBarcos** [comment]
ci:test:relevant

**Review by ccorreagg — APPROVED** [review]

**Comment by ccorreagg** [comment]
ci:forward

**Pull request closed without merging**
