### PR TITLE
LPS-154538 Export `PortletURL` utils and import them throughout the codebase

### PR DESCRIPTION
**Pull request by kresimir-coko**
Pretty self-explanatory. This PR exports the remaining utils living under the `Liferay.Util.PortletURL` namespace, and replaced their usages to importing instead of using the global namespace.

### CODE REVIEW

**Review by diegonvs — APPROVED** [review]

**Comment by kresimir-coko** [comment]
ci:test:acceptance-functional

**Comment by john-co** [comment]
Selection_267

No unique failures on acceptance-functional

**Comment by john-co** [comment]
ci:test:stable

**Comment by john-co** [comment]
I'm pretty sure [portal-license-smoke-jdk8/0/0](https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/59963//consoleText) is a fluke/flaky. Just rerunning to double check.

**Comment by john-co** [comment]
ci:test:relevant

**Comment by kresimir-coko** [comment]
ci:forward

**Pull request closed without merging**
