### PR TITLE
LPS-181808 | Removed ignore from test and added on description the bug ticket that is causing quarantine

### PR DESCRIPTION
**Pull request by abhnerramos**
**Description**
These tests were either _ignored_ or on _quarantine_.
The test that was with ignore, was passing normally so I removed the ignore label.
- ClientExtension#HasMandatoryFieldErrorMessagesWhenEmpty
- FDSFilters#OneFilterCanBeRemoved

For the tests that were in quarantine, I added the bug ticket that is causing the error on the testcase description.

**JIRA Ticket**
https://issues.liferay.com/browse/LPS-181808

### CODE REVIEW

**Comment by abhnerramos** [comment]
ci:stop

**Comment by abhnerramos** [comment]
hey @mateusralv , LGTM! Could you take a look, please?

**Review by mateusralv — APPROVED** [review]
Nice!

**Comment by mateusralv** [comment]
ci:forward

**Pull request closed without merging**
