### PR TITLE
HR_209 If the sidebar menu is a link, the page title should change after activating the link

### PR DESCRIPTION
**Pull request by dsanz**
Reference: https://issues.liferay.com/browse/LPS-169101

In this PR, we are:
 * Turning screen navigation tag into a page subtitle contributor, so that the screen navigation `entry` and `category` labels are added to the page subtitle using portal API. 
 * Using the same `-` character to separate page title and subtitle elements. This provides a nice hierarchical visual schema to present the page title in the browser
 * For the case where a page is being configured, in addition, a suffix "(Configuring)" is added to the title. This follows the existing mechanism we have for the page edition.
 
How to test this:

- Follow LPS instructions or just go to any page configuration (press cog icon near to page in the control menu)
- Navigate through sections 
- Assert page title contains screen navigation entries and categories separated by dashes, before the original page title. For this case, you should see `(Configuring)` at the end of the page title
- For other cases, like object definition admin, just assert page title contains screen navigation entries and categories separated by dashes 

Other notes:
 * This solution does not guarantee screen navigation `entry` and `category` will show up in the page title as some widget might take over the responsibility of setting the full page title (e.g. user management)
 * Some screen navigation categories and entries are not well defined, so resulting page titles might look repetitive as both category and entry have the same value. This is technically not an issue in the page title composition mechanism but rather in the way screen navigation categories and entries are named/translated. That shall be addressed in separate tickets.
 * Page translation is another case where we'd like to apply the page title pattern, but I've left it out till we validate this

cc @ethib137 @marcoscv-work @edalgrin

### CODE REVIEW

**Comment by ethib137** [comment]
@dsanz this is looking good! Since this PR brings about an even greater divergence between the logic for creating a page title using `TitleProvider.java` vs `init.ftl`, could we also use this opportunity to remove the unused page title logic from init.ftl?

**Comment by dsanz** [comment]
ci:test:sf

**Comment by markocikos** [comment]
ci:forward

**Comment by dsanz** [comment]
Hi, after some research on the involved logic in `init.ftl` and trhe way page title variables are computed and used, I've found that simplification of logic requires some careful thought, namely:

- There are 2 different variables: `the_title` and `html_title`
- In the past, `html_title` was built from `the_title` but now, `html_title` takes its value from a new context variable `htmlTitle` provided by the `TitleProvider.java` 
- There is a logic duplication between the `TitleProvider.java` (computes `htmlTitle`) and the `init.ftl` (computes `the_title`) as both variables contain a bunch of common logic.
- Both variables are semantically similar but they're not used the same:
   - `html_title` is only used to set the [html page title](https://github.com/liferay/liferay-portal/blob/1ad28092425a3a915840f38b423d6571eadcbc42/modules/apps/frontend-theme/frontend-theme-unstyled/src/main/resources/META-INF/resources/_unstyled/templates/portal_normal.ftl#L8) and permeates to the ootb themes
   - `the_title` is used in other places ([content section header](https://github.com/liferay/liferay-portal/blob/1ad28092425a3a915840f38b423d6571eadcbc42/modules/apps/frontend-theme/frontend-theme-unstyled/src/main/resources/META-INF/resources/_unstyled/templates/portal_normal.ftl#L50), [set portlet display title](https://github.com/liferay/liferay-portal/blob/1ad28092425a3a915840f38b423d6571eadcbc42/modules/apps/frontend-theme/frontend-theme-unstyled/src/main/resources/META-INF/resources/_unstyled/templates/portal_normal.ftl#L57) and [page title in pop-up mode](https://github.com/liferay/liferay-portal/blob/ab7b964caeba85b0381dcca61b190806af18e45f/modules/apps/frontend-theme/frontend-theme-unstyled/src/main/resources/META-INF/resources/_unstyled/templates/portal_pop_up.ftl#L8)
 - Both variables can be used anywhere else in the theme, so custom themes created by our customers may be using them and making assumptions about their values

Given the above, in conversation with @ethib137 we decided to deal with `init.ftl` logic simplification in a separate ticket

**Pull request closed without merging**
