### PR TITLE
LPS-149662 Sidenav should display correctly for Site Admin, Bookmarks, and Wiki

### PR DESCRIPTION
**Pull request by pat270**
https://issues.liferay.com/browse/LPS-149662

Edit: There are more places to update, but I thought it would be easier to review if it was smaller.  I'll attach them with an old issue https://issues.liferay.com/browse/LPS-127421 if this gets merged.

###### Site Admin
site-admin

###### Bookmarks
bookmarks

###### Wiki
wiki

/cc @liferay-lima

### CODE REVIEW

**Comment by susanchen3** [comment]
[**Comparison run**](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=2&testrayRunIdB=1741988329&testrayRunIdA=1747121847&statusB=3): 
- **LocalFile.WikiDisplayWidget#CanAddFrontPageViaWD** was probably a fluke, passes locally 

---- 


- **LocalFile.WikiAdmin#CanMovePageToNewParentPage**
- **LocalFile.WikiDisplayWidget#CanAddChildPageViaWD**
- **LocalFile.WikiPage#CanAddChildPage**
- **LocalFile.WikiPage#CanAddChildPagesToFrontPage**
- **LocalFile.WikiDisplayWidget#CanAddChildPageWithHTMLViaWD**

can pass locally with test fix [here](https://github.com/susanchen3/liferay-portal/pull/44) 

----

- **LocalFile.PagesAdmin#ViewDisplayPageTemplateViaCollectionItems** is failing because the sidebar disappears after navigation to a new page. The behavior before was that it would stay displayed even through navigation and page refresh. I'm not sure if the intention is to make it disappear? 

**Before PR:**
sidebar


**After PR:** 
no-sidebar

**Comment by pat270** [comment]
ci:test:relevant

**Comment by susanchen3** [comment]
Hey @pat270 do you want to cherry pick my test fix [here](https://github.com/susanchen3/liferay-portal/pull/44/commits/a5b76bc868fa600b746f098a5baad654c42b8f26) for the Wiki tests before running relevant again?

**Comment by pat270** [comment]
@susanchen3 good looking out ❤️ . I'll do that. Thanks!

**Comment by pat270** [comment]
ci:stop

**Comment by pat270** [comment]
ci:test:relevant

**Comment by pat270** [comment]
ci:test:relevant

**Comment by pat270** [comment]
ci:test:relevant

**Comment by pat270** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
cc @markocikos I think your squad has worked with this previously.

**Comment by markocikos** [comment]
> cc markocikos I think your squad has worked with this previously

@bryceosterhaus Nah, barely anybody changed the compoenent after Greg added it 3 years ago :slightly_smiling_face:

**Comment by markocikos** [comment]
> strange, I don't get any vertical overflow. What browser and os?

Chrome 101, Ubuntu 20

I also tried it on Firefox 100. It is not so choppy, but the scrollbar does appear:

screenshot

**Comment by pat270** [comment]
@markocikos just curious did you deploy Admin theme? This [commit](https://github.com/liferay-frontend/liferay-portal/pull/2191/commits/edef489d95c7274e03d15ff3103d5edc4d4bc036) removed some margins that causes the vertical overflow. I can reproduce if I remove those changes.

**Comment by markocikos** [comment]
> just curious did you deploy Admin theme? This [commit](https://github.com/liferay-frontend/liferay-portal/pull/2191/commits/edef489d95c7274e03d15ff3103d5edc4d4bc036) removed some margins that causes the vertical overflow. I can reproduce if I remove those changes.

Yea, that was it! Sorry about the false alarm!

**Review by markocikos — APPROVED** [review]
LGTM!

**Comment by markocikos** [comment]
ci:forward

**Comment by pat270** [comment]
Thanks @markocikos ! I'm going to fix the SF failure and forward it

**Comment by pat270** [comment]
ci:test:sf

**Comment by pat270** [comment]
ci:forward

**Pull request closed without merging**
