### PR TITLE
LPS-113561 Avoid Liferay.provide in document-library-web

### PR DESCRIPTION
**Pull request by jbalsas**
Followup from https://github.com/liferay-frontend/liferay-portal/pull/11

I've added:
- Squashed all history into one initial commit [`LPS-113561 Avoid Liferay.provide in document-library-web`](https://github.com/liferay-frontend/liferay-portal/pull/50/commits/5df6fefb813b0597b8abb14880e2d0eb78386ca0)
- [Refactored `edit_folder.jsp` to avoid race conditions](https://github.com/liferay-frontend/liferay-portal/pull/50/commits/5df6fefb813b0597b8abb14880e2d0eb78386ca0). I opted to basically just move the event to a listener.
- Fixed a small issue with [`openModal` and events not being properly detached](https://github.com/liferay-frontend/liferay-portal/pull/50/commits/89cb9a4aba9fe0a0bcd576b6c8200ecfa68a517c) (actually, events being too eagerly registered). We should followup on this one because Modal components stack and never get unmounted. I think we already knew this, but let's see if we can clean it up, @markocikos, @wincent!

I also thought about simply reverting `upload_multiple_file_entries.jsp`, because we technically could have a race condition there but to get to it one needs to:
- Submitting a form which isn't visible initially 
- That can only be rendered after `<aui:script use="liferay-upload">` has initialized
- And some user actions (picking a file, or selecting one from the previous uploads list) has been taken

One would have to cheat in order to submit the form earlier (making it visible somehow and triggering the submission). In a normal flow, `liferay-upload` will also satisfy `aui-base,aui-loading-mask-deprecated,node-load` which are the dependencies where we declare the global `window['<portlet:namespace />updateMultipleFiles']`, so I'd say this is rare enough to leave as is until we can actually come back here and clean this up a bit more. Or nicely ask @liferay-lima to look into it 😉 

--- 

As part of [LPS-113561](https://issues.liferay.com/browse/LPS-113561) we
eventually want to deprecate the `Liferay.provide` function

To test the change for the `<portlet:namspace />selectFileEntryType`
function:

- Navigate to "Content and Data > Documents and Media"
- Click on the "+" button and choose "Folder"
- Type a name for the folder you want to create
- Click on the "Save" button
- Click on the kebab menu to the right of the folder you created and
  choose "Edit"
- Select the radio button with the label
  "Define Specific Document Type Restrictions and Workflow for This
   Folder (A folder)"
- Click on "Select Document Type"
- In the modal window choose one of the document types and click on
  "Choose"
- Click on the "Save button"

As a result, a notification should be displayed letting you know your
request has completed successfully and no JS errors should appear in the
browser's console.

To test the change for the `<portlet:namspace />updateMultipleFiles`
function:

- Navigate to "Content and Data > Documents and Media"
- Click on the "+" button and choose "Multiple Files Upload"
- Click on the "Select Files" button
- Upload at least 2 files (images or text documents are OK)
- Click on the "Publish" button

As a result, the files you uploaded should be visible in the "Documents"
list and no JS errors should appear in the console.

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:test:sf

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
I think the error might be related... will check tomorrow 😴

**Comment by jbalsas** [comment]
Okay, I've fixed the issue (I think) and force-pushed.

Runing the tests again.

**Comment by jbalsas** [comment]
ci:test:sf

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by wincent** [comment]
> ### ❌ ci:test:sf - 0 out of 1 jobs passed in 3 minutes
> Click here for more details.

fml

**Comment by jbalsas** [comment]
> ❌ ci:test:sf - 0 out of 1 jobs passed in 3 minutes
> Click here for more details.

I'm the literal worst

**Comment by jbalsas** [comment]
I've lost faith on this one :(

**Comment by jbalsas** [comment]
ci:stop

**Comment by jbalsas** [comment]
ci:test:sf

**Comment by jbalsas** [comment]
I'm gonna trust myself 🤷

**Comment by jbalsas** [comment]
ci:forward

**Comment by markocikos** [comment]
> /cc @markocikos, in case you didn't see my comment at [#50 (comment)](https://github.com/liferay-frontend/liferay-portal/pull/50#issue-438748905)... would love to hear your input on this one!

@jbalsas  I did not see it! I checked thoroughly why, as I know how much you love this excuse :smile:   I have a filter set for `@markocikos` mention, to put mail with a mention in a check-here-with-high-priority folder, but nothing came. It seems that [comment edit does not send notifications](https://stackoverflow.com/questions/38986589/does-github-send-notification-emails-when-an-issue-comment-is-edited#:~:text=1%20Answer&text=No%2C%20you%20do%20not%20get,for%20~2%20years%20without%20activity.). It looks like I'm [not the only one](https://github.com/brianchandotcom/liferay-portal-ee/pull/27323#issuecomment-547659127) who figured that out.

As for the change in https://github.com/brianchandotcom/liferay-portal/pull/90582/commits/df771f0930352930eb68df9a36ca7d42111a421b, this seems like a workaround patch, rather than solution of the root problem:
- There should not be a problem with trailing event handlers, even if component does not unmount, such as on modal close. That is why we are [explicitly cleaning up handlers on modal close](https://github.com/liferay/liferay-portal/blob/master/modules/apps/frontend-js/frontend-js-web/src/main/resources/META-INF/resources/liferay/modal/Modal.js#L191-L197).
- This `useEffect` should trigger only once, on first component render. None of the arguments passed to `useEffect` would ever change, until now, where `visible` is a part of the state and can change. This is a bit scary to add, may have weird side-effects.
- I do not fully understand the issue this is trying to solve, I'll look into in detail tomorrow!

**Comment by jbalsas** [comment]
> @jbalsas I did not see it! I checked thoroughly why, as I know how much you love this excuse 😄

Ok, I'll let this one go ;)... I'll try to create my PRs from the GH interface from now on so I can add the whole description... or remember to mention people in additional comments.

> As for the change in brianchandotcom@df771f0, this seems like a workaround patch, rather than solution of the root problem:

That's exactly what it is. The root problem is the `useEffect` and us not unmounting the modals, which I leave to you to properly address ;)

> There should not be a problem with trailing event handlers, even if component does not unmount, such as on modal close. That is why we are explicitly cleaning up handlers on modal close.
> This useEffect should trigger only once, on first component render. None of the arguments passed to useEffect would ever change, until now, where visible is a part of the state and can change. This is a bit scary to add, may have weird side-effects.
> I do not fully understand the issue this is trying to solve, I'll look into in detail tomorrow!

So, this [useEffect](https://github.com/liferay/liferay-portal/blob/master/modules/apps/frontend-js/frontend-js-web/src/main/resources/META-INF/resources/liferay/modal/Modal.js#L226) will run [when `visible changes](https://github.com/liferay/liferay-portal/blob/master/modules/apps/frontend-js/frontend-js-web/src/main/resources/META-INF/resources/liferay/modal/Modal.js#L287) which is caused by your own [`processClose`](https://github.com/liferay/liferay-portal/blob/master/modules/apps/frontend-js/frontend-js-web/src/main/resources/META-INF/resources/liferay/modal/Modal.js#L187)... because `setState` is async and batched, you run the `useEffect` one last time (after you "explicitly cleaning up handlers") re-adding them again.

Since `Liferay` is a global an persisted object... well, this doesn't play well with stray event listeners.

**Comment by wincent** [comment]
> Ok, I'll let this one go ;)... I'll try to create my PRs from the GH interface from now on so I can add the whole description... or remember to mention people in additional comments.

welcome-to-the-real-world

In the meantime, I am going to add this to my list of things-I-hate-about-GitHub.

**Comment by markocikos** [comment]
The [ticket to add the feature](https://github.com/isaacs/github/issues/310) has been open since 2014. Any day now...

**Comment by wincent** [comment]
> The [ticket to add the feature](https://github.com/isaacs/github/issues/310) has been open since 2014. Any day now...

I am sure they will get to it after they finish rounding the corners in the UI.

**Comment by bryceosterhaus** [comment]
@wincent do you have a google doc of the list of things you hate about github that we can follow for amusement?

**Comment by jbalsas** [comment]
> @wincent do you have a google doc of the list of things you hate about github that we can follow for amusement?

mean

**Comment by bryceosterhaus** [comment]
@jbalsas I'm genuinely curious!

**Comment by wincent** [comment]
> @wincent do you have a google doc of the list of things you hate about github that we can follow for amusement?

absolutely

https://docs.google.com/document/d/1XQK0dtkmAmOErsTh_0T2SK4xX5HAI7TUVGvO1QBaiy0/edit

Note that some things about the doc are out of date (eg. it was written before `ci:forward` was a thing), but most of it still applies.

**Pull request closed without merging**
