### PR TITLE
[7.4-only] LPS-123187 Use DropdownActionsTag in UserCardTag and VerticalCardTag

### PR DESCRIPTION
**Pull request by julien**
Instead of rendering markup "manually", we're using the
DropdownActionsTag

### CODE REVIEW

**Comment by julien** [comment]
ci:test:sf

**Comment by julien** [comment]
ci:test:relevant

**Review by carloslancha — APPROVED** [review]
This pr is not horrible

**Comment by carloslancha** [comment]
ci:forward

**Pull request closed without merging**
