### PR TITLE
LPS-125811 | master

### PR DESCRIPTION
**Pull request by john-co**
**Description**
This fixes the failing test WYSIWYGUsecase#ViewWikiFrontPageRightToLeft due to a timing issue waiting for CKEditor to load on wiki portlet

**Test Plan**
- :heavy_check_mark: Failing test WYSIWYGUsecase#ViewWikiFrontPageRightToLeft passes: https://github.com/john-co/liferay-portal/pull/380

**JIRA Ticket**
https://issues.liferay.com/browse/LPS-125811

### CODE REVIEW

**Comment by john-co** [comment]
ci:reevaluate:1227401_7812

**Comment by john-co** [comment]
Reviewed. Test failures are unrelated. :heavy_check_mark: 

[Unrelated]
- WebContentWithCustomStructures#AddWebContentWithRepeatableRichTextField - recently started failing in upstream https://testray.liferay.com/home/-/testray/cases/1348906042

**Comment by zhangyan0701** [comment]
Looks good to me!

**Comment by wincent** [comment]
Manual forward here: https://github.com/brianchandotcom/liferay-portal/pull/99071

**Pull request closed without merging**
