### PR TITLE
LPD-24971 - Use dynamic import to fix race condition between AUI and an ESM module

### PR DESCRIPTION
**Pull request by bryceosterhaus**

### CODE REVIEW

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Review by izaera — APPROVED** [review]

**Comment by bryceosterhaus** [comment]
ci:test:sf

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
ci:forward

**Pull request closed without merging**
