### PR TITLE
[7.4-only] LPS-122492 - Replace uses of dom.triggerEvent with userEvent

### PR DESCRIPTION
**Pull request by bryceosterhaus**
https://issues.liferay.com/browse/LPS-122492

Replaced all uses of `triggerEvent` from metal-dom.

I noticed on some of the tests, they were being disabled via the package.json of the module. I decided to update the code but not enable to tests. I didn't want to spiral down a hole that wasn't necessary.

### CODE REVIEW

**Comment by bryceosterhaus** [comment]
ci:test:sf

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
Looks good!

I'm fetching this to also replace the new tests in `frontend-js-spa-web` after adding Senna into the repo last night.

One thing I noticed is that we have a lot of `fireEvent.click` usage and [testing-library](https://testing-library.com/docs/dom-testing-library/api-events/) explicitly warns against this:

> Most projects have a few use cases for fireEvent, but the majority of the time you should probably use @testing-library/user-event.

I'm wondering if we should update them all... 😂

**Comment by jbalsas** [comment]
ci:test:sf

**Comment by jbalsas** [comment]
ci:test:relevant

**Review by jbalsas — APPROVED** [review]

**Comment by jbalsas** [comment]
@wincent, do you want us to dig into other usages, or this is enough for now?

I think there's a bit of a mixup between `userEvent` from `testing-library/user-event`, `fireEvent` from `testing-library/react` and `fireEvent` from `testing-library/dom`. All used to fire the `.click` event... 🤔

**Comment by wincent** [comment]
> do you want us to dig into other usages, or this is enough for now?

I wouldn't dig into the other usages. I would just create a ticket for it. When [we added the `user-event` library](https://github.com/liferay/liferay-npm-tools/pull/171), we knew it was something we wanted to offer but not force people to use yet, because [the discussion about testing best practices](https://github.com/liferay/liferay-frontend-guidelines/issues/49#issuecomment-510459340) was (and still is) open.

**Comment by jbalsas** [comment]
ci:test:sf

**Comment by jbalsas** [comment]
let's see if CI wants to run tests now... 🤔

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
There's 1 approval (who cares if it's myself) and tests are green after 4 hours 22 minutes, so going to push this forward 🤞

**Comment by jbalsas** [comment]
@bryceosterhaus, please update the titles to contain the `7.4-only` flag so it's clear that Brian shouldn't backport automatically... this one might be safe, but I'm not sure I want to risk it :D

**Comment by jbalsas** [comment]
ci:forward

**Pull request closed without merging**
