### PR TITLE
LPS-142086 Modification of RestBuilder to support new permissions method's names

### PR DESCRIPTION
**Pull request by LuismiBarcos**
Related ticket -> [LPS-142086](https://issues.liferay.com/browse/LPS-142086)

There are some tests that are failing in headless taxonomy. This is because of a rename of some `operationsIds` in [this commit](https://github.com/brianchandotcom/liferay-portal/commit/14f9546e3811c8b9e811436ee99e3b01fd6dcc5e) and [this commit](https://github.com/brianchandotcom/liferay-portal/commit/df5eb7a272d17ff27bce20ca7dfef44a82731836) that was merged directly.

As we want to support these new names, I made the changes to create the methods with the proper names.

I've also made changes in Data Engine APIs to support the same convention of names, so I've also updated some code to the new names.

I hope everything is OK with the changes in the rest builder.

### CODE REVIEW

**Review by javierdearcos — APPROVED** [review]
👏  👏 👏  Looks good.

Let's wait to the tests results before forwarding it

**Comment by LuismiBarcos** [comment]
FYI @nhpatt @javierdearcos 
Some tests of Data Engine were failing for the same reasons as the original ticket. It was using the old convention that was used in the headless-taxonomy API. So, I force to predict the names as Brian did in headless-taxonomy, execute de rest builder, and update the names in the code. I don't know if we can do this or we should inform to the data-engine team.

The tests now pass in my local, let's if the CI has something to complain 🤞 

The commerce tests that are failing don't seem related to my changes.

**Comment by LuismiBarcos** [comment]
ci:test:sf

**Comment by LuismiBarcos** [comment]
ci:test:relevant

**Comment by javierdearcos** [comment]
The Batch planner API failures seem not related.

You need to check the semantic versioning of Headless Delivery.

Great job detecting and taking care of the Data Engine tests. We can specify there are changes in Data Engine in the PR description that may need revision so Brian can ping someone to check. Don't know if it is the case but this change can affect if they are some UI component relying in the permission endpoint or if there are some Poshi tests

**Comment by LuismiBarcos** [comment]
I've checked the semantic versioning of Headless Delivery and now re-executing the CI to see if everything is ok. I will edit the description of the PR to specify the changes in Data Engine as Javi said 🙂

**Comment by LuismiBarcos** [comment]
ci:test:relevant

**Comment by LuismiBarcos** [comment]
CI
text

**Comment by LuismiBarcos** [comment]
ci:reevaluate:1287401_928

**Comment by LuismiBarcos** [comment]
Doing the rebase I've realized that some permissions methods code of `headless-delivery` changed to return empty collections, that is not what we want. So, I set `forcePredictableOperationId` as `true` in `headless-delivery` and adapted the code to the new names. I should have been more carefully, sorry 😞

**Comment by LuismiBarcos** [comment]
ci:test:relevant

**Comment by javierdearcos** [comment]
No problem 🙂 .

It is something to be aware of. We need to add more test coverage for permission methods to avoid this in the future

**Comment by javierdearcos** [comment]
ci:forward

**Pull request closed without merging**
