### PR TITLE
[7.4.x-only][LPS-121725,LPS-121754] Removes conditional branches targeting IE browsers

### PR DESCRIPTION
**Pull request by jbalsas**
This is part of our work to [Remove IE11 Support](https://issues.liferay.com/browse/LPS-121721).

Technically, **this PR is not really necessary** but it cleans up the more obvious IE-specific code branches that could be found by grepping `.isIe(` in DXP codebase.

A deeper analysis of specific hacks and workarounds could be made digging through commit messages to see if something else pops up. I think the chances of finding many additional IE workarounds are small compared to the obvious effort it would take, so I would suggest we leave whatever's missing for future boy-scouts.

This PR **removes**:
- Branches based on `Liferay.Browser.isIe` in JS and JSP
- Branches based on `BrowserSnifferUtil.isIe` in Java
- Vendor prefixed css such as `-ms`, `-o` or `-webkit`
- `*-ie` obvious classes in SCSS

This PR does not touch:
- Modules inside `archived` folder (we keep them as they are as a compat canary)
- Usages in `NtlmFilter` and `NtlmPostFilter` since @liferay-appsec will remove that module entirely as part of their [SSO mechanism clean up cleaning up](https://issues.liferay.com/browse/LPS-121760) epic

**We want to hold this PR until @liferay-echo has had a chance to validate these particular changes:**
- [No longer needed `safeRemoveChild`](https://github.com/liferay-frontend/liferay-portal/pull/450/files#diff-5366757ae93c21d72843350dad9d4e8268ceeb6edf40752afe50b835ee3e7a3cL56)
- [Unnecessary css variable fallback in JS](https://github.com/liferay-frontend/liferay-portal/pull/450/files#diff-e851c56b139be4449cbea65c6b60ea2d8611da268b105ba8e52ea7bc276fc15bL24)
- [Unnecessary css variable fallback in Java](https://github.com/liferay-frontend/liferay-portal/pull/450/files#diff-d0189baee6c130c28310f3ac3afeff9941cc4b38f5af53300537b373336d54f9L720)

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:test:sf

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
ci:test:sf

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by manoelcyreno** [comment]
ci:test:echo

**Review by victorg1991 — APPROVED** [review]

**Comment by jbalsas** [comment]
what now, @manoelcyreno? `ci:echo` certainly doesn't look good but I don't think it's related...

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by manoelcyreno** [comment]
@david-gutierrez-mesa take a look at it please, if the failures have a relationship with the PR... probably not, but take a look, please.

**Comment by jbalsas** [comment]
@manoelcyreno, @david-gutierrez-mesa, we good to forward this manually?

**Comment by manoelcyreno** [comment]
@david-gutierrez-mesa, take care of it.

**Comment by jbalsas** [comment]
I've had to rebase and push force because of changes introduced yesterday... going to test relevant again 😞

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by david-gutierrez-mesa** [comment]
@jbalsas Tests failing in this PR for ci:test:echo are not related to the changes. See analysis here: [Liferay Portal 7.4/EE Pull Request/master - jbalsas > liferay-frontend - PR#450 - 2020-10-28[04:21:08]](https://testray.liferay.com/home/-/testray/case_results?tab=runs&testrayBuildId=1323759490)

**Comment by jbalsas** [comment]
I don't think we caused this, so I'm going to manually send this to Brian.

**Comment by jbalsas** [comment]
Forwarded to Brian at https://github.com/brianchandotcom/liferay-portal/pull/95463

Thanks @david-gutierrez-mesa for the analysis on the echo results! ❤️

**Pull request closed without merging**
