### PR TITLE
[7.4.x only] LPS-122074 | Remove IE11 macros and paths

### PR DESCRIPTION
**Pull request by john-co**
**JIRA Tickets**
https://issues.liferay.com/browse/LPS-122073
https://issues.liferay.com/browse/LPS-122074

**Description**
1. Removing macros with `"${browserType}" == "internetexplorer"` from master branch
2. Removing paths with `"*_IE"` from master branch

**Test:**
Search for any mention of IE or internet explorer in poshi tests, no results return.

### CODE REVIEW

**Comment by john-co** [comment]
ci:test:sf

**Comment by john-co** [comment]
ci:test:relevant

**Comment by john-co** [comment]
Reviewed and looks good to me in https://github.com/john-co/liferay-portal/pull/360

**Comment by john-co** [comment]
ci:test:poshi

**Comment by john-co** [comment]
Running ci:test:poshi to check on other acceptance tests since only minimal poshi tests were executed in previous PR.

**Comment by john-co** [comment]
@zhangyan0701, any other IE11 mentions you can think of to remove from poshi?

**Comment by zhangyan0701** [comment]
Hi @john-co , sorry for the delay. 

I think this is all, no other paths or macros need to be removed.

**Comment by john-co** [comment]
ok, any further review comments @wincent @jbalsas ? Otherwise will forward in the next couple hours.

**Comment by john-co** [comment]
ci:forward

**Comment by wincent** [comment]
> ok, any further review comments @wincent @jbalsas ? Otherwise will forward in the next couple hours.

Thanks for doing this clean-up!

**Pull request closed without merging**
