### PR TITLE
LPS-143258 Update alloyeditor to 2.14.5

### PR DESCRIPTION
**Pull request by diegonvs**
Release notes: https://github.com/liferay/alloy-editor/releases/tag/v2.14.5

## What's Changed
* chore: eslint-plugin migration by @kresimir-coko in https://github.com/liferay/alloy-editor/pull/1505
* fix: Reload image state selection each time you select another one (… by @georgel-pop-lr in https://github.com/liferay/alloy-editor/pull/1508

## New Contributors
* @kresimir-coko made their first contribution in https://github.com/liferay/alloy-editor/pull/1505

**Full Changelog**: https://github.com/liferay/alloy-editor/compare/v2.14.4...v2.14.5

@georgel-pop-lr, see 🎥 : https://drive.google.com/file/d/1ATleOWDGO7tvzRy3uuAeKYyblt-1pD7G/view?usp=sharing

### CODE REVIEW

**Comment by diegonvs** [comment]
ci:test:relevant

**Review by markocikos — APPROVED** [review]
LGTM!

**Comment by markocikos** [comment]
ci:forward

**Comment by rolandpakai** [comment]
ci:test:relevant

**Comment by rolandpakai** [comment]
ci:test:stable

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by markocikos** [comment]
ci:forward

**Pull request closed without merging**
