### PR TITLE
LPD-1230 Delete item action message text is not correct 

### PR DESCRIPTION
**Pull request by thektan**
https://liferay.atlassian.net/browse/LPD-1230

- Fixes the Action delete modal description
- Fixes the Visualization Mode delete modal title (previously said "Delete Filter")
- Makes the delete modal styling consistent

Screenshot 2024-10-23 at 4 57 24 PM
Screenshot 2024-10-25 at 10 24 40 AM

### CODE REVIEW

**Comment by thektan** [comment]
ci:test:relevant

**Review by juanjofgliferay — APPROVED** [review]
LGTM :rocket:

**Comment by thektan** [comment]
ci:test:sf

**Comment by thektan** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
@thektan how come the delete UI's look different? color and icon. Or is this a before/after?

**Comment by thektan** [comment]
ci:forward

**Comment by thektan** [comment]
Failures don't seem related so I'll go ahead and forward

**Comment by thektan** [comment]
ci:forward:force

**Pull request closed without merging**
