### PR TITLE
LPD-39648 - Update eslint-plugin to account for sorting exports

### PR DESCRIPTION
**Pull request by bryceosterhaus**

### CODE REVIEW

**Review by izaera — APPROVED** [review]

**Comment by bryceosterhaus** [comment]
ci:forward

**Comment by bryceosterhaus** [comment]
ci:report:45930072

**Comment by bryceosterhaus** [comment]
ci:forward:force

**Comment by bryceosterhaus** [comment]
ci:stop

**Comment by bryceosterhaus** [comment]
ci:test:sf

**Comment by bryceosterhaus** [comment]
ci:forward:force

**Review by juanjofgliferay — APPROVED** [review]

**Comment by bryceosterhaus** [comment]
ci:forward:force

**Pull request closed without merging**
