### PR TITLE
[7.4-only] LPS-121939 Create clay:*-card-v2 tags and migrate existing usages

### PR DESCRIPTION
**Pull request by markocikos**
This is **step 1** in a multi-step upgrade that we aim to complete before GA1:

1. Create `-v2` tags and move all existing usages to it.
2. Update main tag (validate with sample widget).
3. Update usages from `-v2` to main.
    - Simply rename. Should work all the same. If not, update main tag to account for the fallback.
    - Update deprecated attribute usage.
4. Remove `-v2` tag.

Our intention is that all of this happens before the next release, so customers won't ever see these intermediate states. In the final state, customers will have the same API but a new implementation; we will likely mark some attributes as deprecated in this version but we'll keep them working to give time for users to update over the longer term.

---

@jbalsas @julien @carloslancha 

In this PR, we are creating three new `clay:*-card-v2` copy tags and replacing all usages. See task description in https://issues.liferay.com/browse/LPS-121939.

I did **not** test all usages after mass replace, there are 65 in total. I only checked a few and ran `ant all`. I do believe that there is a very low chance of something going wrong.

### CODE REVIEW

**Comment by markocikos** [comment]
ci:test:sf

**Comment by markocikos** [comment]
ci:test:relevant

**Comment by wincent** [comment]
Just a question about this, probably for @jbalsas; is the long-term plan something like this?

- **7.4:** All existing usages move over to `clay:*-card-v2`; old name `clay:*-card` is somehow marked as not-to-be-used-for-now or deprecated or semantics-will-change-in-next-version.
- **7.5:** `clay:*-card` becomes available with new behavior; `clay:*-card-v2` is deprecated.
- **7.6:** `clay:*-card-v2` actually gets removed.

Or this?

- Squashing those steps together somehow over 1 or 2 releases.

ie. how many steps in the process and what is the end goal?

And how does it compare to?

- **7.4:** Keeping `clay:*-card` as-is. Add new `clay:card-*-some-other-naming-scheme`. Deprecate `v2` tags.
- **7.5:** Remove `v2` tags.

**Comment by markocikos** [comment]
In the current epic we will gradually remove all v2 usages. It would make sense to me to deprecate v2 at that point, meaning it would be deprecated in 7.4 and removed in 7.5.

**Comment by jbalsas** [comment]
@john-co, could you validate these failures? Seem unrelated

**Comment by john-co** [comment]
Just started reviewing :)

**Comment by john-co** [comment]
- Smoke test failure is unrelated: https://issues.liferay.com/browse/LPS-122038
- the modules-integration tests could be related. I don't see those failures in last upstream build https://test-1-16.liferay.com/job/test-portal-acceptance-upstream-dxp-batch(master)/5052/. There's a new upstream test in progress: https://test-1-16.liferay.com/job/test-portal-acceptance-upstream-dxp-batch(master)/5062/#showFailuresLink

**Comment by john-co** [comment]
ci:test:relevant

**Comment by markocikos** [comment]
@john-co  All of the failures [above](https://github.com/liferay-frontend/liferay-portal/pull/426#issuecomment-708127100) are tied to blogs, in one way or another. I tested both tag changes, they seem to working fine, see gif below. Cards are rendered correctly and deletion works fine (deletion is one of the failing tests).

after

I did notice a weird warning in server logs, but is is also reproducible in `master`:
```
14-Oct-2020 10:05:09.419 WARNING [http-nio-8080-exec-8] com.google.template.soy.shared.restricted.Sanitizers.filterNormalizeUri |filterNormalizeUri received bad value 'javascript:Liferay.Sharing.share(32401, 39401, 'Share\x20A\x20Title')'
```

**Comment by markocikos** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
> I did notice a weird warning in server logs, but is is also reproducible in master:

This is because we're passing `javascript:...` as a url which throws a warning in Soy. I think the similar thing also warns in React now, so eventually we should move that inline `onClick` calls. But yes, it's already present in `master` so it should not be an issue.

**Comment by jbalsas** [comment]
Hey @john-co, could you validate the errors?

**Comment by john-co** [comment]
[unrelated]
- [flaky] BlogsEntryAssetSearchTest#testAllAssetCategories1: https://testray.liferay.com/home/-/testray/cases/1310751709
- [fluke/flaky] BlogsUserNotificationTest#testAddUserNotification: https://testray.liferay.com/home/-/testray/cases/863872657 failed around Oct 13 12:55am with same error
- Blogs permissions integration tests: https://issues.liferay.com/browse/LPS-122112
- BlogsUserNotificationTest.testAddUserNotificationWhenEmailNotificationsDisabled - due to https://issues.liferay.com/browse/LPS-122112

Ok taking a deeper look, I think most if not all of the Blogs integration test failures are caused by this inconsistent issue https://issues.liferay.com/browse/LPS-122112

Reviewed. Test failures are unrelated. :heavy_check_mark:

**Comment by john-co** [comment]
fix has been merged a few hours ago, will rerun tests: https://github.com/brianchandotcom/liferay-portal/pull/94966#issuecomment-708546743

**Comment by john-co** [comment]
ci:test:relevant

**Comment by john-co** [comment]
Reviewed. Test failures are unrelated. :heavy_check_mark: 

Seems like a fluke connection issue with mysql database.

**Comment by markocikos** [comment]
ci:test:relevant

**Comment by wincent** [comment]
Hey @markocikos. In our weekly sync with Brian yesterday I gave him a heads up that this PR was on the way — so that he wouldn't get freaked out when he sees a tag with a ghastly `-v2` suffix at the end — and that there will be multiple steps that we aim to complete before the next mini-release, as per the plan laid out by @jbalsas:

> * Create -v2 tag
> * Move usages to -v2
> * Update main tag (validate with sample widget)
> * Update usages from -v2 to main
>   
>   * Simply rename. Should work all the same. If not, update main tag to account for the fallback
>   * Update deprecated attribute usage
> * Remove -v2 tag

He said to just make sure we label each piece clearly (ie. this one as a straight up rename) so that he won't go over it in fine detail and it will get merged quicker. So I'm going to take that list of steps above and paste it into your description now, but feel free to edit it further as you see fit.

**Comment by markocikos** [comment]
Force-pushed, no changes apart from rebase and clearer commit messages.

**Comment by markocikos** [comment]
ci:test:relevant

**Comment by markocikos** [comment]
All green, pushing!

**Comment by markocikos** [comment]
ci:forward

**Comment by markocikos** [comment]
Well, this is new

```
java.lang.RuntimeException: Unable to find Jenkins master name for Jenkins slave hostname cloud-10-0-16-71
```

@john-co @PablitoBonito help!

**Comment by john-co** [comment]
ci:forward

**Comment by john-co** [comment]
ci team is investigating this issue: https://liferay.slack.com/archives/C19PWQ74J/p1602781473082600

**Pull request closed without merging**
