### PR TITLE
LPS-167587 Fix accessibility issue with ckeditor textarea

### PR DESCRIPTION
**Pull request by edalgrin**
This PR fixes an accessibility issue with the ckeditor textarea label

image

### CODE REVIEW

**Comment by marcoscv-work** [comment]
Adding `aria-labelledby` LGTM!

**Comment by edalgrin** [comment]
ci:test:sf

**Comment by edalgrin** [comment]
ci:test:relevant

**Comment by manoelcyreno** [comment]
ci:test:relevant

**Pull request closed without merging**
