### PR TITLE
LPS-132071 Update liferay-ckeditor to v4.16.0-liferay.1

### PR DESCRIPTION
**Pull request by julien**
As requested in [LPS-132071](https://issues.liferay.com/browse/LPS-132071),
we've updated ckeditor to the `4.16.0` tag

**Changes in this version**

### :wrench: Bug fixes

-   fix: only download extra plugins during the build ([\#173](https://github.com/liferay/liferay-ckeditor/pull/173))

### :house: Chores

-   chore(deps-dev): bump codemirror from 5.57.0 to 5.58.2 ([\#170](https://github.com/liferay/liferay-ckeditor/pull/170))
-   chore(deps): bump lodash from 4.17.20 to 4.17.21 ([\#169](https://github.com/liferay/liferay-ckeditor/pull/169))

[Full changelog](https://github.com/liferay/liferay-ckeditor/compare/v4.14.1-liferay.22...v4.16.0-liferay.1)

### CODE REVIEW

**Comment by julien** [comment]
ci:close

**Comment by julien** [comment]
ci:stop

**Comment by julien** [comment]
ci:test:relevant

**Comment by julien** [comment]
@liferay-frontend please review when you can. thanks

**Review by nhpatt — APPROVED** [review]

**Comment by nhpatt** [comment]
ci:forward

**Pull request closed without merging**
