### PR TITLE
LPS-147201 | Add test to verify admin can approve remote app portlet

### PR DESCRIPTION
**Pull request by susanchen3**
Background
Create automated tests for remote app workflow

Test Plan

- apply workflow process to remote apps
- add a user with permissions to create remote apps
- create remote app as user with permissions
- approve remote app as admin
- assert approved status
- add widget page 
- assert remote app portlet can be added to page

JIRA Ticket:
https://issues.liferay.com/browse/LPS-147201

### CODE REVIEW

**Comment by susanchen3** [comment]
ci:test:frontend:nocompile

**Comment by susanchen3** [comment]
ClayCheckbox#VerifyDefaultUI passes locally, not sure why it's failing on CI

**Comment by john-co** [comment]
Just started reviewing :)

**Review by john-co — APPROVED** [review]
Looks good! Thanks!

**Comment by john-co** [comment]
ci:forward

**Comment by john-co** [comment]
> ClayCheckbox#VerifyDefaultUI passes locally, not sure why it's failing on CI

yea looks like a fluke, failed on setup phase.

**Pull request closed without merging**
