### PR TITLE
LPS-200133 Add check icon to active filter/order in management toolbar

### PR DESCRIPTION
**Pull request by p2kmgcl**
Hi there! I have [a story to improve the accessibility of the management toolbar by adding a "check" icon to active items](https://liferay.atlassian.net/browse/LPS-197980).

It needs the `LPS-198573` feature flag and has been added both in the old and new UI:

image

image

image

[I have discussed with Product Experience team](https://liferay.slack.com/archives/C049XG98GQL/p1698306125217589) if we should be adding it directly to the ClayDropDown component, and they told me that no, that the management toolbar will need extra work to make it accessible. So instead of that I just patched the `FilterOrderControls` component taking advantage of the `symbolLeft` option of each item.

### CODE REVIEW

**Comment by p2kmgcl** [comment]
(Just rebased onto master)

**Review by markocikos — APPROVED** [review]
@p2kmgcl LGTM! :sparkles:

**Comment by p2kmgcl** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward:force

**Pull request closed without merging**
