### PR TITLE
[7.4+][PART 5] LPS-134071 Migrate frontend-theme-styled CSS

### PR DESCRIPTION
**Pull request by edalgrin**
This PR removes all the unused and third-party CSS from `frontend-theme-styled`
- [Original PR](https://github.com/liferay-frontend/liferay-portal/pull/1877#issuecomment-1064926374)
- [Strategy](https://liferay.atlassian.net/wiki/spaces/ENGFRONTENDINFRA/pages/1341882669/LPS-127086+-+Analyze+and+prototype+possible+theme+optimizations?focusedCommentId=1969652346#comment-1969652346)
- [Changelog](https://docs.google.com/spreadsheets/d/1IG7o3hAn9w91-sg_vXQZeWhJsRBSSMTrGUi-EVfQ6H8/edit#gid=0)
- [Module testing](https://docs.google.com/spreadsheets/d/1IG7o3hAn9w91-sg_vXQZeWhJsRBSSMTrGUi-EVfQ6H8/edit#gid=1130153366)

### CODE REVIEW

**Comment by Esther-OC** [comment]
After made the [comparison](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=3&testrayRunIdB=1635343725&testrayRunIdA=1635510489&statusB=2) between this PR and upstream and analyzed one by one the unique failures, it seems that they are not related to the PR, so we can move forward.

After reviewing it together with @edalgrin, we have seen that there is a [test fix](https://testray.liferay.com/home/-/testray/case_results/1636234108?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcases%2F1310740405%2Fview%3Fcur%3D1%26delta%3D200%26testrayCaseId%3D1310740405%26orderByCol%3DcreateDate_sortable%26orderByType%3Ddesc) ongoing which affects three test cases  [LocalFile.WorkflowMetrics#BulkTransitionWorkflowTasks
](https://testray.liferay.com/home/-/testray/cases/1493145286), [LocalFile.WorkflowUsecase#UnpublishAndDeleteUploadedDefinition
](https://testray.liferay.com/home/-/testray/cases/1311684750)  and [LocalFile.WorkflowUsecase#AddDDLRecordWithDoubleApproverDefinition
](https://testray.liferay.com/home/-/testray/cases/1310740405) but it looks like it would not affect the PR, as the module `workflow` is not affected by this changes and all the "input" changes are controlled.  But just for the record 😉

Fingers crossed!  🤞🏻

**Comment by Esther-OC** [comment]
PR reviewed again, I missed some unique failures, I'm so sorry for that 😥  I hope that they can be solved easily!


[Comparison of part 5](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=3&testrayRunIdB=1635343725&testrayRunIdA=1635510489&statusB=2) with upstream:  the unique failures that seems to be related to the PR are the following:

- This three with a ` java.lang.NullPointerException`:
     - [LocalFile.ContentPageTemplatesWithStaging#PublishContentPageBasedOnContentPageTemplateToLive](https://testray.liferay.com/home/-/testray/case_results/1635511557)
     - [LocalFile.ContentPageTemplatesWithWidgets#ConfigurePermissionsOfAP](https://testray.liferay.com/home/-/testray/case_results/1635511579)
     - [LocalFile.DisplayPageTemplatesForWebContentArticle#AccessToEditWebContentAtViewMode](https://testray.liferay.com/home/-/testray/case_results/1635512125)
    
- Two due to an `Element is not present at "//textarea[contains(@name,'Title') or contains(@title,'Title')]`:
     - [LocalFile.BlogsNotifications#NoWebsiteNotificationAppearsForNewBlogsEntry](https://testray.liferay.com/home/-/testray/case_results/1635510911)
     - [LocalFile.BlogsNotifications#NoWebsiteNotificationAppearsForUpdatedBlogsEntry](https://testray.liferay.com/home/-/testray/case_results/1635510923)

- `Expected text "Reply" does not match actual text (case insensitive) "Reply as..." at "//button[contains(.,'Reply')]"`: [LocalFile.BlogsNotifications#CanViewWebsiteNotificationForNewComment](https://testray.liferay.com/home/-/testray/case_results/1635510902)

- `Element is not present at "//div[@class='title'] | //h4/a[contains(.,'${key_portletName} ${key_publicationType} ${key_contentBody}')]"`: [LocalFile.BlogsNotifications#CanViewWebsiteNotificationForMention](https://testray.liferay.com/home/-/testray/case_results/1635510892)

- And some which seems to be flaky, due to a punctual exception or timeout, so for now it seems that they probably won't affect the PR:
     - [LocalFile.DisplayPageTemplatesForWebContentArticle#NavigateToDisplayPageTemplateViaAssetPublisher](https://testray.liferay.com/home/-/testray/case_results/1635512145)
     - [LocalFile.DisplayPageTemplatesForWebContentArticle#PreviewDraftWebContent](https://testray.liferay.com/home/-/testray/case_results/1635512182)
     - [LocalFile.DisplayPageTemplatesForWebContentArticle#NavigateToDisplayPageTemplateViaFriendlyURL](https://testray.liferay.com/home/-/testray/case_results/1635512162): `DevToolsActivePort file doesn't exist `--> probably flaky but it's better to put it on record for reference.

**Comment by edalgrin** [comment]
After taking a look at these issues and tried to understand what was the error, here's what I found:
> * Two due to an `Element is not present at "//textarea[contains(@name,'Title') or contains(@title,'Title')]`:
>   
>   * [LocalFile.BlogsNotifications#NoWebsiteNotificationAppearsForNewBlogsEntry](https://testray.liferay.com/home/-/testray/case_results/1635510911)
>   * [LocalFile.BlogsNotifications#NoWebsiteNotificationAppearsForUpdatedBlogsEntry](https://testray.liferay.com/home/-/testray/case_results/1635510923)

Both cases (new-blog-entry and edit-blog-entry) have the `name="...title"` and `title="Title"` in the markup

img2
img1

---

> * `Expected text "Reply" does not match actual text (case insensitive) "Reply as..." at "//button[contains(.,'Reply')]"`:
>   [LocalFile.BlogsNotifications#CanViewWebsiteNotificationForNewComment](https://testray.liferay.com/home/-/testray/case_results/1635510902)

In my case I found "Reply" instead of "Reply as…" which is correct

img3

---

> * `Element is not present at "//div[@class='title'] | //h4/a[contains(.,'${key_portletName} ${key_publicationType} ${key_contentBody}')]"`:
>   [LocalFile.BlogsNotifications#CanViewWebsiteNotificationForMention](https://testray.liferay.com/home/-/testray/case_results/1635510892)

I wasn't able to test it due to an email verification code I didn't receive (it's the same error as the CI test)

img4

**Comment by edalgrin** [comment]
retrying here https://github.com/liferay-frontend/liferay-portal/pull/2088

**Pull request closed without merging**
