### PR TITLE
LPS-147859 Assert clear button is displayed as an icon button in responsive mode

### PR DESCRIPTION
**Pull request by susanchen3**
**Background**
Create automated tests for Management Toolbar.

**Test Plan**
Given a user of the portal on responsive mode
When the user opens any section with the management toolbar
Then the 'clear' button will be displayed as an icon button

**JIRA Ticket:**
https://issues.liferay.com/browse/LPS-147859

### CODE REVIEW

**Comment by susanchen3** [comment]
ci:test:frontend:nocompile

**Comment by susanchen3** [comment]
ci:test:frontend:nocompile

**Review by Esther-OC — APPROVED** [review]

**Comment by Esther-OC** [comment]
Looks good to me!

**Comment by susanchen3** [comment]
ci:forward

**Pull request closed without merging**
