### PR TITLE
LPS-188508 WYSIWYGUsecase#CanAddBlogsEntryWithImageViaBlogsImages

### PR DESCRIPTION
**Pull request by JerryAdrianoo**
**Description:**
I put a function to wait the picture appears. Testing locally, it takes a while to display, but after some seconds, it appears.

**Jira Ticket:**
https://liferay.atlassian.net/browse/LPS-188508

### CODE REVIEW

**Comment by JerryAdrianoo** [comment]
ci:test:sf

**Comment by JerryAdrianoo** [comment]
ci:test:sf

**Comment by JerryAdrianoo** [comment]
cc@CarlosBrichete

**Comment by CarlosBrichete** [comment]
ci:test:frontend

**Comment by mateusralv** [comment]
Hey @JerryAdrianoo I think the name in the PR title should beWYSIWYGUsecase#CanAddBlogsEntryWithImageViaBlogsImages

**Review by CarlosBrichete — APPROVED** [review]

**Pull request closed without merging**
