### PR TITLE
LPD-36619 - Autogenerate FDS cell class name and customize Minium FDS

### PR DESCRIPTION
**Pull request by juanjofgliferay**
## Goal
Provide a mechanism to identify cells, both for header and body, so it is possible to set the same width for all of them.
- followup of https://github.com/liferay-frontend/liferay-portal/pull/4422
- fix https://liferay.atlassian.net/browse/LPP-54602

### Before
image

### After
image

### CODE REVIEW

**Review by markocikos — APPROVED** [review]
@juanjofgliferay LGTM! :sparkles:

**Comment by juanjofgliferay** [comment]
ci:test:sf

**Comment by juanjofgliferay** [comment]
ci:test:relevant

**Comment by juanjofgliferay** [comment]
cc/ @gianmarcobrunialti

**Comment by ethib137** [comment]
LGTM

**Comment by gianmarcobrunialti** [comment]
Hello @juanjofgliferay and @dsanz, after a quick check in a call also with Juanjo, this is fine to cover the case of Minium theme.

**Pull request closed without merging**
