### PR TITLE
LPS-115551 - Add border color light in admin and classic themes

### PR DESCRIPTION
**Pull request by marcoscv-work**
New design for control-menu-light version, with bottom border in light color:

image

To use the same border in modals and navbars with management-bar below, developers will need to add to navbar the class called `border-bottom` (actually they are currently doing this).

To validate the design you can go to navigate to any section of applications (Global menu).

image

### CODE REVIEW

**Comment by marcoscv-work** [comment]
About the `border-bottom` class:

We don't need to replace or add `border-bottom` class, what Victor Valle wants is the possibility to use the same border-bottom color than control-menu-light, in order to add the class when is necessary, for example, a screen with a navigation bar and a management-bar below next to it.

There are some examples of places they are currently using a border-bottom, like select site modal:
image

image

**Comment by marcoscv-work** [comment]
ci:test:sf

**Comment by marcoscv-work** [comment]
ci:test:stable

**Comment by marcoscv-work** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
> [...] Victor Valle wants is the possibility to use the same border-bottom color than control-menu-light, in order to add the class when is necessary [...]

Well, developers can add any CSS class they want, nothing for us to do there... a different question would be if makes sense to provide that as a higher level API than a CSS class...

Assuming that's what you're saying, that:
- We already have a `border-bottom` class
- When the `border-bottom` class is added to a node, it adds a border bottom with the `light` color?

**Comment by marcoscv-work** [comment]
> > [...] Victor Valle wants is the possibility to use the same border-bottom color than control-menu-light, in order to add the class when is necessary [...]
> 
> Well, developers can add any CSS class they want, nothing for us to do there... a different question would be if makes sense to provide that as a higher level API than a CSS class...
> 
> Assuming that's what you're saying, that:
> 
> * We already have a `border-bottom` class
> * When the `border-bottom` class is added to a node, it adds a border bottom with the `light` color?

**Yes**!

**Comment by marcoscv-work** [comment]
ci:forward

**Comment by jbalsas** [comment]
Hey @marcoscv-work, in the future, please wait to get approval from the reviewers before auto-forwarding the PR or at the very least, add a comment stating the reasons why you're moving forward with it.

If you got approval from other channels, please make sure to reflect that here or have the reviewer do so. That should help us all get clarity on what's happening!

**Pull request closed without merging**
