### PR TITLE
LPS-168521 liferay-util-window use div instead of h3 for title

### PR DESCRIPTION
**Pull request by pat270**
LPS-168521 Remove btn-group from logo-selector causing btn to have square borders

https://issues.liferay.com/browse/LPS-168521

### CODE REVIEW

**Comment by pat270** [comment]
The failures 2. and 4. are due to the html element for modal-title being changed from `h3` to `div`. We need to update the tests for these failures.

**Review by bryceosterhaus — APPROVED** [review]
LGTM

**Comment by mateusralv** [comment]
Hi @pat270 the failures are not related! 🎉 

[Testray Comparison](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1681776942760&testrayRunIdA=2266316269&testrayRunIdB=2266818004)

**Comment by ealonso** [comment]
ci:forward:force

**Comment by pat270** [comment]
ci:test:relevant

**Comment by pat270** [comment]
ci:test:sf

**Comment by pat270** [comment]
@ealonso The conflict should be gone now.

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward:force

**Comment by pat270** [comment]
ci:test:relevant

**Pull request closed without merging**
