### PR TITLE
LPS-118487 - Improve semantics and continuous reading order

### PR DESCRIPTION
**Pull request by marcoscv-work**
This PR fixes some accessibility issues in headers order:

image

And improves some other accessibility parts and reading order

- We add a `<h1 class="sr-only">` with the title "Applications menu" in the same way than others administrator components blocks, it allows move you through admin blocks really quick.
- Change headers `<h3>` to `<h2>`
- Remove the last `<h1>` since it is not useful to identify the block because is almost the last element in the semantic block which we call "Applications menu"
- We remove the `<p>`s in Powered by Liferay DXP in order to not break the reading and read:  `Powered by Liferay DXP` instead of `paragraph` , `Powered by` `paragraph` , `Liferay DXP`

--- 

**How to test it:**

- You can use Axe to certify the error has disappeared
- The rest of the changes are improvements you can check by using screen readers

### CODE REVIEW

**Comment by marcoscv-work** [comment]
ci:test:sf

**Comment by marcoscv-work** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
LGTM

**Comment by jbalsas** [comment]
@eduardoallegrini, care to weigh in on this one?

**Comment by eduardoallegrini** [comment]
ci:forward

**Pull request closed without merging**
