### PR TITLE
LPD-31939 Fix "GraphQL editor on Headless Discovery is not accessible"

### PR DESCRIPTION
**Pull request by izaera**

### CODE REVIEW

**Comment by izaera** [comment]
ci:forward

**Comment by izaera** [comment]
ci:forward

**Review by markocikos — APPROVED** [review]
@izaera LGTM! :sparkles:

**Comment by izaera** [comment]
ci:report:44222485

**Comment by izaera** [comment]
- batch-planner/import.spec.ts: this one is flaky (though it is related to headless so maybe...)
- workspaces/liferay-workspace-marketplace/marketplace-customer-dashboard/marketplaceAppDetails.spec.ts: this one is flaky
- workspaces/liferay-workspace-marketplace/marketplace-customer-dashboard/marketplaceAppPurchase.spec.ts: this one is flaky
- headless-builder-web/get.spec.ts:this one is flaky (though it is related to headless so maybe...)
- client-extension-web/editorConfigContributor.spec.ts: a bit flaky but no so much...
- users-admin-web/userPersonalSite.spec.ts: a bit flaky but no so much...
- com.liferay.headless.delivery.resource.v1_0.test.SitePageResourceTest: **need to investigate this since** it is in headless delivery
- com.liferay.headless.delivery.resource.v1_0.test.StructuredContentResourceTest: **need to investigate this** since it is in headless delivery
- PortalLogAssertorTest-modules-integration-mysql57-jdk8/0/2: unrelated and failing upstream
- object-web/objectEntries.spec.ts: failing upstream

**Pull request closed without merging**
