### PR TITLE
[Draft] LPS-129587 Migrate selection modals in users-admin-web & others

### PR DESCRIPTION
**Pull request by kresimir-coko**
This PR migrates selection modals in `users-admin-web`, which caused the regression with these modals yesterday.

As part of the PR, the 2nd commit (https://github.com/liferay-frontend/liferay-portal/commit/4dd6cfc36ff171f80e8ae802c6d60ca3030682f3) removes usages of `selectEntityHandler` that are triggered by the "parent" modal.

There's a usage of `Liferay.Util.getOpener().Liferay.fire(` that needs to be migrated, but need some guidance on how we handle those now.

# Usages
I tried to find all the usages of the `selectEntity` modal by searching for `selectGroup` or `selectSite` which led me to only one real usage, in `site-browser-web` (the regression source). Other usages of those 2 strings are query selectors, events already migrated, or this function invocation:
```js
function <portlet:namespace />selectOrganization(organizationId, groupId, name, type, target) {
	<portlet:namespace />selectGroup(groupId, name, target);
}
```
# 🧪 Testing
## `site-browser-web/view.jsp` - `sites.jsp` modal
1. Create a new user and then edit it
2. Go to `Memberships` of that user
3. Click on `Select` in the `Sites` section

## `users-admin-web/select_organization.jsp` - `organizations.jsp` modal
1. Create an organization
2. Go to the previously created user and go to their `Organizations`
3. Click on `Select` in the `Organizations` section

## `users-admin-web/select_organization_users.jsp` - `users-admin-web/actions#selectUsers` modal
1. Go to the Organizations tab
2. Assign Users to your Organization
3. Select your existing user/s to add to the Organizations
4. Users are added to the Organization

## `user_item_selector.jsp`
1. Go to Site Admin Menu > People > Segments
2. Add a new user segment
3. Drag the User property from the sidebar to Conditions
4. Click on Select

### CODE REVIEW

**Comment by jonmak08** [comment]
The code looks good, but I am wondering if the CI error is actually relevant since it is an issue in viewing a site's collection.

**Comment by kresimir-coko** [comment]
ci:test:sf

**Comment by kresimir-coko** [comment]
ci:test:relevant

**Comment by kresimir-coko** [comment]
@john-co @zhangyan0701 @nkkwon Can one of you wonderful people please confirm the failing test is related? I think this is the test in question https://github.com/liferay/liferay-portal/blob/master/portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/layout/pagesadmin/PagesAdmin.testcase#L353 but I don't see how display pages are related to my changes.

**Comment by zhangyan0701** [comment]
Hi @kresimir-coko 

The PagesAdmin test isn't related, it's a bug that happened on master upstream and just got resolved today.

**Comment by kresimir-coko** [comment]
Thank you @zhangyan0701

**Comment by kresimir-coko** [comment]
ci:test:relevant

**Comment by john-co** [comment]
ci:test:relevant

**Comment by john-co** [comment]
[Unrelated]
modules-semantic versioning:

I found the first modules semantic error about OrganizationWrapper in upstream: https://testray.liferay.com/home/-/testray/case_results/1526013232

But couldn't find similar error for StagingService semantic error. It's possible that it's a very recent regression in BChan's origin that hasn't synced with upstream at the time of test run.

**Comment by kresimir-coko** [comment]
Is the release done @brunofernandezg (not sure who better to ask)? 

Can I get a review on this to send forward to the appropriate team? @markocikos @jonmak08 Would be awesome if one of you boys would actually pull the code and test the changes, it's been a few days now since I opened it. Otherwise I can rebase tomorrow and check myself.

**Review by markocikos — COMMENTED** [review]
@kresimir-coko Apart from minor tweak inline, looks good! Please forward to 'User and System Management' team (@pei-jung) when ready.

**Pull request closed without merging**
