### PR TITLE
LPS-130578 Update @clayui/* dependencies to v3.29.0

### PR DESCRIPTION
**Pull request by matuzalemsteles**
# [3.29.0](https://github.com/liferay/clay/compare/v3.28.0...v3.29.0) (2021-05-28)

### Bug Fixes

-   **@clayui/css:** Global Functions update `setter` to accept more than 2 variables (e.g., `setter($var1, $var2, $var3, $var4, $var5)`) ([2a923f0](https://github.com/liferay/clay/commit/2a923f0)), closes [#4076](https://github.com/liferay/clay/issues/4076)
-   **@clayui/css:** Mixins `clay-aspect-ratio-item-variant` and `clay-aspect-ratio-variant` convert to use new (easier to remember) Sass map keys. The old keys will still work and win over new keys. ([d4680a9](https://github.com/liferay/clay/commit/d4680a9)), closes [#4085](https://github.com/liferay/clay/issues/4085)
-   **@clayui/css:** Mixins Card convert to use new (easier to remember) Sass map keys. The old keys will still work and win over new keys. ([a2e6d34](https://github.com/liferay/clay/commit/a2e6d34)), closes [#4088](https://github.com/liferay/clay/issues/4088)
-   **@clayui/drop-down:** fixes error when closing the contextual menu ([8bdfa79](https://github.com/liferay/clay/commit/8bdfa79))
-   **@clayui/drop-down:** stops closing the drop-down when the focus is inside the sub portal ([cc57b72](https://github.com/liferay/clay/commit/cc57b72))
-   **@clayui/table:** Fixes lint error ([9dec4a4](https://github.com/liferay/clay/commit/9dec4a4))

### Features

-   **@clayui/css:** Adds the `block` SVG icon ([96dabe4](https://github.com/liferay/clay/commit/96dabe4))
-   **@clayui/drop-down:** add the new contextual type to create a cascading menu ([63960b2](https://github.com/liferay/clay/commit/63960b2))
-   **@clayui/drop-down:** Make it possible to render dividers ([51a46d5](https://github.com/liferay/clay/commit/51a46d5))
-   **@clayui/shared:** Add MouseSafeArea to the contextual menu ([7824f16](https://github.com/liferay/clay/commit/7824f16))
-   **@clayui/table:** Adds the `noWrap` prop to ClayTable.Cell ([da88293](https://github.com/liferay/clay/commit/da88293))

### CODE REVIEW

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by matuzalemsteles** [comment]
Well, the test results are very inconsistent with each other, I'll run it again.

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by julien** [comment]
@matuzalemsteles, I had a look at the test results and some seem unrelated to these changes:

> Failures unique to this pull:
> test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8/0
> Job Results:
> 0 Tests Passed.
> 0 Tests Failed.

0 passed and 0 failed :shrug: 

> Please fix semantic versioning on matuzalemsteles/LPS-130578

This is probably a common failure, we're just updating js dependencies here.

For the rest, I don't know, so I'm going to ask @john-co to give us help identifying these when he gets a chance to do so.

**Comment by matuzalemsteles** [comment]
Thanks @julien

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by john-co** [comment]
@nkkwon please analyze the test failures here.

**Comment by nkkwon** [comment]
Just started reviewing :)

**Comment by nkkwon** [comment]
**Analysis details**
It looks like the failures from https://github.com/liferay-frontend/liferay-portal/pull/1134#issuecomment-851702754 is mostly integration tests failing from the bundles not starting and I don't see it being related to the commits you made. This looks like it could be an issue with CI

**Comment by nkkwon** [comment]
@matuzalemsteles 

Looking at the new relevant tests https://github.com/liferay-frontend/liferay-portal/pull/1134#issuecomment-852332191, all these failures are flaky and occurred in other instances and unrelated to the commits to this PR
Looks good to forward to me!

**Comment by matuzalemsteles** [comment]
Thanks @nkkwon, I will send this manually

**Comment by matuzalemsteles** [comment]
Forwarded https://github.com/brianchandotcom/liferay-portal/pull/102608

**Comment by john-co** [comment]
ci:test:frontend

**Pull request closed without merging**
