### PR TITLE
LPS-141458 Inherited Roles UI getting distorted when roles list is long

### PR DESCRIPTION
**Pull request by holatuwol**
https://issues.liferay.com/browse/LPS-141458

/cc @quanhuynhces

### Steps to reproduce (7.3.x only)

1. Navigate Control Panel -> User and Organizations -> Organizations -> Create Org (TestOrg)
2. Navigate Control Panel -> Roles (Regular Roles)
3. Create a regular role with a longer name (example: `RegularRoleOne_RegularRoleTwo_RegularRoleThree_RegularRoleFour_1`)
4. Once Role is created -> Goto Assignees Tab -> Associate Role with (TestOrg)
5. Repeat above Steps (2,3,4) for 2 more times (example: `RegularRoleOne_RegularRoleTwo_RegularRoleThree_RegularRoleFour_2` and `RegularRoleOne_RegularRoleTwo_RegularRoleThree_RegularRoleFour_3`)
6. Navigate to Control Panel -> User and Organizations -> Users -> Create User (TestUser)
7. Assign Organization (TestOrg) to user, it will automatically inherit the roles granted to (TestOrg)
8. Go to Roles tab.

**Expected behavior**: INHERITED REGULAR ROLES can be displayed correctly.
**Current behavior**: Inherited Roles UI getting distorted.

### Notes about the solution

The issue only affects versions of Liferay that use an older version of clay-css, since the issue is resolved in master via an update to clay-css (3.22.0):

* https://github.com/liferay/clay/commit/6f7f2bf55a8820ac545a92cbfbd5eabf5ecee7b7
* https://github.com/liferay/clay/blob/master/packages/clay-css/CHANGELOG.md#3220-2020-12-16

We can fix the issue in those versions without an update to clay by adding the `table-cell-expand` class to the table cell that we need to have `word-wrap: break-word` applied. A lot of the other cells within the same .jsp already have this class, so updating this cell to match seemed like a sensible solution.

### CODE REVIEW

**Comment by holatuwol** [comment]
ci:test:sf

**Comment by bryceosterhaus** [comment]
@holatuwol, this seems good to me. Since this is only 7.3 though, do we need to still forward this for master or can we send it specifically to 7.3.x?

**Comment by holatuwol** [comment]
> Since this is only 7.3 though, do we need to still forward this for master or can we send it specifically to 7.3.x?

My understanding of the unique fixes process is that we can only do 7.3.x unique fixes if the changes cause issues in master or are no longer possible in master (refactoring has moved the code). If the code itself still exists in master and the fix doesn't cause any regressions in master, the change needs to happen to master first.

**Comment by bryceosterhaus** [comment]
Oh gotcha, that makes sense. Also, I didn't realize this initially, but this touches the `users-admin-web` module which I think this should be sent to the User & System Management Team before approving. Not sure if they have their own repo, but you could contact Drew Brokke.

**Comment by holatuwol** [comment]
https://github.com/liferay-usm/liferay-portal/pull/351

**Pull request closed without merging**
