### PR TITLE
LPS-114698 Rename

### PR DESCRIPTION
**Pull request by brunobasto**
@brianchandotcom asked for some changed [here](https://github.com/brianchandotcom/liferay-portal/pull/90984#issuecomment-654448151) so I added https://github.com/liferay-frontend/liferay-portal/pull/79/commits/32ee112a8bd0e4ea504ef6eeb601c448625c3047

### CODE REVIEW

**Comment by brunobasto** [comment]
ci:test:sf

**Comment by brunobasto** [comment]
ci:test:relevant

**Comment by brunobasto** [comment]
ci:forward

**Comment by wincent** [comment]
Fingers crossed this time 🤞 ...

**Comment by brunobasto** [comment]
There were conflicts. I'll resend.

**Pull request closed without merging**
