### PR TITLE
[7.4-only] LPS-123984 Migrate aspectRatioCssClasses usages to use new flush API

### PR DESCRIPTION
**Pull request by julien**
Some uses of the tags were implementing the
`getAspectRatioCssClasses` method (which should be deprecated)
to handle the card image aspect ratios in `<clay:vertical-card>`.

In this change, we're replacing it with the new `isFlushHorizontal`
method.

cc @carloslancha @markocikos 

PS: For the moment, submitting as a draft until the next clay release is in DXP.

### CODE REVIEW

**Comment by julien** [comment]
ci:test:sf

**Review by markocikos — APPROVED** [review]
LGTM!

**Comment by julien** [comment]
ci:test:sf

**Comment by julien** [comment]
ci:test:relevant

**Comment by carloslancha** [comment]
ci:forward

**Pull request closed without merging**
