### PR TITLE
LPS-153277 Move CodeMirrorEditor to frontend-js-components-web

### PR DESCRIPTION
**Pull request by miltonmc**
### References

- [LPS-152284](https://issues.liferay.com/browse/LPS-152284)
- [LPS-153277](https://issues.liferay.com/browse/LPS-153277)

### What is the goal?

The team of the Objects initiative got a request form @brianchandotcom and @marco-leo to avoid create new components if a similar one exists in the Portal, but move to a common place and use it instead. This PR is intend to unify all the implementations of the `CodeMirrorEditor` into a single component.

Currently we have:
- `modules/apps/fragment/fragment-web/src/main/resources/META-INF/resources/js/fragment-editor/CodeMirrorEditor.js`
- `modules/apps/object/object-web/src/main/resources/META-INF/resources/js/components/CodeMirrorEditor.tsx`
- `modules/apps/template/template-web/src/main/resources/META-INF/resources/js/ddm_template_editor/components/CodeMirrorEditor.js`

They all look the same but with little differences and the Idea is move the component from the  `object-web` to the `frontend-js-components-web` and then evolve it until he have all we need to replace and remove the other implementations. This implementation was chosen as the candidate, because it is basically a copy of the one inside the `template-web`, but refactored  and supporting TypeScript.

### What does it look like?
Screenshot from 2022-05-12 16-49-34

### Additional Notes
In order to enable the full support to TypeScript in the `frontend-js-components-web`, this PR also contains the migration of the existent components in the module to TS. 

cc: @matuzalemsteles and @dsanz

### CODE REVIEW

**Comment by diegonvs** [comment]
Hey @miltonmc, could you describe why you're creating this component here? 

You can follow this structure if you want

```
### References

- [LPS-XXXXX](https://issues.liferay.com/browse/LPS-XXXXX)

### What is the goal?

### What does it look like?

#### Before PR
#### After PR

### How to replicate
```

**Comment by miltonmc** [comment]
ci:test:relevant

**Comment by miltonmc** [comment]
ci:test:sf

**Comment by miltonmc** [comment]
ci:test:relevant

**Comment by miltonmc** [comment]
ci:reevaluate:1367401_1118

**Comment by miltonmc** [comment]
ci:reevaluate:1367401_1118

**Comment by miltonmc** [comment]
ci:test:sf

**Comment by miltonmc** [comment]
ci:test:relevant

**Comment by dsanz** [comment]
Hey @miltonmc, thanks so much for this pull. Afaik, this is the first time we reach the "will this component be used in the whole portal?" question in [the process we agreed](https://liferay.atlassian.net/wiki/spaces/ENGFORMS/pages/1992557531/Project+Collaboration+Agreement+-+DXP+React+Component+Library#The-Process).

As per your initial investigation, it looks like there are some usages out there. I'd add some more:
 * [CodeMirrorTextArea.js](https://github.com/liferay/liferay-portal/blob/2071a19645ca3d7bafdbbcc259cf3e9f78837b1d/modules/apps/portal-search/portal-search-web/src/main/resources/META-INF/resources/js/components/CodeMirrorTextArea.js#L36) in `search-web`
 * [CodeMirrorEditor.js](https://github.com/liferay/liferay-portal/blob/ae94e26e33d449a442ad423c53167c80cb0ada2e/modules/dxp/apps/search-experiences/search-experiences-web/src/main/resources/META-INF/resources/sxp_blueprint_admin/js/shared/CodeMirrorEditor.js#L513) in `search-experiences-web`
 
These require some analysis to ensure we can factor out common elements. I'm particularly concerned with the [fragment-editor](https://github.com/liferay/liferay-portal/blob/21078d8663ae2a8d264f611a68d0e17c4ef9a056/modules/apps/fragment/fragment-web/src/main/resources/META-INF/resources/js/fragment-editor/CodeMirrorEditor.js#L233) case, for which I see a fairly complex use case (for example, the registration of events beyond "onChange", or the use of intermediate components like `<FixedText>`) which makes me doubt about the feasibiity of coming up with something that can be used there, other than the "codemirror" itself or a super tiny wrapper on top of it. Similar concerns apply to the search-experiences-web case.

I understand it's not scope of this PR, nevertheless, before creating a component in `frontend-js-components-web` and support the effort of maintaining it portal-wide, we have to be super sure we'll be able to use it in such complex scenarios, otherwise we'd be defeating the concept of a common component usable throughout DXP. I'd like to see more insights about the applicability of the CodeEditor component in these scenarios before making a decision. This is the kind of discussion I'd expect to see in this PR along with @matuzalemsteles and @diegonvs as part of the agreement. A pontentially great reason to unify these is the ability to plug a client extension to change the default editors we use there as we talked several times with @marco-leo

A side question is about the need to migrate every other thing there to typescript. I don't see any particular reason to do this in this pull request, unless it's striclty needed for some compiler-related reason. I'd rather prefer a clear separation of concerns and work on TS adoption in a separate effort. Is there any reason to do this in the same pull?

Thank you

**Comment by miltonmc** [comment]
@dsanz thank you so much for your comments!

You are right, this is the my first component submission for frontend-infra. I'm not sure how to handle that, but I thought we could add the `CodeEditor` to the `frontend-js-components-web` as a kind of draft an evolve it until it is ready to be shared along the portal.

Regarding the TypeScript migration, I was not sure how should I merge an auto generated definition of type with a manual one (I have some ideias but they sound as a workaround), so I did the whole conversion, because it was not a big deal and I would give a better understanding of the components implemented in the module. But I agree with you that it would be better if we split those conversions into distincted PRs. Since I've already splitted the migration in distinct commits it will be an easy thing to do. :smile:

**Comment by matuzalemsteles** [comment]
I have the same feeling as @dsanz here. I think the best way to deal with this would be to first study all the DXP use cases to create something that is common to everyone. The problem with this is that this is a ready-made component so we have to study if it makes sense to create another layer on top of CodeMirrorEditor and create an API mapping, I see value in providing something very simple just with the responsibility of having `CodeMirror ` being rendered as part of "React" otherwise I think we would just be creating a 1:1 API mapping and that would swell over time as each team needs to pass APIs to CodeMirrorEditor.

So I think before submitting this we would need to understand what we have in the other teams and see if the simple one can already be used by the teams otherwise we can add something that doesn't work for everyone.

**Comment by miltonmc** [comment]
ci:test:sf
ci:test:relevant

**Comment by miltonmc** [comment]
ci:test:relevant

**Comment by miltonmc** [comment]
ci:test:relevant

**Comment by miltonmc** [comment]
ci:test:sf

**Comment by miltonmc** [comment]
ci:test:relevant

**Comment by miltonmc** [comment]
ci:test:sf

**Comment by miltonmc** [comment]
ci:test:relevant

**Comment by miltonmc** [comment]
ci:test:relevant

**Comment by miltonmc** [comment]
ci:reevaluate:1307401_4064

**Comment by miltonmc** [comment]
ci:test:relevant

**Comment by miltonmc** [comment]
ci:test:sf

**Comment by miltonmc** [comment]
ci:test:relevant

**Comment by miltonmc** [comment]
@dsanz and @matuzalemsteles this is my last week at Liferay, so how should we proceed with this PR?

**Comment by miltonmc** [comment]
@marco-leo any thoughts about how should we proceed in this case?

**Comment by dsanz** [comment]
@markocikos @carloslancha please take a look at this. I'd like to assess the possibility of owning this component as it's being repeatedly used. Nevertheless, as I [mentioned above](https://github.com/liferay-frontend/liferay-portal/pull/2229#issuecomment-1126243031), I see quite different usages in the portal:
* [CodeMirrorEditor.js](https://github.com/liferay/liferay-portal/blob/9d92df1e7631ee2212accd07a860264a869051f0/modules/apps/layout/layout-content-page-editor-web/src/main/resources/META-INF/resources/page_editor/app/components/CodeMirrorEditor.js#L53https://github.com/liferay/liferay-portal/blob/9d92df1e7631ee2212accd07a860264a869051f0/modules/apps/layout/layout-content-page-editor-web/src/main/resources/META-INF/resources/page_editor/app/components/CodeMirrorEditor.js) in layout-content-page-editor-web
* [CodeMirrorEditor.tsx](https://github.com/liferay/liferay-portal/blob/d2e1a8a27edce11670e8ea8d65bad704ac262734/modules/apps/object/object-js-components-web/src/main/resources/META-INF/resources/components/CodeEditor/CodeMirrorEditor.tsx) in object-js-components-web
* [CodeMirrorEditor.js](https://github.com/liferay/liferay-portal/blob/df4c2b7db59d93d740cdaece21a645266fb8cda0/modules/apps/template/template-web/src/main/resources/META-INF/resources/js/ddm_template_editor/components/CodeMirrorEditor.js) in template-web
* [CodeMirrorEditor.js](https://github.com/liferay/liferay-portal/blob/2366d002ceeaf810f7a67ef8f1edb5ec119ba4e0/modules/apps/fragment/fragment-web/src/main/resources/META-INF/resources/js/fragment-editor/CodeMirrorEditor.js) in fragment-web
* [CodeMirrorEditor.js](https://github.com/liferay/liferay-portal/blob/5129515986dfdff2d526cf261c1036cb58ccbafc/modules/dxp/apps/search-experiences/search-experiences-web/src/main/resources/META-INF/resources/sxp_blueprint_admin/js/shared/CodeMirrorEditor.js) in search-experiences-web

It's clear to me that there are many usages out there, what I'd like to assess is whether there's room for some generalization that could be captured into a component wrapping the bare `codemirror` and used elsewhere.

**Comment by markocikos** [comment]
@dsanz It looks to me like it does make sense for FI to own the component. The 3 usages rule is not in question. I think the only question is if the usages have common parts that make sense to extract, or are they very diverse implementations of external `codemirror/*` libraries. From a glance on this PR, it looks like there are plenty of common parts. @carloslancha knows the component really well, as he did a lot of work on [migration of this component to React](https://issues.liferay.com/browse/LPS-109849). He should give a much more informed answer than me.

**Comment by cgmonte** [comment]
ci:test:sf

**Comment by cgmonte** [comment]
ci:test:relevant

**Comment by cgmonte** [comment]
> @alinedoleron and @cgmonte, could you please resolve the conflicts again?

Yes, sure. I can do it latter today.

**Comment by carloslancha** [comment]
Hey, sorry guys, I'd swear I answered this.

As @markocikos said this is indeed a component that should live under FI umbrella. What I don't think is the best approach is to just move one of the usages (objects in this case) to our roof and just iterate after that to fit with the rest of ussages. We've been dealing with this kind of approaches too much lately and it usually ends with the component full of weird stuff, over engineered code, confuse API and a lot of contradictions about its behavior.

IMHO the correct approach should be to analayse current usages, find the common points, patterns, API and so on and create a component that everyone could use, in the way that we want it to be used instead of just create patches with each "migration".

Any thoughts @markocikos ?

**Comment by cgmonte** [comment]
> > @alinedoleron and @cgmonte, could you please resolve the conflicts again?
> 
> Yes, sure. I can do it latter today.

Regarding de resolution of conflicts, they're already resolved, but I decided to validate a design detail with the design team before pushing it. Will push the rebase as soon as this happens.

**Comment by cgmonte** [comment]
ci:test:sf

**Comment by cgmonte** [comment]
ci:test:relevant

**Comment by markocikos** [comment]
I believe we have reached a consensus on this in FI. We want to make a deep analysis of `CodeMirrorEditor` API and usages. Based on the analysis, we may choose to:
1. keep usages as they are, if the common points in usages are very few. - or -
1. make a wrapper of base editor, extracting commonly used customizations, and migrate existing usages.

If we do add `CodeMirror` wrapper as a new editor, it should be in `frontend-editor` app, consistent with other DXP-wide editors we support.

This would be a new epic, with analysis as its starting spike.

We don't want to move one of the usages, without consideration of the larger picture. As such, **we will not merge this PR**. However, it should still be very useful as a reference for future migration.

@dsanz @carloslancha @cgmonte @rodrigopaulino

**Comment by rodrigopaulino** [comment]
Ok. Thanks for the feedback, @markocikos.

**Comment by rodrigopaulino** [comment]
ci:close

**Pull request closed without merging**
