### PR TITLE
LPS-173575 Use flex class for unstyled to be displayed correctly

### PR DESCRIPTION
**Pull request by georgel-pop-lr**
Changes unstyled theme to use same flex classes as classic theme does: https://github.com/liferay/liferay-portal/blob/bacdae7fa302e5eb5cfae10661273b984ea9ed06/modules/apps/frontend-theme/frontend-theme-classic/src/templates/portal_normal.ftl#L21-L24

Before:
image
image

After this fix:
image
image

### CODE REVIEW

**Comment by georgel-pop-lr** [comment]
ci:test:sf

**Comment by georgel-pop-lr** [comment]
ci:test:sf

**Comment by georgel-pop-lr** [comment]
ci:test:relevant

**Comment by deborasoliveira** [comment]
I'll take a look at it 🧐

**Comment by deborasoliveira** [comment]
Hello!
I wasn't able to finish the analysis today but I'll continue it tomorrow 👍🏽

**Comment by deborasoliveira** [comment]
Hi @georgel-pop-lr! 
Can you take a look at the semantic-versioning-jdk8/0/0 error?
```
clean-up-java-processes:
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/clean_up_java_processes.sh
[stopwatch] [run.batch.test.setup: 19:13.159 sec]
     [echo] run.batch.test.action.start.timestamp: 01-25-2023 04:11:50:576 PST
     [echo] Checking for baseline log files.
     [echo] 
     [echo] ##
     [echo] ## /opt/dev/projects/github/liferay-portal/baseline-reports/portal-impl.log
     [echo] ##
     [echo] 
[beanshell]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
[beanshell] = ================================================== ========== ========== ========== ========== ==========
[beanshell] * com.liferay.portal.util                            MAJOR      41.1.0     41.1.0     42.0.0     VERSION INCREASE REQUIRED
[beanshell] 	>   class      com.liferay.portal.util.PropsValues
[beanshell] 		-   field      TEXT_EXTRACTION_FORK_PROCESS_ENABLED
[beanshell] 			-   access     final
[beanshell] 			-   access     static
[beanshell] 			-   return     boolean
[beanshell] 		-   field      TEXT_EXTRACTION_FORK_PROCESS_MIME_TYPES
[beanshell] 			-   access     final
[beanshell] 			-   access     static
[beanshell] 			-   return     java.lang.String[]
[beanshell] [Baseline Warning] Bundle Version Change Recommended: 66.0.0
[beanshell] 
     [echo] 
     [echo] ##
     [echo] ## /opt/dev/projects/github/liferay-portal/baseline-reports/portal-kernel.log
     [echo] ##
     [echo] 
[beanshell]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
[beanshell] = ================================================== ========== ========== ========== ========== ==========
[beanshell] * com.liferay.portal.kernel.util                     MAJOR      52.0.0     52.0.0     53.0.0     VERSION INCREASE REQUIRED
[beanshell] 	>   interface  com.liferay.portal.kernel.util.PropsKeys
[beanshell] 		-   field      TEXT_EXTRACTION_FORK_PROCESS_ENABLED
[beanshell] 			-   access     final
[beanshell] 			-   access     static
[beanshell] 			-   constant   text.extraction.fork.process.enabled
[beanshell] 			-   return     java.lang.String
[beanshell] 		-   field      TEXT_EXTRACTION_FORK_PROCESS_MIME_TYPES
[beanshell] 			-   access     final
[beanshell] 			-   access     static
[beanshell] 			-   constant   text.extraction.fork.process.mime.types
[beanshell] 			-   return     java.lang.String
[beanshell] 
[stopwatch] [run.batch.test.action: 4.956 sec]
     [echo] Semantic versioning is incorrect.
      [get] Getting: http://test-1-31/job/test-portal-acceptance-pullrequest-downstream(master)/394042//consoleText
      [get] To: /opt/dev/projects/github/liferay-portal/20230125041155533.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/20230125041155533.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null968128974.properties
``` 
🤔 I think it could be related to your PR. Apart from this, there's no failure related to your PR.

**Comment by georgel-pop-lr** [comment]
ci:test:sf

**Comment by georgel-pop-lr** [comment]
ci:test:relevant

**Comment by georgel-pop-lr** [comment]
> Hi @georgel-pop-lr! Can you take a look at the semantic-versioning-jdk8/0/0 error?
> 
> ```
> clean-up-java-processes:
>    [delete] Deleting: /opt/dev/projects/github/liferay-portal/clean_up_java_processes.sh
> [stopwatch] [run.batch.test.setup: 19:13.159 sec]
>      [echo] run.batch.test.action.start.timestamp: 01-25-2023 04:11:50:576 PST
>      [echo] Checking for baseline log files.
>      [echo] 
>      [echo] ##
>      [echo] ## /opt/dev/projects/github/liferay-portal/baseline-reports/portal-impl.log
>      [echo] ##
>      [echo] 
> [beanshell]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
> [beanshell] = ================================================== ========== ========== ========== ========== ==========
> [beanshell] * com.liferay.portal.util                            MAJOR      41.1.0     41.1.0     42.0.0     VERSION INCREASE REQUIRED
> [beanshell] 	>   class      com.liferay.portal.util.PropsValues
> [beanshell] 		-   field      TEXT_EXTRACTION_FORK_PROCESS_ENABLED
> [beanshell] 			-   access     final
> [beanshell] 			-   access     static
> [beanshell] 			-   return     boolean
> [beanshell] 		-   field      TEXT_EXTRACTION_FORK_PROCESS_MIME_TYPES
> [beanshell] 			-   access     final
> [beanshell] 			-   access     static
> [beanshell] 			-   return     java.lang.String[]
> [beanshell] [Baseline Warning] Bundle Version Change Recommended: 66.0.0
> [beanshell] 
>      [echo] 
>      [echo] ##
>      [echo] ## /opt/dev/projects/github/liferay-portal/baseline-reports/portal-kernel.log
>      [echo] ##
>      [echo] 
> [beanshell]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
> [beanshell] = ================================================== ========== ========== ========== ========== ==========
> [beanshell] * com.liferay.portal.kernel.util                     MAJOR      52.0.0     52.0.0     53.0.0     VERSION INCREASE REQUIRED
> [beanshell] 	>   interface  com.liferay.portal.kernel.util.PropsKeys
> [beanshell] 		-   field      TEXT_EXTRACTION_FORK_PROCESS_ENABLED
> [beanshell] 			-   access     final
> [beanshell] 			-   access     static
> [beanshell] 			-   constant   text.extraction.fork.process.enabled
> [beanshell] 			-   return     java.lang.String
> [beanshell] 		-   field      TEXT_EXTRACTION_FORK_PROCESS_MIME_TYPES
> [beanshell] 			-   access     final
> [beanshell] 			-   access     static
> [beanshell] 			-   constant   text.extraction.fork.process.mime.types
> [beanshell] 			-   return     java.lang.String
> [beanshell] 
> [stopwatch] [run.batch.test.action: 4.956 sec]
>      [echo] Semantic versioning is incorrect.
>       [get] Getting: http://test-1-31/job/test-portal-acceptance-pullrequest-downstream(master)/394042//consoleText
>       [get] To: /opt/dev/projects/github/liferay-portal/20230125041155533.txt
>    [delete] Deleting: /opt/dev/projects/github/liferay-portal/20230125041155533.txt
>    [delete] Deleting: /opt/dev/projects/github/liferay-portal/null968128974.properties
> ```
> 
> thinking I think it could be related to your PR. Apart from this, there's no failure related to your PR.
> 
> cc: @mateusralv, @john-co

Hi @deborasoliveira,

I doubt they are related, as I did not touch com.liferay.portal.util.PropsValues and com.liferay.portal.kernel.util.PropsKeys, I rebased the branch and relaunch tests, let's see if it is still complaining.

Regards.

**Comment by georgel-pop-lr** [comment]
ci:test:relevant

**Comment by deborasoliveira** [comment]
Hi @georgel-pop-lr! I'm gonna take a look at the relevant new results 👍🏽

**Comment by deborasoliveira** [comment]
Hi @georgel-pop-lr! I've analyzed the most recent relevant results and according to the [comparison](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1675099343461&testrayRunIdA=2179893916&testrayRunIdB=2180213410), the failures are not related to your PR. If no other dev review is needed you can manually forward it. 👍🏽 

cc: @john-co, @mateusralv

**Comment by georgel-pop-lr** [comment]
> Hi @georgel-pop-lr! I've analyzed the most recent relevant results and according to the [comparison](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1675099343461&testrayRunIdA=2179893916&testrayRunIdB=2180213410), the failures are not related to your PR. If no other dev review is needed you can manually forward it. 👍🏽
> 
> cc: @john-co, @mateusralv

Hi all,

Could this be moved forward?

Regards.

**Comment by deborasoliveira** [comment]
ci:forward

**Comment by john-co** [comment]
Hi @deborasoliveira , thanks for the review and moving this forward but please double check if a dev review is still needed. It doesn't look like any other FI dev reviewed this. Can message @markocikos @dsanz next time if you don't see a dev review checkmark.

**Pull request closed without merging**
