### PR TITLE
LPS-179234 | Add Autom. test ClayAlertToast#ContainerWithLink

### PR DESCRIPTION
**Pull request by deborasoliveira**
**ClayAlertToast#ContainerWithLink**
**Test Plan**

- Given Clay Sample Portlet
- When Click "Disappears After 10 Seconds" button
- And Click on the link Displayed Clay Toast Alert
- Then navigates to the href

JIRA Ticket
https://issues.liferay.com/browse/LPS-179234

### CODE REVIEW

**Comment by deborasoliveira** [comment]
ci:test:frontend

**Comment by deborasoliveira** [comment]
ci:test:relevant

**Comment by deborasoliveira** [comment]
ci:test:frontend

**Review by mateusralv — APPROVED** [review]

**Comment by mateusralv** [comment]
ci:forward

**Pull request closed without merging**
