### PR TITLE
LPS-132744 Isolates Portlet Topper Modals

### PR DESCRIPTION
**Pull request by pat270**
https://issues.liferay.com/browse/LPS-132744

This pr isolates portlet topper modals and simulation menu preview that use the old aui modal plugin and newer  Liferay.Portlet.openModal based on ClayModal. I also fixed the double scrollbars in the modals using the aui version (Look and Feel, Permissions, and Configuration Templates).

Just leaving this part for the future if someone needs to do this. For modals using `Liferay.Portlet.openModal`, you can un-isolate it with:
```
Liferay.Portlet.openModal({
    containerProps: {
        className: '',
    },
});
```

Screenshots:
Look and Feel
look-and-feel

Export Import
export-import

Configuration
configuration

Permissions
permissions

Configuration Templates
configuration-templates

### CODE REVIEW

**Comment by pat270** [comment]
ci:test:relevant

**Comment by pat270** [comment]
ci:reevaluate:1317401_71

**Comment by pat270** [comment]
ci:test:relevant

**Comment by markocikos** [comment]
A true leet PR! :nerd_face:

**Comment by nhpatt** [comment]
Nice catch :D

**Comment by nhpatt** [comment]
Failure is related to the PR:

```
› 1 snapshot failed.
Summary of all failing tests
FAIL test/liferay/modal/Modal.js
  ● Modal › renders markup based on given configuration

    expect(received).toMatchSnapshot()

    Snapshot name: `Modal renders markup based on given configuration 1`

    - Snapshot  - 1
    + Received  + 3

    @@ -1,10 +1,12 @@
      <body
        class="modal-open"
      >
        <div />
    -   <div>
    +   <div
    +     class="cadmin"
    +   >
          <div
            class="modal-backdrop fade show"
          />
          <div
            class="fade modal d-block liferay-modal show"

      47 | 		});
      48 | 
    > 49 | 		expect(baseElement).toMatchSnapshot();
         | 		                    ^
      50 | 	});
      51 | 
      52 | 	it('renders in full screen, if url is set', () => {

      at Object.it (test/liferay/modal/Modal.js:49:23)


Snapshot Summary
 › 1 snapshot failed from 1 test suite. Inspect your code changes or re-run jest with `-u` to update them.
```

I can fix/investigate it if you need it @pat270

**Comment by pat270** [comment]
@nhpatt I'll update and resend. How and where did you find that error?

**Comment by pat270** [comment]
Also 
KmHueA88mFABT9GkkR

**Comment by pat270** [comment]
ci:test:relevant

**Comment by pat270** [comment]
Ok I see how you came to that conclusion now, thanks. The error log was making no sense to me. I used `yarn` to get things to update, hopefully those commands are the same ones executed by `gr packageRunTest`.

**Comment by nhpatt** [comment]
Yep, the gradle wrapper basically calls yarn and adds delays.

**Comment by pat270** [comment]
ci:reevaluate:1277401_818

**Comment by pat270** [comment]
ci:test:relevant

**Comment by pat270** [comment]
QWjFSsvUPCUncq6ItU

**Comment by nhpatt** [comment]
@edalgrin any comments? or we'll ci:forward it

**Review by edalgrin — APPROVED** [review]
The code seems good!

**Comment by nhpatt** [comment]
ci:forward

**Pull request closed without merging**
