### PR TITLE
LPD-39400 Stored XSS in remote apps component 

### PR DESCRIPTION
**Pull request by izaera**
# :green_circle: This is safe to forward after code review

QA analysis: https://github.com/liferay-frontend/liferay-portal/pull/4491#issuecomment-2418701747 :white_check_mark:

### CODE REVIEW

**Comment by izaera** [comment]
ci:test:relevant

**Comment by izaera** [comment]
ci:test:sf

**Comment by izaera** [comment]
ci:report:43469311

**Comment by izaera** [comment]
QA analysis:

No unique failures. This is safe to forward :white_check_mark:

**Review by bryceosterhaus — APPROVED** [review]
LGTM

**Comment by izaera** [comment]
ci:forward:force

**Comment by izaera** [comment]
ci:forward:force

**Pull request closed without merging**
