### PR TITLE
LPS-197771 - Create generic creation button actions

### PR DESCRIPTION
**Pull request by juanjofgliferay**
Followup on https://github.com/liferay-frontend/liferay-portal/pull/3756

### CODE REVIEW

**Comment by juanjofgliferay** [comment]
ci:test:relevant

**Comment by juanjofgliferay** [comment]
ci:test:relevant

**Comment by juanjofgliferay** [comment]
ci:reevaluate:1407401_6743

**Comment by juanjofgliferay** [comment]
ci:test:relevant

**Comment by juanjofgliferay** [comment]
ci:test:stable

**Comment by deborasoliveira** [comment]
I'll check the results.

**Comment by deborasoliveira** [comment]
I've checked relevant and stable results and the failures seem to be unrelated.

[Comparison Run](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=2&testrayRunIdB=2443833640&testrayRunIdA=2442953744&statusB=3)

**Comment by juanjofgliferay** [comment]
ci:forward:force

**Comment by juanjofgliferay** [comment]
ci:test:stable

**Comment by juanjofgliferay** [comment]
ci:forward:force

**Pull request closed without merging**
