### PR TITLE
LPS-130742 Migrate asset/input_asset_links

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @liferay-frontend,

Attached is an update for http://issues.liferay.com/browse/LPS-130742.

**Test Plan:**

1. Login to Liferay
2. Click on the **Product Menu**
3. Go to **Content & Data** -> **Web Content**
4. Click the `+` to add a **Basic Web Content**
5. Scroll down the **Properties**  to the **Related Assets** section
6. Click the **Select** button and choose **Blogs Entry**
7. Publish the **Web Content**
8. Click on the **Product Menu**
9. Go to **Content & Data** -> **Blogs**
10. Click the `+` to add a **Blog Entry**
11. Scroll down to the **Related Assets** section
12. Click the **Select** button and choose **Basic Web Content**
13. Select the newly created **Web Content** in the modal window
asset

**Test Plan for Management Toolbar Update (https://github.com/liferay-frontend/liferay-portal/pull/989/commits/5f3965332e6bfef94ee25af4ec801cd542c72f11)**
14. Click on the **Product Menu**
15. Go to **Site Builder** -> **Pages**
16. Click the `+` to add a **Public Collection Page**
17. Click the `+` to add a **Manual Collection**

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by jonmak08** [comment]
ci:test:sf

**Comment by jonmak08** [comment]
ci:test:relevant

**Review by markocikos — COMMENTED** [review]
@jonmak08  Is [the baseline commit](https://github.com/liferay-frontend/liferay-portal/pull/989/commits/b47fdf684470639ea23161b35dfdb82def8a7d5d) temporary, just for CI testing? It looks unrelated to this PR, changing versions of `portal-impl` and `portal-kernel`.

Other than that, LGTM!

**Comment by jonmak08** [comment]
> @jonmak08 Is [the baseline commit](https://github.com/liferay-frontend/liferay-portal/pull/989/commits/b47fdf684470639ea23161b35dfdb82def8a7d5d) temporary, just for CI testing? It looks unrelated to this PR, changing versions of `portal-impl` and `portal-kernel`.

For some reason when I went to deploy the changes for the `asset` module itself, those files did not appear, but my portal ended up throwing a lot of `NullPointer` errors, so I went and built portal (`ant all`) with my changes and those files were altered after the build was successful.  I usually do not have those files, but figured I would add them to hopefully run the `ci:test:relevant` and see what happens.

 It looks like it is throwing errors anyways, so I will remove that commit and rerun the tests and see if it passes.

**Comment by jonmak08** [comment]
ci:test:sf

**Comment by jonmak08** [comment]
ci:test:relevant

**Comment by jonmak08** [comment]
ci:test:sf

**Comment by jonmak08** [comment]
ci:test:relevant

**Comment by markocikos** [comment]
@jonmak08 with GA released, there are no blockers to move forward with this. Did you manage to build this without weird errors?

**Comment by jonmak08** [comment]
ci:test:sf

**Comment by jonmak08** [comment]
ci:test:relevant

**Comment by jonmak08** [comment]
ci:test:sf

**Comment by jonmak08** [comment]
ci:test:relevant

**Comment by jonmak08** [comment]
ci:test:sf

**Comment by jonmak08** [comment]
ci:test:relevant

**Comment by jonmak08** [comment]
ci:test:relevant

**Comment by jonmak08** [comment]
ci:reevaluate:1047401_8212

**Comment by jonmak08** [comment]
New Pull Request: https://github.com/liferay-echo/liferay-portal/pull/4529

**Pull request closed without merging**
