### PR TITLE
LPD-26764 - Fix failing test DataSetViewActions#CannotLeaveTitleFieldEmptyInSidePanelItemAction

### PR DESCRIPTION
**Pull request by juanjofgliferay**
## Story / Task
[LPD-26763](https://liferay.atlassian.net/browse/LPD-26763) / [LPD-26764](https://liferay.atlassian.net/browse/LPD-26764)

## Issue
Tests fail due to a change in the title field. Previously it was required but recently was changed not to be mandatory

## Solution
Update failing test and clarify purpose of other cases

### CODE REVIEW

**Comment by juanjofgliferay** [comment]
ci:test:sf

**Comment by juanjofgliferay** [comment]
ci:test:sf

**Comment by juanjofgliferay** [comment]
ci:test:frontend

**Comment by juanjofgliferay** [comment]
DataSetViewActions fixed https://testray.liferay.com/home/-/testray/case_results/index?p_p_state=normal&orderByCol=status_sortable&orderByType=asc&testrayBuildId=2572217121&testrayCaseName=LocalFile.DataSetViewActions

**Comment by dsanz** [comment]
ci:forward:force

**Pull request closed without merging**
