### PR TITLE
LPS-199992 Every page with a Clay tag throws the `hasBodyContent` warning

### PR DESCRIPTION
**Pull request by markocikos**
### References

- [LPS-199992 Every page with a Clay tag throws the `hasBodyContent` warning](https://issues.liferay.com/browse/LPS-199992)
- Regression bug from [LPS-173758 Provide a clay taglib for Tabs component](https://liferay.atlassian.net/browse/LPS-173758)

### What is the goal of this PR?

A small bugfix. I grew tired of looking at this warning on every page :sweat_smile:  

`hasBodyContent` prop is a part of an internal mechanism that allows Clay tags to be nested within other Clay tags. It is meant to be removed, after modifying render behavior. We do this correctly, when it is set to `true`. But, when it is set to `false`, we do nothing and it ends up in regular component props. In this PR, we are fixing cleanup, always deleting the prop.

#### Before PR
screen
#### After PR

Error is not in logs.

### Steps to reproduce

Open any page in DXP.

### CODE REVIEW

**Comment by markocikos** [comment]
ci:test:relevant

**Review by bryceosterhaus — APPROVED** [review]
❤️  every day I want to fix this but never do. LGTM!

**Comment by dsanz** [comment]
LGTM ;)

**Review by dsanz — APPROVED** [review]

**Comment by markocikos** [comment]
ci:test:sf

**Comment by markocikos** [comment]
ci:forward

**Comment by deborasoliveira** [comment]
The relevant failures are unrelated to the PR according to the comparison. 😃 

[Comparison run](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1698363356745&testrayRunIdA=2446948333&testrayRunIdB=2446998066)

**Comment by markocikos** [comment]
ci:forward:force

**Pull request closed without merging**
