### PR TITLE
LPS-197043 Update AlloyUI version to v3.1.0-deprecated.115

### PR DESCRIPTION
**Pull request by antonio-ortega**

### CODE REVIEW

**Review by markocikos — APPROVED** [review]
@antonio-ortega LGTM! :sparkles:

**Comment by antonio-ortega** [comment]
ci:test:sf

**Comment by antonio-ortega** [comment]
ci:test:relevant

**Comment by antonio-ortega** [comment]
ci:forward

**Comment by markocikos** [comment]
> 1189 out of 1250 jobs

:scream: I'd say the chance of this passing CI regularly is very close to zero.

**Comment by JerryAdrianoo** [comment]
Hey @antonio-ortega, I'll run ci:test:relevant again because some tests weren't executed, and it returned errors.

**Comment by JerryAdrianoo** [comment]
ci:test:relevant

**Comment by JerryAdrianoo** [comment]
Hey, @antonio-ortega -ortega your changes didn't return failures!
I'll run ci:stable and if it passes, you can forward it.

**Comment by JerryAdrianoo** [comment]
ci:test:stable

**Comment by antonio-ortega** [comment]
Manually forwarded https://github.com/brianchandotcom/liferay-portal/pull/141528

**Pull request closed without merging**
