### PR TITLE
LPS 177540

### PR DESCRIPTION
**Pull request by ealonso**
Motivation
-----
Delete old taglibs from aui without usages in portal

[Link to the ticket](https://issues.liferay.com/browse/LPS-177540)

Proposed solution
-----
Delete old navigation taglibs, we don't have any usages of those taglibs in portal

### CODE REVIEW

**Comment by eltonccdantas** [comment]
ci:help

**Comment by eltonccdantas** [comment]
ci:test:bundle

**Comment by eltonccdantas** [comment]
I'll take a look at it

**Comment by eltonccdantas** [comment]
Hey @ealonso , I won't be able to finish the analysis today, I'll continue working on it as soon as I get to the office tomorrow.

**Comment by ealonso** [comment]
ci:test:sf

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
Screen Shot 2023-03-16 at 11 22 37 AM

❤️ ❤️

**Comment by bryceosterhaus** [comment]
ci:test:sf

**Comment by bryceosterhaus** [comment]
ci:forward

**Comment by ghenadiibatalski** [comment]
@ealonso you don't have any usage but we do, what is the replacement? Don't you need to anounce the removal via breaking change message to all customer?

**Comment by ghenadiibatalski** [comment]
Also it could be helpful to let aui die "as is" with a bit security maintenance without breaking customer code and work on something better - eg react or angular ui in parallel?

**Comment by ealonso** [comment]
@ghenadiibatalski 

AUI was deprecated before 7.2, https://help.liferay.com/hc/en-us/articles/360029004052-Loading-Modules-with-AUI-Script

> Note: AUI is deprecated and no longer in active development in Liferay DXP 7.2, but all the tags will remain fully functional in Liferay DXP 7.2. Eventually, these tags will be replaced with [Clay](https://claycss.com/) tag counterparts.

The replacement should be clay:navigation-bar.

**Comment by ghenadiibatalski** [comment]
@ealonso hi and thank you for the hint! this is your understanding of the deprecation process. I'm looking here https://docs.liferay.com/portal/7.4-latest/taglibs/util-taglib/aui/nav-bar.html and nothing seems to be deprecated in any from

**Comment by ealonso** [comment]
@ghenadiibatalski Could you please let me know which version of Liferay are you using?

**Comment by ghenadiibatalski** [comment]
7.4u69

**Comment by ealonso** [comment]
Ok, I’m going to send a revert, and find a friendly way of removing old taglibs

**Comment by ealonso** [comment]
@ghenadiibatalski I've already send a revert, https://github.com/liferay-echo/liferay-portal/pull/11544, sorry for the inconveniences.

**Pull request closed without merging**
