### PR TITLE
LPS-182564 | Test fix for ClientExtensionThemeSvg#CanExtendSvgFileFromDM and CanExtendSvgFileFromExternalSite

### PR DESCRIPTION
**Pull request by abhnerramos**
**Description**
Test fix for ClientExtensionThemeSvg#CanExtendSvgFileFromDM and ClientExtensionThemeSvg#CanExtendSvgFileFromExternalSite

**JIRA Ticket**
https://issues.liferay.com/browse/LPS-182564

### CODE REVIEW

**Comment by abhnerramos** [comment]
I accidentaly ran `ci:test:frontend-data-set`

**Comment by abhnerramos** [comment]
ci:test:frontend

**Review by mateusralv — APPROVED** [review]
Greaat! 🎉

**Comment by mateusralv** [comment]
ci:forward

**Pull request closed without merging**
