### PR TITLE
LPS-150490 Fix NullPointerException when calling batch mutations from GraphQL

### PR DESCRIPTION
**Pull request by ccorreagg**
Related ticket: [LPS-150490](https://issues.liferay.com/browse/LPS-150490)

This PR contains the fix to the bug with GraphQL and batch mutations.

To reproduce it, it is just necessary to invoke the GraphQL endpoint with the following mutation (given a siteKey/siteId and a contentStructuredId):

```
mutation {
    createSiteStructuredContentBatch(
        siteKey: "20123"
        object: [
        {
            contentStructureId: 42505
            title: "My content from graphQL batch 1"
        },
        {
            contentStructureId: 42505
            title: "My content from graphQL batch 2"
        }
        ]
    )
}
```
Two Structured Contents must be created.

_NOTE_: Do not forget to include the headers: "accept: application/json" and "Content-Type: application/json".

Before the PR:

image

Once fixed the NullPointerException, it has been necessary to include the parameters such as siteId or assetLibraryId in the UriInfoImpl to make it accesible in the Batch Engine as they are not included in the URI directly.

After the PR:

image

image

### CODE REVIEW

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
ci:reevaluate:1277401_2739

**Review by javierdearcos — APPROVED** [review]
Reviewed synchronously

**Comment by ccorreagg** [comment]
ci:forward

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by john-co** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by zhangyan0701** [comment]
Didn't see related failures. Should be all flaky. Will run test again, if still fail with flaky issues, can manually forward.

**Comment by zhangyan0701** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
PR sent to Brian [here](https://github.com/brianchandotcom/liferay-portal/pull/116016)

Closing this PR...

**Pull request closed without merging**
