### PR TITLE
LPS-125174 Remove metal eslintrc preset usage

### PR DESCRIPTION
**Pull request by kresimir-coko**
Fixes [LPS-125174](https://issues.liferay.com/browse/LPS-125174).

This PR removes the metal ESLint rule (only rule in the file) and therefore delete the `.eslintrc` file .

### CODE REVIEW

**Comment by jbalsas** [comment]
Hey @kresimir-coko, were the other changes needed to remove the `.eslintrc` file? I thought that might not have been necessary and it was part of what we already discarded, so wondering why we'd need it :)

**Comment by kresimir-coko** [comment]
> Hey @kresimir-coko, were the other changes needed to remove the .eslintrc file? I thought that might not have been necessary and it was part of what we already discarded, so wondering why we'd need it :)


Hey @jbalsas maybe not, I just went for the easy win, but I can double check and remove everything but the `.eslintrc` change.

**Comment by jbalsas** [comment]
> Hey @jbalsas maybe not, I just went for the easy win, but I can double check and remove everything but the .eslintrc change.

Yeah, since we're in stabilization phase and we agreed the best move for some of these would be to rewrite, even easier win might be not to do anything if not necessary 😉

**Comment by kresimir-coko** [comment]
ci:test:relevant

**Comment by wincent** [comment]
This one could be a manual forward because the test failures are obviously unrelated (`.eslintrc` can _only_ affect `ci:test:sf`, which passed). But you should update the PR description because it is no longer accurate.

**Comment by kresimir-coko** [comment]
ci:forward

**Comment by kresimir-coko** [comment]
@wincent How does one manually forward? Do I just open a PR on Brian's fork?

**Comment by wincent** [comment]
> @wincent How does one manually forward? Do I just open a PR on Brian's fork?

Yes.

https://github.com/brianchandotcom/liferay-portal/compare/master...kresimir-coko:LPS-125174

But some things to bear in mind:

1. The bot will immediately close your PR, so you will have to re-open it with `ci:reopen`.
2. You should copy-paste the original title and description from here.
3. You should link back to this PR (for traceability).
4. You should include a clear description of _why_ you are circumventing CI (in this case, noting that failures are spurious and irrelevant for a lint-related config change like this one).
5. I would also copy-paste and link to the `ci:test:sf` results, showing that they pass.
6. Be aware that you may be fired.

Example manual forwards:

- https://github.com/brianchandotcom/liferay-portal/pull/99999
- https://github.com/brianchandotcom/liferay-portal/pull/99805
- https://github.com/brianchandotcom/liferay-portal/pull/99490
- https://github.com/brianchandotcom/liferay-portal/pull/99157

**Pull request closed without merging**
