### PR TITLE
LPS-139695 remove from bundle after moving the APIs to this folder

### PR DESCRIPTION
**Pull request by nhpatt**
I think* (no-one knows and if you know please speak up) that this removes all these modules from the release but does not ignore them to let the tests run in the CI. 

Let's see if this stupid change works and the CI is happy...

If anyone can read [this](https://github.com/liferay/liferay-portal/blob/master/modules/README.markdown) and let me know the right value that would also be nice.

### CODE REVIEW

**Comment by nhpatt** [comment]
Is this it?

**Comment by nhpatt** [comment]
ci:test:sf

**Review by javierdearcos — APPROVED** [review]
Now I understand better how to ignore an app from the release 🙂 . 

I thought with the *app.bnd* created and the *.lfrbuild-releng-ignore* file was enough to ignore the modules behind the root

**Comment by javierdearcos** [comment]
Well for the SF comment it seems it is only allowed to set to **true** the **Liferay-Releng-Bundle** ...

Talking with @brunofernandezg about how to do this our conclusion was:

- Create the app.bnd and Liferay-Releng-Bundle: true
- Create the  .lfrbuild-releng-ignore

This came from a document Bruno found wich explains:


>Set to true (Liferay-Releng-Bundle) and add a .lfrbuild-releng-ignore file at the app level if the app will be released at a later time. For example, a new app is planned for the next major release but development is still in progress. This will prevent the jars from being published to Nexus, thus preventing the app from being included in the build.

**Comment by nhpatt** [comment]
>Well for the SF comment it seems it is only allowed to set to true the Liferay-Releng-Bundle ...

**Comment by jpince** [comment]
Hi guys, here's what I understand from the current code (including the changes in this PR)
1. bundle = false (and corresponding app.bnd values enforced by SF)
2. `.lfrbuild-portal` file in every batch-planner module (6), excluding *-test modules
3. No `.lfrbuild-releng-ignore`

What will happen:
1. app will NOT be bundled in the release. App will NOT be built during lpkg test batches. (ask John for more info on test batches)
2. App will be built when running `ant all`.
2. & 3. modules will be published to Nexus

Let me know if this is different from your goals with this change.

One thing that does look odd is that the rest modules contain `.lfrbuild-portal`. For example, when I compare vs. modules/apps/account, none of the account rest modules contain `.lfrbuild-portal`. I'm not sure if this is a problem, but wanted to bring that up.

**Comment by nhpatt** [comment]
That is precisely our goal, I think :) Thanks so much for the input Jason, it was invaluable :D

The REST modules contain .lfrbuild-portal markers because we moved them and did not check that, I'll double check.

**Comment by nhpatt** [comment]
Account-rest has been moved to headless so I would say this is normal.

**Comment by nhpatt** [comment]
ci:forward

**Comment by jpince** [comment]
@nhpatt @javierdearcos Brian Chan said that rest-client should never contain `.lfrbuild-portal`, all other rest modules can have it. There is currently one in batch-planner-rest-client, can you please look into it and/or discuss with Brian?
https://github.com/liferay/liferay-portal/blob/master/modules/apps/batch-planner/batch-planner-rest-client/.lfrbuild-portal

**Comment by nhpatt** [comment]
@jpince he is right, test and client modules do not need it, I'll remove it.

**Comment by nhpatt** [comment]
Not so sure now, all -client modules have it, I guess it's because you can use the client in backend modules as some applications are doing (data engine).

**Comment by jpince** [comment]
@nhpatt thanks for identifying, I see them now. I'll ask Brian about it next week. Or if you happen to be talking to him before you hear back from me, please feel free to ask as well.

```
modules/ $ find -name *.lfrbuild-portal -path "*rest-client*"
./apps/batch-planner/batch-planner-rest-client/.lfrbuild-portal
./apps/bulk/bulk-rest-client/.lfrbuild-portal
./apps/data-engine/data-engine-rest-client/.lfrbuild-portal
./dxp/apps/portal-workflow/portal-workflow-metrics-rest-client/.lfrbuild-portal
./dxp/apps/segments/segments-asah-rest-client/.lfrbuild-portal
```

**Pull request closed without merging**
