### PR TITLE
LPS-197336 - Translate checkbox label on first render.

### PR DESCRIPTION
**Pull request by ethib137**
https://liferay.atlassian.net/browse/LPS-197336

### CODE REVIEW

**Review by markocikos — APPROVED** [review]
@ethib137 LGTM! :sparkles:

**Comment by ethib137** [comment]
ci:forward

**Comment by dsanz** [comment]
ci:forward:force

**Comment by dsanz** [comment]
ci:forward:force

**Comment by dsanz** [comment]
we're not being lucky with the stable suite. It's hard to believe these are related, I'm considering manual forward.

@mateusralv would you mind taking a quick look?

**Comment by markocikos** [comment]
ci:test:stable

**Comment by markocikos** [comment]
ci:forward:force

**Pull request closed without merging**
