### PR TITLE
COMMERCE-4589 href action is temporarily not nested

### PR DESCRIPTION
**Pull request by gianmarcobrunialti**
This is an urgent fix, as discussed here: https://github.com/liferay-frontend/liferay-portal/pull/339#discussion_r480546429
Temporarily the `href` is still nested within the `action` object. @brunobasto

### CODE REVIEW

**Comment by gianmarcobrunialti** [comment]
ci:test:sf

**Comment by gianmarcobrunialti** [comment]
ci:test:sf

**Comment by gianmarcobrunialti** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
> This is an urgent fix [...]

emergency

**Comment by brunobasto** [comment]
I've had a [conversation](https://github.com/liferay-frontend/liferay-portal/pull/339#discussion_r480375570) with @gianmarcobrunialti and Fabio about this before. There's some inconsistencies with the DropDown formats that we need to fix, but that will need some adjustments on the backend part. Since this is urgent I think it's fine the way it is right now.

**Comment by jbalsas** [comment]
Sounds good, let's get this moving then!

**Comment by jbalsas** [comment]
ci:forward

**Comment by gianmarcobrunialti** [comment]
Thanks guys! 🎉  @brunobasto @jbalsas

**Pull request closed without merging**
