### PR TITLE
LPS-127923 Standardize link-or-button controls markup in management toolbar

### PR DESCRIPTION
**Pull request by markocikos**
@ambrinchaudhary  @julien @jonmak08 

The main purpose of this PR is to squash a lot of code duplication in management toolbar tag. In quite a few places we are doing
```js
if (href) ? <ClayLink ... /> : <ClayButton ... />
```
... with a lot of same props. Instead, in this PR we are introducing
```js
<LinkOrButton />
```
There is the [LinkOrButton](https://github.com/liferay/clay/blob/master/packages/clay-shared/src/LinkOrButton.tsx) in Clay, but I opted not to use it. There as significant differences in API and implementation:
- we want `disabled` prop to render a disabled button, to match cases in [management toolbar v2](https://github.com/liferay/clay/blob/2.x/packages/clay-management-toolbar/src/ClayManagementToolbar.soy#L733).
- we want to support `symbol` prop, with `children` as fallback
- we want to support `button` prop
- we don't need two `*DisplayTypes`

Clay's LinkOrButton is in @clayui/shared, probably not intended to be used externally. It is used internally in several places, so there would need to be some refactoring, quickly complicating solution. Maybe this would make sense to do if there are other DXP modules that could use this component. I don't know of any.

Along with this refactoring, we are fixing a bug, where sort button is never disabled:
screen

Before it was a `ClayLink` that cannot be disabled, now it is a `LinkOrButton` that can be disabled.

Finally, I should note that I flipped a coin to call it `<LinkOrButton />` or `<Control />`. Control sounds better, but is not quite accurate, as it can be an element that is not a link or a button.

### CODE REVIEW

**Review by kresimir-coko — APPROVED** [review]
This PR is not terrible 👍

**Comment by bryceosterhaus** [comment]
> Clay's LinkOrButton is in @clayui/shared, probably not intended to be used externally

@markocikos do you think it would be helpful for this PR and other teams if we exposed a more general `LinkOrButton` component from Clay? We could expose it from an existing package.

Another option would be to create a new helper/util package that is intended to be consumed? Unlike @clayui/shared, where we explicitly state its for internals.

**Review by ambrinchaudhary — APPROVED** [review]

**Comment by markocikos** [comment]
> @markocikos do you think it would be helpful for this PR and other teams if we exposed a more general `LinkOrButton` component from Clay? We could expose it from an existing package.
> 
> Another option would be to create a new helper/util package that is intended to be consumed? Unlike @clayui/shared, where we explicitly state its for internals.

@bryceosterhaus  I opened [a ticket in Clay](https://github.com/liferay/clay/issues/3940) to continue this discussion, and replied there.

Meanwhile, I think we can move forward with this PR. If / when the Clay component becomes available, we'll refactor the code to use it.

**Comment by markocikos** [comment]
ci:forward

**Pull request closed without merging**
