### PR TITLE
LPS-114084 Update test in segments-web

### PR DESCRIPTION
**Pull request by eduardoallegrini**
This is a simple code replacement of the old layout classes with the new clay layout components

We had some problems testing the original bundle so I've decided to separate the `segments-web` module and work on it separately

I tried to run the local test and test-update commands

`yarn test -u` as @wincent suggested  https://github.com/eduardoallegrini/liferay-portal/pull/92#issuecomment-645414938
`yarn test --updateSnapshot` as @dgarciasarai suggested https://github.com/jbalsas/liferay-portal/pull/2214#issuecomment-643155701

And they are actually green

image
image

@john-co also commented why it's failing here https://github.com/eduardoallegrini/liferay-portal/pull/92#issuecomment-645053038 but I couldn't figure out how to fix it 😞

history of the pr (just in case):
- https://github.com/jbalsas/liferay-portal/pull/2214
- https://github.com/eduardoallegrini/liferay-portal/pull/91
- https://github.com/eduardoallegrini/liferay-portal/pull/92

### CODE REVIEW

**Comment by wincent** [comment]
FWIW:

> `yarn test -u`
> `yarn test --updateSnapshot`




> @john-co also commented why it's failing here [eduardoallegrini#92 (comment)](https://github.com/eduardoallegrini/liferay-portal/pull/92#issuecomment-645053038) but I couldn't figure out how to fix it 😞

**Comment by wincent** [comment]
FWIW:

> `yarn test -u`
> `yarn test --updateSnapshot`

These are the same option (short form and long form).

> @john-co also commented why it's failing here [eduardoallegrini#92 (comment)](https://github.com/eduardoallegrini/liferay-portal/pull/92#issuecomment-645053038) but I couldn't figure out how to fix it 😞

I think updating the snapshots is going to fix it.

**Comment by wincent** [comment]
ci:test:sf

**Comment by wincent** [comment]
ci:test:relevant

**Comment by wincent** [comment]
Failure looks spurious. Trying again.

**Comment by wincent** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
Forwarding based on @wincent previous comments

**Comment by jbalsas** [comment]
ci:forward

**Pull request closed without merging**
