### PR TITLE
LPS-188505 Add JSP comment to remove whitespace and keep source format

### PR DESCRIPTION
**Pull request by fortunatomaldonado**
https://liferay.atlassian.net/browse/LPS-188505

The issue is that jsp has trailing and leading whitespaces due to the formatting. This can cause issue with customers that use "whitespace:pre-wrap" CSS style which will show the whitespaces and break format.
By adding comments, it will remove all the whitespaces and still maintain formatting.
Please let me know if there are any questions or comments about this.

Thank you!

### CODE REVIEW

**Comment by dsanz** [comment]
If we go this route, we'll be supporting this in more and more places where our internal source format will leak onto rendering. We may find cases where this is not possibe, so we have to be careful here.

Has the customer expressed their concerns if asked to use `white-space: pre-line;` instead?

**Comment by izaera** [comment]
>If we go this route, we'll be supporting this in more and more places where our internal source format will leak onto rendering. We may find cases where this is not possibe, so we have to be careful here.

We may also consider rendering things from Java classes directly. Not optimal, but would bypass the SF...  :roll_eyes:

**Comment by kresimir-coko** [comment]
@fortunatomaldonado is this problem occurring elsewhere on the platform? My concern is that if we start doing this here, we must do it across the entire codebase. I feel like this is treating a symptom and not the cause of the issue.

**Comment by fortunatomaldonado** [comment]
@kresimir-coko This is only occurring since the customer is using `whitespace:pre-wrap` with the liferay-ui:search-container-column-text taglib. So the issue is not out of the box but a customization. 

@dsanz, with  `white-space: pre-line;` the customer says that the vertical width of each line of the list display becomes wider. 
I have confirmed it does become wider.

I agree if we do "fix" it here, then we might be asked to fix it in other places.
Since this is not an out of the box issue, are we required to fix it? Or should we create a Fast Track Article about this behavior and how using `whitespace:pre-wrap` and other similar css might affect these taglibs?

**Comment by fortunatomaldonado** [comment]
Hello @dsanz, @kresimir-coko, 
Do you have any input on the comment here: https://github.com/liferay-frontend/liferay-portal/pull/3484#issuecomment-1622577793
Truly appreciate the help on this!

**Comment by kresimir-coko** [comment]
@fortunatomaldonado sorry for the slow responses, I am going to raise this with the team and see what we can do.

**Comment by mateusralv** [comment]
ci:test:relevant

**Comment by fortunatomaldonado** [comment]
From discussions, I will be closing out this PR as it will be best to guide the customer to the style they need, rather than adjusting the markup which may lead to more markup changes throughout the codebase.

**Pull request closed without merging**
