### PR TITLE
[7.4-only]LPS-102100 Removes compat list-group

### PR DESCRIPTION
**Pull request by pat270**
https://issues.liferay.com/browse/LPS-102100

Old list-group classes still exist in:
- Product Menu and Simulation Menu, left it in until we figure out what we are going to do with isolating admin styles
- `modules/apps/application-list/application-list-taglib` this is used only in Product Menu
- `modules/apps/frontend-js/frontend-js-aui-web/src/main/resources/META-INF/resources/liferay/panel_search.js` I dont think this is used anywhere. Left everything as is for backward compatibility?
- `modules/apps/document-library/document-library-web/src/main/resources/META-INF/resources/document_library/js/legacy/upload.js` I don't think this is used anywhere. Left it as is for backward compatibility?

Fixed some rounded corner issues with search-iterator lexicon view, had to wrap the ul's in `<div class="lfr-search-container-list">`. This might break some tests?

What it looks like with these commits:
list-group-compat-removal

### CODE REVIEW

**Comment by pat270** [comment]
ci:test:sf

**Comment by pat270** [comment]
ci:test:relevant

**Comment by kresimir-coko** [comment]
Not terrible PR 👍

**Review by jbalsas — APPROVED** [review]
> This might break some tests

Apparently not :D 

This looks good to me!

@marcoscv-work, @eduardoallegrini, care to take a look and forward if this looks ok to you?

**Comment by marcoscv-work** [comment]
LGTM!

I'm going to use this PR to put the new PR about icons on top of it!

**Comment by marcoscv-work** [comment]
ci:forward

**Pull request closed without merging**
