### PR TITLE
LPS-145112 - Adds API for accessing spritemaps in both java and javascript

### PR DESCRIPTION
**Pull request by bryceosterhaus**
Resent from https://github.com/liferay-frontend/liferay-portal/pull/2141

https://issues.liferay.com/browse/LPS-145112

Hey all, here is the work for adding a public API to access the new icon packs. Let me know if you have any questions or concerns.

```js
// Using `import` syntax

import {getSpritemapPath, getSystemSpritemapPath} from '@liferay/frontend-icons-web';

// Used with no arguments returns the site's spritemap
getSpritemapPath();

// Add an argument to get the icon pack spritemap
getSpritemapPath('clay');

// Returns the system default spritemap (this will be used in control-panel type instances)
getSystemSpritemapPath()
```

```java
// Returns spritemap for all icon-packs scoped to the site
IconsUtil.getSpritemapPath(themeDisplay);

// Returns spritemap for any given icon pack
IconsUtil.getSpritemapPath("my-custom-icon-pack");

// Returns the system default spritemap (this will be used in control-panel type instances)
IconsUtil.getSystemSpritemapPath();
```

Note, I haven't added a feature flag yet, but I plan to look into that next as we start to apply the pattern in our existing code.

### CODE REVIEW

**Comment by bryceosterhaus** [comment]
ci:test:sf

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
ci:test:sf

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
ci:stop

**Comment by bryceosterhaus** [comment]
ci:test:sf

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by magjed4289** [comment]
ci:test:stable

**Comment by bryceosterhaus** [comment]
ci:test:sf

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by Esther-OC** [comment]
QA review for unique failures started.

**Comment by Esther-OC** [comment]
Hi @bryceosterhaus!
Unique failures are not related to the PR, so, from QA perspective, you can forward it manually.

**Comment by bryceosterhaus** [comment]
manual forward at https://github.com/brianchandotcom/liferay-portal/pull/116893

**Pull request closed without merging**
