### PR TITLE
LPS-156475

### PR DESCRIPTION
**Pull request by holatuwol**
## Motivation

https://issues.liferay.com/browse/LPS-156475

## Proposed solution

Add the `nav-btn-monospaced` class that is also present in DDM's plus icon.

https://github.com/liferay/liferay-portal/blob/7.4.1-ga2/modules/apps/dynamic-data-mapping/dynamic-data-mapping-form-web/src/main/resources/META-INF/resources/admin/edit_element_set.jsp#L59

## Steps to verify

1. Start server, login as Test
2. Go to: Control Panel > CONFIGURATION: Job Scheduler
3. Check the plus button on the top right.

### CODE REVIEW

**Review by bryceosterhaus — APPROVED** [review]
LGTM!

**Comment by diegonvs** [comment]
ci:forward

**Comment by susanchen3** [comment]
Reviewed. Test failures are unrelated. :heavy_check_mark: Looks good to manually forward from QA perspective. :smile: 

Going to try to `ci:forward` one more time tho..

**Comment by susanchen3** [comment]
ci:forward

**Comment by diegonvs** [comment]
ci:forward

**Comment by diegonvs** [comment]
@holatuwol, if CI fails again, could you send this PR manually to BC? Thanks

**Comment by diegonvs** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/119928 already merged

**Pull request closed without merging**
