### PR TITLE
LPS 132547 | Refactor FI test names towards SACRED model

### PR DESCRIPTION
**Pull request by john-co**
Resend of https://github.com/liferay-frontend/liferay-portal/pull/1117

~~Having trouble with `gh pr` locally to send my commits...will squash and resend after troubleshooting but wanted to get idea of how the tests will do.~~

**Description**
Test names should describe the specific capability of the feature and not what the test is performing.

**Test Plan**
- [x] Verify all FI test names describe the specific capability of the feature it's testing and not what it's just doing.

**JIRA Ticket:**
https://issues.liferay.com/browse/LPS-132547

### CODE REVIEW

**Comment by john-co** [comment]
ci:test:sf

**Comment by john-co** [comment]
ci:test:frontend

**Comment by john-co** [comment]
ci:test:sf

**Comment by john-co** [comment]
ci:test:frontend

**Comment by john-co** [comment]
ci:test:stable

**Comment by john-co** [comment]
Tests pass, but will wait to merge with https://github.com/liferay-frontend/liferay-portal/pull/1125

**Comment by john-co** [comment]
ci:test:frontend

**Comment by john-co** [comment]
ci:test:relevant

**Comment by john-co** [comment]
ci:test:sf

**Comment by john-co** [comment]
ci:test:frontend

**Comment by john-co** [comment]
Reviewed. Test failures are unrelated. :heavy_check_mark: 

Both tests have been failing on upstream: https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=1552906769

**Review by zhangyan0701 — APPROVED** [review]
LGTM!

**Comment by john-co** [comment]
ci:forward

**Pull request closed without merging**
