### PR TITLE
LPS-148034

### PR DESCRIPTION
**Pull request by holatuwol**
https://issues.liferay.com/browse/LPS-148034

Sending here because it's the name of a color, where the frontend team would know if it's the proper name to use for that color.

## Steps to reproduce

1. Add a style book
2. Navigate to Theme Colors section in sidebar

image

### CODE REVIEW

**Comment by bryceosterhaus** [comment]
I am sure this is fine, but just want to double check with clay squad in case there is another name needed here

cc @matuzalemsteles @pat270

**Comment by matuzalemsteles** [comment]
Yeah, that feels right.

**Comment by diegonvs** [comment]
ci:test:relevant

**Comment by diegonvs** [comment]
> [com.liferay.portal.log.assertor.PortalLogAssertorTest.testScanXMLLog](https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0/405524//testReport/com.liferay.portal.log.assertor/PortalLogAssertorTest/testScanXMLLog)
> [com.liferay.portal.log.assertor.PortalLogAssertorTest.testScanOSGiLog](https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0/405524//testReport/com.liferay.portal.log.assertor/PortalLogAssertorTest/testScanOSGiLog)

go home CI, you're drunk

**Comment by diegonvs** [comment]
ci:forward

**Pull request closed without merging**
