### PR TITLE
LPD-36681 - Remove LPD-25905 FF

### PR DESCRIPTION
**Pull request by juanjofgliferay**
## Story / Task
[LPD-36680](https://liferay.atlassian.net/browse/LPD-36680) / [LPD-36681](https://liferay.atlassian.net/browse/LPD-36681)

## Goal
After adding the option to select complex/composed field names to create filters this tasks removes the FF and the code related to simple field name selection.

It is also included in this PR the possibility of adding fields of type integer for Selection filters, as there are endpoints that expect values (x.e. `id` ) as string and others as integer.

## Issues
PR includes a change in the process of openapi.json endpoint to retrieve the fields that are used in the TreeView component. It also consider the autocalculated `field.type` property instead of the default `type`.

image

### CODE REVIEW

**Comment by juanjofgliferay** [comment]
ci:test:relevant

**Review by markocikos — APPROVED** [review]
@juanjofgliferay LGTM! :sparkles:

**Comment by juanjofgliferay** [comment]
ci:test:sf

**Comment by juanjofgliferay** [comment]
ci:test:relevant

**Comment by juanjofgliferay** [comment]
ci:test:relevant

**Comment by juanjofgliferay** [comment]
ci:test:relevant

**Comment by juanjofgliferay** [comment]
ci:report

**Comment by juanjofgliferay** [comment]
ci:report:21524172

**Comment by juanjofgliferay** [comment]
ci:report:21524172

**Comment by juanjofgliferay** [comment]
Not related errors

**Comment by juanjofgliferay** [comment]
ci:forward

**Comment by juanjofgliferay** [comment]
ci:forward:force

**Pull request closed without merging**
