### PR TITLE
LPS-113531 Move `getOpener` to frontend-js-web

### PR DESCRIPTION
**Pull request by kresimir-coko**
https://issues.liferay.com/browse/LPS-113531

This util returns the `window` object of the page that caused a new (browser) window/tab to be opened or a page change.

You can test this by going to Blogs > `+` button, which will trigger the function to get invoked.

### CODE REVIEW

**Comment by kresimir-coko** [comment]
ci:test:sf

**Comment by kresimir-coko** [comment]
ci:test:sf

**Comment by kresimir-coko** [comment]
ci:test:relevant

**Review by bryceosterhaus — APPROVED** [review]
ci:forward

**Comment by kresimir-coko** [comment]
ci:forward

**Comment by kresimir-coko** [comment]
ci:forward

**Pull request closed without merging**
