### PR TITLE
LPS-158911 Import `getTop` instead of using `Liferay.Util.getTop`

### PR DESCRIPTION
**Pull request by kresimir-coko**

### CODE REVIEW

**Review by bryceosterhaus — APPROVED** [review]
LGTM!

**Comment by kresimir-coko** [comment]
ci:reevaluate:1327401_4948

**Comment by diegonvs** [comment]
ci:test:relevant

**Comment by mateusralv** [comment]
ci:test:relevant

**Comment by mateusralv** [comment]
This problem with ci:test:relevant is occurring in other [PRs](https://liferay.slack.com/archives/CL3TWSMHQ/p1658947803893909). 🤔

**Comment by mateusralv** [comment]
ci:test:relevant

**Comment by kresimir-coko** [comment]
@mateusralv can I manually forward this?

**Comment by mateusralv** [comment]
ci:test:relevant

**Comment by kresimir-coko** [comment]
ci:reevaluate:1357401_2161

**Comment by kresimir-coko** [comment]
ci:reevaluate:1357401_2161

**Comment by kresimir-coko** [comment]
@mateusralv can I manually forward this?

**Comment by mateusralv** [comment]
@kresimir-coko I’m taking a look again, CI was failing.

**Comment by mateusralv** [comment]
ci:test:relevant

**Comment by susanchen3** [comment]
ci:test:relevant

**Comment by susanchen3** [comment]
timed out again... gonna try again cause CI increased the load time [LRCI-3116](https://issues.liferay.com/browse/LRCI-3116)

**Comment by susanchen3** [comment]
ci:test:relevant

**Comment by mateusralv** [comment]
I'm taking a look 🔎

**Comment by yanan** [comment]
Hi @kresimir-coko , I've downloaded the test bundle and there is an `uncaught typeError: (0, n.getTop) is not a function`.

[Comparison run:](https://testray.liferay.com/zh/home/-/testray/runs/compare?compare=true&view=details&statusA=3&testrayRunIdB=1934061329&testrayRunIdA=1934181345&statusB=2)

Unique tests failures for example:
- LocalFile.Picklist#CanUpdatePicklistItemName
picklist-getTop
- LocalFile.ContentPagesWithContentsPanel#EditCollectionItems
- LocalFile.CollectionsWithAssetPublisher#DisplayRelatedAssetsInAssetPublisher
view+edit_collection-items
- LocalFile.CommerceAccelerators#DeactivateCommerceAccountAdminLogOut
- LocalFile.Accounts#AddingSecondUserToPersonAccountWillReplaceFirstUser
Add-user-to-commerce-account

**Comment by kresimir-coko** [comment]
oh, okay @yanan thank you very much!

**Comment by kresimir-coko** [comment]
Omg I don't know how this happened but I didn't commit the most important part of the PR

**Comment by kresimir-coko** [comment]
ci:test:sf

**Comment by kresimir-coko** [comment]
ci:test:relevant

**Comment by diegonvs** [comment]
ci:test:relevant

**Comment by yanan** [comment]
Test [failures](https://testray.liferay.com/zh/home/-/testray/runs/compare?compare=true&view=details&statusA=3&testrayRunIdB=1935927741&testrayRunIdA=1937105807&statusB=2) are unrelated, looks good to forward from QA perspective. :D

**Comment by kresimir-coko** [comment]
ci:forward

**Comment by john-co** [comment]
manually forward to https://github.com/brianchandotcom/liferay-portal/pull/121424

**Pull request closed without merging**
