### PR TITLE
LPS-161059: Expose batch action in the headless APIs

### PR DESCRIPTION
**Pull request by sergiojimcos**
## This is the first version of exposing Batch Actions in Headless Delivery APIs

**What is new?**
- Exposing `createBatch`, `deleteBatch`, `updateBatch` methods in Headless APIs
- Update `portal-vulcan` permission checker without using ID methods

**NEW CHARACTERISTIC**
Here you can see an example of new actions of a particular Schema:

image

**HOW TO REPRODUCE**
1. Deploy `portal-vulcan-api`
2. Deploy `headless-delivery-impl`
3. Deploy `headless-admin-taxonomy`

**JIRA TICKET**
https://issues.liferay.com/browse/LPS-161059

cc/ @4lejandrito

### CODE REVIEW

**Comment by sergiojimcos** [comment]
ci:test:relevant

**Comment by sergiojimcos** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
Hi @sergiojimcos,

The import/export centre lists all these entities:

```
Account (v1_0 - Liferay Headless Admin User)
Account (v1_0 - Liferay Headless Commerce Admin Account)
AccountGroup (v1_0 - Liferay Headless Commerce Admin Account)
AccountRole (v1_0 - Liferay Headless Admin User)
BlogPosting (v1_0 - Liferay Headless Delivery)
BlogPostingImage (v1_0 - Liferay Headless Delivery)
Catalog (v1_0 - Liferay Headless Commerce Admin Catalog)
Channel (v1_0 - Liferay Headless Commerce Admin Channel)
Channel (v1_0 - Liferay Headless Commerce Delivery Catalog)
Comment (v1_0 - Liferay Headless Delivery)
ContentElement (v1_0 - Liferay Headless Delivery)
ContentStructure (v1_0 - Liferay Headless Delivery)
ContentTemplate (v1_0 - Liferay Headless Delivery)
DSEnvelope (v1_0 - Liferay Digital Signature REST)
DataDefinitionFieldLink (v2_0 - Liferay Data Engine REST)
DataLayout (v2_0 - Liferay Data Engine REST)
DataListView (v2_0 - Liferay Data Engine REST)
DataRecord (v2_0 - Liferay Data Engine REST)
DataRecordCollection (v2_0 - Liferay Data Engine REST)
Discount (v1_0 - Liferay Headless Commerce Admin Pricing)
Discount (v2_0 - Liferay Headless Commerce Admin Pricing)
Document (v1_0 - Liferay Headless Delivery)
DocumentFolder (v1_0 - Liferay Headless Delivery)
Form (v1_0 - Liferay Headless Form)
FormRecord (v1_0 - Liferay Headless Form)
FormStructure (v1_0 - Liferay Headless Form)
Keyword (v1_0 - Liferay Headless Admin Taxonomy)
KnowledgeBaseArticle (v1_0 - Liferay Headless Delivery)
KnowledgeBaseAttachment (v1_0 - Liferay Headless Delivery)
KnowledgeBaseFolder (v1_0 - Liferay Headless Delivery)
Language (v1_0 - Liferay Headless Delivery)
ListTypeDefinition (v1_0 - Liferay Headless Admin List Type)
MeasurementUnit (v1_0 - Liferay Headless Commerce Admin Site Setting)
MessageBoardAttachment (v1_0 - Liferay Headless Delivery)
MessageBoardMessage (v1_0 - Liferay Headless Delivery)
MessageBoardSection (v1_0 - Liferay Headless Delivery)
MessageBoardThread (v1_0 - Liferay Headless Delivery)
NavigationMenu (v1_0 - Liferay Headless Delivery)
NotificationTemplate (v1_0 - Liferay Notification REST)
ObjectAction (v1_0 - Liferay Object Admin REST)
ObjectDefinition (v1_0 - Liferay Object Admin REST)
ObjectField (v1_0 - Liferay Object Admin REST)
ObjectLayout (v1_0 - Liferay Object Admin REST)
ObjectRelationship (v1_0 - Liferay Object Admin REST)
ObjectValidationRule (v1_0 - Liferay Object Admin REST)
ObjectView (v1_0 - Liferay Object Admin REST)
Option (v1_0 - Liferay Headless Commerce Admin Catalog)
Order (v1_0 - Liferay Headless Commerce Admin Order)
OrderItem (v1_0 - Liferay Headless Commerce Admin Order)
OrderRule (v1_0 - Liferay Headless Commerce Admin Order)
OrderType (v1_0 - Liferay Headless Commerce Admin Order)
Organization (v1_0 - Liferay Headless Admin User)
PaymentMethod (v1_0 - Liferay Headless Commerce Delivery Cart)
Phone (v1_0 - Liferay Headless Admin User)
PlacedOrderComment (v1_0 - Liferay Headless Commerce Delivery Order)
PlacedOrderItem (v1_0 - Liferay Headless Commerce Delivery Order)
PlacedOrderItemShipment (v1_0 - Liferay Headless Commerce Delivery Order)
PriceList (v1_0 - Liferay Headless Commerce Admin Pricing)
PriceList (v2_0 - Liferay Headless Commerce Admin Pricing)
Product (v1_0 - Liferay Headless Commerce Admin Catalog)
ProductGroup (v1_0 - Liferay Headless Commerce Admin Catalog)
Region (v1_0 - Liferay Headless Admin Address)
ReplenishmentItem (v1_0 - Liferay Headless Commerce Admin Inventory)
Role (v1_0 - Liferay Headless Admin User)
Segment (v1_0 - Liferay Headless Admin User)
Shipment (v1_0 - Liferay Headless Commerce Admin Shipment)
ShippingMethod (v1_0 - Liferay Headless Commerce Admin Channel)
ShippingMethod (v1_0 - Liferay Headless Commerce Delivery Cart)
SitePage (v1_0 - Liferay Headless Delivery)
Sku (v1_0 - Liferay Headless Commerce Admin Catalog)
Specification (v1_0 - Liferay Headless Commerce Admin Catalog)
StructuredContent (v1_0 - Liferay Headless Delivery)
StructuredContentFolder (v1_0 - Liferay Headless Delivery)
Term (v1_0 - Liferay Headless Commerce Admin Order)
UserAccount (v1_0 - Liferay Headless Admin User)
UserGroup (v1_0 - Liferay Headless Admin User)
Warehouse (v1_0 - Liferay Headless Commerce Admin Inventory)
WebUrl (v1_0 - Liferay Headless Admin User)
WikiNode (v1_0 - Liferay Headless Delivery)
WikiPage (v1_0 - Liferay Headless Delivery)
WikiPageAttachment (v1_0 - Liferay Headless Delivery)
```

I see your changes don't cover all of them. Do we have a plan to cover them all?

**Comment by sergiojimcos** [comment]
ci:forward

**Comment by sergiojimcos** [comment]
Forward manually to Brian due to `ci:test:stable` is not working: https://github.com/brianchandotcom/liferay-portal/pull/122742

**Pull request closed without merging**
