### PR TITLE
LPS-174358 | FDS - Add Ignore poshi test + Tab key navigation skips dropdown on filter label

### PR DESCRIPTION
**Pull request by mateusralv**
Description: 
Add the property for the CI to skip the test according to this https://github.com/liferay-frontend/liferay-portal/pull/3094#issuecomment-1463791810

Original PR: https://github.com/liferay-frontend/liferay-portal/pull/3094

cc: @kresimir-coko @manoelcyreno

---
https://issues.liferay.com/browse/LPS-174358

In order to have the proper focus behaviour it was needed to pass a `ClayButton` component instead of the `ClayLabel` component as a `trigger` for the `ClayDropDown`.

I have also noticed a lot of SF inconsistencies in the `frontend-data-set-web` module, for example missing empty lines between sibling elements. Are we disabling our ESLint rules somehow in this module?

### CODE REVIEW

**Comment by mateusralv** [comment]
ci:test:relevant

**Comment by kresimir-coko** [comment]
ci:test:sf

**Comment by kresimir-coko** [comment]
ci:test:sf

**Comment by kresimir-coko** [comment]
ci:forward

**Comment by mateusralv** [comment]
ci:reevaluate:1377401_9780

**Comment by mateusralv** [comment]
ci:forward

**Comment by mateusralv** [comment]
ci:forward

**Pull request closed without merging**
