### PR TITLE
LPS-138145 Update liferay-ckeditor to 4.18.0-liferay.2

### PR DESCRIPTION
**Pull request by diegonvs**
**Full Changelog**: https://github.com/liferay/liferay-ckeditor/releases/tag/v4.18.0-liferay.2

Fixes https://issues.liferay.com/browse/LPS-138145

### CODE REVIEW

**Comment by diegonvs** [comment]
No need review, I already checked it but if you're curious go ahead

**Comment by diegonvs** [comment]
ci:test:relevant

**Comment by diegonvs** [comment]
ci:test:relevant

**Comment by diegonvs** [comment]
ci:test:relevant

**Comment by diegonvs** [comment]
Failures at https://github.com/liferay-frontend/liferay-portal/pull/2609#issuecomment-1206869967 looks weird

**Comment by diegonvs** [comment]
Apparently ckeditor bump version affects kubernetes
[ironic flag on]

**Comment by diegonvs** [comment]
ci:test:relevant

**Comment by john-co** [comment]
Reviewed. Test failures are unrelated. :heavy_check_mark: 

Ok to manually forward from QA perspective. Pending (if any) dev approval.

**Comment by diegonvs** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/121479

**Pull request closed without merging**
