### PR TITLE
COMMERCE-4539 Standard width size for modals when not specified

### PR DESCRIPTION
**Pull request by gianmarcobrunialti**
In the past it seemed as though if a modal `size` was `null` it would fallback to a default. This was not the case for `size` as `undefined`, which would mess up the whole component.

Now the fallback seems to be consistent whether `size` is `null` or `undefined`, hence the fix for modals handled by DataSet components. @brunobasto @jbalsas

### CODE REVIEW

**Comment by gianmarcobrunialti** [comment]
ci:test:sf

**Comment by gianmarcobrunialti** [comment]
ci:test:relevant

**Review by brunobasto — APPROVED** [review]
Seems reasonable.

**Comment by jbalsas** [comment]
> Seems reasonable.

Indeed 😂 

I wonder if after the release frenzy we could move this to the default `openModal` utility and avoid duplication... 🤔

**Comment by brunobasto** [comment]
ci:forward

**Pull request closed without merging**
