### PR TITLE
LPS-116176 Workflow definition source is not displayed and the user cannot type on it when creating a Workflow through Kaleo Forms Admin

### PR DESCRIPTION
**Pull request by markocikos**
In this PR, we are fixing the issue described in https://issues.liferay.com/browse/LPS-116176

The problem was that the height and width calculations in ACE editor are thrown off by the loading indicator. We are always inserting the loading indicator with `openModal`, we didn't use to do it with legacy modals. The editor height is calculated eagerly, while DOM is still not there.

We are now delaying initialization until the modal iframe is loaded.

As an added bonus, we are fixing closing of the modal on the 'cancel' button. This was a part of the original solution but somehow got lost.

If we discover something wrong with this fix, we can revert the original solution, as in https://github.com/liferay-frontend/liferay-portal/pull/62

/cc @julien @jbalsas @john-co

### CODE REVIEW

**Comment by markocikos** [comment]
ci:test:sf

**Comment by markocikos** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
Thanks @markocikos! I'm going to trust you on this one and forward if green! :)

canitrustyou

**Comment by markocikos** [comment]
under pressure

**Comment by jbalsas** [comment]
A promise made is a promise kept

pinkyswear

**Comment by jbalsas** [comment]
ci:forward

**Comment by john-co** [comment]
fyi @rodrigocunhaa, in case you see something else. Also, considering https://issues.liferay.com/browse/LPS-116176 was a FP4 and there's a priority 5 test affected, we may want to think about how to include test coverage in relevant suite for FI team to catch it in the future if worth preventing.

**Comment by rodrigocunhaa** [comment]
Thanks @john-co, none of the tests that caught this issue was on the relevant that's why the `ci:forward` from the original PR didn't run any of them. I'll add one of them to relevant to avoid that.

**Pull request closed without merging**
