### PR TITLE
LPS-121870 Migrate v2 usages in depot/depot-web

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @liferay-frontend,

Attached is an update for http://issues.liferay.com/browse/LPS-121870.

@julien, @markocikos, @ambrinchaudhary,

Just wanted to get another pair of eyes on this as this should cover all the changes we were discussing for the management toolbar updates.

Please let me know if you have any questions. Thanks!

Test Plan:

1. Login to Liferay
2. Click on the **Application Menu**
3. Click on **Asset Libraries**
4. Click on the `+` to add an Asset Library
5. Save Asset Library

asset-library

### CODE REVIEW

**Comment by wincent** [comment]
I took this out of "draft" status but GitHub UI is showing a rebase conflict so I think it needs an update @jonmak08.

**Review by ambrinchaudhary — COMMENTED** [review]
Changes in `depot-web` LGTM. 

Although, I guess the first [commit](https://github.com/liferay-frontend/liferay-portal/pull/766/commits/0dcc180294e66277db4afe92205aabb57de79cb7) doesn't belong to this PR (different module, different LPS and different team) and is the one complaining about conflicts, am I right @jonmak08 ?

**Comment by jonmak08** [comment]
Hey @ambrinchaudhary,

Yes, I will remove the 1st commit.  I just needed the changes from @julien for the `CreationMenu` method to the toolbar.  I will remove that when everyone passes the changes.

Please let me know if you have any questions. Thanks!

**Comment by jonmak08** [comment]
New Pull Request: https://github.com/liferay-lima/liferay-portal/pull/1478

**Pull request closed without merging**
