### PR TITLE
LPS-171612 Add angular-custom-element example

### PR DESCRIPTION
**Pull request by izaera**
https://issues.liferay.com/browse/LPS-171612

### CODE REVIEW

**Comment by izaera** [comment]
ci:test:sf

**Comment by izaera** [comment]
ci:test:sf

**Comment by izaera** [comment]
ci:test:relevant

**Comment by deborasoliveira** [comment]
I'll take a look at it 🧐

**Comment by deborasoliveira** [comment]
Hello @izaera! 
I've analyzed the failures and they look unrelated to your PR according to this [comparison](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1674238713585&testrayRunIdA=2167566164&testrayRunIdB=2167810103). 
If no other dev review is needed you can manually forward it. 👍🏽

**Comment by izaera** [comment]
Thanks @deborasoliveira . Resent manually as https://github.com/brianchandotcom/liferay-portal/pull/129100

**Pull request closed without merging**
