### PR TITLE
LPS-126675 Create propsTransformer and propsTransformerSevletContext parameters in <react:component>

### PR DESCRIPTION
**Pull request by jeyvison**
Hello :)

In this PR i'm creating two parameters for the <react:component> taglib.

### Context/Use Case
Data Engine has a[ builder taglib](https://github.com/liferay/liferay-portal/blob/master/modules/apps/data-engine/data-engine-taglib/src/main/java/com/liferay/data/engine/taglib/servlet/taglib/DataLayoutBuilderTag.java) that creates a react components builder for general purpose. Nowadays, three products use this taglib: [App builder](https://github.com/liferay/liferay-portal/blob/37360aa819a399af55b83604302f74ad4b076d12/modules/apps/app-builder/app-builder-web/src/main/resources/META-INF/resources/edit_form_view.jsp#L74), [WEM](https://github.com/liferay/liferay-portal/blob/37360aa819a399af55b83604302f74ad4b076d12/modules/apps/journal/journal-web/src/main/resources/META-INF/resources/edit_data_definition.jsp#L104) and [DL](https://github.com/liferay/liferay-portal/blob/37360aa819a399af55b83604302f74ad4b076d12/modules/apps/document-library/document-library-web/src/main/resources/META-INF/resources/document_library/ddm/edit_ddm_structure.jsp#L94). 

A lot of the props that are passed to the component taglib are fetched by the server side taglib code so the client doesn't have access to it and can't do any specific business logic transformation with them. This leads to situations like [this](https://github.com/liferay/liferay-portal/blob/37360aa819a399af55b83604302f74ad4b076d12/modules/apps/data-engine/data-engine-taglib/src/main/resources/META-INF/resources/data_layout_builder/js/AppContext.es.js#L217).

That's why I'm creating these two parameters in the react component itself, for cases where there is a taglib( or some other server side component) being used to render some react component, kinda like we are already doing in (some?) clay taglibs.

### Testing 

On top of [this PR](https://github.com/liferay-app-builder/liferay-portal/pull/167)  i created a file under `app-builder/app-builder-web/src/main/resources/META-INF/resources/js` called `transformProps.js` with the content more or less like this: 

``` javascript
export default function transformProps(props){
      console.log(props);
      return props;
}
```
Then, [in here](https://github.com/liferay/liferay-portal/blob/37360aa819a399af55b83604302f74ad4b076d12/modules/apps/app-builder/app-builder-web/src/main/resources/META-INF/resources/edit_form_view.jsp#L74) i sent the values like this:

``` html
<liferay-data-engine:data-layout-builder
        componentId="<%= componentId %>"
        contentType="app-builder"
        dataDefinitionId="<%= dataDefinitionId %>"
        dataLayoutId="<%= dataLayoutId %>"
        fieldSetContentType="app-builder-fieldset"
        namespace="<%= liferayPortletResponse.getNamespace() %>"
        scopes='<%= SetUtil.fromCollection(Arrays.asList("app-builder")) %>'
        propsTransformer="<%=js/propsTransformer.js%>"
        propsTransfomerServletContext="<%= application %>"
  />
```

And then, to check if the propsTransfomer was working as intended i navigated to Applications > App Builder > Objects > New Object > new Form Builder and i asserted that the props were logged in the browser's console.

Let me know if you need more information :)

### CODE REVIEW

**Comment by jeyvison** [comment]
cc: @interaminense @kevenleone

**Comment by julien** [comment]
Hi @jeyvison,


> On top of this PR i created a file under app-builder/app-builder-web/src/main/resources/META-INF/resources/js called transformProps.js with the content more or less like this:

> ```js
>  export default function transformProps(props){
>      console.log(props);
>      return props;
>}
>```

We use the `propsTransformer` pattern in various places, and usually return a function simply called `propsTransformer` (and not `transformProps`), I thought that you'd maybe like to do the same thing for consistency.

Here a some examples:
- [ActionsComponentPropsTransformer.js](https://github.com/liferay/liferay-portal/blob/e597dedaf54b9219df0a67b9673f95d3e93d694f/modules/apps/asset/asset-categories-admin-web/src/main/resources/META-INF/resources/js/ActionsComponentPropsTransformer.js#L54)
- [ConnectedSiteDropdownPropsTransformer.js](https://github.com/liferay/liferay-portal/blob/e597dedaf54b9219df0a67b9673f95d3e93d694f/modules/apps/depot/depot-web/src/main/resources/META-INF/resources/js/ConnectedSiteDropdownPropsTransformer.js#L47)
- [DefaultEventHandlersPropsTransformer.js](https://github.com/liferay/liferay-portal/blob/e597dedaf54b9219df0a67b9673f95d3e93d694f/modules/apps/frontend-taglib/frontend-taglib-clay/src/main/resources/META-INF/resources/DefaultEventHandlersPropsTransformer.js#L15)

> Then, [in here](https://github.com/liferay/liferay-portal/blob/37360aa819a399af55b83604302f74ad4b076d12/modules/apps/app-builder/app-builder-web/src/main/resources/META-INF/resources/edit_form_view.jsp#L74) i sent the values like this:

> ```jsp
> <liferay-data-engine:data-layout-builder
>         componentId="<%= componentId %>"
>         contentType="app-builder"
>         dataDefinitionId="<%= dataDefinitionId %>"
>         dataLayoutId="<%= dataLayoutId %>"
>         fieldSetContentType="app-builder-fieldset"
>         namespace="<%= liferayPortletResponse.getNamespace() %>"
>         scopes='<%= SetUtil.fromCollection(Arrays.asList("app-builder")) %>'
>         propsTransformer="<%=js/propsTransformer.js%>"
>         propsTransfomerServletContext="<%= application %>"
>   />
> ```


I see a difference compared to what we do in `frontend-taglib-clay` for the value of the `propsTransformer` attribute, which does not contain the `.js` extension. So I think it should look like this (no `.js` extension for the `propsTransformer` attribute, and attributes sorted)

```jsp
<liferay-data-engine:data-layout-builder
         componentId="<%= componentId %>"
         contentType="app-builder"       
         dataDefinitionId="<%= dataDefinitionId %>"
         dataLayoutId="<%= dataLayoutId %>"
         fieldSetContentType="app-builder-fieldset"
         namespace="<%= liferayPortletResponse.getNamespace() %>"
         propsTransformer="js/propsTransformer"
         propsTransfomerServletContext="<%= application %>"
         scopes='<%= SetUtil.fromCollection(Arrays.asList("app-builder")) %>'
 />
``` 


Here are some examples, from various modules: 

 - [frontend-taglib-clay-sample-web](https://github.com/liferay/liferay-portal/blob/a9c7b417e8ef81cb4e42d79359abdb1d7121aba0/modules/apps/frontend-taglib/frontend-taglib-clay-sample-web/src/main/resources/META-INF/resources/partials/management_toolbars.jsp#L72)
 - [multi-factor-authentication-fido2-web](https://github.com/liferay/liferay-portal/blob/8eb0ae798c7f743c16b365949c83563afe5b6651/modules/dxp/apps/multi-factor-authentication/multi-factor-authentication-fido2-web/src/main/resources/META-INF/resources/mfa_fido2_checker/verify_browser.jsp#L31)
- [social-bookmarks](https://github.com/liferay/liferay-portal/blob/11e6081f96abb6bf299369519434c1eafa0658e3/modules/apps/social/social-bookmarks-taglib/src/main/resources/META-INF/resources/bookmarks/page.jsp#L38)

For reference you can have a look at the [BaseContainerTag](https://github.com/liferay/liferay-portal/blob/e597dedaf54b9219df0a67b9673f95d3e93d694f/modules/apps/frontend-taglib/frontend-taglib-clay/src/main/java/com/liferay/frontend/taglib/clay/internal/servlet/taglib/BaseContainerTag.java#L319-L323) class. Let me know if that makes sense when you can.

**Comment by jeyvison** [comment]
Hello @julien  =D

> Hi @jeyvison,
> 
> We use the `propsTransformer` pattern in various places, and usually return a function simply called `propsTransformer` (and not `transformProps`), I thought that you'd maybe like to do the same thing for consistency.
> 
> Here a some examples:
> 
>     * [ActionsComponentPropsTransformer.js](https://github.com/liferay/liferay-portal/blob/e597dedaf54b9219df0a67b9673f95d3e93d694f/modules/apps/asset/asset-categories-admin-web/src/main/resources/META-INF/resources/js/ActionsComponentPropsTransformer.js#L54)
> 
>     * [ConnectedSiteDropdownPropsTransformer.js](https://github.com/liferay/liferay-portal/blob/e597dedaf54b9219df0a67b9673f95d3e93d694f/modules/apps/depot/depot-web/src/main/resources/META-INF/resources/js/ConnectedSiteDropdownPropsTransformer.js#L47)
> 
>     * [DefaultEventHandlersPropsTransformer.js](https://github.com/liferay/liferay-portal/blob/e597dedaf54b9219df0a67b9673f95d3e93d694f/modules/apps/frontend-taglib/frontend-taglib-clay/src/main/resources/META-INF/resources/DefaultEventHandlersPropsTransformer.js#L15)
> 

Thanks a lot! I'll ask @interaminense to keep an eye for this pattern when he implements the propsTransformer in App builder side :)

> 
> I see a difference compared to what we do in `frontend-taglib-clay` for the value of the `propsTransformer` attribute, which does not contain the `.js` extension. So I think it should look like this (no `.js` extension for the `propsTransformer` attribute, and attributes sorted)
> 
> ```
> <liferay-data-engine:data-layout-builder
>          componentId="<%= componentId %>"
>          contentType="app-builder"       
>          dataDefinitionId="<%= dataDefinitionId %>"
>          dataLayoutId="<%= dataLayoutId %>"
>          fieldSetContentType="app-builder-fieldset"
>          namespace="<%= liferayPortletResponse.getNamespace() %>"
>          propsTransformer="js/propsTransformer"
>          propsTransfomerServletContext="<%= application %>"
>          scopes='<%= SetUtil.fromCollection(Arrays.asList("app-builder")) %>'
>  />
> ```
> 
> Here are some examples, from various modules:
> 
>     * [frontend-taglib-clay-sample-web](https://github.com/liferay/liferay-portal/blob/a9c7b417e8ef81cb4e42d79359abdb1d7121aba0/modules/apps/frontend-taglib/frontend-taglib-clay-sample-web/src/main/resources/META-INF/resources/partials/management_toolbars.jsp#L72)
> 
>     * [multi-factor-authentication-fido2-web](https://github.com/liferay/liferay-portal/blob/8eb0ae798c7f743c16b365949c83563afe5b6651/modules/dxp/apps/multi-factor-authentication/multi-factor-authentication-fido2-web/src/main/resources/META-INF/resources/mfa_fido2_checker/verify_browser.jsp#L31)
> 
>     * [social-bookmarks](https://github.com/liferay/liferay-portal/blob/11e6081f96abb6bf299369519434c1eafa0658e3/modules/apps/social/social-bookmarks-taglib/src/main/resources/META-INF/resources/bookmarks/page.jsp#L38)
> 
> 
> For reference you can have a look at the [BaseContainerTag](https://github.com/liferay/liferay-portal/blob/e597dedaf54b9219df0a67b9673f95d3e93d694f/modules/apps/frontend-taglib/frontend-taglib-clay/src/main/java/com/liferay/frontend/taglib/clay/internal/servlet/taglib/BaseContainerTag.java#L319-L323) class. Let me know if that makes sense when you can.

I'm so sorry i misled you there XD This is exactly how i tested it (without the `.js` extension). I just typed it wrongly when providing the testing step. Thanks for catching this :) To be clear, it's working exactly as it works for the Clay taglibs.

**Comment by julien** [comment]
> Thanks a lot! I'll ask @interaminense to keep an eye opened for this pattern when he implements the propsTransformer in App builder side :)

Great!

> I'm so sorry i misled you there XD This is exactly how i tested it (without the .js extension). I just typed it wrongly when providing the testing step. Thanks for catching this :) To be clear, it's working exactly as it works for the Clay taglibs.

Ok, then that seems good, thanks for clarifying.
  I'm just going to re-run the CI tests because the error doesn't look related to your changes.

**Comment by julien** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
ci:test:relevant

**Comment by wincent** [comment]
> A lot of the props that are passed to the component taglib are fetched by the server side taglib code so the client doesn't have access to it and can't do any specific business logic transformation with them. This leads to situations like [this](https://github.com/liferay/liferay-portal/blob/37360aa819a399af55b83604302f74ad4b076d12/modules/apps/data-engine/data-engine-taglib/src/main/resources/META-INF/resources/data_layout_builder/js/AppContext.es.js#L217).

Thanks for providing a very detailed description explaining your rationale here. So if I've understood the motivation correctly, in a nutshell it is to get some ugly app-specific props-massaging:

- _Out of_ (taglib-layer): `modules/apps/data-engine/data-engine-taglib/src/main/resources/META-INF/resources/data_layout_builder/js/AppContext.es.js`
- And _into_ (app-specific-layer): `modules/app-builder/app-builder-web/src/main/resources/META-INF/resources/js/transformProps.js`

I don't know much about taglib design so I will leave others to comment on the design here, but one thing I am wondering is how this compares to getting the flexibility you need in a different way.

For example, one question I have is if we ever foresee a second user of `<react:component>` ever needing this `propsTransformer` functionality? If the answer is "probably not", then maybe we could move the switching logic into the one place that needs it (ie. `<liferay-data-engine:data-layout-builder>`) instead. I don't know how well this would work, but what I'm thinking, for example, is that `data-layout-builder` could pass a different `module` into `<react:component>` for any app that wanted to opt into that override via a property (otherwise it would just use the default `App.es.js` module), and that module could then massage the props and pass them into the `App.es.js` component from `data-layout-builder` (ie. via composition). I don't know if that makes sense (like I said, I don't know much about taglibs), but I am interested in hearing opinions because we have to be careful about adding new attributes to widely used tags (like `<react:component>`) that we'll end up having to support "forever", even if there is only a very small number of consumers needing the new functionality.

**Comment by jbalsas** [comment]
> For example, one question I have is if we ever foresee a second user of <react:component> ever needing this propsTransformer functionality? 

I think, based on our own experience it makes sense that sooner or later we'll need `propsTransformer` support inside `react:component`. That being said, we have 84 usages of `react:component` and none of them required of `propsTransformer`. This should be a different conversation and not related to taglib design.

The main use case for `propsTransformer` would be able to inject JS callbacks directly so we avoid writing isolated code and wire it via globally accessible functions in `window`.

Massaging props is also a legit use case, but I agree with @wincent here that this should be further analyzed because massaging could happen also in a different layer already before invoking your main component. 

@jeyvison, I think it's key to see how you plan to leverage this for real. For example, for [`setDataLayout`](https://github.com/liferay/liferay-portal/blob/37360aa819a399af55b83604302f74ad4b076d12/modules/apps/data-engine/data-engine-taglib/src/main/resources/META-INF/resources/data_layout_builder/js/AppContext.es.js#L238)... I don't think you're expecting to massage props directly, but maybe rather passing the `setDataLayout` method as a prop so it can be overridden? 

Overall, I think `propsTransformer` in `react:component` makes sense in the long run, but we should be careful not to try to see everything through that lens.

That being said, I'd like to take a closer look at the code, because the changes to `servletContext` look somewhat scary. @izaera , would you have time to go over the PR?

**Comment by izaera** [comment]
>  @izaera , would you have time to go over the PR?

I'll do. In fact we cannot merge this as it will conflict with https://github.com/liferay-frontend/liferay-portal/pull/734 which changes ReactRenderer heavily :scream: .

In any case, I'll review it having in mind my changes in the other PR. That way, when the other gets merged, we can redo the final version (if we all agree) of this on top with ease.

**Comment by izaera** [comment]
One other concern for me is the fact that the `propsTransformer` seems to be a mechanism that can be severely abused (IMO). 

If it is used to set properties that can only be set browser-side it is reasonable, but it can also be used to map one props object into a different one too (talking about pure data transformation), and that is something that could then be done in two places: Java and JavaScript. Something that would lead to code incoherence in the long term.

It could also make SSR more difficult as it would be impossible for the server to apply those transformations without a proper JavaScript engine.

Seeing this, I'm not sure if we want to add the `propsTransformer` notion to a place where it is not yet present...

This is along the lines of what others have commented.

Also, I don't know if it could be of any help, but we have the `ReactRenderer` component in addition to the `<react:component>` taglib, so maybe we prefer to create a specialized taglib based on it rather than extending `<react:component>` which, being so generic, should only support things widely used, I guess...

**Comment by izaera** [comment]
Seeing now that `<react:component>` [is called inside an internal JSP file of `DataLayoutBuilderTag`](https://github.com/liferay/liferay-portal/blob/master/modules/apps/data-engine/data-engine-taglib/src/main/resources/META-INF/resources/data_layout_builder/end.jsp#L68)  we may as well move the `propsTransformer` to that layer if we don't want to push it to `<react:component>`.

**Comment by jbalsas** [comment]
I think @jeyvison use case is legit, in the sense that right now they have consumer-related logic bleeding into the generic component. 

If I understand correctly, we have. `AppBuilder App` - uses -> `DataEngine Taglib` - uses -> `LayoutBuilder React Component`.

The thing is right now we have logic inside `layout-builder` that knows about `app-builder` just because we don't have an easy way to get that transformation through the indirection layer. Please, @jeyvison, confirm if this is the case or if based on all the comments we've provided you see another way to solve your needs before we continue adding to the thread :)

**Comment by izaera** [comment]
The code LGTM.

> the changes to `servletContext` look somewhat scary

These look good too. If I understood it correctly, what @jeyvison is doing is:

- For the module: use the page's ServletContext by default or the one contained in the `servletContext` attribute (when set)
- For the propsTransfomer: use the `propsTransformerServletContext` if set, otherwise use the ServletContext used for the `modue`

**Comment by jeyvison** [comment]
> If I understand correctly, we have. `AppBuilder App` - uses -> `DataEngine Taglib` - uses -> `LayoutBuilder React Component`.
> 
Exactly @jbalsas 

> The thing is right now we have logic inside `layout-builder` that knows about `app-builder` just because we don't have an easy way to get that transformation through the indirection layer. Please, @jeyvison, confirm if this is the case or if based on all the comments we've provided you see another way to solve your needs before we continue adding to the thread :)

This is exactly the case that I'm trying to solve with this PR. For now i don't see another way to do this. We could try to override `setDataDefinition` but it would lead to code duplication everytime some client would need just a simple prop transforming

**Comment by wincent** [comment]
> For now i don't see another way to do this.

What about the "other way" that [I mentioned earlier](https://github.com/liferay-frontend/liferay-portal/pull/731#issuecomment-768122548):

> what I'm thinking, for example, is that `data-layout-builder` could pass a different `module` into `<react:component>` for any app that wanted to opt into that override via a property (otherwise it would just use the default `App.es.js` module), and that module could then massage the props and pass them into the `App.es.js` component from `data-layout-builder` (ie. via composition).

Does that make any sense? I'm basically talking about a kind of inversion of control where:

- Instead of `data-layout-builder` rendering `App.es.js` unconditionally, and conditionally using a props transformer to manage the props that get passed internally into `<react:component>`...
- We'd teach `data-layout-builder` to accept an override for the `module` property that it will pass into `<react:component>`; when nothing is passed, we use `App.es.js` and business proceeds as usual, but when a custom module is passed, we use that instead, and the idea is that consumers would be able to make `<AppThatTransformsProps>` and would then compose `<App>` inside it...

```js
import {App} from 'data-layout-builder';

export default function AppThatTransformsProps(props) {
   return (
       <App {...{
           ...props,
           name: 'overridden',
       }}>
   );
}
```

**Comment by jeyvison** [comment]
> 
> What about the "other way" that [I mentioned earlier](https://github.com/liferay-frontend/liferay-portal/pull/731#issuecomment-768122548):
> 
I'm really sorry man, i completely missed your comment XD @wincent 

> > what I'm thinking, for example, is that `data-layout-builder` could pass a different `module` into `<react:component>` for any app that wanted to opt into that override via a property (otherwise it would just use the default `App.es.js` module), and that module could then massage the props and pass them into the `App.es.js` component from `data-layout-builder` (ie. via composition).
> 
> Does that make any sense? I'm basically talking about a kind of inversion of control where:
> 
>     * Instead of `data-layout-builder` rendering `App.es.js` unconditionally, and conditionally using a props transformer to manage the props that get passed internally into `<react:component>`...
> 
>     * We'd teach `data-layout-builder` to accept an override for the `module` property that it will pass into `<react:component>`; when nothing is passed, we use `App.es.js` and business proceeds as usual, but when a custom module is passed, we use that instead, and the idea is that consumers would be able to make `<AppThatTransformsProps>` and would then compose `<App>` inside it...
> 
> 
> ```js
> import {App} from 'data-layout-builder';
> 
> export default function AppThatTransformsProps(props) {
>    return (
>        <App {...{
>            ...props,
>            name: 'overridden',
>        }}>
>    );
> }
> ```

Yeah, i think that could work. I'm gonna try it here and let you know. My only worry about this approach is that the client would have to know not only the taglib ( as it is today) but the internal App.js that the taglib uses.

**Comment by jbalsas** [comment]
Hey @jeyvison, do you have any update on your side? A related conversation came up via [Slack](https://liferay.slack.com/archives/CNBG06JS3/p1612860589130400) this week. Did you manage to find a good solution based on @wincent's comments ?

> Yeah, i think that could work. I'm gonna try it here and let you know. My only worry about this approach is that the client would have to know not only the taglib ( as it is today) but the internal App.js that the taglib uses.

Based on your comment I'd say we might still need this, but waiting to hear back from you.

Just for context, I think the flow here goes like:

Implementation:
```html
<react:component
    module="App"
    props="<%= someProps %>"
/>
```

Usage
```html
<liferay-data-engine:data-layout-builder
    attr1="foo"
    attr2="bar"
/>
```

For @wincent's suggestion to work, usage would need to change to:
```html
<react:component
    module="MyAppThatTransformsProps
    props=<%= {"attr1": "foo", "attr2": "bar"}  %>
/>
```

Which will mean that we would need to expose all the internal logic in the tag so the consumer could reuse it.

An alternative approach would be to add support for `data-layout-builder` tag to accept a "module" attribute so it could be overriden and consumed like:

```html
<liferay-data-engine:data-layout-builder
    module="MyAppThatTransformsProps
    attr1="foo"
    attr2="bar"
/>
```

The main issue I see is that before the `data-layout-builder` module only exported the tag as API whereas for this to work, it needs to export both the tag and the React component and the mechanism to allow the override. Feels like a bit of an overreach to me.

I think this case will only ever happen for tags as they introduce this level of indirection between the main module and the consumer, so it's a bit of an edge case, but it will potentially affect all of our tags, so it might be worth considering it as a generic mechanism... 🤔 

@wincent, could you take another look at this when you have the chance, see if any of it changes your take on this?

**Comment by jeyvison** [comment]
hey @jbalsas @wincent Sorry for the delay in answering you guys. I just could work on it this week. I did [this](https://github.com/liferay-app-builder/liferay-portal/pull/167). 

I followed the suggestion from @wincent and the props are getting in my PropsTransformer module as they should be. I didn't close this PR yet because i'm waiting for the front devs to do the tranformations they need and let me know if something is missing or even if this solution will fit the use case ( i think it will) .

**Comment by jbalsas** [comment]
I see, thanks @jeyvison, I see you went with Option 2:

```
An alternative approach would be to add support for data-layout-builder tag to accept a "module" attribute so it could be overriden and consumed like:
```

See my concerns about this on top, but I'm okay if this is good enough for now. Could also be the right pattern since it provides some more composability for such a complex and dynamic component... 🤔

**Comment by wincent** [comment]
> Which will mean that we would need to expose all the internal logic in the tag so the consumer could reuse it to easily generate the proper props.
> 
> An alternative approach would be to add support for `data-layout-builder` tag to accept a "module" attribute so it could be overriden and consumed like:

Yeah, the "alternative approach" is actually the one that I was raising as a suggestion.

> See my concerns about this on top

I don't feel super strongly about this but if it helps, my motivation for exploring this angle was trying to localize "the gnarly bit" closer to what I suspect may be the only site that will actually ever need it (`data-layout-builder`) as opposed to the `react-component` taglib itself, which is used all over the place.

**Comment by jeyvison** [comment]
Hey @jbalsas @wincent @julien @izaera . @interaminense just tested the implementation and it's working beautifully. The fact that we are using the export module directly from data engine will probably help us with some tests too so that was a double win ^^

Thanks a lot for all your help =D

**Comment by wincent** [comment]
> that was a double win ^^
> 
> Thanks a lot for all your help =D I think it's safe to close this one now.

Brilliant, thanks for keeping us in the loop. I'm glad you found a bonus (the testability thing) along the way too.

**Pull request closed without merging**
