### PR TITLE
LPS-183789 | Create stubs for Poshi tests

### PR DESCRIPTION
**Pull request by abhnerramos**
**Description**
Creating stubs for Poshi tests

**JIRA Ticket**
https://issues.liferay.com/browse/LPS-183789

### CODE REVIEW

**Comment by abhnerramos** [comment]
ci:stop

**Comment by abhnerramos** [comment]
ci:test:sf

**Comment by abhnerramos** [comment]
hey @mateusralv , LGTM! Could you take a look, please?

**Comment by mateusralv** [comment]
ci:forward

**Pull request closed without merging**
