### PR TITLE
LPS-138464 Create a common pattern when using ManagementBarSortTag so that the chosen order column/type can be saved in the user preferences

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**
**Steps to Reproduce:**

1. Go to Site Builder > Collections.
2. Create a collection "beta test"
3. Create collection "alpha test".
4. Change to sort by title.
5. Navigate to a different menu option.
6. Go back to Site Builder > Collections.

**Actual Results:**
Sort is done by create date.

**Expected Results:**
Sort should be done by last chosen option (title).

This is a recurrent bug, and usually the retrieval/saving is done in many different ways, that's why a general approach was followed.

### CODE REVIEW

**Review by nhpatt — COMMENTED** [review]
Hi @marianoalvarosaiz!

Can you add more context of the PR and change the title following https://github.com/liferay/liferay-frontend-projects/blob/master/guidelines/general/pull_requests.md ?

**Review by markocikos — CHANGES_REQUESTED** [review]
Hey @marianoalvarosaiz ,

Sorry for the long wait for review!

I should start by saying this PR would be a temporary solution. We are currently working on [Dataset Display Custom Views](https://issues.liferay.com/browse/LPS-130101), which have sort type and order persistence as a part of it. But, it may be a long time before custom views are implemented and all DXP solutions migrated. Management toolbar + search containers may be around for a long time, so this effort is valuable.

While back we had a long discussions on how to implement display types, see https://github.com/liferay-frontend/liferay-portal/pull/416, followup PRs and linked discussions. The task of this PR introduces basically the same feature, except we are persisting different management attributes. Please see how we ended up implementing the feature: https://github.com/brianchandotcom/liferay-portal/pull/98787. A part of solution to specially note is the [SearchDisplayStyleUtil utility](https://github.com/liferay/liferay-portal/blob/master/portal-kernel/src/com/liferay/portal/kernel/portlet/SearchDisplayStyleUtil.java). Ordering persistence should follow the same pattern, meaning:
- We should add something like `SearchDisplayStyleUtil.getOrderByCol` and `SearchDisplayStyleUtil.getOrderByType`. This would replace `ManagementBarOrderByHandler` from this PR.
- These functions should be overloaded with `key` argument. This takes the function of overloading preference name from this PR.
- `defaultValue` argument removes the need for setting of defaults through `ManagementBarOrderByHandlerBuilder`.

/cc @izaera @jbalsas @carloslancha @dsanz

**Comment by nhpatt** [comment]
Just a note here, the backend services/APIs of https://issues.liferay.com/browse/LPS-130101 are meant to be used by *any* view, not just datasets. We generalize it with that goal in mind, to be able to store user preferences in a more solid/durable/updatable mechanism than... user preferences as the default xml in a-column-storage.

One thing to consider is if it makes sense to start using it instead. I do not have the answer as I don't know what patterns are there and if it would a similar case. Invoking @dsanz here too :)

**Comment by dsanz** [comment]
I think in this case, it's better to keep using portletpreferences because:
* We have an established pattern as Marko explained.
* We want this solution to be backported to branches where the frontend state backend service is not available
* We still need to decide how the frontend state service will manage states owned by different components, and that will probably happen after we finished custom views feature.
* We already accounted for migrating these preferences to the frontend state service on the fly as they're accessed (this is happening with the active view settings in the dataset display), which should facilitate future migration of the ordering settings in the management-bar family of tags

**Comment by marianoalvarosaiz** [comment]
OK, as discussed with @antonio-ortega I'll send a new one.

**Comment by markocikos** [comment]
Followup in https://github.com/liferay-frontend/liferay-portal/pull/1619

**Pull request closed without merging**
