### PR TITLE
LPS-132503 Only try to reload the iframe if have a valid contentWindow

### PR DESCRIPTION
**Pull request by boton**
Hi guys,

The problem is that after a submit when the file is uploaded and the user navigates, we have a pending call trying to reload the iframe, and the `instance._frame.get('contentWindow.location')` throws an error when trying to get the `.location` of null.

**How to reproduce:**

1. Navigate to DM
2. Open browser console
3. Upload document or image

**Before the fix**
Throws an error `Uncaught TypeError: Cannot read property 'location' of null`

**After the fix**
No browser errors

### CODE REVIEW

**Comment by boton** [comment]
ci:test:relevant

**Comment by boton** [comment]
ci:test:relevant

**Comment by julien** [comment]
LGTM, semantic versioning error looks unrelated.

**Comment by boton** [comment]
Rebased!

**Comment by boton** [comment]
ci:test:relevant

**Review by julien — APPROVED** [review]

**Comment by julien** [comment]
ci:forward

**Pull request closed without merging**
