### PR TITLE
LPS-124336 Update @clayui deps

### PR DESCRIPTION
**Pull request by carloslancha**
Updating @clayui dependencies after last Clay Release:
```
@clayui/autocomplete     3.2.0  →   3.2.1
@clayui/breadcrumb       3.3.0  →   3.3.1
@clayui/card             3.6.0  →   3.6.1
@clayui/color-picker     3.4.0  →   3.4.1
@clayui/css             3.20.0  →  3.21.0
@clayui/data-provider    3.3.5  →   3.3.6
@clayui/date-picker      3.6.0  →   3.6.1
@clayui/drop-down        3.8.0  →   3.8.1
@clayui/form            3.12.0  →  3.13.0
@clayui/list             3.4.1  →   3.4.2
@clayui/modal            3.8.0  →   3.8.1
@clayui/multi-select     3.8.0  →   3.8.1
@clayui/multi-step-nav   3.3.0  →   3.3.1
@clayui/nav              3.4.0  →   3.4.1
@clayui/navigation-bar   3.3.0  →   3.3.1
@clayui/pagination       3.3.0  →   3.3.1
@clayui/pagination-bar   3.2.0  →   3.2.1
@clayui/panel            3.3.0  →   3.3.1
@clayui/popover          3.5.0  →   3.5.1
@clayui/shared           3.3.0  →   3.3.1
@clayui/tabs             3.3.0  →   3.3.1
@clayui/time-picker      3.2.0  →   3.2.1
@clayui/toolbar          3.0.0  →   3.0.1
@clayui/tooltip          3.4.0  →   3.4.1
@clayui/upper-toolbar    3.1.8  →   3.1.9
```

Updating markup and API in card tags to follow Clay component.

### CODE REVIEW

**Comment by carloslancha** [comment]
ci:test:sf

**Comment by carloslancha** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
Screen Shot 2020-12-02 at 16 27 38

just-sayin

**Comment by jbalsas** [comment]
> /opt/dev/projects/github/liferay-portal/modules/apps/frontend-taglib/frontend-taglib-clay/src/main/java/com/liferay/frontend/taglib/clay/servlet/taglib/VerticalCardTag.java:281: error: ';' expected
     [exec] 		_showSticker = showSticker

epicfail

**Comment by carloslancha** [comment]
ci:test:sf

**Comment by carloslancha** [comment]
ci:test:relevant

**Comment by carloslancha** [comment]
@markocikos @julien @jbalsas if test are passed I'll follow this one so we can have it in master ASAP since it's a bit urgent for support (and for us 😅 )

**Comment by xbrianlee** [comment]
Fixed conflict and re-running Search tests in https://github.com/xbrianlee/liferay-portal/pull/555

**Comment by julien** [comment]
ci:test:sf

**Comment by julien** [comment]
@carloslancha @jbalsas I'm sorry I hadn't seen [this](https://github.com/liferay/clay/pull/3831#issuecomment-737231809) but I did solve the conflict we had with `master`.

**Comment by julien** [comment]
ci:test:relevant

**Comment by markocikos** [comment]
What would be cool is a list of Clay issues fixed in updated package versions. Even cooler would be if this can be automated somehow, like a script that would compare versions in current branch and master and find those issues :thinking:

**Review by markocikos — APPROVED** [review]

**Comment by carloslancha** [comment]
Manually tested. Failing test is working. Forwarding manually

**Comment by carloslancha** [comment]
Manual forward to https://github.com/brianchandotcom/liferay-portal/pull/96582

**Pull request closed without merging**
