### PR TITLE
LPS-130616 Adds Table Toolbar plugin to Balloon Editor

### PR DESCRIPTION
**Pull request by diegonvs**
From https://github.com/diegonvs/liferay-portal/pull/42

I fixed the styles of the ListBox and now it will look like this:

Screen Shot 2021-07-06 at 19 37 58

See the already mentioned link to see the old status.

----- 

Also, I tried to fix an issue where icons are not being rendered correct. Now, I'm passing the correct string to the UI_PANELBUTTON but it renders nothing and a 404 is shown:

Screen Shot 2021-07-06 at 19 40 07

I tried to see if I'm giving an incorrect value to the [clay icon mapping](https://github.com/liferay/liferay-ckeditor/blob/master/skins/moono-lexicon/icons.json#L6) but not. Also, I notice the trash icon is also missing from the sidebar and it is being settled as a balloonpanelbutton in the balloonpanel plugin.

### Things to be fixed:

Here are the things to be fixed before squashing and pushing this code to Julien's branch /cc @markocikos 

- [x] Solve the missing icons issue

- [ ] When clicking in another button to trigger another ListBox, the last clicked ListBox is being shown again

- [ ] Sometimes, by a undiscovered(yet) set of usages, the ListBox renders nothing

- [ ] Don't truncate ListBox items, improve ListBox width(see AE panel width)

### CODE REVIEW

**Comment by julien** [comment]
> I fixed the styles of the ListBox and now it will look like this:

Seems it still needs some changes, right? Or do we want to show "truncated" items in the dropdown menu?

I was also wondering why this wasn't pushed on top of #1070?

Concerning the error with the icons, didn't we agree on using CSS classes and svgs?

**Comment by diegonvs** [comment]
> I was also wondering why this wasn't pushed on top of #1070?

Considering this is an unstable version I don't want to pollute the "main" PR. 

> Seems it still needs some changes, right? Or do we want to show "truncated" items in the dropdown menu?

Yes, I need to adjust panel's width. Thanks for bringing this issue :)

**Comment by markocikos** [comment]
@diegonvs Where is the `134px` coming from? Is it CSS or JS? Increasing it to `160px` is not a great solution, assuming text is localized. It can be much longer in some languages. I think what we ideally want is div extending to text size. If you cannot find a solution for it, we can push it the solution as it is and open a ticket just for the CSS. Then, we can ask @edalgrin for help, without the noise of the rest of PR.

**Comment by diegonvs** [comment]
> Where is the 134px coming from? Is it CSS or JS?

From AE, It's a Sass variable. You can find the definition [here](https://github.com/liferay/alloy-editor/blob/8834c8c9a4e95fe92f8744f93355de4692a0b4ea/src/assets/sass/components/ae-dropdown/variables/structure.scss#L10).

> assuming text is localized. It can be much longer in some languages

Yes, It's complicated. What are the concepts between the min-width of Clay Dropdown panel?

>  If you cannot find a solution for it, we can push it the solution as it is and open a ticket just for the CSS.

Sure. I can open another ticket for it. :)

**Comment by diegonvs** [comment]
When taking a look on CSS of each  table toolbar button element,

```html
<span class="cke_button_icon cke_button__tablecell_icon" style="background-image:url('http://localhost:8080/o/frontend-editor-ckeditor-web/ckeditor/add-cell?t=L4D7');background-position:0 0px;background-size:16px;">&nbsp;</span>
```

I notice the path to icon URL path is wrong in the `tabletoolbar`.

```css
/* in ballontoolbar, correct */
background-image: url('http://localhost:8080/o/frontend-editor-ckeditor-web/ckeditor/plugins/icons_hidpi.png?t=L4D7

/* in tabletoolbar, wrong */
background-image: url('http://localhost:8080/o/frontend-editor-ckeditor-web/ckeditor/plugins/tabletoolbar/icons/add-row.png?t=L4D7')
```

When taking a look in the implementation, We're passing [`icon` property to CKEDITOR.UI_PANELBUTTON component](https://github.com/liferay-frontend/liferay-portal/pull/1227/commits/3c42794be8ddc45743bc229aceaab66dd37dcfcc#diff-325c7592c5f7f73b3eacab75a5bbc5e08abbfe95ca8113713733653825b3a810R959) and this property is passed to the ckeditor4 base button class where [it will search by a relative path to this icon](https://github.com/ckeditor/ckeditor4/blob/cae20318d46745cc46c811da4e7d68b38ca32449/plugins/button/plugin.js#L436). 

One possible way to solve this issue is to remove the dependency of `CKEDITOR.UI_PANELBUTTON` and use `balloonToolbarButton`. However, when using `balloonToolbarButton`, We need to have an extra work in the panel for it use `balloonToolbarPanel` plugin too. Just asking before doing anything wrong. Should I go migrate it to don't use UI_PANELBUTTON or Do you guys have something in mind?

/cc @markocikos @julien

**Comment by diegonvs** [comment]
Screen Shot 2021-07-09 at 15 40 57

When using a development version of CKEditor, following steps described [here](https://github.com/liferay/liferay-ckeditor#testing-in-liferay-portal), icons are shown. I ran a `ant all` again and it stopped working 😓 . Taking a look on [project's changelog](https://github.com/liferay/liferay-ckeditor/blob/master/CHANGELOG.md) I can't see any fix that could be fixed it. So, I'll not re-run a new ant all with a liferay-portal:master rebased version.

Still need to be decided if [I could go with replacing everything of tabletoolbar with balloontoolbarpanel/buttons or not](https://github.com/liferay-frontend/liferay-portal/pull/1227#issuecomment-876806663).

**Comment by diegonvs** [comment]
About "When clicking in another button to trigger another ListBox, the last clicked ListBox is being shown again":

I dig around some cke4 plugins that depends on `CKEDITOR.UI_PANELBUTTON` onBlock method to set the content of a panel and our current usage looks fine. As you can see in [cke4](https://github.com/ckeditor/ckeditor4/blob/8e5575f3c7cc25f28af67d8fa3eb96b7a62b34d7/plugins/emoji/plugin.js#L148) and on [our impl](https://github.com/liferay-frontend/liferay-portal/pull/1227/files#diff-325c7592c5f7f73b3eacab75a5bbc5e08abbfe95ca8113713733653825b3a810R963). If you put a breakpoint on our usage of setHTML, configs are being passed ok when clicking in other panels. So, there isn't an issue with the data passed to this setHTML. However, when this setHTML is called again with the correct value, ListBox markup doesn't update, even [ListBox's setHTML is being called with the correct values](https://github.com/liferay-frontend/liferay-portal/pull/1227/files#diff-325c7592c5f7f73b3eacab75a5bbc5e08abbfe95ca8113713733653825b3a810R1401). I still working trying to figure out what's going on here.

**Comment by markocikos** [comment]
@diegonvs I tested the missing icons, I cannot reproduce the issue (see screen below). URL is wrong in some places, but it is overridden by CSS. It looks like the styles are coming from base ckeditor, `moono-lexicon` skin. I noticed that this PR is on a very old branch, 13k commits behind. When I am pulling PR with `gh`, it is auto-rebasing to `master`. We updated ckeditor version at some point, it might have something to do with this this. 

screen

**Comment by diegonvs** [comment]
I rebased with https://github.com/liferay-frontend/liferay-portal/pull/1070 and the icon issue looks solved ✅ 

However, I'm getting an error which is causing an infinite loop on this following part of the code where showBlock is being called every time. I don't gave the proper time to investigate it and I would start investigating deeply tomorrow. :)

Screen Shot 2021-07-12 at 20 19 47

Before force-pushing the rebase I would investigate a bit this error :)

**Pull request closed without merging**
