### PR TITLE
LRQA-64887 | Refactor panel macro to just use one set

### PR DESCRIPTION
**Pull request by john-co**
**Description**
The test fixes in https://github.com/liferay-frontend/liferay-portal/pull/737 introduced unnecessary redundancy in paths and macros to collapse and expand a panel. It also looks like we tried to continue with this strategy with follow up fixes for the clay panel update in https://github.com/brianchandotcom/liferay-portal/pull/98512. The following commits aim to make the paths more robust and remove the redundancy to make maintenance easier and also fix the remaining tests from the clay panel update listed in this [testray run](https://testray.liferay.com/home/-/testray/case_results/index?delta=200&p_p_state=normal&orderByCol=status_sortable&orderByType=asc&testrayBuildId=1472019420&testrayCaseTypeId=101949&statuses=3&errors=heading
)
 
**Test Plan**
- :heavy_check_mark: Run acceptance poshi tests and make sure they do not have related failures on panel. https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=3&testrayRunIdB=1475023970&testrayRunIdA=1474991493&statusB=2
- :heavy_check_mark:  panel locators are compatible for portal panels prior to and after clay panel update 
- :heavy_check_mark:  panel locators are compatible for bootstrap pattern: https://www.w3schools.com/bootstrap/bootstrap_collapse.asp 
- :heavy_check_mark: panel locators are compatible for current clayui doc panel pattern: https://clayui.com/docs/components/panel.html 
- :heavy_check_mark: panel locators are compatible for panels within iframes
- :heavy_check_mark: panel locators exclude Product Menu panels and categories

**JIRA Ticket**
https://issues.liferay.com/browse/LRQA-64887

### CODE REVIEW

**Comment by john-co** [comment]
ci:help

**Comment by john-co** [comment]
ci:test:poshi

**Comment by john-co** [comment]
cc/ @zhangyan0701 can you please review this and forward if looks ok?

Also, I couldn't assign you as a reviewer. Can you make sure you accepted invitation to be a collaborator on liferay-frontend? If not received invitation please message @brunofernandezg.

**Comment by john-co** [comment]
ci:test:relevant

**Comment by john-co** [comment]
ci:test:poshi

**Comment by zhangyan0701** [comment]
Hi @john-co ,

The panel paths match non-unique elements in some situations, such as when add blog in Blogs admin:
Blogs

Some tests may be affected.

Maybe we can change the path to 
`//*[contains(@class,'panel-group-flush') or contains(@class,'lfr-panel')]//*[normalize-space(text())='${key_panel}']`.

Use class `panel-group-flush` so it will not match the Configuration panel in the Product Menu.

And because these paths are widely used, class `panel-group-flush` doesn't work in some cases, so I added a or in the above path. Could you take a look if there a better way?

And the failed WebContentDisplay tests, looks like a Jenkins issue, I wasn't able to reproduce locally. Could you also take a look at it? I have no idea why and how to fix. Thanks!

**Comment by john-co** [comment]
I see, thanks for the feedback @zhangyan0701 . So now I understand that this path excludes the product menu...I will revise.

**Comment by john-co** [comment]
ci:test:relevant

**Comment by john-co** [comment]
To scope this to outside the product menu, I saw the panels and item selections had @data-qa-id as `appGroup` and `app` respectively so I'm trying to filter them out with `[not(contains(@data-qa-id,'app'))]`

**Explanation of choice:**
It's difficult to find a unique class or id that's outside of product menu useage. 
1. `panel-group` is common with all panels but I feel a developer may decide not to use it
2. `lfr-panel` is not widely used everywhere
3. `panel-group-flush` I would avoid because what if a developer decides not to use it?

Ideally...I think we'd like to have some sort of ability to compose locators. I could see this work well to have a base level path for Clay elements and product teams can clarify the location of those within their usecase. I've raised this request in poshi channel a while back and will raise it again: https://liferay.slack.com/archives/CD7939WBE/p1612983890062900

So with that limitation and seeing that the usecase of Panel.expandPanel macro is to expand all other panels that are not in Product Menu, I'm choosing unique identifiers such as the data-qa-id appGroup and app to filter out.

I took screenshots of the usages of panels within portal that I tested: Calendar, Product Menu, Server Admin, Blogs Admin.
CalendarPanel
ProductMenuPanel
ServerAdminPanel
BlogsAdminPanel

**Comment by john-co** [comment]
ci:test:relevant

**Comment by john-co** [comment]
ci:test:acceptance

**Comment by john-co** [comment]
unique failures are not related to PR commits: https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=3&testrayRunIdB=1475023970&testrayRunIdA=1474991493&statusB=2

Test results do not show indication of issue with panels path locators.

**Comment by john-co** [comment]
ci:forward

**Pull request closed without merging**
