### PR TITLE
LPS-111067 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-111067

This is only for master.

@john-co
@wanderlast

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by wincent** [comment]
ci:reevaluate:1147401_7808

**Comment by wincent** [comment]
> Previous `ci:test:relevant`[build](https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest(master)/7808) was unsuccessfully [reevaluated](https://test-1-9.liferay.com/job/test-portal-evaluate-pullrequest/5/) against more recent upstream results.

hope-never-dies

**Comment by wincent** [comment]
ci:test:relevant

**Comment by john-co** [comment]
ci:test:relevant

**Comment by john-co** [comment]
Closing, will continue in due to modified commit to fix regression https://github.com/liferay-frontend/liferay-portal/pull/842#issuecomment-789819193

**Comment by john-co** [comment]
[Related]
- LocalFile.NavigationMenuWidgetUseCase#NavigationMenuConfigureDisplayTemplate - Impedibug is fixed in https://github.com/liferay-frontend/liferay-portal/pull/842#issuecomment-789819193

[Unrelated]
- functional-tomcat90-mysql57-jdk8/1

```
 [parallel] 2021-03-03 02:11:05.567 ERROR [main][HikariPool:541] HikariPool-1 - Exception during pool initialization.
 [parallel] com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure
 [parallel] 
 [parallel] The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
 [parallel] 	at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:174)
 [parallel] 	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64)
 ```

**Pull request closed without merging**
