### PR TITLE
LPS-143417 Enable keyboard shortcut for interacting with FDS `ActionLinkRenderer`

### PR DESCRIPTION
**Pull request by markocikos**
This is a followup on https://github.com/liferay-frontend/liferay-portal/pull/1737

As @diegonvs is on PTO, I'm jumping in to update the PR.

The previous solution was not entirely correct, as @victorg1991 noted in https://github.com/liferay-frontend/liferay-portal/pull/1737#issuecomment-994722801

In this PR:
- We are preventing default link behavior **only** if confirm message is set.
- We are using the standard `navigate` utility for navigation.

### CODE REVIEW

**Comment by victorg1991** [comment]
LGTM :) Thanks!!

**Comment by victorg1991** [comment]
ci:forward

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
Thanks mighty ci for your infinite kindness 🕯️

**Comment by victorg1991** [comment]
ci:forward

**Comment by john-co** [comment]
cc/ @vicnate5e I've been noticing a lot of flakiness with the semantic versioning and portal license test batches the past couple weeks. Who would be best to reach out to to help see if we can stabilize them?

**Comment by vicnate5** [comment]
@john-co Is SemVer flaky or do we just keep having new issues?

I can look into the license test batch

**Comment by john-co** [comment]
Thanks, I'll take a look to confirm if indeed they are real issues. If they are then it's not a good sign to see so many bypassing `ci:forward` process.

**Pull request closed without merging**
