### PR TITLE
LPS-148425 Use MT UX improvements in Clay sample

### PR DESCRIPTION
**Pull request by tinycarol**
### References

- [LPS-148425](https://issues.liferay.com/browse/LPS-148425)

### What is the goal?

* Update Clay sample to display MT UX improvements epic changes when FF is enabled  

#### FF disabled

https://user-images.githubusercontent.com/6642927/156340901-4781c5e4-5ba0-43af-81c8-63039280edda.mov

#### FF enabled

https://user-images.githubusercontent.com/6642927/156340926-d1996505-1a94-4215-94be-0c3905f59a5b.mov

### How to replicate
* Launch portal
* Run `cd ${PORTAL_ROOT}/modules/apps/frontend-taglib/frontend-taglib-clay-sample-web && gradlew deploy -a`
* Go to `Site Builder > Pages`
* Click on the `+` button next to `Public Pages`, then click on `Add Page`
* Select widget page, name it `Clay sample test`, click on `Add`
* Click `Home` on the left sidebar
* Select the widget page you created in the navigation bar by clicking on `Clay sample test`
* Click on the `+` icon on the right sidebar, the sidebar should extend with the list of available widgets
* Search for `Clay Sample` or click on the `Sample` accordion and see `Clay sample`
* Drag that element to the center of your screen, it should show a tab bar with multiple sections
* Select the `Management Toolbar` section
* Done!

### CODE REVIEW

**Comment by tinycarol** [comment]
ci:test

**Comment by susanchen3** [comment]
ci:test:relevant

**Comment by tinycarol** [comment]
ci:reevaluate:1367401_582

**Comment by tinycarol** [comment]
ci:reevaluate:1367401_582

**Comment by tinycarol** [comment]
ci:reevaluate:1367401_582

**Comment by tinycarol** [comment]
ci:test:relevant

**Comment by tinycarol** [comment]
ci:test:relevant

**Comment by susanchen3** [comment]
ci:test:relevant

**Comment by tinycarol** [comment]
ci:test:relevant

**Comment by tinycarol** [comment]
ci:test:relevant

**Comment by diegonvs** [comment]
ci:test:relevant

**Comment by carloslancha** [comment]
ci:test:relevant

**Comment by Esther-OC** [comment]
After made a comparison between this PR and Upstream, it looks like the failures are not related to this PR, so I think it can be forwarded manually.
The other option is to cross fingers wishing that the CI has a good moment ;-)

**Comment by susanchen3** [comment]
Hi @tinycarol, do you pretty please also mind updating the 'Clear' button as well? :pleading_face: It should display as an icon and show a tooltip message in responsive mode. Thanks in advanced! :D
clear-button

**Comment by tinycarol** [comment]
Hi @susanchen3! That should be working already, just activating the feature flag should do it ^^

**Comment by susanchen3** [comment]
ci:test:relevant

**Comment by diegonvs** [comment]
ci:test:relevant

**Comment by susanchen3** [comment]
Looks like it's not going to pass relevant anytime soon... I reviewed the latest relevant run and I agree with Esther that the failures are unrelated. :+1: Gonna manually forward :)

**Comment by tinycarol** [comment]
Thanks @susanchen3, closing this as it's been merged ❤️

**Pull request closed without merging**
