### PR TITLE
LPS-117796 - [DataSet Display] Brings headless filtering capabilities from Commerce

### PR DESCRIPTION
**Pull request by brunobasto**
Originally https://github.com/liferay-frontend/liferay-portal/pull/158 and then https://github.com/liferay-frontend/liferay-portal/pull/197

Applied changed requested in https://github.com/brianchandotcom/liferay-portal/pull/92122#issuecomment-669699121

### CODE REVIEW

**Comment by brunobasto** [comment]
ci:test:sf

**Comment by brunobasto** [comment]
ci:test:relevant

**Comment by brunobasto** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
lol

**Comment by jbalsas** [comment]
ci:forward

**Pull request closed without merging**
