### PR TITLE
LPD-37261 Write a test using an unautenticated user accessing a page with a fragment

### PR DESCRIPTION
**Pull request by thektan**
Task: https://liferay.atlassian.net/browse/LPD-19841
Subtask: https://liferay.atlassian.net/browse/LPD-37261

- Adds a test for an unauthenticated user viewing a data set fragment
- Added to the `data-set-fragment/dataSets.spec.ts`. Maybe a similar `dataSetsPermissions.spec.ts` could be created for `data-set-fragment`, but since this is just a single test it seemed fine keeping it in `dataSets.spec.ts` for now.

### CODE REVIEW

**Comment by thektan** [comment]
ci:test:playwright

**Comment by juanjofgliferay** [comment]
@thektan Running tests locally and everything works fine. However, after the first run tests start failing due to the presence of Data Sets.
Login as an admin user after the last test will help with the deletion of previous data.

**Comment by thektan** [comment]
ci:test:sf

**Comment by thektan** [comment]
@juanjofgliferay Nice catch. I added an extra step to make sure to log back in as the admin.

Also noticed some typos and had to clear the `article` variable or else it would try to delete an already deleted article and throw an error.

**Comment by thektan** [comment]
ci:test:sf

**Comment by thektan** [comment]
ci:test:playwright

**Review by juanjofgliferay — APPROVED** [review]
LGTM :rocket:

**Comment by thektan** [comment]
ci:report:88146367

**Comment by thektan** [comment]
ci:test:playwright

**Comment by thektan** [comment]
ci:report:88800335

**Comment by thektan** [comment]
Just going to run playwright tests once more...I'm worried if these changes cause any other playwright tests to start as logged out since some of the failures I see have screenshots of the signed-out page.

**Comment by thektan** [comment]
ci:test:playwright

**Comment by dsanz** [comment]
ci:reevaluate:1287401_11921

**Comment by thektan** [comment]
ci:test:playwright

**Comment by thektan** [comment]
ci:test:playwright

**Comment by thektan** [comment]
ci:report:8976421

**Comment by thektan** [comment]
ci:report:89764217

**Comment by thektan** [comment]
Unique failures look like unrelated flaky failures. And the other failures don't seem like any causes from this PR since they've been failing in many other PRs as well so I'm going to go ahead and forward.

**Comment by thektan** [comment]
ci:forward

**Pull request closed without merging**
