### PR TITLE
LPS-116744 Update liferay-ckeditor to 4.14.1-liferay.1

### PR DESCRIPTION
**Pull request by julien**
Release notes:
https://github.com/liferay/liferay-ckeditor/releases/tag/v4.14.1-liferay.1

This completes:
https://issues.liferay.com/browse/LPS-113972

### CODE REVIEW

**Comment by julien** [comment]
ci:test:sf

**Comment by julien** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
Hey @julien, we still are waiting on LPS-116201 [Update liferay-ckeditor version in portal and implement changes to make it fit with new skin](https://github.com/liferay-frontend/liferay-portal/pull/66) which has test failures, probably because of the CKEditor update. 

Can you push over there or make a PR with everything so we can try to get this at once?

Closing here to avoid duplicating this and that. Let's get it done in one single place!

**Comment by jbalsas** [comment]
ci:stop

**Comment by julien** [comment]
@jbalsas of course - thanks

**Comment by julien** [comment]
ci:stop

**Pull request closed without merging**
