### PR TITLE
LPS-178748 Pass the tranlations to clay

### PR DESCRIPTION
**Pull request by robertoDiaz**
Currently FrontendDataSet uses ClayPaginationBarWithBasicItems component but is not passing the translated label values, so ClayPaginationBarWithBasicItems is using its default labels (in english) in all the cases.

I'm fixing it passing this values explicitly.

See the difference. Before:

Captura de Pantalla 2023-03-16 a las 12 45 05

and after:
Captura de Pantalla 2023-03-16 a las 12 44 49

As yo see the iterators labels are been translated as expected.

For more details see the description in https://issues.liferay.com/browse/LPS-178748

@georgel-pop-lr to create this solution

### CODE REVIEW

**Comment by robertoDiaz** [comment]
ci:test:sf

**Comment by robertoDiaz** [comment]
ci:test:relevant

**Comment by eltonccdantas** [comment]
I'll take a look at it

**Comment by eltonccdantas** [comment]
Hi @robertoDiaz , your changes affected some Poshi tests. Could you add me as a contributor to your repository? So I can push the test fixes and then run `ci:test:relevant` again. 

[Comparison run](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=2&testrayRunIdB=2234702089&testrayRunIdA=2233100887&statusB=3)

**Comment by robertoDiaz** [comment]
Dont' worry I could fix them (adding this missing cases to https://github.com/liferay-frontend/liferay-portal/pull/3128/commits/a506cfb26beace69c75330c5514e2d8eef453f4f)

**Comment by robertoDiaz** [comment]
Updated the Pr with the fixes for some test.

Anyway I do not understand why passing the keys could be breaking LocalFile.FDSCustomView#CanBeSaved and LocalFile.FDSCustomView#CanCreateMultiple.

It seems to be a problem with the selector, isn't it?

If not, do you know what do I have to change to fix this tests?

Thanks!!

**Comment by eltonccdantas** [comment]
Yeah, you can check on `FDSCustomView.testcase`, these two tests use `Pagination.viewResults(results = "Showing 1 to 4 of 25");` Therefore, the result is different.

**Comment by eltonccdantas** [comment]
Yeah, the `AssertTextEquals` has got a different result after the modifications, therefore, the tests break.

**Comment by robertoDiaz** [comment]
ci:test:relevant

**Comment by robertoDiaz** [comment]
Hi @eltonccdantas 

I ask @dsanz for some help fixing the tests and he told me to ask you about the needed changes to fix the broken tests

Thank you in advance!

**Comment by eltonccdantas** [comment]
Let me take a look at it

**Comment by eltonccdantas** [comment]
Both tests `FDSCustomView#CanBeSaved` and `FDSCustomView#CanCreateMultiple` share the same fail: `Click( key_menuItem = ${menuItem}, locator1 = "MenuItem#ANY_MENU_ITEM");`

You can check `FDSCustomView.testcase`  on lines `117` and  `211`, you can start debugging from there and go deeper to macros and paths if needed.

**Comment by robertoDiaz** [comment]
Yes, I had seen that.

What i can't find is why this call is broken and where is that implemented.

Any help with this??

**Comment by deborasoliveira** [comment]
@robertoDiaz I can check it, I think this error is probably caused by the path used in the tests.

**Comment by robertoDiaz** [comment]
Thank you!

**Comment by deborasoliveira** [comment]
Hi @robertoDiaz! I executed both _LocalFile.FDSCustomView#CanBeSaved_ and _LocalFile.FDSCustomView#CanCreateMultiple_ using this PR bundle, first the tests failed but after I deployed FDS the tests were executed normally. 
I'm not sure about what the problem could be, but I'll try running relevant again and then investigate the problem further.

**Comment by deborasoliveira** [comment]
ci:test:relevant

**Comment by robertoDiaz** [comment]
hi @deborasoliveira 

Any update related with this??

**Comment by mateusralv** [comment]
I'm taking a look 🕵🏽

**Comment by mateusralv** [comment]
Hi @robertoDiaz The tests are failing because of a path that was modified. To continue the PR I made this commit (https://github.com/liferay-frontend/liferay-portal/pull/3168/commits/394329df48f0bedb311f29393afdfbe82888db08) adding an ignore to the tests and created this investigation ticket [LPS-179895](https://issues.liferay.com/browse/LPS-179895) so that the change can be resolved by some of our QA. 

Could you add this commit https://github.com/liferay-frontend/liferay-portal/pull/3168/commits/394329df48f0bedb311f29393afdfbe82888db08 here before forwarding this PR?

[Testray comparison ](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1679916982916&testrayRunIdA=2240119222&testrayRunIdB=2240187762)

**Comment by robertoDiaz** [comment]
Sure, 

i'll resend with it.

**Comment by robertoDiaz** [comment]
@mateusralv I've resend it

**Comment by robertoDiaz** [comment]
ci:test:relevant

**Comment by eltonccdantas** [comment]
Hi @robertoDiaz , it's all green now, feel free to forward it if no other dev review is needed.

**Pull request closed without merging**
