### PR TITLE
LPS-126737 Replace legacy markup card main-content-card classes with Clay 3 sheet pattern

### PR DESCRIPTION
**Pull request by zhangyan0701**
Resend https://github.com/liferay-frontend/liferay-portal/pull/747 with the test fix.

---

https://issues.liferay.com/browse/LPS-126737

This pr:

- Removes `main-content-card`, adds `container-form-lg` or `container-view` for spacing between `sheet` and navigation, and replace `aui:button-row` with `sheet-footer` and move buttons inside `sheet` where applicable.
- Removes `cssClass="container-form-lg"` from `liferay-frontend:edit-form` tags since it's output by default now
- `liferay-frontend:diff-version-comparator` replace `container-fluid-1280` with `container-fluid container-fluid-max-xl container-view` and remove `main-content-card`
- `liferay-frontend:edit-form` adds `container-form-lg` by default
- `aui:fieldset` adds attribute `panelHeaderLinkCssClass` to pass css classes into the Panel Header Link. It is `sheet-subtitle` by default.
- `aui:fieldset` use `panel panel-unstyled` by default unless a `cssClass` is declared

`liferay-frontend:edit-form` with `aui:fieldset` should look like:
106543551-cbc03c80-64ba-11eb-9b5e-b819db6cbb54

I tried to convert all the nooks and crannies of Portal, but I'm sure I missed a lot. This took too long and hopefully I don't break any tests.

### CODE REVIEW

**Comment by zhangyan0701** [comment]
ci:test:relevant

**Comment by pat270** [comment]
Manually forwarding, see https://github.com/liferay-frontend/liferay-portal/pull/747#issuecomment-773933954

**Comment by pat270** [comment]
ci:forward

**Comment by wincent** [comment]
Forward didn't seem to work, so trying again.

**Comment by wincent** [comment]
ci:forward

**Pull request closed without merging**
