### PR TITLE
LPS-125980 Format .eslintignore

### PR DESCRIPTION
**Pull request by wincent**
Just noticed the mixed indents (tabs and spaces) in `.eslintignore`, which we can fix with by applying the same auto-formatting we already use for `.prettierignore`.

Note that I changed the glob for the latter from `*.prettierignore` to `.prettierignore`, because these files are dotfiles and not extensions.

### CODE REVIEW

**Comment by wincent** [comment]
> ### ❌ ci:test:sf - 0 out of 1 jobs passed in 18 minutes

Error is in a file I didn't touch; SF is checking everything because I changed a file in `modules/util/source-formatter/`. I guess I could fix it, but will probably get a merge conflict with somebody else, so I might just ignore 😁.

**Comment by julien** [comment]
ci:forward

**Comment by wincent** [comment]
ci:stop

**Comment by wincent** [comment]
ci:test:sf

**Comment by wincent** [comment]
ci:test:sf

**Comment by wincent** [comment]
ci:forward

**Comment by wincent** [comment]
ci:forward

**Pull request closed without merging**
