### PR TITLE
LPS-141280 Remote Apps workflow integation first step

### PR DESCRIPTION
**Pull request by javierdearcos**
Add the new columns and integrate with workflow.

The integration is hidden between a feature flag until everything is settled.

Pending how to add the screenshots

### CODE REVIEW

**Review by nhpatt — APPROVED** [review]

**Comment by javierdearcos** [comment]
ci:forward

**Comment by javierdearcos** [comment]
ci:test:relevant

**Comment by javierdearcos** [comment]
Checking the POSHI test screenshots it seems the database is not clean from other execution or the test is trying to create multiple remote apps with the same URL, what is not allowed.

Can you take a look when you have time? 🙏  @magjed4289 @john-co

Anyway I will try running the tests again in case it is a flaky test

**Comment by javierdearcos** [comment]
ci:test:relevant

**Comment by javierdearcos** [comment]
ci:forward

**Comment by john-co** [comment]
Hi @magjed4289, can you follow up on this? It does seem like old data from another testcase could be affecting this. Possibly the teardown step isn't working as well as before now that some other fields are added?

**Comment by javierdearcos** [comment]
I will close this PR as I continue working on a follow up PR and I prefer to send directly the new one:

https://github.com/liferay-frontend/liferay-portal/pull/1667

I'll talk with you again when the PR is ready if the errors are still there.

Thank you for your support!

**Comment by nhpatt** [comment]
You have also https://github.com/liferay-frontend/liferay-portal/pull/1635 open, should it stay open?

**Comment by javierdearcos** [comment]
I don't think so. Closed.

Thank you for noticing

**Comment by magjed4289** [comment]
Just started reviewing :)

**Pull request closed without merging**
