### PR TITLE
LPS-184608 | Element not present in ClientExtensionWorkflow#AdminCanRejectRemotePortlet

### PR DESCRIPTION
**Pull request by abhnerramos**
**Description**
Element not present in ClientExtensionWorkflow#AdminCanRejectRemotePortlet

**JIRA Ticket**
https://issues.liferay.com/browse/LPS-184608

### CODE REVIEW

**Comment by abhnerramos** [comment]
ci:test:sf

**Comment by abhnerramos** [comment]
ci:test:frontend

**Comment by abhnerramos** [comment]
ci:test:sf

**Comment by abhnerramos** [comment]
ci:test:sf

**Comment by abhnerramos** [comment]
ci:test:frontend

**Comment by abhnerramos** [comment]
hey @CarlosBrichete , LGTM! Failures don't seem to be related, could you take a look, please?

**Review by CarlosBrichete — APPROVED** [review]

**Comment by CarlosBrichete** [comment]
LGTM :)

**Comment by abhnerramos** [comment]
ci:forward

**Pull request closed without merging**
