### PR TITLE
LPS-198462 Removes unused frontend-taglib-soy

### PR DESCRIPTION
**Pull request by ealonso**
Motivation
-----
In order to allow us remove soy from portal, removes unused frontend-taglib-soy.

### CODE REVIEW

**Comment by ealonso** [comment]
ci:test:sf

**Review by bryceosterhaus — APPROVED** [review]
If CI is fine with it, I think this is fine

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Hey @bryceosterhaus

I think we need to wait for master sync, since it's depends on some commits that we have in Brian's repo. Once it is synced I'll run it again.

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward:force

**Comment by ealonso** [comment]
Manual forward see: https://github.com/brianchandotcom/liferay-portal/pull/141996

**Comment by bryceosterhaus** [comment]
@ealonso I just thought about this, but make sure to run `yarn` in `./modules` on PRs like this were we either modify or remove a package.json.

I sent a follow up https://github.com/liferay-frontend/liferay-portal/pull/3745

**Comment by ealonso** [comment]
Hey @bryceosterhaus,

Thanks you very much!, I didn't know about it.

**Pull request closed without merging**
