### PR TITLE
LPS-131172 Fix non-working disableNamespace=true attribute in liferay-ui:input-date

### PR DESCRIPTION
**Pull request by jgarcialr**
When using a liferay-ui:input-date with attribute disableNamespace=true, the datepicker is not being created nor shown.

### CODE REVIEW

**Comment by julien** [comment]
Hey @jgarcialr thanks for submitting this.

I'm going to review this but I wanted to ask you if you could read the following articles:
- [Pull Request Etiquette](https://github.com/liferay/liferay-frontend-projects/blob/master/guidelines/general/pull_requests.md#pull-request-etiquette)
- [Frontend Infrastructure Team code review process](https://github.com/liferay/liferay-frontend-projects/blob/master/guidelines/dxp/code_review.md#frontend-infrastructure-team-code-review-process)

If possible, we'd appreciate if you could provide
- Descriptive title beyond a mere LPS
- Thorough description of the issue, things you tried, why you thing your solution is the right approach and any other considerations that might help us in our review
- Test plan with simple steps to validate the issue (or get a feeling of how it has been validated by you)

Thanks!

**Comment by jgarcialr** [comment]
Hi @julien,

Sorry, I didn't know about the etiquette.
-------------------------------------------------------------
Description of the issue:
-------------------------------
When using a liferay-ui:input-date with  disableNamespace attribute value=true, the datepicker is not being created nor shown.
----------------------------------------------------------------
Things I've tried. 

Generated a new portlet with a form with two fields,  one field is a liferay-ui:input-date with disableNamespace=true and a second liferay-ui:input-date with disabledNamespace attribute = false.

Second field works correctly, but first one doesn't register component.

add a console.log inside page.jsp of liferay-ui:input-date for knowing what's receiving the browser in the js script where DatePicker component is created.

Observed that despite attribute useNamespace is false , input fields inside page.jsp created with <aui:input> always use namespace. 

--------------------------------------------------------------------
Test plan

Start liferay with master version
Go to https://issues.liferay.com/browse/LPS-131172 and download prueba.jar
Deploy in your liferay server
Add the portlet to a page -> widget -> sample -> prueba

When clicking on the first field, datepicker is not shown but in the second field is shown.
-------------------

After aplying this change  both fields show datepicker component

**Comment by julien** [comment]
Hey @jgarcialr, 

I fetched this branch and the "sample jar" attached in the [LPS ticket](https://issues.liferay.com/browse/LPS-131172) (to be able to reproduce the error) from [here](https://issues.liferay.com/secure/attachment/403209/prueba-1.0.0.jar)

Here's the **test plan** I used (please correct me if I'm wrong, but if it's OK you could copy this bit in the description)

- Deploy **prueba.jar** inside the `$LIFERAY_HOME/deploy` directory
- Deploy the `portal-web` module (with `ant deploy`)
- Navigate to **Site Builder** > **Pages**
- Created a new **Content Page**
- Drag and Drop the **Prueba** Widget on the page
- Publish the page
- Navigate to the page you just published
- Clicking in both of the (date) input fields should show a date picker 

I've also got two .gifs (we're very fond of those @liferay-frontend) 

Here's what this looks like **before** these changes:


And here's what it looks like **after** deploying the changes:


So before the changes, it seems that nothing happens when clicking in the input field which doesn't have the `useNamespace` attribute.

The last thing I've noticed (and that we very briefly discussed on Slack), is that regardless of these changes, an error is thrown and visible in the browser's console, so here's another .gif


 
 I'm not 100% sure but could this be because we're not using the `<liferay-ui:input-date />` tags inside a `<form >` tag?
 
Thanks

**Comment by julien** [comment]
> Sorry, I didn't know about the etiquette.
No problem, we're here to help with that :+1:

**Comment by jgarcialr** [comment]
> I'm not 100% sure but could this be because we're not using the `<liferay-ui:input-date />` tags inside a `<form >` tag?

Yes, putting those fields inside a form cleans the error from browser console.

Thanks for the help

**Comment by julien** [comment]
@jgarcialr thanks, I've also tested that too and I can confirm that when the `<liferay-ui:input-date />` is in a `<form>` tag, we don't see any errors.

And here's the updated .gif (just in case)
recording

Concerning the changes, I don't see anything wrong about them, so if CI is happy, this looks good to me.

**PS**, I edited your [comment](https://github.com/liferay-frontend/liferay-portal/pull/998#issuecomment-826886841), I hope you don't mind.

**Comment by jgarcialr** [comment]
Hi @julien ,

Thanks for updating the description and the new gif and all the guidance in the process.
Regards

**Comment by wincent** [comment]
ci:forward

**Comment by wincent** [comment]
Ok, so forwarded it, although I have a sneaking suspicion Brian is going to reject it based on the formatting of the ternaries (no spaces around the operators), or because he would prefer a simple `!` negation. But whatever, can't predict that stuff, so let's see what he does.

**Comment by wincent** [comment]
You [got lucky](https://github.com/brianchandotcom/liferay-portal/pull/101136#issuecomment-827556903) @jgarcialr — Brian [applied a fix on top](https://github.com/brianchandotcom/liferay-portal/commit/721b2dbb0ecf0e938ea8f04eba11c348a7014fa7) rather than rejecting it outright.

that-was-close

**Comment by julien** [comment]
Hey @wincent thanks for the heads up, I admit that the I did see the lack of spaces and unnecessary booleans but seeing SF passed made me think it "wasn't that important". I'll be more careful with that.

**Pull request closed without merging**
