### PR TITLE
COMMERCE-4693 Fix assignee button style

### PR DESCRIPTION
**Pull request by eduardoallegrini**
In this PR we are fixing (at least) the following issues:
- [Secondary button style](https://issues.liferay.com/browse/COMMERCE-4685)
- [Header responsiveness](https://issues.liferay.com/browse/COMMERCE-4779)
- [Assignee button style](https://issues.liferay.com/browse/COMMERCE-4693)

But I may have fixed some other issue in the attempt of cleaning the markup structure

**Please, keep in mind that this is a temporary fix until we can work on the final version of the project**

In this phase I prefered to avoid the usage of `clay-taglibs` and `clay-css-variables`

[Design of reference](https://www.figma.com/file/SvueKimLHLZ2NJEXEnx9kT/Commerce-Admin-UI---v7.2?node-id=13102%3A0)

Current behavior:

ezgif com-gif-maker (1)
ezgif com-gif-maker (2)

---

How to test the `header-structure-and-responsiveness` and `secondary-button-style` fixes?

- Create a product from the `application-menu > commerce > product-management > products`
- Insert a name and select a catalog
   - If no catalog is available, create one from `application-menu > commerce > product-management > catalogs`

How to test the `assignee-button-style` fix?

- Go to sites: `application-menu > control-panel > site > sites`
- Create a new site and select the `speedwell` starter theme
- Go to channels `application-menu > commerce > store-management > channels`
- Select the channel assigned to your new site
- Assign a workflow to the channel
image
- Place an order from your new site
   - Go to the new site
   - Open the top left hamburger-icon menu
   - Choose `catalog` from the menu links
   - Click on `add to the cart` on an product
   - Click on the checkout cart-icon menu on the top right
   - Click `checkout`
ezgif com-gif-maker (3)
- Go to the new order `application-menu > commerce > order-management > orders`

---

I'm sending this PR here to double check the changes and to be sure I'm not including not-ready-to-be-implemented modifications 😁

---

@marcoscv-work do you think the `assignee-button-style` modification could be an accessibility issue?

/cc @jbalsas

### CODE REVIEW

**Comment by marcoscv-work** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcoscv-work** [comment]
Probably known issues:

Columns:

image


In mobile, the menu cannot be scrolled:
image
issueMenu

Original menu in Desktop:
image

**Comment by marcoscv-work** [comment]
As @eduardoallegrini told us, this is a temporary fix until we can work on a final version, so in order to push PR's, we go ahead with it!

**Comment by marcoscv-work** [comment]
ci:test:sf

**Comment by marcoscv-work** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
Please, send to @liferay-commerce if all is good, then! 👍

**Comment by marcoscv-work** [comment]
> Please, send to @liferay-commerce if all is good, then! 👍

Should I stop `ci:tests`?

**Review by marcoscv-work — APPROVED** [review]

**Comment by jbalsas** [comment]
> Should I stop ci:tests?

No, seeing this green would be part of "if all is good" ;)

**Comment by marcoscv-work** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcoscv-work** [comment]
Close and resend to:

https://github.com/liferay-commerce/liferay-portal/pull/378

**Pull request closed without merging**
