### PR TITLE
LPS-193195 Add auto-save to FDS view 

### PR DESCRIPTION
**Pull request by edalgrin**
This PR enable auto-save for Fields, Filters and Sorting tabs of the FDS Views and remove the save and cancel buttons

ezgif com-video-to-gif

### CODE REVIEW

**Review by markocikos — CHANGES_REQUESTED** [review]
@edalgrin I tested this solution, and it doesn't behave correctly. We are saving whenever user hovers over an item. What we should do is save only on end, on the `drop` event.


https://github.com/liferay-frontend/liferay-portal/assets/5435511/37f33a3b-bf2a-44d9-b41e-c90da5371ec1

**Comment by dsanz** [comment]
nice catch @markocikos. Nevertheless, code is attaching to `onOrderChange` handler which might be being called [more than needed](https://github.com/liferay/liferay-portal/blob/a69ac3c899791fc483250f1accfbbb63b1a277f7/modules/apps/frontend-data-set/frontend-data-set-views-web/src/main/resources/META-INF/resources/js/components/OrderableTable.tsx#L111) . 

In addition, we may consider saving order also when creating and deleting items

**Comment by markocikos** [comment]
@dsanz The key point of code is the [the `hover` listener](https://github.com/liferay/liferay-portal/blob/master/modules/apps/frontend-data-set/frontend-data-set-views-web/src/main/resources/META-INF/resources/js/components/OrderableTable.tsx#L78-L114) of `useDrop`, hook from `react-dnd`. Within it, we are updating order state. That, in itself, is fine. It has nothing directly to do with saving. Looking at `react-dnd` [docs](https://react-dnd.github.io/react-dnd/docs/api/use-drop), we should leverage the `drop(item, monitor)` object member.

**Comment by edalgrin** [comment]
> @dsanz The key point of code is the [the `hover` listener](https://github.com/liferay/liferay-portal/blob/master/modules/apps/frontend-data-set/frontend-data-set-views-web/src/main/resources/META-INF/resources/js/components/OrderableTable.tsx#L78-L114) of `useDrop`, hook from `react-dnd`. Within it, we are updating order state. That, in itself, is fine. It has nothing directly to do with saving. Looking at `react-dnd` [docs](https://react-dnd.github.io/react-dnd/docs/api/use-drop), we should leverage the `drop(item, monitor)` object member, saving the order within it.

I did some quick tests on it but it's not working, we probably need to split the current function (which has always worked changing the order on hover) into 2 functions: on hover, for the visualization of the list; on drop, for the saving part.

In any case I agree it's necessary to avoid the repetition of the saving and the multiple alerts, BUT maybe we can address this in another ticket, what do you think?

**Comment by dsanz** [comment]
> Looking at react-dnd [docs](https://react-dnd.github.io/react-dnd/docs/api/use-drop), we should leverage the drop(item, monitor) object member, saving the order within it.

Yep, just realized I was not clear in the explanation. What I meant is that the `onOrderChange` function in the `OrderableTable` API is being called on hover, and thus, it does not meet the requirement we want, i.e. save on drop. Nevertheless, from outside `OrderableTable` there is no other way to know about a change in the order, so we just don't have a way to see if order changed because of a drop. 

Current `OrderableTable` usages pass a piece of component own state (say `filters`, `sorts` or `fields`) to the `OrderableTable` via `items` prop. Then the `OrderableTable` creates its own internal state off from it. That internal state can change many times (on each hover operation moving things around with no drop at all). 

However, when it comes to tell parent that a change in the order took place, we use the `onOrderChange`, the expectation is for parent to set its own state, e.g. recompute the string with the ids and save it (btw this recomputation may perhaps take place in the `OrderableTable` using `item.id`). Other thing parent can do is updating its own state (`filters`, `sorts` or `fields`) to reflect the new order, but that's not mandatory as a new render will re-fetch things from the backend with the new order applied.

That brings a question: do we need `OrderableTable` client code to know about any order change due to items hovering, or do we just want to tell what's the order when item is effectively dropped?

Answer to that question determines the next course of action:

1. Either we add a new `onOrderChangeAfterDrop` function handler to the `OrderableTable` component, or 
2. we change the semantics and invoke `onOrderChange` only after dropping, keeping an internal handler to properly re-position items during hover. 

I don't see a valuable use case to support (1) however I might be wrong here.
Thoughts?

**Comment by markocikos** [comment]
> That brings a question: do we need OrderableTable client code to know about any order change due to items hovering, or do we just want to tell what's the order when item is effectively dropped

_need_ is a strong word. Technically, we don't need it, but for the sake of sensible UX, we do need it. I think there needs to be some indicator in UI that shuffling is taking place. Current implementation, copied from how they implemented in Objects team, swaps rows on hover, and is a perfectly fine indicator. Alternative would be to add some fat line between entries, like for example in smartgit (see movie below)

But, whatever this is, it does not change the fact that we want save on drop action. That's unrelated to component behavior on hover.

https://github.com/liferay-frontend/liferay-portal/assets/5435511/25428547-6fd3-4e2b-b2c2-9874fabe8e06

**Comment by dsanz** [comment]
I see your point Marko, your explanation makes me believe that a better separation between hover shuffling and final drop is needed. I see value in current UX where hover changes placement of items as it goes. Nevertheless, the question I tried to answer is more concerned with informing the parent component about this or not. 

So we may keep current ux with reshuffling on hover, but not run the user-provided `onOrderChange` till a real drop takes place. Both things are possible at the same time. My question does not focus on the internal state of the orderable table, but rather, when (and how) that state is communicated to the code using `OrderableTable`.

So, we can make this communication in different ways:

- Separate `onOrderChange` into 2 handlers, one being called back when order changes as a result of hover, the other when item is dropped. So, client code would give the one it's interested in, or both:
``` js
	<ClayLayout.ContainerFluid>
			<OrderableTable
				onChangeHandlerHover={noop}
				onChangeHandlerDrop={ ({orderedItems}: {orderedItems: IFilter[]}) => {
					saveNewFiltersOrder(
						orderedItems.map((filter) => filter.id).join(',')
					);
				}
     ...
```
- Or else, just allow a single `onChangeHandler` in the component API, and call it only on drop, under the assumption that `onChangeHandlerHover` is not going to be much useful.

That's the core of the question I was trying to convey. As you said, there is no reason to remove current UX indicators.

**Comment by markocikos** [comment]
> So we may keep current ux with reshuffling on hover, but not run the user-provided onOrderChange till a real drop takes place. Both things are possible at the same time. My question does not focus on the internal state of the orderable table, but rather, when (and how) that state is communicated to the code using OrderableTable.

Oh, I see what you mean. I see the drop event as natural expected trigger for external `onOrderChange` callback. Internal order can be swapped on hover, this order is only temporary after each hover cross. Later on, we may want to switch internal swapping for some other indicator, but the contract to API would stay the same: order change on drop.

**Comment by dsanz** [comment]
Yes! that is what I meant. I think we can manage this that way in the current pull.

Additionally, a last bit of logic is needed to persist the order on item creation and deletion. That's a separate piece not related with orderabletable. I think it's also doable

**Comment by edalgrin** [comment]
Sorry I got lost in the conversation, do I need to add any change for this PR?

**Comment by markocikos** [comment]
Followup in https://github.com/liferay-frontend/liferay-portal/pull/3656

**Pull request closed without merging**
