### PR TITLE
LPS-139707 Add instanceable field to RemoteAppEntry

### PR DESCRIPTION
**Pull request by izaera**

### CODE REVIEW

**Comment by izaera** [comment]
ci:test:sf

**Comment by izaera** [comment]
ci:test:relevant

**Comment by izaera** [comment]
Errors don't seem related to PR...

**Comment by john-co** [comment]
ci:test:relevant

**Comment by john-co** [comment]
The test failure looks related:

```
     [exec] > Task :apps:site-initializer:site-initializer-extender:site-initializer-extender:compileJava FAILED
     [exec] 
     [exec] > Task :apps:commerce:headless:headless-commerce:headless-commerce-admin-catalog-api:autoUpdateXml SKIPPED
     [exec] > Task :apps:commerce:headless:headless-commerce:headless-commerce-admin-channel-api:autoUpdateXml SKIPPED
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/site-initializer/site-initializer-extender/site-initializer-extender/src/main/java/com/liferay/site/initializer/extender/internal/BundleSiteInitializer.java:1158: error: method addCustomElementRemoteAppEntry in interface RemoteAppEntryLocalService cannot be applied to given types;
     [exec] 			_remoteAppEntryLocalService.addCustomElementRemoteAppEntry(
     [exec] 			                           ^
     [exec]   required: long,String,String,String,boolean,Map<Locale,String>,String,String
     [exec]   found: long,String,String,String,Map<Locale,String>,String,String
     [exec]   reason: actual and formal argument lists differ in length
     ```

**Comment by izaera** [comment]
ci:test:sf

**Comment by izaera** [comment]
ci:forward

**Comment by izaera** [comment]
ci:forward

**Comment by izaera** [comment]
once again

**Comment by izaera** [comment]
come on, bot, forward it :pray:

**Comment by izaera** [comment]
thanks, bro :+1:

**Pull request closed without merging**
