### PR TITLE
LPS-187257 add doAsGroupId to session_click request

### PR DESCRIPTION
**Pull request by antonio-ortega**
Hey guys,

This is just a new pull request about this same issue following the approach suggested by Brian here so JS logic matches Java backend logic.

Let me know if you have any questions about it. Otherwise I'll forward it if test pass sucessfully.

Thanks.

### CODE REVIEW

**Review by bryceosterhaus — APPROVED** [review]
LGTM!

**Comment by antonio-ortega** [comment]
ci:test:relevant

**Comment by antonio-ortega** [comment]
ci:test:sf
ci:test:relevant

**Comment by antonio-ortega** [comment]
ci:test:relevant

**Comment by mateusralv** [comment]
I'm on it 🕵🏽

**Comment by mateusralv** [comment]
ci:test:relevant

**Comment by antonio-ortega** [comment]
I'm closing this PR since this solution is not fully working.

I'll need to resend to Brian https://github.com/brianchandotcom/liferay-portal/pull/138058 which was actually working fine.

**Pull request closed without merging**
