### PR TITLE
LPS-141372 - Remove unused node-shims

### PR DESCRIPTION
**Pull request by bryceosterhaus**
Searched and tested this locally and I didn't see anything wrong but I want to run through CI just to be sure.

### CODE REVIEW

**Comment by bryceosterhaus** [comment]
ci:help

**Comment by bryceosterhaus** [comment]
ci:test:gauntlet

**Comment by bryceosterhaus** [comment]
ci:test:stable

**Comment by bryceosterhaus** [comment]
ci:test:stable

**Comment by izaera** [comment]
nervous

**Comment by magjed4289** [comment]
ci:test

**Comment by bryceosterhaus** [comment]
ci:test

**Comment by bryceosterhaus** [comment]
ci:test:acceptance-functional

**Comment by bryceosterhaus** [comment]
ci:test:upstream-functional

**Comment by bryceosterhaus** [comment]
ci:test:upstream-functional

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by john-co** [comment]
ci:test:relevant

**Comment by john-co** [comment]
ci:test:upstream-functional

**Comment by magjed4289** [comment]
Reviewed. Test failures are unrelated. ✔️
Ok to manually forward.

[Unrelated]
https://issues.liferay.com/browse/LPS-143525

**Comment by bryceosterhaus** [comment]
manual forward at https://github.com/brianchandotcom/liferay-portal/pull/110853

**Pull request closed without merging**
