### PR TITLE
LPS-124112 Add external reference code to KBArticle and KBFolder

### PR DESCRIPTION
**Pull request by LuismiBarcos**
NOTE: About the breaking change requested [here](https://github.com/brianchandotcom/liferay-portal/pull/102299#issuecomment-848428576). I've talked with @pablo-agulla and we prefer to set the methods as deprecated at least one version due to the impact that could have on the users the deletion of the methods.

This pull is the first part of the feature described in [this ticket](https://issues.liferay.com/browse/LPS-124112)
The external reference code (also called ERC) is a unique id to identify a specific resource. It could be scoped by group or by company.

In the PR, it added support for external reference code in KBArticle and KBFolder services to be able to add KBArticles and KBFolders with a specific external reference code. In case that the user does not provide the ERC, it will be assigned by default the id of the resource.

We see that exists a problem with the external reference code when a resource support versioning. In this case, the resource is KBArticle. Every time that we create a new version of a KBArticle a new file is created in the DB with a new kbArticleId. Because the ERC is a representation of a resource scoped by group, the ERC should be the same for all versions of a resource.

To avoid the problem described above, we've created the ERC for KBArticle in the DB manually and add the filters to search the resource by groupId and ERC and by groupId, ERC, and version.

### CODE REVIEW

**Comment by LuismiBarcos** [comment]
FYI: @nhpatt

**Comment by LuismiBarcos** [comment]
ci:forward

**Comment by nhpatt** [comment]
ci:forward

**Comment by LuismiBarcos** [comment]
ci:reevaluate:1127401_4788

**Comment by LuismiBarcos** [comment]
ci:reevaluate:1127401_4788

**Comment by LuismiBarcos** [comment]
Rebase and forward

**Comment by LuismiBarcos** [comment]
ci:forward

**Comment by LuismiBarcos** [comment]
Rebase, baseline, and forward

**Comment by LuismiBarcos** [comment]
ci:forward

**Pull request closed without merging**
