### PR TITLE
LPS-162074 Use imported `sub` instead of `Liferay.Util.sub`

### PR DESCRIPTION
**Pull request by kresimir-coko**
The only potentially questionable part of the PR would be my `sub` mocks in the test commit.

I removed them where I felt was possible, and left the mocks in places where simply adding `x` would compromise the test - either by having multiple elements with the same label, or complex strings that test their values.

### CODE REVIEW

**Comment by kresimir-coko** [comment]
ci:test:sf

**Comment by kresimir-coko** [comment]
ci:test:relevant

**Comment by kresimir-coko** [comment]
ci:stop

**Review by markocikos — APPROVED** [review]
LGTM!

I had problems with that weird SF in my recent PR. To pass CI, I ended up not including it.

**Review by bryceosterhaus — CHANGES_REQUESTED** [review]
Instead of adding multiple mocks for sub inline, can you just move the mock to a global mock for that file? I believe you just need to add `__mocks__/sub.js` next to that module.

Additionally, can you create a ticket on the projects repo to create an eslint rule to prefer `sub` instead of the global util? You could create something called like `avoid-global-util`

**Comment by kresimir-coko** [comment]
Manually forwarded to https://github.com/brianchandotcom/liferay-portal/pull/124024

**Pull request closed without merging**
