### PR TITLE
LPS-135546 Add by-external-reference-code endpoints to Structured Content

### PR DESCRIPTION
**Pull request by javierdearcos**
Add the new by-external-reference-code to Structured Content to delete, get and upsert a Structured Content by external reference code.

The test for upsert should be autogenerated with a following PR that is modifying the REST Builder TestCase template

### CODE REVIEW

**Comment by javierdearcos** [comment]
ci:test:relevant

**Review by nhpatt — APPROVED** [review]

**Comment by javierdearcos** [comment]
ci:test:sf

**Comment by javierdearcos** [comment]
ci:forward

**Comment by javierdearcos** [comment]
ci:forward

**Comment by javierdearcos** [comment]
ci:forward

**Pull request closed without merging**
