### PR TITLE
LPS-150842: Fix XSS searching vulnerability in Management Toolbar

### PR DESCRIPTION
**Pull request by sergiojimcos**
**Steps to reproduce:**

1. Go to **Control Panel** > **Sites**
2. Create a site named **<script>alert(123)</script>**
3. Search the site name **<script>alert(123)</script>**

**Expected Result.**
It should be no XSS issue.

**Before PR**

image

**After PR**

https://user-images.githubusercontent.com/44723449/161242401-17de5217-8f62-4db5-8e75-b2806b952c0f.mov

**JIRA Ticket**
https://issues.liferay.com/browse/LPS-150842

### CODE REVIEW

**Review by bryceosterhaus — APPROVED** [review]
LGTM!

**Review by tinycarol — APPROVED** [review]
LGTM, great job @sergiojimcos ^^

**Comment by brianchandotcom** [comment]
@tinycarol @sergiojimcos I merged this manually.

**Comment by sergiojimcos** [comment]
Manually forwarded: See in d6ef17512feddad43b5f6abfaa0cf08ff07d8fc3

**Pull request closed without merging**
