### PR TITLE
LPS-162900 Submit form manually instead of preventing the submit event

### PR DESCRIPTION
**Pull request by diegonvs**
# How to test it

1. Navigate to SAML Admin.
2. Select the Service Provider as SAML role.
3. Enter samlsp as entity ID, then click Save.
4. Click on Create Certificate under Encryption Certificate and Private Key section.
5. Enter the required information then click Save.
6. Click on Delete Certificate.

**Actual result:**

There's no confirmation message when deleting a certificate.

**Expected result:**

A confirmation message says, "Are you sure you want to delete this certificate from the keystore?" when deleting a certificate.

# How I fixed it

Instead of relying on automatic form event submission from HTML5, handle it on JS side

### CODE REVIEW

**Comment by diegonvs** [comment]
Hey @stian-sigvartsen, I'm not sure if you are the code owner of `saml-web`, but if you're, could you see if everything is okay?

**Comment by diegonvs** [comment]
ci:test:sf

**Comment by diegonvs** [comment]
ci:test:relevant

**Comment by stian-sigvartsen** [comment]
Hi @diegonvs . Yes SAML is a component maintained the App Sec team so me and other member can review. We'll try to review today. Thanks for working on the fix!

**Comment by stian-sigvartsen** [comment]
@diegonvs looks good to me! Forward at liferay-frontend's discretion 👍

**Comment by diegonvs** [comment]
ci:forward

**Pull request closed without merging**
