### PR TITLE
LPS-123551 Deprecate Java minification classes

### PR DESCRIPTION
**Pull request by wincent**
As a final step in our "Simplify JS minification scheme in DXP" epic (https://issues.liferay.com/browse/LPS-122883) we're marking the legacy runtime architecture as deprecated to give customers fair warning about its removal.

This includes the following classes:

- `CSSCompressor`
- `GoogleJavaScriptMinifier`
- `MinifierUtil`
- `YahooJavaScriptMinifier`

and interface:

- `JavaScriptMinifier`

### CODE REVIEW

**Comment by wincent** [comment]
Just a few additional things to note:

- Does it make sense to `@deprecate` an `interface` in Java? I think it does (as in telling people not to create new classes that implement the interface), but I am not sure.
- I didn't update `readme/BREAKING_CHANGES.markdown` because we didn't actually break anything yet, and won't until we actually remove the classes (post-7.4.x).
- We are still using `MinifierUtil` in particular in a few places internally (ie. see [the list here](https://docs.google.com/document/d/1JYSSSVFQlEwy1CRv1ZD6hfql8AzuXTS39qY5HMnvUe4/edit)) — it seems harmless enough to allow those — they are mostly small/simple cases, and won't be active in practice because we have turned off minification by default since https://github.com/brianchandotcom/liferay-portal/pull/96763; am I correct in assuming that we shouldn't remove those calls yet because otherwise the minification settings in the properties file don't make any sense?

**Review by jbalsas — APPROVED** [review]
LGTM

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by wincent** [comment]
> ### ❌ ci:test:stable - 1 out of 9 jobs passed
> ### ❌ ci:test:relevant - 1 out of 23 jobs passed in 1 hour 33 minutes

thanks-obama

**Comment by wincent** [comment]
Flagged in `#ci` [here](https://liferay.slack.com/archives/C19PWQ74J/p1607957314267300).

**Comment by wincent** [comment]
ci:test:relevant

**Comment by john-co** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
ci:forward

**Pull request closed without merging**
