### PR TITLE
LPS-188590 | Create automations (Set data set manager in beta mode)

### PR DESCRIPTION
**Pull request by andreluis2022**
Description:
Create functional automations in Data Sets

JIRA Ticket:
[LPS-188590](https://liferay.atlassian.net/browse/LPS-188590) History

### CODE REVIEW

**Comment by andreluis2022** [comment]
ci:test:frontend-data-set

**Comment by andreluis2022** [comment]
Hey @CarlosBrichete can you take a look in this tests ?

**Review by CarlosBrichete — CHANGES_REQUESTED** [review]
Hey @andreluis2022! Tests look good, but some of them have an incorrect priority. Please review the tests priority and fix it, thanks! :)

**Comment by andreluis2022** [comment]
ci:forward

**Pull request closed without merging**
