### PR TITLE
LPS-172764 | Remembering user selections in search container when SPA is Off

### PR DESCRIPTION
**Pull request by andreluis2022**
**Description**:
Product QA | Functional Automation - LPS-172764 Remembering user selections in search container when SPA is Off

**JIRA Ticket:**
[LPS-172764](https://liferay.atlassian.net/browse/LPS-172764) History

### CODE REVIEW

**Comment by andreluis2022** [comment]
ci:test:sf

**Comment by andreluis2022** [comment]
ci:test:frontend-data-set

**Comment by andreluis2022** [comment]
Hey @CarlosBrichete can you take a look in these tests ?

**Review by CarlosBrichete — APPROVED** [review]
LGTM

**Pull request closed without merging**
