### PR TITLE
LPS-188401 There are some dynamic attributes that can contain xss

### PR DESCRIPTION
**Pull request by victorg1991**
None of the dynamic attributes are escaped when calling the clay taglibs. We cannot escape them from the origin, since the react component already does this for us. We only need to escape those for the server side rendering that is performed in the tag.

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:test:sf

**Review by markocikos — APPROVED** [review]
@victorg1991 LGTM! :sparkles:

**Comment by bakayattila** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:forward

**Comment by dsanz** [comment]
Perhaps rebasing this can get rid of the semver error?

**Comment by victorg1991** [comment]
ci:forward

**Pull request closed without merging**
