### PR TITLE
LPS-188234 Adding stubs for new automations in ViewFields

### PR DESCRIPTION
**Pull request by andreluis2022**
Description:
Add stubs for new automations in Fields

JIRA Ticket:
[LPS-184693](https://liferay.atlassian.net/browse/LPS-184693) Test Scenarios

### CODE REVIEW

**Comment by andreluis2022** [comment]
Hey @mateusralv can you take a look in the stubs, please ?

**Comment by mateusralv** [comment]
ci:test:sf

**Comment by mateusralv** [comment]
ci:test:relevant

**Comment by andreluis2022** [comment]
ci:test:sf

**Comment by andreluis2022** [comment]
ci:test:relevant

**Comment by mateusralv** [comment]
ci:forward

**Pull request closed without merging**
