### PR TITLE
LPS-167280 Add liferay npm scripts for frontend-css-common

### PR DESCRIPTION
**Pull request by Seiphon**
Here is the original pr https://github.com/liferay-frontend/liferay-portal/pull/2966, Brain Chan has merged it, but there is a license issue when publishing "frontend-css-common" module, so he reverted that commit. 

I have asked the colleague who manage the gradle plugin, he said it's ok for him to add '"private": true' property. But if so, the npm will refuse to publish the module, so I want to check with frontend team again, is that OK, if I set it to private?

### CODE REVIEW

**Comment by izaera** [comment]
> But if so, the npm will refuse to publish the module, so I want to check with frontend team again, is that OK, if I set it to private?

Seeing that your original PR added a `package.json` file for `@liferay/frontend-css-common`, I assume it was never published to npm registry (and, in fact, performing a search there for that package shows no results). Thus, I'd say there's no problem in making it private, since, if it wasn't published before, it doesn't need to be published now.

In any case, I'm not the reponsible for that module, so I have no idea if it is intended to be published (now or in the future) or not, so I'll check internally to make sure.

**Comment by Seiphon** [comment]
> 
Thank you so much! @izaera

**Comment by izaera** [comment]
@Seiphon Apparently @pat270 is your man. He knows about the CSS in the portal. Feel free to bug him :sweat_smile: 

However, if you think this may be delayed too much, just send the PR with `private: true` then you can revert it if it is proven necessary.

**Comment by Seiphon** [comment]
Thank you for all your help @izaera , then I gona send the pr with "private: true" for now since I think it will not break anything.😁

**Comment by izaera** [comment]
Perfect @Seiphon :+1:

**Pull request closed without merging**
