### PR TITLE
LPS-146034 | Verify cadmin displays default theme

### PR DESCRIPTION
**Pull request by susanchen3**
Background
Create automated tests for cadmin

Test Plan

- Add cadmin portlet 
- Assert classic background color
- Assert cadmin background color 
- Upload and apply test-theme.war
- Assert test background color
- Assert cadmin background color remains the same 

JIRA Ticket:
https://issues.liferay.com/browse/LPS-146034

### CODE REVIEW

**Comment by susanchen3** [comment]
ci:test:sf

**Comment by john-co** [comment]
Just started reviewing :)

**Comment by john-co** [comment]
ci:test:frontend:nocompile

**Comment by john-co** [comment]
ci:test:sf

**Comment by john-co** [comment]
Hi @susanchen3 , this looks awesome, good job! Please see the additional commits for modifications. I'm also sneaking in an additional commit for LPS-144477.

If the tests pass/unrelated, it's good to forward! :+1:

**Comment by john-co** [comment]
ci:test:relevant

**Review by john-co — APPROVED** [review]

**Comment by susanchen3** [comment]
ci:forward

**Pull request closed without merging**
