### PR TITLE
LPS-154539 Import `openModal` instead of using `Liferay.Util.openModal`

### PR DESCRIPTION
**Pull request by kresimir-coko**

### CODE REVIEW

**Comment by kresimir-coko** [comment]
ci:test:sf

**Comment by kresimir-coko** [comment]
ci:test:sf

**Comment by kresimir-coko** [comment]
ci:test:sf

**Review by markocikos — APPROVED** [review]
LGTM! :sparkles:

**Comment by susanchen3** [comment]
ci:test:sf

**Comment by susanchen3** [comment]
sf confuses me... :zany_face: anyways... 

The test failures are unrelated. :heavy_check_mark: Looks good to manually forward from QA perspective :)

**Comment by kresimir-coko** [comment]
ci:forward

**Review by bryceosterhaus — COMMENTED** [review]
🎉

**Comment by kresimir-coko** [comment]
ci:forward

**Comment by kresimir-coko** [comment]
Manually forwarded https://github.com/brianchandotcom/liferay-portal/pull/119572

**Pull request closed without merging**
