### PR TITLE
LPS-121920 Migrate v2 usages in trash/trash-web

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @liferay-frontend,

Attached is an update for http://issues.liferay.com/browse/LPS-121920.

@markocikos, @julien, @ambrinchaudhary 

I already sent this migration to the echo team, but with the discussion of updated changes, I have made those here as well.  Since we are not forwarding things to the Echo team, I was wondering what the best approach is to have this in sent over to them once they are free?

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by jonmak08** [comment]
ci:test:sf

**Comment by wincent** [comment]
Updated the PR title to include JIRA title but I'll leave actual review up to @markocikos, @julien, @ambrinchaudhary because they know this stuff.

**Review by ambrinchaudhary — APPROVED** [review]
LGTM!

**Comment by jonmak08** [comment]
New Pull Request: https://github.com/liferay-echo/liferay-portal/pull/3681

**Pull request closed without merging**
