### PR TITLE
LRQA-62384 Skip tests running on portal instance

### PR DESCRIPTION
**Pull request by zhangyan0701**
https://issues.liferay.com/browse/LRQA-62384

This issue also affects 7.3.x, please backport to 7.3.x, thanks!

Description:
Skip ClayAlert tests running on Portal Instance, because the SPAConfiguration that used in tests is only available in System Settings.

This is a temporary fix so that tests can keep running, we'll eventually update the tests when we get a test widgets.

/cc @john-co

### CODE REVIEW

**Comment by zhangyan0701** [comment]
ci:forward

**Comment by jbalsas** [comment]
Hey @zhangyan0701, thanks for sending this through and adding some useful information on the description!

If it was up to me, I would simply remove this for now and work on a test that does not have so many assumptions as to how and where it needs to work. The fact that we already have to patch a new test case and backport it to `7.3` should be a red flag that this might be an expensive test to maintain. I'm not sure how critical the test is, but seeing as we didn't have it before, my feeling is that we'd be better off working on a clean slate than having to maintain and patch this.

Also, doing `ci:forward` right away basically limits your chances for a test results and peer review. If you check, we've all been doing `ci:test:sf` and `ci:test:relevant` and then usually after feedback and review of the tests we execute `ci:forward`. In the odd cases one auto-forwards her own PRs, we also usually add a comment explaining why we think it's safe or necessary doing so.

Feel free to let this run its course, I'm just adding my impressions here for you to consider for future work.

Thanks!

/cc @john-co, @PablitoBonito, @manoelcyreno

**Comment by john-co** [comment]
@zhangyan0701 , @PablitoBonito , let's do peer review for test fixes to align more with the frontend guidelines.  Please cc me and each other and run `ci:test:sf` and `ci:test:relevant` to make sure those pass. If there's an urgent test fix or revert then let's comment on reason why.

@zhangyan0701 could you please reach out to our team slack channel for help on building a proper test artifact for this? https://issues.liferay.com/browse/LRQA-62432

**Comment by zhangyan0701** [comment]
> @zhangyan0701 could you please reach out to our team slack channel for help on building a proper test artifact for this? https://issues.liferay.com/browse/LRQA-62432

I will have a try, I think I need watching some on-line trainings first, I may also need some help from out team.

**Pull request closed without merging**
