### PR TITLE
LPS-128443 Run baseline task for frontend-taglib-{clay,react}

### PR DESCRIPTION
**Pull request by wincent**
We can manually forward this one, bypassing CI as [indicated here](https://github.com/brianchandotcom/liferay-portal/pull/99083#issuecomment-784231923):

> @wincent for baseline, feel free to group the PRs together and send it to me in one pull directly (bypassing CI).

For context on why these are getting missed and how we plan to fix it, see [LRQA-6534](https://issues.liferay.com/browse/LRQA-65364).

cc @john-co

### CODE REVIEW

**Comment by wincent** [comment]
Not going to overthink this; just going to manual forward like Brian said the last time.

**Comment by wincent** [comment]
ci:stop

**Comment by wincent** [comment]
Manual forward: https://github.com/brianchandotcom/liferay-portal/pull/99490

**Comment by john-co** [comment]
Reviewed. Test failures are unrelated. :heavy_check_mark: 

cc/ @vicnate5 random NPE error on upgrade test in https://github.com/liferay-frontend/liferay-portal/pull/861#issuecomment-790639045

**Comment by wincent** [comment]
Thanks @john-co.

**Pull request closed without merging**
