### PR TITLE
LPS-168538 Fix pagination accessibility in Page Iterator and Pagination Bar Tags

### PR DESCRIPTION
**Pull request by carloslancha**
Updated markup for search container pagination

Updated markup for Clay Pagination Bar

https://user-images.githubusercontent.com/5803434/219685779-41268b1e-d93c-4f6c-b800-8481fa73d1a9.mp4

### CODE REVIEW

**Comment by carloslancha** [comment]
ci:test:sf

**Comment by carloslancha** [comment]
ci:test:relevant

**Comment by carloslancha** [comment]
ci:test:sf

**Comment by carloslancha** [comment]
ci:test:relevant

**Comment by carloslancha** [comment]
Hey @john-co could you please take a look? I think we may need to update some tests. Thanks!!

**Comment by john-co** [comment]
Hi @carloslancha, I asked Flex QA to take a look at this but they weren't able to get to it today. The rest of our FI QA have Brazil holiday and will return Thursday. I'll take a quick look.

**Comment by john-co** [comment]
[Testray Comparison](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=3&testrayRunIdB=2201940040&testrayRunIdA=2201933950&statusB=2)

[Related]
- a number of tests failing to find pagination path locator Pagination#NEXT_LINK
ie: [ItemSelector#CanDisplaySitePaginationCorrectly](https://testray.liferay.com/reports/production/logs/2023-02/test-1-37/test-portal-acceptance-pullrequest(master)/9145/functional-tomcat90-mysql57-chrome100-jdk8/8/22/LocalFile.ItemSelector_CanDisplaySitePaginationCorrectly/index.html.gz?authuser=0)

Error snippet
```
Element is not present at "//ul[contains(@class,'pagination')]/li/a[contains(.,'Next')] | //ul[contains(@class,'pagination')]/li[@class='']/a/span[contains(@class,'icon-caret-right')] | //button[contains(@class, 'page-link')]//*[contains(@class,'right')]"
```

Recommend test fix on Pagination#NEXT_LINK and review Pagination#PREVIOUS_LINK

**Comment by john-co** [comment]
Pushed in a fix to your branch

**Comment by john-co** [comment]
ci:test:sf

**Comment by john-co** [comment]
ci:test:relevant

**Comment by john-co** [comment]
Trying to fix [MBPage#CanViewPagersForCategoriesAndThreads](https://testray.liferay.com/reports/production/logs/2023-02/test-1-26/test-portal-acceptance-pullrequest(master)/7865/functional-tomcat90-mysql57-chrome100-jdk8/9/15/LocalFile.MBPage_CanViewPagersForCategoriesAndThreads/index.html.gz?authuser=0) will send a test fix shortly

All other test failures are unrelated

**Comment by john-co** [comment]
ci:test:sf

**Comment by john-co** [comment]
Test should be fixed now.

Ok to manually forward from QA perspective. Pending dev approval.

**Comment by carloslancha** [comment]
Forwarded manually https://github.com/brianchandotcom/liferay-portal/pull/130699

Thx @john-co !

**Pull request closed without merging**
