### PR TITLE
[Only 7.4] - LPS-102101 - Remove compat-management_bar

### PR DESCRIPTION
**Pull request by marcoscv-work**
This PR removes the management bar compatibility CSS layer

In order to do that I've moved the CSS to the taglib and I've removed all dependencies with variables and mixins to keep it simple, this taglib is deprecated and should be replaced by the new one as soon as possible, so soon the temporal `main.scss` will not have application in portal. (it is only a fast and I hope it will be a really short -livetemporal solution before removing completely the aold management bar uses)

image

---

To test the PR:

- Create a commerce site
- Reindex search
- Go to Global menu: Commerce > Warehouses (or any other page with old management bar)

### CODE REVIEW

**Comment by jbalsas** [comment]
> Super radical and ninja management-bar CSS movement

ninja

**Comment by marcoscv-work** [comment]
ci:test:sf

**Comment by marcoscv-work** [comment]
ci:test:relevant

**Comment by marcoscv-work** [comment]
ci:test:sf

**Comment by marcoscv-work** [comment]
ci:test:relevant

**Comment by marcoscv-work** [comment]
Rebased, updated, and tested, ready to be reviewed and forwarded to Brian ;-)

**Comment by edalgrin** [comment]
Just started reviewing :)

**Review by edalgrin — APPROVED** [review]
I took a look at the commerce parts and dxp as well, everything seems fine.. so LGTM

**Comment by edalgrin** [comment]
https://github.com/liferay-frontend/liferay-portal/pull/630

**Comment by marcoscv-work** [comment]
ci:forward

**Pull request closed without merging**
