### PR TITLE
LPS-140372 Include example key value in @Schema java annotation

### PR DESCRIPTION
**Pull request by ccorreagg**
This PR contains the code to parse and include the value of the `example` field from the `rest-openapi.yaml` file into the @Schema java annotation of the Java DTOs.

---

Given a schema, for example:
```
        Attachment:
            properties:
                [...]
                cdnURL:
                    example: AB-34098-789-N
                    type: string
                displayDate:
                    example: 2017-07-21
                    format: date
                    type: string
                expirationDate:
                    example: 2017-08-21
                    format: date
                    type: string
                [...]
```

**Before the PR:**

The DTO was created without including the example values:

```
[...]
@Generated("")
@GraphQLName("Attachment")
@JsonFilter("Liferay.Vulcan")
@XmlRootElement(name = "Attachment")
public class Attachment implements Serializable {

	[...]

	@Schema
	public String getCdnURL() {
		return cdnURL;
	}

	[...]

	@Schema
	public Date getDisplayDate() {
		return displayDate;
	}

	[...]
	
	@Schema
	public Date getExpirationDate() {
		return expirationDate;
	}

	[...]
}
```

**After the PR:**

The DTO is created with the example parameter in the @Schema annotation:

```
[...]
@Generated("")
@GraphQLName("Attachment")
@JsonFilter("Liferay.Vulcan")
@XmlRootElement(name = "Attachment")
public class Attachment implements Serializable {

	[...]

	@Schema(example = "AB-34098-789-N")
	public String getCdnURL() {
		return cdnURL;
	}

	[...]

	@Schema(example = "Fri Jul 21 02:00:00 CEST 2017")
	public Date getDisplayDate() {
		return displayDate;
	}

	[...]
	
	@Schema(example = "Mon Aug 21 02:00:00 CEST 2017")
	public Date getExpirationDate() {
		return expirationDate;
	}

	[...]
}
```

### CODE REVIEW

**Comment by ccorreagg** [comment]
ci:test:sf

**Review by javierdearcos — APPROVED** [review]
Very good 🎉 

Maybe our past problems were related to the dates?

This you talk with @LuismiBarcos about this? I remember trying to solve this and find some blocker... Although I'm confident that the tests will tell us if we didn't have something into account

**Comment by ccorreagg** [comment]
> We talked about this and what I remember is that there were some problems generating some APIs with examples. But seems like @ccorreagg has solved it. Perfect! Maybe, the last thing to check and it is something the test will not tell us is if the examples are shown in the API Explorer (and ensure that the API Explore does not explode, I doubt it, but just in case 😁 )

Ok! I will test it and based on the result, I will forward or not. 

Thanks for your time and time! @javierdearcos @LuismiBarcos

**Comment by ccorreagg** [comment]
ci:forward

**Pull request closed without merging**
