### PR TITLE
LPD-21541 & LPD-21542 & LPD-21543

### PR DESCRIPTION
**Pull request by ccorreagg**
From https://github.com/liferay-frontend/liferay-portal/pull/4139

I have updated the REST Builder tests

### CODE REVIEW

**Comment by markocikos** [comment]
ci:test:relevant

**Comment by dsanz** [comment]
ci:test:echo-headless

**Comment by dsanz** [comment]
ci:test:playwright

**Comment by dsanz** [comment]
ci:test:headless-functional

**Comment by dsanz** [comment]
ci:test:echo-headless

**Comment by dsanz** [comment]
ci:test:headless-functional

**Comment by dsanz** [comment]
ci:test:relevant

**Comment by dsanz** [comment]
ci:test:stable

**Comment by dsanz** [comment]
ci:test:stable

**Comment by dsanz** [comment]
ci:test:relevant

**Comment by dsanz** [comment]
we detected what was wrong with `stable` suite. Continuing in https://github.com/liferay-frontend/liferay-portal/pull/4152

**Pull request closed without merging**
