### PR TITLE
LPS-173639 Clay Alert adds symbol attribute

### PR DESCRIPTION
**Pull request by pat270**
https://issues.liferay.com/browse/LPS-173639
https://github.com/brianchandotcom/liferay-portal/pull/129251
https://github.com/liferay/clay/pull/5291

This adds the `symbol` attribute to `clay:alert`. The attribute specifies an icon to use as an indicator. We are no longer locked into using the default icon. It was added in [Clay 3.85.0](https://github.com/liferay/clay/releases/tag/v3.85.0).

### CODE REVIEW

**Comment by pat270** [comment]
ci:test:relevant

**Review by matuzalemsteles — APPROVED** [review]
LGTM!

**Comment by eltonccdantas** [comment]
I'll take a look at it from a QA perspective

**Comment by eltonccdantas** [comment]
Hi @pat270 , I've analyzed your PR and according to the [comparison](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1675114022513&testrayRunIdA=2177044303&testrayRunIdB=2178012864), it looks safe from a QA perspective. You may manually forward if no other dev review is needed.

CC/ @john-co , @mateusralv

**Comment by pat270** [comment]
ci:forward

**Pull request closed without merging**
