### PR TITLE
LPS-126201 - Panels heading update

### PR DESCRIPTION
**Pull request by marcoscv-work**
This PR updates the markup for panel headers:

Issue:
image

Fixed (based on the original format):
image

---

How to test the PR:

- Go to Site Menu > Content & data > Documents and media
- Select a document with metadata (ex: jpg) and upload! 
- Show info bar
- Go scroll down and see the toggle header

### CODE REVIEW

**Comment by pat270** [comment]
@marcoscv-work I couldn't find official documentation on the panel component inside info-panel, but shouldn't it look like:
panel-sidebar-sheet

**Comment by boton** [comment]
Looks beautiful :D but I miss the uppercase too :(

**Comment by marcoscv-work** [comment]
> @marcoscv-work I couldn't find official documentation on the panel component inside info-panel, but shouldn't it look like:
> panel-sidebar-sheet

Oh yeah!!! I think that is the correct design but LPS-126201 was asking for a different expected result.
But yes, @pat270 you are right, better if we ask Lexicon about this. @boton do you agree if we change the style?

**Comment by boton** [comment]
Oh sorry, I create LPS-126201 with a `liferay-ce-portal-7.3.5-ga6` better check with Lexicon as you suggest

**Comment by marcoscv-work** [comment]
Finally, we decided to use the new format, so I'm closing this PR

**Comment by marcoscv-work** [comment]
https://github.com/liferay-frontend/liferay-portal/pull/728

**Pull request closed without merging**
