### PR TITLE
LPS-181351 | Automation for FDSViews#CanSearchViewByName

### PR DESCRIPTION
**Pull request by abhnerramos**
**Description**
- Given access to Datasets admin page
- And Add a Dataset
- When go to the View page of the dataset created.
- And Adding a new view called "View Test" and the description field with "Test Description"
- And Clicking Save button
- And Adding a new view called "Bob Test" and the description field with "Bob Description"
- And Clicking Save button
- And type "View Test" in the search bar and click enter
- Then the corresponding view is displayed

**JIRA Ticket**
https://issues.liferay.com/browse/LPS-181351

### CODE REVIEW

**Comment by abhnerramos** [comment]
ci:test:frontend

**Review by mateusralv — APPROVED** [review]
Cool! 🦖

**Comment by mateusralv** [comment]
Waiting for [liferay-frontend#3245](https://github.com/liferay-frontend/liferay-portal/pull/3245) be merge to forward 🚀

**Comment by mateusralv** [comment]
ci:forward

**Pull request closed without merging**
