### PR TITLE
LPD-15232 - Update frontend-data-set-view-web to ESM module

### PR DESCRIPTION
**Pull request by juanjofgliferay**
https://liferay.atlassian.net/browse/LPD-15232

### CODE REVIEW

**Review by markocikos — APPROVED** [review]
@juanjofgliferay LGTM! :sparkles:

**Comment by juanjofgliferay** [comment]
ci:forward

**Comment by juanjofgliferay** [comment]
ci:stop

**Comment by juanjofgliferay** [comment]
Manually forward to bchan https://github.com/brianchandotcom/liferay-portal/pull/146509

**Pull request closed without merging**
