### PR TITLE
LPS-155165 Add missing CET validators

### PR DESCRIPTION
**Pull request by izaera**

### CODE REVIEW

**Comment by izaera** [comment]
ci:forward

**Comment by izaera** [comment]
ci:test:sf

**Comment by izaera** [comment]
ci:test:relevant

**Comment by magjed4289** [comment]
Failures are not related. OK to manually forward ✅

**Comment by izaera** [comment]
Sent manually as https://github.com/brianchandotcom/liferay-portal/pull/118516

**Pull request closed without merging**
