### PR TITLE
LPS-140052 Fix error upgrading RemoteAppEntry table with SQL Server and Oracle

### PR DESCRIPTION
**Pull request by javierdearcos**
The PR solves the issues with the RemotaAppEntry table upgrade process for SQL Server and Oracle databases (tested with SQL Server).

I've located the error on the 2.0.0 upgrade step that was using the true literal instead of the [$TRUE$] placeholder that is replaced with a valid value for each database vendor.

I've also made changes to specify the most restrictive data types in the 2.1.0 upgrade step

**Steps to Reproduce:**

1. Start from a SQL Server dump from 7.3.10. You can use the dump attached on the [Jira LPS ticket](https://issues.liferay.com/browse/LPS-140052)
2. Run upgrade to upgrade to master

**Expected Result:**
No error on upgrade.

**Old Result:**
com.liferay.remote.app.service upgrade fails

**After changes result:**
The com.liferay.remote.app.service upgrade succeeds, although other errors appear for other modules

### CODE REVIEW

**Comment by nhpatt** [comment]
Nice :D Thank you so much (jason also thank you in today's call)

**Comment by nhpatt** [comment]
ci:forward

**Review by nhpatt — APPROVED** [review]

**Comment by john-co** [comment]
ci:test:upgrade

**Comment by john-co** [comment]
first run's failing tests don't look related.

**Comment by john-co** [comment]
Reviewed. Test failures are unrelated. :heavy_check_mark: 

- :heavy_check_mark: Passing [sqlserver test](https://testray.liferay.com/home/-/testray/case_results/1565485898?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D1565482125%26testrayRunId%3D1565485706%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc)
- :heavy_check_mark:  [oracle 19 ](https://testray.liferay.com/reports/production/logs/2021-09/test-1-29/test-portal-acceptance-pullrequest(master)/370/functional-upgrade-tomcat90-oracle193-jdk8/3/21/jenkins-console.txt.gz)fails on a different module during upgrade process

**Comment by john-co** [comment]
ci:forward

**Comment by javierdearcos** [comment]
Thank you for your support @john-co ! 😃

**Pull request closed without merging**
