### PR TITLE
LPS-188773 - Move FF for data set manager to beta and move the cell renderer client extension FF to be the same as data set manager

### PR DESCRIPTION
**Pull request by bryceosterhaus**
https://liferay.atlassian.net/browse/LPS-188590

Screenshot 2023-06-26 at 2 14 46 PM

### CODE REVIEW

**Comment by mateusralv** [comment]
I'm on it 🕵🏽

**Comment by mateusralv** [comment]
Hey @bryceosterhaus Yep! The failures are not related! 🎉 🚀 

[Testray Comparison](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1687783873128&testrayRunIdA=2361374041&testrayRunIdB=2361418395)

**Comment by dsanz** [comment]
LGTM

**Comment by markocikos** [comment]
ci:forward

**Comment by markocikos** [comment]
ci:forward:force

**Comment by markocikos** [comment]
ci:forward

**Comment by markocikos** [comment]
ci:forward

**Comment by markocikos** [comment]
ci:forward:force

**Pull request closed without merging**
