### PR TITLE
LPS-148104 Update Clay dependencies to v3.49.0

### PR DESCRIPTION
**Pull request by julien**
# [3.49.0](https://github.com/liferay/clay/compare/v3.48.0...v3.49.0) (2022-03-15)

### Bug Fixes

-   **@clayui/color-picker:** Changes to improve inconsistent behavior in some scenarios ([85adf72](https://github.com/liferay/clay/commit/85adf727784d0e5a986cabd3124df77489a2b627))
-   **@clayui/color-picker:** Current colour persist and Hue component synchronization ([07c2552](https://github.com/liferay/clay/commit/07c255200ae0213935f78af651ce5d85df030b55))
-   **@clayui/color-picker:** fixes error of adding repeated colors in custom ([e3fb905](https://github.com/liferay/clay/commit/e3fb905ead79c1217cb7d6eb0ed89ce9df725cf9))
-   **@clayui/color-picker:** fixes error when clicking on a white custom splotch does not update editor and input ([b5e0189](https://github.com/liferay/clay/commit/b5e0189115c2f9b98cbdbb444e5e4fcc8eaa4ef0))
-   **@clayui/color-picker:** Hue behaviour solved and workflow changes ([46821d7](https://github.com/liferay/clay/commit/46821d7e9fc76283e26fbbd4a7e8f08590b7efad))
-   **@clayui/color-picker:** Removing costumize hook ([20fd191](https://github.com/liferay/clay/commit/20fd1919d9acdea016bad5e56878ad3589aa111d))
-   **@clayui/core:** fix error when not rendering component after string with TreeView.Item ([1d275a8](https://github.com/liferay/clay/commit/1d275a8c948dfcfab9206a03b59c6c9d948ce29f))
-   **@clayui/css:** Forms .form-control-tag-group .label (Multiselect) remove references to deprecated keys ([39b360f](https://github.com/liferay/clay/commit/39b360f122ab0fb9a95435fac436b57b1ca6d85a)), closes [#4712](https://github.com/liferay/clay/issues/4712)

### Features

-   **@clayui/core:** adds new properties to set the initial value of properties that can be controlled ([bdfb6b0](https://github.com/liferay/clay/commit/bdfb6b063cc4cd00365609d2f7ce0f525ac16045))
-   **@clayui/drop-down:** add new prop to align Menu in viewport ([1c4f19b](https://github.com/liferay/clay/commit/1c4f19b25c34f6ffb9c2c7b9a99732e2a82d5eb5))
-   **@clayui/drop-down:** make it possible to render the menu lazily ([1e4e565](https://github.com/liferay/clay/commit/1e4e5655503645358245a200e72c8ca711f72956))

### CODE REVIEW

**Comment by susanchen3** [comment]
Taking a look :)

**Comment by susanchen3** [comment]
[Comparison against relevant ](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=2&testrayRunIdB=1635247603&testrayRunIdA=1635240780&statusB=3)
- Couple unique functional test failures, but I ran them locally and they passed :white_check_mark: 

Test failures look unrelated. I can manually forward if ci:forward fails :thumbsup:

**Review by susanchen3 — APPROVED** [review]

**Comment by susanchen3** [comment]
ci:forward

**Comment by john-co** [comment]
> Test failures look unrelated. I can manually forward if ci:forward fails +1
Thanks for the analysis @susanchen3! We can assume that `ci:test:relevant` will always fail for Clay updates and it would be better to just manually forward when we've identified tests are unrelated.

**Comment by matuzalemsteles** [comment]
cc @sandrodw3 The lazy Menu optimization is only rendered over the feature flag now, so you'll have to enable it in your use case until after we can triage the tests that were failing have been fixed to put this default behavior later.

**Comment by john-co** [comment]
To explain why it will always fail. We can expect a certain % of flaky tests. So for example if 1% tests are flaky and we run 100 tests, there will be possibly 1 test that will trip up `ci:forward`. Since we're running close to 3000 tests, even if 0.5% tests are flaky we'll get 150 tests that could possibly flake out on us.

image

**Review by john-co — APPROVED** [review]

**Comment by susanchen3** [comment]
ci:stop

**Comment by susanchen3** [comment]
Manually forwarded to bchan here: https://github.com/brianchandotcom/liferay-portal/pull/114695

**Comment by sandrodw3** [comment]
> cc @sandrodw3 The lazy Menu optimization is only rendered over the feature flag now, so you'll have to enable it in your use case until after we can triage the tests that were failing have been fixed to put this default behavior later.

Cool! Thanks @matuzalemsteles! I'll update our use case 🥰

**Comment by julien** [comment]
@susanchen3 @john-co @matuzalemsteles thanks a lot for the help on this.

**Pull request closed without merging**
