### PR TITLE
LPD-31657 - Pass fieldName to FDS Filter CX

### PR DESCRIPTION
**Pull request by bryceosterhaus**
This depends on https://github.com/liferay/liferay-frontend-projects/pull/1226

This allows for FDSFilter client extensions to know what fieldName it is attached to

### CODE REVIEW

**Comment by bryceosterhaus** [comment]
SF should pass when a new js-api is released, but waiting to release that until these changes are approved

**Review by izaera — APPROVED** [review]

**Comment by dsanz** [comment]
LGTM ;)

**Comment by bryceosterhaus** [comment]
ci:test:sf

**Comment by bryceosterhaus** [comment]
ci:test:sf

**Comment by bryceosterhaus** [comment]
ci:stop

**Comment by bryceosterhaus** [comment]
ci:test:sf

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by dsanz** [comment]
ci:reevaluate:1307401_9673

**Comment by dsanz** [comment]
none of these relevant failures are related

**Comment by dsanz** [comment]
ci:forward:force

**Pull request closed without merging**
