### PR TITLE
LPS-188817 Fix clay modal height

### PR DESCRIPTION
**Pull request by edalgrin**
This PR fixes FDS Modal architecture, it removes the extra container in the middle.

image

### CODE REVIEW

**Comment by dsanz** [comment]
ci:reevaluate:1357401_4453

**Review by dsanz — APPROVED** [review]
LGTM ;)

**Comment by mateusralv** [comment]
Hi @edalgrin the last run of the relevant did not return the report, so I will run it again :/

**Comment by mateusralv** [comment]
ci:test:relevant

**Comment by mateusralv** [comment]
Hi @edalgrin the failures are not related!

[Testray Comparison](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1692356497815&testrayRunIdA=2406989315&testrayRunIdB=2406941168)

**Pull request closed without merging**
