### PR TITLE
LPS-102117 Remove compat-layer:toolbar

### PR DESCRIPTION
**Pull request by edalgrin**
Remove compat-layer:toolbar

Since we were using the class `.toolbar` for JS functions and the I prefered to add the missing style classes and remove the compat-layer

### CODE REVIEW

**Review by jbalsas — APPROVED** [review]
> Since we were using the class .toolbar for JS functions and the I prefered to add the missing style classes and remove the compat-layer

Sounds like a reasonable approach! 👍 

LGTM!

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by edalgrin** [comment]
> Sounds like a reasonable approach! 👍
> 
> LGTM!

`ci` doesn't think the same...

**Comment by jbalsas** [comment]
> ci doesn't think the same...

The approach is reasonable, that doesn't mean it's correct 😉

**Comment by jbalsas** [comment]
CI likey!!

**Comment by jbalsas** [comment]
ci:forward

**Pull request closed without merging**
