### PR TITLE
LPS-152217: Expose ERC in WikiPageAttachment

### PR DESCRIPTION
**Pull request by sergiojimcos**
This PR contains some requested changes from -> https://github.com/brianchandotcom/liferay-portal/pull/121771#issuecomment-1218684447

**JIRA Ticket:** https://issues.liferay.com/browse/LPS-152217

cc/ @4lejandrito

### CODE REVIEW

**Comment by sergiojimcos** [comment]
ci:test:relevant

**Comment by sergiojimcos** [comment]
ci:test:relevant

**Comment by sergiojimcos** [comment]
ci:forward

**Comment by susanchen3** [comment]
Reviewed, [test failures](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=2&testrayRunIdB=1950773849&testrayRunIdA=1950612085&statusB=3) are unrelated :heavy_check_mark: Looks good to manually forward from QA perspective :) :rocket:

**Comment by sergiojimcos** [comment]
ci:forward

**Comment by sergiojimcos** [comment]
Manual forwarding to Brian: https://github.com/brianchandotcom/liferay-portal/pull/121987

**Pull request closed without merging**
