### PR TITLE
LPD-1952 Remove disableFlag property from InputLocalized

### PR DESCRIPTION
**Pull request by igor-franca**
[Related issue](https://liferay.atlassian.net/browse/LPD-1952)

### Description:
In an attempt to select the button related to the flags of the `InputLocalized` component, the application is accidentally selecting the "Applications Menu" button and blocking it.

~~This solution aims to specify the parameters passed to the query selector.~~

https://github.com/liferay-frontend/liferay-portal/assets/61854510/8877a2b0-771a-4098-98be-2c2da8555092

### CODE REVIEW

**Review by juanjofgliferay — APPROVED** [review]
LGTM

**Comment by igor-franca** [comment]
ci:test:relevant

**Comment by juanjofgliferay** [comment]
Just realize that this change will work only for the current issue but will cause unexpected behaviour when there are more than one `inputLocalized` when the `disabledFlag=true` due to the usage of `querySelector`.

**Comment by juanjofgliferay** [comment]
Can reproduce the expected problem of having two different `InputLocalized` components in the same page. One of the with `disabledFlag=false` (Label) and another with `disabledFlag=true` (Confirmation message).

As the `querySelector` over the document selects the first match, it is disabling the incorrect component (Label).

image

**Comment by juanjofgliferay** [comment]
One possible solution (dirty) could be wrapping the `InputLocalized` component and use a `React.useRef()` to get the DOM node reference and then access the current component. cc/ @markocikos 

```
	const localizedInputWrapperRef = useRef<any>();

	useEffect(() => {
		if (disableFlag) {
			(localizedInputWrapperRef.current as HTMLDivElement)
				.querySelector(
					'.input-localized button.dropdown-toggle'
				)?.setAttribute('disabled', 'true');
		}

		...
		...
	}, [disableFlag, selectedLocale]);

	return (
		<div ref={localizedInputWrapperRef}>
			<FieldBase
```
Screenshot from 2024-03-21 17-26-29

**Comment by igor-franca** [comment]
ci:stop

**Comment by igor-franca** [comment]
Hey @juanjofgliferay, thanks for noticing this gap in my solution. And for demonstrating a way to fix this. 😄  

Related to this, I opened a [question](https://liferay.slack.com/archives/C049XG98GQL/p1711039717898569) directed to the platform experience team, to answer some questions related to the disabled property of the `ClayInputLocalized` component.

**Comment by juanjofgliferay** [comment]
@igor-franca For sure, I'll discard the dirty solution I proposed and try to remove any hack or non-React approach as much as we can (`document.querySelector`).

About using the `TranslationManager`, is up to you to refactor the page and use it :smile: 

And, in order to fix the current issue we could use the `<fieldset disabled>` solution. AFAIK the `disableFlag` is always used in combination with `disabled`, to make both, input and language selector disabled, so the idea is to wrap the current `InputLocalized` component with a `fieldset` tag and set the `disabled` property to true **only** if `disabled` and `disableFlag` are true;

```
	useEffect(() => {
		// Remove disableFlag handling here

		const locale =
			availableLocales.find(({label}) => label === selectedLocale)! ??
			availableLocales[0];
		setLocale(locale);
	}, [selectedLocale]);

	return (
		// Add a wrapper to handle input & selector disabling
		<fieldset disabled={disabled && disableFlag}>
			<FieldBase
                        ......
       );
```

This way, we cover Objects use case and keep ClayLocalizedInput for the rest.

cc/ @markocikos

**Comment by igor-franca** [comment]
ci:test:sf

**Comment by igor-franca** [comment]
Hey @juanjofgliferay, thank you very much for the explanations 😄

For time reasons, I did not choose to do this refactoring now, and continued with the fieldset approach. Thank you very much for the explanation, in addition to this, some more contributions appeared in the thread, I will keep an eye out if they make any recommendations in terms of design and usability.

**Comment by igor-franca** [comment]
ci:test:sf

**Comment by igor-franca** [comment]
Hey, @juanjofgliferay . We were able to conclude in the thread that removing this `disableFlag` logic would be the best path to follow. Since only objects use this property, it does not seem to meet our usability standards.

**Review by juanjofgliferay — APPROVED** [review]
LGTM

**Comment by igor-franca** [comment]
ci:test:relevant

**Comment by igor-franca** [comment]
Hey @juanjofgliferay, I was able to analyze the results of the tests and concluded that my modifications are not related to the few tests that failed. Just confirming, can I continue as a PR? Or is there some additional step?

**Comment by juanjofgliferay** [comment]
> Hey @juanjofgliferay, I was able to analyze the results of the tests and concluded that my modifications are not related to the few tests that failed. Just confirming, can I continue as a PR? Or is there some additional step?

@igor-franca Go ahead

**Comment by igor-franca** [comment]
> @igor-franca The code in the PR LGTM!
> 
> As we are removing API, this is technically a breaking change. Please [register a breaking change in the commit](https://liferay.atlassian.net/wiki/spaces/ENGR/pages/2489483265/Process+to+register+breaking+changes+in+commits). Feel free to forward after.

Hey @dsanz just confirming, the documentation talks about the scope of this type of commit and describes phase 1 as:

>  Scope of the process
>  This process applies to any commit that breaks a Java API.
>  
>  In the first phase, we are deliberately not considering breaking changes in CSS and JS libraries.

 


I was able to verify that according to the documentation we are still in phase 1. I would just like to confirm whether we should make this change.

**Comment by igor-franca** [comment]
I modified my commit following the proposed example and I'm moving forward with the PR, thank you!

**Comment by igor-franca** [comment]
ci:forward:force

**Comment by igor-franca** [comment]
ci:forward:force

**Pull request closed without merging**
