### PR TITLE
LPS-130738 Language selector dropdown menu is empty after cloning

### PR DESCRIPTION
**Pull request by antonio-ortega**
Hey guys,

When we use localized inputs with Auto Fields we are not correctly managing the menu because we tried to keep only one menu for all the triggers, what ended up in mixing references and showing empty dropdown menus.

My solution is adding a map of `menu` <-> `trigger` so this references does not get mixed up.

Thanks.

### CODE REVIEW

**Comment by antonio-ortega** [comment]
ci:test:sf

**Comment by antonio-ortega** [comment]
ci:test:relevant

**Comment by antonio-ortega** [comment]
ci:forward

**Comment by mateusralv** [comment]
I'm taking a look 👓

**Comment by mateusralv** [comment]
Hi @antonio-ortega I found some failures related to this PR, could you take a look?

js-unit-jdk8/0/0:

```
Warning: Button Accessibility: Component has only the Icon declared. Define an `aria-label` or `aria-labelledby` attribute that labels the interactive button that screen readers can read. The `title` attribute is optional but consult your design team.
     [exec]     console.error ../../../node_modules/prop-types/checkPropTypes.js:20
     [exec]       Warning: Failed prop type: The prop `name` is marked as required in `BaseEditor`, but its value is `undefined`.
     [exec]           in BaseEditor (created by ForwardRef)
     [exec]           in ForwardRef (created by RichText)
     [exec]           in div (created by ClayInputGroupItem)
     [exec]           in ClayInputGroupItem (created by RichText)
     [exec]           in div (created by ClayInputGroup)
     [exec]           in ClayInputGroup (created by RichText)
     [exec]           in div (created by ClayFormGroup)
     [exec]           in ClayFormGroup (created by FieldBase)
     [exec]           in FieldBase (created by RichText)
     [exec]           in RichText (created by FieldLazy)
     [exec]           in FieldLazy (created by Field)
     [exec]           in Suspense (created by Field)
     [exec]           in div (created by AutoFocus)
     [exec]           in AutoFocus (created by Field)
     [exec]           in ErrorBoundary (created by Field)
     [exec]           in Field (created by FieldStateless)
     [exec]           in FieldStateless (created by FieldRight)
     [exec]           in div (created by FormGroupItem)
     [exec]           in FormGroupItem (created by FieldRight)
     [exec]           in FieldRight (created by Conditions)
     [exec]           in div (created by Panel)
     [exec]           in div (created by ClayPanelBody)
     [exec]           in ClayPanelBody (created by Panel)
     [exec]           in div (created by ClayPanel)
     [exec]           in ClayPanel (created by Panel)
     [exec]           in Panel (created by Conditions)
     [exec]           in li (created by ListItem)
     [exec]           in ListItem (created by Conditions)
     [exec]           in ul (created by List)
     [exec]           in List (created by Conditions)
     [exec]           in Conditions (created by Editor)
     [exec]           in PageProvider (created by Editor)
     [exec]           in ClayModalProvider (created by Editor)
     [exec]           in Editor
```
```
[exec]     console.error ../../../node_modules/prop-types/checkPropTypes.js:20
     [exec]       Warning: Failed prop type: You provided a `value` prop to a form field without an `onChange` handler. This will render a read-only field. If the field should be mutable use `defaultValue`. Otherwise, set either `onChange` or `readOnly`.
     [exec]           in input (created by ClayInput)
...
  [exec]     console.error ../../../../node_modules/warning/warning.js:34
     [exec]       Warning: Button Accessibility: Component has only the Icon declared. Define an `aria-label` or `aria-labelledby` attribute that labels the interactive button that screen readers can read. The `title` attribute is optional but consult your design team.
     [exec]     console.error ../../../../node_modules/prop-types/checkPropTypes.js:20
     [exec]       Warning: Failed prop type: The prop `timeSpanOptions[0].key` is marked as required in `TimeSpanSelector`, but its value is `undefined`.
     [exec]           in TimeSpanSelector (created by ReferralDetail)
     [exec]           in ReferralDetail (created by Detail)
     [exec]           in Detail
     [exec]           in ChartStateContextProvider
     [exec]           in StoreContextProvider
     [exec]     console.error ../../../../node_modules/react/cjs/react.development.js:167
     [exec]       Warning: Each child in a list should have a unique "key" prop.
     [exec]       
     [exec]       Check the render method of `TimeSpanSelector`. See https://fb.me/react-warning-keys for more information.
     [exec]           in Option (created by TimeSpanSelector)
...
  [exec] 
     [exec] > Task :dxp:apps:portal-workflow:portal-workflow-metrics-web:packageRunTest
     [exec] /opt/dev/projects/github/liferay-portal/modules/node_modules/react-dom/cjs/react-dom.development.js:302
     [exec]       var evt = document.createEvent('Event'); // Keeps track of whether the user-provided callback threw an error. We
     [exec]                          ^
     [exec] 
     [exec] TypeError: Cannot read properties of null (reading 'createEvent')
     [exec]     at Object.invokeGuardedCallbackDev (/opt/dev/projects/github/liferay-portal/modules/node_modules/react-dom/cjs/react-dom.development.js:302:26)
     [exec]     at invokeGuardedCallback (/opt/dev/projects/github/liferay-portal/modules/node_modules/react-dom/cjs/react-dom.development.js:440:31)
     [exec]     at flushPassiveEffectsImpl (/opt/dev/projects/github/liferay-portal/modules/node_modules/react-dom/cjs/react-dom.development.js:25392:7)
...
 [exec] > Task :dxp:apps:portal-workflow:portal-workflow-metrics-web:packageRunTest FAILED
     [exec] PASS test/components/instance-list-page/InstanceListPageTable.es.js
     [exec]   ??? Console
     [exec] 
     [exec]     console.error ../../../../node_modules/warning/warning.js:34
     [exec]       Warning: Button Accessibility: Component has only the Icon declared. Define an `aria-label` or `aria-labelledby` attribute that labels the interactive button that screen readers can read. The `title` attribute is optional but consult your design team.
     [exec]     console.error ../../../../node_modules/warning/warning.js:34
     [exec]       Warning: Button Accessibility: Component has only the Icon declared. Define an `aria-label` or `aria-labelledby` attribute that labels the interactive button that screen readers can read. The `title` attribute is optional but consult your design team.
     [exec]     console.error ../../../../node_modules/react-dom/cjs/react-dom.development.js:530
     [exec]       Warning: An update to Table inside a test was not wrapped in act(...).
     [exec]       
```
[Full Log ](https://testray.liferay.com/reports/production/logs/2023-08/test-1-38/test-portal-acceptance-pullrequest(master)/8752/js-unit-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

Other than these errors I found some functional tests that failed (+100) but seem to be related to those above. If you need more details about the functional tests let me know so that I do a deeper investigation
[
Testray Comparison](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1693222302967&testrayRunIdA=2412975851&testrayRunIdB=2413081179)

**Comment by mateusralv** [comment]
ci:test:relevant

**Comment by antonio-ortega** [comment]
ci:test:sf

**Comment by antonio-ortega** [comment]
ci:test:relevant

**Comment by mateusralv** [comment]
Hi @antonio-ortega , first I'm sorry for the delay in replying, while I was working on fixing the tests I discovered that the failures are related to your PR. I didn't realize it at first because the error is only shown after we edit the field.

Some examples where I found the failure always related to dropdown items and translations.

#### Adaptative and Media:

https://github.com/liferay-frontend/liferay-portal/assets/44584050/6920ca7b-f1ca-44e2-a727-c65de017af3d

#### Edit WB Structure 

https://github.com/liferay-frontend/liferay-portal/assets/44584050/58748161-5708-4ba4-987d-a623e5f8d7cf

#### Edit Form Result

https://github.com/liferay-frontend/liferay-portal/assets/44584050/25104c91-3ee0-4eba-aa34-5643543e7855

#### Edit language of a widget page

https://github.com/liferay-frontend/liferay-portal/assets/44584050/2d55bb23-a7c6-4e8f-8203-2a1fa36be331

The functional tests that failed only in this PR are listed here: 

[Testray Comparison](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=2&testrayRunIdB=2420559885&testrayRunIdA=2420487521&statusB=3)

**Comment by antonio-ortega** [comment]
ci:test:sf

**Comment by antonio-ortega** [comment]
Hey @mateusralv ,

I'm sorry for bothering you again with this, but I just sent an additional commit fixing the issues you put in your comment. 

I also run relevant tests again and I can see I've moved from 1161 to 1182 passed tests, but there are still some errors. Would you mind to check whether they are related to this pull request, please?

Thanks a lot!!

**Comment by mateusralv** [comment]
Hi @antonio-ortega, no problem, I'll take a look at it now :)

**Comment by mateusralv** [comment]
hey @antonio-ortega some tests are still failing unique in your PR, could you take a look?

#### Kaleo Forms

https://github.com/liferay-frontend/liferay-portal/assets/44584050/18433e5b-72d3-4015-940a-ec2cc61ab27f

I found the same error in Workflow:
Screenshot from 2023-09-12 17-56-08

[Testray Comparison](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1694546582168&testrayRunIdA=2420487521&testrayRunIdB=2422334092)

**Comment by antonio-ortega** [comment]
ci:test:sf

**Comment by antonio-ortega** [comment]
ci:test:relevant

**Comment by antonio-ortega** [comment]
ci:test:relevant

**Comment by mateusralv** [comment]
ci:test:relevant

**Comment by mateusralv** [comment]
Hi @antonio-ortega I analyzed the failures in the last round of the relevant and did not find any related failures 🙌🏽, but the report was not shown here, I took the results from the testray. I also downloaded the PR bundle and ran exploratory tests and also found no related failures. I will run the relevant again just to confirm these results. since (https://github.com/liferay-frontend/liferay-portal/pull/3614#issuecomment-1717354021) returned many failures.

[Testray Comparison](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1694634335166&testrayRunIdA=2423431213&testrayRunIdB=2423559940)

**Comment by mateusralv** [comment]
ci:test:relevant

**Comment by mateusralv** [comment]
Hi @antonio-ortega The failures are not related, it seems safe to forward.

[Testray Comparison](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1694689239512&testrayRunIdA=2423836741&testrayRunIdB=2423944942)

**Comment by antonio-ortega** [comment]
ci:forward:force

**Pull request closed without merging**
