### PR TITLE
LPS-117317 Unable to drag and drop an image in ckeditor

### PR DESCRIPTION
**Pull request by markocikos**
This is a bugfix, see https://issues.liferay.com/browse/LPS-117317. 

Steps to reproduce:
1. Add an image to web content.
1. Select the image, by clicking on it.
1. Drag & drop image to a different place in the editor.

Before fix:
before

After fix:
after

Notes:
- I believe this was originally a bug only on IE11, but since it has changed to be a different bug, on all browsers. What changed is now we have different dragging behavior, consistent over all browsers. In Chrome, you no longer can drag an drop by clicking anywhere on image, you need to use the handler. This caused dragged content to be HTML consisting not only of `` but also of `<span>`s containing handler icon and wrapper.
- The original bug on IE was that `pasteFilter` does not need to be defined, so one `if` would take care of it. But, the solution in this PR fixes both the original and new versions of the bug, as we are removing the check entirely.
- We added the listener on drop that checks paste filters to fix [drag & drop over different editors](https://issues.liferay.com/browse/LPS-113690). It seems that something unrelated fixed that issue, and we no longer need the check. In the 'After fix' gif, you can see drag & drop to Summary works as expected (nothing happens). @julien Is there perhaps some case that I am missing here, some reason why we would still need the filter check? Looking at [`pasteFilter` docs](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html#cfg-pasteFilter), it seems to be designed as an internal mechanism, settable through config. We shouldn't be worrying about when to trigger it manually.
- One step in steps to reproduce is to click on the image and select it. On master, if you click outside the image and d&d, we don't even enter `drop` listener. I honestly cannot explain it. Still, it becomes irrelevant if we remove the listener, one less inconsistency to worry about.

### CODE REVIEW

**Comment by markocikos** [comment]
ci:test:sf

**Comment by markocikos** [comment]
ci:test:relevant

**Comment by julien** [comment]
Hey @markocikos,

This does fix the issue, but it might need a bit more tweaking, when I added the `drop` listener it was to fix [LPS-113690](https://issues.liferay.com/browse/LPS-113690).

After deploying this change, when dragging an image from the content editor to the description editor, because the description editor is configured with a `pasteFilter`, it isn't added to the description editor, but it still "removed" from the content editor, which is what we wanted to avoid. Maybe adding the `drop` event listener to the description editor (and not all) would be enough.

**Comment by markocikos** [comment]
> This does fix the issue, but it might need a bit more tweaking, when I added the `drop` listener it was to fix [LPS-113690](https://issues.liferay.com/browse/LPS-113690).
> 
> After deploying this change, when dragging an image from the content editor to the description editor, because the description editor is configured with a `pasteFilter`, it isn't added to the description editor, but it still "removed" from the content editor, which is what we wanted to avoid. Maybe adding the `drop` event listener to the description editor (and not all) would be enough.

@julien If I am understanding this correctly, you can see that case in the 'after fix' gif: I am drag & dropping from content editor to summary editor. What I am seeing is the expected behavior, nothing happens. The image does not disappear from content editor. Is there something that I am missing from LPS-113690 steps to reproduce?

**Comment by julien** [comment]
@markocikos this is what I see after deploying the change



So in this case, dragging and dropping an image from the content editor to the summary editor removes the image from the content editor

**Comment by markocikos** [comment]
@julien Oh I see the difference. I am drag & dropping **saved** image. When image is first added, it does not have the the handler wrapper. If you publish content, you should be able to replicate what I am seeing.

**Comment by julien** [comment]
@markocikos you're right, one the article is saved I can see it working like you described 
Tell me if you want me to have a look at this.
Thanks

**Comment by markocikos** [comment]
@julien I force-pushed the fix update. It does the job of fixing the ticket bug, and it should be safe to push. But:
- I wouldn't consider this the cleanest fix. A solution to consider is to have consistent behavior on initial adding of image, where drag handler is always added. But, looking into mechanism how it's done started to drag me into ckeditor rabbit hole, and I decided to offer a quick fix first.
- Drag handler is always added in IE11, so the handler inconsistency would technically be Chrome and Firefox specific issue.
- Drag handler is added after first drag & drop, not only after save. You can see this in gif below.
- I intentionally did not port the change in this PR to [`ClassicEditor` mirror of `drop` code](https://github.com/liferay/liferay-portal/blob/master/modules/apps/frontend-editor/frontend-editor-ckeditor-web/src/main/resources/META-INF/resources/editor/ClassicEditor.js#L121-L137). This is because drag handler does not ever show in `ClassicEditor`. I actually think this behavior is better, drag handler is quite awkward to use. If out goal is to eventually replace editors with `ClassicEditor`, then it makes sense to me not to worry too much about current ckeditor handler inconsistencies and push this quick fix.

After fix:
after

**Comment by markocikos** [comment]
ci:test:sf

**Comment by markocikos** [comment]
ci:test:relevant

**Comment by julien** [comment]
@markocikos thanks for the update, change looks good to me, I tested it too and I would forward this.

**Review by julien — APPROVED** [review]

**Comment by markocikos** [comment]
All green and approved... pushing!

**Comment by markocikos** [comment]
ci:forward

**Pull request closed without merging**
