### PR TITLE
LPS-148599 Screen readers read content below modal windows

### PR DESCRIPTION
**Pull request by markocikos**
### References

- [LPS-148599 Screen readers read content below modal windows](https://issues.liferay.com/browse/LPS-148599)
- [PTR-2921 Modals incorrect behaviour. AUI & Clay](https://issues.liferay.com/browse/PTR-2921)
- Slack discussion: https://liferay.slack.com/archives/C03CAD9EF/p1646392635353689

### What is the goal of this PR?

In this PR, we are adding support for autofocus in `AssetTagsSelector` input, and enabling it in edit tag modal.

On 7.2 the solution would be different, because we are using the old `ItemSelectorDialog`. But, if we agree on the principle for solution in this PR, this is not a problem to update. If PR is green to go, we can forward this to Lima team, as the change is in their domain.

There was some discussion that we should make this a general solution, for all modals. I don't think that is the best way to go, simply because we don't know what part of the modal should be focused. Something like the first input comes to my mind, but what is first can easily be changed by CSS. I think this should be handled on case-to-case usage bases, like in this PR, and in [the sign-in modal](https://github.com/liferay/liferay-portal/blob/master/modules/apps/login/login-web/src/main/resources/META-INF/resources/login.jsp#L172), mentioned in the ticket. Clay should support setting this prop, and it already does in the case of `ClayMultiSelect`.

One thing to note in this PR: we don't want to hardcode autofocus in `AssetTagsSelector`, because it can be both in and out of modal. We are adding support for it, but only enabling it in modal.

/cc @matuzalemsteles @marcoscv-work @crodriguezy @dsanz

#### Before PR
before

#### After PR
after

### Steps to reproduce

See steps to reproduce in [LPS-148599 Screen readers read content below modal windows](https://issues.liferay.com/browse/LPS-148599)

### CODE REVIEW

**Comment by crodriguezy** [comment]
Hey @markocikos , thanks for looking into this. 

I want to mention that In LPS-148599 I just described a single example of the modals in the portal that is not working ok. But this is happening throughout the portal and the customer who reported this needs to have them all fixed. 

So I think we should develop a general solution for all of them, including the logic implemented in `Liferay.Util.openModal()` mentioned by @dsanz in https://issues.liferay.com/browse/PTR-2921, since they are also invoking this method it in custom developments.

Thank you again

**Comment by markocikos** [comment]
@matuzalemsteles Hmm I see what you mean. I guess that focusing on container provides context that there is a modal and it is open. User still needs to navigate to useful content, but it's much better then nothing. I'm curious to see the solution! And yeah, this change definitely sounds like it should be in `ClayModal`.

**Review by kresimir-coko — APPROVED** [review]
Looks simple enough, but does the job! LNHTM 👍

**Review by marcoscv-work — APPROVED** [review]

**Comment by john-co** [comment]
ci:stop

**Comment by john-co** [comment]
ci:test:relevant

**Comment by markocikos** [comment]
I'm closing this, to reduce the noise on the pulls page. We have a more comprehensive solution with https://github.com/liferay/clay/pull/4737. Changes to behavior of components, that may result in better UX, can be left to the product teams.

**Pull request closed without merging**
