### PR TITLE
LPS-168553 Update acorn version to fix vulnerability

### PR DESCRIPTION
**Pull request by edalgrin**
This PR fixes a security vulnerability due to an old version of the `acorn` dependency

`gradlew formatSource` after the change

vul2

### CODE REVIEW

**Comment by edalgrin** [comment]
TESTS:
from liferay-portal/modules
- yarn checkFormat ✅ 
- yarn format ✅ 
- yarn types ✅ 
- yarn cacheClean ✅ 
- ant all (pending)
from liferay-portal/modules/apps/frontend-js/frontend-js-web
- yarn build ✅ 
- yarn format ✅ 
- gradlew deploy ✅

**Comment by eltonccdantas** [comment]
I'll take a look at it

**Comment by eltonccdantas** [comment]
Although there are some failures, they seem to be unrelated to your pull request. You may manually forward it if no other dev review is needed.

[Comparison run](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=2&testrayRunIdB=2276839755&testrayRunIdA=2274597466&statusB=3)

[testray-results](https://github.com/liferay-frontend/liferay-portal/files/11311081/testray-results.csv)

CC/ @mateusralv

**Comment by izaera** [comment]
If CI is green and @edalgrin local tests were OK, this can be forwarded :+1:

**Comment by dsanz** [comment]
ci:forward:force

**Pull request closed without merging**
