### PR TITLE
LPS-122099 Accessibility: Navigation landmarks should describe the purpose of their links

### PR DESCRIPTION
**Pull request by antonio-ortega**
Hi guys,

Could you review this pull request, please?

We are trying to add some information to our navigation landmarks so they can describe the purpose of their links. 

This case is a more serious issue when we have more than one navigation landmark in the page (i.e., when we create a new simple theme from _unstyled_) because we'll have two navigation landmarks but we are not describing what they are for making accessibility validator to trigger an error.

In any case, even when we have only one, I think we should describe what it is for.

- `quick-access` taglib is used in our `portal_normal.ftl` templates for _unstyled_ and _Classic_ themes.
- `navigation.ftl` template is override by _Classic_ Theme avoiding using another `nav` label, but we need to consider the case of creating a new theme on top of _unstyled_ as I explained above. In this case, since we were already using an `aria-label` describing the link inside the landmark, I've just moved it up to the parent nav label.

Thanks.

Regards.

/cc @rolandpakai

### CODE REVIEW

**Comment by wincent** [comment]
cc @marcoscv-work

**Comment by marcoscv-work** [comment]
LGTM! thanks guys!

**Comment by marcoscv-work** [comment]
ci:test:sf

**Comment by marcoscv-work** [comment]
ci:test:relevant

**Comment by rolandpakai** [comment]
Hi @marcoscv-work 

could you please push this forward?

Thanks, Roland

**Comment by rolandpakai** [comment]
Hi @marcoscv-work

could you please push this forward?

cc @wincent 
cc @antonio-ortega 

Thanks, Roland

**Comment by wincent** [comment]
I'll retry `relevant`, but it's possible that this will need a rebase. Let's see... 🤞

**Comment by wincent** [comment]
ci:test:relevant

**Comment by marcoscv-work** [comment]
> Hi @marcoscv-work
> 
> could you please push this forward?
> 
> cc @wincent
> cc @antonio-ortega
> 
> Thanks, Roland

Sorry! I've been to Spain symposium in the last days! now I'm here !!!

**Comment by marcoscv-work** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by wincent** [comment]
Continued at: https://github.com/liferay-frontend/liferay-portal/pull/446

**Pull request closed without merging**
