### PR TITLE
LPS-165438 | Add Autom. test ESModule#CanRenderCustomElementAsModuleType

### PR DESCRIPTION
**Pull request by deborasoliveira**
**Test Plan**

- Given a Remote App > Custom Element with Use ES modules checked
- And Given Add created Remote App portlet to widget page
- When Navigate to remote app portlet page
- Then in the html <script> tag with src "[https://localhost:8081/runtime.js](https://localhost:8081/)" is rendered as a module type

**JIRA Ticket:**
https://issues.liferay.com/browse/LPS-165438

### CODE REVIEW

**Comment by deborasoliveira** [comment]
ci:test:sf

**Comment by deborasoliveira** [comment]
ci:test:frontend:nocompile

**Comment by john-co** [comment]
Just started reviewing :)

**Comment by john-co** [comment]
cc/ @deborasoliveira see adjustment in https://github.com/liferay-frontend/liferay-portal/pull/2839/commits/6bed695d1d3928e278e2cd0ccceae44d6876dc53

pushed to https://github.com/liferay-frontend/liferay-portal/pull/2839

**Comment by john-co** [comment]
looks good! I refactored the test using JSON and am testing to see if it works on CI.

**Pull request closed without merging**
