### PR TITLE
LPS-188028 Improve clay vertical tag

### PR DESCRIPTION
**Pull request by dsanz**
Followup pull for https://github.com/liferay-frontend/liferay-portal/pull/3475 where
* We compute `active` and `defaultExpandedKeys` props in dedicated methods, rather than while rendering
* We give priority to tag attributes vs item properties for `active` and `defaultExpandedKeys`. We do that in the getters.

Other notes:
* Decorated variant keeps failing, probably due to a clay issue. This does not prevent this pull to pass, we can work on this later on
* I left out the [grouping commit](https://github.com/liferay-frontend/liferay-portal/pull/3475/commits/218a56c2c0c7c2bb7986a00989de255f780666c1) for now as we want to merge this today

cc @markocikos @edalgrin

### CODE REVIEW

**Comment by dsanz** [comment]
@CarlosBrichete same issue cc/@markocikos

**Comment by dsanz** [comment]
ci:test:relevant

**Comment by dsanz** [comment]
last chance before a forward

**Comment by markocikos** [comment]
This error is very consistent, and just happening on this PR. It would be very scary to manually forward this. It's like something in this PR breaks CI environment.

**Comment by dsanz** [comment]
Yep that's a bit suspecting, however, the error I see in the jenkins console looks not related:

> BUILD FAILED
> /opt/dev/projects/github/liferay-jenkins-ee/commands/build-common.xml:15079: The following error occurred while executing this line:
> /opt/dev/projects/github/liferay-jenkins-ee/commands/build-common.xml:15116: The following error occurred while executing this line:
> /opt/dev/projects/github/liferay-jenkins-ee/commands/build-test-portal-acceptance-pullrequest.xml:825: The following error occurred while executing this line:
> /opt/dev/projects/github/liferay-jenkins-ee/commands/build-common.xml:5570: Sourced file: inline evaluation of: `` 				 					import com.liferay.jenkins.results.parser.BuildDatabase; 					import  . . . '' : Typed variable declaration : Method Invocation topLevelBuild.getJobSummaryDir : at Line: 22 : in file: inline evaluation of: `` 				 					import com.liferay.jenkins.results.parser.BuildDatabase; 					import  . . . '' : topLevelBuild .getJobSummaryDir ( ) 
> 
> Called from method: getJobSummaryDirPath : at Line: 44 : in file: inline evaluation of: `` 				 					import com.liferay.jenkins.results.parser.BuildDatabase; 					import  . . . '' : getJobSummaryDirPath ( ) 
> 
> Target exception: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.lang.RuntimeException: Invalid PQL: Unmatched opening boundary '('
> ((((app.server.types == null) OR (app.server.types ~ tomcat)) AND ((database.types == null) OR (database.types ~ mysql)) AND ((portal.acceptance != quarantine) AND (portal.upstream == true)) AND (portal.stable != "true")) AND ((() OR ((liferay.online.smoke == "true")) OR ((portal.stable == "true")))) AND (ignored == null) AND (test.run.environment == "EE" OR test.run.environment == null)

**Comment by dsanz** [comment]
ci:test:relevant

**Comment by dsanz** [comment]
ci:test:relevant

**Comment by dsanz** [comment]
ci:forward:force

**Comment by dsanz** [comment]
See https://github.com/liferay-frontend/liferay-portal/pull/3504 followup to solve CI relevant suite errors

**Pull request closed without merging**
