### PR TITLE
LPS-192545 - Update existing package.json for current dependencies and add eslint rule to enforce convention

### PR DESCRIPTION
**Pull request by bryceosterhaus**
update from https://github.com/liferay-frontend/liferay-portal/pull/3570

-------------------

https://liferay.atlassian.net/browse/LPS-192544

Adds an eslint rule to enforce that js dependencies are always specified in the package.json. This will help us in the
release process

### CODE REVIEW

**Comment by bryceosterhaus** [comment]
ci:test:stable

**Review by kresimir-coko — APPROVED** [review]
LNHTM 👍

**Comment by bryceosterhaus** [comment]
ci:test:sf

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/140466

**Pull request closed without merging**
