### PR TITLE
LPS-152444 Remote Apps rename remoteAppsEntryId is now clientAppsEntryId

### PR DESCRIPTION
**Pull request by Esther-OC**
Although UI for Remote Apps has not changed, there has been a change in the code where `remoteAppsEntryId` is now  `clientAppsEntryId`

The goal of this PR is fix it also in the Poshi tests, where the JSON calls are perform to create the Remote Apps, as well as change in it the endpoints, which has change as well, for instance from `/api/jsonws/remoteapp.remoteappentry/delete-remote-app-entry`  to`/api/jsonws/remoteapp.clientextensionentry/delete-client-extension-entry`

Jira issue [LPS-152444](https://issues.liferay.com/browse/LPS-152444)

### CODE REVIEW

**Comment by john-co** [comment]
ci:test:frontend:nocompile

**Comment by Esther-OC** [comment]
ci:test:frontend:nocompile

**Comment by Esther-OC** [comment]
> 

Hi, 
Yes, the failures will not be related to the PR renames, as during the research we discovered an issue [LPS-152482](https://issues.liferay.com/browse/LPS-152482) in the Applications Menu button and its id, which is the reason that the Remote Apps tests fail in their tear down function.

We are relaunching the ci:test:frontend as we have seen that this problems seems to have been solved in the last master version, so 🤞🏻

**Comment by brianchandotcom** [comment]
Merged, can close

@Esther-OC

**Pull request closed without merging**
