### PR TITLE
LPD-26899 Generate AMD export bridges

### PR DESCRIPTION
**Pull request by izaera**
Since this is AMD stuff I have not put a lot of care in cleaning the code. I've just copied what I needed from `npm-scripts` and `js-toolkit-core`.

Hopefully we will be able to remove all this AMD machinery in the mid term and if not, at least it will not change since it's completely deprecated.

### CODE REVIEW

**Comment by izaera** [comment]
The CI failures seem legitimate. Going to investigate...

**Comment by izaera** [comment]
ci:test:sf

**Comment by izaera** [comment]
ci:test:relevant

**Comment by izaera** [comment]
ci:test:relevant

**Comment by izaera** [comment]
This is green. I guess we can forward it...

**Comment by dsanz** [comment]
if tests are green, let's move forward

**Comment by izaera** [comment]
ci:forward

**Pull request closed without merging**
