### PR TITLE
[TS] LPS-138464 Create a common pattern as in SearchDisplayStyleUtil so that the chosen order column/type can be saved in the user preferences

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**
Comes from https://github.com/liferay-frontend/liferay-portal/pull/1445

### CODE REVIEW

**Comment by marianoalvarosaiz** [comment]
ci:test:sf

**Comment by marianoalvarosaiz** [comment]
ci:test:relevant

**Comment by marianoalvarosaiz** [comment]
ci:reevaluate:1217401_8372

**Review by markocikos — APPROVED** [review]
LGTM!

**Comment by markocikos** [comment]
CI failures look unrelated on first glance. I'll try forwarding, let's see if they repeat.

**Comment by markocikos** [comment]
ci:forward

**Comment by markocikos** [comment]
@marianoalvarosaiz Please fix conflict and forward. CI failures are very likely unrelated. The only repeating errors are the `WorkflowUpgrade` tests and they also show on [workflow team PR from a few days ago](https://github.com/liferay-workflow/liferay-portal/pull/609#issuecomment-967165570).

**Comment by marianoalvarosaiz** [comment]
ci:forward

**Comment by marianoalvarosaiz** [comment]
ci:test:relevant

**Comment by marianoalvarosaiz** [comment]
ci:test:relevant

**Comment by marianoalvarosaiz** [comment]
ci:forward

**Comment by marianoalvarosaiz** [comment]
ci:reevaluate:1067401_8851

**Comment by marianoalvarosaiz** [comment]
ci:test:relevant

**Comment by marianoalvarosaiz** [comment]
ci:forward

**Comment by marianoalvarosaiz** [comment]
ci:test:relevant

**Comment by marianoalvarosaiz** [comment]
ci:forward

**Comment by marianoalvarosaiz** [comment]
ci:reevaluate:1017401_6846

**Comment by markocikos** [comment]
@john-co Can we manually forward this? We are getting new exotic CI errors with each try. PR touches a lot of modules, so it may be difficult to be completely green.

**Comment by Esther-OC** [comment]
Starting review ;-)

**Comment by Esther-OC** [comment]
After reviewing it, I think we can manually move forward as the issues seem not be related to the PR or the tests (some already known issues with the batch and semantic-versioning-jdk8 and other Elasticsearch exceptions that, in my opinion, should not be related to the PR).

**Comment by markocikos** [comment]
Manual forward: https://github.com/brianchandotcom/liferay-portal/pull/110049

**Pull request closed without merging**
