### PR TITLE
LPS-172751 - Centralizes more npm dependencies to live in frontend-js-dependencies-web

### PR DESCRIPTION
**Pull request by bryceosterhaus**
https://issues.liferay.com/browse/LPS-172751

This PR does two things. First, we no longer check the dependencies of package.json's that have a sibling yarn.lock. This is to avoid checking site initializers and client extensions, which have freedom to use whatever dependencies they want. Secondly, this PR moves more npm dependencies to live in the central bundle. This should speed up build/deploy times for modules that use these dependencies

### CODE REVIEW

**Review by izaera — APPROVED** [review]
I assume the modified code is OK.

The rest (moving the deps and all that stuff) LGTM. :tada:

**Comment by mateusralv** [comment]
I'm taking a look 🕵🏽‍♂️

**Comment by mateusralv** [comment]
Hi @bryceosterhaus Only two failures are related to your PR:

1. WorkflowMetricsSLA#BlockedSLACanBeFixed:
This test is failing because of a button path change, I will send you a fix that will solve it.

2. WorkflowMetrics#ValidateWorkflowProcessListOnMetrics
This test is failing because it is not possible to open the side menu of a workflow connection when trying to edit. The step-by-step is in the video below:

PR:

https://user-images.githubusercontent.com/44584050/232581535-02711077-9050-4f61-8a3c-31f5627bccd1.mp4

Master:


https://user-images.githubusercontent.com/44584050/232581708-d18c04e2-0a74-47cc-a114-ec500054ce65.mp4

I noticed that the dotted line doesn't show in your PR when I try to connect the blocks.

[Testray Comparison](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1681731750699&testrayRunIdA=2269407286&testrayRunIdB=2270317965)

**Comment by mateusralv** [comment]
I don't have permission to add commits here so I sent a new PR adding just one commit with the test fix I mentioned above. Could you add the commit https://github.com/liferay-frontend/liferay-portal/pull/3241/commits/b1a232e4a967af7e8ee1a70b57fdb1440da15f91 here? (if the fix works 🤞🏽 )

**Comment by bryceosterhaus** [comment]
ci:test:sf

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
@mateusralv I updated the PR with your change and also fixed the issue you discovered. Let's see what the new results say.

**Comment by mateusralv** [comment]
Hi @bryceosterhaus There is only one single failure in this PR and the fix I made and tested here: https://github.com/liferay-frontend/liferay-portal/pull/3241 could you add my commit with the fix here?

After adding the commit I believe the test will pass the CI and then it seems safe to forward 😄 

[Testray comparison
](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=2&testrayRunIdB=2278651164&testrayRunIdA=2278559846&statusB=3)

**Comment by bryceosterhaus** [comment]
ci:test:sf

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
ci:stop

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
ci:test:sf

**Comment by bryceosterhaus** [comment]
@mateusralv I thought I had originally included your fix in that last run, but I will try it again

**Comment by mateusralv** [comment]
I'm taking a look 🕵🏽

**Comment by mateusralv** [comment]
Hi @bryceosterhaus I noticed that the test is still breaking, but in another part after the fix I sent, unfortunately I could not complete the analysis today because I am having DB problems, tomorrow as soon as possible I will post the results here. :/

**Comment by mateusralv** [comment]
Hi @bryceosterhaus I tested locally and the test is passing. I ran the CI again on the PR I made to confirm.

**Comment by mateusralv** [comment]
Hi Bryce it seems that with your changes you fixed the test, I tested without my fix and the test passed(https://github.com/liferay-frontend/liferay-portal/pull/3241#issuecomment-1526539181)  This run only returned one failure and I tested it locally and it is passing, so it looks flaky.

So, is it safe to forward without my commit. could you remove it?
[
Testray comparison](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=2&testrayRunIdB=2283283625&testrayRunIdA=2282859116&statusB=3)

**Comment by bryceosterhaus** [comment]
forwarded at https://github.com/brianchandotcom/liferay-portal/pull/134103

**Pull request closed without merging**
