### PR TITLE
LPS-141789 Hide quick links on mobile to avoid chrome/safari bug

### PR DESCRIPTION
**Pull request by tinycarol**
### References

- [LPS-141789](https://issues.liferay.com/browse/LPS-141789)
- [PTR-2692](https://issues.liferay.com/browse/PTR-2692)

### What is the goal?

* Hide quick links on mobile/tablet browsers to circumvent [this Chromium bug](https://bugs.chromium.org/p/chromium/issues/detail?id=657157) and an equivalent bug in Safari mobile versions.
   * To summarize, hidden links that display when focused don't work on mobile browsers when using a screen reader because the element grabs the accessibility focus, but not the DOM focus. Thus, the element doesn't get the `:focus/:active` pseudo-class and the styles that make it visible aren't applied. 
   * There's no way to detect the accessibility focus, so we cannot use JS to add/remove styles or classes.
   * Only fix is to not display these elements at all.

### A picture is worth a thousand words

**🔉 These videos have sound, hope you enjoy them as much as I did while working on this 🔉**

#### Before PR

The skip link grabs a11y focus and skips to content when clicked, but it's not visible.

##### Chrome in Android with Talkback enabled:

https://user-images.githubusercontent.com/6642927/143059565-c95f7c9d-c2ae-44e7-b642-8646c59fee42.mp4

##### Safari in iOS/iPadOS with Voiceover enabled:

https://user-images.githubusercontent.com/6642927/143061332-faf80a9a-54aa-4dd2-be46-94e515fbb1e2.MP4

#### After PR
The skip link doesn't grab focus.

##### Chrome in Android with Talkback enabled:

https://user-images.githubusercontent.com/6642927/143059576-193ba906-db85-46ec-8108-4f20e4ed4d88.mp4

##### Safari in iOS/iPadOS with Voiceover enabled:

https://user-images.githubusercontent.com/6642927/143061375-f2ca2dfe-b7f8-4043-bbd1-e11b80105ead.MP4

### How to replicate
* Connect your phone/tablet to the same wifi network as your computer
* Enable Talkback/Voiceover in your mobile device
* Somehow open Chrome/Safari in your mobile device and access DXP using your computer's private IP
* Move around the screen by swiping right/left, see that if you swipe right from the search bar focus isn't suddenly invisible and you don't hear "Skip to content".
* Do the same from your computer, see that the "Skip to content" button is visible and you can click it.

### Checklist

- ~~[ ] I have made corresponding changes to the documentation~~
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have checked this works in the corresponding browser

### Notes
Thanks to this bug I found out that the "Skip to content" link doesn't work on Firefox Desktop.

### CODE REVIEW

**Comment by tinycarol** [comment]
@liferay-continuous-integration go home, you're drunk

**Review by edalgrin — APPROVED** [review]
This seems the only available solution at the moment, so I guess it's ok.

We should consider to apply this rule to the [`.sr-only-focusable`](https://github.com/liferay/clay/blob/master/packages/clay-css/src/scss/components/_utilities-functional-important.scss#L453) class at least until the browsers are ready to support it.

/cc @pat270

**Comment by tinycarol** [comment]
ci:test:relevant

**Comment by carloslancha** [comment]
ci:forward

**Comment by pat270** [comment]
@edalgrin @tinycarol 

I don't think we can add this to `sr-only-focusable`. This seems more device dependent than screen size. This will break implementations for screen sizes smaller than xl.

On a side note, I took a quick look at the markup and think that adding `tabindex="0" role="button"` on the anchor tag might force the browser to add the focus pseudo class.

**Comment by edalgrin** [comment]
Sorry! I meant add it for `xs` devices, since it's "phone" issue

About the the markup I tried different solutions but none seems to be working (at least in my phone) 😞 

https://codepen.io/eduardoallegrini/pen/wvqLMmy?editors=1100

**Comment by pat270** [comment]
It's not working because there is an issue with `sr-only sr-only-focusable`. It uses the [clip](https://developer.mozilla.org/en-US/docs/Web/CSS/clip) property which only applies to position absolute and fixed. `sr-only-focusable` changes it to `position: static` and for some reason iOS Safari bugs out, not sure if this is the same issue with Android talkback.

If you remove `position: static` from `sr-only-focusable` + `role="button" tabindex="0"` it shows on iOS Safari + Voiceover.

**Comment by edalgrin** [comment]
I've updated the [codepen](https://codepen.io/eduardoallegrini/pen/wvqLMmy?editors=1100) with your solution but it's still not working on talkback

In any case it seems a little too much for a browser bug/fix, I would prefer to leave it as it is for now

**Pull request closed without merging**
