### PR TITLE
LPS-132752 clay:label tag should allow for literal values

### PR DESCRIPTION
**Pull request by adolfopa**
See https://issues.liferay.com/browse/LPS-132752 for reproduction steps.

The issue is that the clay:label tag tries to translate the label as if it was a lang key. This makes it impossible to display a literal value that happens to have a key with the same name.

To keep backwards compatibility, this adds a new attribute to tell the tag that the label should not be translated, but displayed as is.

Thanks!

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Review by julien — APPROVED** [review]

**Comment by julien** [comment]
@adolfopa does this mean we need to run gradlew baseline?

**Review by diegonvs — APPROVED** [review]
LGTM! :)

**Comment by julien** [comment]
Hey @adolfopa, did you have a chance to look at the test results?

**Comment by adolfopa** [comment]
Rebased, added semver commit and push-forced. No changes to the original commit.

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Review by kresimir-coko — APPROVED** [review]
Interesting, you added a `translateLabel` prop and if it's `false` then it won't translate the `label` provided. Cool, clean solution 👍

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by diegonvs** [comment]
Hey @adolfopa, this PR needed to be rebased to see the new results of the CI and I [created another PR](https://github.com/liferay-frontend/liferay-portal/pull/1171) to see it and then forward if the CI pass.

**Comment by adolfopa** [comment]
Closing in favor of https://github.com/liferay-frontend/liferay-portal/pull/1171

**Pull request closed without merging**
