### PR TITLE
LPS-168102 Update packages @clayui/* to v3.80.0

### PR DESCRIPTION
**Pull request by matuzalemsteles**
### Bug Fixes

-   **@clayui/date-picker:** Map id attribute to .form-control ([b53a81a](https://github.com/liferay/clay/commit/b53a81a98defdb248d5ad86739e766efc88e4dec))
-   **@clayui/drop-down:** adds keyboard navigation with looped arrow keys ([c919b22](https://github.com/liferay/clay/commit/c919b226a1f38750042856157f1b45f76306461c))
-   **@clayui/drop-down:** associates the contextual item with the menu and fixes assertive aria for SRs with contextual menu ([b62b7ba](https://github.com/liferay/clay/commit/b62b7ba93f4f566363a8c7666743594956625f35))
-   **@clayui/drop-down:** disable tabbing of Menu elements ([81c0b20](https://github.com/liferay/clay/commit/81c0b20452008e15f8c0184cdd1318bad7cab488))
-   **@clayui/drop-down:** fix keyboard navigation for context menu ([b44c7db](https://github.com/liferay/clay/commit/b44c7db37a53720860b832f12119d40f377a438b))
-   **@clayui/tooltip:** persist the title attribute when navigate via keyboard ([44fe7c4](https://github.com/liferay/clay/commit/44fe7c4113a0889a109f3d71435800468b9ab94a))

### Features

-   **@clayui/date-picker:** improves semantic accessibility for the component ([60a7f76](https://github.com/liferay/clay/commit/60a7f7616563faa15817b4daa3525bd842260ef3))
-   **@clayui/drop-down:** enable typeahead for menu ([6287f96](https://github.com/liferay/clay/commit/6287f9635e7deeb3973b42f8db4ca62ef7bed7d3))
-   **@clayui/shared:** Add typeahead function to list ([ce1347f](https://github.com/liferay/clay/commit/ce1347fa8dcaa90d2d09e507c357ba834468b75b))
-   **@clayui/time-picker:** Add id prop that sets id on `clay-time-hours` ([63a151b](https://github.com/liferay/clay/commit/63a151bb5168f776caf6bd22ac8edf1c207945e4))

### CODE REVIEW

**Comment by matuzalemsteles** [comment]
cc @mateusralv

**Comment by mateusralv** [comment]
I’m taking a lookj 🕵🏽

**Comment by mateusralv** [comment]
Hi @matuzalemsteles I analyzed the failures and one might be related:
1. The [com.liferay.portal.workflow.metrics.rest.resource.v1_0.test.NodeMetricRe...](https://testray.liferay.com/home/-/testray/case_results/2069239754) test has a unique failure in this PR, ran locally and failed, could you take a look?

2. [LocalFile.CollectionFilter#EnableSearchFieldInDropdownList](https://testray.liferay.com/home/-/testray/case_results/2069224702) test fails when I run the test, but when I play it manually it works so I think of a test fix to forward in this PR.


https://user-images.githubusercontent.com/44584050/203395012-f622c879-fd55-412f-8560-ca1a1bdc2896.mp4


The other failures are not unique.
[comparison run](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1669121565073&testrayRunIdA=2070187202&testrayRunIdB=2069223837)

**Comment by mateusralv** [comment]
ci:test:relevant

**Comment by matuzalemsteles** [comment]
ci:stop

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by mateusralv** [comment]
The failures are not unique. Safe to forward. Thanks @matuzalemsteles 😄 

[comparison run](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1669207274731&testrayRunIdA=2071633178&testrayRunIdB=2071884709)

**Comment by mateusralv** [comment]
forwarded to bchan: https://github.com/brianchandotcom/liferay-portal/pull/126740 🚀

**Pull request closed without merging**
