### PR TITLE
LPS-136645 Avoid ArrayIndexOutOfBoundsException in headless api if you sort using a non-localizable DDM field

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
https://issues.liferay.com/browse/LPS-136645

Change the way we parse the ddmStructureField String:
 - We can have DDM fields without locale. 
 - The locale can also have different number of underscores (en, en_US or sr_RS_latin) so instead of spliting by underscore character, we will do it in a more robust way

This problem has been also addressed in the Custom facet widget, see https://issues.liferay.com/browse/LPS-136137 and https://github.com/liferay-search/liferay-portal/pull/182

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
@javierdearcos

**Comment by nhpatt** [comment]
Thank you so much ❤️ 

LGTM, merging.

**Comment by nhpatt** [comment]
ci:forward

**Review by nhpatt — APPROVED** [review]

**Comment by nhpatt** [comment]
Some failures look unrelated but one is a baseline issue complaining about:

```
  public String getLocaleSuffix() {
```

Does it have to be public? does not seem so... but if it does, baseline, if not change to private and _ naming convention.

We can do it but without permissions to your repo we would have to close and resend, as you wish :)

**Comment by jorgediaz-lr** [comment]
Hi @nhpatt 

I have changed the getLocaleSuffix() to private to avoid modifying the semver, see additional commit [`179d2d0` (#1309)](https://github.com/liferay-frontend/liferay-portal/pull/1309/commits/179d2d0077bbdcf94474b0cbbe0272b3482ca4bb)

**Comment by jorgediaz-lr** [comment]
ci:forward

**Pull request closed without merging**
