### PR TITLE
LPS-168440 - Remove non-locale instances of moment.js

### PR DESCRIPTION
**Pull request by bryceosterhaus**
This removes non-locale dependent instances of moment.js to date-fns

https://issues.liferay.com/browse/LPS-168440

Further work for entire moment.js removal will be figured out in https://issues.liferay.com/browse/LPS-172751

### CODE REVIEW

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by eltonccdantas** [comment]
I'll take a look at it

**Comment by mateusralv** [comment]
Hi @bryceosterhaus I found some failures related:

[Testray comparison](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=2&testrayRunIdB=2174482657&testrayRunIdA=2174348318&statusB=3)

### Workflow metrics failures:

https://user-images.githubusercontent.com/44584050/215216628-af04e5ca-2ddd-4d88-9501-d0431b5a2f8d.mp4

---
### Segmentation Failures:

https://user-images.githubusercontent.com/44584050/215216678-e31e814b-fc15-44cb-84be-4341e06c7ea6.mp4

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
@mateusralv updated and ran tests again, let me know if anything unique

**Comment by mateusralv** [comment]
I'm taking a look 👓

**Comment by eltonccdantas** [comment]
Hi @bryceosterhaus , after further investigation, @mateusralv and I found where the error is. After adding 1 and clicking "save", it turns into a 10, and when I tried updating it returns an error 500.


https://user-images.githubusercontent.com/63858122/216708049-63b75e22-1243-42c0-9eec-1a88d88d3435.mp4

[Testray comparison run](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=2&testrayRunIdB=2182859325&testrayRunIdA=2183417229&statusB=3)


CC/ @john-co

**Comment by bryceosterhaus** [comment]
ci:test:sf

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
ci:test:sf

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by dsanz** [comment]
Hi @eltonccdantas could you please check latest test results and let us know about anything unique to this pull?
Thank you

**Comment by mateusralv** [comment]
I'm on it 🕵🏽

**Comment by bryceosterhaus** [comment]
ci:test:sf

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
@mateusralv let me know if the most recent run satisfies that recent failure

**Comment by mateusralv** [comment]
I'm here again 🕵🏽

**Comment by mateusralv** [comment]
Hi @bryceosterhaus I took a look at the failures and I think is not related, when I run locally the test passed, but on CI is failing... so I'll run ci:test:relevant again and as soon as I'll take a look again.

[Testray comparison ](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=2&testrayRunIdB=2190991465&testrayRunIdA=2190928720&statusB=3)

related test:
WebContentSmokeTests#ViewAndDeleteContentWithTitleAndAllFields

**Comment by mateusralv** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
ci:test:sf

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by mateusralv** [comment]
Hi @bryceosterhaus I took a look at the last result (https://github.com/liferay-frontend/liferay-portal/pull/3001#issuecomment-1425026447 )and has no failure related to your PR.

[Testray Comparison](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=2&testrayRunIdB=2191887694&testrayRunIdA=2190426385&statusB=3)

As soon as the new results of the relevant I take another look, I believe it will be faster 🙌🏽

**Comment by mateusralv** [comment]
i'm take a look again 🕵🏽

**Comment by bryceosterhaus** [comment]
manual forward https://github.com/brianchandotcom/liferay-portal/pull/130149

**Pull request closed without merging**
