### PR TITLE
LPS-159037 Expose binary content in the REST builder auto-generated client to use it for binary contents (as a zip folder)

### PR DESCRIPTION
**Pull request by ccorreagg**
There are some endpoints that returns binary content (application/octet-stream), as for example, the following one:

```
curl -X GET \
      'http://localhost:8080/o/headless-batch-engine/v1.0/import-task/1/content' \
      -u 'test@liferay.com:test' \
      --output myfile.zip
```
The response of that requests is the content of a ZIP file.

Currently, REST Builder is generating a client within the `<module-name>-client` module, with the following class `HttpResponse`:

```
public class HttpResponse {

	public String getContent() {
		return _content;
	}

	public String getMessage() {
		return _message;
	}

	public int getStatusCode() {
		return _statusCode;
	}

	[...]
}
```
As the content of the body is being parsed as a String, in the case where the body contains binary characters, they are being parsed as a String with certain encoding. That makes that parsing it back produces different binary characters from the original ones.

To provide a way to get the binary content, a new method has been created and the parsing process has been modified to keep the binary content unaltered:

```
public class HttpResponse {

	public byte[] getBinaryContent() {
		return _binaryContent;
	}

	public String getContent() {
		return _content;
	}

	[...]
}
```
That method might be used to get the binary content body returned. See the following example for the same endpoint:

```
ImportTaskResource.Builder builder = ImportTaskResource.builder();

importTaskResource = builder.authentication(
	"test@liferay.com", "test"
).locale(
	LocaleUtil.getDefault()
).build();

HttpInvoker.HttpResponse httpResponse =
	importTaskResource.getImportTaskContentHttpResponse(1L);

FileOutputStream fileOutputStream = new FileOutputStream("myfile.zip");

fileOutputStream.write(httpResponse.getBinaryContent());
fileOutputStream.flush();
fileOutputStream.close();
```

### CODE REVIEW

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
ci:test:relevant

**Review by javierdearcos — APPROVED** [review]
Nice 👏 

A minor version change is not needed for every client module? Maybe we need to execute baseline to check it

**Comment by ccorreagg** [comment]
> Nice clap
> 
> A minor version change is not needed for every client module? Maybe we need to execute baseline to check it

I think the baseline is executed together with buildREST command as I don't remember to execute it after buildREST and nobody complained :rofl: 

Anyway, I have executed it and there are no changes :smiley:

**Comment by ccorreagg** [comment]
ci:forward

**Comment by ccorreagg** [comment]
ci:forward

**Comment by ccorreagg** [comment]
ci:reevaluate:1257401_3857

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by yanan** [comment]
I think the failed tests are unrelated to the current pr.

[Comparison run:](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=3&testrayRunIdB=1933508265&testrayRunIdA=1933279683&statusB=2)
- LocalFile.LocalizedNestedFieldsWebContent#TranslationsRemainsUponSavingWebContent 
- com.liferay.object.service.test.ObjectLayoutLocalServiceTest -> testAddObjectLayout(ObjectFieldNameException$MustNotBeDuplicate: Duplicate name xmwe)

Haven't finished downloading the test bundle on my side, but the failed tests also occur in other builds when looking into tests history, so I think it looks good to manually forward from QA perspective.

**Comment by ccorreagg** [comment]
Thanks @yanan !

**Comment by yanan** [comment]
I think the failed tests are unrelated to the current pr.

[Comparison run:](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=3&testrayRunIdB=1933508265&testrayRunIdA=1933279683&statusB=2)
- LocalFile.LocalizedNestedFieldsWebContent#TranslationsRemainsUponSavingWebContent 
- com.liferay.object.service.test.ObjectLayoutLocalServiceTest -> testAddObjectLayout(ObjectFieldNameException$MustNotBeDuplicate: Duplicate name xmwe)

Haven't finished downloading the test bundle on my side, but the failed tests also occur in other builds when looking into tests history, so I think it looks good to manually forward from QA perspective.

**Comment by yanan** [comment]
I think the failed tests are unrelated to the current pr.

[Comparison run:](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=3&testrayRunIdB=1933508265&testrayRunIdA=1933279683&statusB=2)
- LocalFile.LocalizedNestedFieldsWebContent#TranslationsRemainsUponSavingWebContent 
- com.liferay.object.service.test.ObjectLayoutLocalServiceTest -> testAddObjectLayout(ObjectFieldNameException$MustNotBeDuplicate: Duplicate name xmwe)

Haven't finished downloading the test bundle on my side, but the failed tests also occur in other builds when looking into tests history, so I think it looks good to manually forward from QA perspective.

**Comment by yanan** [comment]
I think the failed tests are unrelated to the current pr.

[Comparison run:](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=3&testrayRunIdB=1933508265&testrayRunIdA=1933279683&statusB=2)
- LocalFile.LocalizedNestedFieldsWebContent#TranslationsRemainsUponSavingWebContent 
- com.liferay.object.service.test.ObjectLayoutLocalServiceTest -> testAddObjectLayout(ObjectFieldNameException$MustNotBeDuplicate: Duplicate name xmwe)

Haven't finished downloading the test bundle on my side, but the failed tests also occur in other builds when looking into tests history, so I think it looks good to manually forward from QA perspective.

**Comment by yanan** [comment]
I think the failed tests are unrelated to the current pr.

[Comparison run:](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=3&testrayRunIdB=1933508265&testrayRunIdA=1933279683&statusB=2)
- LocalFile.LocalizedNestedFieldsWebContent#TranslationsRemainsUponSavingWebContent 
- com.liferay.object.service.test.ObjectLayoutLocalServiceTest -> testAddObjectLayout(ObjectFieldNameException$MustNotBeDuplicate: Duplicate name xmwe)

Haven't finished downloading the test bundle on my side, but the failed tests also occur in other builds when looking into tests history, so I think it looks good to manually forward from QA perspective.

**Comment by yanan** [comment]
I think the failed tests are unrelated to the current pr.

[Comparison run:](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=3&testrayRunIdB=1933508265&testrayRunIdA=1933279683&statusB=2)
- LocalFile.LocalizedNestedFieldsWebContent#TranslationsRemainsUponSavingWebContent 
- com.liferay.object.service.test.ObjectLayoutLocalServiceTest -> testAddObjectLayout(ObjectFieldNameException$MustNotBeDuplicate: Duplicate name xmwe)

Haven't finished downloading the test bundle on my side, but the failed tests also occur in other builds when looking into tests history, so I think it looks good to manually forward from QA perspective.

**Comment by yanan** [comment]
I think the failed tests are unrelated to the current pr.

[Comparison run:](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=3&testrayRunIdB=1933508265&testrayRunIdA=1933279683&statusB=2)
- LocalFile.LocalizedNestedFieldsWebContent#TranslationsRemainsUponSavingWebContent 
- com.liferay.object.service.test.ObjectLayoutLocalServiceTest -> testAddObjectLayout(ObjectFieldNameException$MustNotBeDuplicate: Duplicate name xmwe)

Haven't finished downloading the test bundle on my side, but the failed tests also occur in other builds when looking into tests history, so I think it looks good to manually forward from QA perspective.

**Comment by yanan** [comment]
I think the failed tests are unrelated to the current pr.

[Comparison run:](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=3&testrayRunIdB=1933508265&testrayRunIdA=1933279683&statusB=2)
- LocalFile.LocalizedNestedFieldsWebContent#TranslationsRemainsUponSavingWebContent 
- com.liferay.object.service.test.ObjectLayoutLocalServiceTest -> testAddObjectLayout(ObjectFieldNameException$MustNotBeDuplicate: Duplicate name xmwe)

Haven't finished downloading the test bundle on my side, but the failed tests also occur in other builds when looking into tests history, so I think it looks good to manually forward from QA perspective.

**Comment by ccorreagg** [comment]
PR forwarded manually: https://github.com/brianchandotcom/liferay-portal/pull/121116

Closing PR...

**Pull request closed without merging**
