### PR TITLE
LPS-114480 Only sending p_auth if present

### PR DESCRIPTION
**Pull request by 4lejandrito**
From https://github.com/liferay-frontend/liferay-portal/pull/369/commits/30882850f748cb50e41976d0a2bed81430a64334:

When a form's URL does not contain the p_auth parameter (like the download portlet resource URL from the ticket)
the old code was including the p_auth input with an empty value.

Since a download URL does not trigger a page refresh, the empty value is
kept and causes subsequent action requests to fail with a 403.

The original resource request does not fail because resource requests
do not check p_auth.

### CODE REVIEW

**Comment by wincent** [comment]
@4lejandrito Would you mind providing a description so that we know what we're looking at here? (We try to make a point of [always providing useful descriptions](https://github.com/liferay/liferay-frontend-guidelines/blob/master/general/pull_requests.md#write-useful-descriptions-and-titles)).

**Comment by jbalsas** [comment]
ci:test

**Comment by jbalsas** [comment]
ci:relevant

**Comment by jbalsas** [comment]
Hey @4lejandrito, thanks for the explanation! I think that covered most of my concerns about this.

The change still makes me a bit nervous... I wonder if there are things that might be working now depending on this wrong behaviour... let's see how tests look like and forward if green since this seems reasonable.

**Comment by jbalsas** [comment]
ci:test:sf

**Comment by jbalsas** [comment]
> ❌ ci:test:default - 333 out of 343 jobs passed in 3 hours 8 minutes

Looks good enough 😂

**Comment by jbalsas** [comment]
ci:forward

**Pull request closed without merging**
