### PR TITLE
LPS-142823 Update Remote App testcase with new Custom Element URL

### PR DESCRIPTION
**Pull request by sergiojimcos**
**What's new?**
Update Custom Element URL in RemoteApps.testcase. It includes the new one: `https://liferay.github.io/liferay-frontend-projects/vanilla-counter/index.js`.

**Change in:**
- CustomElementCanBeCreated.
- CustomElementCanBeEdited.
- CustomElementCanBeDeleted.
- CustomElementCanBeDisplayedByPortlet.
- CustomElementCanBeInstanceable.
- CustomElementCanBeConfigureByPortletName.

**JIRA Ticket:** https://issues.liferay.com/browse/LPS-142823

### CODE REVIEW

**Comment by john-co** [comment]
Hi @sergiojimcos , can you add me as collaborator to your repo? That way I can push in changes for you.

**Review by john-co — APPROVED** [review]
Also remove any traces of wincent in our URLs. 
ie: http://remote-component-test.wincent.com/index.css needs to be updated to https://liferay.github.io/liferay-frontend-projects/index.css

After this change, ok to forward.

**Comment by sergiojimcos** [comment]
> Hi @sergiojimcos , can you add me as collaborator to your repo? That way I can push in changes for you.

Yes sure, no problem for me 👍

**Comment by sergiojimcos** [comment]
ci:forward

**Pull request closed without merging**
