### PR TITLE
LPS-154649 Add test CanReturnToPreviousStepIfElementDoesNotExist

### PR DESCRIPTION
**Pull request by susanchen3**
**Background**
Create automated tests for Walkthrough component. 
Renamed test to CanReturnToPreviousStepIfElementDoesNotExist because no error message is displayed. 

**Test Plan**
Given: JSON file includes an element that does not exist on the page/sample portlet
And Given: frontend-js-components-sample-web deployed to test page
And Given: Navigate to Test Walkable tab on sample portlet
When: popover mode transitions to the step that has no element
Then: ~error message is displayed~ hotspot returns to last element

**JIRA Ticket:**
https://issues.liferay.com/browse/LPS-154649

### CODE REVIEW

**Comment by susanchen3** [comment]
ci:test:frontend

**Comment by john-co** [comment]
Just started reviewing :)

**Review by john-co — APPROVED** [review]
Great job, looks good to me! :sunglasses:

**Comment by john-co** [comment]
ci:forward

**Comment by john-co** [comment]
ci:forward

**Comment by john-co** [comment]
:confused: :question:

**Comment by john-co** [comment]
ci:test:sf

**Comment by susanchen3** [comment]
ci kinda broken :woozy_face:

**Comment by john-co** [comment]
Manually forwarded to https://github.com/brianchandotcom/liferay-portal/pull/119155

**Comment by john-co** [comment]
ci:stop

**Pull request closed without merging**
