### PR TITLE
Commerce 4757 add sorting capabilities to data-set-display

### PR DESCRIPTION
**Pull request by luca-pellizzon**
cc @marco-leo @FabioDiegoMastrorilli

Currently data-set-display component is missing a complete implementation regarding sorting.
The component itself already has part of this feature managed by the "sorting" parameter, but the underneath infrastructure is not ready.

This PR is solving this issue by implementing what's needed to give to the data-set-display component the parameter to manage sorting.
The taglib has been integrated, adding the "sortItemList". A list containing all the sorting properties we want to manage.
In order to do so, the tld has been updated and some utilities have been added, like SortItemList.
Everything has been done following the patterns already used inside Liferay.

This implementation is coming from a request regarding adding a default sorting (creation date) for the Commerce Orders list.

That said to test this functionality, checking the default behavior of Orders list is enough.
To test the full capabilities, adding the sort property to any data-set-display should do the job.

### CODE REVIEW

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
Hi @luca-pellizzon, good to see you contributing here with us for the first time!!

In order to improve our review workflow, we ask that you help us out by following some these recomendations:
- [Frontend Infrastructure Team code review process](https://github.com/liferay/liferay-frontend-guidelines/blob/master/dxp/code_review.md)
- [Pull Request Etiquette](https://github.com/liferay/liferay-frontend-guidelines/blob/master/general/pull_requests.md)

Most importantly:
- Provide a meaningful PR title (✔️)
- Provide a meaningful PR description (✖️)
    - Describe the observed problem
    - Add a technical explanation of the issue
    - Describe the solution and why it's the right one
    - Comment any technical considerations, things you tried, cases you considered...
- Include a test plan (✖️)

While some of these might seem redundant and the information might be in the LPS, writing all that down here helps us focus on the review and track everything better through the workflow, so we really appreciate you taking the time to make this easier for us 🤗 

Please, reach out to @FabioDiegoMastrorilli or @gianmarcobrunialti if you need some clarification or let us know here so we can move this forward!

**Comment by luca-pellizzon** [comment]
Thank you @jbalsas for your reply, I added a description to the first comment of the PR.
Hope it is enough to understand what this PR is about.

**Comment by jbalsas** [comment]
ci:test:sf

**Comment by jbalsas** [comment]
@izaera, could you take a look at the java bits?

**Review by izaera — APPROVED** [review]

**Comment by izaera** [comment]
ci:forward

**Pull request closed without merging**
