### PR TITLE
LPS-178779 | Automation for FrontendDataSetViews#CannotExceed280Characters

### PR DESCRIPTION
**Pull request by abhnerramos**
**Description**
Confirm the error message that appears when the user tries to create a dataset view with more than 280 characters in the name field.

**Steps**
- Given access Datasets admin page
- When The user goes to add Datasets
- When a user types a name that is more than 280 characters
- And choose the provider named Channel
- And clicking on the Save button
- Then Confirm that alert messages are present 

**JIRA Ticket**
https://issues.liferay.com/browse/LPS-178779

### CODE REVIEW

**Comment by abhnerramos** [comment]
ci:test:frontend

**Comment by abhnerramos** [comment]
ci:test:frontend

**Comment by abhnerramos** [comment]
ci:test:sf

**Comment by abhnerramos** [comment]
ci:test:sf

**Comment by abhnerramos** [comment]
ci:test:frontend

**Review by deborasoliveira — APPROVED** [review]

**Comment by mateusralv** [comment]
ci:forward

**Pull request closed without merging**
