### PR TITLE
LPD-39134 Data Set Objects are not created

### PR DESCRIPTION
**Pull request by markocikos**
### References

- JIRA: [LPD-39134 Data Set Objects are not created](https://issues.liferay.com/browse/LPD-39134)
- Caused by [Enforce with SF](https://liferay.atlassian.net/browse/LPD-30381) 

### What is the goal of this PR?

A regression bugfix cc @ling-alan-huang @4lejandrito

Definition for `DataSet` needs to be last in the list of `items`, because it references previous items in relationships.

I reverted the breaking commit, and re-applied few lines of valid SF, that was not related to order of items.

### CODE REVIEW

**Review by juanjofgliferay — APPROVED** [review]
LGTM :rocket:

**Comment by markocikos** [comment]
ci:forward

**Comment by herrardo** [comment]
Thx!

**Comment by markocikos** [comment]
ci:report:38847809

**Pull request closed without merging**
