### PR TITLE
LPS-128125 Run baseline task for frontend-js-loader-modules-extender-api

### PR DESCRIPTION
**Pull request by wincent**
ie. `cd modules/apps/frontend-js/frontend-js-loader-modules-extender-api && gradlew baseline`

### CODE REVIEW

**Comment by jbalsas** [comment]
Thanks for picking this up @wincent!

**Comment by jbalsas** [comment]
ci:forward

**Comment by jbalsas** [comment]
We also have
- [modules-semantic-versioning-jdk8 failure on com.liferay.frontend.taglib.servlet.taglib](https://issues.liferay.com/browse/LPS-127039)
- [modules-semantic-versioning-jdk8 failure on com.liferay.frontend.token.definition](https://issues.liferay.com/browse/LPS-127360)

@john-co, @manoelcyreno could you dig a little on this, see how come all these semver issues are getting pass CI?

**Comment by wincent** [comment]
Test failure seems obviously bogus (cc @john-co, @calvinctvo, @zhangyan0701) — I can't see how a version number change would lead to a Poshi failure — so I am just going to retry Chema's forward.

**Comment by wincent** [comment]
ci:forward

**Comment by wincent** [comment]
So it failed twice in the same way, and [as noted here](https://github.com/liferay-frontend/liferay-portal/pull/830), you can see other pulls with the same unique failure.

I think I'm going to forward all these manually.

**Comment by wincent** [comment]
Manual forward: https://github.com/brianchandotcom/liferay-portal/pull/99083

**Comment by john-co** [comment]
>  could you dig a little on this, see how come all these semver issues are getting pass CI?

It looks like semantic-versioning-jdk8 will be listed as a common failure even if there's a new unique test that failed related to a PR. https://liferay.slack.com/archives/CL3TWSMHQ/p1614282994020100?thread_ts=1614279778.019500&cid=CL3TWSMHQ

I'm not able to easily tell where those issues first started b/c testray history doesn't easily track individual failures of semantic-versioning test batch due to calling gradlew baseline in every module.

Currently reaching out to CII and others to gather more info.

**Comment by john-co** [comment]
Investigation ticket to track: https://issues.liferay.com/browse/LRQA-65364

**Comment by wincent** [comment]
> Investigation ticket to track: https://issues.liferay.com/browse/LRQA-65364

Nice. Thanks for diving into that @john-co. Does this mean that, until those upstream follow-ups are in place, we should make a point of inspecting "failures in common with upstream" to watch out for these? (If so, can you put some recommendation that effect in the team Slack channel?)

**Comment by john-co** [comment]
yes that's the case, I'll post about it in the slack channel. :)

**Pull request closed without merging**
