### PR TITLE
LPS-159360 Merge FDS Radio and Checkbox filters

### PR DESCRIPTION
**Pull request by markocikos**
### References

- [LPS-159360 Merge FDS Radio and Checkbox filters](https://issues.liferay.com/browse/LPS-159360)
- Related to #2255
- Related to #2572

### What is the goal of this PR?

There is a lot of code duplication between [RadioFilter](https://github.com/liferay/liferay-portal/blob/master/modules/apps/frontend-data-set/frontend-data-set-web/src/main/resources/META-INF/resources/management_bar/components/filters/RadioFilter.js), [CheckboxesFilter](https://github.com/liferay/liferay-portal/blob/master/modules/apps/frontend-data-set/frontend-data-set-web/src/main/resources/META-INF/resources/management_bar/components/filters/CheckboxesFilter.js) and [AutocompleteFilter](https://github.com/liferay/liferay-portal/blob/master/modules/apps/frontend-data-set/frontend-data-set-web/src/main/resources/META-INF/resources/management_bar/components/filters/AutocompleteFilter.js). A textbook example of why this is bad is #2572, where we made a change in one filter but missed to update the same code in another.

In this PR, we are merging `RadioFilter` and `CheckboxesFilter`, into the new `SelectionFilter`. `multiple` props determines if it is single selection (radio inputs) or multiple selection (checkbox inputs). With this, we are applying the support for `entityFieldType` to single selection filter. In addition, we are:
- migrating existing usages
- adding a new field to the sample module, `size`, and a single selection filter on it (see gif) /cc @john-co 

Notes:
- `SingleSelectionItems` and `MultipleSelectionItems` are internal 'helper' components, just to buy space.
- In a future PR, the plan is to merge `AutocompleteFilter` into `SelectionFilter`, to be set by `autocomplete` prop. After that, the only two distinct filters we will have are `SelectionFilter` and `DateRangeFilter`.

/cc @MarinhoFeliphe 

### What does it look like?

after

### Steps to reproduce

1. Deploy `frontend-data-set-sample-web`.
2. Place `Frontend Data Set Sample` widget on any page.

### CODE REVIEW

**Comment by markocikos** [comment]
Force-pushed, with semver update. `baseline` task really acts weird sometimes. I did run it yesterday, but it decided to increase only minor version. On CI, and for me locally today, it increased major version. Conversely, major version is correct, since we are deleting a part of API.

**Comment by markocikos** [comment]
ci:test:relevant

**Comment by markocikos** [comment]
ci:test:relevant

**Review by tinycarol — APPROVED** [review]
LGTM!

**Comment by markocikos** [comment]
ci:forward

**Pull request closed without merging**
