### PR TITLE
LPS-132552 | Use JSON macros in Clay tests

### PR DESCRIPTION
**Pull request by zhangyan0701**
**Description**
Use JSON macros in Clay tests.

**Jira Ticket**
https://issues.liferay.com/browse/LPS-132552

### CODE REVIEW

**Comment by zhangyan0701** [comment]
ci:test:frontend

**Comment by john-co** [comment]
Just started reviewing :)

**Comment by john-co** [comment]
ci:forward

**Comment by john-co** [comment]
Looks good!

**Review by john-co — APPROVED** [review]

**Pull request closed without merging**
