### PR TITLE
[WIP][7.4-only]LPS-123547 - Remove all currently deactivated modules in compatibility layer

### PR DESCRIPTION
**Pull request by marcoscv-work**
This PR **removes** all currently deactivated modules in `admin` and `classic` themes compatibility layer.
and removes `components_animations`

In order to remove all the compatibility layer, we remove all components have been deactivated and tested during last year, from now we only need to remove in `styled` theme.

---

How to test the commit https://github.com/liferay-frontend/liferay-portal/pull/505/commits/8c1701c261703014fa5c1004e55930db75b85f0e:

- Go to the themes directory
- Deploy them
- If it works it's fine, you will not see design changes

How to test the commit https://github.com/liferay-frontend/liferay-portal/pull/505/commits/eb953de3e4b3a2360f826427e913ab0cb596862f

1. Open portal an test all collapse and fade animations:
 - Responsive menus
 - Dropdowns
 - SAidebars

### CODE REVIEW

**Comment by marcoscv-work** [comment]
No testing until `CI` get back to work

**Comment by jbalsas** [comment]
CI should be back by now!

**Comment by jbalsas** [comment]
ci:test:sf

**Comment by jbalsas** [comment]
ci:test:relevant

**Review by eduardoallegrini — APPROVED** [review]
I checked the code and it should be fine since we are removing things we had already disabled. My only concern is the compat-layer-animations because we are not replacing the legacy code but I understand it could be very difficult since we should look for the "in" class that is added in JS. I tried a quick research and found only 3 cases of AUI (we are removing AUI, right?) so I think we should merge it and fix the bugs that eventually could come up

**Comment by marcoscv-work** [comment]
rebased!

**Comment by marcoscv-work** [comment]
ci:test:relevant

**Comment by marcoscv-work** [comment]
> I checked the code and it should be fine since we are removing things we had already disabled. My only concern is the compat-layer-animations because we are not replacing the legacy code but I understand it could be very difficult since we should look for the "in" class that is added in JS. I tried a quick research and found only 3 cases of AUI (we are removing AUI, right?) so I think we should merge it and fix the bugs that eventually could come up

In this case, we had a regression.
I've tested most normal cases and they work, so yes, better if we make the change and wait for the possibility to open new issues to prioritize (if it really is there some)

**Comment by marcoscv-work** [comment]
@john-co can you help us with this?

I've seen it could be by `ConfigureLookAndFeelSettingsSinglePage` or `Welcome to Liferay is present` but they are correctly present.

Maybe this poshi test?
image

**Comment by marcoscv-work** [comment]
Maybe I'm wrong but I do not understand why is failing, the screen poshi test is testing is this one?

image

**Comment by eduardoallegrini** [comment]
If it helps somehow, I noticed there are new tests for some classes we are removing

https://github.com/liferay/liferay-portal/blob/master/modules/apps/static/portal-osgi-web/portal-osgi-web-wab-reference-support-test/src/testIntegration/resources/exploded-test-theme/css/aui/lexicon/lexicon-base/_button-groups.scss

**Comment by jbalsas** [comment]
> If it helps somehow, I noticed there are new tests for some classes we are removing

Those shouldn't matter since they're probably using some specific css to validate some part of the infrastructure but the contents are irrelevant.

We should mostly focus on `*-web`, `*-taglib` and other possible UI usages and tags and ignore the rest.

**Comment by john-co** [comment]
Just started reviewing :)

**Comment by john-co** [comment]
ci:test:bundle

**Comment by john-co** [comment]
- From looking at the poshi report, ClassicTheme#ConfigureLookAndFeelSettingsSinglePage fails while trying to assert that Welcome Liferay text is not present after clicking Minimize from the portlet dropdown menu.
image

- Here's the expected result on master:
MinimizeHelloWorld

Waiting for test bundle to finish in order to manually verify.

**Comment by john-co** [comment]
Reproduced the issue on test bundle:

Peek 2020-11-17 17-57

Also observed other weird behavior with password reminder on first login:
Selection_027
It suspect it may be due to a corrupt bundle though...would have to double check again tomorrow if needed.

**Comment by marcoscv-work** [comment]
Thanks @john-co !
I would never have found it!

Is there any way to skip all tests related to the compatibility layer, and then work on separate issues to fix them step by step?
In order to move forward faster.

**Comment by marcoscv-work** [comment]
rebase and some fixes

**Comment by marcoscv-work** [comment]
ci:test:relevant

**Comment by eduardoallegrini** [comment]
Just started reviewing :)

**Comment by eduardoallegrini** [comment]
I tried to run the changes locally and everything is building and working fine there are a few classes/css-rules we didn't remove last time that are causing some visual bugs

image (1)
image (2)
image (3)
image

**Comment by marcoscv-work** [comment]
Thanks, @eduardoallegrini !

The last time we tried to go forward with removing the compatibility layer we feel exhausted because we were looking for bugs along every corner on portal.
I totally agree to not introduce new issues but this case I think is different, we are trying to remove very old markup which we probably need to update (frontend-infra and teams), and make them visible can be the best at this moment

**Comment by marcoscv-work** [comment]
we are closer but:

```
     [exec]     BUILD FAILED: Element is visible at "//span[contains(.,'Public Pages')]"
     [exec]     /opt/dev/projects/github/liferay-portal/portal-web/test/functional/com/liferay/portalweb/macros/Staging.macro[deactivateStagingCP]:508
     [exec]     /opt/dev/projects/github/liferay-portal/portal-web/test/functional/com/liferay/portalweb/tests/enduser/staging/pgstaging/PGStaging.testcase[ActivateDeactivateRemoteStaging]:77
     [exec] 
     [exec] 
     [exec] com.liferay.poshi.runner.PoshiRunner > test[LocalFile.PGStaging#ActivateDeactivateRemoteStaging] STANDARD_ERROR
     [exec]     java.lang.Exception: Element is visible at "//span[contains(.,'Public Pages')]"
     [exec]     	at com.liferay.poshi.runner.selenium.BaseWebDriverImpl$Condition.assertTrue(BaseWebDriverImpl.java:4576)
     [exec]     	at com.liferay.poshi.runner.selenium.BaseWebDriverImpl$Condition.waitFor(BaseWebDriverImpl.java:4611)
     [exec]     	at com.liferay.poshi.runner.selenium.BaseWebDriverImpl.waitForNotVisible(BaseWebDriverImpl.java:3369)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec]     	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec]     	at java.lang.reflect.Method.invoke(Method.java:498)
     [exec]     	at com.liferay.poshi.runner.PoshiRunnerExecutor$1.call(PoshiRunnerExecutor.java:1190)
     [exec]     	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
     [exec]     	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
     [exec]     	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
     [exec]     	at java.lang.Thread.run(Thread.java:745)
     [exec] 
     [exec] com.liferay.poshi.runner.PoshiRunner > test[LocalFile.PGStaging#ActivateDeactivateRemoteStaging] FAILED
     [exec]     java.lang.Exception at BaseWebDriverImpl.java:4576
     [exec] 
     [exec] 1 test completed, 1 failed
     [exec] 
     [exec] 
     [exec] FAILURE: Build failed with an exception.
```

I'm trying to find out why. @john-co is it more visible for you?

**Comment by marcoscv-work** [comment]
We don't see the problem so we are going to add `.hide` class in `styled`.

**Comment by marcoscv-work** [comment]
ci:test:relevant

**Comment by john-co** [comment]
ci:test:bundle

**Comment by john-co** [comment]
@marcoscv-work , 

In staging admin page, After clicking the None radio button we're expecting no options/content below the Remote Live radio button. However, in the test screenshot, there appears to be some remote staging options still visible after the user saves after selecting None radio button.

Here's what we should expect:
Peek 2020-11-18 13-12

**Comment by john-co** [comment]
@gaborlovasdotcom @JoyceWang08211 could one of you verify the failing remote staging test? I'm finding that I'm a bit more rusty on setting up local remote staging.

**Comment by JoyceWang08211** [comment]
I'll check up the failed staging test on the above bundle. Downloading the bundle. @john-co

**Comment by JoyceWang08211** [comment]
The above bundle is broken. Contact with John Co for remote staging.

**Comment by john-co** [comment]
Reviewed. Test failures are unrelated. :heavy_check_mark: 

Staging test passed in the last run: https://testray.liferay.com/home/-/testray/case_results/1344559328?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D1344543182%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc

And all poshi tests passed from that run too..
https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=1344543182

other unique failures look like network connection issues. Will rerun the tests one more time.

**Comment by john-co** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
ci:forward

**Comment by marcoscv-work** [comment]
ci:test:sf

**Comment by marcoscv-work** [comment]
ci:forward

**Comment by jbalsas** [comment]
**Hey @marcoscv-work, @eduardoallegrini, @pat270, please remember to prefix the PRs with `[7.4-only]` before forwarding them to make sure Brian doesn't automatically attempt to backport them!!**

**Comment by eduardoallegrini** [comment]
> Hey @marcoscv-work, @eduardoallegrini, @pat270, please **remember to prefix the PRs with `[7.4-only]`** before forwarding them to make sure Brian doesn't automatically attempt to backport them!!

Ok! I think we should wait for the https://github.com/liferay-frontend/liferay-portal/pull/521 and then rebase this one

**Comment by jbalsas** [comment]
> Ok! I think we should wait for the #521 and then rebase this one

Put the ones that shouldn't be forwarded in `Draft` and add the `On Hold` label to make it obvious to by-passing reviewers like myself 😂

**Comment by marcoscv-work** [comment]
ci:stop

**Comment by eduardoallegrini** [comment]
ci:test:stop

**Comment by marcoscv-work** [comment]
rebased and continued in: https://github.com/liferay-frontend/liferay-portal/pull/533

**Pull request closed without merging**
