### PR TITLE
LPS-197657 Removing server info from spritemaps

### PR DESCRIPTION
**Pull request by fortunatomaldonado**
https://liferay.atlassian.net/browse/LPS-197657

When CDN is enabled, there are error messages in the logs due to SVG links not containing the correct protocol.
I removed the server info and left the path to the svg so that there is no longer any issue with the protocol.

Please let me know if there are any questions or comments about this.
Thank you!

### CODE REVIEW

**Comment by fortunatomaldonado** [comment]
ci:test:sf

**Comment by fortunatomaldonado** [comment]
ci:test:relevant

**Comment by fortunatomaldonado** [comment]
ci:test:relevant

**Review by bryceosterhaus — COMMENTED** [review]
If you aren't seeing any issues with CDN or anything then I think this change should be safe.

are these really the only place we add the spitemap on the server?

**Comment by fortunatomaldonado** [comment]
Hello @bryceosterhaus,

I narrowed down these changes in FEI that adds the icons and buttons and focused on the main page. 
There are other uses in different components and thought to focus on the issue in the ticket.

Let me know if I should make any changes.
Thank you!

**Comment by bryceosterhaus** [comment]
@fortunatomaldonado ah I see, yeah if this solves your issue than should be good to forward

**Comment by mateusralv** [comment]
Hey @fortunatomaldonado the failures are not related

[Testray Comparison](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1699376164449&testrayRunIdA=2452837033&testrayRunIdB=2453441367)

**Comment by fortunatomaldonado** [comment]
ci:forward

**Comment by fortunatomaldonado** [comment]
ci:stop

**Comment by markocikos** [comment]
ci:test:stable

**Comment by markocikos** [comment]
ci:forward:force

**Comment by fortunatomaldonado** [comment]
@markocikos it was determined that this solution is not the right way to go about resolving the issue. I closed the forward.

**Pull request closed without merging**
