### PR TITLE
LPS-145185 - Fix ability to lint internal remote apps

### PR DESCRIPTION
**Pull request by bryceosterhaus**
https://issues.liferay.com/browse/LPS-145185

Context: https://liferay.slack.com/archives/C03CAD9EF/p1641915255001500

### CODE REVIEW

**Comment by bryceosterhaus** [comment]
@kevenleone can you see if this addresses your issue?

**Comment by kevenleone** [comment]
Just starting reviewing :)

**Comment by kevenleone** [comment]
@bryceosterhaus yes, for sure!

I fixed the SF error and resent: https://github.com/liferay-frontend/liferay-portal/pull/1816

**Comment by bryceosterhaus** [comment]
ci:test:sf

**Comment by bryceosterhaus** [comment]
ci:test:sf

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by john-co** [comment]
Reviewed. Test failures are unrelated. :heavy_check_mark: 
- lpkg test failure looks like a fluke, unrelated to js changes
- plus the test suite passed with same commits in https://github.com/liferay-frontend/liferay-portal/pull/1819#issuecomment-1011190432

**Comment by bryceosterhaus** [comment]
Manual forward: https://github.com/brianchandotcom/liferay-portal/pull/112075

**Pull request closed without merging**
