### PR TITLE
LPS-192880 Emit nonce from JSPs

### PR DESCRIPTION
**Pull request by izaera**
This is a resend of https://github.com/brianchandotcom/liferay-portal/pull/145078 renaming the script tag attributes as per https://github.com/brianchandotcom/liferay-portal/pull/145078#issuecomment-1851112878

----

Once this is merged, DXP’s most restrictive supported CSP will be:

 `script-src '[$NONCE$]'; script-src-attr 'unsafe-inline';`

This is for internal DXP code, not CKEditor, which may need even more permissive policies.

Next steps for the future, would be replacing all onclick, onfocus, etc. attribute handlers by nonced script snippets so that we can remove the script-src-attr 'unsafe-inline' from the most restrictive supported CSP. However to do that we may need to:

1. Change infrastructure tags like <aui:button>, <liferay-ui:icon>, etc. to generate nonce snippets
2. Replace pure HTML attribute handlers (this may need to involve other teams depending on where the pure HTML code is)

Note that 2 has at least two subcases we have already detected:

1. Fragments may include pure HTML code and AFAIK we don’t have any mechanism to make that CSP compliant
2. Site initializers have the same problem.

### CODE REVIEW

**Comment by izaera** [comment]
ci:test:sf

**Comment by izaera** [comment]
ci:test:stable

**Comment by izaera** [comment]
I won't run relevant because this is a resend and the PR contents were cleared before :+1:

**Comment by dsanz** [comment]
ci:forward:force

**Comment by dsanz** [comment]
ci:forward:force

**Pull request closed without merging**
