### PR TITLE
[7.4-only] LPS-102102, LPS-102114 and LPS-102109 - Remove compat-layer modals, splitter, tables and progress-bars

### PR DESCRIPTION
**Pull request by marcoscv-work**
[7.4-only] - Only master
---
This PR removes:
- Modals
- Splitter
- Tables
- Progress-bars

From the compatibility layer

--- 

## Previous PRs:
https://github.com/marcoscv-work/liferay-portal/pull/349
https://github.com/liferay-frontend/liferay-portal/pull/554
https://github.com/liferay-frontend/liferay-portal/pull/542
https://github.com/liferay-frontend/liferay-portal/pull/567

---

To test the PR:

- Global smoke test along portal, tables, progress-bars, and modals should work fine with some possible visual difference, if we find out a difference, please report it

### CODE REVIEW

**Comment by marcoscv-work** [comment]
ci:test:sf

**Comment by marcoscv-work** [comment]
ci:test:relevant

**Comment by john-co** [comment]
Just started reviewing :)

**Comment by john-co** [comment]
ci:test:bundle

**Comment by john-co** [comment]
ci:test:relevant

**Comment by john-co** [comment]
- WebContentDisplayWithStaging#StagingPublishWCWithImageFieldEdit 
looks like narrower item selector causing the nav tab options to be mobile view
image

The other test case issues look weird to me. I feel that the network connection issue messages interfered with the functional tests too. Rerunning and can double check after test bundle is ready if need to look deeper.

**Comment by john-co** [comment]
cc/ @john-co so I can get better notified of the test results.

**Comment by john-co** [comment]
**[Related]**
- WebContentDisplayWithStaging#StagingPublishWCWithImageFieldEdit - narrower modal described in previous analysis

**[Unrelated]**
- startup issue looks like the same issue described in https://issues.liferay.com/browse/LPS-118039
- WorkflowUpgrade#ViewWorkflowArchive621015 looks like a fluke/flaky

**Comment by marcoscv-work** [comment]
Fixing modals and we will add a new LPS (we prefer to merge them all together)..

**Comment by marcoscv-work** [comment]
I think all modals are under control and we have added the removal of pager:

**Comment by marcoscv-work** [comment]
ci:test:sf

**Comment by marcoscv-work** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
Screen Shot 2020-12-03 at 16 25 04

Are you guys trying to touch everything at once? :D

**Comment by john-co** [comment]
looks like modal issue still exists.
image

**Comment by marcoscv-work** [comment]
@john-co :-D are those the same unrelated tests?

**Comment by marcoscv-work** [comment]
How is this possible?!!! :-(

image

Let me double check if we are missing something! thanks @john-co

**Comment by john-co** [comment]
ci:test:bundle

**Comment by marcoscv-work** [comment]
In some cases modal didn't work well, now I've changed to specify the `yui3` class

**Comment by marcoscv-work** [comment]
@john-co can we pass only the test which failed with the modal issue?

**Comment by john-co** [comment]
do you mean, only run the specific test on CI? 
i.e. affected tests with modal issue: 
WebContentDisplayWithStaging#StagingPublishWCWithImageFieldEdit 
Forms#SubmitFormWithRequiredImageField
Forms#SubmitFormWithRequiredImageField

**Comment by john-co** [comment]
ci:test:relevant

**Comment by john-co** [comment]
probably better to just run the whole `ci:test:relevant` since we want to get that to pass for `ci:forward` to work.

**Comment by marcoscv-work** [comment]
**Since we still have test issues with modals I've created a new PR without modals:**
- https://github.com/liferay-frontend/liferay-portal/pull/590

**Commits related to modals:** (to do the update)
- https://github.com/liferay-frontend/liferay-portal/pull/580/commits/5e928626b172908c4ca6830fa0c4a821212d5a8c
- https://github.com/liferay-frontend/liferay-portal/pull/580/commits/1908b8f0597cec9fb9794b8af70c22ba3997dded
- https://github.com/liferay-frontend/liferay-portal/pull/580/commits/e15b14dbf344d775c22e28c3483b83efa2ee8e4d
- https://github.com/liferay-frontend/liferay-portal/pull/580/commits/7fd60c28cd65b35d388c665117549dd74747f7bd
- https://github.com/liferay-frontend/liferay-portal/pull/580/commits/5ad44364738f5da4dbf47b5c25dc44bc5ffbd635
- https://github.com/liferay-frontend/liferay-portal/pull/580/commits/5e76d57aee73d67ec0acc6106f6e236ead53e515
- (Update the removal commit with master when no-modal PR be merged)

**Comment by edalgrin** [comment]
Working on modals here https://github.com/liferay-frontend/liferay-portal/pull/644

**Comment by quanhuynhces** [comment]
Hi @marcoscv-work,  I am working with a LPP issue on branch 7.3 and I found out these your commits can solve this issue. But I see that you marked these commit only for 7.4 so I wonder that are these commits fine to cherry-pick to 7.3. 
Thank you very much.

**Comment by marcoscv-work** [comment]
> Hi @marcoscv-work, I am working with a LPP issue on branch 7.3 (table-cell-expand for roles.jsp) and I found out these your commits can solve this issue. But I see that you marked these commit only for 7.4 so I wonder that are these commits fine to cherry-pick to 7.3. Thank you very much.

Sorry for the delay @quanhuynhces !
Yeah, of course, we can use it!

**Pull request closed without merging**
