### PR TITLE
LPS-120075 Update clay-charts to v2.21.5

### PR DESCRIPTION
**Pull request by julien**
This is a fix for [Predictive Charts unpredictably crash on firefox](https://issues.liferay.com/browse/LPS-120075) that was caused by an old version of `billboard.js`.

This was detected through commerce, but is also reproducible using the `Chart Sample` Widget.

**The fix** consists in updating the `billboard.js` dependency in the `2.x` series to match that of the `3.x` series so we ensure the latest version is loaded.

**Steps to reproduce**
- Create a New Minium Demo Site
    - Open `Product Apps Menu`
    - Go to `Control Panel` > `Sites`
    - Create new site of type `Minium Demo`
- Navigate to the site using Firefox

**Expected**
The forecast chart shows on the demo landing page

**Current**
A JS error is thrown and the chart shows uninitialized

Screen Shot 2020-08-31 at 21 21 27

### CODE REVIEW

**Comment by julien** [comment]
ci:test:sf

**Comment by julien** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
Hey @julien, I'm going to update the description and forward, but please, make sure to remember to do this always to avoid others having to fill in this information for you. Even if the title is descriptive, the PR does not explain why we need to update it or where to test it.

**Comment by jbalsas** [comment]
ci:forward

**Pull request closed without merging**
