### PR TITLE
LPS-164321 - Fix Typo in aria-orientation

### PR DESCRIPTION
**Pull request by Ayoub3r**
### References

- [LPS-164321 Remote Apps Critical Accessibility Bugs](https://liferay.atlassian.net/browse/LPS-164321)

### What is the goal of this PR?

The goal of this PR is to fix the critical accessibility issues detected through AxeDev Tools when creating a Custom Element.

The first issue and the one that this PR is targeted at, is fixing the typo that triggers the "ARIA attributes must conform to valid names" error from "aria-orentation" to "aria-orientation".

The second one is related to the clay component as demonstrated by [this ticket](https://liferay.atlassian.net/browse/LPS-201300) and requires a PR of it's own.

#### Before PR
image (50)

#### After PR
image (51)

### CODE REVIEW

**Comment by markocikos** [comment]
See https://github.com/liferay-frontend/liferay-portal/pull/3819

**Comment by holatuwol** [comment]
ci:forward

**Comment by holatuwol** [comment]
Identical changes were approved here:
https://github.com/liferay-frontend/liferay-portal/pull/3819#pullrequestreview-1725071179

**Comment by markocikos** [comment]
ci:forward

**Comment by JerryAdrianoo** [comment]
Hey @Ayoub3r, these failures are not related to your changes! :)
See [Test Comparison](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1700217139544&testrayRunIdA=2460184848&testrayRunIdB=2460250767)

**Comment by markocikos** [comment]
ci:forward:force

**Pull request closed without merging**
