### PR TITLE
LPD-21229 Add import maps Sample with jQuery

### PR DESCRIPTION
**Pull request by izaera**

### CODE REVIEW

**Comment by izaera** [comment]
ci:test:relevant

**Comment by izaera** [comment]
I'll give it one more chance to run the tests and if it doesn't work I will forward it since we will be rewriting all the tests related to the samples -> https://github.com/liferay-frontend/liferay-portal/pull/4097

**Comment by izaera** [comment]
ci:test:relevant

**Comment by izaera** [comment]
Failures are not related

**Comment by izaera** [comment]
ci:forward:force

**Review by bryceosterhaus — COMMENTED** [review]
it's very funny to see jquery+webpack

**Comment by izaera** [comment]
> it's very funny to see jquery+webpack

image

**Pull request closed without merging**
