### PR TITLE
LPS-118975 - Fix max-height in apple devices

### PR DESCRIPTION
**Pull request by marcoscv-work**
This PR fixes a problem with the applications menu height in Apple mobile devices, it also can be reproduced in iPad.

IMG_3F23AD06AB38-1

About some questions you could have:

- Why I use the `small` breakoint and not `xsmall`?
Because iPad has the same issue

- The lines, 40 and 41:
https://github.com/liferay-frontend/liferay-portal/pull/246/commits/7233c666b239b3681952afec98762a7a98ef279a#diff-a8b960730121fffdaf4e2e25b1826a30R40-R41
There are until we are ready to use `autoprefixer` in this module

- The line 42 has not the same value than prefixers:
https://github.com/liferay-frontend/liferay-portal/pull/246/commits/7233c666b239b3681952afec98762a7a98ef279a#diff-a8b960730121fffdaf4e2e25b1826a30R42
Yes, this because the specification has changed, and the new value is: `stretch`
You can see how it works in autoprefixer by using for example: 
https://autoprefixer.github.io and pasting:
```css
.applications-menu-wrapper {
      max-height: stretch;
}
```
image

--- 

**How to test it**

- Use an apple mobile device or select "iPhone X" in your "BrowserStak"
- Login in portal and open the **applications menu**
- Scroll until the final of the menu

### CODE REVIEW

**Comment by marcoscv-work** [comment]
ci:test:sf

**Comment by marcoscv-work** [comment]
ci:test:relevant

**Comment by marcoscv-work** [comment]
I think setting the height is not a good idea in general

I mean, the only way to use a "responsive" view in sm is to make the desktop browser super tiny, it is not a real case.
If on tablets and mobiles andoid and apple it works without setting the height, I think it is a solution less aggressive

**Comment by marcoscv-work** [comment]
ci:test:sf

**Comment by marcoscv-work** [comment]
ci:test:relevant

**Comment by eduardoallegrini** [comment]
ci:forward

**Pull request closed without merging**
