### PR TITLE
LPS-122448 Expand delegate utility to support cases where a target was the child element

### PR DESCRIPTION
**Pull request by kresimir-coko**
This is a PR that extends the initial implementation done by @bryceosterhaus. I added the ability for the event to propagate from any child to the proper parent, removed the test that was testing against that, and added a new test that tests this newly added functionality.

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:test:sf

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
@bryceosterhaus, could you forward this if it looks good so we can unblock the other `delegate` replacement PRs?

**Review by bryceosterhaus — APPROVED** [review]

**Comment by bryceosterhaus** [comment]
ci:forward

**Pull request closed without merging**
