### PR TITLE
LPS-137441 - Icon Provisoning

### PR DESCRIPTION
**Pull request by bryceosterhaus**
Follow up from https://github.com/brianchandotcom/liferay-portal/pull/115179 with changes requested

cc @victorg1991

### CODE REVIEW

**Comment by bryceosterhaus** [comment]
ci:test:sf

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
ci:stop

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by magjed4289** [comment]
Just started reviewing :)

**Comment by bryceosterhaus** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
