### PR TITLE
LPS-161237 Adds `skippable` functionallity

### PR DESCRIPTION
**Pull request by diegonvs**
# How to use it?

1. Go to Site Settings -> Walkthrough and place this JSON snippet:

```js
{
	pages: {
		'/home' : ['step-1', 'step-2'],
	},
	steps: [
		{
			content: '<span>Content 1</span><br/><code>Hello1</code>',
			darkbg: false,
			id: 'step-1',
			nodeToHighlight: '.logo',
			title: 'Title 1',
		},
		{
			content: '<span>Content 2</span><br/><code>Hello2</code>',
			darkbg: false,
			id: 'step-2',
			nodeToHighlight: '[aria-label="Open menu"]',
			positioning: 'left',
			title: 'Title 2',
		}
	],
        skippable: true,
}
```
_See `skippable: true`_
 
2. Enable Walkthrough and then Save
3. Go to your home page
4. Navigate using Next/Previous
5. Check the `Don't show me again` checkbox if you want

# Considerations

There are lots of possible UX interactions here. I considered this one:

When checking the checkbox, it will save on localStorage a key containing the `siteGroupId` and the `userId` representing this user X on this website Y doesn't want to see these steps again.

It will take effect just when accessing the page again. Requires a page refresh.

## Other possibilities:

1. We can check, and by the end of the tour/walkthrough, once the user clicks on Close, it will not show the Walkthrough again, even on refresh
2. We can check, and if the user closes the Walkthrough, it will not show it again

Hey @drakonux, what do you think is the best? The current implemented one or 1 or 2? 🤔

### CODE REVIEW

**Comment by diegonvs** [comment]
Ok @drakonux, I'll consider covering the existing(refresh) UX and the other two options I provided to you :p

**Review by kresimir-coko — APPROVED** [review]
The code part looks good 👍

**Comment by diegonvs** [comment]
ci:test:sf

**Comment by diegonvs** [comment]
ci:test:relevant

**Comment by diegonvs** [comment]
Now, the "Other Possibilities" section was completely covered by a61cf71

**Comment by diegonvs** [comment]
ci:forward

**Pull request closed without merging**
