### PR TITLE
LPS-160944 Include specific ci relevant tests for frontend js cookies development

### PR DESCRIPTION
**Pull request by john-co**
**Description**
FI is tasked to add some GDPR features for cookies and may touch files in the cookies module. Adding ci test coverage on FI submodules in frontend-js-web related to cookies will help FI catch potential cross-cutting/dependent issues/fixes (like [this one](https://issues.liferay.com/browse/LRQA-76465)) prior to merging to master.
Current FI development can be found in:
[LPS-155901](https://issues.liferay.com/browse/LPS-155901)
[LPS-155888](https://issues.liferay.com/browse/LPS-155888)
[LPS-154290](https://issues.liferay.com/browse/LPS-154290)

**Test Plan**
- [x] Change in frontend-js-web/../cookies includes acceptance tests for cookies and general smoke tests. Done in https://github.com/john-co/liferay-portal/pull/481#issuecomment-1221109493

**JIRA TICKET**
https://issues.liferay.com/browse/LPS-160944

### CODE REVIEW

**Comment by john-co** [comment]
ci:test:relevant

**Review by susanchen3 — APPROVED** [review]
LGTM, good to know how to run relevant for specific modules :) 

Test failures are unrelated as well :heavy_check_mark:

**Review by tinycarol — APPROVED** [review]
LGTM!

**Comment by john-co** [comment]
ci:forward

**Pull request closed without merging**
