### PR TITLE
LPD-42610 Add key press functionality for dropdown of pagination

### PR DESCRIPTION
**Pull request by fortunatomaldonado**
https://liferay.atlassian.net/browse/LPP-56801
https://liferay.atlassian.net/browse/LPD-42610

Sending PR without PW to make sure this is sound. Hope to have the PW done by tomorrow.

The pagination's dropdown for intermediate pages were not working with key presses.
I added keypress functionality so that we are able to move up and down the dropdown list, tab/escape away and select the page.

I formatted the page so here are the main takeaways:

**New language key**
https://github.com/liferay-frontend/liferay-portal/pull/4573/files#diff-ef119629946c9b5876f3ddaf7e739fa3316781f38535fa10141db62509a5d684R16832

**Key Button Events**
https://github.com/liferay-frontend/liferay-portal/pull/4573/files#diff-27f7f71f632e2abd6987f6cd26a773edcaeadf9e3830a13a2b5e40620cbc8296R494-R569

**Tooltip added with language key**
https://github.com/liferay-frontend/liferay-portal/pull/4573/files#diff-27f7f71f632e2abd6987f6cd26a773edcaeadf9e3830a13a2b5e40620cbc8296R267

Please let me know if there are any questions or comments about this.

### CODE REVIEW

**Comment by fortunatomaldonado** [comment]
ci:test:relevant

**Comment by fortunatomaldonado** [comment]
I was not able to finish the PW test and will be on PTO tomorrow and all of next week.

**Comment by fortunatomaldonado** [comment]
@antonio-ortega, is there a PR with the updated fix you created for this?
Should I close this out?

**Comment by antonio-ortega** [comment]
Hi @fortunatomaldonado ,

I haven't been able to send a new pull request yet because it's blocked by LPD-40036, but I'll do it as soon as that one gets merged.

You can close this one.

Thanks.

**Pull request closed without merging**
