### PR TITLE
LRQA-63704 Unquarantine test that is passing on CI

### PR DESCRIPTION
**Pull request by john-co**
**Description**
Test is now passing so safe to unquarantine and put back into acceptance list.

**Test plan**
Make sure test is [passing on ci](https://testray.liferay.com/home/-/testray/case_results/1463395565) :heavy_check_mark: 

**JIRA Ticket:**
https://issues.liferay.com/browse/LRQA-63704

### CODE REVIEW

**Comment by john-co** [comment]
ci:test:frontend

**Comment by john-co** [comment]
@jbalsas , @wincent , do we need an internal review for these kinds of things?

**Comment by john-co** [comment]
I'm going to go ahead and forward this since Chema is out and there's no other feedback. I think this is test is safe enough reopen.

**Comment by john-co** [comment]
ci:forward

**Comment by jbalsas** [comment]
> @jbalsas , @wincent , do we need an internal review for these kinds of things?

Hey @john-co, I think the process you followed here is about right. We often forward or merge PRs pointing out the reasons for us not to wait (trivial enough, reviewed offline, blocking something...).

So, I'd say, always send them through this user so we have a simple and obvious process (no need to make a guess at what's the right process each time) and then use your discretion based on complexity, risk, dependencies and other variables that could play into the decision of moving forward without approval from other team members.

**Comment by wincent** [comment]
Yeah, sorry for delay in replying — was in a bunker mostly ignoring email for a couple days.

> then use your discretion based on complexity, risk, dependencies and other variables that could play into the decision of moving forward without approval from other team members.

☝️ especially in a case like this one where you're the one with the domain expertise and the most we can really do is rubber-stamp it.

**Pull request closed without merging**
