### PR TITLE
LPS-169672 - Provide users with clear information to register iFrame client extensions

### PR DESCRIPTION
**Pull request by dsanz**
This is a new PR for https://github.com/liferay-frontend/liferay-portal/pull/2594 where we're using the right LPS number as dictated by the product delivery playbook.

In addition, I'm fixing a couple of issues found in the previous one:

- Compilation [error](https://github.com/liferay-frontend/liferay-portal/pull/2594#issuecomment-1329858932) due to a wrong parameter order. We will need to use the same pattern in the method as we have 2 variants. I've purposedly left this bit to a different ticket
- Removed usage of `<liferay-frontend:fieldset-group>` tag, which has been removed from DXP
- Rerun buildLang to update translations

Other than the above, we shall get the same result UX wise

### CODE REVIEW

**Comment by john-co** [comment]
ci:test:frontend-remote-apps

**Comment by john-co** [comment]
ci:test:bundle

**Comment by john-co** [comment]
The ci:test:frontend-remote-apps is passing so that's promising. 

cc/ @eltonccdantas would you be able to review the `ci:test:relevant` test results?

**Comment by eltonccdantas** [comment]
Sure, I will.

**Comment by eltonccdantas** [comment]
Hi @dsanz , I've analyzed the errors and they look unrelated to your PR according to the [comparison](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=2&testrayRunIdB=2103306619&testrayRunIdA=2104569185&statusB=3). You may manually forward if no other dev review is needed.

CC/ @john-co , @mateusralv

**Comment by dsanz** [comment]
As https://github.com/brianchandotcom/liferay-portal/pull/127228 was merged, we need to change some stuff here to accomodate. So we can not forward it yet

**Comment by dsanz** [comment]
ci:test:relevant

**Comment by mateusralv** [comment]
Hi @dsanz Thanks for the update, I'll take a look 🕵🏽.

**Comment by john-co** [comment]
ci:test:frontend-remote-apps

**Comment by mateusralv** [comment]
I'm taking a look 🕵🏽

**Comment by mateusralv** [comment]
I analyze the two results: 
1. https://github.com/liferay-frontend/liferay-portal/pull/2894#issuecomment-1341612318
Most failures were caused by tests that did not run on the CI.
[comparison run](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1670594105369&testrayRunIdA=2106004744&testrayRunIdB=2108609488)

2. https://github.com/liferay-frontend/liferay-portal/pull/2894#issuecomment-1341823830:
The failures are not unique 🟢

**Comment by mateusralv** [comment]
ci:test:relevant

**Comment by dsanz** [comment]
force-pushed to fix merge conflicts

**Comment by dsanz** [comment]
ci:test:relevant

**Comment by dsanz** [comment]
ci:reevaluate:1387401_5171

**Comment by dsanz** [comment]
ci:test:relevant

**Comment by dsanz** [comment]
ci:test:relevant

**Comment by dsanz** [comment]
ci:test:relevant

**Comment by dsanz** [comment]
Force-pushed again to remove conflicts

**Comment by dsanz** [comment]
ci:test:relevant

**Comment by dsanz** [comment]
ci:test:frontend-remote-apps

**Comment by dsanz** [comment]
ci:test:frontend-remote-apps

**Comment by dsanz** [comment]
@john-co could you pls take a look to the frontend-remote-apps tests?
thank you

**Comment by john-co** [comment]
ci:test:frontend-remote-apps

**Comment by john-co** [comment]
rerunning since generate report failed. :hourglass_flowing_sand:

**Comment by john-co** [comment]
Reviewed. Test failures are unrelated. :heavy_check_mark: 

Ok to manually forward from QA perspective. Pending dev approval.

**Comment by dsanz** [comment]
see https://github.com/brianchandotcom/liferay-portal/pull/127584

**Pull request closed without merging**
