### PR TITLE
LPS-134552 Escape title, so you are not allowed to inject and execute scripts

### PR DESCRIPTION
**Pull request by georgel-pop-lr**
LPS-134552 Escape title, so you are not allowed to inject and execute scripts

### CODE REVIEW

**Review by diegonvs — APPROVED** [review]
Looks good to me! Re-running `ci:test:relevant`

**Comment by diegonvs** [comment]
ci:test:relevant

**Comment by kresimir-coko** [comment]
ci:test:relevant

**Comment by carloslancha** [comment]
ci:forward

**Pull request closed without merging**
