### PR TITLE
LPS-138088 blogs-web info-bar unstyled due to cadmin

### PR DESCRIPTION
**Pull request by pat270**
https://issues.liferay.com/browse/LPS-138088

Blogs `info-bar` is contained inside the isolated `control-menu-container`. This adds `info-bar` styles to cadmin and updates blogs-web css.

blogs-web-info-bar

### CODE REVIEW

**Comment by pat270** [comment]
ci:test:relevant

**Comment by pat270** [comment]
ci:reevaluate:1267401_194

**Comment by diegonvs** [comment]
ci:test:relevant

**Comment by diegonvs** [comment]
Super unrelated...

**Comment by diegonvs** [comment]
ci:test:relevant

**Comment by pat270** [comment]
ci:test:relevant

**Comment by diegonvs** [comment]
ci:test:relevant

**Comment by diegonvs** [comment]
https://user-images.githubusercontent.com/7663513/133341997-cf61dd2a-2d48-4c62-b5f7-9aa5f686e1e0.mov

**Comment by boton** [comment]
ci:test:relevant

**Comment by boton** [comment]
I'm not going to forward only want to view all tests passed 😄

**Comment by pat270** [comment]
Everything passed! Can we forward it?

**Comment by matuzalemsteles** [comment]
Hey @pat270 @boton, is it ok to be forwarded?

**Comment by boton** [comment]
> Hey @pat270 @boton, is it ok to be forwarded?

Yes, I think so

**Pull request closed without merging**
