### PR TITLE
LPS-133052 Consider owner permissions in MessageBoardThreadModelResourcePermission

### PR DESCRIPTION
**Pull request by javierdearcos**
The owner permissions are not being considered when a custom ModelResourcePermission is passed to the ActionUtil addAction method.

To fix this issue I add the owner consideration inside the MessageBoardThreadModelResourcePermission logic.

### CODE REVIEW

**Review by nhpatt — APPROVED** [review]

**Comment by nhpatt** [comment]
ci:forward

**Comment by nhpatt** [comment]
I think it's correct. I see the use case of `ModelResourcePermission` as: "you provide the permission logic". It could be the case that you don't want owners to be able to edit, so adding it by default when also contributing a `ModelResourcePermission` I think is overreaching.

**Comment by javierdearcos** [comment]
Understood. I've edited the PR description to avoid confusion.

The only remain concern is that, although we are providing a custom ModelResoucePermission to list the allowed actions, I think we are not using it to perform the action itself, so we may have some incongruences.

**Comment by javierdearcos** [comment]
11 hours... Don't think this is actually running...

**Comment by javierdearcos** [comment]
ci:stop

**Comment by javierdearcos** [comment]
ci:forward

**Pull request closed without merging**
