### PR TITLE
LPS-131410 Reduce TreeviewCard padding

### PR DESCRIPTION
**Pull request by p2kmgcl**
This PR updates the TreeviewCard padding (reducing it to 0.5rem = 8px).

Steps to check:
1. Go to web content administration
2. Create a web content
3. Open sidebar panel
4. Go to Categorization > Topic > Select
5. Add any topic

### CODE REVIEW

**Comment by julien** [comment]
Seems like a reasonable and safe change

**Review by kresimir-coko — APPROVED** [review]
LNHTM!

**Comment by wincent** [comment]
Well, let's just ship this and see if anybody complains about us breaking some treeview in another place. 😬

**Comment by wincent** [comment]
ci:forward

**Pull request closed without merging**
