### PR TITLE
LPS-152236 Modernize `toggleRadio`

### PR DESCRIPTION
**Pull request by kresimir-coko**
This PR moves the `toggleRadio`  util from `frontend-js-aui-web` to `frontend-js-web`, adds the types for the util and exports it.

## 🧪 Testing
Can be tested by going to Content & Data > Documents & Media > Edit Folder

image

### CODE REVIEW

**Comment by kresimir-coko** [comment]
I have pushed to fix conflicts @bryceosterhaus should I run CI again?

**Comment by bryceosterhaus** [comment]
@kresimir-coko, yeah I can just run forward and itll send after passing. Manual forwards seem to take longer to get merged these days

**Comment by bryceosterhaus** [comment]
ci:forward

**Comment by kresimir-coko** [comment]
ci:test:relevant

**Comment by kresimir-coko** [comment]
ci:forward

**Pull request closed without merging**
