### PR TITLE
LPS-102112 Remove compat-layer simple-flexbox-grid

### PR DESCRIPTION
**Pull request by eduardoallegrini**
Simple class replacement and compat-layer removal

`flex-container` ➡ `d-flex flex-wrap`
`flex-item-center` ➡ (parent) `align-items-center`
`flex-item-expand` ➡ `flex-fill`

### CODE REVIEW

**Comment by pat270** [comment]
This LGTM!

**Comment by eduardoallegrini** [comment]
ci:test:sf

**Comment by eduardoallegrini** [comment]
waiting for https://github.com/liferay-frontend/liferay-portal/pull/505

**Comment by marcoscv-work** [comment]
LGTM!!!

After issues with https://github.com/liferay-frontend/liferay-portal/pull/505 probably we will merge this PR with another one in order to rebase them and forward

**Review by marcoscv-work — APPROVED** [review]

**Pull request closed without merging**
