### PR TITLE
LPS-175719 Updated EditFilters Macro

### PR DESCRIPTION
**Pull request by eltonccdantas**
This PR fixes some FDS tests.

Poshi reports:

[FDSCustomView#CanBeEdited](https://drive.google.com/file/d/1aWNH_yTEzoURiVNXH4EXFZx_NSzISHVK/view?usp=share_link)

[FDSCustomView#CanBeSaved](https://drive.google.com/file/d/1srRFeAx_N38A4z92rm2Cerz_cnnVWS2V/view?usp=share_link)

[FDSCustomView#CanBeSelected](https://drive.google.com/file/d/1tANL7B1hwzyc2zznKgK-loMlTW03QrYG/view?usp=share_link)

[FDSCustomView#CanCreateMultiple](https://drive.google.com/file/d/1rW8f6JR3e0rtrG-fyeNDSCgn15fqbSEF/view?usp=share_link)

[Jira Ticket](https://issues.liferay.com/browse/LPS-175719)

### CODE REVIEW

**Comment by eltonccdantas** [comment]
ci:help

**Comment by eltonccdantas** [comment]
Waiting on @mateusralv to push it forward

**Review by mateusralv — APPROVED** [review]
God Job 🎉

**Comment by mateusralv** [comment]
ci:forward

**Pull request closed without merging**
