### PR TITLE
LPS-178217 The flag of languages with variant (ca_ES_VALENCIA or sr_RS_latin) are not correctly displayed when adding a translation

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
https://issues.liferay.com/browse/LPS-178217

The flag of languages with variant (ca_ES_VALENCIA or sr_RS_latin) are not correctly displayed when adding a translation

This issue is similar to [LPS-176503](https://issues.liferay.com/browse/LPS-176503) but applied to other Liferay components

**Root cause of the issue:**

- Java Locale code uses underscore character in the locale code to separate language, country and variant, for example: ca_ES_VALENCIA
- But in the frontend side, we have to replace the underscore character with the dash, for example: ca-ES-VALENCIA
- The problem here is we don't usually consider there could be two underscore characters, so only the first one is replaced: ca_ES_VALENCIA => ca-ES_VALENCIA and the flag is not found

**Reproduction steps**

See [LPS-178217](https://issues.liferay.com/browse/LPS-178217) description

**Solution**

I am changing the `locale.replace('_','-')` usages with `locale.replaceAll('_','-')`

The first commit 8f0fc60b9233eaf3f46b00c3ea30d501019c5c73 fixes the flag issue.

I have added an additional commit 656c8f3d3f43d0df935a71d8739e96c55b650e2d that applies the same change everywhere

### CODE REVIEW

**Comment by eltonccdantas** [comment]
I'll take a look at it

**Comment by eltonccdantas** [comment]
ci:help

**Comment by eltonccdantas** [comment]
ci:test:bundle

**Comment by eltonccdantas** [comment]
ci:stop

**Comment by eltonccdantas** [comment]
ci:stop

**Comment by eltonccdantas** [comment]
ci:stop:bundle

**Comment by mateusralv** [comment]
ci:test:sf

**Comment by eltonccdantas** [comment]
Hey @jorgediaz-lr , I've analyzed your pull request and the failures look unrelated. Here's the [comparison run](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=2&testrayRunIdB=2228584927&testrayRunIdA=2228737759&statusB=3). You may forward it if no other dev review is needed.

CC/ @mateusralv

**Comment by dsanz** [comment]
Hi @jorgediaz-lr we've been a bit swamped this week, we could not take this earlier, sorry about that.

Changes look good to me, nevertheless, I've run this command to look for occurrences as this type of substitutions can be tricky, in the hope we don't miss any case:
`git grep -E -e "replace\('[-_]'" -e "replace\(/_/" -e "replace\(/-/" `

I've discarded the files already included in this pull (relative to `modules/` folder), and the false positives i.e. not related to locale management. This is what I got:

- [ ] [apps/object/object-js-components-web/src/main/resources/META-INF/resources/components/CodeEditor/CodeEditorLocalized.tsx](https://github.com/liferay/liferay-portal/blob/e7240b0aea565b89c6cc8f77e71933b0e9ae1500/modules/apps/object/object-js-components-web/src/main/resources/META-INF/resources/components/CodeEditor/CodeEditorLocalized.tsx#L52-L57)
- [ ] [apps/object/object-js-components-web/src/main/resources/META-INF/resources/components/InputLocalized.tsx](https://github.com/liferay/liferay-portal/blob/e7240b0aea565b89c6cc8f77e71933b0e9ae1500/modules/apps/object/object-js-components-web/src/main/resources/META-INF/resources/components/InputLocalized.tsx#L46-L51)
- [ ] [apps/object/object-js-components-web/src/main/resources/META-INF/resources/components/RichTextLocalized.tsx](https://github.com/liferay/liferay-portal/blob/e7240b0aea565b89c6cc8f77e71933b0e9ae1500/modules/apps/object/object-js-components-web/src/main/resources/META-INF/resources/components/RichTextLocalized.tsx#L32-L37)
- [ ] [apps/object/object-web/src/main/resources/META-INF/resources/js/components/ListTypeDefinition/utils.ts](https://github.com/liferay/liferay-portal/blob/a8aa993dd2d68fc7c1d6cfc547254d7df851e047/modules/apps/object/object-web/src/main/resources/META-INF/resources/js/components/ListTypeDefinition/utils.ts#L18-L20): not totally sure this is needed but changing it will probably not hurt
- [ ] [apps/object/object-web/src/main/resources/META-INF/resources/js/utils/string.ts](https://github.com/liferay/liferay-portal/blob/4ebbb75b4be9a13e9785d99dbbfe4fff1bdf87da/modules/apps/object/object-web/src/main/resources/META-INF/resources/js/utils/string.ts#L42-L44)
- [ ] [apps/segments/segments-web/src/main/resources/META-INF/resources/js/components/title_editor/LocalizedDropdown.es.js](https://github.com/liferay/liferay-portal/blob/a3ffea48e3bd7a8398ce87fdd7d72e35456d8fa2/modules/apps/segments/segments-web/src/main/resources/META-INF/resources/js/components/title_editor/LocalizedDropdown.es.js#L187-L194)
- [ ] [dxp/apps/search-experiences/search-experiences-web/src/main/resources/META-INF/resources/sxp_blueprint_admin/js/utils/language/rename_keys.js](https://github.com/liferay/liferay-portal/blob/06e285758e2aeaf0c5d1c6bbdd521691ea09ae45/modules/dxp/apps/search-experiences/search-experiences-web/src/main/resources/META-INF/resources/sxp_blueprint_admin/js/utils/language/rename_keys.js#L25-L27), this is tricky as it depends on the `func` being passed. Looks like [this usage](https://github.com/liferay/liferay-portal/blob/06e285758e2aeaf0c5d1c6bbdd521691ea09ae45/modules/dxp/apps/search-experiences/search-experiences-web/src/main/resources/META-INF/resources/sxp_blueprint_admin/js/utils/language/format_locale_with_underscores.js#L23-L25) is ok already, and [this other](https://github.com/liferay/liferay-portal/blob/06e285758e2aeaf0c5d1c6bbdd521691ea09ae45/modules/dxp/apps/search-experiences/search-experiences-web/src/main/resources/META-INF/resources/sxp_blueprint_admin/js/utils/language/transform_locale.js#L19-L26) is not related.

Also, there are some occurrences in Java code, but they look unrelated.

Could you please add another commit with these cases? I can handle this but you'll be much faster than me

Thanks so much

**Comment by jorgediaz-lr** [comment]
ci:test:sf

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by jorgediaz-lr** [comment]
Hi @dsanz 

I have added a new commit 00eb0ec54a6e649ba4ecdac259afe098a82ceb0f with the changes in the missing typescript files.

In these files we cannot apply the change of replace => replaceAll because the typescript library doesn't have the replaceAll method, see: https://github.com/Microsoft/TypeScript/blob/main/src/lib/es5.d.ts#L439

I have finally used a Regex as an alternative, changing `replace('_', '-')` with `replace(/_/g, '-')`  this behaves in a similar way than replaceAll

About https://github.com/liferay/liferay-portal/blob/a3ffea48e3bd7a8398ce87fdd7d72e35456d8fa2/modules/apps/segments/segments-web/src/main/resources/META-INF/resources/js/components/title_editor/LocalizedDropdown.es.js#L187-L194 it is not necessary to change it as it also uses the `replace(/_/g, '-')` Regex alternative.

Let me know if you have any other idea or alternative.

**Comment by deborasoliveira** [comment]
Hi @jorgediaz-lr! The failures seem to be unrelated to this PR according to the [comparison](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=2&testrayRunIdB=2236110431&testrayRunIdA=2236752681&statusB=3).

- _LocalFile.UsersAdmin#ChangeUserPassword_ and _LocalFile.UsersAdmin#SearchUser_ tests failed on CI but they passed when I tested them using this PR bundle. The other failures seem to be flaky failures.

**Comment by jorgediaz-lr** [comment]
Hi @dsanz 

Do you have any update about this PR?

Thank you

**Comment by dsanz** [comment]
ci:forward:force

**Comment by jorgediaz-lr** [comment]
ci:forward:force

**Comment by eltonccdantas** [comment]
Hey @jorgediaz-lr  and @dsanz, I see this PR is stuck for a long time, is there anything I can do for helping from a QA perspective?

**Comment by dsanz** [comment]
Hey @eltonccdantas given we have your ok that failures are not related, our blocker now is the forwarding, which seems not working.

I'm making a last attempt before a manual forward

**Comment by dsanz** [comment]
ci:forward:force

**Comment by jorgediaz-lr** [comment]
Hi @dsanz 

I have manually forwarded to Brian, see https://github.com/brianchandotcom/liferay-portal/pull/132785

**Pull request closed without merging**
