### PR TITLE
LPS-119666 Fix spacers in ccp-layer and ccp-tokens

### PR DESCRIPTION
**Pull request by eduardoallegrini**
This change fix the spacing variables in the style-book module.

ezgif com-video-to-gif (1)

[Generated CSS](https://gist.github.com/eduardoallegrini/f1a885438db19fcccb4a23d0ec460646)

To test it, create a HTML fragment in your page and paste the following code

```html
<div class="container-fluid container-fluid-max-xl">
  <div class="row">
    <div class="col">
      <div class="border border-dark d-inline-block pl-1">pl-1</div>
      <div class="w-100"></div>
      <div class="border border-dark d-inline-block pl-2">pl-2</div>
      <div class="w-100"></div>
      <div class="border border-dark d-inline-block pl-3">pl-3</div>
      <div class="w-100"></div>
      <div class="border border-dark d-inline-block pl-4">pl-4</div>
      <div class="w-100"></div>
      <div class="border border-dark d-inline-block pl-5">pl-5</div>
      <div class="w-100"></div>
      <div class="border border-dark d-inline-block pl-6">pl-6</div>
      <div class="w-100"></div>
      <div class="border border-dark d-inline-block pl-7">pl-7</div>
      <div class="w-100"></div>
      <div class="border border-dark d-inline-block pl-8">pl-8</div>
      <div class="w-100"></div>
      <div class="border border-dark d-inline-block pl-9">pl-9</div>
      <div class="w-100"></div>
      <div class="border border-dark d-inline-block pl-10">pl-10</div>
      <div class="w-100"></div>
      <div class="border border-dark d-inline-block p-3">p-3</div>
      <div class="w-100"></div>
      <div class="border border-dark d-inline-block pt-3">pt-3</div>
      <div class="w-100"></div>
      <div class="border border-dark d-inline-block pr-3">pr-3</div>
      <div class="w-100"></div>
      <div class="border border-dark d-inline-block pb-3">pb-3</div>
      <div class="w-100"></div>
      <div class="border border-dark d-inline-block px-3">px-3</div>
      <div class="w-100"></div>
      <div class="border border-dark d-inline-block py-3">py-3</div>
      <div class="w-100"></div>
      <div class="border border-dark d-inline-block pl-0">pl-0</div>
      <div class="w-100"></div>
      <div class="border border-dark d-inline-block pl-sm-1">pl-sm-1</div>
      <div class="w-100"></div>
      <div class="border border-dark d-inline-block ml-2">ml-2</div>
      <div class="w-100"></div>
      <div class="border border-dark d-inline-block ml-md-2">ml-md-2</div>
      <div class="w-100"></div>
      <div class="border border-dark d-inline-block ml-n3">ml-n3</div>
      <div class="w-100"></div>
      <div class="border border-dark d-inline-block ml-lg-n3">ml-lg-n3</div>
      <div class="w-100"></div>
      <div class="border border-dark d-inline-block c-pl-4">c-pl-4</div>
      <div class="w-100"></div>
      <div class="border border-dark d-inline-block c-pl-xl-4">c-pl-xl-4</div>
      <div class="w-100"></div>
      <div class="border border-dark d-inline-block c-ml-5">c-ml-5</div>
      <div class="w-100"></div>
      <div class="border border-dark d-inline-block c-ml-n5">c-ml-n5</div>
      <div class="w-100"></div>
      <div class="border border-dark d-inline-block c-ml-sm-n5">c-ml-sm-n5</div>
      <div class="w-100"></div>
    </div>
  </div>
</div>

```

### CODE REVIEW

**Comment by eduardoallegrini** [comment]
The strangest thing is happening

Default situation:

image

If I change --spacer nothing happens even if the output values are updated

image

If I change --spacer-1 both changes are applied

image

**Comment by pat270** [comment]
I'm not sure why the browser doesn't recalculate `--spacer-3`. My best guess is something to do with the cascading rule. `--spacer-3` doesn't get redefined so browser doesn't know which `--spacer` value to use? Or it could be a browser bug, but this happens in every browser so probably not.
```
:root {
  --spacer: 1rem;
  --spacer-3: calc(var(--spacer) * 1);
}

.pl-3 {
  padding-left: var(--spacer-3);
}

<style>
#wrapper {
  --spacer: 2rem;
}
</style>
```

Workaround 1:
```
<style>
:root {
  --spacer: 2rem;
}
</style>
```

Workaround 2:
```
<style>
#wrapper {
  --spacer: 2rem;
  --spacer-0: calc(var(--spacer) * 0);
  --spacer-1: calc(var(--spacer) * 0.25);
  --spacer-2: calc(var(--spacer) * 0.5);
  --spacer-3: calc(var(--spacer) * 1);
  --spacer-4: calc(var(--spacer) * 1.5);
  --spacer-5: calc(var(--spacer) * 3);
  --spacer-6: calc(var(--spacer) * 4.5);
  --spacer-7: calc(var(--spacer) * 6);
  --spacer-8: calc(var(--spacer) * 7.5);
  --spacer-9: calc(var(--spacer) * 9);
  --spacer-10: calc(var(--spacer) * 10);
}
</style>
```

I can get 2) to happen by going through the style book inputs on the right and making a quick change then reverting back to the original.

**Comment by eduardoallegrini** [comment]
After talking with @atjuan, we decided to remove the connections between the `spacers` and the `spacer` in the style-book. I've changed the code keeping the updated custom_properties layer since it doesn't cause any bug and it will be useful for futures changes

**Comment by marcoscv-work** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Review by marcoscv-work — APPROVED** [review]
LGTM

**Comment by eduardoallegrini** [comment]
ci:test:sf

**Comment by eduardoallegrini** [comment]
ci:test:relevant

**Comment by eduardoallegrini** [comment]
ci:test:sf

**Comment by eduardoallegrini** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
Going to forward manually as well :)

**Comment by jbalsas** [comment]
Another one manually forwarded as https://github.com/brianchandotcom/liferay-portal/pull/93576

**Pull request closed without merging**
