### PR TITLE
LPS-195762 XSS with tabs2 in role assignment

### PR DESCRIPTION
**Pull request by manuelecastro**
Related Issue: [LPS-195762](https://liferay.atlassian.net/browse/LPS-195762)

Hi all,

Sending this because of a XSS vulnerability in the tabs2 using NavigationBarTag. See: [select_assignees.jsp](https://github.com/liferay-echo/liferay-portal/blob/master/modules/apps/roles/roles-admin-web/src/main/resources/META-INF/resources/select_assignees.jsp#L38)

Thank you!

### CODE REVIEW

**Comment by thektan** [comment]
ci:test:relevant

**Comment by deborasoliveira** [comment]
The failures are unrelated. 

[Comparison run](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1696364985494&testrayRunIdA=2435187856&testrayRunIdB=2434865576)

**Review by thektan — APPROVED** [review]
LGTM!

**Comment by thektan** [comment]
ci:forward:force

**Pull request closed without merging**
