### PR TITLE
LPS-126737 Replace legacy markup card main-content-card classes with Clay 3 sheet pattern

### PR DESCRIPTION
**Pull request by pat270**
https://issues.liferay.com/browse/LPS-126737

This pr: 
- Removes `main-content-card`, adds `container-form-lg` or `container-view` for spacing between `sheet` and navigation, and replace `aui:button-row` with `sheet-footer` and move buttons inside `sheet` where applicable.
- Removes `cssClass="container-form-lg"` from `liferay-frontend:edit-form` tags since it's output by default now
- `liferay-frontend:diff-version-comparator` replace `container-fluid-1280` with `container-fluid container-fluid-max-xl container-view` and remove `main-content-card`
- `liferay-frontend:edit-form` adds `container-form-lg` by default
- `aui:fieldset` adds attribute `panelHeaderLinkCssClass` to pass css classes into the Panel Header Link. It is `sheet-subtitle` by default.
- `aui:fieldset` use `panel panel-unstyled` by default unless a `cssClass` is declared

`liferay-frontend:edit-form` with `aui:fieldset` should look like:
liferay-frontend-edit-form

I tried to convert all the nooks and crannies of Portal, but I'm sure I missed a lot. This took too long and hopefully I don't break any tests.

### CODE REVIEW

**Comment by pat270** [comment]
@john-co @zhangyan0701 a lot of the test failures are related to updating classes to the `sheet` pattern. I also updated the `panel` pattern in the `aui:fieldset` tag to Clay 3.

**Comment by zhangyan0701** [comment]
ci:test:bundle

**Comment by zhangyan0701** [comment]
Just starting reviewing.

**Comment by zhangyan0701** [comment]
Comparison with master upstream:
https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=3&testrayRunIdB=1462364214&testrayRunIdA=1462364050&statusB=2

**[Related]-LocalFile.CPMessageboards#AddMBThread**
Publish button in Message Board Thread edit page does nothing.
cannot publish message board thread

[Test Fix] All other tests are test fix.

@pat270 I sent you the fix in https://github.com/pat270/liferay-portal/pull/239, could you take a look at the Message Board issue and cherry-pick my commits?

**Comment by pat270** [comment]
ci:test:sf

**Comment by pat270** [comment]
ci:test:relevant

**Comment by pat270** [comment]
Thanks @zhangyan0701! I cherry-picked the commits and fixed the publish button error.

**Comment by pat270** [comment]
@zhangyan0701 I have more failures :(. I think 1) is related to removing panel classes, but not sure about 2) and 3).

**Comment by zhangyan0701** [comment]
Hi @pat270 

1. [Related and Test Fix] - LocalFile.PGAnnouncements#EditAnnouncementsEntry 
I missed this one last time. I will send a commit to fix it.

2. [Unrelated] - LocalFile.AppBuilderWorkflow#CreateObjectAndForm 
It just started to fail on upstream with the same error, so it should not related.

3. [Unrelated] - WorkflowTaskManagerImplTest.testSearchWorkflowTaskByDeletedAsset
This is an Elasticsearch Sidecar issue occasionally happens, not related.

**Comment by zhangyan0701** [comment]
I retested here:
https://github.com/liferay-frontend/liferay-portal/pull/747

**Comment by pat270** [comment]
Thanks again @zhangyan0701 ! I'm going to close and foward the other pr.

**Pull request closed without merging**
