### PR TITLE
LPS-155465, LPS-155467 | master

### PR DESCRIPTION
**Pull request by jaydawu**
**Background**
Create automated tests for the Frontend Dataset component.

**Test Plan**
**FDSQuickActions#BehaviorIsEqualToEllipsisDropdownEquivalentAction**
Given: frontend-data-set-sample-web (FDS Sample Portlet) deployed
And Given FDS Sample Portlet added to page
When: Hover over 1st row item (Sample 1)
And When: click on Pencil Icon
And When: copy the browser URL (#test-pencil is appended)
And When: Click on ellipsis of 1st row item in FDS table
And When: click on Pencil Icon
Then: browser URL matches copied URL (#test-pencil)

**FDSQuickActions#IsNotVisibleOnCheckedRow**
Given: frontend-data-set-sample-web (FDS Sample Portlet) deployed
And Given: FDS Sample Portlet added to page
When: Mark a row checkbox as checked
And When: Hover mouse over checked row
Then: the quick action icons are not visible

**JIRA Ticket:**
https://issues.liferay.com/browse/LPS-155465
https://issues.liferay.com/browse/LPS-155467

### CODE REVIEW

**Comment by jaydawu** [comment]
ci:test:sf

**Comment by susanchen3** [comment]
Taking a look! :detective:

**Review by susanchen3 — APPROVED** [review]
Looks good to me! Thanks! :D

**Comment by susanchen3** [comment]
ci:forward

**Pull request closed without merging**
