### PR TITLE
LRQA-78438 | Fix path in UIInfrastructureUsecase file.

### PR DESCRIPTION
**Pull request by mateusralv**
**Background:**
Fixing of the test cases: 
[LocalFile.UIInfrastructureUsecase#AdminPageCanDisplayStyleCorrectlyAfterPageRefresh](https://issues.liferay.com/issues/?jql=project+in+%2813681%2C+17780%2C+16981%2C+12181%2C+15480%2C+10952%2C+13882%29+AND+cf%5B17320%5D+%3D+%22LocalFile.UIInfrastructureUsecase%23AdminPageCanDisplayStyleCorrectlyAfterPageRefresh%22) [LocalFile.UIInfrastructureUsecase#SitePageCanDisplayStyleCorrectlyAfterPageRefresh](https://issues.liferay.com/issues/?jql=project+in+%2813681%2C+17780%2C+16981%2C+12181%2C+15480%2C+10952%2C+13882%29+AND+cf%5B17320%5D+%3D+%22LocalFile.UIInfrastructureUsecase%23SitePageCanDisplayStyleCorrectlyAfterPageRefresh%22)

### CODE REVIEW

**Comment by mateusralv** [comment]
ci:test:sf

**Comment by mateusralv** [comment]
ci:test:relevant

**Comment by john-co** [comment]
ci:test:frontend:nocompile

**Comment by john-co** [comment]
Looks good to me! :sunglasses:

**Comment by john-co** [comment]
ci:forward

**Pull request closed without merging**
