### PR TITLE
LPS-196146 Hide Creation actions tab from UI

### PR DESCRIPTION
**Pull request by kresimir-coko**
Super simple, we create a new FF here and hide the Creation Actions tab behind it.

### How it looks

image

### CODE REVIEW

**Comment by kresimir-coko** [comment]
ci:test:relevant

**Comment by mateusralv** [comment]
Hi @kresimir-coko The failures are not related.

[Testray Comparison](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1695298440310&testrayRunIdA=2428672771&testrayRunIdB=2428742307)

**Review by markocikos — APPROVED** [review]
@kresimir-coko LGTM! :sparkles:

**Comment by dsanz** [comment]
@kresimir-coko @markocikos , Product asked us to wait for this forward till we have the actions feature working, which requires merging https://github.com/liferay-frontend/liferay-portal/pull/3659 into master

**Comment by markocikos** [comment]
@dsanz all code related to the actions is merged, can we push this?

**Comment by dsanz** [comment]
I think so, this is ready to go :rocket:

**Comment by kresimir-coko** [comment]
ci:forward

**Comment by dsanz** [comment]
ci:forward:force

**Pull request closed without merging**
