### PR TITLE
LPS-154645 Add tests CanDisplayPreviousButtonOnIntermediateStep, FirstStepDoesNotHavePreviousStepButton

### PR DESCRIPTION
**Pull request by susanchen3**
**Background**
Create automated tests for Walkthrough Component.

**Test Plan**
**WalkthroughPopover#CanDisplayPreviousButtonOnIntermediateStep**
Given: frontend-js-components-sample-web deployed to test page
And Given: Navigate to Walkable tab on sample portlet
And Given: popover mode
When: navigate to 2nd step popover
Then: Then previous step button is present
And When: click on previous step button
And Then: 1st step popover is present
And Then: 2nd step popover is not present

**WalkthroughPopover#FirstStepDoesNotHavePreviousStepButton**
Given: frontend-js-components-sample-web deployed to test page
And Given: Navigate to Walkable tab on sample portlet
And Given: popover mode When: on 1st step popover
Then: previous step button is not present
And Then: the primary button next step is present
And When: click on next step button Then: 2nd step popover is present And Then: 1st step popover is not present

**JIRA Ticket:**
https://issues.liferay.com/browse/LPS-154645
https://issues.liferay.com/browse/LPS-154646

### CODE REVIEW

**Comment by susanchen3** [comment]
ci:test:frontend:nocompile

**Comment by susanchen3** [comment]
Fixed merged conflicts

**Comment by john-co** [comment]
Just started reviewing :)

**Review by john-co — APPROVED** [review]
Looks good to me! :sunglasses:

I see what you mean by having click next step as a macro with `Walkthrough.goToNextStep` now. That works.

**Comment by john-co** [comment]
ci:forward

**Pull request closed without merging**
