### PR TITLE
LPD-25447 Space is needed between attributes

### PR DESCRIPTION
**Pull request by fortunatomaldonado**
https://liferay.atlassian.net/browse/LPP-53970
https://liferay.atlassian.net/browse/LPD-25447

There was no space between attributes which caused errors in the log. Adding the space resolves this issue.

I omitted a Playwright test since the page will adjust the html and display it correctly regardless.
Please let me know if there are any questions or comments about this.

Thank you!

### CODE REVIEW

**Comment by fortunatomaldonado** [comment]
ci:test:relevant

**Comment by antonio-ortega** [comment]
Hey @fortunatomaldonado ,

We've been asked to include a test for any bug coming from LPP tickets. Could you add some test for this, please?

Thanks.

**Comment by georgel-pop-lr** [comment]
> Hey @fortunatomaldonado ,
> 
> We've been asked to include a test for any bug coming from LPP tickets. Could you add some test for this, please?
> 
> Thanks.

Hi @fortunatomaldonado,

Maybe here you could try to do an integration test or even better a unitary test, but not sure how can you validate the HTML provided, maybe you should try to parse it like I explained in my comment [HtmlParserImpl.java#L55](https://github.com/liferay/liferay-portal/blob/6ce0b9eb049e99a50285a324a3bd4afd76d340ab/modules/apps/portal/portal-html-parser-impl/src/main/java/com/liferay/portal/html/parser/internal/HtmlParserImpl.java#L55).

Regards.

**Comment by fortunatomaldonado** [comment]
Hello @antonio-ortega and @georgel-pop-lr 
I have been trying to learn how to create a test for this and which test would be best. I will continue to do so and may ask for assistance on this if that's alright.
Thank you!

**Review by markocikos — APPROVED** [review]
@fortunatomaldonado LGTM! :sparkles:

**Comment by fortunatomaldonado** [comment]
Hello @markocikos 
Truly appreciate you taking a look at this!

I found once disabling Javascript in Playwright, I am unable to navigate around the portal since a lot of buttons and components required Javascript.
I have been trying to see if there is a way around this but can't seem to find one.

If you have any further suggestions or things I can try, that would be appreciated.
Thank you!

**Comment by georgel-pop-lr** [comment]
Hi guys,

Could we also add some logs inside https://github.com/liferay/liferay-portal/blob/6ce0b9eb049e99a50285a324a3bd4afd76d340ab/modules/apps/portal/portal-html-parser-impl/src/main/java/com/liferay/portal/html/parser/internal/HtmlParserImpl.java#L55 to identify the content that is failing without the need to debug the code?

I think this would help a lot to see if is ours or custom content.

Regards.

**Comment by fortunatomaldonado** [comment]
Hello @georgel-pop-lr,

I'm looking into Jericho and I'm not able to see a way to go about identifying the content that is failing. It does throw the position in the Error log but that means we would need the full content and check the position.

I was thinking we can specify the component the content is located to better identify where the issue is coming from. 

For this case, the component would be [LayoutContentProviderImpl.java](https://github.com/liferay/liferay-portal/blob/master/modules/apps/layout/layout-impl/src/main/java/com/liferay/layout/internal/content/LayoutContentProviderImpl.java#L152) which means the error is coming from pages.

@dsanz, let me know if this is viable or if I may be missing a more detailed way to find the error content.

**Comment by dsanz** [comment]
@fortunatomaldonado @georgel-pop-lr we are asking search team to build such a patch, we don't have as much expertise as they have for this, pls check https://liferay.atlassian.net/browse/LPP-53980?focusedCommentId=2664762

**Comment by dsanz** [comment]
@fortunatomaldonado do we still have to merge this into master right?

**Comment by fortunatomaldonado** [comment]
Hello @dsanz 
Yes this still has to be merged into Master and needs to add integration test.

Also, I was thinking we do any log optimization in its own LPD ticket.

**Comment by fortunatomaldonado** [comment]
FWD: https://github.com/liferay-frontend/liferay-portal/pull/4254

**Pull request closed without merging**
