### PR TITLE
COMMERCE-10493 Add support for all quantity variations to the `CartQuickAdd` component

### PR DESCRIPTION
**Pull request by kresimir-coko**
https://issues.liferay.com/browse/COMMERCE-10493

### CODE REVIEW

**Review by bryceosterhaus — APPROVED** [review]
LGTM

**Comment by kresimir-coko** [comment]
ci:test:sf

**Comment by kresimir-coko** [comment]
ci:test:relevant

**Comment by eltonccdantas** [comment]
I'll take a look at it

**Comment by eltonccdantas** [comment]
Hey @kresimir-coko , I've analyzed your pull request and according to this [comparison](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=2&testrayRunIdB=2179915635&testrayRunIdA=2179893916&statusB=3), the error looks unrelated to. You may manually forward if no other dev review is needed.

CC/ @john-co , @mateusralv

**Comment by kresimir-coko** [comment]
ci:test:sf

**Comment by kresimir-coko** [comment]
ci:test:relevant

**Comment by lorenzolapescara** [comment]
ci:test:sf

**Comment by lorenzolapescara** [comment]
ci:test:commerce-functional

**Comment by kresimir-coko** [comment]
ci:reevaluate:1277401_6747

**Comment by kresimir-coko** [comment]
ci:test:sf

**Comment by kresimir-coko** [comment]
ci:test:relevant

**Comment by victoroscuro** [comment]
ci:test:commerce-functional

**Comment by kresimir-coko** [comment]
ci:test:sf

**Comment by kresimir-coko** [comment]
ci:test:sf

**Comment by kresimir-coko** [comment]
ci:test:sf

**Comment by kresimir-coko** [comment]
ci:test:relevant

**Comment by victoroscuro** [comment]
ci:test:commerce-functional

**Comment by kresimir-coko** [comment]
ci:test:sf

**Comment by kresimir-coko** [comment]
ci:test:relevant

**Comment by 22LucaGiannotta22** [comment]
ci:test:commerce-functional

**Comment by kresimir-coko** [comment]
ci:test:sf

**Comment by 22LucaGiannotta22** [comment]
ci:test:commerce

**Comment by kresimir-coko** [comment]
ci:test:sf

**Comment by kresimir-coko** [comment]
ci:test:relevant

**Comment by 22LucaGiannotta22** [comment]
ci:test:commerce

**Comment by 22LucaGiannotta22** [comment]
ci:test:relevant

**Comment by kresimir-coko** [comment]
Closing, finish with testing in https://github.com/liferay-commerce/liferay-portal/pull/3415

**Pull request closed without merging**
