### PR TITLE
LPS-129853 Update `@liferay/npm-scripts` to v41.0.0

### PR DESCRIPTION
**Pull request by wincent**
- [`@liferay/npm-scripts` release notes](https://github.com/liferay/liferay-frontend-projects/releases/tag/npm-scripts/v41.0.0).
- Related [`@liferay/eslint-config` release notes](https://github.com/liferay/liferay-frontend-projects/releases/tag/eslint-config%2Fv24.0.0).

**tl;dr:**

Most of the changes here are to improve support for building/testing/linting TypeScript projects in liferay-portal. Additionally, we're taking the opportunity to freshen some related dependencies. Note some minor config changes included because new defaults in place via `@liferay/npm-scripts` make the explicit config unnecessary.

---

## [npm-scripts/v41.0.0](https://github.com/liferay/liferay-frontend-projects/tree/npm-scripts/v41.0.0) (2021-03-29)

[Full changelog](https://github.com/liferay/liferay-frontend-projects/compare/npm-scripts/v40.0.1...npm-scripts/v41.0.0)

### :boom: Breaking changes

-   chore(npm-scripts)!: bump eslint-config to v24.0.0 ([\#477](https://github.com/liferay/liferay-frontend-projects/pull/477))

### :new: Features

-   feat(npm-scripts): automatically run TS tests ([\#473](https://github.com/liferay/liferay-frontend-projects/pull/473))
-   feat(npm-scripts): add @types/react-dom dependency ([\#472](https://github.com/liferay/liferay-frontend-projects/pull/472))

### :house: Chores

-   chore(npm-scripts)!: bump eslint-config to v24.0.0 ([\#477](https://github.com/liferay/liferay-frontend-projects/pull/477))
-   chore: update lint-related dependencies ([\#476](https://github.com/liferay/liferay-frontend-projects/pull/476))
-   chore(npm-scripts): update to typescript@4.2.3 ([\#474](https://github.com/liferay/liferay-frontend-projects/pull/474))

---

## [eslint-config/v24.0.0](https://github.com/liferay/liferay-frontend-projects/tree/eslint-config/v24.0.0) (2021-03-29)

[Full changelog](https://github.com/liferay/liferay-frontend-projects/compare/eslint-config/v23.0.0...eslint-config/v24.0.0)

### :boom: Breaking changes

-   feat(eslint-config)!: adapt no-use-before-define set-up for TypeScript ([\#471](https://github.com/liferay/liferay-frontend-projects/pull/471))

### :new: Features

-   feat(eslint-config)!: adapt no-use-before-define set-up for TypeScript ([\#471](https://github.com/liferay/liferay-frontend-projects/pull/471))

### :house: Chores

-   chore: update lint-related dependencies ([\#476](https://github.com/liferay/liferay-frontend-projects/pull/476))

### CODE REVIEW

**Comment by wincent** [comment]
ci:stop

**Comment by wincent** [comment]
Stopped the tests because my manual testing showed build errors in `remote-app-client-js`. I'd actually seen these errors in my initial testing (prior to this PR), but they went away on the second build, so I'd chalked it up to stale artifacts. Anyway, fixed them by tweaking the types. Pushed one more commit for that. Going to re-run tests now.

**Comment by wincent** [comment]
ci:test:relevant

**Comment by wincent** [comment]
ci:test:sf

**Comment by wincent** [comment]
Ah, forgot to mention that as part of my manual testing I also ran _all_ the JS unit tests (with [`portool test`](https://github.com/wincent/wincent/blob/632aa515e22ac7203418c0b597c0ff7de4e15878/aspects/dotfiles/files/.zsh/liferay/bin/portool-helpers/test)); all green.

**Comment by wincent** [comment]
As explained in [this commit](https://github.com/liferay-frontend/liferay-portal/pull/943/commits/fc12c335963205d1bedc0c866c6c68c7e4609f76), I don't think this is a new failure (I've seen it before this PR), but I'm working around it anyway.

**Comment by wincent** [comment]
ci:test:sf

**Comment by wincent** [comment]
ci:test:relevant

**Comment by wincent** [comment]
`LocalFile.CPCommerceDiscounts#AssertDiscountIsAppliedToChannel` unique failure seems like a lie.

lies

@john-co @calvinctvo @zhangyan0701 — what do you think?

**Comment by calvinctvo** [comment]
hi @wincent , based on the [history|https://testray.liferay.com/home/-/testray/cases/1352000960] this error first occur on March 26th, and it's been flaky since then. Definitely not unique to this PR.

**Comment by calvinctvo** [comment]
ci:test:relevant

**Comment by wincent** [comment]
Thank you @calvinctvo!

**Comment by wincent** [comment]
ci:forward

**Pull request closed without merging**
