### PR TITLE
LPS-148105 Update `@clayui/*` packages to v2.50.0 and `clay-*` packages to v2.24.0

### PR DESCRIPTION
**Pull request by matuzalemsteles**
Common release with some fixes for TreeView, ColorPicker, and Modal, also contains a Clay v2 release that we backported to improve ClayModal accessibility.

### Bug Fixes

-   **@clayui.com:** add a sass function to fix table border-radius issue ([8fe4b05](https://github.com/liferay/clay/commit/8fe4b05ca7e86bbc07215cb0cfde5d56af9e690e))
-   **@clayui.com:** requested chages for PR ([ad5f1c2](https://github.com/liferay/clay/commit/ad5f1c286ecb8f6ad9dcea1bfc1f3d1311d035d2))
-   **@clayui/core:** fixes error when removing parent's intermediate state when item's sibling is intermediate ([782ea42](https://github.com/liferay/clay/commit/782ea426feae8a4e89c24585c16146f4f14a5efa))
-   **@clayui/css:** Functions `clay-border-radius-inner` simplification and error checking ([9c1d5f4](https://github.com/liferay/clay/commit/9c1d5f41100e9afdfddfe60c93c42b5e327355cb))
-   **@clayui/css:** Table List move inner border-radius styles to Sass variables ([47922c7](https://github.com/liferay/clay/commit/47922c791f82d51e94c639aef7f362877eb1c182))

### Features

-   **@clayui/color-picker:** add color validation in input ([203649f](https://github.com/liferay/clay/commit/203649fb258f26b70650f58c7853ac8835687c03))
-   **@clayui/modal:** improves ClayModal component accessibility ([60b24fc](https://github.com/liferay/clay/commit/60b24fc4ba8dc748474a67323e625bbaa6aab867))

### CODE REVIEW

**Comment by matuzalemsteles** [comment]
ci:test:frontend-clay

**Comment by susanchen3** [comment]
Taking a look!

**Comment by susanchen3** [comment]
Over 300 unit test failures "Aborted prior to running test", which aren't unique to this PR. Probably has to do with [Core](https://liferay.slack.com/archives/CL3TWSMHQ/p1647963705677509).

After [comparison](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=2&testrayRunIdB=1642921124&testrayRunIdA=1642998898&statusB=3), there is one unique Poshi test failure
- [FormsColorField#PredefinedValueCanBeAdded](https://testray.liferay.com/home/-/testray/case_results/1642924328):
```
Expected text "7F26FF" does not match actual text "7f26ff" at "//div[contains(@data-field-name,'Color')]//div[contains(@class,'color-picker')]//div[contains(@class,'color')]//input[@type='text']"
``` 
Just need to change `7F26FF` to `7f26ff` in the testcase. Or you can cherry pick my test fix [here](https://github.com/susanchen3/liferay-portal/pull/19). :)

**Comment by susanchen3** [comment]
Manually forwarded to bchan: https://github.com/brianchandotcom/liferay-portal/pull/115056

**Pull request closed without merging**
