### PR TITLE
LPS-117113 Add SidebarPanelInfoView tests

### PR DESCRIPTION
**Pull request by dgarciasarai**
**Description**

Add jest test and snapshot test for SidebarPanelInfoView component

Previous PR: https://github.com/liferay-frontend/liferay-portal/pull/176

cc: @carloslancha

### CODE REVIEW

**Comment by dgarciasarai** [comment]
ci:test:sf

**Comment by dgarciasarai** [comment]
ci:test:relevant

**Comment by dgarciasarai** [comment]
@carloslancha If this looks good to you, maybe we can forward. All yours :)

**Comment by carloslancha** [comment]
ci:forward

**Pull request closed without merging**
