### PR TITLE
LPS-118224 - Remove table and list custom properties

### PR DESCRIPTION
**Pull request by marcoscv-work**
This task removes some components custom properties in order to don’t offer not needed custom properties in classic theme.

---

How to test it:

It does not affect any perceptible component or visual design, but you can inspect HTML and take a look to the list of custom properties, you will be able to see how removed CCPs do not appear

image

### CODE REVIEW

**Comment by jbalsas** [comment]
This better be a good one

Screen Shot 2020-08-03 at 15 43 41

Screen Shot 2020-08-03 at 15 43 44

**Comment by marcoscv-work** [comment]
ci:test:sf

**Comment by marcoscv-work** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
@david-truong, last chance before we merge this in!

After that, all will be lost forever in the stream of time and GitHub history!

lost_tears

**Comment by jbalsas** [comment]
@john-co, @PablitoBonito, could you do some "intensive" smoke testing to make sure removing this won't introduce visual regressions?

**Comment by jbalsas** [comment]
@david-truong gave clearance for this offline. We'll analyze next steps for 7.4, specially in reference to what customizing capabilities are we really providing.

Forwarding since this should help with stability. @john-co, @PablitoBonito, please follow up on this just in case.

**Comment by jbalsas** [comment]
ci:forward

**Comment by john-co** [comment]
ci:test:bundle

**Comment by john-co** [comment]
Exploratory smoke test:
FF/IE11/Chrome
~20 mins each browser

Focus on weird padding or visual issues with:
buttons
alert messages
nav and navbar
forms
cards, table, and list menus

@zhangyan0701 can you do an exploratory of this? Please create task ticket.

**Comment by zhangyan0701** [comment]
Created https://issues.liferay.com/browse/LRQA-60668 for the exploratory smoke test.

**Comment by john-co** [comment]
Results from https://issues.liferay.com/browse/LRQA-60668:

> Exploratory smoke test passed:
> 
> No weird padding or visual issues found.

**Pull request closed without merging**
