### PR TITLE
LPS-147712 - Migrate Clay MT to frontend-js-components-web

### PR DESCRIPTION
**Pull request by tinycarol**
### References

- [LPS-147712](https://issues.liferay.com/browse/LPS-147712)

### What is the goal?

* Migrate `ClayManagementToolbar` from Clay repo to `frontend-js-components-web`
   * Changed the root class name to `management-toolbar` (used to be `management-bar`) to ensure all required stylesheets are migrated.
* Add sample to `frontend-js-components-sample-web`
   * I have used the existing Storybook sample for this, but considering how simple this component is I don't know if we should simplify it

### What does it look like?
imagen

### How to replicate
* Launch portal
* Run `cd ${PORTAL_ROOT}/modules/apps/frontend-js/frontend-js-components-sample-web && gradlew deploy -a`
* Go to `Site Builder > Pages`
* Click on the `+` button next to `Public Pages`, then click on `Add Page`
* Select widget page, name it `Frontend JS components sample`, click on `Add`
* Click `Home` on the left sidebar
* Select the widget page you created in the navigation bar by clicking on `Frontend JS components sample`
* Click on the `+` icon on the right sidebar, the sidebar should extend with the list of available widgets
* Search for `JS Components Sample` or click on the `Sample` accordion and see `JS Components Sample`
* Drag that element to the center of your screen, it should show a tab bar with two sections
* Select the `Management Toolbar` section
* Done!

### CODE REVIEW

**Review by julien — APPROVED** [review]
chachi

**Comment by tinycarol** [comment]
ci:test:sf

**Comment by tinycarol** [comment]
ci:test:sf

**Comment by tinycarol** [comment]
ci:test:sf

**Comment by tinycarol** [comment]
ci:test:relevant

**Comment by tinycarol** [comment]
ci:test:relevant

**Comment by carloslancha** [comment]
ci:test:relevant

**Comment by carloslancha** [comment]
ci:test:sf

**Comment by carloslancha** [comment]
ci:stop

**Comment by carloslancha** [comment]
As talked offline:

- Export ResultsBar as part of ManagementToolbar
- Export ResultsBar.Item as ResultsBarItem

<3

**Comment by tinycarol** [comment]
ci:test:relevant

**Pull request closed without merging**
