### PR TITLE
feat: LPS-115484 Define and implement the token definitions API

### PR DESCRIPTION
**Pull request by izaera**
This is the -hopefully- final PR for the first version of token definitions API.

It simply provides a singleton OSGi service that retrieves the content of a specific file inside theme bundles. In the future we may evolve the API, but for now this is a good starting point.

See originating PR with the whole discussion on this [here](https://github.com/liferay-frontend/liferay-portal/pull/17).

I have tested this API by manually deploying a modified version of the classic-theme project.

## How to use the API

To obtain the token definition of a given theme you just need to inject a `ThemeTokenDefinitions` instance in your component:

```java
@Component
public class YourComponent {

  @Reference
  protected ThemeTokenDefinitions themeTokenDefinitions;

}
```

and call its only method passing the theme id:

```java
String aJsonString = themeTokenDefinitions.getTokenDefinitionString(themeId)
```

## How to attach a token definition to a theme:

In your theme's project you just need to add a header to `liferay-plugin-package.properties` to specify where the JSON file is located inside the WAR: 

```properties
Token-Definition-Path=WEB-INF/your-wonderful-token-definition.json
```

You can also omit it and `WEB-INF/token-definition.json` will be used.

> This header will end up in the `MANIFEST.MF` file of the autogenerated OSGi bundle when your theme is deployed to Liferay.

Then just fill your `token-definition.json` with whatever is needed (the format is out of the scope of this PR for now, as it hasn't been defined yet).

### CODE REVIEW

**Comment by jbalsas** [comment]
Hey @izaera, this LGTM, I think... just some minor things:
- Could you add a code usage example in the description here? To see how it would be consumed from another module?
- In the test... I see we're testing `bundleInspector.getTokenDefinition(...)`. I'm assuming that's not the `Singleton` API others would consume, is it? If it isn't... is that something we can test?
- Not sure about this, but maybe we need this to be `getThemeTokenDefinition`? Also... wondering, since we're not sure about the return types, if we'd want to be conservative and do something like `String getTokenDefinitionString`? 🤷

**Comment by izaera** [comment]
1. :+1: 
2. Yes, that's internal code. I will try to check at the service level too. I think it's possible.
3. Given that the service is called `ThemeTokenDefinitions` I found it a bit redundant to add `Theme` to the method again. Regarding the `String` suffix, I'm not sure, if we then change this to return a different type I would say we should refactor the method, not adding a new one. But yeah, maybe it is better to name it `String` so that the refactor is more evident...

**Comment by jbalsas** [comment]
> Given that the service is called ThemeTokenDefinitions I found it a bit redundant to add Theme to the method again. Regarding the String suffix, I'm not sure, if we then change this to return a different type I would say we should refactor the method, not adding a new one. But yeah, maybe it is better to name it String so that the refactor is more evident...

I have no strong opinion on this, just anticipating what Brian might ask... regarding the suffix, what I had in mind was:

```java
TokenDefinition tokenDefinition = TokenDefinitions.getTokenDefinition(themeId)
String tokenDefinition = TokenDefinitions.getTokenDefinitionString(themeId)
```

So we would be able to add additional APIs and keep this one without breaking anything... but not sure if this is maybe overthinking it or what.

**Comment by izaera** [comment]
Yes, I got your idea, that's why I said that if we add `getTokenDefinition(themeId)` then, we should remove the `getTokenDefinitionString(themeId)` because, why would anyone ask for the string when we give it as abstracted objects?

Unless we have a strong reason to maintain in the future (like, for example, having released it already as a public API) that should be the logical thing to do.

However, just to make sure, let's rename it, as it won't hurt, and if this get released to the public for any reason, we won't need to break anything :+1: .

**Comment by izaera** [comment]
I have added the usage description above and renamed the method. 

I discarded the test because:

1) It needed to be an Arquillian test or otherwise mock lots of OSGi infrastructure
2) The significative code in the SUT is almost inexistent: most of it is pure OSGi scaffolding and wiring to end up reaching `ThemeBundleInspector`
3) The real code is in the `ThemeBundleInspector` which is already tested

**Comment by izaera** [comment]
ci:test:sf

**Comment by izaera** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
LGTM, I think!

**Comment by jbalsas** [comment]
@brunobasto, do you mind taking a quick peek, just because... Java! 😂

**Comment by jbalsas** [comment]
> ThemeBundleInspectorTest.testGetTokenDefinition
>    org.junit.ComparisonFailure: expected:<{[]}> but was:<{[
> ]}>

I'm speechless, @izaera... just speechless... 

TDD FTW!!

**Comment by izaera** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
ci:forward

**Pull request closed without merging**
