### PR TITLE
[TS] LPS-178252 Add link for apple custom favicon

### PR DESCRIPTION
**Pull request by fortunatomaldonado**
FWD: https://github.com/liferay-core-infra/liferay-portal/pull/3833

https://issues.liferay.com/browse/LPS-178252

Hello, I added a link to provide custom favicons for ios safari browsers.
Please let me know if this should be sent else where or if there are any questions or comments about this.

Thank you!

### CODE REVIEW

**Comment by eltonccdantas** [comment]
I'll take a look at it

**Comment by eltonccdantas** [comment]
Hey @fortunatomaldonado , the failures look unrelated to your pull request. You may forward it if no other dev review is needed.

[comparison run](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=2&testrayRunIdB=2232660865&testrayRunIdA=2233100887&statusB=3)

**Comment by bryceosterhaus** [comment]
Looks good! Feel free to manually forward

**Comment by fortunatomaldonado** [comment]
I apologize @eltonccdantas and @mateusralv, I will close this now.

**Pull request closed without merging**
