### PR TITLE
LPS-119868 Adds search to Remote Apps

### PR DESCRIPTION
**Pull request by brunobasto**
~~This is a work in progress. Search results are still a bit flaky. I'm still learning how to implement search properly~~

This PR fixes the search on Remote App Admin. I don't fully understand the mechanisms behind searching, but it should be close enough to how we do it in other places. Search should look for a partial match in either name or url.

### CODE REVIEW

**Comment by brunobasto** [comment]
ci:test:sf

**Comment by brunobasto** [comment]
ci:test:relevant

**Comment by brunobasto** [comment]
Screen Shot 2020-08-31 at 17 21 34

That's an odd failure. I know solar is related to searching so I wonder if that's related to my changes... Doesn't look like it is, but maybe @izaera knows better.. :)

**Comment by brunobasto** [comment]
ci:test:sf

**Comment by brunobasto** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
Maybe @marco-leo can help us out here since he implemented many of these in the early days of the `DataSetDisplay`?

**Comment by brunobasto** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
Going to try this out at a functional level :)

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
@brunobasto, functionally, this looks and feels awesome... super snappy and it seems to provide the expected results!!

I'll try to get someone from the spanish office tomorrow to take a look at this code-wise so we can push it forward with some additional confidence.

Nice job!! 💪

**Comment by jbalsas** [comment]
Ok, so I asked for some anonymous help and this seems to be okay and has chances to get it through albeit the patterns are really no longer up-to-date. 

What I'm going to do with this is:
- Forward it to Brian and ask him to merge if possible
- Ask @javierdearcos assistance to create the Headless API for `Remote Apps` to see if we can migrate to that instead

So... wish us all luck!!

**Comment by jbalsas** [comment]
I've rebased and fixed the `baseline` issue in `remote-app-api`. Trying `relevant` again before sending.

**Comment by jbalsas** [comment]
ci:test:sf

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by javierdearcos** [comment]
> Ok, so I asked for some anonymous help and this seems to be okay and has chances to get it through albeit the patterns are really no longer up-to-date.
> 
> What I'm going to do with this is:
> 
>     * Forward it to Brian and ask him to merge if possible
> 
>     * Ask @javierdearcos assistance to create the Headless API for `Remote Apps` to see if we can migrate to that instead
> 
> 
> So... wish us all luck!!

Contact me whenever you want and we talk to have a little more context. I'll be glad to help 🙂

**Comment by jbalsas** [comment]
ci:test:sf

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
I forgot to push 🙈

**Comment by jbalsas** [comment]
Pushed now, just added the `@Indexable` annotation to the `*Impl` class. Doing that makes the one in `-api` to stay.

**Comment by jbalsas** [comment]
ci:test:sf

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by brunobasto** [comment]
> Pushed now, just added the `@Indexable` annotation to the `*Impl` class. Doing that makes the one in `-api` to stay or so I hope.

My bad. I must have removed it from the Impl and forgot to un buildService. Reason I added and then removed was because I was getting semantic version bumps and after I removed it all was still working os I figured it was not needed..

**Comment by jbalsas** [comment]
All green... let's give this a try!!

**Comment by jbalsas** [comment]
ci:forward

**Comment by jbalsas** [comment]
Hey @arboliveira, going through this it was brought to my attention that we should now be using `Searcher` classes instead... could you point us to some reference implementations or documentation on how should be implement this feature?

I hope it's okay to push this as is (since I still see quite some `Indexer`-based searches in DXP, but looking to update this to the proper pattern as soon as we get the info on it!

Thanks!!

**Pull request closed without merging**
