### PR TITLE
LPS-163590 - Update bundler and add package.json dependencies back in

### PR DESCRIPTION
**Pull request by bryceosterhaus**
Follow up from https://github.com/brianchandotcom/liferay-portal/pull/124234

Previous PR was reverted due to unit test failures

### CODE REVIEW

**Comment by bryceosterhaus** [comment]
ci:stop

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by john-co** [comment]
Reviewed. Test failures are unrelated. :heavy_check_mark: 

Ok to manually forward from QA perspective. Pending dev approval.

**Comment by john-co** [comment]
[Testray Comparison](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=3&testrayRunIdB=2003359691&testrayRunIdA=2003425622&statusB=2)

cc/ @gaborlovasdotcom @JoyceWang08211 @timpak please follow up on sporadic failing tests related to your teams that impacted this PR.

**Comment by bryceosterhaus** [comment]
manual forward https://github.com/brianchandotcom/liferay-portal/pull/124406

**Pull request closed without merging**
