### PR TITLE
LPS-117287 Reduce multiple clicks on navigable links to single navigation

### PR DESCRIPTION
**Pull request by markocikos**
Ticket history:
- https://github.com/liferay-frontend/liferay-portal/pull/233 
- https://github.com/liferay/senna.js/pull/337
- https://github.com/liferay/senna.js/pull/338
- https://github.com/markocikos/liferay-portal/pull/190

Change from https://github.com/markocikos/liferay-portal/pull/190:
- We are extending `onDocClickDelegate`, instead of adding new delegation. With this, we are using internal definitions of valid navigation element and valid navigable URL.

### CODE REVIEW

**Review by jbalsas — APPROVED** [review]
I think this is as safe as it can get... let's see what tests have to say about it! 😉

**Comment by markocikos** [comment]
ci:test:sf

**Comment by markocikos** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
ci:test

**Comment by diegonvs** [comment]
chuck

**Review by diegonvs — APPROVED** [review]
LGTM

**Comment by jbalsas** [comment]
Looks safe enough...

**Comment by jbalsas** [comment]
ci:forward

**Pull request closed without merging**
