### PR TITLE
[TS] LPS-185312 Use escape in aui option, also make sure that LPS-190672, LPS-192582 and LPS-192371 won't happen

### PR DESCRIPTION
**Pull request by evibudai**
Hi Team,

https://liferay.atlassian.net/browse/LPS-185312

The previous PR of this ticket caused regression: https://github.com/liferay-frontend/liferay-portal/pull/3365
It caused regression in:
https://liferay.atlassian.net/browse/LPS-190672
https://liferay.atlassian.net/browse/LPS-192582

I reverted it in this PR: https://github.com/liferay-frontend/liferay-portal/pull/3571 so this current PR doesn't show the reverted commits, since it's not merged yet.

Previous PR fixed an XSS issue with the input-move-boxes tag in the liferay-ui taglib.
I modified that PR so that [LPS-190672](https://liferay.atlassian.net/browse/LPS-190672), [LPS-192582](https://liferay.atlassian.net/browse/LPS-192582) and [LPS-192371](https://liferay.atlassian.net/browse/LPS-192371) won't happen. (The last LPS only caused regression on 7.3.x due to backporting)

password_recovery_works_master

Please review my PR!

Thank you and best regards,
Évi

### CODE REVIEW

**Review by bryceosterhaus — APPROVED** [review]
LGTM

**Comment by evibudai** [comment]
Hi @dsanz , I thought reverting the commit that caused regression was urgent, but as this fix overwrites that same commit, I think it's not needed.

**Comment by evibudai** [comment]
Hi @dsanz  ,
can I ask for an update about this PR?

CC: @bryceosterhaus

**Review by markocikos — APPROVED** [review]
@evibudai LGTM!

For future PRs, if there is a green approved review, and you are ok with solution, feel free to forward yourself.

**Comment by markocikos** [comment]
ci:forward

**Comment by evibudai** [comment]
hi @markocikos ,
okay, I'm going to do that. Thank you for forwarding it! :)

**Comment by mateusralv** [comment]
I'm on it 🕵🏽

**Comment by mateusralv** [comment]
Hi @evibudai and @markocikos The failures are not related!

[Testray Comparison](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1692725673133&testrayRunIdA=2410258854&testrayRunIdB=2410370069)

**Comment by markocikos** [comment]
ci:forward:force

**Comment by markocikos** [comment]
ci:forward:force

**Comment by mateusralv** [comment]
ci:forward:force

**Comment by markocikos** [comment]
ci:forward:force

**Pull request closed without merging**
