### PR TITLE
LPS-134528 update dependencies

### PR DESCRIPTION
**Pull request by nhpatt**
Let's not talk about if these dependencies are being used or not... because it's difficult to say.

### CODE REVIEW

**Review by LuismiBarcos — APPROVED** [review]

**Comment by LuismiBarcos** [comment]
ci:forward

**Comment by nhpatt** [comment]
ci:forward

**Comment by LuismiBarcos** [comment]
I see that you dont't like my `ci:forward` 
sadok

:trollface:

**Comment by nhpatt** [comment]
Ups, they were more or less at the same time 😂

**Pull request closed without merging**
