### PR TITLE
LPS-148661 Migrate existing use cases of native confirm to use openConfirmModal conditionally

### PR DESCRIPTION
**Pull request by diegonvs**
## How to reproduce:

0. Create a Feature Flag by adding `feature.flag.LPS-148659=true` on your `portal-ext.properties` or before testing, you can open your favorite DevTools and inside the console, you can type `Liferay.FeatureFlags['LPS-148659'] = true` 🤷🏼 

Considering the number of changed modules, it's impractical to reproduce inside each module, but you can make those tests:

### Inside a migrated module:

1. Global Menu -> Accounts
2. Create an account called `perico`
3. Go back to the accounts listing
4. Select all on Management Bar and then try to bulk delete

You'll see this confirmation dialog:

image

... When clicking Ok, the account will be deleted 🎉 

## Considerations

I created a utility called `openConfirm` which contains the following implementation:

```javascript
import {openConfirmModal} from 'frontend-js-web';

function openConfirm({message, onConfirm}) {
	if (Liferay.FeatureFlags.enableCustomDialogs) {
		openConfirmModal({message, onConfirm});
	}
	else if (confirm(message)) {
		onConfirm(true);
	}
}
```
It helped deal with confirm compatibility and helped me with use cases. 

I created one implementation for each module because we have some use cases [we couldn't import from `frontend-js-web`](https://github.com/liferay-frontend/liferay-portal/pull/2256/files#diff-22ee0ee3757e1d50cbee0814c51e24fd2d987a91091b54dde287c3b7034ec30cR1149) and I would bring visibility of this code to the PR. Another point I left inside each module is it will be easier to create a unique import in the future if this change is required, instead of doing this job after someone convinced me that I should move to a unique place.

### How to test openConfirm

Whether FF is enabled or not. (or If you don't have the proper context, using the native confirm or not)

```javascript
openConfirm('something', (e) => console.log('amazing', e));
// when clicking on Ok
> 'amazing', true
// when clicking on Cancel/X button
> undefined
```

### CODE REVIEW

**Comment by diegonvs** [comment]
ci:test:sf

**Comment by diegonvs** [comment]
ci:test:relevant

**Comment by diegonvs** [comment]
After analyzing the test results, I'm taking a look on failing unit tests and see what can be done :)

**Comment by diegonvs** [comment]
Fixed unit tests at: [1ba6e0a](https://github.com/liferay-frontend/liferay-portal/pull/2256/commits/1ba6e0a40e2ca1666fcc2892ed6fab2f1e7f66f8)


Sent a centralized mock to: https://github.com/liferay/liferay-frontend-projects/pull/943

**Comment by diegonvs** [comment]
ci:test:relevant

**Comment by diegonvs** [comment]
Come, @liferay-continuous-integration!

**Comment by kresimir-coko** [comment]
Hey @diegonvs even after reading your comment, specifically the part about why you added a new util in every module, I still cannot see why it is justified. In a module where you cannot import it, you can use `Liferay.Util.openConfirm`, as long as you add it to the global namespace (which is something we do, because of JSPs).

I feel like adding this many files that have exactly the same code to the codebase is bad practice.

**Comment by diegonvs** [comment]
> Hey @diegonvs, even after reading your comment, specifically the part about why you added new util in every module, I still cannot see why it is justified. In a module where you cannot import it, you can use Liferay.Util.openConfirm, as long as you add it to the global namespace (which is something we do because of JSPs).

Hey @kresimir-coko, we created this feature flag to enable product teams to remove it when they think it's safe. I think the best approach to doing this is duplication(can be hard duplication that I'm doing, which I don't remember why I decided to go with this; or a wrapper function like a unique openConfirm wrapper that will handle the FF logic).

One thing to remember is that `openConfirmModal` has a different signature/behavior than the `openConfirm` wrapper.

I could move the openConfirm with/wrapping the FF logic to a unique place and remove this wrapper function once everyone has already moved the implementation in a follow-up PR. This approach can be weird for forgetting the time to do this task since PTs will prioritize the removal of this feature flag in different time boxes. (This is why I created this duplication of the `openConfirm` definition 🤔 )

... but I'm inclined to move this wrapper(openConfirm) to a centralized place.

Calling @markocikos, do you think this approach of moving `openConfirm` wrapper to a unique place and then removing it once everyone has already removed the FF is ok?

**Comment by markocikos** [comment]
> do you think this approach of moving openConfirm wrapper to a unique place and then removing it once everyone has already removed the FF is ok?

Do we want to allow product teams to individually remove FF when they are ready? If yes, then duplications must stay. If no, we can have a central place with FF. I'd just add, it's probably a bad idea to wait for all product teams to confirm all is ok, it'll take forever. If we do have a central place for FF, it is because **we** want to be sure there are no regressions before applying it everywhere. That could make sense for a low risk change.

**Comment by dsanz** [comment]
This pull proves 2 properties for the openConfirmModal wrapper:
1. It's signature can be made equal to that of the wrapped function [openConfirmModal](https://github.com/liferay/liferay-portal/blob/128ad7a78e50afe4e9c078b0fbd1e375fc17fabe/modules/apps/frontend-js/frontend-js-web/src/main/resources/META-INF/resources/liferay/modal/Modal.js#L298)
2. It can be applicable to all usages, though there are more involved cases like this or this

Once we know that for sure, we can proceed in a way that minimizes effort in the product team side. Please note we're creating a new collaboration pattern which will be enforced DXP wide in an asyncrhronous way.

Ideally, we should reach a solution which does **not require** modifying (production) client code once tested, but at the same time, it's gated via FF holistically (we don't want 30% of the confirms using modal, 70% using native). This has significant advantages:
1. Reduces the amount of effort needed by developers as once PR is pushed as there's no additional changes
2. Once changes are tested (with FF on and off), tested code does not change, so no extra dev-QA roundtrips on product teams
3. We keep control on FF value and provide a consistent UI across the board.

The above are particularly important for some corner cases where we generate JS from Java, like [this](https://github.com/liferay/liferay-portal/blob/e5f17adffa5340a572f7415f11578ad0f5d0631f/modules/apps/change-tracking/change-tracking-web/src/main/java/com/liferay/change/tracking/web/internal/util/PublicationsPortletURLUtil.java#L43-L53) or [this](https://github.com/liferay/liferay-portal/blob/a42d696d75d5a4a5d444b907033ae02b7e35ec30/modules/apps/document-library/document-library-web/src/main/java/com/liferay/document/library/web/internal/display/context/logic/UIItemsBuilder.java#L437-L464).

Here's he proposal to reach that goal:
- Move FF check directly to the Modal.js
- Have all client code to use the openCofirmDialog function as it's expected to do. As the API is exactly the same, there's no further changes needed
- FF will be off in master for a while
- Teams can test this locally by turning the FF on and running local test suites. Any reported issue is fixed. QA can then adapt their tests to work with the old and new dialogs (poshi clicks and things like that). 
- Once ready, teams can commit their adapted tests to master
- When all teams are done, we can test the full product in the CI by turning the FF on
- Once we have the right confidence level, the FF can be removed.

Note that this approach:
- Does not change client code. FF removal needs affects Modal.js and the tests, nothing else. It's even possible to turn the FF into a setting if product decides that it makes sense
- Requires QA teams the ability to run tests "locally" (i.e. outside of master) with the FF on, and expect other tests to break as they may have not been adapted yet. @john-co please let us know if this is a reasonable assumption

@markocikos @diegonvs @kresimir-coko please add your thoughts. This pattern is crucial for the success of this and I'd like to be super sure before executing it.

**Comment by diegonvs** [comment]
ci:test:relevant

**Comment by diegonvs** [comment]
ci:test:sf

**Comment by diegonvs** [comment]
ci:test:relevant

**Comment by dsanz** [comment]
> Yes, QA will need to be able to run tests locally to validate the issue.
Thanks John, so, theoretically we can move forward with this. So the only blocker is to decide if we want to support the FF or we can do a "classic" migration, that's something that has to be decided product-wise (@pablo-agulla)

> I saw these statements from the epic. How are we testing cross-domain iframes are rendering properly? Do we have an ootb DXP feature that QA can test this condition? If we don't have an ootb feature we'll want a sample to test this. I'm not aware of an existing poshi test that checks the cross-domain iframe condition.

There is one I've figured it out. Not super hard but better to explain in a call, maybe @diegonvs or @markocikos can join too.

**Comment by diegonvs** [comment]
ci:test:relevant

**Comment by diegonvs** [comment]
ci:test:relevant

**Comment by diegonvs** [comment]
@john-co, could you give me a ✋🏼 on CI results when finishing? 🥺

**Comment by john-co** [comment]
Just started reviewing :)

**Comment by john-co** [comment]
Hi @diegonvs ,
It looks like a bunch of the tests are failing on error messages due to unexpected alerts popping up.

- Testray Comparison | [Unique failing tests](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=3&testrayRunIdB=1880064765&testrayRunIdA=1880086684&statusB=2)

- For example, the PortalSmoke#Smoke test shows that an alert message pops up after clicking Publish.
image

- Also, after deleting a Blog
**[ Actual ]**
Selection_273
**[ Expected ]**
screenshot_46

**Comment by diegonvs** [comment]
John, thanks for analyzing!! 💖 

> For example, the PortalSmoke#Smoke test shows an alert message pops up after clicking Publish.

Yes, I identified a wrong pattern during the migration. In cases like

```javascript
if (
			!config.masterUsed ||
			confirm(
				Liferay.Language.get(
					'changes-made-on-this-master-are-going-to-be-propagated-to-all-page-templates,-display-page-templates,-and-pages-using-it.are-you-sure-you-want-to-proceed'
				)
			)
		) {
			setPublishPending(true);
		}
```

I was wrapping the conditional to a openConfirmModal call like:

```javascript
openConfirmModal({
				message: Liferay.Language.get(
					'changes-made-on-this-master-are-going-to-be-propagated-to-all-page-templates,-display-page-templates,-and-pages-using-it.are-you-sure-you-want-to-proceed'
				),
				onConfirm: (isConfirmed) => {
					if (isConfirmed }} !config.masterUsed) {
						setPublishPending(true);
					}
				},
			});
```

but I should do this:

```javascript
if (!config.masterUsed) {
			setPublishPending(true);
		}
		else {
			openConfirmModal({
				message: Liferay.Language.get(
					'changes-made-on-this-master-are-going-to-be-propagated-to-all-page-templates,-display-page-templates,-and-pages-using-it.are-you-sure-you-want-to-proceed'
				),
				onConfirm: (isConfirmed) => {
					if (isConfirmed) {
						setPublishPending(true);
					}
				},
			});
		}
```

I'm fixing the usages that are looking like this. I expect the next CI run could bring better results. Thanks again xoxo

**Comment by diegonvs** [comment]
Let's see how CI goes right now.

**Comment by diegonvs** [comment]
ci:test:relevant

**Comment by diegonvs** [comment]
ci:test:relevant

**Comment by diegonvs** [comment]
let's see how CI behaves, fixed most part of collection/pagecontent stuff.

See: https://liferay.slack.com/archives/C3JBR21HA/p1655502108740619?thread_ts=1655460053.956339&cid=C3JBR21HA

**Comment by diegonvs** [comment]
ci:test:sf

**Comment by diegonvs** [comment]
> [LocalFile.DMFileEntry#CanDeleteAllDocumentsAtOnce](https://test-1-23.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/26090//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_DMFileEntry_CanDeleteAllDocumentsAtOnce_)

Seems weird, on testray summary looks like the trash icon is not being found and when running locally it shows the dialog but it doesn't in Ok or Cancel.

> [LocalFile.DMFileEntry#CanDeleteMultipleDocumentsViaActionsButton](https://test-1-23.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/26090//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_DMFileEntry_CanDeleteMultipleDocumentsViaActionsButton_)

Fixed! :) It was another wrong pattern caused by injecting logic that should be run before opening openConfirmModal but it was being handled inside.

Also, I noticed some missing openConfirmModal cases due to the age of the PR and I updated it

**Comment by diegonvs** [comment]
ci:test:relevant

**Comment by diegonvs** [comment]
ci:test:sf

**Comment by diegonvs** [comment]
ci:test:relevant

**Comment by john-co** [comment]
Just started reviewing :)

**Comment by john-co** [comment]
Unfortunately, still seeing some unexpected alert errors:

[Testray Comparison](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=3&testrayRunIdB=1886334919&testrayRunIdA=1886350916&statusB=2)


- image
Selection_291

**Comment by diegonvs** [comment]
ci:test:relevant

**Comment by diegonvs** [comment]
ci:test:upstream-functional

**Comment by mateusralv** [comment]
ci:test:relevant

**Comment by mateusralv** [comment]
ci:test:relevant

**Comment by diegonvs** [comment]
Rebased and added https://github.com/liferay-frontend/liferay-portal/pull/2256/commits/76819eea6d52b63b6a3e8d0346b0859fed6de228

Since one of the fixes is on FDS, it may reduce the number of broken tests. Let's see! 

Thanks, @mateusralv for teaching me to analyse test stuff :)

**Comment by diegonvs** [comment]
ci:test:sf

**Comment by diegonvs** [comment]
ci:test:relevant

**Comment by diegonvs** [comment]
ci:test:sf

**Comment by diegonvs** [comment]
ci:test:relevant

**Comment by diegonvs** [comment]
ci:test:sf

**Comment by diegonvs** [comment]
ci:test:relevant

**Comment by diegonvs** [comment]
ci:test:relevant

**Comment by diegonvs** [comment]
About

wiki errors: I opened a question about a use case on t-lima(https://liferay.slack.com/archives/CLD39UKM5/p1657129635639329)

walkthrough errors: It will be investigated sooner but it's completely unrelated

site errors: https://github.com/liferay-frontend/liferay-portal/pull/2256/commits/b91b3f5605d2499b2d2963bd00c1b2d1874e347f

other errors seem unrelated, let's see what CI will bring to us

**Comment by diegonvs** [comment]
ci:test:relevant

**Comment by john-co** [comment]
@yanan please analyze the test results if unique test failures are related. see [previous analysis](https://github.com/liferay-frontend/liferay-portal/pull/2256#issuecomment-1157934073) as sample.

**Comment by yanan** [comment]
Hi @diegonvs , most test failures are about wiki. Besides "removeTempImages" problem, there is one problem about failed to publish wiki which seems a little werid, could you please help check if it's related or not? Thanks cc @john-co 

Testray Comparison | [Unique failing tests](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=2&testrayRunIdB=1898588898&testrayRunIdA=1897800304&statusB=3)
  - A/B Tests and Analytics Cloud -> Tests not started, also happens on other run(existing ticket [LRQA-75946](https://issues.liferay.com/browse/LRQA-75946))
  - Test failures on publish a Wiki. For example: WYSIWYGUsecase#CanDisplayContentLeftToRight
    **[Actual]** - no repsonse after clicking on Publish button
    Can-not-publish-wiki
    **[Before/Expected]** - able to publish and a success msg popped up
    publish-wiki-success

**Comment by diegonvs** [comment]
Hey @yanan, I was able to publish(WYSIWYGUsecase#CanDisplayContentLeftToRight) after rebasing with the current master.

I think this test was flaky, I'll re-run CI again

[Screencast from 07-11-2022 06:58:40 PM.webm](https://user-images.githubusercontent.com/7663513/178366000-8bb5dcdf-1ad2-46a8-8411-03ff712bbf55.webm)

**Comment by diegonvs** [comment]
ci:test:relevant

**Comment by diegonvs** [comment]
So, I need help for clear steps of reproduction :/

**Comment by diegonvs** [comment]
ci:test:relevant

**Comment by diegonvs** [comment]
ci:test:sf

**Comment by diegonvs** [comment]
Hey, analyzing the diff here, I tried to review every use case of document-library-web and I couldn't find anything wrong. I'll run again relevant suite and then ask someone from QA to give me a hand in analyzing how to reproduce at least one of these errors on document-library-web :)

**Comment by diegonvs** [comment]
ci:test:relevant

**Comment by susanchen3** [comment]
Based on the [diff](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=2&testrayRunIdB=1906049846&testrayRunIdA=1904940329&statusB=3), looks like Document Management tests all `Failed prior to running test` and in the logs I see 
```
[beanshell] java.lang.RuntimeException: java.io.IOException: Premature EOF
```
which is a connection issue, so hopefully the next run will yield better results :) But I don't see any unique test failures on this relevant run. :heavy_check_mark:

**Comment by susanchen3** [comment]
ci:test:relevant

**Comment by susanchen3** [comment]
Taking a look now :detective:

**Comment by susanchen3** [comment]
Reviewed, test failures unrelated :heavy_check_mark: Looks good to manually forward from QA perspective after conflicting files are fixed :) :hammer: 

[**Comparison run:** ](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=2&testrayRunIdB=1908412068&testrayRunIdA=1909853384&statusB=3)

**Not unique:**
- com.liferay.document.library.info.display.contributor.test.FileEntryInfoDisplayContributorTest
- com.liferay.dynamic.data.mapping.data.provider.test.DDMRESTDataProviderTest
- LocalFile.Tabs#ViewTopperBarWhenSwitchToOtherTabs
- LocalFile.OpenIDConnect#OpenIDConnectSmokeWithAuth0
- com.liferay.company.service.test.CompanyLocalServiceTest

**Aborted prior to running test, passes locally:**
- All the data engine tests
- LocalFile.LocalizationWithWebContentUI#AddWebContentWithSpanishTranslation

**Comment by diegonvs** [comment]
ci:test:relevant

**Comment by diegonvs** [comment]
Conflicts solved, and I'll send manually if CI passes or not. I decided to run CI again because we are going to have time(while I rest 😂 ), and I prefer to send it from forwarding instead of manually.

**Comment by diegonvs** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/120606

**Pull request closed without merging**
