### PR TITLE
LPS-118563 Add token translation to theme-classic

### PR DESCRIPTION
**Pull request by eduardoallegrini**
With this PR, we are adding the missing options of the [Style Editor design](https://www.figma.com/file/47O0VcSpvNbFi3imoVdZqX/Token-categorization-in-a-Style-Book?node-id=0%3A1v)

---

From @marcoscv-work  in  https://github.com/liferay-frontend/liferay-portal/pull/212

To test this PR you can:

- Open your liferay portal
- Edit the Home page (content page) / Create a new content page
- Add an HTML fragment to the page
- Doble click over the HTML fragment
- Paste this HTML:
```html
<h1 class="my-5">Aspect ratios:</h1>

<div class="row">
    <div class="col-3">
    	<h6>1:1</h6>
    	<div class="aspect-ratio bg-secondary"></div>
    </div>
    <div class="col-3">
    	<h6>16:9</h6>
    	<div class="aspect-ratio aspect-ratio-16-to-9 bg-secondary"></div>
    </div>
    <div class="col-3">
    	<h6>8:3</h6>
    	<div class="aspect-ratio aspect-ratio-8-to-3 bg-secondary"></div>
    </div>
    <div class="col-3">
    	<h6>4:3</h6>
    	<div class="aspect-ratio aspect-ratio-4-to-3 bg-secondary"></div>
    </div>
</div>

<h1 class="my-5">Transitions:</h1>

<h2>.collapsing</h2>
<div class="collapsing">collapsing</div>
<h2>.fade</h2>
<div class="fade">fade</div>

<h1 class="my-5">Display texts:</h1>

<div class="display-1">
    display-1
</div>
<div class="display-2">
    display-2
</div>
<div class="display-3">
    display-3
</div>
<div class="display-4">
    display-4
</div>

<h1 class="my-5">Lead text:</h1>

<div class="lead">
    Lead
</div>
<h1 class="lead">
    Lead in a H1
</h1>

<h1 class="my-5">text-muted:</h1>

<div class="text-muted">Text muted</div>
<h1 class="text-muted">Text muted in as H1</h1>

<h1 class="my-5">Blockquotes:</h1>

<div class="blockquote">blockquote</div>
<div class="blockquote-footer">blockquote-footer</div>

<h1 class="my-5">Separator:</h1>

<hr>
```
- Inspect each component and see custom properties are applied
- Uncheck custom properties styles and check everything works in the same way
image

**Problems we already know:**

- The separator has an issue in Clay about the `border: 0` order

### CODE REVIEW

**Comment by eduardoallegrini** [comment]
ci:test:sf

**Comment by eduardoallegrini** [comment]
ci:test:relevant

**Comment by marcoscv-work** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcoscv-work** [comment]
LGTM

**Comment by eduardoallegrini** [comment]
ci:forward

**Comment by john-co** [comment]
ci:test:norebase:bundle

**Pull request closed without merging**
