### PR TITLE
LPS-134654 Use HtmlUtil.escapeAttribute instead of HtmlUtil.escape

### PR DESCRIPTION
**Pull request by julien**
As noted in [LPS-134654](https://issues.liferay.com/browse/LPS-134654),
we should use `HtmlUtil.escapeAttribute` instead of `HtmlUtil.escape`,
since `searchValue` is being used as an attribute.

### CODE REVIEW

**Review by carloslancha — APPROVED** [review]
LGTM

**Comment by carloslancha** [comment]
ci:forward

**Review by jonmak08 — APPROVED** [review]

**Comment by jonmak08** [comment]
ci:test:relevant

**Comment by jonmak08** [comment]
ci:test:relevant

**Comment by jonmak08** [comment]
ci:forward

**Pull request closed without merging**
