### PR TITLE
LPD-19711 Remove, already covered by playwright (see dataSets.spec.ts)

### PR DESCRIPTION
**Pull request by dsanz**
Reference: 
 * https://liferay.atlassian.net/browse/LPD-19710

We don't need those anymore

### CODE REVIEW

**Comment by dsanz** [comment]
ci:test:sf

**Comment by dsanz** [comment]
ci:test:frontend-data-set

**Comment by dsanz** [comment]
ci:test:playwright

**Comment by juanjofgliferay** [comment]
:fire:

**Review by bryceosterhaus — APPROVED** [review]

**Comment by dsanz** [comment]
ci:forward:force

**Pull request closed without merging**
