### PR TITLE
LPS-168199 Update Alloy Editor to v2.14.9

### PR DESCRIPTION
**Pull request by markocikos**
## What's Changed
* fix: avoid null on init and destroy the editor too fast makes the DOM is not loaded by @binhtran92 in https://github.com/liferay/alloy-editor/pull/1541
* fix: Calculate the offsetHeight for the toolbar only when the table is used by @orsolyaDekany in https://github.com/liferay/alloy-editor/pull/1543
* chore(deps-dev): bump karma from 4.0.0 to 6.4.1 by @dependabot in https://github.com/liferay/alloy-editor/pull/1540

## New Contributors
* @binhtran92 made their first contribution in https://github.com/liferay/alloy-editor/pull/1541
* @dependabot made their first contribution in https://github.com/liferay/alloy-editor/pull/1540

**Full Changelog**: https://github.com/liferay/alloy-editor/compare/v2.14.8...v2.14.9

### CODE REVIEW

**Comment by markocikos** [comment]
ci:test:relevant

**Comment by eltonccdantas** [comment]
Hi @markocikos, I've analyzed the errors and they look unrelated to your PR according to the [comparison](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1668202834783&testrayRunIdA=2046948947&testrayRunIdB=2047804069). You may manually forward if no other dev review is needed.

**Comment by markocikos** [comment]
I'll give it one more try. If it fails, I'll manually forward.

**Comment by markocikos** [comment]
ci:forward

**Comment by markocikos** [comment]
Manual forward: https://github.com/brianchandotcom/liferay-portal/pull/126258

**Pull request closed without merging**
