### PR TITLE
LPS-137967 Add serviceContext attribute to handle message board notifications redirections with urlSubject

### PR DESCRIPTION
**Pull request by LuismiBarcos**
Related ticket -> [LPS-137967](https://issues.liferay.com/browse/LPS-137967)

The bug is related to the redirection of the notifications in Questions. When a user is subscribed to a tag and a second user creates a new question with that tag, the notification link is not navigating to the new question but to the questions list instead.

**Steps to reproduce:**
- UserA subscribed to a tag from questions
- As userB creates a question using the subscribed tag
- Login as userA
- Go to the notifications and click on it

**Expected Result:**
It is better for a user can navigate to the questions details.

**Actual Result:**
Users can navigate to the questions list page.

---
With this PR, I am adding a new attribute to serviceContext so I can create the URL of the redirection in the service.

### CODE REVIEW

**Comment by LuismiBarcos** [comment]
This is the first implementation to "make things work". I open it as a Draft because I suppose that there is a better way to do this, so, we can discuss the implementation.

**Review by javierdearcos — APPROVED** [review]
Don't know why my review wasn't published on Friday...

In my opinion, we don't have so much room and we are using the same procedure used by Message Boards Porlet, so it is a good solution for me and it is clean.

My thoughts are about the usage of a new attribute name. It is **"entryUrl"** used anywhere else in the code? 

If it is, as it takes precedence over **"link"**, the code to concat to entryUrl could be execute although we are using link from Questions App

If not, we can reuse the same attribute name or remove the code.

We can leave it to be sure we don't break anything, but then at least, we have to analyze the usage to be sure we want to take precedence over the new **"link"** attribute used from Questions

**Comment by LuismiBarcos** [comment]
I'm a little confused with that. I've been looking for the usages of the `entryURL` in message boards and I found nothing except in the code I am changing and in one test. But I am not sure if we can delete the code because use `entryURL` seems a common pattern in MB, Blogs, DL...

About the order, I saw that `entryURL` is always the first attribute to check. Looks like if there is an `entryURL` it means that is the final URL to use.

So, for me, place the `link` attribute after `entryURL` is not a bad option. Also, Questions use the headless APIs that is where we created the `serviceContext` but now we are not setting the `entryURL`

**Review by nhpatt — APPROVED** [review]
Reviewed and LGTM :D

I don't love to modify existing MB code but I don't see a better way...

Maybe we could disable the notifications and we launch them manually with a completely filled entryURL... but it would be messy.

I saw that entryURL is being used and that we can not reuse it. And that the problem is concatenating the subject. So... LGTM :D

About:

> If it is, as it takes precedence over "link", the code to concat to entryUrl could be execute although we are using link from Questions App

I think it's being used internally in MB and potentially for clients.

If not, we can reuse the same attribute name or remove the code.

> We can't, it would break clients as ServiceContext is public API.

We can leave it to be sure we don't break anything, but then at least, we have to analyze the usage to be sure we want to take precedence over the new "link" attribute used from Questions

> I would go entryURL first (as it is the existing behaviour), our behaviour last.

**Comment by LuismiBarcos** [comment]
Rebase and forward

**Comment by LuismiBarcos** [comment]
ci:forward

**Comment by LuismiBarcos** [comment]
ci:reevaluate:1257401_181

**Comment by LuismiBarcos** [comment]
Not possible to reproduce in local. New try with the CI. If not, we go with a deeper investigation of the failed test.

**Comment by LuismiBarcos** [comment]
ci:forward

**Comment by javierdearcos** [comment]
ci:test:relevant

**Comment by liuxingye** [comment]
ci:test:relevant

**Comment by javierdearcos** [comment]
ci:forward

**Pull request closed without merging**
