### PR TITLE
LPD-30306 Fix failing test in DataSetViewSorting

### PR DESCRIPTION
**Pull request by thektan**
https://liferay.atlassian.net/browse/LPD-30306

Rebased and changed the branch name from https://github.com/liferay-frontend/liferay-portal/pull/4311 to see if this'll get ci:test:relevant to run

### CODE REVIEW

**Comment by thektan** [comment]
ci:test:relevant

**Comment by thektan** [comment]
ci:test:playwright

**Comment by thektan** [comment]
@dsanz I found out that if the PR only has poshi/playwright changes, `ci:test:relevant` does not run. https://liferay.slack.com/archives/C19PWQ74J/p1720194223755869?thread_ts=1720102020.400699&cid=C19PWQ74J

I'll run `ci:test:playwright` to make sure the playwright tests pass in CI and then forward this PR.

**Comment by thektan** [comment]
None of the failures seem related, but I'll run it once again in case there was anything flaky.

**Comment by thektan** [comment]
ci:test:playwright

**Comment by dsanz** [comment]
ci:forward

**Pull request closed without merging**
