### PR TITLE
LPS-118339 Fix harmless typo in regex pattern match

### PR DESCRIPTION
**Pull request by wincent**
This was a copy-paste error from another place where we had this pattern:

    /\.tsx?$/

(ie. to match ".ts" or ".tsx"). We deleted the "x" because this module only has ".ts" files, but we should have deleted the "?" as well, otherwise the pattern matches both ".ts" and ".t" (the latter of which is not a valid extension).

### CODE REVIEW

**Comment by wincent** [comment]
I _accidentally_ sent this directly to Brian's fork, creating [PR #10000](https://github.com/brianchandotcom/liferay-portal/pull/100000). Sending it through here The Right Way™ now.

accidentally

(Just something I noticed the other day.)

**Comment by jbalsas** [comment]
> I _accidentally_ sent this directly to Brian's fork, creating PR #10000. Sending it through here The Right Way™ now.

ohyea

**Comment by jbalsas** [comment]
I see green I forward

**Comment by jbalsas** [comment]
ci:forward

**Pull request closed without merging**
