### PR TITLE
LPS-143179 Extend FDS API with data providers

### PR DESCRIPTION
**Pull request by markocikos**
JIRA: https://issues.liferay.com/browse/LPS-143179

API extension is required to migrate FDS to `objects-web`. PR contains missing API for data providers. I'm sending this first to be the least disruptive to the objects team, as there may be iterations with API. After this is merged, I'll send the migration part to the product team fork.

There is no change in logic in this PR, just the rename and repackage. The code is not yet used anywhere. **Feel free to forward if CI is green.**

For context, [here](https://github.com/liferay/liferay-portal/blob/master/modules/apps/object/object-web/src/main/java/com/liferay/object/web/internal/object/entries/frontend/taglib/clay/data/set/data/provider/RelatedModelsDataSetDataProvider.java#L54-L57) is an example how data provider is currently used:
```java
public List<RelatedModel> getItems(
		HttpServletRequest httpServletRequest, Filter filter,
		Pagination pagination, Sort sort)
	throws PortalException {
```

I made two notable changes to `Filter*`:
- I renamed `Filter*` classes to `FDSKeywords*`. I feel that [Filter.java](https://github.com/liferay/liferay-portal/blob/master/modules/apps/frontend-taglib/frontend-taglib-clay/src/main/java/com/liferay/frontend/taglib/clay/data/Filter.java) is too similar to [FDSFilter.java](https://github.com/liferay/liferay-portal/blob/master/modules/apps/frontend-data-set/frontend-data-set-api/src/main/java/com/liferay/frontend/data/set/filter/FDSFilter.java), they have misleadingly similar names. `Filter` is a simple keywords data filter, and `FDSFilter` is a model for frontend component that allows multiple ways of filtering.
- I placed `FDSKeywords` and `FDSPagination` in the `search` subpackage, to mirror `com.liferay.portal.kernel.search.Sort`, used in the same way.

/cc @LuismiBarcos @javierdearcos @eli-rlima

### CODE REVIEW

**Comment by eli-rlima** [comment]
cc: @guilhermedcamacho @gabrielwas

**Review by nhpatt — APPROVED** [review]
Looks very good, nothing horrible to me. LNHTM.

**Comment by markocikos** [comment]
CI failure in https://github.com/liferay-frontend/liferay-portal/pull/1711#issuecomment-982883869 was very much related, I forgot to update semver. Force-pushed with semver update in https://github.com/liferay-frontend/liferay-portal/pull/1711/commits/69f68c80c7c0668575c2bffc70aafba4492317d0

**Comment by markocikos** [comment]
ci:forward

**Review by javierdearcos — APPROVED** [review]

**Comment by markocikos** [comment]
ci:forward

**Pull request closed without merging**
