### PR TITLE
LPS-138476 Replace A.merge with the spread operator

### PR DESCRIPTION
**Pull request by kresimir-coko**
This is a resend after the previous PR has been reverted in https://github.com/liferay-workflow/liferay-portal/pull/598

I've modified all mentions of `Object.assign(obj1, obj2)` to instead create an empty object in which to combine the `obj1` and `obj2` as the initial implementation without the empty object proved to cause issues because of mutations.

I have tested these changes in the 2 reported (in the linked PR) places, and I can test further if you feel like there is need.

### CODE REVIEW

**Comment by kresimir-coko** [comment]
ci:test:sf

**Comment by kresimir-coko** [comment]
Setting as a draft until I confirm this doesn't re-introduce the bug reported in https://github.com/liferay-frontend/liferay-portal/pull/1633.

**Comment by kresimir-coko** [comment]
This is definitely causing issues reported in #1633.

My investigation revealed that `Object.assign` works well and doesn't cause the bug to happen, whereas the spread operator (`...`) does. So, in this case, our source formatter is changing the code where we don't want it to, as its the thing that's forcing the spread operator instead of the `Object.assign`.

I've ignored the rule on those lines so that it doesn't autofix the `Object.assign` to `...`

**Comment by kresimir-coko** [comment]
ci:test:sf

**Comment by kresimir-coko** [comment]
ci:test:relevant

**Comment by kresimir-coko** [comment]
I've changed some spread operator source formatter fixes and tested how the code works with the reported bugs.

The conclusion is that `A.mix` cannot be replaced with the spread operator `...` to create the required object, but `Object.assign` still works. So, I had to ignore the autofixing where we changed `A.mix`.

From my testing this is good for merging 👍

**Comment by kresimir-coko** [comment]
ci:test:sf

**Comment by kresimir-coko** [comment]
ci:test:relevant

**Comment by kresimir-coko** [comment]
ci:reevaluate:1027401_917

**Comment by sergiojimcos** [comment]
ci:bundle

**Comment by sergiojimcos** [comment]
ci:reevaluate:1027401_917

**Comment by sergiojimcos** [comment]
ci:test:relevant

**Comment by sergiojimcos** [comment]
Hi @kresimir-coko. Tests Reviewed.✔️
Ok to manually forward.

[Unrelated]

- [WidgetPagesUseCase#CannotViewPrivatePageAsUserWithoutPermissions](https://testray.liferay.com/reports/production/logs/2021-11/test-1-2/test-portal-acceptance-pullrequest(master)/917/functional-tomcat90-mysql57-jdk8/7/11/LocalFile.WidgetPagesUseCase_CannotViewPrivatePageAsUserWithoutPermissions/summary.html.gz). This tests cannot continue once the email has been changed.

- [WorkflowMetrics#ApplyPaginationOnBulkReassign](https://testray.liferay.com/reports/production/logs/2021-11/test-1-2/test-portal-acceptance-pullrequest(master)/917/functional-tomcat90-mysql57-jdk8/7/17/LocalFile.WorkflowMetrics_ApplyPaginationOnBulkReassign/summary.html.gz). Doesn't navigate to Applications Menu.

[Related]

- [FormsRulesActions#CanUtilizeDataProvidersInAutofillRule](https://testray.liferay.com/reports/production/logs/2021-11/test-1-2/test-portal-acceptance-pullrequest(master)/917/functional-tomcat90-mysql57-jdk8/3/17/LocalFile.FormsRulesActions_CanUtilizeDataProvidersInAutofillRule/summary.html.gz). Once the Form edition is completed, the test fails.

**Comment by kresimir-coko** [comment]
@sergiojimcos hey, in which module/file is the related test failing? I can't find it in the Jenkins UI. This PR touches a decent amount of files so if you could narrow it down for me that would be great!

**Comment by sergiojimcos** [comment]
> @sergiojimcos hey, in which module/file is the related test failing? I can't find it in the Jenkins UI. This PR touches a decent amount of files so if you could narrow it down for me that would be great!

**Comment by sergiojimcos** [comment]
Hey @kresimir-coko, sorry for not link you the Poshi Summary of the FormsRulesActions#CanUtilizeDataProvidersInAutofillRule ([link here](https://testray.liferay.com/reports/production/logs/2021-11/test-1-2/test-portal-acceptance-pullrequest(master)/917/functional-tomcat90-mysql57-jdk8/3/17/LocalFile.FormsRulesActions_CanUtilizeDataProvidersInAutofillRule/summary.html.gz)). As I saw in the test, the problem is edition Form, it could be in modules/dxp/apps/portal-workflow/portal-workflow-kaleo-designer-web/src/main/resources/META-INF/resources/designer/js/legacy/editors.js and those related. However, I will analyse the rest of the files and try to detect the problem

**Comment by kresimir-coko** [comment]
>  it could be in modules/dxp/apps/portal-workflow/portal-workflow-kaleo-designer-web/src/main/resources/META-INF/resources/designer/js/legacy/editors.js

Thank you @sergiojimcos it's probably that one, yea, thanks for following up

**Comment by kresimir-coko** [comment]
So I ignored the rule that lints against `A.merge` usages inside the `editors.js` file. So let's see if that was the problem. I tried replicating the test but couldn't replicate the problem.

**Comment by kresimir-coko** [comment]
ci:test:sf

**Comment by kresimir-coko** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
ci:forward

**Pull request closed without merging**
