### PR TITLE
LPS-183945 | Automation for DatasetPagination

### PR DESCRIPTION
**Pull request by abhnerramos**
**Description**
Automation for
DatasetPagination#CanAssertDefaultValueIsRequired ([LPS-183945](https://issues.liferay.com/browse/LPS-183945))
DatasetPagination#DefaultValueCannotDivergeFromPaginationItems ([LPS-183946](https://issues.liferay.com/browse/LPS-183946))
DatasetPagination#CanCreatePagination ([LPS-183947](https://issues.liferay.com/browse/LPS-183947))

**JIRA Ticket**
https://issues.liferay.com/browse/LPS-183945

### CODE REVIEW

**Comment by abhnerramos** [comment]
ci:stop

**Comment by abhnerramos** [comment]
ci:test:frontend-data-set

**Review by CarlosBrichete — APPROVED** [review]

**Comment by CarlosBrichete** [comment]
LGTM :)

**Comment by abhnerramos** [comment]
ci:foward

**Pull request closed without merging**
