### PR TITLE
LPS-147499, LPS-147946 | Initial Translation Manager tests

### PR DESCRIPTION
**Pull request by john-co**
**Background**
Create automation tests for Translation Manager

**Test Plan**

Create a page with the widget JS Components Sample
Click and view select translation language menu
Assert the default language is available and no other languages options
Click Manage Translations
Assert the link to Manage Translations is available

**JIRA Ticket:**
https://issues.liferay.com/browse/LPS-147499

**Background**
Create automation tests for Translation Manager

**Test Plan**

Create a page with the widget JS Components Sample
Click translation selector of Admin mode
Search language and the list will filter the results using Code and Language fields
Delete language  and the language will be deleted from the Manage Translation list

**JIRA Ticket:**
https://issues.liferay.com/browse/LPS-147946

### CODE REVIEW

**Comment by john-co** [comment]
@Hijky , please see refactored tests. I removed LPS-147612 because I think it was just a poorly written test to begin with and we needed to remove it completely as requested [here](https://github.com/liferay-frontend/liferay-portal/pull/1930#discussion_r814132630). I need to go back and revise the Given When Then so it's a more clear and useful test.

**Comment by john-co** [comment]
ci:test:frontend

**Comment by john-co** [comment]
ci:stop

**Comment by john-co** [comment]
ci:test:sf

**Comment by john-co** [comment]
ci:test:relevant

**Comment by john-co** [comment]
ci:test:frontend:nocompile

**Comment by Hijky** [comment]
> 
About side by side, I have deleted it, now LPS-147612 is about another case
https://issues.liferay.com/browse/LPS-147612

**Comment by john-co** [comment]
ci:test:sf

**Comment by john-co** [comment]
ci:test:frontend:nocompile

**Comment by Hijky** [comment]
> @Hijky , please see refactored tests. I removed LPS-147612 because I think it was just a poorly written test to begin with and we needed to remove it completely as requested [here](https://github.com/liferay-frontend/liferay-portal/pull/1930#discussion_r814132630). I need to go back and revise the Given When Then so it's a more clear and useful test.

About side by side, I have deleted it, now LPS-147612 is about another case
https://issues.liferay.com/browse/LPS-147612

**Comment by john-co** [comment]
> About side by side, I have deleted it, now LPS-147612 is about another case
> https://issues.liferay.com/browse/LPS-147612

I see yea, it was a little confusing to keep the LPS. However, I still think the test itself doesn't validate anything important. I for those form fields it's better to check that other form fields and localization buttons also change translations in unison.

ie:
https://user-images.githubusercontent.com/35235266/157358808-f37eb408-e7b8-4ef6-99c8-333940e27c3f.mp4

**Comment by john-co** [comment]
ci:test:sf

**Comment by Hijky** [comment]
> 

I understand it, the case need test all of them to be synchronized both in terms of current selection and available languages

**Comment by Hijky** [comment]
when this pull is merged, could I re-write the case to check that other form fields and localization buttons also change translations in unison?

**Comment by john-co** [comment]
> when this pull is merged, could I re-write the case to check that other form fields and localization buttons also change translations in unison?
of course, go for it :)

**Comment by john-co** [comment]
ci:test:frontend:nocompile

**Comment by john-co** [comment]
Tests pass :heavy_check_mark:

**Comment by john-co** [comment]
ci:forward

**Review by zhangyan0701 — APPROVED** [review]

**Comment by john-co** [comment]
ci:test:sf

**Comment by john-co** [comment]
one of these days...

**Comment by john-co** [comment]
ci:forward

**Pull request closed without merging**
