### PR TITLE
LPS-127356

### PR DESCRIPTION
**Pull request by izaera**
This is part of the final PR to support webpack bundling. It contains commits to support both models (bundler+webpack) in some of our infrastructure components.

### CODE REVIEW

**Comment by izaera** [comment]
Shall we forward this? It has passed the tests :tada:

**Comment by jbalsas** [comment]
Hey @izaera, I don't see why not forward this, but could you explain:
- Do we **really** need to update `SoyRenderer`?  I wouldn't think anyone's using it and the goal is to remove that before the release, so maybe that's unnecessary?
- Just to confirm, the change in `DefineObjects` allows us to keep the `resolvedPackageName` variable in JSPs even if that's not a bundlerv2 module?

**Comment by izaera** [comment]
> Do we really need to update SoyRenderer? I wouldn't think anyone's using it and the goal is to remove that before the release, so maybe that's unnecessary?

Yes, unless we remove soy completely from all our libraries (it is still used in, at least, the ManagementToolbar; and I don't know if in some other places too). But because that would block the epic, I prefer to add the support now and remove it once the other task is finished.

In general I'm planning to do the same for all other things: add dual support now to avoid blockage of the higher priority tasks (the ones that let us migrate 99% of the portal). 

The, once we remove all dependencies to the old model we can do another PR to remove all dual supports. They are centralized in infrastructure so it shouldn't be too complex.

**Comment by izaera** [comment]
> Just to confirm, the change in DefineObjects allows us to keep the resolvedPackageName variable in JSPs even if that's not a bundlerv2 module?

Yes. 

The idea is that, because our tags have dual support and autodetect if a module name is webpack-based or bundler-based, if we set `npmResolvedPackageName` to the name of the package (without version of namespace) for webpack-based modules the tags will detect it and they will work.

That way we don't need to change the code. And having the `npmResolvedPackageName` variable is still useful in some cases, so maybe we want to keep it even if we finish the epic.

**Comment by izaera** [comment]
ci:forward

**Pull request closed without merging**
