### PR TITLE
LPS-165301 Update alloy-ui to 3.1.0-deprecated.106

### PR DESCRIPTION
**Pull request by georgel-pop-lr**

### CODE REVIEW

**Comment by georgel-pop-lr** [comment]
ci:test:relevant

**Comment by diegonvs** [comment]
ci:forward

**Review by diegonvs — APPROVED** [review]

**Comment by markocikos** [comment]
ci:forward

**Comment by markocikos** [comment]
ci:forward

**Comment by georgel-pop-lr** [comment]
ci:test:sf

**Comment by georgel-pop-lr** [comment]
ci:forward

**Comment by mateusralv** [comment]
Hey @georgel-pop-lr the failures are not related to your PR 🎉 🚀 . Safe to forward from QA perspective

[comparison run with the master](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1666893510264&testrayRunIdA=2018383266&testrayRunIdB=2017699237)

**Comment by georgel-pop-lr** [comment]
Manually forwarded https://github.com/brianchandotcom/liferay-portal/pull/125514

**Comment by georgel-pop-lr** [comment]
> Hey @georgel-pop-lr the failures are not related to your PR tada rocket . Safe to forward from QA perspective
> 
> [comparison run with the master](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1666893510264&testrayRunIdA=2018383266&testrayRunIdB=2017699237)

Manually forwarded https://github.com/brianchandotcom/liferay-portal/pull/125514

**Pull request closed without merging**
