### PR TITLE
LPS-169282 Fix accessibility problems with the hidden legend

### PR DESCRIPTION
**Pull request by claraizquierdo**
Motivation
=======
JAWS read the hidden legend as a navigable element
[Link to story or ticket](https://issues.liferay.com/browse/LPS-169282)

Proposed Solution
========
The solution is the same we did for https://github.com/liferay-frontend/liferay-portal/pull/3228. We have replaced the `<fieldset>` element with `<div role=“group”>` , removed the legend element and added an aria-label to the `<div role=“group”>` with the text that the legend had.

Steps to Verify:
----------------
1. Navigate to Site Builder->Pages and add a page
2. Navigation to Global templates
3. Add a new Global template
4. Input the page name
5. Navigate to the General tab
6. Use jaws
7. Using the arrow key to traverse the page

### CODE REVIEW

**Comment by eltonccdantas** [comment]
Let me take a look at it 🕵🏻‍♂️

**Comment by claraizquierdo** [comment]
Hi @eltonccdantas , thank you for your review :) Did you find any bug or the tests fail just because the xpaths should be updated?

**Comment by eltonccdantas** [comment]
> Hi @eltonccdantas , thank you for your review :) Did you find any bug or the tests fail just because the xpaths should be updated?

We are going to see what the best solution is... that's what I'm going to find out now

**Comment by eltonccdantas** [comment]
Hey @claraizquierdo , I decided to split the fix by components, I also tried to add/modify as little as possible. So let's run relevant for each change.

**Comment by eltonccdantas** [comment]
ci:test:relevant

**Comment by eltonccdantas** [comment]
ci:test:relevant

**Comment by eltonccdantas** [comment]
ci:test:relevant

**Comment by eltonccdantas** [comment]
I download the bundle again and the tests are mysteriously passing locally.

**Comment by eltonccdantas** [comment]
ci:test:relevant

**Comment by manoelcyreno** [comment]
ci:test:relevant

**Comment by manoelcyreno** [comment]
ci:test:frontend

**Comment by nikki-pru** [comment]
ci:test:stable

**Comment by nikki-pru** [comment]
ci:test:relevant

**Comment by nikki-pru** [comment]
ci:test:relevant

**Comment by eltonccdantas** [comment]
ci:test:relevant

**Review by markocikos — APPROVED** [review]
LGTM! :sparkles:

**Comment by markocikos** [comment]
@eltonccdantas feel free to forward, after CI issues are resolved.

**Comment by eltonccdantas** [comment]
I think that should be enough to fix it, the remaining failures look unrelated this pull request

[Comparison run](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=2&testrayRunIdB=2306010810&testrayRunIdA=2305219059&statusB=3)

[testray-results (#3267)](https://github.com/liferay-frontend/liferay-portal/files/11497659/testray-results.3267.csv)

[VLOOKUP](https://docs.google.com/spreadsheets/d/1k6EZ4aSrdonuZ7DuRXwx1P4O_OdkJjq1/edit?usp=sharing&ouid=101533607319431228990&rtpof=true&sd=true) to find similar errors

**Comment by eltonccdantas** [comment]
ci:forward

**Comment by eltonccdantas** [comment]
ci:forward:force

**Comment by eltonccdantas** [comment]
ci:forward:force

**Comment by eltonccdantas** [comment]
ci:forward:force

**Comment by eltonccdantas** [comment]
ci:forward:force

**Comment by eltonccdantas** [comment]
Manually forwarded to BChan

**Pull request closed without merging**
