### PR TITLE
LPS 174379 - Frontend Data Set Sample Tab Elements | Critical Accessibility Issue - Ensure elements with an ARIA role that require parent roles are contained by them

### PR DESCRIPTION
**Pull request by Youness-ELMO**
**References**
[LPS-174379 : Frontend Data Set Sample Tab Elements | Critical Accessibility Issue - Ensure elements with an ARIA role that require parent roles are contained by them](https://liferay.atlassian.net/browse/LPS-174379)

**What is the goal of this PR?**
The goal of this PR is to add an attribute role to the elements lists to fix the accessibility issue.

**### Before PR**
image

**### After PR**
image

### CODE REVIEW

**Comment by Youness-ELMO** [comment]
ci:test:sf

**Review by markocikos — APPROVED** [review]
@Youness-ELMO LGTM! :sparkles:

**Comment by markocikos** [comment]
ci:forward

**Comment by mateusralv** [comment]
Hi @markocikos The failures are not related.

[Testray Comparison](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1700681774920&testrayRunIdA=2458326740&testrayRunIdB=2458367044)

**Comment by markocikos** [comment]
ci:forward:force

**Pull request closed without merging**
