### PR TITLE
[TS] LPS-159323

### PR DESCRIPTION
**Pull request by crodriguezy**
Hello team,

This update fixes the case described in https://issues.liferay.com/browse/LPS-159323:

1. Start the portal and add the ca/ locale to URL.
2. Create a new basic web content:
3. Go to Schedule section and select a date.

**Expected result**: week days starts on Monday (Dl)

**Current result:** week days starts on Tuesday (Dt):
image

The corresponding change was already merged in https://issues.liferay.com/browse/AUI-3213 and new version of alloyUI was released (3.1.0-dprecated.101)

### CODE REVIEW

**Comment by diegonvs** [comment]
ci:test:relevant

**Comment by mateusralv** [comment]
I’m taking a look at failures 🕵🏽

**Comment by mateusralv** [comment]
Hi @diegonvs, I made [comparison with the master](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1660152922801&testrayRunIdA=1941666775&testrayRunIdB=1941502104) and resulting failures are not related to PR 🎉

**Comment by diegonvs** [comment]
Thanks @mateusralv 😘 

Hey @crodriguezy, could you forward manually to Brian? Thanks :)

**Comment by susanchen3** [comment]
Closing PR as it was manually forwarded and [merged by bchan](https://github.com/brianchandotcom/liferay-portal/pull/121544), thanks! :)

**Pull request closed without merging**
