### PR TITLE
LPD-41254 Extract inline event handlers in <aui:input>, <liferay-ui:input-resource> and <liferay-ui:input-checkbox> 

### PR DESCRIPTION
**Pull request by izaera**
**QA Passed**: https://github.com/liferay-frontend/liferay-portal/pull/4567#issuecomment-2485775876 

----

This is part of https://github.com/liferay-frontend/liferay-portal/pull/4466 (root PR for CSP inline event handlers).

It is in the high risk group, which is composed of infra stuff used pervasively that may break a lot of tests for different teams.

> ⚠️ Note that even though this PR may break tests it doesn't mean it breaks the product.
> Tests can break because:
>
> 1. A bug is introduced in the product, or
> 2. They rely on internals of the taglib changed in the PR

Since the taglib is used almost everywhere we don't have any specific CI test suite to run (we would need to run all of them to make sure). And since we run all tests suites every day on a batch schedule we will rely on that to detect big failures unless someone can find a better way (I'm open to suggestions).

In any case, I've tested one occurence of the tag by hand following the procedures described at https://liferay.atlassian.net/browse/LPD-41254?focusedCommentId=2790515 and below to make sure it's not very badly broken.

### CODE REVIEW

**Comment by izaera** [comment]
ci:test:relevant

**Review by juanjofgliferay — APPROVED** [review]
LGTM :rocket:

**Comment by izaera** [comment]
ci:forward

**Comment by izaera** [comment]
ci:forward:force

**Comment by izaera** [comment]
ci:forward:force

**Comment by izaera** [comment]
ci:forward:force

**Comment by izaera** [comment]
ci:forward:force

**Pull request closed without merging**
