### PR TITLE
LPS-204486 Adding role menu to the list to avoid accessibility issues

### PR DESCRIPTION
**Pull request by antonio-ortega**
Solution according to this [suggestion](https://liferay.atlassian.net/browse/LPP-52092?focusedCommentId=2542611).

We are only using this taglib in our Login Portlet. Nowhere else.

### CODE REVIEW

**Comment by antonio-ortega** [comment]
ci:test:sf

**Comment by antonio-ortega** [comment]
ci:test:relevant

**Comment by dsanz** [comment]
LGTM ;)

**Review by markocikos — APPROVED** [review]
@antonio-ortega LGTM! :sparkles:

**Comment by antonio-ortega** [comment]
ci:test:relevant

**Comment by antonio-ortega** [comment]
ci:test:relevant

**Comment by antonio-ortega** [comment]
ci:forward:force

**Pull request closed without merging**
