### PR TITLE
LPD-38760 Editor in blogs cannot display image added via item selector URL

### PR DESCRIPTION
**Pull request by boton**
# What is this trying to solve?

https://liferay.atlassian.net/browse/LPD-38760

Currently, when an image is added via a URL in the blog editor, it fails to display correctly in edit mode. Additionally, inserting a new image after a URL-based one either hides or removes the previous image, complicating content editing and causing the DOM to retain unnecessary elements, thus increasing page weight.

# How am I fixing it? (Temporary but Impactful)

This fix adjusts selectors to target elements with inline src data, ensuring that hidden images are removed in case of an error. This approach closely follows the original fix that introduced this behavior but adds specificity to avoid redundant image accumulation. While this is a temporary solution, it significantly reduces the problem.

>[!WARNING] 
> Limitation: This fix does not cover cases where inline data (e.g., base64) is used directly in the src attribute.

# How can you verify that it works?

Run the POSHI test `ItemSelector#CanAddBlogsImageViaURL`

## Before the PR
image

## After the PR
image

# Alternative Approach (Long-Term Solution)

A more robust, permanent solution would be to prevent CKEditor from automatically inserting images through the addImages plugin. This approach fixes the root cause by controlling image insertions during pasting events. 

However, I lack the expertise to effectively configure this behavior, and attempting such changes could lead to complex compatibility issues. 

## Issues with the Alternative Solution:

Disabling the automatic paste functionality might inadvertently disrupt modules like Knowledge Base and Web Content..., where the paste is working on **CKEditor default paste**.

Currently, while the addImages plugin is technically initiated, it does not actively perform any actions in these other modules. This suggests that while the plugin is present, it remains inactive and works over **CKEditor default paste** (base64 inline images).

**Configurations**: This plugin was added in the following configurations:
   - `BaseAlloyEditorConfigContributor.java`
   - `CKEditorConfigContributor.java`
   - `LayoutTranslateEditorConfigContributor.java`
   - DDM Configurations

---

>[!NOTE]
> **CSS File**: I try to move the blog CSS to the editor CSS so that it’s closer to the plugin code and deploys at once. However, this could potentially cause some issues in other modules, where CKEditor images are used without the plugin.

### CODE REVIEW

**Comment by boton** [comment]
ci:test:content-management

**Review by markocikos — APPROVED** [review]
@boton LGTM! :sparkles: 

> A more robust, permanent solution would be to prevent CKEditor from automatically inserting images through the addImages plugin. This approach fixes the root cause by controlling image insertions during pasting events.

We are currently working on enabling CKEditor 5 in DXP, see
- [LPD-36623 Modernize rich text experience with ckeditor5](https://liferay.atlassian.net/browse/LPD-36623),  
- https://github.com/liferay-frontend/liferay-portal/pull/4544

Migrating to CKE5 will be the long-term solution. If the issue exists there, which I doubt, we'll need to figure out a solution on that codebase. With this in mind, a quick & dirty fix like in this PR seems more than fine.

**Comment by boton** [comment]
ci:report:1257401_6239

**Comment by boton** [comment]
ci:forward

**Pull request closed without merging**
