### PR TITLE
LPS-128998 [Content Performace] Save attributes in store instead of prop-drilling them

### PR DESCRIPTION
**Pull request by dgarciasarai**
**Description**

This is the second pull request to fix [LPS-128998 Content Performance available endpoints should load at the same time](https://issues.liferay.com/browse/LPS-128998) as I said in a previous PR (see `Notes` from description, but in summary, the idea is that every component reads data from the store instead of calling its `dataProvider` and wait until all endpoints are resolved to display the data in the UI): https://github.com/liferay-frontend/liferay-portal/pull/885#issue-588734880.

As the pull can be huge, I'm going to create sub-tasks for the issue and send the code for each of them separately.

**How to test it**

- Connect Liferay DXP with Analytics Cloud
- Create a Content Page
- Wait 24 hours to let Analytics Cloud process the data (if you don't want to wait for it, change the date of your computer and create the page in the past 😉  )
- Open the Content Performance panel

**Within this pull request**

Everything should work as before. No UI changes.
- Save endpoints, languageTag, namespace and page attributes in store
- Apply in all components and remove prop-drilling those attributes
- Fix frontend tests

**Final solution for the issue**

In the future those handlers will be converted into actions and dispatch it when necessary. Also, some information will be removed from the prop-drilling and save it in the store as-well. Components will read from the store to display the data.

**History pull requests**

- LPS-128998 [Content Performance] Refactor APIService to be called in any component: https://github.com/brianchandotcom/liferay-portal/pull/99816

### CODE REVIEW

**Comment by dgarciasarai** [comment]
I will rebase the pull request when the first one is merged to use the correct commits. Thanks!

**Comment by dgarciasarai** [comment]
ci:stop

**Comment by dgarciasarai** [comment]
ci:test:sf

**Comment by dgarciasarai** [comment]
ci:test:relevant

**Comment by dgarciasarai** [comment]
Hey @wincent, I just updated the PR (rebased and solved conflicts). Can you give me feedback? Thanks!

**Comment by wincent** [comment]
> Hey @wincent, I just updated the PR (rebased and solved conflicts). Can you give me feedback? Thanks!

Hard to see all the uses of `useContext(StoreContext)` in the GitHub UI, but it seems like almost everywhere you use it, I don't see the second value of the returned tuple (`dispatch`) being used, at least in this PR. At some point might be worth refactoring for this common "read-only" case (an example of this would be what they have in `layout-content-page-editor-web`, where they use [a separate context for accessing just `dispatch`](https://github.com/liferay/liferay-portal/blob/09a2856d101fbd76020c26acaeadf51de0b7e755/modules/apps/layout/layout-content-page-editor-web/src/main/resources/META-INF/resources/page_editor/app/store/index.js#L27) where needed.

Anyway, forwarding this in the meantime.

**Comment by wincent** [comment]
ci:forward

**Comment by dgarciasarai** [comment]
> Hard to see all the uses of useContext(StoreContext) in the GitHub UI, but it seems like almost everywhere you use it, I don't see the second value of the returned tuple (dispatch) being used, at least in this PR. At some point might be worth refactoring for this common "read-only" case (an example of this would be what they have in layout-content-page-editor-web, where they use a separate context for accessing just dispatch where needed.

That's the idea for future pull request, separate dispatch and state and create several actions to call the APIService from the available endpoints. When all endpoints are settled, I'll display the components and in the meantime we are going to show a loading indicator. With this change, we are going to clean up a little bit the handlers from the first pull request. Thanks!

**Pull request closed without merging**
