### PR TITLE
LPS-158738 A data request with status field filter breaks in URI parsing

### PR DESCRIPTION
**Pull request by 4lejandrito**
Fixes https://issues.liferay.com/browse/LPS-158738. The odata implementation for objects was missing some methods.

### CODE REVIEW

**Comment by 4lejandrito** [comment]
ci:reevaluate:1387401_3324

**Comment by john-co** [comment]
Looks like a flaky [Objects test](https://testray.liferay.com/home/-/testray/case_results/1960750812/history?tab=result&hideFilterPin=true) cc/ @timpak

**Comment by john-co** [comment]
ci:test:relevant

**Comment by timpak** [comment]
Yeah ObjectsPopulating#CanMapStringTypeAndViewEntries is flaky right now

**Comment by john-co** [comment]
Reviewed. Test failures are unrelated. :heavy_check_mark: 

Ok to manually forward from QA perspective. Pending dev approval.

**Comment by john-co** [comment]
[ObjectPermission#CanEditItsOwnEntryWithOnlyAddPermission](https://testray.liferay.com/home/-/testray/case_results/1960965294/history?tab=result&hideFilterPin=true) looks flaky too cc/ @timpak

**Review by sergiojimcos — APPROVED** [review]
Reviewed and LGTM!! :clap: :clap:

**Review by LuismiBarcos — APPROVED** [review]
LGTM :) 👏 👏 👏 👏 
I think we could send it to Brian because, as we talked, we are adding new methods and not changing any logic. I think it is safe to send it.

**Comment by 4lejandrito** [comment]
ci:forward

**Comment by 4lejandrito** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/122379

**Pull request closed without merging**
