### PR TITLE
LPS-147135: Improve buttons accessibility having discernible text

### PR DESCRIPTION
**Pull request by sergiojimcos**
**What is new?**
Improving  buttons accessibility having discernible text in `Remote Apps` and `Workflow Tasks`. Changes in:
- Management Toolbar: `Search Button`,  ` View Option Type Button`.
-  Frontend Data Set: `Going Back Button`.
- Workflow Approve Popup: `Close Popup Button` .

## Case 1
**Steps to Reproduce:**
1. Application Menu > Remote Apps
2. Use axe DevTools to identify issues

**Before PR:**

**After PR:**
Screenshot 2022-05-06 at 10 28 07

## Case 2
**Steps to reproduce:**
1. Apply workflow to remote apps
2. Add a client extension entry 
3. View notifications and assign remote app to review
4. Click on Approve for popup
5. Use axe DevTools to identify issues

**Before PR:**

**After PR:**
Screenshot 2022-05-06 at 10 30 29

**JIRA TICKET:**
[LPS-147135](https://issues.liferay.com/browse/LPS-147135)

### CODE REVIEW

**Review by tinycarol — APPROVED** [review]
LGTM! 👏

**Comment by Esther-OC** [comment]
After analyzing the failures, it seems that they are not related to this PR, so you can move forward with it from QA perspective.

**Comment by sergiojimcos** [comment]
ci:forward

**Comment by sergiojimcos** [comment]
Forward manually: https://github.com/brianchandotcom/liferay-portal/pull/117129#issuecomment-1121237962

**Pull request closed without merging**
