### PR TITLE
LPS-116194 Add style-editor frontend-token-definition

### PR DESCRIPTION
**Pull request by eduardoallegrini**
New version of the frontend-token-definition

from https://github.com/liferay-frontend/liferay-portal/pull/135
with changes from https://github.com/brianchandotcom/liferay-portal/pull/91544#issuecomment-661223466

---

We noticed that the `tokenSets` have preserved its name in the [schema](https://github.com/liferay/liferay-portal/blob/master/modules/apps/frontend-token/frontend-token-definition-api/src/main/resources/com/liferay/frontend/token/definition/frontend-token-definition.schema.json#L107). Eventually we'd like to change it to `frontendTokenSets` to keep the consistency of the names

### CODE REVIEW

**Comment by brunobasto** [comment]
I'm assuming the issue with outdated master of liferay-frontend recently is that @wincent is on PTO and the script  on his machine is not running 😆 

Screen Shot 2020-07-21 at 19 49 17

**Comment by eduardoallegrini** [comment]
exactly 😄 https://liferay.slack.com/archives/G3JBR21HA/p1595341431479500

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by wincent** [comment]
Screenshot 2020-07-22 -135228-f2SefsU9@2x

(Switched base to force GitHub to stop displaying extraneous commits.)

**Comment by ealonso** [comment]
Included in: https://github.com/liferay-echo/liferay-portal/pull/1611

**Comment by jbalsas** [comment]
Closing since this is going in liferay-echo#1611

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
