### PR TITLE
LPS-173965 | Text Fix for ClientExtensionOSGI#HasViewAction

### PR DESCRIPTION
**Pull request by alexmds2004**
**Background**
Fix "Element is not present in ClientExtensionOSGI"

**Test Plan**

- Given config file for client extension of type custom element created
- Then View action is an available option
- And Then Edit action is not an available option field information is displayed correctly

JIRA Ticket
https://issues.liferay.com/browse/LPS-173965

### CODE REVIEW

**Comment by alexmds2004** [comment]
ci:test:sf

**Comment by carloslancha** [comment]
Hey @alexmds2004 ! Could you please add a meaningful title to the pr? It helps us to understand quickly what prs are about and who should take a look at them.

Here you can find our pr guidelines if you want to take a look https://github.com/liferay/liferay-frontend-projects/blob/master/guidelines/general/pull_requests.md

Thanks!

**Comment by mateusralv** [comment]
ci:test:frontend:nocompile

**Comment by alexmds2004** [comment]
ci:test:sf

**Comment by alexmds2004** [comment]
ci:test:frontend

**Comment by alexmds2004** [comment]
@mateusralv

**Review by mateusralv — CHANGES_REQUESTED** [review]
Hi @alexmds2004 Could you take a look at these requests? If you have a question please let me know  :)

**Comment by alexmds2004** [comment]
ci:test:sf

**Comment by alexmds2004** [comment]
ci:test:sf

**Comment by alexmds2004** [comment]
ci:test:sf

**Comment by alexmds2004** [comment]
ci:test:sf

**Comment by alexmds2004** [comment]
ci:test:sf

**Comment by alexmds2004** [comment]
ci:test:sf

**Comment by alexmds2004** [comment]
ci:test:sf

**Comment by alexmds2004** [comment]
ci:test:frontend

**Comment by mateusralv** [comment]
ci:test:frontend

**Comment by mateusralv** [comment]
The test are passing in CI 🎉

**Comment by mateusralv** [comment]
ci:forward

**Comment by mateusralv** [comment]
ci:test:frontend

**Comment by mateusralv** [comment]
The test passed in CI 🎉 

[.ClientExtensionOSGI#HasViewAction](https://testray.liferay.com/home/-/testray/case_results/2228614927?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2228605237%26testrayRunId%3D2228614894%26cur%3D2%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc%26resetCur%3Dfalse)

**Comment by mateusralv** [comment]
ci:forward

**Pull request closed without merging**
