### PR TITLE
LPS-145939 - Show disabled styles in MT bulk action if disabled

### PR DESCRIPTION
**Pull request by tinycarol**
### References

- [LPS-145939](https://issues.liferay.com/browse/LPS-145939)

### What is the goal?

* Show MT bulk actions button as disabled if `disabled` prop is true

### What does it look like?

https://user-images.githubusercontent.com/6642927/150957967-6ced9b80-e733-478e-9f32-bb10288c42c3.mov

### How to replicate
* Go to `Site Builder > Pages` 
* Click on select all checkbox in MT
* See that if you hover over the `Convert to Content Page` icon it shows as disabled and cannot be clicked

### CODE REVIEW

**Review by carloslancha — APPROVED** [review]
Ship It!

**Review by julien — APPROVED** [review]

**Comment by tinycarol** [comment]
@liferay-continuous-integration 
Do sth

**Comment by tinycarol** [comment]
ci:test:relevant

**Comment by john-co** [comment]
cc/ @zhangyan0701 could you keep an eye on this and manually forward if issues are unrelated?

**Comment by zhangyan0701** [comment]
Test failures are unrelated.

Manually forwarded to BChan: https://github.com/brianchandotcom/liferay-portal/pull/112665

**Pull request closed without merging**
