### PR TITLE
LPS-181123 |Removing the ignore FDSEntry#CannotExceed280Characters

### PR DESCRIPTION
**Pull request by alexmds2004**
**Description**
removed the ignore from the test
**JIRA Test Fix**
https://issues.liferay.com/browse/LPS-181123

### CODE REVIEW

**Comment by alexmds2004** [comment]
ci:test:frontend

**Comment by alexmds2004** [comment]
@mateusralv

**Review by mateusralv — APPROVED** [review]
Thanks @alexmds2004 🎉 🚀

**Comment by mateusralv** [comment]
ci:forward

**Pull request closed without merging**
