### PR TITLE
LPS-142318 | A11yTool - Verifies violations are highlighted and have an icon

### PR DESCRIPTION
**Pull request by susanchen3**
**Background**
Create automated tests for the A11y tool

**Test Plan**
- Verify there are at least 3 different violations
- Assert all 3 violations are highlighted
- Assert all 3 highlighted violations have an icon

**JIRA Ticket:**
https://issues.liferay.com/browse/LPS-142318

### CODE REVIEW

**Comment by john-co** [comment]
ci:test:frontend:nocompile

**Comment by john-co** [comment]
Just started reviewing :)

**Review by john-co — APPROVED** [review]
Looks good! Just check that the a11y test passes and can forward.

Note: I noticed in some recent runs that some a11y tests were failing https://testray.liferay.com/home/-/testray/cases/1572174238
Would you be able to investigate, if it continues to be the case with this next PR test run?

**Comment by susanchen3** [comment]
thats strange.. you got it captain :D

**Comment by susanchen3** [comment]
I think I know why it's failing...

Based on the [Poshi Report](https://testray.liferay.com/reports/production/logs/2021-11/test-1-9/test-portal-acceptance-pullrequest(master)/5135/functional-tomcat90-mysql57-jdk8/0/0/LocalFile.A11yTool_CanDetectViolation/index.html.gz) it looks like its failing because of [LPS-14442](https://issues.liferay.com/browse/LPS-141442). I think the page is having issues detecting the violations, so after it refreshes a couple times and detects the tool, it exits the while loop. But I think it executes one more refresh so that probably makes the tool disappear again, causing the assert to fail.

cc @john-co

**Comment by john-co** [comment]
> Based on the [Poshi Report](https://testray.liferay.com/reports/production/logs/2021-11/test-1-9/test-portal-acceptance-pullrequest(master)/5135/functional-tomcat90-mysql57-jdk8/0/0/LocalFile.A11yTool_CanDetectViolation/index.html.gz) it looks like its failing because of [LPS-14442](https://issues.liferay.com/browse/LPS-141442). I think the page is having issues detecting the violations, so after it refreshes a couple times and detects the tool, it exits the while loop. But I think it executes one more refresh so that probably makes the tool disappear again, causing the assert to fail.

I think it doesn't work at all with the page refreshes. I believe the while loop has a max of 15 tries before it exits. I count that for [A11yTool#CanFilterViolationsByCriticalImpactOnly - Poshi Report](https://testray.liferay.com/reports/production/logs/2021-11/test-1-14/test-portal-acceptance-pullrequest(master)/8557/functional-tomcat90-mysql57-jdk8/0/0/LocalFile.A11yTool_CanFilterViolationsByCriticalImpactOnly/index.html.gz) so I think a11y tool is not being setup up correctly for some reason on CI...

**Comment by john-co** [comment]
but yea probably related to [LPS-14442](https://issues.liferay.com/browse/LPS-141442) where it just doesn't want to load...or maybe the CI environments are recently too slow?

**Comment by john-co** [comment]
ci:test:frontend

**Comment by john-co** [comment]
ci:test:frontend:nocompile

**Comment by susanchen3** [comment]
tool picked up some other violations :thinking: 

image

**Comment by susanchen3** [comment]
ci:test:frontend:nocompile

**Comment by john-co** [comment]
ok to forward since test is likely blocked by [LPS-14442](https://issues.liferay.com/browse/LPS-141442)

**Comment by john-co** [comment]
ci:forward

**Pull request closed without merging**
