### PR TITLE
LPS-115278 Change image icon is disabled for blogs cover image

### PR DESCRIPTION
**Pull request by boton**
This PR adds `cssClass` attribute to recover the CSS class in the render of `<clay:button`.

**Test plan:** 
1. Site > Content & Data > Blogs
1. Add a new blog entry with cover image
1. Click the browse image button to change the cover image

**Actual result**
Can not open the select file modal after clicking the browse image button

**Expected result**
Can open the select file modal after clicking the browse image button

### CODE REVIEW

**Comment by boton** [comment]
ci:test:sf

**Comment by boton** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
LGTM!! Thanks a lot for sending this @boton!!

**Comment by jbalsas** [comment]
ci:forward

**Pull request closed without merging**
