### PR TITLE
LPS-120062 Sync values from the theme in the token definition (Vol.2)

### PR DESCRIPTION
**Pull request by victorg1991**
This is related to the pr I sent yesterday https://github.com/liferay-frontend/liferay-portal/pull/333

> Some default values in the token definition of the classic theme were not the same as the one used in the CSS
> 
> Blockquote small color is defined here
> 
> Body bg is defined here
> 
> In the case of body bg color maybe we want another color? I've used what the theme is defining right now, but maybe there is a mistake there also, can you review it?

I missed text-muted color that was not synchronized with the css value applied

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
I think this is failing all the time... will forward manually

**Comment by jbalsas** [comment]
Forwarded manually to https://github.com/brianchandotcom/liferay-portal/pull/93569

**Pull request closed without merging**
