### PR TITLE
LPS-147280 LPS-147278 Create an approved Layout instead of draft in integration tests

### PR DESCRIPTION
**Pull request by ccorreagg**
Related tickets:

[LPS-147278](https://issues.liferay.com/browse/LPS-147278)
[LPS-147280](https://issues.liferay.com/browse/LPS-147280)
This PR contains a change on the way of generating Layouts for Headless Delivery API tests to mark them as published.

It can be tested by launching the Integration Test

`SitePageResourceTest.testGetSiteSitePagesPageWithFilterDateTimeEquals`

**Before the PR:**

The searchUtil did not find any Layout as its status was 2 (STATUS_DRAFT) in the Elasticsearch entry.

**After the PR:**

The created Layout is marked as published so the status is updated to 0 (STATUS_APPROVED). Then, the API is working as expected.

### CODE REVIEW

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
ci:test:sf

**Review by javierdearcos — APPROVED** [review]
As it is a new method and we are not modifying the existing one that was called in the other test suites I think we are safe just relying in our tests.

Let's push it forward

**Comment by javierdearcos** [comment]
ci:forward

**Pull request closed without merging**
