### PR TITLE
LPS-138141 update to latest Alloy UI version

### PR DESCRIPTION
**Pull request by nhpatt**
Using last version after checking that the build works fine (that was not happening with previous version because a packaging issue).

### CODE REVIEW

**Comment by markocikos** [comment]
Checking if we are clear on regressions...
- [ ] [AUI-3196](https://issues.liferay.com/browse/AUI-3196)
- [ ] [AUI-3201](https://issues.liferay.com/browse/AUI-3201)
- [ ] [AUI-3205](https://issues.liferay.com/browse/AUI-3205)

**Review by markocikos — APPROVED** [review]
No build errors, all clear on regressions. LGTM!

**Comment by nhpatt** [comment]
ci:forward

**Comment by nhpatt** [comment]
PTR validated too, let's check with the ci again...

**Comment by nhpatt** [comment]
Bad CI, bad.

**Pull request closed without merging**
