### PR TITLE
LPS-115593 LPS-115057 Add axis labels, empty state when there are no categories selected 

### PR DESCRIPTION
**Pull request by dgarciasarai**
Previously:

- https://github.com/liferay-frontend/liferay-portal/pull/68
- https://github.com/liferay-frontend/liferay-portal/pull/65

**Description**

The main goal of this pull request is to show the axis names in the chart and put an empty state when the user unchecked all the categories from the legend.

**Changes**

* Use Lexicon colors for the bars
* Display axis names in the chart
* Empty state when there are no categories selected.

**Feature flag: YES**

The Audit Graph is hidden. The configuration file to show the chart is here: https://issues.liferay.com/browse/LPS-115805

**Module**

```
~/liferay-portal/modules/apps/content-dashboard/content-dashboard-web
```

**Screenshots**

Screenshot 2020-06-29 at 12 02 29

Screenshot 2020-06-29 at 13 24 00

Previous PR: https://github.com/liferay-frontend/liferay-portal/pull/65

cc: @bryceosterhaus @wincent

### CODE REVIEW

**Comment by dgarciasarai** [comment]
ci:reopen

**Comment by dgarciasarai** [comment]
ci:test:relevant

**Comment by dgarciasarai** [comment]
ci:test:sf

**Comment by dgarciasarai** [comment]
ci:test:sf

**Comment by wincent** [comment]
ci:forward

**Pull request closed without merging**
