### PR TITLE
LPS-144688 | Adjusting LexiconEntry.gotoEntry and LexiconEntry.gotoEntryMenuItem to work for Client Extension

### PR DESCRIPTION
**Pull request by deborasoliveira**
Adjusting _LexiconEntry.gotoEntry_ and _LexiconEntry.gotoEntryMenuItem_ paths to work for Client Extension. 

**JIRA Ticket**
https://issues.liferay.com/browse/LPS-144688

### CODE REVIEW

**Comment by deborasoliveira** [comment]
ci:test:frontend

**Comment by mateusralv** [comment]
ci:help

**Comment by mateusralv** [comment]
ci:test:acceptance

**Comment by mateusralv** [comment]
ci:test:acceptance

**Comment by deborasoliveira** [comment]
ci:test:acceptance

**Comment by mateusralv** [comment]
The failures related to [ci:test:acceptance](https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2253104426) not be related to this PR. 

[Testray Comparison](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1680266012302&testrayRunIdA=2252500498&testrayRunIdB=2253105110)

**Comment by mateusralv** [comment]
ci:forward

**Pull request closed without merging**
