### PR TITLE
LPS-114272 versions

### PR DESCRIPTION
**Pull request by nhpatt**
Back to the old name in the collection endpoint. We need to use `/structured-contents/{structuredContentId}` to modify all the fields of the StructuredContent. 

The `StructuredContentVersion` exists but only in code, we create it with `EntityExtensionUtil.extend` (adding `StructuredContent` + `Version`.

An alternative would be creating another pattern for this kind of endpoints.

### CODE REVIEW

**Comment by nhpatt** [comment]
ci:forward

**Comment by jbalsas** [comment]
I don't see no ninja-merge token here nor someone else's permission 😂

**Comment by nhpatt** [comment]
Hehe, it's a PR that was already reviewed (done by Luismi) and merged but Brian made us revert it. This was back to the old code but with more explanation of the reason behind it.

**Comment by jbalsas** [comment]
That sounds like great info to go with the `ci:forward` for anyone looking back at this in the future 😉

**Comment by nhpatt** [comment]
Yeah, it's true, it was missing all the context 😓

**Pull request closed without merging**
