### PR TITLE
LPS-141734 | A11yTool - Verifies impact and category filter toggles are available

### PR DESCRIPTION
**Pull request by susanchen3**
**Background**
Create automated tests for the A11y tool

**Test Plan**
- Verify the side panel appears with violations listed
- Click on the filter button
- Verify filtering by impact and category toggles are listed

**JIRA Ticket:**
https://issues.liferay.com/browse/LPS-141734

### CODE REVIEW

**Comment by john-co** [comment]
ci:test:frontend:nocompile

**Comment by john-co** [comment]
Just started reviewing :) ...for reals :sweat_smile:

**Review by john-co — APPROVED** [review]
Looks good to me!

**Comment by john-co** [comment]
ok to forward if the a11y testcase passes.

**Comment by susanchen3** [comment]
ci:test:frontend:nocompile

**Comment by susanchen3** [comment]
ci:forward

**Pull request closed without merging**
