### PR TITLE
[TS] LPS-200609 

### PR DESCRIPTION
**Pull request by MirnaGama**
### Context:
[LPS-200609 - Edit client credentials modal causes blank space above page and collapses screen](https://liferay.atlassian.net/browse/LPS-200609)

### Steps to reproduce:

1. Go to Control Panel > Security > OAuth 2 Administration
2. Select any "OAuth 2 Administration"
3. Click "Edit" button on "Client ID" or "Client Secret"

Actual result: An unnecessary blank space appears at the top of the screen.
Expected result: Unnecessary blank space is not displayed.

### Implementation details:
 The best long term solution would be to migrate away from new `A.Modal`. The amount of logic that’s being handled by javascript in the jsp could be handled much more simply if more of it is migrated to React. We would then be using the Clay Modal and not have to worry about things being as fragile in the future.

### CODE REVIEW

**Comment by MirnaGama** [comment]
ci:test:sf

**Comment by MirnaGama** [comment]
ci:test:relevant

**Review by markocikos — APPROVED** [review]
@MirnaGama LGTM! Nice job on TS!  :sparkles:

**Comment by MirnaGama** [comment]
ci:forward

**Comment by MirnaGama** [comment]
ci:forward:force

**Pull request closed without merging**
