### PR TITLE
LPS-192880 Emit nonce from JSPs

### PR DESCRIPTION
**Pull request by izaera**
Once this is merged, DXP’s most restrictive supported CSP would be:

 `script-src '[$NONCE$]'; script-src-attr 'unsafe-inline';`

This is for internal DXP code, not  CKEditor, which may need even more permissive policies.

Next steps for the future, would be replacing all onclick, onfocus, etc. attribute handlers by nonced script snippets so that we can remove the script-src-attr 'unsafe-inline' from the most restrictive supported CSP. However to do that we may need to:

1. Change infrastructure tags like <aui:button>, <liferay-ui:icon>, etc. to generate nonce snippets
2. Replace pure HTML attribute handlers (this may need to involve other teams depending on where the pure HTML code is)

Note that 2 has at least two subcases we have already detected:

1. Fragments may include pure HTML code and AFAIK we don’t have any mechanism to make that CSP compliant
2. Site initializers have the same problem.

### CODE REVIEW

**Comment by izaera** [comment]
ci:test:relevant

**Comment by izaera** [comment]
ci:test:sf

**Comment by izaera** [comment]
ci:test:relevant

**Comment by izaera** [comment]
ci:test:relevant

**Comment by izaera** [comment]
ci:test:stable

**Comment by izaera** [comment]
ci:test:sf

**Comment by izaera** [comment]
ci:test:relevant

**Comment by izaera** [comment]
I've force-pushed a fix for the previous `test:stable` error

**Comment by izaera** [comment]
Asked QA for an analysis -> https://liferay.slack.com/archives/C3JBR21HA/p1700117564522399

**Comment by mateusralv** [comment]
ci:test:relevant

**Comment by izaera** [comment]
ci:test:relevant

**Comment by mateusralv** [comment]
I'm on it 🕵🏽

**Comment by mateusralv** [comment]
Hi @izaera , approximately 50 tests failed unique in this PR, and most of the failures are related to the points below:

1. Calendar Fragment

https://github.com/liferay-frontend/liferay-portal/assets/44584050/b4e13efd-e468-4410-83d4-72d17921392e

2. Sign Out

https://github.com/liferay-frontend/liferay-portal/assets/44584050/426ccb2c-c3bf-42b8-afaa-a258dc28de34

**Comment by dsanz** [comment]
@mateusralv @izaera about the logout, looks like we're serving `text/html` content which ends up being a `<script>` tag. Very likely this is an additional protection from CSP to avoid mime type confusion attacks, probably from `redirect_js.jsp` or `forward_js.jsp`.

**Comment by dsanz** [comment]
About the calendar error, just looking at the error trace, I suspect of some interaction with [these scripts](https://github.com/liferay/liferay-portal/blob/6ce0b9eb049e99a50285a324a3bd4afd76d340ab/modules/apps/calendar/calendar-web/src/main/resources/META-INF/resources/event_recorder.jspf), used [here](https://github.com/liferay/liferay-portal/blob/6ce0b9eb049e99a50285a324a3bd4afd76d340ab/modules/apps/calendar/calendar-web/src/main/resources/META-INF/resources/scheduler.jsp#L107). cc/ @izaera

**Comment by izaera** [comment]
ci:test:sf

**Comment by izaera** [comment]
ci:test:sf

**Comment by izaera** [comment]
ci:test:relevant

**Comment by mateusralv** [comment]
Hi @izaera I will run the relevant again because some tests failed in the CI but when I run locally passed then I will do a second check.

**Comment by mateusralv** [comment]
ci:test:relevant

**Comment by mateusralv** [comment]
The CI did not return the results 😵‍💫

**Comment by mateusralv** [comment]
ci:test:relevant

**Comment by izaera** [comment]
It's OK to continue with testing in case we find anything else unique to this PR, however, I will need to rebase this on top of https://github.com/liferay-frontend/liferay-portal/pull/3864 once it is merged to master.

So I'm considering this PR to on hold until that happens.

**Comment by izaera** [comment]
I need to rebase this if we want to run more tests :-/ 

I'll rebase on top of https://github.com/liferay-frontend/liferay-portal/pull/3864 and push the commits

**Comment by izaera** [comment]
ci:test:sf

**Comment by izaera** [comment]
ci:test:relevant

**Comment by izaera** [comment]
ci:test:sf

**Comment by izaera** [comment]
ci:test:relevant

**Comment by izaera** [comment]
ci:test:sf

**Comment by andreluis2022** [comment]
Hey @izaera  the crashes don't seem to be related to your changes, you can forward it if no further developer review is needed

**Comment by izaera** [comment]
ci:forward:force

**Pull request closed without merging**
