### PR TITLE
LPS-158216 Create FDS custom views backend service

### PR DESCRIPTION
**Pull request by markocikos**
### References

- [LPS-158216 Create FDS custom views backend service](https://issues.liferay.com/browse/LPS-158216)
- Related to https://github.com/brianchandotcom/liferay-portal/pull/102230
- Related to https://github.com/liferay-frontend/liferay-portal/pull/2509
- This is a followup on #2526

### What is the goal of this PR?

Applying sort, requested in https://github.com/brianchandotcom/liferay-portal/pull/120875#issuecomment-1198323829 . We are keeping `fdsName`. The changes are in 5 new commits.

I'm taking the opportunity to retest CI missing dependencies issues, that were consistent in #2526. I'd like to confirm that the app release really fixed the problem, that is was not an unlikely coincidence. I removed the app release commit, will bring it back if the same error repeats. /cc @john-co  

There is no need to peer review this PR, feel free to forward if CI is green.

/cc @dsanz @diegonvs

### CODE REVIEW

**Comment by diegonvs** [comment]
ci:forward

**Comment by markocikos** [comment]
Force-pushed! Changes:
- fixed a minor conflict with SF on unrelated code
- returned the release commit. Without it, we are again seeing the dependency errors, https://github.com/liferay-frontend/liferay-portal/pull/2584#issuecomment-1199862602. I am fairy sure that CI will now be green. /cc @john-co

**Comment by markocikos** [comment]
ci:test:sf

**Comment by markocikos** [comment]
ci:forward

**Pull request closed without merging**
