### PR TITLE
[TS] LPS-144168 Get the language key instead of hardcoding

### PR DESCRIPTION
**Pull request by orsolyaDekany**
Hi Team,

LPS: https://issues.liferay.com/browse/LPS-144168

Could you please review it?
Thank you!

### CODE REVIEW

**Comment by orsolyaDekany** [comment]
ci:test:sf

**Comment by orsolyaDekany** [comment]
ci:test:relevant

**Review by victorg1991 — APPROVED** [review]
LGTM :)

**Comment by orsolyaDekany** [comment]
Thank you @victorg1991 , can you please push this forward? :)

**Comment by carloslancha** [comment]
ci:forward

**Pull request closed without merging**
