### PR TITLE
 LPS-143467 LPS-143469 LPS-143455 COMMERCE-7574 Generate Entity metadata to improve the support for Batch and Import / Export

### PR DESCRIPTION
**Pull request by javierdearcos**
This PR adds new methods to the VulcanBatchEngineTaskItemDelegate to provide entity metadata information about:

- The VulcanBatchEngineTaskItemDelegate version
- The VulcanBatchEngineTaskItemDelegate entity class name
- The available scopes for the read (export) and create (import) methods. The update and delete does not need them as they act directly with the entity id
- The entity field name, description, types, access type (READ, WRITE or READWRITE), and if they are required to create an entity.

Includes the COMMERCE-7574 Batch-engine should allow skipping failed records https://github.com/liferay-frontend/liferay-portal/pull/1948

The last commit ensures that the generation only takes place in 7.4 version, avoiding incompatibility problems in older branches.

### CODE REVIEW

**Comment by javierdearcos** [comment]
ci:test:sf

**Comment by javierdearcos** [comment]
ci:test:relevant

**Comment by javierdearcos** [comment]
ci:test:sf

**Comment by javierdearcos** [comment]
ci:test:relevant

**Comment by javierdearcos** [comment]
ci:test:sf

**Comment by javierdearcos** [comment]
ci:test:relevant

**Comment by javierdearcos** [comment]
ci:test:sf

**Comment by javierdearcos** [comment]
ci:test:relevant

**Comment by javierdearcos** [comment]
ci:stop

**Comment by javierdearcos** [comment]
ci:test:sf

**Comment by javierdearcos** [comment]
ci:forward

**Comment by javierdearcos** [comment]
ci:reevaluate:1287401_2152

**Comment by javierdearcos** [comment]
ci:test:relevant

**Comment by javierdearcos** [comment]
ci:forward

**Comment by javierdearcos** [comment]
ci:forward

**Comment by javierdearcos** [comment]
ci:test:sf

**Comment by javierdearcos** [comment]
ci:test:relevant

**Comment by javierdearcos** [comment]
ci:test:relevant

**Comment by javierdearcos** [comment]
ci:test:relevant

**Comment by kenjiheigel** [comment]
ci:test:relevant

**Comment by javierdearcos** [comment]
ci:stop

**Comment by javierdearcos** [comment]
Thank you @kenjiheigel for helping forwarding the PR.

Brian ask me for some changes so I will close it and send it again with the requested changes.

Sorry for the inconvenience

**Pull request closed without merging**
