### PR TITLE
LPS-182790 LPS-184492 Implements searching on a field content renderer in OrderableTable

### PR DESCRIPTION
**Pull request by thektan**
**Story:** https://issues.liferay.com/browse/LPS-182790
**Subtask:** https://issues.liferay.com/browse/LPS-184492

### What is the goal of this PR?
- Allows passing a `textMatch` property for specific text to match for searching on
- Allows the custom content renderer component to apply fuzzy bold styling

### What does it look like?
https://github.com/liferay-frontend/liferay-portal/assets/4496722/9fc00ae7-f18e-429c-bdb4-092cec078c0b

### CODE REVIEW

**Review by bryceosterhaus — APPROVED** [review]
LGTM!

**Comment by markocikos** [comment]
ci:forward

**Comment by markocikos** [comment]
@thektan Please fix conflicts and ci : forward. CI failures look unrelated, we can get QA in this if they keep repeating.

**Comment by thektan** [comment]
ci:forward

**Pull request closed without merging**
