### PR TITLE
LPS-162074 Replace rest of usages of `Liferay.Util.sub` with imported `sub`

### PR DESCRIPTION
**Pull request by kresimir-coko**
There was a decent amount of usages of `Liferay.Util.sub` that we missed in an [earlier PR](https://github.com/liferay-frontend/liferay-portal/pull/2223). We should probably also work on some eslint rules that forbid further additions of utils from the global scope.

### CODE REVIEW

**Comment by kresimir-coko** [comment]
@mateusralv can you please check this one out, too?

The failing test in `analytics-reports-web` is failing on master, I just checked.

**Comment by mateusralv** [comment]
Yep, I’ll take a look at other failures 🕵🏽

**Comment by mateusralv** [comment]
Hey @kresimir-coko the failures is not related to your PR 🎉

**Comment by kresimir-coko** [comment]
Closing in favor of the forwarded PR https://github.com/brianchandotcom/liferay-portal/pull/122668

**Comment by john-co** [comment]
Hey @kresimir-coko and @mateusralv , the js unit test failure is related to this PR. BChan will [revert this commit](https://liferay.slack.com/archives/CLCD3DQLF/p1662572518567759?thread_ts=1662477601.854519&cid=CLCD3DQLF).

**Pull request closed without merging**
