### PR TITLE
LPS-127657 Update ClassicEditor usage

### PR DESCRIPTION
**Pull request by sandrodw3**
This is intended to fix https://issues.liferay.com/browse/LPS-127657 (CKEditor is not listening to config changes, so it does not apply rtl direction when setting a rtl language). It's the first part of the fix, the second one will be sent to liferay-data-engine.

The idea consists in wrapping `ClassicEditor` component in `React.forwardRef`, so we can use the editor instance outside this component. 

This way, we'll be able to update the editor config when a web content's language is switched.

cc @julien 🙂

### CODE REVIEW

**Review by wincent — APPROVED** [review]
Changes look reasonable to me. Let's see what CI says.

**Comment by wincent** [comment]
> It's the first part of the fix, the second one will be sent to liferay-data-engine.

@sandrodw3: So that we don't have to look at this twice or test it, can you push the commits of second part here too? We can always say 👍 here and then you can forward to somebody else if you want additional approval.

**Comment by julien** [comment]
ci:test:relevant

**Review by julien — APPROVED** [review]

**Comment by sandrodw3** [comment]
> > It's the first part of the fix, the second one will be sent to liferay-data-engine.
> 
> @sandrodw3: So that we don't have to look at this twice or test it twice, can you push the commits of second part here too? We can always say 👍 here and then you can forward to somebody else if you want additional approval.

Sure! I already pushed the second part 🙂 do you want the ci to pass here before I forward it to `liferay-data-engine` or I can do it now?

**Comment by sandrodw3** [comment]
ci:test:relevant

**Comment by sandrodw3** [comment]
ci:test:sf

**Comment by wincent** [comment]
> Sure @wincent! I already pushed the second part 🙂 do you want the ci to pass here before I forward it to `liferay-data-engine` or I can do it now?

I'd forward it now. I just took another look at it and it seems fine. In the meantime, no harm in letting the CI continue here (just in case one of the fails).

**Comment by wincent** [comment]
ci:test:bundle

**Comment by wincent** [comment]
Has been forwarded here: https://github.com/liferay-data-engine/liferay-portal/pull/289

We can close this once we see the test results (don't want to close it now just in case the CI bot goes crazy and aborts the runs — I don't think it will, but you never know).

**Comment by jbalsas** [comment]
Going to close here, but those test failures look indeed related and also show in common in https://github.com/liferay-data-engine/liferay-portal/pull/289 so I think we might need to look at what's happening in MB with these changes.

**Pull request closed without merging**
