### PR TITLE
LPS-150996 Add modernized utils to our main export file

### PR DESCRIPTION
**Pull request by kresimir-coko**
This PR adds utils that we've modernized as part of the [current epic](https://issues.liferay.com/browse/LPS-113522), and also adds some of the utils that I felt like needed to be added because they were modernized in the past but not added to the exports.

These utils will be able to be imported in JS files instead of using the `Liferay.Util` global namespace

### CODE REVIEW

**Comment by kresimir-coko** [comment]
Local `ant all` built successfully, and I can't execute gradle commands inside the `portal-workflow-metrics-web` module that appears to be the culprit. Not sure how to fix this or even replicate it @magjed4289 👀

**Review by bryceosterhaus — CHANGES_REQUESTED** [review]
Hey @kresimir-coko can you also go through and apply these changes throughout DXP? Meaning, if a module was previously using one of these like `Liferay.Util.formatStorage` from the Liferay object, can we update that to be imported and used from this file?

**Comment by kresimir-coko** [comment]
ci:test:sf

**Comment by kresimir-coko** [comment]
ci:test:relevant

**Comment by kresimir-coko** [comment]
fixed the conflict and force pushed

**Comment by kresimir-coko** [comment]
ci:test:relevant

**Comment by kresimir-coko** [comment]
ci:test:relevant

**Comment by kresimir-coko** [comment]
ci:test:relevant

**Comment by magjed4289** [comment]
Just started reviewing :)

**Comment by kresimir-coko** [comment]
ci:test:sf

**Comment by kresimir-coko** [comment]
ci:test:relevant

**Comment by kresimir-coko** [comment]
ci:reevaluate:1377401_1907

**Comment by kresimir-coko** [comment]
ci:test:relevant

**Comment by kresimir-coko** [comment]
ci:test:relevant

**Comment by kresimir-coko** [comment]
ci:test:relevant

**Comment by kresimir-coko** [comment]
ci:test:relevant

**Comment by kresimir-coko** [comment]
Hey @bryceosterhaus can you give it a look please? I went through every file twice and found a couple mistakes, but after running `ant all` with these changes, the portal is still producing the same errors. I've got no idea on where to look for fixes anymore.

**Comment by kresimir-coko** [comment]
ci:test:acceptance:functional

**Comment by kresimir-coko** [comment]
ci:test:relevant

**Comment by kresimir-coko** [comment]
Hey @magjed4289 I couldn't find anything useful in the failing functional test thingy. Can you take a look too, please?

**Comment by kresimir-coko** [comment]
I will close this PR as we will handle these changes in a series of separate PRs starting with #2223

**Pull request closed without merging**
