### PR TITLE
LPS-119846 Call proper method to retrieve JavaScript source map input stream

### PR DESCRIPTION
**Pull request by brunobasto**
As some of you may have noticed, JavaScript source maps started to fail to load. @jbalsas pointed me towards https://github.com/brianchandotcom/liferay-portal/pull/93087 as the possible cause of the problem and indeed it was. To my understanding, in that PR @izaera introduced two distinct methods to retrieve input streams:
1. `jsModule.getInputStream()`
2. `jsModule.getSourceMapInputStream()`

But only the first was called. The fix consists of simply calling the right method when we detect a source map was requested.

**Steps to Reproduce:**

1. Start portal
2. Go to the URL: http://localhost:8080/o/js/resolved-module/frontend-js-spa-web@4.0.14/liferay/app/App.es.js.map

**Expected Result:**
The file served by the portal is a [source map](https://sourcemaps.info/spec.html).

**Actual Result:**
The file served by the portal is the JavaScript source code. 

Chrome will actually give you lots of warnings too:
Source Map Errors

### CODE REVIEW

**Comment by brunobasto** [comment]
ci:test:sf

**Comment by brunobasto** [comment]
ci:test:relevant

**Review by jbalsas — APPROVED** [review]
Nicely done! 👍

**Comment by jbalsas** [comment]
ci:forward

**Pull request closed without merging**
