### PR TITLE
LPS-141280 Remote Apps workflow integation first step

### PR DESCRIPTION
**Pull request by javierdearcos**
Add the new columns and integrate with workflow.

The integration is hidden between a feature flag until everything is settled.

Pending the attachments part

### CODE REVIEW

**Comment by javierdearcos** [comment]
ci:test:relevant

**Comment by javierdearcos** [comment]
/cc @izaera @nhpatt 

The same thing you've already reviewed.

Sending the first part hided behind a Feature Flag

**Comment by javierdearcos** [comment]
ci:forward

**Comment by javierdearcos** [comment]
Failing due to the changes in the service API... Any thoughts about how to unblock this? Talk with someone from QA? Send to Brian directly?

**Comment by nhpatt** [comment]
If you are in a hurry, send. If you are not, talk with @magjed4289 (why your username is so ugly Meg? I'm sorry but it is).

**Comment by izaera** [comment]
@javierdearcos The CI error is fixed [like this](https://github.com/liferay-frontend/liferay-portal/pull/1637/commits/9f8fc0dc639d250a7e56b8329d95aa1bd52da82b), in case you want to do it yourself.

**Comment by javierdearcos** [comment]
> @javierdearcos The CI error is fixed like this, in case you want to do it yourself.

Thank you @izaera! I'll handle it myself then

**Comment by javierdearcos** [comment]
ci:forward

**Pull request closed without merging**
