### PR TITLE
LPS-198123 Return detailed message for exception.

### PR DESCRIPTION
**Pull request by SelenaAungst**
Hi Frontend Infra Team,
I am working on this solution for https://liferay.atlassian.net/browse/LPS-198123 and received a request to make some changes in a previous PR: https://github.com/liferay-peds/liferay-portal/pull/320#issuecomment-1757268247.

I wanted to request some assistance with this and confirm that this is a possible/necessary change before I go through and add it. It looks like the way `getLocalizedMessage` is used, I would need to modify or move the existing calls/thrown exceptions in all the files that use ClientExtensionEntryTypeSettingsException. Please let me know if this is the correct way to go about this, or if something else is more preferable. 

Thank you!

### CODE REVIEW

**Comment by izaera** [comment]
TBH, I think it doesn't make any sense to localize exception messages when 99.9% of them are written directly in English and never localized (in DXP).

Additionally my personal opinion, as a native Spanish speaker, is that translating error and debug messages is quite useless and only helps to add noise when it comes to understand what is really happening and search for it in the web. I understand this is because I speak English too, but I think we all get the idea...

So, if I were you, I would send this to Brian as is and wait for him to complain or not.

If he doesn't like it we can then decide how to tackle it again. :shrug:

**Comment by SelenaAungst** [comment]
Thanks @izaera! Ill close this one and forward my original PR.

**Comment by izaera** [comment]
@SelenaAungst Let me know how it goes :-)

**Comment by SelenaAungst** [comment]
Hi @izaera,
It looks like he did not like the solution ): https://github.com/brianchandotcom/liferay-portal/pull/142537
Do you have any recommendations on how to proceed from here?

**Comment by ethib137** [comment]
In this case this is a new pattern because the using arguments in an exception class is also a new pattern. The only other place this is used is `RequiredLocaleException`. `RequiredLocaleException` is quite isolated though. That exception is only thrown from an action command within a try catch that adds the exception to session errors so that the JSP can translate it. 

Alternatively, `ClientExtensionEntryTypeSettingsException` can show up in many places since it's thrown when calling a util method `ClientExtensionEntryLocalServiceUtil.addOrUpdateClientExtensionEntry`. In this case it makes more sense to expect more generic error handling such as `e.getMessage()` returning something understandable.

So in this situation, it looks to me like the best option is the proposed solution or to do nothing at all and expect anyone programatically dealing with the exception to know how to properly print the message: `out.println("An exception occurred: " + LanguageUtil.format(LocaleUtil.getDefault(), e.getMessageKey(), e.getMessageArguments()))`. I think we could propose this as a reason to Brian to add a new pattern, but I'm curious to hear @izaera 's thoughts.

**Comment by izaera** [comment]
I suggested to create that LPS because someone in the community slack said he had lost a huge amount of time due to this exception not showing any message in the logs, which is quite understandable so I don't think leaving it as is is an option.

Now, I've run this search to find exceptions that use `LanguageUtil.format`:

```
$ find . -name "*Exception.java" | xargs grep -F LanguageUtil.format
```

And I got three files:

```
./modules/apps/change-tracking/change-tracking-api/src/main/java/com/liferay/change/tracking/exception/CTLocalizedException.java
./modules/apps/info/info-api/src/main/java/com/liferay/info/exception/InfoFormFileUploadException.java
./modules/apps/info/info-api/src/main/java/com/liferay/info/exception/InfoFormValidationException.java
```

None of them use `LanguageUtil` to compose the technical exception message. Instead they have a `getLocalizedMessage` method to obtain the human friendly message and either they leave the technical message empty, or they pass it explicitly as an argument to the constructor.

In this case we don't need to provide a `getLocalizedMessage` method because we wouldn't use it anyway (since there's a JSP tag that is already doing that).

So, one option we could try is providing a technical message as an additional argument, then rewriting all the places where this exception is thrown.

Something like:

```java
public ClientExtensionEntryTypeSettingsException(String msg, String messageKey, Object... messageArguments) {
	super(msg);

	_messageKey = messageKey;
	_messageArguments = messageArguments;
}
```

and then throw it like this:

```java
throw new ClientExtensionEntryTypeSettingsException(
	"Invalid CSS URL: " + cssURL, 
	"css-url-x-is-invalid", 
	cssURL
);
```

**Comment by izaera** [comment]
If you look at the code, it looks (and probably is :sweat_smile: ) quite pedantic, but it's true that relying on a localization framework and assume that the keys will be correctly set and all that is a bit of an abuse.

In the end, if you hardcode the message, it will always be available no matter what, whereas making the error layer (exceptions) depend on a higher level layer (localization) may break somehow.

**Comment by izaera** [comment]
@SelenaAungst @ethib137 :point_up:

**Comment by ethib137** [comment]
@izaera fair point... it is pedantic but it's easy to understand and follows existing patterns. I think your approach of changing the signature to `String msg, String messageKey, Object... messageArguments` is probably the best way to fix this. @SelenaAungst , let me know if you need any help implementing this.

**Comment by SelenaAungst** [comment]
Hi @ethib137 @izaera,
It actually used to be formatted in that way but was changed here https://github.com/brianchandotcom/liferay-portal/commit/3eb00b18c43566b2a2ef7670e12af6d522682aee causing the current issue.
It was changed for https://liferay.atlassian.net/browse/LPS-155165.
Should I just revert the exception file and thrown exceptions?

**Comment by ethib137** [comment]
@SelenaAungst this would be different than just reverting. We would keep the single Exception class Brian created, but just update the signature of its constructor to match what @izaera is suggesting. Then we would need to update all instances of the exception being thrown to match this signature. Does that make sense?

**Comment by SelenaAungst** [comment]
I tried to update the changes here but forgot to reopen the PR first, so I resent here: https://github.com/liferay-frontend/liferay-portal/pull/3775

**Pull request closed without merging**
