### PR TITLE
LPS-157028 Add a test to assert get ManyToMany relationship details as nested fields_6

### PR DESCRIPTION
**Pull request by Hijky**
Background
Add a test to assert get ManyToMany relationship details as nested fields_6

Test Plan
Given university created
And Given subject created
And Given manyToMany relationship universitySubjects created
And Given two university entries created
And Given two subject entries created
When each subject related to each universtity
Then I receive correct information about the related objects o/c/universities?nestedFields=universitiesSubjects

JIRA Ticket
https://issues.liferay.com/browse/LPS-157028

### CODE REVIEW

**Comment by Hijky** [comment]
ci:test:headless-frontend-functional:nocompile

**Comment by Hijky** [comment]
ci:test:sf

**Comment by Hijky** [comment]
ci:test:headless-frontend-functional:nocompile

**Review by magjed4289 — APPROVED** [review]

**Comment by magjed4289** [comment]
ci:forward

**Pull request closed without merging**
