### PR TITLE
LPS-124914 Migrate instances of AlloyEditor in Commerce commerce-product-definitions-web

### PR DESCRIPTION
**Pull request by julien**
The `editorName` attribute has been removed from the
`<liferay-ui:input-localized>` tag instance, so that it uses
`_EDITOR_WYSIWYG_DEFAULT`, which is `ckeditor`.

**Test plan**

- Deploy the `commerce-product-definitions-web` module
- From the global menu, select the **Control Panel** tab
- Navigate to **Sites**
- Create a new site based on the **Speedwell** template
- From the global menu, select the **Commerce** tab
- Select **Products**
- Edit an existing product
- Assert that a ckeditor instance is visible under **Full Description**

**Before**

**After**

**PS**
Sending this for an internal review, before sending it @liferay-commerce

### CODE REVIEW

**Review by jbalsas — APPROVED** [review]
LGTM!

**Comment by julien** [comment]
ci:stop

**Comment by julien** [comment]
ci:close

**Comment by julien** [comment]
Submitted [here](https://github.com/liferay-commerce/liferay-portal/pull/446)

**Pull request closed without merging**
