### PR TITLE
LPS-165964 portlet-content-editable should have better contrast (accessibility)

### PR DESCRIPTION
**Pull request by pat270**
https://issues.liferay.com/browse/LPS-165964

@allen-ziegenfus I made changes to `/modules/apps/site-initializer/site-initializer-liferay-learn/`. I wasn't sure if this is needed. I'll remove the commit if not.

### CODE REVIEW

**Comment by allen-ziegenfus** [comment]
@pat270  That looks fine!

**Comment by dsanz** [comment]
ci:forward

**Comment by dsanz** [comment]
ci:stop

**Comment by dsanz** [comment]
ci:forward

**Pull request closed without merging**
