### PR TITLE
LPS-199234 Allow admins to configure session.timeout.auto.* properties

### PR DESCRIPTION
**Pull request by izaera**
I've implemented this as a multi-staged configuration based on the following hierarchy:

1. Site configuration
2. Instance configuration
3. System settings
4. Portal properties

This means that the first level where it is configured is the one that is used.

This is how the configuration looks like in site settings:

image

### CODE REVIEW

**Comment by izaera** [comment]
I've realized now that I'm missing the system settings level in the implementation, so I'm setting this to draft until I fix it.

**Comment by izaera** [comment]
Asked this in slack regarding this implementation -> https://liferay.slack.com/archives/C03LW8NUK/p1697633724282199 because I'm not totally sure this is the simplest way to do it...

**Comment by izaera** [comment]
This is done. I've reworked it to use `ConfigurationProvider` and removed the portal property.

**Review by bryceosterhaus — APPROVED** [review]
LGTM!

**Comment by izaera** [comment]
ci:forward

**Comment by izaera** [comment]
ci:test:relevant

**Comment by izaera** [comment]
ci:test:relevant

**Comment by izaera** [comment]
ci:forward

**Comment by mateusralv** [comment]
I'm on it 🕵🏽

**Comment by mateusralv** [comment]
Hi @izaera the failures are not related.

The test [LocalFile.SitetemplatesUsecase#SiteTemplatePageLinkInWebContentRedirectCorrectly ](https://testray.liferay.com/home/-/testray/case_results/2447892918)returned as a single failure but I ran it locally on the PR bundle and it passed. 🟢 

[Testray comparison](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1698419580161&testrayRunIdA=2447500155&testrayRunIdB=2447885139)

**Comment by izaera** [comment]
ci:forward:force

**Comment by izaera** [comment]
ci:forward:force

**Comment by izaera** [comment]
ci:forward:force

**Comment by izaera** [comment]
Manually sent as https://github.com/brianchandotcom/liferay-portal/pull/142981

**Pull request closed without merging**
