### PR TITLE
LPS-124915 Migrate instances of AlloyEditor in Commerce commerce-product-type-virtual-web

### PR DESCRIPTION
**Pull request by julien**
The `editorName` attribute has been removed from the
`<liferay-ui:input-localized>` tag instance, so that it uses
`_EDITOR_WYSIWYG_DEFAULT`, which is ckeditor.

**Test plan**

- Deploy the `commerce-product-type-virtual-web` module
- From the global menu, select the **Control Panel** tab
- Navigate to **Sites**
- Create a new site based on the **Speedwell** template
- From the global menu, select the **Commerce** tab
- Select **Products**
- Create a new **virtual** product
- Select the **Virtual** tab
- Toggle the **Enable Terms of Use** check box
- Assert that a ckeditor instance is visible and usable

**Before**

**After**

**PS**

Submitting this for an internal review before sending to @liferay-commerce

### CODE REVIEW

**Comment by jbalsas** [comment]
Looks good to me, @julien!

Feel free to wrap up all commerce PRs together and send them forward with my blessing 😉

**Comment by julien** [comment]
Thanks @jbalsas, I'll do that now.

**Comment by julien** [comment]
ci:stop

**Comment by julien** [comment]
ci:close

**Comment by julien** [comment]
Submitted [here](https://github.com/liferay-commerce/liferay-portal/pull/446)

**Comment by julien** [comment]
ci:stop

**Pull request closed without merging**
