### PR TITLE
LPS-187257 add doAsGroupId to session_click request to avoid redundant calculations

### PR DESCRIPTION
**Pull request by antonio-ortega**
Forward port of [LPS-135925](https://liferay.atlassian.net/browse/LPS-135925), to be more specific [this commit](https://github.com/liferay/liferay-portal-ee/pull/24793/commits/774599703cea52f03638c6a9f4f9fefa5cbc2860).

### CODE REVIEW

**Comment by antonio-ortega** [comment]
ci:reopen

**Comment by antonio-ortega** [comment]
ci:test:sf

**Comment by antonio-ortega** [comment]
ci:test:relevant

**Comment by antonio-ortega** [comment]
ci:test:sf

**Comment by deborasoliveira** [comment]
I'll take a look at it.

**Comment by deborasoliveira** [comment]
hi @antonio-ortega, 
_js-unit-jdk8/0/0_ is failing in the relevant run. Could you take a look at this? This is the only failure that I think might be related to the changes you made, the other failures are unrelated. 
```
     [exec] Summary of all failing tests
     [exec] FAIL test/liferay/util/session.es.js
     [exec]   ??? Session API ??? getSessionValue ??? GETs the session_click endpoint
     [exec] 
     [exec]     expect(jest.fn()).toHaveBeenCalledWith(...expected)
     [exec] 
     [exec]     Expected: "http://localhost:8080/c/portal/session_click", Anything
     [exec]     Received: "http://localhost:8080/c/portal/session_click?doAsGroupId=20126", {"body": {}, "headers": {Symbol(map): {}}, "method": "POST"}
     [exec] 
     [exec]     Number of calls: 1
     [exec] 
     [exec]       29 | 			expect(fetch).toHaveBeenCalledTimes(1);
     [exec]       30 | 
     [exec]     > 31 | 			expect(fetch).toHaveBeenCalledWith(
     [exec]          | 			              ^
     [exec]       32 | 				'http://localhost:8080/c/portal/session_click',
     [exec]       33 | 				expect.anything()
     [exec]       34 | 			);
     [exec] 
     [exec]       at Object.<anonymous> (test/liferay/util/session.es.js:31:18)
     [exec]       at processTicksAndRejections (node:internal/process/task_queues:96:5)
     [exec] 
     [exec]   ??? Session API ??? setSessionValue ??? POSTs a simple key/value to the session_click endpoint for basic values
     [exec] 
     [exec]     expect(received).toBe(expected) // Object.is equality
     [exec] 
     [exec]     Expected: "http://localhost:8080/c/portal/session_click"
     [exec]     Received: "http://localhost:8080/c/portal/session_click?doAsGroupId=20126"
     [exec] 
     [exec]       63 | 			expect(fetch).toHaveBeenCalledTimes(1);
     [exec]       64 | 
     [exec]     > 65 | 			expect(fetch.mock.calls[0][0]).toBe(
     [exec]          | 			                               ^
     [exec]       66 | 				'http://localhost:8080/c/portal/session_click'
     [exec]       67 | 			);
     [exec]       68 | 
     [exec] 
     [exec]       at Object.<anonymous> (test/liferay/util/session.es.js:65:35)
     [exec]       at processTicksAndRejections (node:internal/process/task_queues:96:5)
     [exec] 
     [exec]   ??? Session API ??? setSessionValue ??? POSTs a key/serializedValue to the session_click endpoint for object values
     [exec] 
     [exec]     expect(received).toBe(expected) // Object.is equality
     [exec] 
     [exec]     Expected: "http://localhost:8080/c/portal/session_click"
     [exec]     Received: "http://localhost:8080/c/portal/session_click?doAsGroupId=20126"
     [exec] 
     [exec]       78 | 			expect(fetch).toHaveBeenCalledTimes(1);
     [exec]       79 | 
     [exec]     > 80 | 			expect(fetch.mock.calls[0][0]).toBe(
     [exec]          | 			                               ^
     [exec]       81 | 				'http://localhost:8080/c/portal/session_click'
     [exec]       82 | 			);
     [exec]       83 | 
     [exec] 
     [exec]       at Object.<anonymous> (test/liferay/util/session.es.js:80:35)
     [exec]       at processTicksAndRejections (node:internal/process/task_queues:96:5)
     [exec] 
     [exec] 
     [exec] Test Suites: 1 failed, 57 passed, 58 total
     [exec] Tests:       3 failed, 3 skipped, 459 passed, 465 total
     [exec] Snapshots:   8 passed, 8 total
     [exec] Time:        13.522s
     [exec] Ran all test suites.
     [exec] Command /opt/dev/projects/github/liferay-portal/modules/node_modules/@liferay/npm-scripts/node_modules/.bin/jest --config TEMP_jest.config.json exited with code 1
     [exec] Received 1
     [exec] error Command failed with exit code 1.
     [exec] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
     [exec] 
     [exec] > Task :apps:frontend-js:frontend-js-web:packageRunTest FAILED
     [exec] 
```
[Comparison run](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=2&testrayRunIdB=2354506769&testrayRunIdA=2353392589&statusB=3)

**Comment by antonio-ortega** [comment]
Thanks for catching this @deborasoliveira 

I'm going to have a look at this case to fix it.

**Pull request closed without merging**
