### PR TITLE
LPS-139334 Text Edition Toolbar does not appear when highlighting a text in a table row

### PR DESCRIPTION
**Pull request by markocikos**
JIRA: https://issues.liferay.com/browse/LPS-139334

See steps to reproduce in the JIRA ticket.

In this PR, we are:
- Moving table tools handling from `balloonToolbars.create` API to own plugin. This is because `balloonToolbars.create` API relies on CSS selectors. To achieve the desired effect, we would need to set higher priority of text node trigger than a `td` node trigger. I believe this is impossible, as it is impossible to select a text node with a CSS selector.
- Disabling insert button creation within a table
- Disabling text toolbar if there is not a single alphanumeric in selection. Without this, or a similar restriction, text toolbar opens on multiple cell selection.
- Reverting temporary CI test ignore /cc @magjed4289 

Sidenote: I noticed during testing that the 'Headers' option in table toolbar does not work. This is not related to this PR, the feature never worked. We can fix this in a separate PR.

I'm flagging @carloslancha and @julien as reviewers. @diegonvs is the most familiar with the task, but he is on PTO.

Before PR:
before

After PR:
after

### CODE REVIEW

**Comment by markocikos** [comment]
@magjed4289 Can you please take a look at the CI failure in https://github.com/liferay-frontend/liferay-portal/pull/1761#issuecomment-996118274. The first one is unrelated, but the second one is related, it's the one we are enabling in this PR. Looking at [before and after images](https://testray.liferay.com/reports/production/logs/2021-12/test-1-31/test-portal-acceptance-pullrequest(master)/1463/functional-tomcat90-mysql57-jdk8/0/1/LocalFile.BalloonEditor_CanEditTextInTable/summary.html.gz), it looks to me like behavior is correct.

**Review by diegonvs — APPROVED** [review]
Looks good! Thanks Marko :)

@julien @carloslancha would like to leave any comments?

**Comment by diegonvs** [comment]
ci:test:relevant

**Comment by diegonvs** [comment]
ci:test:relevant

**Comment by diegonvs** [comment]
@john-co @zhangyan0701, `LocalFile.BalloonEditor#CanEditTable` is failing in this PR and [on this PR](https://github.com/liferay-lima/liferay-portal/pull/2624#issuecomment-1009410597). I ran `ant -f build-test.xml run-selenium-test -Dtest.class="BalloonEditor#CanEditTable"` but I'm not understanding what is failing because the x-path `//a[contains(@class,'cke_button') and contains(@title,'OK')] | //a[contains(@class,'cke_button') and contains(@data-restore-title,'OK')]//span[contains(@class,'check_icon')]` is defined :/

**Comment by susanchen3** [comment]
taking a look!

**Comment by susanchen3** [comment]
**LocalFile.BalloonEditor#CanEditTextInTable** is failing because `AssertVisible(locator1 = "CKEditor#TOOLBAR_ANY_ITEM_BUTTON");` is missing `key_titleName = "test"`

still looking into **LocalFile.BalloonEditor#CanEditTable**

**Comment by susanchen3** [comment]
I can do more investigating tmr, unless @zhangyan0701 has the bandwidth to take a look? :eyes:

**Comment by zhangyan0701** [comment]
The two failed BalloonEditor tests both look more like Test Fix.

**LocalFile.BalloonEditor#CanEditTextInTable** - Missing the value for variable ${key_titleName}.

**LocalFile.BalloonEditor#CanEditTable** - Also agree with Susan, doubleclick should work in this test.

@diegonvs The test LocalFile.BalloonEditor#CanEditTable in PR https://github.com/liferay-lima/liferay-portal/pull/2624 was failed with difference issue from this PR. I need some time to investigate it.

**Comment by zhangyan0701** [comment]
Hi @susanchen3 
Looks like you have been already working on the fix of the failed BalloonEditor tests, right? I saw you testing PR and the test results look good.

@diegonvs Please see my comment in https://github.com/liferay-lima/liferay-portal/pull/2624#issuecomment-1011058127.

**Comment by markocikos** [comment]
@susanchen3 @zhangyan0701 

After this PR, `LocalFile.BalloonEditor#CanEditTable` is no longer correct. Double-click will not fix it. With this PR, we are changing that selecting text in a cell opens the text toolbar. Thrash can icon is a part of table toolbar. We now show table toolbar only of the cell is empty. You can see this behavior in 'after PR' gif in opening comment. To update this test, I think we should remove the step before, `task ("Write in a cell")`

We are re-enabling `LocalFile.BalloonEditor#CanEditTextInTable` in this PR. The problem with that one, as far as I can tell, is that `//a[contains(@href,"${key_titleName}")]` does not correctly check if text toolbar is open. 'After failure' image is correct, I believe that implied that the behavior is correct. I think it is the DOM test we need to change, to accurate check something from the text toolbar.

/cc @diegonvs

**Comment by markocikos** [comment]
Sidenote - @diegonvs  The bug in https://github.com/liferay-lima/liferay-portal/pull/2624#issuecomment-1011058127 is unrelated to two issues in this PR. It may be caused by https://github.com/liferay-lima/liferay-portal/pull/2624/commits/958ab22a6167d093b0f8965217e15250c2b5aedf

**Comment by susanchen3** [comment]
Hi @markocikos,

After this PR, for `LocalFile.BalloonEditor#CanEditTable` it looks like triple clicking the text makes the **text** toolbar popup and double/single clicking a cell makes the **table** toolbar popup (regardless if there is text in it or not). You can see in the 'after PR' gif that clicking in the cell with text still displays the **table** toolbar. I was able to reproduce this locally as well. Can you confirm this behavior?

For `LocalFile.BalloonEditor#CanEditTextInTable`, I think I have a test fix for it. The path is fine, its just missing the 'key_titleName' variable that is in `//a[contains(@href,"${key_titleName}")]`.

**Comment by markocikos** [comment]
> After this PR, for `LocalFile.BalloonEditor#CanEditTable` it looks like triple clicking the text makes the **text** toolbar popup and double/single clicking a cell makes the **table** toolbar popup (regardless if there is text in it or not). You can see in the 'after PR' gif that clicking in the cell with text still displays the **table** toolbar. I was able to reproduce this locally as well. Can you confirm this behavior?

Ah yes, you are right, it is not only empty cell that opens table toolbar. Sorry, my mistake to say it! To directly convey the code, It is **selection of text** that opens the text toolbar. Single click never selects text (always shows table toolbar). Double click on a word selects text (shows text toolbar). Double click in a cell, but not on a word, does not select text (shows table toolbar). Triple-click anywhere in cell selects the whole text in the cell (shows table toolbar only if the call is empty).

**Comment by susanchen3** [comment]
Nice, thanks for the response! I'll send in some test fixes, run relevant and see how it goes :crossed_fingers:

**Comment by john-co** [comment]
Hi @markocikos , could you invite me and @susanchen3 as collaborator to your repo? We can cherry pick and push in the changes to your branch to maintain this PR.

**Comment by john-co** [comment]
The PR is ready here: https://github.com/markocikos/liferay-portal/pull/198

**Comment by markocikos** [comment]
I took the https://github.com/markocikos/liferay-portal/pull/198 branch, rebased and force-pushed here. With tests green and review green, this is ready to roll out!

**Comment by markocikos** [comment]
ci:forward

**Comment by susanchen3** [comment]
ci:forward

**Pull request closed without merging**
