### PR TITLE
LPS-142737 Fix rendering issues in frontend-taglib-clay-sample-web

### PR DESCRIPTION
**Pull request by julien**
The label attribute isn't supposed to be HTML in StickerTag, so
this example has been removed. The URL for the images in the sticker
sample has been fixed so that it doesn't trigger a 404 error.

**Test plan**
- Fetch this branch
- Deploy the `frontend-taglib-clay-sample-web` OSGi module
- Create a new (blank) page
- Add the "Clay Sample" widget
- Publish the page
- Assert that there are no rendering issues

**Before**

**After**

### CODE REVIEW

**Comment by john-co** [comment]
ci:test:relevant

**Comment by john-co** [comment]
ci:test:bundle

**Comment by john-co** [comment]
Reviewed. Test failures are unrelated. :heavy_check_mark:

**Review by victorg1991 — APPROVED** [review]
LGTM :)

**Comment by julien** [comment]
ci:test:relevant

**Comment by julien** [comment]
@liferay-frontend if the CI tests don't pass this time, I think I'll just manually forward

**Review by john-co — APPROVED** [review]

**Comment by carloslancha** [comment]
Please don't forward, I need a bit more context about this to understand why we are removing a sample. I'll call @julien to make it faster. Thx!! :D

**Comment by carloslancha** [comment]
ci:forward

**Comment by carloslancha** [comment]
@julien since @john-co approved the pr could you please manually send this to Bchan? Thx!!

**Comment by julien** [comment]
@carloslancha sure :+1:

**Comment by julien** [comment]
Submitted [here](https://github.com/brianchandotcom/liferay-portal/pull/110212)

**Pull request closed without merging**
