### PR TITLE
LPD-8726 Set Editor Config Contributor FF as a release FF

### PR DESCRIPTION
**Pull request by markocikos**
### References

- Parent task: [LPD-7915 Move Editor Config Contributor CET FF to release status](https://issues.liferay.com/browse/LPS-123456)

### What is the goal of this PR?

We're moving Editor Config Contributor CET FF to release status.

I'm opening this PR as a draft, to hit the ground running when the feature passes product review.

### What does it look like?

image

### CODE REVIEW

**Comment by markocikos** [comment]
ci:test:sf

**Comment by bryceosterhaus** [comment]
LGTM!

**Comment by dsanz** [comment]
ci:forward

**Comment by markocikos** [comment]
SF failure in https://github.com/liferay-frontend/liferay-portal/pull/3958#issuecomment-1918825637 is unrelated, I pushed autogenerated output of `ant format-source-current-branch`.

**Comment by markocikos** [comment]
ci:test:sf

**Comment by markocikos** [comment]
ci:forward

**Comment by markocikos** [comment]
ci:report:2533278327

**Comment by dsanz** [comment]
It's very strange that this PR can cause any error that was not being there before. We might seriously consider forwarding

@markocikos @pablo-agulla

**Comment by markocikos** [comment]
Testray seems to be down atm, that's why nothing comes from `ci : report`s

**Comment by dsanz** [comment]
ci:report:2533278327

**Comment by dsanz** [comment]
ci:reevaluate:1327401_3541

**Comment by markocikos** [comment]
ci:report:2533278327

**Comment by markocikos** [comment]
No unique failures, based on report in https://github.com/liferay-frontend/liferay-portal/pull/3958#issuecomment-1920812937

**Comment by markocikos** [comment]
ci:test:stable

**Comment by markocikos** [comment]
Force-pushed without SF junk, that got fixed upstream.

**Comment by markocikos** [comment]
ci:test:sf

**Comment by markocikos** [comment]
ci:forward

**Comment by dsanz** [comment]
ci:report:2533351896

**Comment by dsanz** [comment]
no unique failures, forwarding

**Comment by dsanz** [comment]
ci:forward:force

**Comment by dsanz** [comment]
ci:forward:force

**Pull request closed without merging**
