### PR TITLE
LPS 138264 Mime types filter tree with colored icons

### PR DESCRIPTION
**Pull request by claraizquierdo**
Motivation
=======
[Link to story or ticket](https://issues.liferay.com/browse/LPS-138264)

Proposed Solution
========
We changed TreeviewCard component so that nodes accept the property iconCssClass, that will be applied to the icon if both icon and iconCssClass are present for the node.

Change summary:
---------------
* LPS-138264 Adding cssClass prop to add color to the icons
* LPS-138264 Add icon class to TreeviewCard component
* LPS-138264 Add tests for Treeview new iconCssClass prop for nodes

Steps to Verify:
----------------
1. Add some documents and media to your site
1. Go to Content Dashboard
1. Open extension filter modal and check that the icons in the tree have colors
1. Open type filter modal and check that the icons in the tree do NOT have colors

### CODE REVIEW

**Review by markocikos — APPROVED** [review]
LGTM!

Nice job on the tests! :hugs:

**Review by julien — COMMENTED** [review]
Can't tell you about the Java part, but I trust @4lejandrito, as for the JS it looks good to me

**Comment by 4lejandrito** [comment]
@julien you're too optimistic. The test failure is my fault. We'll move this PR back to tango, fix it there and forward. Thanks!

**Comment by julien** [comment]
@4lejandrito I try to be optimistic, thanks for the additional information

**Comment by 4lejandrito** [comment]
See https://github.com/liferay-tango/liferay-portal/pull/1605.

**Comment by 4lejandrito** [comment]
ci:close

**Pull request closed without merging**
