### PR TITLE
[TS] LPS-148819 When inserting a video into AlloyEditor, a line break will be inserted each time you Save as Draft

### PR DESCRIPTION
**Pull request by holatuwol**
https://issues.liferay.com/browse/LPS-148819

### Steps to reproduce

1. Create a blog post
2. In the content section, switch to source view and add the following HTML (which imitates the HTML generated in 7.2.x when Xuggler integration is enabled):
```html
<p>AAAA</p>

<p>
<div class="liferayckevideo video-container" data-document-url="" data-width="400">
<div class="ckvideo-no-id"></div>
<script type="text/javascript">AUI().use("aui-base", "aui-video",function(A) {});</script></div>
</p>

<p>AAAA</p>
```
3. Save as draft
4. Save as draft again

**Actual result**
A line break is inserted each time you click "Save as Draft".

**Expected result**
No line breaks are inserted.

### CODE REVIEW

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Review by diegonvs — APPROVED** [review]

**Comment by diegonvs** [comment]
ci:test:relevant

**Comment by john-co** [comment]
Just started reviewing :)

**Comment by john-co** [comment]
**[Issues Related]**
- Blogs tests: Looks like `<p>` tag is not included when typing in the Blogs Content section.

[Before]
Before
[After]
After

I feel like this is a regression since [CKEditor](https://ckeditor.com/ckeditor-4/demo) would usually add `<p>` for text within the editor. There doesn't seem to be an issue when viewing the Blog on page, the text seems to correctly formatted by ckeditor and contained within `<p>` tag.
image


cc/ @austinchiang

**Comment by holatuwol** [comment]
Is there some way to update the test to not check for the `<p>` tag, since that's the cause for the issue we're trying to fix?

**Comment by john-co** [comment]
I'll work on a test fix then since this sounds like it was intentional.

**Comment by john-co** [comment]
Testing here: https://github.com/john-co/liferay-portal/pull/456

**Comment by john-co** [comment]
@austinchiang is working on a test fix at https://github.com/austinchiang/liferay-portal/pull/1292 since it looks like it affects a lot of blogs tests.

**Comment by holatuwol** [comment]
https://github.com/liferay-lima/liferay-portal/pull/2957

**Pull request closed without merging**
