### PR TITLE
LPS-124465 Avoid unwanted minification of `Liferay` global

### PR DESCRIPTION
**Pull request by wincent**
As explained in https://issues.liferay.com/browse/LPS-124465 our minification [takes some care](https://github.com/liferay/liferay-frontend-projects/blob/a33874a2630a07e24cd46421fb346235467ea6c5/projects/npm-tools/packages/npm-scripts/src/config/terser.config.js#L10-L12
) to avoid mangling property access.

Combined with the fact that `Liferay` is usually accessed as a global and therefore not minified, that means that we can rely on the minifier leaving strings like `Liferay.Language.get` untouched in the source. The LanguageFilter can then find those strings and substitute them on the fly.

In LPS-124465 we see a pattern that breaks this. `Liferay` is passed into a function, where, as a local binding, the minifier is free to rewrite it (eg. to `t`), so our source text now reads `t.Language.get` and the LanguageFilter does not substitute it.

Fix taken here is to avoid that pattern in `portlet.js` and everywhere else we seem to be doing it (not many places, all found with a crude regex for `\((\s*\w+\s*,)*\bLiferay\b(\s*,\s*\w+\s*)*\)`; that won't cover everything, like things split across multiple lines, but it will catch most things... probably everything).

Instead of:

```js
(function (Liferay) {
    // blah...
})(Liferay);
```

we just do:

```js
(function () {
    // blah...
})();
```

There was one place where we had:

```js
Liferay = window.Liferay || {};
```

Note that the minifier is "smart" enough to know that `Liferay` there is not a global, and it preserves the name. But prior to this PR, if you inspect the build output it does the unwanted `t` mangling; ie. before:

    Liferay=window.Liferay||{},function(t){ /* a bunch of stuff */ }(Liferay);

after:

    Liferay=window.Liferay||{},function(){ /* a bunch of stuff */ }();

### CODE REVIEW

**Comment by wincent** [comment]
Now observe SF blow up on this one because I tried to run it locally and it ran out of memory (probably due to having an `ant all` going at the same time...)

**Comment by wincent** [comment]
ci:test:bundle

**Comment by wincent** [comment]
We could look at adding a lint to stop anybody from doing anything like this again, but I am lazy, and propose that we only do that if it actually does happen again.

**Review by jbalsas — APPROVED** [review]
👍 

> We could look at adding a lint to stop anybody from doing anything like this again, but I am lazy, and propose that we only do that if it actually does happen again.

We could even agree to only do that if it actually happens at least twice again ;)

**Comment by wincent** [comment]
> We could even agree to only do that if it actually happens at least twice again ;)

Or if somebody paid us 5 Lifebucks.

**Comment by wincent** [comment]
Regression is gone:

Screenshot 2020-12-17 -164106-3CgNfuK8@2x

**Comment by jbalsas** [comment]
> LocalFile.CPCommerceSettings#ViewInstanceCurrenciesAvailable - Poshi Report - Poshi Summary - Console Output

This answers https://github.com/liferay-frontend/liferay-portal/pull/629#issuecomment-747495004, so I'd say let's get on with `redirect: "manual"` which we know is the way!

**Comment by jbalsas** [comment]
Forwarded manually to https://github.com/brianchandotcom/liferay-portal/pull/97045

**Comment by wincent** [comment]
> > LocalFile.CPCommerceSettings#ViewInstanceCurrenciesAvailable - Poshi Report - Poshi Summary - Console Output
> 
> This answers [#629 (comment)](https://github.com/liferay-frontend/liferay-portal/pull/629#issuecomment-747495004), so I'd say let's get on with `redirect: "manual"` which we know is the way!

And here too: https://github.com/liferay-frontend/liferay-portal/pull/632

**Pull request closed without merging**
