### PR TITLE
LPD-19840 Enable permission bypass when accessing DSM object entries from the fragment

### PR DESCRIPTION
**Pull request by dsanz**
Reference:
 * https://liferay.atlassian.net/browse/LPD-19840

In this PR, we let FDS fragment bypass any permission check when accessing any necessary, DSM managed object entries (such as `FDSEntry` and friends) to do its duties.

Reasoning is that any permission for such entities must be interpreted in the DSM context, and not in the fragment usage context. So, the fact that a user can't `VIEW` a given `FDSEntry` object means it won't be shown in the DSM, but still, that same user could consume the dataset when rendered through the fragment. See https://liferay.atlassian.net/browse/LPD-6836 for more context.

Notes:
 * This is a story we did not estimate yet. However, as solution is so straightforward, I'm sending it in a subtask
 * Some other solutions are possible, but the convenient to object entries via `defaultObjectEntryManager` makes us go through [objectEntryService](https://github.com/liferay/liferay-portal/blob/dc929f3b8eeffe163a17564938188e33a8b3a41f/modules/apps/object/object-service/src/main/java/com/liferay/object/service/impl/ObjectEntryServiceImpl.java#L286-L299) (instead of the local service). So, easiest way to bypass this is the trheadLocal pattern already used in portal.
 * This PR enables any user to consume any data-set view. Other permission limitations still apply, namely:
   * Permissions to view the page where fragment is
   * Permissions on individual data items being fetched by the FDS when rendering
   * Permissions on the actions that can be performed on such data items
 * There is another subtask to add a test. We need to estimate that one because we need to either sign in with a less privileged user in order to test this
 * Depending on the API REST endpoint targeted by the dataset, `guest` users may get a `403` forbidden http response when browsing the fragment, shown in a toast. This is expected and has to do with the FDS not being able to fetch data at all. I'm not dealing with this in this PR because it's not clear whether we want to keep or hide the toast

### CODE REVIEW

**Comment by dsanz** [comment]
ci:test:playwright

**Comment by dsanz** [comment]
ci:test:relevant

**Comment by dsanz** [comment]
ci:reevaluate:1407401_8922

**Review by markocikos — COMMENTED** [review]
@dsanz The code LGTM. My doubt about the solution are the implications.

> Reasoning is that any permission for such entities must be interpreted in the DSM context, and not in the fragment usage context.

Aren't those different sets of permissions? In DSM, we're taking about _admin_ permissions, with the emphasis on what they are allowed to create or modify. Here, in fragment renderer, we're talking about _end user_ permissions, with the emphases only on viewing. I believe that the consequence of removing all permission checks will be that anybody will be able to see the fragment, including guest users (not logged in). Are we ok with that?

**Comment by dsanz** [comment]
> Are we ok with that?

Yep I think so, because permissions about data being consumed still apply when end users interact with the FDS. If we look at DSM objects making up the FDS View as intermediaries to configure the FDS, then it makes sense not to tie end-users ability to consume the views because of such permissions, but rather use them only to administer them.

Perhaps I would agree on using the top-level, FDSEntry `VIEW` permission as an all-or-nothing gate to render the fragment, but stil that's an interpretation for such permission that goes beyond administration purposes. Story ticket provides some more context, aligned with this idea.

**Comment by dsanz** [comment]
ci:forward:force

**Comment by markocikos** [comment]
ci:forward:force

**Pull request closed without merging**
