### PR TITLE
LPS-196615 Change FDS Action url field type to long text

### PR DESCRIPTION
**Pull request by dsanz**
Reference: https://liferay.atlassian.net/browse/LPS-196615

In this PR we're making FDS Action URL field bigger as we need to store URLs longer than 280 characters

### CODE REVIEW

**Comment by dsanz** [comment]
Hey  @CarlosBrichete I don't think there is a relation between this change and the relevant. We're making an existing field bigger, for which there is no automation yet, what do you think?

**Comment by CarlosBrichete** [comment]
Hey @dsanz, failures are not related, LGTM :)

**Review by markocikos — APPROVED** [review]
@dsanz LGTM!

**Comment by markocikos** [comment]
ci:forward:force

**Pull request closed without merging**
