### PR TITLE
LPS-151395 Migrate frontend-taglib-clay to ESM build

### PR DESCRIPTION
**Pull request by izaera**
Let's see what CI has to say...

----

### Build times before this PR:

- `frontend-js-web`: 34"
- `frontend-js-components-web`: 18"
- `frontend-taglib-clay`: 27"

### Build times after this PR:

- `frontend-js-web`: 20"
- `frontend-js-components-web`: 16"
- `frontend-taglib-clay`: 24"

## Total saved time: 19"

### CODE REVIEW

**Comment by izaera** [comment]
ci:test:sf

**Comment by izaera** [comment]
ci:test:relevant

**Comment by izaera** [comment]
ci:test:sf

**Comment by izaera** [comment]
ci:test:relevant

**Comment by mateusralv** [comment]
This [error](https://github.com/liferay-frontend/liferay-portal/pull/2749#issuecomment-1259741697) seems strange to me, I will run Relevant again and analyze [the last results](https://github.com/liferay-frontend/liferay-portal/pull/2749#issuecomment-1259785596) to see if I find something. 🤔

**Comment by mateusralv** [comment]
ci:test:relevant

**Comment by mateusralv** [comment]
Hi @izaera, I could not finish the analysis of these failures today because had [148 ](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1664314533138&testrayRunIdA=1992193992&testrayRunIdB=1991981624)failures different from the master (seems to have occurred some problem on IC) and the new results are not yet available 😞  

I marked @/qafrontend in your Slack post, if no one can finish, I will do it tomorrow when I start working.

**Comment by yanan** [comment]
I've checked the relevant test results [comparison run](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=2&testrayRunIdB=1991981624&testrayRunIdA=1992193992&statusB=3), and here are some test failures might be related, @izaera could you help take a look when you have time? Thanks in advance! cc @john-co @mateusralv 

1. Problem when config asset publisher `Uncaught ReferenceError: delegateModule is not defined`
**Steps to reproduce:**
- go to localhost:8080
- add Asset Publish
- click on Options > Configuration
- notice there is no configurations for SCOPE,SOURCE, FILTER
pr_Asset-publisher-configuration-error
On master:
Asset-Publisher-Configration-Master

2. Error in browser console `Uncaught SyntaxError: cannot use import statement outside a module` Some cases are: Checked select all checkbox, adding a calendar to a widget page, LocalFile.ContentDashboardAuditGraph#CheckSecondPositionVocabularyCheckbox
**Steps to reproduce on checked the SelectAll checkbox:**
- Control Panel > Sites
- Checked `Select all` checkbox
pr_Select_all_sites
pr_error_adding_a_calendar

3. Error in browser console when adding a blog entry to a webpage `liferay-adm-loader`
**Steps to reproduce:**
- Menu > Content & Data > Blogs > Add a new blog
- go to localhost:8080 > add Blog to webpage
image
pr_error-adding-blog-entry-to-webpage

**Comment by izaera** [comment]
Fixed first error. Will revisit the following ones once we fix the impormaps errors -> https://liferay.slack.com/archives/CNBG06JS3/p1664362633777569

**Comment by izaera** [comment]
ci:test:relevant

**Comment by izaera** [comment]
The SF failure is fake. @bryceosterhaus and @dsanz are working on it I think.

**Comment by izaera** [comment]
@yanan @mateusralv Can you have another look at this PR once test relevant finishes? It's not urgent. Thanks :-)

**Comment by mateusralv** [comment]
Hi @izaera, I'll take a look asap 🕵🏽

**Comment by izaera** [comment]
ci:test:sf

**Comment by izaera** [comment]
ci:test:relevant

**Comment by mateusralv** [comment]
I'm taking a look at this [failures](https://github.com/liferay-frontend/liferay-portal/pull/2749#issuecomment-1273676561). 🕵🏽

**Comment by mateusralv** [comment]
Hey @izaera I made a [comparison run](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=2&testrayRunIdB=2002603198&testrayRunIdA=2002631484&statusB=3) and found some failures are related. When you have some time could you take a look?


Semantic failure:
[modules-semantic-versioning-jdk8/0/1](https://testray.liferay.com/home/-/testray/case_results/2002629573)
```
[exec] com.liferay.semantic.versioning.SemanticVersioningTest > testSemanticVersioning[/apps/portal-url-builder/portal-url-builder-api] FAILED
     [exec]     java.lang.AssertionError:   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec]     = ================================================== ========== ========== ========== ========== ==========
     [exec]     * com.liferay.portal.url.builder                     MINOR      3.0.0      3.0.0      3.1.0      VERSION INCREASE REQUIRED
     [exec]     	<   interface  com.liferay.portal.url.builder.AbsolutePortalURLBuilder
     [exec]     		+   method     forESModule(java.lang.String,java.lang.String)
     [exec]     			+   access     abstract
     [exec]     			+   return     com.liferay.portal.url.builder.ESModuleAbsolutePortalURLBuilder
     [exec]     	+   interface  com.liferay.portal.url.builder.ESModuleAbsolutePortalURLBuilder
     [exec]     		+   access     abstract
     [exec]     		+   implements com.liferay.portal.url.builder.facet.BuildableAbsolutePortalURLBuilder
     [exec]     		+   implements com.liferay.portal.url.builder.facet.CDNAwareAbsolutePortalURLBuilder
     [exec]     		+   implements com.liferay.portal.url.builder.facet.CacheAwareAbsolutePortalURLBuilder
     [exec]     		+   implements com.liferay.portal.url.builder.facet.PathProxyAwareAbsolutePortalURLBuilder
     [exec]     		+   method     build()
     [exec]     			+   access     abstract
     [exec]     			+   return     java.lang.String
     [exec]     		+   method     cache(com.liferay.portal.url.builder.facet.CacheAwareAbsolutePortalURLBuilder$CachePolicy)
     [exec]     			+   access     abstract
     [exec]     			+   return     java.lang.Object
     [exec]     		+   method     ignoreCDNHost()
     [exec]     			+   access     abstract
     [exec]     			+   return     java.lang.Object
     [exec]     		+   method     ignorePathProxy()
     [exec]     			+   access     abstract
     [exec]     			+   return     java.lang.Object
     [exec]     [Baseline Warning] Bundle Version Change Recommended: 5.1.0
     [exec]         at org.junit.Assert.fail(Assert.java:88)
```

---
### Failures in language page
Test case:
LocalFile.LanguageOverride#CanRemoveAllTranslationOverridesViaMenuItem

Steps to reproduce:
Open portal > go to Language Override > Add Language Key Or edit an existing one > Save Language Key > Try to edit the created language

https://user-images.githubusercontent.com/44584050/194958827-73e2b498-7829-414b-a8cb-5ea0beade37b.mp4

and
Open portal > go to Language Override

https://user-images.githubusercontent.com/44584050/194959551-7aa59bc4-88f4-408a-ab76-00dad6c23e12.mp4

---
### Failures in rules page
Testcases:
RolesAdmin#OrganizationRoleCanBeDeleted
RolesAdmin#RegularRoleCanBeDeleted
RolesAdmin#SiteRoleCanBeDeleted
RolesandpermissionsUsecase#ViewAutomaticAssignedRoles

Steps to reproduce:
Open portal > Roles > Organization Roles > Click on Add button

https://user-images.githubusercontent.com/44584050/194964233-b5242820-611d-431e-b024-be8ac26ec529.mp4

---
### Failures in Server Administration page
Test case:
SAML#ViewSingleLogoutAndForceAuthWithMultipleSPs

Steps to reproduce:
Open portal > Server Administration > when clicking on the profile button nothing happens :/ 

https://user-images.githubusercontent.com/44584050/194965384-3eb3acd8-2096-42b1-9edd-b6adcff6a806.mp4

**Comment by izaera** [comment]
I'm moving some of the commits (all those not belonging to LPS-1515395) to their own PR to send this in chunks -> https://github.com/liferay-frontend/liferay-portal/pull/2778

**Comment by izaera** [comment]
ci:test:sf

**Comment by izaera** [comment]
ci:test:relevant

**Comment by izaera** [comment]
ci:test:relevant

**Comment by izaera** [comment]
ci:test:relevant

**Comment by izaera** [comment]
@mateusralv Can you please check again? It says "build aborted" in one of the tests so I wonder if the rest is broken too :thinking:

**Comment by mateusralv** [comment]
Hey @izaera sorry for delay, I can take a look as soon as I start working tomorrow (side of Brazil), if it is very urgent I can ask another qa-FI to take a look. 🤔

**Comment by izaera** [comment]
@mateusralv It's OK, I can wait :+1:

**Comment by mateusralv** [comment]
I'm taking a look 👓

**Comment by mateusralv** [comment]
Hey @izaera through the [comparison](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=2&testrayRunIdB=2005434337&testrayRunIdA=2005340474&statusB=3) with the master I found failures related to your PR, when have a time could take a look? 
### Failures, not unique:

1. modules-semantic-versioning-jdk8/0/1
2. com.liferay.dispatch.service.test.DispatchLogLocalServiceTest
3. com.liferay.dispatch.web.test.DispatchLogDisplayContextTest
4. LocalFile.PortalSmokeUpgrade#ViewPortalSmokeArchive70106
5. com.liferay.document.library.app.local.service.test.DLAppLocalServiceWhenDeletingAFolderTest
6. com.liferay.document.library.app.local.service.test.DLAppLocalServiceWhenGettingAFileEntryTest
7. com.liferay.document.library.app.service.test.DLAppServiceWhenAddingAFileEntryTest
8. com.liferay.document.library.asset.auto.tagger.tensorflow.test.DLFileEntryAutoTaggerTest
9. com.liferay.document.library.content.change.tracking.test.DLContentTableReferenceDefinitionTest
10. com.liferay.document.library.content.service.persistence.test.DLContentPersistenceTest
11. com.liferay.document.library.content.service.test.DLContentLocalServiceTest
12. com.liferay.document.library.preview.audio.test.DLAudioFFMPEGAudioConverterTest
13. com.liferay.document.library.repository.portlet.file.repository.test.PortletFileRepositoryTest
14. com.liferay.document.library.repository.portlet.repository.test.PortletRepositoryTest
15. com.liferay.document.library.sync.service.persistence.test.DLSyncEventPersistenceTest
16. LocalFile.ObjectPortlet#CannotViewOtherUsersEntryWithOnlyAddPermission
17. com.liferay.document.library.opener.google.drive.test.DLOpenerGoogleDriveManagerTest
18. com.liferay.document.library.opener.service.persistence.test.DLOpenerFileEntryReferencePersistenceTest
19. com.liferay.document.library.opener.uad.anonymizer.test.DLOpenerFileEntryReferenceUADAnonymizerTest
20. com.liferay.document.library.opener.uad.exporter.test.DLOpenerFileEntryReferenceUADExporterTest
21. com.liferay.document.library.opener.upload.test.UniqueFileEntryTitleProviderTest
22. LocalFile.OpenIDConnect#AssertRegularRoleIsAssignedToOIDCUser

---
### Failures unique:
The failures in these tests are related to the reply buttom of a thread:
1. LocalFile.MentionsMB#CanViewMentionViaMBThreadReply
2. LocalFile.MBPermissions#CannotViewMessageViaNotificationWithoutPermissionsOnContentPage
3. LocalFile.MBPage#CanReplyToThreadAsGuest

Steps to reproduce:
Content & Data >  Message Boards  > Add new thread > Save new thread > Click on Reply

https://user-images.githubusercontent.com/44584050/195912214-df2179a4-c09c-45b1-a956-24a8035318c0.mp4

- LocalFile.ManagementToolbar#OrderButtonAsAToggleCanDisplayTooltip:
The failure of this test is also related, but the problem is in a path used in the test which I can fix it. 🤔 

---
### Flaky failures:
This tests passed when run locally:

1. LocalFile.Forms#ViewDefaultFieldNamesWithPunctuationCharacters

**Comment by izaera** [comment]
ci:test:sf

**Comment by izaera** [comment]
ci:test:relevant

**Comment by izaera** [comment]
@mateusralv I fixed the errors and catched some others that were left behind. In theory everything should work fine now :crossed_fingers:

**Comment by izaera** [comment]
Regarding:

>LocalFile.ManagementToolbar#OrderButtonAsAToggleCanDisplayTooltip:
>The failure of this test is also related, but the problem is in a path used in the test which I can fix it.

Do you need anything from me? Any clarification? If I understood correctly, you are saying that the problem is in the test itself, not the PR code, right?

**Comment by izaera** [comment]
l've screened some of the failing tests:

1. **LocalFile.CPCommerceProductMedia#AddAnImageToAnOption** : this works as in master. It looks weird because right after adding the new option "Color" the list below is disabled until you click it, but since this happens in master too I guess it's not due to the PR.

**Comment by izaera** [comment]
Since the previous build was aborted, I'm running test:relevant again to see what happens.

**Comment by mateusralv** [comment]
> Do you need anything from me? Any clarification? If I understood correctly, you are saying that the problem is in the test itself, not the PR code, right?

Yes, I can reproduce the test manually, the problem is only in one path in the poshi test that I can fix. One doubt, this fix I send in a PR only when this PR is merged? 🤔

**Comment by mateusralv** [comment]
Hey @izaera I have good news, the only mistakes are the two tests I mentioned earlier. 

- Forms#ViewDefaultFieldNamesWithPunctuationCharacters
The test fails in CI but works when I run in POSHI and manually. Can be a flaky failure

and 

- ManagementToolbar#OrderButtonAsAToggleCanDisplayTooltip
The same error as before, a path that changed and is used only in this test. manually passed

---
Failures not unique:

1. LocalFile.DisplayPageTemplatesWithMapping#ViewTypesDuringCreation
2. com.liferay.oauth2.provider.client.test.OAuth2WebServerServletTest
3. LocalFile.ObjectPermission#CanEditItsOwnEntryWithOnlyAddPermission
4. LocalFile.SiteTeams#AddSiteTeamRemoveUser
5. LocalFile.AutoTranslationGoogle#CanTranslateWCToJapaneseWithGoogle

So I believe this safe to forward 🎉 🚀

**Comment by izaera** [comment]
Forwarded as https://github.com/brianchandotcom/liferay-portal/pull/125119

**Pull request closed without merging**
