### PR TITLE
COMMERCE-4651 data renderer workflow status css scoped to affect only data set displays

### PR DESCRIPTION
**Pull request by FabioDiegoMastrorilli**
For displaying labels for commerce specific workflow statuses we added some logic that interferes with the default ones if not scoped.

Another solution would be adding these new rules directly in the admin theme.

cc @marco-leo

### CODE REVIEW

**Comment by FabioDiegoMastrorilli** [comment]
ci:test:sf

**Comment by jbalsas** [comment]
ci:test:relevant

**Review by jbalsas — APPROVED** [review]
Looks good enough to me!

**Comment by jbalsas** [comment]
ci:forward

**Pull request closed without merging**
