### PR TITLE
LPS-117074 Update liferay-ckeditor to 4.14.1-liferay.4

### PR DESCRIPTION
**Pull request by mateomustapic**
Update `liferay-ckeditor` in portal after https://issues.liferay.com/browse/LPS-117074 fix

### CODE REVIEW

**Comment by wincent** [comment]
FYI: got rid of all the extraneous commits by toggling the base away from and back to `master`:

Screenshot 2020-07-22 -135010-3db2EFJR@2x

**Comment by wincent** [comment]
ci:test:sf

**Comment by wincent** [comment]
ci:test:relevant

**Comment by carloslancha** [comment]
> FYI: got rid of all the extraneous commits by toggling the base away from and back to master:

Nice trick!

**Comment by carloslancha** [comment]
ci:forward

**Pull request closed without merging**
