### PR TITLE
LPS-181339 |automation  FDSViews#CanCreateView

### PR DESCRIPTION
**Pull request by alexmds2004**
**Description**
Given access to Datasets admin page

**And** Add a Dataset

**When** go to the View page of the dataset created.

**And** Filling the name with "View Test" And  Clicking Save button

**Then** Confirm the view name in View page as expected

**And** Confirm the description is "Test Description"

**Link JIRA**
https://issues.liferay.com/browse/LPS-181339

### CODE REVIEW

**Comment by alexmds2004** [comment]
ci:test:sf

**Comment by alexmds2004** [comment]
ci:test:sf

**Comment by alexmds2004** [comment]
ci:test:frontend

**Comment by alexmds2004** [comment]
ci:test:sf

**Review by mateusralv — APPROVED** [review]
Great !!!!!

**Comment by mateusralv** [comment]
ci:forward

**Pull request closed without merging**
