### PR TITLE
LPS-156749 Update clay-css dependencies to v2.24.3

### PR DESCRIPTION
**Pull request by georgel-pop-lr**

### CODE REVIEW

**Comment by georgel-pop-lr** [comment]
ci:test:relevant

**Comment by matuzalemsteles** [comment]
Hey @susanchen3 could you also look at that PR as well when you have time? looks like the tests are failing here too.

**Comment by susanchen3** [comment]
Taking a look now! :detective:

**Comment by susanchen3** [comment]
The radio button looks off on this PR as well as seen [here](https://github.com/liferay-frontend/liferay-portal/pull/2437#issuecomment-1169021555). 

Reviewed. Test failures unrelated :heavy_check_mark: Looks good to manually forward. Not sure if you wanted me to manually forward this @georgel-pop-lr 

[Comparison run:](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=2&testrayRunIdB=1891010917&testrayRunIdA=1890661549&statusB=3) 
- LocalFile.ManagementToolbar#ResponsiveModeNewButtonAsIconButton: Flaky 
- LocalFile.InstanceSettings#ExportedFactoryConfigurationCanBeImported: Not unique to this PR
- LocalFile.CPReportsadmin#AddSchedule: Not unique to this PR

**Comment by georgel-pop-lr** [comment]
Manually forwarded: https://github.com/brianchandotcom/liferay-portal/pull/119533

**Pull request closed without merging**
