### PR TITLE
LPS-173985 - Update npm-scripts to latest

### PR DESCRIPTION
**Pull request by bryceosterhaus**
fixes https://issues.liferay.com/browse/LPS-173985

### CODE REVIEW

**Comment by izaera** [comment]
@bryceosterhaus Shouldn't this PR include the change in ComboServlet too? :thinking:

**Comment by bryceosterhaus** [comment]
ci:test:sf

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by deborasoliveira** [comment]
I'll take a look at it 👍🏽

**Comment by deborasoliveira** [comment]
Hi @bryceosterhaus! The failures seem to be unrelated to your PR according to the [Testray comparison](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=2&testrayRunIdB=2189577757&testrayRunIdA=2188024324&statusB=3). 
- I've also analyzed _com.liferay.oauth2.provider.client.test.AnnotationsAndHttpApplicationClientTest_ and _com.liferay.oauth2.provider.token.endpoint.test.RefreshTokenAuthorizationGrantTest_  and they seem to be flaky failures.

**Comment by bryceosterhaus** [comment]
manual forward at https://github.com/brianchandotcom/liferay-portal/pull/129972

**Pull request closed without merging**
