### PR TITLE
LPS-125509 Replaces metal-dom's closest function with native closest on commerce-product-options-web

### PR DESCRIPTION
**Pull request by diegonvs**
It was a leftover from:

https://github.com/liferay-frontend/liferay-portal/pull/462
https://issues.liferay.com/browse/LPS-122392

I need help for finding the use case commerce. Could you guys help me?

/cc @marco-leo @FabioDiegoMastrorilli @john-co

### CODE REVIEW

**Review by bryceosterhaus — APPROVED** [review]
Code wise this LGTM!

**Comment by john-co** [comment]
Reviewed. Test failures are unrelated. :heavy_check_mark: 
- modules semantic versioning is a recent failure affecting upstream and other PRs
https://liferay.spiraservice.net/16/TestCase/229530.aspx
- modules integration test aborted due to a thread lock. Rerunning the test will likely pass.

**Comment by john-co** [comment]
ci:test:relevant

**Comment by john-co** [comment]
ci:forward

**Pull request closed without merging**
