### PR TITLE
LPS-119875 Replaces custom ae_autolink with ootb autolink plugin

### PR DESCRIPTION
**Pull request by jbalsas**
Based on [Page freezes when long alphanumeric strings are pasted into a Blogs editor](https://issues.liferay.com/browse/LPS-119875). 

I haven't thoroughly tested this, but I suspected either our `addimages` or our `ae_autolink` plugins could be at fault, since they're both 2 plugins that inspect `keypress` and `paste` operations and do something with it, so it stands to reason that big chunks of text could impact their performance.

I reproduced on my own and [got confirmation](https://issues.liferay.com/browse/LPS-119875?focusedCommentId=2233816&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-2233816) from @ambrinchaudhary that it did not reproduce without the `ae_autolink` plugin.

So, based on that, going here on a limb (which I wanted to do anyways) and:
- Replaced `ae_autolink` with [`autolink`](https://ckeditor.com/cke4/addon/autolink). All the functionality with none of the bugs or maintenance 🤞 
- Sneaked in `autolink` by default in the CKEditor configuration so we can get this everywhere

I tested and couldn't reproduce the frozen AlloyEditor, so hoping this does the trick!

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:test:sf

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
Seeing as everything is green and this is an FP5 blocker I'm going to self-forward this... 

selffive

**Comment by jbalsas** [comment]
ci:forward

**Comment by carloslancha** [comment]
> Seeing as everything is green and this is an FP5 blocker I'm going to self-forward this...

<a href="https://gitme.me/image?url=https%3A%2F%2Fmedia3.giphy.com%2Fmedia%2FlOm54CjDUT8LPMKwzF%2Fgiphy.gif&token=selfhighfive" data-gitmeme-token="selfhighfive"></a>

**Pull request closed without merging**
