### PR TITLE
LPS-134141 | Taglib aui:fieldset does not include legend when markupView is lexicon

### PR DESCRIPTION
**Pull request by ricardocousolr**
Hi @liferay-frontend,

This pr tries to fix [LPS-134141](https://issues.liferay.com/browse/LPS-134141) to include the tag `<legend>` inside `<fieldset>` when invoked via the taglib `<aui:fieldset>` when `markupView` is `"lexicon"`. 

This solution is related or complementary to that of [LPS-133314](https://issues.liferay.com/browse/LPS-133314) (cc @georgel-pop-lr). 

Notes:
1. The tag `<legend>` should be an immediate child of `<fieldset>` (see for example, https://html.spec.whatwg.org/multipage/form-elements.html#the-legend-element). This means that `<legend>` cannot be included inside another element such as `<a>`.
2. Since the label of collapsible fieldsets are shown inside an `<a>` element, it's necessary for the `<legend>` to include an `sr-only` label and for the `header` to include `aria-hidden="true"` to avoid redundancy. 
3. When `label` doesn't exist, we show `<legend>` with the portlet title.
4. [LPS-126737](https://issues.liferay.com/browse/LPS-126737) removed a couple of `<div>`'s in `portal-web` but not in `frontend-taglib`. I've chosen to remove those elements as well in `frontend-taglib` but please correct this if it's not ok.
5. Deletion of these `<div>`'s in LPS-126737 deleted two `id`'s that another two `aria-labelledby` where pointing to. I've deleted those `aria-labelledby` since they're not needed any longer.
6. Since we're using the strategy of `<fieldset>` plus `<legend>` instead of `role=group` plus `aria-labelledby`, I've deleted uses of `role=gorup`. (The probably shoud have been removed in [LPS-64310](https://issues.liferay.com/browse/LPS-64310) when `<fieldset>` was used instead o `<div>`.)
7. It's remarked in some places (for example in https://www.w3.org/WAI/tutorials/forms/grouping/) about the element `<legend>` that  
  > Depending on the configuration, some screen readers read out the legend either with every form element, once, or, rarely, not at all.
In my tests with ChromeVox this screen reader won't reader the text in `<legend>` but I think it's best to have a theoretically correct markup rather than trying to accommodate to one particular screen reader. Please let me know if this isn't the right choice. 

Thanks!

### CODE REVIEW

**Comment by ricardocousolr** [comment]
ci:test:sf

**Comment by ricardocousolr** [comment]
ci:test:relevant

**Comment by ricardocousolr** [comment]
Hi @liferay-frontend,
please let me know if there's anything I can do to move this pr forward.
Thanks!

**Comment by julien** [comment]
Hey @nkkwon, could you please tell us if the errors are related to these changes?
I had a quick look but I couldn't figure it out. Thanks!

**Comment by ricardocousolr** [comment]
Thanks @julien, @nkkwon. 

I couldn't determine if the errors were related either. I could only suggest that maybe some changes in the markup (such as adding `<span aria-hidden="true">`) conflicted with some tests.

**Comment by nkkwon** [comment]
Just started reviewing! :)

**Comment by nkkwon** [comment]
**Analysis Details**
@ricardocousolr 
[PortalSmokeUpgrade#ViewPortalSmokeArchive621021](https://testray.liferay.com/reports/production/logs/2021-06/test-1-8/test-portal-acceptance-pullrequest(master)/7563/functional-upgrade-tomcat90-mysql57-jdk8/0/0/jenkins-console.txt.gz) - Looks like this is failing with [LPS-134610](https://issues.liferay.com/browse/LPS-134610) which is a flaky issue occuring in CI.
PR looks good to forward manually!

**Comment by ricardocousolr** [comment]
Thanks @nkkwon!

@julien, please let me know if you have any questions.

**Comment by ricardocousolr** [comment]
Hi @julien,

This is issue is affecting a customer and I'd like to get an OK on the pr to starting preparing a patch for them. When would you estimate you could take a look at it?

Thanks!

**Comment by julien** [comment]
@ricardocousolr let's try to forward this

**Comment by julien** [comment]
ci:forward

**Comment by julien** [comment]
@ricardocousolr I wonder if rebasing with the `master` branch would make the CI tests pass, I think it's worth a try otherwise we'll have to manually forward this one.

**Comment by ricardocousolr** [comment]
ci:reevaluate:1257401_2311

**Comment by julien** [comment]
ci:forward

**Comment by ricardocousolr** [comment]
Hi @julien, 
I don't think the new failure in `LocalFile.ClaySelect#SmokeRegularSelect` is related to this pr. If you agree, could you retry `ci:forward`?

**Comment by julien** [comment]
Sure, let's retry again before asking help from @nkkwon

**Comment by julien** [comment]
ci:forward

**Comment by julien** [comment]
Hey @nkkwon, I know we're already asked for help but looking at the poshi result I saw this error

```js
javascript error: Failed to execute 'elementsFromPoint' on 'Document': The provided double value is non-finite.
``` 

and was wondering if it could be related to these changes.

**Comment by brunofernandezg** [comment]
Hi, adding @zhangyan0701 to the thread, as this issue is affecting to a customer and Nick won't be back until Wednesday
Thanks.

**Comment by zhangyan0701** [comment]
Same result as https://github.com/liferay-frontend/liferay-portal/pull/1212#issuecomment-873888037

Failure is not related.

**Comment by brunofernandezg** [comment]
Thanks!

**Comment by julien** [comment]
ci:forward

**Comment by nhpatt** [comment]
ci:test:relevant

**Comment by nhpatt** [comment]
Sending manually :)

**Comment by nhpatt** [comment]
Sending manually here: https://github.com/brianchandotcom/liferay-portal/pull/104201

**Pull request closed without merging**
