### PR TITLE
LPS-116099 Move product menu title padding to its theme contributor

### PR DESCRIPTION
**Pull request by marcoscv-work**
This PR resolve an align problem in the product menu site title:
image

The Eudaldo's commit dint fix the issue completely, in mobile it still designed in mobile:
image

After applying this PR site icon looks aligned, even when the global menu is not activated:
image

---

**Why I moved the styles to the product menu contributor?**
Currently, the paddings applied are a mix of styles from compatibility layer and bootstrap helpers si I consider this specific style for product me u should be allocated in product menu contributor

---

To test the pr:

Open the product menu and see the correct alignment.

### CODE REVIEW

**Comment by marcoscv-work** [comment]
ci:test:sf

**Comment by marcoscv-work** [comment]
ci:test:stable

**Comment by marcoscv-work** [comment]
ci:test:relevant

**Comment by wincent** [comment]
> ci:test:stable

Pro-Tip™ @marcoscv-work: you don't need to do `ci:test:stable` (those tests are effectively included in `ci:test:relevant`).

**Comment by jbalsas** [comment]
ci:forward

**Pull request closed without merging**
