### PR TITLE
LPS-182790 LPS-184491 FDS Sorting delete and edit

### PR DESCRIPTION
**Pull request by thektan**
**Story:** https://issues.liferay.com/browse/LPS-182790
**Subtask:** https://issues.liferay.com/browse/LPS-184491

### What is the goal of this PR?

- Allows sorting items to be deleted
- Allows sorting items to be edited

### What does it look like?

https://github.com/liferay-frontend/liferay-portal/assets/4496722/429f7a3a-f3e9-42e2-905c-c7717d36317a

### CODE REVIEW

**Comment by thektan** [comment]
ci:test:sf

**Comment by thektan** [comment]
ci:test:relevant

**Review by bryceosterhaus — APPROVED** [review]
LGTM!

**Comment by mateusralv** [comment]
I'm taking a look 🕵🏽

**Comment by mateusralv** [comment]
Testray is down, as soon as I get back I'll do the analysis 🤔

**Comment by thektan** [comment]
Pushed commits to change the modal title naming from "Edit X" to "Edit X Sorting"

**Comment by thektan** [comment]
ci:test:sf

**Comment by thektan** [comment]
ci:test:relevant

**Comment by mateusralv** [comment]
Hi @thektan the failures are not related.
[
Testray comparison](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1684508800786&testrayRunIdA=2301080995&testrayRunIdB=2310200037)

**Comment by thektan** [comment]
Thanks for checking @mateusralv!

**Comment by thektan** [comment]
ci:forward:force

**Pull request closed without merging**
