### PR TITLE
LPS-147835 Assert action buttons are displayed as icon buttons in responsive mode

### PR DESCRIPTION
**Pull request by susanchen3**
**Background**
Create automated tests for management toolbar.

**Test Plan**
Given a user of the portal on responsive mode
When the user opens any section with the management toolbar
Then the actions of the MT will be displayed as icon buttons

**JIRA Ticket:**
https://issues.liferay.com/browse/LPS-147835

### CODE REVIEW

**Comment by susanchen3** [comment]
ci:test:frontend:nocompile

**Comment by susanchen3** [comment]
ci:test:sf

**Comment by john-co** [comment]
Just started reviewing :)

**Review by john-co — APPROVED** [review]
Looks good to me, I tweaked the name of the test to try and follow [SACRED model examples](https://liferay.slack.com/archives/CLD1FFVL6/p1618527187013400?thread_ts=1618516694.010400&cid=CLD1FFVL6)

What do you think @Esther-OC ? Go ahead and forward if you think this looks good too. We may want to also touch up our other testcase names to follow this trend.

**Comment by john-co** [comment]
If we follow this trend, then some other helpful verbs other than "Can" and "Should" http://www.panthercountry.org/userfiles/358/Classes/4914/Prep%20%20HV%20Songs-0.pdf

**Comment by Esther-OC** [comment]
Looks good to me too, so forwarding it.

I will keep in mind the SACRED model examples and suggestions for the verbs for the future test cases, thanks!

**Review by Esther-OC — APPROVED** [review]

**Comment by Esther-OC** [comment]
ci:forward

**Pull request closed without merging**
