### PR TITLE
LPS-132737 Isolate Product Menu, Control Menu, Add Panel CSS

### PR DESCRIPTION
**Pull request by zhangyan0701**
Resent https://github.com/liferay-frontend/liferay-portal/pull/1109 with the test fix.

----

https://issues.liferay.com/browse/LPS-132737

This PR isolates the CSS in Product Menu, Control Menu, Simulation Menu, Add Panel, and Page Audit. I wanted to send them as separate pulls to make it easier to review but these components are too intertwined together, changing one (e.g., Control Menu) breaks all the Menus. This will change how we write our CSS for admin controls (See Isolating Admin Components From CSS Customizations for Site Creators on Confluence). An example below:

```scss
@import 'cadmin-variables';

html#{$cadmin-selector} {
  .cadmin {
    &.my-component-that-doesnt-have-a-parent-element-to-attach-cadmin-to {
      // css properties
    }

    .my-component {
      // css properties
    }
  }

  .my-other-component-that-is-mixed-with-user-facing-content {
    // a good example of this is `page-editor__topper__content` or 
    // `page-editor__disabled-area`
  }
}
```
@liferay-echo This pr causes some alignment and style issues in `page-editor__toolbar` because it's bundled in the `control-menu-container`. These will be fixed when I convert the page editor admin controls in https://issues.liferay.com/browse/LPS-132744. Keep this in mind if you get bug reports regarding this. This is the epic covering all these tasks https://issues.liferay.com/browse/LPS-122068.

The CSS I'm using to test my changes:

```html
<style>
html {
  font-size: 20px;
}

#senna_surface1 h1,
#senna_surface1 h2,
#senna_surface1 h3,
#senna_surface1 h4,
#senna_surface1 h5,
#senna_surface1 h6 {
  background-color: #282828;
  border: 4px solid #00ff66;
  color: #00ff66;
  font-family: Georgia;
  font-size: 50px;
  font-style: italic;
  font-variant: small-caps
  font-weight: bold;
  line-height: 100px;
  letter-spacing: 2px;
  margin: 10px 0;
  padding: 10px;
  text-align: center;
  text-shadow: 1px 1px 0 #fff;
  text-transform: uppercase;
  white-space: nowrap;
}

#senna_surface1 .btn {
  background-color: #282828;
  border: 4px solid #00ff66;
  color: #00ff66;
  font-family: Georgia;
  font-size: 50px;
  font-style: italic;
  font-variant: small-caps
  font-weight: bold;
  line-height: 100px;
  letter-spacing: 2px;
  margin: 10px 0;
  padding: 10px;
  text-align: center;
  text-shadow: 1px 1px 0 #fff;
  text-transform: uppercase;
  white-space: nowrap;
}

#senna_surface1 .btn:hover {
  background-color: #000;
  color: #ffcc00;
  letter-spacing: 4px;
  font-size: 40px;
}

#senna_surface1 a {
  background-color: #282828;
  border: 4px solid #00ff66;
  color: #00ff66;
  font-family: Georgia;
  font-size: 50px;
  font-style: italic;
  font-variant: small-caps
  font-weight: bold;
  line-height: 100px;
  letter-spacing: 2px;
  margin: 10px 0;
  padding: 10px;
  text-align: center;
  text-shadow: 1px 1px 0 #fff;
  text-transform: uppercase;
  white-space: nowrap;
}

#senna_surface1 a:hover {
  background-color: #000;
  color: #ffcc00;
  letter-spacing: 4px;
  font-size: 40px;
}
</style>
```

Product Menu Isolated
product-menu-isolated

Simulation Menu Isolated
simulation-menu-isolated

Add Panel Isolated
add-panel-isolated

Page Audit Isolated
page-audit-isolated

### CODE REVIEW

**Comment by pat270** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
ci:test:relevant

**Comment by nkkwon** [comment]
Looks like the failures are all previous failures that occurred in acceptance too. No unique failures that were caused from commits from this PR

**Comment by pat270** [comment]
Replacing this one with #1235.

**Pull request closed without merging**
