### PR TITLE
LPS-113527 - Deprecate getColumnId() and simplify its usages

### PR DESCRIPTION
**Pull request by kresimir-coko**
As discussed in [this Slack thread](https://liferay.slack.com/archives/C3JBR21HA/p1645606941803519), in this PR I'm deprecating the `getColumnId` method and replacing it's 2 usages with the action it is doing, which is a simple string replacement.

I've tested this by messing around with the drag and dropping modules onto the landing page on DXP making sure that my changes produce the same string as using the method.

### CODE REVIEW

**Comment by kresimir-coko** [comment]
ci:test:relevant

**Comment by kresimir-coko** [comment]
ci:reevaluate:1277401_1917

**Comment by kresimir-coko** [comment]
ci:reevaluate:1277401_1917

**Comment by kresimir-coko** [comment]
ci:test:relevant

**Review by bryceosterhaus — APPROVED** [review]
LGTM!

**Comment by kresimir-coko** [comment]
ci:forward

**Pull request closed without merging**
