### PR TITLE
LPD-32037 - Add accept-language headers to DSM & FDS requests

### PR DESCRIPTION
**Pull request by juanjofgliferay**
## Task
[LPD-32037] / (https://liferay.atlassian.net/browse/LPD-32037)

## Issue
Apply headers after Headless changes in https://liferay.atlassian.net/browse/LPD-19654
We are adding `accept-language` headers to ensure we get the correct localized values. We've already covered in PW tests in [DSM Visualization Modes](https://github.com/liferay-frontend/liferay-portal/blob/master/modules/test/playwright/tests/frontend-data-set-admin-web/tests/data-set-admin/visualizationModes.spec.ts#L889)

### CODE REVIEW

**Comment by juanjofgliferay** [comment]
@markocikos @dsanz To avoid future problems if we forget to add those headers we may add the `Accept-Language` header only to the [@frontend-js-web/fetch utility](https://github.com/liferay-frontend/liferay-portal/blob/master/modules/apps/frontend-js/frontend-js-web/src/main/resources/META-INF/resources/liferay/util/fetch.es.js#L78). This way we ensure that all requests use it. 
Any thoughts?

**Comment by juanjofgliferay** [comment]
ci:test:sf

**Review by markocikos — APPROVED** [review]
@juanjofgliferay LGTM! :sparkles:

**Comment by juanjofgliferay** [comment]
ci:forward

**Pull request closed without merging**
