### PR TITLE
LPS-149682 `--container-max-*` CSS custom properties should apply to …

### PR DESCRIPTION
**Pull request by pat270**
…`.container` / `.container-fluid`

https://issues.liferay.com/browse/LPS-149682

We need to wait for https://github.com/liferay/clay/pull/4757 (next Clay release) to make it in liferay-portal for this PR. The mixins `_assert-ascending` and `_assert-starts-at-zero` were duplicated and the old ones were winning over the new ones in Portal for some reason.

### CODE REVIEW

**Comment by pat270** [comment]
ci:stop

**Comment by matuzalemsteles** [comment]
Hey @pat270 if this is urgent we can cut a Clay release and send it along with this PR.

**Comment by pat270** [comment]
@matuzalemsteles up to you if you have time. Crystal mentioned it was ok to have it by next week. https://issues.liferay.com/browse/LPS-149682

**Comment by matuzalemsteles** [comment]
good, so we can leave it for Monday 😅.

**Comment by pat270** [comment]
Haha sounds good.

**Comment by pat270** [comment]
ci:test:relevant

**Comment by pat270** [comment]
@liferay-frontend can we send this one over? Some GS people are waiting for this I believe.

**Comment by bryceosterhaus** [comment]
@pat270, this looks good to me. Clay release was merged here, https://github.com/liferay-frontend/liferay-portal/pull/2065

**Comment by bryceosterhaus** [comment]
ci:forward

**Comment by pat270** [comment]
Thanks @bryceosterhaus !

**Pull request closed without merging**
