### PR TITLE
LPS-196145 - Remove filter specific feature flag

### PR DESCRIPTION
**Pull request by bryceosterhaus**
https://liferay.atlassian.net/browse/LPS-196145

### CODE REVIEW

**Comment by dsanz** [comment]
LGTM ;)

**Comment by dsanz** [comment]
ci:test:stable

**Review by markocikos — APPROVED** [review]
@bryceosterhaus The code looks good, we only may want to delay forwarding until https://github.com/liferay-frontend/liferay-portal/pull/3667 merged.

**Comment by dsanz** [comment]
yes @bryceosterhaus @markocikos Pablo asked me to wait till we merge all filters/sorting related stuff. I'm adding the "on hold" label to signal this situation

**Comment by bryceosterhaus** [comment]
https://github.com/liferay-frontend/liferay-portal/pull/3667 was merged, so I think we can forward now

**Comment by bryceosterhaus** [comment]
ci:forward

**Comment by bryceosterhaus** [comment]
ci:forward:force

**Comment by dsanz** [comment]
ci:forward:force

**Comment by bryceosterhaus** [comment]
ci:test:sf

**Comment by bryceosterhaus** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/141455

**Pull request closed without merging**
