### PR TITLE
LPS-154540 Import `openSelectionModal` instead of using `Liferay.Util.openSelectionModal`

### PR DESCRIPTION
**Pull request by kresimir-coko**

### CODE REVIEW

**Comment by kresimir-coko** [comment]
ci:test:relevant

**Review by bryceosterhaus — APPROVED** [review]
LGTM!

**Comment by mateusralv** [comment]
ci:test:relevant

**Comment by susanchen3** [comment]
Taking a look now! :detective:

**Comment by susanchen3** [comment]
Reviewed. Test failures are unrelated. :heavy_check_mark: Looks good to manually forward from QA perspective :) 

- [com.liferay.segments.internal.events.test.SegmentsServicePreActionTest](https://testray.liferay.com/home/-/testray/case_results/1894613233?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D1894608917%26testrayRunId%3D1894608957%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc) is failing intermittently with 
```
[beanshell] java.lang.RuntimeException: org.elasticsearch.ElasticsearchStatusException: ElasticsearchStatusException[Elasticsearch exception [type=search_phase_execution_exception, reason=all shards failed]]; nested: ElasticsearchException[Elasticsearch exception [type=illegal_argument_exception, reason=Result window is too large, from + size must be less than or equal to: [10] but was [10000]. See the scroll api for a more efficient way to request large data sets. This limit can be set by changing the [index.max_result_window] index level setting.]]; nested: ElasticsearchException[Elasticsearch exception [type=illegal_argument_exception, reason=Result window is too large, from + size must be less than or equal to: [10] but was [10000]. See the scroll api for a more efficient way to request large data sets. This limit can be set by changing the [index.max_result_window] index level setting.]];
[beanshell] 	at org.elasticsearch.rest.BytesRestResponse.errorFromXContent(BytesRestResponse.java:178) ~[elasticsearch-7.17.1.jar:7.17.1]
```
but I don't think it's related to this PR and the tests pass locally

- [com.liferay.change.tracking.service.test.CTEntryLocalServiceTest](https://testray.liferay.com/home/-/testray/case_results/1894612620?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D1894608917%26testrayRunId%3D1894608957%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc) is also unique to this PR, but it passes locally

**Comment by kresimir-coko** [comment]
Manually forwarded https://github.com/brianchandotcom/liferay-portal/pull/119786

**Pull request closed without merging**
