### PR TITLE
LPS-101658 [Bug] Button "View Data in Analytics Cloud" is not always shown

### PR DESCRIPTION
**Pull request by dgarciasarai**
**Description**
When creating a new AB Test, the button "View Data in Analytics Cloud" doesn't display in the UI. If the user makes another action or refreshes the page the button appeared.

**Solution**
I add the detailsURL to the segmentsExperiment object and take that property into account from the response when creating the new AB Test on the frontend side. That way, the button appeared right after the creation without doing any action on the page. With this button, the user can go to the test details in Analytics Cloud.
Also, this property was added in the props when we load the component for the first time. I change it to not duplicate code.

**How to test it**
- Connect and sync your Liferay DXP with Analytics Cloud
- Click on the AB Test button
- Create a new AB Test

With these steps, you will be able to show the button when creating a new AB Test.

### CODE REVIEW

**Comment by dgarciasarai** [comment]
ci:test:sf

**Comment by dgarciasarai** [comment]
Hey @liferay-frontend, can you give me feedback about the frontend part? The backend part is been reviewed by @darquesdev in this pull request: https://github.com/liferay-tango/liferay-portal/pull/512. I'll apply the feedback and forward the changes from Tango's repo. So here, I only need to get some frontend feedback :)

Thanks! 😄

**Comment by wincent** [comment]
Frontend looks fine to me — disclaimer: I didn't look _super_ closely because I have the eng all hands meeting going into my brain via headphones right now; so if you've tested it and it works and CI is happy 👍

**Comment by dgarciasarai** [comment]
Yeah, sure. I test it in the UI and the frontend tests are passing successfully.

Basically, the frontend part is:
* Renaming from `viewSegmentsExperimentDetailsURL` to `detailsURL` in backend and put that parameter inside the experiment object
* Get that parameter from the creation response (we didn't have it before) and set it in the state of the app via `viewExperimentDetailsURL`
* Fix the PropTypes
* Add a check for the button "View Data in Analytics Cloud" in a jest test
* If there is no experiment in the first render: `viewExperimentDetailsURL: initialSegmentsExperiment?.detailsURL || '',` (state)

Anything else to take into account?

Thanks @wincent ;)

**Comment by wincent** [comment]
> Anything else to take into account?

Nothing that my mind can detect!

dumb-and-dumber

**Comment by dgarciasarai** [comment]
Interesting... Did I pass Greg's source format? 😂
If so, I can close this one and keep reviewing in Tango's repo :)

**Comment by dgarciasarai** [comment]
Continues in https://github.com/liferay-tango/liferay-portal/pull/512. Thanks @wincent for taking a look at this pull request :)

**Pull request closed without merging**
