### PR TITLE
LPD-31398 Fix API Headless filters edition

### PR DESCRIPTION
**Pull request by chestofwonders**
Issue: https://liferay.atlassian.net/browse/LPD-31398

The goal of this PR is to fix API Headless selection filters edition.

**Changes**

- Control state changes about rest application and rest schemas in useEffect hooks, because those changes were only happening on clicking elements, not when a filter was loaded.
- Reset item key, item label and source items when something about the endpoint changes

### CODE REVIEW

**Comment by chestofwonders** [comment]
ci:test:sf

**Comment by juanjofgliferay** [comment]
@chestofwonders The issue with item key / item label seems to be fixed. However, I still can reproduce the issue mentioned in https://liferay.atlassian.net/browse/LPD-31008.
If the issue is unrelated, current fix LGTM

**Comment by herrardo** [comment]
> @chestofwonders The issue with item key / item label seems to be fixed. However, I still can reproduce the issue mentioned in https://liferay.atlassian.net/browse/LPD-31008. If the issue is unrelated, current fix LGTM

I would treat the LPD-31008 in another PR.

**Comment by dsanz** [comment]
Pls see https://github.com/liferay-frontend/liferay-portal/pull/4328

**Pull request closed without merging**
