### PR TITLE
LPS-143101 Update `clay-` packages to 2.23.1

### PR DESCRIPTION
**Pull request by matuzalemsteles**
cc @georgel-pop-lr

---

### Bug Fixes

* **clay-css): Revert "fix(clay-css:** `atlas-variables.scss` and `base-variables.scss` should be Sass partials. The CSS equivalent shouldn't be created since these files are only meant to be consumed by `.scss` files." ([c3e951f](https://github.com/matuzalemsteles/clay/commit/c3e951f))

### Bug Fixes

* **clay-link:** listens for the `handleClick` event and removes the preventDefault call by default ([29be437](https://github.com/liferay/clay/commit/29be437))

### Bug Fixes

* **clay-css:** `atlas-variables.scss` and `base-variables.scss` should be Sass partials. The CSS equivalent shouldn't be created since these files are only meant to be consumed by `.scss` files. ([5d33765](https://github.com/liferay/clay/commit/5d33765))
* **clay-css:** 2.x Input Group move `.btn` and `.form-control` z-index styles to `input-group-prepend` and `input-group-append`. Input Groups input disappears when focused inside a modal with iframe. ([02e5a75](https://github.com/liferay/clay/commit/02e5a75))
* **clay-css:** SF import `components/_reboot.scss` in `packages/clay-css/src/scss/_components.scss` ([2770857](https://github.com/liferay/clay/commit/2770857)), closes [liferay#4124](https://github.com/liferay/issues/4124)
* Add title in a span element, so it can be accessible to screen readers tools ([564bbaf](https://github.com/liferay/clay/commit/564bbaf))
* Regenerate snapshots and updates tests files ([8aa4aac](https://github.com/liferay/clay/commit/8aa4aac))

### Features

* **clay-link:** Trigger an "itemClicked" event and improve a11y ([190e060](https://github.com/liferay/clay/commit/190e060))

### CODE REVIEW

**Review by julien — APPROVED** [review]

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by matuzalemsteles** [comment]
Hey @john-co can you check if these errors are related to this PR?

**Comment by john-co** [comment]
Thanks for reaching out @matuzalemsteles ! @susanchen3 will take a look.

**Comment by susanchen3** [comment]
Taking a look!

**Comment by susanchen3** [comment]
The unique failures look unrelated to your changes. 

First failure looks like flaky communications link failure. Something could've went wrong with app server startup.
The two Poshi errors are common flaky Forms failures. [LRQA-71677](https://issues.liferay.com/browse/LRQA-71677)

So it looks good to me!

**Comment by matuzalemsteles** [comment]
Hey @georgel-pop-lr I'm coming on vacation today, so if you need this to work on your PR, feel free to send it forward when it's ready.

**Comment by pat270** [comment]
There's something missing from this. There was an [accessibility update](https://github.com/liferay/clay/commit/27708570cccb8b9a6ca314214db61fd90458689e) where an import was added to `clay/_components.scss`. The imports in `_styled/css/clay/` need to be updated to match the imports from the same files in unstyled. If they don't get manually updated the changes won't apply due to compatibility layer modification in styled.

**Comment by julien** [comment]
@pat270 are you saying this needs to be done on the clay 2.x branch?

**Comment by pat270** [comment]
@julien This needs to be done in this pr, in the frontend-theme-styled folder.

**Comment by julien** [comment]
:+1: thanks @pat270

**Comment by pat270** [comment]
@julien never mind my review, I failed to realize this is the master branch.

**Comment by julien** [comment]
@pat270 I know it's confusing but both clay 2.x and clay 3.x are used in `master`, some teams never switch to the newer version of the components.

**Comment by julien** [comment]
Ok guys, apparently nothing is missing here

**Comment by julien** [comment]
ci:test:relevant

**Comment by julien** [comment]
Rebased with master and re-submitted here https://github.com/liferay-frontend/liferay-portal/pull/1781

**Pull request closed without merging**
