### PR TITLE
LPS-139450 expose scope key

### PR DESCRIPTION
**Pull request by nhpatt**
Expose ScokeKey for entities that have an scope right now (only asset libraries and sites). I'm exposing the group name to avoid hardcoding ids in enduser apps.

It's messier than I thought because the logic is conditional based on the `ObjectDefinition` and although it's probably cached, I want to avoid querying from cache/DB inside the converter if I can avoid it, as the GraphQL adapter and the REST application already have it as a field.

### CODE REVIEW

**Comment by nhpatt** [comment]
-- rebased and added `LPS-139449 remove c_ObjectDefinitionId` as I also need `ObjectDefinition` and I would have to do the same refactors.

**Comment by nhpatt** [comment]
ci:test:relevant

**Review by javierdearcos — APPROVED** [review]

**Comment by javierdearcos** [comment]
Failing tests don't seem related. Forwarding again

**Comment by javierdearcos** [comment]
ci:test:relevant

**Comment by nhpatt** [comment]
ci:forward

**Comment by nhpatt** [comment]
ci:forward

**Comment by nhpatt** [comment]
-- here we go again :(

**Comment by nhpatt** [comment]
ci:forward

**Pull request closed without merging**
