### PR TITLE
LPS-181454

### PR DESCRIPTION
**Pull request by izaera**
## :warning: No need to review

Followup of https://github.com/izaera/liferay-portal/pull/164

### CODE REVIEW

**Comment by izaera** [comment]
ci:forward

**Comment by bryceosterhaus** [comment]
> No need to review

gonna start using this header on my sketchier PRs

**Comment by izaera** [comment]
The SF failure is bogus -> https://liferay.slack.com/archives/C1SJ64S9X/p1682356479787379?thread_ts=1682344341.321469&cid=C1SJ64S9X

**Comment by izaera** [comment]
I'll fix the semver error too.

**Comment by izaera** [comment]
ci:forward

**Comment by izaera** [comment]
manually sent as https://github.com/brianchandotcom/liferay-portal/pull/133881

**Pull request closed without merging**
