### PR TITLE
LPS-129670 - Update module names to include prefixes

### PR DESCRIPTION
**Pull request by bryceosterhaus**
https://issues.liferay.com/browse/LPS-129670

This helps enforce consistency across modules by making sure they are namespaced.

### CODE REVIEW

**Comment by bryceosterhaus** [comment]
ci:test:sf

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Review by markocikos — APPROVED** [review]
LGTM! Nice initiative! I am not sure why Greg was hesitant to do this :thinking:  might be some complications, indicated in CI errors.

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by diegonvs** [comment]
Does it requires publishing all these modules on npm? Or we can leave it as is since nobody can publish under liferay scope?

**Comment by bryceosterhaus** [comment]
@diegonvs we should be able to leave them, these aren't actually published to npm

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
ci:test:stop

**Comment by bryceosterhaus** [comment]
ci:stop

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by susanchen3** [comment]
Found at least one error that might be related to your changes

`/opt/dev/projects/github/liferay-portal/modules/build-app-module.xml:438: Warning: Could not find file /opt/dev/projects/github/liferay-portal/bundles/deploy/	"name": "@liferay/minium-theme",.war to copy.` 
[full log](https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0/475619//consoleText)

**Comment by susanchen3** [comment]
I'm not sure how to reproduce the error :sweat_smile:, but I found two ST that contain that error if that's helpful in any way
[portal-license-smoke-jdk8/0/0](https://testray.liferay.com/home/-/testray/case_results/1609536221?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D1609530428%26testrayRunId%3D1609532093%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc)
[lpkg-controller-jdk8/0/0](https://testray.liferay.com/home/-/testray/case_results/1609534785?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D1609530428%26testrayRunId%3D1609532093%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc)

**Comment by bryceosterhaus** [comment]
I'll retry without my changes to the minium theme

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
In the most recently result which without the changes to the minium/speedwell themes, the two tests above passed.

If with the changes to the two themes, the error occurs when build LPKG files, I could reproduce the error locally with command:
`ant build-app-lpkg -Dosgi.dir=${osgi.dir} -Dliferay.home=${liferay.home.dir} -Dproject.dir=${project.dir} -Dapp.name=commerce/commerce-theme-minium` (execute under ${project.dir}/modules folder and the target build-app-lpkg is in /modules/build-app.xml).

It supposed to find the minium-theme.war file in ${liferay.home.dir}/deploy and compress it into Liferay Commerce - Liferay Commerce - Impl.lpkg file in /osgi/marketplace folder.

**Pull request closed without merging**
