### PR TITLE
LPS-115075 Update modal usages in asset modules

### PR DESCRIPTION
**Pull request by markocikos**
In this PR, we are updating modals in asset modules. I think this is the first update PR where we don't need to extend `openModal` API :open_mouth: 

Usage Tests:
1. Asset Publisher app > Configuration > Setup > Scope > Select > Other Site or Asset Library...
- modal in modal
---
1. Asset Publisher app > Configuration > Setup > Source > Set Asset Type 'Document'
1. Set Document Type 'Google Drive Shortcut'
1. Flip 'Filter by Field' to 'Yes'
1. Select a field
---
1. Asset Publisher app > Configuration > Setup > Display Settings > Display Template > Choose 'Rich Summary'
1. Check 'Print'
1. Save & close
1. Publish page
1. Asset item > Click on printer icon on the right
- This looks a bit broken in master, in this PR we don't increase brokenness
---
1. Site > Content & Data > Collections > (+) > Add a Dynamic Selection Collection
1. Scope > Select > Other Site or Asset Library...
---
1. Site > Content & Data > Collections > Dynamic Selection item > Edit
1. Source > Set Asset Type 'Document'
1. Set Document Type 'Google Drive Shortcut'
1. Flip 'Filter by Field' to 'Yes'
1. Select a field
---
1. Site > Content & Data > Collection item > Permissions
---
1. Site > People > Segments > (+) > Create a new segment
1. Site > Content & Data > Collections > New Personalized Variation
---
1. Site > Site Builder > Page Templates > (+) > Create a page template
1. Site > Site Builder > Page Templates > Display Page Templates > (+) > Create a display page template
1. Display page template options > Mark As Default 
1. Site > Content & Data > Web Content item > Edit
1. Display Page Template > Default Display Page Template > Eye Icon
---
1. The same as above, except last step Display Page Template > Specific Display Page Template > Eye Icon
- I don't know why this icon does not show, I manually added it, by hacking [this condition](https://github.com/liferay/liferay-portal/blob/288a2a276f51e85ac153d3403267c870aa2cfa42/modules/apps/asset/asset-taglib/src/main/resources/META-INF/resources/select_asset_display_page/page.jsp#L61) to `<c:if test="<%= true %>">`. This may be an unrelated bug in master.
---
1. Modal in asset_add_button/page.jsp is not used anywhere. It is in <liferay-asset:asset-add-button> and its only use has `useDialog="<%= false %>"`
---
1. Modal in asset_view_usages/page.jsp is not used anywhere. It is in <liferay-asset:asset-view-usages>, a deprecated and replaced tag. I still updated it, so it doesn't show up in searches.

### CODE REVIEW

**Comment by markocikos** [comment]
ci:test:sf

**Comment by jbalsas** [comment]
> I think this is the first update PR where we don't need to extend openModal API 😮

believeinyourdreams

**Comment by jbalsas** [comment]
Going to go on a limb here... since it's green and 

> I think this is the first update PR where we don't need to extend openModal API 

Forwarding!

**Comment by jbalsas** [comment]
ci:forward

**Pull request closed without merging**
