### PR TITLE
LPS-167330 Add aria label to the management toolbar's search and view opitons button

### PR DESCRIPTION
**Pull request by pei-jung**
/cc @drewbrokke

### CODE REVIEW

**Comment by bryceosterhaus** [comment]
Looks good to me!

**Comment by ealonso** [comment]
ci:reevaluate:1397401_1869

**Comment by deborasoliveira** [comment]
Hi @pei-jung! I was analyzing your PR and although there's a failure it's not related to it. For further investigation, you can check this [comparison](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=2&testrayRunIdB=2073566970&testrayRunIdA=2075020642&statusB=3). If no other dev review is needed, you can manually forward.

**Comment by pei-jung** [comment]
@patriciajeanperez can you double-check the test failures? Thank you!

**Comment by patriciajeanperez** [comment]
@pei-jung I can confirm the test failure is not related to this PR. Can we manually forward?

**Comment by patriciajeanperez** [comment]
Pushed to BChan
https://github.com/brianchandotcom/liferay-portal/pull/126964

**Comment by patriciajeanperez** [comment]
ci:close

**Pull request closed without merging**
