### PR TITLE
LPD-23358 FDS client extension filter overrides Java API filters

### PR DESCRIPTION
**Pull request by markocikos**
### References

- [LPD-23358 FDS client extension filter overrides Java API filters](https://issues.liferay.com/browse/LPD-23358)
- [Relevant Slack discussion](https://liferay.slack.com/archives/C3JBR21HA/p1713167357316029)

### What is the goal of this PR?

A bugfix, see details in JIRA. We're changing the behavior from override to addition. 

Notably, we are **not** changing the default order of filters, until we settle on desired behavior. A bit of TS cleanup on the side.

### What does it look like?

image

### CODE REVIEW

**Comment by markocikos** [comment]
ci:test:relevant

**Review by juanjofgliferay — APPROVED** [review]
LGTM :rocket:

**Review by dsanz — APPROVED** [review]
LGTM ;)

**Comment by izaera** [comment]
I have nothing to say. FDS is like Chinese for me. I would need to dig into it again to remember everything and be able to provide any feedback :shrug:

**Comment by markocikos** [comment]
ci:report:2561217945

**Comment by markocikos** [comment]
No unique failures, based on https://github.com/liferay-frontend/liferay-portal/pull/4130#issuecomment-2063413249

**Comment by markocikos** [comment]
ci:test:stable

**Pull request closed without merging**
