### PR TITLE
LPS-190313 Adding tests for datasets to edit a view

### PR DESCRIPTION
**Pull request by JerryAdrianoo**
**Description:**
Adding tests for datasets to edit a view.

**Jira Ticket:**
https://liferay.atlassian.net/browse/LPS-193013

### CODE REVIEW

**Comment by JerryAdrianoo** [comment]
ci:stop

**Comment by JerryAdrianoo** [comment]
ci:test:frontend

**Comment by JerryAdrianoo** [comment]
ci:test:sf

**Comment by JerryAdrianoo** [comment]
ci:test:frontend

**Comment by JerryAdrianoo** [comment]
ci:stop

**Comment by JerryAdrianoo** [comment]
@CarlosBrichete I finished it, all the tests are ok, but the CI suits aren't working. :/ I asked for help [here](https://liferay.slack.com/archives/CL3TWSMHQ/p1698230589385389).

**Comment by pyoo47** [comment]
ci:test:sf

**Comment by pyoo47** [comment]
ci:test:sf

**Comment by pyoo47** [comment]
ci:test:frontend

**Comment by JerryAdrianoo** [comment]
ci:test:frontend

**Comment by JerryAdrianoo** [comment]
ci:test:frontend-data-set

**Comment by JerryAdrianoo** [comment]
ci:help

**Comment by JerryAdrianoo** [comment]
ci:test:frontendthese failures are not related :)

**Comment by JerryAdrianoo** [comment]
ci:test:frontend

**Comment by JerryAdrianoo** [comment]
ci:help

**Comment by JerryAdrianoo** [comment]
@CarlosBrichete failures unrelated 😃

**Review by CarlosBrichete — APPROVED** [review]

**Comment by CarlosBrichete** [comment]
LGTM

**Comment by JerryAdrianoo** [comment]
ci:forward

**Pull request closed without merging**
