### PR TITLE
LPS-118651 Adds custom request param to identify routed requests

### PR DESCRIPTION
**Pull request by jbalsas**
This is a possible fix for [Hello Soy Portlet uncaught type errors](https://issues.liferay.com/browse/LPS-118651)

Even if the report is specific to the Hello Soy Portlet which is not present in `master`, the truth is that this is caused in the underlying infrastructure which it still is.

**The Problem:**
This was likely caused by the solution applied to [Serving a MVCResourceCommand in a SoyPortlet triggers unnecessary rendering](https://issues.liferay.com/browse/LPS-91062) which makes any requests without `p_p_lifecycle` in their URL fail to be properly routed and return an empty `serveResource` body instead.

**The fix:**
Add an additional parameter `soy_route` (be my guest and find a better name for it) so there's no overlap with other features. If the param is there, it's a routed request, if not, it isn't (or so I hope). 

**Test plan:**
I tested this on `7.2.x` (haven't tested in `master`, so I might've messed up in translation)

#### LPS-118651
- Add the Hello Soy Portlet to a page

Assert that navigation and submission works in the portlet

#### LPS-91062
- Go to Content -> Documents and Media.
- Create a Basic Document.
- Click on the document's action menu and click Share.
- Type something in the autocomplete.

Assert that no errors are being thrown in the console (I previously checked that making `isRoutedRequest` always return `true` makes this reproducible.

### CODE REVIEW

**Comment by jbalsas** [comment]
@brunobasto, this is just for you!! 🤗 

/cc @antonio-ortega, @NemethNorbert

**Comment by jbalsas** [comment]
ci:test:sf

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by brunobasto** [comment]
LGTM

**Comment by brunobasto** [comment]
ci:forward

**Pull request closed without merging**
