### PR TITLE
LPS-198051 Moving styles to BaseEditor so they apply to every editor

### PR DESCRIPTION
**Pull request by antonio-ortega**
Hey guys,

These kind of styles used to apply to every editor, not only to BalloonEditor, although we messed it up when taking them away from Styled Theme. As an example you can see [LPS-139143](https://liferay.atlassian.net/browse/LPS-139143).

In case you want to know more, you can see [LPS-198051](https://liferay.atlassian.net/browse/LPS-198051) and [this Slack thread](https://liferay.slack.com/archives/C3JBR21HA/p1696343137651109).

Thanks.

Regards.

### CODE REVIEW

**Comment by antonio-ortega** [comment]
ci:test:relevant

**Review by markocikos — APPROVED** [review]
@antonio-ortega LGTM! :sparkles:

**Comment by markocikos** [comment]
ci:test:relevant

**Comment by antonio-ortega** [comment]
ci:forward

**Pull request closed without merging**
