### PR TITLE
LPS-184908 Title field appears in wrong format when related

### PR DESCRIPTION
**Pull request by murilostodolni**
Motivation
=======
Format the date when the user select the relationship.

Proposed Solution
========
Use the `DateTimeRenderer` function in [ObjectRelationship.tsx](https://github.com/liferay-objects/liferay-portal/pull/2192/commits/16f31631d670e973d1d2a8ed545a847af2de1666#diff-a4f1228058343fbc8a2f8fb014097d3a936e9617e6c8d7f1e96c06beb986cce5) to format the date. For this, we need to export the `DateFormatRenderer` in FDS in this [commit](https://github.com/liferay-objects/liferay-portal/pull/2192/commits/8400b698d343dd139cf3ff2eb0785494cf0655b5).

Commit to review
========
The [PR](https://github.com/liferay-objects/liferay-portal/pull/2192) has been approved for the object changes. Could you review just this [commit](https://github.com/liferay-objects/liferay-portal/pull/2192/commits/8400b698d343dd139cf3ff2eb0785494cf0655b5), please?

Screenshots
========
Before:
screenshot-1686158133

After:
screenshot-1686160512

**Jira Ticket:** https://issues.liferay.com/browse/LPS-184908

### CODE REVIEW

**Comment by murilostodolni** [comment]
ci:test:sf

**Comment by murilostodolni** [comment]
ci:test:sf

**Comment by murilostodolni** [comment]
The sf error has been because a rebase with FDS repository. I rebase with liferay master without changes in commits.

**Comment by murilostodolni** [comment]
ci:test:relevant

**Review by bryceosterhaus — APPROVED** [review]
LGTM! Just need green CI or QA sign off

**Comment by murilostodolni** [comment]
ci:test:relevant

**Comment by murilostodolni** [comment]
ci:forward:force

**Comment by murilostodolni** [comment]
ci:forward

**Comment by murilostodolni** [comment]
ci:forward

**Comment by murilostodolni** [comment]
ci:forward

**Comment by murilostodolni** [comment]
ci:forward

**Comment by murilostodolni** [comment]
Forward manually: https://github.com/brianchandotcom/liferay-portal/pull/136048

**Comment by bryceosterhaus** [comment]
Hey @murilostodolni how do we know that the errors are not related? Did you get someone from QA to help sign off on that?

Typically our workflow for forwarding PRs is either "green CI" or get QA approval that the failures are unrelated and manually forward. Often QA has a bit more insight to know if things are related or not.

**Pull request closed without merging**
