### PR TITLE
LPS-197697 Make FDS Filter Client Extensions FF to use data set manager FF

### PR DESCRIPTION
**Pull request by dsanz**
Reference: https://liferay.atlassian.net/browse/LPS-197697

In this PR we just use the Data Set Manager FF to control FDS Filter client extensions, in the same way we already did with FDS Cell Renderer client extension. This is because it makes no sense to use different ones, the Data Set Manager is the app making use of available FDS Filter client extension entries to configure valid FDS instances in the fragment. 

This functionalty, though available programmatically, makes no sense out of the context of Data Set Manager and therefore, we tie both features together under the same FF

### CODE REVIEW

**Comment by dsanz** [comment]
ci:sf

**Review by markocikos — APPROVED** [review]
@dsanz LGTM! :sparkles:

**Comment by dsanz** [comment]
ci:test:stable

**Comment by dsanz** [comment]
ci:forward

**Comment by dsanz** [comment]
ci:forward:force

**Pull request closed without merging**
