### PR TITLE
LPS-124112 Add external reference code to KBArticle and KBFolder

### PR DESCRIPTION
**Pull request by LuismiBarcos**
This pull is the first part of the feature described in [this ticket](https://issues.liferay.com/browse/LPS-124112)
The external reference code (also called ERC) is a unique id to identify a specific resource. It could be scoped by group or by company.

In the PR, it added support for external reference code in KBArticle and KBFolder services to be able to add KBArticles and KBFolders with a specific external reference code. In case that the user does not provide the ERC, it will be assigned by default the id of the resource.

We see that exists a problem with the external reference code when a resource support versioning. In this case, the resource is KBArticle. Every time that we create a new version of a KBArticle a new file is created in the DB with a new kbArticleId. Because the ERC is a representation of a resource scoped by group, the ERC should be the same for all versions of a resource.

To avoid the problem described above, we've created the ERC for KBArticle in the DB manually and add the filters to search the resource by groupId and ERC and by groupId, ERC, and version.

### CODE REVIEW

**Comment by LuismiBarcos** [comment]
FYI @nhpatt

**Comment by LuismiBarcos** [comment]
ci:forward

**Comment by nhpatt** [comment]
Any reasons for opening a new PR?

**Comment by LuismiBarcos** [comment]
Yeah, to apply the changes requested [here](https://github.com/brianchandotcom/liferay-portal/pull/102089#issuecomment-847253129)

**Comment by nhpatt** [comment]
> Yeah, to apply the changes requested [here](https://github.com/brianchandotcom/liferay-portal/pull/102089#issuecomment-847253129)

But you can apply them in the same PR and we do not lose all the comments/context. Rebases are fine.

**Comment by LuismiBarcos** [comment]
Even when the previous PR was sent by the CI and closed? Should I reopened it and work in that PR? Sorry, I can make it if it is a better practice.

**Comment by nhpatt** [comment]
Oh, ignore my comment, I thought you closed it 😓

**Pull request closed without merging**
