### PR TITLE
LPS-141475 Migrate Data Set Display frontend to a dedicated module

### PR DESCRIPTION
**Pull request by markocikos**
JIRA: https://issues.liferay.com/browse/LPS-141475

This is a followup on https://github.com/liferay-frontend/liferay-portal/pull/1609. Changes In this PR:
- Module is now `frontend-data-set/frontend-data-set-web`. Other app modules will be in `frontend-data-set/*`.
- Frontend component is now `DataSet`. I considered `FrontendDataSet`, but it looks wrong to me.
- To be consistent, I removed all instances of `*display` suffix in frontend (in React components, directories and CSS classes).

We will update backend classes in a future PR, replacing `ClayDataSetDisplay*` with `FrontendDataSet*` in Java classes.
We will update tags in a future PR, replacing `<clay:*data-set-display>` with something like `<data-set:classic/headless>` or `<liferay-frontend-data-set:classic/headless>` (TBD).

/cc @carloslancha @nhpatt @javierdearcos @izaera @dsanz @tinycarol

### CODE REVIEW

**Comment by markocikos** [comment]
Since the only changes from #1609 are renaming, I think there is no need for more reviews, we can forward if CI is green. I did want to run through CI, to catch some silly mistakes I might have done in renaming.

**Comment by markocikos** [comment]
Force-pushed. Changes:
- reverted wrapper css class change, as it is used in CI tests
- fixed samver conflict

**Comment by markocikos** [comment]
ci:forward

**Comment by markocikos** [comment]
ci:reevaluate:1287401_883

**Comment by markocikos** [comment]
ci:forward

**Comment by john-co** [comment]
Just started reviewing :)

**Comment by markocikos** [comment]
ci:stop

**Comment by john-co** [comment]
john-co:stop-reviewing

**Comment by markocikos** [comment]
Force-pushed CI fixes.

**Comment by john-co** [comment]
ci:forward

**Pull request closed without merging**
