### PR TITLE
LPS-171405 | Fix for Client extension test cases

### PR DESCRIPTION
**Pull request by mateusralv**
Description: 
fix for testing on client extensions 

JIRA LINK:
https://issues.liferay.com/browse/LPS-171405

### CODE REVIEW

**Comment by mateusralv** [comment]
ci:test:sf

**Comment by mateusralv** [comment]
ci:test:client-extensions

**Comment by mateusralv** [comment]
ci:test:frontend-client-extensions

**Comment by mateusralv** [comment]
The fix works in CI 🎉, Hi @john-co could take a look?

**Review by john-co — APPROVED** [review]
Looks good to me! :sunglasses:

**Comment by john-co** [comment]
ci:forward

**Pull request closed without merging**
