### PR TITLE
LPS-139149 Move headless admin batch planner modules to batch-planner

### PR DESCRIPTION
**Pull request by javierdearcos**
The build in the CI has been broken these days because the Headless Admin Batch Planner modules need the Batch Planner modules that are excluded from the release.

Moving the modules to the same root I'm trying to find out if with this fix we can create a successful build in the CI, run the tests and keep the modules excluded from the release

### CODE REVIEW

**Comment by javierdearcos** [comment]
ci:test:relevant

**Comment by nhpatt** [comment]
ci:forward

**Comment by nhpatt** [comment]
Move completely

**Comment by javierdearcos** [comment]
Thank you! Yesterday I've make a first test leaving the old name on purpose and going step by step until I talk to the team, but I also leave a lot of other things missing...

I'll talk to the Batch Planner and if the agree with the change, I continue forwarding it

**Comment by javierdearcos** [comment]
Talked with the team and they agree with the changes. Forwarding it

**Comment by javierdearcos** [comment]
ci:forward

**Comment by javierdearcos** [comment]
ci:forward

**Comment by javierdearcos** [comment]
ci:test:relevant

**Comment by nhpatt** [comment]
ci:test:relevant

**Comment by nhpatt** [comment]
ci:forward

**Pull request closed without merging**
