### PR TITLE
COMMERCE-4013 accept-language headers aligned with liferay standards

### PR DESCRIPTION
**Pull request by FabioDiegoMastrorilli**
Purpose of this PR is replacing all the occurrences of `getAcceptLanguageHeaderParam` with `Liferay.ThemeDisplay.getBCP47LanguageId` which is widely used in portal.

The fetched data will then result correctly localised.

---
This is is a copy of [this PR](https://github.com/liferay-commerce/liferay-portal/pull/619)

### CODE REVIEW

**Comment by wincent** [comment]
Those test failures look unrelated to me, so I am going to try forwarding — if that doesn't work, would you mind rebasing @FabioDiegoMastrorilli to see if that fixes them?

**Comment by wincent** [comment]
ci:forward

**Comment by FabioDiegoMastrorilli** [comment]
@wincent I just push forced after rebasing

**Comment by FabioDiegoMastrorilli** [comment]
ci:forward

**Comment by wincent** [comment]
```
      [exec] Execution failed for task ':apps:commerce:commerce-frontend-js:packageRunTest'.
```

Looks legit this time, @FabioDiegoMastrorilli.

**Comment by FabioDiegoMastrorilli** [comment]
ci:test:sf

**Comment by FabioDiegoMastrorilli** [comment]
ci:test:stable

**Comment by wincent** [comment]
ci:test:relevant

**Comment by wincent** [comment]
ci:forward

**Pull request closed without merging**
