### PR TITLE
LPS-133798 add custom URL provider for questions that overrides frien…

### PR DESCRIPTION
**Pull request by nhpatt**
…dly URL configuration and returns the full URL in the canonical URL. Without it we are returning 2 different canonical URLs, one rendered by questions with Helmet that is correct and another by the layout SEO logic that uses the friendly URL and does not return the full URL.

I guess that this is the result of returning just "localhost/ask" in the friendly URL, nevermind if the URL really is "localhost/ask/questions/lkjadsfjkkasd". We need to return the root to let the history router work but then we break the canonical URL (it was already broken nevertheless).

Ideally these cases should be supported directly.

### CODE REVIEW

**Comment by javierdearcos** [comment]
Reviewed 👍 

Do we have already Questions registered as the high-ranked Asset Renderer for MessageBoards?

**Comment by nhpatt** [comment]
ci:forward

**Comment by nhpatt** [comment]
> Do we have already Questions registered as the high-ranked Asset Renderer for MessageBoards?

Yes. Also doing ugly things, I had to change depot code to be able to do it: https://github.com/liferay-frontend/liferay-portal/pull/1135

**Comment by nhpatt** [comment]
ci:forward

**Comment by nhpatt** [comment]
ci:forward

**Comment by nhpatt** [comment]
ci:forward

**Comment by nhpatt** [comment]
ci:forward

**Pull request closed without merging**
