### PR TITLE
[7.4+][PART 1] LPS-134071 Migrate frontend-theme-styled CSS

### PR DESCRIPTION
**Pull request by edalgrin**
This PR removes all the unused and third-party CSS from `frontend-theme-styled`
- [Original PR](https://github.com/liferay-frontend/liferay-portal/pull/1877#issuecomment-1064926374)
- [Strategy](https://liferay.atlassian.net/wiki/spaces/ENGFRONTENDINFRA/pages/1341882669/LPS-127086+-+Analyze+and+prototype+possible+theme+optimizations?focusedCommentId=1969652346#comment-1969652346)
- [Changelog](https://docs.google.com/spreadsheets/d/1IG7o3hAn9w91-sg_vXQZeWhJsRBSSMTrGUi-EVfQ6H8/edit#gid=0)
- [Module testing](https://docs.google.com/spreadsheets/d/1IG7o3hAn9w91-sg_vXQZeWhJsRBSSMTrGUi-EVfQ6H8/edit#gid=1130153366)

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@edalgrin merged manually

**Comment by diegonvs** [comment]
ci:test:relevant

**Comment by edalgrin** [comment]
ci:test:relevant

**Comment by Esther-OC** [comment]
After reviewing this las build and Testray results, and making a [comparison](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=3&testrayRunIdB=1638962400&testrayRunIdA=1642309261&statusB=2) between it and upstream, there are no unique failures related to the PR, so it seems that it can be forwarded manually.

**Comment by Esther-OC** [comment]
Hi, 
After reviewing the PR and made the [comparison](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=3&testrayRunIdB=1638962400&testrayRunIdA=1642309261&statusB=2) with upstream, we have seen that there is one unique failure.

We have launch a ci:test:frontend to run the frontend tests, if the issue ([js-unit-jdk8/0/0](https://testray.liferay.com/home/-/testray/case_results/1642309938)) is still present it seems that it is probably related to the PR, as in other PRs is not failing.

So let's wait!

**Comment by john-co** [comment]
ci:test:frontend:norebase

**Comment by john-co** [comment]
Hi @edalgrin, can you try rebasing and rerunning the tests locally? I believe there are 3 js unit test issues after rebasing to master.

**Comment by edalgrin** [comment]
Hey @john-co I already tried to rebase it but, because we merged it before and then reverted, Github doesn't add those changes to the list. So I'm going to take a second look and try to "un-revert" the changes.

**Comment by edalgrin** [comment]
Resend here https://github.com/liferay-frontend/liferay-portal/pull/2030

**Pull request closed without merging**
