### PR TITLE
LPS-116105 Fix style of view-all in global-app-menu

### PR DESCRIPTION
**Pull request by eduardoallegrini**
The request was to align the `view all` button to the left of the sites column

image

I took into consideration the following solutions:
- Add the class `.btn-unstyled` to the button
  - the btn-unstyled reset the font-size and we wanted to preserve it small
- Add a `negative-margin-left` to the button
  - not the best practice because out of context it could overlap other components
- Remove the `padding-left` from the button
  - I prefer this option and used the Clay utility class `.c-pl-0` that does exactly what we needed without causing the `!important` attribute problem.

**Result:**

image

### CODE REVIEW

**Comment by jbalsas** [comment]
LGMT!

**Comment by jbalsas** [comment]
ci:test:sf

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by eduardoallegrini** [comment]
This fix doesn't work on the Classic-Theme because the specificity of the CSS Custom Properties

image

But the solution is not part of the Global-App-Menu so I've opened a thread in Slack to discuss about it https://liferay.slack.com/archives/G3JBR21HA/p1594126880002700

**Comment by jbalsas** [comment]
So what do you expect us to do with this PR? It's not clear if you want it forwarded or not :)

**Comment by eduardoallegrini** [comment]
Yes we must forward this, my concern is about the opened ticket we cannot close it until we fix the CCP

**Comment by eduardoallegrini** [comment]
ci:forward

**Pull request closed without merging**
