### PR TITLE
LPS-126135 - Adding brand colors

### PR DESCRIPTION
**Pull request by marcoscv-work**
Some teams like LOL or liferay.com team need to create brand fragments/content based on branding colors, not in components colors, that's the main reason to add the new colors category "Brand Colors"

About naming: `brand-color-1` `2` `3` `4`
### **Why do we use numbers instead of labeling like "primary" "secondary", etc?**

Branding colors can be pallets with colors with the same importance, so primary, secondary, tertiary.. wouldn't be correct to naming those variables, we finally add 4 number variables to provide flexibility and adaptability.

---

### How to test this PR?

- Go to product menu > style > stylebook > Create a new one
- Go to Color system
- Change the Brand color 4 and see changes in the footer

image

image

### CODE REVIEW

**Comment by marcoscv-work** [comment]
ci:test:sf

**Comment by marcoscv-work** [comment]
ci:test:sf

**Comment by marcoscv-work** [comment]
ci:stop

**Comment by marcoscv-work** [comment]
ci:test:relevant

**Review by nhpatt — COMMENTED** [review]
Does this make sense for all users of Liferay? @drakonux @ealonso

**Review by edalgrin — COMMENTED** [review]
The code seems fine, specially the first commit where we remove unused variables but I'm not sure that we need to add those custom properties "globally", do we have a LOL CSS file? and do the token-definition can be defined outside the theme-classic?

**Comment by marcoscv-work** [comment]
The classic theme should be enough to customize a basic site in Liferay, As I tried to explain right now there is no difference between theme colors (mainly components colors) and branding colors, it is confusing to use and very limited.

The first set of variables was an agreement between echo and FI, Juan Anton ( @atjuan ) and myself and now by chance of fate Juan and myself are working together in Liferay OnLine trying to create a set of simple starter kits (examples sites with simple content to get started with Liferay).
We really think we need those 4 variables to create consistent and simple-to-understand sites and probably we will need more in the future.
On the other hand, we have other teams and customers feedback (not in an "official" way). asking about this point.

Another point to have in a count is that Dialect makes this difference between color categories, and yes.. even if classic does not need to fit  Dialect 100% it is something really simple we can learn about their work.

I think we have plenty of reasons to go ahead and don't stop this simple color category contribution.

**Comment by drakonux** [comment]
I haven't any reason to say no to this proposal even more if it fits with real cases of our customers. However, although this is mainly a DXP decision, it would be interesting what @hold-shift has to say because, he is currently involved on the new design token definition for Clay.

**Comment by marcoscv-work** [comment]
Here an screenshot from Dialect:

image


As you can see there is a clear difference between Brand, Neutral (called grays in our tokens). and Accent/Actions

I insist we are no trying to offer all that Dialect is proposing, probably they will always need their own tokens, but the idea from a design point of view is useful and consistent, and in LOL we wanted to follow something similar, even before of know about Dialect existence.

**Review by nhpatt — APPROVED** [review]

**Comment by edalgrin** [comment]
Just started reviewing :)

**Comment by edalgrin** [comment]
Had to change a couple of things and took advantage to refactor the commits 😬 https://github.com/liferay-frontend/liferay-portal/pull/1290

**Comment by drakonux** [comment]
> Does this make sense for all users of Liferay? @drakonux @ealonso

Certainly, Idk 🤷‍♂️, at least I would say a "Brand color" is something more familiar for marketing people and besides, Juan Antón was working for a while with team-echo and he agrees with this improvement... so, let's go with it.

**Comment by nhpatt** [comment]
@drakonux we can't because it was already merged 20 hours ago: https://github.com/brianchandotcom/liferay-portal/pull/104870 :P

**Pull request closed without merging**
