### PR TITLE
LPD-15209 - Update modules to ESM

### PR DESCRIPTION
**Pull request by bryceosterhaus**

### CODE REVIEW

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
ci:report:2533437491

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
ci:report:2534092519

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Review by p2kmgcl — APPROVED** [review]
Hi @bryceosterhaus! I've basically tried to go module by module to verify that everything is working... and it looks perfect :smile:

**Comment by bryceosterhaus** [comment]
Thanks @p2kmgcl! It's so far been a bit of a shotgun approach with migrating  modules, and can be hard to track failures across modules as CI doesn't always pick up the runtime issues. Thanks for the help

**Comment by bryceosterhaus** [comment]
ci:report:2534715102

**Comment by bryceosterhaus** [comment]
ci:report:2534715102

**Comment by bryceosterhaus** [comment]
ci:test:sf

**Comment by bryceosterhaus** [comment]
ci:forward:force

**Comment by bryceosterhaus** [comment]
manual forward https://github.com/brianchandotcom/liferay-portal/pull/146962

**Pull request closed without merging**
