### PR TITLE
LPS-201102 Do not flush the Hibernate session if we do not change companyId context since that causes to increase the mvccVersion in the middle of the process and StaleObjectException is thrown

### PR DESCRIPTION
**Pull request by achaparro**
Hi,

When DB Partitioning is enabled, we flush the Hibernate session when we change the company context so we make Hibernate aware of the correct partition for the previous modifications.

In this case with Client Extensions, the flush is executed even when there are no change of company and the _mvccVersion_ is increased (due to the flush) in the middle of the process, when we have already got the entity from the cache. Due to we have an old version of the entity, we got and StaleObjectException later on.

This fix solves the issue  in my environment. I have kept Daniel's changes since they are beneficial and does not harm.

Let me know if you need anything else.

cc/ @dsanz @CarlosBrichete

### CODE REVIEW

**Comment by CarlosBrichete** [comment]
@mateusralv

**Comment by achaparro** [comment]
I have modified the commit, thanks @dsanz !

**Comment by achaparro** [comment]
ci:test:sf

**Comment by dsanz** [comment]
ci:test:relevant

**Comment by dsanz** [comment]
See https://github.com/liferay-frontend/liferay-portal/pull/3812

**Pull request closed without merging**
