### PR TITLE
Disable svg4everybody unless its IE or cross-origin

### PR DESCRIPTION
**Pull request by bryceosterhaus**
I am working on https://issues.liferay.com/browse/LPS-115810 and I am hitting a wall with how to load `svg4everybody` dynamically in the JS. I tested this code out by copying and pasting the svy4everybody file directly in here, but ideally I would be able to grab it from the node_modules.

Here is how this works...

1. If the browser is IE, we use svg4everybody and don't worry about custom logic.
2. If the browser is not IE, we use similar logic as svg4everybody and iterate through all `<use>` tags and replace `data-href` with `href`.
    - If the href is cross origin, we skip our custom logic and opt for svg4everybody.

Any thoughts on how to conditionally load svg4everybody in this file? The `require()` statements do not work. I am also open to other suggestions on how to go about this.

### CODE REVIEW

**Comment by jbalsas** [comment]
> Any thoughts on how to conditionally load svg4everybody in this file? The require() statements do not work. I am also open to other suggestions on how to go about this.

This is probably much easier from the Java side, similar to how we load our IE polyfills, jquery or other priority scripts using a `TopHeadDynamicInclude`. In there, you should be able to test if we're in IE and also if the conditions for CDN are met (cdn properties not null).

> If the browser is not IE, we use similar logic as svg4everybody and iterate through all <use> tags and replace data-href with href

This is something that should be reverted. We should get rid of all svgs that render a `data-href` and render an `href`. That should be the default and it should not be penalized by IE support. 

In case we wanted, we could generate dual markup so that in IE or in CDN-enabled scenarios we do switch back to rendering `data-href`, but I wouldn't worry for now.

This is to say, I don't think we should be making js changes on markup, but rather producing the proper markup upfront.

**Comment by bryceosterhaus** [comment]
@jbalsas I was thinking this would have to be done client side since we have to check all svgs for cross-origin content. Can we do that check in a single place?

**Comment by jbalsas** [comment]
> @jbalsas I was thinking this would have to be done client side since we have to check all svgs for cross-origin content. Can we do that check in a single place?

Well... we are mostly the ones in control of the generation, so we should know if they're going to be cross-origin or not. At least for the most part, if the `cdn.something.something` property is set, then the spritemap for the icons would be cross-origin... at least that was my reasoning, but I might be off-target here. I'll take a closer look tomorrow morning 😂

**Comment by bryceosterhaus** [comment]
@jbalsas ah that makes sense, I was thinking if someone added one via webcontent so maybe I was thinking a little _too_ dynamic. I just saw the jquery and fontawesome modules, ill copy that pattern and see how it goes. Thanks for the advice!

**Comment by jbalsas** [comment]
> @jbalsas ah that makes sense, I was thinking if someone added one via webcontent so maybe I was thinking a little too dynamic.

Yeah, I think that's a valid concern, though, but might also be a bit more nuanced than that. We certainly don't want to force svg4everybody if people write bad contents... so we have to see which tools we have to enforce better patterns and when we don't... we might have to do the dynamic dance ;)

**Pull request closed without merging**
