### PR TITLE
LPS-143550 | A11yTool - Add task blocks to pre-existing tests

### PR DESCRIPTION
**Pull request by susanchen3**
**Background**
Create automated tests for the A11y tool

**Test Plan**
Refactor tests by adding task blocks 

**JIRA Ticket:**
https://issues.liferay.com/browse/LPS-143550

### CODE REVIEW

**Comment by susanchen3** [comment]
ci:test:frontend:nocompile

**Review by john-co — APPROVED** [review]
Looks good!

**Comment by john-co** [comment]
ci:forward

**Comment by john-co** [comment]
Reviewed. Test failures are unrelated. :heavy_check_mark: 
https://github.com/liferay-frontend/liferay-portal/pull/1733#issuecomment-989125120

**Pull request closed without merging**
