### PR TITLE
LPS-118726 - Fixes AppBuilder [object Object] Toast Messages

### PR DESCRIPTION
**Pull request by jbalsas**
The changes from [LPS-117760 Improve openToast handling of html content](https://github.com/liferay-frontend/liferay-portal/pull/208) have caused [Success Message is wrong when deploying an app, the message "Success:[object Object]" is shown](https://issues.liferay.com/browse/LPS-118726).

**The problem:**
In this case, `app-builder-web` was passing a `React.element` as the `message` param. Now that we're explicitly assuming we get an html string, we render the string representation of an object, ie: `[object Object]`.

**The options:**
- Make it possible to allow react elements as `message` as part of the `openToast` API
- Create a wrapper around the usage in `app-builder` or directly use `<ClayAlert>`
- Generate the HTML by hand inside `app-buidler-web`

**The solution:**

- This seems to be the **only** case in all DXP where we were doing this
- The use case is **pretty trivial**. We either render
    - Nothing
    - A string
    - A link with an icon
- We **don't want to expand the API surface** right away

Based on the above, I think we can simply "dumb down" the code in `app-builder-web` to generate the proper string and see if this need becomes more clear in the future.

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:test:sf

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
ci:test:sf

**Comment by jbalsas** [comment]
Hey @albinojunior, I've pushed one additional commit with a similar fix for `app-builder-workflow`. I haven't tested this though, so please, make sure I didn't mess up.

@diegonvs, @matuzalemsteles, @brunobasto, can any of you please take it from here?

I'm officially on vacation now!!

vacation

**Comment by matuzalemsteles** [comment]
ci:test:sf

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by matuzalemsteles** [comment]
🤔

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by brunobasto** [comment]
@matuzalemsteles It seems app builder unit tests are failing

**Comment by wincent** [comment]
> * We **don't want to expand the API surface** right away

original-slow-clap

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by matuzalemsteles** [comment]
ci:test:sf

**Comment by matuzalemsteles** [comment]
I think this is ready to go ahead, @brunobasto anything else you noticed?

**Comment by brunobasto** [comment]
> I think this is ready to go ahead, @brunobasto anything else you noticed?

Nope. LG2M

**Comment by matuzalemsteles** [comment]
ci:forward

**Pull request closed without merging**
