### PR TITLE
LPS-136999 Support friendly URL mappings in remote apps

### PR DESCRIPTION
**Pull request by izaera**
This adds a new `friendlyURLMapping` field in `RemoteAppEntry` so that we can use friendly URLs for frontend routing.

Each `RemoteAppEntry` which is non-instanceable and has `friendlyURLMapping` informed will instantiate a `FriendlyURLMapper` that lets any path be used to retrieve the portlet.

So, for instance, imagine our beloved `vanilla-counter`, where we configure its friendly URL mapping:

imagen

That lets you request URLs like `http://localhost:8080/web/guest/4/-/periquito/my/path/used/to/route/through/javascript`:

imagen

### CODE REVIEW

**Comment by zhangyan0701** [comment]
Seems like there is a failed test related:
[LocalFile.RemoteApps#CanBeDeleted](https://testray.liferay.com/home/-/testray/case_results/1573825392)

Error thrown when add remote app with json ws:
```
     [exec]     Executing commands: curl -X POST -u 'test@liferay.com:test' -d 'iFrameURL=http%3A//www.liferay.com/my_new_remote_app' -d 'instanceable=true' -d 'nameMap='{\"en_US\":\"My%20New%20Remote%20App%20To%20Delete\"}'' -d 'portletCategoryName=RemoteApps' -d 'properties=' http://test-1-27-30.lax.liferay.com:8080/api/jsonws/remoteapp.remoteappentry/add-i-frame-remote-app-entry
     [exec] 2021-10-29 08:45:45.771 ERROR [http-nio-8080-exec-3][JSONWebServiceServiceAction:126] No JSON web service action with path /remoteapp.remoteappentry/add-i-frame-remote-app-entry and method POST for remoteapp
```

**Comment by magjed4289** [comment]
Just started reviewing :)

**Comment by magjed4289** [comment]
Just started reviewing :)

**Comment by magjed4289** [comment]
ci:test

**Comment by magjed4289** [comment]
ci:test:relevant

**Comment by magjed4289** [comment]
ci:stop

**Comment by magjed4289** [comment]
Reviewed. Test failures are unrelated. ✔️
Ok to manually forward.

[Unrelated]

1. - **LocalFile.InstanceSettings#ExportedFactoryConfigurationCanBeImported** - failure not related to the PR
2. - **LocalFile.PGStaging#ActivateRemoteStaging** - failure not related to the PR
3. - **LocalFile.QuestionsEntry#CanAddQuestionWithImage** - failure not related to the PR
4. - **AdaptiveMedia#CanAdaptSVGImageInBlogsEntry** - run locally on the PR's branch - PASSED - failure not related to the PR

**Comment by izaera** [comment]
Resent as https://github.com/brianchandotcom/liferay-portal/pull/109527

**Pull request closed without merging**
