### PR TITLE
LPS-195735 Update AlloyUI to v3.1.0-deprecated.117

### PR DESCRIPTION
**Pull request by antonio-ortega**

### CODE REVIEW

**Comment by antonio-ortega** [comment]
ci:test:relevant

**Review by markocikos — APPROVED** [review]
@antonio-ortega LGTM! :sparkles:

**Comment by antonio-ortega** [comment]
ci:test:relevant

**Comment by antonio-ortega** [comment]
Manually forwarded https://github.com/brianchandotcom/liferay-portal/pull/141652

**Comment by antonio-ortega** [comment]
ci:reopen

**Pull request closed without merging**
