### PR TITLE
LPS-169277 Test fix + HR_138 The drop down is not disappearing even after selects time in expiration date when using keyboard

### PR DESCRIPTION
**Pull request by mateusralv**
**Description:**
Fix the date and time path in poshi tests caused by original PR implementations.

**Original PR:** https://github.com/liferay-frontend/liferay-portal/pull/3284

---
Fixes https://issues.liferay.com/browse/LPS-169277

### CODE REVIEW

**Comment by mateusralv** [comment]
ci:test:relevant

**Comment by dsanz** [comment]
Thanks @deborasoliveira, please check the latest results. We are prioritizing this pull over the others.

**Comment by mateusralv** [comment]
I'm on it

**Comment by mateusralv** [comment]
Hi @dsanz and @veroglez After the repairs the tests failed in a few steps forward and I found the reason, but I want a confirmation if it is as expected:

When we create the event the value is shown in 24h but when we view it in the calendar it is shown in 12h:
Bundles' PR:

https://github.com/liferay-frontend/liferay-portal/assets/44584050/427d7dce-31b0-47f0-b9ec-c2aae9d0498f

Master: 

https://github.com/liferay-frontend/liferay-portal/assets/44584050/2ddac4a7-7881-40ef-aff5-3827215fa1b4


Some tests take the value to compare with the value shown in the calendar, so the tests are failing because it is saved at 18:00, and in the verification it is compared with 06 pm.

Affected tests:
 LocalFile.WorkflowCalendar#ApproveEventWithInvitedUser 
 LocalFile.CalendarStaging#InviteUserViaUnpublishedEventAndViewNoRespon
 LocalFile.EventDetails#DeleteRegular
 LocalFile.EventDetails#DeleteRepeatingAllFollowing 
 LocalFile.ManageCalendar#SearchForOtherCalendars 
 LocalFile.NewEvent#AddAllDay 
 LocalFile.NewEvent#AddRepeatingMonthly2Times
 LocalFile.CPCommercePriceLists#AllowMultiplePriceEntriesInTheSamePriceList *
 LocalFile.CommerceProductDetails#SelectOptionValueAndAssertBundledProduc... * 
[
Testray Comparison](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=2&testrayRunIdB=2350387743&testrayRunIdA=2350103378&statusB=3)

I spent some time to understand why these tests were failing, so I took my time with the analysis result :/

**Comment by veroglez** [comment]
Hi @mateusralv! Thanks for testing this!
Regarding what you comment, we are using the native component that we were already using in mobile. The value of this native component is 24h (https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/time#setting_the_value_attribute). The only thing we have done is apply the same behavior on desktop. I share with you a video of master on mobile:


https://github.com/liferay-frontend/liferay-portal/assets/9701095/5c18538a-bbb3-44bd-b252-55b3134bde5c


So as you can see, the behavior is correct, so we can change the test.

**Comment by dsanz** [comment]
Hey @mateusralv  very good job! 

Using a native component has some consequences, that must be reflected in tests and explained to users in case they ask. 

Most notably:
* Browser will control the time selection UX, rather than us. This limits our ability to properly style it, though this is unrelated to this PR. This opens time selection UX to what browser manufacturer implements, i.e, it's not part of the Liferay UI anymore.
* As you can see in https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/time#chrome_and_opera, the use of 12h or 24h to show the hour in the UI depends on the browser and mostly on the user locale. 
* Note that "user locale" here does not mean liferay user preferences or language but the language configured in the browser itself, which may be not the same as in the portal.

As a result, just change your settings to Spanish in the browser and you'll see a nice 24h control, no matter what user is logged in the portal. Back to English (US), a 12h control with AM/PM will be shown.

So yes, test must reflect the usage of this new component properly. It's fine if tests just cover the US user if that's the default.

**Comment by dsanz** [comment]
Also @mateusralv do we have an idea of the effort needed to fix the tests?

Thanks

**Comment by mateusralv** [comment]
ci:test:sf

**Comment by mateusralv** [comment]
ci:test:sf

**Comment by mateusralv** [comment]
ci:test:relevat

**Comment by mateusralv** [comment]
ci:test:relevant

**Comment by mateusralv** [comment]
ci:reevaluate:1377401_12474

**Comment by mateusralv** [comment]
ci:test:relevant

**Comment by mateusralv** [comment]
Hi @dsanz , it took me longer than usual to make this fix because of the dropdown that is different from most of the Portal, but I got it, I tested all the tests locally and they passed, I'm just waiting for the result of the relevant one that is not returning 🤞🏽

**Comment by mateusralv** [comment]
ci:test:calendar

**Comment by mateusralv** [comment]
ci:test:commerce-functional

**Comment by mateusralv** [comment]
I found new tests that will need fixing with the result of the [ci:test:calendar ](https://github.com/liferay-frontend/liferay-portal/pull/3436#issuecomment-1597101187) These failures were not shown in the ci:test:relevant 🤔

**Comment by mateusralv** [comment]
ci:test:sf

**Comment by mateusralv** [comment]
ci:test:relevant

**Comment by mateusralv** [comment]
Hi @dsanz @veroglez I fixed all the related tests that failed in the suites: `commerce-functional`, `ci:test:calendar` and `relevant. `

I ran it locally and passed it on let's wait for the results in the CI 🤞🏽 

And I found a failure while doing an exploratory test, it doesn't break any functional tests, but returns an error in the console that doesn't show on the master:

PR's Bundles:

https://github.com/liferay-frontend/liferay-portal/assets/44584050/8b5a6a5d-6de5-442e-a09e-9a1928083e52

Master:

https://github.com/liferay-frontend/liferay-portal/assets/44584050/c456047f-74f8-460f-9742-9964378fc8fc

[Testray Comparison:](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1687210975934&testrayRunIdA=2354414949&testrayRunIdB=2354475164) commerce-functional
[Testray Comparison:](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1687182342795&testrayRunIdA=2354414949&testrayRunIdB=2354470835) ci:test:calendar
[Testray Comparison: ](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=2&testrayRunIdB=2354567817&testrayRunIdA=2354414949&statusB=3)ci:test:relevant

**Comment by mateusralv** [comment]
cc: @CarlosBrichete

**Comment by mateusralv** [comment]
ci:test:calendar

**Comment by mateusralv** [comment]
ci:test:commerce-functional

**Comment by veroglez** [comment]
@mateusralv, verifying your video, it is something that already happened on master in mobile. 

https://github.com/liferay-frontend/liferay-portal/assets/9701095/db1fc1a0-84f4-4131-b946-eb5e9eff2afc

Extending the behavior to desktop produces the same error. The error occurs when '0' is pressed in the hour field and appears to be an issue caused by the AUI component. This is not breaking any functional tests, we can open a separate bug and add it as a known issue. What do you think?

**Comment by dsanz** [comment]
Hey @mateusralv @veroglez I have to leave now, could not push to your origin Mateus, but please, take this last commit from my origin to fix the error:
https://github.com/liferay/liferay-portal/compare/master...dsanz:liferay-portal:LPS-169277

**Comment by mateusralv** [comment]
ci:test:sf

**Comment by mateusralv** [comment]
ci:test:relevant

**Comment by mateusralv** [comment]
ci:test:calendar

**Comment by mateusralv** [comment]
ci:test:relevant not working, see https://liferay.slack.com/archives/C19PWQ74J/p1687275570567429

**Comment by mateusralv** [comment]
ci:test:relevant

**Comment by dsanz** [comment]
ci:test:relevant

**Comment by veroglez** [comment]
Hi @dsanz, I have checked your commit (https://github.com/liferay/liferay-portal/commit/01a3f58e402a194cf9aaf8e8198d932e027cc7e1) and the main problem is that `date` is coming as `undefined`. This is produced from the AUI component we are using. Also, when you press 0 or the backspace key the entire input is reset generating unexpected behavior, as shown in the attached video. I think we should investigate what is the root of the issue and see if there is another way to correct it. I propose to go ahead with this PR and create a new issue for this problem that already existed before. What do you think?

Before the commit - Expected behavior

https://github.com/liferay-frontend/liferay-portal/assets/9701095/988734de-9a38-449d-8907-14d2faba62b1


After the commit - Unexpected behavior

https://github.com/liferay-frontend/liferay-portal/assets/9701095/82a49de8-9641-4ee6-80ad-742616d796a3


cc @marcoscv-work

**Comment by dsanz** [comment]
Hi @veroglez I do agree that this needs a separate investigation. I'm a bit hesitant to release this as it is (with or without the commit I've made) because of the potential weird behaviors that we can find. The fact that each browser provides different native impls of the picker creates more variance in the tests. For example, I could not reproduce the issue of writing a 0 in firefox, only in chrome.

In the end, we had this already for mobile, so, I'm fine with sending either version. am leaning towards the last one a little because I've made some testing on web contents trying to break this. I got the same result as your "After the commit" video: an empty time value, no exception in the browser console. This was well handled by the system as the old time value was kept. However, my tests were limited to web content and other parts shall be checked to see if the behavior of writing a 0 and "nullifying" the date is ok in other scenarios. 

Given that we want to release this, and that we'll keep working, I'm fine with your plan of sending this with no null check, then open a separate ticket.

Best

**Comment by mateusralv** [comment]
Hi @dsanz and @veroglez I added an ignore to the tests that I couldn't fix and noticed that some of them failed again after the last commit 🤔

One of the tests related to web content fails because it cannot enter the time: 01:01 AM, I tried manually and couldn't do it either.

https://github.com/liferay-frontend/liferay-portal/assets/44584050/e7ddb1bf-05c6-4a54-8e23-5db3fef96d1a

I opened this task where I list the tests that I put on ignore: https://liferay.atlassian.net/browse/LPS-188237

[
Testray Comparison](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1687434175996&testrayRunIdA=2357443160&testrayRunIdB=2357541746)

**Comment by mateusralv** [comment]
ci:test:relevant

**Comment by mateusralv** [comment]
ci:test:sf

**Comment by veroglez** [comment]
Hi @mateusralv, as @dsanz and I have mentioned in the previous comments, we are going to continue forward with this PR without taking account last commit (https://github.com/liferay-frontend/liferay-portal/pull/3436/commits/51b9f696a6f1ff5a91d3036e27beec5c91b8ca32) and open a specific ticket for that issue. Could you check the tests for the PR without last commit? Thank you so much 😄

**Comment by mateusralv** [comment]
ci:test:relevant

**Comment by mateusralv** [comment]
ci:test:sf

**Comment by mateusralv** [comment]
ci:test:stable

**Comment by mateusralv** [comment]
ci:test:relevant

**Comment by mateusralv** [comment]
Finally, the relevant did not return any single failures and the failures are not related!

[Testray Comparison](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1687702598323&testrayRunIdA=2360661039&testrayRunIdB=2360705569)

Tests quarantined:
View24hourTimeFormat
ViewEventDateAndTimeInResourcesAvailability

Jira ticket: https://liferay.atlassian.net/browse/LPS-188237

**Comment by mateusralv** [comment]
ci:forward

**Comment by mateusralv** [comment]
ci:test:sf

**Comment by mateusralv** [comment]
ci:forward:force

**Comment by mateusralv** [comment]
ci:forward:force

**Comment by mateusralv** [comment]
ci:forward:force

**Comment by mateusralv** [comment]
forwarded manually to https://github.com/brianchandotcom/liferay-portal/pull/137042

**Pull request closed without merging**
