### PR TITLE
LPS-205356

### PR DESCRIPTION
**Pull request by boton**
Hi there,

I'm only adding a failure screenshot and pasting the initial PR, I've reviewed the Initial PR ✅ 

## Before the PR
image

## Initial PR https://github.com/liferay-lima/liferay-portal/pull/5059

- LPS-205356 only show filter dropdown if there is something to show
- LPS-205356 invert show order code to match with name

https://liferay.atlassian.net/browse/LPS-205356

Steps to reproduce:

1) Navigate to blog admin
2) Click “New“
3) Click “Select File” to select a cover image
4) Navigate to the “Blogs Images“ tab
5) Click the “Filter“

After PR:
image

### CODE REVIEW

**Review by markocikos — APPROVED** [review]
@boton LGTM! :sparkles:

**Comment by boton** [comment]
ci:forward

**Comment by boton** [comment]
Looks like the failure **LocalFile.ClayAlertToast#DisappearsAfter10SecsWithActions** is unrelated but I'm not sure.

image

**Comment by boton** [comment]
ci:forward

**Comment by dsanz** [comment]
ci:report:2489005345

**Comment by ambrinchaudhary** [comment]
Hi team, any updates about this pull? Do we know if errors are related to this pull? 
Thanks in advance. 

cc/ @AliciaGarciaGarcia @boton

**Comment by AliciaGarciaGarcia** [comment]
```

Unique Failures
NONE,N/A,Unique,N/A
```

**Comment by AliciaGarciaGarcia** [comment]
ci:forward:force

**Comment by AliciaGarciaGarcia** [comment]
@ambrinchaudhary 
Thanks for the alert!

I was on PTO and forget about it :)

**Pull request closed without merging**
