### PR TITLE
Lps 134200

### PR DESCRIPTION
**Pull request by manuelRives**
This has already been discussed with @antonio-ortega.

The situation is that the customer has noticed that when adding a new row in searchContainer, using addRow, the new cells on that row don't have the same CSS classes that the rest of the table has.

In order to solve this behavior what @antonio-ortega proposed was instead of cloning the template row, clone the previows row existing in the container (if it exists). But this had a limitation and if the table has no previous rows when we add the first one with the addRow this row will not have the CSS classes that would have a row generated by the jsp.

In order to solve this problem I tried to replicate something similar of what was done on LPS-130722 capturing the CSS class when processing the taglib on the doStartTag method of  SearchContainerColumnTag (LPS-130722 is on the same method of SearchContainerRowTag). But since when the table has no rows the tags of the columns are not processed it wouldn't have solved the problem.

Finally to overcome this limitation I have added a new param on the addRow method so now we can specify the CSS classes of  the cells of the new row and doing so we can add rows to a empty container, and those cells will have the desired style.

### CODE REVIEW

**Comment by manuelRives** [comment]
ci:test:sf

**Comment by manuelRives** [comment]
ci:test:relevant

**Comment by manuelRives** [comment]
ci:test:sf

**Comment by manuelRives** [comment]
Hi @liferay-frontend the test:sf has failed two times but when I launch it locally it works perfectly.
Do you now what might be happening?

**Comment by nhpatt** [comment]
They don't seem related to the PR, let's retry...

**Comment by nhpatt** [comment]
ci:test:sf

**Comment by nhpatt** [comment]
Ok, I see. There is a conflict when doing the rebase in search_container.js (because a rule limiting abbreviations), so you have to rebase and force push.

**Comment by antonio-ortega** [comment]
Rebased and resent https://github.com/liferay-frontend/liferay-portal/pull/1178

**Comment by kresimir-coko** [comment]
@antonio-ortega & @manuelRives should this one be closed since you resent it in #1178 ?

**Comment by manuelRives** [comment]
@kresimir-coko Yes, this one should be closed. Thank you!

**Pull request closed without merging**
