### PR TITLE
LPS-122274 - Add aspect ratio custom property for card type asset

### PR DESCRIPTION
**Pull request by marcoscv-work**
This PR fixes the no correct aspect ratio for cards.

Since cards use a 16-9 aspect-ratio we can use the same custom property.

image

---

How to test the PR:

1. Add widget of document and media
2. Uploads some docs, images, etc
3. Reload matrix

### CODE REVIEW

**Comment by marcoscv-work** [comment]
ci:test:sf

**Comment by marcoscv-work** [comment]
ci:test:relevant

**Comment by julien** [comment]
@marcoscv-work this is interesting, clay card components have a [`flushHorizontal` and `flushVertical`](https://github.com/liferay/clay/blob/8b18dc5e48f730aa60ef1fdc51a6f75edabc3494/packages/clay-card/src/CardWithInfo.tsx#L139-L140) property, do you know if it's related?
If so, maybe we could also integrate this in the card component?

 /cc @bryceosterhaus @matuzalemsteles @pat270 (just-asking.gif)

**Comment by matuzalemsteles** [comment]
@julien I remember that it was up to the product to define the aspect ratio. Before this was configured via props, it is available in the component [`<ClayCard.AspectRatio />`](https://clayui.com/docs/components/card/api.html#card.aspectratio) but not in the high-level components, maybe we should add this in the high-level components.

**Comment by julien** [comment]
@matuzalemsteles thanks for clarifying - I know that we can [pass more classes](https://github.com/liferay/clay/blob/8b18dc5e48f730aa60ef1fdc51a6f75edabc3494/packages/clay-card/src/CardWithInfo.tsx#L137) to the `` element which means it's still possible to get the same result (as far as I understand) but I just wanted to ask.

**Comment by marcoscv-work** [comment]
That's actually a bug fix to get back the original and correct behavior, about the component everything should keep being Ok!

**Comment by julien** [comment]
Thanks @marcoscv-work :+1:

**Comment by eduardoallegrini** [comment]
This could be interesting https://www.w3schools.com/css/css3_object-fit.asp

**Comment by eduardoallegrini** [comment]
After reviewing the proposed solution I’m a little confused.

I thought: instead of adding further lines to the css-custom-properties layer we could remove the overwrite caused by it (with something like “apply the custom properties to the `.aspect-ratio` not child of `.card-type-asset`”) but then I noticed something unusual. The structure of the card-page (`.card-type-asset .aspect-ratio`) is overwriting the default `.aspect-ratio` and [it’s happening in Clay](https://github.com/liferay/clay/blob/master/packages/clay-css/src/scss/components/_cards.scss#L789).

image

I wonder, why is it doing that instead of using the right `.aspect-ratio-16-to-9` in the markup? Could we upgrade the markup and avoid this overwrite?

**Comment by eduardoallegrini** [comment]
Or.. since we are not using the aspect-ratio classes anywhere, a simpler solution would be to make the `.aspect-ratio` class 16:9 as default and provide a new class for the 1:1 ratio (We did something similar for the `.container-fluid-max-xl` – the most used is the default one)

**Comment by marcoscv-work** [comment]
@eduardoallegrini yes, you are right, there were reasons to do the overwrite, and as we have spoked, there are not real uses of `aspect-ratio`, they are Clay helpers not much used in our cases, but in order to fix the issue LPS-122274, please we can move it forward? :-D

**Comment by eduardoallegrini** [comment]
Ok, I think we can forward this and remove once we have [the change in Clay](https://github.com/liferay/clay/issues/3792)

**Comment by marcoscv-work** [comment]
Rebased

**Comment by marcoscv-work** [comment]
ci:test:sf

**Comment by marcoscv-work** [comment]
ci:test:relevant

**Comment by marcoscv-work** [comment]
ci:forward

**Pull request closed without merging**
