### PR TITLE
LPS-119586 Update @clayui/* packages to new version

### PR DESCRIPTION
**Pull request by matuzalemsteles**
This is an update with some CSS fixes and some updates to the packages, nothing too big, you can find the milestone with the features that came in this version in [milestone#27](https://github.com/liferay/clay/milestone/27?closed=1).

- Diff https://github.com/liferay/clay/pull/3640
- New version commit https://github.com/liferay/clay/commit/a4b1e06294d7ac22e864e840c3ed20f8198f9ffd

### CODE REVIEW

**Comment by jbalsas** [comment]
Rebased, updated snapshots and force-pushed

**Comment by jbalsas** [comment]
ci:test:sf

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
Hey @PablitoBonito, @john-co, @zhangyan0701 can you check to see if the test failures are related?

**Comment by john-co** [comment]
ci:test:bundle

**Comment by john-co** [comment]
Quickly reviewing, only this test is unique: WorkflowMetrics#ViewWorkloadByAssigneePage, my guess is that it's a fluke seeing all other WorkflowMetrics have passed. 

https://liferay.spiraservice.net/16/TestRun/29478366.aspx?testCaseId=134053

All other test failures don't seem to be related, failing in other PRs.

**Comment by jbalsas** [comment]
Thanks @john-co, I'll forward manually, then!

**Comment by jbalsas** [comment]
Forwarded manually to https://github.com/brianchandotcom/liferay-portal/pull/93138

**Comment by john-co** [comment]
WorkflowMetrics#ViewWorkloadByAssigneePage test passes locally, and issue not reproducible manually. cc/ @rodrigocunhaa

Reviewed. Test failures are unrelated. :heavy_check_mark:

**Comment by rodrigocunhaa** [comment]
Thanks @john-co , looks like the test didn't wait for the page to be fully loaded. I'll investigate it further.

**Pull request closed without merging**
