### PR TITLE
LPS-178066 CSP part 1 checks

### PR DESCRIPTION
**Pull request by izaera**

### CODE REVIEW

**Comment by izaera** [comment]
ci:test:sf

**Comment by izaera** [comment]
ci:test:relevant

**Comment by izaera** [comment]
ci:test:relevant

**Comment by izaera** [comment]
ci:test:relevant

**Comment by dsanz** [comment]
ci:test:relevant

**Comment by izaera** [comment]
ci:test:relevant

**Comment by izaera** [comment]
ci:test:sf

**Comment by izaera** [comment]
I've fixed the SF error caused by a double service registration.

**Comment by izaera** [comment]
ci:test:relevant

**Comment by izaera** [comment]
ci:test:sf

**Comment by izaera** [comment]
ci:test:relevant

**Comment by izaera** [comment]
ci:test:relevant

**Comment by izaera** [comment]
ci:test:relevant

**Comment by izaera** [comment]
ci:test:relevant

**Comment by JerryAdrianoo** [comment]
Hey, @izaera are all your PR's (Parts 1,2,3 and 4) ready to be reviewed yet? If yes, I can start.

**Comment by bryceosterhaus** [comment]
@JerryAdrianoo not yet, I believe there are some failures he is aware of that will be addressed when he gets back from PTO

**Comment by bryceosterhaus** [comment]
Sent https://github.com/liferay-frontend/liferay-portal/pull/3628 with udpate

**Comment by izaera** [comment]
closing. will continue at https://github.com/liferay-frontend/liferay-portal/pull/3628

**Pull request closed without merging**
