### PR TITLE
LPS-117986 Fix for multiple mentioning

### PR DESCRIPTION
**Pull request by antonio-ortega**
Hi guys,

Could you review this pull request, please?

You can find more information in LPS-117896 and original message submitted by @holatuwol

> https://issues.liferay.com/browse/LPS-117986
> 
> Based on testing by @hongvo2308 , this is the simplest check without hard-coding a dependency on the value specified by the autocomplete_input.js plugin.
> 
> https://github.com/liferay/liferay-portal/blob/7.3.3-ga4/modules/apps/frontend-js/frontend-js-aui-web/src/main/resources/META-INF/resources/liferay/autocomplete_input.js#L70-L73
> 
> Please let us know if you have any questions, or if you think there's a better way to fix the issue.
> 

Thanks.

Regards.

### CODE REVIEW

**Comment by wincent** [comment]
Anybody who's been working on CKEditor lately feel familiar enough with the set-up to review this? @carloslancha, @markocikos, @julien?

**Comment by wincent** [comment]
ci:test:sf

**Comment by wincent** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
Hey @antonio-ortega, @hongvo2308, @holatuwol, thanks for sending this over! It brings me back to my younger days 😂 

I don't see how this change can actually fix the reported issue... the change is done in the method that's used to replace the html once an item from the autocomplete list is selected. The reported issue states that the list doesn't show up the second time, so that conditional should have no effect whatsoever on this.

I haven't had a lot of time to look into this, but from what I've seen, the issue is related to [#10031 CKEditor injects special character in Chrome](https://dev.ckeditor.com/ticket/10031). This is to be expected on Webkit-based browsers and CKEditor accounts for in its [FILLING_CHAR_SEQUENCE](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_dom_selection.html#property-FILLING_CHAR_SEQUENCE)

What I'm seeing is that in presence of the filler char, our computation is off by as many filler chars as present, making the query fail. Curiously enough, an arrow movement (back) or mouse click make the fillers go away and allow the autocomplete to show again.

I don't have permissions to push to this fork, so I've sent https://github.com/liferay-frontend/liferay-portal/pull/223 to continue exploring this over there. I'm not including the original fix from here since it doesn't have any effect that I can appreciate, but feel free to re-push it in case I missed anything.

**Pull request closed without merging**
