### PR TITLE
LPS-132642 - Update @liferay/npm-scripts to v45.0.0

### PR DESCRIPTION
**Pull request by bryceosterhaus**
https://issues.liferay.com/browse/LPS-132642

Release notes:

https://github.com/liferay/liferay-frontend-projects/releases/tag/npm-scripts%2Fv45.0.0

Most noteworthy:

We are removing ".json" files from the list of files we are formatting with npm-scripts. This is due to the portal source formatter clashing with prettier and leading to unexpected CI failures.

### CODE REVIEW

**Comment by bryceosterhaus** [comment]
ci:test:sf

**Comment by bryceosterhaus** [comment]
I didn't realize we had this custom glob here on the DXP side... We wouldn't have needed to remove it from npm-scripts if I knew that 😢

**Comment by izaera** [comment]
> I didn't realize we had this custom glob here on the DXP side... We wouldn't have needed to remove it from npm-scripts if I knew that :cry: 

Yeah, I tried to move all portal specific things to the root `npmscripts.config.js` file, so anything in `npm-scripts` is supposed to be generic (though there may be some leftovers).

However, I'm not sure if we may need to revisit that demarcation criterion, since we won't be using `npm-scripts` for outer builds, for the moment... :thinking:

**Comment by bryceosterhaus** [comment]
ci:test:sf

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
@izaera I don't think its a terrible idea to keep this config in dxp, it will allow us to change things without doing full releases of npm-scripts (like we are doing here). But you are right that we may need to revisit when we start thinking about thinking about outside projects. For now though, I think this is fine to keep in DXP.

**Comment by bryceosterhaus** [comment]
ci:test:sf

**Comment by bryceosterhaus** [comment]
ci:forward

**Comment by izaera** [comment]
>  it will allow us to change things without doing full releases

Yeah, true. We also moved the config to DXP because of branching. If we move specific config for every branch (7.2, 7.3, ...) to `liferay-portal` then it's possible that one day we **may** have a single `npm-scripts` to rule them all.

**Comment by bryceosterhaus** [comment]
one day...

**Pull request closed without merging**
