### PR TITLE
LPD-7820 Remove Creation Actions FF

### PR DESCRIPTION
**Pull request by chestofwonders**
Issue: https://liferay.atlassian.net/browse/LPD-7820

The goal is to remove LPS-194395 FF, so users that have access to Data Set Manager can manage all actions types by default.

### CODE REVIEW

**Review by markocikos — APPROVED** [review]
@chestofwonders LGTM! :sparkles:

**Review by markocikos — COMMENTED** [review]
@chestofwonders Wait, the code in PR is fine, but isn't there still an entry in `portal.properties`?

**Comment by chestofwonders** [comment]
@markocikos Yes, there was an occurrence in `portal.properties`, thanks for the point!

**Comment by chestofwonders** [comment]
ci:test:sf

**Comment by chestofwonders** [comment]
ci:forward

**Comment by chestofwonders** [comment]
ci:forward:force

**Pull request closed without merging**
