### PR TITLE
LPS-205902 Make onKeyPress event for Clear link

### PR DESCRIPTION
**Pull request by fortunatomaldonado**
https://liferay.atlassian.net/browse/LPS-205902

I added tabIndex and onKeyPress event so that the user will be able to tab to the Clear link and select it with an Enter press.
Let me know if there are any questions or comments about this.
Thank you!

### CODE REVIEW

**Comment by fortunatomaldonado** [comment]
ci:test:relevant

**Review by bryceosterhaus — APPROVED** [review]
LGTM!

**Comment by fortunatomaldonado** [comment]
ci:forward

**Comment by fortunatomaldonado** [comment]
FWD: https://github.com/brianchandotcom/liferay-portal/pull/146150

**Pull request closed without merging**
