### PR TITLE
[TS] LPS-191923 zh_HK has invalid characters when used as a date mask

### PR DESCRIPTION
**Pull request by thektan**
https://liferay.atlassian.net/browse/LPS-191923

Follow-up from: https://github.com/liferay-frontend/liferay-portal/pull/3560

From my investigation, the format being returned was `yyyy'年'MM'月'dd'日'` where the single quotes were causing an issue when adding it into the javascript (see screenshot).

Screenshot 2023-08-15 at 3 51 49 PM

My fix is to remove all single quotes that could cause the javascript strings to break.

I was looking up the [Hong Kong date format](https://worldpopulationreview.com/country-rankings/date-format-by-country) and they do use (yy)yy年(m)m月(d)d日 so it does seem like those characters should be part of the mask.

## Demo

https://github.com/liferay-frontend/liferay-portal/assets/4496722/3d235508-54a7-475c-aad7-310c6031501a

cc @wanderlast

### CODE REVIEW

**Comment by thektan** [comment]
ci:test:sf

**Comment by thektan** [comment]
ci:test:relevant

**Comment by thektan** [comment]
ci:test:relevant

**Comment by thektan** [comment]
Hi @mateusralv, I wanted to check in if you had any updates looking into these failures or if we should run the tests again?

**Comment by mateusralv** [comment]
Hi @thektan The failures are not related.

[Testray Comparison](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1692727549669&testrayRunIdA=2407805130&testrayRunIdB=2408221806)

**Comment by thektan** [comment]
Thanks! I'll force forward this.

**Comment by thektan** [comment]
ci:forward:force

**Comment by thektan** [comment]
ci:forward:force

**Comment by thektan** [comment]
Manually forwarded: https://github.com/brianchandotcom/liferay-portal/pull/139579

**Pull request closed without merging**
