### PR TITLE
LPS-145116 - Apply icons API throughout DXP

### PR DESCRIPTION
**Pull request by bryceosterhaus**
Follow up from https://github.com/brianchandotcom/liferay-portal/pull/117924

### CODE REVIEW

**Comment by bryceosterhaus** [comment]
ci:stop

**Comment by bryceosterhaus** [comment]
ci:test:sf

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by Hijky** [comment]
@bryceosterhaus I check it, and it seems failures are unrelated, but it seems a Conflicting files portal-kernel/bnd.bnd

**Comment by bryceosterhaus** [comment]
manual forward https://github.com/brianchandotcom/liferay-portal/pull/118074

**Pull request closed without merging**
