### PR TITLE
LPS-198500 Adapting openSimpleInputModal to render textarea inputs

### PR DESCRIPTION
**Pull request by patriciajeanperez**
Resent from https://github.com/liferay-frontend/liferay-portal/pull/3764:

From @Stephy6 
> ### Motivation
> The motivation behind this PR is the modification of the openInputSimpleModal component (1st commit) so it is able to render textarea inputs. The component receives a boolean parameter to know if the desired input is textare or standard input. What do you think?
> https://github.com/liferay-echo/liferay-portal/pull/14043
> 
> Best regards.

### CODE REVIEW

**Comment by patriciajeanperez** [comment]
Hey @Stephy6!

This new PR contains test fixes so we can unmask some of the other failures. I will re-run the test and review again tomorrow but so far, these are the issues I have found:

- I still can't add a comment to the workflow task assigned
- There is an asterisk in the comment section that gives the impression that it is a required field when it's not
- Filter and Order does not work after a certain number of clicks. This one was caught by our functional tests and requires specific steps

1. Assign Single Approver workflow to Blogs Entry
2. Add a Blog Entry
3. Go to My Workflow Tasks
4. Go to Assigned to My Roles tab
5. Click Assign to Me under the blogs entry, click Done
6. Once you are navigated back to Assigned to Me tab, filter by Pending
7. Filter by Completed, Pending, Pending

Assert Filter by Order dropdown as well as the tabs are not responsive until you refresh

MEEDTEGCmA

Please let me know if you need help reproducing any of the issues. Thank you!

**Comment by patriciajeanperez** [comment]
ci:test:workflow

**Comment by Stephy6** [comment]
> Hey @Stephy6!
> 
> This new PR contains test fixes so we can unmask some of the other failures. I will re-run the test and review again tomorrow but so far, these are the issues I have found:
> 
> * I still can't add a comment to the workflow task assigned
> * There is an asterisk in the comment section that gives the impression that it is a required field when it's not
> * Filter and Order does not work after a certain number of clicks. This one was caught by our functional tests and requires specific steps
> 
> 1. Assign Single Approver workflow to Blogs Entry
> 2. Add a Blog Entry
> 3. Go to My Workflow Tasks
> 4. Go to Assigned to My Roles tab
> 5. Click Assign to Me under the blogs entry, click Done
> 6. Once you are navigated back to Assigned to Me tab, filter by Pending
> 7. Filter by Completed, Pending, Pending
> 
> Assert Filter by Order dropdown as well as the tabs are not responsive until you refresh
> 
> MEEDTEGCmA [ MEEDTEGCmA ](https://user-images.githubusercontent.com/14059015/283351401-0faec320-18e8-4d86-8f05-3613eb308e8e.gif) [ ](https://user-images.githubusercontent.com/14059015/283351401-0faec320-18e8-4d86-8f05-3613eb308e8e.gif)
> 
> Please let me know if you need help reproducing any of the issues. Thank you!

I'm on it, thanks @patriciajeanperez

**Comment by sandrodw3** [comment]
Resent fixing the issues in https://github.com/liferay-frontend/liferay-portal/pull/3845

**Comment by sandrodw3** [comment]
ci:close

**Pull request closed without merging**
