### PR TITLE
LPS-118290 Update liferay-ckeditor to v4.14.1-liferay-9

### PR DESCRIPTION
**Pull request by julien**
This new version of `liferay-ckeditor` contains the `codemirror` plugin

Before this change, editing source code with CKEditor looked like this:

After this change it looks like this:

Additionally, I also configured the `CKEditorBBCodeConfigContributor` and
`CKEditorCreoleConfigContributor` classes, to keep using the original 
`sourcearea` plugin because the `codemirror` plugin doesn't support 
`bbcode` and `creole` formatting

### CODE REVIEW

**Comment by julien** [comment]
ci:test:sf

**Comment by julien** [comment]
ci:test:relevant

**Review by jbalsas — APPROVED** [review]
LGTM! 👍

**Comment by carloslancha** [comment]
<a href="https://gitme.me/image?url=https%3A%2F%2Fmedia3.giphy.com%2Fmedia%2FHw8vYF4DNRCKY%2Fgiphy.gif&token=shipit" data-gitmeme-token="shipit"></a>

**Comment by jbalsas** [comment]
ci:forward

**Pull request closed without merging**
