### PR TITLE
LPS-200229 Resolve path traversals in Combo Servlet

### PR DESCRIPTION
**Pull request by izaera**

### CODE REVIEW

**Comment by izaera** [comment]
ci:test:relevant

**Comment by izaera** [comment]
I've found another vulnerability while trying to backport this to 7.0 (related to using multiple contiguous `/` to request the same file) so I will push another commit and retest.

**Comment by izaera** [comment]
ci:test:sf

**Comment by izaera** [comment]
ci:test:relevant

**Comment by dsanz** [comment]
LGTM ;)

This solution still allows paths like `/a/b/c/../../child-of-a.js` but not `/a/b/../../../parent-of-a.js`. 

Also there's a subtle optimization: now, a combo request asking for two paths `/a/c.js` and `/a/b/../c.js`  won't send `c.js` twice as both names will collide into the same `modulePathsSet` element

Makes sense to me

**Comment by markocikos** [comment]
ci:test:stable

**Comment by izaera** [comment]
ci:forward

**Comment by izaera** [comment]
The [previous CI run](https://github.com/liferay-frontend/liferay-portal/pull/3882#issuecomment-1841276339) had no unique failures and I haven't pushed any change.

Additionally, stable has passed.

So I'm forward forcing this PR.

**Pull request closed without merging**
