### PR TITLE
LPD-40811 - Fix page navigation in PW test

### PR DESCRIPTION
**Pull request by juanjofgliferay**
https://liferay.atlassian.net/browse/LPD-40811

### CODE REVIEW

**Comment by juanjofgliferay** [comment]
ci:test:relevant

**Comment by juanjofgliferay** [comment]
ci:test:playwright

**Review by markocikos — APPROVED** [review]
@juanjofgliferay LGTM! :sparkles:

**Comment by juanjofgliferay** [comment]
ci:test:sf

**Comment by juanjofgliferay** [comment]
ci:test:playwright

**Comment by juanjofgliferay** [comment]
It works when it first navigate to the newly created site but it fails in the "Go back to isolated page and check SPA". Adding the `/web/guest/` part in this step will make it work in CI but will fail locally. :disappointed:

**Comment by juanjofgliferay** [comment]
ci:test:playwright

**Comment by juanjofgliferay** [comment]
Fixed now https://testray.liferay.com/#/project/35392/routines/45357/build/57050316/case-result/57051196 :tada: 

image

**Comment by juanjofgliferay** [comment]
ci:forward

**Pull request closed without merging**
