### PR TITLE
LPS-116677 - Add a separator line to navigation-bar-light

### PR DESCRIPTION
**Pull request by marcoscv-work**
**Only for testing and @victorvalle quick review**

This PR adds a separator line under `navigation-bar-light`

image

To test this PR we only need to go to `User and Organizations`

### CODE REVIEW

**Comment by jbalsas** [comment]
Why do it in both themes and not in `styled`, @marcoscv-work?

We can always move it anyways, so I'd say let's give this a run

**Comment by jbalsas** [comment]
ci:test:sf

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by marcoscv-work** [comment]
Hey @jbalsas !
@drakonux was worried about the use of this gray line, it could be considered not a standard use for a navigation bar. if we finally want to move it to the component as standard probably we would need to move it to Clay

**Comment by pat270** [comment]
We can do this via Sass variables:
```
$navigation-bar-size: (
	border-bottom-width: 0.0625rem,
	active-border-offset-bottom: -0.5625rem,
	active-border-offset-bottom-mobile: -0.5625rem,
);

$navigation-bar-light: (
	border-color: $gray-200,
);
```

**Comment by marcoscv-work** [comment]
> We can do this via Sass variables:
> 
> ```
> $navigation-bar-size: (
> 	border-bottom-width: 0.0625rem,
> 	active-border-offset-bottom: -0.5625rem,
> 	active-border-offset-bottom-mobile: -0.5625rem,
> );
> 
> $navigation-bar-light: (
> 	border-color: $gray-200,
> );
> ```

@pat270 if I put the vars in `_clay_variables.scss` I need to use the HEX color instead of `$gray-200`. Where do you prefer to add it?

**Comment by eduardoallegrini** [comment]
Maybe you can use `light` instead of `gray-200` https://github.com/liferay/clay/blob/master/packages/clay-css/src/scss/atlas/variables/_globals.scss and `map-get($theme-colors, "light")` https://sass-lang.com/documentation/modules/map (not sure it would work 🤷‍♀️)

**Comment by jbalsas** [comment]
Sounds good to me @marcoscv-work! Are you planning to push changes?

**Comment by pat270** [comment]
> if I put the vars in _clay_variables.scss I need to use the HEX color instead of $gray-200. Where do you prefer to add it?

@marcoscv-work You need to declare `$gray-200` in `_clay_variables.scss` since it's the first import. This should work:
```
$gray-200: #f1f2f5 !default;

$navigation-bar-size: (
	border-bottom-width: 0.0625rem,
	active-border-offset-bottom: -0.5625rem,
	active-border-offset-bottom-mobile: -0.5625rem,
);

$navigation-bar-light: (
	border-color: $gray-200,
);
```

**Comment by marcoscv-work** [comment]
> > if I put the vars in _clay_variables.scss I need to use the HEX color instead of $gray-200. Where do you prefer to add it?
> 
> @marcoscv-work You need to declare `$gray-200` in `_clay_variables.scss` since it's the first import. This should work:
> 
> ```
> $gray-200: #f1f2f5;
> 
> $navigation-bar-size: (
> 	border-bottom-width: 0.0625rem,
> 	active-border-offset-bottom: -0.5625rem,
> 	active-border-offset-bottom-mobile: -0.5625rem,
> );
> 
> $navigation-bar-light: (
> 	border-color: $gray-200,
> );
> ```

I was trying to avoid the variable re-assign or pre-assign :-(
Resending..

**Pull request closed without merging**
