### PR TITLE
LPS-158259 Refactor to move GraphQL fetching data functionality into a specific classes

### PR DESCRIPTION
**Pull request by ccorreagg**
This PR contains the code to refactor certain functionality by moving it from the GraphQLServletExtender java class into a some DataFetcher classes and new Processors. This is the first step to solve the [this bug [Returns 401 Unauthorized error when using OAuth 2.0 as the authorization mechanism]](https://issues.liferay.com/browse/LPS-158259)

### CODE REVIEW

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by 4lejandrito** [comment]
✅

**Comment by ccorreagg** [comment]
ci:forward

**Pull request closed without merging**
