### PR TITLE
LPS-134865 Upgrade tinycolor2 to 1.4.2

### PR DESCRIPTION
**Pull request by rolandpakai**
jQuery dependency coming from our clayui/color-picker which has a dependency of tinyColor2 (https://github.com/liferay/clay/blob/master/packages/clay-color-picker/package.json#L35), whose @1.4.1 version includes jQuery@1.9.1 (https://github.com/bgrins/TinyColor/blob/1.4.1/demo/jquery-1.9.1.js). Luckily for us, tinycolor2@1.4.2 removed any dependency from jQuery  (https://github.com/bgrins/TinyColor/commit/250a1e2421242b336770d50c2b5e1eae292bc727)

More details: https://issues.liferay.com/browse/PTR-2475

cc @antonio-ortega

### CODE REVIEW

**Comment by matuzalemsteles** [comment]
Hey @rolandpakai, I wouldn't recommend making the change directly in `yarn.lock`, the best would be to make sure to update it in Clay and once done that would be reflected here. What do you think?

**Comment by bryceosterhaus** [comment]
I agree with Matu here, we shouldn't be making any direct changes to our yarn.lock unless there is a corresponding dependency change in one of our package.json files. Updating tinycolor2 is best done in the Clay repo, and an even better option would be removing it entirely as a dependency from clay 😜

**Comment by matuzalemsteles** [comment]
> Updating tinycolor2 is best done in the Clay repo, and an even better option would be removing it entirely as a dependency from clay 😜 . And for what it is worth, it is my fault it's a dependency in Clay 😂

haha 😂 that's true 😁, well, depending on whether we can analyze whether it's worth it, I didn't get to look at the `tinycolor2` implementation, maybe it's worth it.

**Comment by bryceosterhaus** [comment]
I'm gonna close to avoid an accidental forwards, but feel free to continue the conversation on this PR

**Comment by bryceosterhaus** [comment]
Also, note that tinycolor2 was never using jquery for anything in its functionality, it was just there for their own demo site. So I don't think this would actually be an issue for that PTR.

**Comment by rolandpakai** [comment]
Hi @matuzalemsteles 

thank you for taking care for the upgrade in the clay.
Could you please let me known where can i check the new release of the @clayui/color-picker which contains the tinycolor2@1.4.2 ?  

Thanks, Roland

**Comment by rolandpakai** [comment]
Thank you @matuzalemsteles

**Comment by rolandpakai** [comment]
Hi @matuzalemsteles 

do you think i can backport @clayui/color-picker 3.31.0 to 73x without any issue or version dependency?

In 73x the current version is 3.5.0
https://github.com/liferay/liferay-portal-ee/blob/7.3.x/modules/apps/frontend-taglib/frontend-taglib-clay/package.json#L10

Thanks, Roland

**Comment by matuzalemsteles** [comment]
hey @rolandpakai, sorry for delay, looking at the changelog we haven't had many significant changes that might break something, so I think it's safe.

**Pull request closed without merging**
