### PR TITLE
LPS-142335 Establish z-index for input field in Modal for Chrome

### PR DESCRIPTION
**Pull request by fortunatomaldonado**
https://issues.liferay.com/browse/LPS-142335

This issue only relates to Chrome as it has a weird behavior with the input fields text being pushed back and not visible when clicked on. This only occurs when the input field is in a modal and not anywhere else in chrome. All the other browsers seem to behavior normally. 
A solution is to add `z-index: auto` to the input field so it would take the z-index of its parent element and remain on top. Including the z-index resolves the weird behavior that chrome has and will not affect any other browsers. This will be added to all inputs that are in a modal.

Let me know if there are any questions or comments about this.
Thank you.

### CODE REVIEW

**Comment by fortunatomaldonado** [comment]
ci:test:sf

**Comment by fortunatomaldonado** [comment]
ci:test:relevant

**Comment by fortunatomaldonado** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
Hey @pat270 in case it helps, it seems that the problem is in clay css: https://github.com/liferay/clay/blob/dc5312ed5cdac52662a429624c4628b7ee57eec6/packages/clay-css/src/scss/cadmin/components/_input-groups.scss#L72

This z-index creates a next stacking context that makes the input disappear, do you have any idea why this may be happening?

This solution works, but maybe we can just remove the z-index from clay too 🤔

**Comment by julien** [comment]
I agree with @victorg1991 and [this](https://issues.liferay.com/browse/LPS-141916) issue also seems related

**Comment by pat270** [comment]
I'm going to fix this in Clay. See more details at https://github.com/liferay/clay/issues/4423.

**Pull request closed without merging**
