### PR TITLE
LPS-125853 Switch to our `@liferay/jquery-form` fork

### PR DESCRIPTION
**Pull request by wincent**
Instead of maintaining a patched copy of [the upstream project](ttps://github.com/jquery-form/form) in-line in this repo, we've made [an actual fork of it](https://github.com/liferay/liferay-frontend-projects/tree/master/third-party) and are pulling that in here via npm. This gives us [a clear CHANGELOG.md documenting where we've deviated from the upstream](https://github.com/liferay/liferay-frontend-projects/blob/master/third-party/projects/jquery-form/CHANGELOG.md).

The motivating use case here is closing an XSS hole by [bringing in a fix that is currently being ignored in the upstream repo](https://github.com/jquery-form/form/pull/586).

To test, enabled jQuery in system settings and confirmed that `jquery/form.js` is coming down _and_ that it indeed [matches the patched version](https://github.com/liferay/liferay-frontend-projects/blob/b1bb4882e621caae213057e2d526c0216d5fd6b2/third-party/projects/jquery-form/jquery.form.js#L13-L16) that we're shipping in our fork:

Screenshot 2021-02-08 -175308-TS95MLco@2x

### CODE REVIEW

**Comment by wincent** [comment]
@NemethNorbert, can you please check this out and see if it makes sense? It replaces the [PR you originally sent](https://github.com/liferay-frontend/liferay-portal/pull/699).

@jbalsas or @izaera: perhaps one of you can satisfy my curiosity about how the resource serving works in this case. When I build this, I can see the `jquery/form.js` file getting put exactly where I'm telling it to go, into `tmp/`:

```
tmp
└── META-INF
    └── resources
        └── jquery
            ├── bootstrap.bundle.min.js
            ├── bootstrap.bundle.min.js.map
            ├── form.js
            ├── jquery.min.js
            ├── popper.min.js
            └── popper.min.js.map

3 directories, 6 files
```

(That's `frontend-js-jquery-web/tmp`, at the same level as `src`, `build`, `classes`; not to be confused with `build/tmp`.)

What's not clear to me is how DXP is actually able to serve that file. You can see the request being made in my screenshot in the PR summary, and it is coming down correctly, but it is not coming from the JAR (_none_ of the files from `tmp/` are in the JAR — I know this because I unzipped it and looked inside) and I would have thought that Tomcat could only serve stuff that was deployed to it via a JAR. Is there some additional "side-loading" mechanism at play here? And if so, does it only apply because I am using "dev"-ish settings?

```
$ find . -name '*form.js'
./classes/META-INF/resources/node_modules/@frontend-js-jquery-web$liferay%2Fjquery-form@3.51.0-liferay.1/jquery.form.js
./build/node/packageRunBuild/resources/node_modules/@frontend-js-jquery-web$liferay%2Fjquery-form@3.51.0-liferay.1/jquery.form.js
./build/tmp/jar/com.liferay.frontend.js.jquery.web-3.0.0/META-INF/resources/node_modules/@frontend-js-jquery-web$liferay%2Fjquery-form@3.51.0-liferay.1/jquery.form.js
./tmp/META-INF/resources/jquery/form.js
```

Note how the only copy of `form.js` is in `tmp/`, and the original `jquery.form.js` is in the JAR only because it sneaks in via `node_modules`, just like the other modules do:

```
$ ls ./build/tmp/jar/com.liferay.frontend.js.jquery.web-3.0.0/META-INF/resources/node_modules
@frontend-js-jquery-web$liferay%2Fjquery-form@3.51.0-liferay.1
frontend-js-jquery-web$jquery@3.5.1
frontend-js-jquery-web$popper.js@1.14.7
```

**Comment by wincent** [comment]
ci:test:sf

**Comment by wincent** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
> @jbalsas or @izaera: perhaps one of you can satisfy my curiosity about how the resource serving works in this case. When I build this, I can see the jquery/form.js file getting put exactly where I'm telling it to go, into tmp/:

Hey @wincent, easy peasy! Just a pinch of good ol'

magic

In all seriousness, [this](https://github.com/liferay-frontend/liferay-portal/blob/4c4254711526d855334d6d7f40315aff5ffff6a0/modules/apps/frontend-js/frontend-js-jquery-web/bnd.bnd#L5) is the key:

```
-includeresource: META-INF/resources=tmp/META-INF/resources
```

This instruction tells `bndtools` (I think) to overlay `tmp/META-INF/resources` into the `META-INF/resources` resulting folder before assembling the jar. That's how I understand it, my my understanding is limited in this case, so there might be something else going on ;)

**Comment by NemethNorbert** [comment]
Hey @wincent,

This looks great, I like it better than the patch direction.

Thank you for working on this

**Comment by wincent** [comment]
ci:test:relevant

**Comment by wincent** [comment]
> This instruction tells `bndtools` (I think) to overlay `tmp/META-INF/resources` into the `META-INF/resources` resulting folder before assembling the jar. That's how I understand it, my my understanding is limited in this case, so there might be something else going on ;)

"Something like that" 😂 (seeing as the files aren't in the JAR).

**Comment by jbalsas** [comment]
> "Something like that" 😂 (seeing as the files aren't in the JAR).

Are you positive? They should be there, at least they are on `master`.

They should be in `META-INF/resources` and not in `tmp/META-INF/resources`

Screen Shot 2021-02-08 at 21 49 28

In this example, both `bootstrap.js` and `jquery.js` are the ones coming from `tmp`, so same should be for `form.js` after this.

**Comment by jbalsas** [comment]
Here's some literature about [-includeresource](https://bnd.bndtools.org/instructions/includeresource.html) with some examples that might be interesting, although we might as well forget about this until next time 😂

**Comment by wincent** [comment]
> Are you positive?

Well, when it comes to computers I am never 100% positive about anything... but quoting [from my original comment](https://github.com/liferay-frontend/liferay-portal/pull/772#issuecomment-775303721), I did a `find` after unzipping the JAR in-place and it locates these items:

- `./classes/META-INF/resources/node_modules/@frontend-js-jquery-web$liferay%2Fjquery-form@3.51.0-liferay.1/jquery.form.js`
- `./build/node/packageRunBuild/resources/node_modules/@frontend-js-jquery-web$liferay%2Fjquery-form@3.51.0-liferay.1/jquery.form.js`
- `./build/tmp/jar/com.liferay.frontend.js.jquery.web-3.0.0/META-INF/resources/node_modules/@frontend-js-jquery-web$liferay%2Fjquery-form@3.51.0-liferay.1/jquery.form.js` ← this is the only hit from the JAR
- `./tmp/META-INF/resources/jquery/form.js`

And my screenshot shows the right file is being served. (I also tried renaming the file to `formz.js` in the `build.gradle` but not in the `.java` class to prove to myself that it would 404, and it did.)

🤷

**Comment by wincent** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
> Well, when it comes to computers I am never 100% positive about anything... but quoting from my original comment, I did a find after unzipping the JAR in-place and it locates these items:

I assume you took the `jar` from the `./build` folder? I think that one's not properly overlayed yet and is only a temporary artifact. I usually look at them in the `/tools/sdk/dist` folder.

After fetching this branch and running the build on it, I get the following `jar`

Screen_Shot_2021-02-08_at_22_14_25

Hope that makes sense!! This LGTM!

**Comment by wincent** [comment]
> I assume you took the `jar` from the `./build` folder? I think that one's not properly overlayed yet and is only a temporary artifact. I usually look at them in the `/tools/sdk/dist` folder.

Dark secrets indeed. I did indeed take the one from `./build/tmp/jar/`, which was the only one I knew about... Truly diabolical.

**Comment by wincent** [comment]
Also, I see you are using Vim...

amazed

**Comment by wincent** [comment]
ci:test:relevant

**Comment by izaera** [comment]
Late to the conversation, but the safest place to look for JARs is in the `osgi/modules` folder of the deployed portal. For the rest, you never know what's gonna happen. The `osgi/modules` one is the one that Tomcat sees, so it's the one you will end up executing.

Also, a useful trick I sometimes use to avoid a deploy is to open those JAR files with vi and change `.js` files, for example. You can do it even with Tomcat running and it triggers an OSGi reload.

magic

**Comment by wincent** [comment]
ci:forward

**Pull request closed without merging**
