### PR TITLE
LPS-179109 - ActionLinkRender never finds actionId

### PR DESCRIPTION
**Pull request by david-truong**

### CODE REVIEW

**Comment by deborasoliveira** [comment]
ci:test:relevant

**Comment by deborasoliveira** [comment]
I'll take a look at the most recent relevant result 👍🏽  
In the first relevant result, there were many tests that failed before being executed.

**Comment by dsanz** [comment]
@markocikos I think we shall add an example of this in the sample widget. I guess this was not caught earlier because all use cases take the first action in the action link renderer.

**Comment by markocikos** [comment]
@dsanz Yeah, makes sense to add a sample. 

I'm seeing two usages of `fdsTableSchemaField.setActionId` in commerce. I'm surprised they didn't notice the issue earlier, the bug manifests as an always empty field:
screen

**Comment by markocikos** [comment]
Followup in https://github.com/liferay-frontend/liferay-portal/pull/3160

**Pull request closed without merging**
