### PR TITLE
LPS-144832 - Add selectedLanguageIdAtom and use in input_localized and samples

### PR DESCRIPTION
**Pull request by tinycarol**
This PR was reverted a second time due to [this bug](https://issues.liferay.com/browse/LPS-149392). After analyzing it, the cause is a race condition: the workflow team is using `Liferay.component` in an inline script to get the `input_localized` instance, which now takes longer to initialize due to the atom. Getting the instance asynchronously using `Liferay.componentReady` fixes the bug.

### References

- [LPS-144832](https://issues.liferay.com/browse/LPS-144832)
- [LPS-148305](https://issues.liferay.com/browse/LPS-148305)
- [LPS-149392](https://issues.liferay.com/browse/LPS-149392)

### What is the goal?

* Add `selectedLanguageIdAtom` to share the currently selected language between `input_localized` and any React component. 

### What does it look like?

https://user-images.githubusercontent.com/6642927/156166334-1f342c33-fd83-42d0-ac86-c5a41de61469.mov

### How to replicate
* Go to `Content & Data > Web Content`
* Click on `+` button and select `Basic Web Content` in the dropdown
* Type something in the input at the top
* Click on the flag next to that input, select a different flag
* See that the input has the same value as before (might change alignment in different locales)
* See that if you click on the flag next to the input, the currently selected language still shows as `Not translated`

### Notes
* I'm not convinced by this solution: having two different "events" for this makes it flaky, and maybe the opposite could happen in the future (someone using the atom having the changes to the atom overridden because of the event). Maybe we should remove `inputLocalized:localeChanged` and use the atom instead, or remove the atom and use that event in React components.

### CODE REVIEW

**Comment by john-co** [comment]
Hi @tinycarol , I reproduced the issue with the bundle from this PR.

https://user-images.githubusercontent.com/35235266/159806589-63d87584-4d21-4254-8b2f-b64e7b0f8a64.mp4

I also tried on Firefox browser and used BrowserStack on MacOS Safari and still reproduced the issue.

**Comment by john-co** [comment]
ci:test:relevant

**Comment by john-co** [comment]
I'm not sure why you're not seeing the issue on your end. @Esther-OC could you sanity check if you can reproduce [the issue](https://issues.liferay.com/browse/LPS-149392)? I'm wondering if there's any difference with Mac environment.

**Comment by tinycarol** [comment]
@john-co It seems like this view looks different for me 😕 
This is what it looks like on my machine:
image
Vs your screenshot:
image
I'll take a look today to see if I'm missing something, but this looks like a 👻

**Comment by tinycarol** [comment]
ci:test:sf

**Comment by tinycarol** [comment]
ci:test:relevant

**Comment by john-co** [comment]
Reviewed. Test failures are unrelated. :heavy_check_mark: 

cc/ @anabuchmann another flaky workflow test

**Comment by john-co** [comment]
Ok to manually forward from QA side.

**Comment by carloslancha** [comment]
LGTM. Mis dies!

**Comment by tinycarol** [comment]
Forwarded to Brian https://github.com/brianchandotcom/liferay-portal/pull/115181

**Pull request closed without merging**
