### PR TITLE
LPS-174464 Implement improvements on performance of resolve modules servlet URL generation

### PR DESCRIPTION
**Pull request by izaera**
This is another take at LPS-174464.

It contains all the changes we rolled back:

- https://github.com/brianchandotcom/liferay-portal/pull/129834
- https://github.com/brianchandotcom/liferay-portal/pull/129910

But, additionally, it implements:

1. Full hashing of resolution state to be safer
2. Resolution state snapshots so that resolutions are stable and don't poison CDN caches

Given the problems found in previous PRs, it would be worth checking this thoroughly from a QA standpoint.

### CODE REVIEW

**Comment by izaera** [comment]
ci:test:sf

**Comment by izaera** [comment]
ci:test:sf

**Comment by izaera** [comment]
ci:test:relevant

**Comment by izaera** [comment]
ci:test:relevant

**Comment by eltonccdantas** [comment]
I'll take a look at it

**Comment by eltonccdantas** [comment]
Hi @izaera , I found a failure concerning semantic versioning related to your request:

`[exec] com.liferay.semantic.versioning.SemanticVersioningTest > testSemanticVersioning[/apps/frontend-js/frontend-js-loader-modules-extender-api] FAILED
     [exec]     java.lang.AssertionError:   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec]     = ================================================== ========== ========== ========== ========== ==========
     [exec]     * com.liferay.frontend.js.loader.modules.extender.npm MAJOR      5.0.0      5.0.0      6.0.0      VERSION INCREASE REQUIRED
     [exec]     	-   interface  com.liferay.frontend.js.loader.modules.extender.npm.ModifiableJSPackage
     [exec]     		-   access     abstract
     [exec]     		-   implements com.liferay.frontend.js.loader.modules.extender.npm.JSBundleObject
     [exec]     		-   implements com.liferay.frontend.js.loader.modules.extender.npm.JSPackage
     [exec]     		-   method     addJSModule(com.liferay.frontend.js.loader.modules.extender.npm.JSModule)
     [exec]     			-   access     abstract
     [exec]     			-   return     void
...`

**Comment by izaera** [comment]
The problem CI is complaining about was fixed in the last commit I pushed -> https://github.com/liferay-frontend/liferay-portal/pull/3122/commits/b4de5789fd8b50f86579b65d45de018018ce0d21

The CI, in theory, was invoked after that commit -> https://github.com/liferay-frontend/liferay-portal/pull/3122#issuecomment-1470015697

So, I don't know  why it reported that error :shrug: 

I'll launch CI tests again.

**Comment by izaera** [comment]
ci:test:relevant

**Review by bryceosterhaus — COMMENTED** [review]
I don't remember fully remember what the issues were last time with this PR but I remember approving it previously, so I didn't go too deep in looking through this. I also probably am not the best to give an in-depth java review.

**Comment by izaera** [comment]
ci:stop

**Comment by izaera** [comment]
ci:test:relevant

**Comment by eltonccdantas** [comment]
Nice, all green!

**Comment by izaera** [comment]
ci:forward

**Pull request closed without merging**
