### PR TITLE
LPS-187617 - Chat workspace

### PR DESCRIPTION
**Pull request by bryceosterhaus**
Coming from @mahmoudhtayem87, https://github.com/brianchandotcom/liferay-portal/pull/136142

https://liferay.atlassian.net/browse/LPS-187617

### CODE REVIEW

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by CarlosBrichete** [comment]
Hey @bryceosterhaus, failures are not related to your changes :)

**Comment by bryceosterhaus** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/140089

**Pull request closed without merging**
