### PR TITLE
LPS-163662 Update liferay-ckeditor to 4.18.0-liferay.3

### PR DESCRIPTION
**Pull request by diegonvs**
**Full Changelog**: https://github.com/liferay/liferay-ckeditor/releases/tag/v4.18.0-liferay.3

Fixes https://issues.liferay.com/browse/LPS-163662

### CODE REVIEW

**Review by markocikos — APPROVED** [review]
LGTM!

**Comment by markocikos** [comment]
ci:forward

**Comment by markocikos** [comment]
Looks like slaves are unable to read trees, in https://github.com/liferay-frontend/liferay-portal/pull/2781#issuecomment-1277719229. Not sure what to do with this information :thinking:

**Comment by diegonvs** [comment]
ci:forward

**Comment by markocikos** [comment]
ci:forward

**Comment by diegonvs** [comment]
ci:forward

**Comment by markocikos** [comment]
ci:forward

**Pull request closed without merging**
