### PR TITLE
LPD-28612 - Configure API Headless filters in fragment

### PR DESCRIPTION
**Pull request by juanjofgliferay**
## Story / Task
[LPD-19880](https://liferay.atlassian.net/browse/LPD-19880) / [LPD-28612](https://liferay.atlassian.net/browse/LPD-28612)

> [!CAUTION]
> @chestofwonders https://github.com/liferay-frontend/liferay-portal/pull/4270/ changes need to be merged before.
> 

## Goal
Process API Headless filters information to be able to use them in the FDS component.
API Headless filters will retrieve the options from an external URL and setup the preselected values if needed.

## UI
[Screencast from 2024-06-20 13-06-31.webm](https://github.com/liferay-frontend/liferay-portal/assets/132653342/d2485adb-db8d-4fe0-a154-e46923c74258)

## Playwright
apifiltertest

### CODE REVIEW

**Comment by juanjofgliferay** [comment]
ci:test:playwright

**Review by dsanz — APPROVED** [review]
LGTM ;) no particular comments

**Review by markocikos — APPROVED** [review]
@juanjofgliferay LGTM! It'll only need some conflicts fixing after https://github.com/brianchandotcom/liferay-portal/pull/151730 is merged

**Comment by juanjofgliferay** [comment]
ci:test:sf

**Comment by juanjofgliferay** [comment]
ci:forward

**Pull request closed without merging**
