### PR TITLE
LPS-161704 Add GET system relationship endpoint to API Explorer.

### PR DESCRIPTION
**Pull request by LuismiBarcos**
Related ticket with the prerequisites -> https://issues.liferay.com/browse/LPS-161704
____
## How to test it
* Deploy the following modules:
  * object-api
  * portal-vulcan-api
  * portal-vulcan-impl
  * object-rest-impl
* Ensure that you have the prerequisites on your Liferay.
* Ensure that you have the feature flag enabled -> `feature.flag.LPS-153324=true`
* Go to API Explorer (http://localhost:8080/o/api)
  * Go to headless-admin-user
  * Go to UserAccount. The last endpoint should be the relationships endpoint.
* Type de Id of a user with some relationships

You should see something like this
image

### CODE REVIEW

**Comment by LuismiBarcos** [comment]
Take into account that this is a first approximation about how to expose dynamic endpoints in API Explorer. This implementation could change at any time.

Some of my concerns in this PR are:
* In the module `object-rest-impl` I'm using this dependency:
`compileOnly group: "io.swagger.core.v3", name: "swagger-models", version: "2.0.6"`
	I think that it could be great if, in the future, we do not have this dependency and could expose all the necessary through Vulcan. But it could be a hard task.
* I am using a dummy implementation to show the endpoint response in API Explorer. That should change but could be done in future PRs.
* The reason I am using a dummy implementation is that it is hard to get the `$ref` parameter to point to the Schema that we are going to respond to. I mean, the responses are dynamic, like the endpoint. Sometimes, we will return a Subject, other times we will return a Student, and so on. Infer that Schema to show it in the API explorer is hard because it could be in any Jaxrs Application and, if it is a custom object, the names are dynamics too.
* The implementation is to create a GET endpoint. I would like to have a better implementation that could generate any type of endpoints but in my experience, it is better to go step by step and change the implementation to one more generic when we will need it. If you believe that it could be more generic in this PR, tell me and I will change it :)

**Comment by LuismiBarcos** [comment]
cc/ @4lejandrito

**Comment by LuismiBarcos** [comment]
The SF errors could be related to the CDN problems reported in internal channels. I am trying again.

**Comment by LuismiBarcos** [comment]
ci:test:sf

**Comment by 4lejandrito** [comment]
ci:test:sf

**Comment by 4lejandrito** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
ci:test:sf

**Comment by 4lejandrito** [comment]
ci:stop

**Comment by 4lejandrito** [comment]
Moved to the new repo https://github.com/liferay-headless/liferay-portal/pull/716.

**Comment by 4lejandrito** [comment]
ci:close

**Pull request closed without merging**
