### PR TITLE
LPS-193100 Increasing the value to 60 seconds

### PR DESCRIPTION
**Pull request by antonio-ortega**
Related [discussion](https://liferay.slack.com/archives/C3JBR21HA/p1691564522490459) on Slack.

### CODE REVIEW

**Comment by izaera** [comment]
LGTM!

LGTM

**Comment by antonio-ortega** [comment]
ci:test:relevant

**Comment by JerryAdrianoo** [comment]
ci:test:relevant

**Comment by mateusralv** [comment]
Hi @antonio-ortega the failures are not related.

[Testray Comparison](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1692275768047&testrayRunIdA=2406989315&testrayRunIdB=2407447171)

**Comment by antonio-ortega** [comment]
ci:forward:force

**Pull request closed without merging**
