### PR TITLE
LPS-188205 Fix for ClientExtensionUsingConfigFile#CanCreateCellRendererViaOSGI 

### PR DESCRIPTION
**Pull request by mateusralv**
**Description:**
Fix ClientExtensionUsingConfigFile#CanCreateCellRendererViaOSGI on CI. 

**JIRA link:**
https://liferay.atlassian.net/browse/LPS-188205

### CODE REVIEW

**Comment by mateusralv** [comment]
ci:test:frontend-data-set

**Comment by mateusralv** [comment]
ci:help

**Comment by mateusralv** [comment]
ci:test:frontend

**Review by CarlosBrichete — APPROVED** [review]
LGTM

**Comment by mateusralv** [comment]
ci:test:frontend

**Comment by mateusralv** [comment]
ci:test:sf

**Comment by mateusralv** [comment]
ci:test:frontend

**Comment by mateusralv** [comment]
ci:test:sf

**Comment by mateusralv** [comment]
ci:test:frontend

**Comment by mateusralv** [comment]
ci:test:sf

**Comment by mateusralv** [comment]
ci:test:frontend

**Comment by mateusralv** [comment]
ci:forward

**Comment by mateusralv** [comment]
The test is [passing](https://testray.liferay.com/home/-/testray/case_results/2445622775?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2445622428%26testrayRunId%3D2445622446%26cur%3D2%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc%26resetCur%3Dfalse) on CI

**Pull request closed without merging**
