### PR TITLE
LPS-156925 Update Alloy Editor to v2.14.8

### PR DESCRIPTION
**Pull request by diegonvs**
Follow https://issues.liferay.com/browse/LPS-156925 for reproduction steps.

# Release Notes

## What's Changed
* use defaultLinkTarget when creating a link, fixes autolink by @markocikos in https://github.com/liferay/alloy-editor/pull/1536
* fix: Reset uibridge definitions each time we destroy and create and editor (#1537) by @georgel-pop-lr in https://github.com/liferay/alloy-editor/pull/1538

## New Contributors
* @markocikos made their first contribution in https://github.com/liferay/alloy-editor/pull/1536

**Full Changelog**: https://github.com/liferay/alloy-editor/compare/v2.14.7...v2.14.8

### CODE REVIEW

**Comment by diegonvs** [comment]
ci:test:sf

**Comment by diegonvs** [comment]
ci:test:relevant

**Comment by diegonvs** [comment]
Unrelated, re-running CI again

**Comment by diegonvs** [comment]
ci:test:relevant

**Comment by diegonvs** [comment]
Unrelated again...

**Comment by diegonvs** [comment]
ci:test:relevant

**Review by markocikos — APPROVED** [review]
LGTM!

**Comment by markocikos** [comment]
ci:forward

**Comment by diegonvs** [comment]
ci:forward

**Comment by mateusralv** [comment]
I’m taking a look at [these results](https://github.com/liferay-frontend/liferay-portal/pull/2686#issuecomment-1237299532) 🕵🏽

**Comment by mateusralv** [comment]
Hey @diegonvs I made a [comparison with master ](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1662404086936&testrayRunIdA=1966967674&testrayRunIdB=1967260763)and the resulting failures are not unique to your PR, so are not related 🎉

**Comment by diegonvs** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/122712

**Pull request closed without merging**
