### PR TITLE
[7.4.x-only] | LRQA-62492 Update the console text theme assertion to 7.4

### PR DESCRIPTION
**Pull request by PablitoBonito**
https://issues.liferay.com/browse/LRQA-62492
**DESCRIPTION**
It fixes the issue of no theme found for specified theme id testtheme73_WAR_testtheme.

### CODE REVIEW

**Comment by john-co** [comment]
ci:test:sf

**Comment by john-co** [comment]
ci:test:relevant

**Comment by john-co** [comment]
As discussed, I think we want more text to guide the reviewer in the first PR comment for the description: https://github.com/liferay-frontend/liferay-portal/pull/435#issuecomment-712666060

And this may be an unwritten rule but I was taught that we capitalize the first word of the commit, and prefer a verb. No -ing. So something like `Update...` is better.

**Comment by john-co** [comment]
I added 7.4.x-only into the title. During this transition time from 7.3 to 7.4, we want to make it more obvious for BChan to not backport 7.4 only code changes.

**Review by john-co — APPROVED** [review]

**Comment by john-co** [comment]
Looks good, [test passes locally](https://issues.liferay.com/browse/LRQA-62492?focusedCommentId=2300118&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-2300118) Forwarding.

**Comment by john-co** [comment]
ci:forward

**Comment by jbalsas** [comment]
> As discussed, I think we want more text to guide the reviewer in the first PR comment for the description: #435 (comment)

You can see the PRs in the repo for a good measure of the expected contents in the description.

**Pull request closed without merging**
