### PR TITLE
LPS-167156 Make page title visible with 200% zoom

### PR DESCRIPTION
**Pull request by edalgrin**
This PR fixes an accessibility issue with the visibility of the page title within 200% zoom configuration

Ticket: https://issues.liferay.com/browse/LPS-167156

ezgif com-gif-maker

### CODE REVIEW

**Comment by edalgrin** [comment]
ci:stop

**Comment by edalgrin** [comment]
ci:test:sf

**Comment by dsanz** [comment]
ci:test:relevant

**Comment by dsanz** [comment]
ci:test:stable

**Review by marcoscv-work — APPROVED** [review]

**Comment by eltonccdantas** [comment]
Hi @edalgrin, I've analyzed the errors. They look unrelated to your PR according to the [comparison](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=2&testrayRunIdB=2162756758&testrayRunIdA=2162363589&statusB=3). You may manually forward if no other dev review is needed.

CC/ @john-co , @mateusralv

**Comment by marcoscv-work** [comment]
I think we can go ahead and send it manually

**Comment by edalgrin** [comment]
> I think we can go ahead and send it manually

We need to ask @liferay-echo and @liferay-tango first, since we are adding a new "category" to the control-menu and moving the segments-experience into it.

@liferay-echo @liferay-tango can you take a look please?

**Comment by claraizquierdo** [comment]
Hi,

I'm going to review the behavior, but everything seems ok to me. Maybe @cgoncas can confirm better than me that the change in the category is not a problem.

**Comment by edalgrin** [comment]
> The only thing I have found is that if we have a long experience name and a small screen, the label overlaps with the experience name: Captura de pantalla 2023-01-19 a las 16 21 12

that could be annoying, I'm going to take a second look, thanks!

**Comment by jkappler** [comment]
@edalgrin, @dsanz, is it really necessary to create the new navigation control menu entry? It seems to be a too specific use case.

@ealonso, @lfbesada, @ruben-pulido

**Comment by edalgrin** [comment]
ezgif com-gif-maker

**Comment by edalgrin** [comment]
> @edalgrin, @dsanz, is it really necessary to create the new navigation control menu entry? It seems to be a too specific use case.
> 
> @ealonso, @lfbesada, @ruben-pulido

Hey @jkappler in order to obtain the required behavior of the control-menu is the only way (without using JS workarounds). Is it a problem to have a new entry?

**Comment by marcoscv-work** [comment]
> ezgif com-gif-maker [ ezgif com-gif-maker ](https://user-images.githubusercontent.com/46778114/213652849-0f97a559-df80-451c-ab03-183b6b15db05.gif) [ ](https://user-images.githubusercontent.com/46778114/213652849-0f97a559-df80-451c-ab03-183b6b15db05.gif)

For me is also working in this way

**Review by claraizquierdo — APPROVED** [review]
LGTM! 🎉

**Comment by dsanz** [comment]
> @edalgrin, @dsanz, is it really necessary to create the new navigation control menu entry? It seems to be a too specific use case.
> 
> @ealonso, @lfbesada, @ruben-pulido

This is necessary to provide separate containers in the markup for the segments experience to enable wrapping behavior. 

As an alternative, we could change `flex` options inside the `tools-control-group` for the `control-menu-nav` div ([here](https://github.com/liferay-frontend/liferay-portal/pull/2958/commits/3245aa599ec0d3d6889104ba9bed8d669715b2fb#diff-5e60d0cf93bc7f80bda54acbfd392557ad9fc68c11ddc6330ced03eea978687dR275)). In that case, I think the behavior would not be the same as the flex would apply first inside the control menu nav, then outside, something like this:
image

@edalgrin not sure if this is something you considered, I don't believe we'll get the desired result but wanted to make sure we discarded this

**Comment by jkappler** [comment]
Hi @dsanz, @edalgrin, thanks for the answer. Just wanted to be sure

**Comment by dsanz** [comment]
ci:test:relevant

**Comment by dsanz** [comment]
ci:test:sf

**Comment by dsanz** [comment]
Hi @eltonccdantas could you please let us know whether failed relevant test are related to this pull? Edu made another change after the first analysis

Thank you

**Comment by dsanz** [comment]
@edalgrin could you please take a look to the conflict? seems that we'll need to rebase the styling changes in that file.

Thank you

**Comment by edalgrin** [comment]
> @edalgrin could you please take a look to the conflict? seems that we'll need to rebase the styling changes in that file.
> 
> Thank you

Yes, I was waiting for the second QA review

**Comment by mateusralv** [comment]
Hi @edalgrin and @dsanz I took a look at these results here (https://github.com/liferay-frontend/liferay-portal/pull/2958#issuecomment-1398539325) and the only failure are not related. 🟢 🎉 

[Testray comparison](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1674491619767&testrayRunIdA=2170279151&testrayRunIdB=2167861123)

**Comment by dsanz** [comment]
Thanks @edalgrin and @mateusralv!

Edu, pls send the followup commit and forward it

**Comment by dsanz** [comment]
While solving the merge conflict, I've realized that there's deeper change in the `segments_experience_selector.jsp`, which now relies entirely on a react component. This means that the original changes we made to the jsp side ([removing text-truncate](https://github.com/liferay-frontend/liferay-portal/pull/2958/commits/9c5333c9c038165fdd95074dd11d8404e3e818a3#diff-d501c4e4b21cfe2eb044b07fe9a17c5b6a72aea42e632445c619313ca60b22ecR32) and [add flex-wrap](https://github.com/liferay-frontend/liferay-portal/pull/2958/commits/371752cc5c579bfa07d5aa4f0ce4cd3d4ee34a32#diff-d501c4e4b21cfe2eb044b07fe9a17c5b6a72aea42e632445c619313ca60b22ecR26)) are no longer applicable. 

Still, there's [this truncate](https://github.com/liferay/liferay-portal/blob/master/modules/apps/segments/segments-web/src/main/resources/META-INF/resources/js/components/ExperiencePicker.js#L38) in the new ExperiencePicker which brings back the `text-truncate` we removed.

@edalgrin is working on this, we'll probably need @claraizquierdo to take a look

**Comment by claraizquierdo** [comment]
Hi @dsanz ,

you are right. We just migrated the experience selector to the Picker component. Let me know if I can help in any way.

**Comment by dsanz** [comment]
> Hi @dsanz ,
> 
> you are right. We just migrated the experience selector to the Picker component. Let me know if I can help in any way.

Thanks @claraizquierdo , looks like changes won't be big. I was able to make it work locally with these quick changes:
image

Edu will send the final commits on top of this PR

**Comment by edalgrin** [comment]
I updated the PR with the adjustments to the new component. It should be working fine. In my test the page title is missing but I think it's because a bad deployed module, so I'm launching an `ant all` to test it again.

ezgif com-gif-maker

@claraizquierdo can you test the changes as well?

On the other hand:
- I needed a new CSS class for the experience text to fix the `white-space: nowrap` property defined by the `.form-control-select` class – is the name `.experience-picker-text` correct?
- I noticed that because of the `padding-right: inherit` property of the `.c-inner` class we are inheriting the padding of its parent `.form-control-select` and creating a double space for the select icon – is this "bug" known?

**Comment by kresimir-coko** [comment]
I changed the title from `visibible` to `visible`, my self-diagnosed OCD was kicking in too much

**Comment by dsanz** [comment]
> I changed the title from `visibible` to `visible`, my self-diagnosed OCD was kicking in too much

Nice catch Kreso! As Edu has italian roots, maybe this is an unconscious mix between `visibile` and `visible` (Spanish word for this is the same as English) :it:

**Review by claraizquierdo — APPROVED** [review]
I reviewed the behavior again and everything looks fine 👍

**Comment by dsanz** [comment]
@edalgrin please forward this to BChan as we have all the blessings now

**Comment by edalgrin** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/129226

**Pull request closed without merging**
