### PR TITLE
LPS-114698 Brings Dataset Display TagLib from Commerce

### PR DESCRIPTION
**Pull request by brunobasto**
@brianchandotcom asked for some changes [here](https://github.com/brianchandotcom/liferay-portal/pull/91051#issuecomment-656280369) so I've made the changes.

@wincent @jbalsas 

Previously:

- https://github.com/liferay-frontend/liferay-portal/pull/75
- https://github.com/wincent/liferay-portal/pull/319
- https://github.com/brunobasto/liferay-portal/pull/1203
- https://github.com/liferay-frontend/liferay-portal/pull/79

### CODE REVIEW

**Comment by brunobasto** [comment]
ci:test:sf

**Comment by brunobasto** [comment]
ci:test:relevant

**Comment by brunobasto** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
Let's try again? I would suggest squashing and keep only the last new commits for Brian's reference, but not sure it will make a difference.

I mentioned this PR in our weekly call yesterday and he said it was almost done, so hopefully we won't have many more iterations... 🤞

**Comment by jbalsas** [comment]
ci:forward

**Comment by wincent** [comment]
If only Commerce were already on master, this would have gone in incrementally long ago...

despair

**Comment by brunobasto** [comment]
Let me check what is going on with those baseline errors..

**Comment by brunobasto** [comment]
ci:test:sf

**Comment by brunobasto** [comment]
ci:test:relevant

**Comment by brunobasto** [comment]
ci:forward

**Pull request closed without merging**
