### PR TITLE
LPS-156755 - Update npm-scripts and eslint-config packages

### PR DESCRIPTION
**Pull request by bryceosterhaus**
https://issues.liferay.com/browse/LPS-156755

Updates both packages to latest. Some formatting fixes but no major functionality changes.

### CODE REVIEW

**Comment by kresimir-coko** [comment]
@bryceosterhaus reminder that this bad boy has a bunch of conflicts

**Comment by bryceosterhaus** [comment]
ci:test:sf

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by magjed4289** [comment]
Test failures are unrelated. OK to rebase and manually forward. 👌🏻

**Comment by bryceosterhaus** [comment]
manual forward at https://github.com/brianchandotcom/liferay-portal/pull/119472

**Pull request closed without merging**
