### PR TITLE
LPS-155352 | Add takeScreenshot() for ClaySmoke#CanRenderUi

### PR DESCRIPTION
**Pull request by abhnerramos**
**Description**
Check if each nav section of clay sample portlet looks normal from screenshot

**Test Plan**
- Set browser window size
- Change tabs and take a screenshot

**JIRA Ticket**
https://issues.liferay.com/browse/LPS-155352

### CODE REVIEW

**Comment by abhnerramos** [comment]
ci:test:frontend

**Comment by abhnerramos** [comment]
@mateusralv waiting for your approval to run `ci:forward`

**Review by mateusralv — CHANGES_REQUESTED** [review]
Could you put the function `takeScreenshot();` inside the `ClaySamplePortlet.assertNavTabVisualContent` macro?

e.g.:

```
macro assertNavTabVisualContent {
		var tabName = StringUtil.replace(${tab}, " ", "_");

		var tabName = StringUtil.toLowerCase(${tabName});

		Navigator.gotoNavTab(navTab = ${tab});

		OcularAssertElementImage(
			locator1 = "ClaySamplePortlet#CLAY_SECTION",
			value1 = "liferay-portal/portal-web/test/functional/com/liferay/portalweb/dependencies/ocular/baseline/clay_smoke/can_render_ui/${tabName}.png",
			value2 = 70);

		takeScreenshot();
	}
```

**Comment by abhnerramos** [comment]
ci:test:sf

**Comment by abhnerramos** [comment]
ci:test:relevant
ci:test:stable
ci:test:frontend

**Comment by mateusralv** [comment]
ci:forward

**Pull request closed without merging**
