### PR TITLE
LPS-125846 Grey bars of assets with just one vocabulary categories

### PR DESCRIPTION
**Pull request by dgarciasarai**
**Description**

The Content Dashboard shows assets with just one vocabulary category selected. If you configure the chart with two vocabularies, we can see sections with "No XXX Specified".

**Solution**

* Use grey color for bars of asset with just one vocabulary (instead of one of the list)
* Change copy from "No {CategoryName} Category" to "No {CategoryName} Specified"

**Screenshoot**

Screenshot 2021-01-26 at 10 08 06

### CODE REVIEW

**Comment by dgarciasarai** [comment]
Hey @liferay-frontend, can you review these changes? Backend code was already reviewed in https://github.com/liferay-tango/liferay-portal/pull/800 so if the frontend code is also ok, we can forward it. Thanks!

**Review by bryceosterhaus — APPROVED** [review]
Looks good to me! Can forward once tests pass

**Comment by bryceosterhaus** [comment]
ci:forward

**Comment by dgarciasarai** [comment]
Thanks @bryceosterhaus!!

**Pull request closed without merging**
