### PR TITLE
LPS-168867 Remove FDS expand property

### PR DESCRIPTION
**Pull request by juanjofgliferay**
Follows https://github.com/liferay-frontend/liferay-portal/pull/3433

- Remove expand property, logic and styles from the frontend-data-set
- Remove use case from commerce-catalog

### CODE REVIEW

**Comment by markocikos** [comment]
ci:forward

**Comment by markocikos** [comment]
ci:stop

**Comment by juanjofgliferay** [comment]
ci:forward

**Comment by markocikos** [comment]
ci:forward

**Comment by markocikos** [comment]
At a glance, https://github.com/liferay-frontend/liferay-portal/pull/3442#issuecomment-1589900429 look unrelated

**Comment by markocikos** [comment]
ci:forward

**Comment by markocikos** [comment]
ci:forward

**Comment by markocikos** [comment]
ci:forward

**Comment by juanjofgliferay** [comment]
ci:forward

**Comment by markocikos** [comment]
ci:forward

**Pull request closed without merging**
