### PR TITLE
LPS-142359 Implement new TM attributes for input-field in aui:input

### PR DESCRIPTION
**Pull request by carloslancha**

### CODE REVIEW

**Comment by carloslancha** [comment]
ci:test:sf

**Comment by carloslancha** [comment]
ci:test:relevant

**Review by tinycarol — APPROVED** [review]
LNHTM,BIANSIWTMC

**Review by nhpatt — APPROVED** [review]
ci:forward

**Comment by diegonvs** [comment]
ci:forward

**Pull request closed without merging**
