### PR TITLE
LPS-129517 Update lodash from 4.17.19 to 4.17.21

### PR DESCRIPTION
**Pull request by wincent**
Motivated by: https://snyk.io/vuln/SNYK-JS-LODASH-590103

### CODE REVIEW

**Comment by wincent** [comment]
And to save you the hassle of running `yarn why lodash` after this PR, [here is the output](https://gist.github.com/wincent/606c310e57f5339bf382c0df1e762f27).

**Comment by wincent** [comment]
Looks like we can `ci:forward` this...

**Comment by jbalsas** [comment]
ci:forward

**Comment by wincent** [comment]
Screenshot 2021-03-24 -120730-7yLGBEF0@2x

dreams-come-true

**Comment by jbalsas** [comment]
> Screenshot 2021-03-24 -120730-7yLGBEF0@2x
> 
> dreams-come-true

iknow

**Pull request closed without merging**
