### PR TITLE
LPS-194941 Element is not present in DataSetViewDateFilters#CanConfirmChangesInDate

### PR DESCRIPTION
**Pull request by andreluis2022**
**Description**:
Element is not present in DataSetViewDateFilters#CanConfirmChangesInDate

**JIRA Ticket:**
[LPS-194941](https://liferay.atlassian.net/browse/LPS-194941) FIX

### CODE REVIEW

**Comment by andreluis2022** [comment]
ci:test:frontend-data-set

**Comment by andreluis2022** [comment]
Hey @CarlosBrichete can you take a look in this fix?

**Review by CarlosBrichete — APPROVED** [review]
LGTM

**Comment by andreluis2022** [comment]
ci:forward

**Comment by andreluis2022** [comment]
ci:forward:force

**Pull request closed without merging**
