### PR TITLE
LPS-143033 Add missing return statements

### PR DESCRIPTION
**Pull request by jonathanmccann**
**Steps to reproduce:**
1. Go to this [link](https://github.com/liferay/liferay-portal/blob/013fd759eaec2cc5f2ead7519085b617f068a245/modules/apps/frontend-taglib/frontend-taglib-clay/src/main/java/com/liferay/frontend/taglib/clay/servlet/taglib/ManagementToolbarTag.java).
2. Go to lines **244** and **324**.

**Actual Result:**
Those two lines doesn't have `return` statement.

**Expected Result:**
Those two lines must have `return` statement.

**JIRA Ticket:**
https://issues.liferay.com/browse/LPS-143033

### CODE REVIEW

**Comment by diegonvs** [comment]
Hey @jonathanmccann, thanks for submitting this!

Please read [FI Pull Request Etiquette](https://liferay.atlassian.net/wiki/spaces/ENGFRONTENDINFRA/pages/1998258186/FI+Pull+Request+Etiquette).

If possible, we'd appreciate if you could provide

* Descriptive title
* Thorough description of the issue, things you tried, why you thing your solution is the right approach and any other considerations that might help us in our review
* If there is a visual component to the change, screenshots or gifs, before and after PR
* Test plan with simple steps to validate the issue (or get a feeling of how it has been validated by you)

Thank you!

**Comment by sergiojimcos** [comment]
ci:test:relevant

**Comment by Esther-OC** [comment]
Unique failures do not seem related to the PR, so it is ok to forward it manually from QA perspective.

**Comment by sergiojimcos** [comment]
Manual forward: https://github.com/brianchandotcom/liferay-portal/pull/115717

**Pull request closed without merging**
