### PR TITLE
LPS-123906 Update clayui deps

### PR DESCRIPTION
**Pull request by carloslancha**
Updating `@clayui/sticker`, `@clayui/list` and `@clayui/card` dependencies

This pr includes a cherry-pick of a commit from LPS-121964 so we avoid conflicts.

### CODE REVIEW

**Comment by carloslancha** [comment]
ci:test:sf

**Review by julien — APPROVED** [review]
This PR is not horrible :heart:

**Comment by carloslancha** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
ci:forward

**Pull request closed without merging**
