### PR TITLE
LPD-1376 | Fix icon selection via keyboard in data-set-admin actions

### PR DESCRIPTION
**Pull request by kresimir-coko**
[Jira ticket](https://liferay.atlassian.net/browse/LPD-1376)

This is how it looks like after the fix
image

### CODE REVIEW

**Comment by kresimir-coko** [comment]
ci:test:relevant

**Review by markocikos — APPROVED** [review]
@kresimir-coko LGTM! :sparkles:

**Comment by kresimir-coko** [comment]
ci:test:relevant

**Comment by kresimir-coko** [comment]
ci:forward

**Pull request closed without merging**
