### PR TITLE
LPS-148154 Include asset priority in StructuredContent in Headless API

### PR DESCRIPTION
**Pull request by ccorreagg**
Related ticket: [LPS-148154](https://issues.liferay.com/browse/LPS-148154)

This PR contains the code to expose the asset priority field for StructuredContent in the Headless API.

The field has been exposed by modifying the rest-openapi.yaml file:

        StructuredContent:
            description:
                Represents content that has fields and is rendered by a template backed by a `ContentStructure`. This is
                modeled internally as a `JournalArticle`.
            properties:
            [...]
                priority:
                    # @review
                    description:
                        The blog post's priority.
                    format: double
                    type: number
            [...]

It may be tested by invoking the /headless-delivery/v1.0/sites/{siteId}/structured-contents endpoint; see the following example with siteId 20123:

```
curl \
	-H "accept: application/json" \
	-H "Content-Type: application/json" \
	-X 'POST' "http://localhost:8080/o/headless-delivery/v1.0/sites/${1}/structured-contents" \
	-u "test@liferay.com:test" \
	--data-binary @- << EOF
		{
			"contentFields": [
				{
				"contentFieldValue": {
					"data": "<p>My content</p>"
				},
				"dataType": "string",
				"label": "content",
				"name": "content",
				"nestedContentFields": [],
				"repeatable": false
				}
			],
			"contentStructureId" : "39774",
			"title" : "Able",
			"priority": 1.3
		}
	EOF
```
getting the following response:

```
{
  "actions": {
    "get-rendered-content": {
      "method": "GET",
      "href": "http://localhost:8080/o/headless-delivery/v1.0/structured-contents/40422/rendered-content/{contentTemplateId}"
    },
    "get-rendered-content-by-display-page": {
      "method": "GET",
      "href": "http://localhost:8080/o/headless-delivery/v1.0/structured-contents/40422/rendered-content-by-display-page/{displayPageKey}"
    },
    "subscribe": {
      "method": "PUT",
      "href": "http://localhost:8080/o/headless-delivery/v1.0/structured-contents/40422/subscribe"
    },
    "unsubscribe": {
      "method": "PUT",
      "href": "http://localhost:8080/o/headless-delivery/v1.0/structured-contents/40422/unsubscribe"
    },
    "get": {
      "method": "GET",
      "href": "http://localhost:8080/o/headless-delivery/v1.0/structured-contents/40422"
    },
    "replace": {
      "method": "PUT",
      "href": "http://localhost:8080/o/headless-delivery/v1.0/structured-contents/40422"
    },
    "update": {
      "method": "PATCH",
      "href": "http://localhost:8080/o/headless-delivery/v1.0/structured-contents/40422"
    },
    "delete": {
      "method": "DELETE",
      "href": "http://localhost:8080/o/headless-delivery/v1.0/structured-contents/40422"
    }
  },
  "availableLanguages": [
    "en-US"
  ],
  "contentFields": [
    {
      "contentFieldValue": {
        "data": "<p>My content</p>"
      },
      "dataType": "string",
      "label": "content",
      "name": "content",
      "nestedContentFields": [],
      "repeatable": false
    }
  ],
  "contentStructureId": 39774,
  "creator": {
    "additionalName": "",
    "contentType": "UserAccount",
    "familyName": "Test",
    "givenName": "Test",
    "id": 20127,
    "name": "Test Test"
  },
  "customFields": [],
  "dateCreated": "2022-02-25T11:52:28Z",
  "dateModified": "2022-02-25T11:52:28Z",
  "datePublished": "2022-02-25T11:52:00Z",
  "description": "",
  "externalReferenceCode": "40420",
  "friendlyUrlPath": "able",
  "id": 40422,
  "key": "40420",
  "keywords": [],
  "numberOfComments": 0,
  "priority": 1.3,
  "relatedContents": [],
  "renderedContents": [
    {
      "contentTemplateId": "BASIC-WEB-CONTENT",
      "contentTemplateName": "Basic Web Content",
      "markedAsDefault": true,
      "renderedContentURL": "http://localhost:8080/o/headless-delivery/v1.0/structured-contents/40422/rendered-content/BASIC-WEB-CONTENT"
    }
  ],
  "siteId": 20123,
  "subscribed": false,
  "taxonomyCategoryBriefs": [],
  "title": "Able",
  "uuid": "350a9551-2ced-0bfa-1d6a-0a9d050b2af3"
}

```

### CODE REVIEW

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by LuismiBarcos** [comment]
Just kidding, we need to know how to automate the CI for you

**Comment by LuismiBarcos** [comment]
ci:test:sf

**Comment by LuismiBarcos** [comment]
ci:test:relevant

**Review by LuismiBarcos — APPROVED** [review]
LGTM :)

**Comment by LuismiBarcos** [comment]
ci:forward

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by LuismiBarcos** [comment]
ci:forward

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by javierdearcos** [comment]
ci:forward

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by LuismiBarcos** [comment]
ci:forward

**Pull request closed without merging**
