### PR TITLE
LPS-150218 Update `@clayui/*` packages to v2.52.0

### PR DESCRIPTION
**Pull request by matuzalemsteles**
# [3.52.0](https://github.com/liferay/clay/compare/v3.51.0...v3.52.0) (2022-04-04)

### Bug Fixes

-   **@clayui/clay-tabs:** Insert displayType for nav-tabs and nav-underline classes ([10ddb29](https://github.com/liferay/clay/commit/10ddb29a88884e05d4d4f71caec111a58c809bb7))
-   **@clayui/drop-down:** fix contextual menu error not rendering icons without spaces ([a115add](https://github.com/liferay/clay/commit/a115add1d60ff61012013932cbff42af31aff70e))
-   **@clayui/navigation-bar:** add truncate text OOTB to ClayNavigationBar.Item ([b8a53a2](https://github.com/liferay/clay/commit/b8a53a20d81e10fa065997d740fc000f58334a0c))
-   **@clayui/navigator-bar:** Long text in Item is truncated ([587171d](https://github.com/liferay/clay/commit/587171d48bcfff641135176a2fae493c695d95b6))
-   **@clayui/shared:** fix error when controlling focus in React 17.x ([76f5f0d](https://github.com/liferay/clay/commit/76f5f0d964231d8442c780b44f6a320b50b9948b))

### Features

-   **@clay/empty-state:** Enable users to not render title related markup on empty-state ([608378b](https://github.com/liferay/clay/commit/608378b15985f273845d0fee7a91e486b4c78666))
-   **@clayui/clay-tabs:** Adding additional new tests ([d74322c](https://github.com/liferay/clay/commit/d74322c4820ef1f0bbb9c0c64263f82c39d70576))
-   **@clayui/clay-tabs:** Remain modern prop and overrides displayType. Update in BREAKING.md ([cb9eb31](https://github.com/liferay/clay/commit/cb9eb31d3da70de3ccdb653a9e574da497d6ee84))
-   **@clayui/color-picker:** Add more test cases in color-picker ([89e5ef6](https://github.com/liferay/clay/commit/89e5ef6b4d91f43d6cbd072daaa37e1f6b0c9fb9))
-   **@clayui/color-picker:** Adding more test cases and change snapshots by expect functions ([6ef292c](https://github.com/liferay/clay/commit/6ef292c48e6da6f8606db4616f1ff5f8d01bd871))
-   **@clayui/color-picker:** Update snapshots ([e71da9d](https://github.com/liferay/clay/commit/e71da9d9304684b73e24fe5b9dff3e4380cbfdc3))
-   **@clayui/color-picker:** Updates in test case title and not expecting splotch clicked ([6b5ff9f](https://github.com/liferay/clay/commit/6b5ff9f27b9472cae7f0fb76a15accb363b65117))
-   **@clayui/modal:** When using ClayModalProvider, `footer`,`header` properties now are optional ([4bcbac2](https://github.com/liferay/clay/commit/4bcbac2d42be1c3d58876bbf65cd2e6d86c1b6fc))
-   **@clayui/navigation-bar:** add the `nav-link` class by default for Clay components ([c6cff02](https://github.com/liferay/clay/commit/c6cff020911b8080112f0b97199b353f996836f7))

### CODE REVIEW

**Comment by matuzalemsteles** [comment]
ci:test:frontend-clay

**Comment by matuzalemsteles** [comment]
ci:test:sf

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by matuzalemsteles** [comment]
ci:test:stop

**Comment by matuzalemsteles** [comment]
ci:stop

**Comment by matuzalemsteles** [comment]
ci:test:sf

**Comment by matuzalemsteles** [comment]
ci:test:sf

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by matuzalemsteles** [comment]
ci:test:frontend-clay

**Comment by susanchen3** [comment]
Taking a look :detective:

**Comment by susanchen3** [comment]
Over 250 unique test failures after [comparison run](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=2&testrayRunIdB=1655166037&testrayRunIdA=1655136586&statusB=3):

- About ~50 Forms [test](https://testray.liferay.com/reports/production/logs/2022-04/test-1-33/test-portal-acceptance-pullrequest(master)/1575/functional-tomcat90-mysql57-jdk8/17/0/LocalFile.FormsRulesActions_CanBeEdited/index.html.gz?authuser=0) failures because I am unable to click on `Form`, `Rules`, and `Entries` buttons consistently, it takes a lot of spam clicking and luck
Form

- Around ~200 Object [test](https://testray.liferay.com/reports/production/logs/2022-04/test-1-33/test-portal-acceptance-pullrequest(master)/1575/functional-tomcat90-mysql57-jdk8/10/7/LocalFile.CreateObject_CanAddFieldTab/index.html.gz?authuser=0) failures (and a few other product tests) because the paths have changed from 
image
to 
image

Not sure if you would want me to go in and fix the tests because it seems like I can modify most paths from `//a[contains(text(), 'Fields')]` to `//span[contains(text(), 'Fields')]`, I'm just afraid of missing some tests.
    - ex. [LocalFile.PGDynamicdatalists#ViewListRecordWithUploadedFreeMarkerDisplayTemplate](https://testray.liferay.com/reports/production/logs/2022-04/test-1-33/test-portal-acceptance-pullrequest(master)/1575/functional-tomcat90-mysql57-jdk8/26/16/LocalFile.PGDynamicdatalists_ViewListRecordWithUploadedFreeMarkerDisplayTemplate/index.html.gz?authuser=0)

**Comment by matuzalemsteles** [comment]
Thanks @susanchen3 for the details, yeah Navigation Bar changed the markup to fix the bug the text is not truncated, I think we will have to update the paths.

I'll take a look at what might be happening with Forms.

**Comment by susanchen3** [comment]
Ah I see, I'll start working on updating the paths tomorrow :)

**Comment by susanchen3** [comment]
Testing the updated paths in this [PR](https://github.com/susanchen3/liferay-portal/pull/25). Hoping for better results, but still expecting test failures (other than Forms) :smile:  :crossed_fingers:

**Comment by matuzalemsteles** [comment]
Thanks @susanchen3, I'm going to check the behavior of Forms now, I had many meetings this morning I ended up running out of time.

**Comment by matuzalemsteles** [comment]
Well, I fixed the Forms implementation which was not expecting a markup change because there is an implementation of controlling the taglib in React to simplify the system routing system.

**Comment by susanchen3** [comment]
Thanks! I'll test it out and run relevant again after the run on my PR finishes :)

**Comment by susanchen3** [comment]
Hey @matuzalemsteles, sorry for taking so long on updating the paths, it's taking 10+ hours to see test results from CI. :( 

I pushed in one more fix, so [this run](https://github.com/susanchen3/liferay-portal/pull/25#issuecomment-1090727721) _should_ be good to go. :crossed_fingers:  Shall I manually forward if the test results look good? Seems like the navigation error in Forms is fixed as well :)

**Comment by matuzalemsteles** [comment]
@susanchen3 no problem, yes please if the tests are ok you can send them.

**Comment by susanchen3** [comment]
Tested test fixes in this [PR](https://github.com/susanchen3/liferay-portal/pull/25). Test failures are unrelated :heavy_check_mark:   Manually forwarded [here](https://github.com/brianchandotcom/liferay-portal/pull/115826)

[Comparison run](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=2&testrayRunIdB=1657142772&testrayRunIdA=1657342870&statusB=3):
- Forms tests are passing locally
- No other tests failing due to changes from PR :tada:

**Pull request closed without merging**
