### PR TITLE
LPS-164618 | Add Autom. test FDSCustomView#CanCreateMultiple

### PR DESCRIPTION
**Pull request by deborasoliveira**
**Test Plan**

- Given Custom view enabled for a dataset display instance
- And Given A custom view is created and selected
- When Make some changes to dataset display (filter, sorting, page size or visible columns if data display in table)
- And Click Save as button, provide a name
- Then A new custom view is created, and selected as current view

**JIRA Ticket:**
https://issues.liferay.com/browse/LPS-164618

### CODE REVIEW

**Comment by deborasoliveira** [comment]
ci:test:sf

**Comment by deborasoliveira** [comment]
ci:test:frontend:nocompile

**Review by john-co — APPROVED** [review]
Looks good to me! :sunglasses:

**Comment by john-co** [comment]
already reviewed in https://github.com/mateusralv/liferay-portal/pull/15#issuecomment-1279599711

@deborasoliveira, please rebase to master upstream and make adjustments to conflicting files.

**Comment by deborasoliveira** [comment]
ci:test:sf

**Comment by deborasoliveira** [comment]
ci:test:frontend:nocompile

**Comment by deborasoliveira** [comment]
> already reviewed in [mateusralv#15 (comment)](https://github.com/mateusralv/liferay-portal/pull/15#issuecomment-1279599711)
> 
> @deborasoliveira, please rebase to master upstream and make adjustments to conflicting files.

I already finished to rebase and the changes needed.

**Comment by deborasoliveira** [comment]
ci:test:frontend:nocompile

**Comment by deborasoliveira** [comment]
ci:test:frontend:nocompile

**Comment by deborasoliveira** [comment]
ci:test:sf

**Comment by deborasoliveira** [comment]
ci:forward

**Pull request closed without merging**
