### PR TITLE
LPS-115798 Namespaces ignoreUserLocaleOptions sessionClick key

### PR DESCRIPTION
**Pull request by jbalsas**
Resend from https://github.com/brianchandotcom/liferay-portal/pull/90541#event-3475762282 to account for the non-namespaced key.

### Test Case:
Load a page in a different language from the default.
Like:

- Create a new site called Site Name with a public page called Home.
- Add an es_ES translation for Home page. eg. Casa.
- Navigate to the following url:
http://localhost:8080/es/web/site-name/home

--- 

Please keep in mind that I'm pretty sure this doesn't 100% work. The toast shows, which is the goal of this task, but the remember feature doesn't. The `useHttpSession` here is passed as a sessionClick value, but then read [with ParamUtil](https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portal/action/SessionClickAction.java#L57) so I doubt this is doing what it thinks it's doing.

I attempted a change in [Session.setSessionValue](https://github.com/liferay/liferay-portal/commit/534ba19ed733adee96b107361054a6b8413ad473) to properly handle this... but since this didn't work before nor after this change, I decided to let it go for now, but it would look something like:

```javascript
function getSessionClickURL({useHttpSession) {
	return `${Liferay.ThemeDisplay.getPortalURL()}${Liferay.ThemeDisplay.getPathMain()}/portal/session_click${useHttpSession ? '?useHttpSession="true" : ''}`;
}

export function setSessionValue(key, value, config = {useHttpSession: true}) {
    	return fetch(getSessionClickURL(config), {
		body: formData,
		method: 'POST',
	});
}
```

Based on [Allow users to dismiss the message during the session (until next login)](https://github.com/liferay/liferay-portal/commit/534ba19ed733adee96b107361054a6b8413ad473), I expect this worked in the beginning... but I fail to see how it can work now...

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:test:sf

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
All looks good, I think... 

And @kenji-heigel said here that [it all should we swell forwarding](https://liferay.slack.com/archives/C19PWQ74J/p1592957764069700?thread_ts=1592420332.050100&cid=C19PWQ74J) now:

> Sorry for the late update! the bug that was preventing some pulls with “no unique failures” (with only upstream functional test failures) from being forwarded has been fixed as of 1:30PM PST today.
i saw one PR that was forwarded to BChan within the past hour that show that the issue has been resolved. Please continue to let us know about any other issues or unhelpful behavior. Thanks!

**Comment by jbalsas** [comment]
tumbleweed

**Comment by jbalsas** [comment]
ci:forward

**Comment by jbalsas** [comment]
Well.. of course, this had unique failures, just flaky... what was I thinking...

victorydance

**Comment by jbalsas** [comment]
ci:stop

**Comment by jbalsas** [comment]
ci:stop

**Comment by wincent** [comment]
make-it-stop

**Comment by jbalsas** [comment]
ci:stop

**Comment by jbalsas** [comment]
stahp

**Comment by jbalsas** [comment]
Manually forwarded... https://github.com/brianchandotcom/liferay-portal/pull/90575

**Pull request closed without merging**
