### PR TITLE
LPS-117116 Use useTimeout hook instead of setTimeout

### PR DESCRIPTION
**Pull request by wincent**
Use `useTimeout()` because it is not safe to make state-setting calls inside a `setTimeout()` callback, unless guarded by an `isMounted()` check (which `useTimeout()` includes automatically).

We'll eventually [create a lint](https://github.com/liferay/eslint-config-liferay/issues/116) to catch this kind of thing automatically in the future.

(Noticed this while doing post-hoc review of [liferay-frontend#142](https://github.com/liferay-frontend/liferay-portal/pull/142)).

cc @carloslancha

### CODE REVIEW

**Comment by wincent** [comment]
ci:test:sf

**Comment by wincent** [comment]
ci:test:relevant

**Comment by wincent** [comment]
Disclaimer: I did not do manual testing of this because it seems trivial; you can see [how `useTimeout()` works](https://github.com/wincent/liferay-portal/blob/40aefc1941e92d7ee19b8fb4c63409c5de8a7fed/modules/apps/frontend-js/frontend-js-react-web/src/main/resources/META-INF/resources/js/hooks/useTimeout.es.js) and what is [expected in its tests](https://github.com/wincent/liferay-portal/blob/40aefc1941e92d7ee19b8fb4c63409c5de8a7fed/modules/apps/frontend-js/frontend-js-react-web/test/js/hooks/useTimeout.es.js).

**Comment by carloslancha** [comment]
Thanks @wincent , much better! I'll add this to the pr I'm working on right now so I'm closing this  😄

**Comment by wincent** [comment]
```
React Hook useEffect has a missing dependency: 'delay'.
```

Sigh... update incoming.

**Comment by carloslancha** [comment]
ci:stop

**Comment by carloslancha** [comment]
> Sigh... update incoming.

Don't worry, I'll fix it in my pr, just to avoid probable conflicts xD

**Comment by wincent** [comment]
> > Sigh... update incoming.
> 
> Don't worry, I'll fix it in my pr, just to avoid probable conflicts xD

roger

**Comment by wincent** [comment]
FWIW, even though it would mean undoing this change, I think you might be able to do without the arbitrary 100ms timeout by use `requestAnimationFrame` instead (but then you would need to do an explicit `isMounted()` check just to be bullet-proof).

**Comment by carloslancha** [comment]
> ci:stop

I feel ignored

**Comment by carloslancha** [comment]
ci:stop

**Pull request closed without merging**
