### PR TITLE
LPS-119114 Fix space to make the product-menu closable

### PR DESCRIPTION
**Pull request by eduardoallegrini**
The first solution I tried, was to move the condition and re-enable the close button

image

But, as you can see, it's pretty ugly 😁.

So I decided to slightly change the layout of the current Product-Menu

ezgif com-video-to-gif (2)

### CODE REVIEW

**Comment by wincent** [comment]
ci:test:bundle

**Comment by wincent** [comment]
ci:test:sf

**Comment by wincent** [comment]
ci:test:bundle

**Comment by eduardoallegrini** [comment]
@atjuan what do you think about this?

**Comment by marcoscv-work** [comment]
I think this is a really heavy UX change.
Personally I think it opens the door to possible new errors and new unexpected behaviors, for example:

- If you are in a widget page and you open the product menu and press in the eye icon (hide/show controls) you cannot see the changes
- If you open the product menu and then open the application menu. ¿What should happen? the last one has the preference?, you can open a layer over a layer?
- The product menu icon does not provide the info about you are going to hide or show the product menu so by using the keyboard we need a close button.

I would choose to add a close button.

**Comment by eduardoallegrini** [comment]
You are probably right, I tried to specify the breakpoint to make it the least painful possible but as you said, there are things we are not accounting. So, since this is a @liferay-echo module and the FP is now 2, I'm going to close this and assign the ticket to them

**Pull request closed without merging**
