### PR TITLE
LRQA-64994 | Replace wait for metal component card macro usage with alternatives

### PR DESCRIPTION
**Pull request by john-co**
**Description**
This replaces the MetalComponent.waitForCard macro to fix tests that are pausing for 30 seconds. 

This macro isn’t functioning correctly any more. The metal component macro is supposed to get the id of an element and pass that along to be identified in the Liferay.component() function in the DOM. The card for Sites doesn’t have an id so it waits 30 seconds by default to finish through the while loop. This is a workaround until we can identify if it's still possible to still use Lifray.component() for this usecase or better solution.

**Test Plan**
- :heavy_check_mark: Validate ci tests pass and tests don't hang when selecting site card. Passes in https://github.com/john-co/liferay-portal/pull/381#issuecomment-781678364
- :heavy_check_mark: Validate ci tests pass where MetalComponent.waitForCard is replaced. Passes in https://github.com/john-co/liferay-portal/pull/381#issuecomment-781678364

**Ticket**
https://issues.liferay.com/browse/LRQA-64994

### CODE REVIEW

**Comment by jbalsas** [comment]
Hey @john-co, as far as I can tell these cards don't have an `id` which would make the macro fail to locate anything at all in

> MetalComponent.waitForMetalComponent(id = selenium.getAttribute("//div[contains(@class,'card')][contains(.,'${card}')]@id"));

You should be able to verify this by adding an `id="something"` attribute to the `card` in `site-admin-web/select_site_initializer.jsp` for example. It's possible that we were auto-generating some id's based on some other attributes, so it would be interesting to understand what changed to make sure it was a desired change.

The querying mechanism could also be improved to use `Liferay.componentReady` instead of a polling mechanism. Again, this depends on the components being identifiable, which they are not if they are not given a unique `id`.

@wincent, just bringing this to your attention, as we're moving more components into React, I think it's going to become increasingly hard for CI to know when everything is ready to be inspected and interacted with... not sure if we could/would want to signal this somehow... 🤔

**Comment by wincent** [comment]
> @wincent, just bringing this to your attention, as we're moving more components into React, I think it's going to become increasingly hard for CI to know when everything is ready to be inspected and interacted with... not sure if we could/would want to signal this somehow... 🤔

Indeed, although this "wait for last" hack is pretty clean as far as hacks go:

```
function waitForLastScript {
	selenium.waitForElementPresent("xpath=(//script)[last()]");
}
```

I don't have any bright ideas about the generating predictable identities for React components yet.

**Comment by wincent** [comment]
Ok, so it seems we have some follow-up to do here:

> It's possible that we were auto-generating some id's based on some other attributes, so it would be interesting to understand what changed to make sure it was a desired change.

But the PR works around a real problem (tests that are pausing for 30 seconds), so it seems appropriate to forward it to at least stop the bleeding while we do the deeper analysis. So the ticket should probably stay open, but I think we can forward the PR in the meantime.

I know the risk is that we forward it and then fail to do the follow-up, but I'm looking at our 21-deep PR queue right now and I am keen to reduce it a little bit. I gather @john-co may need some eng support from us in order to get to the bottom of what has changed here, so that might take a while, and this PR might otherwise end up hanging around here for days getting stale, so I thinking forwarding is a reasonable interim step. cc @manoelcyreno just so it's on your radar too.

**Comment by wincent** [comment]
ci:forward

**Pull request closed without merging**
