### PR TITLE
LPS-118408 Final Visual/Layout Improvements for Application Menu

### PR DESCRIPTION
**Pull request by carloslancha**
https://issues.liferay.com/browse/LPS-118408

Done:
- Changed "Sites" for "Environments" at the menu top area
- Added Virtual Instance section inside Environments area.
- Removed "Powered by Liferay"

TODO:
- In the bottom left corner of the apps menu it should appear the DXP Logo + Liferay DXP in DXP version or the CE Liferay Logo + Liferay for CE version. JS component is prepared to render it as it should be but backend (`ApplicationsMenuDisplayContext.java`) needs to be updated to pass the correct values for `liferayLogoURL` and `liferayName`.

image

### CODE REVIEW

**Comment by carloslancha** [comment]
@liferay-echo could you please take a look at how to implement this?
> In the bottom left corner of the apps menu it should appear the DXP Logo + Liferay DXP in DXP version or the CE Liferay Logo + Liferay for CE version. JS component is prepared to render it as it should be but backend (ApplicationsMenuDisplayContext.java) needs to be updated to pass the correct values for liferayLogoURL and liferayName.

Thx!

**Comment by jbalsas** [comment]
Why don't you send this directly to @liferay-echo? Then they can move it forward as they see fit :)

[just saying...]

**Comment by carloslancha** [comment]
For you guys to review it @jbalsas ;)

**Comment by jbalsas** [comment]
Hey @carloslancha, looks good to me... superficially :)

Could you squash https://github.com/liferay-frontend/liferay-portal/pull/309 and cherry-pick it on top of this so we can send a single PR with everything that's missing? that way we avoid conflicts and overhead and make sure it makes it in one piece.

**Comment by carloslancha** [comment]
Continue in https://github.com/liferay-frontend/liferay-portal/pull/322

**Pull request closed without merging**
