### PR TITLE
LPS-133224 Allow filtering object entries by object field values

### PR DESCRIPTION
**Pull request by javierdearcos**
I've added the nestedFieldArray logic inside the elasticSearch7 implementation following the same pattern that was used to allow sorting by object fields.

As this is an important portal future it makes sense to me to be considered in the core of the portal.

This way, the implementation of the rest of the modules is very clean.

Need to keep working in the rest of the filter types to be sure we give enough coverage to the existing cases

### CODE REVIEW

**Comment by nhpatt** [comment]
The implementation looks very clean, I'm worried about what it means when using the search API because we change the shape to our wishes... how would be a normal query after and before? you can capture real queries with a breakpoint and run them against the search endpoint like:

Nevertheless, send it to the search team to consider :)

```
## Request (2) Duplicate (2)
curl "http://localhost:9201/_search?pretty=true&size=1000" \
     -H 'Content-Type: application/json' \
     -H 'Cookie: JSESSIONID=D6DDA9A24144C6ECA271608846A09957' \
     -d $'{
  "from": 0,
  "sort": [
    {
      "entryClassPK": {
        "order": "asc",
        "unmapped_type": "keyword"
      }
    },
    {
      "entryClassPK_sortable": {
        "order": "asc",
        "unmapped_type": "keyword"
      }
    }
  ],
  "explain": false,
  "track_total_hits": 2147483647,
  "size": 2,
  "query": {
    "bool": {
      "adjust_pure_negative": true,
      "filter": [
        {
          "bool": {
            "must": [
              {
                "bool": {
                  "must": [
                    {
                      "terms": {
                        "groupId": [
                          "93160"
                        ],
                        "boost": 1
                      }
                    },
                    {
                      "terms": {
                        "scopeGroupId": [
                          "93160"
                        ],
                        "boost": 1
                      }
                    }
                  ],
                  "adjust_pure_negative": true,
                  "boost": 1
                }
              },
              {
                "bool": {
                  "boost": 1,
                  "should": [
                    {
                      "bool": {
                        "must_not": [
                          {
                            "exists": {
                              "field": "ctCollectionId",
                              "boost": 1
                            }
                          },
                          {
                            "term": {
                              "status": {
                                "value": "8",
                                "boost": 1
                              }
                            }
                          }
                        ],
                        "adjust_pure_negative": true,
                        "must": [
                          {
                            "term": {
                              "entryClassName": {
                                "value": "com.liferay.journal.model.JournalArticle",
                                "boost": 1
                              }
                            }
                          },
                          {
                            "term": {
                              "latest": {
                                "value": "true",
                                "boost": 1
                              }
                            }
                          }
                        ],
                        "boost": 1
                      }
                    }
                  ],
                  "adjust_pure_negative": true
                }
              }
            ],
            "adjust_pure_negative": true,
            "boost": 1
          }
        }
      ],
      "must": [
        {
          "bool": {
            "must": [
              {
                "bool": {
                  "adjust_pure_negative": true,
                  "filter": [
                    {
                      "bool": {
                        "must": [
                          {
                            "term": {
                              "localized_title_en_US_sortable": {
                                "value": "0wedvcvw",
                                "boost": 1
                              }
                            }
                          },
                          {
                            "term": {
                              "folderId": {
                                "value": "0",
                                "boost": 1
                              }
                            }
                          }
                        ],
                        "adjust_pure_negative": true,
                        "boost": 1
                      }
                    }
                  ],
                  "must": [
                    {
                      "bool": {
                        "must": [
                          {
                            "match_all": {
                              "boost": 1
                            }
                          }
                        ],
                        "adjust_pure_negative": true,
                        "boost": 1
                      }
                    }
                  ],
                  "boost": 1
                }
              }
            ],
            "adjust_pure_negative": true,
            "boost": 1
          }
        }
      ],
      "boost": 1
    }
  },
  "stored_fields": [
    "companyId",
    "entryClassPK",
    "rootEntryClassPK",
    "entryClassName",
    "scopeGroupId",
    "articleId"
  ]
}'

```

**Comment by nhpatt** [comment]
^Test are definitely related

**Comment by javierdearcos** [comment]
Thanks for pointing this out. I'll take a look at the failing tests and consequences in search requests

**Comment by javierdearcos** [comment]
Sent here to Search team to be analyzed
https://github.com/liferay-search/liferay-portal/pull/149

**Comment by javierdearcos** [comment]
Closing it as it was sent from https://github.com/BryanEngler/liferay-portal/pull/588

**Pull request closed without merging**
