### PR TITLE
[TS] LPS-134368 Add context path to handle custom context

### PR DESCRIPTION
**Pull request by diegonvs**
This PR came from https://github.com/liferay-frontend/liferay-portal/pull/1218

From @rolandpakai, 

```
Hi Team,

could you please check my fix.
Because of not handling the context path loading css fails.
Adding context path fix the issue.
```

### CODE REVIEW

**Comment by diegonvs** [comment]
"LPS-134368 Move getPathContext call to method" 🤦🏼 pushing force to update the commit title

**Comment by diegonvs** [comment]
``LPS-134368 Move getPathContext call to _getBackgroundImage method` looks better

**Comment by diegonvs** [comment]
ci:stop

**Comment by diegonvs** [comment]
ci:forward

**Comment by rolandpakai** [comment]
ci:test:relevant

**Comment by diegonvs** [comment]
ci:forward

**Pull request closed without merging**
