### PR TITLE
LPS-147945 Allow dropdown to receive clicks

### PR DESCRIPTION
**Pull request by victorg1991**
Related ticket: https://issues.liferay.com/browse/LPS-147945

This is caused by https://github.com/liferay-frontend/liferay-portal/pull/1918

This PR fixes a problem in which the menu display don't navigate to a child page when clicking in it.

Clay sets `pointer-events: none` to dropdown items with the active property. In the portal there is an ancient logic that when some element is focused the `active` class is added to that element. What happened is that when the click event is started, the dropdown item already had the active class and didn't receive any click event. This PR makes sure to not block this event with the pointers-none style.

@pat270 Not sure if we can move this to clay, but it was faster to add it here for now instead of waiting for a new clay release to be created. 

### How to reproduce it
- Add a new page
- Add a child page to the page
- Go to the child page through the menu display (the portlet that it included in the theme by default)

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by pat270** [comment]
@victorg1991 This is fine with me, I created an issue at https://github.com/liferay/clay/issues/4690

**Comment by victorg1991** [comment]
Hey @pat270 since this issue has _blocker_ potential, could we just pass this PR like this? It just involved one line of code. After that we can investigate the thing that you mentioned about changing active to focus. This is an ancient aui logic that I'm not sure if it will have any collateral effect :)

**Review by markocikos — APPROVED** [review]
LGTM!

**Comment by markocikos** [comment]
@pat270 you can have the final word to forward, or hold until this is fixed in Clay.

**Comment by john-co** [comment]
ci:forward

**Comment by john-co** [comment]
forwarding on @pat270 's behalf :)

**Comment by pat270** [comment]
Sorry I missed this! It's good with me.

**Pull request closed without merging**
