### PR TITLE
LPS-170037 Removed frontend taglibs CSS #2

### PR DESCRIPTION
**Pull request by edalgrin**
This PR is the second part of https://github.com/liferay-frontend/liferay-portal/pull/3035 and it removes CSS classes from deprecated taglibs in https://issues.liferay.com/browse/LPS-170037

### CODE REVIEW

**Comment by dsanz** [comment]
ci:reevaluate:1297401_6499

**Comment by dsanz** [comment]
ci:reevaluate:1297401_6499

**Comment by dsanz** [comment]
ci:reevaluate:1297401_6499

**Comment by deborasoliveira** [comment]
@dsanz I'll take a look at it.

**Comment by deborasoliveira** [comment]
According to the [comparison](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=2&testrayRunIdB=2217203121&testrayRunIdA=2217658160&statusB=3), the failures are not related to the PR. 
WorkflowMetrics#ViewReports test failed before being executed on the routine, but it passes when I execute it on PR bundle, so it seems like a CI execution problem. 

cc: @mateusralv

**Comment by deborasoliveira** [comment]
According to the [comparison](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=2&testrayRunIdB=2217203121&testrayRunIdA=2217658160&statusB=3), the failures are not related to the PR.
WorkflowMetrics#ViewReports test failed before being executed on the routine, but it passes when I execute it on PR bundle, so it seems like a CI execution problem.

cc: @mateusralv

**Comment by dsanz** [comment]
ci:forward:force

**Pull request closed without merging**
