### PR TITLE
LPD-43376 - Use correct japanese word for sorting order

### PR DESCRIPTION
**Pull request by juanjofgliferay**
https://liferay.atlassian.net/browse/LPD-43376

### CODE REVIEW

**Review by markocikos — APPROVED** [review]
@juanjofgliferay LGTM! :sparkles:

**Comment by juanjofgliferay** [comment]
ci:forward

**Comment by juanjofgliferay** [comment]
ci:test:relevant

**Comment by juanjofgliferay** [comment]
ci:test:sf

**Comment by juanjofgliferay** [comment]
ci:forward

**Comment by juanjofgliferay** [comment]
ci:forward

**Comment by markocikos** [comment]
ci:forward

**Comment by markocikos** [comment]
ci:forward

**Pull request closed without merging**
