### PR TITLE
[TS] LPS-139932 - Move list title to an upper level 

### PR DESCRIPTION
**Pull request by georgel-pop-lr**
[LPS-139932](https://issues.liferay.com/browse/LPS-139932) Move list title to an upper level in order to respect this accessibility criteria 1.3.1 Info and Relationships, 2.4.6 Headings and Labels

Example nested List:
```
<ul>
    <li>
        Fruit
        <ul>
            <li>Apple</li>
            <li>Pear</li>
            <li>Organge</li>
        </ul>
    </li>
</ul>
```

### CODE REVIEW

**Comment by diegonvs** [comment]
Hey @georgel-pop-lr, could you provide for these specs?

Also, could be useful a recording or a screenshot for your change

**Comment by pat270** [comment]
This pr will probably break the layout. Is it possible to use https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dl instead of unordered list?

**Comment by georgel-pop-lr** [comment]
> This pr will probably break the layout. Is it possible to use https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dl instead of unordered list?

Hi @pat270 @diegonvs,

Actually is not breaking anything, everything looks and behave like before.

Before picture:
image

After picture:
image

I think this is a good solution and not doing an entire change and use dl elements that could break the layout entirely.

Best regards.

**Comment by pat270** [comment]
In the original picture, there is a 1px border between `list-group-header` and `list-group-item`. The after picture shows a 2px border. There are probably `border-radius` issues between header and item, but you can't see it in the screenshot.

The margin at the bottom of the component will be doubled due to two `list-group` classes.

**Comment by georgel-pop-lr** [comment]
> fter picture sh

Hi @pat270,

Looking more carefully, you are right.

Can you exemplify how this list would look like with dl? 

Also, what do you mean by using div, removing the entire list? 

Regards.

**Comment by pat270** [comment]
Undo your commit and change:
|old|new|
|----|----|
|ul.list-group|dl.list-group|
|li.list-group-header|dt.list-group-header|
|li.list-group-item|dd.list-group-item|

or

|old|new|
|----|----|
|ul.list-group|div.list-group|
|li.list-group-header|h#.list-group-header / div.list-group-header|
|li.list-group-item|div.list-group-item|

**Comment by georgel-pop-lr** [comment]
> Undo your commit and change:
> 
> old	new
> ul.list-group	dl.list-group
> li.list-group-header	dt.list-group-header
> li.list-group-item	dd.list-group-item
> or
> 
> old	new
> ul.list-group	div.list-group
> li.list-group-header	h#.list-group-header / div.list-group-header
> li.list-group-item	div.list-group-item

Thanks @pat270,

It was working, please review.

Regards.

**Comment by pat270** [comment]
LGTM

**Review by diegonvs — APPROVED** [review]

**Comment by diegonvs** [comment]
ci:forward

**Comment by diegonvs** [comment]
ci:forward

**Comment by georgel-pop-lr** [comment]
ci:forward

**Comment by georgel-pop-lr** [comment]
> ci:forward

Hi @diegonvs,

Could we get some help forwarding this?

Thanks.

**Comment by john-co** [comment]
Just started reviewing :)

**Comment by john-co** [comment]
seems like `ul` and `li` tags are modified to `dd` and `dl`
screenshot_16

**Comment by john-co** [comment]
So looks intentional from: https://github.com/liferay-frontend/liferay-portal/pull/1640#issuecomment-965457702

I'll try an initial test fix and see what else we need to clean up.

**Comment by john-co** [comment]
My initial estimate is that the test fixes may take about a week to fully refactor tests affected depending on how widespread the change is and how many variant xpaths product teams are using...could be quicker or longer. Are we ok with this timeframe @georgel-pop-lr ? Are we able to follow up with the dl dd tags in a different ticket/PR?

**Comment by john-co** [comment]
Testing Test Fix in: https://github.com/john-co/liferay-portal/pull/442

**Comment by georgel-pop-lr** [comment]
> My initial estimate is that the test fixes may take about ~a week~ 2 to 3 days to fully refactor tests affected depending on how widespread the change is and how many variant xpaths product teams are using...could be quicker or longer. I'll have a better idea after first run at the test fix. Are we ok with this timeframe @georgel-pop-lr ? Something to consider, are we able to follow up with the dl dd tags in a different ticket/PR?

Hi @john-co,

No problem with waiting one week, the client has already the patch as it is not needed to update tests on the patcher.

My question is when I backport to 7.3.x and 7.2.x, would this test work for each branch, or we require checking each individually? 

Best regards.

**Comment by john-co** [comment]
> My question is when I backport to 7.3.x and 7.2.x, would this test work for each branch, or we require checking each individually?

The testfixes with the backport will probably fix most of the tests in legacy branches. But I'd want to be thorough with double checking and fixing the tests similar to the process I'm doing right now. If the leftover fixes aren't too bad, I might be able to ask our legacy QA to work on fixing the remaining tests in 7.3.x and 7.2.x.

**Comment by john-co** [comment]
Hi @georgel-pop-lr , I don't think I can finish the test fixes this week and I'll be off all of next week. I can continue with this the following week when I return but if need to expedite, please ask @zhangyan0701.

So far found 1 regression:
https://github.com/john-co/liferay-portal/pull/442#issuecomment-971937979

**Comment by georgel-pop-lr** [comment]
> Hi @georgel-pop-lr , I don't think I can finish the test fixes this week and I'll be off all of next week. I can continue with this the following week when I return but if need to expedite for some reason, please ask @zhangyan0701.
> 
> So far found 1 regression: [john-co#442 (comment)](https://github.com/john-co/liferay-portal/pull/442#issuecomment-971937979)

Hi @john-co,

No problem, I understand there are lots of changes. Let me know when you are done.

I will check the bug you found and see why is this happening.

Regards.

**Comment by john-co** [comment]
Just started reviewing :)

**Comment by john-co** [comment]
Can you invite me as github collaborator to your repo @georgel-pop-lr ? That way I can push in test fix commits directly to this PR.

**Comment by georgel-pop-lr** [comment]
> g you mentio

Hi @john-co,

Sure, I don't mind doing that, but as you need always this rights on liferay-frontend PR's why not trying to add you on to write permissions group for this specific repo.

image


@nhpatt Do you know if we can give him write access to this user? 

Regards.

**Comment by markocikos** [comment]
@georgel-pop-lr Collaborator are pushing to PR branches on your fork. Only you can enable collaborators on your fork, https://github.com/georgel-pop-lr/liferay-portal/settings/access

**Comment by georgel-pop-lr** [comment]
> Can you invite me as github collaborator to your repo @georgel-pop-lr ? That way I can push in test fix commits directly to this PR.

Hi @john-co,

I have invited you as collaborator.

Let me know if anything else is needed.

Regards.

**Comment by john-co** [comment]
I force pushed the test fixes to this PR. I also squashed @zhangyan0701 's [test fix](https://github.com/zhangyan0701/liferay-portal/pull/319) as well into my last commit. 

@zhangyan0701 found a couple related regressions detailed in https://github.com/john-co/liferay-portal/pull/442#issuecomment-984601050, could you take a look @georgel-pop-lr?

Let's run another `ci:test:upstream-functional` when regressions are fixed and evaluate remaining tests are fine.

**Comment by georgel-pop-lr** [comment]
> I force pushed the test fixes to ~this PR~ your branch. I also squashed @zhangyan0701 's [test fix](https://github.com/zhangyan0701/liferay-portal/pull/319) as well into my last commit.
> 
> @zhangyan0701 found a couple related issues detailed in [john-co#442 (comment)](https://github.com/john-co/liferay-portal/pull/442#issuecomment-984601050), could you take a look @georgel-pop-lr?
> 
> Let's run another `ci:test:upstream-functional` when issues are fixed and evaluate remaining tests are fine.

Hi,

Thanks for helping, I will have a look on these regressions.

Once I get any updates, I will let you know.

Regards.

**Comment by georgel-pop-lr** [comment]
ci:test:sf

**Comment by georgel-pop-lr** [comment]
ci:test:sf

**Comment by georgel-pop-lr** [comment]
ci:test:upstream-functional

**Comment by georgel-pop-lr** [comment]
ci:test:relevant

**Comment by georgel-pop-lr** [comment]
> > I force pushed the test fixes to ~this PR~ your branch. I also squashed @zhangyan0701 's [test fix](https://github.com/zhangyan0701/liferay-portal/pull/319) as well into my last commit.
> > @zhangyan0701 found a couple related issues detailed in [john-co#442 (comment)](https://github.com/john-co/liferay-portal/pull/442#issuecomment-984601050), could you take a look @georgel-pop-lr?
> > Let's run another `ci:test:upstream-functional` when issues are fixed and evaluate remaining tests are fine.
> 
> Hi,
> 
> Thanks for helping, I will have a look on these regressions.
> 
> Once I get any updates, I will let you know.
> 
> @john-co Update: I have pushed [1f53a1b](https://github.com/liferay-frontend/liferay-portal/commit/1f53a1b0145e109fae38956394ae73bb7a59ce0e) that should fix the regressions found
> 
> Let me know if anything is needed after we run tests again.
> 
> Regards.

Hi @john-co,

Any news regarding this pull, we still need to update tests paths?

Regards.

**Comment by georgel-pop-lr** [comment]
Hi @magjed4289,

I did a rebase of this PR with the latest changes on master, let me know if anything else is needed.

Regards.

**Comment by magjed4289** [comment]
ci:test:upstream-functional

**Comment by magjed4289** [comment]
ci:test:stable

**Comment by magjed4289** [comment]
ci:test:relevant

**Comment by magjed4289** [comment]
qa analysis retaken by @sergiojimcos

**Comment by sergiojimcos** [comment]
ci:test:stable

**Comment by sergiojimcos** [comment]
ci:test:relevant

**Comment by sergiojimcos** [comment]
Thanks to the help of @magjed4289 comparing Georgel relevant's with master I could see most of the tests that have failed are related to a modification in PageEditor. It is related to a component that visualize which Collection Display we have selected (See in video). As I told to @georgel-pop-lr, it is solved in master but in his bundle not yet and could be a change that have't been rebased. For that reason, we will see what happen when this PR are updated as master

**Comment by sergiojimcos** [comment]
This is in master:

https://user-images.githubusercontent.com/44723449/147084583-a3b6028d-2af3-4f18-b5b2-b470c91c580a.mp4

And this with this bundle:


https://user-images.githubusercontent.com/44723449/147084704-9705696f-2460-4eeb-b8a1-7f74a25c7b83.mov

**Comment by sergiojimcos** [comment]
I'm going to check what's wrong and why test:relevant doesn't passed

**Comment by sergiojimcos** [comment]
As I could see, there is a problem related to these tests:

- LocalFile.VisualizeObjectCollectionDisplay#CanDisplayEntriesOnTableFormat
- LocalFile.VisualizeObjectCollectionDisplay#ObjectEntriesAreRendered
- LocalFile.VisualizeObjectCollectionDisplay#CanDisplayEntriesOnTableFormat

Each of them doesn't visualize the component that allows to indicate which element are imported in the Page Editor. It is similar to tests that have failed previously

Previously, they are solved in this ticket: https://issues.liferay.com/browse/LRQA-70740

This is the video:

https://user-images.githubusercontent.com/44723449/147120007-32122727-8a72-4a11-a2a6-bfb32d8130a9.mov

**Comment by georgel-pop-lr** [comment]
ci:test:sf

**Comment by georgel-pop-lr** [comment]
ci:test:relevant

**Comment by georgel-pop-lr** [comment]
> As I could see, there is a problem related to these tests:
> 
> * LocalFile.VisualizeObjectCollectionDisplay#CanDisplayEntriesOnTableFormat
> * LocalFile.VisualizeObjectCollectionDisplay#ObjectEntriesAreRendered
> * LocalFile.VisualizeObjectCollectionDisplay#CanDisplayEntriesOnTableFormat
> 
> Each of them doesn't visualize the component that allows to indicate which element are imported in the Page Editor. It is similar to tests that have failed previously
> 
> Previously, they are solved in this ticket: https://issues.liferay.com/browse/LRQA-70740
> 
> This is the video:
> 
>  Screen.Recording.2021-12-22.at.16.55.05.mov

Hi @sergiojimcos,

I did push a change that should fix this regression, I run again the tests, please review when you can.

Regards.

**Comment by sergiojimcos** [comment]
Starting reviewing :)

**Comment by sergiojimcos** [comment]
Hi @georgel-pop-lr, as I saw in the Testray report there are 5 failed tests and these are unrelated. One of them is related to Outh2 test but there is not any reference with your changes.

**Comment by georgel-pop-lr** [comment]
> > ```
> > 						<h1>Unable to generate test report.</h1><p>Jenkins encountered the following error while generating test report:</p><pre><code>Sourced file: inline evaluation of: `` 						 							import com.liferay.jenkins.results.parser.Build; 							import co . . . '' : TargetError : at Line: 48 : in file: inline evaluation of: `` 						 							import com.liferay.jenkins.results.parser.Build; 							import co . . . '' : throw e ; 
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Target exception: java.lang.NullPointerException
> > #### Base Branch:
> > Branch Name: [master](https://github.com/liferay/liferay-portal/tree/master)
> > Branch GIT ID: [adad0cb6aa43de2f43ef918b322072c23b4155ff](https://github.com/liferay/liferay-portal/commit/adad0cb6aa43de2f43ef918b322072c23b4155ff)
> > #### Job Summary:
> > Job Link: [test-portal-acceptance-pullrequest(master)](https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest(master)/1160/)
> > For more details click [here](https://test-1-29.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/1160/jenkins-report.html).
> > ##### Test bundle downloads:
> > 
> > * [liferay-portal-bundle-tomcat.tar.gz](https://files.liferay.com/private/bundles/test-1-29/jobs/test-portal-acceptance-pullrequest(master)/builds/1160/liferay-portal-bundle-tomcat.tar.gz) (mirrors: [dlc](http://mirrors.dlc.liferay.com/files.liferay.com/private/bundles/test-1-29/jobs/test-portal-acceptance-pullrequest(master)/builds/1160/liferay-portal-bundle-tomcat.tar.gz), [lax](http://mirrors.lax.liferay.com/files.liferay.com/private/bundles/test-1-29/jobs/test-portal-acceptance-pullrequest(master)/builds/1160/liferay-portal-bundle-tomcat.tar.gz))

**Comment by georgel-pop-lr** [comment]
> Hi @georgel-pop-lr, as I saw in the Testray report there are 5 failed tests and these are unrelated. One of them is related to Outh2 test but there is not any reference with your changes.

Hi @sergiojimcos,

So you think we can forward this PR?

Regards.

**Comment by sergiojimcos** [comment]
> > Hi @georgel-pop-lr, as I saw in the Testray report there are 5 failed tests and these are unrelated. One of them is related to Outh2 test but there is not any reference with your changes.
> 
> Hi @sergiojimcos,
> 
> So you think we can forward this PR?
> 
> Regards.



> > > ```
> > > 						<h1>Unable to generate test report.</h1><p>Jenkins encountered the following error while generating test report:</p><pre><code>Sourced file: inline evaluation of: `` 						 							import com.liferay.jenkins.results.parser.Build; 							import co . . . '' : TargetError : at Line: 48 : in file: inline evaluation of: `` 						 							import com.liferay.jenkins.results.parser.Build; 							import co . . . '' : throw e ; 
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Target exception: java.lang.NullPointerException
> > > #### Base Branch:
> > > Branch Name: [master](https://github.com/liferay/liferay-portal/tree/master)
> > > Branch GIT ID: [adad0cb6aa43de2f43ef918b322072c23b4155ff](https://github.com/liferay/liferay-portal/commit/adad0cb6aa43de2f43ef918b322072c23b4155ff)
> > > #### Job Summary:
> > > Job Link: [test-portal-acceptance-pullrequest(master)](https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest(master)/1160/)
> > > For more details click [here](https://test-1-29.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/1160/jenkins-report.html).
> > > ##### Test bundle downloads:
> > > 
> > > * [liferay-portal-bundle-tomcat.tar.gz](https://files.liferay.com/private/bundles/test-1-29/jobs/test-portal-acceptance-pullrequest(master)/builds/1160/liferay-portal-bundle-tomcat.tar.gz) (mirrors: [dlc](http://mirrors.dlc.liferay.com/files.liferay.com/private/bundles/test-1-29/jobs/test-portal-acceptance-pullrequest(master)/builds/1160/liferay-portal-bundle-tomcat.tar.gz), [lax](http://mirrors.lax.liferay.com/files.liferay.com/private/bundles/test-1-29/jobs/test-portal-acceptance-pullrequest(master)/builds/1160/liferay-portal-bundle-tomcat.tar.gz))
> 
> Hi @sergiojimcos,
> 
> What about this error?
> 
> Regards.

This is something that I haven't seen before. Let me check it!

**Comment by sergiojimcos** [comment]
ci:test:acceptance-functional

**Comment by sergiojimcos** [comment]
Hi @georgel-pop-lr! According what I have told you yesterday about NullPointerException, when a relevant test is executed it appears also in other PR. For that reason, I think it is not related to your changes, it is related to CI. From now I have more details about what is failing, let's start!

**Comment by sergiojimcos** [comment]
According to the new Testray report, I could see that all the test that fails are unrelated due to some aspects:

- Some of them are related to **Analytics Cloud**.
- There are several test that must be fixed related to other teams.

From my point of view, it could be forwarded!

**Comment by georgel-pop-lr** [comment]
> According to the new Testray report, I could see that all the test that fails are unrelated due to some aspects:
> 
> * Some of them are related to **Analytics Cloud**.
> * There are several test that must be fixed related to other teams.
> 
> From my point of view, it could be forwarded!

Hi @diegonvs,

Could you please have another look and forward this if you feel like everything is okay?

Regards.

**Comment by diegonvs** [comment]
ci:forward

**Comment by diegonvs** [comment]
ci:forward

**Comment by diegonvs** [comment]
ci:forward

**Comment by diegonvs** [comment]
One last try, I'll forward manually if the unrelated failures continues

**Comment by john-co** [comment]
ci:test:upstream-functional

**Comment by john-co** [comment]
We should also re-evaluate the results from `ci:test:upstream-functional` since this PR has been on hold for so long since that test suite was run/evaluated. I'm concerned since this is a widespread change and we've seen a number of related test failures. Past analysis only involved `ci:test:acceptance-functional` which is a smaller amount of tests.

@zhangyan0701 could you re-evaluate and manually forward if looks ok?

**Comment by georgel-pop-lr** [comment]
> We should also re-evaluate the results from `ci:test:upstream-functional` since this PR has been on hold for so long since that test suite was run/evaluated. I'm concerned since this is a widespread change and we've seen a number of related test failures. Past analysis only involved `ci:test:acceptance-functional` which is a smaller amount of tests.
> 
> @zhangyan0701 could you re-evaluate and manually forward if looks ok?

Ok @john-co, we will wait for the results.

Regards.

**Comment by zhangyan0701** [comment]
No regressions found. But there are still several tests failed due to xpath change. Seems like they failed to run in previous jobs in this PR. I am now working on a fix.

**Comment by georgel-pop-lr** [comment]
> No regressions found. But there are still several tests failed due to xpath change. Seems like they failed to run in previous jobs in this PR. I am now working on a fix.

Thanks @zhangyan0701

**Comment by zhangyan0701** [comment]
Hi @georgel-pop-lr 

I send you the fix here: https://github.com/georgel-pop-lr/liferay-portal/pull/25 as I cannot push my commit directly to you branch. Could you cherry-pick my fix?

There are some tests wasn't running, I checked them locally, no related issues found. So I think this PR can be forwarded.

**Comment by georgel-pop-lr** [comment]
> Hi @georgel-pop-lr
> 
> I send you the fix here: [georgel-pop-lr#25](https://github.com/georgel-pop-lr/liferay-portal/pull/25) as I cannot push my commit directly to your branch. Could you cherry-pick my fix?
> 
> And there are some tests failed to run in the most recently job, I checked them locally, no related issues found. So I think this PR can be forwarded.

Hi @zhangyan0701,

I cherry-picked https://github.com/liferay-frontend/liferay-portal/pull/1640/commits/f0bf14d43d25d327d9f1585167ba85962cc01b50 please confirm everything is in place. 

Should we run again the tests?

Regards.

**Comment by georgel-pop-lr** [comment]
ci:test:sf

**Comment by john-co** [comment]
ci:test:upstream-functional

**Comment by john-co** [comment]
cc/ @zhangyan0701 thanks for the past analysis and fix. Please double check and manually forward if this PR looks good :)

**Comment by zhangyan0701** [comment]
> cc/ @zhangyan0701 thanks for the past analysis and fix. Please double check and manually forward if this PR looks good :)

I will check the new results.

**Comment by zhangyan0701** [comment]
The results look good, no related failures found, and no more test fixes needed.

Manually forwarded, please see https://github.com/brianchandotcom/liferay-portal/pull/111939.

So closed this one.

**Pull request closed without merging**
