### PR TITLE
LPD-20691 This was added because IE11 was unable to handle more than one favicon with SPA

### PR DESCRIPTION
**Pull request by antonio-ortega**
Hey,

This was added [here](https://github.com/liferay/senna.js/issues/285) due to IE 11 support, so I think it's safe to get rid of it now.

Thanks.

Regards.

### CODE REVIEW

**Comment by antonio-ortega** [comment]
ci:test:relevant

**Review by markocikos — APPROVED** [review]
@antonio-ortega LGTM! :sparkles:

**Review by bryceosterhaus — APPROVED** [review]
fire-flames-gif

**Comment by antonio-ortega** [comment]
ci:test:relevant

**Comment by antonio-ortega** [comment]
ci:forward

**Comment by antonio-ortega** [comment]
ci:forward

**Comment by markocikos** [comment]
ci:forward

**Comment by antonio-ortega** [comment]
ci:forward:force

**Comment by antonio-ortega** [comment]
Manually forwarded https://github.com/brianchandotcom/liferay-portal/pull/148432

**Pull request closed without merging**
