### PR TITLE
LPS-144832 - Add selectedLanguageIdAtom and use it in input_localized 

### PR DESCRIPTION
**Pull request by tinycarol**
### References

- [LPS-144832](https://issues.liferay.com/browse/LPS-144832)

### What is the goal?

* Add `selectedLanguageIdAtom` to share state between localized React and tag components.

### What does it look like?

https://user-images.githubusercontent.com/6642927/152391083-995568ea-b2d7-481a-8252-19a6bbddcc0b.mov

### How to replicate
* Launch portal
* Deploy `frontend-js-components-sample-web` (I don't think this should be necessary, but otherwise the sample widget wasn't appearing for me, even after an `ant all` 🤷‍♀️) 
   * `cd {PORTAL_ROOT}/modules/apps/frontend-js/frontend-js-components-sample-web`
   * `gradlew clean deploy`
* Edit the Home page
* Add the `JS Components Sample` widget from the fragments and widget side bar 
* Save, go to home page
* See that if you select a language in the `React Component`, `AUI Tag` or `Liferay UI Tag`, the language changes in all other elements

### CODE REVIEW

**Comment by tinycarol** [comment]
ci:test:sf

**Comment by tinycarol** [comment]
ci:test:relevant

**Comment by tinycarol** [comment]
@liferay-continuous-integration me quitas las ganas de vivir

**Comment by tinycarol** [comment]
ci:test:relevant

**Comment by carloslancha** [comment]
ci:forward

**Pull request closed without merging**
