### PR TITLE
LPS-149534 Date filter in FDS sample module is not working

### PR DESCRIPTION
**Pull request by beltranrengifo**
[Jira ticket](https://issues.liferay.com/browse/LPS-149534)

## Steps to reproduce:

1. Place FDS sample module on a page
2. Choose any values on the 'Date Range' filter

## Expected results:

- Data is filtered withing set range
- Filters bar appears

## What actually happens:

- FDS disappears from UI
- Error 400 request, returning

### CODE REVIEW

**Comment by beltranrengifo** [comment]
Hi @markocikos !
As you said, I'm not been able to manage the server error, but just controlling the FE not to break.
I'll wait for a backend peer

**Review by markocikos — COMMENTED** [review]
@beltranrengifo The changes look good to me! They could normally be sent alongside the main issue fix, but we don't know when this will be. It may make sense that you open a new ticket, and resend under it. Something like `Improve failure handling of FDS filters update`.

**Comment by beltranrengifo** [comment]
> @beltranrengifo The changes look good to me! They could normally be sent alongside the main issue fix, but we don't know when this will be. It may make sense that you open a new ticket in the epic, and resend under it. Something like `Improve failure handling of FDS filters update`.

Good! Let's wait for a couple of days, now that Dani has taken a look at the problem. If the backend side does not progress I'll send this fix under other LPS

**Comment by beltranrengifo** [comment]
ci:close

**Pull request closed without merging**
