### PR TITLE
[WIP][7.4+] LPS-134071 Migrate frontend-theme-styled CSS

### PR DESCRIPTION
**Pull request by edalgrin**
WIP

Changed modules:
- modules/apps/adaptive-media/adaptive-media-web/
- modules/apps/announcements/announcements-web/
- modules/apps/asset/asset-publisher-web/
- modules/apps/asset/asset-taglib/
- modules/apps/batch-planner/batch-planner-web/
- modules/apps/blogs/blogs-web/
- modules/apps/calendar/calendar-web/
- modules/apps/commerce/commerce-address-web/
- modules/apps/commerce/commerce-availability-estimate-web/
- modules/apps/commerce/commerce-currency-web/
- modules/apps/commerce/commerce-frontend-impl/
- modules/apps/commerce/commerce-order-web/
- modules/apps/commerce/commerce-product-asset-categories-navigation-web/
- modules/apps/commerce/commerce-product-content-web/
- modules/apps/commerce/commerce-product-measurement-unit-web/
- modules/apps/commerce/commerce-product-options-web/
- modules/apps/commerce/commerce-product-tax-category-web/
- modules/apps/commerce/commerce-product-type-grouped-web/
- modules/apps/commerce/commerce-product-type-virtual-order-content-web/
- modules/apps/commerce/commerce-shipment-content-web/
- modules/apps/commerce/commerce-warehouse-web/
- modules/apps/commerce/commerce-wish-list-web/
- modules/apps/contacts/contacts-web/
- modules/apps/digital-signature/digital-signature-web/
- modules/apps/dispatch/dispatch-web/
- modules/apps/document-library/document-library-web/
- modules/apps/dynamic-data-lists/dynamic-data-lists-web/
- modules/apps/dynamic-data-mapping/dynamic-data-mapping-data-provider-web/
- modules/apps/dynamic-data-mapping/dynamic-data-mapping-form-field-type/
- modules/apps/dynamic-data-mapping/dynamic-data-mapping-form-web/
- modules/apps/dynamic-data-mapping/dynamic-data-mapping-service/
- modules/apps/dynamic-data-mapping/dynamic-data-mapping-web/
- modules/apps/frontend-css/frontend-css-cadmin-web/
- modules/apps/frontend-editor/frontend-editor-ckeditor-web/
- modules/apps/frontend-js/frontend-js-aui-web/
- modules/apps/frontend-js/frontend-js-spa-web/
- modules/apps/frontend-theme/frontend-theme-styled/
- modules/apps/frontend-theme/frontend-theme-unstyled/
- modules/apps/journal/journal-content-web/
- modules/apps/knowledge-base/knowledge-base-web/
- modules/apps/message-boards/message-boards-web/
- modules/apps/object/object-web/
- modules/apps/portal-rules-engine/portal-rules-engine-sample-web/
- modules/apps/redirect/redirect-web/
- modules/apps/translation/translation-web/
- modules/apps/users-admin/users-admin-web/
- modules/dxp/apps/commerce/commerce-machine-learning-forecast-alert-web/
- modules/dxp/apps/portal-security-audit/portal-security-audit-web/
- modules/dxp/apps/portal-workflow/portal-workflow-kaleo-forms-web/
- modules/sdk/gradle-plugins-css-builder/
- portal-web/

### CODE REVIEW

**Comment by edalgrin** [comment]
ci:test:sf

**Comment by edalgrin** [comment]
ci:test:sf

**Comment by edalgrin** [comment]
ci:test:sf

**Comment by edalgrin** [comment]
ci:test:sf

**Comment by edalgrin** [comment]
ci:test:sf

**Comment by edalgrin** [comment]
ci:test:sf

**Comment by edalgrin** [comment]
ci:test:sf

**Comment by edalgrin** [comment]
image

**Comment by edalgrin** [comment]
ci:test:sf

**Comment by edalgrin** [comment]
ci:test:sf

**Comment by edalgrin** [comment]
ci:test:relevant

**Comment by sergiojimcos** [comment]
ci:test:stable

**Comment by sergiojimcos** [comment]
ci:test:relevant

**Comment by sergiojimcos** [comment]
Just starting reviewing :)

**Comment by sergiojimcos** [comment]
Just starting to review!

**Comment by sergiojimcos** [comment]
Hi @edalgrin! According to the new Testray I can determine the following:

- There are two flaky tests that are related to the Forms part. Those two tests are unrelated as they do not influence the changes you have made.
- There is another flaky test called **ObjectPortlet#CanAddEntryWithoutSelectingPicklist** which is also unrelated to your changes and runs without any problems locally.
- Finally I want you to take a look at the changes you have made in the **Workflow** part as the tests don't pass correctly and don't run properly.

**Comment by sergiojimcos** [comment]
Hi @edalgrin! If there is not changes in `workflow-metrics`, you can forward manually as the rest of the failed tests are flaky ones.

**Comment by edalgrin** [comment]
https://github.com/liferay-frontend/liferay-portal/pull/1877

**Pull request closed without merging**
