### PR TITLE
LPS-132436 | master

### PR DESCRIPTION
**Pull request by john-co**
Original post from @kresimir-coko in https://github.com/liferay-data-engine/liferay-portal/pull/456#issue-651206975:

This is a part of an ongoing epic to replace legacy AUI-based modals with Clay/React-based `openSelectionModal`. We have previously migrated DDM modals, but we were not aware of openDDMPortlet utilily. This PR is a first part of the task that migrates openDDMPortlet related to structure, similar to what is being done with template .

I decided to have a granular approach with this task to make both working on it and reviewing easier. The other usages of openDDMPortlet in relation to structure are:

- `select_structure.jsp`
- `edit_structure.jsp`, which I'll start working now. Let me know if you want me to couple that one to this PR or to send a separate PR for that other modal.

# 🧪  Testing
Content & Data > Dynamic Data Lists
Open the Add new List page
Click on Select

### CODE REVIEW

**Comment by john-co** [comment]
ci:test:frontend

**Comment by john-co** [comment]
cc/ @kresimir-coko

**Comment by john-co** [comment]
cc/ @emanuelfisilva please see test fix for the regression from `ci:test:relevant`. I'm not sure if there are other tests that may be affected outside of relevant. https://github.com/liferay-data-engine/liferay-portal/pull/456#issuecomment-852191369

We can foward back to data engine for you to investigate any other fixes, if you feel there's no need then we can just forward from here.

**Comment by john-co** [comment]
Test Fix involves the ordering of the Add List Iframe and the Data Definitions Iframe within the html structure:

PR_selectDDMIframeIs2ndInHTML

Head_DataDefinitionIs1stIframe

Because the test is selecting the first IFrame to view in context, the test was passing in upstream b/c the Data Definition showed up higher in the HTML structure. But because the commits here cause the Data Definition element to come after Add List, it broke the poshi macro. The test fix now specifically looks for the `Data Definition` title IFrame.

cc/ @kresimir-coko

**Comment by john-co** [comment]
Could be a perceived regression on Iframe animation behavior, not sure if that's part of the epic scope or specific request by data engine team? cc/ @kresimir-coko @emanuelfisilva :

Upstream: immediately renders iframe

https://user-images.githubusercontent.com/35235266/120381101-dd81e700-c2d6-11eb-808e-be55d157c232.mp4

PR: delayed fly in animation rendered iframe

https://user-images.githubusercontent.com/35235266/120381102-de1a7d80-c2d6-11eb-90f4-875b4ab2ab47.mp4

**Comment by emanuelfisilva** [comment]
Hi @john-co , thanks so much for the detailed analysis and information.
For right now, I don't really believe any necessary effort would have to be made, thus, you can forward with this fix.

Thanks again!
cc: @guilhermedcamacho

**Comment by kresimir-coko** [comment]
@john-co 
> Could be a perceived regression on Iframe animation behavior, not sure if that's part of the epic scope or specific request by data engine team? cc/ @kresimir-coko @emanuelfisilva :

It's not part of the epic, and not specifically requested by the Data Engine team.

**Comment by markocikos** [comment]
@john-co The spinner is standard for `openSelectionModal` implementation. It does look faster than the upstream behavior, but that's a good thing :slightly_smiling_face:  . We improved the perceived behavior [a while back](https://issues.liferay.com/browse/LPS-118805).

> For right now, I don't really believe any necessary effort would have to be made, thus, you can forward with this fix.

@emanuelfisilva Sir, Yes, Sir!

**Comment by markocikos** [comment]
ci:forward

**Pull request closed without merging**
