### PR TITLE
LPS-179895 | Test Fix for FDSCustomView#CanBeSaved

### PR DESCRIPTION
**Pull request by abhnerramos**
**Description**
Element was not present in FDSCustomView#CanBeSaved.

**JIRA Ticket**
https://issues.liferay.com/browse/LPS-179895

### CODE REVIEW

**Comment by abhnerramos** [comment]
ci:stop

**Comment by abhnerramos** [comment]
ci:test:frontend

**Comment by abhnerramos** [comment]
ci:test:sf

**Comment by abhnerramos** [comment]
ci:test:frontend

**Comment by mateusralv** [comment]
ci:forward

**Pull request closed without merging**
