### PR TITLE
LPS-120103 Update the @clayui/multi-select package version to 3.7.0

### PR DESCRIPTION
**Pull request by matuzalemsteles**
In this version only contains the fix made in the PR https://github.com/liferay/clay/pull/3673, which fixes the ticket https://issues.liferay.com/browse/LPS-120103.

- Diff https://github.com/liferay/clay/pull/3674

### CODE REVIEW

**Comment by matuzalemsteles** [comment]
ci:test:sf

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
I don't think these are related... trying one last time just in case

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
No luck... forwarding manually

**Comment by jbalsas** [comment]
Forwarded https://github.com/brianchandotcom/liferay-portal/pull/93568

**Comment by matuzalemsteles** [comment]
Thanks @jbalsas!

**Pull request closed without merging**
