### PR TITLE
LPS-168960 | Created autom. test ClientExtensionIFrame#HasWidgetCategory

### PR DESCRIPTION
**Pull request by mateussandes23**
**Descitpion**
Create test for Client Extension

**Test Scenario**
- Given a Liferay DXP instance
- When access IFrame type client extension
- Then portal category "Client Extensions" is set by default

**JIRA Ticket**
- https://issues.liferay.com/browse/LPS-170582

cc/ @john-co @mateusralv

### CODE REVIEW

**Comment by eltonccdantas** [comment]
Hi @mateussandes23 , I've analyzed the errors and they look unrelated to your PR according to the [comparison](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1670445756369&testrayRunIdA=2106004744&testrayRunIdB=2108291516). You may manually forward if no other dev review is needed.

**Comment by john-co** [comment]
Just started reviewing :)

**Comment by john-co** [comment]
Hi @mateussandes23 , please remember to run the test locally and include the poshi report on the ticket and/or run a ci test suite that includes the new test. This helps the reviewer make sure that the test will pass ci.

**Comment by john-co** [comment]
ci:test:frontend-remote-apps:nocompile

**Comment by john-co** [comment]
ci:test:frontend-remote-apps:nocompile

**Comment by john-co** [comment]
Hi @mateussandes23 , please see changes in https://github.com/liferay-frontend/liferay-portal/pull/2896/commits/76e01bb13660722fb9af44039c01202924df534a We want to assert that the option is selected. If you AssertText, I think it will always pass the test even if a different option has been selected.

**Review by john-co — APPROVED** [review]
Refactored and approved. Thanks!

**Comment by john-co** [comment]
ci:test:sf

**Comment by mateusralv** [comment]
Hey @john-co These tests are depending on https://github.com/edalgrin/liferay-portal/pull/147, I think we can not forward direct because the commits of PR are here. We can add the committees with the test in the original PR. Or wait for it to merge, I can add if it sounds good to you.

**Comment by john-co** [comment]
Thanks @mateusralv , I'll cherry pick and push the test files to edu's PR.

**Pull request closed without merging**
