### PR TITLE
LPS-137369 Add method ManagementToolbarDisplayContext.getAdditionalProps()

### PR DESCRIPTION
**Pull request by ngriffin7a**

### CODE REVIEW

**Comment by ngriffin7a** [comment]
@liferay-frontend This pull was reviewed and approved by @drewbrokke in drewbrokke#1368

Please ci:forward to Brian if you approve. Thanks.

**Comment by ngriffin7a** [comment]
@liferay-frontend I have reviewed the failures and I can't see how any of them are related to this PR.

Please ci:forward to Brian after your review. Thank you, Neil

**Comment by john-co** [comment]
Just started reviewing :)

**Comment by john-co** [comment]
Reviewed. Test failures are unrelated. :heavy_check_mark: 

I will manually forward this.

[Not Related]
- Commerce tests should be fixed in https://github.com/liferay-commerce/liferay-portal/pull/1578
- modules-integration tests caused by: https://issues.liferay.com/browse/COMMERCE-7017

My hunch is the comparison is incorrectly identifying them as unique since Acceptance tests failed to build due to outage over weekend. Raised to qa-ci slack channel.

**Comment by john-co** [comment]
pushed to https://github.com/brianchandotcom/liferay-portal/pull/105671

**Pull request closed without merging**
