### PR TITLE
[WIP!!!]- LPS-102103 Remove compat management_bar, compat nav and nav-tabs

### PR DESCRIPTION
**Pull request by marcoscv-work**
Only testing

Putting together:
#598
#626
#588

### CODE REVIEW

**Comment by jbalsas** [comment]
Lol.. I don't see this getting anywhere near green with CI, but who knows...

believeinyourdreams

**Comment by marcoscv-work** [comment]
> Lol.. I don't see this getting anywhere near green with CI, but who knows...
> 
> believeinyourdreams

you order actions to the CI !!!! :-(

**Comment by edalgrin** [comment]
I think it's my last commit, better close this in favor of https://github.com/liferay-frontend/liferay-portal/pull/630

**Comment by edalgrin** [comment]
ci:test:stop

**Comment by marcoscv-work** [comment]
We will update the latest commits and run the test.

**Comment by julien** [comment]
Hey @marcoscv-work just so you know (and maybe you already do), for work in progress PRs you can alway submit them as "drafts".

**Comment by wincent** [comment]
And even change them to drafts after the fact, using this link that doesn't look at all like a link:

Screenshot 2020-12-17 -155605-z7TyiZ8J@2x

**Comment by edalgrin** [comment]
Do tests run in draft mode?

**Comment by julien** [comment]
They do :)

**Comment by julien** [comment]
It's just a way for us to "filter" out PRs that aren't ready for review

**Pull request closed without merging**
