### PR TITLE
LPS-124187 Fix style of form validation

### PR DESCRIPTION
**Pull request by edalgrin**
This PR fixes an error caused by the compat-layer removal. 

We had the CSS class `.help-block` that simulated the new `.form-feedback-item` from Clay

We added the new class using the AUI API

image

### CODE REVIEW

**Comment by edalgrin** [comment]
ci:reevaluate:1222004_7728

**Comment by edalgrin** [comment]
ci:test:relevant

**Comment by edalgrin** [comment]
@john-co can you help me with this? Or since it's related to the compat-laye should I ask Summer? (she was working on it, right?)

**Comment by john-co** [comment]
Looks like those test batches are flaky...I've seen some random failures in those batches in other PRs such as https://github.com/liferay-frontend/liferay-portal/pull/740#issuecomment-771128193

**Comment by john-co** [comment]
ci:test:relevant

**Comment by edalgrin** [comment]
Thank you!

**Comment by edalgrin** [comment]
ci:forward

**Pull request closed without merging**
