### PR TITLE
LPD-22985 Playwright tests for date-time support in DSM and FDS

### PR DESCRIPTION
**Pull request by markocikos**
### References

- Parent Story: [LPD-19647 Make “Date and Time” and "Date" types available to be source for filters](https://issues.liferay.com/browse/LPD-19647)

### What is the goal of this PR?

We're adding tests for `date-time` filters handling. The tests are limited to scope of the story, leaving out general filters management (saving, editing, sorting, deleting etc).

As a sidequest, we're refactoring all DSM tests to use isolated layout, instead of isolated site. This reduced a lot of code, and should help a bit in performance.

### What does it look like?

image

### CODE REVIEW

**Comment by markocikos** [comment]
ci:test:playwright

**Comment by juanjofgliferay** [comment]
I like the `isolatedLayout`, much cleaner :clap:

**Comment by markocikos** [comment]
Added fix for the related failure in https://github.com/liferay-frontend/liferay-portal/pull/4157#issuecomment-2077661155, and renamed file to be more consistent with https://github.com/liferay-frontend/liferay-portal/pull/4141

**Comment by markocikos** [comment]
ci:forward

**Pull request closed without merging**
