### PR TITLE
LPS-173327 Expose FDS utilities to reload data and open side panel in custom actions and custom data renderers

### PR DESCRIPTION
**Pull request by markocikos**
### References

- [LPS-173327 Expose FDS context in custom actions and custom data renderers](https://issues.liferay.com/browse/LPS-173327)
- Related Slack discussion: https://liferay.slack.com/archives/CNBG06JS3/p1674074856364879

### What is the goal of this PR?

In this PR:
1. We are exposing `loadData` and `openSidePanel` utilites in custom actions and custom data renderers.
2. We are adding samples for exposed props, both new and existing ones.
3. We are exposing utility to close modal, as I found this useful in modal example.

Notes:
- I considered exposing the entire `FrontendDataSetContext`. While this would be an easier solution and more powerful tool for customization, I concluded that this would not be a good idea. This would expose too much, adding risk to any internal changes  down the line. Even if we wouldn't use something from Context, there would be a possibility that some customers do. Instead, I think it's a better idea if we expose only explicit utilities that we need.
- There is a bug that `x` close button of empty side panel does not work. This is unrelated to this PR. In real usages, this gets overlayed by panel content, and panel content contains the close button. We should probably remove this button, but that's outside of scope of this ticket.
- I don't think that we need to expose `openSidePanel` utilites for bulk actions, side panel seems related only to workflows related to single item. If I'm wrong, we can add this later.

### What does it look like?

https://user-images.githubusercontent.com/5435511/213746867-86d6a0ea-0d98-4faa-bf0b-e05c3e690edf.mp4

### Steps to reproduce

1. Deploy `frontend-data-set-sample-web`.
4. Place `Frontend Data Set Sample` widget on any page.

### CODE REVIEW

**Comment by markocikos** [comment]
ci:test:relevant

**Review by carloslancha — COMMENTED** [review]
I don't know if I like the approach. I understand your concerns about exposing the whole context but the amount of code we need to add in so many places to just expose that couple functions via callbacks... I'm not sure if that scales well.

As you commented, If we need to expose it for the bulk actions too we'll add it. And if we need to add another one, we'll need to add it everywhere.

What would be the actual cons or problems about exposing the whole context? What if we create a public context for this kind of public API?

Just throwing some ideas ;)

**Comment by markocikos** [comment]
>I don't know if I like the approach. I understand your concerns about exposing the whole context but the amount of code we need to add in so many places to just expose that couple functions via callbacks... I'm not sure if that scales well.

@carloslancha Yeah, you have a good point there! One thing to have in mind that some of these places to change are unnecessary, only result of code duplication in FDS. For example, I am fairly sure that three `onActionDropdownItemClick` invocations in `Actions.js` and `ActionsDropdown.js` can be reduced to one, and the whole props propagation through `handleAction` removed / simplified. It's probably best that we leave refactoring out of this task. With that in mind, there will likely always be two or more places to extend, one for each content renderer. `table` and `list` reuse `Actions` component, while `cards` has unique actions implementation.

>What would be the actual cons or problems about exposing the whole context? What if we create a public context for this kind of public API?

Public context is really interesting idea! There is a tradoff here, as we are increasing boilerpate and complexity, for the sake of increasing maintainability down the line. I think that good rule of thumb here would be rule of three. If there are three or more props to expose, expose them bundled in in common context. For one prop, it's definitely unnecessary. For two, it's a borderline case. I checked other exposed props, and the two in PR are the only ones from component context. The other props are specific to item cell. For this PR, I'd be ok either way.

**Comment by carloslancha** [comment]
Go with it then, my main concern would be about maintenance and scalability, but if you think that should be easier after some refactoring you do have more context than me. LGTM!

**Comment by markocikos** [comment]
ci:forward

**Pull request closed without merging**
