### PR TITLE
[7.4-only]LPS-102105 - Removes compat nav

### PR DESCRIPTION
**Pull request by pat270**
https://issues.liferay.com/browse/LPS-102105

This removes the `nav` compat layer. Most of the navs are updated already so nothing of significance should happen with this pr. The only things that were missing were `nav-item` and `nav-link` on `li` and `a/button` respectively.

https://issues.liferay.com/browse/LPS-102116

- Styled theme removes toggle-switch compat layer
- updates aui:input toggle-switch to use Clay 3 markup.
- aui:input toggle-switch removes the output of yes and no data-labels by default
- aui:input adds attribute labelCssClass to allow adding css classes to the label element
- aui:input adds attributes buttonIconOff, buttonIconOn, iconOff, and iconOn so we can pass in icons to toggle-switch
- Apps use simple-toggle-switch where applicable (asset, blogs, bookmarks, change-tracking, commerce, depot, document library, expando, iframe, journal, layout, mentions, message boards, mobile-device-rules, password-policies-admin, portal-instances, portal-security, portlet-configuration, roles, rss, sharing, site-navigation, site, sync, users-admin, dxp/apps/commerce-avalara, dxp/apps/segments)

### CODE REVIEW

**Comment by pat270** [comment]
ci:test:sf

**Comment by pat270** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
Hey @pat270, can you edit the description here according to our guidelines so it's clear what's going on and what type of changes to expect from this?

I know it can be somewhat tedious and sometimes the LPS "says it all", but adding a clear description and test plan (with snapshots when possible) helps reviewers get a quick sense on how safe things are make decisions faster about how to review and forward a PR.

This also helps us track things down in the future without having to jump through too many hoops ;)

Code changes look good to me!

**Comment by marcoscv-work** [comment]
LGTM !

In order to avoid conflicts per day, could we merge this PR with https://github.com/liferay-frontend/liferay-portal/pull/585and sent them together?

**Comment by pat270** [comment]
@marcoscv-work @edalgrin I cherry picked the commits from #585, rebased, and fixed conflicts.

**Comment by pat270** [comment]
ci:test:sf

**Comment by pat270** [comment]
ci:test:relevant

**Comment by marcoscv-work** [comment]
Really ugly Github UI rebase 

:-S

**Comment by marcoscv-work** [comment]
ci:test:sf

**Comment by pat270** [comment]
ci:test:sf

**Comment by pat270** [comment]
@marcoscv-work I fixed the SF issue and rebased.

**Comment by marcoscv-work** [comment]
We should sync to be able to send today Patrick's PR's, they were waiting for days, sorry @pat270 ;-) ! 
@edalgrin and I will try to merge some PRs and test them during this morning, if we are not able, we will go ahead with this one, but this PR should be sent today! :-D

**Comment by marcoscv-work** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcoscv-work** [comment]
Trying to merge with:

- management bar:
https://github.com/liferay-frontend/liferay-portal/pull/630

- management bar and nav-tabs
https://github.com/liferay-frontend/liferay-portal/pull/630

**Comment by marcoscv-work** [comment]
ci:forward

**Comment by marcoscv-work** [comment]
https://github.com/liferay-frontend/liferay-portal/pull/630 Failed, so I tried a `ci:forward` but there is a conflict I already solved in #630

Can we fix the conflict and resend rebased with https://github.com/brianchandotcom/liferay-portal/pull/97055 which already are on brian repo?

**Comment by pat270** [comment]
ci:forward

**Comment by pat270** [comment]
@john-co @zhangyan0701 not sure about this [failure](https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=19,label_exp=!master/420283/testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_CPCommerceSettings_ViewInstanceCurrenciesAvailable_/), I don't think I modified anything related to that.

**Comment by zhangyan0701** [comment]
ci:test:bundle

**Comment by marcoscv-work** [comment]
manual forward? or should we repeat `relevant`?

**Comment by zhangyan0701** [comment]
The test failure of test LocalFile.CPCommerceSettings#ViewInstanceCurrenciesAvailable is unrelated.

It was quarantined in commit https://github.com/liferay-commerce/liferay-portal/pull/360/commits/1a8a090727d8974b6fbda5bf2280524053a8c97b, but hasn't merged into upstream yet.

So I suggest manually forward this PR to BChan.

**Comment by marcoscv-work** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcoscv-work** [comment]
Manual forward here: https://github.com/brianchandotcom/liferay-portal/pull/97084

**Pull request closed without merging**
