### PR TITLE
LPS-173302 Error - OpenIdConnectSessionValidationFilter

### PR DESCRIPTION
**Pull request by AlmirFe**
Previous PR: #3240 

Context
=======
Hi guys, this PR contains the solution to [LPS-173302](https://issues.liferay.com/browse/LPS-173302) wich fixes the [LPP-47683](https://issues.liferay.com/browse/LPP-47683). The SRE team has observed several errors in the VALE project (LXC) that are causing performance issues, and this PR solves one of these issues. Unfortunately we have no steps to reproduce this error. The solution was created based on stacktrace (You can find it on LPS ticket). I would like your review to know if this change can be merged on master.

Proposed Solution
========
I added a check to prevent the moduleName variable from being used if it is null. As commented in the PR #3240, a debug log was added to see when the moduleName is null.

### CODE REVIEW

**Comment by bryceosterhaus** [comment]
cc @izaera you'd probably have the most context to review this change

**Comment by izaera** [comment]
@AlmirFe The changes look good to me :+1:  

I would advise logging the `pathInfo` in addition to the message `"moduleName value is null"` so that one day we may know, looking at the logs, which requests are causing this to fail (because they must be invalid requests for .js files and knowing them may lead to finding another error that needs to be fixed).

In any case, feel free to modify the log sentence or forward it as is.

Seeing that tests are not green I'm going to ask QA if this can be forwarded.

**Comment by mateusralv** [comment]
Hi @AlmirFe and @izaera I had a look at the ci:test:relevant results and did not find any unique failure. 

[Testray Comparison](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1687181354964&testrayRunIdA=2352439361&testrayRunIdB=2352543243)

**Comment by izaera** [comment]
So, @AlmirFe, feel free to run `ci:forward:force` or, if you think makes sense, modify the log first as I suggested [here](https://github.com/liferay-frontend/liferay-portal/pull/3456#issuecomment-1594600047)

**Comment by izaera** [comment]
ci:forward:force

**Comment by izaera** [comment]
ci:forward:force

**Pull request closed without merging**
