### PR TITLE
LPS-123515 [7.4.x-only] Update @liferay/npm-scripts to v36.1.0

### PR DESCRIPTION
**Pull request by wincent**
[Release notes](https://github.com/liferay/liferay-frontend-projects/releases/tag/npm-scripts%2Fv36.1.0).

Of principal interest is [this PR](https://github.com/liferay/liferay-frontend-projects/pull/233), which adds build-time minification to any JS touched by `@liferay/npm-scripts` during the build (note: this is not all JS in DXP, but most of it).

We have a few options to pursue to increase coverage, which we'll be looking at in future pulls:

- Tweaking Gradle build so that we can pre- or post-process JSP to minify JS contents.
- Extending this treatment to Sass as well.
- Running `@liferay/npm-scripts build` in more places, to catch JS which gets copied into JARs via other means.

See [LPS-122883](https://issues.liferay.com/browse/LPS-122883) for other tasks that we'll be following up with, such as turning of the run-time minifier by default and marking it as deprecated.

Previously tested at [wincent#370](https://github.com/wincent/liferay-portal/pull/370).

### CODE REVIEW

**Comment by wincent** [comment]
ci:test:sf

**Comment by wincent** [comment]
ci:test:relevant

**Comment by wincent** [comment]
ci:test:bundle

**Comment by wincent** [comment]
Note that I've marked this as 7.4-only for now, out of caution. We could potentially allow this to be backported without too many ill effects (ie. if we don't want to turn off run-time minification by default on 7.3.x and older, we don't have to — at worst, it will just be redundantly trying to minify something that has already been minified). 🤷

**Comment by jbalsas** [comment]
What are we waiting for? 😂 

releasethehounds

**Comment by wincent** [comment]
> What are we waiting for? 😂

Well, I was looking into Peter Shin's suggestion of [how to integrate the JSP minification](https://github.com/wincent/liferay-portal/pull/371). Also, there's [this related draft](https://github.com/liferay-frontend/liferay-portal/pull/553/files) about the "breaking change" (`minifier.enabled=false`) that I wanted to see if anybody had a comment on, in case that would require a follow-up.

Which is to say, this is ok to ship, but I expect there'll be inevitable follow-up and I wanted to see if I could batch it a bit.

**Comment by jbalsas** [comment]
> Also, there's this related draft about the "breaking change" (minifier.enabled=false) that I wanted to see if anybody had a comment on, in case that would require a follow-up.

Yeah, I came here from there... that one LGTM and so does this one and the one about JSP... I'm very easy to please 😂 

> Which is to say, this is ok to ship, but I expect there'll be inevitable follow-up and I wanted to see if I could batch it a bit.

I'd say, group them all together and send one single PR

**Comment by jbalsas** [comment]
Hey @wincent, @izaera, what should we do with this? It's green, but @izaera is supposedly sending a new version...

**Comment by wincent** [comment]
Let's just close this. @izaera can update to this-version-plus-one.

**Pull request closed without merging**
