### PR TITLE
LPS-148663 Migrate use cases of window.confirm on DXP Java files

### PR DESCRIPTION
**Pull request by diegonvs**
### Publications

1. Global Menu -> Publications
2. Enable Publications and mark sandbox only to true
3. Add a new publication, name it 'fiona'
4. Go back to publications listings and try to delete 'fiona'

image

You should be able to open the confirm dialog and when clicking on Ok, it will delete, cancel will do nothing and close the dialog.

### Document Library

1. First, you need to disable the Recycle bin (the confirm only appears when there is no recycle bin). On the product menu, go to Configuration > Site Settings > Recycle bin and disable it.
2. Add the Documents and Media widget to a page, and on the configuration section, check the “show actions”  option
3. Select an entry and go to the detail of it. Here you will see at the top the toolbar items. Delete is the one you are looking for 

Same as publications, the dialog and the actions

## icon-delete (a.k.a IconDeleteTag)

1. Global Menu -> Roles
2. Create a new Role. I named it Cat Fan
3. Go to Roles listings
4. Click on the three-dot button on "Cat Fan" row, then, click on "Delete"

## icon-deactivate (a.k.a IconDeactivateTag)

1. Global Menu -> Accounts
2. Create a new Account. Name it "Refrigerantes Dolly"
3. See Account listings and click on three dot button and then "Deactivate"

### CODE REVIEW

**Review by markocikos — APPROVED** [review]
LGTM!

Well TBH, is looks pretty terrible, as any JS in Java does, but one step at a time...

**Comment by diegonvs** [comment]
ci:test:relevant

**Comment by diegonvs** [comment]
Updated how to test section and fixed an issue with deactivate-icon tag

**Comment by diegonvs** [comment]
ci:test:relevant

**Comment by diegonvs** [comment]
ci:test:relevant

**Comment by diegonvs** [comment]
[LocalFile.DMCache#CanConfigureCacheControlAsPrivate](https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/240691//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_DMCache_CanConfigureCacheControlAsPrivate_) when running locally it is passing. Re-running again

**Comment by diegonvs** [comment]
ci:test:relevant

**Comment by diegonvs** [comment]
ci:test:sf

**Comment by diegonvs** [comment]
ci:test:relevant

**Comment by mateusralv** [comment]
hey @diegonvs, ci:test:relevant passed 🟢 🎉

**Comment by diegonvs** [comment]
ci:forward

**Pull request closed without merging**
