### PR TITLE
LPS-135182 Isolate Page Editor Inline Controls

### PR DESCRIPTION
**Pull request by pat270**
https://issues.liferay.com/browse/LPS-135182

@liferay-echo This isolates the CSS (make it difficult to overwrite) for Page Editor Inline Controls.

The CSS I'm using to test:
```html
<style>
html {
  font-size: 20px;
}

#senna_surface1 h1,
#senna_surface1 h2,
#senna_surface1 h3,
#senna_surface1 h4,
#senna_surface1 h5,
#senna_surface1 h6 {
  background-color: #282828;
  border: 4px solid #00ff66;
  color: #00ff66;
  font-family: Georgia;
  font-size: 50px;
  font-style: italic;
  font-variant: small-caps
  font-weight: bold;
  line-height: 100px;
  letter-spacing: 2px;
  margin: 10px 0;
  padding: 10px;
  text-align: center;
  text-shadow: 1px 1px 0 #fff;
  text-transform: uppercase;
  white-space: nowrap;
}

#senna_surface1 .btn {
  background-color: #282828;
  border: 4px solid #00ff66;
  color: #00ff66;
  font-family: Georgia;
  font-size: 50px;
  font-style: italic;
  font-variant: small-caps
  font-weight: bold;
  line-height: 100px;
  letter-spacing: 2px;
  margin: 10px 0;
  padding: 10px;
  text-align: center;
  text-shadow: 1px 1px 0 #fff;
  text-transform: uppercase;
  white-space: nowrap;
}

#senna_surface1 .btn:hover {
  background-color: #000;
  color: #ffcc00;
  letter-spacing: 4px;
  font-size: 40px;
}

#senna_surface1 a {
  background-color: #282828;
  border: 4px solid #00ff66;
  color: #00ff66;
  font-family: Georgia;
  font-size: 50px;
  font-style: italic;
  font-variant: small-caps
  font-weight: bold;
  line-height: 100px;
  letter-spacing: 2px;
  margin: 10px 0;
  padding: 10px;
  text-align: center;
  text-shadow: 1px 1px 0 #fff;
  text-transform: uppercase;
  white-space: nowrap;
}

#senna_surface1 a:hover {
  background-color: #000;
  color: #ffcc00;
  letter-spacing: 4px;
  font-size: 40px;
}
</style>
```

Screenshot:
page-editor-controls

### CODE REVIEW

**Comment by pat270** [comment]
ci:test:relevant

**Comment by pat270** [comment]
@zhangyan0701 @nkkwon I'm not sure why 1. test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/1 is failing. I rebuilt and manually checked it and it seems to be working. Could one of you take a look and see if I'm replicated the test case correctly? Also I have no idea how my changes would cause 2. to fail. I'm rerunning the tests hopefully it passes this time 🙏 

master-pages-dropdown

**Comment by zhangyan0701** [comment]
@pat270 

The second run shows no unique failures, but I checked the test results on Jenkins, the Dropdown tests failed in this run as well, and I could reproduce when running the poshi tests locally. So I think the failures are related to this PR, but look more like test fix as the dropdown works for me too when I manually check.

The tests can pass locally if I update them using javaScriptClick function to click the Dropdown. I send the fix to you in https://github.com/pat270/liferay-portal/pull/241. Could you resolve the conflicts and cherry-pick my commit then rerun the test?

**Comment by pat270** [comment]
Sent this to team echo for review.

**Pull request closed without merging**
