### PR TITLE
LPS-195696 We need to manage focusManager similarly to overlay when working with several menus on a page

### PR DESCRIPTION
**Pull request by antonio-ortega**
Hi guys,

This [LPS-195696](https://liferay.atlassian.net/browse/LPS-195696) was caused by [LPS-130738](https://liferay.atlassian.net/browse/LPS-130738), because in that one we started managing one overlay for every menu in the page (we had to do it that way to properly deal with auto fields). 

But after that, focusManager stopped working because it was always related to the first menu in the page, so I'm following the same approach, having one focusManager for each menu trigger.

Thanks.

Regards.

### CODE REVIEW

**Comment by antonio-ortega** [comment]
ci:test:relevant

**Comment by antonio-ortega** [comment]
ci:test:relevant

**Comment by mateusralv** [comment]
Hey @antonio-ortega The failures are not related 🎉 
[
Testray Comparison](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=2&testrayRunIdB=2438807621&testrayRunIdA=2437403411&statusB=3)

**Comment by antonio-ortega** [comment]
Manually forwarded https://github.com/brianchandotcom/liferay-portal/pull/142098

**Pull request closed without merging**
