### PR TITLE
LPS-185440 Add support for status in Screen Navigation taglib

### PR DESCRIPTION
**Pull request by sandrodw3**
Hi guys!

This PR adds support for status in Screen Navigation taglib entries. The solution is thought to be able to show something like this:

image

I have added `T context` as param from both methods so on each implementation we are able to do some checks to add the status.

Could you please give me your feedback? Thanks a lot 😄

**LPS ticket:** https://issues.liferay.com/browse/LPS-185440

### CODE REVIEW

**Comment by sandrodw3** [comment]
ci:test:sf

**Comment by sandrodw3** [comment]
ci:test:relevant

**Comment by sandrodw3** [comment]
ci:test:sf

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
