### PR TITLE
LPS-127081 Adjust remote-app-client-js for forwards-compatibility

### PR DESCRIPTION
**Pull request by wincent**
A forthcoming `@liferay/npm-scripts` release will include [this PR](https://github.com/liferay/liferay-frontend-projects/pull/425) which adds some basic support for building TypeScript in liferay-portal (beyond the webpack-based build that we're already using in remote-app-client-js).

I don't know exactly when the next release will be, because we have other changes ongoing in `@liferay/npm-scripts` and I don't want to clash with those, but I do want to make sure that _if_ we were to merge, and cut a release, liferay-portal would be ready for it.

This configuration tweak allows the existing `HEAD` of the `master` branch to continue building correctly (verified with `yarn build`), while preparing it for the subsequent `@liferay/npm-scripts` release, whenever that ends up happening.

### CODE REVIEW

**Comment by wincent** [comment]
> ci:test:sf - 0 out of 1 jobs passed in 3 minutes

Definitely my favorite kind of failure.

**Comment by wincent** [comment]
ci:test:sf

**Comment by wincent** [comment]
ci:test:relevant

**Comment by wincent** [comment]
> ci:test:sf - 0 out of 1 jobs passed in 4 minutes

Sigh. `gradlew formatSource` changed the end-of-file newline, but not the wrapping. Manually fixing.

**Comment by wincent** [comment]
ci:stop

**Comment by wincent** [comment]
Oh, great... it's even better. Prettier wants the newline and Java SF doesn't. 🤦‍♂️

**Comment by wincent** [comment]
ci:test:sf

**Comment by wincent** [comment]
@jbalsas: What do you think about revisiting our policy on who (ie. Prettier or Java SF) is responsible for formatting JSON? I just wasted a good chunk of time figuring this out again, when all I really wanted to do was ship a trivial config change.

Current status:

-   Java SF [special-cases `package.json` files](https://github.com/liferay/liferay-portal/blob/97c81548cc2c7aa05bc0f2a815c8d30b26549845/modules/util/source-formatter/src/main/java/com/liferay/source/formatter/checks/JSONStylingCheck.java#L45-L47) so that:
    -   If a Liferay employee edits one by hand and has their editor configured to _omit_ the trailing newline at end of file (like every good employee following the company handbook does 😉), SF will accept it.
    -   If a tool like `yarn` updates one programmatically and _adds_ a trailing newline, SF will preserve it.
    -   Every other JSON file must not have a trailing newline.
-   We've [told Prettier to format JSON files in the top-level of OSGi modules](https://github.com/liferay/liferay-portal/blob/97c81548cc2c7aa05bc0f2a815c8d30b26549845/modules/npmscripts.config.js#L16-L20), because we can, but it also means that we have to tell Prettier not to mess with `tsconfig.json` files so as not to conflict with Java SF.

Because the check-and-fix globs apply at the top level, this means that when you run `ci:test:sf` or a format source task form the top level, `tsconfig.json` files don't get touched. But if you do what I did (run `gradlew formatSource` or `yarn run format` inside `remote-app-client-js`), then Prettier formats the file, which leads Java to disagree (at least it does in this specific instance because of the array which would fit on one line).

I really think we should just turn off `JSONStylingCheck.java` at this point and let Prettier handle all JSON. It would avoid silly little time-sinks like this, and allow us to stop using a class that already has a pretty ugly special-case buried deep in its heart. We could also tell Prettier to forget about JSON, but that strikes me as a step backwards; I want to be able to run a `yarn format` command from any module, have it do its job in a few seconds at most, and then return control to me, as opposed to firing up dozens of megabytes of heavyweight Ant and Gradle-powered machinery to format a snippet of *JS*ON.

**Comment by wincent** [comment]
ci:test:relevant

**Comment by wincent** [comment]
Very skeptical of that unique failure, so re-running.

**Comment by wincent** [comment]
ci:test:relevant

**Comment by wincent** [comment]
@john-co, @calvinctvo, @zhangyan0701: should I be afraid here?

[First run](https://github.com/liferay-frontend/liferay-portal/pull/871#issuecomment-791735182):

> ❌ ci:test:relevant - 20 out of 23 jobs passed in 3 hours 37 minutes
>
> #### Failures unique to this pull:
> 1. ##### [test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8/0](https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/219759/)###### Job Results:12 Tests Passed.2 Tests Failed.1. [AXIS_VARIABLE=2,label_exp=!master #219759](https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=2,label_exp=!master/219759//consoleText)1. [LocalFile.PortalSmokeUpgrade#ViewPortalSmokeArchive7110](https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=2,label_exp=!master/219759//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_PortalSmokeUpgrade_ViewPortalSmokeArchive7110_) - [Poshi Report](https://testray.liferay.com/reports/production/logs/test-1-6/1614968099473/test-portal-acceptance-pullrequest(master)/8065/functional-upgrade-tomcat90-mysql57-jdk8/0/2/LocalFile.PortalSmokeUpgrade_ViewPortalSmokeArchive7110/index.html.gz) - [Poshi Summary](https://testray.liferay.com/reports/production/logs/test-1-6/1614968099473/test-portal-acceptance-pullrequest(master)/8065/functional-upgrade-tomcat90-mysql57-jdk8/0/2/LocalFile.PortalSmokeUpgrade_ViewPortalSmokeArchive7110/summary.html.gz) - [Console Output](https://testray.liferay.com/reports/production/logs/test-1-6/1614968099473/test-portal-acceptance-pullrequest(master)/8065/functional-upgrade-tomcat90-mysql57-jdk8/0/2/jenkins-console.txt.gz)2. [AXIS_VARIABLE=3,label_exp=!master #219759](https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=3,label_exp=!master/219759//consoleText)1. [LocalFile.PortalSmokeUpgrade#ViewPortalSmokeArchive71103](https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=3,label_exp=!master/219759//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_PortalSmokeUpgrade_ViewPortalSmokeArchive71103_) - [Poshi Report](https://testray.liferay.com/reports/production/logs/test-1-6/1614968099473/test-portal-acceptance-pullrequest(master)/8065/functional-upgrade-tomcat90-mysql57-jdk8/0/3/LocalFile.PortalSmokeUpgrade_ViewPortalSmokeArchive71103/index.html.gz) - [Poshi Summary](https://testray.liferay.com/reports/production/logs/test-1-6/1614968099473/test-portal-acceptance-pullrequest(master)/8065/functional-upgrade-tomcat90-mysql57-jdk8/0/3/LocalFile.PortalSmokeUpgrade_ViewPortalSmokeArchive71103/summary.html.gz) - [Console Output](https://testray.liferay.com/reports/production/logs/test-1-6/1614968099473/test-portal-acceptance-pullrequest(master)/8065/functional-upgrade-tomcat90-mysql57-jdk8/0/3/jenkins-console.txt.gz)

[Second run](https://github.com/liferay-frontend/liferay-portal/pull/871#issuecomment-791968924):

> ✔️ ci:test:relevant - 22 out of 23 jobs passed in 1 hour 51 minutes
>
> #### Failures (upstream comparison is not available):
> 1. ##### [test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0](https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/426895/)###### Job Results:1 Test Passed.1 Test Failed.1. [AXIS_VARIABLE=0,label_exp=!master #426895](https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/426895//consoleText)1. [LocalFile.RemoteApps#AddRemoteApp](https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/426895//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_RemoteApps_AddRemoteApp_) - [Poshi Report](https://testray.liferay.com/reports/production/logs/test-1-14/1615036448939/test-portal-acceptance-pullrequest(master)/7861/functional-tomcat90-mysql57-jdk8/0/0/LocalFile.RemoteApps_AddRemoteApp/index.html.gz) - [Poshi Summary](https://testray.liferay.com/reports/production/logs/test-1-14/1615036448939/test-portal-acceptance-pullrequest(master)/7861/functional-tomcat90-mysql57-jdk8/0/0/LocalFile.RemoteApps_AddRemoteApp/summary.html.gz) - [Console Output](https://testray.liferay.com/reports/production/logs/test-1-14/1615036448939/test-portal-acceptance-pullrequest(master)/7861/functional-tomcat90-mysql57-jdk8/0/0/jenkins-console.txt.gz)

Different failures each time, but second time mentions "RemoteApps" which is a bit scary given that I touched this module. (FWIW, I don't believe it is related at all.)

**Comment by zhangyan0701** [comment]
The upgrade tests should be fluke since they passed on the second run.

The RemoteApps test failure started to happen on upstream with the same error based on the [history results](https://testray.liferay.com/home/-/testray/case_results/1498258091/history?tab=result&hideFilterPin=true), so it shouldn't be related to this pr.

**Comment by wincent** [comment]
Thanks @zhangyan0701.

Going to forward this. For anybody watching, note that as we roll out TypeScript more broadly over liferay-portal we'll start to identify common patterns that we can bake into `@liferay/npm-scripts`, alleviating the need for micromanaging the config like this, but at these early stages, manual is the way to go.

**Comment by wincent** [comment]
ci:forward

**Comment by jbalsas** [comment]
> I really think we should just turn off JSONStylingCheck.java at this point and let Prettier handle all JSON. It would avoid silly little time-sinks like this, and allow us to stop using a class that already has a pretty ugly special-case buried deep in its heart. 

Hey @wincent, while I share the sentiment, I think this isn't currently some low-hanging fruit. There's JSON all over the place in `liferay-portal` in places where we don't run `yarn format` like [address-impl](https://github.com/liferay-frontend/liferay-portal/tree/master/modules/apps/address/address-impl/src/main/resources/com/liferay/address/dependencies). 

> We could also tell Prettier to forget about JSON, but that strikes me as a step backwards; I want to be able to run a yarn format command from any module, have it do its job in a few seconds at most, and then return control to me, as opposed to firing up dozens of megabytes of heavyweight Ant and Gradle-powered machinery to format a snippet of JSON.

I agree that sounds like a step backwards but at the same time it's not as if we do a lot with JSON, so maybe that's indeed something worthwhile for now until we can put some extra time into how to better integrate our tooling with the build process?

**Pull request closed without merging**
