### PR TITLE
LPS-116771 Fix style of navigation-bar removing the extra container

### PR DESCRIPTION
**Pull request by eduardoallegrini**
This is a simple style fix. I removed the extra container from the navigation-bar

image

### CODE REVIEW

**Comment by eduardoallegrini** [comment]
ci:test:sf

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
LGTM! 👍

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
Hey @john-co, failures look unrelated... running again just in case, could you take a look to see if something's wrong with CI?

**Comment by john-co** [comment]
ci:test:bundle

**Comment by jbalsas** [comment]
ci:forward

**Pull request closed without merging**
