### PR TITLE
LPS-170287 Documents and Media - Wrong name is set when creating a folder with a lowercase

### PR DESCRIPTION
**Pull request by markocikos**
### References

- [LPS-170287 Fix all the things](https://issues.liferay.com/browse/LPS-170287)
- followup on https://github.com/liferay-frontend/liferay-portal/pull/2917
- followup on https://github.com/liferay-frontend/liferay-portal/pull/3144

### What is the goal of this PR?

We're removing an unnecessary check, see https://github.com/brianchandotcom/liferay-portal/pull/131977#issuecomment-1476559755

There is no need for peer review on this PR, feel free to forward if CI is green.

/cc @thienquach87 @dsanz

### CODE REVIEW

**Comment by mateusralv** [comment]
Hi @markocikos the failures are not related! 

[Testray comparison](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=2&testrayRunIdB=2239033608&testrayRunIdA=2238974100&statusB=3)

**Comment by markocikos** [comment]
One last try before manual forward..

**Comment by markocikos** [comment]
ci:forward

**Comment by markocikos** [comment]
ci:forward

**Pull request closed without merging**
