### PR TITLE
LPD-20726 Update liferay-ckeditor version

### PR DESCRIPTION
**Pull request by antonio-ortega**

### CODE REVIEW

**Comment by antonio-ortega** [comment]
ci:test:relevant

**Comment by antonio-ortega** [comment]
ci:test:relevant

**Comment by antonio-ortega** [comment]
ci:test:relevant

**Review by markocikos — APPROVED** [review]
@antonio-ortega LGTM! :sparkles:

**Comment by antonio-ortega** [comment]
ci:forward

**Comment by antonio-ortega** [comment]
ci:forward

**Comment by antonio-ortega** [comment]
ci:forward

**Comment by antonio-ortega** [comment]
ci:forward

**Comment by antonio-ortega** [comment]
ci:test:relevant

**Comment by antonio-ortega** [comment]
ci:forward:force

**Comment by markocikos** [comment]
ci:forward:force

**Pull request closed without merging**
