### PR TITLE
LPD-36910 Remove dev FF

### PR DESCRIPTION
**Pull request by chestofwonders**
Issue: https://liferay.atlassian.net/browse/LPD-36910

Remove FF LPD-34636 from https://github.com/liferay-frontend/liferay-portal/pull/4387

### CODE REVIEW

**Review by juanjofgliferay — APPROVED** [review]
LGTM :rocket:

**Review by markocikos — APPROVED** [review]
@chestofwonders LGTM! :sparkles:

**Comment by chestofwonders** [comment]
ci:forward

**Comment by chestofwonders** [comment]
ci:report:16672081

**Comment by chestofwonders** [comment]
ci:test:relevant

**Comment by chestofwonders** [comment]
ci:stop

**Comment by chestofwonders** [comment]
Continues in https://github.com/liferay-frontend/liferay-portal/pull/4442

**Pull request closed without merging**
