### PR TITLE
LPS-120345 Use openToast from frontend-js-web in experiences

### PR DESCRIPTION
**Pull request by dgarciasarai**
**Description**

I found that there were some uses of `Liferay.Util.openToast` in the experiences part and I changed it to use `openToast` from `frontend-js-web` module instead. Also, I removed a pending TODO.

* Related issue: https://issues.liferay.com/browse/LPS-107024

### CODE REVIEW

**Comment by dgarciasarai** [comment]
Hey @julien, I think you did these changes all over `layout-content-page-editor-web`, but I found more in the experiences part. Can you take a look at this pull request? Thanks! 😄

**Comment by dgarciasarai** [comment]
ci:test:sf

**Comment by julien** [comment]
@dgarciasarai these changes look good to me (and by removing a `TODO` comment you get 10 bonus points :+1)

**Comment by dgarciasarai** [comment]
Thanks @julien! Let's run the CI :)

**Comment by dgarciasarai** [comment]
ci:test:relevant

**Review by julien — APPROVED** [review]

**Comment by dgarciasarai** [comment]
I'll review the tests 👍

**Comment by dgarciasarai** [comment]
ci:test:sf

**Comment by dgarciasarai** [comment]
ci:forward

**Pull request closed without merging**
