### PR TITLE
LPD-22678 FIX LocalFile.CPCommerceChannels#CanPaginatePaymentAndShippingRestrictions

### PR DESCRIPTION
**Pull request by dsanz**
Reference: https://liferay.atlassian.net/browse/LPD-22678

In this PR we apply a more defensive approach in the FDS view components to account for the case where there are no supplied items.

Background: once empty state management [was centralized at the topmost level](https://github.com/liferay-frontend/liferay-portal/pull/4110/commits/d575283758651cd2300dbc7d54e2a0fdfb669c5b), views components are not meant to render when there are no items. However, internal state changes may trigger such view re-renderings. One of them caused https://liferay.atlassian.net/browse/LPD-22678.

Solution:

- Add back the `items` non-null check before rendering the view for all affected view components.

### CODE REVIEW

**Comment by dsanz** [comment]
ci:test:commerce

**Review by andrea-ale-sbarra — APPROVED** [review]
The test is now passing, the fix looks right.
Thank you!

**Review by juanjofgliferay — APPROVED** [review]
LGTM :rocket:

**Comment by dsanz** [comment]
ci:forward

**Comment by dsanz** [comment]
ci:test:stable

**Comment by dsanz** [comment]
ci:forward:force

**Pull request closed without merging**
