### PR TITLE
LPS-165262 Add Autom. test FrontendJSCustomDialog#CanRenderOpenConfirmModal

### PR DESCRIPTION
**Pull request by eltonccdantas**
**Test Plan**
Given: Enabled Custom Dialog
And When: run JS code: 
Liferay.Util.openConfirmModal({message: "Test Confirm Modal", onConfirm: ()=>{}})
RunScript(locator1 = "Liferay.Util.open...");
Then: text Test Confirm Modal is present in the modal

**JIRA Ticket:** 
https://issues.liferay.com/browse/LPS-165262

### CODE REVIEW

**Comment by eltonccdantas** [comment]
ci:test:frontend:nocompile

**Comment by eltonccdantas** [comment]
cc @mateusralv, @john-co

**Comment by eltonccdantas** [comment]
[comparison run](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1668444692807&testrayRunIdA=2041279452&testrayRunIdB=2041114532)

**Comment by john-co** [comment]
was working on refactor here: https://github.com/liferay-frontend/liferay-portal/pull/2860

Will push changes to your branch now that I'm collaborator and look into rebasing due to merge conflict.

**Comment by john-co** [comment]
ci:test:frontend:nocompile

**Comment by john-co** [comment]
rebased

**Comment by john-co** [comment]
ci:test:frontend:nocompile

**Comment by john-co** [comment]
ci:test:sf

**Comment by john-co** [comment]
ci:forward

**Pull request closed without merging**
