### PR TITLE
LPS-113686 - Fix spaces in md devices

### PR DESCRIPTION
**Pull request by marcoscv-work**
This PR fixes the align and space error in Widget configuration footer in medium devices:

image

After the change:

image

---

Steps to test it:

- Use a medium device or your browser in emulation mode (MD breakpoint)
- Press in the configuration in a widget
- Go to the footer and see the modal footer

### CODE REVIEW

**Comment by marcoscv-work** [comment]
ci:test:sf

**Comment by marcoscv-work** [comment]
ci:test:relevant

**Comment by eduardoallegrini** [comment]
ci:forward

**Comment by marcoscv-work** [comment]
> I spent some time trying to understand the change! 😁 It's very subtle and I think we should review the whole modal structure but for now it fixes the visual bug(?)... so LGTM! 👍

I have a little mess with modals in portal, you can see the difference by calling the widget configuration modal and then the widget look and feel modal.
As soon as we can get the same modal for everything we will be closer to make a global change

**Pull request closed without merging**
