### PR TITLE
LPD-15337 Improve editorConfigContributor automation to deploy the required CX

### PR DESCRIPTION
**Pull request by markocikos**
### References

- [LPD-15337 Improve client-extension-web/editorConfigContributor.spec.ts to deploy the required CX](https://issues.liferay.com/browse/LPD-15337)
- Samples of global setup: https://github.com/michaelhashimoto/liferay-portal/pull/2718

### What is the goal of this PR?

Testing new CX deployment automation. It does not work locally, that's expected, but I'm hoping it will work on CI.

### CODE REVIEW

**Comment by markocikos** [comment]
ci:test:playwright

**Comment by dsanz** [comment]
ci:test:playwright

**Comment by markocikos** [comment]
This feature looks like it's very much work in progress. I'm keeping an eye on @michaelhashimoto's [fork](https://github.com/michaelhashimoto/liferay-portal/pulls).

**Comment by markocikos** [comment]
ci:test:playwright:nocompile

**Comment by markocikos** [comment]
Hmm, it's possible that this works. CX did not deploy, but there was a try:
```
     [exec] Deploy '/opt/dev/projects/github/liferay-portal/workspaces/liferay-sample-workspace/client-extensions/liferay-sample-editor-config-contributor'
     [exec] Downloading https://services.gradle.org/distributions/gradle-7.3.3-bin.zip
[beanshell] 2 hours 5 minutes until timeout.
[beanshell] The top level build is alive.
     [exec] ...........
     [exec] Exception in thread "main" java.io.IOException: Downloading from https://services.gradle.org/distributions/gradle-7.3.3-bin.zip failed: timeout
```

**Comment by markocikos** [comment]
ci:test:playwright

**Comment by markocikos** [comment]
ci:test:playwright

**Comment by markocikos** [comment]
ci:test:playwright

**Comment by markocikos** [comment]
ci:test:playwright

**Comment by markocikos** [comment]
ci:test:playwright

**Comment by markocikos** [comment]
ci:test:playwright

**Comment by markocikos** [comment]
ci:stop

**Comment by markocikos** [comment]
ci:test:playwright

**Comment by markocikos** [comment]
ci:report:2544120277

**Comment by markocikos** [comment]
No unique failures, based on https://github.com/liferay-frontend/liferay-portal/pull/3959#issuecomment-1968511592

**Comment by markocikos** [comment]
ci:forward:force

**Pull request closed without merging**
