### PR TITLE
LPS-115866 Disables AUI Preload Setting by default

### PR DESCRIPTION
**Pull request by jbalsas**
This could technically be a Breaking Change for code not properly declaring their dependencies, so I added a note about it.

This PR basically just flips the switch on some AUI modules being loaded by default in every page. Below are some performance metrics (values not to be taken literally but as a mere indicator of progress).

| Device | Before | After |
| --- | --- | --- |
| Phone | Screen Shot 2020-08-20 at 10 11 10 | Screen Shot 2020-08-20 at 10 14 13 |
| Desktop | Screen Shot 2020-08-20 at 10 10 44 | Screen Shot 2020-08-20 at 10 15 02 |

Just for reference, we were waiting to flip the switch to avoid issues backporting... but let's look at this carefully just in case :)

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:test:sf

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
ci:test

**Comment by jbalsas** [comment]
Going to run a full `test` suit just to see how this looks

**Comment by jbalsas** [comment]
Hey @john-co, @PablitoBonito, I think this looks pretty safe to forward... wdt?

**Comment by john-co** [comment]
looks good to me!

**Comment by jbalsas** [comment]
cu:forward

**Comment by jbalsas** [comment]
ci:forward

**Pull request closed without merging**
