### PR TITLE
[Only-7.4] LPS-125761 and LPS-125859: - Fix compat management-bar

### PR DESCRIPTION
**Pull request by marcoscv-work**
This PR fixes two issues with compat management bar:

- LPS-125761: Fix the checkbox
- LPS-125859: Fix the super extra space

https://user-images.githubusercontent.com/7963804/104601519-a211b380-567a-11eb-89bb-dd0eb6fead3c.mov

Mobile:
image

---

How to test it?

 - Product menu > configuration > mobile device families
 - Create a new one
 - See the pretty and awesome old management bar

### CODE REVIEW

**Comment by marcoscv-work** [comment]
ci:test:sf

**Comment by marcoscv-work** [comment]
ci:test:relevant

**Comment by marcoscv-work** [comment]
Re-testing because I've added a fix for LPS-125859

**Review by edalgrin — APPROVED** [review]
👍

**Comment by edalgrin** [comment]
Just started reviewing :)

**Comment by edalgrin** [comment]
ci:forward

**Pull request closed without merging**
