### PR TITLE
LPS-123865 [Bug] Publish winner button inside success alert has wrong colors

### PR DESCRIPTION
**Pull request by dgarciasarai**
**Description**
If there is a winner variant in an AB Test, we display an alert with a button "Publish Winner" to make more clear which is the winner one at the top of the AB Test, and in most of the cases, the user will publish the winner one. We found that the publish winner button inside the success alert has primary colors and should have success colors.

**Solution**

- Use new markup for ClayAlert with action buttons following this documentation: https://clayui.com/docs/components/alert.html#using-with-claybutton
- Fix custom properties (thanks to @eduardoallegrini) :)

**Screenshot**

Screenshot 2020-11-24 at 10 43 50

### CODE REVIEW

**Comment by dgarciasarai** [comment]
ci:test:sf

**Comment by dgarciasarai** [comment]
ci:test:relevant

**Review by carloslancha — COMMENTED** [review]
js LGTM

**Review by eduardoallegrini — APPROVED** [review]

**Comment by dgarciasarai** [comment]
Waiting until @marcoscv-work gives some feedback on this :)

**Comment by marcoscv-work** [comment]
go ahead with it!

**Comment by dgarciasarai** [comment]
ci:forward

**Pull request closed without merging**
