### PR TITLE
LPS-168383 Add aria-current to the proper navigation

### PR DESCRIPTION
**Pull request by sandrodw3**
Hi guys! This is a follow-up to https://github.com/liferay-frontend/liferay-portal/pull/2978.

After Clay merging https://github.com/liferay/clay/issues/5307, we have discussed the behavior of the `screen-navigation` taglib and we think this new approach is more correct.

The `screen-navigation` taglib has two different navigations, the navigation bar in the top and the vertical navigation (they are optional, users can combine both or use only one of them).

As it's incorrect having the `aria-current` in both navigations, now we will decide in the taglib itself wether we add it to the top navigation bar or to the vertical one (the top one will only have it if the vertical is not present).

So what I do in this PR is:
- Adapt `clay:navigation-bar` taglib so it supports getting the `aria-current` by param, just as the Clay component do
- Remove the `ariaCurrent` param in `screen-navigation` taglib as it doesn't make sense that it's optional, we will always want `aria-current` in one of the navigations
- Apply `aria-current` to the correct navigation in each case in `screen-navigation` taglib

Thanks in advance and please tell me if I can clarify something!

### CODE REVIEW

**Comment by sandrodw3** [comment]
ci:test:sf

**Comment by sandrodw3** [comment]
ci:test:relevant

**Review by carloslancha — COMMENTED** [review]
Hey Sandro!

I see that you're removing `ariaCurrent` attribute from `screen-navigation` Tag. Why is that? Is always going to be `page` or null? The specification of `aria-current` asses that valid values would be `page`, `step`, `location`, `date`, `time`, `true`, and `false`.

Also is kind of weird to me that we call this attribute `ariaCurrent` when there's a possible dynamic attribute called `aria-current`. It could be confusing.

Since the idea of this attribute is to set the type (including false) of the active item's `aria-current`, maybe `activeItemAriaCurrentType` could be more accurate (and the same for the Clay Component, I will tell Matu same thing). If the idea is that it will always should be `page` or `false`, then I'd name it `disableActiveItemAriaCurrent` or something similar.

Could you please explain me what's the goal with more detail? Thx!!

**Comment by sandrodw3** [comment]
Hi Carlos! Thanks for the review and the feedback 😄 I'll try to explain things a bit better.

The PR has two main goals:
- Add support for `aria-current` in `clay:navigation-bar` taglib (now that Matu added it to Clay's component)
- Disable the option of passing `aria-current` as a param to `liferay-frontend:screen-navigation` taglib and decide inside the taglib itself whether we add it to the vertical navigation or the top one.

And answering your questions:

> I see that you're removing `ariaCurrent` attribute from `screen-navigation` Tag. Why is that? Is always going to be `page` or null? The specification of `aria-current` asses that valid values would be `page`, `step`, `location`, `date`, `time`, `true`, and `false`.

About this, the thing is that `liferay-frontend:screen-navigation` taglib can render both top and vertical navigation or only one of them. What I thought was, as the taglib is specifically used for navigation, the `aria-current` there in the active link will always be `"page"`, because it's always indicating the current page. So I thought it wouldn't make sense to pass it from outside, because we will always want to add it to one of the navigations and it will always be `"page"`

> Since the idea of this attribute is to set the type (including false) of the active item's `aria-current`, maybe `activeItemAriaCurrentType` could be more accurate (and the same for the Clay Component, I will tell Matu same thing). If the idea is that it will always should be `page` or `false`, then I'd name it `disableActiveItemAriaCurrent` or something similar.

Regarding this, I actually agree. I put `ariaCurrent` so it was consistent with the name in Clay's component, but I agree with you that something like `activeItemAriaCurrent` would make sense. I will rename it and update the PR. And if you can let Matu know it so he can rename also the Clay's component param, it would be great (we will also have to do the rename in the taglib when Matu does it in Clay).

Please let me know what you think, thanks a lot!

**Comment by sandrodw3** [comment]
Update: I updated the PR renaming `ariaCurrent` to `activeItemAriaCurrent` . If you can let Matu know it so he can rename also the Clay's component param, it would be great (we will also have to update the taglib changing the Clay's component param when he does it).

**Comment by ealonso** [comment]
Since the owner of this component is Echo, we are going to move this pr to @liferay-echo user.

**Comment by ealonso** [comment]
ci:close

**Comment by sandrodw3** [comment]
ci:reopen

**Comment by sandrodw3** [comment]
Hey @ealonso, I didn't know `screen-navigation` taglib belonged to Echo. Considering it, I'm updating the PR leaving only the part related to `clay:navigation-bar`.

Hi Carlos! Thanks for the review and the feedback 😄 

> Since the idea of this attribute is to set the type (including false) of the active item's `aria-current`, maybe `activeItemAriaCurrentType` could be more accurate (and the same for the Clay Component, I will tell Matu same thing). If the idea is that it will always should be `page` or `false`, then I'd name it `disableActiveItemAriaCurrent` or something similar.

Regarding this, I actually agree. I put `ariaCurrent` so it was consistent with the name in Clay's component, but I agree with you that something like `activeItemAriaCurrent` would make sense. I will rename it and update the PR.

Please let me know what you think, thanks a lot!

**Review by bryceosterhaus — APPROVED** [review]
LGTM!

**Comment by carloslancha** [comment]
LGTM. @sandrodw3 [here](https://liferay.slack.com/archives/C049XG98GQL/p1675934486216989?thread_ts=1675933975.500849&cid=C049XG98GQL) is the conversation with Clay about the naming change. We can go with this and update it once the changes are applied in Clay. Thx!

**Comment by carloslancha** [comment]
ci:forward

**Comment by sandrodw3** [comment]
> LGTM. @sandrodw3 [here](https://liferay.slack.com/archives/C049XG98GQL/p1675934486216989?thread_ts=1675933975.500849&cid=C049XG98GQL) is the conversation with Clay about the naming change. We can go with this and update it once the changes are applied in Clay. Thx!

That's cool! Thanks a lot @carloslancha @bryceosterhaus 😄

**Comment by carloslancha** [comment]
@sandrodw3 semver strikes back!

**Comment by sandrodw3** [comment]
> @sandrodw3 semver strikes back!

Hey @carloslancha the semver error is not related to this PR but I have cherrypicked the fix 😄 let's see if it succeed this time

**Comment by sandrodw3** [comment]
ci:forward

**Comment by sandrodw3** [comment]
Forwarding manually since failures are not related: https://github.com/brianchandotcom/liferay-portal/pull/130063.

(cc @ealonso)

**Pull request closed without merging**
