### PR TITLE
LPS-117288 If I have more than one HTML field on a web content I'm not able to edit on click

### PR DESCRIPTION
**Pull request by markocikos**
This is a bugfix, see details and how to reproduce in https://issues.liferay.com/browse/LPS-117288

The root cause are these styles from base CKEditor:
```css
.cke_editable:after {
    border: 1px solid #e7e7ed;
    bottom: 0;
    content: '';
    left: 0;
    position: fixed;
    right: 0;
    top: 0
}
``` 
I could not find these in CKEditor repo, I found them in runtime in a generated merged CSS file. Recently we updated base CKEditor, I'm guessing these were added or changed then.

The styles are defining a full page overlay in `:after`. In this PR, we are overriding styles to hide the overlay. I don't know what problem the overlay is solving, but in our context it seems to be a needless appendage.

This PR also fixes the issue of not being able to mouse-drag select parts of text, that I mentioned in https://github.com/liferay-frontend/liferay-portal/pull/107#issue-448333193

I am not completely sure I added these styles in the right places:
- I added `ckeditor` styles in the theme. This is because `ckeditor` is rendered in an `iframe`
- I added `alloyeditor` styles in `frontend-css-web`, which I hope is a preferred place of adding styles.

### CODE REVIEW

**Comment by markocikos** [comment]
Pinging our css-meister @marcoscv-work  for review. I don't think review request sends a notification.

**Comment by carloslancha** [comment]
Hey @markocikos this should be fixed in `moono-lexicon` skin in `liferay-ckeditor` repo if possible. We moved all the styling there.

**Comment by markocikos** [comment]
@carloslancha Oh no, I was afraid of that. Time to relearn all the fun ways repos build and interact.. :smile:

**Comment by carloslancha** [comment]
hahahaha, it should be easy following all steps and advices on the `README`, but if you need help just let me know!

**Comment by markocikos** [comment]
Followup in https://github.com/liferay/liferay-ckeditor/pull/98

**Pull request closed without merging**
