### PR TITLE
LPS-160316 Use exported utils: `addParams`, `getWindow`, `openWindow`, and `toggleDisabled`

### PR DESCRIPTION
**Pull request by kresimir-coko**

### CODE REVIEW

**Comment by kresimir-coko** [comment]
ci:reevaluate:1297401_4330

**Comment by mateusralv** [comment]
I'm taking a look 🕵🏽

**Comment by mateusralv** [comment]
I [compared with the master ](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=2&testrayRunIdB=1962009074&testrayRunIdA=1962828260&statusB=3)and the results are not related to your PR. 🎉

**Comment by kresimir-coko** [comment]
ci:forward

**Pull request closed without merging**
