### PR TITLE
LRQA-66242 | Take a screenshot of all the rendered pages in each tab of clay sample portlet.

### PR DESCRIPTION
**Pull request by mateusralv**
Background
Create automation tests for take a screenshot of all the rendered pages in each tab of clay sample portlet.

Test Plan
Given: clay sample portlet deployed on page
When: navigate to each page
And when: viewing each screenshot
Then: each nav section of clay sample portlet looks normal

JIRA Ticket:
[LRQA-66242](https://issues.liferay.com/browse/LRQA-66242)

### CODE REVIEW

**Comment by mateusralv** [comment]
ci:test:frontend:nocompile

**Comment by mateusralv** [comment]
ci:test:sf

**Comment by mateusralv** [comment]
ci:test:sf

**Comment by mateusralv** [comment]
ci:test:frontend:nocompile

**Comment by john-co** [comment]
Removed baseline images and refactored in https://github.com/liferay-frontend/liferay-portal/pull/1958

**Pull request closed without merging**
