### PR TITLE
ISSITES 5878 3

### PR DESCRIPTION
**Pull request by allen-ziegenfus**

### CODE REVIEW

**Comment by allen-ziegenfus** [comment]
ci:forward

**Comment by allen-ziegenfus** [comment]
cc: @ryanschuhler 

I removed the public site navigation importer

**Comment by allen-ziegenfus** [comment]
ci:forward

**Comment by allen-ziegenfus** [comment]
ci:forward

**Comment by brittneyq** [comment]
ci:forward

**Comment by allen-ziegenfus** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/129478

**Pull request closed without merging**
