### PR TITLE
[7.4-only] LPS-121853 Renaming in management toolbar to match naming convention

### PR DESCRIPTION
**Pull request by markocikos**
This is a followup on https://github.com/liferay-frontend/liferay-portal/pull/639 and https://github.com/liferay-frontend/liferay-portal/pull/713. See details about the renaming in https://github.com/liferay-frontend/liferay-portal/pull/713#issue-558236868

The change in this PR is based on https://github.com/brianchandotcom/liferay-portal/pull/97913#issuecomment-764516581

@carloslancha @jbalsas @julien @jonmak08

### CODE REVIEW

**Comment by jbalsas** [comment]
Hey @markocikos, I think we should update also all existing usages in this PR so we don't have usages of the old API. Could you take care of that?

I know we could do it as we move along the migration process, but better get it done now so we don't have to remember in each PR in the future.

**Comment by markocikos** [comment]
> I think we should update also all existing usages in this PR so we don't have usages of the old API.

@jbalsas The only existing usage so far is the one in sample-web, and we are updating it in this PR. Other management toolbars are still `-v2`.

**Comment by jbalsas** [comment]
> @jbalsas The only existing usage so far is the one in sample-web, and we are updating it in this PR. Other management toolbars are still -v2.

Got it!!

**Comment by jbalsas** [comment]
ci:forward

**Pull request closed without merging**
