### PR TITLE
LPS-185990 Improve the UX when selecting default values for the dynamic filter

### PR DESCRIPTION
**Pull request by markocikos**
### References

- [LPS-185990 Improve the UX when selecting default values for the dynamic filter](https://issues.liferay.com/browse/LPS-185990)
- This is a followup on https://github.com/liferay-frontend/liferay-portal/pull/3492

### What is the goal of this PR?

I added a fix to CI test, needed as we are changing markup in this PR. @mateusralv please take a look at the change, if maybe something else is needed. Note - this PR is not a priority for Q2 release.

I'm opening a followup PR as I cannot push on Bryce's branch.

### CODE REVIEW

**Comment by mateusralv** [comment]
I'm taking a look 🕵🏽

**Comment by mateusralv** [comment]
Hey @markocikos the failures are not related! 

One doubt, I found a difference between the mockup and the implemented one, is it as expected?

Mockup:
image

PR:
image

[Testray Comparison](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1688135293153&testrayRunIdA=2366214663&testrayRunIdB=2366339993)

**Comment by markocikos** [comment]
@mateusralv Thanks for checking! I'm fairly sure this is fine. Unfortunately, we don't have the latest mockups for this exact case. I believe we concluded it is not needed, since it is very similar to existing [mockups](https://www.figma.com/file/VTOLTBFe99y9kA7AY3TcNR/lps-165276-design-app-to-manage-datasets?type=design&node-id=1777-163286&mode=design&t=GK0WV9aJLPTa6HU1-0) for preselected values of static filters.

**Comment by markocikos** [comment]
I am concerned about the second failure in https://github.com/liferay-frontend/liferay-portal/pull/3514#issuecomment-1614664397, it looks possibly related :thinking: I'll run the test again

**Comment by markocikos** [comment]
ci:forward

**Comment by markocikos** [comment]
@mateusralv I think the test `DataSetViewFilters#SinglePreventsMoreThanOneItem` is not right. It's the one failing [above](https://github.com/liferay-frontend/liferay-portal/pull/3514#issuecomment-1618889420). 

If I'm reading the reports correctly, the relevant steps in the test are:
1. And Preselected Values: car
2. And Select the option single radio button
3. And add another item to Preselected Values
4. Then an error message is displayed 

This does not seem right. Error should appear after the **second** item is added, not first. That's the behavior in PR:

https://github.com/liferay-frontend/liferay-portal/assets/5435511/d1f7a97a-1a1d-4ffb-bd6d-8ac6e12c5c4e

**Comment by mateusralv** [comment]
Hi @markocikos Yes tu está certo! esses são os passos do teste. 

>  Error should appear after the second item is added, not first.

The test does this, notice that in step 1 one item is added: the car:
> 1. And Preselected Values: car

in step 3 the second item is added: bike
> 3. And add another item to Preselected Values

Then it is to return an error because in step two the single option was selected.

Here is the complete test:

> Given the creation of a new data set //Name: Dataset Test 
> //REST Application: /c/fdsfields
> /c/fdsdatefilters
> //REST Schema: FDSField 
> FDSDateFilter
> //REST Endpoint:/ 
> And adding a dataset view 
> //Name: View Test 
> //Description: Description Test 
> And creating a picklist 
> //Use Picklist.addPicklistViaAPI(picklistName = "Transport"); 
> And Add items to the created picklist //Use: Picklist.addPicklistItemViaAPI 
> //Item name: bike, car, and bus 
> And go to the Filters tab inside the View Test 
> And create a new filter 
> //Name: Filter test 
> //Filter by: creator 
> **//Source option: Transport** 
> **//Preselected Values: car** 
> **When the user checks the Single option in the Selection field** 
> **And add another item to Preselected Values** 
> Then an error message is displayed
> And the user can’t save the filter

The test fails in your PR because the dropdown list does not close after selecting the item, I can solve this by adding a click outside the list


https://github.com/liferay-frontend/liferay-portal/assets/44584050/fe3f0c54-a9f5-43ca-b77e-da29135d5b28

I'm not sure if I understood your question, but if you still have any doubts, please let me know.  :smile:

**Comment by markocikos** [comment]
@mateusralv Oh I see. Yeah, you are right, the steps are fine. 

> The test fails in your PR because the dropdown list does not close after selecting the item, I can solve this by adding a click outside the list

Nice catch!

Can you please quarantine the test, or fix it, so we can move forward with PR.

**Comment by mateusralv** [comment]
ci:test:sf

**Comment by mateusralv** [comment]
ci:forward

**Comment by markocikos** [comment]
ci:forward

**Comment by mateusralv** [comment]
ci:test:stable

**Comment by mateusralv** [comment]
ci:test:stable

**Comment by bryceosterhaus** [comment]
sent an update here, https://github.com/liferay-frontend/liferay-portal/pull/3530

**Pull request closed without merging**
