### PR TITLE
LPS-185990 - Update filters UX

### PR DESCRIPTION
**Pull request by bryceosterhaus**
https://liferay.atlassian.net/browse/LPS-185990

### CODE REVIEW

**Comment by mateusralv** [comment]
ci:test:frontend-data-set

**Review by markocikos — APPROVED** [review]
LGTM! :sparkles:

**Comment by markocikos** [comment]
ci:forward

**Comment by markocikos** [comment]
ci:forward

**Comment by markocikos** [comment]
ci:forward

**Comment by markocikos** [comment]
Followup in https://github.com/liferay-frontend/liferay-portal/pull/3514

**Pull request closed without merging**
