### PR TITLE
LPS-156268 Apply Clay classes when it has animation so the content is centered and well spaced

### PR DESCRIPTION
**Pull request by sandrodw3**
/cc @john-co 

Hi guys! This is a follow-up of https://github.com/liferay-frontend/liferay-portal/pull/2359, and contains a fix for a regression I caused with the first PR 😅

I have added some CSS classes that are used here: https://clayui.com/docs/components/empty-state/markup.html. I'm adding `c-empty-state-animation` when it has an animation so the correct margin is applied and the content is centered. Adding it only when it has animation also makes this case work as expected:

image

This one won't be affected by `c-empty-state-animation` so it will remain left aligned.

Please let me know what you think.

Thanks! 🥰

### CODE REVIEW

**Review by diegonvs — APPROVED** [review]
Nice! It solves https://issues.liferay.com/browse/LPS-156413 too! Thanks :)

**Comment by diegonvs** [comment]
Hey @sandrodw3, I was going to link LPS-156268 with https://issues.liferay.com/browse/LPS-156413, but I noticed you hadn't started progress on it. I was going to assign https://issues.liferay.com/browse/LPS-156413 to you -> FE Infra and link with the Test Scenarios Coverage issue, but I'm not sure if it will cause any misunderstanding, So I'll keep it intact 😂

**Comment by sandrodw3** [comment]
Hi @diegonvs! I'm so sorry to have caused https://issues.liferay.com/browse/LPS-156413 😞I think it's a good idea to link it to this one, so everyone knows it will be fixed with this PR. I'm going to link it and leave a comment if you are ok with that 😄

**Comment by sandrodw3** [comment]
ci:test:relevant

**Comment by john-co** [comment]
ci:test:relevant

**Comment by john-co** [comment]
Reviewed. Test failures are unrelated. :heavy_check_mark: 

Ok to manually forward from QA perspective. I'll go ahead and manually forward after doing a quick manual check for the blocker bug.

**Comment by john-co** [comment]
forwarded to https://github.com/brianchandotcom/liferay-portal/pull/119256

**Pull request closed without merging**
