### PR TITLE
LPS-158049 Support a new type of portlet header to add <script type="module"> scripts

### PR DESCRIPTION
**Pull request by izaera**

### CODE REVIEW

**Comment by izaera** [comment]
ci:test:relevant

**Comment by izaera** [comment]
ci:test:relevant

**Review by bryceosterhaus — APPROVED** [review]
LGTM

**Comment by mateusralv** [comment]
ci:test:relevant

**Comment by mateusralv** [comment]
ci:test:relevant

**Comment by izaera** [comment]
ci:test:sf

**Comment by izaera** [comment]
ci:test:relevant

**Comment by izaera** [comment]
Same for StructuredContentFilteringAndSorting#CanFilterGreaterThanPriorityValuesSortedDescending  (fails on master locally)

**Comment by izaera** [comment]
The third one is failling locally too. Usually I get this in the JS console:

image

**Comment by Esther-OC** [comment]
Failures are not related to the PR, so it is ok to move forward from QA perspective.

**Comment by izaera** [comment]
Sent manually https://github.com/brianchandotcom/liferay-portal/pull/120568

**Pull request closed without merging**
