### PR TITLE
[7.4-only] LPS-102111 Remove sidebar compat layer

### PR DESCRIPTION
**Pull request by marcoscv-work**
From https://github.com/liferay-frontend/liferay-portal/pull/547 /cc @zhangyan0701 @pat270 
---
https://issues.liferay.com/browse/LPS-102111

This is from PR https://github.com/liferay-frontend/liferay-portal/pull/524 with the fix of the tests.

### CODE REVIEW

**Comment by marcoscv-work** [comment]
ci:test:sf

**Comment by marcoscv-work** [comment]
ci:test:relevant

**Comment by marcoscv-work** [comment]
ci:test:relevant

**Comment by john-co** [comment]
Reviewed. Test failures are unrelated. :heavy_check_mark: 

The failing test looks like it appears in upstream results: https://testray.liferay.com/home/-/testray/cases/1310724267

Can try retesting or manually forward to BChan. However, there looks like a rebase conflict that needs to be addressed first.

**Comment by pat270** [comment]
See #574

**Pull request closed without merging**
