### PR TITLE
LPS-147202 | Add test to verify admin can receive request to approve remote app

### PR DESCRIPTION
**Pull request by susanchen3**
Background
Create automated tests for remote apps workflow

Test Plan

- apply workflow process to remote apps
- add a user with permissions to create remote apps
- create remote app as user with permissions
- assert admin received notification to approve remote app

JIRA Ticket:
https://issues.liferay.com/browse/LPS-147202

### CODE REVIEW

**Comment by susanchen3** [comment]
ci:test:frontend:nocompile

**Comment by susanchen3** [comment]
Failures don't related to my changes, DatePicker.es.js failure (I've been seeing these a lot lately :thinking:) and time out/invalid session id on the Clay test

**Comment by john-co** [comment]
cc/ @matuzalemsteles , looks like the DatePicker js unit test has been flaky...I think we'll need to disable the test for now until we have a fix for it.

**Review by john-co — APPROVED** [review]
Looks good to me! :rocket:

**Comment by john-co** [comment]
ci:forward

**Pull request closed without merging**
