### PR TITLE
[TS] LPS-139791

### PR DESCRIPTION
**Pull request by crodriguezy**
Steps to reproduce:

In portal-ext.properties include fr_CI (Cote d'Ivoire language) in locales and locales.enabled properties.
Start the server.
Go to Site's Configuration -> Site Settings ->Site Configuration
Expected result: no errors in console.

Current result: you can see a js error in the console: "Uncaught syntax error: Unexpected identifier".

It is caused by fr_CI English (and French) display name: French (Cote d'Ivoire), which is included with the unescaped apostrophe in top_js.jspf.

You can check the details in https://issues.liferay.com/browse/LPS-139791, and this is a related issue: https://issues.liferay.com/browse/LPS-131814

I've escaped again, this time in taglib input_localized, each available language displayName to avoid apostrophes, which may be frequently found in some languages names (especially french ones, L'Antartique also, for example), from being interpreted as closing quotes and provoque navigation errors.

### CODE REVIEW

**Review by diegonvs — APPROVED** [review]
Nice!

**Comment by diegonvs** [comment]
Hey @liferay-lexicon, when playing with this locale I found there is a missing flag:

Screen Shot 2021-09-27 at 13 02 20


and when taking a look in [Clay Icons at flags section](https://clayui.com/docs/components/icon.html) I noticed Cote d'Ivoire flag is missing but [other flags for non-default-localed](https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/portal.properties#L3015) like `lo-la - Lao - Laos` is there. Is this flag missing?

**Comment by diegonvs** [comment]
@markocikos @carloslancha can I hit the forward button?

**Comment by carloslancha** [comment]
LGTM

**Comment by diegonvs** [comment]
ci:forward

**Pull request closed without merging**
