### PR TITLE
LPS-140010 Remove npm bridges where possible

### PR DESCRIPTION
**Pull request by victorg1991**
Rebase of https://github.com/liferay-frontend/liferay-portal/pull/1515

> This is part 1 of the LPS. I'm removing as much as I can here except for commerce, that I will address in a following PR/commits.
> 
> I'm sending this for review and CI testing to check if something has been broken.
> 
> I haven't removed bridges completely from:
> 
> ./modules/apps/frontend-js/frontend-js-web/.npmbridgerc
> ./modules/apps/frontend-js/frontend-js-metal-web/.npmbridgerc
> ./modules/apps/frontend-taglib/frontend-taglib-clay/.npmbridgerc
> This is because these where added to support backwards compatibility with frontend-js-web utilities, metal library, and the old clay library (not @clayui/... but clay-*).
> 
> I'm not sure if this compatibility can be removed already. Any insight on this would be much appreciated.

Checked locally and all seems to be working fine, let's see what the ci have to say about it

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:test

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:test

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
Checking the test result test failure doesn't seem related. could you help me verifying that? @magjed4289 @Esther-OC @john-co  😇  many thanks!!

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by john-co** [comment]
Just started reviewing :)

**Comment by john-co** [comment]
Reviewed. Test failures are unrelated. :heavy_check_mark: 
May manually forward if ready

- Looks like there's random flaky issues with either CI or the test in the most recent runs.

**Comment by victorg1991** [comment]
Manually forwarded here: https://github.com/brianchandotcom/liferay-portal/pull/111359

**Pull request closed without merging**
