### PR TITLE
LPS-118955, LRQA-60886 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-118955
https://issues.liferay.com/browse/LRQA-60886

This is only for master.

@izaera
@pavel-savinov

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by izaera** [comment]
This should be forwarded after the fix in #237 is merged. However, because this PR already includes the fix, I suppose we can close #237. @pavel-savinov do you agree ?

**Comment by pavel-savinov** [comment]
@izaera Yep, 100%. Closed.

**Comment by izaera** [comment]
ci:forward

**Pull request closed without merging**
