### PR TITLE
LPS-146978 Update dateFormat in rest builder

### PR DESCRIPTION
**Pull request by LuismiBarcos**
Comes from [here](https://github.com/liferay-frontend/liferay-portal/pull/1900)
___ 
**Description**

- Our REST builder defines a [SimpleDateFormat](https://docs.oracle.com/javase/8/docs/api/java/text/SimpleDateFormat.html) object with the general pattern yyyy-MM-dd HH:mm:ss timezone
- But it seems there was a typo defining that pattern related to the timezone, maybe because of a quoted 'T' letter added between date and time: we did the same with 'Z' letter (it is quoted)
- So, the pattern is defined as yyyy-MM-dd'T'HH:mm:ss'Z' and then, the quoted 'Z' (timezone) is not interpreted during formatting.

### CODE REVIEW

**Comment by LuismiBarcos** [comment]
FYI @samanzanedo @javierdearcos I've executed the rest builder with the new date format. Let's see if any test fails or forward it.

**Comment by LuismiBarcos** [comment]
See comment [here](https://issues.liferay.com/browse/LPS-146978)

**Comment by LuismiBarcos** [comment]
After a deeper investigation, we realize that we should use the pattern `yyyy-MM-dd'T'HH:mm:ssXX`. So, if we receive a Date with offset, we are able to parse the Date into UTC Date taking into account the offset of the date. Also, the Date returned will be the Date in UTC (with a Z at the end) but calculating correctly the hours.
So, this maintains the format that we use in the REST APIs, so there should be no errors with this.
What do you think @javierdearcos ?

cc/ @samanzanedo

**Comment by LuismiBarcos** [comment]
ci:test:sf

**Comment by LuismiBarcos** [comment]
ci:test:relevant

**Comment by javierdearcos** [comment]
ci:forward

**Review by javierdearcos — APPROVED** [review]

**Comment by javierdearcos** [comment]
> I understand that this way we support both cases. dates like "2022-01-01T09:00Z" and "2022-01-01T09:00+02" or "2022-01-01T09:00+02:00" or any offset, is that right?

I saw your answer about the date format in slack. Don't need to answer

**Comment by LuismiBarcos** [comment]
ci:forward

**Comment by LuismiBarcos** [comment]
Errors seem not related to the changes, trying again

**Comment by LuismiBarcos** [comment]
ci:forward

**Comment by LuismiBarcos** [comment]
ci:test:relevant

**Comment by javierdearcos** [comment]
ci:forward

**Pull request closed without merging**
