### PR TITLE
LPS-192272 Adding tests for the new CX Filter

### PR DESCRIPTION
**Pull request by JerryAdrianoo**
**Description:** 
Adding tests for the new CX Filter.

**Jira Ticket:** 
https://liferay.atlassian.net/browse/LPS-192272

### CODE REVIEW

**Comment by JerryAdrianoo** [comment]
ci:test:frontend

**Comment by JerryAdrianoo** [comment]
ci:test:frontend

**Comment by JerryAdrianoo** [comment]
@CarlosBrichete these failures are not related :)

**Comment by JerryAdrianoo** [comment]
ci:test:sf

**Review by CarlosBrichete — APPROVED** [review]
LGTM

**Comment by JerryAdrianoo** [comment]
ci:forward

**Comment by JerryAdrianoo** [comment]
ci:forward

**Comment by JerryAdrianoo** [comment]
ci:stop

**Pull request closed without merging**
