### PR TITLE
Frontend CX is not registered when deployed from workspace and only enabled via the Feature Flags UI in Instance Settings.

### PR DESCRIPTION
**Pull request by ethib137**
https://liferay.atlassian.net/browse/LPD-21008

CompanyId is needed for instance scoped feature flags.

### CODE REVIEW

**Comment by ethib137** [comment]
ci:test:sf

**Comment by ethib137** [comment]
ci:test:relevant

**Comment by dsanz** [comment]
Thanks a lot @ethib137 I'd say this is behind some messages we saw recently. 

We need to check a few tickets here as I believe they're connected:

- https://liferay.atlassian.net/browse/LPD-21008 (this one)
- https://liferay.atlassian.net/browse/LPD-19408 
- https://liferay.atlassian.net/browse/LPD-16005

cc @izaera @herrardo @pablo-agulla

**Comment by izaera** [comment]
Shall we forward this? It's all green...

**Comment by izaera** [comment]
> Shall we forward this? It's all green...

Nobody said anything in 4 days so I guess I'll forward it :shrug:

**Comment by izaera** [comment]
ci:forward

**Comment by izaera** [comment]
> We need to check a few tickets here as I believe they're connected: [...]

Once this is merged we can check and close them according to the results...

**Pull request closed without merging**
