### PR TITLE
LPS-178778 | FrontendDataSetViews#ErrorAppearsWhenNameBlank

### PR DESCRIPTION
**Pull request by abhnerramos**
**Description**
Confirm the error message that appears when the user tries to create a Data Set without the filled provider.

**Steps**
- Given access Datasets admin page
- When The user goes to add 
- And choose the Provider called channel
- And clicking on the Save button
- Then Confirm that "This field is required" alert messages are present in the name field

**JIRA Ticket**
https://issues.liferay.com/browse/LPS-178778

### CODE REVIEW

**Comment by abhnerramos** [comment]
ci:test:frontend

**Comment by abhnerramos** [comment]
ci:test:sf

**Comment by abhnerramos** [comment]
ci:test:frontend

**Comment by eltonccdantas** [comment]
ci:test:frontend

**Pull request closed without merging**
