### PR TITLE
LPS-116361 Adds Admin Portlet for Remote Apps

### PR DESCRIPTION
**Pull request by brunobasto**
Originally https://github.com/liferay-frontend/liferay-portal/pull/200
Previously https://github.com/liferay-frontend/liferay-portal/pull/231 and then https://github.com/liferay-frontend/liferay-portal/pull/235 and then https://github.com/liferay-frontend/liferay-portal/pull/245 then https://github.com/liferay-frontend/liferay-portal/pull/248 then https://github.com/liferay-frontend/liferay-portal/pull/252 then https://github.com/liferay-frontend/liferay-portal/pull/261 then https://github.com/liferay-frontend/liferay-portal/pull/265

Applied changes requested here: https://github.com/brianchandotcom/liferay-portal/pull/92818#issuecomment-675205149

### CODE REVIEW

**Comment by brunobasto** [comment]
ci:test:sf

**Comment by brunobasto** [comment]
ci:test:sf

**Comment by brunobasto** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
ci:forward

**Pull request closed without merging**
