### PR TITLE
LPD-7932 - Update DXP modules to ESM

### PR DESCRIPTION
**Pull request by bryceosterhaus**
https://liferay.atlassian.net/browse/LPD-7845

rebased on https://github.com/liferay-frontend/liferay-portal/pull/3984

### CODE REVIEW

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
The most recent failure occurred because this branch now has a merge conflict with upstream master. I've confirmed this locally as well.
```
Could not apply 6baab43ff3641... LPD-7932 - Update template-web module to ESM
```

**Comment by pyoo47** [comment]
ci:test:relevant:norebase

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
ci:test:sf

**Comment by bryceosterhaus** [comment]
ci:report:2538228172

**Comment by bryceosterhaus** [comment]
ci:forward:force

**Pull request closed without merging**
