### PR TITLE
[7.4-only] LPS-112478 Deprecate labelStylesMap attribute

### PR DESCRIPTION
**Pull request by julien**
We're deprecating the `labelStylesMap` attribute for `<clay:file-card />`, `<clay:image-card />` and `<clay:vertical-card />`, the reason is that this was added in clay 2.x to be able to map labels with styles and ended up being unused. 

There are no usages, and this isn't needed in for our clay 3.x tags.

### CODE REVIEW

**Comment by julien** [comment]
ci:test:sf

**Comment by julien** [comment]
ci:test:relevant

**Review by carloslancha — APPROVED** [review]
LGTM

image
😱 😝

**Comment by julien** [comment]
I'll add that @carloslancha good point

**Comment by carloslancha** [comment]
ci:test:stop

**Comment by carloslancha** [comment]
ci:stop

**Comment by carloslancha** [comment]
ci:test:sf

**Comment by carloslancha** [comment]
ci:test:relevant

**Comment by carloslancha** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
ci:forward

**Pull request closed without merging**
