### PR TITLE
LPS-167912 Change cancel link into button for accessibility improvement

### PR DESCRIPTION
**Pull request by edalgrin**
This PR fixes the accessibility issue with the cancel link in the Open Graph section of the page configuration

accessibility-1

### CODE REVIEW

**Comment by mateusralv** [comment]
ci:test:sf

**Comment by edalgrin** [comment]
ci:test:sf

**Comment by edalgrin** [comment]
ci:test:relevant

**Comment by eltonccdantas** [comment]
Hey @edalgrin , it's all green now, feel free to forward it if no other dev review is needed.

**Comment by edalgrin** [comment]
ci:forward

**Pull request closed without merging**
