### PR TITLE
LPS-145116 - Apply new icons API to rest of portal

### PR DESCRIPTION
**Pull request by bryceosterhaus**
Rebased on top of https://github.com/brianchandotcom/liferay-portal/pull/117185

Aim of this PR is to apply new icons API throughout DXP and see how CI feels about this.

### CODE REVIEW

**Comment by bryceosterhaus** [comment]
ci, plz treat me nicely

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by susanchen3** [comment]
Taking a look now :mag:

**Comment by susanchen3** [comment]
I'm sure I've missed a lot of failures, but here is the bulk of what is failing on this [run](https://github.com/liferay-frontend/liferay-portal/pull/2231#issuecomment-1127889328): 

### Blogs
**Unable to Select File**
- **Steps**: Create new Blog Entry
- **Result**: "Select File" button is unclickable

**Unable to publish entry**
- **Steps**: Create new Blog Entry> click "Publish"
- **Result**: nothing happens, doesn't publish blog

**Unable to upload image**
- **Steps**: Create new Blog Entry > click on "Add" button for Content field > Insert Image > Select File > Upload an Image
- **Result**: nothing happens, image doesn't upload

**Unable to edit friendly URL**
- **Steps**: Create new Blog Entry > Configuration > switch URL to "Custom" > try to add input for "Friendly URL"
- **Result**: unable to type anything

**Unable to edit abstract**
- **Steps**: Create new Blog Entry > Configuration > switch Abstract to "Custom Abstract" > try to add input for "Description"
- **Result**: unable to type anything

**User avatar icon**
- **Steps**: Create new Blog Entry
- **Result**: User avatar background color is black, should be white and should be locatable with "//span[@class='user-avatar-link']//span[*[name()='svg'][contains(@class,'lexicon-icon-user')]]"

### Pages
**Browser**
- **Steps**: Create Content Page > navigate to content page > click Browser on left side
- **Result**: "Refresh" button appears
**Expected**: page tree should be displayed

**Dropdown component**
- **Steps**: Create Content Page > navigate to content page > drag to add "Dropdown" basic component to page
- **Result**: throws a Freemarker error

**Add image**
- **Steps**: Pages > Configure "Search" page > Open Graph > click "Select" under Image > click "+" button
- **Result**: unable to add new image, I don't think this is unique to Open Graph Image iframe only

### Page Templates
- **Steps**: Design > Page Templates > Display Page Templates > click "+" > click "Blank" card
- **Result**: nothing happens
- **Expected**: iFrame should pop up to add Display Page Template

### Documents and Media
**Management Toolbar**
- **Steps**: Content and Data > Documents and Media > click on "+"
- **Result**: unable to add new document and media and click on anything in the management toolbar

**Search**
- **Steps**: Content and Data > Documents and Media > type something in the search bar
- **Result**: "Please select a tool from the left menu."

### Forms
**Management Toolbar**
- **Steps**: Content and Data > Forms> click on "+"
- **Result**: unable to add new form and click on anything in the management toolbar

**Dropdown Menu (If able to create Form)**
- **Steps**: Create new Form Entry > navigate back to Forms home page > click on vertical ellipsis of created form
- **Result**: clicking on vertical ellipsis doesn't display dropdown menu

**Search**
- **Steps**: Content and Data > Forms > type something in the search bar
- **Result**: "Please select a tool from the left menu."

### Sites
**Speedwell and Minium**
- **Steps**: Create new site called speedwell with Speedwell template > navigate to http://localhost:8080/group/speedwell
- **Result**: "An unexpected system error occurred" (same with minium template)

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by susanchen3** [comment]
Not sure if you wanted a second round of analysis but the fixes narrowed it down to:

**A good amount of tests are failing with**
```
     [exec] 2022-05-17 10:30:47.912 ERROR [http-nio-8080-exec-5][PasswordModifiedFilter:62] java.lang.NullPointerException
     [exec] java.lang.NullPointerException: null
     [exec] 	at com.liferay.frontend.icons.web.internal.util.SVGUtil.getSVGSpritemap(SVGUtil.java:97) ~[?:?]
     [exec] 	at com.liferay.frontend.icons.web.internal.servlet.FrontendIconsServlet.doGet(FrontendIconsServlet.java:122) ~[?:?]
```
[on CI](https://testray.liferay.com/reports/production/logs/2022-05/test-1-29/test-portal-acceptance-pullrequest(master)/2953/functional-tomcat90-mysql57-jdk8/5/19/jenkins-console.txt.gz?authuser=0), not sure how to reproduce locally because the tests pass locally

**Lots of commerce test failures**
- **Steps**: Create new site with minium or speedwell template > navigate to http://localhost:8080/web/minium or http://localhost:8080/web/speedwell
- **Result**: "An unexpected system error" and [freemarker error](https://gist.github.com/susanchen3/c72ac696cd50bc864fce76cdff3477bc) thrown in console 

**Dropdown**
- **Steps**: Create content page > Add "Dropdown" to page 
- **Result**: [freemarker error](https://gist.github.com/susanchen3/6850597df750b7eb7e5b912bfd1425bb) thrown in console, unable to add Dropdown

**Comment by bryceosterhaus** [comment]
Thank you @susanchen3! Very helpful feedback

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
> [portal-license-smoke-jdk8/0/0](https://testray.liferay.com/home/-/testray/case_results/1852973151), [lpkg-controller-jdk8/0/0](https://testray.liferay.com/home/-/testray/case_results/1852970884), and failing with

Hmm, I've never seen these fail before. Do you know how I would be able to reproduce locally?

Same for the nullpointers... I can't seem to reproduce locally. I will add a null check and re-test though

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by susanchen3** [comment]
I think it's related to the command Summer posted before: https://github.com/liferay-frontend/liferay-portal/pull/1892#issuecomment-1035917150 

Although I think `${artifact.location.src}` i supposed to be replaced with a file

**Comment by bryceosterhaus** [comment]
> I think it's related to the command Summer posted before: https://github.com/liferay-frontend/liferay-portal/pull/1892#issuecomment-1035917150

This seems really odd to have this failure, because I haven't updated anything to commerce themes that would effect the generation of the .war files...

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by susanchen3** [comment]
ok I think I understand now :D 

For the `frontend-icons` app, you are replacing `.lfrbuild-releng-ignore` with `.lfrbuild-portal` so you want to build the app.

To build the app locally here are the steps I took to reproduce the error:
1. Navigate to `master-portal/modules`
2. Run 
```
ant build-app-lpkg -Dapp.name=frontend-icons -Dosgi.dir=<liferay osgi folder location>  -Dliferay.home=<liferay home location> -Dproject.dir=<liferay source location>
```
which gave me [BUILD FAILED](https://gist.github.com/susanchen3/17729e7c6ea592527570ce980c53dc92), same as CI.

3. Now run
```
ant build-app -Dapp.name=frontend-icons -Dapp.version=1.0.0
```
which gave me [Missing artifact.properties file](https://gist.github.com/susanchen3/461543d5ac6d88e52c53d3337e0ba759) error.

I think the artifact.properties file needs to be generated (ex. [frontend-js-a11y-web artifact.properties](https://github.com/liferay/liferay-portal/blob/master/modules/.releng/apps/frontend-js/frontend-js-a11y-web/artifact.properties)), which needs [jars from the nexus](https://repository-cdn.liferay.com/nexus/content/repositories/liferay-public-releases/com/liferay/). Bchan may need to help with that according to Step 2 [here](https://liferay.atlassian.net/wiki/spaces/QA/pages/1615495658/Marketplace+App+JIRA+Workflow#Marketplace-App-Release-Testing-Workflow).

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by susanchen3** [comment]
Test failures are unrelated :heavy_check_mark:  Looks good from QA perspective 

[Comparison run:](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=2&testrayRunIdB=1857310638&testrayRunIdA=1857311579&statusB=3) 
- [modules-semantic-versioning-jdk8/0/0](https://testray.liferay.com/home/-/testray/case_results/1857327723) not unique to this PR
- Other tests are flaky and not unique to this PR

**Comment by bryceosterhaus** [comment]
manual forward https://github.com/brianchandotcom/liferay-portal/pull/117881

**Pull request closed without merging**
