### PR TITLE
LPS-149012 Update alloy-ui to 3.1.0-deprecated.91

### PR DESCRIPTION
**Pull request by rolandpakai**
Hi Team,

could you please push this forward?

The new alloyUI version is fixing the following issue: https://issues.liferay.com/browse/LPS-149012

This is the original alloy-ui issue:
https://github.com/liferay/liferay-frontend-projects/issues/879

### CODE REVIEW

**Comment by rolandpakai** [comment]
Hi @liferay-frontend 

could you please review my PR?

Thanks, Roland

**Review by markocikos — APPROVED** [review]
LGTM! Sorry for late response!

**Comment by markocikos** [comment]
ci:forward

**Comment by rolandpakai** [comment]
Thanks for the review @markocikos

**Pull request closed without merging**
