### PR TITLE
LPS-168138 Add role="button" to order link in MT

### PR DESCRIPTION
**Pull request by carloslancha**

### CODE REVIEW

**Comment by deborasoliveira** [comment]
ci:test:relevant

**Comment by carloslancha** [comment]
ci:reevaluate:1397401_3400

**Comment by carloslancha** [comment]
@deborasoliveira could you please take a look to confirm failing tests are not related? Thx!!

**Comment by deborasoliveira** [comment]
sure @carloslancha! I'll take a look at it 👍🏽

**Comment by deborasoliveira** [comment]
Hi @carloslancha! 
According to the [comparison](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=2&testrayRunIdB=2219055339&testrayRunIdA=2217658160&statusB=3), the failures seem to be not related to this PR.

- _LocalFile.PortalSmokeUpgrade#ViewPortalSmokeArchive7413_ is a flaky failure. 

- _LocalFile.Permissions#CannotConfigureBlogsPortletAsGuestPG_ and _LocalFile.StagingUsecaseWithVersioning#StagingPublishLast_ failure occurred before the execution of the tests.  After downloading this PR bundle and running the tests locally, they succeeded in their execution.

**Comment by carloslancha** [comment]
Nice, thx @deborasoliveira !

**Comment by carloslancha** [comment]
ci:forward:force

**Pull request closed without merging**
