### PR TITLE
LPS-124521 Card view-style uses .lfr-asset-item width. If an item has a long name, 50% width will make the view unreadable in mobile view. We can remedy this using 100% width instead.

### PR DESCRIPTION
**Pull request by brianikim**
Resending from: https://github.com/liferay-frontend/liferay-portal/pull/601

Card view-style uses .lfr-asset-item width. If an item has a long name, 50% width will make the view unreadable in mobile view. We can remedy this using 100% width instead.

**Test plan:**

1. Log into a Liferay DXP 7.3 bundle
2. Create an additional site or two, one should have a longer name
3. Access the bundle via a mobile device or using a browser's developer tools
4. On the main landing page click on the user's Avatar -> My Sites -> Select Sites -> My Sites or Recent

### CODE REVIEW

**Comment by brianikim** [comment]
**Before**
Before
**After**
After

**Comment by pat270** [comment]
This LGTM!

**Comment by jbalsas** [comment]
> This LGTM!

Forward it then, @pat270 !! 😉

**Comment by pat270** [comment]
ci:forward

**Pull request closed without merging**
