### PR TITLE
[TS] LPS-111067 Persist Display Style in additional menus

### PR DESCRIPTION
**Pull request by wanderlast**
This is an addition to a pre-existing ticket: https://issues.liferay.com/browse/LPS-111067

It uses the new Util established in LPS-111067 and applies the pattern to a handful of portlets that were accidentally overlooked in the initial PR. Since this is mostly just covering a previous gap, I've included it as a part of LPS-111067, but please let me know if I should create a new LPS for it. Thanks!

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:forward

**Comment by jbalsas** [comment]
Test failures look unrelated... going to try again and forward manually if nothing stands out

**Comment by jbalsas** [comment]
ci:forward

**Comment by jbalsas** [comment]
Hey @wanderlast, could you double check the test failures? Since both happened twice in a row, they might be related.

@zhangyan0701, @john-co, @calvinctvo, could you take a look to help us decide if they're indeed related or not?

Thanks!

**Comment by john-co** [comment]
Just started reviewing :)

**Comment by john-co** [comment]
ci:test:bundle

**Comment by john-co** [comment]
[Related]
- Test Fix - It's looking like a test fix on path locators since the screenshots and test steps look normal up to where the test stops. Seems to make sense since there are changes to the Site membership and navigation portlet which is where the test stops. I'll check manually on the test bundle.

**Comment by john-co** [comment]
[Related]
- SiteMemberships#OrganizationsView - the test macro by default assumes a table display style but and the test tries to assert a table entry but fails because PR has made display style changes persist. This will require a refactor in the Site.viewMemberOrganizationCP macro and or testcase to account for previously changing the display style. Probably better to forward to qa echo to fix their tests to account for this since there may be more of their sites and site membership tests affected. cc/ @david-gutierrez-mesa 
- NavigationMenuWidgetUseCase#NavigationMenuConfigureDisplayTemplate - update needed to path locator. I think there's an improper assertion with the test to begin with. The test was trying to assert the active page and works in upstream because there's an extra navigation portlet. However, with the updates from this PR, it causes both navigation portlets to change their display style so then the path locator assertion doesn't work. I think the path locator could be updated to fix this.

https://user-images.githubusercontent.com/35235266/109371142-63197500-7858-11eb-8d14-1e0e6b402024.mp4

**Comment by john-co** [comment]
@wanderlast , if NavigationMenuWidgetUseCase#NavigationMenuConfigureDisplayTemplate passes please include the test fix commit from https://github.com/john-co/liferay-portal/pull/382.

Will still need echo qa to review and fix affected Site tests.

**Comment by Tim-Cao** [comment]
Hi @john-co, @wanderlast and @wanderlast, there is a regression issue caused by this PR. NavigationMenuWidgetUseCase#NavigationMenuConfigureDisplayTemplate this one should be a regression bug.
The display template of default Navigation Menu widget (on navbar) shouldn't be affected by other ones.
*Step to reproduce:*
# Add a widget page
# Assert the display template of default Navigation Menu (on navbar) is **Bar minimally styled**
# Add a Navigation Menu portlet to page
# Click the ellipsis button of Navigation Menu > Configuration > Configuration
# Select the **Split Button Dropdowns** in Display Template > Save
# Close the modal
# Assert the display template of new Navigation Menu is **Split Button Dropdowns**
# Assert the display template of default Navigation Menu (on navbar) is still **Bar minimally styled**
# Navigate to widget page again

*Expected Results:*
The display template of default Navigation Menu (on navbar) should be still **Bar minimally styled**

*Actual Results:*
The display template of default Navigation Menu (on navbar) becomes **Split Button Dropdowns**
Actual

**Comment by Tim-Cao** [comment]
Hi @wanderlast,
I've sent test fix about SiteMemberships#OrganizationsView here, could you cherry-pick my commit before next run.

**Comment by wanderlast** [comment]
I've cherry-picked to include @Tim-Cao's test fix.

**Comment by john-co** [comment]
So that we're on the same page, @Tim-Cao is saying that the behavior of the NavigationMenuWidgetUseCase#NavigationMenuConfigureDisplayTemplate with Split Button Dropdown affecting other navigation portlets is a bug. @wanderlast , can you confirm what we should expect?

**Comment by wanderlast** [comment]
@john-co I've looked into it and I believe @Tim-Cao is correct and it's an unintended regression. I've removed the code that causes the change, so it should be fine now.

**Comment by john-co** [comment]
ci:test:relevant

**Comment by john-co** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by john-co** [comment]
[Unrelated]
- LocalFile.CommerceSmoke#PublishSimpleProduct - flaky commerce test @lorenzolapescara. Looks like the test opens an iframe but b/c SelectFrame.selectFrameNoLoading is used, it doesn't wait long enough for the iframe to fully render and fails to see iframe. Likely just need to replace that failing test step with `SelectFrame(locator1 = "IFrame#MODAL_BODY");` which has an inbuilt waitfor modal listener.

**Comment by john-co** [comment]
Reviewed. Test failures are unrelated. :heavy_check_mark: Ok to manually forward.

**Comment by jbalsas** [comment]
And green now, so off we go!!

**Comment by jbalsas** [comment]
ci:forward

**Pull request closed without merging**
