### PR TITLE
[WIP] unstyled and styled themes mix

### PR DESCRIPTION
**Pull request by marcoscv-work**
This PR is only a test to prove if it is possible and easy or not

### CODE REVIEW

**Comment by marcoscv-work** [comment]
ci:stop

**Comment by pat270** [comment]
Just curious how this will affect users upgrading from older versions that based their theme on styled?

**Comment by jbalsas** [comment]
Hey @pat270, the idea I had and discussed with @david-truong and @dsanz was to provide this through tooling, so during upgrade, if you're extending `styled` (or `admin`) we will make sure your theme has the proper sets.

I haven't checked this PR yet, but that means we should make it easy to overlay and somewhat keep the themes composeable so we can simply add or remove `imports` to move from one base theme (styled) to others (classic, admin).

**Comment by marcoscv-work** [comment]
This PR is only a test to prove if it is possible and easy or not :-D

**Comment by jbalsas** [comment]
> This PR is only a test to prove if it is possible and easy or not :-D

Soo... what was the conclusion, was it or not? 😂 

Going to close here for cleaning purposes. We can discuss about this later this week as we work through our next steps.

**Pull request closed without merging**
