### PR TITLE
LPS-155507 Fix API Explorer

### PR DESCRIPTION
**Pull request by LuismiBarcos**
Related ticket -> [LPS-155507](https://issues.liferay.com/browse/LPS-155507)

Fix API Explorer getting access to the spritemap without the Liferay JS Object as the API Explorer does not have access to the Liferay Object.

To try this, just get this branch and deploy the module `modules/apps/headless/headless-discovery/headless-discovery-web`

### CODE REVIEW

**Comment by LuismiBarcos** [comment]
@bryceosterhaus I revert some of your changes as this broke the API Explorer. If you could take a quick look it would be great. In another case, I will send the PR to Brian.
Thanks for your help 🙂 

cc/ @ccorreagg

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by kresimir-coko** [comment]
@LuismiBarcos @dsanz I see that the original PR - the one that caused the issue had more changes than just this one. If you are aware of that and if in your tests reverting just the big change works then go for it. I don't see anything wrong with this.

**Comment by LuismiBarcos** [comment]
ci:forward

**Comment by LuismiBarcos** [comment]
Please CI, be good with me

**Comment by joanagrego** [comment]
Just starting reviewing :)

**Comment by bryceosterhaus** [comment]
Thanks for the heads up @LuismiBarcos! I will send a follow up PR with a proper fix for my initial PR and not break your stuff

**Pull request closed without merging**
