### PR TITLE
LPS-141228 Remote apps test automation

### PR DESCRIPTION
**Pull request by Esther-OC**
Solving rebase conflicts from https://github.com/brianchandotcom/liferay-portal/pull/111420

### CODE REVIEW

**Comment by Esther-OC** [comment]
ci:forward

**Comment by Esther-OC** [comment]
ci:forward

**Comment by Esther-OC** [comment]
ci:test:sf

**Comment by sergiojimcos** [comment]
ci:forward

**Review by sergiojimcos — APPROVED** [review]

**Review by sergiojimcos — APPROVED** [review]

**Review by sergiojimcos — APPROVED** [review]

**Comment by sergiojimcos** [comment]
ci:forward

**Comment by Esther-OC** [comment]
ci:forward

**Comment by Esther-OC** [comment]
Closing as it's failing without reason, try in another new pull request.

**Comment by Esther-OC** [comment]
ci:forward

**Pull request closed without merging**
