### PR TITLE
LPS-142430 Fix: printing all the pages not only one page

### PR DESCRIPTION
**Pull request by rolandpakai**
Hi Team,

could you please review my fix?

**Steps to reproduce:**

1. Start the bundle and login as admin
2. Go to Content & Data → Web Content and create a new web content in a multiple page length
3. Go to Home page and place a web content display widget
4. Set the widget to display the created web content and enable print button in User Tools
5. Click on the print button

**Actual behavior:** It only displays one page and the rest is not there, if it is saved as PDF, the result is the same.

**Expected behavior:** It should display all the pages.

**Root cause:**

The frontend-theme unstyled theme's portal_pop_up.ftl is responsible for displaying the pop_up/print content.

The portal-popup css class sets the print layout.

https://github.com/liferay/liferay-portal/blob/master/portal-web/test/functional/com/liferay/portalweb/dependencies/test-theme.war/templates/portal_pop_up.ftl#L13

The frontend-theme styled theme's _modal.scss .portal-popup:not(.article-preview) #main-content rule defines the css for the print layout.

https://github.com/liferay/liferay-portal/blob/master/modules/apps/frontend-theme/frontend-theme-styled/src/main/resources/META-INF/resources/_styled/css/application/_modal.scss#L1-L13

**Solution:**

Using **position:static** is solving the issue

https://issues.liferay.com/browse/LPS-142430

### CODE REVIEW

**Review by edalgrin — CHANGES_REQUESTED** [review]
Hi @rolandpakai although this solution fixes this issue, it will cause several bugs in other cases.

a scoped solution like

```scss
.portal-popup:not(.article-preview) {
	#main-content,
	#wrapper {
		bottom: 0;
		left: 0;
		overflow: auto;
		padding: $dialog-iframe-padding;
		position: absolute;
		right: 0;
		top: 0;
		-webkit-overflow-scrolling: touch;

		@media print {
			position: initial;
		}
	}
}
```

will work better and won't cause any bug

**Comment by rolandpakai** [comment]
Hi @edalgrin 

thanks for the solution, i tested the change and it solves the issue.
I updated and resent this PR .

Thanks, Roland

**Review by edalgrin — APPROVED** [review]
LGTM!

**Comment by edalgrin** [comment]
ci:test:fi

**Comment by edalgrin** [comment]
ci:test:sf

**Comment by edalgrin** [comment]
ci:test:relevant

**Comment by edalgrin** [comment]
ci:test:forward

**Comment by edalgrin** [comment]
ci:forward

**Pull request closed without merging**
