### PR TITLE
LPS-170537 Add Autom. Test FDSAsyncItemAction#RequestNonExistingResourceCanReturnErrorNotFound

### PR DESCRIPTION
**Pull request by markocikos**
### References

- [LPS-170537 FDSAsyncItemAction#RequestNonExistingResourceCanReturnErrorNotFound](https://issues.liferay.com/browse/LPS-170537)
- This is a followup on https://github.com/liferay-frontend/liferay-portal/pull/2911

### What is the goal of this PR?

We are find portal URL in FDS sample module, instead of hardcoding it to `localhost`
- CI requires this change. I believe it is also necessary to get portal URL through `company`, as CI creates virtual instances on the fly.
- `Async Connection Refused` case is still ok to stay hardcoded, it represents non-existing server URL

### CODE REVIEW

**Comment by markocikos** [comment]
ci:test:frontend

**Comment by eltonccdantas** [comment]
Hey @markocikos, could you add me as a contributor so that I could push some changes to this test?  I need to remove some unnecessary lines. Thanks for fixing the issue.

**Comment by markocikos** [comment]
@eltonccdantas I added you to the list of collaborators on my fork, you should be able to push now. If not for some reason, feel free to open a new PR and close this one.

**Comment by eltonccdantas** [comment]
ci:test:sf

**Comment by eltonccdantas** [comment]
ci:test:frontend

**Comment by mateusralv** [comment]
the failures are not related 😄

**Comment by mateusralv** [comment]
ci:forward

**Comment by john-co** [comment]
try one more time

**Comment by john-co** [comment]
ci:forward

**Pull request closed without merging**
