### PR TITLE
LPS-160083 Update alloyUI version to 3.1.0-deprecated.102

### PR DESCRIPTION
**Pull request by crodriguezy**
Hello team, we need to update alloyUI version again to fix a regression bug:

https://issues.liferay.com/browse/LPS-160083

### CODE REVIEW

**Comment by diegonvs** [comment]
ci:forward

**Comment by susanchen3** [comment]
ci:forward

**Comment by crodriguezy** [comment]
Hi @susanchen3 , do you need me to manually forward it to Brian?

**Comment by susanchen3** [comment]
hey @crodriguezy, I just wanted better results to review :detective: 

The [test failures](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=2&testrayRunIdB=1946592548&testrayRunIdA=1945892709&statusB=3) are unrelated, looks good to manually forward from QA perspective :)

**Comment by crodriguezy** [comment]
Hi @diegonvs , according tu Susan's comment, should we forward it manually to Brian?

**Comment by diegonvs** [comment]
Yes, could you send to him?

**Comment by diegonvs** [comment]
I saw your work day already ended. I'll do this

**Comment by diegonvs** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/121883

**Comment by crodriguezy** [comment]
Thank you @diegonvs ! :)

**Pull request closed without merging**
