### PR TITLE
LPS-199436 Manually redirect in Safari and iOS

### PR DESCRIPTION
**Pull request by antonio-ortega**
Hey,

We've been widely discussing this issue in this [Slack Thread](https://liferay.slack.com/archives/C3JBR21HA/p1697523832525359) and even though our original intention was to properly update the way how we manage redirections, we were in our way to patch a patch. So I decided to stepped back and follow a similar approach to what was done [here](https://github.com/liferay-frontend/liferay-portal/pull/581), although that means we are just fixing this very specific case and nothing else and although that means this is still valid:

> _The future_
> _We should investigate further if a better approach that works through fetch is possible._

### CODE REVIEW

**Comment by antonio-ortega** [comment]
ci:test:relevant

**Comment by antonio-ortega** [comment]
ci:test:relevant

**Review by izaera — APPROVED** [review]

**Comment by deborasoliveira** [comment]
I'll take a look at it.

**Comment by deborasoliveira** [comment]
Can you take a look at this, @antonio-ortega? 
```
build-common-java.compile:
    [javac] Compiling 2219 source files to /opt/dev/projects/github/liferay-portal/portal-impl/classes
    [javac] /opt/dev/projects/github/liferay-portal/portal-impl/src/com/liferay/portal/ee/license/LifecycleAction.java:14: error: package com.liferay.portal.kernel.security.auth.session does not exist
    [javac] import com.liferay.portal.kernel.security.auth.session.AuthenticatedSessionManagerUtil;
    [javac]                                                       ^
    [javac] /opt/dev/projects/github/liferay-portal/portal-impl/src/com/liferay/portal/ee/license/UpdateLicenseAction.java:16: error: cannot find symbol
    [javac] import com.liferay.portal.kernel.security.auth.http.HttpAuthManagerUtil;
    [javac]                                                    ^
    [javac]   symbol:   class HttpAuthManagerUtil
    [javac]   location: package com.liferay.portal.kernel.security.auth.http
    [javac] 2 errors
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:7338: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:7372: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:13339: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-release-tool-ee/build-release-slim.xml:40: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build.xml:323: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-common-java.xml:52: Compile failed; see the compiler error output for details.
```
This is the only failure I think could be related to the PR, other than that the other failures are unrelated. 

[Comparison run](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=2&testrayRunIdB=2447864272&testrayRunIdA=2446948333&statusB=3)

**Comment by antonio-ortega** [comment]
ci:test:relevant

**Comment by antonio-ortega** [comment]
Hi @deborasoliveira ,

Now all the test:stable suite has passed successfully, so can we assume those errors were not related?

If you can confirm it, I'll forward it to Brian.

**Comment by deborasoliveira** [comment]
> Hi @deborasoliveira ,
> 
> Now all the test:stable suite has passed successfully, so can we assume those errors were not related?
> 
> If you can confirm it, I'll forward it to Brian.

Hi @antonio-ortega! Only that failure seemed related, the other failures were unrelated so you can forward it.

**Comment by antonio-ortega** [comment]
ci:forward

**Comment by antonio-ortega** [comment]
Manually forwarded https://github.com/brianchandotcom/liferay-portal/pull/143127

**Pull request closed without merging**
