### PR TITLE
LRQA-76707 Assert portlet body not visible

### PR DESCRIPTION
**Pull request by susanchen3**
**Background**
Caused by changes in https://github.com/liferay/liferay-portal/commit/275af11cf909fd6df313371b140f67d9b3af8890

**JIRA Ticket:**
https://issues.liferay.com/browse/LRQA-76707

### CODE REVIEW

**Comment by susanchen3** [comment]
ci:test:frontend:nocompile

**Comment by susanchen3** [comment]
I'm not entirely sure if this fix is okay, the macro used `Click.waitForMenuToggleJSClick();` before [Yang's changes](https://github.com/liferay/liferay-portal/commit/275af11cf909fd6df313371b140f67d9b3af8890). 

`waitForMenuToggleJSClick` calls on `Click();` in it, which is why I opted for just using `Click();`

I guess in our case, using `Click.javaScriptClick();` won't work because it's not simulating a user click? I read about it here:
https://stackoverflow.com/questions/34562061/webdriver-click-vs-javascript-click

A good amount of tests use this `Portlet.gotoPortletOptions` macro, so I'm sure how much this will affect the other tests. 

Thoughts? @john-co

**Comment by john-co** [comment]
Just started reviewing :)

**Comment by john-co** [comment]
It looks like the issue is not with Yang's changes because the portlet options click does work since the portlet contents have been minimized (contents are not visible). However, the html is still present in the DOM...

image

It's b/c now clicking minimize portlet just adds `d-none` class which makes the contents not visible. So we can try using selenium's Visible functions to assert content is actually not Visible instead of the ElementPresent functions that check the html.

**Comment by john-co** [comment]
https://user-images.githubusercontent.com/35235266/186791499-68bf7be4-5709-40bf-a120-de671457a3c5.mp4

**Review by john-co — CHANGES_REQUESTED** [review]
see above comments

**Comment by susanchen3** [comment]
ohhh i see, yeah that makes sense. Although I opted to use `Portlet#BODY` instead of `PORTLET_CONTENT` because content targets 2 elements. The second element is the one with `d-none`.

**Comment by john-co** [comment]
ci:test:frontend:nocompile

**Comment by susanchen3** [comment]
test failures are unrelated :heavy_check_mark:

**Comment by john-co** [comment]
ci:forward

**Review by john-co — APPROVED** [review]
Looks good to me! :sunglasses:

**Pull request closed without merging**
