### PR TITLE
LPS-121753 Drop IE support from build in backportable way

### PR DESCRIPTION
**Pull request by wincent**
This is a copy of https://github.com/liferay-frontend/liferay-portal/pull/441 because for some reason, the pull request tester appears to be ignoring commands on it. Going to try again here...

---

> ℹ️ Believe it or not, **this one is safe to backport to 7.3** because we have implemented branch-specific behavior as described [in this PR](https://github.com/liferay/liferay-frontend-projects/pull/214).

Previously, we used to transpile all of our ".js" files to be ES5 compatible. That's a very old standard (5.1 was finalized in 2011), and goes significantly beyond what we strictly needed to in order to meet the requirements of our compatibility matrix.

In this commit, we not only drop support for IE, but we make our Babel config very strictly match exactly what is in the compatibility matrix. As an example of the gains, take frontend-js-web as an example, we see this change strip off about 1,305 lines of code, and 69,752 characters (pre-gzip):

Before:

    $ cloc build/node/packageRunBuild/resources

    -------------------------------------------------------------------------------
    Language                     files          blank        comment           code
    -------------------------------------------------------------------------------
    JavaScript                     139           1589           2345           8142

    $ wc build/node/packageRunBuild/**/*.js | tail -1
       12005   44520  580077 total

After:

    $ cloc build/node/packageRunBuild/resources

    -------------------------------------------------------------------------------
    Language                     files          blank        comment           code
    -------------------------------------------------------------------------------
    JavaScript                     139           1407           2529           6836

    $ wc build/node/packageRunBuild/**/*.js | tail -1
       10701   39260  510325 total

Here is a concrete example of a file, `side_navigation.es.js`:

- Before: https://gist.github.com/wincent/be6203a1e3032251a8974bcc633d3751
- After: https://gist.github.com/wincent/b2b073003ce91b9256e1b86bbb1b8ac2
- Diff: https://gist.github.com/wincent/408131bf38c070b10574e976930ad0aa

The major version bump in `@liferay/npm-scripts` is because in a very narrow _technical_ sense, it is a "breaking change" (ironically, only on 7.4). This is because it requires us to add one .babelrc.js for the benefit of analytics-client-js where we continue to want IE support to be in place, even though it lives on 7.4. The file will be harmless no-op on 7.3, so nothing will break on it.

[Release notes for `@liferay/npm-scripts` v34.0.0](https://github.com/liferay/liferay-frontend-projects/releases/tag/npm-scripts%2Fv34.0.0)

Why so many commits? These correspond to manual changes that were made in response to testing. We had over 360 places where we were using `const` variables before declaring them. This worked before because Babel turned them all into `var`, which doesn't care about the so-called "Temporal Dead Zone". But now that the browser is seeing all these `const`, the use-before-definition sloppiness turns into a `ReferenceError`. So I turned on the ESLint `no-use-before-define` rule and then went hunting down all the errors, and made one commit per OSGi module just in case anything goes wrong (ie. so that we can do a granular revert of the affected module).

### CODE REVIEW

**Comment by wincent** [comment]
ci:test:sf

**Comment by wincent** [comment]
ci:test:relevant

**Comment by wincent** [comment]
ci:test:bundle

**Comment by wincent** [comment]
I'll look into these failures on Monday I guess. Some of them aren't making much sense to me, so I'll do a re-run as well to see if the results change.

Examples:

```
     [exec] Execution failed for task ':apps:remote-app:remote-app-client-js:packageRunTest'.
```

Passes for me locally:

```
remote-app-client-js ❯ portool test                  1.89s ~modules/apps/remote-app/remote-app-client-js
yarn run v1.22.5
warning package.json: No license field
$ liferay-npm-scripts test .
Using NODE_ENV: "test"
Browserslist: caniuse-lite is outdated. Please run the following command: `yarn upgrade`
 PASS  test/js/index.ts
  SDK.Client()
    ✓ can be instantiated (4ms)
    debug
      ✓ defaults to off (1ms)
      ✓ can be overridden at construction time (9ms)
      ✓ can be updated after construction
      ✓ logs when true (3ms)
      ✓ logs nothing when false (1ms)
    state
      ✓ initiates registration as soon as it is constructed

  console.log src/main/resources/META-INF/resources/js/log.ts:17
    [CLIENT: 5c0bee75...] posting message... { command: 'register' }

  console.log ../../../node_modules/jest-environment-jsdom-thirteen/node_modules/jest-mock/build/index.js:866
    [CLIENT: fc2b8e95...] enqueuing message... { command: 'openToast', message: 'hello', type: 'info' }

Test Suites: 1 passed, 1 total
Tests:       7 passed, 7 total
Snapshots:   0 total
Time:        2.323s
Ran all test suites matching /./i.
✨  Done in 4.11s.
```

And:

```
junit.framework.AssertionFailedError: 
(/o/js/resolved-module/frontend-js-web@5.0.0/liferay/aop/AOP.es.js:38): Class level JSDocs (@interface, @extends, etc.) are not allowed on class members [JSC_DISALLOWED_MEMBER_JSDOC]
```

Wat? Never touched AOP.es.js...

```
frontend-js-web ❯ git diff --stat upstream/master -- .   1m47s ~modules/apps/frontend-js/frontend-js-web
 .../src/main/resources/META-INF/resources/liferay/modal/Modal.js  | 446 +++++++++++++++---------------
 .../META-INF/resources/liferay/portlet/portlet_util.es.js         | 314 ++++++++++-----------
 .../resources/META-INF/resources/liferay/side_navigation.es.js    |  58 ++--
 .../apps/frontend-js/frontend-js-web/test/liferay/aop/AOP.es.js   |  16 +-
 4 files changed, 417 insertions(+), 417 deletions(-)
```

And `git grep 'Class level JSDocs'` and `git grep JSC_DISALLOWED_MEMBER_JSDOC` return no hits, so I am not even sure where those assertions are coming from. I really have no idea why or what is keying off of `/o/js/resolved-module/frontend-js-web@5.0.0/liferay/aop/AOP.es.js` for a JSDoc-related test... Maybe we have some test code that is somehow hitting the AOP module on its way to do something else entirely... @john-co, @PablitoBonito — do you know anything about these tests?

**Comment by wincent** [comment]
ci:test:relevant

**Comment by john-co** [comment]
Not sure about the js-unit tests when I took a quick look...but there's a number of functional tests getting this error thrown when landing on the home page from what it looks like based on the poshi reports.

```
LIFERAY_ERROR: (/o/js/resolved-module/frontend-js-web@5.0.0/liferay/aop/AOP.es.js:38): Class level JSDocs (@interface, @extends, etc.) are not allowed on class members [JSC_DISALLOWED_MEMBER_JSDOC]
```
Selection_010

**Comment by wincent** [comment]
One of those rare occasions when Google only turns up 3 hits... there is something in the output that the Google Closure Compiler doesn't like — 🤦‍♂️ ... will try to figure out what it is and whether it is solvable by an upgrade (it would be a real shame if we were blocked from shipping modern JS by a flaw in the Closure compiler).

Screenshot 2020-10-26 -084656-GrwNsvCS@2x

**Comment by wincent** [comment]
Ok, rebased. Hopefully https://github.com/liferay-frontend/liferay-portal/pull/447/commits/f0de30a09dac2710c4e65150d6bb93125852711f fixes the issue; it's not as bad as I thought.

---

CI reveals a runtime error when our JS passes through the Google Closure Compiler:

> Class level JSDocs (`@interface`, `@extends`, etc.) are not allowed on class members

Based on [this code here](https://github.com/google/closure-compiler/blob/a1f6c7e01705511ef146da5843275a7774b15937/src/com/google/javascript/jscomp/CheckJSDoc.java#L426), I believe the annotations we have to care about are:

- `@base`
- `@constructor`
- `@extends`
- `@interface`

So, I searched across the entire code base for those and thankfully there are only a small number of hits (about 25), and one of them indeed falls inside the `AOP.es.js` class that was visible in the error report.

Looks like before we modernized our Babel transform this code:

```js
class AOP {
  /**
   * @constructor
   */
  constructor() {}
}
```

was getting transformed into (something like):

```js
"use strict";

function _instanceof(left, right) { if (right != null && typeof Symbol !== "undefined" && right[Symbol.hasInstance]) { return !!right[Symbol.hasInstance](left); } else { return left instanceof right; } }

function _classCallCheck(instance, Constructor) { if (!_instanceof(instance, Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

var AOP =
/**
 * @constructor
 */
function AOP() {
  _classCallCheck(this, AOP);
};
```

which prevented the Closure Compiler from "seeing" the problem and complaining about it.

The other 20+ hits all look fine to me.

**Comment by wincent** [comment]
ci:test:sf

**Comment by wincent** [comment]
ci:test:relevant

**Comment by wincent** [comment]
ci:test:bundle

**Comment by jbalsas** [comment]
Another option would be to add `JSC_DISALLOWED_MEMBER_JSDOC` to the [list of ignored warnings](https://github.com/liferay-frontend/liferay-portal/blob/master/modules/apps/frontend-js/frontend-js-minifier/src/main/java/com/frontend/js/minifier/GoogleJavaScriptMinifier.java#L116-L121)

In any case, I think it's obvious by now that we want to get rid of this minifier... I'll see if I can plan the epic in the next days.

**Comment by wincent** [comment]
That SF error is due to a new violation sneaking in between the first version of this PR and the rebase... this is a race against time! 😱

race

**Comment by wincent** [comment]
ci:stop

**Comment by wincent** [comment]
Rebased and squashed in the additional fixes for the new violation, going to try again.

**Comment by wincent** [comment]
ci:test:sf

**Comment by wincent** [comment]
ci:test:relevant

**Comment by wincent** [comment]
ci:test:bundle

**Comment by wincent** [comment]
I'll push a fix for the JS unit failure, but perhaps @john-co or @PablitoBonito can help me diagnose the other failures. Looks like I fixed the `JSC_DISALLOWED_MEMBER_JSDOC` ones that were seen on a prior run, but I am not sure how to read the Poshi report for these new ones, which are different.

In the meantime I'll re-run to see the JS unit green and also to see if that first unique failure (`HikariPool-1 - Exception during pool initialization ... com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure`) is spurious/ephemeral, as it looks it might be.

**Comment by wincent** [comment]
ci:test:sf

**Comment by wincent** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
@wincent, apparently the forms app is not able to start. I don't see any console errors caught anywhere, but it looks like it's not rendering. Could you try locally to go to `Content & Data > Forms` and see if anything weird pops up?

**Comment by wincent** [comment]
> @wincent, apparently the forms app is not able to start. I don't see any console errors caught anywhere, but it looks like it's not rendering. Could you try locally to go to `Content & Data > Forms` and see if anything weird pops up?

It's some garbage coming up from the bowels of `incremental-dom` (most of the frames in the following trace are in `incremental-dom`). Given that's only used in two modules, both in `dynamic-data-mapping`, I'm going to override then Babel changes there.

```
  TypeError: Cannot read property 'getRenderer' of undefined
    at renderFromTag_ (VM2773 render.js:504)
    at Sidebar.handleChildrenCaptured_ (VM2773 render.js:252)
    at handleInterceptedCloseCall_ (VM2770 children.js:171)
    at Object.handleCall (VM2769 incremental-dom-aop.js:121)
    at fnVoid (VM2769 incremental-dom-aop.js:103)
    at Object.handleCall (VM2769 incremental-dom-aop.js:121)
    at VM3032 Sidebar.es.js:1011
    at wrapper (VM2938 iDOMHelpers.js:54)
    at scope.iDOMHelpers.renderArbitrary (VM2938 iDOMHelpers.js:65)
    at Array.forEach (<anonymous>)
```

**Comment by wincent** [comment]
ci:stop

**Comment by wincent** [comment]
ci:test:sf

**Comment by wincent** [comment]
ci:test:relevant

**Comment by wincent** [comment]
ci:test:bundle

**Comment by jbalsas** [comment]
> [...] Given that's only used in two modules, both in dynamic-data-mapping, I'm going to override then Babel changes there.

I approve of this action. I don't find it immoral.

**Comment by jbalsas** [comment]
This looks good now... @john-co, @PablitoBonito, @manoelcyreno, want another round here as well? or manually forward it?

**Comment by wincent** [comment]
> This looks good now... @john-co, @PablitoBonito, @manoelcyreno, want another round here as well? or manually forward it?

In the event that the answer is "forward", please don't hesitate to do the `ci:forward` yourself — as this touches files all over the place it runs the risk of hitting a merge conflict if we let it sit for too long.

**Comment by john-co** [comment]
ci:forward

**Comment by john-co** [comment]
I can't confirm or deny if the test failures are related so I'll run `ci:forward` and if they pass then it'll forward without further wait for us to check in on the results. If the don't pass I'll compare the results and evaluate manual forwarding.

**Comment by john-co** [comment]
The failures look unique based on test history but the thing I'm unsure about is if they're fluke's or related to the PR

First test failed on compile but there's tests that [are running in upstream](https://testray.liferay.com/home/-/testray/cases/index?name=TaxonomyCategoryResourceTest&testrayProjectId=1306746258&orderByCol=testrayComponentName_sortable&orderByType=asc&resetCur=false&delta=200). The compile error looks like this:
```
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/headless/headless-admin-taxonomy/headless-admin-taxonomy-test/src/testIntegration/java/com/liferay/headless/admin/taxonomy/resource/v1_0/test/TaxonomyCategoryResourceTest.java:83: error: cannot find symbol
     [exec] 		AssetCategoryLocalServiceUtil.addAssetEntryAssetCategory(
     [exec] 		                             ^
     [exec]   symbol:   method addAssetEntryAssetCategory(long,Long)
     [exec]   location: class AssetCategoryLocalServiceUtil
``` 

The second one with DocumentFolderResourceTest.testGetDocumentFolder [has been passing in upstream](https://testray.liferay.com/home/-/testray/cases/1310804146). I'm just not sure what to make of the error, it doesn't seem related to the PR...
https://gist.github.com/john-co/595d4c6047fb294a4bfe0dc3f763119f

**Comment by manoelcyreno** [comment]
@john-co  If you are unsure, don't spend more time and ask in the QA channel for help.

**Comment by john-co** [comment]
@manoelcyreno , I had asked @vicnate5 for help but couldn't gather enough certainty if it was unrelated. But ok, as you said I will ask QA channel next time.

**Comment by wincent** [comment]
> The failures look unique based on test history

I'm skeptical that a JS-only change would cause a Java compilation failure.

**Comment by wincent** [comment]
Merge conflict, so I rebased to resolve the conflicts and resent here: https://github.com/brianchandotcom/liferay-portal/pull/95337

**Pull request closed without merging**
