### PR TITLE
LPS-181879 - TESTING react to 18.2.0

### PR DESCRIPTION
**Pull request by bryceosterhaus**
checking CI

### CODE REVIEW

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by deborasoliveira** [comment]
I'm taking a look at the poshi failures.

**Comment by deborasoliveira** [comment]
The failures seem to be related to the PR, especially because many tests are failing when doing edition steps, for example when editing a content. 
As many tests failed, and although they have the similar failure their contexts are different, I will need to investigate this further locally.

[Comparison run](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=2&testrayRunIdB=2439289569&testrayRunIdA=2438944747&statusB=3)

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by deborasoliveira** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
Going to rebase and re-run tests

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by deborasoliveira** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by michaelhashimoto** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
ci:test:relevant:norebase

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by mateusralv** [comment]
Hey @bryceosterhaus Most of the functional tests failed (about 3500), I did some manual tests and I found the errors:


https://github.com/liferay-frontend/liferay-portal/assets/44584050/9fd12e7a-345b-47b6-a4cf-97a9d2a6e6b7

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
@mateusralv my bad, previous tests were using the wrong version of clay which caused errors everywhere. This new run should be better 🤞

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
ci:test:relevant:norebase

**Comment by bryceosterhaus** [comment]
closing. going to open new PR

**Pull request closed without merging**
