### PR TITLE
LPS-168442 - Centralize JS dependencies into central module

### PR DESCRIPTION
**Pull request by bryceosterhaus**
testing new PR with single commit

### CODE REVIEW

**Comment by bryceosterhaus** [comment]
ci:stop

**Comment by bryceosterhaus** [comment]
ci:start:relevant

**Comment by bryceosterhaus** [comment]
ci:start:sf

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by mateusralv** [comment]
I'm taking a look 🕵️‍♀️

**Comment by bryceosterhaus** [comment]
@mateusralv feel free to send me a PR with the fix and I will add to my branch

**Comment by mateusralv** [comment]
Hi @bryceosterhaus I created the fix for the workflow tests and ran ci:test:relevant, could you wait for the new results and then add the commit here?

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
ci:test:sf

**Comment by mateusralv** [comment]
I'm taking a look

**Comment by mateusralv** [comment]
@bryceosterhaus could you add this commit https://github.com/mateusralv/liferay-portal/pull/36/commits/8b76c6f13d4336757321ddeaafb8867b369a989a here?

**Comment by bryceosterhaus** [comment]
@mateusralv added. Feel free to re-run tests as needed

**Comment by mateusralv** [comment]
ci:test:relevant

**Comment by mateusralv** [comment]
Hi @bryceosterhaus I took a closer look at that failures that was occurring in the Forms tests and found something that is related to PR. 

The error occurs when we try to add a file. mp4 in a Forms in your PR it does not return the error: `"Please enter a file with a Valid Extension (doc, docx, jpeg, jpg, pdf, png, ppt, pptx, tiff, txt, xls, xlsx)."`

### Master:

https://user-images.githubusercontent.com/44584050/216172922-2a5aaa44-50b3-4760-96a6-744239073337.mp4

### PR: 

https://user-images.githubusercontent.com/44584050/216172999-07e6f238-6df7-4cf2-8634-db723babd5be.mp4

---
### Tests related to failure:
FormsUploadField#CanBeSubmittedByGuestUser
FormsUploadField#GuestUserCannotUploadFileWithInvalidSize

[Testray comparison](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1675255873341&testrayRunIdA=2182273229&testrayRunIdB=2182666989)

**Comment by bryceosterhaus** [comment]
ci:test:sf

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by mateusralv** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
@mateusralv any update on this from the lastest run?

**Comment by mateusralv** [comment]
I'm on it!

**Comment by bryceosterhaus** [comment]
manual forward at https://github.com/brianchandotcom/liferay-portal/pull/129973

**Pull request closed without merging**
