### PR TITLE
LPS-141280 Proposal to add the screenshots of a Remote App Entry as a part of the description

### PR DESCRIPTION
**Pull request by javierdearcos**
To be able to validate the Remote App by a reviewer, it is needed to add some extra fields as description, sourceCodeURL, and some screenshots. 

After trying to achieve the addition of screenshots using attachments and prove that it would be a complex task, and also that there are different approaches in the different usages in the platform, I've decided to take a more pragmatic and simpler approach to see if it is enough to provide value.

The approach is to change the description field to be an HTML that can embed different images and use an editor to fulfill the field in the frontend.

The result is shown in the following image:

Captura de pantalla 2021-11-15 a las 16 25 13

This approach could be used with a hint in the UI to enforce the usage of screenshots in the description.

The database upgrade step is pending until the approach is validates, because it's not straightforward

### CODE REVIEW

**Review by nhpatt — APPROVED** [review]
LGTM.

IMHO As Brian is the main reviewer I would seen as soon as possible, even if it's not completely finished to get feedback.

**Comment by javierdearcos** [comment]
ci:test:sf

**Comment by javierdearcos** [comment]
ci:test:relevant

**Comment by nhpatt** [comment]
There are remote-app tests failing: 

LocalFile.RemoteApps#CanBeCreated - Poshi Report - Poshi Summary - Console Output
LocalFile.RemoteApps#CustomElementCanBeCreated

**Comment by javierdearcos** [comment]
Yes. As I have the approval of PM, I just need to modify the upgrade process to create the new localized entities table.

Then I will talk with Meg to check the tests

**Comment by javierdearcos** [comment]
Hi @magjed4289 !

Sorry for the delay. I was fighting with the database upgrade process.

This is the final solution so here we can work on the failing tests.

Don't know if you prefer to first run the tests to see the result and work from there. I let you decide.

Thank you very much for the support!

**Comment by magjed4289** [comment]
Just started reviewing :)

**Comment by magjed4289** [comment]
ci:test:relevant

**Comment by magjed4289** [comment]
Just started reviewing :)

**Comment by magjed4289** [comment]
ci:test:relevant

**Comment by magjed4289** [comment]
ci:test:relevant

**Comment by magjed4289** [comment]
ci:test:relevant

**Comment by magjed4289** [comment]
ci:reevaluate:1297401_723

**Comment by magjed4289** [comment]
ci:test:relevant

**Comment by magjed4289** [comment]
ci:test:stop

**Comment by magjed4289** [comment]
ci:stop

**Comment by magjed4289** [comment]
ci:stop

**Comment by magjed4289** [comment]
ci:stop

**Comment by magjed4289** [comment]
ci:stop

**Comment by javierdearcos** [comment]
ci:test:sf

**Comment by javierdearcos** [comment]
ci:forward

**Comment by javierdearcos** [comment]
ci:forward

**Comment by javierdearcos** [comment]
ci:forward

**Comment by javierdearcos** [comment]
ci:test:sf

**Comment by javierdearcos** [comment]
ci:stop

**Comment by javierdearcos** [comment]
ci:test:sf

**Comment by javierdearcos** [comment]
ci:forward

**Pull request closed without merging**
