### PR TITLE
LPS-142295 Create sample Vanilla Counter remote app

### PR DESCRIPTION
**Pull request by izaera**
We create a sample row pointing to our Vanilla Counter app per company,
but only when the table is empty (ie: on fresh installations).

Note that this will recreate the sample if it is deleted, no other
remote app is created and portal is restarted. PM thinks this is a fair
behaviour but, if we see it creates any problem, we may change it in
the future.

### CODE REVIEW

**Comment by magjed4289** [comment]
Just started reviewing :)

**Comment by magjed4289** [comment]
ci:test:relevant

**Comment by nhpatt** [comment]
It has to be a draft, right? as it can't be merged until the URL is valid.

**Comment by izaera** [comment]
The URL is already valid :tada:

**Comment by izaera** [comment]
https://liferay.github.io/liferay-frontend-projects/

**Comment by izaera** [comment]
We need to fix the fix the failing integration test for labels. I'll give it a try when I get some time...

**Comment by izaera** [comment]
I have pushed a commit to fix one of the CI errors.

**Comment by izaera** [comment]
ci:test:relevant

**Comment by izaera** [comment]
ci:test:sf

**Review by nhpatt — APPROVED** [review]

**Review by bryceosterhaus — APPROVED** [review]
LGTM!

**Comment by izaera** [comment]
ci:test

**Comment by izaera** [comment]
ci:test:relevant

**Comment by izaera** [comment]
ci:test:sf

**Comment by izaera** [comment]
ci:test:sf

**Comment by izaera** [comment]
ci:test:relevant

**Comment by izaera** [comment]
ci:test:sf

**Comment by izaera** [comment]
ci:test:relevant

**Review by javierdearcos — APPROVED** [review]
I guess I have my payback with a horrendous rebase... Sorry for the trouble.

LGTM

**Comment by javierdearcos** [comment]
Added a new method to provide the status when adding a new custom element. If the status is approved the workflow framework is not triggered.

I will talk with the LOL team to know if this is also useful for them, and maybe we can get rid of the old method and just leave the new one

**Comment by izaera** [comment]
thank you

**Comment by javierdearcos** [comment]
ci:test:relevant

**Comment by izaera** [comment]
ci:test:relevant

**Comment by javierdearcos** [comment]
ci:test:sf

**Comment by javierdearcos** [comment]
ci:test:relevant

**Comment by javierdearcos** [comment]
ci:forward

**Pull request closed without merging**
