### PR TITLE
LPS-156407: Align default value for ERC of structured content with other entities

### PR DESCRIPTION
**Pull request by sergiojimcos**
**What is new?**

- Update `JournalArticleLocalService` and `JournalArticleModelValidator` to update ERC using the UUID.
- Update `JournalArticleServiceTest` checking that ERC is the UUID.

**Note:** The rest of entities validates the ERC using the UUID instead of entity ID.

**JIRA Ticket**
https://issues.liferay.com/browse/LPS-156407

### CODE REVIEW

**Review by javierdearcos — APPROVED** [review]
Perfect 🎉

**Review by LuismiBarcos — APPROVED** [review]
LGTM :) 👏 👏 👏

**Review by ccorreagg — APPROVED** [review]

**Comment by ccorreagg** [comment]
ci:forward

**Comment by javierdearcos** [comment]
ci:test:relevant

**Comment by javierdearcos** [comment]
ci:test:relevant

**Pull request closed without merging**
