### PR TITLE
LPD-23440 - poshi - Remove a test that was replaced by Playwright in liferay-frontend#4139

### PR DESCRIPTION
**Pull request by kresimir-coko**
Original PR: https://github.com/liferay-frontend/liferay-portal/pull/4147

Reopened due to CI being stuck

### CODE REVIEW

**Comment by kresimir-coko** [comment]
ci:test:relevant

**Comment by kresimir-coko** [comment]
ci:test:relevant

**Comment by dsanz** [comment]
LGTM ;)

**Comment by dsanz** [comment]
ci:forward:force

**Pull request closed without merging**
