### PR TITLE
LPS-187505 Add missing `propsTransformer` to enable `onClick` handlers

### PR DESCRIPTION
**Pull request by kresimir-coko**
Source of this task is an [LPP](https://liferay.atlassian.net/browse/LPP-49308).

The problem is that the 2 dropdown options on a Web Content Folder weren't being invoked.

The reason was the lack of a `propsTransformer` defined on the `clay:horizontal-card` usage that represented the Folder.

### CODE REVIEW

**Comment by deborasoliveira** [comment]
I'll take a look at it.

**Comment by deborasoliveira** [comment]
Hello @kresimir-coko!
The relevant failures are not unique so they aren't related to this PR. 

[Comparison run](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=2&testrayRunIdB=2354500517&testrayRunIdA=2353392589&statusB=3)

**Review by markocikos — APPROVED** [review]
@kresimir-coko LGTM! :sparkles:

**Comment by kresimir-coko** [comment]
ci:forward

**Comment by kresimir-coko** [comment]
ci:reevaluate:1397401_5645

**Comment by kresimir-coko** [comment]
Manually forwarded to https://github.com/brianchandotcom/liferay-portal/pull/136901

**Pull request closed without merging**
