### PR TITLE
LPS-152238 Migrate frontend-taglib-chart to ESM build

### PR DESCRIPTION
**Pull request by izaera**

### CODE REVIEW

**Comment by izaera** [comment]
ci:test:sf

**Review by bryceosterhaus — APPROVED** [review]
Looks pretty good to me. My only suggestion would be possibly updating the name from `frontend-taglib-chart` to `@liferay/frontend-taglib-chart`. May be out of scope, but might be nice to do now since you have so much context for the module at the moment.

**Comment by izaera** [comment]
As agreed in a supersecret :ninja:  conversation, we won't rename the npm package because we own it in npm and this module is not even used by us, but only present for compatiblity. In fact, we may try to remove it in the near future.

**Comment by izaera** [comment]
ci:test:sf

**Comment by mateusralv** [comment]
Hi @izaera the failures are not related! Most failures also occur on the master, only two are unique, but they don't seem regressions, so safe to forward.

The unique failures: 

modules-semantic-versioning-jdk8/0/0
``` [exec] com.liferay.semantic.versioning.SemanticVersioningTest > testSemanticVersioning[/apps/frontend-taglib/frontend-taglib-chart] FAILED
     [exec]     java.lang.AssertionError:   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec]     = ================================================== ========== ========== ========== ========== ==========
     [exec]     * com.liferay.frontend.taglib.chart.servlet.taglib.soy MINOR      1.0.0      1.0.0      1.1.0      VERSION INCREASE REQUIRED
     [exec]     	<   class      com.liferay.frontend.taglib.chart.servlet.taglib.soy.AreaSplineChartTag
     [exec]     		+   method     cleanUp()
     [exec]     			+   access     protected

```


portal-license-smoke-mysql57-jdk8/0/0
```
 [junit] Testcase: testScanXMLLog(com.liferay.portal.log.assertor.PortalLogAssertorTest):	FAILED
    [junit] 
    [junit] Portal log assert failure, see above log for more information: 
    [junit] HHH000315: Exception executing batch [java.sql.BatchUpdateException: Duplicate entry '20096-com.liferay.commerce.price.list.model.CommercePriceList-4-' for key 'IX_A9FF4B2C'], SQL: insert into ResourcePermission (mvccVersion, ctCollectionId, companyId, name, scope, primKey, primKeyId, roleId, ownerId, actionIds, viewActionId, resourcePermissionId) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
    [junit] junit.framework.AssertionFailedError: 
    [junit] HHH000315: Exception executing batch [java.sql.BatchUpdateException: Duplicate entry '20096-com.liferay.commerce.price.list.model.CommercePriceList-4-' for key 'IX_A9FF4B2C'], SQL: insert into ResourcePermission (mvccVersion, ctCollectionId, companyId, name, scope, primKey, primKeyId, roleId, ownerId, actionIds, viewActionId, resourcePermissionId) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
    [junit] 	at com.liferay.portal.log.assertor.PortalLogAssertorTest.scanXMLLogFile(PortalLogAssertorTest.java:171)
    [junit] 	at com.liferay.portal.log.assertor.PortalLogAssertorTest$1.visitFile(PortalLogAssertorTest.java:98)
    [junit] 	at com.liferay.portal.log.assertor.PortalLogAssertorTest$1.visitFile(PortalLogAssertorTest.java:88)
    [junit] 	at java.nio.file.Files.walkFileTree(Files.java:2670)
    [junit] 	at java.nio.file.Files.walkFileTree(Files.java:2742)
    [junit] 	at com.liferay.portal.log.assertor.PortalLogAssertorTest.testScanXMLLog(PortalLogAssertorTest.java:86)
    [junit] 
    [junit] 
    [junit] Test com.liferay.portal.log.assertor.PortalLogAssertorTest FAILED
[stopwatch] [test.cmd: 0.666 sec]
```
seems a flake issue 

[Testray Comparison](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=2&testrayRunIdB=2327645300&testrayRunIdA=2327635490&statusB=3)

**Comment by izaera** [comment]
ci:test:sf

**Comment by izaera** [comment]
ci:test:stable

**Comment by izaera** [comment]
ci:test:stable

**Comment by izaera** [comment]
ci:forward

**Comment by izaera** [comment]
ci:forward:force

**Pull request closed without merging**
