### PR TITLE
LPS-203827 Fix small prop 

### PR DESCRIPTION
**Pull request by victorg1991**
> Hi guys!
> 
> In Echo team we are making improvements for the `TranslationAdminSelector` component and `input localized` according to this story https://liferay.atlassian.net/browse/LPS-200663. In this story several improvements are proposed:
> 
> _Selector_: A new horizontal design for the translation selector
> 
> 
> _Dropdown_: A new status for translations, indicating the number of fields that have been translated.
> 
> 
> Therefore the following has been done:
> 
> **For TranslationAdminSelector.tsx**
> 
> * The possibility to display the `TranslationAdminSelector` component with a horizontal design. For this reason, a new prop has been added to this component: `displayType`, with two options, `default` and `horizontal`.
> * A new `translationProgress` prop has been included. This prop is used to indicate how many fields are translated in the translation status (see second image from above). It has the following structure:
> 
> ```
> TranslationProgress {
> 	totalItems: number;
> 	translatedItems: Record<string, number>;
> }
> ```
> 
> * Accessibility improvements
>   - Context improvements adding `aria-*`
>   - When the selector doesn't show the Translation Manager button it must be a `picker`, and otherwise a `dropdown`
>   - For the `dropdown`, when an option is selected the focus will return to the trigger
> 
> **For input_localized.js**
> 
> * Two attributes have been added to the hidden inputs of the localized input: `data-language-id="{languageId}"` and `data-field-name="{fieldName}"` to make it easier to search from outside the component
> * It's necessary to know when the translations are updated, so a `Liferay.fire('inputLocalized:updateTranslationStatus')` is added in the localized input.
> 
> Thanks in advance! 🙂

### CODE REVIEW

**Review by markocikos — APPROVED** [review]
@victorg1991 LGTM! :sparkles:

**Comment by dsanz** [comment]
ci:forward

**Comment by victorg1991** [comment]
ci:forward

**Comment by victorg1991** [comment]
ci:forward

**Comment by victorg1991** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by victorg1991** [comment]
ci:forward

**Comment by liulukiwi** [comment]
Hi @victorg1991 , TranslationAdminSelector.js test failed, can you take a look?
     [exec] > Task :apps:frontend-js:frontend-js-components-web:packageRunTest FAILED
     [exec] PASS test/treeview/Treeview.js (11.575s)
     [exec] PASS test/hooks/useSessionState.test.js (12.496s)
     [exec] FAIL test/translation_manager/TranslationAdminSelector.js (13.604s)
details:
[https://gist.github.com/liulukiwi/458ea820bad0b30b1a96daa58f744f39](https://gist.github.com/liulukiwi/458ea820bad0b30b1a96daa58f744f39)

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by liulukiwi** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/145854

**Comment by liulukiwi** [comment]
ci:close

**Pull request closed without merging**
