### PR TITLE
LPS-196513 Update liferay-ckeditor v4.21.0-liferay.1

### PR DESCRIPTION
**Pull request by fortunatomaldonado**
https://liferay.atlassian.net/browse/LPS-196513

Updated ckeditor to v4.21 in order to fix the issues in the ticket above.
Let me know if there are any questions or comments about this.

Thank you!

### CODE REVIEW

**Review by markocikos — APPROVED** [review]
@fortunatomaldonado LGTM! :sparkles:

**Comment by fortunatomaldonado** [comment]
ci:forward

**Comment by markocikos** [comment]
ci:forward

**Comment by JerryAdrianoo** [comment]
@fortunatomaldonado These failures are not related to your changes.
See [Test Comparison](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1695990779623&testrayRunIdA=2433035916&testrayRunIdB=2433857568)

**Comment by thektan** [comment]
Forwarded to https://github.com/brianchandotcom/liferay-portal/pull/141572

**Comment by thektan** [comment]
ci:close

**Pull request closed without merging**
