### PR TITLE
LPS-130894 Add endpoints to delete, get and upsert documents by externalReferenceCode

### PR DESCRIPTION
**Pull request by javierdearcos**
I've removed the Transactional annotation because I added it by mistake in an older commit and I realized this annotation is always added at the interface level and not at the class implementation level.

### CODE REVIEW

**Comment by javierdearcos** [comment]
ci:forward

**Comment by nhpatt** [comment]
-- rebased

**Comment by nhpatt** [comment]
ci:forward

**Comment by javierdearcos** [comment]
ci:reevaluate:1157401_4430

**Comment by javierdearcos** [comment]
Sent here https://github.com/liferay-frontend/liferay-portal/pull/1103

**Pull request closed without merging**
