### PR TITLE
LPS-160757 | Autom ProxyPathRedirect test

### PR DESCRIPTION
**Pull request by abhnerramos**
**Description** 
Create a new automation test that covers https://issues.liferay.com/browse/LPS-96596 as requested by BChan here: https://github.com/brianchandotcom/liferay-portal/pull/76674

**Test Plan**
Given proxy server setup with `liferay`
When on default home page
Then all resources load properly

**JIRA TICKET**
https://issues.liferay.com/browse/LPS-160757

**Files changed**
- PortalProxyPath#ProxyPathRedirect test
- assertJavaScriptErrors function

### CODE REVIEW

**Comment by abhnerramos** [comment]
ci:test:sf

**Comment by abhnerramos** [comment]
ci:test:sf

**Comment by abhnerramos** [comment]
ci:test:sf

**Review by john-co — APPROVED** [review]
Looks good to me! :sunglasses:

**Comment by john-co** [comment]
ci:forward

**Pull request closed without merging**
