### PR TITLE
LPS-124253 Use new custom hooks in ReferralDetail to share TimeSpanSelector state between main and detail view

### PR DESCRIPTION
**Pull request by dgarciasarai**
**Description**
ReferralDetail should use/manage the same state as the main view. This detail will be hidden from now until we have the final data from AC (we don't display a link in this traffic channel in the PieChart section).

Two commits on top of https://github.com/liferay-frontend/liferay-portal/pull/578.

- https://github.com/liferay-frontend/liferay-portal/commit/864da00409d11805e75d3e2f7350c26c9b5aa104: LPS-124253 Use chart state custom hooks in referral detail view
- https://github.com/liferay-frontend/liferay-portal/commit/8adcb13947795c4c8b99de3fffe0bd50d9efdfd0: LPS-124253 Fix test

**Solution**
Use custom hooks created in https://github.com/liferay-frontend/liferay-portal/pull/578 to keep TimeSpanSelector state between main and detail views.

### CODE REVIEW

**Comment by dgarciasarai** [comment]
ci:test:sf

**Comment by wincent** [comment]
I just looked at the top two commits; they look fine to me.

**Comment by dgarciasarai** [comment]
`nextTimeSpan` and `previousTimeSpan` didn't receive any event, but `onTimeSpanChange={changeTimeSpanKey}` yes...

```js
const changeTimeSpanKey = useChangeTimeSpanKey();

const handlePreviousTimeSpanClick = () => {
	previousTimeSpan();
};

const handleNextTimeSpanClick = () => {
	nextTimeSpan();
};

const handleTimeSpanChange = (event) => {
	const {value} = event.target;

	changeTimeSpanKey({key: value});
};
```

And then in the component:

```js
<TimeSpanSelector
    onTimeSpanChange={handleTimeSpanChange}
/>
```

What happen with that `event.target.value`?

**Comment by wincent** [comment]
> What happened with that `event.target.value`?

If `handleTimeSpanChange` received `event` as a parameter and you replace it with `changeTimeSpanKey`, then `event` will be passed into `changeTimeSpanKey`. `changeTimeSpanKey` expects a `payload` parameter containing a `key` property. `event` does not have the same shape as you expect `payload` to.

I imagine that lines up with your analysis too, right?

**Comment by wincent** [comment]
Not sure if you were asking a different question though; it's just a matter of looking at what each function does, what params it expects, what params it gets passed. To make it work, you have to give any given function the right params. 🤷‍♂️

**Comment by dgarciasarai** [comment]
Yeah, I think I understand it, instead of getting the payload in the hook, I just have to get the event (as in the handle method) and construct my payload to make it work. I'll add a commit refactoring both, the `ReferralDetail` and `SocialDetail`. That way, I save a couple of lines :)

**Comment by dgarciasarai** [comment]
@wincent I think this is what you suggested: https://github.com/liferay-frontend/liferay-portal/pull/582/commits/10f3588a0f99112138bbf22a38930f37522ac90e

**Comment by dgarciasarai** [comment]
ci:test:sf

**Comment by dgarciasarai** [comment]
ci:test:relevant

**Comment by wincent** [comment]
> @wincent I think this is what you suggested: [10f3588](https://github.com/liferay-frontend/liferay-portal/commit/10f3588a0f99112138bbf22a38930f37522ac90e)

Mostly. I wouldn't have actually changed `changeTimeSpanKey` though — I was just trying to make sense of your question. In [my initial comment](https://github.com/liferay-frontend/liferay-portal/pull/582#commitcomment-44736836) I was talking only about the functions that "do nothing except call another function" — the `handleTimeSpanChange` callback does more than just call another function (it prepares/massages params and then calls another function).

By changing `useChangeTimeSpanKey`, you've now mixed event management into a hook that was previously just a pure data management hook.

**Comment by dgarciasarai** [comment]
Hey @wincent, I let the method `handleTimeSpanChange` as it was and only simplify the "do nothing except call another function" functions: `nextTimeSpan` and `previousTimeSpan`. Also, I rebased the pull because the other commits were merged yesterday. Thanks!

**Comment by dgarciasarai** [comment]
ci:test:sf

**Comment by wincent** [comment]
ci:test:relevant

**Comment by wincent** [comment]
> Hey @wincent, I let the method `handleTimeSpanChange` as it was and only simplify the "do nothing except call another function" functions: `nextTimeSpan` and `previousTimeSpan`. Also, I rebased the pull because the other commits were merged yesterday. Thanks!

Sounds good. I'm rerunning the tests now — feel free to `ci:forward` if/once you see them green.

**Comment by dgarciasarai** [comment]
ci:forward

**Pull request closed without merging**
