### PR TITLE
[Safe to backport] LPS-122968 Removes legacy xp_progressbar library

### PR DESCRIPTION
**Pull request by jbalsas**
This is a simple maintenance task to remove the `xp_progress.js` library that has been lingering around in our codebase for ages.

The library was used to show an animated progress bar when hitting the following endpoints
- `/c/portal/j_login` which was mapped to `j_login.jsp`
- `/c/portal/protected` mapped to `protected.jsp`
- `/c/portal/touch_protected` which rendered `touch_protected.jsp`

**The change**
Since this is a simple animated progressbar with no real interactivity, we could replace it with any loading indicator of our choice, so I decided to just use clay's loading animation.

**Test plan**
All these paths are part of a Java Authentication and Authorization Service (JAAS) scheme, so to be able to see them one needs to set in `portal-ext.proprties` at least

```properties
 portal.jaas.enable=true
```

Then, restart the server and navigate manually to `http://localhost:8080/c/portal/j_login`

j_login

| Before | After |
| --- | --- |
| Screen Shot 2020-11-02 at 22 22 01 | Screen Shot 2020-11-02 at 22 20 21 |

**Additional Considerations**
The status of this feature is a bit of a mistery, so @david-truong is making some inquiries. Interestingly, this is our disclaimer in the `portal.jaas.enable` property:

> [...] Disabling JAAS speeds up login. JAAS must be disabled if administrators are to be able to impersonate other users.

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:test:sf

**Comment by jbalsas** [comment]
ci:test:relevant

**Review by wincent — APPROVED** [review]
```
Copyright 2004 Brian Gosselin of ScriptAsylum.com
```

RIP `xp_progress.js` 2004-2020

So I gather, @jbalsas, that we need to add the CSS in all these places because it isn't already covered by [`portal-web/docroot/html/common/themes/top_head.jsp`](https://github.com/liferay/liferay-portal/blob/afb229df01a027b6f438bf1628290d9470d1e4d8/portal-web/docroot/html/common/themes/top_head.jsp#L27)?

Other than that doubt, lg2m.

**Comment by jbalsas** [comment]
> So I gather, @jbalsas, that we need to add the CSS in all these places because it isn't already covered by portal-web/docroot/html/common/themes/top_head.jsp?

Yeah, this is very much served standalone. There's really no theme involved in here (see that we still use a path to fetch `clay.css`) which is not super nice, but it's almost guaranteed to be there. This is a page that will hardly ever be seen and hopefully will go away, so I didn't put much more thought into it.

**Comment by wincent** [comment]
ci:forward

**Comment by wincent** [comment]
release-the-hounds

**Pull request closed without merging**
