### PR TITLE
LPS-152237 Modernize `toggleSelectBox`

### PR DESCRIPTION
**Pull request by kresimir-coko**
This PR modernizes the `Liferay.Util.toggleSelectBox` utility. The utility accepts 2 elements and a value, where the 1st element is used to change the state of the 2nd element depending on the value.

## 🧪 Testing
In the sidebar of Web Content, under Display Page, switching between Specific, Default, and None will trigger the `change` event specified inside the utility.
image

### CODE REVIEW

**Comment by kresimir-coko** [comment]
ci:test:relevant

**Review by bryceosterhaus — APPROVED** [review]
LGTM

**Comment by kresimir-coko** [comment]
ci:reevaluate:1317401_3640

**Comment by kresimir-coko** [comment]
ci:test:relevant

**Comment by kresimir-coko** [comment]
ci:forward

**Pull request closed without merging**
