### PR TITLE
LCD-14473 - JavaScript OAuth client library/API in DXP

### PR DESCRIPTION
**Pull request by bryceosterhaus**
Resend from https://github.com/liferay-frontend/liferay-portal/pull/2724

cc  @rotty3000

### CODE REVIEW

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by mateusralv** [comment]
Hey @bryceosterhaus. Analyzing the last results of [ci:test:relevant](https://github.com/liferay-frontend/liferay-portal/pull/2736#issuecomment-1252246914): 
###  🔴 Unique failure: 
1. [com.liferay.document.library.web.exportimport.data.handler.test.DLPortletDataHandlerTest
](https://testray.liferay.com/home/-/testray/case_results/1983911479)

```
[exec] com.liferay.document.library.web.exportimport.data.handler.test.DLPortletDataHandlerTest > testPublishedCustomRepositoryEntriesPrepareManifestSummary FAILED
     [exec]     java.lang.AssertionError
     [exec]     	at org.junit.Assert.fail(Assert.java:87)
     [exec]     	at org.junit.Assert.assertTrue(Assert.java:42)
     [exec]     	at org.junit.Assert.assertTrue(Assert.java:53)
     [exec]     	at com.liferay.document.library.web.exportimport.data.handler.test.DLPortletDataHandlerTest.testPublishedCustomRepositoryEntriesPrepareManifestSummary(DLPortletDataHandlerTest.java:455)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec]     	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec]     	at java.lang.reflect.Method.invoke(Method.java:498)
     [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$3.evaluate(TestExecutorRunnable.java:353)
     [exec]     	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
     [exec]     	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
     [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$1.evaluate(TestExecutorRunnable.java:237)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
     [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable._execute(TestExecutorRunnable.java:316)
     [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable.run(TestExecutorRunnable.java:95)
     [exec]     	at java.lang.Thread.run(Thread.java:745)
```

---
###  🟢 Failures, not unique: 

1. com.liferay.digital.signature.manager.test.DSEnvelopeManagerTest
2. com.liferay.oauth2.provider.client.test.AnnotationsAndHttpPrefixApplicationClientTest
3. com.liferay.staging.test.StagingImplTest

[Comparison run wit the master](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1663676892882&testrayRunIdA=1983747460&testrayRunIdB=1983910634)

---
###  🟢 Previously failures:

Tests failed previously are passing now:
1. OAuth2#AuthorizationCanBeIssuedWhenTokenIssuerMatchesWithSystemLevelOrInstanceLevel
2. [OAuth2#ConfigureOnSystemLevelShouldApplyToInstanceLevel](https://testray.liferay.com/home/-/testray/case_results/1983910712?)
3. [OAuth2#ExternalApplicationCanBeAddedAndEdited](https://testray.liferay.com/home/-/testray/case_results/1983910709)
4. [OAuth2#GrantedAuthorizationsCanBeRevoked](https://testray.liferay.com/home/-/testray/case_results/1983910662)
5. OAuth2#InstanceLevelConfigurationWillCoverSystemLevelWhenTheyConfiguredWithSameIssuer

**Comment by bryceosterhaus** [comment]
@mateusralv I have some doubts that [com.liferay.document.library.web.exportimport.data.handler.test.DLPortletDataHandlerTest](https://testray.liferay.com/home/-/testray/case_results/1983911479) is unique to this PR... This PR doesn't touch any code related to document library. Were you able to verify this failure locally?

**Comment by mateusralv** [comment]
Hi @bryceosterhaus Interesting 🤔, I looked at all the latest ci:test:relevant results and that test doesn’t show up, so it could have been a random error.

And it seems safe to forward the PR after this last analysis.

**Comment by bryceosterhaus** [comment]
@rotty3000 please confirm that this can be forwarded, just want to make sure you give it the go-ahead before sending since you wrote this.

**Comment by rotty3000** [comment]
Yeah I tested this. It's a good start.

**Comment by bryceosterhaus** [comment]
manual forward https://github.com/brianchandotcom/liferay-portal/pull/123600

**Pull request closed without merging**
