### PR TITLE
LPS-116927 Use ClassicEditor instead of Editor directly and add configs in Rich Text

### PR DESCRIPTION
**Pull request by matuzalemsteles**
Rebase #198 on top #264! It depends on #264.

---

### Setup

Before you can start testing this in the Journal, you need to add a new config in `osgi/configs`:

`com.liferay.journal.web.internal.configuration.JournalDDMEditorConfiguration.config`
```
useDataEngineEditor=B"true"
```

### Test case

1. Open the Menu and click on `Content & Data` and then `Web Content`
2. Click on `Structures` and create a new structure
3. Add a new "Rich text" field to the builder
4. Add a title and save
5. Click on `Web Content`
6. Create a new Web Content using the structure you just created

### Image

Screen Shot 2020-07-31 at 19 20 03

### CODE REVIEW

**Comment by jbalsas** [comment]
#264 is at brian now! -> https://github.com/brianchandotcom/liferay-portal/pull/92886

**Comment by matuzalemsteles** [comment]
ci:test:sf

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by matuzalemsteles** [comment]
ci:test:sf

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
I think @brunobasto already signed this off when we reviewed it initially... so going to give it a try, maybe? 🤞

**Comment by jbalsas** [comment]
ci:forward

**Pull request closed without merging**
