### PR TITLE
LPS-198764 Adding tests for Icon in the Data Set Actions

### PR DESCRIPTION
**Pull request by JerryAdrianoo**
**Description:**
Adding tests for some functions in the icon field, such as: delete, change, add.. etc.

**Jira Ticket:**
https://liferay.atlassian.net/browse/LPS-198764

### CODE REVIEW

**Comment by JerryAdrianoo** [comment]
ci:test:frontend

**Comment by JerryAdrianoo** [comment]
@CarlosBrichete failures are unrelated :)

**Comment by CarlosBrichete** [comment]
ci:forward

**Comment by CarlosBrichete** [comment]
ci:forward

**Comment by CarlosBrichete** [comment]
ci:forward

**Comment by CarlosBrichete** [comment]
@JerryAdrianoo can you close this PR and resend again? no need to run the tests again, just resend and forward it directly. This one seems to be glitched :/

**Pull request closed without merging**
