### PR TITLE
LPS-158820 Import `getOpener` instead of using `Liferay.Util.getOpener`

### PR DESCRIPTION
**Pull request by kresimir-coko**

### CODE REVIEW

**Comment by kresimir-coko** [comment]
ci:stop

**Comment by kresimir-coko** [comment]
ci:test:sf

**Comment by kresimir-coko** [comment]
ci:test:relevant

**Comment by mateusralv** [comment]
I'm taking look.

**Comment by mateusralv** [comment]
Hi @kresimir-coko, the most failures also occurring on the master ([comparison run](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1658754520181&testrayRunIdA=1915854446&testrayRunIdB=1916118230)). 

This test have unique failures:
- `PageAudit#CheckMissingInputALTAttributes` It returned a Poshi failure:
```
   BUILD FAILED: Element is not present at "//*[contains(@class, 'progress-bar')]"
     [exec]     /opt/dev/projects/github/liferay-portal/portal-web/test/functional/com/liferay/portalweb/macros/layout/pageaudit/PageAudit.macro[runPageAudit]:223
     [exec]     /opt/dev/projects/github/liferay-portal/portal-web/test/functional/com/liferay/portalweb/tests/enduser/pageaudit/PageAudit.testcase[CheckMissingInputALTAttributes]:898
```
But looking at the[ poshi report I](https://testray.liferay.com/reports/production/logs/2022-07/test-1-36/test-portal-acceptance-pullrequest(master)/1652/functional-tomcat90-mysql57-jdk8/26/4/LocalFile.PageAudit_CheckMissingInputALTAttributes/index.html.gz?authuser=0) see that it is a flake failure. To confirm I ran it locally in the PR bundle and the test passed.

I looked at the others failures and don't seem related to your PR, so it is ok to move forward from QA perspective.

cc: @john-co

**Comment by kresimir-coko** [comment]
ci:forward

**Comment by kresimir-coko** [comment]
Manually forwarded https://github.com/brianchandotcom/liferay-portal/pull/120872

**Pull request closed without merging**
