### PR TITLE
LPS-191296 Functional tests:  Use date filters defined in fragment

### PR DESCRIPTION
**Pull request by mateusralv**
Description:
Add poshi tests Poshi tests related to date filters in Data Set Fragment

[LPS-185991](https://liferay.atlassian.net/browse/LPS-185991)

### CODE REVIEW

**Comment by mateusralv** [comment]
ci:test:frontend-data-set

**Review by CarlosBrichete — APPROVED** [review]
LGTM

**Comment by mateusralv** [comment]
ci:test:sf

**Comment by mateusralv** [comment]
ci:test:frontend-data-set

**Comment by mateusralv** [comment]
ci:test:sf

**Comment by mateusralv** [comment]
ci:test:frontend-data-set

**Comment by mateusralv** [comment]
ci:test:frontend-data-set

**Comment by mateusralv** [comment]
ci:test:sf

**Comment by mateusralv** [comment]
ci:test:frontend-data-set

**Comment by mateusralv** [comment]
All tests passed the CI 🎉

**Comment by mateusralv** [comment]
ci:forward

**Pull request closed without merging**
