### PR TITLE
LPD-41251 Extract inline event handlers in RowChecker

### PR DESCRIPTION
**Pull request by izaera**
**QA analysis**: :green_circle: https://github.com/liferay-frontend/liferay-portal/pull/4565#issuecomment-2487901166
**Sign-off**: :green_circle: https://github.com/liferay-frontend/liferay-portal/pull/4565#pullrequestreview-2447840999

----

This is part of https://github.com/liferay-frontend/liferay-portal/pull/4466 (root PR for CSP inline event handlers).

It is in the high risk group, which is composed of infra stuff used pervasively that may break a lot of tests for different teams.

> ⚠️ Note that even though this PR may break tests it doesn't mean it breaks the product.
> Tests can break because:
>
> 1. A bug is introduced in the product, or
> 2. They rely on internals of the taglib changed in the PR

Since the taglib is used almost everywhere we don't have any specific CI test suite to run (we would need to run all of them to make sure). And since we run all tests suites every day on a batch schedule we will rely on that to detect big failures unless someone can find a better way (I'm open to suggestions).

In any case, I've tested one occurence of the tag by hand following the procedure described at https://liferay.atlassian.net/browse/LPD-41251?focusedCommentId=2790402 and https://liferay.atlassian.net/browse/LPD-41251?focusedCommentId=2790383 to make sure it's not very badly broken.

### CODE REVIEW

**Comment by izaera** [comment]
ci:test:relevant

**Comment by izaera** [comment]
I'm running tests again to filter out false positives (because there are many of them failing)

**Review by juanjofgliferay — APPROVED** [review]
LGTM :rocket:

**Comment by izaera** [comment]
ci:report:72258280

**Comment by izaera** [comment]
QA analysis:

- **DLFileEntryFinderTest**: this is a flaky test and the exception (ORM related) that makes it fail is not justified by the changes in this PR.
- **AccountMemberResourceTest**: this is a flaky test and the exception (`NoClassDefFoundError`) that makes it fail is not justified by the changes in this PR.
- **DefaultObjectEntryManagerImplTest**: this is a flaky test.

**Comment by izaera** [comment]
I'm forwarding this as @dsanz got the OK from Brian in a private conversation even though the performance of the solution is still being evaluated (see https://github.com/brianchandotcom/liferay-portal/pull/156300). The plan is to keep merging while we decide the other stuff.

**Pull request closed without merging**
