### PR TITLE
LPD-18862 Adapt Global JS sample to support the new caching mechanism

### PR DESCRIPTION
**Pull request by izaera**

### CODE REVIEW

**Comment by izaera** [comment]
ci:test:relevant

**Comment by izaera** [comment]
Force forwarding as per -> https://github.com/liferay-frontend/liferay-portal/pull/4019#issuecomment-1968759090

I will send follow up commit according to this -> https://github.com/liferay-frontend/liferay-portal/pull/4019#pullrequestreview-1908154390 but I will push them to that PR and will forward this as is.

**Review by bryceosterhaus — APPROVED** [review]
👍 👍

**Comment by izaera** [comment]
ci:forward:force

**Pull request closed without merging**
