### PR TITLE
WIP: Playwright second iteration

### PR DESCRIPTION
**Pull request by chestofwonders**
This PR continues the work from https://github.com/liferay-frontend/liferay-portal/pull/3924 I've continued in a new branch because current work it's not related to any LPS yet.

Main goals of this PR:

- Fixed suggestions/comments from previous PR
- Refactor pages (specially constructors)
- Added an example of test data creation and deletion on a page fixture for reusability.  So any test that depends on that page can use test data by default.
- Added method for created test data by API, whose implementation on the fixture is being a pain. So, I just leave both methods for creation -UI and API based-. Feel free to complain against them. We could find better naming.

### CODE REVIEW

**Comment by izaera** [comment]
LGTM

I'm a bit worried about adding methods to create test data in the pages. To me it looks like an internal helper (or global if other teams would use it in their tests) would suit that function better, but I'm not especially convinced of the superiority of any of the two methods, so.... :shrug:

**Comment by chestofwonders** [comment]
ci:forward

**Comment by chestofwonders** [comment]
ci:test:sf

**Review by markocikos — CHANGES_REQUESTED** [review]
@chestofwonders There is something wrong with the branch of this PR, it contains 2296 unique commits. This makes it very hard to review, in fact my browsers lags and crashes when I look at changes. Please rebase to master and force push.

Also a nit, please change PR title to contain issue number. This will make it easier to search later on.

**Pull request closed without merging**
