### PR TITLE
LPS-160314 - Sanitize content before setting href

### PR DESCRIPTION
**Pull request by bryceosterhaus**
https://issues.liferay.com/browse/LPS-160314

This should be backported to 7.0.X, 7.1.X, 7.2.X, 7.3.X as well

### CODE REVIEW

**Comment by bryceosterhaus** [comment]
ci:test:sf

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Review by kresimir-coko — APPROVED** [review]
Great!

**Comment by bryceosterhaus** [comment]
ci:forward

**Pull request closed without merging**
