### PR TITLE
[TS] LPS-125881 Fix Liferay.Util.openWindow config title value

### PR DESCRIPTION
**Pull request by rolandpakai**
Hi Team,

could you plesae check my fix and push it forward?

Thanks, Roland

https://issues.liferay.com/browse/LPS-125881

### CODE REVIEW

**Comment by julien** [comment]
Hi @rolandpakai thanks for submitting this fix.

I tested the change and it does fix the issue described in [LPS-125881](https://issues.liferay.com/browse/LPS-125881) and the code change looks OK to me.

I'll let @carloslancha have a look at this too,  the previous change was added in [this commit](https://github.com/liferay/liferay-portal/commit/d7cd5e652d3e88eea1582a8655e9492ddd957de1) which he submitted; and he might have something to say.

**Comment by rolandpakai** [comment]
Thank you @julien 

I also found Carlos changes on LPS-62332
https://issues.liferay.com/browse/LPP-39994?focusedCommentId=2351833&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-2351833

**Comment by carloslancha** [comment]
Hey @rolandpakai I'm not sure right know why we went with `&nbsp;` instead an empty string (long time since 2016 xD), probably something related with some styles breaking or some IE stuff if I have to bet.

Just check that everything is working as expected, if so this LGTM. Thx!!

**Comment by rolandpakai** [comment]
Thank you @carloslancha for checking the change.

Could you please push it forward?

Thanks, Roland

**Comment by julien** [comment]
Yes sure. we can

**Comment by julien** [comment]
ci:forward

**Pull request closed without merging**
