### PR TITLE
LPS-120347 Some unexpected things are happening when selecting the image with the item selector

### PR DESCRIPTION
**Pull request by boton**
**Steps to reproduce:**

- Add a blank page
- Add an Image fragment to the page
- Double click the fragment to add an image
- Upload an image (or select an available one)

**Before the fix:**
- Selecting one image and try to change come into a loop
- Clear button is opening the modal

**After the fix:**
- Item selector disappears and image is displayed on the fragment.
- Clear button clear the value

---

I realized that the onClose function was lost in some refactor, I just put it back.

I tested and fixed in `da23ec114d56d3d2e42c23606b0e8fc847b9332a` in master.

/cc @liferay-echo

### CODE REVIEW

**Comment by boton** [comment]
ci:test:sf

**Comment by boton** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
cc: @jbalsas

**Review by jbalsas — APPROVED** [review]
LGTM! Tested locally and works as expected too!

The `relevant` failures looks like a fluke, will re-run and submit manually if it doesn't pass.

**Comment by jbalsas** [comment]
I was going to forward this, but I'm wondering if this is the right fix...

Since this is the openSelectionModal, I think it might make more sense to move the calling logic into the onSelect rather than to the onClose.

If someome can analyze that, otherwise I'll take a look before forwarding. The API sounds like it could be useful but I don't want to it unless strictly necessary.

**Comment by boton** [comment]
I could review it tomorrow. I agree it can be implemented in the onSelect but I'm not confident about changing this part in the page editor, because I don't know the consequences.

**Comment by jbalsas** [comment]
Okay, I did a quick check of the logic, and this is being used to cleanup something... which might not happen if there's no selection, so it stands to reason that we'll need an `onClose` so I'll forward this.

As a followup, @victorg1991, @p2kmgcl, out of https://github.com/liferay/liferay-portal/blob/master/modules/apps/layout/layout-content-page-editor-web/src/main/resources/META-INF/resources/page_editor/core/openImageSelector.js#L23-L46
- [`if (selectedItem)`](https://github.com/liferay/liferay-portal/blob/master/modules/apps/layout/layout-content-page-editor-web/src/main/resources/META-INF/resources/page_editor/core/openImageSelector.js#L23) should no longer be needed. The `onSelect` callback will only be called if there is indeed a selection
- The [`else`](https://github.com/liferay/liferay-portal/blob/master/modules/apps/layout/layout-content-page-editor-web/src/main/resources/META-INF/resources/page_editor/core/openImageSelector.js#L41-L45) branch will never be reached because there should always be a `selectedItem`

- The destroyCallback will always be called when the dialog is closed so everything should be disposed properly. Please, take a look to try clean that up if possible!

**Comment by jbalsas** [comment]
ci:forward

**Pull request closed without merging**
