### PR TITLE
LPD-21541 & LPD-21542 & LPD-21543

### PR DESCRIPTION
**Pull request by dsanz**
This is a followup of https://github.com/liferay-frontend/liferay-portal/pull/4047 (which I closed), where:

- We remove flakiness when selecting the "Client Extension" filter as default timeout was too short
- We avoid a costly `page.goto('/')` call just before posting a new site

### CODE REVIEW

**Comment by dsanz** [comment]
ci:test:playwright

**Comment by dsanz** [comment]
ci:test:sf

**Comment by dsanz** [comment]
ci:test:playwright

**Comment by dsanz** [comment]
ci:test:sf

**Comment by dsanz** [comment]
ci:test:playwright

**Comment by dsanz** [comment]
ci:test:sf

**Comment by dsanz** [comment]
ci:test:sf

**Comment by dsanz** [comment]
ci:test:playwright

**Review by markocikos — APPROVED** [review]
@dsanz LGTM! The failures in https://github.com/liferay-frontend/liferay-portal/pull/4112#issuecomment-2039517221 are not related.

**Comment by markocikos** [comment]
ci:test:relevant

**Comment by markocikos** [comment]
ci:report:2558803817

**Comment by markocikos** [comment]
No unique failures, based on https://github.com/liferay-frontend/liferay-portal/pull/4112#issuecomment-2039850552

**Comment by markocikos** [comment]
ci:forward:force

**Pull request closed without merging**
