### PR TITLE
LPS-115204 Adds hydration support to clay:navigation-bar

### PR DESCRIPTION
**Pull request by zhangyan0701**
Based on [liferay-frontend#8](https://github.com/liferay-frontend/liferay-portal/pull/8)

--- 

This is a resend of the hydration of the `NavigationBar` component that was supposed to fix [The dropdown list of the site scope is missing in the define permission](https://issues.liferay.com/browse/LPS-115204) but [got reverted](https://github.com/brianchandotcom/liferay-portal/pull/90123) because it caused [Property 'label' is undefined when click Import button of page fragment collections
](https://issues.liferay.com/browse/LPS-115521) and in fact also [Clicking on rules tab redirects to form builder](https://issues.liferay.com/browse/LPS-115498)

This PR aims to bring back the fix without introducing the other regressions 🤞 

Based on this [comment](https://github.com/wincent/liferay-portal/pull/356/commits/585b85c1a0893e4b572ef002f152f687fc7688f7#r440372317)

> When ClayLink renders the a element, React won't insert an empty href attribute in the DOM. At least, if href is undefined (in contrast, if it is an empty string, it will):

I've taken the liberty to push a couple of additional commits to make sure we don't set `StringPool.BLANK` as the default value in `NavigationItem` objects so values are more explicit and easier to reason with. We can drop those if they cause any trouble.

Additionally... there's the question about what to do if `navigationItems` are not passed to the component... I thought about just no rendering anything from the backend if no items were passed... or simply not render anything from React... but it feels like making a very strong assumption about what the user wants, so I've tabled that for further discussion and simply [stopped rendering clay:navigation-bar when unneeeded](https://github.com/liferay-frontend/liferay-portal/pull/8/commits/679406323fada79d2a2ba03e0f477fc812761e4e).

### CODE REVIEW

**Comment by zhangyan0701** [comment]
ci:test:sf

**Comment by zhangyan0701** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
Hey @zhangyan0701, thanks a lot for looking over this!

I wanted to ask you to do something else for us in the future :)

As you can see, we're starting to be very careful with our PR descriptions and titles. This is a conscious effort by the whole team to improve our processes and make sure all the information is available at any level in the chain (pre and post merge). Keep in mind that when running `ci:forward` both the title and description is the information that gets carried over to brian which often can benefit from this.

When forwarding or resending our PRs, could please make sure you copy over the titles and descriptions along with any existing additional breadcrumb or comments that might provide valuable information?

I've edited the description and title in this PR to reflect what I think we'd be looking for, so we would be extremely grateful if you could keep this in mind the future as well!

/cc @john-co, @manoelcyreno so you're aware too
/cc @wincent, in case you want to add something ;)

**Comment by zhangyan0701** [comment]
> **When forwarding or resending our PRs, could please make sure you copy over the titles and descriptions along with any existing additional paper trail or comments** that might provide valuable information?
> 
> I've edited the description and title in this PR to reflect what I think we'd be looking for, so we would be extremely grateful if you could keep this in mind the future as well!

@jbalsas , Thanks for updating the description and title! Yes, in the future I will copy titles and descriptions into the PR to make sure it contains valuable information. And thanks for letting me know this!

**Comment by jbalsas** [comment]
yeah

**Comment by jbalsas** [comment]
Forwarding based on [previous approval](https://github.com/liferay-frontend/liferay-portal/pull/8#pullrequestreview-431379126) from @wincent 

> lg2m. Feel free to forward if you please.

**Comment by jbalsas** [comment]
ci:forward

**Pull request closed without merging**
