### PR TITLE
LPS-123529 Add status and sorting filters to management toolbar

### PR DESCRIPTION
**Pull request by adolfopa**
Dear Frontend Dwellers,

In this PR I'm updating a ManagementToolbarDisplayContext, adding some filter and order dropdown items. Everything seems to be working fine except for the button to change the sorting order, which fails to appear.

I've compared my implementation with other equivalent ones, and I don't see any major piece missing, so I need some help here. Can you provide some pointers as to what do I need to do so that the sorting button shows up?

To see the problem, deploy the `apps/translation/translation-web` module and go to Content & Data > Translation app in the product menu.

You'll need to add a translation first; for that:
- Go to Content & Data > Web Content
- Create a Basic Article (actual content doesn't really matter)
- Go to Content & Data > Web Content
- For the article you just created, select the "Translate" action from its action dropdown
- Type anything in the side by side and click Publish

Thanks!

### CODE REVIEW

**Comment by carloslancha** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by carloslancha** [comment]
Hey @adolfopa the Management Toolbar component is not receiving any `sortingOrder` value, that's why the button is not being showed.

In models (display context) this value is retrieve from [`BaseManagementToolbarDisplayContext.getSorgingOrder`](https://github.com/liferay/liferay-portal/blob/c74cbb3487428c54ae2122c205af3c954e0e01a3/modules/apps/frontend-taglib/frontend-taglib-clay/src/main/java/com/liferay/frontend/taglib/clay/servlet/taglib/display/context/BaseManagementToolbarDisplayContext.java#L110) which calls [`BaseManagementToolbarDisplayContext.getOrderByType`](https://github.com/liferay/liferay-portal/blob/c74cbb3487428c54ae2122c205af3c954e0e01a3/modules/apps/frontend-taglib/frontend-taglib-clay/src/main/java/com/liferay/frontend/taglib/clay/servlet/taglib/display/context/BaseManagementToolbarDisplayContext.java#L263) and sets it to "asc" by default.

But this displayContext extends from [`SearchContainerManagementToolbarDisplayContext`](https://github.com/liferay/liferay-portal/blob/c74cbb3487428c54ae2122c205af3c954e0e01a3/modules/apps/frontend-taglib/frontend-taglib-clay/src/main/java/com/liferay/frontend/taglib/clay/servlet/taglib/display/context/SearchContainerManagementToolbarDisplayContext.java) which overrides `getOrderByType` method and [returns the value from the searchContainer instance](https://github.com/liferay/liferay-portal/blob/c74cbb3487428c54ae2122c205af3c954e0e01a3/modules/apps/frontend-taglib/frontend-taglib-clay/src/main/java/com/liferay/frontend/taglib/clay/servlet/taglib/display/context/SearchContainerManagementToolbarDisplayContext.java#L90)

As far as I can see this application displayContext [`ViewDisplayContext`](https://github.com/liferay-frontend/liferay-portal/blob/a92ce10e553fc285a490ec1773e33d61ed6f6669/modules/apps/translation/translation-web/src/main/java/com/liferay/translation/web/internal/display/context/ViewDisplayContext.java) is not defining any `orderType` for the searchContainer, so I guess that's what is missing. 

In Blogs for example it's being done [here](https://github.com/liferay-frontend/liferay-portal/blob/a92ce10e553fc285a490ec1773e33d61ed6f6669/modules/apps/blogs/blogs-web/src/main/java/com/liferay/blogs/web/internal/display/context/BlogEntriesDisplayContext.java#L164).

Another approach would be to override the `getSortingOrder` method (example in [JournalManagementToolbarDisplayContext](https://github.com/liferay-frontend/liferay-portal/blob/a92ce10e553fc285a490ec1773e33d61ed6f6669/modules/apps/journal/journal-web/src/main/java/com/liferay/journal/web/internal/display/context/JournalManagementToolbarDisplayContext.java#L402)

Please, let me know if following any of these approaches solves the problem.

Thx!

**Comment by carloslancha** [comment]
Hey @adolfopa @boton @ambrinchaudhary did this work for you? Can we close the pr? Thx!

**Comment by ambrinchaudhary** [comment]
> Hey @adolfopa @boton @ambrinchaudhary did this work for you? Can we close the pr? Thx!

Hi @carloslancha, @adolfopa is on PTO today, he can check your solution tomorrow, which totally makes sense. So here, is up to you, we can wait for tomorrow for his confirmation, or close this and if it doesn't fix the problem we create a new one. 

Thanks for your help!

**Comment by carloslancha** [comment]
I'm ok with leaving this open until is solved, just wanted to check. Thx @ambrinchaudhary !

**Comment by adolfopa** [comment]
Initializing the sorting stuff in the SearchContainer fixed everything. Thanks a lot for your help @carloslancha !

**Pull request closed without merging**
