### PR TITLE
LPS-118809: Line breaks disappear when selecting a user from mention.

### PR DESCRIPTION
**Pull request by holatuwol**
From: @dinh-thai
> This issue relate to the changed of ticket https://issues.liferay.com/browse/LPS-47033.
The current logic code is after autocomplete, it will remove next node if that node not include white space.

### CODE REVIEW

**Comment by jbalsas** [comment]
Hey @holatuwol, can we get some additional information on [LPS-117986 Fixes query selection in CKEditor autocomplete plugin](https://github.com/liferay-frontend/liferay-portal/pull/223) before moving forward with this? 

@dinh-thai, could you confirm that with the changes in https://github.com/liferay-frontend/liferay-portal/pull/223 this issue is still present?

The current autocomplete implementation is brittle enough that I feel honestly uneasy adding new changes without properly understanding everything that's going, being afraid of us having to go back and forth.

I also created [Replace autocomplete implementation](https://issues.liferay.com/browse/LPS-118804) to move to CKEditor's out of the box autocomplete support, but in the meantime, let's move one step at a time, here, please? 🙏

**Comment by dinh-thai** [comment]
> @dinh-thai, could you confirm that with the changes in #223 this issue is still present?

Hi @jbalsas 
I checked with latest version which included the changed in #223, this issue is still present.
I attached recording my screen at [LPP-38497](https://issues.liferay.com/browse/LPP-38497)
Regards,
Dinh

**Comment by jbalsas** [comment]
Hey @dinh-thai, thanks for the additional information. I was able to verify the issue and play around with this for a little while.

I saw some edge cases with the current solution regarding autocomplete activation maybe caused by some of the caret selection changes. 

Could you test this snippet instead to see if that addresses this issue and validate it in different types of scenarios?

```javascript
var nextElement = newElement.getNext(function (node) {
	return (
		node.type !== CKEDITOR.NODE_TEXT || node.getText().trim()
	);
});

if (nextElement && nextElement.$.nodeName === 'BR') {
	nextElement = null;
}
```

With this, we keep most logic in the same place and the rest just depends on `nextElement` being or not present, thus avoiding us having to repeat different conditionals all over the place. I've added an additional filter method to the `getNext` call so that we skip dummy text nodes that can be added at the end of lines before a `br` tag.

Please, could you give this a try and let us know how it looks?

**Comment by dinh-thai** [comment]
> Please, could you give this a try and let us know how it looks?

Hi @jbalsas ,
I try as you suggest and your solution is solved this issue.
In another case, I've found other issue and it is created at [LPP-38588](https://issues.liferay.com/browse/LPP-38588). (This issue is able to reproduce on master, not only on changed code).
How do you think if I update changed code as your suggest and send PR to Minh Chau Dang, then he will send it to you?

**Comment by jbalsas** [comment]
Hey @dinh-thai!

> How do you think if I update changed code as your suggest and send PR to Minh Chau Dang, then he will send it to you?

Just push the changes to this branch and we can continue the review and forward when ready. No need for additional PRs.

**Comment by dinh-thai** [comment]
Hi @jbalsas ,
I can not push my code to remote of Minh Chau Dang, so I create new Pull Request for you.
[liferay-frontend#274](https://github.com/liferay-frontend/liferay-portal/pull/274)
I will close this Pull Request.

**Comment by jbalsas** [comment]
Superseeded by liferay-frontend#274

**Pull request closed without merging**
