### PR TITLE
LPS-190391 Test Fix for Data Set Poshi tests

### PR DESCRIPTION
**Pull request by mateusralv**
**Description**
This PR contains the test fix:

1. DataSet#CanDiscartChangesOnCancelButton
2. DataSet#CanRenameDataSet
3. DataSet#CanViewRenameDataSetModal
4. DataSet#CanViewRenameMenuOption

Added Ignore in the test:

1. DataSet#CannotLeaveNameFieldEmpty (Blocked by LPS-191845)

**Jira Ticket:**
https://liferay.atlassian.net/browse/LPS-190391

### CODE REVIEW

**Comment by mateusralv** [comment]
ci:test:sf

**Comment by mateusralv** [comment]
ci:test:frontend-data-set

**Comment by mateusralv** [comment]
ci:test:sf

**Comment by mateusralv** [comment]
ci:test:frontend-data-set

**Comment by mateusralv** [comment]
ci:test:sf

**Comment by mateusralv** [comment]
ci:test:frontend

**Comment by mateusralv** [comment]
Hi @CarlosBrichete the fix worked on the CI, could you take a look? Thaaanks :)

**Review by CarlosBrichete — APPROVED** [review]
LGTM :)

**Comment by mateusralv** [comment]
ci:forward

**Pull request closed without merging**
