### PR TITLE
[TS] LPS-185312 Escape the list elements of input-move-boxes

### PR DESCRIPTION
**Pull request by markgulacsy**
Hi team,

I fixed an XSS issue with the input-move-boxes tag in the liferay-ui taglib.
[LPS-185312](https://issues.liferay.com/browse/LPS-185312)
Could you review my changes, please?

Thank you!

### CODE REVIEW

**Comment by bryceosterhaus** [comment]
LGTM. Just need either CI to pass or QA sign off before forwarding

**Comment by mateusralv** [comment]
I'm taking a look 🕵🏽

**Comment by samuelkong** [comment]
This looks like the wrong fix to me.
1. `label="<%= HtmlUtil.escapeAttribute(kvp.getValue()) %>` is wrong because the `label` attribute is ultimately not used in an tag attribute context. Therefore `HtmlUtil.escape` should be used instead. 
2. A user of `<aui:option>` should not need to know about point number 1 above. Therefore, the escaping should be done by/within the `<aui:option>` .

**Comment by bryceosterhaus** [comment]
>  1. `label="<%= HtmlUtil.escapeAttribute(kvp.getValue()) %>` is wrong because the `label` attribute is ultimately not used in an tag attribute context. Therefore `HtmlUtil.escape` should be used instead. 

We use escapeAttribute with aui:option in several instances already in portal, so either those need to be updated as well or it should be fine to use either escape or escapeAttribute. (TBH I don't know much about the HtmlUtil class to know the difference). Bust just going off whats already in portal, I don't see why we couldn't use one versus the other, unless the other instances need changing.

> A user of <aui:option> should not need to know about point number 1 above.

It's pretty common for us to not escape within the tag itself because there are cases where we do allow for passing in unescaped HTML. So we tend to defer to the user of the tag to provide the proper escaping for the context of their use case.

**Comment by samuelkong** [comment]
@bryceosterhaus 
Those other instances should be changed. 

Escaping always needs to be context specific. The following is not necessary the best example, but it should illustrate the point:
You must use `escape` if you have something like `<div><%= HtmlUtil.escape(untrustedData) %></div>` and you must use `escapeAttribute` if you have something like `<div name="<%= HtmlUtil.escapeAttribute(untrustedData) %>">foo</div>`


This is not taken from the actual aui:option code, but for example, let's assume we have:
```<aui:option value="<%= value %> " />```
And in start.jsp, this gets turned into:
```<option value="<%= value %>"><%= value %></option>```

How is the person calling <aui:option> suppose to pass the correct value?
`<aui:option value="<%= HtmlUtil.escapeAttribute(untrustedData) %>">`
 is wrong because this gets translated to 
`<option value="<%= HtmlUtil.escapeAttribute(value) %>"><%= HtmlUtil.escapeAttribute(value) %></option>`

`<aui:option value="<%= HtmlUtil.escape(untrustedData) %>">`
 is also wrong because this gets translated to 
`<option value="<%= HtmlUtil.escape(value) %>"><%= HtmlUtil.escape(value) %></option>`

What you really need is 
`<option value="<%= HtmlUtil.escapeAttribute(value) %>"><%= HtmlUtil.escape(value) %></option>`
But there's no way for the person calling <aui:option> to pass the correct data.

Well, there's no way unless you change the <aui:option> taglib to something like:
`<aui:option valueEscaped="<%= HtmlUtil.escape(untrustedData) %>" valueAttributeEscaped="<%= HtmlUtil.escapeAttribute(untrustedData) %>">`
But it gets worse. As I said above, escaping is always context specific, so something more realistic is:
`<aui:option valueEscaped="<%= HtmlUtil.escapeAttribute(untrustedData) %>" valueAttributeEscaped="<%= HtmlUtil.escapeAttribute(untrustedData) %>" valueCssEscaped="<%= HtmlUtil.escapeCSS(untrustedData) %>" valueJsEscaped="<%= HtmlUtil.escapeJs(untrustedData) %>">`
and it gets even worse because there are scenarios when even this is not enough. 
Of course this is only for one attribute. So, you'll need to repeat this for every other attribute the taglib has.

**Comment by markgulacsy** [comment]
Hi @samuelkong, @bryceosterhaus,

I am a little bit confused what should be the correct fix for this one? If I understand it correctly Sam suggests that we should rewrite all the places where we handled this type of XSS's with an escape and make it happen in the tag implementations (for example here in InputMoveBoxesTag.java).
Sam, could you help me with how should I modify this PR to make it a correct fix?

**Comment by samuelkong** [comment]
This should be fixed in `/aui/option/start.jsp`. Something along the line of:
```
<option ... value="<%= HtmlUtil.escapeAttribute(...) %>" ...>
<c:if test="<%= Validator.isNotNull(label) %>">
	<liferay-ui:message key="<%= HtmlUtil.escape(...) %>" ... />
</c:if>
```

**Comment by markgulacsy** [comment]
Hi,
I force-pushed the changes and moved the escaping into the aui option. Can this PR remain open or should I open a new one?

**Comment by markgulacsy** [comment]
ci:test:relevant

**Comment by markgulacsy** [comment]
ci:test:sf

**Comment by markgulacsy** [comment]
On the first ci:test:relevant run there were 1028 out of 1055 jobs passed.
On the second ci:test:relevant run there were 671 out of 1103 jobs passed.

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by mateusralv** [comment]
ci:bundles

**Comment by mateusralv** [comment]
ci:test:bundle

**Comment by mateusralv** [comment]
Hi @markgulacsy the failures are not related!

[Testray Comparison ](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1686675308222&testrayRunIdA=2340024116&testrayRunIdB=2340406594)

**Comment by markgulacsy** [comment]
Hi @mateusralv,
Thank you!

**Comment by evibudai** [comment]
Hi all, @bryceosterhaus @markgulacsy @samuelkong 
Sadly, Mark left the company, could you please give me an update on what is the next step with this PR?
I see that there were some fixes, and the last CI tests were quasi-successful, or at least the failures are not related to the fix, can you move this PR forward?

Thank you in advance!
Évi

**Comment by bryceosterhaus** [comment]
ci:forward:force

**Comment by bryceosterhaus** [comment]
@evibudai QA signed off and the code was reviewed. I will forward

**Comment by bryceosterhaus** [comment]
ci:forward:force

**Comment by evibudai** [comment]
Thank you @bryceosterhaus !

**Comment by bryceosterhaus** [comment]
manual forward https://github.com/brianchandotcom/liferay-portal/pull/136688

**Pull request closed without merging**
