### PR TITLE
[TS] LPS-130851 LPS-102563 Fix focusing

### PR DESCRIPTION
**Pull request by rolandpakai**
Hi,

reverting the "LPS-102563 Revert "LPS-102563 Fix focusing"" commit is fixing the issue.

@wincent @markocikos Could you please check my changes is cause any regression?

Thanks, Roland

https://issues.liferay.com/browse/LPS-130851

### CODE REVIEW

**Comment by wincent** [comment]
> @wincent @markocikos Could you please check my changes is cause any regression?

The only problem is that this component is used in several places. We could certainly regression test it for you, but it would be much easier for us if you shared your [test plan](https://github.com/liferay/liferay-frontend-projects/blob/master/guidelines/general/pull_requests.md#prefer) (see also [code review guidelines](https://github.com/liferay/liferay-frontend-projects/blob/dc7d947da927de33e556c7570c007325efa560dc/guidelines/dxp/code_review.md#guidelines)) with us so that we can see how you verified that it doesn't regress.

Any additional context you could provide would be helpful too, because this doesn't look to be a straight revert (or at least, not a `git revert`), because the commit message doesn't give the SHA-1 hash (or hashes) that it is undoing. Looking in the history, I think you're reverting [this](https://github.com/brianchandotcom/liferay-portal/pull/82157/commits/27a2a4aee38c30e904ff147951dc5a42367d3403), which itself reverted [this](https://github.com/brianchandotcom/liferay-portal/pull/82157/commits/60888ae8f456aa37a0a24fedbe3c9f290ef0f8df), but as I noted in _my_ revert, there are [a few issues](https://github.com/wincent/liferay-portal/pull/104#issuecomment-564487801):

> I've had time to do a little testing now this and there are a few bugs or behavior differences to fix (I'll do a bit of investigation and see if I can tackle them):
>
> - `Tab` is [supposed to navigate away](http://oaa-accessibility.org/examplep/treeview1/) from the treeview, but in this PR it jumps around the "+"/"-" buttons.
> - Seems you can't select the first item in any list with `Space` on the keyboard (you can click with the mouse though).
> - Hitting space causes the list to scroll a small amount in addition to selecting an item (this bug also happens in `master`); on this PR it will scroll by a large amount when on the first item of a list.
> - On initial load, list is partially expanded (it is supposed to be collapsed if there are no selected items).
>
> Not sure if anything else but that's what I saw in a first pass. If I can get it working I'll push something to the branch.

So I am a bit concerned that reverting the revert is just going to introduce regressions elsewhere (and the code comes from December 2019, so my memory isn't exactly fresh on this stuff.

Please provide whatever context you can so that we can stop this from becoming a time sink and hopefully also control the risk a little bit.

**Comment by rolandpakai** [comment]
Hi @wincent 

thanks for checking it. I will test the above listed issues.

Thanks, Roland

**Comment by rolandpakai** [comment]
Hi @wincent 

### Reproduction steps from the https://issues.liferay.com/browse/LPS-130851

1. Create 10 widget pages: p1, p2, p3 .........
2. Create another widget page named fE: Read
. Add an Asset Publisher
. Configure the Asset Publisher: Display Settings > Set as the Default Asset Publisher for This Page
3. Create a new Web Content
. Select Display Page Template > Specific Display Page Template
. Click Select
. Open the Public Pages tab
. Scroll to 'Read'
. Click the 'Read' page

**Expected Result**
We can select the 'Read' page with one click/attempt

**Actual Result**
The first time 'Read' is selected the page jumps to the top of the list.
A second click on 'Read' is required to select it successfully

### Reproduction with Categories based on https://issues.liferay.com/browse/LPP-41164

1. Create a vocabulary, then 10 or more categories in it
2. Create a Web Content
3. Go to its categories
4. Scroll down the list, select a category

**Expected behavior:** Category should be selected
**Current behavior**: Category won't be selected and it jumps back to the top of the list

Based on my investigation i found  out that the **Treeview** componend is responsible for the tree view.
and in the source the biggest change was on LPS-102563. https://github.com/brianchandotcom/liferay-portal/pull/82157
One of the commits is fixing focusing but also reverting it.
LPS-102563 Fix focusing https://github.com/brianchandotcom/liferay-portal/pull/82157/commits/60888ae8f456aa37a0a24fedbe3c9f290ef0f8df
LPS-102563 Revert "LPS-102563 Fix focusing" https://github.com/brianchandotcom/liferay-portal/pull/82157/commits/27a2a4aee38c30e904ff147951dc5a42367d3403

For testing purpose i reverted LPS-102563 Revert "LPS-102563 Fix focusing"  and based on my tests it was fixing the issue.
I didnt reverted the tadindex='-1' change in the NodeListItem.js bacause it is breaking the tab navigation,

I also tested against the above listed issues as well and based on my tests they didnt breaks.

Thanks, Roland

**Comment by rolandpakai** [comment]
ci:test:sf

**Comment by rolandpakai** [comment]
Hi @wincent 

could you please check my last comment?

Thanks, Roland

**Comment by jbalsas** [comment]
Hey @rolandpakai, haven't checked on the specifics of the issue, but I think we don't usually accept "Revert of Revert" as commit messages. There's even a bot for that, although this one seems kinda manual 🤔 

In any case, I think our common pattern is to just reintroduce the commit again as if it were new.

@antonio-ortega, since this apparently already caused some regression and has raised some concerns, could you also help us out taking a look here? 🙏

**Comment by rolandpakai** [comment]
Hi @jbalsas 

thanks for letting me known. I updated the commit message.

Thanks, Roland

**Comment by rolandpakai** [comment]
Hi @antonio-ortega 

could you please look at my PR?

Thanks, Roland

**Comment by antonio-ortega** [comment]
Hi @rolandpakai ,

Can you raise a PTR so we can have a look together at the right solution for this case?

Thanks.

Regards.

**Comment by rolandpakai** [comment]
Thank you @antonio-ortega 

I opened the PTR here: https://issues.liferay.com/browse/PTR-2428

**Comment by markocikos** [comment]
I put this `on hold` for now, it looks we need to analyse the issue more before proceeding.

**Comment by georgel-pop-lr** [comment]
Just started reviewing :)

**Comment by markocikos** [comment]
Closing this PR, to reduce pulls page noise. For latest progress, see https://issues.liferay.com/browse/PTR-2428

**Pull request closed without merging**
