### PR TITLE
LPS-122399 Update loader-related frontend dependencies

### PR DESCRIPTION
**Pull request by wincent**
**:information_source: This is safe to backport to 7.3.x.**

These are just maintenance updates to reflect the migration of the `liferay-amd-loader` project to the named scope (ie. `@liferay/amd-loader`) version of the package. There should be no behavioral changes, but this bring the project into a namespace that we fully control.

There are some cascading side-effects of this, which mean that we have to additionally update `@liferay/npm-bundler-preset-liferay-dev` (because it references the loader), which in turn means we must update `@liferay/npm-scripts` (because it references the preset). Finally, we have to update `@liferay/npm-bundler` because it references the loader too.

Release notes for all of these:

- https://github.com/liferay/liferay-frontend-projects/releases/tag/amd-loader%2Fv4.3.1
- https://github.com/liferay/liferay-frontend-projects/releases/tag/npm-bundler-preset-liferay-dev%2Fv4.6.5
- https://github.com/liferay/liferay-frontend-projects/releases/tag/npm-scripts%2Fv33.1.4
- https://github.com/liferay/liferay-frontend-projects/releases/tag/npm-bundler%2Fv3.0.1

### CODE REVIEW

**Comment by wincent** [comment]
I haven't tested this yet, but wanted to get this up so that CI could get a head start. In the meantime, doing an `ant all`...

**Comment by wincent** [comment]
ci:test:sf

**Comment by wincent** [comment]
ci:test:relevant

**Comment by wincent** [comment]
ci:test:bundle

**Review by jbalsas — APPROVED** [review]
LGTM 👍

**Comment by wincent** [comment]
ci:stop

**Comment by wincent** [comment]
ci:test:sf

**Comment by wincent** [comment]
ci:test:relevant

**Comment by wincent** [comment]
ci:test:bundle

**Comment by jbalsas** [comment]
> Based on my local testing, I think I am going to have to squash this in here:

That's a good call and totally correct. I actually stopped at that diff initially but totally missed the extra folder now 🙈

**Comment by wincent** [comment]
> That's a good call and totally correct. I actually stopped at that diff initially but totally missed the extra folder now 🙈

AKA, "your PR is not horrible".

**Comment by jbalsas** [comment]
> AKA, "your PR is not horrible".

Yeah, I've seen worse PRs

**Comment by wincent** [comment]
> Yeah, I've seen worse PRs than this one

gee-thanks

**Comment by diegonvs** [comment]
image

Since @liferay-continuous-integration says its okay, Who am i to say otherwise?

LGTM!

**Comment by wincent** [comment]
ci:forward

**Pull request closed without merging**
