### PR TITLE
LPS-119041

### PR DESCRIPTION
**Pull request by holatuwol**
https://issues.liferay.com/browse/LPS-119041
https://liferay.slack.com/archives/C03CAD9EF/p1655693104695169

## Steps to reproduce

1. Start up Liferay and access it in a web browser
1. Open developer tools

:heavy_check_mark: Expected behavior is that the browser doesn't make request for source maps that do not exist / are not accessible
:heavy_multiplication_x: Actual behavior is that the browser makes a lot of requests that lead to 404s, flooding the developer console with warning messages

## Solution overview

As mentioned in the linked Slack channel, the TSE was able to figure out a way to address the issue on the server side by removing all the source maps in the Javascript files that are served via ComboServlet. We also found some specific instances where Javascript was inlined in DynamicInclude modules, and so those were fixed as well.

In earlier discussions, we weren't sure whether it made sense to have a server-side solution, so this pull request was made to start that conversation by providing an example of what that solution would look like.

### CODE REVIEW

**Comment by holatuwol** [comment]
ci:test:bundle

**Review by bryceosterhaus — COMMENTED** [review]
This seems fine by me, although would this make more sense to just disabled the source map generation at build time? We could check if NODE_ENV=production, and if it is then we don't generate the maps.

Either way, I am fine though.

**Comment by holatuwol** [comment]
ci:test:relevant

**Comment by izaera** [comment]
LGTM :+1: 

We can start with this, then do as @bryceosterhaus says in our build, to optimize the solution.

In any case, even if we do it in the build, I think we should leave this code, because there are corner cases we may not cover (eg: third party JS files) and also because we may want to remove source maps when files are aggregated/inlined but not when served on their own. In other words: it's the ComboServlet which should be responsible for removing the source maps, since it is the "culprit" of making them useless.

**Comment by susanchen3** [comment]
ci:test:relevant

**Comment by susanchen3** [comment]
Reviewed, [test failures](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=2&testrayRunIdB=1946669824&testrayRunIdA=1945892709&statusB=3) are unrelated :heavy_check_mark: Looks good to manually forward from QA perspective if ready on dev side.

**Comment by holatuwol** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/121863

**Pull request closed without merging**
