### PR TITLE
LPS-171607 Create a sample for FDS custom data renderer from an external component v2

### PR DESCRIPTION
**Pull request by markocikos**
### References

- [LPS-171607 Create a sample for FDS data renderer loaded from an external component](https://issues.liferay.com/browse/LPS-171607)
- Related Slack discussion: https://liferay.slack.com/archives/CNBG06JS3/p1671208032869539
- This is a followup on https://github.com/liferay-frontend/liferay-portal/pull/2920

### What is the goal of this PR?

Followup is based on https://github.com/brianchandotcom/liferay-portal/pull/128085#issuecomment-1364557265. We can reference `NPMResolver` directly.

/cc @dsanz @marcelabc

### CODE REVIEW

**Comment by markocikos** [comment]
CI failure looks unrelated. This is a followup, no need for peer review. Pushing!

**Comment by markocikos** [comment]
ci:forward

**Comment by mateusralv** [comment]
I'm taking a look 🕵🏽

**Comment by mateusralv** [comment]
Hey @markocikos the failures are not unique and unrelated to your PR. 🟢 

[Testray  Comparison](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1673369125650&testrayRunIdA=2154383316&testrayRunIdB=2154364945)

**Comment by markocikos** [comment]
I'll try one more time, manually forward if it fails.

**Comment by markocikos** [comment]
ci:forward

**Pull request closed without merging**
