### PR TITLE
LPS-120294 Allow changing existing images in CKEditor using the Image Dialog

### PR DESCRIPTION
**Pull request by jbalsas**
Issue discovered doing a review with Tarik from Echo about the migration from AlloyEditor to CKEditor.

**Steps to Reproduce**
- Navigate to `Content & Data > Web Content`
- Use the Image button to add an image previously uploaded to the `Document Library`
- Double click on the image element to show the image edition dialog
- Click on the `Browse Server` button to pick a different image
- Select a different image

image

**The problem**
We switched from `image` to `image2` as our default CKEditor plugin for images. Because of that, our logic to bind the `Browse Button` to execute our own command fails.

**The fix**
Add the necessary additional logic to cover the `image2` plugin use case

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:test:sf

**Comment by jbalsas** [comment]
ci:test:relevant

**Review by carloslancha — APPROVED** [review]
<a href="https://gitme.me/image?url=https%3A%2F%2Fmedia4.giphy.com%2Fmedia%2FPudZiAbQDUEik%2Fgiphy-downsized-medium.gif&token=approve" data-gitmeme-token="approve"></a>

**Review by julien — APPROVED** [review]

**Comment by carloslancha** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
I see pair of approvals, so Imma ship it!

**Comment by jbalsas** [comment]
ci:forward

**Pull request closed without merging**
