### PR TITLE
LPD-26184 - Ensure FDS with custom header does not display duplicated title

### PR DESCRIPTION
**Pull request by dsanz**
Continuation of https://github.com/liferay-frontend/liferay-portal/pull/4196, rebased + baseline commit

cc/ @juanjofgliferay @markocikos

### CODE REVIEW

**Comment by dsanz** [comment]
ci:forwrard

**Comment by dsanz** [comment]
ci:forward

**Comment by juanjofgliferay** [comment]
🚀

**Comment by dsanz** [comment]
ci:test:stable

**Comment by markocikos** [comment]
ci:report:2571664646

**Comment by markocikos** [comment]
no unique failures, based on https://github.com/liferay-frontend/liferay-portal/pull/4212#issuecomment-2128966315

**Comment by dsanz** [comment]
I've force-pushed this branch after rebasing it against `brianchandotcom/master` 

Goal is to check if stable suite passes here. Also, we are resolving conflicts in tests that otherwise would show up afterwards.

**Comment by dsanz** [comment]
ci:test:sf

**Comment by dsanz** [comment]
ci:test:stable

**Comment by dsanz** [comment]
ci:test:relevant

**Comment by dsanz** [comment]
ci:test:stable

**Comment by dsanz** [comment]
ci:test:sf

**Comment by dsanz** [comment]
Just force pushed agains new brianchandotcom/master as per [this message](https://liferay.slack.com/archives/C8AAQNS2E/p1716564512185369)

**Comment by dsanz** [comment]
ci:test:sf

**Comment by dsanz** [comment]
ci:test:stable

**Comment by dsanz** [comment]
Trying a new one after all the garbage we got in this one. See https://github.com/liferay-frontend/liferay-portal/pull/4218

**Pull request closed without merging**
