### PR TITLE
LPS-187257 Passing doAsUserLanguageId in session_click to avoid unwanted language changes

### PR DESCRIPTION
**Pull request by antonio-ortega**

### CODE REVIEW

**Comment by antonio-ortega** [comment]
ci:test:sf

**Comment by antonio-ortega** [comment]
ci:test:relevant

**Comment by antonio-ortega** [comment]
ci:test:relevant

**Comment by andreluis2022** [comment]
The failures seem to be unrelated to your PR according to this [comparison](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=2&testrayRunIdB=2412283511&testrayRunIdA=2412603815&statusB=3)

**Comment by dsanz** [comment]
@antonio-ortega any reason not to send this? thx

**Pull request closed without merging**
