### PR TITLE
LPS-120594 Update liferay-ckeditor to v4.11.1-liferay.12

### PR DESCRIPTION
**Pull request by julien**
[Changelog](https://github.com/liferay/liferay-ckeditor/releases/tag/v4.14.1-liferay.12)

### CODE REVIEW

**Review by wincent — APPROVED** [review]
Pre-emptive approval, assuming CI is going to be green.

**Comment by wincent** [comment]
ci:test:sf

**Comment by wincent** [comment]
ci:test:relevant

**Comment by wincent** [comment]
ci:test:bundle

**Comment by jbalsas** [comment]
Let's test our luck with another forward... @john-co, @PablitoBonito could you validate these failures if needed?

**Comment by jbalsas** [comment]
ci:forward

**Comment by john-co** [comment]
Just started reviewing :)

**Comment by john-co** [comment]
From the older test run: https://github.com/liferay-frontend/liferay-portal/pull/425#issuecomment-707767862

the tests seem like a fluke or flaky... @vicnate5 is there an existing issue for the Upgrade Test? 
https://testray.liferay.com/reports/production/logs/test-1-13/1602585447719/test-portal-acceptance-pullrequest(master)/4813/functional-upgrade-tomcat90-mysql57-jdk8_stable/6/0/jenkins-console.txt.gz

From the most recent test run:
https://github.com/liferay-frontend/liferay-portal/pull/425#issuecomment-708052862

It also seems like a flaky issue https://liferay.slack.com/archives/CLCD3DQLF/p1602633954046900?thread_ts=1602543127.038000&cid=CLCD3DQLF

**Comment by vicnate5** [comment]
@john-co Ticket for the blogs issue: https://issues.liferay.com/browse/LPS-122112

**Comment by PablitoBonito** [comment]
ci:forward

**Comment by john-co** [comment]
ci:forward

**Comment by john-co** [comment]
one more try...let's do a manual forward if this doesn't go through.

**Comment by vicnate5** [comment]
@john-co based on https://github.com/liferay-frontend/liferay-portal/pull/425#issuecomment-708344934, This should be manually forwarded.

Also, both issues that caused the failure should no longer occurring after today, we sent both a fix and quarantine to upstream.

**Pull request closed without merging**
