### PR TITLE
[TECHNICAL SUPPORT] LPS-152166 UserPortraitTag does not setAttributes for jsp override

### PR DESCRIPTION
**Pull request by NemethNorbert**
Hey,
[LPS-152166](https://issues.liferay.com/browse/LPS-152166)

The customer wanted to use the old feature of displaying user initials in our userPortrait taglib. However they failed to create the customisation due to the missing attributes we removed in https://github.com/liferay/liferay-portal/commit/c8aa67e0f80bfe920a2e106d14c641911c9bc3ef#diff-2dea5f2dacc39552fed8fd8f87c40ed8bb7e961aac3debc76c6060c07cdf7337

I added the attributes and also recreated the userInitials feature and shared it as an attribute in the request.

Please review my changes

### CODE REVIEW

**Comment by NemethNorbert** [comment]
ci:test:sf

**Comment by NemethNorbert** [comment]
ci:test:relevant

**Comment by NemethNorbert** [comment]
ci:test:sf

**Comment by NemethNorbert** [comment]
ci:test:relevant

**Comment by diegonvs** [comment]
This PR looks fine but I'm also worried since those things were removed due to performance but I can't see reasons or maybe more explanation on commit messages. I would request a review from someone of back-end.

**Comment by NemethNorbert** [comment]
Hey @diegonvs ,
Can you move this PR forward to someone of back-end or ask review from a specific team you think would suffice?
Thank you in advance,

**Comment by diegonvs** [comment]
Hey @NemethNorbert, sorry for late response but could you send this PR to https://github.com/liferay-core-infra/liferay-portal/pulls? 💔 

From FEI perspective I think it looks ok

**Pull request closed without merging**
