### PR TITLE
LPD-40849 Remove CKEditor underline format button

### PR DESCRIPTION
**Pull request by boton**
>[!NOTE]
> This PR is already reviewed here https://github.com/liferay-content-management/liferay-portal/pull/6056

# What is this trying to solve?

https://liferay.atlassian.net/browse/LPD-40849

Underline isn't working in Wiki CKEditor

# How am I fixing it?

I removed the underling because we accidentally added it in LPS-110019 (12dfaf5).

Before I realized that is included by accident I try to add support to underline in [frontend-editor-ckeditor/.../creole_data_processor.js](../blob/master/modules/apps/frontend-editor/frontend-editor-ckeditor-web/src/main/resources/META-INF/resources/_diffs/plugins/creole/creole_data_processor.js) but apparently, our current parser only supported [Creole 1.0](http://www.wikicreole.org/wiki/Creole1.0).

# How can you verify that it works?

1. Go to Site > Content & Data > Wiki
1. Main > Add a Page

Confirm the underline `U` format button is not in the toolbar.

## Before PR
image

## After PR
image

# Why doesn't this include any test?

We are removing a format button, which doesn't work before the PR.

### CODE REVIEW

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Review by markocikos — APPROVED** [review]
@boton LGTM! :sparkles:

**Comment by boton** [comment]
Thank you for the review, @markocikos. Can I forward it, or do we have to wait for further reviews?

**Comment by markocikos** [comment]
@boton If you are ok with it, and there is a green review from anybody, feel free to forward.

**Comment by boton** [comment]
ci:forward

**Pull request closed without merging**
