### PR TITLE
LPS-145387 Indexing translations by id instead of by label

### PR DESCRIPTION
**Pull request by sergiojimcos**
**Steps to reproduce:**

1. Go to Content & Data > Web Content > Structures.
2. Create new Structure with a default title and save it.
3. Edit the structure and select a new Locale (ie. es-ES) and change the title Language. Save it.
4. Go again to the structure and see in the Translation Admin Selector es-ES is translated.

**Expected Result**.
It will have the same behaviour but instead of being indexed by its label, it will be indexed by its id.

https://user-images.githubusercontent.com/44723449/152178045-5a79c164-030f-4d77-82e8-7c7855592768.mov

**JIRA TICKET:** https://issues.liferay.com/browse/LPS-145387

### CODE REVIEW

**Comment by julien** [comment]
@sergiojimcos don't worry too much about the "ci:test:sf" error because it's not caused by your changes - just so you know.

**Comment by carloslancha** [comment]
ci:test:sf

**Review by carloslancha — APPROVED** [review]
LGTM, Nice @sergiojimcos !

**Review by tinycarol — APPROVED** [review]
LGTM!

**Comment by julien** [comment]
ci:forward

**Pull request closed without merging**
