### PR TITLE
[7.4-only] LPS-102102 and LPS-102114 Remove compat-layer modals, splitter and tables

### PR DESCRIPTION
**Pull request by marcoscv-work**
[7.4-only] - Only master
---
This PR removes:
- Modals
- Splitter
- Tables

From the compatibility layer

--- 

## Previous PRs:
https://github.com/liferay-frontend/liferay-portal/pull/554
https://github.com/liferay-frontend/liferay-portal/pull/542

---

To test the PR:

- Global smoke test along portal, tables, and modals should work fine with some possible visual difference, if we find out a difference, please report it

### CODE REVIEW

**Comment by marcoscv-work** [comment]
ci:test:sf

**Comment by marcoscv-work** [comment]
ci:test:relevant

**Comment by marcoscv-work** [comment]
ci:stop

**Comment by marcoscv-work** [comment]
ci:test:stop

**Comment by marcoscv-work** [comment]
ci:test:sf

**Comment by marcoscv-work** [comment]
ci:test:sf

**Comment by marcoscv-work** [comment]
ci:test:relevant

**Comment by john-co** [comment]
Seems like a network issue with cdn?

```
     [exec] FAILURE: Build failed with an exception.
     [exec] 
     [exec] * What went wrong:
     [exec] Could not resolve all artifacts for configuration 'classpath'.
     [exec] > Could not resolve gradle.plugin.org.ysb33r.gradle:gradletest:2.0.
     [exec]   Required by:
     [exec]       unspecified:unspecified:unspecified
     [exec]    > Could not resolve gradle.plugin.org.ysb33r.gradle:gradletest:2.0.
     [exec]       > Could not get resource 'https://repository-cdn.liferay.com/nexus/content/groups/public/gradle/plugin/org/ysb33r/gradle/gradletest/2.0/gradletest-2.0.pom'.
     [exec]          > Could not HEAD 'https://repository-cdn.liferay.com/nexus/content/groups/public/gradle/plugin/org/ysb33r/gradle/gradletest/2.0/gradletest-2.0.pom'.
     [exec]             > Remote host closed connection during handshake
     [exec] > Could not resolve xalan:xalan:2.7.2.
     [exec]   Required by:
     [exec]       unspecified:unspecified:unspecified
     [exec]    > Could not resolve xalan:xalan:2.7.2.
     [exec]       > Could not parse POM https://repository-cdn.liferay.com/nexus/content/groups/public/xalan/xalan/2.7.2/xalan-2.7.2.pom
     [exec]          > Could not resolve org.apache:apache:4.
     [exec]             > Could not resolve org.apache:apache:4.
     [exec]                > Could not get resource 'https://repository-cdn.liferay.com/nexus/content/groups/public/org/apache/apache/4/apache-4.pom'.
     [exec]                   > Could not HEAD 'https://repository-cdn.liferay.com/nexus/content/groups/public/org/apache/apache/4/apache-4.pom'.
     [exec]                      > repository-cdn.liferay.com:443 failed to respond
```

**Comment by john-co** [comment]
ci:test:relevant

**Comment by john-co** [comment]
- Modal for file selector seems to be narrower than before causing some tabs within the modal to be displayed in a mobile version: 
image

- [NavigationMenuWidget#SelectGlobalNavigationMenuInNormalSite](https://testray.liferay.com/reports/production/logs/test-1-9/1606760130196/test-portal-acceptance-pullrequest(master)/4017/functional-tomcat90-mysql57-jdk8/2/4/LocalFile.NavigationMenuWidget_SelectGlobalNavigationMenuInNormalSite/index.html.gz) - fluke?

cc/ @zhangyan0701 @PablitoBonito , can someone investigate further?

**Comment by john-co** [comment]
ci:test:bundle

**Comment by zhangyan0701** [comment]
NavigationMenuWidget#SelectGlobalNavigationMenuInNormalSite seems a fluke, I wasn't able to reproduce locally.

**Comment by marcoscv-work** [comment]
Working on fixing the modal! but for compatibility tasks, we would rather go ahead with PR's and then open issues if needed

**Comment by eduardoallegrini** [comment]
Just started reviewing :)

**Comment by eduardoallegrini** [comment]
> * Modal for file selector seems to be narrower than before causing some tabs within the modal to be displayed in a mobile version:

I took a look and indeed it's breaking in forms but I think we shouldn't worry too much and go ahead with the PR. It can be fixed easily adding `.modal { max-width: none; }` to the module `src/main/resources/META-INF/resources/admin/css/_general.scss` but I rather upgrade the modal if it's possible instead of apply this patch
image
image

**Comment by jbalsas** [comment]
Hey @eduardoallegrini, not sure what "updating" the modal would mean, so I'd suggest to add that small hack to unblock this PR and then create an issue to remove it in the context of this same epic. 

Could you push that additional fix to see if we can push this forward!?

**Comment by eduardoallegrini** [comment]
Actually I was waiting because this is "the last resort" we talked about 😄

**Comment by marcoscv-work** [comment]
Need to update after https://github.com/brianchandotcom/liferay-portal/pull/96511

**Comment by eduardoallegrini** [comment]
https://github.com/liferay-frontend/liferay-portal/pull/580

**Comment by edalgrin** [comment]
Just started reviewing :)

**Comment by edalgrin** [comment]
Working on modals here https://github.com/liferay-frontend/liferay-portal/pull/644

**Pull request closed without merging**
