### PR TITLE
LPS-169287 HR_322 Dynamic Loading spinner has no equivalent alt-text

### PR DESCRIPTION
**Pull request by veroglez**
Fixes https://issues.liferay.com/browse/LPS-169287

I'm sending this fix because JAWS is not reading correctly the status message. It's necessary to take into account the loading status inside the StatusMessage component to ensure that the screen reader reads the message.

cc @eltonccdantas

### CODE REVIEW

**Comment by eltonccdantas** [comment]
Nice, waiting on CI's result in order to analyze it.

**Comment by CarlosBrichete** [comment]
ci:reevaluate:1367401_3505

**Comment by eltonccdantas** [comment]
ci:help

**Comment by eltonccdantas** [comment]
Let me check

**Comment by eltonccdantas** [comment]
ci:test:stable

**Comment by eltonccdantas** [comment]
Hey @veroglez , the failures are unrelated to me, let's just run `ci:stable` again and if it gets green you may forward it if no other dev review is needed.

I also saw it worked well in JAWS, so let me know as soon as [the ticket](https://issues.liferay.com/browse/LPS-169287) gets to ready for testing, so I can post the evidence and change the status for ready for release.
[Comparison Run](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=2&testrayRunIdB=2279991177&testrayRunIdA=2279895581&statusB=3)

**Comment by mateusralv** [comment]
I'm taking a look 🕵🏽

**Comment by ethib137** [comment]
Resending [here](https://github.com/liferay-frontend/liferay-portal/pull/3295) with fixed snapshots. Please close this one.

**Comment by ethib137** [comment]
ci:close

**Pull request closed without merging**
