### PR TITLE
LPS-135921 Fix if statements in ClayCard samples

### PR DESCRIPTION
**Pull request by julien**
As part of [LPS-112478](https://issues.liferay.com/browse/LPS-112478),
we [added|https://git.io/JWpIJ] 3 samples for ClayCard tags.
@hhuijser notified that there are 3 `if` statements that look incorrect
and need to be fixed.

### CODE REVIEW

**Review by carloslancha — APPROVED** [review]
TPRLNHTM :3

**Comment by julien** [comment]
I don't really know what's happening, but I might need to rebase with `master`, if that doesn't work, I'll ask help from QA.

**Comment by julien** [comment]
ci:test:relevant

**Comment by julien** [comment]
Hey @nkkwon could you please tell me if this is related to these changes when you get a chance? Thanks

**Comment by nkkwon** [comment]
It looks like this was caused by a flaky error that happened in acceptance too.
PR looks good to manually forward!

**Review by diegonvs — APPROVED** [review]
LNHTME!

**Comment by carloslancha** [comment]
ci:forwardw

**Comment by carloslancha** [comment]
ci:forward

**Pull request closed without merging**
