### PR TITLE
LPS-147943

### PR DESCRIPTION
**Pull request by holatuwol**
https://issues.liferay.com/browse/LPS-147943

/cc @hongvo2308 @sontruongces

Resend of https://github.com/liferay-frontend/liferay-portal/pull/2156 after running source formatter.

### Steps to reproduce

1. Go to Control Panel - Configuration - Language Override
1. Add a new language key
1. Search it or filter by Any Language

### Solution overview

Identified uses of "x-results-for" and replaced it, as needed, with a ternary statement that's still compatible with the pattern used by [Language.process](https://github.com/liferay/liferay-portal/blob/7.4.1-ga2/portal-impl/src/com/liferay/portal/language/LanguageImpl.java#L2028-L2031), used by LanguageFilter.

### CODE REVIEW

**Review by diegonvs — APPROVED** [review]
Good catch :)

**Comment by diegonvs** [comment]
ci:forward

**Comment by diegonvs** [comment]
ci:forward

**Comment by john-co** [comment]
Just started reviewing :)

**Comment by john-co** [comment]
Some test failures asserting "1 Results for" are failing. Will try adding a mass test fix for this.

Sample list of tests affected:
- https://testray.liferay.com/home/-/testray/case_results/1818508166
- https://testray.liferay.com/home/-/testray/case_results/1818358657
- https://testray.liferay.com/home/-/testray/case_results/1818505931

**Comment by john-co** [comment]
Running tests on test fix in https://github.com/john-co/liferay-portal/pull/460

**Comment by diegonvs** [comment]
Thanks John 💖

**Comment by john-co** [comment]
manually forwarded with test fix commit to https://github.com/brianchandotcom/liferay-portal/pull/117460

**Pull request closed without merging**
