### PR TITLE
LPD-21541 & LPD-21542 & LPD-21543

### PR DESCRIPTION
**Pull request by dsanz**
Back from https://github.com/liferay-headless/liferay-portal/pull/1974, this time including a new approach where the `LayoutModelDocumentContributor.java` takes care of populating the right value for  `CTX` attribute no matter the usage case where the index request takes place.

This should render any change in the REST builder unnecesary, so I'm also deleting the workaround added [here](https://github.com/liferay/liferay-portal/commit/f3cd9827aaf6febaddfb8c5d803e6859a45c9d55)

### CODE REVIEW

**Comment by dsanz** [comment]
ci:test:echo-headless

**Comment by dsanz** [comment]
ci:test:playwright

**Comment by dsanz** [comment]
ci:test:headless-functional

**Comment by dsanz** [comment]
ci:test:sf

**Comment by dsanz** [comment]
ci:test:playwright

**Comment by dsanz** [comment]
ci:test:echo-headless

**Comment by dsanz** [comment]
ci:test:headless-functional

**Comment by dsanz** [comment]
ci:test:relevant

**Comment by dsanz** [comment]
ci:test:stable

**Comment by ccorreagg** [comment]
See https://github.com/liferay-frontend/liferay-portal/pull/4149, I have included a commit with the REST Builder tests updated. It is not necessary to execute REST Builder under the workspaces

**Comment by markocikos** [comment]
Followup in https://github.com/liferay-frontend/liferay-portal/pull/4149

**Pull request closed without merging**
