### PR TITLE
LPS-165193 - Migrate frontend-js-walkthrough-web to new storage API

### PR DESCRIPTION
**Pull request by tinycarol**
### References

- [LPS-165193](https://issues.liferay.com/browse/LPS-165193)

### What is the goal?

* Migrate `localStorage` usages in `frontend-js-walkthrough-web` to new storage API

### How to replicate
* In your terminal, navigate to `liferay-portal/modules/apps/frontend-js/frontend-js-walkthrough-sample-web`, run `gradlew deploy -a`
* In your DXP instance, in the site menu navigate to `Site Builder > Pages`
* Add two widget pages: `/widget-page-1` and `/widget-page-2`
* Edit those pages so the routes correspond to the name
* Navigate to those pages and add the `JS Walkthrough sample` widget, as follows:

https://user-images.githubusercontent.com/6642927/200358879-24151668-5c2a-495b-ad1a-9fa751a9623c.mov

* Access `/widget-page-1`
* See that the blue button now has a blue circle (aka hotspot), as follows:
Captura de pantalla 2022-11-07 a las 17 13 08

* See that if you click it, the walkthrough is displayed, as follows:
Captura de pantalla 2022-11-07 a las 17 14 05

* Follow the previous steps with the cookie feature flag (`feature.flag.LPS-142518`) enabled and disabled, and with cookie management enabled and disabled, check that nothing breaks

### CODE REVIEW

**Comment by tinycarol** [comment]
ci:test:relevant

**Comment by tinycarol** [comment]
ci:test:relevant

**Comment by john-co** [comment]
ci:test:frontend-walkthrough

**Comment by john-co** [comment]
ci:test:frontend-walkthrough

**Comment by john-co** [comment]
ci:test:frontend-walkthrough

**Comment by john-co** [comment]
ci:test:frontend-walkthrough

**Comment by john-co** [comment]
ci:test:frontend-walkthrough

**Comment by john-co** [comment]
Seeing the walkthrough tests pass consistently gives me hope that this will fix some inconsistent test failures we were seeing with the walkthrough tests in past few weeks/months. :pray:

**Review by markocikos — APPROVED** [review]
@tinycarol the changes in PR LGTM!

It's unusual to see an instance of a class being exported, `localStorage`. Typically we only export functions or components. A more common pattern would be something like
```js
import {getLocalStorage} from 'frontend-js-web';

const localStorage = getLocalStorage();
```
Is there any benefit to exporting class instance? :thinking:

**Comment by tinycarol** [comment]
Hi @markocikos, thx for the review! ❤️ 

The main benefit is that the API is basically the same as the native one, the only change is having to pass consent types. It makes it easier to use and migrate for devs that are already used to the storage API.

The reason we're exporting the instance is because of the implementation: since the API for local and session storage is the same, from our side the logic is also the same, only changing which object we interact with. So we abstracted all the common logic into a [`Storage` class](https://github.com/liferay-frontend/liferay-portal/blob/master/modules/apps/frontend-js/frontend-js-web/src/main/resources/META-INF/resources/liferay/util/storage.js#L17) and pass the storage object as a parameter in the constructor.

With that in mind, wrapping that instantiation in a getter would just add an extra step wherever devs want to use the API, which shouldn't be necessary.

**Comment by tinycarol** [comment]
ci:forward

**Comment by bryceosterhaus** [comment]
Sorry, I just saw this mention now, GH noifications are messed up for me for some reason...


> It's the import that's holding a value that feels weird to me

I tend to agree with this and we could actually potentially run into issues with this depending on the build/bundle process. If we have two modules that both use webpack and import `some-library`, its possible that they would have different runtime values because you get two singletons. Now, I'm not sure we actually would run into this issue because with npm-scripts we try to individually bundle each dependency and so it should hopefully use the same instance. However, it is sort of a smell to me that we are import/export a non-constant.

**Pull request closed without merging**
