### PR TITLE
LPS-167618 Modify macro to adapt new behavior

### PR DESCRIPTION
**Pull request by ealonso**
Motivation
====
Fix accessibility issues in old liferay-ui:icon-options

Proposed Solution
====
In order to fix the accessibility issues, we created a new taglib in liferay-frontend called icon-options. Since this taglib is not in kernel, like liferay-ui:icon-options, we can use clay:dropdown-menu.

To allow us use clay:dropdown-menu, we need to refactor PortletConfigurationIcon to convert it from icon to dropdown item. It is not a trivial task and we created a new global js variable to put some functions on it, since the icons are executing onClick method and dropdown item doesn't allow it.

Things to take into account
----
Since we are in a rush and it contains a lot of code, we send some code to master directly, sorry about that. The related LPS are:

[LPS-166701](https://issues.liferay.com/browse/LPS-166701) -> Refactor for PortletConfigurationIcon 
[LPS-166972](https://issues.liferay.com/browse/LPS-166972) -> Creation of new taglib
[LPS-166547](https://issues.liferay.com/browse/LPS-166547) -> Some fixes. Since I made a mistake and I used a wrong LPS 😞, the commits are 7cd70f1c3eef192b354e837d479e0975f03cc9af, 2d7941b4d5a0bee15c619d98b4abf752cbc0b81c, cfea593cac83b582a49fe41f3c7319f297233fd7, 29ce4c9c2f261b8a2816726bc72e73c0e14ed5aa, 081724dfad738f60e9a58a97ff1992446663bd78

Link to the [issue](https://issues.liferay.com/browse/LPS-165627)

Please let me know what do you think.

### CODE REVIEW

**Comment by ealonso** [comment]
ci:test:sf

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Hey @dsanz and @markocikos,

It also fixing another accessibility issues since we are replacing it in all portal, 💃🏾, for example: https://issues.liferay.com/browse/LPS-167331, that it's mark for phase 2.

Also, all test are in green in the first try, 😱 

Regards,
Eudaldo.

**Review by markocikos — COMMENTED** [review]
@ealonso please see comment inline.

I addition, I tested this, on `ant all`d branch, and found two small bugs. They are unrelated to this PR, but to code already merged. 

1. The ellipsis icon is invisible until hover, caused by `text-white` [CSS class](https://github.com/liferay/liferay-portal/blob/master/modules/apps/frontend-taglib/frontend-taglib/src/main/resources/META-INF/resources/icon_options/page.jsp#L25).
2. Click anywhere throws JS error in console. [This event setting](https://github.com/liferay/liferay-portal/blob/master/modules/apps/frontend-taglib/frontend-taglib/src/main/resources/META-INF/resources/icon_options/js/PortletOptionsDropdownPropsTransformer.js#L47-L57) is not correct.


screenshot

**Comment by ealonso** [comment]
Hey @victorg1991,

Could you please take a look to the @markocikos feedback? For 1 and 2?

@markocikos, since the pr is in green and it should be merge on master as soon as possible (The due date for this one was November 1st), What do you think about sending this one and then work in the bugs/improvements?  We can send another one later today or tomorrow morning.

Regards,
Eudaldo

cc: @dsanz

**Comment by markocikos** [comment]
We could merge without the utility improvement, but would it be ok to merge with bugs? Especially the one that makes configuration button invisible, I'd classify that as a blocking bug.

**Comment by ealonso** [comment]
ci:test:sf

**Comment by ealonso** [comment]
Hey @markocikos,

Last two commits fix the bugs that you found. [20558ca](https://github.com/liferay-frontend/liferay-portal/pull/2837/commits/20558ca9d875ac6bb3beaba525eea8bf8fce8902) and [daba089](https://github.com/liferay-frontend/liferay-portal/pull/2837/commits/daba089bb20ba153668a8cbc44d4e8484186ef2c)

**Review by markocikos — APPROVED** [review]
Bug fixes LGTM! Since there is a need for urgency, we can push PR as it, leaving improvements from https://github.com/liferay-frontend/liferay-portal/pull/2837#discussion_r1015523483 for a followup task /cc @dsanz

**Comment by ealonso** [comment]
Manual forward: https://github.com/brianchandotcom/liferay-portal/pull/125911

**Pull request closed without merging**
