### PR TITLE
LPS-152409 Simplify PQL

### PR DESCRIPTION
**Pull request by susanchen3**
**Background**
Requested here: https://github.com/liferay-frontend/liferay-portal/pull/2151#discussion_r858081516

**JIRA Ticket:**
https://issues.liferay.com/browse/LPS-152409

### CODE REVIEW

**Comment by susanchen3** [comment]
ci:test:frontend:nocompile

**Comment by susanchen3** [comment]
Looks like it works according to the [Job Summary](https://testray.liferay.com/reports/production/logs/2022-04/test-1-29/test-portal-acceptance-pullrequest(master)/2699/job-summary/index.html.gz?authuser=0)
image

**Comment by john-co** [comment]
Just started reviewing :)

**Comment by john-co** [comment]
Looks good to me! :sunglasses:

**Comment by john-co** [comment]
ci:forward

**Pull request closed without merging**
