### PR TITLE
LPS-165925 Migrate frontend-js-metal-web to ESM build

### PR DESCRIPTION
**Pull request by izaera**
We have detected that frontend-taglib-clay is bundling metal inside each legacy clay package, which makes them be 600K in size and take a long time to build (74 seconds for a production build).

This would be fixed if they could share metal, as we did in the AMD model.

### CODE REVIEW

**Comment by izaera** [comment]
I'll wait for the tests to end before pushing the SF fixes I have in local.

**Comment by izaera** [comment]
Apparently there's [a check in metal-dom](https://github.com/metal/metal.js/blob/master/packages/metal-dom/src/events.js#L54) that makes it behave differently when it is in browser than when it is in the server. I will try to find a way to make it think it's in the browser to make it export the correct objects.

**Comment by izaera** [comment]
Seeing the [server check code](https://github.com/metal/metal.js/blob/6002ec63153bca307859a5dfdfda0affb0274d49/packages/metal/src/coreNamed.js#L294-L310) it seems to me that the most civilized way to make this work is to set some environment variable when `npm-scripts` requires a package inside the build. Any other solution I can think of seems a hack.

What we'll do is adding a way to define env vars to npmscripts.config.js for scenarios where `symbols: 'auto'` is used with one package like this one.

**Comment by izaera** [comment]
So, the solution I explained above is very good but it will lead to a failure of the build because precisely, what we want is `metal-dom` to think it is being required from a browser and that is what makes the build fail.

So we need:

1. The env vars in `npmscripts.config.js` to fool `metal-dom` in any type of build and make it think it's in the browser.
2. Either:
    a. Changes in metal to prevent it from failing if `document` does not exist
    b. Changes in npm-scripts to polyfill the browser

:thinking:

**Comment by izaera** [comment]
ci:test:relevant

**Comment by izaera** [comment]
ci:test:relevant

**Comment by izaera** [comment]
ci:test:relevant

**Comment by mateusralv** [comment]
I'm taking a look 🔬

**Comment by mateusralv** [comment]
I took a look at [comparison](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1666784974053&testrayRunIdA=2015133857&testrayRunIdB=2015960512) with the failures in the master and realized that there is only one failure in your PR. 

🟢 Unique flaky failure:
com.liferay.portal.workflow.kaleo.internal.runtime.integration.test.WorkflowInstanceManagerImplTest

To be sure I [compared the last 2 results of ci:test:relevan](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=2&testrayRunIdB=2015452228&testrayRunIdA=2015960512&statusB=3)t and this test is not present.

---

🟢 Failures not unique:
com.liferay.oauth2.provider.token.endpoint.test.RefreshTokenAuthorizationGrantTest
com.liferay.oauth2.provider.client.test.AnnotationsAndHttpApplicationClientTest

### So, the failures are not related to your PR, safe to forward 🎉 🚀

**Comment by izaera** [comment]
Sent manually as https://github.com/brianchandotcom/liferay-portal/pull/125273

**Pull request closed without merging**
