### PR TITLE
LPS-129626 overriding dialog onShow event handler to make sure the dialog is centered when it is shown

### PR DESCRIPTION
**Pull request by marcosapmf**
Hi @liferay-frontend,

This pull intends to fix the issue that keeps the CKEditor plugin dialogs decentralized.

Basically, I needed to override the `onShow` function from the dialog definition, then I used `CKEDITOR.tools.override` so 
I can call the previous `onShow` implementation, which has different logic for each plugin, and add the code related to centralizing the dialog.

Please let me know if you have any points about this

Thanks in advance 😃

Related issue: https://issues.liferay.com/browse/LPS-129626

### CODE REVIEW

**Comment by julien** [comment]
Code change LGTM, I'm just going to fetch this for a test drive :+1:

**Comment by julien** [comment]
Just to confirm: it works too

**Before** 


**After**


Thanks @marcosapmf.

Additionally, from the [issue](https://issues.liferay.com/browse/LPS-129626), it  looks like the "content" editor (the one where the content is typed) is using `ClassicEditor.js` (ckeditor_classic) and the one in the sidebar is using (good ol') `ckeditor.jsp`: if you look at the attached video, you'll notice the dialogs are centered for the editor in the sidebar and aren't for dialogs opened from the "content" editor. 

At one point we might consider using the same editor  because now this code to "center" dialogs" is going to be duplicated (here and one [there](https://github.com/liferay/liferay-portal/blob/20206ada64511caf36d53e6bf5781dfe948f2f30/modules/apps/frontend-editor/frontend-editor-ckeditor-web/src/main/resources/META-INF/resources/_diffs/extension/dialog_definition.js), and I also spotted [this](https://github.com/liferay/liferay-portal/blob/20206ada64511caf36d53e6bf5781dfe948f2f30/modules/apps/frontend-editor/frontend-editor-ckeditor-web/src/main/resources/META-INF/resources/_diffs/extension/creole_dialog_definition.js)) - That doesn't mean we shouldn't merge these changes but I think we should keep this on our "radar" for the future.

**Review by julien — APPROVED** [review]

**Review by jbalsas — COMMENTED** [review]
Hey @marcosapmf, @julien, why not load [`dialog_definition.js`](https://github.com/liferay/liferay-portal/blob/master/modules/apps/frontend-editor/frontend-editor-ckeditor-web/src/main/resources/META-INF/resources/_diffs/extension/dialog_definition.js) the same way we already do in [CKEditorOnEditorCreateDynamicInclude](https://github.com/liferay/liferay-portal/blob/master/modules/apps/frontend-editor/frontend-editor-ckeditor-web/src/main/java/com/liferay/frontend/editor/ckeditor/web/internal/servlet/taglib/CKEditorOnEditorCreateDynamicInclude.java)??

Just add the extension point (which is missing in `ckeditor_classic.jsp` and either use the same class registering an additional extension point or create one of its own.

One thing is that this code is not exactly the same as the one we already have, so this is also likely going to result in additional discrepancies between the two

**Comment by julien** [comment]
@jbalsas that sounds like a good idea which I hadn't even thought about.

The only thing I'm not sure about right now is that dialog_definition.js uses a [global ckEditor variable](https://github.com/liferay/liferay-portal/blob/20206ada64511caf36d53e6bf5781dfe948f2f30/modules/apps/frontend-editor/frontend-editor-ckeditor-web/src/main/resources/META-INF/resources/_diffs/extension/dialog_definition.js#L16), but I'm sure we can figure out how that can be done with ckeditor_classic or better, avoid that global variable in that script.

**Comment by marcosapmf** [comment]
Hi @julien, @jbalsas 

thanks for reviewing this pull :) 

Putting a breakpoint in `CKEditorOnEditorCreateDynamicInclude`, I see it is called by `ckeditor.jsp` and there, we pass the `editorName` through the `dynamicInclude` tag. 

I don't know if I understood well, so please, correct me if I am wrong, but it seems like the dynamic include will add that behaviour just for the editor called `editorName`. 
Additionally, since we are in the React context, we will need to add this extension point for each module that uses `ClassicEditor` component, won't we? I mean, we'll need to add a DynamicInclude class for Journal, Forms, etc.

Is there any other way to add this behaviour within the ClassicEditor?

Thanks a lot for your help

**Comment by julien** [comment]
@marcosapmf we use [`ckeditor_classic.jsp`](https://github.com/liferay/liferay-portal/blob/02c62c690a8056ad107ac4f79b69cadca07d027c/modules/apps) for [`ClassicEditor`](https://github.com/liferay/liferay-portal/blob/02c62c690a8056ad107ac4f79b69cadca07d027c/modules/apps/frontend-editor/frontend-editor-ckeditor-web/src/main/resources/META-INF/resources/editor/ClassicEditor.js), so let me see if we can do something similar. 

My guess is that if it's possible to do it there the same way as in `ckeditor.jsp` we can probably use the same script for both.

**Comment by julien** [comment]
@marcosapmf after a second look into this and unless I'm wrong, I think we could simplify this

When you look at the event listener for the `CKEDITOR.on('dialogDefinition` event, you'll see that it's [checking if the `editor` we get by the event is `ckEditor`](https://github.com/liferay/liferay-portal/blob/8a38ac87b2db388c85c4e7330c9440be5faafcf1/modules/apps/frontend-editor/frontend-editor-ckeditor-web/src/main/resources/META-INF/resources/_diffs/extension/dialog_definition.js#L16); and I don't think that's necessary: because we want "any" editor's dialogs to be centered, so by simply removing that check, we get all dialogs centered for "free" ... I just need to check what happens with the dialogs in "Blogs" where we aren't using ckeditor (yet).

I don't have much knowledge about how the page is structured in Web Content (I'm going to have a look at that now to get an idea of how it's done), but it seems that `ClassicEditor` is rendered directly by a React component (what I mean is that it's not using [`ckeditor_classic.jsp`](https://github.com/liferay/liferay-portal/blob/8a38ac87b2db388c85c4e7330c9440be5faafcf1/modules/apps/frontend-editor/frontend-editor-ckeditor-web/src/main/resources/META-INF/resources/ckeditor_classic.jsp) in this case)

If this seems like a good solution, one other thing I was thinking is that we could remove the [AUI "dependency" from that script](https://github.com/liferay/liferay-portal/blob/8a38ac87b2db388c85c4e7330c9440be5faafcf1/modules/apps/frontend-editor/frontend-editor-ckeditor-web/src/main/resources/META-INF/resources/_diffs/extension/dialog_definition.js#L42-L49)

**Comment by julien** [comment]
>  I just need to check what happens with the dialogs in "Blogs" where we aren't using ckeditor (yet).

Sorry; I wrote that before actually thinking carefully about it ... in Blogs, since [AlloyEditor](https://github.com/liferay/liferay-portal/blob/8a38ac87b2db388c85c4e7330c9440be5faafcf1/modules/apps/frontend-editor/frontend-editor-alloyeditor-web/src/main/resources/META-INF/resources/alloyeditor.jsp) is going to be used, that should be a problem

**Comment by julien** [comment]
@marcosapmf I've sent a draft PR [here](https://github.com/liferay-frontend/liferay-portal/pull/941), 
tell me what you think when you get a chance.

**Comment by jbalsas** [comment]
Closing this one in favour of https://github.com/liferay-frontend/liferay-portal/pull/941 where @julien worked and @marcosapmf gave approval

**Pull request closed without merging**
