### PR TITLE
LPS-132741 Isolate Portlet Topper in all ootb themes

### PR DESCRIPTION
**Pull request by pat270**
https://issues.liferay.com/browse/LPS-132741

This PR isolates portlet toppers and their dropdown menus. This is potentially a breaking change. I know liferay.com modified their edit controls. This would conflict with their custom styles.

The CSS I'm using to test:

```html
<style>
html {
  font-size: 20px;
}

#senna_surface1 h1,
#senna_surface1 h2,
#senna_surface1 h3,
#senna_surface1 h4,
#senna_surface1 h5,
#senna_surface1 h6 {
  background-color: #282828;
  border: 4px solid #00ff66;
  color: #00ff66;
  font-family: Georgia;
  font-size: 50px;
  font-style: italic;
  font-variant: small-caps
  font-weight: bold;
  line-height: 100px;
  letter-spacing: 2px;
  margin: 10px 0;
  padding: 10px;
  text-align: center;
  text-shadow: 1px 1px 0 #fff;
  text-transform: uppercase;
  white-space: nowrap;
}

#senna_surface1 .btn {
  background-color: #282828;
  border: 4px solid #00ff66;
  color: #00ff66;
  font-family: Georgia;
  font-size: 50px;
  font-style: italic;
  font-variant: small-caps
  font-weight: bold;
  line-height: 100px;
  letter-spacing: 2px;
  margin: 10px 0;
  padding: 10px;
  text-align: center;
  text-shadow: 1px 1px 0 #fff;
  text-transform: uppercase;
  white-space: nowrap;
}

#senna_surface1 .btn:hover {
  background-color: #000;
  color: #ffcc00;
  letter-spacing: 4px;
  font-size: 40px;
}

#senna_surface1 a {
  background-color: #282828;
  border: 4px solid #00ff66;
  color: #00ff66;
  font-family: Georgia;
  font-size: 50px;
  font-style: italic;
  font-variant: small-caps
  font-weight: bold;
  line-height: 100px;
  letter-spacing: 2px;
  margin: 10px 0;
  padding: 10px;
  text-align: center;
  text-shadow: 1px 1px 0 #fff;
  text-transform: uppercase;
  white-space: nowrap;
}

#senna_surface1 a:hover {
  background-color: #000;
  color: #ffcc00;
  letter-spacing: 4px;
  font-size: 40px;
}
</style>
```

Screenshot:
portlet-topper1

### CODE REVIEW

**Comment by pat270** [comment]
ci:test:sf

**Comment by pat270** [comment]
ci:test:sf

**Comment by pat270** [comment]
@nkkwon I looked over the failures and it seems to be working unless I reproduced the test cases incorrectly.

topper-failure

I added a class to portlet-topper in https://github.com/liferay-frontend/liferay-portal/blob/945d80db4339eae084f425bc6924c21c6c471b8f/modules/apps/frontend-theme/frontend-theme-unstyled/src/main/resources/META-INF/resources/_unstyled/templates/portlet.ftl#L23. Would it mess up the locator `//header[@class='portlet-topper' and contains(.,'IFrame')]//div[contains(@class,'portlet-options')]/a` ?

**Comment by nkkwon** [comment]
Taking a look right now!

**Comment by nkkwon** [comment]
It just needs a test fix to change some of the paths. Can you add me as a collaborator to the repo?

**Comment by pat270** [comment]
@nkkwon Just added you, thanks!

**Comment by nkkwon** [comment]
@pat270 I pushed up the test fix, I will retrigger ci:test:relevant

**Comment by nkkwon** [comment]
ci:test:relevant

**Comment by edalgrin** [comment]
This PR will probably be in conflict with the [frontend-css-web removal one](https://github.com/liferay-frontend/liferay-portal/pull/1186) because it touch /styled/ files – can we wait to merge it?

**Comment by marcoscv-work** [comment]
We should keep the compatibility with classic custom properties:

https://github.com/liferay/liferay-portal/blob/master/modules/apps/frontend-theme/frontend-theme-classic/src/css/custom_properties/_custom_properties_set.scss#L183-L188

https://github.com/liferay/liferay-portal/blob/master/modules/apps/frontend-theme/frontend-theme-classic/src/css/custom_properties/_custom_properties_variables.scss#L242-L248

And be careful if we decided to deprecate SASS variables:
https://github.com/liferay/liferay-portal/blob/master/modules/apps/frontend-theme/frontend-theme-styled/src/main/resources/META-INF/resources/_styled/css/portlet/_variables.scss#L3-L15

On the other hand, it looks great and fixes the issue :-D

**Review by marcoscv-work — APPROVED** [review]

**Comment by markocikos** [comment]
@marcoscv-work @edalgrin How risky is this PR? Should be put it on hold until GA3? If it's safe, feel free to forward.

**Review by edalgrin — APPROVED** [review]
Since the other PR is on hold, we can submit this first!

**Comment by edalgrin** [comment]
> @marcoscv-work @edalgrin How risky is this PR? Should be put it on hold until GA3? If it's safe, feel free to forward.

I think is a pretty safe change if we block this we should block all the similar PRs, _if necessary_ I'm going to double check the change before forward it

**Comment by nhpatt** [comment]
ci:forward

**Comment by nhpatt** [comment]
Can ci:forward the full repository?

**Comment by pat270** [comment]
ci:forward

**Comment by pat270** [comment]
ci:forward

**Comment by pat270** [comment]
ci:test:relevant

**Comment by pat270** [comment]
@nkkwon @zhangyan0701 I need some help with the tests. I have no idea what it's saying.

**Comment by nkkwon** [comment]
@pat270 Looks like it's a CI issue that is causing these failures. It doesn't look like any of the failures here are related to the commits in this PR. Looks good to manually forward!

**Comment by pat270** [comment]
@nkkwon this is a dumb question, but do we have a ci command to manually forward or do I directly send it to bchan?

**Comment by nkkwon** [comment]
You just send it directly to bchan!

**Comment by pat270** [comment]
Thanks @nkkwon !

**Comment by nhpatt** [comment]
-- Sent directly here: https://github.com/brianchandotcom/liferay-portal/pull/105221

**Comment by bryceosterhaus** [comment]
> ci command to manually forward

This would be nice

**Pull request closed without merging**
