### PR TITLE
LPS-177720 HR_70 (scenario 2) Disabled checkbox should not be readable

### PR DESCRIPTION
**Pull request by dsanz**
In this PR we're hiding the internal checkbox to the eyes of the screen reader and the tab indexes by adding it `display:none` in the <liferay-ui:input-permissions> tag. This internal ckeckbox is added to the `VIEW` action _behind_ a disabled checkbox to prevent modifications of `VIEW` permissions, but it was still being seen by assistive technologies.

@marcoscv-work would you mind to test this using JAWS and let me know if it solves the issue? Thanks a lot

cc/ @edalgrin @kresimir-coko

### CODE REVIEW

**Comment by dsanz** [comment]
@mateusralv it looks like the failing tests are not related, are they? Thanks a lot!

**Review by kresimir-coko — APPROVED** [review]

**Comment by kresimir-coko** [comment]
ci:test:relevant

**Comment by kresimir-coko** [comment]
ci:test:relevant

**Comment by kresimir-coko** [comment]
ci:reevaluate:1407401_1928

**Comment by mateusralv** [comment]
Hi @dsanz I took a look and the failures are not related 🎉 

[Testray Comparison](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1682703231866&testrayRunIdA=2282859116&testrayRunIdB=2283433255)

**Comment by dsanz** [comment]
ci:forward:force

**Comment by kresimir-coko** [comment]
ci:forward

**Comment by kresimir-coko** [comment]
ci:forward

**Comment by kresimir-coko** [comment]
ci:forward

**Comment by kresimir-coko** [comment]
ci:forward

**Comment by kresimir-coko** [comment]
@dsanz can you manually forward this since you have the code on your branch?

**Pull request closed without merging**
