### PR TITLE
LPS-165319 Use setData instead of setHTML to avoid CKEditor content duplications during resizing

### PR DESCRIPTION
**Pull request by orsolyaDekany**
Hello,

**Reproductions steps and discussion:**
https://issues.liferay.com/browse/LPS-165319
https://issues.liferay.com/browse/PTR-3373

**Issue**
Drag to move handler multiplies in CKEditor, when an image is added to the editor body and we toggle between mobile and desktop view. The editor is recreated during resizing and the ckEditorContent is wrongly set.
The issue can be reproduced in Chrome, but not in Firefox.

**Solution**
Replacing _setHTML_ to _setData_ CKEditor method.

Please review it. 
Thank you.

cc. @georgel-pop-lr

### CODE REVIEW

**Review by markocikos — COMMENTED** [review]
@orsolyaDekany  A cautious LGTM! Cautious, because there is a long history of regression whenever we touch anything related to data setting in CKEditor :sweat_smile:  

With the change in PR, it looks like we are losing a bit of performance, in a fringe case where CKEditor re-initialization takes longer then two debounced events (250ms). That seems to be the point of `setHTML`. But, something in these partial initializations is going wrong, so overall I think it's fine we remove it. This might have been far more critical in times of ancient browsers.

Speaking of removing, I believe we can remove the whole [setHTML](https://github.com/liferay/liferay-portal/blob/master/modules/apps/frontend-editor/frontend-editor-ckeditor-web/src/main/resources/META-INF/resources/ckeditor.jsp#L291-L313), as it is unused after the change in this PR.

If we wanted to truly improve performance, we should analyze alternative methods to [completely destroy and recreate editor on resize](https://github.com/liferay/liferay-portal/blob/master/modules/apps/frontend-editor/frontend-editor-ckeditor-web/src/main/resources/META-INF/resources/ckeditor.jsp#L580-L582). It's hard for me to believe there is no API for resizing in base CKEditor.  /cc @dsanz 

One minor note - the JIRA ticket states to set `...blogs.edit_entry.jsp=alloyeditor`. I believe this should be `ckeditor`. I was able to replicate the issue only with `ckeditor`.

**Review by markocikos — APPROVED** [review]
LGTM!

**Comment by markocikos** [comment]
ci:forward

**Comment by georgel-pop-lr** [comment]
> @orsolyaDekany A cautious LGTM! Cautious, because there is a long history of regression whenever we touch anything related to data setting in CKEditor sweat_smile
> 
> With the change in PR, it looks like we are losing a bit of performance, in a fringe case where CKEditor re-initialization takes longer then two debounced events (250ms). That seems to be the point of `setHTML`. But, something in these partial initializations is going wrong, so overall I think it's fine we remove it. This might have been far more critical in times of ancient browsers.
> 
> Speaking of removing, I believe we can remove the whole [setHTML](https://github.com/liferay/liferay-portal/blob/master/modules/apps/frontend-editor/frontend-editor-ckeditor-web/src/main/resources/META-INF/resources/ckeditor.jsp#L291-L313), as it is unused after the change in this PR.
> 
> If we wanted to truly improve performance, we should analyze alternative methods to [completely destroy and recreate editor on resize](https://github.com/liferay/liferay-portal/blob/master/modules/apps/frontend-editor/frontend-editor-ckeditor-web/src/main/resources/META-INF/resources/ckeditor.jsp#L580-L582). It's hard for me to believe there is no API for resizing in base CKEditor. /cc @dsanz
> 
> One minor note - the JIRA ticket states to set `...blogs.edit_entry.jsp=alloyeditor`. I believe this should be `ckeditor`. I was able to replicate the issue only with `ckeditor`.

Hi @markocikos,

What do you think of increasing debounced event 250ms to more 1000ms?

Regards.

**Comment by orsolyaDekany** [comment]
Hi @markocikos ,
Just add a comment to your thoughts, as an alternative solution, do you think we could use the `editor.resize` method from CKEditor instead of destroying and recreating the editor on resize?https://ckeditor.com/docs/ckeditor4/latest/features/resize.html#changing-editor-size-on-the-fly

**Comment by markocikos** [comment]
ci:stop

**Review by markocikos — CHANGES_REQUESTED** [review]
See https://github.com/liferay-frontend/liferay-portal/pull/2786#issuecomment-1283843692

**Comment by orsolyaDekany** [comment]
Hi @liferay-frontend Team,
I pushed the modification of the debounced event that increased to 1000ms for better performance. 
Regarding the improvement that @markocikos mentioned, I would set it as a future task. We could create a ticket for that and I would assign that to myself.

Could you please review the updated PR?
Thank you.

cc. @georgel-pop-lr

**Comment by orsolyaDekany** [comment]
ci:test:sf

**Comment by orsolyaDekany** [comment]
ci:test:relevant

**Comment by rolandpakai** [comment]
Hi @georgel-pop-lr

could you please review this PR?

Thanks, Roland

**Comment by john-co** [comment]
Reviewed. Test failures look related. :x: 

- [LocalFile.WYSIWYGUsecase#CanDisplayContentLeftToRight](https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/257493//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_WYSIWYGUsecase_CanDisplayContentLeftToRight_) - [Poshi Report](https://testray.liferay.com/reports/production/logs/2022-10/test-1-26/test-portal-acceptance-pullrequest(master)/5693/functional-tomcat90-mysql57-jdk8/0/2/LocalFile.WYSIWYGUsecase_CanDisplayContentLeftToRight/index.html.gz)
- [LocalFile.WYSIWYGUsecase#CanDisplayContentRightToLeft](https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/81446//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_WYSIWYGUsecase_CanDisplayContentRightToLeft_) - [Poshi Report](https://testray.liferay.com/reports/production/logs/2022-10/test-1-26/test-portal-acceptance-pullrequest(master)/5693/functional-tomcat90-mysql57-jdk8/0/6/LocalFile.WYSIWYGUsecase_CanDisplayContentRightToLeft/index.html.gz)

```
javascript error: _com_liferay_wiki_web_portlet_WikiPortlet_contentEditor.setHTML is not a function
```

Perhaps there's still setHTML usages left in the wiki portlet.

**Comment by markocikos** [comment]
I took a closer look, here are my findings:
1. The whole point of re-initializing editor on resize is to have different toolbars on different sizes (`phone`, `tablet` and `liferay`). It looks like we don't use this feature anywhere in DXP, there is only equivalent implementation in the archived [TinyMCEEditor](https://github.com/liferay/liferay-portal/blob/master/modules/apps/archived/frontend-editor-tinymce-web/src/main/java/com/liferay/frontend/editor/tinymce/web/internal/editor/configuration/TinyMCEEditorConfigContributor.java#L187-L201). We could remove this feature, but it would be a minor risk of breaking change with customers. Honestly, it's not worth the effort. The proper solution, in any case, is to replace `ckeditor` with `ckeditor_classic`, and that implementation does not support toolbar shifting. /cc @dsanz 
2. @john-co I could not reproduce failures in https://github.com/liferay-frontend/liferay-portal/pull/2786#issuecomment-1302497048. Wiki portlet does not invoke `setHTML`. What I suspect is happening is our **tests** are setting content, using `setHTML` as API. Looking at test steps, there is suddenly a check for content value `Wiki Left to Right Content`. I don't think it's worth the effort to update our tests. It's not a big deal if we leave `setHTML` snippet in. There might even be some edge case where CI sets data while editor data is initializing.
3. 1000 ms debouncing results in very jarring UX. After ending resize, you start already to do the next thing when refresh happens. I'd keep it on 250ms. It's not a big risk for performance, as we only re-initialize when changing toolbar size thresholds

@orsolyaDekany To summarize, can you please remove the last two commits, with code cleanup and debouncing change. Let's go forward with PR in it's original form.

**Pull request closed without merging**
