### PR TITLE
LPS-113801 Refreshes `export-import` portlet when selection modal is closed 

### PR DESCRIPTION
**Pull request by diegonvs**
### Test Case

1. Control Panel > Sites > Site Templates
2. Click the ellipsis button on the right upper corner
3. Import the attached lar file(see Jira's link for the attached lar file)
4. Close the Import dialog

You'll notice we aren't able to see the recently imported lar file on the table view. Users needs to refresh the entire page to see the result.

See https://issues.liferay.com/browse/LPS-113801 for attachments/additional details.

### What I did

I noticed We don't have a handling for closing the opened modal on module's call. So, I added a onClose callback on openModal call and called `Liferay.Portlet.refresh` API for prevent reloading the entire page. (thanks to @brunobasto)

### Questions

JFYI, before, when using an AUI component for opening a modal/window, [this event](https://github.com/liferay/liferay-portal/blob/master/modules/apps/frontend-js/frontend-js-web/src/main/resources/META-INF/resources/liferay/events.js#L171) was being triggered causing an update on the page.

Does make sense moving this code from onClose callback to the openModal/Window command or fire the `closeWindow` Liferay's event?

**Update:**

See the following `openWindow` example: https://github.com/liferay/liferay-portal/blob/master/modules/apps/calendar/calendar-web/src/main/resources/META-INF/resources/view_calendar_menus.jspf#L70

```js
refreshWindow: window,
```

Before, We had an attribute called `refreshWindow` that I'm guessing that can be used for it.

Does make sense updating https://github.com/liferay/liferay-portal/blob/master/modules/apps/frontend-js/frontend-js-web/src/main/resources/META-INF/resources/liferay/modal/Modal.js#L95 for using this property?

WDYT folks?

### CODE REVIEW

**Comment by diegonvs** [comment]
ci:test:sf

**Comment by diegonvs** [comment]
ci:test:relevant

**Comment by markocikos** [comment]
ci:test:relevant

**Comment by diegonvs** [comment]
Thanks for pointing up this, @markocikos !

I tested here and worked fine. Updating with your suggestion :)

**Comment by diegonvs** [comment]
ci:test:sf

**Comment by diegonvs** [comment]
ci:test:relevant

**Comment by markocikos** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
2 approvals and a green check...

shipit

**Comment by jbalsas** [comment]
ci:forward

**Pull request closed without merging**
