### PR TITLE
LPS-139275 change test generation to use null instead of random strings in search params

### PR DESCRIPTION
**Pull request by nhpatt**
Change generation of search param to null to avoid false negatives and an issue with the Object APIs.

-- Tests will fail

### CODE REVIEW

**Review by javierdearcos — APPROVED** [review]
Good point.

Make a similar change putting every parameter that was not an entity to null but in this case, it caused problems in some tests.

**Comment by javierdearcos** [comment]
ci:forward

**Comment by john-co** [comment]
Reviewed. Test failures are unrelated. :heavy_check_mark: 

- test is failing in other recent runs: https://testray.liferay.com/home/-/testray/case_results/1561387089/history?tab=result&hideFilterPin=true

**Comment by nhpatt** [comment]
ci:forward

**Comment by javierdearcos** [comment]
ci:reevaluate:1257401_233

**Comment by javierdearcos** [comment]
ci:forward

**Comment by javierdearcos** [comment]
ci:test:relevant

**Comment by javierdearcos** [comment]
ci:stop

**Comment by javierdearcos** [comment]
Brian merged it manually

**Pull request closed without merging**
