### PR TITLE
LPD-35798, LPD-36081, LPD-33708 Noncify usages of <style> and <link>

### PR DESCRIPTION
**Pull request by ling-alan-huang**
(Comes from https://github.com/liferay-frontend/liferay-portal/pull/4432)

@izaera Please check my changes in SF part.
This is the SF result from my local run:
```
     [java] java.lang.Exception: Found 6 formatting issues:
     [java] 1: Missing attribute '${nonceAttribute}' in <style> tag, see LPD-18227: ./modules/apps/commerce/commerce-service/src/main/resources/com/liferay/commerce/internal/notification/term/evaluator/dependencies/commerce_order_order_items.ftl 1 (SourceCheck:CSPComplianceCheck)
     [java] 2: Missing attribute '${nonceAttribute}' in <style> tag, see LPD-18227: ./modules/apps/site-navigation/site-navigation-language-web/src/main/resources/com/liferay/site/navigation/language/web/portlet/display/template/dependencies/portlet_display_template_long_text.ftl 1 (SourceCheck:CSPComplianceCheck)
     [java] 3: Missing attribute '${nonceAttribute}' in <style> tag, see LPD-18227: ./modules/apps/site-navigation/site-navigation-language-web/src/main/resources/com/liferay/site/navigation/language/web/portlet/display/template/dependencies/portlet_display_template_short_text.ftl 1 (SourceCheck:CSPComplianceCheck)
     [java] 4: Missing attribute '${nonceAttribute}' in <style> tag, see LPD-18227: ./modules/dxp/apps/commerce-demo-pack/commerce-theme-minium/commerce-theme-minium-full-site-initializer/src/main/resources/com/liferay/commerce/theme/minium/full/site/initializer/internal/dependencies/display_templates/MINIUM_NEWS.ftl 1 (SourceCheck:CSPComplianceCheck)
     [java] 5: Missing attribute '${nonceAttribute}' in <style> tag, see LPD-18227: ./modules/dxp/apps/commerce-demo-pack/commerce-theme-minium/commerce-theme-minium-full-site-initializer/src/main/resources/com/liferay/commerce/theme/minium/full/site/initializer/internal/dependencies/journal_articles/MINIUM_PROMO.ftl 1 (SourceCheck:CSPComplianceCheck)
     [java] 6: Missing attribute '${nonceAttribute}' in <style> tag, see LPD-18227: ./portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/journal/dependencies/frontpage_3_column_with_images_template.ftl 1 (SourceCheck:CSPComplianceCheck)

```

### CODE REVIEW

**Comment by izaera** [comment]
So, this is better than the original PR but it's creating a new problem :disappointed:  : 

image

That is because this code -> https://github.com/liferay/liferay-portal/blob/a0fc33915d0349603c7d63400d8f16ec6b117a8f/modules/util/source-formatter/src/main/java/com/liferay/source/formatter/check/PropertiesSourceFormatterFileCheck.java#L78 splits the `.properties` file lines,
then uses this method which just looks for `=`  -> https://github.com/liferay/liferay-portal/blob/a0fc33915d0349603c7d63400d8f16ec6b117a8f/modules/util/source-formatter/src/main/java/com/liferay/source/formatter/check/PropertiesSourceFormatterFileCheck.java#L348-L364 , so the check is not really parsing the properties file properly

**Comment by ling-alan-huang** [comment]
Hi @izaera I already sent the fix for that: https://github.com/brianchandotcom/liferay-portal/pull/154427#event-14348903514

**Comment by izaera** [comment]
> Hi @izaera I already sent the fix for that: https://github.com/brianchandotcom/liferay-portal/pull/154427#event-14348903514

I've rebased this PR with Brian's master locally and it works. Thx :-)

**Comment by izaera** [comment]
ci:test:sf

**Comment by izaera** [comment]
Since this was tested before, I'll force-forward it.

**Comment by izaera** [comment]
ci:forward:force

**Comment by izaera** [comment]
Since CI is down I'm forwarding this manually :shrug:

**Comment by izaera** [comment]
Sent as https://github.com/brianchandotcom/liferay-portal/pull/154444

**Pull request closed without merging**
