### PR TITLE
LPS-118563 - Add separator custom properties

### PR DESCRIPTION
**Pull request by marcoscv-work**
This PR adds the following custom properties:

- Aspect ratio
- Transitions
- Displays text styles
- Lead font text styles
- Text-muted styles
- Blockquote styles
- Separator

Providing the possibility to customize them thought custom properties.

--- 

To test this PR you can:

- Open your liferay portal
- Edit the Home page (content page) / Create a new content page
- Add an HTML fragment to the page
- Doble click over the HTML fragment
- Paste this HTML:
```html
<h1 class="my-5">Aspect ratios:</h1>

<div class="row">
    <div class="col-3">
    	<h6>1:1</h6>
    	<div class="aspect-ratio bg-secondary"></div>
    </div>
    <div class="col-3">
    	<h6>16:9</h6>
    	<div class="aspect-ratio aspect-ratio-16-to-9 bg-secondary"></div>
    </div>
    <div class="col-3">
    	<h6>8:3</h6>
    	<div class="aspect-ratio aspect-ratio-8-to-3 bg-secondary"></div>
    </div>
    <div class="col-3">
    	<h6>4:3</h6>
    	<div class="aspect-ratio aspect-ratio-4-to-3 bg-secondary"></div>
    </div>
</div>

<h1 class="my-5">Transitions:</h1>

<h2>.collapsing</h2>
<div class="collapsing">collapsing</div>
<h2>.fade</h2>
<div class="fade">fade</div>

<h1 class="my-5">Display texts:</h1>

<div class="display-1">
    display-1
</div>
<div class="display-2">
    display-2
</div>
<div class="display-3">
    display-3
</div>
<div class="display-4">
    display-4
</div>

<h1 class="my-5">Lead text:</h1>

<div class="lead">
    Lead
</div>
<h1 class="lead">
    Lead in a H1
</h1>

<h1 class="my-5">text-muted:</h1>

<div class="text-muted">Text muted</div>
<h1 class="text-muted">Text muted in as H1</h1>

<h1 class="my-5">Blockquotes:</h1>

<div class="blockquote">blockquote</div>
<div class="blockquote-footer">blockquote-footer</div>

<h1 class="my-5">Separator:</h1>

<hr>
```
- Inspect each component and see custom properties are applied
- Uncheck custom properties styles and check everything works in the same way
image

**Problems we already know:**

- The separator has an issue in Clay about the `border: 0` order

### CODE REVIEW

**Comment by marcoscv-work** [comment]
ci:test:sf

**Comment by marcoscv-work** [comment]
ci:test:relevant

**Comment by marcoscv-work** [comment]
ci:stop

**Comment by marcoscv-work** [comment]
ci:test:sf

**Comment by marcoscv-work** [comment]
ci:test:relevant

**Comment by marcoscv-work** [comment]
ouch !!! it can't be true !!!
I wanted to have this for the release :-(

@john-co can you help us?

**Comment by jbalsas** [comment]
Looks green to me!

**Comment by jbalsas** [comment]
@marcoscv-work, why do you want this in for the release? Without a classic token definition update, these do nothing on their own.

I'd rather keep this for the next release to avoid introducing last minute visual regressions.

Thoughts?

**Comment by marcoscv-work** [comment]
> @marcoscv-work, why do you want this in for the release? Without a classic token definition update, these do nothing on their own.
> 
> I'd rather keep this for the next release to avoid introducing last minute visual regressions.
> 
> Thoughts?

I misunderstood this, I thought we are trying to connect the stylebook and CCPs for this release.
Better for us! more time for testing!!

**Comment by jbalsas** [comment]
> I misunderstood this, I thought we are trying to connect the stylebook and CCPs for this release.

Not sure what you mean by "connect the stylebook and CCPs for this release"... but if it is what I think it is, this PR is missing the connection! That's done through the `token-definition.json` file in the classic theme. Without it, this is not connected nor will show in the Stylebook UI.

**Comment by eduardoallegrini** [comment]
Shall we hold this until the release then? 🤔

**Comment by jbalsas** [comment]
If you send the accompanying changes to `theme-classic` so it generates interface, I'll allow it. 

Just as it is now, with only the variables, this **adds no value at the cost of possible regressions**. The way to change the equation is to make it provide value :)

**Comment by marcoscv-work** [comment]
Evaluating with @eduardoallegrini !

**Comment by marcoscv-work** [comment]
@jbalsas today we will have ready the changes in the `frontend-token-definition.json` in order to send these two PRs together

**Comment by eduardoallegrini** [comment]
I think we can add a commit to this PR

**Comment by jbalsas** [comment]
> [...] to send these two PRs together

# **1 PR**

therecanonlybeone

**Comment by eduardoallegrini** [comment]
Just started reviewing :)

**Comment by eduardoallegrini** [comment]
@marcoscv-work, @jbalsas  I added the changes to the token-definition but I think we are missing the translation of the labels

**Comment by jbalsas** [comment]
There's conflicts, @eduardoallegrini, probably because some translations were received. The best way to deal with this and prevent it from becoming a nightmare is usually to split the label thingy into 2 commits
- Add new language keys (adding only the new keys to the `Language.properties` file)
- Generate language keys (auto-generated)

That way, now you'd only need to drop that last commit and regenerate it with `gradlew buildLang`. I'd suggest you just do that instead of trying to resolve the merge conflict.

**Comment by eduardoallegrini** [comment]
Resend in https://github.com/liferay-frontend/liferay-portal/pull/230

**Pull request closed without merging**
