### PR TITLE
LPS-205373 - Add missing dependency, aui-component.

### PR DESCRIPTION
**Pull request by ethib137**
https://liferay.atlassian.net/browse/LPS-205373

Adds missing dependency in menu.js which causes errors to be thrown when quickly clicking on an instance of liferay-ui:icon-menu. This was discovered while playing around with playwright.

Screenshot 2024-01-09 at 4 12 33 PM

### CODE REVIEW

**Comment by ethib137** [comment]
ci:test:relevant

**Comment by ethib137** [comment]
ci:test:relevant

**Comment by ethib137** [comment]
ci:stop

**Comment by ethib137** [comment]
ci:test:relevant

**Comment by dsanz** [comment]
LGTM ;)

**Comment by ethib137** [comment]
ci:test:relevant

**Comment by ethib137** [comment]
ci:forward:force

**Pull request closed without merging**
