### PR TITLE
LPS-128362 - Enable dartSass build option for themes

### PR DESCRIPTION
**Pull request by bryceosterhaus**
**This is not intended to be merged until @liferay/npm-scripts is merged with a greater version than v37.1.2**

This PR is intended to be used with `liferay-theme-tasksv10.3.0` which is included in the next npm-scripts release.

I am sending this now as a draft now in case I am on leave when npm-scripts is updated. Feel free to test and merge once npm-scripts is updated.

### CODE REVIEW

**Comment by bryceosterhaus** [comment]
ci:stop

**Comment by wincent** [comment]
Changes look good. I added the "on hold" label until the release is out and integrated, at which point we can test.

**Comment by jbalsas** [comment]
Testing this as we speak

**Comment by jbalsas** [comment]
Ok, so this seems to work other than it basically doubles compilation time for themes 🙈 

I think we have no other option since node-sass is dead, but... 🤔 

@wincent, thoughts?

**Comment by wincent** [comment]
> Ok, so this seems to work other than it basically doubles compilation time for themes 🙈
> 
> I think we have no other option since node-sass is dead, but... 🤔
> 
> @wincent, thoughts?

Previously discussed [here](https://github.com/liferay-frontend/liferay-portal/pull/617#issuecomment-751653864). We always knew it was going to be slower, but hopefully not by too much relative to our overall build process, and hopefully not for ever. What were the concrete numbers you saw?

But at the end of the day, our hand is forced here by the fact that node-sass is a dead-end. Look on the bright side: it's a step closer to seeing the end of support requests related to node-sass exploding whenever it sees a different version of Node.

**Comment by jbalsas** [comment]
K, I rebased, fixed SF and force-pushed.

> What were the concrete numbers you saw?

I was seeing below 20s for node-sass and above 30s for dart-sass. Funny part of this is [we're already using `renderSync`](https://github.com/liferay/liferay-frontend-projects/blob/master/projects/js-themes-toolkit/packages/liferay-theme-tasks/theme/tasks/build/sass.js#L48) which as per [Sass propaganda](https://github.com/sass/dart-sass#javascript-api) is twice as fast as the other option.

> Note however that by default, renderSync() is more than twice as fast as render() due to the overhead of asynchronous callbacks. To avoid this performance hit, render() can use the fibers package to call asynchronous importers from the synchronous code path. To enable this, pass the Fiber class to the fiber option

I don't want to even try and see how slow this gets with `renderSync`... 🙈 

Seeing as this is what it is, going to take it out of draft and give forward a try 🤞

**Comment by jbalsas** [comment]
ci:forward

**Comment by jbalsas** [comment]
> I don't want to even try and see how slow this gets with renderSync... 🙈

Alas, I tried and it's as bad as I expected 😂

**Comment by jbalsas** [comment]
Let's try this one more time...

**Comment by jbalsas** [comment]
ci:forward

**Comment by pat270** [comment]
@jbalsas @wincent @bryceosterhaus Maybe `node-sass` isn't down for the count, there is active development in `libSass`. See https://github.com/sass/libsass/pull/3135.

**Comment by jbalsas** [comment]
> @jbalsas @wincent @bryceosterhaus Maybe node-sass isn't down for the count, there is active development in libSass. See sass/libsass#3135.

wat

**Comment by wincent** [comment]
Although they still have the huge deprecation notice on the readme:

> **Warning:** [LibSass is deprecated](https://sass-lang.com/blog/libsass-is-deprecated). While it will continue to receive maintenance releases indefinitely, there are no plans to add additional features or compatibility with any new CSS or Sass features. Projects that still use it should move onto [Dart Sass](https://sass-lang.com/dart-sass).

which they added as part of the pretty decisive-sounding [PR #3133](https://github.com/sass/libsass/pull/3133) (related issue: [#3123](https://github.com/sass/libsass/issues/3123)).

One of the maintainers may have had a change of heart, but I am still inclined to think [fool me once, shame on... shame on you... but fool me you can't get fooled again](https://youtu.be/eKgPY1adc0A).

**Comment by pat270** [comment]
Haha 👍 @wincent

**Pull request closed without merging**
