### PR TITLE
LPS-121217 Add remote app `navigate()` API

### PR DESCRIPTION
**Pull request by wincent**
This allows the application in the iframe to trigger a navigation in an SPA-aware manner.

As an enxample of a using this functionality in a remote app, [this commit adds a "Sign out" button to a remote app](https://github.com/wincent/remote-app-test/commit/553041f62de0f11f48088be85518c8ed905e3f5f).

### CODE REVIEW

**Comment by wincent** [comment]
ci:test:sf

**Comment by wincent** [comment]
ci:test:relevant

**Comment by wincent** [comment]
This one is a bit RFC-ish; it's the crudest and most minimal implementation possible doing nothing more than forward the client call to `Liferay.Util.navigate()` (ie. it doesn't try to implement the second, optional `listeners` parameter to that API, mostly because proxying callbacks across the iframe boundary is a bit fiddly). Is this useful? I don't even know what the lifecycle callbacks that might be interesting are.

**Comment by bryceosterhaus** [comment]
I was actually just looking for this sort of API last week, I think it'd be pretty helpful and open up possibilities for remote apps.

**Comment by wincent** [comment]
That test failure sure looks unrelated.

**Comment by wincent** [comment]
cc @john-co @PablitoBonito about suspected test flakiness — I'm going to rebase and rerun anyway.

**Comment by wincent** [comment]
ci:test:sf

**Comment by wincent** [comment]
ci:test:relevant

**Review by jbalsas — APPROVED** [review]
LGTM!

**Comment by jbalsas** [comment]
> I was actually just looking for this sort of API last week, I think it'd be pretty helpful and open up possibilities for remote apps.

@bryceosterhaus, do you have any additional requests? 😉

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by wincent** [comment]
> ### ❌ ci:test:stable - 11 out of 21 jobs passed
> ### ❌ ci:test:relevant - 23 out of 44 jobs passed in 4 hours 11 minutes

Without getting too deep into the analysis, something seems afoul and obviously unrelated [there](https://github.com/liferay-frontend/liferay-portal/pull/397#issuecomment-696653644) ([reported in **`#ci`** channel in Slack here](https://liferay.slack.com/archives/C19PWQ74J/p1600777257021200)).

**Comment by jbalsas** [comment]
> Without getting too deep into the analysis, something seems afoul and obviously unrelated there (reported in #ci channel in Slack here).

Yeah, I just figured we could give it another try just in case, but I'd just manually forward this as is 👍

**Comment by wincent** [comment]
> Yeah, I just figured we could give it another try just in case, but I'd just manually forward this as is 👍

Sure thing.

[Upstream confirmation that everything is on fire](https://liferay.slack.com/archives/C19PWQ74J/p1600777257021200).

**Comment by wincent** [comment]
Manual forward: https://github.com/brianchandotcom/liferay-portal/pull/94465

**Comment by bryceosterhaus** [comment]
@wincent @jbalsas would it be overkill to allow access to the entire `Liferay` js object in the remote app?

**Comment by wincent** [comment]
Totally overkill.

- For one thing, a lot of stuff wouldn't serialize well over the iframe boundary (callbacks, for example), which means we'd have to do a lot of fiddly proxying (and possibly in some cases it wouldn't work the same or at all; it would be bad if we had an API in the SDK that was _like_ the one in DXP, with the same name, but subtly different). Another obvious gotcha is that cross-iframe transport is always async, but lots of APIs under `Liferay` are sync, so that's exactly the kind of impedance mismatch I'm talking about (where you have something with the same name but it's async instead of sync, which sucks, so you come up with a different name to distinguish it, but that sucks too because you wind up with a bunch of variant methods when you only wanted one of each).
- The other thing is that access to the `Liferay` global in the first place is an antipattern that we'd like to gradually move away from (in favor of explicit `import`); by exposing `Liferay` to remote apps running in iframes, we increase our exposure of the API we're trying to distance ourself from, and in a context where we can pretty much _never_ make any breaking changes (because the SDK is going to be served over CDN and will always be "live", we basically have to be fanatically committed to forward and backward compatibility). So even, if we got rid of all `Liferay` global access in liferay-portal one day (I know, not happening any time soon), we'd be stuck with this ghost of it in the remote apps SDK.
- Finally, even if we could expose the entire API without the smell of mirroring a global, we want to start with a small restrictive API and slowly expand it from there: you can't put the genie back in the bottle, so we want to only put stuff in there that we're happy to support... _forever_...

**Comment by bryceosterhaus** [comment]
makes sense!

**Pull request closed without merging**
