### PR TITLE
LPS-122157 Migrate v3 js-toolkit packages to named scope versions

### PR DESCRIPTION
**Pull request by wincent**
The contents of the packages should be basically identical (other than the names), with a few small fixes applied on top to facilitate integration into DXP as described in [the release notes](https://github.com/liferay/liferay-frontend-projects/releases/tag/npm-bundler%2Fv3.0.1-pre.0).

Tested this out by deploying the "frontend-js-recharts" module, which is the only one in DXP currently using v3 of the toolkit.

### CODE REVIEW

**Comment by wincent** [comment]
This one is a draft right now because it doesn't work...

Here's what I know so far:

On master `build` of `frontend-js-recharts` looks like this:

```
build
├── node
│   └── packageRunBuild
│       └── resources
│           ├── manifest.json
│           ├── node_modules
│           │   └── frontend-js-recharts$recharts@1.8.5
│           │       ├── index.js
│           │       ├── lib
│           │       │   └── index.js
│           │       └── package.json
│           ├── package.json
│           ├── recharts.bundle.js
│           ├── recharts_lib_index.bundle.js
│           ├── runtime.bundle.js
│           ├── vendor.bundle.js
│           └── webpack.manifest.js
└── tmp
    ├── autoUpdateXml
    ├── compileJSP
    ├── copyCSS
    └── jar
        ├── MANIFEST.MF
        ├── bnd6623008590216948136.bnd
        └── com.liferay.frontend.js.recharts-2.0.0.jar

11 directories, 13 files
```

The new build from this PR is very different (and incomplete because it blows up along the way):

```
build
├── node
│   ├── bundler
│   │   └── bundler
│   │       ├── generated
│   │       │   ├── recharts.js
│   │       │   ├── recharts_lib_index.js
│   │       │   └── webpack.config.json
│   │       └── webpack
│   └── packageRunBuild
│       └── resources
│           └── package.json
└── tmp
    ├── autoUpdateXml
    ├── compileJSP
    └── copyCSS
```

Here is the error output:

```
$ liferay-npm-bundler
❌ EntryModuleNotFoundError: Entry module not found: Error: Can't resolve './/Users/greghurrell/code/portal/liferay-portal/modules/apps/frontend-js/frontend-js-recharts/build/node/bundler/bundler/generated/recharts.js' in '/Users/greghurrell/code/portal/liferay-portal/modules/apps/frontend-js/frontend-js-recharts'
...at <unknown file>

❌ EntryModuleNotFoundError: Entry module not found: Error: Can't resolve './/Users/greghurrell/code/portal/liferay-portal/modules/apps/frontend-js/frontend-js-recharts/build/node/bundler/bundler/generated/recharts_lib_index.js' in '/Users/greghurrell/code/portal/liferay-portal/modules/apps/frontend-js/frontend-js-recharts'
...at <unknown file>

❌ Build failed: webpack build finished with errors
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':apps:frontend-js:frontend-js-recharts:packageRunBuild'.
> Process 'command '/Users/greghurrell/code/portal/liferay-portal/build/node/bin/node'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 12s
2 actionable tasks: 2 executed
```

Going to look into this more deeply, as I am not sure what might have changed between `liferay-npm-bundler` 3.0.0-snapshot.dda6cd1 (which we published 7 months ago) and the new `@liferay/npm-bundler` 3.0.0-alpha.5 (which I just published today). It's possible I broke something when I moved things around into the named scope, but I'll also look back through the history to figure out if anything other changes got made but were never tested in DXP (ie. in 3.0.0-alpha.1, 3.0.0-alpha.2, 3.0.0-alpha.3, 3.0.0-alpha.4 or 3.0.0-alpha.5).

**Comment by wincent** [comment]
Looks like the behavior change was [introduced in alpha.3](https://github.com/liferay/liferay-js-toolkit/blob/3.x-WIP/packages/liferay-npm-bundler/CHANGELOG.md).

- Switched to 3.0.0-alpha.1: build works.
- Switched to 3.0.0-alpha.2: build works.
- Switched to 3.0.0-alpha.3: build explodes.
- 3.0.0-alpha.4: didn't bother testing.
- 3.0.0-alpha.5: didn't bother testing.

```
> Task :apps:frontend-js:frontend-js-recharts:packageRunBuild FAILED
yarn run v1.13.0
warning package.json: No license field
$ liferay-npm-bundler
❌ EntryModuleNotFoundError: Entry module not found: Error: Can't resolve './/Users/greghurrell/code/portal/liferay-portal/modules/apps/frontend-js/frontend-js-recharts/build/node/bundler/bundler/generated/recharts.js' in '/Users/greghurrell/code/portal/liferay-portal/modules/apps/frontend-js/frontend-js-recharts'
...at <unknown file>

❌ EntryModuleNotFoundError: Entry module not found: Error: Can't resolve './/Users/greghurrell/code/portal/liferay-portal/modules/apps/frontend-js/frontend-js-recharts/build/node/bundler/bundler/generated/recharts_lib_index.js' in '/Users/greghurrell/code/portal/liferay-portal/modules/apps/frontend-js/frontend-js-recharts'
...at <unknown file>

❌ Build failed: webpack build finished with errors
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':apps:frontend-js:frontend-js-recharts:packageRunBuild'.
> Process 'command '/Users/greghurrell/code/portal/liferay-portal/build/node/bin/node'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 5s
2 actionable tasks: 2 executed
```

So that gives me something to go on. I'm going to investigate the changes and see if I can unbreak things. I'll escalate do @izaera if I can't figure it out. Moving forward, we should make a point of integrating every js-toolkit release into DXP right away so that we find out about these things as they happen (this has come up on the 2.x branch before, but I believe this is the first time it bites us on the 3.x series).

**Comment by wincent** [comment]
I'm the one who [released alpha.3](https://github.com/liferay/liferay-js-toolkit/releases/tag/liferay-npm-bundler%2Fv3.0.0-alpha.3) by the way, because I wanted a clean slate for the migration to the monorepo. On the one hand, I could have integrated immediately (that would have been best practice) but on the other it would have side-tracked me when it didn't work (especially because I'm not all that familiar with the PRs that went into the release). 🤷‍♂️

**Comment by wincent** [comment]
At @izaera's suggestion, I checked the other alphas too:

alpha.4:

```
$ liferay-npm-bundler
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module '../lib/globals'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/greghurrell/code/portal/liferay-portal/modules/apps/frontend-js/frontend-js-recharts/node_modules/liferay-npm-bundler/bin/liferay-npm-bundler.js:36:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
error Command failed with exit code 1.
```

alpha.5:

```
> Task :apps:frontend-js:frontend-js-recharts:packageRunBuild FAILED
yarn run v1.13.0
warning package.json: No license field
$ liferay-npm-bundler
❌ EntryModuleNotFoundError: Entry module not found: Error: Can't resolve './/Users/greghurrell/code/portal/liferay-portal/modules/apps/frontend-js/frontend-js-recharts/build/node/bundler/bundler/generated/recharts.js' in '/Users/greghurrell/code/portal/liferay-portal/modules/apps/frontend-js/frontend-js-recharts'
...at <unknown file>
```

(etc... it's the same error as seen in previous comments).

I think the obvious smell to investigate here is the nested `bundler/bundler` path inside `build/`, but it may be unrelated.

**Comment by wincent** [comment]
Left [a comment here](https://github.com/liferay/liferay-js-toolkit/commit/a931aedcfdc9f9d30d994c85b56ed6ad246ec418#r43235455) to show where the nested paths are coming from.

**Comment by wincent** [comment]
Other obvious smell to investigate is paths which look like the concatenation of a relative root `./` together with an absolute path: `'.//Users/...` etc.

**Comment by wincent** [comment]
Evil path is getting constructed here: https://github.com/liferay/liferay-js-toolkit/commit/8f4754ae8f7d9fb70aef416e5e763620abc5fa60#r43236682

When you fix that, you see:

```
Error: ENOENT: no such file or directory, open '/Users/greghurrell/code/portal/liferay-portal/modules/node_modules/@liferay/npm-bundler/lib/adapt/templates/export-module.ejs'
```

And that file is indeed missing, so I am going to look into where it went, and whether the complaint is legit or not.

**Comment by wincent** [comment]
Ok, I think things are fixed now:

Screenshot 2020-10-14 -153221-KdksfUxn@2x

`build/` looks like this:

```
build
└── node
    ├── bundler
    │   ├── bundler
    │   │   ├── generated
    │   │   │   ├── recharts.js
    │   │   │   ├── recharts_lib_index.js
    │   │   │   └── webpack.config.json
    │   │   └── webpack
    │   ├── generated
    │   │   ├── recharts.js
    │   │   ├── recharts_lib_index.js
    │   │   └── webpack.config.json
    │   └── webpack
    │       ├── recharts.bundle.js
    │       ├── recharts.bundle.js.map
    │       ├── recharts_lib_index.bundle.js
    │       ├── recharts_lib_index.bundle.js.map
    │       ├── runtime.bundle.js
    │       ├── runtime.bundle.js.map
    │       ├── vendor.bundle.js
    │       └── vendor.bundle.js.map
    └── packageRunBuild
        └── resources
            ├── node_modules
            │   └── frontend-js-recharts$recharts@1.8.5
            │       ├── index.js
            │       ├── lib
            │       │   └── index.js
            │       └── package.json
            ├── package.json
            ├── recharts.bundle.js
            ├── recharts.bundle.js.map
            ├── recharts_lib_index.bundle.js
            ├── recharts_lib_index.bundle.js.map
            ├── runtime.bundle.js
            ├── runtime.bundle.js.map
            ├── vendor.bundle.js
            ├── vendor.bundle.js.map
            └── webpack.manifest.js

12 directories, 27 files
```

Going to have to send a PR for the toolkit and cut a new release and try again.

**Comment by wincent** [comment]
Ok, updated it and took it out of draft mode. Going to run the tests now.

**Comment by wincent** [comment]
ci:test:sf

**Comment by wincent** [comment]
ci:test:relevant

**Comment by wincent** [comment]
ci:test:bundle

**Comment by wincent** [comment]
```
     [exec] Execution failed for task ':apps:frontend-js:frontend-js-recharts:packageRunBuild'.
```

😱 — worked for me locally, I swear!

**Comment by jbalsas** [comment]
> 😱 — worked for me locally, I swear!

I believe you sister!!

**Comment by wincent** [comment]
Well, after `rm -r build node_modules`, it [still works](https://gist.github.com/wincent/f7ee3a1c3b239053ca977b54ca71fe6e). So I am going to kick of a `git clean` and an `ant all` and check back in on this tomorrow.

**Comment by wincent** [comment]
After full clean and build...

```
BUILD SUCCESSFUL
Total time: 23 minutes 6 seconds
```

But in the CI logs you see:

```
     [exec] $ liferay-npm-bundler
     [exec] ??? EntryModuleNotFoundError: Entry module not found: Error: Can't resolve './/opt/dev/projects/github/liferay-portal/modules/apps/frontend-js/frontend-js-recharts/build/node/bundler/bundler/generated/recharts.js' in '/opt/dev/projects/github/liferay-portal/modules/apps/frontend-js/frontend-js-recharts'
     [exec] ...at <unknown file>
     [exec] 
     [exec] ??? EntryModuleNotFoundError: Entry module not found: Error: Can't resolve './/opt/dev/projects/github/liferay-portal/modules/apps/frontend-js/frontend-js-recharts/build/node/bundler/bundler/generated/recharts_lib_index.js' in '/opt/dev/projects/github/liferay-portal/modules/apps/frontend-js/frontend-js-recharts'
     [exec] ...at <unknown file>
     [exec] 
     [exec] ??? Build failed: webpack build finished with errors
```

Note the `bundler/bundler` in there... it's as though it's using the old version still, and indeed, when I look in the `yarn.lock` I see it is... — maybe I didn't actually `git push` the right rev or something? 🤦‍♂️

despair

**Comment by wincent** [comment]
ci:test:sf

**Comment by wincent** [comment]
ci:test:relevant

**Comment by wincent** [comment]
ci:test:bundle

**Comment by wincent** [comment]
I see Recharts still working in the Content Dashboard, so I think this one is good to go maybe?

Screenshot 2020-10-15 -134738-Rfn6H1Dj@2x

**Comment by wincent** [comment]
ci:forward

**Pull request closed without merging**
