### PR TITLE
[7.4-only] LPS-112477 Remove labels attribute from UserCardTag

### PR DESCRIPTION
**Pull request by carloslancha**
User Cards shouldn't support any labels. This is something we introduce during the migration process so we can just simply get rid of it.

Read more about it in https://github.com/liferay/clay/issues/3799

### CODE REVIEW

**Comment by carloslancha** [comment]
ci:test:sf

**Comment by carloslancha** [comment]
ci:test:sf

**Comment by carloslancha** [comment]
ci:test:relevant

**Review by julien — APPROVED** [review]
This PR is not horrible :heart:

**Review by markocikos — APPROVED** [review]
@carloslancha LGTM, but there is a minor conflict to fix before we can push.

**Comment by carloslancha** [comment]
ci:test:sf

**Comment by carloslancha** [comment]
ci:test:relevant

**Comment by carloslancha** [comment]
ci:stop

**Comment by carloslancha** [comment]
ci:test:sf

**Comment by carloslancha** [comment]
ci:test:relevant

**Comment by julien** [comment]
ci:forward

**Pull request closed without merging**
