### PR TITLE
LPD-33480 [DataSetViewBug.testcase] Delete poshi

### PR DESCRIPTION
**Pull request by thektan**
https://liferay.atlassian.net/browse/LPD-33480

- Moves a poshi test that checks the fields `parentTaxonomyCategory` and `parentTaxonomyVocabulary` aren't displayed as selectable fields

**Some additional fixes:**
- Fixed a typo: `searchAndSelecteField` -> `searchAndSelectField`
- Made an improvement that checks `tableVisualizationModeContainer` to exist after selecting the "Table" tab instead of the search bar. I'd expect this to be more reliable and when navigating to the List and Cards tabs, they are already checking in a similar way with `listVisualizationModeContainer` and `cardsVisualizationModeContainer`

### CODE REVIEW

**Comment by thektan** [comment]
ci:test:playwright

**Comment by thektan** [comment]
Looking at failures on testray, none of the failures seem related.

**Review by markocikos — APPROVED** [review]
@thektan LGTM! :sparkles:

**Comment by juanjofgliferay** [comment]
@thektan @markocikos I would say that it will be enough removing the Poshi test as it is no longer a bug. We allow users to select composed fields. 
The test is working because the default Data Set we create uses the `/data-set-manager/table-sections` restApplication and it doesn't have the fields you are looking for.

Creating a Data Set with the restApplication [referenced in the poshi test](https://github.com/liferay-frontend/liferay-portal/pull/4378/files#diff-14925d3457b7d8eaf7e1c54575ca217d3639f270eb4ebce6100e7290d9e47c83L20) you will get those fields.

image

**Comment by thektan** [comment]
@juanjofgliferay Ah, nice catch! I'll remove the playwright test I added.

**Comment by thektan** [comment]
ci:forward

**Pull request closed without merging**
