### PR TITLE
LPS-171860 Fix for Client extension test cases

### PR DESCRIPTION
**Pull request by mateusralv**
Description: 
fix for testing on client extensions (old remote app)

JIRA LINK:
https://issues.liferay.com/browse/LPS-171018
https://issues.liferay.com/browse/LPS-171860
https://issues.liferay.com/browse/LPS-164613
https://issues.liferay.com/browse/LPS-171405

### CODE REVIEW

**Comment by mateusralv** [comment]
ci:test:sf

**Comment by mateusralv** [comment]
ci:test:frontend-remote-apps

**Review by john-co — APPROVED** [review]
Looks good to me! :sunglasses:

Nice job!

**Comment by mateusralv** [comment]
ci:forward

**Pull request closed without merging**
