### PR TITLE
LPS-136752 staging-bar-web isolate CSS and minor bug fixes

### PR DESCRIPTION
**Pull request by pat270**
https://issues.liferay.com/browse/LPS-136752

Screenshot:
staging-bar-web

### CODE REVIEW

**Comment by nhpatt** [comment]
I think it's @claraizquierdo and @YurenaC repository (tango) and it's here: https://github.com/liferay-tango/liferay-portal

**Comment by pat270** [comment]
ci:stop

**Comment by pat270** [comment]
Thanks @nhpatt, I'll send it there.

**Comment by YurenaC** [comment]
@pat270 @nhpatt this is not a Tango team related feature, we think it should be reviewed by frontent-infra team

**Comment by nhpatt** [comment]
ci:reopen

**Comment by nhpatt** [comment]
It's a staging issue (it's wrongly assigned) and they don't have frontends assigned to review it.

**Comment by pat270** [comment]
ci:test:relevant

**Comment by pat270** [comment]
ci:test:relevant

**Comment by pat270** [comment]
ci:test:relevant

**Comment by pat270** [comment]
VGoZVlR9naOZCiRLSy

**Comment by JoyceWang08211** [comment]
The above functional test failures are not related to the current PR. 

@pat270 and @moltam89

**Comment by JoyceWang08211** [comment]
ci:test:relevant

**Comment by nhpatt** [comment]
ci:forward

**Pull request closed without merging**
