### PR TITLE
LPS-118964 - Fix floatElements uses

### PR DESCRIPTION
**Pull request by marcoscv-work**
This PR fixes the use of `floatElements`
Where we needed an `autofit-float` class we were getting `autofit-float-true`.
Now it is fixed

---

How to test the PR:

- Add to the homepage an **Asset Publisher widget**
- Configure it to show all icons of sharing, print, etc
- Save and refresh the page to see the correct class `autoflit-row` applied

### CODE REVIEW

**Comment by marcoscv-work** [comment]
ci:test:sf

**Comment by marcoscv-work** [comment]
ci:test:relevant

**Comment by wincent** [comment]
@hhuijser: given that `floatElements="true"` is always a mistake, is this something the source-formatter could check/fix?

**Comment by marcoscv-work** [comment]
ci:forward

**Pull request closed without merging**
