### PR TITLE
LPS-127468 Implements page accessibility tool sidebar (resent)

### PR DESCRIPTION
**Pull request by diegonvs**
It came from: https://github.com/brianchandotcom/liferay-portal/pull/103123

```
@diegonvs can you help me with the language keys:

These 3 are not in title casing. See https://capitalizemytitle.com/

code-of-the-element=Code of the element
filter-by-category=Filter by category
filter-by-impact=Filter by impact
These are supposed to be sentences but are not complete sentences.

set-of-rules-violated-by-the-highlighted-issues=Set of rules violated by the highlighted issues.
there-are-no-accessibility-violations-in-this-page=There are no accessibility violations in this page
Please resend. Thx @diegonvs
```

Where changes were applied to: d7bbc8e

### CODE REVIEW

**Comment by diegonvs** [comment]
ci:forward

**Comment by diegonvs** [comment]
CI is down :/

**Comment by nhpatt** [comment]
ci:forward

**Comment by nhpatt** [comment]
-- CI right now.

**Pull request closed without merging**
