### PR TITLE
LPS-174965 Revert LPS-172852 

### PR DESCRIPTION
**Pull request by rolandpakai**
Hi Team,

this is a revert request from Danial Sanz here:  https://issues.liferay.com/browse/LPP-47667

Thanks, Roland

https://issues.liferay.com/browse/LPS-174965

### CODE REVIEW

**Review by markocikos — APPROVED** [review]
LGTM!

Failures in https://github.com/liferay-frontend/liferay-portal/pull/3034#issuecomment-1421557896 are probably unrelated.

**Comment by markocikos** [comment]
ci:forward

**Comment by mateusralv** [comment]
I'm on it! 🕵🏽

**Comment by mateusralv** [comment]
Hi @markocikos the failures are not related to your PR 🎉

**Comment by markocikos** [comment]
ci:foward

**Comment by markocikos** [comment]
ci:forward

**Comment by markocikos** [comment]
I'll try one more time, manually forward if it fails.

**Comment by markocikos** [comment]
ci:forward

**Comment by markocikos** [comment]
CI report?

**Comment by markocikos** [comment]
Manual forward: https://github.com/brianchandotcom/liferay-portal/pull/130080

**Pull request closed without merging**
