### PR TITLE
LPS-178777 | Automation DatasetsAPI#CanCreateDatasetEntryViaAPI

### PR DESCRIPTION
**Pull request by abhnerramos**
**Description**
- Given creating a Data Set via API
- When a Data set is created
- Then the data set is shown in the list

**JIRA Ticket**
https://issues.liferay.com/browse/LPS-178777

**Recurring error**
Every time I run `ant format-source-current-branch` to check if source-format is right, it asks me to add a FF on `src/portal.properties'

### CODE REVIEW

**Comment by abhnerramos** [comment]
ci:stop

**Comment by abhnerramos** [comment]
ci:test:frontend

**Comment by abhnerramos** [comment]
ci:test:sf

**Comment by abhnerramos** [comment]
ci:test:sf

**Comment by abhnerramos** [comment]
ci:test:frontend

**Comment by manoelcyreno** [comment]
ci:test:relevant

**Comment by manoelcyreno** [comment]
ci:test:frontend

**Comment by abhnerramos** [comment]
hey @manoelcyreno , @mateusralv  said that everything is right, but the only change we have to make is split the API up to follow liferay's standard. Mateus said he would do it and I am waiting for his push.

**Comment by mateusralv** [comment]
ci:test:frontend

**Comment by mateusralv** [comment]
ci:test:sf

**Comment by mateusralv** [comment]
ci:test:frontend

**Comment by mateusralv** [comment]
ci:test:sf

**Comment by mateusralv** [comment]
ci:test:frontend

**Pull request closed without merging**
