### PR TITLE
LPS-175377 Improve UX of FDS Views Manager headless resource selection

### PR DESCRIPTION
**Pull request by markocikos**
### References

- [LPS-175377 Improve UX of headless resource selection](https://issues.liferay.com/browse/LPS-175377)
- This is a followup on https://github.com/liferay-frontend/liferay-portal/pull/3031
- [Figma mockups](https://www.figma.com/file/VTOLTBFe99y9kA7AY3TcNR/lps-175276-design-app-to-manage-datasets?node-id=68%3A99382&t=gzTL547Z7wFDfZdy-0)

### What is the goal of this PR?

We are replacing `ClayAutocomplete` component with `ClayDropDown`, implementing selection, filtering and highlighting logic manually. 

Notes:
- See previous discussions on the feature
  -  https://github.com/liferay-frontend/liferay-portal/pull/3031#discussion_r1099251104 
  -  https://github.com/liferay-frontend/liferay-portal/pull/3031#discussion_r1099285775
- With this lower-level approach, I could also implement styled appearance of selected item, going a bit beyond mockups cc @ugeortiz see end of movie below.
- I initially tried with the `ClayPicker` component, but I was not able to add functional search input into dropdown menu.
- `Dropdown` component is just for readability, to reduce line breaking.
- `DropdownMenu` component is a standalone component, containing state for querying, filtering and highlighting. This prevents issues with full component refreshing into closed dropdown menu.
 
/cc @bryceosterhaus @dsanz @kresimir-coko 

### What does it look like?

https://user-images.githubusercontent.com/5435511/218513111-3f2b48e8-4adc-484c-b431-a3920dba3ade.mp4

### Steps to reproduce

1. Add `feature.flag.LPS-164563=true` to `portal-ext.properties`
2. Open Global Menu > Control Panel > Object > Datasets

### CODE REVIEW

**Comment by john-co** [comment]
ci:help

**Comment by john-co** [comment]
ci:test:relevant

**Comment by john-co** [comment]
ci:test:frontend-data-set

**Comment by john-co** [comment]
Rerunning since a new test related to this has been recently merged: https://github.com/liferay-frontend/liferay-portal/pull/3043/files

**Review by kresimir-coko — APPROVED** [review]

**Comment by markocikos** [comment]
@mateusralv @john-co The test that caused failure in https://github.com/liferay-frontend/liferay-portal/pull/3051#issuecomment-1430428477 does not look right. This is [the newly merged test](https://github.com/liferay-frontend/liferay-portal/pull/3043/files). Can you please take a look?

```
Click(locator1 = "CreateObject#OBJECT_LABEL");
```
This seems to result in 
```
Element is not present at "//input[@id='_com_liferay_object_web_internal_object_definitions_portlet_ObjectDefinitionsPortlet_label'] | //div[@class='input-group-item']//input[@class='form-control'] | //label[text()='Label']/following-sibling::div//input"
```
`ObjectDefinitionsPortlet` is not the right portlet, and the checked markup likely relates to it.

**Comment by markocikos** [comment]
cc @eltonccdantas

**Comment by markocikos** [comment]
Force-pushed, with some minor changes:
- Updated Clay version in dependencies. This made push necessary.
- Improved accessibility, fixing https://issues.liferay.com/browse/LPS-175754 (additional commit)
- Changed some interface names, for consistency (additional commit)

**Comment by eltonccdantas** [comment]
Thanks @markocikos , I'll check if [that](https://issues.liferay.com/browse/LPS-175336) is no longer reproducible so that I can go on [those](https://issues.liferay.com/browse/LPS-174054) tests automation.

**Review by matuzalemsteles — COMMENTED** [review]
Hey @markocikos sorry for the long delay with this. We even discussed this in PEDS which would be the best component for this, Picker or Autocomplete, Autocomplete would make more sense an issue here is we may be trying to create a component at the end with the same objectives, the big issue we were discussing was the respect for accessibility.

For example Autocomplete follows combobox recommendations with autocomplete list https://www.w3.org/WAI/ARIA/apg/patterns/combobox/examples/combobox-autocomplete-list/ already when you want the behavior of selecting an item within a list in the case of Picker we follow the accessibility recommendations https://www.w3.org/WAI/ARIA/apg/patterns/combobox/examples/combobox-select-only/.

When we try to add new behaviors in the case of adding a search to a Picker for example, it breaks all accessibility behavior, moving between elements using visual focus instead of browser focus, keyboard shortcuts. This would also be the same for Autocomplete.

So adding new extensions changes the whole accessibility part and we have to rethink how best to deal with it while respecting the w3c rules. Moving this to use DropDown is a good idea the visual and interaction part will look like what the designer wants but the accessibility part is still an issue because DropDown accessibility is more of a menu of actions and has different recommendations for what we want .

cc @marcoscv-work @ethib137

**Comment by markocikos** [comment]
Force-pushed! Changes:
- Added regex simplification based on great comment https://github.com/liferay-frontend/liferay-portal/pull/3051#discussion_r1107241960 (additional commit) @dsanz 
- Added accessibility improvements for dropdown, based on https://github.com/liferay-frontend/liferay-portal/pull/3051#pullrequestreview-1300422109. I copied the roles for the list element and items from the `Picker` component.     @matuzalemsteles Is this enough to set it away from "menu of actions" role?

**Comment by dsanz** [comment]
ci:test:relevant

**Comment by mateusralv** [comment]
I'm on it 🕵🏽

**Comment by mateusralv** [comment]
Hi @markocikos I realized that you sent me authorization to add commits to this repository but I did not see the email before, could you send it again? :/

**Comment by mateusralv** [comment]
Hi @markocikos I found one unique failure and created a test fix for solving this.

Unique failure: 
[LocalFile.FrontendDataSetAdmin#CanDisplayHeadlessDeliveryAPIResources](https://testray.liferay.com/home/-/testray/case_results/2199562233)

[Testray comparison ](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1676579772125&testrayRunIdA=2199437956&testrayRunIdB=2199562106)

**Comment by mateusralv** [comment]
ci:test:relevant

**Comment by matuzalemsteles** [comment]
> I copied the roles for the list element and items from the Picker component. @matuzalemsteles Is this enough to set it away from "menu of actions" role?

I believe so, this is the first step, still of course we are not handling with the keyboard shortcuts from the accessibility part of combobox only but we will need to investigate first how this behaves within a popup with a search since it doesn't cover this use case.

**Comment by markocikos** [comment]
ci:forward

**Comment by markocikos** [comment]
The SF failure in https://github.com/liferay-frontend/liferay-portal/pull/3051#issuecomment-1434409230 in unrelated, but I don't see solution anywhere in Brian's fork or PR queue. I'll add SF fix in commit, push PR with it.

**Comment by markocikos** [comment]
ci:test:sf

**Comment by markocikos** [comment]
ci:forward

**Pull request closed without merging**
