### PR TITLE
LPS-152751 Update tests from RemoteAppsWorkflow file.

### PR DESCRIPTION
**Pull request by mateusralv**
Background:
Follow up on [LPS-152607](https://issues.liferay.com/browse/LPS-152607). The Workflow System Settings is planned to change to Client Extension Entry. Please update the poshi tests to match this with the fix.

Affected Cases:
[LocalFile.RemoteAppsWorkflow#AdminCanApproveRemotePortlet](https://testray.liferay.com/home/-/testray/case_results/1713924092)
[LocalFile.RemoteAppsWorkflow#CanSendWorkflowNotification](https://testray.liferay.com/home/-/testray/case_results/1713924325)
[LocalFile.RemoteAppsWorkflow#PendingRemoteAppCannotBeAddedToPage](https://testray.liferay.com/home/-/testray/case_results/1713924327)
[LocalFile.RemoteAppsWorkflow#CanConfigureWorkflowInstanceLevel](https://testray.liferay.com/home/-/testray/case_results/1713924324)

JIRA Ticket:
https://issues.liferay.com/browse/LPS-152751

### CODE REVIEW

**Comment by mateusralv** [comment]
ci:test:frontend:nocompile

**Comment by susanchen3** [comment]
Taking a look :mag:

**Review by susanchen3 — APPROVED** [review]
Looks good to me! Thanks! :D

**Comment by susanchen3** [comment]
ci:forward

**Pull request closed without merging**
