### PR TITLE
LPS-188834 Hide DS view item selector as per the feature flag

### PR DESCRIPTION
**Pull request by markocikos**
### References

- [LPS-188834 Hide dataset view item selector as per the feature flag](https://issues.liferay.com/browse/LPS-188834)

### What is the goal of this PR?

We're making three changes in this PR, in their respective commits:
1. Adding a missing language key.
2. Hiding DS view selector if FF is not enabled.
3. Hiding DS fragment from selection in page configuration, if FF is not enabled.

### CODE REVIEW

**Comment by markocikos** [comment]
Force-pushed, to fix conflicts on lang files. No changes in code.

**Comment by markocikos** [comment]
ci:test:sf

**Comment by markocikos** [comment]
@dsanz can we forward this?

**Comment by markocikos** [comment]
ci:test:relevant

**Comment by markocikos** [comment]
ci:test:relevant

**Review by dsanz — APPROVED** [review]

**Comment by dsanz** [comment]
@markocikos  ready to go, just resolve the conflicts and forward

**Comment by markocikos** [comment]
ci:forward

**Comment by dsanz** [comment]
@mateusralv this one is also something we are aiming at merging, and we're not sure about the relevant

**Comment by markocikos** [comment]
Fixed lang key conflict, no other changes.

**Comment by markocikos** [comment]
ci:test:sf

**Comment by dsanz** [comment]
@mateusralv we're getting closer, this "relevant" suite also needs review before fwd, thanks again!

**Comment by mateusralv** [comment]
Hi @markocikos and @dsanz I found no unique, PR-related failures in this relevant result https://github.com/liferay-frontend/liferay-portal/pull/3501#issuecomment-1614555649 😄 

[Testray Comparison](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1688143335570&testrayRunIdA=2366214663&testrayRunIdB=2366275077)

**Comment by mateusralv** [comment]
ci:test:relevant

**Comment by mateusralv** [comment]
The results I analyzed were from before the last commits were added, so I ran the relevant one again and will take a look at the new results 😄

**Comment by mateusralv** [comment]
Hi @markocikos and @dsanz The failures are not related!
[
Testray Comparison](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1688156064435&testrayRunIdA=2366499659&testrayRunIdB=2366723098)

**Comment by mateusralv** [comment]
ci:forward

**Comment by dsanz** [comment]
ci:forward:force

**Pull request closed without merging**
