### PR TITLE
LPS-202135 Exchange flipping and style evaluation order

### PR DESCRIPTION
**Pull request by chestofwonders**
The goal is to make a technical proposition for [this analysis](https://liferay.atlassian.net/wiki/spaces/ENGFRONTENDINFRA/pages/2558951461/LPS-201051+Research+SPA+style+evaluation).

This solution is just to exchange flipping pages and style evaluation order, so the main problem is avoided. Some minor flikering effects still happen, but look very small in comparison, and seems that get absolute no flickering effects is not possible.

### CODE REVIEW

**Review by bryceosterhaus — CHANGES_REQUESTED** [review]
> no flickering effects is not possible.

This worries me. Was this flickering happening before this change? If not, I don't think we can proceed with merging this, especially because if this changes introduces flickering, then we will introduce that for _all_ users, whereas the original LPP issue is only happening for stylebook users.

**Comment by chestofwonders** [comment]
> > no flickering effects is not possible.
> 
> This worries me. Was this flickering happening before this change? If not, I don't think we can proceed with merging this, especially because if this changes introduces flickering, then we will introduce that for _all_ users, whereas the original LPP issue is only happening for stylebook users.

I agree with you. Of course, if we are introducing new undesirable effects we shouldn't merge the code, but I haven't noticed any new issue.

What I mean with my comment is that this solution solves the specific flickering problem reported in the issue, but not another minor effects that still happen 

(for example, in the user profile icon there's a flicking of the background color)
image

which is a pity since the original purpose was trying to solve all of them.

**Comment by bryceosterhaus** [comment]
I am a little confused... The flickering you mentioned, does that happen before your changes or only after?

**Comment by chestofwonders** [comment]
> I am a little confused... The flickering you mentioned, does that happen before your changes or only after?

Before and after

**Comment by bryceosterhaus** [comment]
@chestofwonders ah I see, I thought it was just a result after. If it's happening in both cases then this is fine and can see what ci/qa says

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by mateusralv** [comment]
Hi @chestofwonders I found no failures in functional tests, but the `js-unit-jdk8/0/0` module returned the error that I am in doubt if it is related, could you take a look?

```
Warning: Button Accessibility: Component has only the Icon declared. Define an `aria-label` or `aria-labelledby` attribute that labels the interactive button that screen readers can read. The `title` attribute is optional but consult your design team.
     [exec]     console.error ../../../node_modules/react/node_modules/prop-types/checkPropTypes.js:20
     [exec]       Warning: Failed prop type: The prop `name` is marked as required in `BaseEditor`, but its value is `undefined`.
     [exec]           in BaseEditor (created by ForwardRef)

...

console.error ../../../node_modules/warning/warning.js:34
     [exec]       Warning: Button Accessibility: Component has only the Icon declared. Define an `aria-label` or `aria-labelledby` attribute that labels the interactive button that screen readers can read. The `title` attribute is optional but consult your design team.
     [exec]     console.error ../../../node_modules/react-dom/cjs/react-dom.development.js:530
     [exec]       Warning: Invalid DOM property `readonly`. Did you mean `readOnly`?
     [exec]           in input (created by ClayInput)

...

       in Editor
     [exec]     console.error ../../../node_modules/react-dom/cjs/react-dom.development.js:530
     [exec]       Warning: Invalid DOM property `tabindex`. Did you mean `tabIndex`?
     [exec]           in input (created by ClayInput)
     [exec]          

...

onsole.error ../../../node_modules/react/cjs/react.development.js:167
     [exec]       Warning: Each child in a list should have a unique "key" prop.
     [exec]       
     [exec]       Check the render method of `FieldsDropdown`. See https://fb.me/react-warning-keys for more information.
     [exec]           in ClayDropDownItem (created by FieldsDropdown)
     [exec]       

```
And I’ll run the stable again to do double-check.

**Comment by mateusralv** [comment]
ci:test:stable

**Comment by chestofwonders** [comment]
> Hi @chestofwonders I found no failures in functional tests, but the `js-unit-jdk8/0/0` module returned the error that I am in doubt if it is related, could you take a look?
> 
> ```
> Warning: Button Accessibility: Component has only the Icon declared. Define an `aria-label` or `aria-labelledby` attribute that labels the interactive button that screen readers can read. The `title` attribute is optional but consult your design team.
>      [exec]     console.error ../../../node_modules/react/node_modules/prop-types/checkPropTypes.js:20
>      [exec]       Warning: Failed prop type: The prop `name` is marked as required in `BaseEditor`, but its value is `undefined`.
>      [exec]           in BaseEditor (created by ForwardRef)
> 
> ...
> 
> console.error ../../../node_modules/warning/warning.js:34
>      [exec]       Warning: Button Accessibility: Component has only the Icon declared. Define an `aria-label` or `aria-labelledby` attribute that labels the interactive button that screen readers can read. The `title` attribute is optional but consult your design team.
>      [exec]     console.error ../../../node_modules/react-dom/cjs/react-dom.development.js:530
>      [exec]       Warning: Invalid DOM property `readonly`. Did you mean `readOnly`?
>      [exec]           in input (created by ClayInput)
> 
> ...
> 
>        in Editor
>      [exec]     console.error ../../../node_modules/react-dom/cjs/react-dom.development.js:530
>      [exec]       Warning: Invalid DOM property `tabindex`. Did you mean `tabIndex`?
>      [exec]           in input (created by ClayInput)
>      [exec]          
> 
> ...
> 
> onsole.error ../../../node_modules/react/cjs/react.development.js:167
>      [exec]       Warning: Each child in a list should have a unique "key" prop.
>      [exec]       
>      [exec]       Check the render method of `FieldsDropdown`. See https://fb.me/react-warning-keys for more information.
>      [exec]           in ClayDropDownItem (created by FieldsDropdown)
>      [exec]       
> ```
> 
> And I’ll run the stable again to do double-check.

Hi @mateusralv ! These failures are not related, for me the PR it's safe for forward, but I realized stable test has failed. Anything I can do from my side?

**Comment by mateusralv** [comment]
Hi @chestofwonders I took a look at the latest results of the stable and it returned the same results, is it because of these errors that the stable is failing, could you update the PR branch with master and run the stable again?

**Comment by chestofwonders** [comment]
ci:test:stable

**Comment by chestofwonders** [comment]
ci:test:stable

**Comment by chestofwonders** [comment]
ci:forward

**Comment by dsanz** [comment]
ci:forward:force

**Pull request closed without merging**
