### PR TITLE
LPS-189514 When a CET FF is off, the list of client extensions does not render

### PR DESCRIPTION
**Pull request by dsanz**
In this PR we're controlling the exception thrown when CET factory can't handle a type of CE. This way, when we turn a CE FF off, the process of getting the list of CEs will not break and CE UI will display.

To reproduce this error, turn Dataset beta feature on, then create a "FDS Cell Renderer Client Extension" via UI. Now turn feature off and go back to the CE UI. List render is stuck.

Other notes:
 - We also filter out the CET included from the workspace in case their corresponding FF is turned off

### CODE REVIEW

**Comment by dsanz** [comment]
ci:test:sf

**Review by markocikos — APPROVED** [review]
@dsanz LGTM! :sparkles:

**Comment by dsanz** [comment]
@mateusralv could we have a quick look to "relevant"? This PR solves a very noticeable bug in the client extension list. Thanks a lot

**Comment by mateusralv** [comment]
Hi Dani, I found some failures in this PR after analyzing the tests that failed the relevant one. When creating client extensions of type Iframe and custom element the success toast is shown but the client extension is not shown in the list 😢 

PR Bundles:

https://github.com/liferay-frontend/liferay-portal/assets/44584050/58de4275-cc4e-49cf-9571-557b7ea6f0fe


[Testray Comparison](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1688615580505&testrayRunIdA=2370436449&testrayRunIdB=2370844233)

**Comment by dsanz** [comment]
Nice catch @mateusralv I've made a mistake in the logic and fixed it in the new commit

**Comment by dsanz** [comment]
ci:test:sf

**Comment by dsanz** [comment]
ci:test:relevant

**Comment by dsanz** [comment]
ci:test:stable

**Comment by markocikos** [comment]
ci:forward

**Pull request closed without merging**
