### PR TITLE
LPS-160155 Rename "Remote Apps" to "Client Extensions" files related to poshi test

### PR DESCRIPTION
**Pull request by mateusralv**
**Background:**
All poshi test files in portal repo are updated from "Remote Apps" to "Client Extensions"

**To-do:**
- [x] Testcases files, see on CI https://github.com/liferay-frontend/liferay-portal/pull/2937#issuecomment-1367590877 🟢 
- [x] Macro files
- [x] JSON Macro files
- [x] Path Files

**JIRA link:**
https://issues.liferay.com/browse/LPS-160155

### CODE REVIEW

**Comment by mateusralv** [comment]
ci:test:frontend-remote-apps

**Comment by mateusralv** [comment]
ci:test:relevant

**Comment by mateusralv** [comment]
ci:stop

**Comment by mateusralv** [comment]
ci:test:relevant

**Comment by mateusralv** [comment]
ci:stop

**Comment by mateusralv** [comment]
ci:test:relevant

**Comment by mateusralv** [comment]
ci:test:frontend-remote-apps

**Comment by mateusralv** [comment]
ci:test:relevant

**Comment by mateusralv** [comment]
ci:test:relevant

**Comment by mateusralv** [comment]
ci:test:relevant

**Comment by mateusralv** [comment]
ci:test:frontend-remote-apps

**Comment by mateusralv** [comment]
ci:test:sf

**Comment by mateusralv** [comment]
ci:test:sf

**Comment by mateusralv** [comment]
ci:test:sf

**Comment by mateusralv** [comment]
ci:stop

**Comment by mateusralv** [comment]
ci:test:sf

**Comment by mateusralv** [comment]
ci:test:frontend-remote-apps

**Comment by mateusralv** [comment]
ci:test:relevant

**Comment by mateusralv** [comment]
I took a look at the results of the [ci:test:frontend-remote-apps](https://github.com/liferay-frontend/liferay-portal/pull/2937#issuecomment-1371209152) and no failures are unique, all are also in the master. 

[testray comparison](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1672861395615&testrayRunIdA=2147731740&testrayRunIdB=2149520403)

**Comment by mateusralv** [comment]
ci:stop

**Comment by mateusralv** [comment]
ci:test:relevant

**Comment by mateusralv** [comment]
ci:stop:relevant

**Comment by mateusralv** [comment]
ci:commerce

**Comment by john-co** [comment]
Hi @mateusralv , please rebase to fix the conflict

**Comment by mateusralv** [comment]
Done! @john-co

**Review by john-co — APPROVED** [review]
Looks good to me! :sunglasses:

There are some other mentions of remote apps within description, tasks, and other files like test.properties and ci.properties that I can think of from top of my head to clean up as a follow up as well.

**Comment by john-co** [comment]
ci:forward

**Pull request closed without merging**
