### PR TITLE
LPS-135068 Add asset tags persisted subscribers to MBMessage subscription sender to notify users subscribed to the tags added to the MBMessage

### PR DESCRIPTION
**Pull request by javierdearcos**

### CODE REVIEW

**Comment by javierdearcos** [comment]
It would be possible to add the feature to taggable entities with little effort, so the users will be notified when a taggable entity using the tag is created.

The entities I've found that can be tagged are JournalArticle, BlogsEntry, DLFileEntry, KBArticle, WikiPage.

The code will be very similar so we can try to find a common place to call it. SubscriptionSender would be a good candidate to have something like addAssetEntryPersistedSubscriber but we should pass the AssetEntryLocalService as it is a util class and not a component. Another possibility would be to add a new method in AssetEntryLocalService passing the SubscriptionSender inverting the dependency.

**Review by nhpatt — APPROVED** [review]
Pretty straightforward, let's go ahead!

**Comment by nhpatt** [comment]
ci:forward

**Comment by nhpatt** [comment]
I would invert the dependency. I think Blogs is already using `SubscriptionSender` so it makes sense to keep following the same pattern and ideally `SubscriptionSender` should not depend in concrete entities like AssetTags.

**Pull request closed without merging**
