### PR TITLE
LPS-143454 Restrict the VulcanBatchEngineTaskItemDelegates generated from REST Builder

### PR DESCRIPTION
**Pull request by javierdearcos**
There were many cases where the API Resources were implementing the VulcanBatchEngineTaskItemDelegate interface in resources that have no batch capabilities.

I've restricted the implementation of this interface just in the cases that make sense, where there are batch endpoints or at least there is an endpoint to return a list of resources that can be used to export the resources.

This way we get rid of a lot of false positives that were present mostly in Commerce APIs.

Refactored to unify the generateBatch logic in the FreeMarkerTool class.

I've preferred to avoid breaking the APIs by leaving the setVulcanBatchEngineImportTaskResource method in resources and the call from the GraphQL Mutation class.

### CODE REVIEW

**Comment by ccorreagg** [comment]
> ###  ci:test:stable - 26 out of 27 jobs passed
> ###  ci:test:relevant - 177 out of 186 jobs passed in 1 hour 54 minutes
> Click here for more details.
> ##### Test bundle downloads:
> * [liferay-portal-bundle-tomcat.tar.gz](https://files.liferay.com/private/bundles/test-1-36/jobs/test-portal-acceptance-pullrequest(master)/builds/1083/liferay-portal-bundle-tomcat.tar.gz) (mirrors: [dlc](http://mirrors.dlc.liferay.com/files.liferay.com/private/bundles/test-1-36/jobs/test-portal-acceptance-pullrequest(master)/builds/1083/liferay-portal-bundle-tomcat.tar.gz), [lax](http://mirrors.lax.liferay.com/files.liferay.com/private/bundles/test-1-36/jobs/test-portal-acceptance-pullrequest(master)/builds/1083/liferay-portal-bundle-tomcat.tar.gz))

I think the buildREST command is missing in the modules/dxp/apps folder

**Comment by javierdearcos** [comment]
I've made changes to unify the generateBatch logic in all templates and remove the no necessary code although some API versions are bumped in major.

I've run again the buildREST command because you were right. I had the portal profile instead of the DXP profile and the buildREST command was not executed in DXP apps

**Comment by javierdearcos** [comment]
ci:test:sf

**Comment by javierdearcos** [comment]
ci:test:relevant

**Review by ccorreagg — APPROVED** [review]
Much better to update all the generateBatch references to the same function :+1: 

Great and simple

**Comment by ccorreagg** [comment]
After having a look at the PR deeply, I am doubting about if it is necessary or not to modify this code in `ResourceOpenAPIParser` class:

```
if (configYAML.isGenerateBatch() &&
	[...]
```

**Comment by javierdearcos** [comment]
ci:test:sf

**Comment by javierdearcos** [comment]
ci:test:relevant

**Comment by javierdearcos** [comment]
ci:forward

**Pull request closed without merging**
