### PR TITLE
LPS-124035 Fix css custom properties button rules

### PR DESCRIPTION
**Pull request by eduardoallegrini**
This PR fixes a bug generated by a recent change (in css-custom-properties layer) we did to avoid a conflict with Clay.

During that change we forgot to update a second CSS rule that produced this error https://issues.liferay.com/browse/LPS-124035.

In order to avoid these situations we created a variable that contains all these rules.

/cc @dgarciasarai

### CODE REVIEW

**Comment by eduardoallegrini** [comment]
ci:test:sf

**Comment by eduardoallegrini** [comment]
ci:test:relevant

**Comment by eduardoallegrini** [comment]
ci:forward

**Comment by dgarciasarai** [comment]
Thanks @eduardoallegrini!

**Pull request closed without merging**
