### PR TITLE
LPS-187771 Add test to rest information on DataSetViews

### PR DESCRIPTION
**Pull request by JerryAdrianoo**
**Description:**
Add tests to dataset views.

**Jira Ticket:**
https://liferay.atlassian.net/browse/LPS-187771

### CODE REVIEW

**Comment by JerryAdrianoo** [comment]
ci:test:frontend-data-set

**Comment by JerryAdrianoo** [comment]
cc:@CarlosBrichete

**Comment by JerryAdrianoo** [comment]
ci:test:frontend-data-set

**Comment by JerryAdrianoo** [comment]
These failures are not related.

**Review by CarlosBrichete — APPROVED** [review]
LGTM

**Comment by JerryAdrianoo** [comment]
ci:forward

**Pull request closed without merging**
