### PR TITLE
LPS-179380 Search bar does not work on the Dataset view page

### PR DESCRIPTION
**Pull request by dsanz**
Reference: 
 - https://issues.liferay.com/browse/LPS-179380

In this PR we're changing the endpoint used to fetch related FDSViews from a given FDSEntry so that we can make search work. Before this PR, we were fetching the FDSViews from the FDSEntry endpoint as related objects. This endpoint does not support Search at this moment. 

Solution is to use the "proper" endpoint for the entity in question (FDSViews) but pre-filtered to just fetch the FDSViews associated to the current FDSEntry.

### CODE REVIEW

**Comment by dsanz** [comment]
ci:test:sf

**Comment by dsanz** [comment]
ci:test:sf

**Comment by markocikos** [comment]
I'll push this, we can make the small tiding up as a part of a future task.

**Comment by markocikos** [comment]
ci:forward

**Pull request closed without merging**
