### PR TITLE
LPS-153319 Allow to set/update extended properties in existing Liferay Portal Entities

### PR DESCRIPTION
**Pull request by javierdearcos**
Changes in the old PR based on the received feedback:

- Delete deprecated ExtensionContext and related classes
- Rename ExtensionProviders to EntityExtensionHandler, as it is a class that will handle the logic of entity extensions getting the extended properties, setting them, validating them... This new name also matches with existing writer interceptors as EntityExtensionWriterInterceptor and PageEntityExtensionWriterInterceptor, and with the EntityExtensionThreadLocal
- Rename ExtendedPropertyValidator and FieldType to PropertyValidator and PropertyType. Change the rest of the fields and methods in the same way. This way we avoid mixing the field and property concepts and everything it related to the property concept

---
Original pull request comment:
This PR defines the new API Extensibility Framework that will allow the extension of System Objects to set/update extended properties and get these extended properties.

The new interface is called **ExtensionProvider** and is meant to replace the old ExtensionContext mechanism. The definition of the new interface is the following:
```
public interface ExtensionProvider {

        // To be called to get the extended properties of an object
	public Map<String, Serializable> getExtendedProperties(
			long companyId, Object entity)
		throws Exception;

         // To be called to get the definition of the extended properties to validate and to document
	public Map<String, ExtendedPropertyDefinition>
		getExtendedPropertyDefinitions(long companyId, String className);

         // To be called to get the filtered properties of an object
	public Collection<String> getFilteredPropertyNames(
		long companyId, Object entity);

        // To check if the extension applies to the given company and className. Used by the infrastructure to select the correct ExtensionProviders
	public boolean isExtensionFor(long companyId, String className);

        // To be called to set/update the extended properties of an object
	public void setExtendedProperties(
			long companyId, Object entity,
			Map<String, Serializable> extensionProviderExtendedProperties)
		throws Exception;

}
```
The infrastructure includes an **ExtensionProviderRegistry** that will register all ExtensionProviders active in the portal. This registry is used by the **ExtensionProvidersContextResolver** that will be called by the infrastructure to get the ExtensionProviders class, which contains the list of all ExtensionProviders that applies to the object in the request.

The **ExtensionProviders** class is necessary to have a ContextResolver that will inject this class, and also ease the aggregation logic by calling all extension providers that apply to a given object.

The **EntityExtensionThreadLocal** is needed to save the extended properties that come in the message body and then recover them in the writer interceptors to call the set/update logic.

The workflow is:

1. A new request is received
2. The JAX-RS message body reader checks if the class of the message body has any ExtensionProvider
3. If true get the extended property definitions to validate the extended properties received in the message body
4. Save the extended properties in the thread-local to be recovered later
5. Process the original request
6. After processing the request, in the JAX-RS writer interceptors recover the extended properties
7. If exists call the setExtendedProperties to set/update the extended property values
8. Call the getExtendedProperties to be included in the response
9. Proceed to send the response

This is the first PR to start establishing the infrastructure

### CODE REVIEW

**Comment by javierdearcos** [comment]
ci:test:sf

**Review by ccorreagg — APPROVED** [review]
LGTM!

**Comment by javierdearcos** [comment]
Let's try forwarding it from here. And if it takes to much time or fails I will send it directly

**Comment by javierdearcos** [comment]
ci:forward

**Pull request closed without merging**
