### PR TITLE
COMMERCE-4645 data set display now supports apiURLs with filter param already in it

### PR DESCRIPTION
**Pull request by FabioDiegoMastrorilli**
In some scenarios we might want to display a set of data already filtered and still being able to refine the query by adding more filters on top.

This PR make it possibile by making the data set able to digest an apiURL with filter param already in it

### CODE REVIEW

**Comment by brunobasto** [comment]
ci:test:sf

**Comment by brunobasto** [comment]
@FabioDiegoMastrorilli SF errors 😢

**Comment by wincent** [comment]
> this looks a bit complicated. We should probably start to think about extracting these odata string manipulation to a reusable module. I know that segments also has its own [set of utilities](https://github.com/liferay/liferay-portal/blob/a0397bf6adc1a9d6e60fb43579475241720f6526/modules/apps/segments/segments-web/src/main/resources/META-INF/resources/js/utils/odata.es.js) as well. So maybe we could see wha they have in common and add something in frontend-js-web.

I think I brought this up as part of the review we did a while back ([IFI-1401](https://issues.liferay.com/browse/IFI-1401)) and there might even have been a Jira ticket for it but I can't find anything in Google Drive, Jira, my email archive, or Slack, so maybe I am misremembering... 🤔

**Comment by jbalsas** [comment]
@FabioDiegoMastrorilli, what's the timeline on this? Do we need it for the GA release? 

We have some cleanup to do around dataset and odata support, if it can wait we can try to work out some of the pieces. Otherwise, I guess we'll have to forward it and address it later... but the more we add the harder it will become later to untangle, so please, be mindful here and let us know how critical this is so we can decide how to proceed! :)

**Comment by FabioDiegoMastrorilli** [comment]
We already pass filters via apiURL in commerce so, at the moment, there are a few bugs which are gonna be fixed by merging this PR :) Anyway I totally agree with moving all the odata related code in a specific module... let's just do it after making commerce code work as expected after migration please :3

**Comment by FabioDiegoMastrorilli** [comment]
ci:test:sf

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by brunobasto** [comment]
> > this looks a bit complicated. We should probably start to think about extracting these odata string manipulation to a reusable module. I know that segments also has its own [set of utilities](https://github.com/liferay/liferay-portal/blob/a0397bf6adc1a9d6e60fb43579475241720f6526/modules/apps/segments/segments-web/src/main/resources/META-INF/resources/js/utils/odata.es.js) as well. So maybe we could see wha they have in common and add something in frontend-js-web.
> 
> I think I brought this up as part of the review we did a while back ([IFI-1401](https://issues.liferay.com/browse/IFI-1401)) and there might even have been a Jira ticket for it but I can't find anything in Google Drive, Jira, my email archive, or Slack, so maybe I am misremembering... 🤔

I remember you did bring this up a while back indeed. And I just found the ticket: https://issues.liferay.com/browse/LPS-116585

**Comment by wincent** [comment]
> I remember you did bring this up a while back indeed. And I just found the ticket: https://issues.liferay.com/browse/LPS-116585

Nice!

now-where-did-i-put-my-glasses

**Comment by jbalsas** [comment]
> Overall LGTM [...]

Going to go on with this, since `commerce` is still the main consumer and we can work on improving this before rolling it out to more teams

**Comment by jbalsas** [comment]
ci:forward

**Pull request closed without merging**
