### PR TITLE
LPS-107476 Adds a missing `selectedLanguageId` on input_localized AUI component

### PR DESCRIPTION
**Pull request by diegonvs**
### Test Case:

1. Create a basic web content for the default language (say, en_US) with title "bwcenglish".
2. Edit the web content and click on the upper-most flag icon to select another language, for example, Spanish (es_ES).
3. Change the title to "bwcspanish".
4. Save as Draft.
5. Click on the same flag icon and try to change back to the default language.

✅  Expected: The language can be changed.
❌  Observed: The language remains as Spanish.

Taking as a basis Pavel's comment on https://issues.liferay.com/browse/LPS-107476?focusedCommentId=2153486&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-2153486, I added the selectedLanguageId and updated the behaviour on AUI component when it decides which languageId will be settled by default.

You may ask about the differences between `selectedLanguageId` and `defaultLanguageId`:
The difference between those tags is because `defaultLanguageId` is defined by the system and `selectedLanguageId` can be dynamic depending on the context.

### CODE REVIEW

**Comment by diegonvs** [comment]
ci:test:sf

**Comment by diegonvs** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
Hey @diegonvs, I followed the reproduction steps before and after the changes and I still can reproduce the issue. Could you double check?

**Comment by jbalsas** [comment]
ci:forward

**Pull request closed without merging**
