### PR TITLE
LPS-129169 Some management toolbars do not display the stored display style

### PR DESCRIPTION
**Pull request by markocikos**
Fixes https://issues.liferay.com/browse/LPS-129169
- this issue is a splitoff from https://github.com/liferay-frontend/liferay-portal/pull/899. The bug was noticed in that ticket, but it was unrelated. See https://github.com/liferay-frontend/liferay-portal/pull/899#issuecomment-799295104
- this is somewhat the part 2 of [Make Display Style persist in multiple menus](https://github.com/brianchandotcom/liferay-portal/pull/98787), applying it to management toolbars.

@izaera @jbalsas @ealonso

The key change is that management toolbar needs to get the active display style from the same source as the rest of the page. Both need to use display contexts, that leverage the new utility. We added this in https://github.com/brianchandotcom/liferay-portal/pull/98787.

We have total of 146 management toolbars. 40 of them are updated in this PR. It was not possible to have a common solution in a base class, as the storage key is set in a display context, where both key and display context class are unique for each usage. Unfortunately our `*DisplayContext`s don't extend a base class, that would maybe make this PR easier.

These are the types of management toolbars that did **not** need to be updated:
- MTs with no display types
- MTs that implement `getViewTypeItems`. This attribute overrides the simpler `getDisplayViews` attribute and requires display style, so these are already using the value from context. These were the MTs that worked as expected from the ticket description, such as blogs.
- MTs with only one display type

Sample after the fix, there are too many to gif them all 
after

### CODE REVIEW

**Comment by markocikos** [comment]
Force-pushed to fix conflict, no changes.

**Comment by markocikos** [comment]
ci:test:sf

**Comment by markocikos** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
Hey @markocikos, this looks good to me, just one thought... many of these DC extend `SearchContainerManagementToolbarDisplayContext `. It feels like that could be a good place to at least concentrate some of the logic (taking the displayStyle key and handling it in a central way).

Could you take a look, see if that's feasible and if it simplifies the changes a bit? If it doesn't, then we can ping the teams involved and go ahead with this with their approval.

**Comment by markocikos** [comment]
> It feels like that could be a good place to at least concentrate some of the logic (taking the displayStyle key and handling it in a central way

@jbalsas The problem is that each usage has a different `*DisplayContext`. Not `*ManagementToolbarDisplayContext`, but page / module scope display context, from where we reading the display style. For example, in asset-browser-web, we are reading from [AssetBrowserDisplayContext](https://github.com/liferay/liferay-portal/blob/master/modules/apps/asset/asset-browser-web/src/main/java/com/liferay/asset/browser/web/internal/display/context/AssetBrowserDisplayContext.java#L185-L194). All these display contexts are POJOs, not extending anything. As I mentioned in opening comment, this task would maybe be simpler if they extended some base class. Then, we could extend base management toolbar to accept this generic display context, and place the getter for display style in it. The biggest issue here is that there are many many generic display contexts (`class .*DisplayContext` search in `*.java` files returns 749 results), and I suspect they vary greatly. I think it would be an epic-level undertaking to analyse this and create one or several base context types.

**Comment by jbalsas** [comment]
Hey @markocikos, yeah, makes sense... I was hoping we could do something around `SearchContainerManagementToolbarDisplayContext`. 

In my mind, it was something simpler, like taking a `String displayStyleKey` and performing the same operation we do in the other DCs... but in that case we'd also need to keep the implementation in sync, and this way we defer the `displayStyle` to one single place which feels more robust.

>  I think it would be an epic-level undertaking to analyse this and create one or several base context types

Let's keep this in mind... we might want to do something about this once the dust settles on the MT migration... 🤔 

@liferay-echo, @liferay-lima, @pei-jung, I think you're the most affected by this change... could you please take a look and see if this looks okay or you prefer us sending this over to your teams?

**Comment by markocikos** [comment]
> In my mind, it was something simpler, like taking a `String displayStyleKey` and performing the same operation we do in the other DCs... but in that case we'd also need to keep the implementation in sync, and this way we defer the `displayStyle` to one single place which feels more robust.

Yeah, that could work, but would probably not be ideal. Any change in how the key is defined from default, like for example we did in  https://github.com/liferay-frontend/liferay-portal/pull/899, would result in a bug in a seemingly unrelated place. Dev would need to know he needs to override the display style getter in the manager toolbar.

**Comment by 4lejandrito** [comment]
Hi! In representartion of @liferay-lima, I agree with you guys. It would be cool to unify this behaviour in the future, but for now the changes look 👍 .

Thanks!

**Comment by jbalsas** [comment]
ci:forward

**Comment by markocikos** [comment]
> I took a look and it is ok, I don't like really much the solution but it is not so bad

"This PR is not horrible" is about as good we can hope :joy:

**Pull request closed without merging**
