### PR TITLE
LPS-129051 Remove unneeded propsTransformer attribute

### PR DESCRIPTION
**Pull request by julien**
In [`22b0aff`](https://github.com/liferay/liferay-portal/commit/22b0aff696eff783ec4016c7942a3da853d9de16),we migrated `<clay:management-toolbar-v2 />` to
`<clay:management-toolbar />`, and introduced a bug:

The instances of the `<clay:management-toolbar />` tag in
[select_organization_role.jspf](https://github.com/liferay/liferay-portal/blob/aa7b7141b63ef4781020c31783b3cdd13fc883f0/modules/apps/roles/roles-admin-web/src/main/resources/META-INF/resources/select_organization_role.jspf) and [select_site_role.jspf](https://github.com/liferay/liferay-portal/blob/aa7b7141b63ef4781020c31783b3cdd13fc883f0/modules/apps/roles/roles-admin-web/src/main/resources/META-INF/resources/select_site_role.jspf)
don't need a `propsTransformer` attribute **and adding one will cause the
following JavaScript error** in the brower's console, when these JSPs are loaded:

```javascript
TypeError: Cannot read property 'deleteRolesURL' of undefined
    at Object.propsTransformer [as default] (ViewRolesManagementToolbarPropsTransformer.js:18)
```

This change fixes the JavaScript error.

**Before this change** (i.e. in `master` with [`aa7b714`](https://github.com/liferay/liferay-portal/commit/aa7b714))

*Pay attention to the browser's console in the .gif*

error-in-master

**With this change**:

However, even when reverting [these changes](https://github.com/liferay/liferay-portal/commit/22b0aff696eff783ec4016c7942a3da853d9de16), the search results
are still not shown correctly.

### CODE REVIEW

**Comment by julien** [comment]
cc @markocikos @ambrinchaudhary @jonmak08

**Review by ambrinchaudhary — APPROVED** [review]

**Review by markocikos — APPROVED** [review]
LGTM!

**Comment by markocikos** [comment]
A fix of a regression bug, CI green, reviews green.. pushing!

**Comment by markocikos** [comment]
ci:forward

**Pull request closed without merging**
