### PR TITLE
LPS-168731 Fix failing test FDSTable#HeadersCanBeLocalized

### PR DESCRIPTION
**Pull request by deborasoliveira**
**Description**
Due to the fail `Element is not present at "xpath=(//div[contains(@class, "dnd-tr")])[1]"`, I added a function to wait for the element to be present and fix the test. 

**JIRA TICKET**
https://issues.liferay.com/browse/LPS-168731

### CODE REVIEW

**Comment by deborasoliveira** [comment]
ci:test:frontend:nocompile

**Comment by deborasoliveira** [comment]
ci:test:frontend:nocompile

**Comment by eltonccdantas** [comment]
Hi @deborasoliveira , I've analyzed the errors and they look unrelated to your PR according to the [comparison run](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1668806453163&testrayRunIdA=2062447313&testrayRunIdB=2063792517). You may manually forward if no other dev review is needed.

**Comment by john-co** [comment]
ci:forward

**Comment by john-co** [comment]
Thanks @deborasoliveira ! Please monitor the test to see if the issue is fixed. I'm doubting if this will fix it but let's see what happens.

**Pull request closed without merging**
