### PR TITLE
LPS-195788 Adding tests to delete Actions.

### PR DESCRIPTION
**Pull request by JerryAdrianoo**
**Description:**
Adding tests to delete Actions.

**Jira Ticket:**
https://liferay.atlassian.net/browse/LPS-195788

### CODE REVIEW

**Comment by JerryAdrianoo** [comment]
ci:test:sf

**Comment by JerryAdrianoo** [comment]
ci:test:frontend

**Comment by JerryAdrianoo** [comment]
ci:test:frontend

**Comment by JerryAdrianoo** [comment]
ci:stop

**Comment by JerryAdrianoo** [comment]
ci:test:frontend

**Comment by JerryAdrianoo** [comment]
ci:test:frontend

**Comment by JerryAdrianoo** [comment]
afcb

**Comment by JerryAdrianoo** [comment]
ci:test:frontend

**Comment by JerryAdrianoo** [comment]
cc: @CarlosBrichete These failures are not related

**Review by CarlosBrichete — APPROVED** [review]
LGTM :)

**Comment by CarlosBrichete** [comment]
ci:forward

**Pull request closed without merging**
