### PR TITLE
LPS-121084 openSelectionModal sends the multiple parameter through the request

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
**Motivation:** 

Currently, we have a generic Item Selector View that will now support single and multiple selection (completed in [LPS-120838](https://issues.liferay.com/browse/LPS-120838)) But for that, we will need a flag to indicate whether it is multiple or not, as the view slightly changes.

Taking in mind that we also need a flag from the frontend size, the idea is to use that and send it to the views through the url (See commit https://github.com/liferay-lima/liferay-portal/pull/800/commits/a73803ccfd9f644fdaa206ceced28be422eb0aaa). 

The `p_p_id` parameter is needed because item selector's urls are friendly and don't include the portlet id, but the function `createPortletURL` needs it. 

**Note**: it would be nice to have this merged before the /dev/24 talk, we need it for the demo.

### CODE REVIEW

**Comment by jbalsas** [comment]
Hi @ambrinchaudhary, thanks for sending this over!

Could you please add a test plan if possible here so we know how to test this? I checked the LPS information and I couldn't find a test plan there. I think I can get the basic idea from your `motivation` description but a quick test would help clarify if we're indeed providing the expected functionality in the proper place.

Also, since we're getting close to the release... could you let us know what's the priority on this? Are you expecting it to make it into the release or can this wait?

**Comment by ambrinchaudhary** [comment]
Hi @jbalsas, 

as this is new, we do not have any usage yet on portal. But @4lejandrito gives a talk on /dev/24 about the item selector and we want to show that our generic view is valid for single and multiple selection. For that, we sent a pull to master (https://github.com/brianchandotcom/liferay-portal/pull/94338) to cover this, and [here](https://github.com/4lejandrito/liferay-pokemon-item-selector/pull/9) is the demo that is consuming that view for single and multiple selection. It would be great if we get this merged before the talk so our audience don't see that they need to do [this](https://github.com/4lejandrito/liferay-pokemon-item-selector/pull/9/commits/9caacb578c030566a993c9b362910dd472fb493c#diff-5855053c9494aaed616c3bcd073334a5R40) to get that working ;-)

**Comment by ambrinchaudhary** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
> as this is new, we do not have any usage yet on portal. But @4lejandrito gives a talk on /dev/24 about the item selector and we want to show that our generic view is valid for single and multiple selection. For that, we sent a pull to master (brianchandotcom#94338) to cover this, and here is the demo that is consuming that view for single and multiple selection. It would be great if we get this merged before the talk so our audience don't see that they need to do this to get that working ;-)

Thanks @ambrinchaudhary, those links help provide some important context!

I don't feel this is the right approach. We're now overriding a parameter in a very low-level primitive such as `openSelectionModal`. On top of that, we default to an `ItemSelector` value for `p_p_id` whose cascading effects are hard to predict.

I might be missing something, so please, bear with me while we try to figure this out:
- Is there a reason why we can't or wouldn't want to add the params when generating the URL in the backend at https://github.com/4lejandrito/liferay-pokemon-item-selector/blob/master/src/main/java/com/liferay/pokemon/item/selector/web/portlet/PokemonPortlet.java#L69?
- Have you tried using [addParams](https://github.com/liferay/liferay-portal/blob/master/modules/apps/frontend-js/frontend-js-web/src/main/resources/META-INF/resources/liferay/util/add_params.js) [instead of createPortletURL](https://github.com/4lejandrito/liferay-pokemon-item-selector/pull/9/commits/9caacb578c030566a993c9b362910dd472fb493c#diff-5855053c9494aaed616c3bcd073334a5R40)

**Comment by ambrinchaudhary** [comment]
Hi @jbalsas, sorry for my late reply:

> Is there a reason why we can't or wouldn't want to add the params when generating the URL in the backend inside PokemonPortlet?

That was our first approach, to set the multiple option in the backend. But is the front who decides if the selector is multiple or not, so backend views should be independent and receive somehow the “front” decision. This also facilitates from the developer point of view and helps avoiding inconsistencies. 

> Have you tried using addParams instead of createPortletURL

Yes, @4lejadrito tried it and and myself to be sure and it also needs a portletId. Not sure which one is better here... Anyway, I see what you mean… As far as I remember, `openSelectorModal` replaces the `ItemSelectorDialog`, so there is a real connection between that p_p_id. In addition, I don’t think that a frontend person needs to know what `p_p_id` is for and which value has to pass it, that is the reason for setting a default value.

> How standard is the multipleSelection param? How can we know we always want it in the URL and it always has that name?

Well, we want it to be standard from now. For all the item selector’s modals will be useful and will always be set if this changes are merged. That param will be there for whoever needs it, but could also be ignored.

**Comment by jbalsas** [comment]
> As far as I remember, openSelectorModal replaces the ItemSelectorDialog, so there is a real connection between that p_p_id

In fact, it replaced as many [`Liferay.Util.selectEntity`](https://github.com/liferay-frontend/liferay-portal/pull/263/commits/36eaf38c0f81c7ed358e4d72d56eee80bd289c2a) occurrences as it did [`ItemSelectorDialog`](https://github.com/liferay-frontend/liferay-portal/pull/263/commits/45526eab038e8a585e0243cc9cfc819fc0b6f43d) ones.

> Yes, @4lejandrito tried it and and myself to be sure and it also needs a portletId. 

Yes, that's what I'd expect. The thing is, it's only when initiating the `open` action that you know what `portlet` the URL belongs to. In this case, inside the "Pokemon" portlet you actually want the "ItemSelector" portletId. This knowledge feels like a very specific implementation detail of how the selection view in the Pokemon view has been implemented.

> I don’t think that a frontend person needs to know what p_p_id is for and which value has to pass it

I 80% agree with this :)

> The p_p_id parameter is needed because item selector's urls are friendly and don't include the portlet id, but the function createPortletURL needs it

You can use `addParams` for this but you still need to namespace the param because that's how portlet params work. We have global params and portlet namespaced params... so you need to know the portletId to namespace your params if you want to dynamically add them. That's why `createPortletURL` requires it (because you're adding portlet params). The `addParams` utility let's you freely construct the URL, but because your portlet (ItemSelctor) needs to read them, you still need to namespace it.

There are still some parts of the system that don't quite click in my mind. Could you please verify if the following understanding of the situation is correct?
- The backend generates a friendly ItemSelectorURL
- The ItemSelectorURL has **no queryParams** and no **p_p_id**
- We dynamically want to append the "multiple" query parameter
- The "multiple" query param needs to be namespaced because otherwise we can't retrieve it

What I don't understand is:
- How are the other params (criterion, returnType...) being passed?
- It's okay that after the addition of params the URL is unfriendly-ish?

Assuming most of this is correct, my suggestion would be to do offer a `createItemSelectorURL` utility to encapsulate this and future ItemSelector URL transformations we might need. That way, we could have something like:

```autocomplete
import {DefaultEventHandler, openSelectionModal} from 'frontend-js-web';
import {createItemSelectorURL} from 'item-selector-web';

const Pokemon = ({eventName, itemSelectorURL}) => {
	const [multiple, setMultiple] = useState(false);

	return (
		<Fragment>
			<ClayButton
				onClick={() =>
					openSelectionModal({
						...
						url: createItemSelectorURL(itemSelectorURL, {
							multipleSelection: multiple,
						}),
						multiple,
					})
				}
			>
				{Liferay.Language.get('select-a-pokemon')}
			</ClayButton>
		</Fragment>

		...     
	);
};
```

This would give you freedom to control the `createItemSelectorURL`. You can decide if you want free param maps like the `createPortletURL` or a more controlled, builder-type utility that only supports real ItemSelector capabilities (or both).

Do you think this would make sense?

**Comment by ambrinchaudhary** [comment]
Hi @jbalsas, 

makes sense what you said. As we have spoken by slack, what we would prefer is to have an `openItemSelectorModal` in the _item-selector-web_ module that will add that "multipleSelection" param to the url and call later to your `openSelectionModal`. 

Thanks for your help!

**Comment by jbalsas** [comment]
Sounds good to me! Thanks for working this out with us! ❤️

**Comment by ambrinchaudhary** [comment]
See https://github.com/liferay-lima/liferay-portal/pull/811

**Pull request closed without merging**
