### PR TITLE
LPS-121912 Migrate v2 usages in site/site-memberships-web

### PR DESCRIPTION
**Pull request by julien**
The <clay:management-toolbar-v2 /> tag has been replaced with the
<clay:management-toolbar /> tag (which uses clay v3).

Managing site memberships should work as expected.

**Test plan**:
- Navigate to **People**>**Memberships**
- Assert that you can add and delete a user
- Assert that you can asign one or several roles to a user
- Assert that you can add and delete and organization
- Assert that you can asign one or several roles to an organization
- Assert that you can create and delete a user group
- Assert that you can asign one or several roles to a user group

**Additional notes**:
Submitting this as a draft so that @markocikos, @ambrinchaudhary and @jonmak08 can review before forwarding

### CODE REVIEW

**Review by markocikos — COMMENTED** [review]
@julien The code LGTM! Can we safely remove trailing `*ManagementToolbarDefaultEventHandler`s?

**Comment by julien** [comment]
@markocikos yes, good point. Let me get rid of those.

**Comment by julien** [comment]
@markocikos done in [https://github.com/liferay-frontend/liferay-portal/pull/825/commits/220286c4a58f3975838b73737ecdc41b89162454](https://github.com/liferay-frontend/liferay-portal/pull/825/commits/220286c4a58f3975838b73737ecdc41b89162454), I also got rid of some default event handlers used by cards.

**Comment by julien** [comment]
ci:test:sf

**Comment by julien** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
LGTM!

**Review by markocikos — APPROVED** [review]
LGTM!

**Comment by wincent** [comment]
Given prior reviews and green CI, going to try a forward.

**Comment by wincent** [comment]
ci:forward

**Pull request closed without merging**
