### PR TITLE
LPS-136502 add overflow to alert messages in editors to avoid overlapping

### PR DESCRIPTION
**Pull request by antonio-ortega**
[Original explanation](https://github.com/antonio-ortega/liferay-portal/pull/159#issue-703731767) from @orsolyaDekany 

> The issue is that when an alert message is inserted below an image in CKEditor and AlloyEditor, and we set the image to float to the right or left (none is the default), the message is going to overlap the image.
> LPS: https://issues.liferay.com/browse/LPS-136502
> 
image
> Root cause: the image is positioned with the float property, that allows the block element (Clay alert messages) to overlap
> overlap ckeditor
> 
> Fix: add overflow-auto class to the elements in the editors modules. I was a bit hesitating to choose other solutions as changing the display type of the div from block to flexbox give a clear property to Alerts in Clay for instance. I am not sure which would be the better option here.
> overflow
> 
image
> Please review it and let me know your opinion.

### CODE REVIEW

**Comment by carloslancha** [comment]
@marcoscv-work @edalgrin could you please take a look?

**Review by edalgrin — APPROVED** [review]
I tried the solution and it actually works very well, LGTM!

**Comment by edalgrin** [comment]
ci:stop

**Comment by edalgrin** [comment]
Just started reviewing :)

**Comment by edalgrin** [comment]
Trying to run the test here https://github.com/liferay-frontend/liferay-portal/pull/1335 if it's a CI problem I will stop it and resume this PR

**Comment by nhpatt** [comment]
ci:forward

**Comment by nhpatt** [comment]
Oh heavens, CI...

**Comment by nhpatt** [comment]
ci:test:sf

**Comment by edalgrin** [comment]
ci:forward

**Pull request closed without merging**
