### PR TITLE
LPD-32049 Make SPA style application synchronous based on a configuration flag (II)

### PR DESCRIPTION
**Pull request by dsanz**
Continuation of https://github.com/liferay-frontend/liferay-portal/pull/4338. 

In this PR we switch the order between `evaluateStyles()` and `flip()` depending on the new `preloadCSS` setting. This minimizes the FUOC on the target navigation page, at the cost of a minimal flicker before leaving the source page, which is intended as long as `preloadCSS` configuration is set.

This change is particularly noticeable when slow device is simlulated and we force browser to not caching styles

To illustrate, this is how a navigation with preload-css off looks like
[preload-css-off-2024-07-30_20.18.32.webm](https://github.com/user-attachments/assets/d5a3eb25-fe85-4e5b-96dd-bf4a2c8d36d2)

In contrast, preload-css on makes things more natural as fuoc is reduced:
[before-change-preload-css-on-2024-07-30_20.20.31.webm](https://github.com/user-attachments/assets/535393da-f8dc-46e1-a3b7-939f79b04956)

After the last commit, we evaluate styles before flipping pages so there is a small flicker before leaving the page but when new page is rendered, there is no fuoc at all:
[after-change-preload-css-on-2024-07-30_20.15.45.webm](https://github.com/user-attachments/assets/71034820-6452-45e9-a6c0-9d3fb01d06eb)

cc @markocikos @izaera

### CODE REVIEW

**Comment by dsanz** [comment]
ci:test:relevant

**Comment by dsanz** [comment]
ci:test:sf

**Comment by dsanz** [comment]
ci:forward

**Comment by dsanz** [comment]
ci:test:relevant

**Comment by dsanz** [comment]
ci:test:stable

**Comment by dsanz** [comment]
ci:test:sf

**Comment by dsanz** [comment]
ci:test:relevant

**Comment by dsanz** [comment]
ci:test:stable

**Review by markocikos — APPROVED** [review]
@dsanz LGTM! :sparkles:

**Comment by dsanz** [comment]
ci:forward

**Pull request closed without merging**
