### PR TITLE
LPS-164820 | Add FDSCustomView file.

### PR DESCRIPTION
**Pull request by mateusralv**
Background:
Add FDSCustomView file for automated testings 

JIRA Link:
https://issues.liferay.com/browse/LPS-164820

### CODE REVIEW

**Comment by mateusralv** [comment]
ci:test:sf

**Comment by mateusralv** [comment]
ci:test:sf

**Comment by john-co** [comment]
ci:test:sf

**Comment by john-co** [comment]
Looks good to me! :sunglasses:

**Comment by john-co** [comment]
ci:forward

**Pull request closed without merging**
