### PR TITLE
LPD-20683 - Fix flaky Data Set creation test

### PR DESCRIPTION
**Pull request by juanjofgliferay**
## Bug
https://liferay.atlassian.net/browse/LPD-20683

## Issue
Data Set tests fail randomly among different runs.

## Solution
Ensure that we wait for the response to update the UI and we are able to continue with Data Set checks.

Ensure that tests run consistent (success) several times using `--repeat-each=N` independently 
- `npx playwright test tests/frontend-data-set-views-web/dataSets.spec.ts --repeat-each=12` 
- `npx playwright test tests/frontend-data-set-views-web/ --repeat-each=3`

### CODE REVIEW

**Comment by juanjofgliferay** [comment]
ci:test:playwright

**Comment by markocikos** [comment]
ci:test:playwright

**Comment by markocikos** [comment]
False positive playwright test in https://github.com/liferay-frontend/liferay-portal/pull/4076#issuecomment-2008930071, see https://liferay.slack.com/archives/C06A59K5D46/p1710899860256679

**Comment by juanjofgliferay** [comment]
> False positive playwright test in [#4076 (comment)](https://github.com/liferay-frontend/liferay-portal/pull/4076#issuecomment-2008930071), see https://liferay.slack.com/archives/C06A59K5D46/p1710899860256679

I was expecting some kind of error due to CI reset https://liferay.slack.com/archives/C19PWQ74J/p1710863872882549

**Comment by juanjofgliferay** [comment]
ci:test:playwright

**Comment by juanjofgliferay** [comment]
ci:test:playwright

**Comment by juanjofgliferay** [comment]
Data Set creation tests were successful -> https://testray.liferay.com/reports/production/logs/2024-03/test-1-33/test-portal-acceptance-pullrequest(master)/5387/playwright-js-tomcat90-mysql57-jdk8/13/0/playwright-report/index.html

**Comment by juanjofgliferay** [comment]
ci:forward

**Pull request closed without merging**
