### PR TITLE
[7.4-only] LPS-102111 Remove sidebar compat layer

### PR DESCRIPTION
**Pull request by pat270**
From #564 /cc @zhangyan0701 @john-co @marcoscv-work 
https://issues.liferay.com/browse/LPS-102111

This is from PR #524 with the fix of the tests and rebased.

### CODE REVIEW

**Comment by john-co** [comment]
ci:test:sf

**Comment by john-co** [comment]
ci:test:relevant

**Comment by marcoscv-work** [comment]
LGTM!! forward! :-D

**Comment by john-co** [comment]
Looks like a fluke. cc/ @david-gutierrez-mesa maybe you can take a closer look?

I suspect this is a pre-existing flaky issue with asserting modals being present similar to the issue from previous PR: https://github.com/liferay-frontend/liferay-portal/pull/564#issuecomment-735803881
Also seen in a different [PR](https://testray.liferay.com/home/-/testray/case_results/1345535305?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcases%2F1310751361%2Fview%3FtestrayCaseId%3D1310751361%26cur%3D2%26delta%3D200%26orderByCol%3DcreateDate_sortable%26orderByType%3Ddesc%26resetCur%3Dfalse)

**Comment by john-co** [comment]
ci:forward

**Comment by john-co** [comment]
ci:forward

**Comment by john-co** [comment]
ci:test:bundle

**Comment by john-co** [comment]
ci:test:relevant

**Comment by john-co** [comment]
cc/ @zhangyan0701 @PablitoBonito , can one of you please analyze the failing webcontent test? This is two times in a row now this failure occured for this PR. If it's not related, please forward to BChan.

**Comment by john-co** [comment]
going to manually forward, we're running into way too many flaky tests here...

**Comment by john-co** [comment]
manually forwarded in https://github.com/brianchandotcom/liferay-portal/pull/96511

**Pull request closed without merging**
