### PR TITLE
[7.4-only] LPS-102104 LPS-125194 Remove $compat-navbar and $compat-basic-search

### PR DESCRIPTION
**Pull request by pat270**
https://issues.liferay.com/browse/LPS-102104
https://issues.liferay.com/browse/LPS-125194

This PR depends on #588. The classes `nav-link` and `nav-item` are added on the tag `aui:nav-item` there.

- Styled Theme removes compat navbar and compat basic-search
- liferay-ui:input-search updates input-group markup to Clay 3 and removes basic-search markup from lexicon view
- aui:nav-bar remove replace Clay 1 classes with Clay 3
   - removes Clay 1 class navbar-default
   - replace Clay 1 class navbar-toggle-left navbar-toggle-page-name with navbar-toggler navbar-toggler-link
   - use c-inner on toggler button to prevent focus outline on click
   - replace fontawesome icon with aui:icon
   - removes Clay 1 navbar-header element
- aui:nav lexicon view adds Liferay.MenuToggle to open and close collapsed navigation in mobile since we don't include Bootstrap 4 js by default
- aui:nav-item update markup to Clay 3
   - replaces Clay 1 class nav-item-label with navbar-text-truncate
   - use c-inner pattern for anchor tag
- liferay-ui:search-toggle lexicon and default view update markup to Clay 3
   - use Clay 3 input-group pattern
   - replace font awesome icons with Clay 3 svg icons
   - remove Clay 1 basic-search class
- Update markup in modules that use `aui:nav-bar` to use Clay 3 classes
    - Calendar
    - Export Import
    - Portal Workflow Kaleo
    - Staging
- Removes Clay 1 basic search pattern and replace with Clay 3 input-group pattern
   - Web Content
   - site-navigation-item-selector-web
   - Message Boards
- archived mail-reader-web
   - didn't touch this since it's not in use?

### CODE REVIEW

**Comment by pat270** [comment]
ci:test:sft

**Comment by pat270** [comment]
ci:test:sf

**Comment by pat270** [comment]
ci:test:relevant

**Comment by marcoscv-work** [comment]
@pat270 do you need to update more navbars? or is it ok? :-D

**Comment by pat270** [comment]
@marcoscv-work I need to work on this one a little bit more. I'll update it today.

**Comment by pat270** [comment]
ci:test:sf

**Comment by pat270** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
Hey @edalgrin, do you think this is good to go?

**Comment by edalgrin** [comment]
> Hey @edalgrin, do you think this is good to go?

From the code yes, but I didn't try it yet so not 100% 🤷‍♀️

**Comment by jbalsas** [comment]
ci:forward

**Comment by pat270** [comment]
ci:forward

**Comment by pat270** [comment]
@john-co @PablitoBonito @zhangyan0701 I think the unique failures:

1) related to commit https://github.com/liferay-frontend/liferay-portal/pull/618/commits/faf88cfed57036552886e676557efcf575916e24. I removed `navbar` and turned it into an `input-group`.

2) Seems unrelated, but I have no idea 🤷‍♂️ .

**Comment by john-co** [comment]
@zhangyan0701, @PablitoBonito please take a look and verify.

**Comment by john-co** [comment]
ci:test:bundle

**Comment by zhangyan0701** [comment]
**LocalFile.WebContentTemplates#CannotAddTemplateWhenDisableTemplateCreation**

Wasn't able to reproduce locally, seems like a fluke, the web content portlet was uninstalled somehow.

**MailboxUtilTest.testDepositMailWithReaperThreadEnabled**

Seems unrelated. But not sure about this neither.

So I will re-run test to see if they will fail again.

**Comment by zhangyan0701** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
ci:stop

**Comment by zhangyan0701** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
The new results should be unrelated, not just happen in this PR.

**Comment by pat270** [comment]
@john-co Just fixed the conflicts right now.

**Comment by john-co** [comment]
ci:forward

**Comment by john-co** [comment]
Reviewed. Test failures are unrelated. :heavy_check_mark: 

Forwarded manually to https://github.com/brianchandotcom/liferay-portal/pull/97415

**Comment by john-co** [comment]
[Testray Results](https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=1394720147)

- Forms test failures are flaky
- Web Content and workflow tests seem like they just recently failed on upstream
- Upgrade test seems like a ci network connection issue

cc/ @cvanut @david-gutierrez-mesa @rodrigocunhaa

**Comment by pat270** [comment]
Looks like it was merged. Closing.

**Pull request closed without merging**
