### PR TITLE
COMMERCE-5035 Fix broken redirect from modals [SAFE TO BACKPORT]

### PR DESCRIPTION
**Pull request by wincent**
Since dropping support for IE from our build in [LPS-121753](https://issues.liferay.com/browse/LPS-121753), things like object concise method syntax are passing through to the browser without being transpiled; eg.

```js
Liferay.PortletURL = {
    createActionURL() {}
}
```

Used to be transpiled to something like:

```js
Liferay.PortletURL = {
    createActionURL: function createActionURL() {}
}
```

Which you could call like this:

```js
new Liferay.PortletURL.createActionURL()
```

After the build changes, trying to use the `new` operator in this way will result in error about `createActionURL()` not being a constructor, because concise methods cannot be used as constructors.

Seeing as we don't want to break the API, the fix is to write these without using concise method syntax.

FWIW, I think it is a smell that we have functions (like `createActionURL()`) that are used as constructors when really they're just functions, but like I said, we don't want to break APIs, so it will have to stay this way.

### CODE REVIEW

**Comment by wincent** [comment]
cc @FabioDiegoMastrorilli @marco-leo @jbalsas

Can you verify that this fixes the problem for you?

**Comment by wincent** [comment]
@john-co @PablitoBonito This one is an interesting one because it didn't get caught by `ci:test:relevant` in the original PR (https://github.com/liferay-frontend/liferay-portal/pull/447).

Anyway, going to kick off the tests now.

**Comment by wincent** [comment]
ci:test:sf

**Comment by wincent** [comment]
ci:test:relevant

**Comment by wincent** [comment]
ci:test:bundle

**Comment by wincent** [comment]
ci:test:commerce

**Comment by john-co** [comment]
> @john-co @PablitoBonito This one is an interesting one because it didn't get caught by `ci:test:relevant` in the original PR (#447).
> 
> Anyway, going to kick off the tests now.

@iovaneale , please let us know if there is already a ci test to cover this in commerce.

**Comment by wincent** [comment]
Won't bother waiting for `ci:test:commerce` results, as this seems worth getting a fix in quickly.

**Comment by wincent** [comment]
ci:forward

**Review by julien — APPROVED** [review]

**Comment by john-co** [comment]
I didn't see any functional test cases run in ci:test:commerce, is that supposed to be the case @iovaneale?

**Comment by iovaneale** [comment]
@john-co ATM yes, they are not running on CI. We are working on making them stable and remove them from quarantine.

**Comment by marco-leo** [comment]
@FabioDiegoMastrorilli  can we please update our code to don't use those functions as constructor even if now is again possible, I am understanding is the wrong way. So let's fix it in the internal usage at least.

**Comment by jbalsas** [comment]
The right move would be to move all those usages to the new [`portlet_url`](https://github.com/liferay/liferay-portal/tree/master/modules/apps/frontend-js/frontend-js-web/test/liferay/util/portlet_url) APIs we introduced in `7.3`.

As you can see those are plain functions and can be both consumed from JSPs or imported from JS.

We applied them globally in all DXP codebase as part of [Modernize major Javascript utilities](https://issues.liferay.com/browse/LPS-94620) before Commere was in `master`. This explains why mostly Commerce has been the only one affected, because it's the only app still using it 😢

**Comment by wincent** [comment]
@FabioDiegoMastrorilli, @marco-leo, @jbalsas: FWIW, Brian asked about whether we can lint for this and [I told him](https://github.com/brianchandotcom/liferay-portal/pull/95472#issuecomment-719422633) that: (a) it's not cheaply feasible or worth it yet; and (b) Commerce knows about the more modern APIs now.

**Pull request closed without merging**
