### PR TITLE
LPD-21228 & LPD-22034

### PR DESCRIPTION
**Pull request by dsanz**
This PR is a followup of both https://github.com/liferay-frontend/liferay-portal/pull/4109 and https://github.com/liferay-frontend/liferay-portal/pull/4090 (which I've closed), so, it includes:

**From LPD-21228 (already reviewed)**

- The `sticker` field has been removed for mapping, so we need to remove the blue sticker icon from the Cards markup.
- This PR includes the refactor made in https://github.com/liferay-frontend/liferay-portal/pull/4046 of [Cards.js](https://github.com/liferay-frontend/liferay-portal/pull/modules/apps/frontend-data-set/frontend-data-set-web/src/main/resources/META-INF/resources/views/cards/Cards.js) to buld the solution in top of it to prevent further merge conflicts.

**From LPD-22034**

- Changes mentioned in https://github.com/liferay-frontend/liferay-portal/pull/4109 have been added on top of `Cards.tsx` once migrated to TS in previous commits
- In addition, `onActionDropdownItemClick` logic on card action click handler has been removed as it's redundant, already managed by the general-purpose handler function added in this PR
- As a bonus, Card empty state has been deleted, along with all the other FDS views empty states as this is now managed from the top-level FDS component. @markocikos I've left `overrideEmptyResultView` parameter as we need to review the top-level API more thoroughly and this PR already has a lot

### CODE REVIEW

**Comment by dsanz** [comment]
ci:test:relevant

**Review by juanjofgliferay — APPROVED** [review]
LGTM :raised_hands:

**Review by chestofwonders — APPROVED** [review]
Code ported are fine, LGTM! ✨

**Comment by dsanz** [comment]
looks like `frontend-data-set` suite is consistently failing at some tests. We can address this later as it's poshi stuff we anyways have to review.

**Comment by dsanz** [comment]
ci:stop

**Comment by dsanz** [comment]
ci:test:relevant

**Comment by markocikos** [comment]
> looks like frontend-data-set suite is consistently failing at some tests. We can address this later as it's poshi stuff we anyways have to review

Should be better after https://github.com/liferay-frontend/liferay-portal/pull/4088 is merged

**Review by markocikos — APPROVED** [review]
@dsanz LGTM! The failures in https://github.com/liferay-frontend/liferay-portal/pull/4110#issuecomment-2038202548 are unrelated

**Comment by markocikos** [comment]
ci:forward:force

**Pull request closed without merging**
