### PR TITLE
LPS-120077 Remove uppercase transform to virtual instance

### PR DESCRIPTION
**Pull request by carloslancha**
https://issues.liferay.com/browse/LPS-120077

Virtual Instance was not meant to be transformed to uppercase, so we're removing that from the styles.

image

### CODE REVIEW

**Comment by carloslancha** [comment]
ci:test:sf

**Comment by carloslancha** [comment]
ci:test:relevant

**Comment by jpince** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
ci:forward

**Pull request closed without merging**
