### PR TITLE
[TECHNICAL SUPPORT] LPS-177707 When Toggle Controls is off, portlet-topper is still displayed in the DOM and blocks some userInteraction

### PR DESCRIPTION
**Pull request by NemethNorbert**
Hey,

[LPS-177707](https://issues.liferay.com/browse/LPS-177707)
Based on the answer I got in [PTR-3736](https://issues.liferay.com/browse/PTR-3736), I fixed the issue of portlet-topper blocking user interactions in case the Toggle Controls is off.

Please review my changes

### CODE REVIEW

**Comment by mateusralv** [comment]
I'm on it 🕵🏽

**Comment by mateusralv** [comment]
Hi @NemethNorbert The failures are not related! 

[Testray comparison](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1678390181416&testrayRunIdA=2223606242&testrayRunIdB=2223638208)

**Comment by NemethNorbert** [comment]
Hey @liferay-frontend ,

Can you review and forward the PR if you agree with my changes?

Thanks

**Comment by bryceosterhaus** [comment]
LGTM!

**Comment by NemethNorbert** [comment]
> LGTM!

Can you forward the PR, please?

**Comment by markocikos** [comment]
ci:forward

**Pull request closed without merging**
