### PR TITLE
LPD-19659 Make favicon sample cacheable forever

### PR DESCRIPTION
**Pull request by izaera**

### CODE REVIEW

**Comment by izaera** [comment]
ci:test:relevant

**Comment by izaera** [comment]
CI errors are not related.

**Review by bryceosterhaus — APPROVED** [review]
Not a huge fan of having to do custom gradle tasks, but 🤷  not sure there is anything better

**Comment by izaera** [comment]
>Not a huge fan of having to do custom gradle tasks, but 🤷 not sure there is anything better

The other option would be a npm script, but that would introduce a new dependency since gradle it's already there, but npm is not. So I preferred to implement it in gradle due to how simple the solution is and the fact that this kind of project won't probably get more complex in the future (since it's just a favicon, what else can we possibly add to this CX? :shrug: ).

**Comment by izaera** [comment]
ci:forward:force

**Pull request closed without merging**
