### PR TITLE
LPS-186758 Reintroduce Migrate frontend-taglib-chart to ESM after rollback in LPS-186698 (PART 1)

### PR DESCRIPTION
**Pull request by izaera**
This is the first part of the whole feature. It is just a refactor of the part that renders ESM imports in react renderer so that it can be used later from recharts (in part 2).

This PR adds nothing to DXP so there's no need for QA. We only need that it doesn't break anything :crossed_fingers:

### CODE REVIEW

**Comment by izaera** [comment]
ci:test:relevant

**Comment by izaera** [comment]
ci:test:relevant

**Comment by izaera** [comment]
ci:test:relevant

**Comment by mateusralv** [comment]
I'm on it 🕵🏽

**Comment by mateusralv** [comment]
Oops I saw that no QA review was required.

**Comment by izaera** [comment]
ci:test:relevant

**Comment by izaera** [comment]
ci:forward

**Pull request closed without merging**
