### PR TITLE
LPS-197328 Testfix ClientExtension#ErrorAppearsWhenHTMLBlank

### PR DESCRIPTION
**Pull request by JerryAdrianoo**
**Description:**
Changing old error message.

**Jira Ticket:**
https://liferay.atlassian.net/browse/LPS-197328

### CODE REVIEW

**Comment by JerryAdrianoo** [comment]
ci:test:frontend-data-set

**Comment by JerryAdrianoo** [comment]
@CarlosBrichete these failures are not related 😄

**Review by CarlosBrichete — APPROVED** [review]
LGTM

**Comment by JerryAdrianoo** [comment]
ci:forward

**Pull request closed without merging**
