### PR TITLE
LPS-168440 - Remove moment.js in favor of date-fns

### PR DESCRIPTION
**Pull request by bryceosterhaus**
checking CI again

### CODE REVIEW

**Comment by bryceosterhaus** [comment]
I can't seem to figure out why this is breaking in CI but locally it builds fine

**Comment by bryceosterhaus** [comment]
ci:test:sf

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
@mateusralv could you take a look at these failures? I see the JS unit ones, but wasn't sure about the poshi ones

**Comment by eltonccdantas** [comment]
I'll take a look at it for you, @bryceosterhaus

**Comment by mateusralv** [comment]
Hi Bryce, sorry for delay, I'll take a look tomorrow morning and return the results as soon as possible

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by mateusralv** [comment]
I'm taking a look 🕵️‍♀️

**Comment by mateusralv** [comment]
Hi @bryceosterhaus, The number of unique failures reduced, now +480. The `js-unit-jdk8/0/0 ` module keeps returning errors similar to the ones before, could take a look? 
```
 [exec]     [36m</body>[39m
     [exec] 
     [exec]       69 | 		);
     [exec]       70 | 
     [exec]     > 71 | 		expect(getByText('12/20/2020')).toBeTruthy();
     [exec]          | 		       ^
     [exec]       72 | 	});
     [exec]       73 | 
     [exec]       74 | 	it('renders dates in the portuguese BR format', () => {
     [exec] 
     [exec]       at Object.getElementError (../../../node_modules/@testing-library/dom/dist/config.js:38:19)
     [exec]       at ../../../node_modules/@testing-library/dom/dist/query-helpers.js:90:38
     [exec]       at ../../../node_modules/@testing-library/dom/dist/query-helpers.js:62:17
     [exec]       at getByText (../../../node_modules/@testing-library/dom/dist/query-helpers.js:111:19)
     [exec]       at Object.<anonymous> (test/js/custom/form-report/components/list/List.js:71:10)
     [exec]       at processTicksAndRejections (node:internal/process/task_queues:96:5)

...

[exec]       79 | 		);
     [exec]       80 | 
     [exec]     > 81 | 		expect(getByText('20/12/2020')).toBeTruthy();
     [exec]          | 		       ^
     [exec]       82 | 
     [exec]       83 | 		setDefaultOptions({locale: enUS});
     [exec]       84 | 	});
     [exec] 
     [exec]       at Object.getElementError (../../../node_modules/@testing-library/dom/dist/config.js:38:19)
     [exec]       at ../../../node_modules/@testing-library/dom/dist/query-helpers.js:90:38
     [exec]       at ../../../node_modules/@testing-library/dom/dist/query-helpers.js:62:17
     [exec]       at getByText (../../../node_modules/@testing-library/dom/dist/query-helpers.js:111:19)
     [exec]       at Object.<anonymous> (test/js/custom/form-report/components/list/List.js:81:10)
     [exec]       at processTicksAndRejections (node:internal/process/task_queues:96:5)

...

 [exec] 
     [exec]       89 | 		);
     [exec]       90 | 
     [exec]     > 91 | 		expect(getByText('12/20/2020 2:48 PM')).toBeTruthy();
     [exec]          | 		       ^
     [exec]       92 | 	});
     [exec]       93 | 
     [exec]       94 | 	it('renders dates and time in the japanese format', () => {
     [exec] 
     [exec]       at Object.getElementError (../../../node_modules/@testing-library/dom/dist/config.js:38:19)
     [exec]       at ../../../node_modules/@testing-library/dom/dist/query-helpers.js:90:38
     [exec]       at ../../../node_modules/@testing-library/dom/dist/query-helpers.js:62:17
     [exec]       at getByText (../../../node_modules/@testing-library/dom/dist/query-helpers.js:111:19)
     [exec]       at Object.<anonymous> (test/js/custom/form-report/components/list/List.js:91:10)
     [exec]       at processTicksAndRejections (node:internal/process/task_queues:96:5)

...

[exec] > Task :apps:data-engine:data-engine-taglib:packageRunTest
     [exec] PASS test/js/data-layout-builder/components/rules/editor/Editor.es.js (38.984s)
     [exec]   ��� Console
     [exec] 
     [exec]     console.error ../../../node_modules/warning/warning.js:34
     [exec]       Warning: Button Accessibility: Component has only the Icon declared. Define an `aria-label` or `aria-labelledby` attribute that labels the interactive button that screen readers can read. The `title` attribute is optional but consult your design team.

...

[exec]   ��� Console
     [exec] 
     [exec]     console.error ../../../node_modules/prop-types/checkPropTypes.js:20
     [exec]       Warning: Failed prop type: You provided a `value` prop to a form field without an `onChange` handler. This will render a read-only field. If the field should be mutable use `defaultValue`. Otherwise, set either `onChange` or `readOnly`.
     [exec]           in input (created by ClayInput)

...

[exec]   ��� The time range filter component should ��� Render with custom date range option selected and ��� Show the date the href has as a suggestion
     [exec] 
     [exec]     expect(received).toEqual(expected) // deep equality
     [exec] 
     [exec]     Expected: "12/03/2019"
     [exec]     Received: "12/02/2019"
     [exec] 
     [exec]       106 | 			dateEndInput = document.querySelectorAll('.form-control')[1];
     [exec]       107 | 
     [exec]     > 108 | 			expect(dateStartInput.value).toEqual('12/03/2019');
     [exec]           | 			                             ^
     [exec]       109 | 			expect(dateEndInput.value).toEqual('12/09/2019');
     [exec]       110 | 		});
     [exec]       111 | 
     [exec] 
     [exec]       at Object.<anonymous> (test/components/filter/TimeRangeFilter.es.js:108:33)
     [exec]       at processTicksAndRejections (node:internal/process/task_queues:96:5)
     [exec] 
     [exec] PASS test/components/process-metrics/workload-by-assignee-card/WorkloadByAssigneeCardBody.es.js (9.939s)
     [exec] PASS test/components/instance-list-page/modal/reassign/single/SingleReassignModal.es.js (5.082s)

...

[exec]     expect(element).toHaveTextContent()
     [exec] 
     [exec]     Expected element to have text content:
     [exec]       Jan 24, 2020, 2:08 PM (0d 3h 43min overdue)
     [exec]     Received:
     [exec]       Update Jan 24, 2020, 2:08 AM (0d 3h 43min overdue)
     [exec] 
     [exec]       118 | 
     [exec]       119 | 			expect(getByText('OPEN (1)')).toBeTruthy();
     [exec]     > 120 | 			expect(resultStatus[0]).toHaveTextContent(
     [exec]           | 			                        ^
     [exec]       121 | 				'Jan 24, 2020, 2:08 PM (0d 3h 43min overdue)'
     [exec]       122 | 			);
     [exec]       123 | 			expect(resultIcons[1].children[0].classList).toContain(
     [exec] 
     [exec]       at Object.<anonymous> (test/components/instance-list-page/modal/instance-details/InstanceDetailsModal.es.js:120:28)
     [exec] 
     [exec]   ��� The InstanceDetailsModal component should ��� render with a completed Instance ��� Render Process details with correct infos
     [exec] 
     [exec]     expect(element).toHaveTextContent()
     [exec] 
     [exec]     Expected element to have text content:
     [exec]       Jan 20, 2020, 3:08 PM
     [exec]     Received:
     [exec]       creation-dateJan 20, 2020, 3:08 AM
     [exec] 
     [exec]       137 | 			expect(instanceDetailsRows[0]).toHaveTextContent('completed');
     [exec]       138 | 			expect(instanceDetailsRows[1]).toHaveTextContent('Test Test');
     [exec]     > 139 | 			expect(instanceDetailsRows[2]).toHaveTextContent(
     [exec]           | 			                               ^
     [exec]       140 | 				'Jan 20, 2020, 3:08 PM'
     [exec]       141 | 			);
     [exec]       142 | 			expect(instanceDetailsRows[3]).toHaveTextContent('Blogs Entry');
     [exec] 
     [exec]       at Object.<anonymous> (test/components/instance-list-page/modal/instance-details/InstanceDetailsModal.es.js:139:35)
     [exec] 
     [exec]   ��� The InstanceDetailsModal component should ��� render with a pending Instance ��� Render Process details with correct infos
     [exec] 
     [exec]     expect(element).toHaveTextContent()
     [exec] 
     [exec]     Expected element to have text content:
     [exec]       Jan 20, 2020, 3:08 PM
     [exec]     Received:
     [exec]       creation-dateJan 20, 2020, 3:08 AM
     [exec] 
     [exec]       208 | 			expect(instanceDetailsRows[0]).toHaveTextContent('pending');
     [exec]       209 | 			expect(instanceDetailsRows[1]).toHaveTextContent('Test Test');
     [exec]     > 210 | 			expect(instanceDetailsRows[2]).toHaveTextContent(
     [exec]           | 			                               ^
     [exec]       211 | 				'Jan 20, 2020, 3:08 PM'
     [exec]       212 | 			);
     [exec]       213 | 			expect(instanceDetailsRows[3]).toHaveTextContent('Blogs Entry');
     [exec] 
     [exec]       at Object.<anonymous> (test/components/instance-list-page/modal/instance-details/InstanceDetailsModal.es.js:210:35)

...

  [exec]        98 | 
     [exec]        99 | 		const creatorCell = queryByText('User 1');
     [exec]     > 100 | 		const dateCreatedCell = getByText('Jan 01, 2019, 4:00 AM');
     [exec]           | 		                        ^
     [exec]       101 | 		const taskNamesCell = queryByText('Review, Update');
     [exec]       102 | 
     [exec]       103 | 		expect(creatorCell).toBeTruthy();
     [exec] 
     [exec]       at Object.getElementError (../../../../node_modules/@testing-library/dom/dist/config.js:38:19)
     [exec]       at ../../../../node_modules/@testing-library/dom/dist/query-helpers.js:90:38
     [exec]       at ../../../../node_modules/@testing-library/dom/dist/query-helpers.js:62:17
     [exec]       at getByText (../../../../node_modules/@testing-library/dom/dist/query-helpers.js:111:19)
     [exec]       at Object.<anonymous> (test/components/instance-list-page/InstanceListPageItem.es.js:100:27)
     [exec]       at processTicksAndRejections (node:internal/process/task_queues:96:5)
     [exec] 
     [exec]   ��� The instance list item should ��� Be rendered with due date success when the slaStatus is "OnTime" and slaResult status is "RUNNING"
     [exec] 
     [exec]     expect(received).toBeTruthy()
     [exec] 
     [exec]     Received: null
     [exec] 
     [exec]       226 | 		);
     [exec]       227 | 
     [exec]     > 228 | 		expect(slaDateTimeRemaingTime).toBeTruthy();
     [exec]           | 		                               ^
     [exec]       229 | 
     [exec]       230 | 		fireEvent.mouseLeave(popoverElement);
     [exec]       231 | 		fireEvent.mouseOut(dateText);
     [exec] 
     [exec]       at Object.<anonymous> (test/components/instance-list-page/InstanceListPageItem.es.js:228:34)
     [exec]       at processTicksAndRejections (node:internal/process/task_queues:96:5)
     [exec] 
     [exec]   ��� The instance list item should ��� Be rendered with due date danger when the slaStatus is "Overdue" and slaResult status is "RUNNING"
     [exec] 
     [exec]     expect(received).toBeTruthy()
     [exec] 
     [exec]     Received: null
     [exec] 
     [exec]       290 | 		);
     [exec]       291 | 
     [exec]     > 292 | 		expect(slaDateTimeRemaingTime).toBeTruthy();
     [exec]           | 		                               ^
     [exec]       293 | 
     [exec]       294 | 		fireEvent.mouseOut(dateText);
     [exec]       295 | 
     [exec] 
     [exec]       at Object.<anonymous> (test/components/instance-list-page/InstanceListPageItem.es.js:292:34)
     [exec]       at processTicksAndRejections (node:internal/process/task_queues:96:5)
     [exec] 
     [exec]   ��� The instance list item should ��� Be rendered with remaining time when the SLA is less than a minute.
     [exec] 
     [exec]     expect(received).toBeTruthy()
     [exec] 
     [exec]     Received: null
     [exec] 
     [exec]       367 | 		);
     [exec]       368 | 
     [exec]     > 369 | 		expect(slaDateTimeRemaingTime).toBeTruthy();
     [exec]           | 		                               ^
     [exec]       370 | 	});
     [exec]       371 | 
     [exec]       372 | 	it('Be rendered with due date when the slaResults is empty', () => {
     [exec] 
     [exec]       at Object.<anonymous> (test/components/instance-list-page/InstanceListPageItem.es.js:369:34)
     [exec]       at processTicksAndRejections (node:internal/process/task_queues:96:5)
     [exec] 
     [exec] FAIL test/components/filter/CustomTimeRangeForm.es.js
     [exec]   ��� The performance by assignee card component should ��� Be redered with default custom dates
     [exec] 
     [exec]     expect(received).toBe(expected) // Object.is equality
     [exec] 
     [exec]     Expected: "12/03/2019"
     [exec]     Received: "12/02/2019"
     [exec] 
     [exec]       39 | 		const dates = getAllByPlaceholderText('MM/DD/YYYY');
     [exec]       40 | 
     [exec]     > 41 | 		expect(dates[0].value).toBe('12/03/2019');
     [exec]          | 		                       ^
     [exec]       42 | 		expect(dates[1].value).toBe('12/09/2019');
     [exec]       43 | 	});
     [exec]       44 | });
     [exec] 
     [exec]       at Object.<anonymous> (test/components/filter/CustomTimeRangeForm.es.js:41:26)
     [exec]       at processTicksAndRejections (node:internal/process/task_queues:96:5)
     [exec] 

```

**Comment by bryceosterhaus** [comment]
gonna close this and send a new PR when more work is done

**Pull request closed without merging**
