### PR TITLE
LPS-142323 | A11yTool - Verifies occurrence is viewed in the side panel

### PR DESCRIPTION
**Pull request by susanchen3**
**Background**
Create automated tests for the A11y tool

**Test Plan**
- Verify there are violations the page
- Click on an icon
- Click on the rule in the popover
- Assert the violation occurrence is displayed in the side panel

**JIRA Ticket:**
https://issues.liferay.com/browse/LPS-142323

### CODE REVIEW

**Comment by susanchen3** [comment]
ci:test:frontend:nocompile

**Comment by john-co** [comment]
Just started reviewing :)

**Review by john-co — APPROVED** [review]
Looks good to me :+1:

**Comment by john-co** [comment]
ci:forward

**Pull request closed without merging**
