### PR TITLE
LPS-132868 Fix error when the root topic is selected in Questions

### PR DESCRIPTION
**Pull request by javierdearcos**
Fix the argument passed to the getSectionBySectionTitle query to be inside the variables property, and make the same transformation of the response we are doing when we make the getSections query to have the same result and have the same behavior in the next chaining transformations.

Also fix some issues when some properties were null.

### CODE REVIEW

**Review by nhpatt — APPROVED** [review]

**Comment by nhpatt** [comment]
ci:forward

**Comment by javierdearcos** [comment]
ci:forward

**Comment by javierdearcos** [comment]
ci:forward

**Comment by javierdearcos** [comment]
This seems to be completely stuck... Do you agree to close it and send it again in another PR?

**Comment by nhpatt** [comment]
I think you can do ci:stop, rebase and rerun

**Comment by javierdearcos** [comment]
ci:stop

**Comment by javierdearcos** [comment]
ci:forward

**Pull request closed without merging**
