### PR TITLE
LPS-190237 - SF unrelated changes

### PR DESCRIPTION
**Pull request by bryceosterhaus**

### CODE REVIEW

**Comment by bryceosterhaus** [comment]
ci:test:sf

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by mateusralv** [comment]
Hi @bryceosterhaus the failures are not related.

[Testray Comparison](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1690800751986&testrayRunIdA=2396554362&testrayRunIdB=2396645612)

**Comment by mateusralv** [comment]
ci:test:stable

**Comment by bryceosterhaus** [comment]
ci:forward:force

**Comment by bryceosterhaus** [comment]
ci:forward:force

**Pull request closed without merging**
