### PR TITLE
LPS-148244 Update Clay 2.x packages to 2.23.4

### PR DESCRIPTION
**Pull request by matuzalemsteles**
### Bug Fixes

* **clay-css:** Updates `content` property values to conform to what is allowed by OAW Tracker ([a0d6adf](https://github.com/matuzalemsteles/clay/commit/a0d6adf)), closes [#4683](https://github.com/matuzalemsteles/clay/issues/4683)

### CODE REVIEW

**Comment by julien** [comment]
ci:test:relevant

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by susanchen3** [comment]
Hi @matuzalemsteles,

The failures look unrelated to your changes. Ok to manually forward :+1:

**Comment by matuzalemsteles** [comment]
Manually forwarded https://github.com/brianchandotcom/liferay-portal/pull/114089

**Pull request closed without merging**
