### PR TITLE
LPS-114072 Replace layout classes with new clay components in layout-admin-web

### PR DESCRIPTION
**Pull request by eduardoallegrini**
This is a simple code replacement of the layout classes for the new Clay Layout Components

Group 1 (1)

### CODE REVIEW

**Comment by jbalsas** [comment]
I think this LGTM... but based on what it touches, I'd send it to @liferay-echo so they can review and forward at will?

**Comment by eduardoallegrini** [comment]
As for the miller-columns I was able to find the UI and it's still working pretty well (not sure about the `.col-xs-11` class that should be `col-11`)

Modified (the `edu` class was inserted as a test and then removed)
Screenshot 2020-06-24 at 12 08 35

Original
image

> I'd send it to @liferay-echo so they can review and forward at will?
Then I'll send it to them!

**Comment by jbalsas** [comment]
> Modified (the edu class was inserted as a test and then removed)

Awesome!! Make sure you provide all this useful information! Specially this last bit about how and what you tested to verify this was safe! :)

**Comment by jbalsas** [comment]
Please, resend, close this and post the link here to the new PR when ready!

**Comment by eduardoallegrini** [comment]
https://github.com/liferay-echo/liferay-portal/pull/1251

**Pull request closed without merging**
