### PR TITLE
LPD-20694 Fix aria-label attribute for MT filter and order buttons

### PR DESCRIPTION
**Pull request by dsanz**
This PR fixes `aria-label` properties in clay MT component to match a11y tree with reality.

Reference: https://liferay.atlassian.net/browse/LPD-20693  (see there for snapshots)

Note: PR does not include MT in FDS as this is part of a much larger initiative to harmonize FDS MT

### CODE REVIEW

**Review by markocikos — APPROVED** [review]
@dsanz LGTM! :sparkles:

**Comment by dsanz** [comment]
ci:forward

**Comment by markocikos** [comment]
ci:forward

**Comment by markocikos** [comment]
ci:forward

**Pull request closed without merging**
