### PR TITLE
LPD-34947 Update AlloyUI to v3.1.0-deprecated.123

### PR DESCRIPTION
**Pull request by igor-franca**
Related [ticket](https://liferay.atlassian.net/browse/LPD-34947)

### CODE REVIEW

**Comment by igor-franca** [comment]
ci:test:playwright

**Comment by igor-franca** [comment]
I believe the error in sf is not related, I have success running the portal-impl former locally on my branch with these changes.

**Comment by dsanz** [comment]
yep, sf error is due to another cause.

**Comment by dsanz** [comment]
@igor-franca feel free to manually forward, or else rebase this onto a more recent master where SF error is corrected and then resend.
Thank you

**Comment by igor-franca** [comment]
ci:test:sf

**Comment by igor-franca** [comment]
ci:forward

**Pull request closed without merging**
