### PR TITLE
LPS-141280 Proposal to add the screenshots of a Remote App Entry as a part of the description

### PR DESCRIPTION
**Pull request by javierdearcos**
Removed the Feature Flag.

I've added description as a field instead of a localized-entity. The problem that I had on the first try is that we don't have a field that is localized and HTML at the same time, and because the database escapes the HTML to save the localized field with the XML format that we use, it is very difficult to recover it correctly from the database (if I unescape the string I also unescape the XML), so I think the best approach is to use one of the following approaches:
- Non-localized description field. I think it is a good solution as I don't see the need to localize this field as it is meant to be used in the remote app review.
- Description as a localized entity to ease the storage and recovery of the information from the database (I would send you again the old PR without the configuration)

---

Original commit:

To be able to validate the Remote App by a reviewer, it is needed to add some extra fields as description, sourceCodeURL, and some screenshots.

After trying to achieve the addition of screenshots using attachments and prove that it would be a complex task, and also that there are different approaches in the different usages in the platform, I've decided to take a more pragmatic and simpler approach to see if it is enough to provide value.

The approach is to change the description field to be an HTML that can embed different images and use an editor to fulfill the field in the frontend.

The result is shown in the following image:

This approach could be used with a hint in the UI to enforce the usage of screenshots in the description.

The database upgrade step is pending until the approach is validates, because it's not straightforward

### CODE REVIEW

**Comment by javierdearcos** [comment]
ci:forward

**Comment by javierdearcos** [comment]
ci:forward

**Comment by javierdearcos** [comment]
ci:forward

**Comment by javierdearcos** [comment]
ci:forward

**Comment by javierdearcos** [comment]
ci:forward

**Comment by zhangyan0701** [comment]
The two failed upgrade tests look related:
[LocalFile.PortalSmokeUpgrade#ViewPortalSmokeArchive7310](https://testray.liferay.com/home/-/testray/case_results/1584179375)
[LocalFile.PortalSmokeUpgrade#ViewPortalSmokeArchive7413](https://testray.liferay.com/home/-/testray/case_results/1584179380)

Below error thrown during the upgrade from 7310 and 7413:
**7310:** 
```
     [java] 2021-11-26 18:38:20.519 ERROR [main][UpgradeStepRegistratorTracker:143] Failed upgrade process for module com.liferay.remote.app.service
     [java] java.lang.IllegalStateException: There are 2 possible end nodes for 1.0.0
```
Full console: https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/478327/AXIS_VARIABLE=1/consoleFull

**7410:**
```
     [java] 2021-11-26 18:33:45.140 ERROR [main][UpgradeStepRegistratorTracker:143] Failed upgrade process for module com.liferay.remote.app.service
     [java] java.lang.IllegalStateException: There are 2 possible end nodes for 2.1.0
```
Full console: https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/478327/AXIS_VARIABLE=2/consoleFull

**Comment by javierdearcos** [comment]
Thank you zhangyan0701! 

I'll take a look, fix it and send it again

**Comment by javierdearcos** [comment]
Silly mistake rebasing...

Now everything is fixed and tested manually and working correctly. I will try to forward it for the last time, and if it is not successful, I will send it directly to Brian

**Comment by javierdearcos** [comment]
ci:test

**Comment by javierdearcos** [comment]
ci:stop

**Comment by javierdearcos** [comment]
ci:forward

**Comment by javierdearcos** [comment]
ci:test:sf

**Comment by javierdearcos** [comment]
ci:test:sf

**Comment by javierdearcos** [comment]
Sent directly to Brian here: https://github.com/brianchandotcom/liferay-portal/pull/110482

**Pull request closed without merging**
