### PR TITLE
LPS-119691 Removes common markup ids to avoid them being styled as if this was inside a popup (which it is not)

### PR DESCRIPTION
**Pull request by jbalsas**
This was caused by https://github.com/liferay-frontend/liferay-portal/pull/294, making the Setup Wizard look off.

SetupWizard-Chrome84

**The problem**
- We're styling `.portal-popup:not(.article-preview) #main-content` with `position:absolute` and other niceties. 
- Setup Wizard renders in "popup" mode but outside a dialog

**The fix**
- Smallest possible fix is to simply remove the `main-content` id. 
- Other options would be to restyle the the content, or add another exception to the `.portal-popup` rule.

Screen Shot 2020-08-25 at 09 50 03

I'm trying the first one here to see if tests would need to be adjusted and we can simply get away with that minimal fix.

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:test:sf

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
Tests are green, so... 🤷 

@brunobasto, do you have any thoughts on this? I would ask @marcoscv-work too, but he's on PTO :D

**Review by eduardoallegrini — CHANGES_REQUESTED** [review]
I don't see any problem with the removals unless we are not considering some JS reference on those classes/ids.

On the other hand I think this is a good place to use the "new" clay-tags `<clay:container-fluid>` and `<clay:sheet>` and I'm surprise we aren't already using them 🤔
https://docs.google.com/document/d/1PdnTm4tpxObLLlyQnDQZLKbhSxzXyBTpP-ZwlK692K8/edit

**Comment by jbalsas** [comment]
> On the other hand I think this is a good place to use the "new" clay-tags <clay:container-fluid> and <clay:sheet> and I'm surprise we aren't already using them 🤔

Only tags inside `util-taglib`/`portal-web` can be used here. This is what we usually call "core" and it doesn't have access to tags in modules like `clay:*`.

**Review by eduardoallegrini — APPROVED** [review]

**Comment by jbalsas** [comment]
ci:forward

**Pull request closed without merging**
