### PR TITLE
LPS-162585 | master

### PR DESCRIPTION
**Pull request by sontruongces**
Hi team,

This is the fix for the [LPS-162585](https://issues.liferay.com/browse/LPS-162585), the original has passed my review at sontruongces#35. Please help me review and give feedback.

Thanks!
cc: @thienquach87

### CODE REVIEW

**Comment by thienquach87** [comment]
ci:test:relevant

**Comment by diegonvs** [comment]
Hey @sontruongces, we are not the owners of these modules you changed:

bookmarks-web
document-library-web
journal-web

What I recommend to you is to send this PR separately to these teams(in this case, lima and echo) and then, once you get the approval send the definitive PR :)

**Comment by thienquach87** [comment]
@diegonvs,

Thank you for your recommendation!

**Comment by thienquach87** [comment]
ci:close

**Comment by thienquach87** [comment]
thank you :dancers:

**Pull request closed without merging**
