### PR TITLE
LPS-177171 - Remove metal usage

### PR DESCRIPTION
**Pull request by bryceosterhaus**
Removes all support for metal and soy from our npm-scripts build tools. This also entirely removes the frontend-js-metal-web 
module.

### CODE REVIEW

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
ci:stop

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
ci:test:relevant:norebase

**Comment by deborasoliveira** [comment]
I'll take a look at it.

**Comment by bryceosterhaus** [comment]
ci:test:sf

**Comment by bryceosterhaus** [comment]
ci:test:sf

**Comment by bryceosterhaus** [comment]
ci:test:sf

**Comment by bryceosterhaus** [comment]
ci:test:sf

**Comment by bryceosterhaus** [comment]
ci:test:sf

**Comment by bryceosterhaus** [comment]
ci:test:sf

**Comment by bryceosterhaus** [comment]
manual forward https://github.com/brianchandotcom/liferay-portal/pull/142740

**Pull request closed without merging**
