### PR TITLE
[TS] LPS-142136

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-142136

Please let me know if you have any questions, thanks!

### CODE REVIEW

**Comment by diegonvs** [comment]
Hey Chris, thanks for contributing! RegEXP are always hard for Web patterns like [URLs](https://mathiasbynens.be/demo/url-regex), HTML strings.

When testing your change and I'm not finding how it solves the white space issue:

```js
// With yours regex:
Liferay.Util.unescapeHTML('&#39;&quot;x1 &lt; x2 &amp;&amp; y2 &gt; y1&quot;&#39;')
`'"x1 < x2 && y2 > y1"'`

// With the current regex:
Liferay.Util.unescapeHTML('&#39;&quot;x1 &lt; x2 &amp;&amp; y2 &gt; y1&quot;&#39;')
`'"x1 < x2 && y2 > y1"'`
```

Could you explain a bit more? Providing one more test [here](https://github.com/liferay-frontend/liferay-portal/blob/4e4b352f53fb8165f0da91b6109f3b6fc540ca3e/modules/apps/frontend-js/frontend-js-web/test/liferay/util/html_util.js#L40) would be useful :)

Also, could you change your PR title to a more legible one? Following our PR guidelines? 💔 

https://github.com/liferay/liferay-frontend-projects/blob/master/guidelines/general/pull_requests.md#prefer

Thanks 💖

**Comment by diegonvs** [comment]
Also, I found this RegExp here: https://github.com/google/closure-library/blob/a1fa9f4f8d8c5ec67ce2c975a16d2bb93e1fd593/closure/goog/string/string.js#L719 and It can be useful. Could you bring some samples of string you are trying to test? Thanks :)

**Comment by ChrisKian** [comment]
Hi @diegonvs,
This fix isn't to properly escape an encoded string, but rather to prevent a string from being unnecessarily escaped.

Following the steps on [LPS-142136](https://issues.liferay.com/browse/LPS-142136), if we input the following string into a Text field, we will scrub some HTML data due to the RegExp matching:

```
<a href="https://www.liferay.com?param1=1&param2=2">Visit Liferay</a>
<a href="https://www.google.com">
    <img src="https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png" alt="Google" style="padding-top: 2px;" />
</a>
```
So for this example, the "&" separating the params in the Liferay URL will match the start of the Regexp, and the ";" in the Google style element will match the end of the RegExp.  Unescaping this data results in a loss of data.

My solution was to simply make sure any escaped HTML we are using the RegExp on is actually valid.  Escaped HTML codes shouldn't have any whitespace in them (afaik), so this was the easiest and safest way to do this.

Lastly, it looks like the RegExp example from Google you linked also makes sure there are no whitespace characters, so I think the approach is (mostly) correct.

**Comment by ChrisKian** [comment]
Another example of a string will be unescaped without my solution is this:

`1, 2, & 3 are prime numbers; 4 is not.`

The "&" will be matched first, all characters will be valid, and the ";" will be matched last, so the capture group will be:
` 3 are prime numbers`

Although unescaping this has no impact, we are still matching an escape code when we shouldn't.

**Comment by diegonvs** [comment]
Hey @markocikos, this PR looks good to me. Would you add something?

**Review by markocikos — APPROVED** [review]
LGTM!

**Comment by markocikos** [comment]
ci:forward

**Pull request closed without merging**
