### PR TITLE
LPS 128635 | Workaround for failing remote app test

### PR DESCRIPTION
**Pull request by calvinctvo**
Workaround for failing remote app test due to remote app table changes
**Test Plan:**

1. Go to Control Panel > Custom Apps > Remote Apps
2. Add a new Remote App by clicking on + icon
3. Name remote app "Test Remote App"
4. Observe the Remote Apps table

https://issues.liferay.com/browse/LPS-128635

### CODE REVIEW

**Review by john-co — APPROVED** [review]
Looks good, please add a passing poshi report on the JIRA ticket or link to passing ci run. This will make it faster for test reviewer to make sure test passes.

**Comment by calvinctvo** [comment]
ci:forward

**Comment by john-co** [comment]
hmm...interesting that you can skip the `ci:test:relevant` results with `ci:forward` in the middle of the run...

**Comment by john-co** [comment]
ci:forward

**Comment by john-co** [comment]
just to keep things kosher.

**Comment by john-co** [comment]
ci:forward

**Comment by john-co** [comment]
oh I realized this is a new feature for poshi only changes: https://liferay.slack.com/archives/C19PWQ74J/p1614823879045500?thread_ts=1614823812.044700&cid=C19PWQ74J

`ci:forward` will skip `ci:test:relevant` if it detects only poshi changes. There's some risk in not running other poshi tests but it's prevented if we follow Rodrigo's suggestion: https://liferay.slack.com/archives/C19PWQ74J/p1614872189053500?thread_ts=1614823812.044700&cid=C19PWQ74J

**Pull request closed without merging**
