### PR TITLE
LPD-21465 Show the first page of results after filtering in management toolbar

### PR DESCRIPTION
**Pull request by antonio-ortega**
[Previous pull request](https://github.com/liferay-frontend/liferay-portal/pull/4105)

Hey,

After a deeper analysis of this case I could identify three cases (although I wouldn't discard there is something else):
* Filter is done through a direct option in management toolbar (_Expired_, _approved_, _mine_, ...)
* Filter is done through a modal window for either tags or categories
* Filter is done through a modal window for whatever else (_type of asset_, _structure_, _author_, ...)

I've committed changes for every case in a different commit so it's easier to identify them. 

The big issue here is the third case since that's part of client code so I had to fix the case in D&M, Journal and Content Dashboard. There are some other cases where they are using a modal window to filter some content but this issue is not reproducible for different reasons (i.e, they don't navigate after filtering), so I haven't modify them.

Initially I thought about creating some sort of util with this solution, but it could not be use everywhere because there are a few particular cases, so I thought it would be better this way.

Thanks.

Regards.

### CODE REVIEW

**Comment by antonio-ortega** [comment]
ci:test:sf

**Comment by antonio-ortega** [comment]
ci:test:sf

**Comment by antonio-ortega** [comment]
ci:test:sf

**Comment by antonio-ortega** [comment]
ci:test:relevant

**Comment by antonio-ortega** [comment]
ci:test:relevant

**Comment by dsanz** [comment]
LGTM ;)

**Comment by antonio-ortega** [comment]
ci:forward

**Pull request closed without merging**
