### PR TITLE
LPS-148445 Draft PR to check webpack+ESM based build in CI

### PR DESCRIPTION
**Pull request by izaera**

### CODE REVIEW

**Comment by izaera** [comment]
ci:test

**Comment by izaera** [comment]
ci:test

**Comment by izaera** [comment]
ci:test

**Comment by izaera** [comment]
I've managed to find why this fails :tada: 

There are some icons missing from the UI and that's because `@clayui/button` is bundling `@clayui/icon` inside itself and that makes the `ClayIconSpriteContext` be duplicated so that the one `frontend-js-react-web/js/render.js` injects does not correspond to the one `@clayui/button` uses.

I think we can fix this by creating different entry points when invoking webpack so that `@clayui/button` can pull `@clayui/icon` via ESM, instead of bundling it internally, so I'll try it.

**Comment by izaera** [comment]
I think I've fixed it, but I've had to internalize `@clayui/provider` instead of making it an export. This is because, for some unknown reason, webpack doesn't export anything as ESM for this package.

I'm going to investigate it a bit more.

**Comment by bryceosterhaus** [comment]
> I think I've fixed it,

Where exactly did you add this at? I didn't see any additional commits to this PR

**Comment by julien** [comment]
@izaera I thought it might be good idea to ping @matuzalemsteles in this "thread" just in case he's able to clear some doubts about this.

**Comment by izaera** [comment]
> Where exactly did you add this at? I didn't see any additional commits to this PR

Sorry about that. I only added that comment at the end of the day for the record. I'm planning to investigate why it fails and why it is fixed today, because the solution is a workaround, and I prefer to know if we can fix it some other way.

**Comment by izaera** [comment]
> to clear some doubts about this.

Which doubts? Yours or mine? :sweat_smile:

**Comment by julien** [comment]
:joy: good point: all those comments you left here are interesting for the Clay squad; and since we're also working on moving Clay to DXP; and even if that doesn't end up happening, I'd like us to follow this conversation.

**Comment by izaera** [comment]
OK, so, the reason why this was failing is that `@clayui/provider` [is using some way to export its stuff](https://github.com/liferay/clay/blob/c62913222b959af3ce13f0e00cd10a8406ab4a33/packages/clay-provider/src/index.ts#L6) that when processed by typescript is translated to [something obscure](https://unpkg.com/@clayui/provider@3.40.0/lib/index.js) that is probably fooling webpack.

This code is not statically analyzable:

```javascript
Object.keys(_Provider).forEach(function (key) {
  if (key === "default" || key === "__esModule") return;
  if (key in exports && exports[key] === _Provider[key]) return;
  Object.defineProperty(exports, key, {
    enumerable: true,
    get: function get() {
      return _Provider[key];
    }
  });
});
```

Even though it comes from [one that was statically analizable](https://github.com/liferay/clay/blob/c62913222b959af3ce13f0e00cd10a8406ab4a33/packages/clay-provider/src/index.ts#L6).

Because of that, webpack seems to give up when trying to determine what to export with ESM syntax and the produced .js file ends up exporting nothing, thus making everything fail at runtime.

One possible way of fixing this would be generating ESM code while constructing `@clayui/provider` (in addition to the CommonJS one) and using that from webpack. However, given that we can expect to find this problem in more places, I have created some code in `npm-scripts` to workaround this.

I will release a new snapshot of `npm-scripts` and push some changes to this PR to use it and see what happens. In any case, I've tried the fix locally and the icons are not lost any more.

**Comment by matuzalemsteles** [comment]
> OK, so, the reason why this was failing is that @clayui/provider [is using some way to export its stuff](https://github.com/liferay/clay/blob/c62913222b959af3ce13f0e00cd10a8406ab4a33/packages/clay-provider/src/index.ts#L6) that when processed by typescript is translated to [something obscure](https://unpkg.com/@clayui/provider@3.40.0/lib/index.js) that is probably fooling webpack.

hey @izaera this is interesting maybe it makes sense in case the typescript compiles to something like this at the end because we are using the `export * from ''` syntax, this really wouldn't have any way to infer, we can change it too so that the parse can be inferred to `export {Provider, useProvider} from ''` the output looks like this:

```js
Object.defineProperty(exports, "__esModule", {
  value: true
});
Object.defineProperty(exports, "Provider", {
  enumerable: true,
  get: function get() {
    return _Provider.Provider;
  }
});
Object.defineProperty(exports, "useProvider", {
  enumerable: true,
  get: function get() {
    return _Provider.useProvider;
  }
});

var _Provider = require("./Provider");
```

Maybe webpack can't parse because it doesn't have the plugin? This is also weird because the spec came in 2019 apparently, in theory, this shouldn't be a problem or it could just be a webpack and typescript output divergence fight  🤷‍♂️

> There are some icons missing from the UI and that's because @clayui/button is bundling @clayui/icon inside itself and that makes the ClayIconSpriteContext be duplicated so that the one frontend-js-react-web/js/render.js injects does not correspond to the one @clayui/button uses.
> I think we can fix this by creating different entry points when invoking webpack so that @clayui/button can pull @clayui/icon via ESM, instead of bundling it internally, so I'll try it.

Hm, just to understand here. Is this happening because both are in different places (modules) and webpack doesn't have visibility of both packages to determine a single point? This should probably work for building the Clay module in this case, or is it one unique point for all packages?

**Comment by izaera** [comment]
>  this shouldn't be a problem or it could just be a webpack and typescript output divergence fight 

The problem is that I'm running webpack over the output of your compilation. That's why *my* webpack is fooled by the output of your webpack/typescript compiler.

In any case, you don't need to worry about it, given that what @clayui/provider is doing is perfectly valid. I think it's a bug in webpack due to a corner case (as we are using experimental features).

**Comment by izaera** [comment]
> Hm, just to understand here. Is this happening because both are in different places (modules) and webpack doesn't have visibility of both packages to determine a single point? This should probably work for building the Clay module in this case, or is it one unique point for all packages?

Currently, you may only have one instance of @clayui/provider in the same JS engine. This is because if you end up having more than one, only one of them will be properly initialized by frontend-js-react-web/render.

Our bundler guaranteed before that there was only one copy of each package, but because I'm using webpack now, I need to tweak it to make that happen. The usual way to tweak it in standard webpack builds is to use a shared chunk and the dependOn config option of webpack. In our case, what I'm doing is launching webpack several times and making sure that all of them get @clayui/provider as an external (https://webpack.js.org/configuration/externals/).

**Comment by matuzalemsteles** [comment]
Oh that makes sense @izaera, thanks for the explanation!

**Comment by izaera** [comment]
Failing DDM Form tests are due to AMD imports by path, which should not be used (ie: `import x from '@clayui/button/lib/some/internal/path';` instead of `import {x}  from '@clayui/button';`.

This is good because it means the foundation is probably working correctly (thus there are no major impediments to the proposed architecture) and we are nearer to make this work :crossed_fingers:

**Comment by izaera** [comment]
ci:test

**Comment by izaera** [comment]
ci:test

**Comment by izaera** [comment]
ci:test

**Comment by izaera** [comment]
ci:test

**Comment by izaera** [comment]
ci:test

**Comment by izaera** [comment]
The last CI run has used an old commit (don't know why) that's why it is failing with errors that I already fixed

**Comment by izaera** [comment]
ci:bundle

**Comment by izaera** [comment]
ci:test:bundle

**Comment by izaera** [comment]
Superseded by https://github.com/liferay-frontend/liferay-portal/pull/2013

**Pull request closed without merging**
