### PR TITLE
LPS-127732 Update liferay-ckeditor to v4.14.1-liferay.19

### PR DESCRIPTION
**Pull request by wincent**
Brings in [this fix](https://github.com/liferay/liferay-ckeditor/pull/156).

Full [release notes](https://github.com/liferay/liferay-ckeditor/releases/tag/v4.14.1-liferay.19).

cc @NemethNorbert, @julien

### CODE REVIEW

**Comment by wincent** [comment]
ci:test:bundle

**Comment by wincent** [comment]
@NemethNorbert, going through the repro recipe on the LPS:

> ### Reproduction Steps:
>
> #### Go to Site Builder --> Pages and add a public (Content) Page.
>
> 1. While the page is in Edit mode, from the right side Fragments and Widgets menu drag and drop a Paragraph card to the Page
> 2. Go to the text of the Paragraph and double click it so the text toolbar pops up
> 3. Set the Style of the text on the toolbar to Lead or Small
>    Checkpoint: The text style is changed successfully
> 4. Try to set the text back to Normal.
>
> **Expected Result:** The text should be set back successfully to Normal or to the text size that we select.
>
> **Actual Result:** The Small or Lead styles can only be removed if the Small or Lead style is clicked.

I still see the old behavior. May be something with my portal instance though, so we can double check once the `ci:test:bundle` has finished running.

**Review by julien — APPROVED** [review]

**Comment by NemethNorbert** [comment]
> @NemethNorbert, going through the repro recipe on the LPS:
> 
> > ### Reproduction Steps:
> > #### Go to Site Builder --> Pages and add a public (Content) Page.
> > 
> > 1. While the page is in Edit mode, from the right side Fragments and Widgets menu drag and drop a Paragraph card to the Page
> > 2. Go to the text of the Paragraph and double click it so the text toolbar pops up
> > 3. Set the Style of the text on the toolbar to Lead or Small
> >    Checkpoint: The text style is changed successfully
> > 4. Try to set the text back to Normal.
> > 
> > **Expected Result:** The text should be set back successfully to Normal or to the text size that we select.
> > **Actual Result:** The Small or Lead styles can only be removed if the Small or Lead style is clicked.
> 
> I still see the old behavior. May be something with my portal instance though, so we can double check once the `ci:test:bundle` has finished running.

Hey @wincent ,
I retested the solution on master by updating ckeditor to v4.14.1-liiferay.19
My tests were green and I was not able to reproduce the issue anymore.
I think it was something with your portal instance, but let me know if you keep getting the same results.

Thanks,

**Comment by julien** [comment]
@NemethNorbert I'm currently downloading the "bundle", but this is what I see locally with these changes deployed

recording (2)

Once the style has been set to "Lead", clicking on "Normal" doesn't seem to reset it

**Comment by NemethNorbert** [comment]
> @NemethNorbert I'm currently downloading the "bundle", but this is what I see locally with these changes deployed
> 
> recording (2)
> 
> Once the style has been set to "Lead", clicking on "Normal" doesn't seem to reset it

I see the issue, I was selecting the whole paragraph during my tests and it works that way.
It might be caused by the default value of the second parameter of **enlarge**, that is a bool to determine whether to include line-breaks when expanding. It defaults to false.

What I see is when we select a word, or part of the sentence and change the style:
- we create a new line break before and after of our selection, and apply the changes to the paragraph

This kinda explains why the current solution does not cover this scenario. Let me test my idea and resend the solution, I feel positive about this one :)

Thanks,

**Comment by jbalsas** [comment]
Looks like this is going to be a resend, so I'm going to close here to prevent us from accidentally sending this forward. Please, feel free to reopen if we should still push this as is!

**Comment by NemethNorbert** [comment]
Hey @wincent , @julien 

I tested my theory about the usage of the second parameter. Unfortunately my positiveness quickly depleted when I saw no difference between setting the second attribute to true or not. At this point I am not sure, if the general direction of this fix is wrong, or the second parameter doesn't do what it should here...
The fact that the solution works, when we select the whole paragraph, but it doesn't if we only select part of it even when we account the line breaks when we enlarge kinda confused me here.

Could you guys advise me at this point?

**Comment by NemethNorbert** [comment]
I found we put our selection into a `<span>` and only apply the style changes within that boundary
Screenshot 2021-03-12 at 13 37 28
In case we select the whole paragraph, the `<span>` will enclose our element.
Screenshot 2021-03-12 at 13 37 45

When we only select one word, it will only encapsulate that
Screenshot 2021-03-12 at 13 41 52

I still don't see difference between using the second boolean attribute of the enlarge method. I tested it with and without line breaks when selecting part of the text, but no difference in behaviour

**Comment by jbalsas** [comment]
Hey @NemethNorbert, I'm inclined to think this is not a bug, specially not a bug in the editor. I get the feeling this is working as intended and there's some confusion as to what is the expectation.

These are [block level](https://ckeditor.com/docs/ckeditor4/latest/features/styles.html#style-types) styles as can be seen in [Applying Styles to Editor Content](https://ckeditor.com/docs/ckeditor4/latest/features/styles.html#style-types). The provided styles are configuration (not something AlloyEditor does by default) set by [FragmentEntryLinkRichTextEditorConfigContributor](https://github.com/liferay/liferay-portal/blob/master/modules/apps/layout/layout-content-page-editor-web/src/main/java/com/liferay/layout/content/page/editor/web/internal/editor/configuration/FragmentEntryLinkRichTextEditorConfigContributor.java#L200-L216).

A crude fix would be to add `class=""` to the heading styles so that they'd reset the `lead` and `small` cases, but that wouldn't work with `normal`,  I think.

I think we should work in the context of the configuration and the styles API rather than trying to patch the default CKEditor behaviour.

**Comment by NemethNorbert** [comment]
> Hey @NemethNorbert, I'm inclined to think this is not a bug, specially not a bug in the editor. I get the feeling this is working as intended and there's some confusion as to what is the expectation.
> 
> These are [block level](https://ckeditor.com/docs/ckeditor4/latest/features/styles.html#style-types) styles as can be seen in [Applying Styles to Editor Content](https://ckeditor.com/docs/ckeditor4/latest/features/styles.html#style-types). The provided styles are configuration (not something AlloyEditor does by default) set by [FragmentEntryLinkRichTextEditorConfigContributor](https://github.com/liferay/liferay-portal/blob/master/modules/apps/layout/layout-content-page-editor-web/src/main/java/com/liferay/layout/content/page/editor/web/internal/editor/configuration/FragmentEntryLinkRichTextEditorConfigContributor.java#L200-L216).
> 
> A crude fix would be to add `class=""` to the heading styles so that they'd reset the `lead` and `small` cases, but that wouldn't work with `normal`, I think.
> 
> I think we should work in the context of the configuration and the styles API rather than trying to patch the default CKEditor behaviour.

Hey @jbalsas, I was starting to play around with that idea as well. When I first heard about the issue, I thought its a won't fix due to this is the expected behaviour of ckeditor. But based on the comment here: https://github.com/liferay/alloy-editor/blob/master/src/components/buttons/button-styles-list-item.jsx#L91-L103
We have a different expectation within AlloyEditor.

What I was thinking, why are we using css classes to provide the lead and small styles? Why aren't we using `<small>` and `<big>` html elements, like the ckeditor for example here: https://ckeditor.com/docs/ckeditor4/latest/examples/removeformat.html

I believe that would resolve this issue as well and we could modify part of the paragraph with these changes not just the whole.

**Comment by NemethNorbert** [comment]
Hey @wincent , @julien , @jbalsas 
By changing the configuration to make the small and lead styles to be inline styles, resolves the issue quite nicely:
`return JSONUtil.putAll(
			getStyleFormatJSONObject(
				LanguageUtil.get(resourceBundle, "small"), "span", "small", 2),
			getStyleFormatJSONObject(
				LanguageUtil.get(resourceBundle, "lead"), "span", "lead", 2),
			getStyleFormatJSONObject(
				LanguageUtil.format(resourceBundle, "heading-x", "1"), "h1",
				null, 1),
			getStyleFormatJSONObject(
				LanguageUtil.format(resourceBundle, "heading-x", "2"), "h2",
				null, 1),
			getStyleFormatJSONObject(
				LanguageUtil.format(resourceBundle, "heading-x", "3"), "h3",
				null, 1),
			getStyleFormatJSONObject(
				LanguageUtil.format(resourceBundle, "heading-x", "4"), "h4",
				null, 1));
	}`
I ended up using spans and the same css classes, it works so the less change the better I thought.
With this change the block level and inline level styles does not have an effect on each other unless everything is selected. The behaviour ends up the same as ckeditor and we don't have to wrap our head around dealing with block level changes, that are coupled with css attributes form a partial selection within our editor.

As this change is not part of our FEI, I will drop the new PR at the WEM team, but I still wanted to ask what do you think about this direction?

**Comment by jbalsas** [comment]
> What I was thinking, why are we using css classes to provide the lead and small styles? Why aren't we using <small> and <big> html elements, like the ckeditor for example here: https://ckeditor.com/docs/ckeditor4/latest/examples/removeformat.html

I think it was due to the fact that those elements have no default browser styles and we rely on the bootstrap implementation via class to make them look different. 

> As this change is not part of our FEI, I will drop the new PR at the WEM team, but I still wanted to ask what do you think about this direction?

Sounds good to me, @NemethNorbert. The proposal is a functionality change, so I'd make sure to be very explicit about it when discussing it with the team.

Also, @julien, could we make sure to revert the patch we applied for this to make sure it doesn't introduce other unwanted behaviours?

**Comment by julien** [comment]
@jbalsas yes of course, I'll take of that.

**Pull request closed without merging**
