### PR TITLE
LPS-168441 - Centralize JS dependencies in single osgi module

### PR DESCRIPTION
**Pull request by bryceosterhaus**
Resend from https://github.com/liferay-frontend/liferay-portal/pull/2944

### CODE REVIEW

**Comment by mateusralv** [comment]
Hi @bryceosterhaus This PR has some failures related. With the comparison we have over 200 single failures, some of them are: 

### Failure related to creating a Forms: 

https://user-images.githubusercontent.com/44584050/213525467-d0a898ee-4799-40f3-9411-e2c19aeeef28.mp4

---
### Failure relates to DM:

https://user-images.githubusercontent.com/44584050/213525596-de601885-8e80-40b0-92a2-47e1a12f75c1.mp4


[Testray comparison](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=2&testrayRunIdB=2165007859&testrayRunIdA=2164281093&statusB=3)

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
re-running. I wasn't able to reproduce the failures when running poshi locally...

**Comment by mateusralv** [comment]
Hi @bryceosterhaus Previous failures no longer occur, the number of single failures decreased, now we have ~70. [Testray Comparison](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=2&testrayRunIdB=2170296383&testrayRunIdA=2170279151&statusB=3)

### Failure in the semantic module

```
 [exec] com.liferay.semantic.versioning.SemanticVersioningTest > testSemanticVersioning[/apps/object/object-admin-rest-api] FAILED
     [exec]     java.lang.AssertionError:   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec]     = ================================================== ========== ========== ========== ========== ==========
     [exec]     * com.liferay.object.admin.rest.dto.v1_0             MINOR      7.5.0      7.5.0      7.6.0      VERSION INCREASE REQUIRED
     [exec]     	<   class      com.liferay.object.admin.rest.dto.v1_0.ObjectValidationRule
     [exec]     		+   field      objectDefinitionExternalReferenceCode
     [exec]     			+   access     protected
     [exec]     			+   annotated  com.fasterxml.jackson.annotation.JsonProperty
     [exec]     				+   property   access='READ_WRITE'
     [exec]     			+   annotated  com.liferay.portal.vulcan.graphql.annotation.GraphQLField
     [exec]     			+   annotated  com.liferay.portal.vulcan.graphql.annotation.GraphQLField
     [exec]     			+   return     java.lang.String
     [exec]     		+   method     getObjectDefinitionExternalReferenceCode()
     [exec]     			+   annotated  io.swagger.v3.oas.annotations.media.Schema
     [exec]     			+   return     java.lang.String
     [exec]     		+   method     setObjectDefinitionExternalReferenceCode(com.liferay.petra.function.UnsafeSupplier)
     [exec]     			+   annotated  com.fasterxml.jackson.annotation.JsonIgnore
     [exec]     			+   return     void
     [exec]     		+   method     setObjectDefinitionExternalReferenceCode(java.lang.String)
     [exec]     			+   return     void
     [exec]     * com.liferay.object.admin.rest.dto.v1_0.util        MAJOR      4.0.0      4.0.0      5.0.0      VERSION INCREASE REQUIRED
     [exec]     	>   class      com.liferay.object.admin.rest.dto.v1_0.util.ObjectActionUtil
     [exec]     		+   method     toObjectAction(java.util.Map,java.util.Locale,com.liferay.notification.service.NotificationTemplateLocalService,com.liferay.object.service.ObjectDefinitionLocalService,com.liferay.object.model.ObjectAction)
     [exec]     			+   access     static
     [exec]     			+   return     com.liferay.object.admin.rest.dto.v1_0.ObjectAction
     [exec]     		-   method     toObjectAction(java.util.Map,java.util.Locale,com.liferay.object.service.ObjectDefinitionLocalService,com.liferay.object.model.ObjectAction)
     [exec]     			-   access     static
     [exec]     			-   return     com.liferay.object.admin.rest.dto.v1_0.ObjectAction
     [exec]     		+   method     toParameters(com.liferay.notification.service.NotificationTemplateLocalService,com.liferay.object.service.ObjectDefinitionLocalService,com.liferay.portal.kernel.util.UnicodeProperties)
     [exec]     			+   access     static
     [exec]     			+   return     java.util.Map
     [exec]     		-   method     toParameters(com.liferay.object.service.ObjectDefinitionLocalService,com.liferay.portal.kernel.util.UnicodeProperties)
     [exec]     			-   access     static
     [exec]     			-   return     java.util.Map
     [exec]     [Baseline Warning] Bundle Version Change Recommended: 16.0.0
     [exec]         at org.junit.Assert.fail(Assert.java:88)
     [exec]         at org.junit.Assert.assertTrue(Assert.java:41)
     [exec]         at org.junit.Assert.assertFalse(Assert.java:64)
     [exec]         at com.liferay.semantic.versioning.SemanticVersioningTest.testSemanticVersioning(SemanticVersioningTest.java:82)
     [exec]         at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
     [exec]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

...

     [exec] 
     [exec] com.liferay.semantic.versioning.SemanticVersioningTest > testSemanticVersioning[/apps/object/object-api] FAILED
     [exec]     java.lang.AssertionError:   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec]     = ================================================== ========== ========== ========== ========== ==========
     [exec]     * com.liferay.object.exception                       MAJOR      14.1.0     14.1.0     15.0.0     VERSION INCREASE REQUIRED
     [exec]     	>   class      com.liferay.object.exception.RequiredObjectFieldException
     [exec]     		-   method     <init>(java.lang.String)
     [exec]     			-   return     void
     [exec]     		-   method     <init>(java.lang.String,java.lang.Throwable)
     [exec]     			-   return     void
     [exec]     		-   method     <init>(java.lang.Throwable)
     [exec]     			-   return     void
     [exec]     		+   method     getMessageKey()
     [exec]     			+   return     java.lang.String
     [exec]       com.liferay.object.util                            REMOVED    0.0.0      5.0.0      -          PACKAGE REMOVED, UNNECESSARY PACKAGEINFO
     [exec]     [Baseline Warning] Bundle Version Change Recommended: 55.0.0
     [exec]         at org.junit.Assert.fail(Assert.java:88)
```
---
### Failures in the metrics of the workflow

https://user-images.githubusercontent.com/44584050/214193734-96822a43-6413-44b9-9531-41415168c973.mp4

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
@mateusralv looks like we are making some progress. A handful of these now look pretty flaky. I will re-run and see. Let me know if you notice anything as well

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by mateusralv** [comment]
Hi @bryceosterhaus, We still have some unique failures related to workflow. 

[Testray Comparison](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1674581865622&testrayRunIdA=2171647902&testrayRunIdB=2171870258)

Workflow failures: 

https://user-images.githubusercontent.com/44584050/214395950-c3f20a38-563c-4cac-9924-a102f2584fae.mp4

**Comment by mateusralv** [comment]
cc: @john-co

**Comment by bryceosterhaus** [comment]
@mateusralv I can't seem to reproduce that locally. I get this instead, which doesn't impede functionality

Screen Shot 2023-01-25 at 12 37 39 PM

**Comment by bryceosterhaus** [comment]
Sent a follow up PR here, https://github.com/liferay-frontend/liferay-portal/pull/2999, just to see if CI was caching anything from run to run.

**Pull request closed without merging**
