### PR TITLE
LPS-192545 - Update existing package.json for current dependencies and add eslint rule to enforce convention

### PR DESCRIPTION
**Pull request by bryceosterhaus**
https://liferay.atlassian.net/browse/LPS-192544

Adds an eslint rule to enforce that js dependencies are always specified in the package.json. This will help us in the 
release process

### CODE REVIEW

**Review by markocikos — APPROVED** [review]
@bryceosterhaus LGTM! :sparkles:

**Comment by deborasoliveira** [comment]
I'm on it.

**Comment by bryceosterhaus** [comment]
getting 40min build times with this PR... going to investigate

**Comment by deborasoliveira** [comment]
ci:test:relevant

**Comment by mateusralv** [comment]
ci:test:relevant

**Comment by JerryAdrianoo** [comment]
Hey, @bryceosterhaus can you rebase your branch, please? Thanks in advance.

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
ci:test:sf

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by JerryAdrianoo** [comment]
I'll run relevant again.

**Comment by JerryAdrianoo** [comment]
ci:test:relevant

**Comment by JerryAdrianoo** [comment]
ci:stop

**Comment by JerryAdrianoo** [comment]
Hey @bryceosterhaus I found some failures in js-unit-jdk8/0/0. But the rest is ok. Below is an example.

FAIL test/js/components/share-form/ShareFormModal.js
  ��� Test suite failed to run

    Cannot find module '../../../src/main/resources/META-INF/resources/admin/js/components/share-form/openShareFormModal.es' from 'ShareFormModal.js'

      16 | import ReactDOM from 'react-dom';
      17 | 
    > 18 | import {Modal} from '../../../src/main/resources/META-INF/resources/admin/js/components/share-form/openShareFormModal.es';
         | ^
      19 | 
      20 | import '@testing-library/jest-dom/extend-expect';
      21 | 

      at Resolver.resolveModule (../../../node_modules/jest-resolve/build/index.js:276:11)
      at Object.<anonymous> (test/js/components/share-form/ShareFormModal.js:18:1)
      
Can you take a look, please ? Thanks in advance.

**Comment by bryceosterhaus** [comment]
https://github.com/liferay-frontend/liferay-portal/pull/3638

**Pull request closed without merging**
