### PR TITLE
LPS-121044 The alert message for video field empty is not translated

### PR DESCRIPTION
**Pull request by markocikos**
This is a bugfix. See steps to reproduce in https://issues.liferay.com/browse/LPS-121044

After fix:
screen

Nice little quick win :slightly_smiling_face:

### CODE REVIEW

**Comment by markocikos** [comment]
ci:test:sf

**Comment by markocikos** [comment]
ci:test:relevant

**Review by carloslancha — APPROVED** [review]
I wish all bugs were like this one xD. LGTM!

**Comment by wincent** [comment]
I don't know... I kind of liked the old message with the hyphens. Had a kind of elite "hacker" feel to it.

But whatever...

whatever

**Comment by markocikos** [comment]
ci:forward

**Pull request closed without merging**
