### PR TITLE
LPS-157796 - Only render header JS and header CSS if combo loader is disabled

### PR DESCRIPTION
**Pull request by bryceosterhaus**
Not really sure if this is really the proper place to add these checks, but I couldn't really find a better place to do so.

Before (the bottom 3 requests duplicate the CSS found in the combo):
Screen Shot 2022-07-07 at 1 58 57 PM

After:
Screen Shot 2022-07-07 at 2 03 13 PM

### CODE REVIEW

**Comment by bryceosterhaus** [comment]
ci:stop

**Comment by bryceosterhaus** [comment]
ci:test:sf

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by izaera** [comment]
Can you explain a bit what is the commit doing and the root cause of the problem? :thinking:  
Thx

**Comment by bryceosterhaus** [comment]
Talked with @izaera on slack. Going to forward this for now and then he will follow up in research as he looks to add type="module" support for js resources to the head.

**Comment by bryceosterhaus** [comment]
ci:forward

**Pull request closed without merging**
