### PR TITLE
LPS-114149 Remove logic that was setting placeholder to BLANK on IE >=10

### PR DESCRIPTION
**Pull request by carloslancha**
Removing logic that was setting placeholder to BLANK on IE >=10.

IE10 is no longer supported and behavior described in [LPS-73502](https://issues.liferay.com/browse/LPS-73502), where this fix was introduced in the first place, is no longer reproducible in IE11.

Steps to reproduce:

Using IE11
- Go to blogs
- Add new blog
- Title and subtitle placeholders should appear
- If no subtitle is introduced and blog is published, "subtitle" is not saved as this field value

### CODE REVIEW

**Comment by carloslancha** [comment]
ci:test:sf

**Comment by carloslancha** [comment]
ci:test:relevant

**Comment by brunobasto** [comment]
Screen Shot 2020-08-03 at 17 17 49
Looks good

**Comment by wincent** [comment]
slow-clap-dwight

**Comment by jbalsas** [comment]
If @brunobasto is happy and @wincent is happy and @jbalsas doesn't want to think about Windows for the rest of the week...

shipit

**Comment by jbalsas** [comment]
ci:forward

**Pull request closed without merging**
