### PR TITLE
LPS-120913 CSS Custom properties should not affect borderless buttons

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
See https://issues.liferay.com/browse/LPS-120913 
**Before:**
Screenshot 2020-09-15 at 10 16 29

**After:**
Screenshot 2020-09-15 at 10 18 06

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
@eduardoallegrini please review, and thanks for your help!

**Review by eduardoallegrini — APPROVED** [review]

**Comment by ambrinchaudhary** [comment]
Sending forward as @eduardoallegrini approved the changes ;-)

**Comment by ambrinchaudhary** [comment]
ci:forward

**Pull request closed without merging**
