### PR TITLE
[Don't forward] LPS-121862 Migrate v2 usages in asset/asset-tags-admin-web

### PR DESCRIPTION
**Pull request by julien**
The <clay:management-toolbar-v2 /> tag has been replaced with the
<clay:management-toolbar /> tag (which uses clay v3).

Creating, merging and deleting tags should work as expected.

**Test plan**:
- Navigate to **Categorization**>**Tags**
- Assert that you can create a tag
- Assert that you can delete the tag you created previously
- Assert that you can merge two or more tags correctly.

**Additional notes**
Submitting this as a draft so that @markocikos, @ambrinchaudhary and @jonmak08 can review

### CODE REVIEW

**Review by wincent — COMMENTED** [review]
lg2m but I leave actual approval to _les experts_, @ambrinchaudhary, @jonmak08, @markocikos.

**Comment by ambrinchaudhary** [comment]
LGTM!

**Review by kresimir-coko — APPROVED** [review]

**Comment by wincent** [comment]
At first blush [that unique test failure](https://github.com/liferay-frontend/liferay-portal/pull/823#issuecomment-783396718) doesn't look related, but it could be. I'm going to try re-running it, and in the meantime tag @john-co, @zhangyan0701, @calvinctvo to assess.

**Comment by wincent** [comment]
ci:test:relevant

**Review by markocikos — APPROVED** [review]
LGTM!

**Comment by john-co** [comment]
@calvinctvo , please investigate the test failure.

**Comment by calvinctvo** [comment]
ci:test:bundle

**Comment by calvinctvo** [comment]
Hi @julien and @wincent , the failure on this PR is a known issue from Lima team https://issues.liferay.com/browse/LPS-128068 and somehow it got flagged as unique failure.

**Comment by julien** [comment]
@calvinctvo thanks for the information

**Comment by julien** [comment]
Submitted [here](https://github.com/liferay-echo/liferay-portal/pull/3828)

**Pull request closed without merging**
