### PR TITLE
LPS-119175 Diff version compartor has not enough space/paddings

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
**Steps to reproduce:**

1. Add a wiki page
2. Edit to page to create another version
3. Navigate to page info > Versions > Compare
4. Compare to 1.1 to 1.0
5. View comparison table that appears

**Before the fix:**

No padding in the card, nor the legends. 
wiki comparison actual

**After the fix:** 
The legend text is spaced properly. The diff section has more height and padding (similar in 7.1 version)

Screenshot 2020-08-19 at 13 09 24

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
ci:test:relevant

**Comment by marcoscv-work** [comment]
LGTM

**Review by marcoscv-work — APPROVED** [review]

**Review by eduardoallegrini — APPROVED** [review]
Didn't test it on DXP but the code seems ok to me and we had a conversation about this in slack

**Comment by marcoscv-work** [comment]
ci:forward

**Pull request closed without merging**
