### PR TITLE
[TS] LPS-146513

### PR DESCRIPTION
**Pull request by crodriguezy**
As discussed in https://issues.liferay.com/browse/PTR-2875, this change was suggested in order to improve accessibility and fix the case described in https://issues.liferay.com/browse/LPS-146513:

Steps to reproduce:

1. Enable Jaws screen reader.
2. Go to home page.
3. Use the tab key to reach, for example, the Navigation icon menu. 
4. Press the space tab: check the menu is open and navigate through the options with up and down keys.
5. Press escape key to exit the menu.
6. Navigate to the icon menu again. Jaws says 'Press space tab to open the options'.
7. Press the space tab.

**Expected result**: menu is open

**Current result:** menu is not open

Notes: 

After refreshing the page menu steps 1-7 can be reproduced again. i.e, Space tab opens the menu only the first time after loading the page. This may be because when you click on the icon-menu, a
role="button"
is added to the html element.

Jaws does not inform about the space tab the first time the icon is reached.
Reproduced with Jaws screen reader (default config).
Not reproduced with Window's 11 default screen reader 'Narrator'.

cc/ @pat270

### CODE REVIEW

**Comment by pat270** [comment]
> role="button" is added to the html element.

@crodriguezy Deleting https://github.com/liferay/liferay-portal/blob/0876c4ff2e20691df829d192039047f26cf63508/modules/apps/frontend-js/frontend-js-aui-web/src/main/resources/META-INF/resources/liferay/menu.js#L456 will remove `role="button"`. We don't need it anymore since we are using the `<button>` element.

**Comment by crodriguezy** [comment]
ci:test:relevant

**Comment by crodriguezy** [comment]
hi @pat270 , do you think now the changes look ok? could them be moved forward and backported to the branches?
thanks!

**Comment by crodriguezy** [comment]
Hi @liferay-frontend , does the change look ok? 
Thank you.

**Comment by pat270** [comment]
@crodriguezy LGTM, but looks like it broke some tests. I think it's looking for the `a` element that we changed to `button`.

/cc @john-co do we have a liferay-frontend-qa user?

**Comment by magjed4289** [comment]
Just started reviewing :)

**Comment by magjed4289** [comment]
ci:test:relevant

**Comment by magjed4289** [comment]
ci:close

**Pull request closed without merging**
