### PR TITLE
LPS-183948 | Automation for DatasetPagination

### PR DESCRIPTION
**Pull request by abhnerramos**
**Description**
Automation for
DatasetPagination#CannotUseCharactersInDefaultValueField ([LPS-183948](https://issues.liferay.com/browse/LPS-183948))
DatasetPagination#CanCancelPaginationCreationOnCancelButton ([LPS-183950](https://issues.liferay.com/browse/LPS-183950))
DatasetPagination#ErrorAppearsWhenPaginationItemBlank ([LPS-183940](https://issues.liferay.com/browse/LPS-183940))
DatasetPagination#CanCreateWithOnePaginationItem ([LPS-183941](https://issues.liferay.com/browse/LPS-183941))
DatasetPagination#CannotExceed25PaginationItems ([LPS-183943](https://issues.liferay.com/browse/LPS-183943))
DatasetPagination#CannotExceed1000ItemsPerPage ([LPS-183944](https://issues.liferay.com/browse/LPS-183944))

**JIRA Ticket**
https://issues.liferay.com/browse/LPS-183948

### CODE REVIEW

**Comment by abhnerramos** [comment]
ci:test:frontend-data-set

**Review by CarlosBrichete — APPROVED** [review]

**Comment by CarlosBrichete** [comment]
LGTM :)

**Comment by abhnerramos** [comment]
ci:test:frontend-data-set

**Comment by abhnerramos** [comment]
ci:forward

**Pull request closed without merging**
