### PR TITLE
LRQA-83852 Test Fix DataSetFragment#CanAddDataSetView

### PR DESCRIPTION
**Pull request by JerryAdrianoo**
**Description:**
Fixing some failures in the macro that made it impossible to add a view to the page.

**Jira Ticket:**
https://liferay.atlassian.net/browse/LRQA-83852

### CODE REVIEW

**Comment by JerryAdrianoo** [comment]
ci:test:frontend

**Comment by JerryAdrianoo** [comment]
ci:test:frontend

**Comment by JerryAdrianoo** [comment]
ci:test:frontend

**Comment by JerryAdrianoo** [comment]
@CarlosBrichete these failures aren't related

**Comment by JerryAdrianoo** [comment]
ci:test:sf

**Review by CarlosBrichete — APPROVED** [review]
LGTM

**Comment by JerryAdrianoo** [comment]
ci:forward

**Pull request closed without merging**
