### PR TITLE
LPS-141928 The user list cannot be displayed when mentioning user in some special places

### PR DESCRIPTION
**Pull request by boton**
BUG 🐛 : https://issues.liferay.com/browse/LPS-141928

**Steps to Prepare:**
1. Login 
2. Add a new widget page with a blog/mb/dm/wiki widget
3. Go to the widget to add a new entry
4. Add comment to this entry

**Steps to Reproduce: (no reloads in the middle of the process)**

1. Logout
2. Login
3. Go to the new page with the blog/mb/dm/wiki widget
4. reply to a previous comment
5. Mention other users

---

At first, I tried to understand the bug but I was getting stuck in AUI :(

The next strategy is to use the RCA information and revert this commit bb2ad29705910473f7069b569067db4a6842a842, this fixed the problem.

I want to find the faulty change, at first, I discard this change because looks naif and test others but in the end, it is the cause.

If anyone understands the problem please I am all ears 👂 🥺 

**Before FIX**

https://user-images.githubusercontent.com/67901/140512575-e0c69ad3-3b08-4290-8b83-539f10713815.mp4

**After FIX**

https://user-images.githubusercontent.com/67901/140512424-b1ce6ff6-bb99-44ee-882f-513af833976f.mp4

### CODE REVIEW

**Comment by boton** [comment]
ci:test:relevant

**Comment by matuzalemsteles** [comment]
Hey @boton I don't understand the link between the fix and the bug 😅, it's actually pretty weird how it fixed it. And apparently, they reversed the commit on master https://github.com/liferay-frontend/liferay-portal/commit/bc0148c2ced4ee08cebd7da4aa23b0f6ecc82ed5. cc @kresimir-coko

**Comment by boton** [comment]
@matuzalemsteles I'm not sure but looks like some internals in `A.mix` but I don't understand the connection between the fix and the bug either 😞  .

I'm going to close this PR because the origin is reverted and the job is done.

**Comment by matuzalemsteles** [comment]
@boton don't worry, I've imagined something out with `A.mix` internals too.

**Comment by kresimir-coko** [comment]
Hey @matuzalemsteles & @boton the comment above that mentioned me got buried in my mail and I just saw it now. The changes got reverted but I opened a PR that reintroduces them but it should work this time 👍 

The problem was that `A.merge()` creates a new object and then combines the objects passed as arguments into that new object, whereas `Object.assign(sourceObj, otherObj)` assigns `otherObj` to `sourceObj` and it's the mutation that causes the errors.

**Comment by boton** [comment]
Hey @kresimir-coko 

For me, the merge with only one object like `A.merge(object)` works equal that `{...object}` or `Object.assign({}, object)`, I'm missing something?

I took at the new PR and have the same change, the problem isn't the merge itself but if [we remove](https://github.com/liferay-frontend/liferay-portal/pull/1653/files?authenticity_token=6gKx3wzPRzeoJuQjUQx3ZA5j35AK9eMrpCVRnO8sb4DueGL38TC1FFvvmc22TB7BMVpT7h2SyoQXf%2FkSSyB6og%3D%3D&file-filters%5B%5D=.js#diff-e0a97383294cb2d44d84a879df494eec9e0c636f666d028ee3d7c70d547dbde8L284-L286) the merge probably we will have the bug reopened again, maybe is related to the next `A.mix`.

Can you please verify that this bug is not reintroduced by this new PR?

**Comment by kresimir-coko** [comment]
@boton I'll double-check tomorrow so I have time for `ant all` and all that nonsense, I'll put the PR as a draft until I confirm it works 👍

**Comment by boton** [comment]
Thanks @kresimir-coko :D

**Pull request closed without merging**
