### PR TITLE
LPS-142330 | A11yTool - Verifies the correct target and code is displayed for the second violation

### PR DESCRIPTION
**Pull request by susanchen3**
**Background**
Create automated tests for the A11y tool

**Test Plan**
- Click on the violation with 2 occurrences
- Click on the 2nd occurrence
- Assert the correct target and code is displayed

**JIRA Ticket:**
https://issues.liferay.com/browse/LPS-142330

### CODE REVIEW

**Comment by susanchen3** [comment]
ci:test:frontend:nocompile

**Comment by susanchen3** [comment]
unrelated to my changes

**Comment by susanchen3** [comment]
ci:test:frontend:nocompile

**Review by zhangyan0701 — APPROVED** [review]
Looks good to me!

**Comment by susanchen3** [comment]
ci:forward

**Pull request closed without merging**
