### PR TITLE
LPS-167280 Add liferay npm scripts to trigger packageRunCheck task

### PR DESCRIPTION
**Pull request by Seiphon**
cc @ling-alan-huang

### CODE REVIEW

**Comment by Seiphon** [comment]
ci:test:relevant

**Comment by Seiphon** [comment]
ci:test:sf

**Comment by Seiphon** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
Looks good to me! Just need passing tests on relevant or QA sign off before forwarding

**Comment by deborasoliveira** [comment]
I'll take a look at it 🧐

**Comment by deborasoliveira** [comment]
Hello @Seiphon!
I've analyzed the failures and they seem to be unrelated to your PR according to this [comparison](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=2&testrayRunIdB=2166042384&testrayRunIdA=2166315013&statusB=3).

cc: @john-co, @mateusralv

**Comment by Seiphon** [comment]
> Looks good to me! Just need passing tests on relevant or QA sign off before forwarding

Thank you @deborasoliveira, should I rebase this pr to the latest master and rerun the test?

**Comment by izaera** [comment]
@Seiphon no, just manually send it to Brian (by creating a new PR based off of this branch), add a comment here to cross link them for future reference, and close this one.

Rebase is optional but, unless you expect some conflicts when Brian merges, it's not necessary because Brian does it when pulling your PR.

Also, if you decide to rebase, there's no need to run the tests again, unless you had so many conflicts that you are not sure of whether you resolved them correctly.

**Comment by Seiphon** [comment]
> @Seiphon no, just manually send it to Brian (by creating a new PR based off of this branch), add a comment here to cross link them for future reference, and close this one.
> 
> Rebase is optional but, unless you expect some conflicts when Brian merges, it's not necessary because Brian does it when pulling your PR.
> 
> Also, if you decide to rebase, there's no need to run the tests again, unless you had so many conflicts that you are not sure of whether you resolved them correctly.

OK, well noted, thanks @izaera

**Comment by Seiphon** [comment]
ci:reopen

**Comment by Seiphon** [comment]
`
warning package.json: License should be a valid SPDX license expression
warning ../../../../../package.json: No license field
warning package.json: License should be a valid SPDX license expression
[1/4] Bumping version...
info Current version: 6.0.6
[2/4] Logging in...
[3/4] Publishing...
error Couldn't publish package: "https://registry.npmjs.org/@liferay%2ffrontend-css-common: You must sign up for private packages"
info Visit https://yarnpkg.com/en/docs/cli/publish for documentation about this command.


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':apps:frontend-css:frontend-css-common:publishNodeModule'.
> Process 'command '/home/brian/dev/projects/github/liferay-portal/build/node/bin/node'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org/
`

Hi guys, after Brain merged this pr, when publishing the pacakage this failure will happen. If I add "private": true to package.json, can it resolve this failure? (It happens only when publishing)

**Comment by izaera** [comment]
@Seiphon We don't manage the gradle plugin that makes the releases, so we have no idea on how to disable it. I would say you need to raise the question in Slack.

**Comment by Seiphon** [comment]
> 

OK, thank you!

**Pull request closed without merging**
