### PR TITLE
LPS-175504 Removes soy dependency from modules, since it is not used

### PR DESCRIPTION
**Pull request by ealonso**
Motivation
----
Removes unnecessary dependencies from modules to soy

### CODE REVIEW

**Comment by carloslancha** [comment]
<a href="https://gitme.me/image?url=https%3A%2F%2Fmedia0.giphy.com%2Fmedia%2Fl3JDnePt8MlFnFApq%2Fgiphy.gif&token=fire" data-gitmeme-token="fire"></a>

LGTM

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by mateusralv** [comment]
Hi @ealonso I took a look and the failures are not related to your PR. Safe to forward manually 

[Testray comparison](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1676382964635&testrayRunIdA=2196356432&testrayRunIdB=2196467859)

**Pull request closed without merging**
