### PR TITLE
LPS-183938 | Automation for DatasetPagination#CanAssertDefaultValues

### PR DESCRIPTION
**Pull request by abhnerramos**
**Description**
> Given access to the Datasets admin page
> And The user goes to add a new Dataset
> And Add a new view
> When goes to Fields Tab.
> Then the default values for Pagination items will be 4, 8, 20, 40, 60, separated by commas
> And The default value for the Default Value field is 20

**JIRA Ticket**
https://issues.liferay.com/browse/LPS-183938

### CODE REVIEW

**Comment by abhnerramos** [comment]
ci:stop

**Comment by abhnerramos** [comment]
ci:test:frontend-data-set

**Comment by abhnerramos** [comment]
ci:test:sf

**Comment by abhnerramos** [comment]
ci:test:frontend-data-set

**Review by CarlosBrichete — APPROVED** [review]

**Comment by abhnerramos** [comment]
ci is having some problems to run the suits :\ 
I'll run it again

**Comment by abhnerramos** [comment]
ci:forward

**Pull request closed without merging**
