### PR TITLE
LPS-187592 Adding tests for CX with Data Set fragment

### PR DESCRIPTION
**Pull request by JerryAdrianoo**
**Description:**
Adding tests for the CX - Data Set to see the apple icon and deploy a client extension.
Based in this thread -> [link](https://liferay.slack.com/archives/CL3TWSMHQ/p1696422634537479), I putted the FDS file inside the global dependencies.

**Jira Ticket:**
https://liferay.atlassian.net/browse/LPS-187592

### CODE REVIEW

**Comment by JerryAdrianoo** [comment]
ci:test:frontend-data-set

**Comment by JerryAdrianoo** [comment]
ci:help

**Comment by JerryAdrianoo** [comment]
ci:test:frontend-client-extensions

**Comment by JerryAdrianoo** [comment]
ci:stop

**Comment by JerryAdrianoo** [comment]
ci:test:frontend-data-set

**Comment by JerryAdrianoo** [comment]
ci:test:frontend

**Comment by JerryAdrianoo** [comment]
ci:test:frontend

**Comment by JerryAdrianoo** [comment]
ci:stop

**Comment by JerryAdrianoo** [comment]
ci:test:frontend

**Comment by JerryAdrianoo** [comment]
ci:test:sf

**Comment by JerryAdrianoo** [comment]
ci:test:frontend

**Comment by JerryAdrianoo** [comment]
ci:test:frontend

**Comment by JerryAdrianoo** [comment]
ci:stop

**Comment by JerryAdrianoo** [comment]
ci:stop

**Comment by JerryAdrianoo** [comment]
ci:test:stop

**Comment by JerryAdrianoo** [comment]
ci:test:sf

**Comment by JerryAdrianoo** [comment]
ci:test:sf

**Comment by JerryAdrianoo** [comment]
ci:test:frontend

**Comment by JerryAdrianoo** [comment]
ci:test:frontend

**Comment by JerryAdrianoo** [comment]
ci:test:frontend

**Comment by JerryAdrianoo** [comment]
ci:test:frontend

**Comment by JerryAdrianoo** [comment]
ci:test:stop

**Comment by JerryAdrianoo** [comment]
ci:test:frontend

**Comment by JerryAdrianoo** [comment]
cc @CarlosBrichete These failures are not related, and this automation fixed these two issues: 

1. [FrontendDataSetClientExtension#AssertTheCellRendererIsDisplayed](https://testray.liferay.com/home/-/testray/case_results/2440700312?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2440696285%26testrayRunId%3D2440696308%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc)
2. [FrontendDataSetClientExtension#CanAssertClientExtensionInDropdown](https://testray.liferay.com/home/-/testray/case_results/2440700356?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2440696285%26testrayRunId%3D2440696308%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc)


**Ticket:** https://liferay.atlassian.net/browse/LRQA-82935

**Review by CarlosBrichete — APPROVED** [review]
LGTM

**Comment by CarlosBrichete** [comment]
ci:forward

**Comment by JerryAdrianoo** [comment]
ci:forward:force

**Comment by JerryAdrianoo** [comment]
ci:forward:force

**Comment by CarlosBrichete** [comment]
ci:forward

**Pull request closed without merging**
