### PR TITLE
LPS-143885 Move remaining files and tag from frontend-taglib-clay to a dedicate module

### PR DESCRIPTION
**Pull request by LuismiBarcos**
Related ticket -> [LPS-143885](https://issues.liferay.com/browse/LPS-143885)

The purpose of this branch is to move the logic of the data-set-display from the module `frontend-taglib-clay` to `frontend-data-set` 

I copied, pasted and renamed the remaining files from frontend-taglib-clay to frontend-data-set. I set the files in the module I consider that it belongs (-api, -impl, -taglib...).

To test this I migrate two modules (not in this PR) and, doing that, I realized that other teams are adding more logic to the module `frontend-taglib-clay` doing the migration more difficult.

As we are going to do the migration of the components that are using these tags, we can take care of migrating these new files but, at the time we start to do the migration, I suppose that we have to tell the other teams that the module `frontend-data-set`  will be the new place for the logic of the data set display.

This PR is a follow up of [this request](https://github.com/brianchandotcom/liferay-portal/pull/111961#issuecomment-1010199660)

### CODE REVIEW

**Comment by LuismiBarcos** [comment]
FYI @javierdearcos @markocikos

**Comment by LuismiBarcos** [comment]
ci:forward

**Review by markocikos — APPROVED** [review]
@LuismiBarcos please update semver

**Comment by LuismiBarcos** [comment]
Updated semver. Trying again

**Comment by magjed4289** [comment]
ci:help

**Pull request closed without merging**
