### PR TITLE
LPS-119736 Menu must be closed using the modal closing method to correctly handle the animation

### PR DESCRIPTION
**Pull request by carloslancha**
https://issues.liferay.com/browse/LPS-119736

Applications Menu fading / sliding on close animation wasn't working when closing the menu with the keyboard shortcut (CMD + SHIFT + M).

Modal's hook `onClose` method needs to be used to close the menu to make this work.

Steps to reproduce:
- Go to Home
- Press `CMD` + `SHIFT` + `M`. The Menu should open sliding from top.
- Press `CMD` + `SHIFT` + `M`. The Menu should close sliding and fading to top.

### CODE REVIEW

**Comment by carloslancha** [comment]
ci:test:sf

**Comment by carloslancha** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
Looks and feels great to me! Forwarding manually to @liferay-echo!

**Comment by jbalsas** [comment]
Forwarded https://github.com/liferay-echo/liferay-portal/pull/2155

**Comment by ealonso** [comment]
ci:forward

**Comment by carloslancha** [comment]
ci:forward

**Pull request closed without merging**
