### PR TITLE
LPD-36212, LPD-37203, LPD-36188 Allow using directive script-src-attr 'none' by removing inline handlers

### PR DESCRIPTION
**Pull request by izaera**

### CODE REVIEW

**Comment by izaera** [comment]
ci:test:relevant

**Comment by izaera** [comment]
ci:report:21374943

**Comment by izaera** [comment]
ci:test:sf

**Comment by izaera** [comment]
ci:test:relevant

**Comment by izaera** [comment]
I've found some errors in this PR while working on https://github.com/liferay-frontend/liferay-portal/pull/4407, so I'm fixing them and will push the fixes here to retest again.

**Comment by izaera** [comment]
ci:test:sf

**Comment by izaera** [comment]
ci:test:relevant

**Comment by izaera** [comment]
And here's how a failed playwright test would look like:

image

**Comment by izaera** [comment]
ci:report:24471916

**Comment by izaera** [comment]
Failed tests:

1. SharingDLViewFileVersionDisplayContextTest :heavy_check_mark:  (passes locally)
2. KBArticleStagedModelDataHandlerTest
3. LinkedProductResourceTest
4. MappedProductResourceTest
5. PinResourceTest
6. ProductOptionResourceTest
7. ProductResourceTest
8. ProductSpecificationResourceTest
9. RelatedProductResourceTest
10. SkuResourceTest
11. WishListItemResourceTest
12. WishListResourceTest
13.

**Comment by izaera** [comment]
ci:test:sf

**Comment by izaera** [comment]
ci:test:relevant

**Comment by izaera** [comment]
ci:report:27144611

**Comment by izaera** [comment]
IMO this is clear to forward...

**Comment by dsanz** [comment]
LGTM ;) 

Good job Iván

**Comment by izaera** [comment]
ci:forward:force

**Pull request closed without merging**
