### PR TITLE
LPS-167705 Collapsible fieldsets should announce on screen readers co…

### PR DESCRIPTION
**Pull request by pat270**
…rrectly

https://issues.liferay.com/browse/LPS-167705

I couldn't find an easy way to get `aria-orientation="vertical"` and `role="tablist"` to print out only for collapsible fieldsets without touching every component that used this pattern. The good news is these attributes don't affect the screen reader readout when `collapsible="<%= false %>"`.

I got rid of the `legend` tag in collapsible panels since the `fieldset` is described by the title. `legend` is an optional element in `fieldset` according to https://developer.mozilla.org/en-US/docs/Web/HTML/Element/fieldset#technical_summary.

### CODE REVIEW

**Comment by dsanz** [comment]
This fix can work while we provide the <clay:panel> tag (see https://github.com/liferay-frontend/liferay-portal/pull/3414), my only concern is the `tab` panel titles are still `<a role="tab">` rather than `<button>`. Would this be ok @marcoscv-work?

**Comment by mateusralv** [comment]
I'm taking a look 🕵🏽

**Comment by dsanz** [comment]
ci:forward:force

**Comment by dsanz** [comment]
ci:forward:force

**Pull request closed without merging**
