### PR TITLE
LPS-140078 Support importing .json files

### PR DESCRIPTION
**Pull request by bryceosterhaus**
Previous https://github.com/liferay-frontend/liferay-portal/pull/1597

https://issues.liferay.com/browse/LPS-140078

We updated a rule in our eslint-config, which applies quote-props rule to be consistent in objects when needed ([issue reference](https://github.com/liferay/liferay-frontend-projects/issues/3)). Because eslint and prettier overlap a bit, we had to also add the quoteProps config to prettier.

Prettier config lives in npm-scripts, and so because that was released, it included this new rule via prettier even though we haven't released eslint-config yet with that new rule.

Thus, all of these changes stem from that auto-format from prettier.

### CODE REVIEW

**Comment by kresimir-coko** [comment]
@bryceosterhaus Tiny mistake => `Expected object keys to be in natural ascending order. 'quoteProps' should be before 'useTabs'.  sort-keys`

**Comment by bryceosterhaus** [comment]
ci:test:sf

**Comment by bryceosterhaus** [comment]
ci:test:sf

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Pull request closed without merging**
