### PR TITLE
[TS] LPS-125037 Apply button in Filter by Field panel is not shown correctly after trying to modify the value that we set earlier

### PR DESCRIPTION
**Pull request by bakayattila**
hi Team,
Could you please review this pull request?
https://issues.liferay.com/browse/LPS-125037

best,
Attila
____________________________________________________________________

Steps

Setup Liferay DXP 7.2 with
Create a new structure with a Text field
Create a new web content with the structure
In the field
On the Home page add an Asset Publisher
Go to the configuration panel of the Asset Publisher→Display Settings
Asset Selection: Dynamic
Asset Type: Web Content Article
Web Content Article Structures: Basic Web Content
Filter by Field: YES
Click on Select
Check the new form

Expected Behavior
Only the apply button of the selected radio button is enabled

Actual Behavior
All the apply buttons enabled

The main reason behind the null check here is to prevent unnecessary modification on any form that is not related to asset selection.

### CODE REVIEW

**Comment by jbalsas** [comment]
Test error was flagged last week, so I'm going to rerun to see this green.

@bakayattila, while we wait to get confirmation from CI, could you please take some time to read through the following submission guidelines and update the PR with the suggestions below?
- [Pull Request Etiquette](https://github.com/liferay/liferay-frontend-projects/blob/master/guidelines/general/pull_requests.md#pull-request-etiquette)
- [Frontend Infrastructure Team code review process](https://github.com/liferay/liferay-frontend-projects/blob/master/guidelines/dxp/code_review.md#frontend-infrastructure-team-code-review-process)

In summary, we'd appreciate if you could provide:
- Descriptive title beyond a mere LPS ✅ 
- Thorough description of the issue, things you tried, why you thing your solution is the right approach and any other considerations that might help us in our review 🔴 
- Test plan with simple steps to validate the issue (or get a feeling of how it has been validated by you) 🔴 

I understand some of these might already be covered in the LPS itself, but having some of that data here helps us track it down and trace it when things move from user to user and allows us to focus on the review itself.

Thanks for your help in making this process better for everyone!! ❤️

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by bakayattila** [comment]
Hi @jbalsas , I updated the PR. I hope it is acceptable now.

**Comment by jbalsas** [comment]
> Hi @jbalsas , I updated the PR. I hope it is acceptable now.

Thanks @bakayattila, appreciate the effort!! 🤗 

> The main reason behind the null check here is to prevent unnecessary modification on any form that is not related to asset selection.

This is the kind of information that is interesting and helps speed up the process! 😉

**Comment by jbalsas** [comment]
I haven't tested this, but changes kinda make sense, so I'm going to take your word for it assuming you've done the proper manual testing since this is an old part of portal and automatic test coverage is not going to help us much.

Thanks!

**Comment by jbalsas** [comment]
ci:forward

**Pull request closed without merging**
