### PR TITLE
LPS-144301 - Update test to use testing-library v12

### PR DESCRIPTION
**Pull request by victorg1991**
This is ready to be reviewed :) 

Missing modules:

- [x] modules/apps/batch-planner/batch-planner-web
- [x] modules/apps/commerce/commerce-frontend-js
- [x] modules/apps/data-engine/data-engine-js-components-web
- [x] modules/apps/data-engine/data-engine-taglib
- [x] modules/apps/dynamic-data-mapping/dynamic-data-mapping-form-field-type
- [x] modules/apps/dynamic-data-mapping/dynamic-data-mapping-form-web
- [x] modules/dxp/apps/portal-workflow/portal-workflow-metrics-web

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:stop

**Comment by sergiojimcos** [comment]
Just starting to review the PR

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
ci:reevaluate:1317401_1631

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by sergiojimcos** [comment]
Just starting review!

**Comment by sergiojimcos** [comment]
Hi @victorg1991! I've just reviewed your PR and this is what I have came into some conclusions when I analysed the failed tests:

- The majority of the failed tests are flaky ones.
- There are two tests related to **Forms**, both of them are flaky ones and are unrelated to your changes.
- There is a fix test that is unrelated to your changes (_ExperienceCreateExperience#DuplicateExperience_).
- There some fixed test that are related to Analytics Cloud, for that reason they are unrelated to your changes.

In conclusions, your 99.9% of assurance is going to be 100% 😁

**Review by julien — APPROVED** [review]
:heart: Thanks for taking the time to update this

**Comment by julien** [comment]
Manually forwarded https://github.com/brianchandotcom/liferay-portal/pull/111788

**Pull request closed without merging**
