### PR TITLE
LPS-167193 Do not apply animation in portlet topper when it is focused by keyboard

### PR DESCRIPTION
**Pull request by veroglez**
Hi guys! 
I send you a fix for this ticket: https://issues.liferay.com/browse/LPS-167193
I hope you can take a look, thanks!

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
ci:test:stable

**Comment by eltonccdantas** [comment]
ci:test:frontend:nocompile

**Comment by eltonccdantas** [comment]
I'll take a look at it

**Comment by eltonccdantas** [comment]
Hi @veroglez , I've analyzed the errors and they look unrelated to your PR according to the [comparison](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=2&testrayRunIdB=2060569559&testrayRunIdA=2057743999&statusB=3). You may manually forward if no other dev review is needed.

**Comment by bryceosterhaus** [comment]
cc @pat270 can you just verify this css? It's been a long time for me and wasn't sure if we support this sort of syntax of `@include media-breakpoint-up(`

**Comment by marcoscv-work** [comment]
**Following accessibility pending issues I've reviewed this one**, it looks perfect for me, **JAWS works correctly**! Perfect example about how to play animations when the correct input hit the animate trigger.

`@include media-breakpoint-*` is used 11 times in the same file so even if we can change that part I would be ahead and if you guys want to update that part I woulds create a different task.

So LGTM!

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
