### PR TITLE
LPS-189206 Apply order of fields in the fragment

### PR DESCRIPTION
**Pull request by dsanz**
In this PR we are using the information about the relative order of fields that the data set app stores in a given view to sort the list of fields we send to the FDS component. This way the table will show the columns in the order specified by the user for the fields when creating the view

### CODE REVIEW

**Review by markocikos — APPROVED** [review]
@dsanz LGTM! :sparkles:

**Comment by dsanz** [comment]
ci:reevaluate:1297401_7575

**Comment by dsanz** [comment]
ci:reevaluate:1297401_7575

**Comment by dsanz** [comment]
Hi @mateusralv would you mind checking the relevant failures? they seem not related, this PR just changes the order of columns in the dataset fragment. Thanks a lot

**Comment by mateusralv** [comment]
Hi @dsanz I'm on it!

**Comment by mateusralv** [comment]
The failures are not related!

[Testray comparison](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1688136355484&testrayRunIdA=2365688422&testrayRunIdB=2366116877)

**Pull request closed without merging**
