### PR TITLE
LPD-23920 - Add default data to prevent FDS configuration errors

### PR DESCRIPTION
**Pull request by juanjofgliferay**
## Task
https://liferay.atlassian.net/browse/LPD-23920

## Goal
We need to provide data for every Data Set we need to test in the fragment. Otherwise, the FDS component will fail silently and the fragment will not receive the correct configuration.

Remove Settings test that was expecting an empty view. There is an ongoing conversation to fix that. [See slack thread](https://liferay.slack.com/archives/C3JBR21HA/p1713781391888969)

### CODE REVIEW

**Review by markocikos — APPROVED** [review]
@juanjofgliferay LGTM! :sparkles:

**Comment by juanjofgliferay** [comment]
ci:stop

**Comment by juanjofgliferay** [comment]
ci:test:frontend-data-set

**Comment by juanjofgliferay** [comment]
It seems that relevant finished some time ago 🤷 

Screenshot 2024-04-24 at 08 35 09

**Comment by juanjofgliferay** [comment]
ci:forward

**Pull request closed without merging**
