### PR TITLE
LPS-119377 Update the version of ClayPopover to 3.4.5

### PR DESCRIPTION
**Pull request by matuzalemsteles**
This update is only for the `@clayui/popover` package that includes the https://github.com/liferay/clay/issues/3625 fix to unlock the App Builder team with an FP5.

### CODE REVIEW

**Comment by matuzalemsteles** [comment]
ci:test:sf

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
LGTM, @matuzalemsteles! Can you also add the FP5 blocker link here so we can track it down? For cases like this, in the future, I'd say it's enough to use that same LPS rather than creating one specific to update clay.

**Comment by matuzalemsteles** [comment]
@jbalsas yeah a good idea, I hadn't thought of that. I asked guys for the ticket, as soon as I receive it I will update it here.

cc @interaminense @kevenleone

**Comment by kevenleone** [comment]
@matuzalemsteles , thanks for fix it.

@jbalsas , we have no longer the FP5, that issue was downgraded to FP3.

You can see here: https://issues.liferay.com/browse/LPS-118777

**Comment by matuzalemsteles** [comment]
CI green, going ahead.

**Comment by matuzalemsteles** [comment]
ci:forward

**Pull request closed without merging**
