### PR TITLE
LPS-119291 bug blogs dropdown actions a11y

### PR DESCRIPTION
**Pull request by boton**
Hi,

Trying to avoid keyboard issues in Blogs with the dropdown we move the old implementation of dropdown in blogs to the new `<clay:dropdown-actions` as @jbalsas suggest to me.

But we find a problem with the`<clay:dropdown-actions` renders the dropdown button even if doesn´t have dropdown items we try to fix this in the DropdownMenuTag.java cad6ee2 instead of adding ifs everywhere.

What do you think about this change?

Previously revised here: liferay-lima#1606

### CODE REVIEW

**Comment by boton** [comment]
ci:test:relevant

**Review by jbalsas — APPROVED** [review]
Looks great to me!! Waiting for CI before forwarding!

verygood

**Comment by adolfopa** [comment]
ci:reevaluate:1217401_7727

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by liuxingye** [comment]
ci:test:relevant

**Comment by boton** [comment]
🎉  thanks guys for the test relevant 😄

**Comment by jbalsas** [comment]
ci:forward

**Pull request closed without merging**
