### PR TITLE
 LPS-140133 visual adjustments to TranslationAdmin to match Figma design 

### PR DESCRIPTION
**Pull request by tinycarol**
### References

- [LPS-140133](https://issues.liferay.com/browse/LPS-140133)

### What is the goal?

Update TranslationAdmin to match Figma design
* Align dropdown translations status labels to the right
* Use small icon for search bar `+` sign 
* Restructure `TranslationAdminContent`:
   * Add another `ClayModal.Header` without close icon and move the search bar there
   * Fix paddings for specific components
      * The Clay team will add a border-top to `ClayModal.Body` when there's content between `ClayModal.Header` and `ClayModal.Body` so we don't need multiple `ClayModal.Header`s 

### A picture is worth a thousand words

|Where|Dropdown|Modal | Video
---|---|---|---
[Figma](https://www.figma.com/file/I1gFWSJ9gHIubnC4SsIl9h/lexi-1236-review-delete-translations?node-id=43%3A82) |image | image | -
Before PR | image| image | https://user-images.githubusercontent.com/6642927/137739718-149311b9-b2f9-4296-a9bb-834b96120541.mov
After PR | image|image | https://user-images.githubusercontent.com/6642927/137741926-6fe24622-8b7f-425b-a94a-0d54821a1959.mov

### How to replicate
* Go to Content & Data > Web Content
* Create at least two new Basic Web Contents
* Open translation dropdown
   * See that the `Manage translations` icon's spacing is the same as the language flags
   * See that the translation statuses are now aligned to the right
* Click on `Manage translations`
   * See that the search is bar now displayed in a separate section
   * See that if you add many languages and you scroll the table, the search bar is still visible
   * See that the `+` icon to the right of the search bar is now smaller 

### Checklist

- ~~[ ] I have made corresponding changes to the documentation~~
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have checked this works in the corresponding browser

### CODE REVIEW

**Comment by tinycarol** [comment]
ci:test:sf

**Comment by tinycarol** [comment]
ci:test:sf

**Comment by tinycarol** [comment]
ci:test:relevant

**Comment by diegonvs** [comment]
ci:forward

**Comment by tinycarol** [comment]
ci:forward

**Pull request closed without merging**
