### PR TITLE
LPS-127831 Sets proper active class depending on search container displayStyle

### PR DESCRIPTION
**Pull request by jbalsas**
After dropping the BS3-BS4 compat layer, the `active` class no longer works for table displays which need the `table-active` class instead.

This commit makes it so the `table-active` class is used for tables (default displayStyle) and `active` for any other visualization.

This is a continuation of https://github.com/liferay-frontend/liferay-portal/pull/821 because I couldn't push to @pat270's origin...

### CODE REVIEW

**Comment by wincent** [comment]
ci:test:bundle

**Comment by wincent** [comment]
Code looks good to me, but I fired off a `ci:test:bundle` in case @marcoscv-work or @pat270 want to run and test this without having to pull it down and build it.

**Comment by jbalsas** [comment]
> 1 Test Failed.

youdidnt

**Comment by john-co** [comment]
[Unrelated]

- LocalFile.CommerceSmoke#PublishSimpleProduct - Test looks flaky, failing on `SelectFrame.selectFrameNoLoading(locator1 = "IFrame#MODAL_BODY");` I think test step needs to waitFor the Iframe to load, suggest replace with `SelectFrame(locator1 = "IFrame#MODAL_BODY");`

cc/ @iovaneale please investigate and fix/quarantine flaky test.

**Pull request closed without merging**
