### PR TITLE
LPS-148154 Add priority as sortable and filtrable field of ContentElement

### PR DESCRIPTION
**Pull request by ccorreagg**
Related ticket: [LPS-148154](https://issues.liferay.com/browse/LPS-148154)

This PR contains the code for providing the field "priority" as sortable and filtrable for ContentElement GET methods.

**Before the PR:**

_Request:_
```
curl -X 'GET' \
  'http://localhost:8080/o/headless-delivery/v1.0/sites/20124/content-elements?filter=priority%20gt%201.1&sort=priority%3Adesc' \
  -H 'accept: application/json' \
  -u 'test@liferay.com:test'
```
_Response:_ HTTP Code **400**
```
{
  "status": "BAD_REQUEST",
  "title": "A property used in the filter criteria is not supported: prioritys gt 1.1"
}
```

**After the PR:**

_Request:_
```
curl -X 'GET' \
  'http://localhost:8080/o/headless-delivery/v1.0/sites/20124/content-elements?filter=priority%20gt%201.1&sort=priority%3Adesc' \
  -H 'accept: application/json' \
  -u 'test@liferay.com:test'
```
_Response:_ HTTP Code **200**
```
{
  "actions": {},
  "facets": [],
  "items": [
    {
      "content": {
        "actions": {},
        "availableLanguages": [
          "en-US"
        ],
        "contentFields": [
          {
            "contentFieldValue": {
              "data": "<p>My web content</p>"
            },
            "dataType": "string",
            "label": "content",
            "name": "content",
            "nestedContentFields": [],
            "repeatable": false
          }
        ],
        "contentStructureId": 42397,
        "creator": {
          "additionalName": "",
          "contentType": "UserAccount",
          "familyName": "Test",
          "givenName": "Test",
          "id": 20128,
          "name": "Test Test"
        },
        "customFields": [],
        "dateCreated": "2022-03-22T17:25:20Z",
        "dateModified": "2022-03-22T17:25:21Z",
        "datePublished": "2022-03-22T17:25:00Z",
        "description": "",
        "externalReferenceCode": "44411",
        "friendlyUrlPath": "my-web-content",
        "id": 44413,
        "key": "44411",
        "keywords": [],
        "numberOfComments": 0,
        "priority": 1.2,
        "relatedContents": [],
        "renderedContents": [
          {
            "contentTemplateId": "BASIC-WEB-CONTENT",
            "contentTemplateName": "Contenido web básico",
            "markedAsDefault": true,
            "renderedContentURL": "http://localhost:8080/o/headless-delivery/v1.0/structured-contents/44413/rendered-content/BASIC-WEB-CONTENT"
          }
        ],
        "siteId": 20124,
        "subscribed": false,
        "taxonomyCategoryBriefs": [],
        "title": "My web content",
        "uuid": "f2155336-1eae-d83d-eff7-588e95b0ea77"
      },
      "contentType": "StructuredContent",
      "id": 44413,
      "title": "My web content"
    }
  ],
  "lastPage": 1,
  "page": 1,
  "pageSize": 20,
  "totalCount": 1
}
```

### CODE REVIEW

**Comment by ccorreagg** [comment]
ci:reevaluate:1377401_1118

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by LuismiBarcos** [comment]
CI errors seem related, right?

**Review by LuismiBarcos — APPROVED** [review]
LGTM :)

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
ci:test:relevant

**Review by LuismiBarcos — APPROVED** [review]
Reviewed doing pair programming 🥳

**Comment by LuismiBarcos** [comment]
ci:forward

**Pull request closed without merging**
