### PR TITLE
LPS-160310 Headless API is unable to get global vocabularies on virtual instance

### PR DESCRIPTION
**Pull request by thektan**
https://issues.liferay.com/browse/LPS-160310

### Motivation
The search team is using the `/o/headless-admin-taxonomy/v1.0/sites/${SITE_ID}/taxonomy-vocabularies` endpoint to get vocabularies for a category selection autocompletion and modal. This was throwing an error on the virtual site. (This is a PR of the component we're building: https://github.com/liferay-search/liferay-portal/pull/496)

On the virtual instance, the global site had more asset types for the vocabularies (unknown as to why) and due to the missing `com.liferay.portal.kernel.repository.model.FileEntry` mapping, it calls `ResourceActionsUtil.getModelResource` which throws a `NullPointerException`.

### Proposed Solution
This adds the missing asset type mapping to avoid the NPE. I chose the name "Document" since this name was used also in [DisplayPageTemplateSettingsUtil.java](https://github.com/liferay/liferay-portal/blob/fc5172930fcbddb83433923a7eb64a1fe09b61f2/modules/apps/headless/headless-admin-content/headless-admin-content-impl/src/main/java/com/liferay/headless/admin/content/internal/dto/v1_0/util/DisplayPageTemplateSettingsUtil.java#L141)

This is the response on the virtual instance after the fix. The 3rd "Document" (`com.liferay.portal.kernel.repository.model.FileEntry`) type is what was causing the NPE.
Screen Shot 2022-08-10 at 5 47 18 PM

On the non-virtual instance site (localhost:8080), there were no errors since the asset types of "Stage" and "Audience" only had the `AllAssetTypes` type.
Screen Shot 2022-08-10 at 6 31 59 PM

### CODE REVIEW

**Comment by LuismiBarcos** [comment]
Thanks for the PR! We will review it as soon as we can

**Comment by thektan** [comment]
Closing this as no longer reproducible. After rebuilding portal and reindexing all search indexes, I couldn't reproduce this issue. It's unknown to me how the `com.liferay.portal.kernel.repository.model.FileEntry` type would have changed, but I can reopen this PR if this issue occurs again.

**Comment by thektan** [comment]
Reopening this because this does still occur when upgrading from an older database. See the steps listed in the ticket https://issues.liferay.com/browse/LPS-160310 under "Steps to reproduce on latest master".

**Comment by 4lejandrito** [comment]
Hi @thektan,

We'll review as soon as we can. How urgent is this for you?

**Comment by thektan** [comment]
Hi @4lejandrito, there isn't a customer deadline, but this is blocking a story ticket https://issues.liferay.com/browse/LPS-140641. Also since this is a 1 line code addition, I'm hoping it could be reviewed sooner. Thanks in advance!

**Review by LuismiBarcos — APPROVED** [review]
Hi @thektan,
Finally, I've had time to review this, and I could reproduce it. 
The change looks good to me. 
Thanks for taking care of it and for all the context provided in the PR and the ticket. That was very helpful for the review.

**Comment by LuismiBarcos** [comment]
ci:forward

**Comment by thektan** [comment]
Thanks for the review @LuismiBarcos!

Following up on BChan's comment in https://github.com/brianchandotcom/liferay-portal/pull/123083#issuecomment-1246522261, would it be appropriate to rename one of these asset type names? If so, would there be a preferred name? I didn't find any uses of DLFileEntry vs FileEntry and any names that would distinguish them.

Or should `Document` always be default mapped to a specific class which means this overwriting can be ok?

**Comment by 4lejandrito** [comment]
Found the root cause, that classname (FileEntry) should have never been there in the first place. Sent https://github.com/liferay-tango/liferay-portal/pull/2831 to the Tango team since they own that part of the code. Thanks @thektan for your patience and for the awesome steps to reproduce in the issue, it would have been impossible without them.

**Pull request closed without merging**
