### PR TITLE
LPS-124133 Refactor Content Performance navigation to detail view

### PR DESCRIPTION
**Pull request by dgarciasarai**
**Description**
We are going to add a second level (detail view) for Referral and Social traffic channels. Now there is a detail only for Organic and Paid. To make this happen, first, we have to make a little refactor in the code and be prepared for it. The traffic channels are fixed values, we have Organic, Paid, Direct, Social, and Referral.

**In this pull**

- Navigate to detail view using the traffic channel name instead of generic `traffic-source-detail`
- `Detail` component will be the base for rendering all the traffic channel details, so I move the check (if we click on organic, paid, etc), inside the `Detail` component
- For better understanding, I create a new `KeywordsDetail` component to render the detail view if we clicked on Organic or Paid traffic channels. The idea of the `Detail` component is only to check what traffic channel is and render the proper detail component
- We are going to use the `TimeSpanSelector` component in the details, so it has to be reusable, so I move the CSS margins out of the component
- Fix frontend tests

**Notes**
This refactoring does not change any UI. It's only code refactor to prepare it for the new second-level screens (referral and social).

### CODE REVIEW

**Comment by dgarciasarai** [comment]
Hey @liferay-frontend, can you review this refactor and give me feedback? Thanks!

**Comment by dgarciasarai** [comment]
ci:test:sf

**Comment by dgarciasarai** [comment]
ci:test:relevant

**Review by wincent — APPROVED** [review]
Looks good to me. Didn't test it, but nothing glaring stands out to me.

If tests end up green feel free to `ci:forward`.

**Comment by dgarciasarai** [comment]
ci:forward

**Comment by dgarciasarai** [comment]
Thanks @wincent for the review! Let's forward it 😄

**Pull request closed without merging**
