### PR TITLE
LPS-134984 product-navigation-applications-menu-web isolate CSS

### PR DESCRIPTION
**Pull request by pat270**
https://issues.liferay.com/browse/LPS-134984

This PR isolates CSS related to Applications Menu.

The CSS I'm using to test:
```html
<style>
html {
  font-size: 20px;
}

#senna_surface1 h1,
#senna_surface1 h2,
#senna_surface1 h3,
#senna_surface1 h4,
#senna_surface1 h5,
#senna_surface1 h6 {
  background-color: #282828;
  border: 4px solid #00ff66;
  color: #00ff66;
  font-family: Georgia;
  font-size: 50px;
  font-style: italic;
  font-variant: small-caps
  font-weight: bold;
  line-height: 100px;
  letter-spacing: 2px;
  margin: 10px 0;
  padding: 10px;
  text-align: center;
  text-shadow: 1px 1px 0 #fff;
  text-transform: uppercase;
  white-space: nowrap;
}

#senna_surface1 .btn {
  background-color: #282828;
  border: 4px solid #00ff66;
  color: #00ff66;
  font-family: Georgia;
  font-size: 50px;
  font-style: italic;
  font-variant: small-caps
  font-weight: bold;
  line-height: 100px;
  letter-spacing: 2px;
  margin: 10px 0;
  padding: 10px;
  text-align: center;
  text-shadow: 1px 1px 0 #fff;
  text-transform: uppercase;
  white-space: nowrap;
}

#senna_surface1 .btn:hover {
  background-color: #000;
  color: #ffcc00;
  letter-spacing: 4px;
  font-size: 40px;
}

#senna_surface1 a {
  background-color: #282828;
  border: 4px solid #00ff66;
  color: #00ff66;
  font-family: Georgia;
  font-size: 50px;
  font-style: italic;
  font-variant: small-caps
  font-weight: bold;
  line-height: 100px;
  letter-spacing: 2px;
  margin: 10px 0;
  padding: 10px;
  text-align: center;
  text-shadow: 1px 1px 0 #fff;
  text-transform: uppercase;
  white-space: nowrap;
}

#senna_surface1 a:hover {
  background-color: #000;
  color: #ffcc00;
  letter-spacing: 4px;
  font-size: 40px;
}
</style>
```

Screenshot:
applications-menu

### CODE REVIEW

**Comment by diegonvs** [comment]
LGTM :)

**Review by edalgrin — APPROVED** [review]
I remember part of this code! 😄

**Comment by edalgrin** [comment]
Just started reviewing :)

**Comment by edalgrin** [comment]
It seems to be working fine, going to forward this!

test

**Comment by edalgrin** [comment]
ci:forward

**Pull request closed without merging**
