### PR TITLE
LPS-181244 | Organize FDS Datasets test cases

### PR DESCRIPTION
**Pull request by abhnerramos**
**Description**
To-do list:
1. Rename FrontendDataSetViews.testcase > FDSEntries.testcase
2. Move FDSEntries.testcase to uiinfrastructure/frontenddataset/datamanagement
3. Create FDSViews.testcase inside uiinfrastructure/frontenddataset/datamanagement

**JIRA ticket**
https://issues.liferay.com/browse/LPS-181244

### CODE REVIEW

**Comment by abhnerramos** [comment]
ci:test:stop

**Comment by abhnerramos** [comment]
ci:test:frontend

**Comment by abhnerramos** [comment]
ci:test:sf

**Comment by abhnerramos** [comment]
ci:test:frontend

**Comment by mateusralv** [comment]
ci:test:sf

**Comment by abhnerramos** [comment]
ci:test:sf

**Review by mateusralv — APPROVED** [review]
Good Job, thanks a lot @abhnerramos 🎉 🚀

**Comment by mateusralv** [comment]
ci:forward

**Comment by mateusralv** [comment]
ci:forward:stop

**Pull request closed without merging**
