### PR TITLE
LPS-197848 Use the permissionKey as value in the form

### PR DESCRIPTION
**Pull request by dsanz**
Reference: https://liferay.atlassian.net/browse/LPS-197848

In this PR we're giving the right value to the "Headless Action Key" field for the action being edited, which we missed in the original PR

### CODE REVIEW

**Review by markocikos — APPROVED** [review]
@dsanz LGTM! :sparkles:

**Comment by thektan** [comment]
ci:test:relevant

**Comment by dsanz** [comment]
ci:foward

**Comment by dsanz** [comment]
ci:forward

**Pull request closed without merging**
