### PR TITLE
LPS-177493 | Test Fix Element is not present, ManagementToolbar#ViewButtonCanRenderDoubleCaret

### PR DESCRIPTION
**Pull request by andreluis2022**
Background:
Test Fix "Element is not present at ManagementToolbar#ViewButtonCanRenderDoubleCaret"

Test plan
- Assert the view button also has a double caret icon

JIRA Ticket:
https://issues.liferay.com/browse/LPS-177493

### CODE REVIEW

**Comment by mateusralv** [comment]
ci:test:frontend

**Comment by mateusralv** [comment]
Hi @andreluis2022 the test still failing in CI could take a look? Thanks :) 

[ManagementToolbar#ViewButtonCanRenderDoubleCaret](https://testray.liferay.com/home/-/testray/case_results/2223758588?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2223758175%26testrayRunId%3D2223758379%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc)

**Comment by andreluis2022** [comment]
> Oi@andreluis2022o teste ainda está falhando no CI poderia dar uma olhada? Obrigado :)
> 
> [ManagementToolbar#ViewButtonCanRenderDoubleCaret](https://testray.liferay.com/home/-/testray/case_results/2223758588?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2223758175%26testrayRunId%3D2223758379%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc)

Ok I will analyze and change

**Comment by andreluis2022** [comment]
@mateusralv

**Comment by mateusralv** [comment]
ci:test:frontend

**Comment by andreluis2022** [comment]
ci:test:sf

**Review by mateusralv — CHANGES_REQUESTED** [review]
changes requested by Slack to make the test more readable.

**Comment by andreluis2022** [comment]
> alterações solicitadas pelo Slack para tornar o teste mais legível.

ok

**Comment by andreluis2022** [comment]
ci:test:sf

**Review by mateusralv — APPROVED** [review]

**Comment by mateusralv** [comment]
ci:forward

**Pull request closed without merging**
