### PR TITLE
LPS-134021 Lowercase data attributes keys, so we avoid React warnings

### PR DESCRIPTION
**Pull request by sandrodw3**
Related ticket: https://issues.liferay.com/browse/LPS-134021

## Proposed solution
Lowercasing data attributes keys

## Steps to reproduce
Go to Content & Data > Web Content  and observe the browser console
 
### Expected result
There are no warnings in the browser console

### Actual result
A warning is displayed saying that data attributes should be lowercased
image

### CODE REVIEW

**Review by julien — APPROVED** [review]
thanks @sandrodw3 LGTM

**Comment by julien** [comment]
@john-co do you know anything about the error returned by the CI, it's the first time I've seen one of these?

**Comment by john-co** [comment]
ci:test:relevant

**Comment by john-co** [comment]
Not exactly sure what happened but the error is but it was trying to setup the liferay-portal-ee as a subrepo and didn't find the SHA: 5530cdefde1665acdf069e1aeed09522c80b0231. I don't see how the PR is related so I'm rerunning the tests.

**Comment by julien** [comment]
ci:reevaluate:1287401_249

**Comment by julien** [comment]
@john-co thanks for the help. The latest errors don't seem to be related to these changes, do any poshi tests need to be updated?

**Comment by julien** [comment]
ci:test:relevant

**Comment by sandrodw3** [comment]
ci:test:relevant

**Comment by julien** [comment]
ci:forward

**Comment by john-co** [comment]
Reviewed. Test failures are unrelated. :heavy_check_mark: 
- Upgrade test is flaky on this test run: https://github.com/liferay-frontend/liferay-portal/pull/1458#issuecomment-918886728
```
LIFERAY_ERROR: bundle com.liferay.portal.properties.swapper:5.0.4 (296)[com.liferay.portal.properties.swapper.internal.DefaultGuestGroupLogoSwapper(10093)] : The activate method has thrown an exception
```
cc/ @julien thanks for follow up, it's a known bug that's inconsistent: https://issues.liferay.com/browse/LPS-120921?focusedCommentId=2509034&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-2509034

cc/ @vicnate5

**Comment by julien** [comment]
@john-co thanks again for the help

**Comment by carloslancha** [comment]
Hi guys! This change would fix the issue and remove all the warnings in portal but IMHO I don't think this is the best fix. Doing this we're causing kind of a side effect since we're sending to the component/tag a data attribute in a format that will be changed and that could cause confusion using it from the application.

When we first implemented this we didn't introduce this change because we thought the best solution is every team to fix it in their apps.

What do you guys think? cc @sandrodw3 @julien

**Comment by julien** [comment]
Hey @carloslancha yes, I agree while this fixes the issue, the real fix would be to stop setting `data-*` attributes in camelCase

**Comment by sandrodw3** [comment]
Hi @carloslancha! Thanks for the feedback. I noticed that, but if we don't lowercase the data attributes, React will do it anyway. So, the confusion is the same, right? At least this way we avoid the warnings 😛

**Comment by julien** [comment]
@sandrodw3 

> ...if we don't lowercase the data attributes, React will do it anyway

No, it won't, see [here](https://codesandbox.io/s/awesome-zhukovsky-3o41y?file=/src/index.js)

**Comment by sandrodw3** [comment]
> @sandrodw3
> 
> > ...if we don't lowercase the data attributes, React will do it anyway
> 
> No, it won't, see [here](https://codesandbox.io/s/awesome-zhukovsky-3o41y?file=/src/index.js)

But if you inspect the app, it's lowercased
image

**Comment by julien** [comment]
> But if you inspect the app, it's lowercased, I think React does it automatically.

Yes but if you open the console, you'll see the same warning you fixed

**Comment by sandrodw3** [comment]
> > But if you inspect the app, it's lowercased, I think React does it automatically.
> 
> Yes but if you open the console (devtools), you'll see the same warning that you fixed

Yes, yes 🙂 the thing is @carloslancha said he thinks it's not a good idea to lowercase the attributes, and what I'm saying is that if we don't lowercase the attributes, React will lowercase them anyway. At least, if we lowercase them, we avoid the warnings.

**Comment by julien** [comment]
@sandrodw3, I think we're not on the same page: what I understood is that @carloslancha said that the correct way to write `data-*` attributes in is lowercase, and that's what the [spec](https://www.w3.org/TR/2011/WD-html5-20110525/elements.html#embedding-custom-non-visible-data-with-the-data-attributes) also says. If you're getting a warning, it's exactly because of that. 

Additionally, what @carloslancha said is that with this fix we automatically convert those attributes to lowercase, but the real solution would be to not set those attributes incorrectly.

So we should stop doing 

```jsx
<SomeComponent
    dataFoo="bar" />
```

A start doing

```jsx
<SomeComponent
    datafoo="bar" />
```

**Comment by carloslancha** [comment]
Exactly, what @julien says. The correct solution is to rename those attributes on each app to avoid the side effect. If we lowercase them from the tags we're doing the same as React but without warnings 😅

**Comment by sandrodw3** [comment]
I agree this is not the ideal solution. I just thought it would be better to lowercase them before React does it, because the result in the browser is the same.

In my opinion, the correct solution would be to set those attributes for each item with `element.dataset[key] = value` instead of building the key manually, expecting each app to send them lowercased from the backend.

Anyway, feel free to revert this if you find it convenient 🙂

Thanks guys for the feedback.

**Pull request closed without merging**
