### PR TITLE
LPS-154730: Expose ERC in DocumentsFolder

### PR DESCRIPTION
**Pull request by sergiojimcos**
This PR contains some requested changes from -> https://github.com/brianchandotcom/liferay-portal/pull/121551#issuecomment-1214467983

**JIRA Ticket:** https://issues.liferay.com/browse/LPS-154730

cc/ @4lejandrito

### CODE REVIEW

**Comment by sergiojimcos** [comment]
ci:test:relevant

**Comment by susanchen3** [comment]
[Semantic versioning](https://testray.liferay.com/home/-/testray/case_results/1948433345) error :(
```
     [exec] com.liferay.semantic.versioning.SemanticVersioningTest > testSemanticVersioning[/apps/document-library/document-library-api] FAILED
     [exec]     java.lang.AssertionError:   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec]     = ================================================== ========== ========== ========== ========== ==========
     [exec]     * com.liferay.document.library.display.context       MAJOR      5.0.0      5.0.0      6.0.0      VERSION INCREASE REQUIRED
     [exec]     	>   class      com.liferay.document.library.display.context.BaseDLViewFileEntryHistoryDisplayContext
     [exec]     		-   method     getMenu()
```
No other unique test failures though! :)

**Comment by sergiojimcos** [comment]
ci:test:relevant

**Comment by sergiojimcos** [comment]
ci:test:relevant

**Comment by susanchen3** [comment]
Reviewed, [test failures](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=2&testrayRunIdB=1949309229&testrayRunIdA=1947880478&statusB=3) are unrelated :heavy_check_mark: Looks good to manually forward from QA perspective if ready on dev side :)

**Comment by sergiojimcos** [comment]
Thanks @susanchen3!!

**Comment by sergiojimcos** [comment]
ci:forward

**Comment by sergiojimcos** [comment]
ci:forward

**Comment by sergiojimcos** [comment]
Manual forwarding to Brian: https://github.com/brianchandotcom/liferay-portal/pull/121934

**Pull request closed without merging**
