### PR TITLE
LPS-124912 Migrate instances of AlloyEditor in Forms edit_element_set.jsp

### PR DESCRIPTION
**Pull request by julien**
AlloyEditor instances have been replaced with `<aui:input />`

**Test plan**

- Deploy the `dynamic-data-mapping-form-web` module
- Navigate to **Content & Data** > **Forms**
- Select the **Element Sets** tab
- Create a new form and save it

*PS*
Sending here for internal review before forwarding it to @liferay-forms

### CODE REVIEW

**Comment by jbalsas** [comment]
Hey @julien, should you put this together with https://github.com/liferay-frontend/liferay-portal/pull/624? There seems to be quite some overlap, so sending them together probably makes sense. You can have a PR with more than one LPS ;)

**Comment by julien** [comment]
@jbalsas yeah that makes much more sense.

**Comment by julien** [comment]
ci:stop

**Comment by julien** [comment]
ci:close

**Pull request closed without merging**
