### PR TITLE
LPD-23440 - poshi - Remove a test that was replaced by Playwright in liferay-frontend#4139

### PR DESCRIPTION
**Pull request by kresimir-coko**
https://liferay.atlassian.net/browse/LPD-23440

This PR removes a Poshi test that we added to Playwright in #4139

### CODE REVIEW

**Comment by kresimir-coko** [comment]
ci:test:relevant

**Review by markocikos — APPROVED** [review]
@kresimir-coko LGTM! :sparkles:

**Comment by kresimir-coko** [comment]
ci:stop

**Comment by kresimir-coko** [comment]
ci:stop

**Comment by kresimir-coko** [comment]
ci:stop

**Comment by kresimir-coko** [comment]
ci:close

**Comment by kresimir-coko** [comment]
ci:reopen

**Pull request closed without merging**
