### PR TITLE
LPS-109432 - Remove unneeded padding

### PR DESCRIPTION
**Pull request by marcoscv-work**
This PR resolve an ugly jump on top of the screen takes place when we follow those steps:

- Create a page and don't publish it
- Go back to the pages administrator
- Go edit page

--- 

How to test it:

Add to the nodes tree a breakpoint in the body element on subtree modifications. then follow the steps

- Create a page and don't publish it
- Go back to the pages administrator
- Go edit page

### CODE REVIEW

**Comment by marcoscv-work** [comment]
ci:test:sf

**Comment by marcoscv-work** [comment]
ci:test:stable

**Comment by marcoscv-work** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
ci:forward

**Pull request closed without merging**
