### PR TITLE
LPS-117821 Move useStateSafe into frontend-js-react-web

### PR DESCRIPTION
**Pull request by wincent**
As noted [here](https://github.com/liferay-frontend/liferay-portal/pull/156/files#r459905408), this hook was originally added [to layout-content-page-editor-web](https://github.com/liferay/liferay-portal/blob/9a9b3d1bc8199ef517d1ea94ee4158ba3ae4aeda/modules/apps/layout/layout-content-page-editor-web/src/main/resources/META-INF/resources/page_editor/core/hooks/useStateSafe.js) and it has since been copied verbatim to [data-engine-taglib](https://github.com/liferay/liferay-portal/blob/9a9b3d1bc8199ef517d1ea94ee4158ba3ae4aeda/modules/apps/data-engine/data-engine-taglib/src/main/resources/META-INF/resources/data_layout_builder/js/hooks/useStateSafe.es.js). 

Given that it would have been useful in [the linked PR](https://github.com/liferay-frontend/liferay-portal/pull/156), let's just move it into frontend-js-react-web.

Test plan: `yarn test` the added unit tests. These simulate the typical pattern of an async callback that runs after some time and tries to set state without checking to see whether the component is still mounted.

cc @carloslancha: this is the one that we said we would do a follow-up on and use.

### CODE REVIEW

**Comment by wincent** [comment]
ci:test:sf

**Comment by wincent** [comment]
ci:test:relevant

**Comment by wincent** [comment]
SF failure looks like an infra failure:

```
format-source-files:
     [java] Java Result: 1
     [echo] 
     [echo] There are no modified files on the current branch (wincent-165-wincent/LPS-117821/use-state-safe).
     [echo] Executing Source Formatter task on all files.
     [echo] 
     [java] java.lang.NullPointerException
     [java] 	at com.liferay.portal.tools.GitUtil._getLatestCommitId(GitUtil.java:517)
     [java] 	at com.liferay.portal.tools.GitUtil.getCurrentBranchFileNames(GitUtil.java:87)
     [java] 	at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:160)
```

[Reported here](https://liferay.slack.com/archives/C1SJ64S9X/p1595844198074300).

**Comment by carloslancha** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by wincent** [comment]
Manual forward: https://github.com/brianchandotcom/liferay-portal/pull/91831

**Pull request closed without merging**
