### PR TITLE
LPS-151474 ActiveViewSettings are not being applied

### PR DESCRIPTION
**Pull request by markocikos**
### References

- [LPS-151474 ActiveViewSettings are not being applied](https://issues.liferay.com/browse/LPS-151474)

### What is the goal of this PR?

We are fixing handling of view persistence, more specifically selection of visible columns. The root cause of the issue is that the `activeViewSettings` attribute of the tag is a JSON string, not an object. We need to parse this string first.

#### After PR

after

### Steps to reproduce

See steps to reproduce in [LPS-151474 ActiveViewSettings are not being applied](https://issues.liferay.com/browse/LPS-151474)

### CODE REVIEW

**Review by beltranrengifo — APPROVED** [review]
LGTM!

**Comment by beltranrengifo** [comment]
ci:reevaluate:1377401_1666

**Comment by diegonvs** [comment]
ci:test:relevant

**Comment by markocikos** [comment]
ci:forward

**Pull request closed without merging**
