### PR TITLE
LPS-165857 Update packages `@clayui/*` to v3.78.0

### PR DESCRIPTION
**Pull request by matuzalemsteles**
### Bug Fixes

-   **@clayui/css:** Cadmin Management and Navigation Bar only output media queries for md breakpoint ([617d696](https://github.com/liferay/clay/commit/617d696b2a6efe5739671e103e849dc6ac2777db))
-   **@clayui/css:** Mixin clay-navbar-expand-variant shouldn't style `.btn-unstyled` ([04615be](https://github.com/liferay/clay/commit/04615be71d48342bb2d4048e1cdc59f5201d2370))
-   **@clayui/drop-down:** fix error when esc open menu ([9ecc8e4](https://github.com/liferay/clay/commit/9ecc8e4acdebaa60f72ca3f13c22e138518d4540))
-   **@clayui/drop-down:** fix focus order error ([3062d5e](https://github.com/liferay/clay/commit/3062d5ed09292e187529749607f39f965ed71ae2))
-   **@clayui/shared:** fix error of not finding focused elements when React.Portal is under a conditional ([179cd7a](https://github.com/liferay/clay/commit/179cd7a523ebc5a4c96fcb0194e5c8873da6c367))
-   **@clayui/shared:** fixes error when identifying non-visible element as focusable ([82cc0f8](https://github.com/liferay/clay/commit/82cc0f8078810b4610f220d09792ee53f9fb3da8))
-   **clayui.com:** Github link accessibility fixe ([90e380c](https://github.com/liferay/clay/commit/90e380c43866fca915b754acda440fb4f8174c27))

### Features

-   **@clayui/css:** Mixins `clay-navbar-size` don't output media-query styles ([7ddcb52](https://github.com/liferay/clay/commit/7ddcb52498d865c4e6003c47a7c91e19dba782a6))
-   **@clayui/shared:** add hook to detect user interaction type ([a20e236](https://github.com/liferay/clay/commit/a20e23638e28d27da18d8d140ebb38818595f129))
-   **@clayui/tabs:** add new API to configure browsing behavior between tabs ([30595be](https://github.com/liferay/clay/commit/30595bed1d5ec2de1a7d3d1759d6a2398c904c76))

### CODE REVIEW

**Comment by matuzalemsteles** [comment]
cc @mateusralv

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by mateusralv** [comment]
I’ll analyze new failure as soon as [ci:test:relevant](https://github.com/liferay-frontend/liferay-portal/pull/2816#issuecomment-1291100118) is done 🕵🏽

**Comment by dsanz** [comment]
ci:test:relevant

**Comment by dsanz** [comment]
ci:reevaluate:1387401_4525

**Comment by dsanz** [comment]
@john-co I kinda doubt failing tests are related, however I'd like to double-check as some poshi report mentions dropdown. (e.-g. MultiFactorAuthentication#LoginWithOTPEnabled and OAuth2#GrantedAuthorizationsCanBeRevoked) Could you please help me to understand?

cc/ @matuzalemsteles

**Comment by mateusralv** [comment]
Hi @dsanz I'm taking a look now 🕵🏽

**Comment by mateusralv** [comment]
Hey @matuzalemsteles I analyzed the failures that [are not present in the master](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1666798139233&testrayRunIdA=2015982916&testrayRunIdB=2016816952) and obtained the results: 

The `modules-semantic-versioning-jdk8/0/0` module returned the following error, you could take a look if is related?

```
[exec] com.liferay.semantic.versioning.SemanticVersioningTest > testSemanticVersioning[/apps/frontend-taglib/frontend-taglib] FAILED
     [exec]     java.lang.AssertionError:   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec]     = ================================================== ========== ========== ========== ========== ==========
     [exec]     * com.liferay.frontend.taglib.servlet.taglib         MINOR      5.0.0      5.0.0      5.1.0      VERSION INCREASE REQUIRED
     [exec]     	+   class      com.liferay.frontend.taglib.servlet.taglib.EditFormButtonsTag
     [exec]     		+   extends    com.liferay.taglib.util.IncludeTag
     [exec]     		+   method     <init>()
     [exec]     			+   return     void
     [exec]     		+   method     cleanUp()
     [exec]     			+   access     protected
     [exec]     			+   return     void
     [exec]     		+   method     clone()
     [exec]     			+   access     protected
     [exec]     			+   return     java.lang.Object
     [exec]     		+   method     equals(java.lang.Object)
     [exec]     			+   return     boolean
     [exec]     		+   method     finalize()
     [exec]     			+   access     protected
     [exec]     			+   return     void
     [exec]     		+   method     getRedirect()
     [exec]     			+   return     java.lang.String
     [exec]     		+   method     hashCode()
     [exec]     			+   return     int
     [exec]     		+   method     processEndTag()
     [exec]     			+   access     protected
     [exec]     			+   return     int
     [exec]     		+   method     setRedirect(java.lang.String)
     [exec]     			+   return     void
     [exec]     		+   method     toString()
     [exec]     			+   return     java.lang.String
     [exec]     [Baseline Warning] Bundle Version Change Recommended: 9.1.0
```
com.liferay.portal.tools.sample.sql.builder.io.CharPipeTest

---
🟠 Unique failures:
1. MultiFactorAuthentication#LoginWithOTPEnabled
2. ObjectPermission#CanDefineSinglePicklistPermissionsWithPermissionsPermission
3. ObjectPermission#CanViewItsOwnEntryWithOnlyAddPermission
4. ObjectPermission#CanViewSinglePicklistWithViewPermission
5. ObjectPermission#GuestCannotViewObjectEntriesWithoutViewPermission

The CI error occurred when a new user tries to open the dropdown menu related to the profile boot, when locally reproduced the error does not occur. When I run the tests on POSHI break and return a failure related to [LRQA-77904](https://issues.liferay.com/browse/LRQA-77904) 

https://user-images.githubusercontent.com/44584050/198125274-fcd651bc-68d1-4fc5-aa86-a633b886ad67.mp4


---
🟢 Not unique failures:

1. com.liferay.view.count.service.impl.test.ViewCountEntryLocalServiceTest
2. com.liferay.oauth2.provider.client.test.TOCTOUTest
3. ObjectActions#CanEditExpression
4. ObjectPortlet#CannotViewOtherUsersEntryWithOnlyAddPermission
5. com.liferay.segments.configuration.provider.test.SegmentsConfigurationProviderTest

🟢 Flaky failures:
1. ObjectActions#CanEditExpression

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by dsanz** [comment]
ci:reevaluate:1377401_5952

**Comment by dsanz** [comment]
Thank you @mateusralv !

About com.liferay.frontend.taglib.servlet.taglib.EditFormButtonsTag, that's a new Tag Echo is working on for a totally different thing, so, that error is not related.

About [LRQA-77904](https://issues.liferay.com/browse/LRQA-77904), it was created 12 days before this pull, so it can't be unique failure for this PR.

@matuzalemsteles let's focus on the dropdown part as we need to investigate this anyway. Let's sync with @mateusralv to narrow this down as much as possible

**Comment by dsanz** [comment]
ci:reevaluate:1377401_5952

**Comment by dsanz** [comment]
ci:reevaluate:1377401_5952

**Comment by mateusralv** [comment]
Hey @matuzalemsteles and @dsanz I have analysed the last results and obtained results: 

[comparison run with the master](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=2&testrayRunIdB=2019335528&testrayRunIdA=2018383266&statusB=3)
### 🔴 Unique failure

1. PagesAdmin#DeletePage
2. PagesAdmin#SearchPages
3. LocalFile.PagesAdmin#ViewDisplayPageTemplateViaCollectionItems
4. LocalFile.PagesAdminWithJavaScriptExtension#AddJavaScriptExtension
5. LocalFile.WidgetPages#EditViaPagesAdmin
6. LocalFile.WidgetPagesUI#AddChildPage

These tests have a similar failure. The dropdown menu closes very quickly. I think the implementation solved the failures of the Objects team tests but generated these. :/ 

https://user-images.githubusercontent.com/44584050/198313854-c748c934-73ed-4bc8-bf97-9250057e29b6.mp4


---

### 🟢 Team Objects tests that previously failed:

The tests that had unique failures before are passing now:


1. [ObjectPermission#CanDefineSinglePicklistPermissionsWithPermissionsPermission](https://testray.liferay.com/home/-/testray/case_results/2019336379)
2. [MultiFactorAuthentication#LoginWithOTPEnabled](https://testray.liferay.com/home/-/testray/case_results/2019336197)
3. [ObjectPermission#CanViewSinglePicklistWithViewPermission
](https://testray.liferay.com/home/-/testray/case_results/2019336410)
4. [ObjectPermission#GuestCannotViewObjectEntriesWithoutViewPermission](https://testray.liferay.com/home/-/testray/case_results/2019336021)

---
### 🟢 Not unique failures:

1. com.liferay.dynamic.data.mapping.form.field.type.internal.radio.RadioDDMFormFieldValueValidatorTest
7. com.liferay.asset.link.exportimport.test.AssetLinkExportImportTest
8. com.liferay.oauth2.provider.client.test.TokenExpeditionTest
9. CreateObject#CanAddRelationOnRelationshipField
10. CreateObject#CanAddRelationOnRelationshipTab
11. CreateObject#CanOnlySeeEntriesFromAccount
12. CreateObject#CanViewObjectEntryTitleStringOnRelationshipField
13. CreateObject#CascadeDeletionOneToManyWillAllowDeleteParent
14. CreateObject#DisassociateDeletionOneToManyWillAllowDeleteParent
15. ObjectFields#CanCreateObjectEntryWithEveryField
16. ObjectPermission#CanViewItsOwnEntryWithOnlyAddPermission
17. ObjectRelationships#CanAddOneToManyRelationWithNativeObject
18. SystemObjectAccount#CanAssociateAnyTypeOfAccount
19. portal-license-smoke-jdk8/0/0

**Comment by john-co** [comment]
Reviewed. Test failures are unrelated. :heavy_check_mark: 

Ok to manually forward from QA perspective. Pending dev approval.

**Comment by matuzalemsteles** [comment]
Thanks @john-co! Feel free to send it directly to Brian!

**Comment by john-co** [comment]
Pushed to https://github.com/brianchandotcom/liferay-portal/pull/125415

**Pull request closed without merging**
