### PR TITLE
LPS-120178 - Not use color picker for hr-border-color

### PR DESCRIPTION
**Pull request by marcoscv-work**
This PR removes the `colorpicker` for `hr-border-color` in _stylebook_, in order to do not offer colorpiker to chose a new color

image

---

To test it:

1. Add a page based on Blank
2. Add a Heading fragment to page
3. Open the body of Heading
4. Selection panel > Styles tab
5. Open the Text Color field

### CODE REVIEW

**Comment by marcoscv-work** [comment]
ci:test:sf

**Comment by marcoscv-work** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
Pretty trivial... forwarding!

**Comment by jbalsas** [comment]
ci:forward

**Comment by marcoscv-work** [comment]
> Pretty trivial... forwarding!

release blocker!

**Pull request closed without merging**
