### PR TITLE
LPS-132738 Fix unable to add question via tags

### PR DESCRIPTION
**Pull request by javierdearcos**
In this case, it makes no sense to be able to add questions from the tag's page, because the app wouldn't know in which topic you want to create the question.
 
I've hidden the button when there is no sectionTitle in the Questions page (that is when we get there from the Tags page), and show the no results empty state, as it feels more correct for me because we are doing a search by tag

### CODE REVIEW

**Review by nhpatt — APPROVED** [review]

**Comment by nhpatt** [comment]
ci:forward

**Comment by nhpatt** [comment]
I wasn't sure if we show the create button anywhere else but I see that we do not show it in tags toolbar, so let's go! 👍

**Comment by javierdearcos** [comment]
ci:forward

**Comment by javierdearcos** [comment]
ci:forward

**Comment by javierdearcos** [comment]
ci:stop

**Comment by javierdearcos** [comment]
ci:forward

**Pull request closed without merging**
