### PR TITLE
LPD-32476 [DataSetSettings.testcase] Delete poshi

### PR DESCRIPTION
**Pull request by thektan**
https://liferay.atlassian.net/browse/LPD-32476

- Despite the file name, these tests covered things all related with the Data Set Manager feature flag

**Notes:**
- Created a new file `featureFlag.ts` to have a clean separation of setting `'LPS-164563': true` and `'LPS-164563': false` in the setup. Also avoided any unnecessary data initialization in other files.

### CODE REVIEW

**Comment by thektan** [comment]
ci:test:playwright

**Comment by chestofwonders** [comment]
LGTM 🎉

**Review by chestofwonders — APPROVED** [review]
LGTM 🎉

**Comment by dsanz** [comment]
@thektan code looks good to me, just check that failing tests are not related and this is ready to go.
Thanks!

**Comment by thektan** [comment]
No related failures, forwarding!

**Comment by thektan** [comment]
ci:forward

**Pull request closed without merging**
