### PR TITLE
LPS-111973 - Fix dropdown with btn-link

### PR DESCRIPTION
**Pull request by marcoscv-work**
This PR fix the problem with CSS properties and an old dropdown with the combination of `dropdown-item` and `btn-link`.

image

**Testing the PR:**

To test the PR you will need:
- Create a widget page
- Add Documents and Media portlet
- Configure portlet to show actions:
image
- Upload some doc/image
- Select it on the list and now you have access to the actions, open the dropdown:

You will see:
image

### CODE REVIEW

**Comment by marcoscv-work** [comment]
ci:test:sf

**Comment by marcoscv-work** [comment]
ci:test:relevant

**Comment by eduardoallegrini** [comment]
I think we can forward this, eventually we are going to move the ccp-layer to Clay 🤷‍♂️

**Comment by marcoscv-work** [comment]
ci: forward

**Comment by marcoscv-work** [comment]
ci:forward

**Pull request closed without merging**
