### PR TITLE
LPS-154637 Add WalkthroughHotspot#WillDisplayPopoverWhenClicked

### PR DESCRIPTION
**Pull request by jaydawu**
**Background**
Create automated tests for Walkthrough component.

**Test Plan**
Given: frontend-js-components-sample-web deployed to test page
And Given: Navigate to Walkable tab on sample portlet
When: Click hospot element
Then: popover is present
And Then: hotspot element is not present

**JIRA Ticket:**
https://issues.liferay.com/browse/LPS-154637

### CODE REVIEW

**Comment by jaydawu** [comment]
ci:test:sf

**Comment by jaydawu** [comment]
ci:test:frontend:nocompile

**Comment by susanchen3** [comment]
Taking a look now!

**Review by susanchen3 — APPROVED** [review]
Looks good to me! Thanks Jayda! :D

**Comment by susanchen3** [comment]
ci:forward

**Pull request closed without merging**
