### PR TITLE
LPS-178655 | Fix accessibility issues on modals and popovers, prevent from losing focus

### PR DESCRIPTION
**Pull request by georgel-pop-lr**
Steps to reproduce:

1. Add a calendar widget in the default site
2. Add an event
3. Start the windows reader
4. Once you get into the event with the TAB, hit enter to open it in order to edit it
5. Move with the TAB through the calendar edit pop over and you can navigate behind it

### CODE REVIEW

**Comment by georgel-pop-lr** [comment]
ci:test:relevant

**Comment by georgel-pop-lr** [comment]
ci:reevaluate:1357401_3938

**Comment by georgel-pop-lr** [comment]
ci:test:relevant

**Comment by georgel-pop-lr** [comment]
ci:forward

**Comment by mateusralv** [comment]
I'm taking a look 🕵🏽

**Comment by mateusralv** [comment]
Hi @georgel-pop-lr The failures are not related 🟢 

[Testray Comparison](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1679916537466&testrayRunIdA=2243298183&testrayRunIdB=2244155208)

**Comment by georgel-pop-lr** [comment]
ci:forward:force

**Pull request closed without merging**
