### PR TITLE
LPD-41119 Pass the request (instead of the nonce) to ContentSecurityPolicyHTMLRewriter

### PR DESCRIPTION
**Pull request by izaera**
QA analysis: :green_circle:  https://github.com/liferay-frontend/liferay-portal/pull/4542#issuecomment-2462183030 
Sign-off: https://github.com/liferay-frontend/liferay-portal/pull/4542#pullrequestreview-2426275266

### CODE REVIEW

**Comment by izaera** [comment]
ci:test:relevant

**Comment by izaera** [comment]
ci:test:data-engine

**Comment by izaera** [comment]
ci:report:62468387

**Comment by izaera** [comment]
ci:report:62567141

**Review by bryceosterhaus — APPROVED** [review]
LGTM

**Comment by izaera** [comment]
ci:test:data-engine

**Comment by izaera** [comment]
Running test:data-engine again to see if the errored tests behave differently

**Comment by izaera** [comment]
ci:report:67257493

**Comment by izaera** [comment]
Since this is green I will force forward

**Comment by izaera** [comment]
ci:forward:force

**Comment by izaera** [comment]
ci:forward:force

**Comment by izaera** [comment]
ci:forward:force

**Pull request closed without merging**
