### PR TITLE
LPS-115751 Update liferay-npm-scripts to v32.5.1

### PR DESCRIPTION
**Pull request by wincent**
[Release notes](https://github.com/liferay/liferay-npm-tools/releases/tag/liferay-npm-scripts%2Fv32.5.1).

Enforces base indent level in JS blocks inside JSP script tags, which was initially [reported here](https://github.com/brianchandotcom/liferay-portal/pull/90231).

### CODE REVIEW

**Comment by wincent** [comment]
ci:test:sf

**Comment by wincent** [comment]
ci:test:relevant

**Comment by wincent** [comment]
FWIW I don't believe this could possibly cause a CI failure (because I already ran a full SF over liferay-portal to confirm that there were no changes), but we'll see how friendly `ci:test:relevant` is feeling today.

**Comment by jbalsas** [comment]
> FWIW I don't believe this could possibly cause a CI failure (because I already ran a full SF over liferay-portal to confirm that there were no changes), but we'll see how friendly ci:test:relevant is feeling today.

😂 

How did you run it? `yarn format` from `modules` would've caught this... and you might want to take a look at that because it's reporting over 60ish fixed files but only these are actually touched.

Another option is `ant format-source-all`? I tried but gave up after 15 minutes :D 

I pushed one additional commit fixing those jsps to your branch... let's see how this goes!

**Comment by jbalsas** [comment]
ci:test:sf

**Comment by jbalsas** [comment]
Well... seeing as SF is happy and we already saw a green run, I'm going to risk it

**Comment by jbalsas** [comment]
ci:forward

**Comment by wincent** [comment]
> > FWIW I don't believe this could possibly cause a CI failure (because I already ran a full SF over liferay-portal to confirm that there were no changes), but we'll see how friendly ci:test:relevant is feeling today.
> 
> 😂
> 
> How did you run it? `yarn format` from `modules` would've caught this...

With `portool yarn format` from top-level modules. Having said that, I ran that on current `master` that I had pulled some time yesterday afternoon, so it's possible the problematic files came in after that. [Test plan](https://github.com/liferay/liferay-npm-tools/pull/468) was written in the original pull.

> Test plan: With this PR installed in liferay-portal, run `yarn format` from top level and see no changes (per `git diff`).

On this one:

> and you might want to take a look at that because it's reporting over 60ish fixed files but only these are actually touched.

This is a known "gotcha" because there are a couple of tiny things where ESLint and Prettier disagree with how things should look. So when you run `format`, what actually happens is:

1. ESLint runs first, doing some bad things that Prettier doesn't like.
2. Prettier runs second, fixing the things it doesn't like (that's the 60-ish files you talk about.
3. You run `git diff`, wondering why it says nothing changed.

So it is something we could put some special casing in so as to avoid confusion, but I hadn't done it yet because I wasn't sure the complexity was worth it (we'd basically have to accumulate results, adjust/interpret them, then print them at the end of the two passes based on whether or not anything actually changed, instead of just printing them eagerly during processing). I'll make a ticket for that so we can decide whether it's worth it.  Technically, the fact that it prints misleading info to the console *is* a bug.

Issue is: https://github.com/liferay/liferay-npm-tools/issues/469

In any case, thanks for fixing/forwarding!

**Comment by jbalsas** [comment]
> With portool yarn format from top-level modules. Having said that, I ran that on current master that I had pulled some time yesterday afternoon, so it's possible the problematic files came in after that. Test plan was written in the original pull.

🤷 

Maybe... sounds unlikely 6 of them made it through in that short period of time, but who knows?

**Comment by wincent** [comment]
> Maybe... sounds unlikely 6 of them made it through in that short period of time, but who knows?

Git knows!

My guess is that I probably did something silly in my test:

1. Prepare PR.
2. Get distracted.
3. Reset `liferay-npm-tools` to `master` and forget about it.
4. Get distracted.
5. Install `liferay-npm-tools` into poral (ie. `master` instead of my PR), mistakenly thinking I was testing my PR.
6. Run test.

**Comment by jbalsas** [comment]
> Git knows!

That's true!! Now... is it worth it us to knowing it too? 😂

**Comment by wincent** [comment]
> That's true!! Now... is it worth it us to knowing it too? 😂

I am pedantic enough that I already checked before writing my comment. First file I looked at was committed to *after* I made my commit. Nice...

niiiice

Second and third file I looked at was last commit days before... 😢 So I had to assume that my "test" hadn't be a test at all.

despair

**Comment by jbalsas** [comment]
> First file I looked at was committed to after I made my commit. Nice...
>
> Second and third file [...]

finishline

**Pull request closed without merging**
