### PR TITLE
LPS-133578 Show default language first in TM locales list

### PR DESCRIPTION
**Pull request by tinycarol**
### References

- [LPS-133578](https://issues.liferay.com/browse/LPS-133578)

### What is the goal?

* Display the default language first in the TM locales list to avoid confusion after save

#### Before fix
While your are creating the form, the default language comes first, but once you click on save the order is different

https://user-images.githubusercontent.com/6642927/178759557-9a9ca971-5cb0-4e7c-aee8-32be9cb66508.mov

#### After fix
The default language is displayed first, as requested.

https://user-images.githubusercontent.com/6642927/178759980-5238e96f-efab-44e2-bbe7-f700d5b401b3.mov

### How to replicate
* Go to Control Panel > Instance Settings > Localization
* Select Portuguese as default language
* Go to Content & Data > Forms
* Click on Add new form
* Set the title for Portuguese
* Add English translation, set the title for that one
* Add one text field
* Click on Save
* See that the default language is displayed first

### CODE REVIEW

**Comment by mateusralv** [comment]
I'm taking a look at the failures.

**Comment by mateusralv** [comment]
Hi, @tinycarol the failures about `AssetsCustomAsset#CanCreateMultipleCustomAssetReport` and `CustomEventsSettings#CustomEventIsShownInAC` be related to analytics cloud and not seem related to your PR.

But the test `FormsRulesActions#CanUtilizeDataProvidersInAutofillRule` seem related to your PR, I run locally end return the error:
`java.lang.Exception: Expected text "???" does not match actual text "" at "//input[@type='text' and contains(@id,'Text36561349')] | //input[@type='text' and contains(@name,'Text36561349')] | //div[contains(@class,'form-group')]//p[text()='${key_fieldLabel}'] | //div[contains(@data-field-name,'Text36561349')]//div[contains(@class,'form-group')]//input | //div//div[contains(@class,'form-group')]//label[text()='Text36561349']/..//input[@type='text']"`

Could you take a look? 

[Comparison run](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1657904956846&testrayRunIdA=1907780201&testrayRunIdB=1906741595) with the master 

cc: @john-co

**Comment by tinycarol** [comment]
Thanks @mateusralv! I'm taking a look now

**Comment by tinycarol** [comment]
Hi @mateusralv, just tested this locally by manually following the steps in the Poshi report and it seems like it's a little flaky. Most times it works, it autofills the address: 
imagen

But sometimes I get this error in the terminal:

 `2022-07-18 08:34:25.312 WARN  [hystrix-DDMDataProviderInvokeCommandGroup-1][DDMRESTDataProvider:125] The data provider was not able to connect to the web service. Unable to transmit request to zipcloud.ibsnet.co.jp`

 When this happens, the other field doesn't get autofilled, resulting in the same screenshot as in the Poshi report:
 
imagen

The downside is that I cannot replicate this consistently, it looks like it's an external API failure. It's also not very frequent, I spent ~5 minutes retrying every few seconds and only managed to get one error 😕

This was all with the branch from this PR, here you can see I'm adding more translations and the default language is displayed first in the form edition form (which was the purpose of this PR), but also on the form preview the address gets autofilled for all languages:

https://user-images.githubusercontent.com/6642927/179480091-a5929b10-1461-4d59-b347-58164d9617ca.mov



I did notice that by sending the request from the browser (http://zipcloud.ibsnet.co.jp/api/search?zipcode=1500000) at first it took multiple seconds to respond, but now it takes <200ms, so maybe this was caused by server downtime, high load or something like that. I'll re-trigger the tests, maybe I'll be more lucky this time 😅

**Comment by tinycarol** [comment]
ci:test:relevant

**Comment by mateusralv** [comment]
Hi @tinycarol, It makes sense, and now I see the same error occurs in another [PR](https://github.com/liferay-frontend/liferay-portal/pull/2480#issuecomment-1187168981) and it doesn't really seem to be related to your PR. Thanks for take a look 🤗

**Comment by tinycarol** [comment]
ci:reevaluate:1387401_2374

**Comment by susanchen3** [comment]
Taking a look! :detective:

**Review by carloslancha — COMMENTED** [review]
LGTM. We can improve the performance of this by using `useMemo` to set `sortedLocales` so is not processed on every render. If you consider it useful apply it, if not feel free to forward it :)

**Comment by tinycarol** [comment]
ci:test:sf

**Comment by tinycarol** [comment]
ci:test:relevant

**Comment by tinycarol** [comment]
ci:test:relevant

**Comment by susanchen3** [comment]
Reviewed, test failures are unrelated :heavy_check_mark: Looks good to manually forward from QA perspective :) :rocket:

**Comment by tinycarol** [comment]
Manually forwarded to Brian https://github.com/brianchandotcom/liferay-portal/pull/121872, thanks @susanchen3 ❤️

**Pull request closed without merging**
