### PR TITLE
LPS-167891 Update user icon colors

### PR DESCRIPTION
**Pull request by marcoscv-work**
Update colors to match minimum accessibility contrast, currently applied to styled theme.

### CODE REVIEW

**Comment by marcoscv-work** [comment]
ci:test:sf

**Comment by marcoscv-work** [comment]
ci:test:relevant

**Comment by marcoscv-work** [comment]
ci:test:relevant

**Comment by pat270** [comment]
ci:test:relevant

**Comment by pat270** [comment]
LGTM! I'm not sure what this failure is about, maybe @eltonccdantas might know?

**Comment by marcoscv-work** [comment]
Forgotten add a screenshot in different areas:

image

Now all personal user icon are the same color

**Comment by marcoscv-work** [comment]
They are just color, no test on them, can we go ahead @eltonccdantas ?
Thanks!

**Comment by edalgrin** [comment]
Since we did a similar change recently in another context, I would suggest to try to reuse the same colors.

Example:

```scss
```

**Comment by marcoscv-work** [comment]
I think you are using a not valid reference of `_variabless.scss` on `liferay-portal/modules/apps/static/portal-osgi-web/portal-osgi-web-wab-reference-support-test/src/testIntegration/resources/exploded-test-theme/css/application/_variables.scss`

There are only two files that we need to change in order to change all `user-icon-color` colors of the portal and make them the same:
`liferay-portal/modules/apps/frontend-css/frontend-css-cadmin-web/src/main/resources/META-INF/resources/clay_admin.scss`
and
`liferay-portal/modules/apps/frontend-theme/frontend-theme-styled/src/main/resources/META-INF/resources/_styled/css/application/_variables.scss`

With this PR both files have the same `$user-icon-color-*` variables.

**Comment by marcoscv-work** [comment]
ci:test:relevant

**Comment by john-co** [comment]
Reviewed. Test failures are unrelated. :heavy_check_mark: 

Ok to manually forward from QA perspective. Pending dev approval.

**Comment by marcoscv-work** [comment]
> Reviewed. Test failures are unrelated. ✔️
> 
> Ok to manually forward from QA perspective. Pending dev approval.

We have the approval from Patrick (commented) and Eduardo (thumbs up in my previous comment).

**Comment by john-co** [comment]
forwarded to https://github.com/brianchandotcom/liferay-portal/pull/130121

**Pull request closed without merging**
