### PR TITLE
LPS-147404, LPS-147832 | Assert 'more actions' and quick actions are displayed 

### PR DESCRIPTION
**Pull request by susanchen3**
**Background**
Create automated tests for Management Toolbar.

**Test Plan**
- Given a user of the portal
- When the user opens any section with the management toolbar
- Then the 'more actions' button will be displayed
- And all the actions of the MT will be displayed as icon plus text buttons
-
- Given a user of the portal
- When the user opens any section with the management toolbar
- And clicks on the 'more actions' button
- Then the quick actions will be displayed 

**JIRA Ticket:**
https://issues.liferay.com/browse/LPS-147404
https://issues.liferay.com/browse/LPS-147832

*Side Note: 'more actions' button isn't actually a button, just referring to the vertical ellipsis

### CODE REVIEW

**Comment by susanchen3** [comment]
ci:test:frontend:nocompile

**Comment by john-co** [comment]
Just started reviewing :)

**Review by john-co — APPROVED** [review]
Looks good to me! :sunglasses:

**Comment by john-co** [comment]
ci:forward

**Pull request closed without merging**
