### PR TITLE
LPS-199022 CSRF bypass related to `p_l_back_url` in content page editor

### PR DESCRIPTION
**Pull request by dsanz**
In this PR we're adding a new hardcoded parameter to handle the case where we don't want SPA to deal with links pointing to sensitive portlet action URLs

We might want to revert commerce PR that tried to solve this via java for some specific cases

@boton @bryceosterhaus pls take a look

### CODE REVIEW

**Comment by boton** [comment]
ci:test:sf

**Comment by boton** [comment]
**LGTM**, I fixed one SF complaint and pushed it.

## Manually Tested

### Before PR
image

###  After PR
image

#### Console output

```sh
2023-12-01 12:02:41.721 WARN  [http-nio-8080-exec-2][SecurityPortletContainerWrapper:395] User 20122 is not allowed to access URL http://localhost:8080/group/guest/~/control_panel/manage and portlet com_liferay_server_admin_web_portlet_ServerAdminPortlet: User 20122 did not provide a valid CSRF token for com.liferay.portlet.SecurityPortletContainerWrapper
```

**Comment by dsanz** [comment]
ci:test:sf

**Comment by dsanz** [comment]
ci:forward

**Comment by dsanz** [comment]
@mateusralv we'd like to forward this to fix the issue as soon as we can. Could you please let me know if relevant failureas are related? thanks a lot

**Comment by mateusralv** [comment]
Hi @dsanz The failures are not related. 🎉

**Comment by dsanz** [comment]
ci:forward:force

**Pull request closed without merging**
