### PR TITLE
LPS-168946 Fix pagination accessibility on new-site page

### PR DESCRIPTION
**Pull request by edalgrin**
This PR Fixes pagination accessibility on new-site page

accessibility-a

### CODE REVIEW

**Comment by edalgrin** [comment]
ci:test:relevant

**Comment by edalgrin** [comment]
ci:forward:force

**Comment by dsanz** [comment]
ci:forward:force

**Comment by edalgrin** [comment]
Manual forwarded in https://github.com/brianchandotcom/liferay-portal/pull/132702

**Pull request closed without merging**
