### PR TITLE
LRQA-61019 Add Theme test of publishing a Theme’s Look and Feel settings from staged to live

### PR DESCRIPTION
**Pull request by zhangyan0701**
https://issues.liferay.com/browse/LRQA-61019

/cc @john-co @manoelcyreno

### CODE REVIEW

**Comment by zhangyan0701** [comment]
ci:test:sf

**Comment by zhangyan0701** [comment]
ci:test:sf

**Comment by zhangyan0701** [comment]
ci:test:sf

**Comment by jbalsas** [comment]
Hey @zhangyan0701, @john-co, @manoelcyreno I'm really conflicted about this test. I'm 90% sure this is a test for Echo (or even Staging) and in no way related to the theme's infrastructure.

You should be more or less be able to suspect that by seeing the important keywords in the test like "Site Builder", "Pages", "Page Configuration", "Staging"...

As infrastructure, we should be testing that a theme provides settings that can be queried to retrieve whatever is defined in their model (label, type, default value...). How those are used are part of the application layer. I haven't gone into the test in detail, but my guess is this is mostly testing the [`layout-admin-web`](https://github.com/liferay-frontend/liferay-portal/tree/master/modules/apps/layout/layout-admin-web/src/main/resources/META-INF/resources) module which uses theme settings to render forms and store their values on a per-layout or per-layout-set basis. 

An example of what we should be testing (from our end) can be found in [layout-admin-web/.../look_and_feel_theme_details](https://github.com/liferay-frontend/liferay-portal/blob/master/modules/apps/layout/layout-admin-web/src/main/resources/META-INF/resources/look_and_feel_theme_details.jsp#L140)

```java
<%
Map<String, ThemeSetting> configurableSettings = selTheme.getConfigurableSettings();
[...]
for (Map.Entry<String, ThemeSetting> entry : configurableSettings.entrySet()) {
    String name = LanguageUtil.get(selThemeResourceBundle, entry.getKey());
    ThemeSetting themeSetting = entry.getValue();

    String type = GetterUtil.getString(themeSetting.getType(), "text");
    String value = StringPool.BLANK;

    [...]
}
```

As you can see, that's the infrastructure we offer which other teams use to build their apps. That's what I think we should be testing and ensuring works.

**Review by jbalsas — CHANGES_REQUESTED** [review]
I would suggest we offer this test to echo or other teams interested and re-focus our efforts on testing the real theme infrastructure which is still yet to be looked into.

**Comment by zhangyan0701** [comment]
@jbalsas Thanks for taking look at the tests!

If I understand correctly, in this case we should check if the configurable settings and their values that are designed in classic-theme can display in page's look and feel tab and are editable, but if the changes can reflect in pages, that belongs to Echo team, right?

**Comment by jbalsas** [comment]
> If I understand correctly, in this case we should check if the configurable settings and their values that are designed in classic-theme can display in page's look and feel tab and are editable, but if the changes can reflect in pages, that belongs to Echo team, right?

The page's look and feel tab is also part of the Echo team. In this case, I think we could use:
- Java integration tests with a test theme to ensure that settings are properly read and exposed to consumers (like the look and feel page).
- Java integration tests to ensure our Classic theme provides the expected settings

I'm closing here since we won't be merging this ourselves. Feel free to continue the conversation in our channel!

**Pull request closed without merging**
