### PR TITLE
LPS-121424 Fix inserting images in IE 11

### PR DESCRIPTION
**Pull request by julien**
In this change, we use CKEDITOR's `insertElement` method instead of
`insertHtml` - for some reason on IE, this was preventing the modal to be closed

Before fix:

After fix:

**Test plan**

- Fetch this branch and deploy the `frontend-editor-ckeditor-web` module
- Open IE 11 
- Navigate to "Content & Data" > "Knowledge Base"
- Click on the blue "+" button in the top right and select "Basic" Article"
 - Add an image from the editor
- Assert that the selected image is inserted and that the modal is closed

### CODE REVIEW

**Comment by julien** [comment]
ci:test:sf

**Comment by julien** [comment]
ci:test:relevant

**Review by wincent — APPROVED** [review]
Disclaimer: haven't tested this myself, but your test plan looks good to me.

The fix seems reasonable.

**Comment by PablitoBonito** [comment]
ci:test:bundle

**Comment by john-co** [comment]
ci:stop

**Comment by john-co** [comment]
ci:test:bundle

**Comment by PablitoBonito** [comment]
ci:stop

**Comment by john-co** [comment]
ci:test:bundle

**Comment by michaelhashimoto** [comment]
ci:test:bundle

**Comment by julien** [comment]
ci:forward

**Pull request closed without merging**
