### PR TITLE
LPS-113561 Avoid use of Liferay.provide in dynamic-data-lists-web

### PR DESCRIPTION
**Pull request by wincent**
Moving this here from https://github.com/wincent/liferay-portal/pull/339 to keep things centralized.

cc @julien 

Description copied from commit:

---

As part of [LPS-113561](https://issues.liferay.com/browse/LPS-113561), we eventually want to deprecate the `Liferay.provide` function.

In this change, we avoid declaring the `<portlet:namespace />selectRecordSet` function as a global on the `window` object, and also remove the `<portlet:namespace />` prefix from the `selectRecordSet` function.

To test this change:

- Navigate to "Content And Data > Dynamic Data Lists"
- Click on the "+" button to create a new Dynamic Data List
- Enter a name for your list
- Click the "Select" button underneath the "Data Definition" input field
- In the modal window that appears, click on "Contacts"
- Click on the "Save" button
- Navigate to "Site Builder > Pages"
- Click on the "+" button to create a new page
- Select the "Blank" template from "Basic Templates"
- Enter a name for your page (for example Page)
- Drag and drop the "Dynamic Data Lists Display" widget on the page
- Click the kebab menu on the right side of the "Dynamic Data Lists Display" widget
- Click on "Configuration"
- In the modal window that appears, click on the Dynamic Data List's name created previously
- Click on the "Save" button

As a result, a success notification should be displayed confirming you have successfully updated the widget's configuration, and no JS errors should appear in the browser's console.

### CODE REVIEW

**Comment by wincent** [comment]
ci:test:sf

**Comment by wincent** [comment]
ci:test:relevant

**Comment by wincent** [comment]
Tests failed on https://github.com/wincent/liferay-portal/pull/339 so giving them another try here. Still need to look at the recent changes to the code, as I haven't looked at this since the last update.

**Comment by wincent** [comment]
I see "DDL" in the failures, which makes me think it is possibly legit. @john-co: would you mind checking for us?

**Comment by wincent** [comment]
ci:test:bundle

**Comment by john-co** [comment]
@rodrigocunhaa, seeing the same error on the workflow tests here too. Can you take a look?

https://github.com/liferay-frontend/liferay-portal/pull/8#issuecomment-645506592

**Comment by rodrigocunhaa** [comment]
Hi @john-co , the path is fixed and merged. If you run the tests again, it should pass.

**Comment by john-co** [comment]
Thanks @rodrigocunhaa!

Reviewed. Test failures are unrelated. :heavy_check_mark: 

Note: I think `ci:forward` may work now. I'm just not sure if this applies to test results received before this implementation. https://liferay.slack.com/archives/C19PWQ74J/p1592420332050100

**Comment by wincent** [comment]
Let's give it a try then.

**Comment by wincent** [comment]
ci:forward

**Comment by wincent** [comment]
> Please try again later

Ok!

**Comment by wincent** [comment]
ci:forward

**Comment by wincent** [comment]
Seeing as CI is not playing nicely on this one, I squashed and forwarded it here instead for "one last" try: https://github.com/liferay-frontend/liferay-portal/pull/33

**Pull request closed without merging**
