### PR TITLE
LPS-116099 Fix style of product-menu items in mobile

### PR DESCRIPTION
**Pull request by eduardoallegrini**
This is a simple style fix, I added the required responsive change and a further modification for the sub-navigation items.

Here's the result

Screenshot 2020-07-02 at 16 14 56
Screenshot 2020-07-02 at 16 14 14

---

Having said that, @jbalsas if we are planning to keep this menu, we should consider a renovation of the markup and CSS, right now there are 10 different `.product-menu`s and a lot of "noise" in the file https://github.com/liferay/liferay-portal/blob/master/modules/apps/product-navigation/product-navigation-product-menu-theme-contributor/src/main/resources/META-INF/resources/product_navigation_product_menu.scss

/cc @marcoscv-work

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:test:sf

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
> Having said that, @jbalsas if we are planning to keep this menu, we should consider a renovation of the markup and CSS, right now there are 10 different .product-menus and a lot of "noise" in the file https://github.com/liferay/liferay-portal/blob/master/modules/apps/product-navigation/product-navigation-product-menu-theme-contributor/src/main/resources/META-INF/resources/product_navigation_product_menu.scss

I don't see why not... let's get this fixed and then figure out what else we can do... one thing that worries me is to touch this a lot now that we're getting closer to release and add too much instability for little gain... 🤔

**Comment by jbalsas** [comment]
@pat270, since @marcoscv-work is on PTO, do you mind signing off on this?

**Comment by pat270** [comment]
I'll take a look right now.

**Comment by jbalsas** [comment]
@eduardoallegrini, feel free to push things forward if you've gotten clear approval from reviewers 😉

**Comment by jbalsas** [comment]
ci:forward

**Pull request closed without merging**
