### PR TITLE
LPS-145947 Adapts QuestionsEditor to use new onChange payload from Editor component

### PR DESCRIPTION
**Pull request by diegonvs**
> This PR re-revert changes of LPS-137761 (Add BalloonEditor to contentEditor)

## In Short

Instead of defining global handler in base Editor component, keep Editor component simple as it was and replicate the logic of exposing globals in ClassicEditor and BalloonEditor as these components are being inteded to expose.

Tested with:

**- Balloon Editor**

1. Using contentEditor on Blogs under Feature Flag

2. Inside ckeditor-sample-web module

**- Classic Editor**

1. Creating and using a Basic Web Content

2. Creating a Basic Article of Knowledge Base

**- QuestionsEditor**

Following the steps described on https://issues.liferay.com/browse/LPS-145947 :)

### CODE REVIEW

**Comment by diegonvs** [comment]
ci:test:frontend

**Review by markocikos — COMMENTED** [review]
Do we need to revert all code duplication, `getHTML` etc.? If the intent is to have external references to `BalloonEditor` and `ClassicEditor`, why not just add `forwardRef`s?

**Comment by diegonvs** [comment]
> why not just add forwardRefs?

I was already have done this(see the commit on top the revert, I'm lost in tracking those commits but trust me 🤷🏼 😂 ) this but it don't fix the issue.

The main issue here is about maintianing getHTML etc inside Editor(the "base" Editor) component. When moving things to Editor component we were thinking about avoiding duplication but it broke the usages of Editor component where it was expected a "pure" React component :)

With this thought, I replicated the exposes and the onChange modification to BalloonEditor and ClassicEditor components.

**Comment by diegonvs** [comment]
ci:test:sf

**Comment by diegonvs** [comment]
ci:test:relevant

**Comment by diegonvs** [comment]
After 2 hours juggling with git for making the revert of the reverts be fine and to make sure that I didn't lost anything. Here it is:

@markocikos, ready for review again

**Comment by diegonvs** [comment]
ci:test:relevant

**Comment by markocikos** [comment]
> The main issue here is about maintianing getHTML etc inside Editor(the "base" Editor) component. When moving things to Editor component we were thinking about avoiding duplication but it broke the usages of Editor component where it was expected a "pure" React component :)

@diegonvs I am not sure what you mean by a "pure" React component :thinking:  There are no gradations in React-ness. A component is a React component or it is not.

The cause of the bug is that `onChange` is a default event listener in `Editor`, but has special implementation in `ClassicEditor`.   As a quick-fix, changing [these lines](https://github.com/liferay/liferay-portal/blob/master/modules/apps/questions/questions-web/src/main/resources/META-INF/resources/js/components/DefaultQuestionsEditor.es.js#L82-L84) to
```js
onChange={(data) => {
   setContent(data);
}}
```
should fix the issue.

But, the root problem here is that people are using `Editor` directly. I don't know why are we exposing it :disappointed:  We want to support `ClassicEditor` and `BalloonEditor`. `Editor` serves as an internal mechanism, to have common code, such as dependancy on `ckeditor4-react`. I see two usages, in `questions-web` and `portal-workflow-kaleo-designer-web`. What we should do is plan to migrate those two usages to `ClassicEditor`, and remove `Editor` from exports.

**Comment by julien** [comment]
@markocikos, @diegonvs hey guys, sorry to interrupt :) I think @diegonvs might be referring to https://reactjs.org/docs/react-api.html#reactpurecomponent when he mentions a "React pure component", that said since we're using function components I also got confused.

**Comment by diegonvs** [comment]
> I am not sure what you mean by a "pure" React component

Sorry, I mean a component without too much logic inside it, like states etc

**Comment by diegonvs** [comment]
After talking internally, we decided to maintain Editor component with the code to prevent DRY and we just updated the usages on questions-web. It will fix the issue. See slack discussion: https://liferay.slack.com/archives/C3JBR21HA/p1643920675100599

**Comment by diegonvs** [comment]
ci:test:relevant

**Comment by diegonvs** [comment]
ci:test:sf

**Comment by markocikos** [comment]
@diegonvs To simplify development, let's discard this solution path, and focus on https://github.com/liferay-frontend/liferay-portal/pull/1891. If that one leads to a dead end or gets too complicated, we can revisit this one.

**Pull request closed without merging**
