### PR TITLE
LPS-102111 Remove sidebar compat layer

### PR DESCRIPTION
**Pull request by pat270**
https://issues.liferay.com/browse/LPS-102111

### CODE REVIEW

**Comment by pat270** [comment]
ci:test:sf

**Comment by pat270** [comment]
ci:test:relevant

**Comment by pat270** [comment]
ci:stop

**Comment by pat270** [comment]
ci:test:sf

**Comment by pat270** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
ci:test:bundle

**Comment by zhangyan0701** [comment]
Results of ci:test:relevant:

- [Test Fix] - LocalFile.CPDocumentsandmedia#EditDocument: need to update path DocumentsAndMediaDocument#DOCUMENT_INFO_FILE_NAME from "//h3[contains(@class,'sidebar-title')]" to "//h3[contains(@class,'component-title)]".

- [Related] - The DM Folders not display correctly. The ellipsis icon of folder display outside of the card, and the second folder is too wide.
LocalFile.CPDocumentsandmedia#EditFolder
LocalFile.CPDocumentsandmedia#MoveToRecycleBinFolder

DMfolder

- [Not sure about this one] - In Web Content's Info panel, there is no close icon displays on the UI, but in HTML code there is a button element with class sidenav-close. No item in UI matches it. Not sure if button element should exist in HTML. I am not about this because this doesn't happen in DM's Info panel.

LocalFile.WebContentExportImport#AddCreatedStructureForImportedTemplate
LocalFile.WebContentExportImport#ImportAndUseGlobalStructureAndTemplate
LocalFile.WebContentExportImport#MoveImportedWebContentArticlesToFolders

web content info panel

**Comment by pat270** [comment]
@zhangyan0701 Thanks for catching these.

> The DM Folders not display correctly. The ellipsis icon of folder display outside of the card, and the second folder is too wide.

Should be fixed now.

>  In Web Content's Info panel, there is no close icon displays on the UI, but in HTML code there is a button element with class sidenav-close.

All the info panels have this. It should display when the screen size is less than 576px.

> Need to update path DocumentsAndMediaDocument#DOCUMENT_INFO_FILE_NAME from "//h3[contains(@Class,'sidebar-title')]" to "//h3[contains(@Class,'component-title)]".

It might be `component-subtitle` instead of `component-title` now.

**Comment by pat270** [comment]
ci:test:sf

**Comment by pat270** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
ci:test:bundle

**Comment by zhangyan0701** [comment]
> All the info panels have this. It should display when the screen size is less than 576px.

@pat270 Thanks for the confirmation! I see now. So this is also a test fix.

I resend in PR https://github.com/liferay-frontend/liferay-portal/pull/547 with the fix of the failed tests and rerun ci tests there.

**Pull request closed without merging**
