### PR TITLE
LPS-115273 Use openModal instead of Liferay.Util.openWindow

### PR DESCRIPTION
**Pull request by brunobasto**
This PR is a follow up on a review @wincent did a while ago: See https://github.com/wincent/liferay-portal/pull/319#discussion_r436904186

### CODE REVIEW

**Comment by brunobasto** [comment]
ci:test:sf

**Comment by brunobasto** [comment]
ci:test:relevant

**Comment by markocikos** [comment]
LGTM!

**Comment by markocikos** [comment]
ci:forward

**Comment by jbalsas** [comment]
I got here late, but I have the same question about some of this as in https://github.com/liferay-frontend/liferay-portal/pull/117#issuecomment-658594622

Do we really need all of these indirections? In particular, the `openPermissionsModal(url)` is only used once for a straightforward `openModal` call... 🤔

**Comment by brunobasto** [comment]
Makes sense. I'll make sure to squeeze that change in a future PR

**Pull request closed without merging**
