### PR TITLE
LPS-154644, LPS-154640 | master

### PR DESCRIPTION
**Pull request by jaydawu**
**Background**
Create automated tests for Walkthrough component.

**Test Plan**
**WalkthroughPopover#CanDisplayStepNumber**
Given: frontend-js-components-sample-web deployed to test page
And Given: Navigate to Walkable tab on sample portlet
And Given: Click hotspot element
When: Click through all primary step buttons
Then: Step number is displayed consecutively

**WalkthroughPopover#CanHaveAShadowAroundElement**
Given: frontend-js-components-sample-web deployed to test page
And Given: Navigate to Walkable tab on sample portlet
When: Click hotspot element until Step 4
Then: element is outlined with a shadow

**JIRA Ticket:**
https://issues.liferay.com/browse/LPS-154644
https://issues.liferay.com/browse/LPS-154640

### CODE REVIEW

**Comment by jaydawu** [comment]
ci:test:sf

**Comment by jaydawu** [comment]
ci:test:frontend:nocompile

**Review by susanchen3 — APPROVED** [review]
Looks good to me! Thanks Jayda!

**Comment by susanchen3** [comment]
ci:forward

**Comment by jaydawu** [comment]
Resend https://github.com/brianchandotcom/liferay-portal/pull/119040

**Pull request closed without merging**
