### PR TITLE
LPS-130137 Mark frontend-js-state-web for inclusion in release

### PR DESCRIPTION
**Pull request by wincent**
We weren't in a hurry to do this because we wanted to let it "bake" for a while. But as per [discussion in Slack](https://liferay.slack.com/archives/G01FM0XR2L8/p1615547338090600) we're flipping the switch now so that it can be included in the next release, whichever that might be.

### CODE REVIEW

**Comment by wincent** [comment]
```
java.net.NoRouteToHostException: No route to host (Host unreachable)
```

not-my-fault

Going to try again.

**Comment by wincent** [comment]
ci:test:sf

**Comment by wincent** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by wincent** [comment]
ci:forward

**Comment by wincent** [comment]
Feeling lucky.

**Comment by wincent** [comment]
ci:forward

**Comment by jbalsas** [comment]
Screen Shot 2021-04-07 at 17 30 17

You did 😂

**Comment by wincent** [comment]
> Shall we try again, just for the lols?

Indeed! My thinking is, "it is bad to hammer CI with a bunch of retries when it is probably under strain" _but_ "it is the end of the day here in Spain and if this doesn't forward today it will be delayed by around 24 hours", so it seems reasonable to be swayed in favor of avoiding the long delay.

move-fast-with-stable-infra

**Comment by jbalsas** [comment]
> Indeed! My thinking is, "it is bad to hammer CI with a bunch of retries when it is probably under strain" but "it is the end of the day here in Spain and if this doesn't forward today it will be delayed by around 24 hours", so it seems reasonable to be swayed in favor of avoiding the long delay.

Forwarding manually is off the table? 😂

**Comment by wincent** [comment]
> Forwarding manually is off the table? 😂

Well, you do have a point. 🤔

move-fast-and-break-things

**Comment by wincent** [comment]
Ok, going to try and save a Bothan and close this. Manual forward is at: https://github.com/brianchandotcom/liferay-portal/pull/100584

**Comment by wincent** [comment]
ci:stop

**Comment by wincent** [comment]
ci:stop

**Pull request closed without merging**
