### PR TITLE
LPS-175255 - Add API to access control panel spritemap

### PR DESCRIPTION
**Pull request by bryceosterhaus**
https://issues.liferay.com/browse/LPS-175255

I wasn't sure whether to call it `controlPanelSpritemap`, `systemSpritemap`, or `adminSpritemap`.

I settled with control panel since we already have "control panel" type wording in themeDisplay

### CODE REVIEW

**Comment by carloslancha** [comment]
LGTM!

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
ci:test:sf

**Comment by izaera** [comment]
:+1:

**Comment by mateusralv** [comment]
I'm on it 🕵🏽

**Comment by mateusralv** [comment]
Hi @bryceosterhaus the failures are not related to your PR.

[Testray comparison ](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1678282289080&testrayRunIdA=2224552379&testrayRunIdB=2224769337)

**Pull request closed without merging**
