### PR TITLE
LPS-174534 Update packages `@clayui/*` to v3.87.0

### PR DESCRIPTION
**Pull request by matuzalemsteles**
### Bug Fixes

-   **@clayui/autocomplete:** fix error when filtering autocomplete with regex special character ([079e4f7](https://github.com/liferay/clay/commit/079e4f7985a50a54dfbda36e1460204a0562a922))
-   **@clayui/css:** Atlas Dropdown items should be 32px tall ([237f8fd](https://github.com/liferay/clay/commit/237f8fd744d4f8c5fa259c20e2837500301e6f31))
-   **@clayui/css:** Buttons btn-secondary should have darker border for better contrast ([336bdc3](https://github.com/liferay/clay/commit/336bdc3c290e1ec2c2994618ddbca93669a0eab9))
-   **@clayui/css:** Cadmin declare font size for btn-monospaced size variants ([2e85acd](https://github.com/liferay/clay/commit/2e85acde4b9a8521c77d94054994a53dc3c457a2))
-   **@clayui/css:** Cadmin text-# utilities should use px values ([a47aa7e](https://github.com/liferay/clay/commit/a47aa7e506c460db81727dca5e3b4ae03a50f850))
-   **@clayui/modal:** fixes error when closing the modal and not removing elements with inert ([1e99716](https://github.com/liferay/clay/commit/1e997160e7edada2fbc1ee4b928cbfe9ac54a40d))
-   **@clayui/shared:** prevent closing the modal when clicking outside an Overlay rendered in the modal ([d363535](https://github.com/liferay/clay/commit/d36353591e43dfe46841c48006298e8a3853fb21))

### Features

-   **@clayui/core:** adds new selection API to configure more options ([7839fa2](https://github.com/liferay/clay/commit/7839fa2c801ba2d4736fffd85c7b141551b69a70))
-   **@clayui/shared:** adds the possibility to have overlay stacked ([1a4d281](https://github.com/liferay/clay/commit/1a4d281ab9e0aed7275c9f9a27a9d2e014ed8ab6))
-   **@clayui/tabs:** adds the pattern of uncontrolled to the `active` property of Tabs.Item in the new composition ([fd5299a](https://github.com/liferay/clay/commit/fd5299a6148f67de85b4d8f565ce2331f137472e))

### CODE REVIEW

**Comment by matuzalemsteles** [comment]
cc @mateusralv

**Comment by mateusralv** [comment]
I'm on it!

**Comment by mateusralv** [comment]
Hi @matuzalemsteles The `ci:test:relevant` did not return results and no tests came to run, it seems strange I found something in one of the logs, do you think it may be related? I will run again 

```
     [exec] 
     [exec] > Task :apps:frontend-theme:frontend-theme-dialect:packageRunBuild FAILED
     [exec] [19:57:55] 'build:compile-css' errored after 611 ms
     [exec] [19:57:55] [31mError[39m in plugin "[36msass[39m"
     [exec] Message:
     [exec]     build/_css/clay/atlas/variables/_globals.scss
     [exec] Error: $color: var(--color-brand-secondary) is not a color.
     [exec]     ���
     [exec] 113 ��� $secondary-l0: clay-lighten(saturate(adjust-hue($secondary, 3), 0.03), 11.18);
     [exec]     ���                                      ^^^^^^^^^^^^^^^^^^^^^^^^^
     [exec]     ���
     [exec]   build/_css/clay/atlas/variables/_globals.scss 113:38  @import
     [exec]   build/_css/clay/atlas/_variables.scss 1:9             @import
     [exec]   build/_css/clay/atlas.scss 9:9                        @import
     [exec]   build/_css/clay.scss 1:9                              root stylesheet
     [exec] Details:
     [exec]     formatted: Error: $color: var(--color-brand-secondary) is not a color.
     [exec]     ���
     [exec] 113 ��� $secondary-l0: clay-lighten(saturate(adjust-hue($secondary, 3), 0.03), 11.18);
     [exec]     ���                                      ^^^^^^^^^^^^^^^^^^^^^^^^^
     [exec]     ���
     [exec]   build/_css/clay/atlas/variables/_globals.scss 113:38  @import
     [exec]   build/_css/clay/atlas/_variables.scss 1:9             @import
     [exec]   build/_css/clay/atlas.scss 9:9                        @import
     [exec]   build/_css/clay.scss 1:9                              root stylesheet
     [exec]     line: 113
     [exec]     column: 38
     [exec]     file: /opt/dev/projects/github/liferay-portal/modules/apps/frontend-theme/frontend-theme-dialect/build/_css/clay/atlas/variables/_globals.scss
     [exec]     status: 1
     [exec]     messageFormatted: build/_css/clay/atlas/variables/_globals.scss
     [exec] Error: $color: var(--color-brand-secondary) is not a color.
     [exec]     ���
     [exec] 113 ��� $secondary-l0: clay-lighten(saturate(adjust-hue($secondary, 3), 0.03), 11.18);
     [exec]     ���                                      ^^^^^^^^^^^^^^^^^^^^^^^^^
     [exec]     ���
     [exec]   build/_css/clay/atlas/variables/_globals.scss 113:38  @import
     [exec]   build/_css/clay/atlas/_variables.scss 1:9             @import
     [exec]   build/_css/clay/atlas.scss 9:9                        @import
     [exec]   build/_css/clay.scss 1:9                              root stylesheet
     [exec]     messageOriginal: $color: var(--color-brand-secondary) is not a color.
     [exec]     ���
     [exec] 113 ��� $secondary-l0: clay-lighten(saturate(adjust-hue($secondary, 3), 0.03), 11.18);
     [exec]     ���                                      ^^^^^^^^^^^^^^^^^^^^^^^^^
     [exec]     ���
     [exec]   build/_css/clay/atlas/variables/_globals.scss 113:38  @import
     [exec]   build/_css/clay/atlas/_variables.scss 1:9             @import
     [exec]   build/_css/clay/atlas.scss 9:9                        @import
     [exec]   build/_css/clay.scss 1:9                              root stylesheet
     [exec]     relativePath: build/_css/clay/atlas/variables/_globals.scss
     [exec]     domainEmitter: [object Object]
     [exec]     domainThrown: false
     [exec] 
     [exec] [19:57:55] 'build' errored after 2.09 s
     [exec] Command /opt/dev/projects/github/liferay-portal/modules/node_modules/@liferay/npm-scripts/node_modules/.bin/gulp build --css-common-path build_gradle/frontend-css-common --sass-include-paths /opt/dev/projects/github/liferay-portal/modules/node_modules --styled-path /opt/dev/projects/github/liferay-portal/modules/apps/frontend-theme/frontend-theme-styled/src/main/resources/META-INF/resources/_styled --unstyled-path /opt/dev/projects/github/liferay-portal/modules/apps/frontend-theme/frontend-theme-unstyled/src/main/resources/META-INF/resources/_unstyled exited with code 1
     [exec] error Command failed with exit code 1.
```

**Comment by matuzalemsteles** [comment]
Hey @mateusralv I'll take a look at this I think it's related to the CSS changes.

**Comment by matuzalemsteles** [comment]
I fixed the bug in Clay and tested it locally, now it seems to be working fine. I'll run the tests again.

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by mateusralv** [comment]
Hi @matuzalemsteles Has a unique failure in an integration test, could you take a look? 

[com.liferay.dispatch.talend.web.internal.executor.test.TalendDispatchTaskExecutorTest](https://testray.liferay.com/home/-/testray/case_results/2190603355)

```
##
## com.liferay.dispatch.talend.web.internal.executor.test.TalendDispatchTaskExecutorTest > testExecute
##

	com.liferay.portal.kernel.messaging.MessageListenerException: com.liferay.dispatch.exception.DispatchLogStartDateException: Start date must precede end date
		at com.liferay.portal.kernel.messaging.BaseMessageListener.receive(BaseMessageListener.java:41)
		at com.liferay.dispatch.talend.web.internal.executor.test.TalendDispatchTaskExecutorTest._simulateSchedulerEvent(TalendDispatchTaskExecutorTest.java:106)
		at com.liferay.dispatch.talend.web.internal.executor.test.TalendDispatchTaskExecutorTest.testExecute(TalendDispatchTaskExecutorTest.java:84)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$3.evaluate(TestExecutorRunnable.java:353)
		at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
		at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
		at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
		at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
		at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
		at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
		at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
		at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
		at org.junit.rules.RunRules.evaluate(RunRules.java:20)
		at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$1.evaluate(TestExecutorRunnable.java:237)
		at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
		at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
		at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
		at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
		at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
		at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
		at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
		at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
		at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
		at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
		at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
		at org.junit.rules.RunRules.evaluate(RunRules.java:20)
		at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable._execute(TestExecutorRunnable.java:316)
		at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable.run(TestExecutorRunnable.java:95)
		at java.lang.Thread.run(Thread.java:745)
	Caused by: com.liferay.dispatch.exception.DispatchLogStartDateException: Start date must precede end date
		at com.liferay.dispatch.service.impl.DispatchLogLocalServiceImpl._checkDispatchLogPeriod(DispatchLogLocalServiceImpl.java:177)
		at com.liferay.dispatch.service.impl.DispatchLogLocalServiceImpl.updateDispatchLog(DispatchLogLocalServiceImpl.java:153)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

[Testray Comparison](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=2&testrayRunIdB=2184795140&testrayRunIdA=2183964678&statusB=3)


The test `ObjectActions#VerifyTheConditionCardAreHidden` is failing on CI but when I run locally the test are passing, so seems like a flaky failure.

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by mateusralv** [comment]
I'm on it.

**Comment by mateusralv** [comment]
Hi @matuzalemsteles the failures are not related 🎉 

[Testray comparison](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1676040149478&testrayRunIdA=2190928720&testrayRunIdB=2191958634)

**Comment by mateusralv** [comment]
ci:test:relevant

**Comment by mateusralv** [comment]
ci:test:relevant

**Comment by mateusralv** [comment]
The failures are not related I'll forward it manually!

**Comment by mateusralv** [comment]
Forwarded to brianchandotcom: https://github.com/brianchandotcom/liferay-portal/pull/130174

**Pull request closed without merging**
