### PR TITLE
LPS-125138 Remove usages of Config.string() across DXP

### PR DESCRIPTION
**Pull request by kresimir-coko**
I've removed usages of `Config.string()` across the codebase. I've purposefully left all other validators out of this PR to both reduce the scope and to confirm this is the road we want to take. This is an alternative to #853 following up on @jbalsas' proposal.

### CODE REVIEW

**Comment by kresimir-coko** [comment]
ci:test:sf

**Comment by kresimir-coko** [comment]
ci:test:sf

**Comment by kresimir-coko** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
Ok, so after an offline conversation, we've agreed (or I've pushed @kresimir-coko to do so) on dropping this completely. We'll check if what's missing of the epic makes sense or we just focus on migrating away from metal the parts that matter.

**Comment by jbalsas** [comment]
ci:stop

**Pull request closed without merging**
