### PR TITLE
LPS-113524 Deprecate AUI `checkTab` and `processTab` utility

### PR DESCRIPTION
**Pull request by kresimir-coko**
Hey folks, it's ya boi here with a PR.

This one deprecates and removes any usages not found under `archived/` of the `checkTab` AUI utility found under `frontend-js-aui-web/util.js`.

I've tested the functionality with and without my changes and it is exactly the same, it seems that the utility was circumventing a functionality that is now in browsers by default. 

One note is that the code (found in `processTab`) suggests that it looks for the textbox and forces focus on it, but the functionality wasn't as such. It is also manipulating with the `selection` which I do not know why but it certainly doesn't work as it once might have, because the browsers don't support them anymore (`createRange()` I'm looking at you).

### CODE REVIEW

**Comment by kresimir-coko** [comment]
ci:test:sf

**Comment by kresimir-coko** [comment]
ci:test:relevant

**Comment by kresimir-coko** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
> it seems that the utility was circumventing a functionality that is now in browsers by default.

Is there any way we can be sure of this? I am hesitant to just remove the calls to checkTab and processTab without any replacements. I wonder if they were there for some security purpose or something to do with the page being embedded to an iframe.

**Comment by kresimir-coko** [comment]
Hey @bryceosterhaus, the first "issue" is that the code doesn't even reach inside the if block.

```js
if (document.all && Number(window.event.keyCode) === 9) {
	box.selection = document.selection.createRange();

	setTimeout(() => {
		Util.processTab(box.id);
	}, 0);
}
```

That is because of the `document.all` returns `false` even though it is an `HTMLAllCollection` with 534 members.

Further along, `document.selection.createRange()` throws the following error, this is because `document.selection` is `undefined`: 
```
util.js:268 Uncaught TypeError: Cannot read properties of undefined (reading 'createRange')
```

That means that `processTab` doesn't even get invoked because JS errors out on an earlier line.

If I circumvent this error and invoke `processTab` it errors out with the same error as before when trying to get the `document.all[id].selection`.

----
## A New Hope

As a test, I rewrote both into vanilla JS functions, and it behaves differently, when pressing tab it maintains focus on the textarea.

```js
checkTab(box) {
	var selection = window.getSelection().toString();

	if (Number(window.event.keyCode) === 9) {
		box.selection = selection;

		setTimeout(() => {
			Util.processTab(box.id);
		}, 0);
	}
},

processTab(id) {
	var input = document.getElementById(id);

	if (input) {
		input.selection = String.fromCharCode(9);
		input.focus();
	}
},
```

**Comment by bryceosterhaus** [comment]
Ah that is good to know about document.all an that it returns false. I dug a little deeper and found this [helpful comment on Stackoverflow](https://stackoverflow.com/questions/10350142/why-is-document-all-falsy).

Particularly this point:
> Basically, for a long time document.all was used in this way to detect old browsers.

So I think we should be safe with removing the calls to checkTab because in our supported browsers, that code will never get invoked due to document.all being false.



I think this PR is good to go!

**Comment by kresimir-coko** [comment]
ci:forward

**Pull request closed without merging**
