### PR TITLE
LPS-196695 Scroll not possible in modal windows in iOS devices

### PR DESCRIPTION
**Pull request by antonio-ortega**
Hey guys,

This piece of code is blocking scroll functionality in modal windows for iOS devices. It was added as part of [LPSA-35005](https://liferay.atlassian.net/browse/LPSA-35005), however it is not needed anymore since that original issue is now fixed through CSS, so we can get rid of this condition.

Thanks.

Regards.

### CODE REVIEW

**Comment by antonio-ortega** [comment]
ci:forward:force

**Comment by antonio-ortega** [comment]
ci:forward

**Review by markocikos — APPROVED** [review]
@antonio-ortega LGTM! :sparkles:

**Comment by antonio-ortega** [comment]
Manually forwarded https://github.com/brianchandotcom/liferay-portal/pull/141146

**Pull request closed without merging**
