### PR TITLE
LPS-118797 Bug Wiki ckeditor create table

### PR DESCRIPTION
**Pull request by boton**
### The bug

Is the same that @julien [commented](https://github.com/liferay-frontend/liferay-portal/pull/213#issuecomment-669929260).

**Steps to Reproduce:**

Navigate to CP > Content and Data > Wiki
Click Main
Click Plus button
Click on Table icon

**Expected Result:**
A table UI pop up and table inserted and renders borders.

**Actual Result:**
There's no pop up on table UI and error is thrown in browser console.

### The problem

In master the problem is the order when I click in the toolbar table button is passing first for creole_dialog_definition ([remove txtBorder](https://github.com/liferay/liferay-portal/blob/86404edebc666ff13b0e3a81e0e7be2f92bff38e/modules/apps/frontend-editor/frontend-editor-ckeditor-web/src/main/resources/META-INF/resources/_diffs/extension/creole_dialog_definition.js#L50)) and then the plugin showborders try to [get txtBorder](https://github.com/ckeditor/ckeditor4/blob/eb2d11644a796cd13cd047cd55541430359f9317/plugins/showborders/plugin.js#L131) and crash.

In master with `liferay-ckeditor@4.13.1-liferay.8` before clean plugins https://github.com/liferay/liferay-ckeditor/commit/468d7e4345d9df25cb52ad57f59f120cff1c7078#diff-e9f394f8c7b75652dab866e4d9f42b68L79 the order is other (probably because the plugin is bundled with ckeditor) first the plugin showborders get txtBorder and later creole_dialog_definition remove txtBorder.

### The fix

Don´t remove txtBorder in creole_dialog_definition **but I don't know what can happen.** 

@jbalsas could you imagine the consequences of not deleting that `txtBorder`?  In the creole dialog at a quick glance, I don´t view another option for txtBorder.

### CODE REVIEW

**Comment by wincent** [comment]
@julien and @carloslancha: can you comment on this one?

**Comment by julien** [comment]
@wincent sure, was going to review this one

**Comment by julien** [comment]
@boton rather than doing this wouldn't it be safer to re-enable the `showborders` plugin in `liferay-ckeditor`?

I'm asking because I see that the [creole_dialog_definition.js](https://github.com/liferay-frontend/liferay-portal/blob/26322670abf01ce8f7bef61d2d69a204ad562ada/modules/apps/frontend-editor/frontend-editor-ckeditor-web/src/main/resources/META-INF/resources/_diffs/extension/creole_dialog_definition.js) file hasn't been changed for a while (very little changes since the [first](https://github.com/liferay/liferay-portal/blob/a4df2c65a8fb39c139e0e9781078b2092c868f68/modules/frontend/frontend-editors-web/src/META-INF/resources/html/editors/ckeditor_diffs/extension/creole_dialog_definition.js) commit I found) and I don't know what we could break here ... (have you tried opening all ckeditor dialogs in portal to make sure?).

Additionally, two small details even though it probably doesn't matter a lot:

1. The [commit](https://github.com/liferay-frontend/liferay-portal/pull/234/commits/26322670abf01ce8f7bef61d2d69a204ad562ada) message is:

    > LPS-118797 Leave txtBorder in table/tableProperties because the plugin showborders need it

    But we're actually removing something so it's a bit confusing

2. When the table dialog is "opened" it isn't centered like the other dialogs,
    
    When deploying this change, here's what I see in wiki

    wiki

    And this is what I see when I click on the "table" button in blogs 

    blogs

**Comment by boton** [comment]
> @boton rather than doing this wouldn't it be safer to re-enable the showborders plugin in liferay-ckeditor?
👍  Yep, but I understand that is better only load plugins in the context that is needed.

> have you tried opening all ckeditor dialogs in portal to make sure?

**Comment by julien** [comment]
> +1 Yep, but I understand that is better only load plugins in the context that is needed.

Ok, well then forget my previous comment :+1: 

I guess we can work on fixing the dialog's position in another PR 

Maybe [this](https://github.com/wincent/liferay-portal/pull/247) can be a good place to start.

**Comment by julien** [comment]
ci:test:sf

**Comment by boton** [comment]
@julien if we re-enable the showborders plugin in liferay-ckeditor, only have to revert this commit 7467d404d2cec1f4a735fa1dacf4195cc28886c7 and close the bug because with the other order I think is working for me.

I'm a little scared to touch an old definition file.

**Comment by julien** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
Hey guys, 
my vote for: 
> rather than doing this wouldn't it be safer to re-enable the showborders plugin in liferay-ckeditor?
This plugin was enabled by default for all ckeditors. It doesn't make sense to have to add it in Wiki, but I still don't get why without this plugin in other editors (like KB) the table works....

**Comment by boton** [comment]
> I still don't get why without this plugin in other editors (like KB) the table works....

@ambrinchaudhary If I understand correctly this border dotted border only appears when it has no border or is greater than zero https://github.com/ckeditor/ckeditor4/blob/eb2d11644a796cd13cd047cd55541430359f9317/plugins/showborders/plugin.js#L102

**Comment by ambrinchaudhary** [comment]
Hey @julien and @carloslancha, any conclusion about which is the best approach to solve this bug?

**Comment by julien** [comment]
@ambrinchaudhary since https://github.com/liferay-frontend/liferay-portal/pull/213 was merged,  I'd suggest merging this too.

Concerning 
>  This plugin was enabled by default for all ckeditors. It doesn't make sense to have to add it in Wiki, but I still don't get why without this plugin in other editors (like KB) the table works....

We recently decided to [streamline the ckeditor bundle](https://github.com/liferay/liferay-ckeditor/pull/73), so that it contains the minimum set of plugins required. I personally don't think it's a problem to enable this plugin just for Wiki and apply this fix.

**Comment by jbalsas** [comment]
Hey @ambrinchaudhary, @boton, @julien, [Creole](http://www.wikicreole.org/wiki/Creole1.0) does **NOT** support table borders and many other things in their spec. That's the reason why we remove those from the modal definitions. 

Failing to do so will in the best case add an input that has no effect and in the worst one, make our creole parser fail to process tables at all. 

If there's a chance that field shows for creole, then we should make sure it's removed, so I think it wouldn't hurt to simply check and remove it if the field exists rather than doing it unconditionally.

**Comment by julien** [comment]
@boton @ambrinchaudhary @jbalsas re-sent here https://github.com/liferay-frontend/liferay-portal/pull/260

**Comment by jbalsas** [comment]
Closing since it's not clear what's going on here... let's please figure it out over at #260

**Pull request closed without merging**
