### PR TITLE
[7.4+][PART 4] LPS-134071 Migrate frontend-theme-styled CSS

### PR DESCRIPTION
**Pull request by edalgrin**
This PR removes all the unused and third-party CSS from `frontend-theme-styled`
- [Original PR](https://github.com/liferay-frontend/liferay-portal/pull/1877#issuecomment-1064926374)
- [Strategy](https://liferay.atlassian.net/wiki/spaces/ENGFRONTENDINFRA/pages/1341882669/LPS-127086+-+Analyze+and+prototype+possible+theme+optimizations?focusedCommentId=1969652346#comment-1969652346)
- [Changelog](https://docs.google.com/spreadsheets/d/1IG7o3hAn9w91-sg_vXQZeWhJsRBSSMTrGUi-EVfQ6H8/edit#gid=0)
- [Module testing](https://docs.google.com/spreadsheets/d/1IG7o3hAn9w91-sg_vXQZeWhJsRBSSMTrGUi-EVfQ6H8/edit#gid=1130153366)

### CODE REVIEW

**Comment by Esther-OC** [comment]
Review started 🧐

**Comment by Esther-OC** [comment]
After made the [comparison](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=3&testrayRunIdB=1635343725&testrayRunIdA=1635499718&statusB=2) between the PR and upstream, it looks like the unique failures are not related to the PR, and failed test cases are passed in previous and following routines.

Anyway, there are some failed tests in one routine that are about some changes in the `dropdown-toggle`, so it will be better to check the css changes in the element before forwarding it to avoid future problems.  
Thanks!

**Comment by edalgrin** [comment]
Hey @Esther-OC, I opened a separated [issue in Clay](https://github.com/liferay/clay/pull/4287) for this `dropdown-toggle`. Since it's not being used in Lexicon it shouldn't be used anywhere

**Comment by edalgrin** [comment]
Thank you @Esther-OC! I tried to look at the reported error but I don't know how to read/verify it and the poshi results aren't available, what did you mean?

**Comment by Esther-OC** [comment]
I think that this issue is not related to the PR, so, ok to manually forward from QA perspective.

**Comment by edalgrin** [comment]
Thank you @Esther-OC , I'll proceed with the manual forward.

**Pull request closed without merging**
