### PR TITLE
LPS-155911 [noGlobalDecl] Move ScriptData implementation to OSGi land

### PR DESCRIPTION
**Pull request by izaera**
This is similar to https://github.com/liferay-frontend/liferay-portal/pull/2368 but separating raw and non raw code into two different <script> nodes. It is a work related to https://issues.liferay.com/browse/LPS-159368

### CODE REVIEW

**Comment by izaera** [comment]
ci:test:relevant

**Comment by izaera** [comment]
Launched tests again to compare two runs.

This PR still may need to address these issues -> https://github.com/liferay-frontend/liferay-portal/pull/2368#issuecomment-1196154615

**Comment by izaera** [comment]
ci:stop

**Comment by izaera** [comment]
Launching tests again to see if compilation issues have been fixed.

**Comment by izaera** [comment]
ci:test:relevant

**Comment by izaera** [comment]
@susanchen3 I've fixed all the errors in https://github.com/liferay-frontend/liferay-portal/pull/2368#issuecomment-1196154615 except the last one (related to pages) that I cannot reproduce (I'm not sure if I have fixed it as a result of the other changes or if I have to do anything else to reproduce it).

I'll push my changes now and run test relevant again to see what happens.

Can you please have a look (if you are able to and CI finishes in your timezone :sweat_smile: ) at the next bugs (if any)? If not, I will try to analyze the raw results of the CI looking for more possible errors.

It looks like we can continue down this path and make this pass. We tried an alternative approach (https://issues.liferay.com/browse/LPS-159368) but it hasn't taken me too far :-(

Thx a lot for your help :hugs:

**Comment by izaera** [comment]
ci:test:relevant

**Comment by izaera** [comment]
@susanchen3 I think the problem with [OAuth2#AuthorizationCanBeIssuedWhenTokenIssuerMatchesWithSystemLevelOrInstanceLevel](https://testray.liferay.com/home/-/testray/case_results/1917407506) is that, after pressing "Save", the dialog should close and take you to the list again, whereas in this PR it remains in the add dialog.

I'm going to build master and see what happens there (if the dialog closes) and if so, I'll try to fix it.

**Comment by izaera** [comment]
I've run the same test (manually) in master and it works as in this PR (the add dialog is not closed). Seems to imply that the test is wrong... :thinking:

**Comment by izaera** [comment]
OK, my fault. I thought `applicationName` was "OAuth 2 Administration", which is the portlet's title. But it is the name of the item the test is creating, so the test is OK and it expects the "add dialog" not to be closed, and the page header be updated with the name of the item being created (which is "OAuth2 Application").

I'll build the PR again and see what can be happening...

**Comment by izaera** [comment]
Got it. The test is not filling the "Callback URI" field, which is mandatory:

image

It is missing the `callbackUri` parameter in this call -> https://testray.liferay.com/reports/production/logs/2022-07/test-1-38/test-portal-acceptance-pullrequest(master)/2537/functional-tomcat90-mysql57-jdk8/23/23/LocalFile.OAuth2_AuthorizationCanBeIssuedWhenTokenIssuerMatchesWithSystemLevelOrInstanceLevel/index.html.gz?authuser=0

One thing I'm not sure of is: how can a test be incorrectly written and not fail in the other PRs? Is it that we don't run all our tests once a day at least to detect these things? :thinking:

**Comment by izaera** [comment]
Apparently the test is not incorrect because that field is not mandatory :open_mouth: . The problem now is: why the CI thinks it is in that run? :thinking: 

See [this slack thread](https://liferay.slack.com/archives/C3JBR21HA/p1659442615708669) where I discuss it with @magjed4289 .

**Comment by izaera** [comment]
Found the problem! :tada: 

In this PR the Callback URI field shows as mandatory while in master it shows as optional :open_mouth: .

**Comment by susanchen3** [comment]
Taking a look now :detective: 

Great investigation on the OAuth 2 test!! :clap: thanks for the help @magjed4289 :heart:

**Comment by susanchen3** [comment]
Test failures are slowly going down :tada: 

[**Comparison run:** ](https://testray.liferay.com/home/-/testray/runs/compare?view=details&testrayRunIdA=1934742283&testrayRunIdB=1934630659&statusA=2&statusB=3&cur=1&delta=20&orderByCol=testrayComponentName&orderByType=asc)

### Unable to configure Asset Publisher on page

1. Add asset publisher on home page (or Header/Footer fragment and hover over Home button)
2. Try to click on the 3 ellipsis on the right side of the widget

-----

### Can't interact with Forms

1. Create a form
2. Add some languages and any field
3. Preview > Can't interact with the preview (it's grayed out) or the language module

-----

### Can't edit in Oauth2

1. Control Panel > OAuth 2 Administration > Add
2. Enter name and URI > Save
3. Edit Client ID or Client Secret

([OAuth2#AuthorizationCanBeIssuedWhenTokenIssuerMatchesWithSystemLevelOrInstanceLevel](https://testray.liferay.com/home/-/testray/case_results/1917407506) got past the `callbackUri` step and is now failing with this )

-----

### Can't assign users/organizations to a site in card view

1. Add user/organization
2. Product Menu > Memberships > Add
3. Change to Cards view (works for table/list view)
4. Select user/organization > Done

**Comment by izaera** [comment]
I've fixed and/or checked all errors in https://github.com/liferay-frontend/liferay-portal/pull/2586#issuecomment-1203356546

**Comment by izaera** [comment]
ci:test:relevant

**Comment by kresimir-coko** [comment]
Hey @izaera I assume this is a revival of the big PR approach?

**Comment by izaera** [comment]
@kresimir-coko yes.

**Comment by izaera** [comment]
@kresimir-coko see https://liferay.slack.com/archives/C3JBR21HA/p1659444864776879?thread_ts=1659434415.235769&cid=C3JBR21HA

**Comment by susanchen3** [comment]
We might want to run `ci:test:upstream-functional` or `ci:test:acceptance-functional` after we get through the relevant tests to check for more bugs since this is so low level :thinking: But those suites take a while to run on CI

[**Comparison run:**](https://testray.liferay.com/home/-/testray/runs/compare?view=details&testrayRunIdA=1935927741&testrayRunIdB=1935890777&statusA=2&statusB=3&cur=1&delta=20&orderByCol=testrayComponentName&orderByType=asc)

### Can't assign organizations to a site in card view

1. Add organization
2. Product Menu > Memberships > Organizations > Add
3. Change to Cards view (works for table/list view)
4. Select organization > Done

----

### Can't edit in Oauth2

1. Control Panel > OAuth 2 Administration > Add
2. Enter name and URI > Save
3. Edit Client ID or Client Secret
outh2

----

### Unable to configure Asset Publisher on page

1. Add web content
2. Create content page
3. Add Asset publisher to page
4. Try to click on the 3 ellipsis on the right side of the widget
configuration

----

**Flaky, not unique**
- LocalFile.DMPermissions#ViewDocumentWithOwnerAccessOnly
- LocalFile.CollectionDisplayWithRelatedItemsCollectionProviders#ViewRelatedCategoriesInCollectionDisplayWithCategoriesForThisItem
- LocalFile.NavigationMenusWithPreview#PreviewMenuInNavigationMenuEditor
- com.liferay.oauth2.provider.client.test.AnnotatedApplicationClientTest
- LocalFile.OpenIDConnect#ConfigureOnSystemLevelShouldApplyToInstanceLevel
- LocalFile.CollectionsWithAssetPublisher#DisplayRelatedAssetsInAssetPublisher
- LocalFile.SiteTeams#AddSiteTeamSearchUsers
- LocalFile.Staging#StagingMultipleDM
- LocalFile.SelectFromList#MapRelationshipWithCustomObject

**Comment by izaera** [comment]
OK, I've fixed the errors in https://github.com/liferay-frontend/liferay-portal/pull/2586#issuecomment-1204616896 and probably some others, because I've generalized the solution to some of them (hopefully I will fix errors instead of breaking more things :crossed_fingers: ).

However, I'm not able to reproduce the Asset Publisher error (last) and I wasn't yesterday, either. I've tried with and without JS fast load and it always work... :thinking:

**Comment by izaera** [comment]
ci:test:relevant

**Comment by izaera** [comment]
> However, I'm not able to reproduce the Asset Publisher error (last) and I wasn't yesterday, either. I've tried with and without JS fast load and it always work... thinking

I'm not even able to reproduce it with the CI bundle taken from here -> https://github.com/liferay-frontend/liferay-portal/pull/2586#issuecomment-1204293419 :shrug:

**Comment by susanchen3** [comment]
ci:test:relevant

**Comment by susanchen3** [comment]
:thinking: I think when I first started the bundle I wasn't able to reproduce the Asset Publisher issue, but once I ran a Poshi test using it, it started failing (ex. [LocalFile.ContentPages#ConfigureConfigurationTemplateOfAssetPublisherInPageEditor](https://testray.liferay.com/home/-/testray/case_results/1935892988)). Maybe some configuration in the test makes it happen :thinking: 

I can do more investigation, but I will be on PTO the next couple of days :palm_tree:

**Comment by izaera** [comment]
I've made the configuration ellipsis fail locally with `CollectionDisplayWithCollectionProviders#ViewMostViewedAssets`. It fails even refreshing the page (so, not SPA related). However it doesn't fail in Firefox, just Chrome.

**Comment by yanan** [comment]
Same here, can't reproduce the same issue on Firefox, and it is reproducible in Chrome with a config file in osgi/configs folder which set `defaultSelectionStyle="dynamic"`.
 
Taking a look at the latest test results, [Comparison run:](https://testray.liferay.com/zh/home/-/testray/runs/compare?compare=true&view=details&statusA=3&testrayRunIdB=1935927741&testrayRunIdA=1936990945&statusB=2), there is one more problem about not able to edit `client secret` in Oauth2

1. Unable to configure Asset Publisher on page
- Create a new file named com.liferay.asset.publisher.web.internal.configuration.AssetPublisherSelectionStyleConfiguration.config in which set defaultSelectionStyle to dynamic and the file to bundles/osgi/config folder 
- Add web content
- Create content page
- Add Asset publisher to page
- Try to click on the 3 ellipsis on the right side of the widget
cannot-click-configure

2. Can't edit 'Client Secret' in Oauth2
- Control Panel > OAuth 2 Administration > Add
- Enter name and URI > Save
- Edit Client Secret
cannot-edit-Client-Secret

**Comment by izaera** [comment]
Thx @yanan 

I have  been investigating more and I think that the root cause is an interaction between [this file](https://github.com/liferay/liferay-portal/blob/f8ae45aa55c90773748430ce7660a868d22bd840/modules/apps/layout/layout-content-page-editor-web/src/main/resources/META-INF/resources/page_editor/app/components/UnsafeHTML.js#L49) and the new way to bootstrap portlet JavaScript code.

It is causing several reexecutions of the same <script> nodes, which leads to multiple attachments to events and that causes the popup menu to be shown and hidden immediately after it (because the JS code sees two consecutive click events).

It needs to be fixed in code, so don't worry about testing more for now. I'll notify you all when I think it's fixed. Thx a lot @susanchen3, @yanan and @magjed4289 for your support :heart: .

**Comment by izaera** [comment]
Fixed the Asset Publisher error :sweat:

**Comment by izaera** [comment]
ci:test:relevant

**Comment by izaera** [comment]
ci:test:relevant

**Comment by mateusralv** [comment]
I’m taking a look new failures 🕵🏽

**Comment by mateusralv** [comment]
Hi @izaera, I’m still analyzing all the failures and these are some partial results that I got. 

### Asset Publisher failure

The problem with configure Asset Publisher on page is not reproducible. 🎉 

---
### Failures about forms's tests
The failures in the Forms tests:
```
FormRules#CreationCanBeCanceled 
FormRules#DisplaysFieldReferenceInCalculator
Forms#CanBeCreatedFromAutosavedDraft
Forms#CanBeDuplicated
Forms#CanBePreviewed
Forms#CanBePublished
Forms#CanBeUnpublished
```
 are related to error:
```
     [exec] > Task :yarnInstall FAILED
     [exec] Using registry http://mirrors.lax.liferay.com:4873
     [exec] /opt/dev/projects/github/liferay-portal/build/node/lib/node_modules/yarn/yarn-1.13.0.js:42668
     [exec]         _this.plugnplayEnable
```
--- 
### Failures about Oauth2's tests
The problem with edit 'Client Secret' in Oauth2 still reproducible 

Steps:
1. Control Panel > OAuth 2 Administration > Add
2. Enter name and URI > Save
3. Edit Client Secret

https://user-images.githubusercontent.com/44584050/183713409-4bcd52cb-e08c-4a91-9935-4e0269be90d2.mp4

---
I’m still analyzing failures related to Fragments, when I finish I put here a comment 🕵🏽

**Comment by izaera** [comment]
ci:test:relevant

**Comment by izaera** [comment]
I think "Failures about forms's tests" are not legitimate, because they seem to be caused by a yarn installation, which is something this PR doesn't modify at all :shrug: 

OAuth2, I'm going to check now. Will come with more news... :walking:

**Comment by izaera** [comment]
I've fixed the Oauth2 test, but I'm not going to push until the CI finishes, because I don't want to stop it.

**Comment by izaera** [comment]
I've fixed OAuth2 error.

I've also tried to reproduce `LocalFile.Checkbox#ConfigureCheckbox` manually and everything works correctly. However, the test seems badly written, because the XPath to look for the label doesn't look good to me...

**Comment by izaera** [comment]
ci:test:relevant

**Comment by izaera** [comment]
ci:rest:relevant

**Comment by izaera** [comment]
ci:rest:relevant

**Comment by izaera** [comment]
ci:stop

**Comment by izaera** [comment]
ci:rest:relevant

**Comment by izaera** [comment]
ci:test:relevant

**Comment by izaera** [comment]
ci:test:relevant

**Comment by mateusralv** [comment]
I'm taking a look this [failures](https://github.com/liferay-frontend/liferay-portal/pull/2586#issuecomment-1212347026) 🕵🏽

**Comment by mateusralv** [comment]
Sorry for the delay in returning the results, I compared with the [last results of ci:test:Relevant:](https://github.com/liferay-frontend/liferay-portal/pull/2586#issuecomment-1213131662)

-[ Comparison run](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1660324283478&testrayRunIdA=1944056892&testrayRunIdB=1944181041) with the master. 

#### Can't edit in Oauth2
The problem of not being able to edit  Oauth2 was solved, but this returning a large space, as I show in the video. 

https://user-images.githubusercontent.com/44584050/184438934-2114526f-e7d4-4226-b4cd-71f43a9838a3.mp4



---
#### Failure, not unique

1. com.liferay.document.library.change.tracking.test.DLFileVersionTableReferenceDefinitionTest
2. semantic-versioning-jdk8/0/0
3. com.liferay.oauth2.provider.client.test.AnnotationsAndHttpApplicationClientTest
4. com.liferay.oauth2.provider.client.test.TOCTOUTest
5. MastersPageTemplates#PropagateChangesFromCustomMastersToAllBasedOnCustomMasters

**Comment by susanchen3** [comment]
ci:test:acceptance-functional - triggering this suite for more test coverage as changes are very low level

**Comment by susanchen3** [comment]
The large space @mateusralv is referring to isn't unique to this PR, I am able to recreate that on master. [Results](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=2&testrayRunIdB=1946305202&testrayRunIdA=1945892709&statusB=3) from `ci:test:acceptance-functional` look promising, only one unique failure. 

[LocalFile.MastersPageTemplates#PropagateChangesFromCustomMastersToAllBasedOnCustomMasters](https://testray.liferay.com/home/-/testray/case_results/1946312340)
- similar to the Asset Publisher issue

1. add `com.liferay.asset.publisher.web.internal.configuration.AssetPublisherSelectionStyleConfiguration.config` file with `defaultSelectionStyle="dynamic"`
2. edit home page
3. add footer 
4. click on 3 ellipsis of "Home"
footer

**Comment by susanchen3** [comment]
ci:test:upstream-functional - Running one last test suite, the PR almost looks good to forward from QA perspective :) :tada:

**Comment by izaera** [comment]
> the PR almost looks good to forward from QA perspective**

scream

**Comment by izaera** [comment]
I'm trying to find a fix for https://github.com/liferay-frontend/liferay-portal/pull/2586#issuecomment-1216001122 but haven succeeded :-( 

I'm gonna need help from [victorg1991](https://github.com/victorg1991) but he's not available, so we'll have to wait :shrug:

**Comment by susanchen3** [comment]
on the bright side... the results from `ci:test:upstream-functional` look good. :tada:  I think once that bug in https://github.com/liferay-frontend/liferay-portal/pull/2586#issuecomment-1216001122 is fixed, this PR should be good to go :)

**Comment by izaera** [comment]
Fixed the last error (hopefully not introducing regressions :crossed_fingers: )

**Comment by izaera** [comment]
ci:test:relevant

**Comment by susanchen3** [comment]
Unfortunately there are [more bugs](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=2&testrayRunIdB=1953167528&testrayRunIdA=1953411623&statusB=3) :(

### Unable to configure DM on Content Pages

1. Add Documents and Media to home page (content page)
2. Try to click on the 3 ellipsis on the right
d m

----

### Portlet doesn't refresh after saving changes

1. Add Asset Publisher to home page (content page)
2. Configuration 
3. Asset Selection > Dynamic 
4. Display Settings > Set and Enable > check Ratings > Save

**Results:**
pr

**Expected Results:**
master

**Comment by susanchen3** [comment]
It seems like being unable to click on the 3 ellipsis on a widget in content pages bug is kinda common, is there a way check or have a test to check that other widgets won't break? (without having to check all widgets manually) :thinking:

**Comment by izaera** [comment]
> It seems like being unable to click on the 3 ellipsis on a widget in content pages bug is kinda common, is there a way check or have a test to check that other widgets won't break? (without having to check all widgets manually) thinking

Unfortunately not, because even if the symptom is always the same, the cause is different in each case :-(

However, we think we've fixed it for once :tada: Let's see what CI thinks about it...

**Comment by izaera** [comment]
ci:test:relevant

**Comment by susanchen3** [comment]
Seems to be integration test failures
**com.liferay.frontend.js.web.internal.servlet.taglib.aui.PortletDataRendererImplTest**
```
     [exec] com.liferay.frontend.js.web.internal.servlet.taglib.aui.PortletDataRendererImplTest > testGenerateVariableStripsLastInvalidCharacter FAILED
     [exec]     java.lang.NoClassDefFoundError: Could not initialize class com.liferay.portal.kernel.util.StringBundler
     [exec]         at com.liferay.frontend.js.web.internal.servlet.taglib.aui.PortletDataRendererImpl._computeRawCode(PortletDataRendererImpl.java:345)
     [exec]         at com.liferay.frontend.js.web.internal.servlet.taglib.aui.PortletDataRendererImpl.write(PortletDataRendererImpl.java:49)
     [exec]         at com.liferay.frontend.js.web.internal.servlet.taglib.aui.PortletDataRendererImplTest.testGenerateVariableStripsLastInvalidCharacter(PortletDataRendererImplTest.java:173)
     [exec]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec]         at java.lang.reflect.Method.invoke(Method.java:498)
     [exec]         at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
```
[Full stack trace](https://gist.github.com/susanchen3/541c042f970d9bc8ec84ffa6fc1fa7ec)

**com.liferay.frontend.taglib.servlet.taglib.ComponentTagTest**
```
     [exec] com.liferay.frontend.taglib.servlet.taglib.ComponentTagTest > testDoEndTag FAILED
     [exec]     java.lang.NullPointerException
     [exec]         at com.liferay.portal.kernel.servlet.taglib.aui.ScriptData.writeTo(ScriptData.java:137)
     [exec]         at com.liferay.frontend.taglib.servlet.taglib.ComponentTagTest._toString(ComponentTagTest.java:153)
     [exec]         at com.liferay.frontend.taglib.servlet.taglib.ComponentTagTest.testDoEndTag(ComponentTagTest.java:99)
     [exec]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec]         at java.lang.reflect.Method.invoke(Method.java:498)
```
[Full stack trace](https://gist.github.com/susanchen3/4cf50917a523d4ddf88b6d76f5db702a)

**Comment by izaera** [comment]
ci:test:relevant

**Comment by izaera** [comment]
ci:test:relevant

**Comment by yanan** [comment]
Hello @izaera , I've run `ant all` to build a new bundle with the current branch for testing.
 
The good news is that all failed functional tests are unrelated [comparison run](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=3&testrayRunIdB=1957537783&testrayRunIdA=1958366062&statusB=2)
- Existing qa ticket on OpenIdConnect [LRQA-75623](https://issues.liferay.com/browse/LRQA-75623)
- Other failed funcationl tests seem flaky since they all passed after run locally

The only unique failure on backend tests is:
**com.liferay.frontend.taglib.servlet.taglib.ComponentTagTest**
 ```
Task :apps:frontend-taglib:frontend-taglib:test
     [exec] com.liferay.frontend.taglib.servlet.taglib.ComponentTagTest > testDoEndTag STARTED
     [exec] com.liferay.frontend.taglib.servlet.taglib.ComponentTagTest > testDoEndTag FAILED
     [exec]     org.junit.ComparisonFailure: expected:<...ray.Loader.require(
     [exec]     []'null/module',
     [exec]     funct...> but was:<...ray.Loader.require(
     [exec]     [  ]'null/module',
     [exec]     funct...>
     [exec]         at org.junit.Assert.assertEquals(Assert.java:115)
     [exec]         at org.junit.Assert.assertEquals(Assert.java:144)
     [exec]         at com.liferay.frontend.taglib.servlet.taglib.ComponentTagTest.testDoEndTag(ComponentTagTest.java:109)
     [exec]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

**Comment by susanchen3** [comment]
Latest [run](https://github.com/liferay-frontend/liferay-portal/pull/2586#issuecomment-1230583031) also shows that **com.liferay.frontend.taglib.servlet.taglib.ComponentTagTest** is the only unique failure :tada:

**Comment by izaera** [comment]
I've fixed the `ComponentTagTest`, so this should be OK :tada: 
Going to launch ci:test:relevant one more time to make sure `ComponentTagTest` works and after that we can forward it.

**Comment by john-co** [comment]
I'm worried that `ci:test:stable` didn't pass...hoping it's just a fluke

**Comment by john-co** [comment]
ci:test:relevant

**Comment by john-co** [comment]
@yanan please analyze and manually forward if looks ok.

**Comment by john-co** [comment]
ci:test:stable

**Comment by john-co** [comment]
ci:test:stable

**Comment by john-co** [comment]
ci:test:stable

**Comment by john-co** [comment]
ci:test:stable

**Comment by john-co** [comment]
so it seems like `ci:test:stable` test failures were flukes and likely test flakiness with license-smoke.

**Comment by yanan** [comment]
ci:test:relevant

**Comment by michaelhashimoto** [comment]
ci:reevaluate:1387401_3377

**Comment by john-co** [comment]
Reviewed. Test failures are unrelated. :heavy_check_mark: 

Ok to manually forward from QA perspective. Pending dev approval.

----
[Testray Comparison](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=2&testrayRunIdB=1965338898&testrayRunIdA=1965303148&statusB=3)

I think the `ci:test:stable` test failures are due to the CI load. Amount of tests run on `ci:test:relevant` is causing tests that wouldn't normally pass to now fail.

**Comment by bryceosterhaus** [comment]
forwarded at https://github.com/brianchandotcom/liferay-portal/pull/122939

**Pull request closed without merging**
