### PR TITLE
LPS-144199 Rich Text predefined value cannot be deleted

### PR DESCRIPTION
**Pull request by markocikos**
### References

- [LPS-144199 Rich Text predefined value cannot be deleted (On change is not being called)](https://issues.liferay.com/browse/LPS-144199)

### What is the goal of this PR?

There are two aspects of this bugfix.

On one side, there is the easy fix, where we are removing `editor.checkDirty()` check. It was fun tracking down when and why we added this. It was more than 12 years ago, in https://github.com/liferay/liferay-portal/commit/a192c8d3d3adce019da2470512bce18de80afa8a . LPS-10749 :smile: The check was to ensure that the hacky timeout doesn't make an unwanted callback. Back then, it was [CKEditor v3.2](https://github.com/liferay/liferay-portal/blob/a192c8d3d3adce019da2470512bce18de80afa8a/portal-web/docroot/html/js/editor/_ckeditor/ckeditor.js#L6).  Through many many versions and rewrites, this check survived. Nowadays, it is unnecessary, as it probably was for a long time. The change event firing is [under the full control of `CKEditor` from `ckeditor4-react`](https://github.com/liferay/liferay-portal/blob/master/modules/apps/frontend-editor/frontend-editor-ckeditor-web/src/main/resources/META-INF/resources/editor/BaseEditor.js#L104). We are only providing callback, that should unconditionally resolve if the event happened.

As such, I believe we can safely merge this PR and call the bug fixed.

But, the awkward question remains: _why_ does `checkDirty` does not work? It is unnecessary, but it should not be bugged. It should recognize the difference between preloaded text and deleted text. This means that either (1) setting of preloaded text does not correctly set content in some internal CKeditor state, or (2) there is a bug with `checkDirty` in the base editor. I am especially fearful of (1), as it may be a symptom of [unclear content control](https://liferay.slack.com/archives/CNBG06JS3/p1634832024012200?thread_ts=1634823002.007900&cid=CNBG06JS3). Fortunately, we can ignore this, for the scope of this bug. 

#### Before PR

See JIRA ticket.

#### After PR

after

### Steps to reproduce

See JIRA ticket.

### CODE REVIEW

**Comment by diegonvs** [comment]
> It was fun tracking down when and why we added this. It was more than 12 years ago, in https://github.com/liferay/liferay-portal/commit/a192c8d3d3adce019da2470512bce18de80afa8a . LPS-10749 smile The check was to ensure that the hacky timeout doesn't make an unwanted callback. Back then, it was [CKEditor v3.2](https://github.com/liferay/liferay-portal/blob/a192c8d3d3adce019da2470512bce18de80afa8a/portal-web/docroot/html/js/editor/_ckeditor/ckeditor.js#L6).

Nice finding!

I remember seeing this `checkDirty` on ckeditor.jsp too. See this [LOC](https://github.com/liferay/liferay-portal/blob/98cd36ad4ad280d988c3979aa03104268cc234d0/modules/apps/frontend-editor/frontend-editor-ckeditor-web/src/main/resources/META-INF/resources/ckeditor.jsp#L282). Should we remove at this place too?

**Review by diegonvs — APPROVED** [review]
Nice finding! I think it's optional to remove at `ckeditor.jsp` https://github.com/liferay-frontend/liferay-portal/pull/2549#issuecomment-1189365784

**Comment by markocikos** [comment]
@diegonvs  Force-pushed! Changes are in the new commit.

When I tried to remove the dirty check from `ckeditor.jsp`, I found that we are still using the timeout check! In the commit, I removed it, replacing it with the `change` event. [`change` event](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_editor.html#event-change) was added in ckeditor v4.2, but we never updated to use it. Now we will have:
1. Consistent behavior, in both `ClassicEditor` and `<liferay-editor:editor>`
2. Better performance, no endless loop check.
3. Less code to maintain, as we rely on base CKEditor behavior.

Interestingly, even after timeout removal, there still is a use of content check with using `change` event. As it is described in event docs, `change` does not reflect actual content change. It is basically a composite event of all browser events that would change content, like key press or paste. Effect of this is that there are edge cases when content is not changed but the event is still fired. You can see example of this in the 'after' gif below, where I continue pressing backspace and event keeps firing. Normally, this should not be a problem. If it is for some reason, in a specific use of ckeditor, this can be handled in top listener. We are doing that exact change check [here in RichText](https://github.com/liferay/liferay-portal/blob/master/modules/apps/dynamic-data-mapping/dynamic-data-mapping-form-field-type/src/main/resources/META-INF/resources/RichText/RichText.es.js#L71). Keeping the check on low level does have some merit, but I still like us to be less opinionated in this case. By removing the check, we are reducing the wrapper around base CKEditor, inheriting its behavior.

An example of tag ckeditor use is Documents and Media > Item > Comment. `onChange` event toggles disabled on the `Reply` button.

**Before PR update:**
before

**After PR update:**
after2

**Comment by markocikos** [comment]
ci:test:relevant

**Comment by markocikos** [comment]
ci:forward

**Pull request closed without merging**
