### PR TITLE
LPS-182184 | Product QA | Functional Automation - LPS-182184 Export / Import FrontEnd Client Extensions individually

### PR DESCRIPTION
**Pull request by deborasoliveira**
PR Adjusted following this suggestion:
> resend without making a new client extension. 

**JIRA Ticket:**

https://liferay.atlassian.net/browse/LPS-186730

### CODE REVIEW

**Comment by deborasoliveira** [comment]
@CarlosBrichete could you take a look at these tests? Thanks in advance!

**Comment by deborasoliveira** [comment]
@CarlosBrichete FYI, I was told that it would be better if I didn't add to liferay-portal any new sample files to use in these tests.
Brian suggested that I create a new client extension, export it, then delete the file and import the downloaded file to use in the tests. So I did these steps in the Given section of each test but I don't know if it's ok to leave them in the Given section or if I should add a new task and put these steps inside it.

**Review by CarlosBrichete — APPROVED** [review]
Hey @deborasoliveira, LGTM! For me there's no problem to have it in the Given step :)

**Comment by deborasoliveira** [comment]
ci:help

**Comment by deborasoliveira** [comment]
ci:forward

**Pull request closed without merging**
