### PR TITLE
LPS-112426 Removes implementation of dynamic include to load all fields

### PR DESCRIPTION
**Pull request by matuzalemsteles**
This removes the Java implementation that we had to load all fields before continuing to render the application due to the Soy register, the import order mattered... but now we can safely remove that since we are loading the fields in https://github.com/liferay/liferay-portal/blob/master/modules/apps/dynamic-data-mapping/dynamic-data-mapping-form-renderer/src/main/resources/META-INF/resources/js/components/Field/Field.es.js.

@brunobasto I'm not sure if I removed everything from that mechanism, let me know if there is anything else that we need to remove.

I spent some time trying to do some performance tests to measure the startup time, but without success, not being able to collect the metrics. Apparently we have a gain of ~1s or more, savings of some MBs and less ~100 requests during the initialization of Forms, user view, and consequently other applications that use it.

I also did some tests with an old soy field in the ddm-field-type module to check if everything was working well.

### CODE REVIEW

**Comment by matuzalemsteles** [comment]
ci:test:sf

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by brunobasto** [comment]
Nice @matuzalemsteles! If we load https://github.com/liferay/liferay-portal/blob/master/modules/apps/dynamic-data-mapping/dynamic-data-mapping-form-renderer/src/main/resources/META-INF/resources/css/main.scss from JS we could also get rid of https://github.com/liferay-frontend/liferay-portal/blob/599e525b317dcab0510f0ed896dce69dfd493dc5/modules/apps/dynamic-data-mapping/dynamic-data-mapping-form-renderer/src/main/java/com/liferay/dynamic/data/mapping/form/renderer/internal/DDMFormRendererImpl.java#L100 as well

Looks good to me

**Comment by jbalsas** [comment]
Since this is all green and approved by @brunobasto, going to see if we hit the morning merge window with a quick forward!

**Comment by jbalsas** [comment]
ci:forward

**Pull request closed without merging**
