### PR TITLE
[TS] LPS-150397 Clay checkbox is not sending "on" by default when it is checked

### PR DESCRIPTION
**Pull request by jcampoy**
https://issues.liferay.com/browse/LPS-150397

According to this documentation https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/checkbox#attr-value , a checkbox should send "on" by default if it is checked and it has not a value attribute

This is not happening with the current implementation of the clay:checkbox, that it is sending an empty value if the attribute is not added, just something like this code:

```
	<clay:checkbox
		label="clayCheckox"
		inline="<%= true %>"
		id="<%= liferayPortletResponse.getNamespace() + "clayCheckbox" %>"
		name="<%= liferayPortletResponse.getNamespace() + "clayCheckbox" %>"
	/>
```
Steps to reproduce:

1. Deploy [org.support.liferay.checkbox.jar](https://issues.liferay.com/secure/attachment/446569/446569_org.support.liferay.checkbox.jar)[](https://issues.liferay.com/secure/attachment/446442/446442_checkKO.png) , which has a aui:checkbox, a clay:checkbox and a html input:checkbox to compare differences.
2. Add the Checkbox portlet to a page, and select the three checboxes and click save.
3. Take a look to the values in the request (with the web developer tools of the browser) and also to the server log, in where parameters are written in the log file and previously loaded with the `com.liferay.portal.kernel.util.ParamUtil` class, just this code:
```
		boolean auiCheck = ParamUtil.getBoolean(renderRequest, "auiCheckbox");
		boolean clayCheck = ParamUtil.getBoolean(renderRequest, "clayCheckbox");

		String sAuiCheck = ParamUtil.getString(renderRequest, "auiCheckbox");
		String sClayCheck = ParamUtil.getString(renderRequest, "clayCheckbox");

		if (_log.isInfoEnabled()) {
			_log.info("auiCheckbox " + auiCheck + " string value: " + sAuiCheck);
			_log.info("clayCheckbox " + clayCheck + " string value: " + sClayCheck);
		}
```
	
 **Expected**: all sent values are the same, "on", when they are checked, and true if they are loaded with ParamUtil.getBoolean(...)
 
 **Observed**: Clay checkbox sends an empty value, this results in a false value when the checkbox is loaded from the request using our utils.

### CODE REVIEW

**Comment by jcampoy** [comment]
ci:test:relevant

**Comment by matuzalemsteles** [comment]
Hey @jcampoy thanks for submitting this but I have just a few considerations here, this is a bit strange that the Checkbox when checked even though it doesn't have a value is sending an empty value, according to the specification this is a native behavior, so if there is no `value ` the `on` is automatically added in that case it wouldn't make sense to manually add `on` because we are using the browser's native `input` here.

I did a test for example using `FormData` that gets the values from the form input in case the checkbox doesn't have a value without this PR.

Screen Shot 2022-03-29 at 1 08 03 PM

The same happens if you manually set a value for the checkbox. Another thing to consider is that if the checkbox is unchecked, the value is not sent in the request, this is a native behavior, so if there is a value being received in the backend it should always be considered as checked and never unchecked, in cases like this it is not we should use `ParamUtil.getBoolean` to check if it is checked, only if there is any value.

**Comment by jcampoy** [comment]
Hey @matuzalemsteles 

I am not adding a value="on", with this PR the html markup will do not have the value="" that currently is generated by the taglib when you do not specify the value attribute, so the problem is that the taglib:

```
<clay:checkbox
		label="clayCheckox"
		inline="<%= true %>"
		id="<%= liferayPortletResponse.getNamespace() + "clayCheckbox" %>"
		name="<%= liferayPortletResponse.getNamespace() + "clayCheckbox" %>"
	/>
```

is generating this markup (take a look to the "value" attr):

```
<div class="custom-control custom-checkbox custom-control-inline">
  <label>
  <input name="_org_support_liferay_checkbox_CheckboxPortlet_INSTANCE_suqn_clayCheckbox" id="_org_support_liferay_checkbox_CheckboxPortlet_INSTANCE_suqn_clayCheckbox" aria-label="clayCheckox" class="custom-control-input" type="checkbox" value="">
  <span class="custom-control-label"><span class="custom-control-label-text">clayCheckox</span></span></label></div>
```

Even more, this do not happen with other taglibs to generate checkboxes, eg, aui:checkbox, if you do not inform the value, you do not get a value in the markup, in consequence you get the native behavior of sending "on".
 
Developers changing/upgrading alloy developments to clay are finding this issue.

**Comment by matuzalemsteles** [comment]
Hey @jcampoy you are correct, I was assuming that as the `value` is by default `null` when passing to the React.js part it would not render the `value` empty, this is a bit curious, maybe because null is converted to a string empty? I'm not sure how the cast of values works here. But this solution makes sense to me, thanks again!

**Review by matuzalemsteles — APPROVED** [review]

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by matuzalemsteles** [comment]
Hey @susanchen3 or @john-co can anyone help here if the failures in the CI are referring to this PR?

**Comment by susanchen3** [comment]
Taking a look! :mag:

**Comment by matuzalemsteles** [comment]
Manually forwarded https://github.com/brianchandotcom/liferay-portal/pull/115598

**Pull request closed without merging**
