### PR TITLE
LPS-114069 Replace layout classes with new clay components in headless-discovery-web

### PR DESCRIPTION
**Pull request by eduardoallegrini**
@jbalsas 

As required in [the previous PR](https://github.com/liferay-frontend/liferay-portal/pull/28) I updated the dependencies and run the tests in the involved modules and in the [mentioned one](https://github.com/liferay-frontend/liferay-portal/pull/28#issuecomment-647958279) but this is still red

image

### CODE REVIEW

**Comment by eduardoallegrini** [comment]
Since the errors seems to be caused by the order of the classes, I'm going to update the snapshots, even though I'm not sure why `app-builder-web` is included in this bundle 

image
image

**Comment by jbalsas** [comment]
> Since the errors seems to be caused by the order of the classes, I'm going to update the snapshots, even though I'm not sure why app-builder-web is included in this bundle

It's probably because the tests there use [FieldType](modules/apps/data-engine/data-engine-taglib/src/main/resources/META-INF/resources/data_layout_builder/js/components/field-types/FieldType.es.js) somehow, which you've updated here.

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
ci:test:sf

**Comment by jbalsas** [comment]
LGTM, running the tests to see how it looks on CI.

@eduardoallegrini, did you verify Drag and Drop inside FormBuilder was working properly? I seem to remember that was one of the cases with the missing `ref` support in the new components.

**Comment by eduardoallegrini** [comment]
> @eduardoallegrini, did you verify Drag and Drop inside FormBuilder was working properly? I seem to remember that was one of the cases with the missing `ref` support in the new components.

I'm not sure if this is the right module, but I think it's working

form-builder

**Comment by matuzalemsteles** [comment]
Hey guys, just FYI: FormBuilder still uses metal-dnd, so there are no big problems with this change in impacting drag and drop, we just have to leave the classes they use, but this is in the FormRenderer module.

**Comment by jbalsas** [comment]
> Hey guys, just FYI: FormBuilder still uses metal-dnd, so there are no big problems with this change in impacting drag and drop, we just have to leave the classes they use, but this is in the FormRenderer module.

Cool, thanks for the update @matuzalemsteles! If tests are green we can forward!

**Comment by matuzalemsteles** [comment]
Perfect!

**Comment by jbalsas** [comment]
ci:forward

**Comment by jbalsas** [comment]
> liferay/ci:test:relevant Pending — "ci:test:relevant" was invoked on Jenkins.

/cc @john-co. Will resend manually too

**Comment by jbalsas** [comment]
ci:stop

**Comment by jbalsas** [comment]
ci:stop

**Comment by jbalsas** [comment]
Manually forwarded to https://github.com/brianchandotcom/liferay-portal/pull/90527

**Comment by jbalsas** [comment]
ci:stop

**Comment by john-co** [comment]
Did a quick analysis on the common failure: https://github.com/liferay-frontend/liferay-portal/pull/45#issuecomment-648153153

The error message is different from the upstream failing test: https://testray.liferay.com/home/-/testray/cases/1151953287

This different error message could mean a fluke or that we may need a test fix for the path locator AppBuilder#ITEM_ON_THE_TABLE since it doesn't look like a regression based on poshi report screenshots.
```
Expected text "1" does not match actual text (case insensitive) "05/02/2016" at "//table[contains(@class,'table')]//*[contains(text(),'1')]
```

cc/ @alexcandidos have you seen this before?

**Comment by palomaanunes** [comment]
hey @john-co, I will check [this](https://issues.liferay.com/browse/LRQA-59645)!

**Comment by palomaanunes** [comment]
@john-co , I was able to run it locally and the same error was caught! It seems to be a test fix, but I still will work on it by Thursday once tomorrow is holiday! Following the gif I recorded during local execution:

**Pull request closed without merging**
