### PR TITLE
LPS-143417 Enable keyboard shortcut for interacting with ActionLinkRenderer

### PR DESCRIPTION
**Pull request by diegonvs**
# How to view my changes

1. Global Menu -> Control Panel -> Objects
2. Try to click in User link using (CMD + Left Click), inside the Dataset(a.k.a Table)

You'll notice that is impossible to open the link in another tab

# One video >>> words

https://user-images.githubusercontent.com/7663513/145468140-04c49e4a-4b55-4b8e-b017-bbd0cdb100d2.mov

# Changes

* This issue was caused due to a `event.preventDefault` on ClayLink component that disables the user to proper open the link in another tab
* When removing the `event.preventDefault` call, it still buggy because it will perform a SPA navigation even just trying to open the link in the new tab

# Questions

When examining possible regressions, I saw in the blame [this ticket](https://issues.liferay.com/browse/LPS-138619) containing [this commit](https://github.com/liferay/liferay-portal/commit/48105b2f236732f743e8392f78abe04c20da62cd) that introduces this bug. It is not reproducible even with my fix(removing a part of the old fix) but I'm not sure if I left something or not. /cc @guilhermedcamacho @gabrielwas @ rodrigocunhaa

### CODE REVIEW

**Comment by diegonvs** [comment]
ci:test:help

**Comment by diegonvs** [comment]
ci:test:object

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
Hey @diegonvs 

This seems to be working fine, just tested it. However I think there is one more case that we need to cover here.

Checking at the code there is a possibility that we show a confirm message to abort the navigation: https://github.com/liferay/liferay-portal/blob/e3ffd8abbf929774d07cec051a13b54d323c64c3/modules/apps/frontend-data-set/frontend-data-set-web/src/main/resources/META-INF/resources/data_renderers/ActionLinkRenderer.js#L134-L140

In that case we may bring back the  `event.preventDefault()` and add it inside the if block. 

This is a bit weird though, having a link that doesn't navigate doesn't seems good for accessibility, but I guess we can address this is another issue/PR 🤔

**Pull request closed without merging**
