### PR TITLE
LPD-33708 Noncify usages of <style> and <link>

### PR DESCRIPTION
**Pull request by bryceosterhaus**
update from https://github.com/liferay-frontend/liferay-portal/pull/4372

### CODE REVIEW

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
ci:report:73286396

**Comment by bryceosterhaus** [comment]
cc @izaera I will let you debug these failures since you're more familiar with the origins of this stuff

**Comment by izaera** [comment]
rebased and fixed in https://github.com/liferay-frontend/liferay-portal/pull/4399

**Pull request closed without merging**
